### ISSUE TITLE
New "report": Admin Order Export

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#1022]
Add the ability to export orders.

The "canada post desktop export" plugin is really just an order-exporter, and might be a practical starting point: https://www.zen-cart.com/downloads.php?do=file&id=833

NOTE: Should be done using the LEAD infrastructure, instead of the old-style code.

Expanding to allow specifying ranges by dates or order-numbers and/or applying an order-status filter might be additional features to consider. 

IDEALLY all reports should have the ability to be exported ... somehow. not just CSV

**Comment by zcwilt** [comment]
Just wanted to add a note here, although it's more relevant to the overall reports infrastructure then this specific issue. 

Currently reports have no `idea` about totalling, no column sorting and no css `hinting` for printing. So there are some further reporting infrastructure changes needed.
