### ISSUE TITLE
Add totals/sums to new Admin Reporting infrastructure

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#1026]
Currently the new LEAD reports have no idea about `totaling`.
Something needs to count sums and perhaps other values in order for other kinds of reports to be meaningful.

**Comment by scottcwilson** [comment]
Suggest this issue be broken out into three separate tickets: 
- Add totals/sums to Admin Reporting infrastructure (LEAD)  (original ticket) 
- Add css hints for printing to Admin Reporting infrastructure (LEAD)
- add column sorting to Admin Reporting infrastructure (LEAD)

**Comment by drbyte** [comment]
... are you leaning towards implementing a particular one?

**Comment by scottcwilson** [comment]
I would not do sorting or css.  Possibly I could do totals.

**Comment by drbyte** [comment]
Shucks!  :D 

I agree: they should be split out

**Comment by drbyte** [comment]
Actually, will leave those others alone for now. Totals are more essential. The others are candy that can be added later when demand is present.

Issue title edited accordingly.

**Comment by scottcwilson** [comment]
I can take this if @zcwilt doesn't have work in progress.
