### ISSUE TITLE
Renaming listingBox classes directories and Abstracts

### ISSUE THREAD

**Issue by zcwilt** [zencart/zencart#1029]
listingBox classes were originally created to make it easier to define queries/filters etc for providing product listings in catalog. e.g. featured/specials/search

However we now re-use some of that infrastructure in Admin as well to manage LEAD/Report pages.

As such `listingBox` no longer semantically  reflects what those classes represent.

What the classes do represent is a set of configuration definitions that are passed to the `QueryBuilder` class that produce an sql query, and also define how the resulting query will be displayed. 

It would be better now to do some renaming. 

My current preference is for the `listingBox` directory to be changed to `listingQueries` and the `boxes'`directory to be changed to `definitions`

**Comment by drbyte** [comment]
`\QueryDefinitions\definitions`

**Comment by zcwilt** [comment]
As @drbyte mentioned we changed our mind about the naming 
I should also point out that there will be still references to `listingBox` or `listingBoxes` in terms of variable naming and Database tables. These will be addressed in future commits to prevent this commit from becoming more unwieldy.
