### ISSUE TITLE
GROUP BY and ORDER BY used in wrong order by LEAD query

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1040]
If both `groupBys` and `orderBys` are specified in `$listingQuery`, they are used in the wrong order when the query is built, leading to a 1064 SQL Syntax error.

**Comment by zcwilt** [comment]
Noted.

**Comment by zcwilt** [comment]
@scottcwilson 

As a very quick test, you could try this. 
in `class QueryBuilder` in method `processQuery`
try switching around these lines 
so 

        $this->processOrderBys();
        $this->processGroupBys();

becomes 

        $this->processGroupBys();
        $this->processOrderBys();

**Comment by scottcwilson** [comment]
Also required change in how query was built but this was the right place.  Thanks!
