### ISSUE TITLE
Allow dashboard widgets to span more than one column or more than one row.

### ISSUE THREAD

**Issue by zcwilt** [zencart/zencart#1042]
Currently Dashboard widgets can only be one size. e.g. 1 column and 1 row. 

Some widgets, especially Graphing widgets would benefit from having more space. 

We could use something like http://gridster.net/ to provide this.

**Comment by scottcwilson** [comment]
Would also love to have this for the logs widget, which is a bit squeezed right now.

**Comment by zcwilt** [comment]
As noted in the commit message, there is more that needs to be done here. 

- No current widgets are marked as bigger than 1 row/column
- Would like to add a minimize/maximize button
- `Add widget` code needs better integration with gridstack.js 
- Consider using https://github.com/furf/jquery-ui-touch-punch
