### ISSUE TITLE
Getting "shared" folder errors when active template files not found

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#1054]
Error:

`PHP Warning:  include(): Failed opening 'includes/templates/shared/template_info.php' for inclusion`

Situation:
- in Admin the specified template is `foo`
- the `/includes/templates/foo` folder doesn't exist
... so the template lookup code starts traversing "shared" etc for `template_info.php` etc.

To reproduce the problem:
- create a new template
- via the Admin switch the new template on
- delete the new template's folder from `/includes/templates`
- browse around the catalog and note the errors in the `/logs/`

**Comment by drbyte** [comment]
@scottcwilson are you interested in tackling this one?

**Comment by scottcwilson** [comment]
Happy to - please assign to me.
