### ISSUE TITLE
Admin timeout and ajax responses

### ISSUE THREAD

**Issue by zcwilt** [zencart/zencart#1066]
Currently if you are using a page in admin that relies on Ajax. 
e.g. the LEAD pages.
If the session times out, any use of ajax will trigger an alert box with
`An unknown response was received while processing an ajax call`

**Comment by drbyte** [comment]
Is this related to the open gzip issue?

**Comment by zcwilt** [comment]
no.

**Comment by scottcwilson** [comment]
I did one (local) fix for this issue - https://github.com/zencart/zencart/pull/964.

**Comment by zcwilt** [comment]
needs support in abstractController
