### ISSUE TITLE
Lead pages and date_added, last_modified

### ISSUE THREAD

**Issue by zcwilt** [zencart/zencart#1067]
A number of tables that are managed using the LEAD infrastructure have date_added, last_modified
columns that are currently not being updated correctly. 
The LEAD infrastructure does have code to manage this, however the correct array entries have not been added the `QueryBuilderDefinitions`

The array structure to manage this is 

            'autoMap' => array(
                'add' => array(
                    array(
                        'field' => 'date_added',
                        'value' => 'now()',
                        'bindVarsType' => 'passthru'
                    )
                ),
                'edit' => array(
                    array(
                        'field' => 'last_modified',
                        'value' => 'now()',
                        'bindVarsType' => 'passthru'
                    )
                )
            ),
see https://github.com/zencart/zencart/blob/v160/includes/library/zencart/QueryBuilderDefinitions/src/definitions/LeadRecordArtists.php as an example

**Comment by drbyte** [comment]
It's probably worth auditing which tables really need those date fields, just to be sure we don't needlessly write code for some of the unused cases.

**Comment by zcwilt** [comment]
@drbyte agreed. Some tables will definitely need them. 
However I think sometimes we just added them just to follow a pattern.

**Comment by drbyte** [comment]
fields | table
-------|-------
last_modified | admin
date_added | banners
date_status_change | banners
date_added, last_modified | categories
date_added, last_modified | configuration
date_created, date_modified | coupons
customers_info_date_account_created, customers_info_date_account_last_modified | customers_info
featured_date_added, featured_last_modified | featured
date_added, last_modified | geo_zones
date_added, last_modified | group_pricing
date_added, last_modified | manufacturers
date_added, last_modified | media_clips
date_added, last_modified | media_manager
date_added, last_modified | music_genre
last_modified | orders
date_added | orders_status_history
date_added, last_modified | paypal
date_added | paypal_payment_status_history
date_added, last_modified | paypal_testing
date_added, last_modified | product_type_layout
date_added, last_modified | product_types
products_date_added, products_last_modified | products
date_added | products_notifications
date_added, last_modified | record_artists
date_added, last_modified | record_company
date_added, last_modified | reviews
sale_date_added, sale_last_modified | salemaker_sales
specials_date_added, specials_last_modified | specials
date_added, last_modified | tax_class
date_added, last_modified | tax_rates
date_added, last_modified | zones_to_geo_zones

**Comment by zcwilt** [comment]
@drbyte Nice

The question now is which of those is actually needed :)
