### ISSUE TITLE
Tax Rates priority does not validate

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#1075]
When editing a tax rate, the priority value is being checked on being an integer. No matter which value I enter, it always returns an onscreen error, telling me the value entered is not an integer.
![image1](https://cloud.githubusercontent.com/assets/2766593/16650037/4b38b93c-443c-11e6-8bb3-5b9847b35b7a.jpg)

**Comment by zcwilt** [comment]
Hi 
Thanks for the catch. The patterns used weren't valid CSS3 validations. However this also speaks to some other problems regarding validation of LEAD forms.

We recently introduced https://github.com/vlucas/valitron to use for this purpose, although currently it is only used on the admin/users page.

I've held off rolling it out for other LEAD pages as I have some worries over the array structures currently used in the `QueryBuilderDefinitions`.

Will probably open an issue to start a conversation around that
