### ISSUE TITLE
Validation of forms in admin LEAD pages.

### ISSUE THREAD

**Issue by zcwilt** [zencart/zencart#1078]
Currently apart from the admin/users page, none of the LEAD pages that allow for add/edit do any validation of the forms. (apart from maybe some `required` processing) 

Validation can have 3 parts 
1.  Use of HTML5 pattern attribute and required attribute
2.  Use of javascript validation on form submit 
3.  fallback validation using PHP 

LEAD code currently allows for 1 and 3 at the moment, however because validations are defined in an array, 
this should allow for common javascript to validate entries as well. 

The format for defining validations is currently to add an entry to a `fields` definition 

e.g .

```
            'admin_name' => array(
                'bindVarsType' => 'string',
                'layout' => array(
                    'common' => array(
                        'title' => TEXT_ENTRY_ADMIN_NAME,
                        'align' => 'right',
                        'type' => 'text',
                        'size' => '10'
                    )
                ),
                'validations' => array(
                    'required' => true,
                    'pattern' => 'someHTMLvalidationpattern',
                    'rules' => array(
                        array('type' => 'lengthBetween', 'params'=>array(4,12))
                    )
                )
```

The structure still needs some work in terms of defining custom error messages, however I think my biggest problem is that having to define validations per field bloats the definition array and it may be better to have a top level validations array 
e.g. 

```
            'validations' => array(
                'admin_name' = array (
                    'required' => true,
                    'pattern' => 'someHTMLvalidationpattern',
                    'rules' => array(
                        array('type' => 'lengthBetween', 'params'=>array(4,12))
                    )
                ),
                'admin_email' => array (
                    'required' => true,
                      'rules' => array(
                            array('type' => 'email')
                        )
                    }
                )
```

**Comment by zcwilt** [comment]
referencing https://github.com/zencart/zencart/issues/1075

**Comment by drbyte** [comment]
I'm leaning towards having a top-level validations array. 
This allows for sharability. 
And avoids code-bloat as you suggested.

I think we can also use ajax for the javascript validation ... as this would trigger the PHP validation ... and give optimum consistency. And of course that allows for graceful degradation even if ajax fails.
