### ISSUE TITLE
Exposed Password Reset Email Content when using SMTP

### ISSUE THREAD

**Issue by bislewl** [zencart/zencart#1079]
I discovered something interesting. When a customer (or admin) resets their password, and the email settings are set to use Mandrill via SMTP a user with access to mandrill can see the content email including the password. I'm unsure of a solution to this issue.

**Comment by drbyte** [comment]
I'm not sure how this is a Zen Cart issue.  
And it's not isolated to "when using SMTP".
Nor is it isolated to Mandrill.
Whatever is emailed is visible in the email message. It has to be, else the email is useless.

Mandrill is an email delivery service ... so whatever is emailed is visible if that email service allows for it.

In ZC the Admin uses an expiring password-reset token, but anyone with access to the emails (regardless whether it's a Mandrill administrator, or a Google Mail For Business administrator, or whatever) will be able to view them.

> I'm unsure of a solution to this issue.

I'm not sure one is needed.

**Comment by bislewl** [comment]
Passwords are being stored in plain text, no?
If we moved to a password reset URL would that comply?

**Comment by bislewl** [comment]
One could do something like this, right?
![image](https://cloud.githubusercontent.com/assets/2678085/16668290/1138e062-4456-11e6-866a-59d423593ae5.png)

**Comment by drbyte** [comment]
No, Zen Cart has NEVER stored passwords in plain text. 
I still don't see why this has anything to do with PCI in Zen Cart.

**Comment by bislewl** [comment]
Agreed, I don't think it is a Zen Cart Issue, however I'm thinking more of a disclosure in the "EMAIL_TRANSPORT" configuration description. It could be left alone as well, my only thoughts were to better inform the store owner. I trust your judgement.

**Comment by drbyte** [comment]
> however I'm thinking more of a disclosure in the "EMAIL_TRANSPORT" configuration description

Given that the issue is the same regardless of which transport is used (SMTP, SMTPAUTH, PHP, even gmail can all be "spied upon" by system/account administrators), I don't think any messaging is necessary. I wouldn't even use the word `disclosure` in this context.

**Comment by drbyte** [comment]
While it would be awkward with the current way the code works (and there are plans to clean it up), there are lots of modernized ways of handling login, including emailing a login token (in lieu of a password), as well as tokenized password-resets, and so on.

After the customer-related code and functions get consolidated into a customer class/object, some of these alternate approaches could be entertained.
