### ISSUE TITLE
Fix wording of Visitors Cart text notice

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#1080]
`TEXT_VISITORS_CART` could use some tweaks to make it more explicit that it applies only to customers with an account.

And, it's not the same in `login.php` and `shopping_cart.php` ... so it might be worth splitting them into different defines because they're quite different.

**Comment by scottcwilson** [comment]
Note: #1023 is merged if someone wishes to take this issue.

**Comment by drbyte** [comment]
Note to #hacktoberfest coders. Addressing this issue will require digging into understanding the infrastructure for `language files` and `templating system`.

**Comment by kerrinhardy** [comment]
From `shopping_cart.php`:
    define('TEXT_VISITORS_CART', '<a class="help" href="javascript:popupInfoShoppingCart();"><i class="fa fa-question-circle fa-2x"></i></a>');

From `login.php`:
    define('TEXT_VISITORS_CART', '<strong>Note:</strong> If you have shopped with us before and left something in your cart, for your convenience, the contents will be merged if you log back in. <a href="javascript:popupInfoShoppingCart();">[More Info]</a>');
