### ISSUE TITLE
Incorrect operator 

### ISSUE THREAD

**Issue by tomrichmond** [zencart/zencart#1092]
In enable_error_logging.php:

```
function zen_debug_error_handler ($errno, $errstr, $errfile, $errline) {
  if (!(error_reporting() && $errno)) {
    return;
  }
  ...
}
```

The logical operator `&&` has been used instead of the bitwise operator `&`.

This causes the error handler to execute regardless of whether the current error code is included in error_reporting().

**Comment by zcwilt** [comment]
:+1:

**Comment by ebcode** [comment]
Jumping on this one!  Seems simple enough.  :)
