### ISSUE TITLE
Initial Setup Wizard: Forced to use USA state

### ISSUE THREAD

**Issue by dakanji** [zencart/zencart#1101]
You are forced to enter a USA state when setting up the store for the first time no matter which country you enter as Store Country.

**Comment by dakanji** [comment]
Notice there is this JS supposedly to take care of this on the page but must be something not working as it should with it.

**Comment by dakanji** [comment]
Okay ... the Ajax call, to "/admin/index.php?cmd=index&action=getZones" is returning '{"html":""}' which I presume is why the zones are not working as expected.

**Comment by zcwilt** [comment]
The problem is here 

    $('#store_zone_container').html(response.html);

pretty sure that should just be 

    $('#store_zone').html(response.html);

**Comment by dakanji** [comment]
Yes indeed .... Will push the fix
