### ISSUE TITLE
Having one row of short widgets can cut off long admin menus

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1118]
See attached image. The configuration menu is cut off before the last entry.   I am not sure  that this is related to #1060 but @zcwilt believes it might be.  I was able to duplicate this by using a fresh install, then deleting all the widgets, then adding these three back in left to right order. 

<img width="812" alt="screen shot 2016-07-18 at 7 53 58 pm" src="https://cloud.githubusercontent.com/assets/4391638/16945065/8e9fe090-4d71-11e6-8bbd-4d8aa9382eb2.png">

**Comment by zcwilt** [comment]
see https://github.com/zencart/zencart/pull/1116

This fixes the truncated menu as well

**Comment by scottcwilson** [comment]
LOL you guys are too quick for me! 👍  Thank you.  Can't wait to merge this in.
