### ISSUE TITLE
Suggestion: zc_install/includes/localConfig.php should be in the .gitignore file

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1121]
This seems like the kind of file that people would want to modify locally.  Perhaps checkin to source a dist-localConfig.php file and remove the existing one, then add to .gitignore?

**Comment by drbyte** [comment]
Torn on this.

The `zc_install/includes/extra_configures/` folder already supports what you were suggesting to do with adding extra defines. Not necessary to use `localConfig.php`

**Comment by drbyte** [comment]
... and if you name the file as `dev-xxxxxxxxxx.php` (the `dev-` prefix) it will automatically be ignored by virtue of the current .gitignore rules.

**Comment by scottcwilson** [comment]
But ... but .... *local*Config - seems like it should be, you know, local.

**Comment by scottcwilson** [comment]
I kind of was assuming we would do this when I made the change #1123.  I want to set it and forget it.

**Comment by scottcwilson** [comment]
Ok.  If that's your recommendation, I will do a follow on change to include
this file if it exists.

**Comment by drbyte** [comment]
No change needed. That folder is already auto included.

**Comment by drbyte** [comment]
It's actually a very easy set-and-forget. 
I do the same with the admin warning page: `dev-` prefix on file in extra_configures with the requisite define inside. 
Just drag the files into the requisite folders, and it's all set.
