### ISSUE TITLE
Resetting an admin user's password should also reset the lockout expires field

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1135]
If an admin user's pass is reset, it is being by another admin, so the original user
should no longer be subject to timeout.  (This issue occurred for me, working with a customer on a 1.5.5 site, and I really thought the behavior should be changed.)

If this is accepted, please assign to me.

**Comment by drbyte** [comment]
Good point. I remember intending to do that, and thought it had been done. But you're right, it wasn't. Have at it.
