### ISSUE TITLE
Force Cookie usage problems

### ISSUE THREAD

**Issue by zcwilt** [zencart/zencart#1143]
see https://www.zen-cart.com/showthread.php?220506-V154-amp-V155-when-cookies-off-zenid-changing-with-every-change-of-page-add-item-fails

The main problem here is that adding an item to the cart does not trigger the Cookie Usage page if Force Cookie Usage is true. 

We should also set Force Cookie Usage to true by default

**Comment by syntaxerror** [comment]
Was this ever backported for 1.5, or wasn't it needed?
