### ISSUE TITLE
(Mostly) unused return value from buildResults()

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1155]
In `includes/library/zencart/QueryBuilderDefinitions/src/definitions/AbstractLeadDefinition.php`, the `function buildResults()` returns a value which is ignored except in `includes/library/zencart/Controllers/src/AbstractLeadController.php`. 

Could the latter be refactored to simply look in `$this->listingBox->tplVars['formattedItems'][0][$key];` (if tplVars was changed to not protected) or perhaps to just set the value in another way?  

It's a bit confusing to see a function that returns a value that's generally unused.

**Comment by zcwilt** [comment]
agreed it's a mess :)

**Comment by scottcwilson** [comment]
"Mess" is a strong word.  If you approve, I can remove "protected" from tplVars, or I can keep looking for a better solution.  Perhaps we could copy the key value to a non-protected structure, for example, or even create a public method in listingBox to do the copying.

**Comment by zcwilt** [comment]
I'm working on some other refactoring that might impinge on this 
the reason I said it was a mess, is that the 2 functions have different signatures 
e.g. one does a return, the other doesn't. 

However there is no need to remove the protected on tplVars as there is a getter 
e.g. $this->getTplVars()

but I'm not even sure thats ok
What might be ok is to have a getResults method that wraps the buildResults in the AbstractLeadController

**Comment by scottcwilson** [comment]
Ping me when you're done your work - no sense in creating a collision.
