### ISSUE TITLE
ajax.googleapis.com not reachable from certain geographical location

### ISSUE THREAD

**Issue by netcrop** [zencart/zencart#1161]
* In file admin/includes/admin_html_head.php 
```
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
```
not reachable from certain geographical location. v160
* Affected location: CN
* Impact: storeBackend javascript not functioning correct.
* Reason: [please consult this article] (http://meta.stackoverflow.com/questions/258288/use-of-ajax-googleapis-com-not-china-friendly)
* Suggestion: disable javascript. OR distribute file jquery-ui.min.js together with zencart releases. Verified and working on v160.

**Comment by drbyte** [comment]
Thanks for the supporting information. 
We're looking into the possibility of dropping dependency on jQuery UI altogether. But if we do keep it we'll aim to bring it in as part of the distribution.

**Comment by netcrop** [comment]
Further investigation shows:
* In file admin/includes/admin_html_head.php, **replace** ajax.googleeapis.com with
```
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
```
**is** reachable.

* In file admin/includes/template/dashboardWidgets/tplCounterHistoryGraph.php And
admin/includes/template/dashboardWidgets/tplSalesGraphReport.php
```
Load the AJAX API FOR GOOGLE GRAPHS,
src="https://www.google.com/jsapi"
...
 Load the Visualization API and the piechart package
https://www.google.com/uds/?file=visualization&v=1&packages=corechart
```
**not** reachable.
