### ISSUE TITLE
zc_install folder removal requirement maintained in developer mode

### ISSUE THREAD

**Issue by dakanji** [zencart/zencart#1162]
In transitioning to using the developer mode outlined by @drbyte in https://github.com/zencart/zencart/issues/404#issuecomment-234328537, I notice that the zc_install folder removal requirement is still in force leading to gitignore issues.

This requirement should be overridden in developer mode.

**Comment by scottcwilson** [comment]
You just  need to also create includes/local/configure.php that says 
<?php
define('ADMIN_BLOCK_WARNING_OVERRIDE', '1');

**Comment by dakanji** [comment]
Thanks.

I noticed that ADMIN_BLOCK_WARNING_OVERRIDE was not defined anywhere.
Working on a comprehensive rollup of the dev mode thing by incorporating it in the installation process where a user can check a box and it is done.

Doing final test installation before pushing a PR.

**Comment by dakanji** [comment]
Closed as appears to have a "won't fix" status
