### ISSUE TITLE
Missing css classes 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1167]
The files 

`tpl_checkout_guest_account_collect_default.php`  `tpl_checkout_guest_emailonly_account_collect_default.php` 

reference classes like small-3 and small-9 which don't exist in the css we have.  
This makes the fields have a uniform length which is inappropriate; the lengths should be more like the ones shown on the login page.

Are these perhaps from Grid?

**Comment by zcwilt** [comment]
Yes, old foundation grid stuff. I'm not sure it warrants fixing at the moment as there will be a new template at some point.

**Comment by scottcwilson** [comment]
Oh ok.  I am anxious to see the new template!
