### ISSUE TITLE
paypalwpp.php minor text error

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#1177]
`if (!defined('MODULE_PAYMENT_PAYPALWPP_CHECKOUTSTYLE')) {
        $db->Execute("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Use InContext Checkout?', 'MODULE_PAYMENT_PAYPALWPP_CHECKOUTSTYLE', 'InContext', 'PayPal now offers a newer friendlier InContext (in-page) checkout mode (Requires that you enter your MerchantID in the Merchant ID Setting below). Or you can use the older checkout style which offers Pay Without Account by default but on a full-page-redirect.', '6', '25', 'zen_cfg_select_option(array(\'InContext\', \'Old\'), ', now())");
      }`

Should be
"enter your MerchantID in the Merchant ID Setting above"
 
....

**Comment by drbyte** [comment]
In v155 and v160 it currently says "above" on fresh installs of the module.

Apparently the word "below" was left in the part that adds that setting for people upgrading (because the insert is duplicated again (but wasn't updated) to help avoid having to remove and re-install the module).
