### ISSUE TITLE
attempt to make shopping_cart class easier to understand and debug

### ISSUE THREAD

**Issue by netcrop** [zencart/zencart#1198]
This is my attempt to make shopping_cart class easier to understand and debug.

When I discussed issue #1163 with @mc12345678 , I found the functions inside class shopping_cart were complex and difficult to debug. It might not true for      developer involved in this project since longtime, but it was obvious for me that a refactoring of functions is required to fully understand what the code   is doing.
**And here is the code after my refactoring.**
[shopping_cart.php.txt](https://github.com/zencart/zencart/files/419372/shopping_cart.php.txt)

I have tested in v160, it may only be used for development, because it may break dependencies beyond my knowledge.

Each of these private functions are dedicated for a single purpose which can be determined by it's name. When the debug flag turns on, you can easily follow   the process calling stack.

```
    private function messageDebug($message)
    private function validAttributes()
    private function setDBQuantity($productsId)
    private function getDBOptionAttributes($products_id,$option,$value)
    private function setDBOptionAttributes($products_id,$attributes)
    private function removeProduct($productsId)
    private function decimalQty()
    private function checkInputQty($productsId,$inputQty)
    private function messageAdjustQty($productsId)
    private function adjustQty($productsId)
    private function getDBQtyUnitMix($productsId)
    private function getDBAttributes($productsId)
    private function uploadFile()
```

Each of these public caller functions calls a subset of previous private callees based on it's purpose. Since each callee function is single purpose, redundant sanitizing E.g user input, adjust quantity etc. are reduced to the minimum.

```
    function actionUpdateProduct($goto, $parameters) {
    function actionMultipleAddProduct($goto, $parameters)
    function actionAddProduct($goto, $parameters, $allowRedirect = true)
    function actionBuyNow($goto, $parameters)
    function actionCustomerOrder($goto, $parameters)
```

Multi level IF statements are reduced, which makes the code easier to understand and debug.

Logic for adjust products quantity are hard to trace in the original code, which i refactored to these functions.

```
    private function getDBQtyUnitMix($productsId)
    private function checkInputQty($productsId,$inputQty)
    private function messageAdjustQty($productsId)
    private function adjustQty($productsId)

```

The most complex logic for change and update quantity is in `adjustQty($productsId)` that is much easier to debug, change, extend or replace.

There is no reason to use the code I have written here, if you don't consider the orignal code needs any refactoring. My point is, it can be done in a way that is much more pleasant to read and debug.

**Comment by zcwilt** [comment]
v2 will probably update this code anyway, Thanks for the ideas, and we may take advantage of them.
