### ISSUE TITLE
AJAX: Session variables' changes aren't saved

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1202]
See [this ](https://www.zen-cart.com/showthread.php?220887-AJAX-Session-variable-changes-not-saved&p=1317262#post1317262)Zen Cart posting for details.

Essentially, the `/ajax.php` script needs to end with a require of `includes/application_bottom.php` so that any session-related changes made by an AJAX handler are properly recorded in the session.

**Comment by drbyte** [comment]
Assigned to @zcwilt to determine the best approach for v160

**Comment by drbyte** [comment]
Ref #1298 for an update to the v155 version of this
