### ISSUE TITLE
Dashboard widgets description table should not have a languages_id column

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1207]
Widgets do have language defines of course but the widgets should work in any language.  This column should be removed.

**Comment by scottcwilson** [comment]
(If approved, please assign to me.)

**Comment by zcwilt** [comment]
@scottcwilson will assign soon, just I'm working on some controller logic changes that encompass dashboard widgets and don't want to clash.

**Comment by scottcwilson** [comment]
Very good - thank you.

**Comment by zcwilt** [comment]
Actually, reviewing my changes there should be no clash. Assigned.

**Comment by scottcwilson** [comment]
I should be able to take care of this issue this week.
