### ISSUE TITLE
checkLiveCurl() Operation timed out after 11001 milliseconds

### ISSUE THREAD

**Issue by netcrop** [zencart/zencart#1216]
From error_log('CURL Test URL: ' . $url . " " . $result . " " . $errtext,0);
```[22-Aug-2016 16:53:42 Asia] CURL Test URL: https://s3.amazonaws.com/zencart-curltest/endpoint  Operation timed out after 11001 milliseconds with 0 bytes received```
**Problem:**
file /zc_install/includes/classes/class.systemChecker.php
function checkLiveCurl
curl_setopt($ch, CURLOPT_TIMEOUT, **11**);
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, **10**);

**Solution suggestion 1:**
curl_setopt($ch, CURLOPT_TIMEOUT, **25**);
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, **24**);

**Solution suggestion 2:**
Add: 
curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);

Choose **both** solutions would be most confident.

**Comment by drbyte** [comment]
I'm wondering why it's taking 11+ seconds to resolve the name of an AWS server though ...

**Comment by netcrop** [comment]
This problem is caused by slow DNS request. Because, If I use IP address instead, the checkLiveCurl() passed instantly. But with https, the certification validation process will not accept IP address.
I switched with different DNS vendors, the result are the same.
