### ISSUE TITLE
shopping cart duplicate span/surplus br  on $product['flagStockCheck']

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#1220]
in shopping cart header_php.php:
`$flagStockCheck = '<span class="markProductOutOfStock">' . STOCK_MARK_PRODUCT_OUT_OF_STOCK . '</span>';`

which ends up inside another span in tpl_shopping_cart
`echo $product['showFixedQuantityAmount'] . '<br /><span class="alert bold">' . $product['flagStockCheck'] . '</span><br /><br />' . $product['showMinUnits'];`

Something is redundant here.

Also when IN stock, there are three br for no reason, span is empty (invalid html) and the quantity amount gets pushed up to the top of that td, messing up visual/middle alignment.

Suggest along the lines of
`echo $product['showFixedQuantityAmount'] . ($product['flagStockCheck'] ?  '<br />' . $product['flagStockCheck'] : '')  .  ($product['showMinUnits'] ? '<br />' . $product['showMinUnits'] : '');`

**Comment by scottcwilson** [comment]
Please flag with "firsttimers only"

**Comment by proseLA** [comment]
at the risk of being flogged, allow me to weigh in here.

- i do not think this is a bug.
- empty spans are not invalid html.
- while i see the 3 br's, the visual alignment does not look messed up to me.

however, my opinion is that we should keep html in the template directory and that's where all styling belongs (or at least out of the modules directory).  i am not sure if this is something that is held out from a previous version; but the class markProductOutOfStock has no corresponding styling in any of the css files; so it is not really doing anything here in any event.

**Comment by zcwilt** [comment]
Given v2 will have  new template anyway, going to close this for now.
