### ISSUE TITLE
Displaying a header alert on admin home page wipes out menus

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1225]
Repro steps: On an updated 160 site, go to admin->configuration->website maintenance to true.  (This would be done automatically on an upgrade).  

You will then notice your header menu items are obfuscated.  See image. 
![bad_menu](https://cloud.githubusercontent.com/assets/4391638/17965880/cfc5c7b4-6a8c-11e6-806a-054896679403.jpg)

**Comment by scottcwilson** [comment]
Alternate title "Database Upgrade produces system with no menu entries" (I wanted to direct you to the root cause, not the most common repro.)

I noticed this when testing the upgrade logic.  I do not have a fix; please don't assign to me.

**Comment by scottcwilson** [comment]
Attached is the HTML for the extra message if that helps. 

[message.txt](https://github.com/zencart/zencart/files/436964/message.txt)

**Comment by drbyte** [comment]
Ya, I've noticed this for awhile. Haven't gotten around to fixing it yet.

**Comment by scottcwilson** [comment]
Oh ok.  I thought it was new because I do try to do an upgrade every once in a while to make sure it's ok.

**Comment by netcrop** [comment]
Maybe my upgrade process wasn't correct, but here is my procedure and results.
1. Export database using phpMyAdmin to a file zencart-ver-155.sql.
2. A fresh install of zencart v160 with a new database zencart-ver-160
3. Drop database zencart-ver-160 and recreate an empty one with the same name.
4. Import zencart-ver-155.sql to zencart-ver-160 using phpMyAdmin.
5. In browser, surf to zc_install/index.php and choose "Database Upgrade" then v1.5.5 to v1.6.0.
Here is the result image.

**Comment by barco57** [comment]
AdminLTE.css line 203 comment out or remove the max-height: 100px; solves this problem
```
.main-header {
  position: relative;
  max-height: 100px;
  z-index: 1030
}
```

**Comment by scottcwilson** [comment]
@barco57 Can you create a PR for this change?  I'd like you to get credit for fixing this.

**Comment by drbyte** [comment]
@barco57 ... ditto to what @scottcwilson said: Thanks for this!  And thanks for the PR too ;)

**Comment by scottcwilson** [comment]
👍
