### ISSUE TITLE
Unpredictable auto_loader load order due to operating system differences

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1228]
Since `/includes/initsystem.php` makes use of the PHP `dir` function to load the files present in the /includes/auto_loaders directory, there's no guarantee that the file named aaa.php loads before aaa_other.php, which can result in unwanted results.

Per the PHP documentation for the dir function: `The order in which directory entries are returned by the read method is system-dependent.`

If, on some Linux systems, the file aaa_other.php was copied to the server **before** aaa.php, the aaa_other.php file will load first.

It would be "a good thing" from a support-ability/development standpoint if the load-order was predictable, as it would be if the module used the PHP `glob` function which returns the files in ascending alpha sort-order.

**Comment by drbyte** [comment]
Fair point.

Have you an example of where you encountered this specifically? What names were you using that encountered backward ordering? 

As an aside, but is very specific to your mention of the `auto_loaders` folder, most everything in that folder is aggregated into an array before the array is processed ... and as such the load-order is essentially controllable by specifying the array index.  Or were you doing something exceptional such as trying to completely replace a default index order with another?

**Comment by lat9** [comment]
I was tracking down a report where the "Price/Weight" add-on to my "Products' Options' Stock Manager" was not working.

The base plugin's auto_loader is named config.products_options_stock.php and the add-on's auto_loader is named config.products_options_stock_pw.php.  On Windoze systems (like my local testbed), those files load in that order; unfortunately, on the client's Unix system that was not the case.

FWIW, the add-on's observer class (on load) makes an instance of the _presumed_ base plugin's observer for its use ... and wasn't working properly because the add-on's config was loaded before the base.  Both observers were being loaded at the same auto-load checkpoint since I'd ass-u-me'd that the distinction in the config-files' names would be enough.

I'm preparing an update that causes the base plugin to be loaded one-tick earlier in the auto-load chain to work around the issue.

**Comment by lat9** [comment]
An aside:  If this change is planned for incorporation, I suggest that it be slated for v1.6.0 since that release is going to be revolutionary.  Making the change to the 1.5.5 code-base could cause installations that are now working ... to stop due to potential re-ordering.

**Comment by drbyte** [comment]
True -- and, as a general rule, we're only accepting PRs for v160 now anyway.  (Your last was an exception)

**Comment by drbyte** [comment]
> I'm preparing an update that causes the base plugin to be loaded one-tick earlier in the auto-load chain to work around the issue.

Good call.

Thanks for sharing the specifics.   Context is always helpful ;)

**Comment by netcrop** [comment]
suggestion: I think scandir() can be used to replace dir(). the following test code will do the job with less **nested** IF statements compared with the original code.
```
$base_dir = DIR_WS_INCLUDES . 'auto_loaders/';
if (file_exists(DIR_WS_INCLUDES . 'auto_loaders/overrides/' . $loader_file))
  $base_dir = DIR_WS_INCLUDES . 'auto_loaders/overrides/';
if (file_exists($base_dir . $loader_file)) include($base_dir . $loader_file);
$matchPattern = '/^' . $loaderPrefix . '\./';
$loader_dir = scandir(DIR_WS_INCLUDES . 'auto_loaders');
foreach($loader_dir as $loader_file){
  if ((preg_match($matchPattern, $loader_file) <= 0) ||
    (preg_match('~^[^\._].*\.php$~i', $loader_file) <= 0)) continue;
  if ($loader_file == $loaderPrefix . '.core.php') continue;
  if (file_exists(DIR_WS_INCLUDES . 'auto_loaders/overrides/' . $loader_file))
    $base_dir = DIR_WS_INCLUDES . 'auto_loaders/overrides/';
  else
    $base_dir = DIR_WS_INCLUDES . 'auto_loaders/';
  include($base_dir . $loader_file);
  error_log('initSystem: ' . $base_dir . $loader_file,0);
}
```
Here is the result form logs
```
includes/auto_loaders/config.1.php
includes/auto_loaders/config.2.php
includes/auto_loaders/config.3.php
includes/auto_loaders/config.4.php
includes/auto_loaders/config.a.php
includes/auto_loaders/config.b.php
includes/auto_loaders/config.c.php
includes/auto_loaders/config.canonical.php
includes/auto_loaders/config.d.php
includes/auto_loaders/config.products_viewed_counter.php
```

**Comment by torvista** [comment]
...I think this is related to this:
https://www.zen-cart.com/showthread.php?126810-SitemapXML-v-2&p=1351164#post1351164

**Comment by zcwilt** [comment]
Note. I have remove this from the v2 milestone. It maybe we can add it back to some future v1.5.x milestone at some point. 
The reason for removing it from v2 is that at some point we need to make the way we init services less procedural, and while at the moment we don't have an rfc/roadmap for this it will come at some point.

**Comment by scottcwilson** [comment]
@lat9 Do you want to take this issue?

**Comment by lat9** [comment]
After review, making any change here would open up various 'gremlins' of "Why doesn't this work on zc158, it worked fine before" issues.  As indicated in various comments, specifying unique load-points within a plugin's `auto_loaders` module can be used to force the correct load-order.

Closing.

**Comment by scottcwilson** [comment]
Agreed.  The auto loading (vs manual loading) documentation discusses this: 
https://docs.zen-cart.com/dev/code/notifiers/#auto-loaded-observers
