### ISSUE TITLE
accessing https://my_domain.com/admin/index.php?cmd=languages results in error

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#1238]
When accessing the language page I get a white page with the following text in the debug file. This is happening after the latest updates to the lead pages.

> [27-Aug-2016 12:47:39 Europe/Amsterdam] Request URI: /MY_ADMIN/index.php?cmd=languages, IP address: 123.123.123.1
> #1  require_once(/home/zc160/public_html/includes/library/zencart/Controllers/src/admin/Languages.php) called at [/home/zc160/public_html/MY_ADMIN/index.php:37]
> 
> [27-Aug-2016 12:47:39 Europe/Amsterdam] PHP Warning:  Declaration of ZenCart\Controllers\Languages::initController() should be compatible with ZenCart\Controllers\AbstractListingController::initController($leadDefinitionBuilder) in /home/zc160/public_html/includes/library/zencart/Controllers/src/admin/Languages.php on line 13
> [27-Aug-2016 12:47:39 Europe/Amsterdam] Request URI: /MY_ADMIN/index.php?cmd=languages, IP address: 123.123.123.1
> #1  ZenCart\Controllers\AbstractListingController->initController() called at [/home/zc160/public_html/includes/library/zencart/Controllers/src/admin/Languages.php:36]
> #2  ZenCart\Controllers\Languages->initController() called at [/home/zc160/public_html/includes/library/zencart/Controllers/src/AbstractListingController.php:73]
> #3  ZenCart\Controllers\AbstractListingController->__construct()
> #4  ReflectionClass->newInstanceArgs() called at [/home/zc160/public_html/includes/library/aura/di/src/Injection/InjectionFactory.php:77]
> #5  Aura\Di\Injection\InjectionFactory->newInstance() called at [/home/zc160/public_html/includes/library/aura/di/src/Container.php:505]
> #6  Aura\Di\Container->newInstance() called at [/home/zc160/public_html/MY_ADMIN/index.php:41]
> 
> [27-Aug-2016 12:47:39 Europe/Amsterdam] PHP Warning:  Missing argument 1 for ZenCart\Controllers\AbstractListingController::initController(), called in /home/zc160/public_html/includes/library/zencart/Controllers/src/admin/Languages.php on line 36 and defined in /home/zc160/public_html/includes/library/zencart/Controllers/src/AbstractListingController.php on line 80
> [27-Aug-2016 12:47:39 Europe/Amsterdam] PHP Fatal error:  Uncaught Error: Call to a member function factory() on null in /home/zc160/public_html/includes/library/zencart/Controllers/src/AbstractListingController.php:85
> Stack trace:
> #0 /home/zc160/public_html/includes/library/zencart/Controllers/src/admin/Languages.php(36): ZenCart\Controllers\AbstractListingController->initController()
> #1 /home/zc160/public_html/includes/library/zencart/Controllers/src/AbstractListingController.php(73): ZenCart\Controllers\Languages->initController(Object(ZenCart\Lead\BuilderFactory))
> #2 [internal function]: ZenCart\Controllers\AbstractListingController->__construct(Object(ZenCart\Request\Request), Object(queryFactory), Object(ZenCart\AdminUser\AdminUser), Object(ZenCart\View\ViewFactory), Object(ZenCart\Paginator\Paginator))
> #3 /home/zc160/public_html/includes/library/aura/di/src/Injection/InjectionFactory.php(77): ReflectionClass->newInstanceArgs(Array)
> #4 /home/zc160/public_html/includes/library/aura/di/src/Container.php(505): Aura\Di\Injection\InjectionFactory->newInstance('ZenCart\\Control...', Array, Array)
> #5 /home/zc160/public_html/MY_ADMIN/index.php(41): Aura\Di\Container->newInstance('ZenCart\\Control...')
> #6 {main}
>   thrown in /home/zc160/public_html/includes/library/zencart/Controllers/src/AbstractListingController.php on line 85

**Comment by scottcwilson** [comment]
Yep - same issue.  @zcwilt looks like it's in your area.

**Comment by zcwilt** [comment]
Should be fixed now

**Comment by scottcwilson** [comment]
Agreed - please close.
