### ISSUE TITLE
Large Gravatar image distorted

### ISSUE THREAD

**Issue by barco57** [zencart/zencart#1241]
I noticed while playing around that the gravatar in the popup when you hover the little gravatar in the menu is hideous. Very distorted because it is using the same image for both, 20px x 20px

![large_gravatar_fugly](https://cloud.githubusercontent.com/assets/1237035/18031170/cd9f50a4-6c99-11e6-9640-430105425e69.png)

Looking at the code it seems that only the 20px x 20px version is requested from gravatar.com using this function
```
protected function getGravatar( $email, $s = 20, $d = 'mm', $r = 'g', $img = false, $atts = array() )
```
So, either there needs to be two functions, one to pull a 90px x 90px and one for the 20px x 20px or the function needs to be changed to pull the 90px version and then styling changes added to downsize it to 20px.

**Comment by scottcwilson** [comment]
👍 Thanks for writing this up.

**Comment by zcwilt** [comment]
:+1:  agree with @scottcwilson 
I had noticed this but kept meaning to investigate, especially as my own gravatar image looks pretty horrible there too.
