### ISSUE TITLE
Some admin nav items hard to see on certain pages

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1247]
v1.6.0.  Clicking on any of the tools within the Admin tab results in the upper-admin toolbar (Admin Home and all links to the right) being disabled.

You've got to cancel out and/or click some non-Admin tab-tool to restore that functionality.

**Comment by drbyte** [comment]
Do you mean the text turns white instead of black?

**Comment by lat9** [comment]
Yes, after you mentioned it.  I didn't try hovering; the links are there, the coloring (as you said) is just off.

**Comment by lat9** [comment]
I'm still familiarizing myself with the code restructuring, so apologies if this additional note is unnecessary ... but I've found that the same behavior is exhibited when cmd=view_log is active.

**Comment by scottcwilson** [comment]
I see what Cindy means.  For example, compare Admin->Discounts ->Coupon Admin (looks bad) vs. Admin->Tools->Server/Version Info (looks good).

**Comment by scottcwilson** [comment]
This issue is also captured in #996.  Close as dup?

**Comment by lat9** [comment]
Why were **both** of these issues closed, given that the issue is still present?

**Comment by drbyte** [comment]
A larger project is in place to continue the overhaul of the Admin to make all pages use a single template infrastructure.
