### ISSUE TITLE
includes/classes/shopping_cart.php line 894 parameters bad

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1252]
The call has 4 parameters but the method only has two. 
`
              $added_charge = zen_get_attributes_qty_prices_onetime($chk_price, $chk_price, $attribute_price->fields['attributes_price_factor_onetime'], $attribute_price->fields['attributes_price_factor_onetime_offset']);`

Perhaps the intention was:

`$added_charge = zen_get_attributes_qty_prices_onetime($attribute_price->fields['attributes_price_factor_onetime'], 1);`

(I'm not sure, this is just a suggestion.)

**Comment by drbyte** [comment]
Not sure which way it was intended. Posted comment at: https://github.com/zencart/zencart/commit/35fa4c4c184486786d2680ab9f8f91fcb317aa64#comments

**Comment by scottcwilson** [comment]
@ajeh Can you clarify the intent?

**Comment by drbyte** [comment]
@scottcwilson do you recall how you stumbled upon this?  Was there a specific scenario? Or just reviewing code?

**Comment by scottcwilson** [comment]
oh I was running PHPStorm's code inspector, which often finds missing
parameters, bad calls, etc. and it uncovered this.
