### ISSUE TITLE
admin orders.php unnecessary br tags

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#1253]
For the info_boxes, since each $contents[] gets it's own `<tr>`,  the `<br />` tags are unneeded and simply waste space. Occurs in other places too I imagine...
Eg.
`$contents[] = array('text' => '<br />' . TEXT_DATE_ORDER_CREATED . ' ' . zen_date_short($oInfo->date_purchased));
        $contents[] = array('text' => '<br />' . $oInfo->customers_email_address);
        $contents[] = array('text' => TEXT_INFO_IP_ADDRESS . ' ' . $oInfo->ip_address);
        if (zen_not_null($oInfo->last_modified)) $contents[] = array('text' => TEXT_DATE_ORDER_LAST_MODIFIED . ' ' . zen_date_short($oInfo->last_modified));
        $contents[] = array('text' => '<br />' . TEXT_INFO_PAYMENT_METHOD . ' '  . $oInfo->payment_method);
        $contents[] = array('text' => '<br />' . ENTRY_SHIPPING . ' '  . $oInfo->shipping_method);
        $contents[] = array('text' => '<br />' . TEXT_INFO_ORDER_LANGUAGE . ' ' . $order->language['name']);`

**Comment by GaryH21** [comment]
I'll take this one if that's ok?

**Comment by GaryH21** [comment]
Pull-request submitted #1299

**Comment by drbyte** [comment]
Merged
