### ISSUE TITLE
Debug-log notifications:  Clicking link goes nowhere

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1256]
If a debug-log is generated, a notification shows up in the admin header, displaying the following text-link:

`Debug log file(s) discovered.  Found (n)`

Clicking on the associated link goes ... nowhere.

**Comment by scottcwilson** [comment]
I don't think it was really intended to be a clickable link.

**Comment by lat9** [comment]
If a link isn't supposed to be clickable, it shouldn't be coded as an anchor-link.

If the notification doesn't point the admin-user to a page for additional information/resolution, its usefulness is significantly reduced and will result in multiple "what does this mean" postings on the forums once the code is released.  There's a log-file widget on the main page, why not link the notification there?

**Comment by scottcwilson** [comment]
I'm not sure linking to the main page would be the way to go because the widget may not be displayed.  But you're right - it shouldn't be an anchor link if it isn't - I didn't do a view source so I didn't know that it was.

**Comment by drbyte** [comment]
> the associated link goes ... nowhere.

It goes to `#`, which is typically a placeholder anchor (often suggesting further development is planned but not implemented yet). 

Understandably those are confusing and annoying.

The default of `#` is set in `includes/library/zencart/AdminNotifications/src/AdminNotifications.php`
and the output links are generated in the `/admin/includes/template/partials/specialMenu/tplNotificationsBell.php` template.

Both files would require changing if the `#` default were to be squashed. 

Or better would be to actually create a page for the link to actually link to. There's no such page at this point. 

> @lat9  wrote: "There's a log-file widget on the main page, why not link the notification there?"

I'm not sure that's helpful. To "link to" a widget on the home page is basically just a link to the home page. I guess if you were already at some page "other than" the home page when you finally clicked on the notifications dropdown then "home" might make sense. But if you were already on the home page, then the concern about "creating confusion" is not mitigated.

**Comment by zcwilt** [comment]
My preferred option would be to create a page to view the logs as a report. This however requires some more infrastructure.

e.g. 
 

1. A Paginator Adapter class that works from an array (as opposed to a sql query)
2.  A Report Definitions Class that doesn't require a queryBuilder definition 

Both should be fairly simple to implement and would have use for some other pages.

**Comment by lat9** [comment]
Sounds like a plan, @zcwilt!

**Comment by scottcwilson** [comment]
Issues 1268 and 1269 created to track these requests.  I will take the first one.
