### ISSUE TITLE
Admin Languages: Either link or text needs update

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1258]
Click Localization->Languages (nice new look&feel, BTW).  

On the left-side of the screen there's a button named "Orders Status" that links to /index.php?cmd=zones ... either the text or the link is incorrect.

**Comment by lat9** [comment]
On a similar vein, click Localization->Orders Status.

The button labeled "Currencies" links to /index.php?cmd=countries and the one labeled "Languages" links to /index.php?cmd=geo_zones.

**Comment by scottcwilson** [comment]
Good catch.  Fixed.
