### ISSUE TITLE
Customers->Customers, missing right-pane on initial entry

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1259]
Click Customers->Customers (I've got the demo products loaded).  On initial entry, the list shows the table entry for "Bill Smith", but the right-side pane (with the edit/delete/email/reset pwd buttons) is missing.

Clicking on Bill's table-entry causes that right-side pane to be properly displayed.  The right-side pane should be displayed on initial entry.

**Comment by scottcwilson** [comment]
Same issue on Customers->Orders.  This is not so much a bug as an inconsistency with 1.5.5 and prior releases.  This might not be worth fixing if the intent is to replace these pages with Admin LEAD pages.

**Comment by lat9** [comment]
Potato, Potahto ... for admin users that are "used to how prior releases work", inconsistency === bug!

If the pages are going to the new LEAD interface (very nice, BTW), then I agree with you; let's keep this issue on-hold until such a determination is made.

**Comment by zcwilt** [comment]
Yes, the plan would be that all current admin pages would be moved to the new Controller infrastructure and pages like Orders/Customers use the LEAD (with some extensions)  stuff  as well.

**Comment by drbyte** [comment]
Yes, the display will change even more (for the better) when those pages are converted.
