### ISSUE TITLE
A Paginator Adapter class that works from an array

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1268]
Current paginators work from a sql query.
Required to resolve issue #1256.
Please assign to me.

**Comment by scottcwilson** [comment]
@zcwilt Are you sure `includes/classes/paginator/paginatorAdapters/class.zcPaginatorAdapterArray.php` doesn't already do this?

**Comment by zcwilt** [comment]
Those classes are deprecated (not sure why they haven't been removed)
The new paginator classes are in the includes/library directory structure and are somewhat different from the original.
