### ISSUE TITLE
ajax.php: Should $robotsNoIndex be set?

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1296]
I've been chasing an issue for the past year on one of my commercial plugins that makes use of the Zen Cart's default ajax.php handling.  That plugin's AJAX handler performs some input validation and I've seen multiple reports of the plugin logging the fact that its parameters aren't properly set.

I believe that this is due to search engines finding and calling the ajax.php function.  As such, I was thinking that having the ajax.php module include (prior to its load of application_top.php) the following statement:

`$robotsNoIndex = true;`

might mitigate that invalid usage.

**Comment by drbyte** [comment]
At the present time, `$robotsNoIndex` is used to indicate that an HTML `<meta robots="noindex,nofollow">` tag is to be output into generated HTML in the `<head`> section of (certain) template pages.

The ajax.php script is used for making ajax calls (which should not be returning full HTML pages).

**Comment by lat9** [comment]
OK, then is there some kind of processing flag that identifies that the access is being made by a robot/spider?

**Comment by lat9** [comment]
OK, then is there some kind of processing flag that identifies that the access is being made by a robot/spider?

**Comment by lat9** [comment]
How about adding the following to the ajax.php processing?  Although that value can be hacked, it will cover the majority of the times when the script is loaded outside of an AJAX handler.
>         // -----
>         // Continue only if the request was AJAX requested.
>         if ((isset ($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower ($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest')) {
>             <remaining processing>
>         }

**Comment by drbyte** [comment]
@zcwilt and I were just discussing this. We like that "test", but would probably do it with an "early return" approach (ie: exit with a failure status if not a valid request) instead of wrapping all the "okay" execution path inside an "if" construct. 

I'll take a look at a possible PR for this, and would be glad for your feedback on its effectiveness.

**Comment by drbyte** [comment]
@lat9 can you test out this update: https://github.com/zencart/zencart/pull/1298

**Comment by lat9** [comment]
I agree with the return-on-detection approach; that's what I've currently got implemented!

It turns out that the above check is necessary but insufficient, as good ol' googlebot comes through with that value set.  What I'm currently testing is:
>         // -----
>         // If this request was not made via AJAX or the request appears from a spider or bot, simply return.
>         if (!(isset ($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower ($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest') || 
>              (isset ($_SERVER['HTTP_USER_AGENT']) && preg_match ('/bot|crawl|slurp|spider/i', $_SERVER['HTTP_USER_AGENT'])) ) {
>             return;
>         }

**Comment by drbyte** [comment]
What sort of errors are you seeing in your logs, caused by spiders accessing ajax.php? 

I guess I need more context here.

**Comment by lat9** [comment]
It's just that I write my code "defensively", so my AJAX class expects **and checks for** properly-supplied $_POST inputs when it starts and logs an interface error when the inputs aren't present.  Those inputs aren't present when the bots make that ajax.php call directly.

**Comment by drbyte** [comment]
Good approach.

I'd suggest adding a similar rejection with a `400` response if inputs aren't present. And maybe only log an error when running in your dev environment.

**Comment by lat9** [comment]
Sounds like a plan; thanks for the update.
