### ISSUE TITLE
some metatag descriptions have a space at the end

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#1303]
in /modules/metatags.php
various places.

`META_TAG_DESCRIPTION......$meta_products_description . ' '));`

I don't think there should be white space at the start or end of an attribute but in any case but I don't think these spaces serve any purpose?

**Comment by drbyte** [comment]
I'd entertain a PR that removed the space from those 2 or 3 spots.

**Comment by jonny2plates** [comment]
i'll take this one if that's ok

**Comment by drbyte** [comment]
Okay

**Comment by drbyte** [comment]
Merged #1324
