### ISSUE TITLE
Refactor/modernize the upload class

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#1307]
Presently the upload.php class has a flaw in that it attempts to support some very old PHP constructs that are no longer relevant.
(And in at least one reported case appears to trigger uncaught errors with bogus upload attempts).

It really could use an overhaul. 

Naturally, it's important to keep in mind that anything which has access to upload files to the server needs some pretty solid security protections to as to avoid malicious abuse. 

The class needs to support both admin and non-admin implementations.

Existing validation support should be retained.

**Comment by llynix** [comment]
I took a stab at this.  But I needed to dig deeper on the changes between 1.5.5 and 1.6.

I thought I'd add what I had here.  I didn't do much to it except cut out a TON of unneeded code.  It is untested.
[upload.txt](https://github.com/zencart/zencart/files/578964/upload.txt)

**Comment by drbyte** [comment]
Closed by #1393
