### ISSUE TITLE
ajax.php: Functions need to be defined before use (155 branch)

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1318]
When using the ajax.php file on a ZC 1.5.5a installation, I receive an "Error 500" when the interface is used:

`PHP Fatal error:  Call to undefined function utf8_encode_recurse()`

The issue is that the utf8_encode_recurse function doesn't exist and the fall-back declaration (as well as the ajaxAbort declaration) occurs **after** the functions' invocation.

**Comment by drbyte** [comment]
Fixed by https://github.com/zencart/zencart/pull/1323
