### ISSUE TITLE
Orders Status History - Updated By

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1342]
Is there any interest in adding the `updated_by` field to the orders_status_history handling, currently provided by [this ](https://www.zen-cart.com/showthread.php?212664-Orders-Status-History-Updated-By-Support-Thread)plugin?  If so, I'll generate a PR.

**Comment by drbyte** [comment]
Sure.

**Comment by lat9** [comment]
Is there any documentation (or guidance) for the places that "need to be touched" to add another field to a database table for the zc_install processing?

**Comment by drbyte** [comment]
`/zc_install/sql/install/mysql_zencart.sql`
`/zc_install/sql/updates/mysql_upgrade_zencart_160.sql`

**Comment by lat9** [comment]
Thanks, DrByte, for the file-related pointers.

Next question:  Is there some means of identifying that a code change includes a required database update (for all the developers that have currently forked and/or downloaded a development version)?

Once this change is accepted, orders' processing will require the presence of that `updated_by` field.

**Comment by drbyte** [comment]
Good point.

Unfortunately no there's no indicator like that for "dev environments" ... other than getting a blank page and checking the logs which will point out the missing field.

**Comment by lat9** [comment]
Perhaps the addition of an issue-status that can be applied to a commit that contains a required database update?  It's not a perfect solution, but that would serve as both "notice" and "reminder".

**Comment by drbyte** [comment]
meh ... to me it feels like more administrative burden, and something I'm likely to forget to do.

Short of human error we're not going to merge PRs which require db changes if those changes are not included in the `/zc_install/sql/updates/mysql_upgrade_zencart_160.sql` file. So that's the only file that needs to be monitored if you're trying to keep your dev db up to date while preferring not to do fresh installs.

**Comment by lat9** [comment]
Fair enough.  I'll add that to my list of stuff to check!

**Comment by scottcwilson** [comment]
Every once in a while you need to regenerate your V160 database from scratch because of a db change.   This is a pain, but on the other hand, it gives you an opportunity to do a quick test of either an upgrade from 1.5 or a fresh install, and I have found bugs in both by doing this.  :)

**Comment by drbyte** [comment]
@lat9 would it be too complicated for plugin compatibility checking to have this in v156? 
Or leave it for a future release?

**Comment by lat9** [comment]
Leaving it for the next release after 1.5.6 is fine with me.

**Comment by drbyte** [comment]
I'm okay with implementing the fields and related code into v156.
But just wondered whether doing that creates upgrade problems for people already using the plugin?

**Comment by lat9** [comment]
Shouldn't be an issue, assuming that the `zen_update_orders_history` function's interface (and associated notifications) are maintained.

**Comment by scottcwilson** [comment]
I have always thought this should be part of the core. Thanks for doing it, Cindy.

**Comment by drbyte** [comment]
Closed by #1827
