### ISSUE TITLE
Question:  Where did the server_info.php functionality "disappear" to?

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1367]
I was looking to update the handling to include the SQL server information, but there's no longer a server_info.php file in the admin.

Where did that processing get incorporated?

**Comment by zcwilt** [comment]
Hi
In 1.6 that page has been converted to the new controller structure.
The class that creates the information is at  
`includes/library/zencart/Controllers/src/admin/ServerInfo.php`
and the template at 
`admin/includes/template/templates/tplServerInfo.php`

Note, in the future there may be changes to the directory structure for controllers, and some extra notfiers for overrides. For now though, feel free to hack on it and submit PR.

**Comment by lat9** [comment]
Will do, zcwilt (and thanks).  It would have taken me a while to track that down.

**Comment by lat9** [comment]
OK, so I see where the controller/template files get loaded.  How does the ServerInfo.php controller's language file (server_info.php) get loaded?  Is that converting the camelCased name of the controller into a `_` separated value?

**Comment by zcwilt** [comment]
so the link to the server info page is 
/index.php?cmd=server_info
and the language file is loaded from the cmd=
so ultimately that language file is the same as it ever was 
eg admin/includes/languages/english/server_info.php

**Comment by zcwilt** [comment]
and that is another thing to note in admin
you won't ever see a link like 
admin/page.php 
it will always be 
admin/index.php?cmd=page

**Comment by drbyte** [comment]
Closed by #1375
