### ISSUE TITLE
Module mapping v1.5.x -> v2.0?

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1372]
As spoken by Dorothy in the _Wizard of Oz_:

> 'Toto, I've a feeling we're not in Kansas anymore.'

Is there any kind of documentation (even a simple list) that provides a mapping of modules from the 1.5.x series (i.e. Kansas) to their new home in v1.6.0 (Oz)?

**Comment by drbyte** [comment]
"modules"?

**Comment by lat9** [comment]
Source files, e.g. my friend /admin/server_info.php which no longer exists in 1.6.0.

**Comment by zcwilt** [comment]
I understand by modules, you mean pages. 
e.g 1.5 admin had a page called admin/countries.php which now does not exist in 1.6

These now exist in 1.6 as controller classes. 
Unfortunately documentation is lagging behind code. 
@scottcwilson did do some work on documenting the Lead controllers 
see https://docs.zen-cart.com/Developer_Documentation/1.6/code_docs/admin_lead_pages/introduction

However even this is out of date. My fault not @scottcwilson 

I'm currently working on refactoring the controller stuff for 1.6 so there isn't much point juts yet in updating docs. 

But to give you an idea of why we made the change and where we are going with this.

Most admin pages are just a way of listing the contents of a database table, and then allowing for Editing/Adding/Deleting entries.

In 1.5 to create a new page that managed a database table, you would probably copy an existing page and then spend a long time changing references/links etc and then more time debugging the bits you missed. 

In 1.6 you can now define a page that manages a database table by defining an array of properties, and for the most part, you don't have to write any php code.

**Comment by zcwilt** [comment]
Further server_info now exists at 
app/controllers/admin/ServerInfo.php

**Comment by lat9** [comment]
Thanks, @zcwilt.  I understand the reason for the change, it's just that I'm having (based on my current v1.6.0 experience or lack thereof) a heck of a time figuring out how everything "fits together" in the new structure.
