### ISSUE TITLE
v155 zc_install does not fully support table prefixed upgrade of 1.3.8

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#1386]
The upgrade script from 1.3.8 to 1.3.9 includes a query that is not fully supported by the zc_install process as rewritten for ZC 1.5.5.

This issue is further discussed in the ZC forum at [Error: Database upgrade from 1.3.8a](https://www.zen-cart.com/showthread.php?221788-Error-Database-upgrade-from-1-3-8a).

**Comment by drbyte** [comment]
Closing this, as there's no need to open "both" an "issue" and a "Pull Request" separately.  The pull request serves adequately as an "issue" if it contains sufficient descriptive content ;)

**Comment by mc12345678** [comment]
Got it.  Thought there was some additional "need" for the independent issue as a "formality". :)
