### ISSUE TITLE
Non-ASCII text attributes' values improperly truncated.

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1387]
When a text-box attribute's input contains non-ASCII characters, those attributes' values can be improperly truncated due to the use of the PHP "normal" string-related functions instead of their multi-byte counterparts.

See [this ](https://www.zen-cart.com/showthread.php?221825-Text-Attribute-String-Length&p=1325631#post1325631)Zen Cart posting for details.

**Comment by drbyte** [comment]
Switching to the mb_xxxxx functions everywhere is a large refactoring exercise.
Safer to do it in the `develop` branch, not in the v15x series.
