### ISSUE TITLE
Notifiers In Admin

### ISSUE THREAD

**Issue by bislewl** [zencart/zencart#139]
I think it would be helpful if the notifiers were also in the Admin. This could be helpful for a variety of modules and creating new modules.

**Comment by drbyte** [comment]
@bislewl Do you have a list of the kinds of notifier hooks you're interested in for the Admin?

**Comment by bislewl** [comment]
Some basic things would be a great start!
* Configuration Changes
* Changing Specials
* Modify/Add/Remove Product/Category
* Modify Attributes (This could be useful for a mod like SBA)
* Modify/Add/Remove Admins
