### ISSUE TITLE
tpl_product_info_display.php form element

### ISSUE THREAD

**Issue by reetp** [zencart/zencart#1406]
Only a  small annoyance but I noticed in tpl_product_info_display.php that at the end of the file there is a standard html `</form>` tag, but my IDE complained there was no matching `<form>`

That's because it is programmatically generated at line 20

```php
<!--bof Form start-->
<?php echo zen_draw_form('cart_quantity', zen_href_link(zen_get_info_page($_GET['products_id']), zen_get_all_get_params(array('action')) . 'action=add_product', $request_type), 'post', 'enctype="multipart/form-data"') . "\n"; ?>
<!--eof Form start-->
```

A simple fix is to wrap the offending tag in PHP - I'm not sure that is the correct way to deal with it but it shuts up my IDE and just makes things tidy :-)

```php
<!--bof Form close-->
<?php echo "</form>"; ?>
<!--bof Form close-->

```

```diff
-</form>
+<?php echo "</form>"; ?>

```

**Comment by drbyte** [comment]
Hi @reetp 

Thanks for posting this. It's true: whenever zen_draw_form or other helper functions for drawing form fields are used, some IDEs will complain if the closing tag for those elements is in plain HTML instead of quoted in a PHP string.
