### ISSUE TITLE
Laravel Capsule

### ISSUE THREAD

**Issue by zcwilt** [zencart/zencart#1409]
Some months ago we added Laravel Capsule to core code and are updating core code to use this. 

Laravel Capsule allows you to use the Laravel Model/ORM infrastructure in a project that is not in itself based on Laravel.

Why are we doing this ?
-  Security

Currently when writing database queries you need to manually ensure that parameters are safe to use, to mitigate the potential for SQL Injection hacks. Currently this can be done by either casting the value 
e.g. `(int)$someValue` 
or using the bindVars protocol 
e.g. `$sql = $db->bindVars($sql, ':ordersID:', $ordersID, 'integer');`

Laravel Model/ORM automatically uses PHP PDO to bind variables to a field, reducing the complexity and removing the worry of ensuring database query parameters are 'safe'

- Simplicity

Zen Cart has a diverse user base, and a diverse developer base,. Could we make writing sql queries easier for those developers who haven't the experience with sql. 

Laravel ORM gives you a fluent interface for writing  queries.

Take for example this legacy code  

```
   $sql = "UPDATE " . TABLE_COUPON_GV_QUEUE . " set release_flag = 'Y' WHERE unique_id = :id:";
   $sql = $this->dbConn->bindvars($sql, ':id:', $id, 'integer');
   $result = $this->dbConn->execute($sql);
```
converting would give us 

```
    $couponQueueModel = $this->modelFactory->factory('CouponGvQueue');
    $result = $couponQueueModel->where('unique_id', $id)->update(['release_flag' => 'Y']);

```

 - Consistency

 Having a fluent interface to sql queries, makes core code more consistent and easier to understand. especially for developers with little experience in SQL.

- automation 

For many database tables we have a last_modified and date_added field, and when writing insert/update queries we have to manually set these fields 
e.g.  last_modified = now()

Laravel Model/ORM allows you to define in configuration whether a table uses these `timestamps` and they will automatically be added to the insert/update sql. 
- other

There are a lot of other benefits, 
e.g. relationships, foreign key constraints and others which will allow for cleaner code in the future.

**Note.** The legacy queryFactory class will always still be available.

**Comment by mc12345678** [comment]
What are/would be the code tests/checks of the presence of the Laravel Model/ORM code's presence?

**Comment by zcwilt** [comment]
The Laravel ORM system is loaded automatically in includes/init_includes/init_database.php for both catalog and admin code.

The actual models are stored in `app/Model`
e.g. `app/Model/Products.php`

It should be noted that at this point not all database tables have been converted to Model classes, and for those model classes that have been created, not all are complete in their code, although this is mainly for foreign key relationship descriptions. 

In terms of using the code, you first need to have access to the ModelFactory class and how you do this is dependant on where you are writing code. In a lot of the new admin code I'm using Dependency Injection (automated by Aura/DI) to inject an instance of the ModelFactory class, but this boils down to doing 

`$modelFactory = new App\Model\ModelFactory($db) `
were `$db` is the global `$db queryFactory` value, although I should note that passing this will not be necessary once I do my next PR. 

Getting a concrete model instance is then just a matter of doing 

`$myModel = $modelFactory->factory('ModelName') `
so for the Products.php model class the model name is Products

One further thing, and this relates to tables that have translatable entities, e.g. products and products_description

I have started some work on automating the model queries, such that translated entities will be automatically pulled in with the base model without the need to manually create a join on the translation table. 
see` app/Model/TranslatedModel.php`

This code also allows more specificity for language locales, allowing for say en_US and en_UK, and for cascading fallback languages.

As I mentioned earlier, I have an ongoing update branch that I'm using to integrate the use of Models into the admin code (and some catalog code) and hope to push the PR in the next week (if not sooner)

Hope that helps

**Comment by mc12345678** [comment]
It certainly is descriptive, but my thought in the question was in the concept of dual design at least during this transition period such that the old could eventually replace the new.  Yes, the new will still accept the old, but as described there are some obvious benefits of using the new.  But not all systems will support the new right away.  So the question is/was for what is envisioned that can be checked/tested (a existence of a class, a file, a method, a module, etc...) that would identify that the Laravel ORM system could be used instead of the old database access.  There certainly are things that will need to be reviewed as the project continues, just trying to grasp at an understanding. :)

**Comment by drbyte** [comment]
So, in less words, are you asking "how do I write my plugins to work with both old and new versions at the same time"?

**Comment by mc12345678** [comment]
> So, in less words, are you asking "how do I write my plugins to work with both old and new versions at the same time"?

That is answered by using the old/current style of writing. But along that line: "how do I write my plugins to include both old and new styles at the same time"?

**Comment by drbyte** [comment]
That remains to be seen.

It may not make sense to use both at the same time. ie: they may need to be separate beasts.

**Comment by mc12345678** [comment]
> ie: they may need to be separate beasts.

Agree, though looking for the programmatic fork in the road, when/if it exists. :) (I don't want to get the carriage too close to the horse, but don't want it left in the dust either.) Time will tell how/if it is something that can be "tucked away" or if instruction provided to forget the old and start using the new (for plugins).

**Comment by zcwilt** [comment]
@mc12345678  said

>  So the question is/was for what is envisioned that can be checked/tested (a existence of a class, a file, a method, a module, etc...) that would identify that the Laravel ORM system could be used instead of the old database access.

There isn't any test, nor does there need to be.

The laravel ORM will always be available in both admin/catalog and 1.6 will have models for all core database files.

**Comment by amirshawn** [comment]
I'm curious, does this mean future development will be possible using eloquent?

**Comment by zcwilt** [comment]
@amirshawn Sorry for not answering this earlier. 
Yes, in the 1.6 branch you will be able to use eloquent for all database queries, The old queryFactory class will still be there to support legacy code.

Routing is a different topic. We don't have any current plans to introduce routing into the initial 1.6 release. Much as we would like to, There are lots of complications, such as managing legacy urls, and not busting your sites google foo.

**Comment by zcwilt** [comment]
@mc12345678 
I think it would be a bad idea to try and write a plugin that supported both 1.6 and 1.5 style queries. As mentioned earlier QueryFactory sql queries will still work. Given other changes happening in 1.6 I  would expect that plugin authors would release 1.6 only versions. A PITA for support, but necessary to get some modernisation into code.
