### ISSUE TITLE
Shipping module update (virtual -> non-virtual)

### ISSUE THREAD

**Issue by flyvholm** [zencart/zencart#1410]
I had a problem with shipping modules not updating correctly when the shopping cart was revised during checkout, changing the order from virtual to non-virtual. I did a simple fix that seems to work for me without ill effects, editing includes/modules/pages/checkout_shipping/header_php.php:

`   if ($order->content_type == 'virtual') {`
`    $_SESSION['shipping'] = array();`
`    $_SESSION['shipping']['id'] = 'free_free';`
`    $_SESSION['shipping']['title'] = 'free_free';`
`    $_SESSION['shipping']['cost'] = 0;`
`    $_SESSION['sendto'] = false;`
`    zen_redirect(zen_href_link(FILENAME_CHECKOUT_PAYMENT, '', 'SSL'));`
**`  } else { unset($_SESSION['shipping']); }`**

Just added the `else {}` at the end. I hope this doesn't break anything and thought it was worth bringing to your attention in any case.

**Comment by drbyte** [comment]
That could have undesired side effects. When cart contents change it normally presents a message saying that the shipping options have also changed, and forces going back thru re/choosing a shipping module.

Can you explain in great detail what exactly the problematic symptoms were that you were trying to resolve? Including what shipping modules, what combination of (kinds of) products in the cart both before and after the change, etc? Anything and everything that would be needed to duplicate the *exact* same problem on another fresh uncustomized site (no plugins).

**Comment by mc12345678** [comment]
Also, it seems that it may be worth identifying the version of ZC on which this problem was identified (maybe DrByte knows by familiarity with that section of code, but it helps to have it stated). There were some related issues on one of the versions of ZC that were provided a solution in the applicable bug fixes for that version.

**Comment by flyvholm** [comment]
My apologies. After testing on a clean Zen Cart install I see why $_SESSION['shipping'] didn't update the way I expected it to. However, I also see that there are problems handling special characters. This is the case for order comments entered by customers during checkout and for emails sent from admin. A mix of conversion errors show up in previews and the actual emails sent, text and HTML. You can verify this easily by testing with a string containing characters affected by htmlspecialchars() and stripslashes().

Do you want me to compile a list of where I've come across this? If so, should I post it as a new issue?

**Comment by drbyte** [comment]
Customer order comments intentionally disallow use of HTML markup, and will be translated to their respective HTML entities, or stripslashes will bust them by converting them to `_` chars.

It's definitely a different issue than the Shipping one originally opened here.  If you're going to open another one, be sure to have thoroughly tested the symptoms on a fresh v1.5.5 or v1.6.0 install using a UTF8 database with default demo data and default english language pack, and no plugins. Include your PHP version.
