### ISSUE TITLE
Use PHP sprintf "argument swapping" instead of eval'd formats

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1415]
It's always bothered me that the address-formatting uses the PHP `eval()` function and I'd like to suggest, instead, that we use the PHP sprintf function's argument-swapping instead.

For example, the current address-format for address-format 1 is

`$firstname $lastname$cr$streets$cr$city, $postcode$cr$statecomma$country`

Assuming that the formatting of the address is coded with a fixed format:

`$address_out = sprintf ($address_format, $cr, $firstname, $lastname, $streets, $city, $postcode, $state, $country);`

Then the address-format for address-format 1 could be written as:

`%2$s %3$s%1$s%4$s%1$s%5$s, %6$s%1$s%7$s%8$s`

Yes, it's _somewhat_ cryptic, but the variables will be assigned as:

%1$s ... $cr  (used multiple times!)
%2$s ... $firstname
%3$s ... $lastname
%4$s ... $streets
%5$s ... $city
%6$s ... $postcode
%7$s ... $state  (with either the comma pre-appended or not)
%8$s ... $country

**Comment by zcwilt** [comment]
yes, it's always worried me as well. The eval stuff goes back along way into osCommerce legacy code, and I was never a big fan of the way address formatting (and the related db schema stuff) worked. 

Have you built any code for this yet?

**Comment by lat9** [comment]
@zcwilt, I have not (yet) built any code to do this; I wanted to gauge interest before devoting actual-coding time!  

I'm taking your answer as "interest" and will go to the next level to see how much effort is involved.

**Comment by zcwilt** [comment]
Definitely interest. I guess the problem I foresee is that of upgrading.

**Comment by lat9** [comment]
Agreed.  I'm not aware of any plugins that manipulate the `address_formats` table, but I'm sure that they're "out there".

How about I approach it starting with a new table, e.g. `address_formats2`, to keep the currently-defined formats around at least through some transitional period?

**Comment by drbyte** [comment]
I was looking at this after you posted it, and wondered if eval is even needed. Can't we just let PHP's own variable substitution take care of it?  That's what double-quotes and braces are for, right?

I do like that the address-formats in the table are quite easy to read. I'd rather not see them become more complicated to grok for the layperson

**Comment by lat9** [comment]
Good point, DrByte ... there are always multiple ways to "skin a cat"!  As mentioned in my initial post, using the sprintf formats will result in address-formats that are (at best) "thought-provoking".

Are you going to continue the investigation regarding the "removal" of the use of `eval()`?

**Comment by drbyte** [comment]
I was talking with @zcwilt  about the possibility of using a regex parser to read the current formats, update them to work with interpolation (double-quotes and braces), and output without `eval`. He said he'd explore that a bit further.

Additionally, I've seen packages that provide address format info for "some" countries, using `Liquid` syntax, ie:

`{{address}}\n{{city}}, {{state}}\n{{zip}}\n{{country}}`

I like keeping the formats very human-readable so they're easy to understand what to expect.

**Comment by drbyte** [comment]
But then that leads me to wondering ...

If we had say a `country_demographics` table that included ISO data on states, currencies, languages, and fairly-standardized address-formats, for each country, and a class to take care of lookup of that data, how could we rework internals such as:

- restricting which countries a store wants to ship to
- formatting address labels
- recommending currencies/languages a storeowner might choose to support
- labeling fields for customers entering address info (like "state" or "province" or "county" etc)
- matching up country/region pairings to declare geo_zones to support current zone handling

**Comment by lat9** [comment]
Sounds good!  I was mulling around the thought of an `Address` class that would serve as a "portal" into this realm.

Then the address-related functions could be updated to use the class-based methods to provide the information.

**Comment by drbyte** [comment]
Closed by PR #1809
