### ISSUE TITLE
Isn't it time to make ez-pages multilingual?

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#1416]
This has been something that annoyed me since I started with Zen Cart, in the 1.3.8 era.  The ez-pages are only single language in the core.
Is there any interest to bring this add-on: [Multi-Language EZ-Pages](https://www.zen-cart.com/downloads.php?do=file&id=36), to the core code?

**Comment by drbyte** [comment]
I've often considered it, but then when I go to inspect how stable the plugin is it seems someone else is posting that they're having pain with it.

I'd consider a PR for v160

**Comment by Zen4All** [comment]
I have installed this module on multiple installations, and can't remember I ever had a problem with it, but I'll install and test it on a zc160 testbed, and see what happens.
If nothing out of the ordinary happens, I'll prepare a pull for the 1.6 branch

**Comment by drbyte** [comment]
I'd welcome a PR. 
Even for v156 as long as the schema changes aren't terribly drastic or complex regarding old data.

**Comment by Zen4All** [comment]
I'll make a pr next week.
The scheme changes are not that complex.

**Comment by drbyte** [comment]
Hi @Zen4All what are your thoughts on readiness of this for v156?

**Comment by drbyte** [comment]
Closed by PR #1789
