### ISSUE TITLE
GV FAQ displaying email address

### ISSUE THREAD

**Issue by judygunderson** [zencart/zencart#1418]
With harvesters of email addresses running rampant on the internet with the sole intention of finding exposed email addresses and sell them to spammers... I would like to suggest that the GV FAQ page not populate the store email address on the "When Problems Occur" section.  I have been changing the includes/languages/english/gv_faq.php file like this:

```diff
-define('SUB_HEADING_TEXT','For any queries regarding the ' . TEXT_GV_NAME . ' System, please contact the store by email at '. STORE_OWNER_EMAIL_ADDRESS . '. Please make sure you give as much information as possible regarding the issue so that we can fully address the problem.');
+define('SUB_HEADING_TEXT','For any queries regarding the ' . TEXT_GV_NAME . ' System, please contact the store by email by filling out the form on our <a href="index.php?main_page=contact_us">Contact Us page</a>. Please make sure you give as much information as possible in the email. ');`
```

There may be other pages that use  `STORE_OWNER_EMAIL_ADDRESS` that expose the email address to harvesters... but this is the one I found recently and thought I should report.

**Comment by zcwilt** [comment]
Hi Judy

so in Europe its a legal requirement to display somewhere a contact email (along with other contact details|) I'm not up to date with US/Canada requirements.

**Comment by judygunderson** [comment]
Noted Ian - but that can be done with an Impressum page or even on the contact us page - while not having to reveal their email address because of the form.  

Having it on the GV FAQ page certainly does not meet the legal requirements first because it is not "easily found" and secondly because many people turn off this page because they do not offer gift certificates.
