### ISSUE TITLE
Image Rotation

### ISSUE THREAD

**Issue by bislewl** [zencart/zencart#1439]
There seems to be issues with uploading images. When taking the photo with the photo of the product with their smartphone, they turn the camera sideways (portrait). When looking at the picture on their desktop it looks fine then when uploading it's turned sideways. 

Maybe something like this would help?
http://php.net/manual/en/imagick.getimageorientation.php#111448

**Comment by barco57** [comment]
First, not every server has ImageMagick installed. 
Second, how timely, as I am working on a client site where they used their camera to take all of the images and uploaded them without preprocessing. So I have a site that is extremely heavy, like most people, they have no idea that they should not upload 5MB slider images, 2MB product images, that they should be preprocessing those images in an image editor.
So the idea of adding something to core code that says basically says "hey, we know you are stupid and are going to upload the raw image from your camera, without regard as to whether or not it is a good idea, so we have included some code that will at least get the display orientation to match what orientation you held the camera when taking the picture." makes me cringe

**Comment by wiztechinc** [comment]
Biggest issue I have is clients adding way large files - this is a horrendous idea. Not just for load time but most servers don't allow the capacity image handler needs to resize large files and it takes pages down (not as a php error either)

**Comment by bislewl** [comment]
@barco57 I understand your position but we have to be mindful for people not to abuse it either. Maybe a comprehensive solution that has processing for reducing the images. 
@wiztechinc You gave me an idea that would solve the problems. 
What about if rather the processing on customer views, If we processed on admin upload? 
That should solve the load time issue @wiztechinc mentioned, the huge file issue @barco57 mentioned. If those images optimized from the start that would eliminate the need for IH, wouldn't it?

I can think of a few sites that I have used this on. Most of them also do drag/drop uploading and drag/drop sorting. Another thing to think about too!

**Comment by drbyte** [comment]
I've used the http://image.intervention.io package on some sites (not ZC related) with great success. Setting the right image orientation is a simple one-liner.
It can also be used to build resized images from a larger master during upload. 
Haven't tried integrating it with Zen Cart yet.

**Comment by wiztechinc** [comment]
One thing I think is important to also mention. There are folks who want the large images for one reason or another - using zoom to see the details in a large pic for example. They may or may not use image handler. They may or may not create different images for each size. But they want a choice. 

I suggest perhaps that when uploading an image that is just ridiculously large, the site owner is told it's large and ask if he / she wants it optimized / resized appropriately. And /or an admin setting that does it automatically as opposed being faced with the choice each time. The notification is something that can be put in long before deciding on any of the rest.

**Comment by mc12345678** [comment]
@bislewl commented on one aspect that is in part "outside" of ZC which is the drag/drop ie. ftp of image files.  With so many alternate ways of uploading the image, it would almost seem like something that scavenges the images directory for such "non-compliance" issues would be a better way to go.  Certainly triggered as a part of the image upload process, but also available for those images placed on the server to then be used or linked.

I don't think that addressing the single image size would necessarily do away with IH, but it would at least ensure that the first image is within an expected/acceptable limited size and therefore anything such as IH could do what is needed from there. Yes having options available certainly makes the total package more appealing but unfortunately and not convinced that it is a ZC limit some images just can't be so easily processed and perhaps need to be downloaded to the customer for their own viewing/sizing/manipulation.

Interesting issue though of transformation of cell photo to online and the problem(s) caused (i.e. portrait to landscape or vice versa).

**Comment by drbyte** [comment]
We should probably adjust the core code to allow for a lightweight plugin to intercept the upload of images and do some brief processing.
In fact, we probably already have a notifier-hook that could be leveraged for this.

**Comment by drbyte** [comment]
Notifier hook `NOTIFY_ADMIN_PRODUCT_IMAGE_UPLOADED` can be used for this.
