### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by zhonghaozhao** [zencart/zencart#1443]
[removed]

affect 1.6.0

**Comment by drbyte** [comment]
Thanks. Please report security concerns by email to security[at] zen-cart [dot]com

**Comment by drbyte** [comment]
The XSS allegation you posted can't be replicated on a legitimate fresh install of v1.6.0 on latest PHP version.

Closing.

**Comment by zhonghaozhao** [comment]
I send a email to your security partment, and you guy reproduced this issuse.   I want to know whether this issuse is fixed or not? How is it going ?

**Comment by drbyte** [comment]
See #1446

**Comment by drbyte** [comment]
Thanks for the report. 

It is important to note: Zen Cart v1.6.0 is UNRELEASED CODE at this time. This version is not in use on live websites.
