### ISSUE TITLE
Admin - vertical align of text with radio button

### ISSUE THREAD

**Issue by WebsiteRob** [zencart/zencart#1448]
admin/includes/css/bootstrap.css #5

1 change

from:
input[type=checkbox],input[type=radio]{margin:4px 0 0;margin-top:1px\9;line-height:normal}

to:
input[type=checkbox],input[type=radio]{position:relative;top:4px}

It's just a little thing, but does make for a nicer look.

**Comment by zcwilt** [comment]
@WebsiteRob 
changing boostrap.css is probably not the best place to do this, unless/until we have some sass stuff in1.6 as we only load the min.css version.

That said, code works just as well adding it to stylesheet.css, and does make radio buttons look much better. I tested by looking at adding/editing products. 

Will look to do a quick PR for this.

**Comment by drbyte** [comment]
I'm going to disagree here. 
Adding `input[type=checkbox],input[type=radio]{position:relative;top:4px}` to the v160 stylesheet (or changing bootstrap css directly) messes up layout. 

In the case of editing products, all the text gets set confusingly shifted above the radio-buttons and checkboxes. Same in all the LEAD pages. 

Example from editing a product:

<img width="619" alt="screen shot 2017-07-08 at 5 04 32 pm" src="https://user-images.githubusercontent.com/404472/27989127-d0d99d02-63ff-11e7-91de-016940f79e05.png">
