### ISSUE TITLE
includes/languages/english/checkout_payment.php - mismatched SPAN tags

### ISSUE THREAD

**Issue by WebsiteRob** [zencart/zencart#1452]
includes/languages/english/checkout_payment.php

line 32 - mismatched SPAN tags

define('TEXT_CONDITIONS_DESCRIPTION', '<span class="termsdescription">Please acknowledge the terms and conditions bound to this order by ticking the following box. The terms and conditions can be read <a href="' . zen_href_link(FILENAME_CONDITIONS, '', 'SSL') . '"><span class="pseudolink">here</span></a>.');

corrected
define('TEXT_CONDITIONS_DESCRIPTION', '**<span class="termsdescription">**Please acknowledge the terms and conditions bound to this order by ticking the following box. The terms and conditions can be read <a href="' . zen_href_link(FILENAME_CONDITIONS, '', 'SSL') . '"><span class="pseudolink">here</span></a>.**</span>**');

**Comment by WebsiteRob** [comment]
OK, so that didn't work out so well.

Trying again.

``define('TEXT_CONDITIONS_DESCRIPTION', '<span class="termsdescription">Please acknowledge the terms and conditions bound to this order by ticking the following box. The terms and conditions can be read <a href="' . zen_href_link(FILENAME_CONDITIONS, '', 'SSL') . '"><span class="pseudolink">here</span></a>.');``

corrected
``define('TEXT_CONDITIONS_DESCRIPTION', '<span class="termsdescription">Please acknowledge the terms and conditions bound to this order by ticking the following box. The terms and conditions can be read <a href="' . zen_href_link(FILENAME_CONDITIONS, '', 'SSL') . '"><span class="pseudolink">here</span></a>.</span>');``

`</span>` added to end of sentence

**Comment by Zen4All** [comment]
In my opinion the span have should be in the template file, an not in a language define. So if people change the text they do not accidentally delete the span, and its class.

**Comment by drbyte** [comment]
For v155, fixed as @WebsiteRob suggested.
For v160, refactored as @Zen4All suggested.
