### ISSUE TITLE
No zcInstall*.log file generated on initial installation (v1.6.0)

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1453]
Using a copy of the file-set from 2017-07-04, I did a fresh install of ZC1.6.0.  When I looked in the /logs directory, there was no `zcInstall*.log` file generated.

Did that change or did the file's generation get "lost"?

**Comment by drbyte** [comment]
See #579  as a result of #561

**Comment by lat9** [comment]
From my perspective, rather than removing what might be perceived as "history" (I happen to keep my zcInstall*.log files to remember when the various updates were performed), I'd have thought that the checking for the logs should be updated to not look for those types of logs, focusing only on the myDEBUG*.log flavored ones.

**Comment by drbyte** [comment]
The cleanup of those zcInstall*.log files happens only when accessing the Admin. So, if you grab those desired log files before opening the Admin page, you'll have full access to them.
