### ISSUE TITLE
Why does the admin password need to be changed every 90 days?

### ISSUE THREAD

**Issue by dabockster** [zencart/zencart#1461]
Question in title. However, I'm really more interested in learning the thought process on why this was considered a good design decision as opposed to having an even stricter password requirement.

**Comment by drbyte** [comment]
That's the rule decided up on by the PCI Security Council.

It's not something that Zen Cart "came up with".  We don't necessarily agree that it's the "best design decision". However, it IS required if you want to comply with PCI requirements ... as imposed by credit card processing companies and other security best-practices.

**Comment by dabockster** [comment]
Thanks for the response. Would it be possible to add this reasoning to your formal documentation on zen-cart.com? All I could find on the subject was essentially "you must change the admin password every 90 days" with no reasoning on why. If it is on the site, it's highly buried.

**Comment by drbyte** [comment]
Fair point. I'll pass it along and ask someone to review it for clarity.

Also note: If your store doesn't need strict PCI compliance, you can turn off enforcement of the rule in Admin->Configuration->My Store: you'll see 2 PCI or PA-DSS settings there.
