### ISSUE TITLE
"Funky" order-totals display when coupon includes free shipping

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1463]
If a customer applies a coupon that includes a form of "free shipping" to an order with a $75.00 subtotal and $11.67 of shipping, that processing currently sets the order's shipping-cost to 0, resulting in a display similar to:
![image](https://user-images.githubusercontent.com/2685585/28491549-ca079656-6ec1-11e7-9a69-d845fa18216f.png)

I've corrected the issue for the site that "discovered" the issue by making the following change to /includes/modules/order_total/ot_coupon.php's `process` function:

```diff
      // free shipping for free shipping 'S' or percentage off and free shipping 'E' or amount off and free shipping 'O'
+      //-lat9-The coupon amount has included the shipping-cost; no need to wipe it to 0 as it results in an "off" display
-      if ($od_amount['type'] == 'S' || $od_amount['type'] == 'E' || $od_amount['type'] == 'O') $order->info['shipping_cost'] = 0;
```
... so that the display is now
![image](https://user-images.githubusercontent.com/2685585/28491561-211dcbb8-6ec2-11e7-88cf-4d8298dfb1ff.png)

Note that there are ancillary considerations that I haven't totally investigated, since the site doesn't use the associated functionality, in ot_gv.php, ot_group_pricing.php, ot_loworderfee.php and ot_shipping.php -- all based on using the admin's DTK to see where `'shipping_cost'` was used.

**Comment by scottcwilson** [comment]
Wouldn't it be better to set the sort order of shipping above the coupon so that the shipping amount would show as a charge, and then the coupon as a refund?  This seems more intuitive to me.

**Comment by lat9** [comment]
Good point, Scott.  Talk about not seeing the forest for the trees!  Closing.
