### ISSUE TITLE
Storefront: Search results in error warning ...

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1483]
Within the storefront, I searched for `test120` and received the `WARNING: An Error occurred, please refresh the page and try again.` message (the log follows).  It looks like the query-builder is using the database name as its alias but someone forgot to tell the advanced-search results page!

Shouldn't that query-builder class also have a definition for a table's alias?  I'm thinking that there is going to be a lot of plugin "breakage" if `products` table references go to `products.products` instead of the `p.products` reference that is used in the 1.5.x (and earlier) ZC versions.

> [14-Aug-2017 10:46:45 America/New_York] Request URI: /zc160/index.php?main_page=advanced_search_result&search_in_description=1&keyword=test120, IP address: ::1
> #1  trigger_error() called at [C:\xampp\htdocs\zc160\includes\classes\db\mysql\query_factory.php:171]
> #2  queryFactory->show_error() called at [C:\xampp\htdocs\zc160\includes\classes\db\mysql\query_factory.php:143]
> #3  queryFactory->set_error() called at [C:\xampp\htdocs\zc160\includes\classes\db\mysql\query_factory.php:270]
> #4  queryFactory->Execute() called at [C:\xampp\htdocs\zc160\includes\library\zencart\Paginator\src\adapters\SqlQuery.php:43]
> #5  ZenCart\Paginator\adapters\SqlQuery->getTotalItemCount() called at [C:\xampp\htdocs\zc160\includes\library\zencart\Paginator\src\AbstractAdapter.php:51]
> #6  ZenCart\Paginator\AbstractAdapter->process() called at [C:\xampp\htdocs\zc160\includes\library\zencart\Paginator\src\AbstractAdapter.php:37]
> #7  ZenCart\Paginator\AbstractAdapter->__construct() called at [C:\xampp\htdocs\zc160\includes\library\zencart\Paginator\src\Paginator.php:94]
> #8  ZenCart\Paginator\Paginator->buildAdapter() called at [C:\xampp\htdocs\zc160\includes\library\zencart\Paginator\src\Paginator.php:66]
> #9  ZenCart\Paginator\Paginator->doPagination() called at [C:\xampp\htdocs\zc160\includes\library\zencart\ListingQueryAndOutput\src\definitions\AbstractDefinition.php:182]
> #10 ZenCart\ListingQueryAndOutput\definitions\AbstractDefinition->getPaginatedResultItems() called at [C:\xampp\htdocs\zc160\includes\library\zencart\ListingQueryAndOutput\src\definitions\AbstractDefinition.php:85]
> #11 ZenCart\ListingQueryAndOutput\definitions\AbstractDefinition->processPaginatorResults() called at [C:\xampp\htdocs\zc160\includes\library\zencart\ListingQueryAndOutput\src\definitions\AbstractDefinition.php:59]
> #12 ZenCart\ListingQueryAndOutput\definitions\AbstractDefinition->buildResults() called at [C:\xampp\htdocs\zc160\includes\modules\pages\advanced_search_result\header_php.php:141]
> #13 require(C:\xampp\htdocs\zc160\includes\modules\pages\advanced_search_result\header_php.php) called at [C:\xampp\htdocs\zc160\index.php:35]
> 
> 
> [14-Aug-2017 10:46:45 America/New_York] PHP Fatal error:  1054:Unknown column 'pd.products_name' in 'where clause' :: SELECT COUNT(DISTINCT products.products_id)
> 
>                                  AS total  FROM (products AS products LEFT JOIN products_description AS products_description ON products.products_id = products_description.products_id LEFT JOIN manufacturers AS manufacturers ON products.manufacturers_id = manufacturers.manufacturers_id LEFT JOIN products_to_categories AS products_to_categories ON products.products_id = products_to_categories.products_id LEFT JOIN meta_tags_products_description AS meta_tags_products_description ON products.products_id = meta_tags_products_description.products_id ) WHERE 1 AND (products.products_status = 1  AND products_description.language_id = 1  AND (  (pd.products_name LIKE '%test120%' OR p.products_model LIKE '%test120%' OR m.manufacturers_name LIKE '%test120%'  OR (mtpd.metatags_keywords LIKE '%test120%' AND mtpd.metatags_keywords !='')  OR (mtpd.metatags_description LIKE '%test120%' AND mtpd.metatags_description !='')  OR pd.products_description LIKE '%test120%'  )  ))  ==> (as called by) C:\xampp\htdocs\zc160\includes\library\zencart\Paginator\src\adapters\SqlQuery.php on line 43 <== in C:\xampp\htdocs\zc160\includes\classes\db\mysql\query_factory.php on line 171
> 
>

**Comment by proseLA** [comment]
hi,
perhaps i'm a little confused here as to the new structure.  it seems that this fix is contained here:

includes/library/zencart/ListingQueryAndOutput/src/filters/SearchResults.php

i am not sure how that would affect old plugins.  as the table prefixes seem to be hardcoded into this script (legacy code).  which really do not seem to be needed; as far as this search goes...  although they could be added where the tables are defined in that script or even in the table definition (not sure how much that would break).

plugins that add fields would need to be updated....  but will not most plugins need update to work in v160?
