### ISSUE TITLE
CKEditor javascript not honoring class names.

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#1499]
I am working on a new layout for the product collect info page, and ran into a problem.
- Zen Cart 1.5.5e
- php 7.1.8
- jQuery 1.12.4
- CKEditor  installed

There are multiple text areas on this new page, ,and CKEditor is enabled. I do not want the editor on all text areas, so the ones that do need the editor have the class editorHook, and the ones that need plain text have noEditor.

The problem:
When the page displays all text-areas are rendered with the CKEditor. The noEditor hooks are not honored.

Temporary solution:
I removed the editorHook, and noEditor from the text-areas, and the javascript form
"admin\includes\ckeditor.php". 
The the text-areas that need the editor get the ckeditor class. (default CKEditor behaviour)
This works.

Now when other editors are installed this will offiously not work for those editors, so the javascript form
"admin\includes\ckeditor.php" needs some tuning. I do not have a fix for that yet.

**Comment by drbyte** [comment]
I'm curious why it's not working for just that page, when the `editorHook` and `noEditor` are properly honoured on other admin pages, (send email, category edit, etc).

**Comment by Zen4All** [comment]
These pages all have only one text-area per page. What I wan to achieve is something like the picture below.
![multiple text areas](https://user-images.githubusercontent.com/2766593/29740880-8df2d4a8-8a61-11e7-8e82-c9ecaf215dcd.png)

**Comment by drbyte** [comment]
I'm not sure where the problem is.

On a fresh 155 store I just cloned a language so that I have a multi-language shop. Then I edited collect_info.php to clone the description field to display twice: first with `editorHook`, and for the 2nd, with `noEditor`. It immediately treated the textarea fields properly:

<img width="621" alt="screen shot 2017-08-26 at 5 19 07 pm" src="https://user-images.githubusercontent.com/404472/29745221-fff5105e-8a82-11e7-9c94-9fce6dbbb86d.png">

**Comment by Zen4All** [comment]
Hmmm, then i will need to investigate futher.

**Comment by Zen4All** [comment]
I found the problem.
I have classes like `class="form-control editorHook"`, and `class="form-control noEditor"`. This does not work.
It only works if there is only 1 class name in the class field, like `class="editorHook"`

**Comment by drbyte** [comment]
Perhaps changing line 27 may help:

```diff
-    if ($(this).attr('class') == 'editorHook' || ($(this).attr('name') != 'message' && $(this).attr('class') != 'noEditor'))
+    if ($(this).hasClass('editorHook') || ($(this).attr('name') != 'message' && ! $(this).hasClass('noEditor')))
```

**Comment by Zen4All** [comment]
Thanks Doc, that did the job!!

**Comment by drbyte** [comment]
Great! Will wrap it into v1.5.6

**Comment by Zen4All** [comment]
👍  FYI, this is the mod I was using it for : https://github.com/Zen4All-nl/Zen-Cart-Collect-Info-Through-Tabs-In-New-Style

**Comment by drbyte** [comment]
Inspired by some of the changes I saw you had to make to do that, I've submitted a PR to split off the js for easier customizing:
https://github.com/zencart/zencart/pull/1505
