### ISSUE TITLE
What is the future of attributes_controller.php

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#1511]
I am writing a new module for Zen Cart, in which the product collect info page is completely rewritten. The data is presented in tabs, and should be more user friendly. (see: [Zen-Cart-Collect-Info-Through-Tabs-In-New-Style](https://github.com/Zen4All-nl/Zen-Cart-Collect-Info-Through-Tabs-In-New-Style)). This also brings the possibility of adding extra info/fields to the page by dropping in extra tabs to a special folder..

Which brings me to the title of this issue.

On inspecting the code of the admin/attributes_controller.php file:
- I see a lot of html errors
- The html table structure is a mess, some tags are not closed or opened, or are in the wrong location in the code.
- Use of hard-coded input fields, instead of  using the zen cart functions
- Database query's that ask for all information in a table where only 3 or 4 field of the 27 are needed.

This can easily be "repaired", but I would like to know if I should spend time on it, or wait for Zen Cart 1.6

**Comment by drbyte** [comment]
I agree: It needs some work. 
I'd welcome a PR that cleans it up a bit. 

If it's ready before the end of the month, you can PR it against the `v156` branch.

**Comment by Zen4All** [comment]
👍 I'll see what I can do

**Comment by mc12345678** [comment]
FYI, the last time I tried to correct the html validation on the admin/attributes_controller.php page for ZC 1.5.5, it broke the responsive nature of the display and pushed content out across the display instead of keeping it "tight".  At that point I didn't feel like doing a comparison between the modified version and a non-modified version to correct the associated issue(s), but look forwards to your ideas.

**Comment by Zen4All** [comment]
Well, like I said I was doing some major rework for my own module ![example](https://github.com/Zen4All-nl/Zen-Cart-Collect-Info-Through-Tabs-In-New-Style/blob/master/Documentation/images/new%20look.png), so I already located the problems 😄 .

The biggest problem is that some tables are not closed, and row are not properly opened.

**Comment by Zen4All** [comment]
This will not be ready before the end of the moth.

**Comment by Zen4All** [comment]
Looking through the file I see no way of deleting/removing a download form an attribute.
Once a file is assigned to an attribute the only way to remove it, is to delete the attribute. Leaving the filename filed empty has no effect, because there is a zen_not_null check.

I am going to change this in the update function

**Comment by Zen4All** [comment]
https://github.com/Zen4All/zencart/blob/v156_attributes_controller/admin/attributes_controller.php

**Comment by Zen4All** [comment]
@drbyte what to do with the search box on the right top of the page? when a search is performed one is redirected to the categories page. Should this box stay on the page, or can it be deleted.

**Comment by drbyte** [comment]
I believe the intention of having that box is to be able to quickly navigate to another product ... either when finished editing the attributes for the current one, or when one changes their mind and wants to navigate to something else.

Are you finding a technical challenge to keep it?

**Comment by Zen4All** [comment]
No, no problems, just wondering as I did not see a use for it . Will leave the box in place.

I am almost finished, tracking the last responsive issues.

**Comment by drbyte** [comment]
Great! Thanks!

**Comment by Zen4All** [comment]
#1531

**Comment by drbyte** [comment]
This appears to be completed.

**Comment by mc12345678** [comment]
Running into some issues with this as currently available in the 1.5.6 branch. For some reason any time I try to add an attribute to a product that does not already have attributes that either the screen refreshes to no product being selected (base display of the attributes_controller) or am advised that the item has already been added to the product and that duplicates can not be added.

Looks like products_id is not "POSTED" when adding attributes to a product (regardless of if it has/had attributes). Somewhere between line 1064 and line 2004.
