### ISSUE TITLE
zc156: Error message in admin on initial install

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1526]
I pulled a copy of the v156 branch about 1/2 hour ago and did a fresh installation.  On my first login to the admin, the front-page shows:
![image](https://user-images.githubusercontent.com/2685585/31319011-8139aba8-ac29-11e7-95d2-04d60948ab0d.png)
I'm guessing that it's because it's a fresh site, so there's no information yet collected.

**Comment by drbyte** [comment]
Good catch. Fixed.
