### ISSUE TITLE
Is the $_GET in this line ever being set/used?

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#1543]
In my mission to update various pages on the backend I came across this line of code. I can not find any use of the hidden field that is being set here, nor the $_GET['options_id_from'] being set.
https://github.com/zencart/zencart/blob/76b352a54168d90c0680af74f1b9d8f9c315bf6d/admin/options_values_manager.php#L902
So before deleting this line I would like some feedback to make sure it is safe to delete.

**Comment by drbyte** [comment]
Agreed. I believe it's safe to remove: `echo zen_draw_hidden_field('option_value_from_filter', $_GET['options_id_from']);`

**Comment by Zen4All** [comment]
Thanks
