### ISSUE TITLE
Incorrect use of logo image height and width in tpl_header.php

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#1548]
When someone wants to use 100% for the logo image size or a size larger than that of the original file, the system does not accept the input but rather uses the size of the file itself.  In fact, it may not use the settings in includes/languages/english/header.php at all.

Line 69 of includes/templates/template_default/common/tpl_header.php currently reads:
`<div id="logo"><?php echo '<a href="' . HTTP_SERVER . DIR_WS_CATALOG . '">' . zen_image($template->get_template_dir(HEADER_LOGO_IMAGE, DIR_WS_TEMPLATE, $current_page_base,'images'). '/' . HEADER_LOGO_IMAGE, HEADER_ALT_TEXT) . '</a>'; ?></div>`

In order for it to actually use the image width and height, it needs to be:
`<div id="logo"><?php echo '<a href="' . HTTP_SERVER . DIR_WS_CATALOG . '"><img src="' . DIR_WS_TEMPLATE .  'images/' . HEADER_LOGO_IMAGE . '" height="' . HEADER_LOGO_HEIGHT . '" width="'. HEADER_LOGO_WIDTH .'" alt="' . HEADER_ALT_TEXT . '" title="' . HEADER_ALT_TEXT . '"></a>' ?></div>`

The corresponding line in includes/templates/responsive_classic/common/tpl_header.php needs to be changed as well.

**Comment by drbyte** [comment]
Could it be simpler?

```diff
-    <div id="logo"><?php echo '<a href="' . HTTP_SERVER . DIR_WS_CATALOG . '">' . zen_image($template->get_template_dir(HEADER_LOGO_IMAGE, DIR_WS_TEMPLATE, $current_page_base,'images'). '/' . HEADER_LOGO_IMAGE, HEADER_ALT_TEXT) . '</a>'; ?></div>
+    <div id="logo"><?php echo '<a href="' . HTTP_SERVER . DIR_WS_CATALOG . '">' . zen_image($template->get_template_dir(HEADER_LOGO_IMAGE, DIR_WS_TEMPLATE, $current_page_base,'images'). '/' . HEADER_LOGO_IMAGE, HEADER_ALT_TEXT, HEADER_LOGO_WIDTH, HEADER_LOGO_HEIGHT) . '</a>'; ?></div>
```

**Comment by drbyte** [comment]
Could it be done simpler than that? By adding `, HEADER_LOGO_WIDTH, HEADER_LOGO_HEIGHT` params, like this:

```diff
-    <div id="logo"><?php echo '<a href="' . HTTP_SERVER . DIR_WS_CATALOG . '">' . zen_image($template->get_template_dir(HEADER_LOGO_IMAGE, DIR_WS_TEMPLATE, $current_page_base,'images'). '/' . HEADER_LOGO_IMAGE, HEADER_ALT_TEXT) . '</a>'; ?></div>
+    <div id="logo"><?php echo '<a href="' . HTTP_SERVER . DIR_WS_CATALOG . '">' . zen_image($template->get_template_dir(HEADER_LOGO_IMAGE, DIR_WS_TEMPLATE, $current_page_base,'images'). '/' . HEADER_LOGO_IMAGE, HEADER_ALT_TEXT, HEADER_LOGO_WIDTH, HEADER_LOGO_HEIGHT) . '</a>'; ?></div>
```

**Comment by dbltoe** [comment]
Yep, that works correctly with changing either or both in pixels AND either or both in percentages.
Additionally, something elsewhere is determining the height.
If I comment out the HEADER_LOGO_HEIGHT in the header.php, the system apparently sets the height in order to avoid a "warped" logo.  With every change of width value, the height value changed accordingly to maintain the image's integrity.
SO.. even `<div id="logo"><?php echo '<a href="' . HTTP_SERVER . DIR_WS_CATALOG . '">' . zen_image($template->get_template_dir(HEADER_LOGO_IMAGE, DIR_WS_TEMPLATE, $current_page_base,'images'). '/' . HEADER_LOGO_IMAGE, HEADER_ALT_TEXT, HEADER_LOGO_WIDTH) . '</a>'; ?></div>` works.

**Comment by drbyte** [comment]
Admin->Configuration->Images->Calculate Image Size is probably set to true, and may be causing that override. That setting affects the whole site though.

Probably best instead to actually use an image that's already the correct dimensions, and then it won't need to trigger resizing, and thus won't be "warped"

**Comment by dbltoe** [comment]
If I set Calculate Image Size to false, I still get the same result as if the height did not need to be there but it does.
If height is a null in the header.php or HEADER_LOGO_HEIGHT is not included in the tpl_header.php call, the header.php settings have no effect and the image remains at its original, created size regardless of the Calculate Image Size setting.
If height is any number in the header.php and HEADER_LOGO_HEIGHT is included in the tpl_header.php call, the header.php setting for width adjusts the entire image proportions to match the width setting regardless of the Calculate Image Size setting.
Changing the height settings in the header.php has not made any difference regardless of the width settings in the header.php or the Calculate Image Size being set to True or False.
Looks like best way to go is with the original suggestion by drbyte.  That will allow width settings in the header.php to actually manipulate the width.

**Comment by drbyte** [comment]
@dbltoe thanks for researching and posting your findings.
Did you want to submit a PR?  (If not, I will; but if you're comfortable with it, you may as well do it.)

**Comment by dbltoe** [comment]
Not familiar with the process and don't want to mess it up.
THANX
John

**Comment by drbyte** [comment]
Do you want to tackle it?  The process is documented here: http://docs.zen-cart.com/Contributing/main

If not, no worries, just lemme know.

**Comment by dbltoe** [comment]
It says it went.  Should I have updated the date?

Instructions at http://docs.zen-cart.com/Contributing/main/github_workflow don't match browser version.

**Comment by drbyte** [comment]
Almost. 

You did the PR against yourself, and then merged it. 
I can see how it could be confusing because the green "create pull request" button shows inside both your and the ZC repository.

After doing your commit, you were to go back to the `zencart/zencart` repository and then click the green "create pull request" button there.  And then wait for us to review it and we would merge it once approved.
