### ISSUE TITLE
V156 Obsolete code in layout_controller.php

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#1552]
I am working my way through the Layout Controller, and stumbled upon these 2 code blocks.
https://github.com/zencart/zencart/blob/cbc58dac5b7d40a3f2594f508d02c6a3ff3831e9/admin/layout_controller.php#L71-L90

https://github.com/zencart/zencart/blob/cbc58dac5b7d40a3f2594f508d02c6a3ff3831e9/admin/layout_controller.php#L260-L273

They seem to be unused. Is it safe to delete?

**Comment by drbyte** [comment]
Your observation is correct.  As far as core code goes, safe to delete.

**Comment by Zen4All** [comment]
Thanks
