### ISSUE TITLE
Mark What the Product's Meta Tag Title Should Include

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#1555]
This baffles me.
When entering data in the admin\includes\modules\product\collect_info_metatags.php

You can toggle the radiobuttons to include or exclude from the meta-tag. When setting values to exclude this is saved in the database as a 0 value (be sure to leave the input fields empty). So far all goes well.

Now re-open the page and all radio buttons are "reset" to include (value = 1), although the database contains 0 values.
The trigger for this is an if statement that checks for the meta_description and metatags_keywords being empty.
https://github.com/zencart/zencart/blob/783637669f95c66a460c348830a1da4f616c3186/admin/includes/modules/product/collect_info_metatags.php#L63-L68
What is the logic behind this? because now on screen you have other data then is in the database .

**Comment by drbyte** [comment]
If I recall correctly, this reflects the auto-calculation of metatag display on the storefront:
On the storefront, if there is no defined override text for either keyword or description, then the system (ref the metatags.php module) treats it as though there are no overrides, so all defaults are engaged. 

I believe the logic at the time was that it was foolish to be outputting empty keywords+description, so safeties were put in place to protect against that. 

And thus the checkbox behavior seen here is somewhat of a reflection of that. 

I get how it's confusing that the checkboxes don't reflect what's set in the database. 

I don't mind it being changed to have the checkboxes display what the database contains, but I guess the it's also necessary to provide some in-page messaging that explains that the checkboxes are being ignored if the keyword and description fields are both blank.

**Comment by Zen4All** [comment]
I can live with the logic 😃  We could also make sure that the database values are not written in case there are no values. And give some on screen explanation.

**Comment by drbyte** [comment]
A PR for improving consistency between display and database is welcome. ie: make display reflect what's being done to the database (not changing the database part).

**Comment by Zen4All** [comment]
I will investigate next week, and see what i van do

**Comment by Zen4All** [comment]
I am going to give this back, unless you can give me a 30 hour day 😃

**Comment by drbyte** [comment]
Haha! I completely understand!
