### ISSUE TITLE
ALL ZC versions.... change of debugging....

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#1557]
one of the issues i have with ZC is debugging.  and in looking at application_top.php, this became a little clearer to me.

if i were to set DEBUG_AUTOLOAD to true (not something one would do on a production server), why would it not just set the error_reporting on as well?  instead, i have to remember that there is another variable there called STRICT_ERROR_REPORTING and set that also to true.  why not turn that on, if DEBUG_AUTOLOAD is already set to true?

thoughts??

**Comment by drbyte** [comment]
`DEBUG_AUTOLOAD` is a very specific setting, used only for dumping out the steps processed in the autoload array, such as the init files getting loaded and some classes being instantiated. This is not the same as setting an error-reporting level. 

Let's back WAY up: what exact problem are you trying to troubleshoot when this "issue" came to mind? 
There's a whole lot of context missing here ...

**Comment by proseLA** [comment]
when i was helping a ZC user with a blank page, the problem ending up being the putenv variable.  an odd case of the server, no doubt...  my feeling is that if someone turns on debug, we should provide all messages to help with the debugging process.

in application_top.php, i would propose changing this:

`if (defined('STRICT_ERROR_REPORTING') && STRICT_ERROR_REPORTING == true) {`

to something like:

`if ((DEBUG_AUTOLOAD) || ((defined('STRICT_ERROR_REPORTING') && STRICT_ERROR_REPORTING == true))) {`

i do not think it is a big change, and, at least for me, it is easier to remember to turn one thing on, as opposed to multiple flags.

as far as context, multiple people (including me) were convinced the problem was with the configure.php script.  when i looked at that, i could not see the problem, so i turned debug on....  still a blank page...  and now i have to start adding echo statements to even see if we are hitting the script.

i suppose i could have remembered to enable STRICT_ERROR_REPORTING, and i would have seen the error, but isn't the point of debugging to see errors?  to me, turning on debugging should automatically enable error reporting.  neither value should be on for a production site, so i see little harm in the suggested change.

**Comment by drbyte** [comment]
Okay. I'd accept a PR for that. 

It's a digression from the original intent of those separate debugging settings, but I'm willing to let them converge. 

One thing that could be missed by some who use it is that if one sets `DEBUG_AUTOLOAD` to `true` in an `extra_configures` file, that won't trigger the error-reporting level change, because this change will only have that fire if `DEBUG_AUTOLOAD` is set explicitly by actually altering `application_top.php` or by adding a `local/configure.php` which contains it.

**Comment by proseLA** [comment]
ok.... on which version should i issue a PR?  i was thinking about v156...

with regards to how everything loads, and this change only working on 2 of the 3 provided scenarios, i'm comfortable with that.

**Comment by drbyte** [comment]
Yes, 156 is okay for this.
