### ISSUE TITLE
ZC160: admin/includes/admin_html_head.php is missing closing tag

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#1558]
The file admin/includes/admin_html_head.php is missing the </head> closing tag. Instead this is included in the files where admin_html_head.php is inserted in to. In my opinion it is better practice to include the closing tag in admin_html_head.php, or was there a reason not to so this.

If not, i can make a PR to "correct" this.

**Comment by drbyte** [comment]
It was intentional, so that other files can be loaded in between.

**Comment by Zen4All** [comment]
Those files would be css and js files, at least I can not think of other files.
For the css files there is already a rudimentary loader in place. The same could/should be done for js files.

**Comment by drbyte** [comment]
The intention was: 
```php
include('admin_html_head.php');
?>
<link "stylesheetXYZ.css">
<script src="some script specific to just this page.js"></script>
</head>
```

**Comment by Zen4All** [comment]
okay,

**Comment by drbyte** [comment]
That said, I do see your point, and agree that it's better to have the closing `</head>` in the same file as the opening `<head>` ... or at least not mismatched as much as this is.

While I'm open to implementing a simplified loader system, I don't want something that goes so extremely far as the rubickintegration mod did with the CSS/JS Loader mess. That's way overkill, and too complicated for most shopowners to use, let alone plugin authors and integrators/upgraders.

**Comment by Zen4All** [comment]
I totally agree that that loader is overkill. 
this is already in place
https://github.com/zencart/zencart/blob/a90bc32f284208813837a3d954f6a78dc581ecce/admin/includes/admin_html_head.php#L30-L34
and could easily be adapted for JavaScript as well.

Or, if we make it a bit more complicated we could copy the front-end loader that is used
