### ISSUE TITLE
PHP 7.2.0 (xampp)  - ZC installer says it's too old!

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#1567]
In the interests of fixing 155e problems with 7.2.0 I tried to install 156 for comparison.
Installer fails.
![clipboard01](https://user-images.githubusercontent.com/4391026/34318655-b3d19c2a-e7ce-11e7-9f3d-3f4cdcaf55d7.gif)
1.6 does not have this error.

**Comment by drbyte** [comment]
Haha! Thanks. 
Fixed in https://github.com/zencart/zencart/pull/1571
