### ISSUE TITLE
Double "time zone" displayed

### ISSUE THREAD

**Issue by syntaxerror** [zencart/zencart#1570]
https://github.com/zencart/zencart/blob/d36d7d3621552d3840fb9bedd653413c8cc9dabb/admin/includes/header.php#L179

Not a big issue, but this line causes a double "time zone" to be displayed in admin header. It seems to be included in the language string already through the %X, for non English locales like t.ex. nb_NO:

https://github.com/zencart/zencart/blob/v156/admin/includes/languages/english.php#L31

It's displayed as:
> 14.22 **+0100 +0100** GMT

Linux box running PHP 5.6 and UTF-8

**Comment by syntaxerror** [comment]
I choose to close it, as it can be fixed through language files, t.ex. by replacing %X with %T.
Still I'm not sure why this one needed its own string, and it's missing or not changed in quite a few language packs.

**Comment by drbyte** [comment]
Ya, I was just looking in an english-only site, and it doesn't do that doubling. 
So, ya, it must be specific to the language packs. Thanks for pointing it out.

<img width="346" alt="screen shot 2017-12-27 at 1 22 09 pm" src="https://user-images.githubusercontent.com/404472/34390664-2e79aa60-eb0f-11e7-8282-177444f206a0.png">
