### ISSUE TITLE
ZC 156/160: Refactoring admin categories / products and listing page

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#1583]
What is your opinion on refactoring admin categories / products and listing page?
Currently we have:
- admin/categories.php
- admin/product.php
- admin/includes/modules/category_product_listing.php
These files share code, contain duplicate (unused) code,

I propose to make the listing a separate page and not a module file. this would mean moving it to the admin folder form includes/modules.
code will need to be moved around between the three file, but will make it much easier to find and modify things in the future.

**Comment by drbyte** [comment]
No objection here.  Those pages do need an overhaul.

Keep in mind there are multiple product types supported, so consideration should be given there too.

**Comment by Zen4All** [comment]
Ok, i'll get to it. Yes I will remember product types. I was working on a way to eliminate the need for new files for each product type, but that is a long way from being ready.

**Comment by drbyte** [comment]
> I was working on a way to eliminate the need for new files for each product type

Thumbs up 👍 to that!

The product-free-shipping was only added as an example of how to slightly clone the product-general for some customization.
The others serve similarly.
But it's definitely long overdue for a simpler way to have multiple types without so much annoying duplication! (and so many near-duplicate files in core code, and having to be handled during upgrades, and for some plugins, etc etc).

**Comment by Zen4All** [comment]
The setup I am testing right now is:
- Put all fields in a database table
- connect these fields to a product type
- read the fields from the database
- build a screen dynamically, according to the fields that are connected to a specific product type.

This setup works, and gives a nice clean file. The "problem", you need to put a lot of info per field in the database. The advantage is, adding new fields is childs play, using a simple screen interface.

But all this if for later.
First things first

**Comment by drbyte** [comment]
Oh. You mean having a database of database field names/types/constraints/etc?
Definitely pros and cons with that.

**Comment by Zen4All** [comment]
Yes exactly
![product_fields](https://user-images.githubusercontent.com/2766593/34512919-a008c2aa-f065-11e7-97bf-a707fc503182.png)

**Comment by drbyte** [comment]
k - may require some metrics testing, since it forces db integrity to be handled by code instead of by the db, which can cause performance issues. It also introduces reporting challenges. 
Not opposed to it, just aware that it'll need to be treated carefully. 

As you said, it's a separate project.

**Comment by Zen4All** [comment]
Nothing's final yet. It started out with a simple table, but go tout of hand rather quickly 😆 . An other possibility for defines etc is to use a file-based system, but I have to investigate on that.

**Comment by drbyte** [comment]
👍 
Probably worth starting a separate issue for discussing all those aspects.

**Comment by drbyte** [comment]
... but even that isn't urgent.

First things first ;)

**Comment by Zen4All** [comment]
Will be submitting a pr soon.
I eliminated a lot of unused code blocks, some block were present 3 times in various files 😱 .
Modernized the look and feel.

updated:
- [x] categories
- [x] product info
- [x] category/product listing
- [ ] product metatags
- [ ] category metatags

The need for a product type "product.php" file is eliminated. So for example "music_product.php" can be deleted, but files like "collect_info.php" are still used in the "old way".

**Comment by proseLA** [comment]
1. i am a fan of redoing.  i think the ability to define additional fields for a product from within ZC (and not some plugin) is great.  definitely adds a layer of complexity for store owners, but i'm in favor.
2. i have recently updated a clients version of search in the product listing and found it to be much more useful. i think it is something that should be incorporated as well...  code basically breaks search into separate words as opposed to complete phrase, ie:

```    
    $parts = explode(" ", trim(zen_db_input($_GET['search'])));
    $sql = '';
    foreach ($parts as $k => $v) {
        $sql_add = " pd.products_name like '%:part%' ";  
        if ($k != 0) {
            $sql_add = ' and ' . $sql_add;
        }
        $sql_add = $db->bindVars($sql_add, ':part', $v, 'noquotestring');
        $sql = $sql . $sql_add;
    };
    if (!empty($sql)) {
        $sql = (" and (" . $sql . ") ");
    }
```
this just constructs the search part of the product sql.  now i have created it using a function, and if we wanted to use the 3 current search fields (model, name, and description), we could call the function with each field name as a variable to search all 3 fields with an or between them.

just a thought, as single word searching seems to be more useful than searching for a phrase.

**Comment by Zen4All** [comment]
@proseLA I like the idea of your search function, but am not going to implement it in this PR, because it is already complicated enough. You could also make a PR yourself.

**Comment by proseLA** [comment]
i'll look into doing a PR after yours.  i'm also looking into combining functions from the catalog and admin side to eliminate some of the duplicate code.  this search function is a classic example of something that should be available on both the admin and catalog side.

**Comment by drbyte** [comment]
@proseLA wrote:
> i'll look into doing a PR after yours. i'm also looking into combining functions from the catalog and admin side to eliminate some of the duplicate code.

NOTE: There was a massive consolidation done between admin/catalog in v160 already.

**Comment by proseLA** [comment]
thanks. 

i heard that classes were consolidated but that functions were still being worked on. 

in any event, i’m sure i will see consolidation work once i tackle this issue.  no worries.

**Comment by drbyte** [comment]
@Zen4All according to your checkboxes it's just language files that are still outstanding?
Is that accurate?

**Comment by Zen4All** [comment]
I think all was done, but will check, and let you know.

**Comment by Zen4All** [comment]
This can be closed. I checked the language defines, and could not find any missing.
