### ISSUE TITLE
admin customers addresses popup link, cosmetic change

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#1585]
In the customers listing., when the customer has multiple addresses, all of 
"| 1 of 2"
is made into a link including the separator, rather than just the "1 of 2" or perhaps just the "2" as would be expected.
This is due to the constant TEXT_INFO_ADDRESS_BOOK_COUNT containing the separator
`define('TEXT_INFO_ADDRESS_BOOK_COUNT', ' | 1 of  ');`

corresponding line in customers.php:
`<td class="dataTableContent" align="right"><?php echo $customer['customers_id'] . ($zc_address_book_count == 1 ? TEXT_INFO_ADDRESS_BOOK_COUNT . $zc_address_book_count : '<a href="' . zen_admin_href_link(FILENAME_CUSTOMERS, 'action=list_addresses' . '&cID=' . $customer['customers_id'] . ($page > 0 ? '&page=' . $page : '')) . '">' . TEXT_INFO_ADDRESS_BOOK_COUNT . $zc_address_book_count . '</a>'); ?></td>`

**Comment by drbyte** [comment]
Am I correct in reading this that you're recommending the pipe (`|`) symbol be made something separate?

**Comment by torvista** [comment]
Yes. It is always there and is not language dependant.

**Comment by drbyte** [comment]
Closed via PR #1767
