### ISSUE TITLE
Remove filenames to hardcode

### ISSUE THREAD

**Issue by drillsar** [zencart/zencart#1594]
I think this will be an improvement. I can do this if approved. Thanks

**Comment by drbyte** [comment]
Your request/proposal is not clear. What are you talking about?

**Comment by drillsar** [comment]
define('FILENAME_ACCOUNT', 'account');

Make it account and get rid of filenames.php

**Comment by drillsar** [comment]
That’s one example

**Comment by drbyte** [comment]
Why will this be an improvement? What problem does such a change solve for you?

**Comment by drillsar** [comment]
When you do a module less files you have to edit, etc. Cleaner code in my opinion.

**Comment by scottcwilson** [comment]
This ticket should be closed.  Some mods redefine these values and shouldn't need to do it in multiple places.  The existing infrastructure for file name definition works and does not need to  be changed.
