### ISSUE TITLE
V156 geo_zones.php bug

### ISSUE THREAD

**Issue by drillsar** [zencart/zencart#1599]
I am going to look into this but confirmed bug in version 156. When you try to add a zone it don't do anything.

**Comment by drillsar** [comment]
Not sure what is wrong.

**Comment by drbyte** [comment]
First step is to confirm whether the same problem existed in v1.5.5

**Comment by drillsar** [comment]
I checked that uploaded it from v155 and works. I will check to see if I can find problem later today.

**Comment by drillsar** [comment]
@drbyte ok this line is the problem 

V156 Code:
`$contents = array('form' => zen_draw_form('zones', FILENAME_GEO_ZONES, 'zpage=' . $_GET['zpage'] . '&zID=' . $_GET['zID'] . '&action=insert_zone', 'class="form-horizontal"'));`

V155 code:
` $contents = array('form' => zen_draw_form('zones', FILENAME_GEO_ZONES, 'zpage=' . $_GET['zpage'] . '&zID=' . $_GET['zID'] . '&action=insert_zone'));`

Also tax_rates.php has same issue probably same thing above. Not sure what change supposed to be here

**Comment by Zen4All** [comment]
It is not the form-horizontal class, but a missing parameter in the form function. I'll pr the fix today, as it was i who introduced this bug 😊 .

**Comment by Zen4All** [comment]
#1602
