### ISSUE TITLE
zc156: Additional order-related fields

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1600]
The current DB-updates include some additional order fields to make it easier to "re-construct" the order in the admin.

> # Add fields for easier order reconstruction/edit
> ALTER TABLE orders ADD order_weight FLOAT NOT NULL DEFAULT '0';
> ALTER TABLE orders MODIFY shipping_method VARCHAR(255) NOT NULL DEFAULT '';
> ALTER TABLE orders MODIFY order_total decimal(15,4) default NULL;
> ALTER TABLE orders MODIFY order_tax decimal(15,4) default NULL;
> 
> ALTER TABLE orders_products ADD products_weight float NOT NULL default '0';
> ALTER TABLE orders_products ADD products_virtual tinyint( 1 ) NOT NULL default '0';
> ALTER TABLE orders_products ADD product_is_always_free_shipping tinyint( 1 ) NOT NULL default '0';
> ALTER TABLE orders_products ADD products_quantity_order_min float NOT NULL default '1';
> ALTER TABLE orders_products ADD products_quantity_order_units float NOT NULL default '1';
> ALTER TABLE orders_products ADD products_quantity_order_max float NOT NULL default '0';
> ALTER TABLE orders_products ADD products_quantity_mixed tinyint( 1 ) NOT NULL default '0';
> ALTER TABLE orders_products ADD products_mixed_discount_quantity tinyint( 1 ) NOT NULL default '1';
> ALTER TABLE orders_products_download ADD products_attributes_id int( 11 ) NOT NULL default '0';

Having these newly-added fields default to a particular value is not going to help, since any order-reconstruction won't know the difference between a pre-existing order where those fields have been defaulted (i.e. those values don't "count") and a newly-generated order where those fields' values do count.

Might I suggest instead:

> # Add fields for easier order reconstruction/edit
> ALTER TABLE orders ADD order_weight FLOAT **default NULL**;
> ALTER TABLE orders MODIFY shipping_method VARCHAR(255) NOT NULL DEFAULT '';
> ALTER TABLE orders MODIFY order_total decimal(15,4) default NULL;
> ALTER TABLE orders MODIFY order_tax decimal(15,4) default NULL;
> 
> ALTER TABLE orders_products ADD products_weight float **default NULL**;
> ALTER TABLE orders_products ADD products_virtual tinyint( 1 ) **default NULL**;
> ALTER TABLE orders_products ADD product_is_always_free_shipping tinyint( 1 ) **default NULL**;
> ALTER TABLE orders_products ADD products_quantity_order_min float **default NULL**;
> ALTER TABLE orders_products ADD products_quantity_order_units float **default NULL**;
> ALTER TABLE orders_products ADD products_quantity_order_max float **default NULL**;
> ALTER TABLE orders_products ADD products_quantity_mixed tinyint( 1 ) **default NULL**;
> ALTER TABLE orders_products ADD products_mixed_discount_quantity tinyint( 1 ) **default NULL**;
> ALTER TABLE orders_products_download ADD products_attributes_id int( 11 ) **default NULL**;

**Comment by drbyte** [comment]
Really good point.
And even the `shipping_method` could actually allow NULL , and default to it as well.
