### ISSUE TITLE
[v156] Is this code block ever used?

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#1605]
I took products price manager as an example, but there are multiple files using this block of code. This code is supposed to set the products_filter variable, but after much testing I only can one case.

This is when you select a category without a product. But then this query seems useless to me, because it is returning an empty result,and will not set the product_filter with a products_id.
Maybe it was used in the days when categories could have both products and sub categories.

https://github.com/zencart/zencart/blob/420eade88d9cff4a9c846da00574c4d30c799b02/admin/products_price_manager.php#L28-L86

**Comment by drbyte** [comment]
I wonder if part of this was incompletely-sanitized at one point? 
In this particular case, the `$products_id` and `$current_category_id` are also set to an integer value before your highlighted section ever runs ... meaning the compare against `!= ''` in the 2nd and 3rd `if` statements will never be truthy, so those variants will never fire. 
Granted, it's using a loose-comparison (`==`) and not strict (`===`) so its results are a bit undefined. 

If you change those `if` comparisons to compare against `0` and run tests again, I'm guessing you'll still have the same results. In which case I have no objection to removal.  At the very least these 3 identical queries (save for 1 $var change beforehand) could be collapsed.

**Comment by Zen4All** [comment]
I am going to leave this code intact for now, as i do not have the time to investigate right now
