### ISSUE TITLE
[v156] Admin UI: products not allowed to be selected

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#1606]
I took products price manager as an example, but there are multiple files using this block of code. 
Apparently it is not allowed to select products that can not be added to cart. i do not see the logic behind this, as those product can have a price, but you are just not able to add them to your cart.

https://github.com/zencart/zencart/blob/420eade88d9cff4a9c846da00574c4d30c799b02/admin/products_price_manager.php#L349-L357

**Comment by drbyte** [comment]
I tend to agree.

Would be good to test removal on a large diverse product db.;
As you know, some of these files contain code that wasn't removed during an old refactor.  In situations like these I'm always trying to find the place where it *is* used, as a determiner to whether the other places are actually obsoleted.

**Comment by drbyte** [comment]
A PR is welcome.

**Comment by Zen4All** [comment]
I'll look at it next week
