### ISSUE TITLE
init_templates.php

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#1616]
i was hating the admin title in v155, and thought i would look into changing it for v160; and it looks like it was already done!  that said, i'm not sure if it is worth it, but the code on line could be changed from:

`$pagename = preg_replace('/\.php$/', '', basename($PHP_SELF));`

to 

`$pagename = basename($PHP_SELF, '.php');`

a bit cleaner IMHO, but a very minor detail.  i am also a big fan of breaking out the html header as currently done in v160.

**Comment by drbyte** [comment]
👍 Good point.  Feel free to submit a PR.

**Comment by proseLA** [comment]
ok.

there are also a few instances of this (or something similar):

`if (basename($PHP_SELF) == FILENAME_DEFAULT . '.php') {`

which could be moved to:

`if (basename($PHP_SELF, '.php') == FILENAME_DEFAULT) {`

not sure if that is clearer/better or not.  leave well enough alone there?  or include those as well?  i see maybe four instances of that change; all on the admin side.

**Comment by jsteggy** [comment]
That change also means the FILENAME_DEFAULT would need to change too. yes?

**Comment by proseLA** [comment]
no.  that is incorrect.  in the first if statement, we are concatenating  FILENAME_DEFAULT with .php and then comparing it to basename($PHP_SELF); in the second if statement, the function basename removes the .php from the $PHP_SELF, if there, and then we compare to FILENAME_DEFAULT.

i am not sure which way is easier to read/understand; nor which uses less CPU resources.  but there is NO change to logic or variables.  at least as far as i can tell/intend.
