### ISSUE TITLE
paypal express and micropayments.

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#1618]
includes/modules/payment/paypal/paypal_curl.php:526

AMT does not look to be part of paypal express.  i recommended a hack as seen in the code here:

https://www.zen-cart.com/showthread.php?223396-can-t-switch-between-PayPal-and-Micropayments-accounts&p=1341528#post1341528

in thinking about it, i'm not sure it is better to add the AMT field in the express module.  not sure if that will get sent to paypal or not.  as i have not really done much work with paypal.  

to me, it makes sense to provide support for all paypal modules for micropayments.

thoughts?

**Comment by drbyte** [comment]
Yes, I'm okay with your proposed code change.
