### ISSUE TITLE
1.6: admin index page crashes when second language installed

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#1620]
I installed my Github spanish pack for 1.6 testing.
All the other admin pages work but on the admin index changing to either language causes a debug.

> [01-Feb-2018 11:56:20 Europe/Madrid] Request URI: /zencart-160/admin1/?cmd=&language=en, IP address: 127.0.0.1
> #1  require() called at [....zencart-160\admin1\index.php:35]
> 
> [01-Feb-2018 11:56:20 Europe/Madrid] PHP Warning:  require(.php): failed to open stream: No such file or directory in ....zencart-160\admin1\index.php on line 35
> [01-Feb-2018 11:56:20 Europe/Madrid] PHP Fatal error:  require(): Failed opening required '.php' (include_path='C:\xampp.7.1.12\php\PEAR') in ....zencart-160\admin1\index.php on line 35

**Comment by drbyte** [comment]
Do you mind testing this small change? 

/admin/index.php, line 13:
```diff
-$cmd = isset($_GET['cmd']) ? $_GET['cmd'] : 'index';
+$cmd = ! empty($_GET['cmd']) ? $_GET['cmd'] : 'index';
```

**Comment by torvista** [comment]
That seems to have fixed the problem.
