### ISSUE TITLE
Drop support for IE6 and 7

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#1638]
Do we really still need to support ie6. It is only available for Windows XP, and then people can and should already have installed IE8.
https://github.com/zencart/zencart/blob/dc14d064758b95e470f7ceb1c972e33a5a499ab1/includes/modules/pages/download/header_php.php#L183-L200

**Comment by barco57** [comment]
Personally, I would drop support for IE6. In PCI compliant environments, 2018 is the year of "break all the things" being that in June TLS1.0 and TLS1.1 gets turned off and older IE browsers on older Windows versions will no longer be able to connect to websites where TLS1.2 only is used. We have one server that is already TLS1.2 only and have already experienced issues with Outlook on older Windows OS as Microsoft thought it was a good idea to hook their apps so tightly to the OS it is the OS that is the problem with the old browsers making TLS1.2 connection for either Outlook or IE. The fix on older windows versions is to switch to firefox or chrome and Thunderbird for email support with TLS1.2
The list of problem children browser/OS versions:
IE 6 / XP
IE 7 / Vista
IE 8 / XP
IE 8-10 / Win 7

**Comment by drbyte** [comment]
Point taken. 

However, I suspect there are other far more crucial places to consider browser version support than in this code segment.  ie: merely removing lines 186-187 doesn't "really" completely "drop support for IE6 & 7". It merely ignores caching-commonalities when serving downloadable files.

**Comment by Zen4All** [comment]
There probably are, but this piece of code came under my attention during one of the recent commits.

**Comment by dakanji** [comment]
I am sure it is known but worth mentioning that there is a big difference between not supporting something and hunting through code to break support for it.

Dropping support for IE6 is fine but this should simply be a case of not specifically writing new code to cater for it. Doesn't need rooting through the code to specifically break support.

**Comment by drbyte** [comment]
For future development we indeed will not code for supporting older browsers. 

A PR for removing the IE6/IE7 entries in the download header_php.php would be acceptable.

**Comment by Zen4All** [comment]
I am going to leave this task to someone else
