### ISSUE TITLE
zc156/zc160: Admin customers.php notifiers mismatch

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1651]
In reviewing the `/admin/customers.php` notifiers used by various plugins, I've found some discrepancies between the v156 and v160 versions of the module:

| zc156 | zc160 | notifier "name | Notes |
| :-----: | :-----: | -------------- | ---- |
| &check; | &cross; | NOTIFY_ADMIN_CUSTOMERS_LIST_ADDRESSES | &nbsp; |
| &check; | &cross; | NOTIFY_ADMIN_CUSTOMERS_UPDATE_VALIDATE | &nbsp; |
| &check; | &cross; | NOTIFY_ADMIN_CUSTOMERS_B4_ADDRESS_UPDATE | &nbsp; |
| &cross; | &check; | ADMIN_CUSTOMER_UPDATE | &nbsp; |
| &check; | &cross; | NOTIFIER_ADMIN_ZEN_CUSTOMERS_DELETE_CONFIRM | &nbsp; |
| &check; | &cross; | NOTIFY_ADMIN_CUSTOMERS_CUSTOMER_EDIT | &nbsp; |
| &check; | &cross; | NOTIFY_ADMIN_CUSTOMERS_LISTING_HEADER | &nbsp; |
| &check; | &cross; | NOTIFY_ADMIN_CUSTOMERS_LISTING_NEW_FIELDS | &nbsp; |
| &check; | &cross; | NOTIFY_ADMIN_CUSTOMERS_LISTING_ELEMENT | &nbsp; |
| &check; | &check; | NOTIFY_ADMIN_CUSTOMERS_MENU_BUTTONS | *Match* |
| &check; | &check; | NOTIFY_ADMIN_CUSTOMERS_MENU_BUTTONS_END | *Match* |

These need to be aligned as more and more plugins are making use of the notification subsystem to enable a more seamless upgrade experience for store owners.

**Comment by scottcwilson** [comment]
Looks like the only one that still needs to be done is NOTIFY_ADMIN_CUSTOMERS_LIST_ADDRESSES.

**Comment by drbyte** [comment]
Done.
