### ISSUE TITLE
Tools->Server/Version Info:  phpinfo has been disabled for security reasons ...

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1660]
I've only come across this on one hosted site, but it's possible for the `phpinfo` function, used by `admin/server_info.php` to be disabled via the php.ini `disable_functions` directive.  When that's the case a PHP warning is thrown and logged and (surprise!) no PHP-related information is displayed.

Perhaps, in that condition, the subject tool should display a notification of the disablement and fall back to at least displaying the PHP version (as returned by `phpversion`).

**Comment by scottcwilson** [comment]
```
$dis = ini_get('disable_functions');
if (strpos($dis,"phpinfo") !== false) die("You will need to migrate to a real hoster");
```

**Comment by proseLA** [comment]
while your die message may seem funny, i think it's of more value to provide a meaningful message referencing the disabled function in php.ini.

**Comment by scottcwilson** [comment]
Not really intended to be funny.  Hosters who randomly disable things to provide "security" are clueless.

**Comment by drbyte** [comment]
Done
