### ISSUE TITLE
Create Account - Put Country before Province

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#1665]
At the moment, the layout demands the customer fills in a province field with text, and then selects the country.
If a province is defined for that country, after the initial submission the form is spat back with an error requiring the province to be selected from the list. This seems pretty poor GUI to me.
Putting the country prior to the province is the minimum, but in my opinion it should be at the start, before the name, as the first thing in the address fieldset, to provide the province dropdown in the first instance.
I have had this layout since day one as I also use that country selection to define country-specific postcode and tax id checks on the form.

**Comment by drbyte** [comment]
Would you like to submit a PR?

**Comment by torvista** [comment]
Yes, but I'll never get round to it, it implies getting to grips with Github properly and I have too much fire fighting to do in the real (not virtual) world to do that at midnight when I have "spare" time.

**Comment by torvista** [comment]
based on 1.56 or 1.6?

**Comment by scottcwilson** [comment]
Created #1741.

**Comment by drbyte** [comment]
Closed via PR #1741

**Comment by scottcwilson** [comment]
This hasn't been actually closed yet.
