### ISSUE TITLE
ZC156 Inconstancy in install and upgrade script

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#1666]
Today I was uograding a 1.5.5f test shop to 1.5.6. Allwent fine until I tried to login to the admin again.
I got an error, telling me the session table did not exist.

Looking at the database in phpmyadmin I saw the table was indeed missing. I opened the upgrade.sql, and saw this query
https://github.com/zencart/zencart/blob/8100fcb709853a0e4bf668dfb2c9e28adf3b329d/zc_install/sql/updates/mysql_upgrade_zencart_156.sql#L153-L160
copy/paste to phpmyadmin and I get this error

> Error
>SQL query:
>
>
>CREATE TABLE sessions (
>  sesskey varchar(256) default NULL,
>  expiry int(11) unsigned NOT NULL default 0,
>  value mediumblob NOT NULL,
>  PRIMARY KEY  (sesskey)
>) ENGINE=InnoDB
>MySQL said: Documentation
>
> 1171 - All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead

But I remember installing a fresh 156 shop went fine. Also the InnoDB looked strange, as this used to be MyISAM
checking the install script revealed the same query, but I know older versions of Zen Cart had
```
CREATE TABLE sessions (
  sesskey varchar(255) NOT NULL default '',
  expiry int(11) unsigned NOT NULL default '0',
  value mediumblob NOT NULL,
  PRIMARY KEY  (sesskey)
) ENGINE=MyISAM;
```
My solution for now is to change
>sesskey varchar(256) default NULL,

to

>sesskey varchar(255) NOT NULL default '',

to make it work, but there may be a better solution

**Comment by torvista** [comment]
maybe it's related to this
https://github.com/zencart/zencart/pull/1596

**Comment by Zen4All** [comment]
@torvista Thanks, I know that thread, but i don't think it is the same, as it has nothing to do with the length of the field. The field length is a limitation in earlier mysql versions

I think it has to do with tring to set the field default to NULL, which is not possible if the key has to be unique. It is the same as trying to set the default to somting like 'hello', or '0'.

Some additional info from my server setup:
>Database server:
Server: Localhost via UNIX socket
Server type: MySQL
Server version: 5.7.21-0ubuntu0.16.04.1 - (Ubuntu)
Protocol version: 10
Server charset: UTF-8 Unicode (utf8)

>Web server:
Apache
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 7.0.29-1+ubuntu16.04.1+deb.sury.org+1

**Comment by drbyte** [comment]
>  i don't think it is the same, as it has nothing to do with the length of the field. The field length is a limitation in earlier mysql versions
I think it has to do with trying to set the field default to NULL, which is not possible if the key has to be unique. 

You are correct: it is because the default is being set to NULL. But the reason for using NULL was inspired by the utf8mb4 index length issues required in newer MySQL versions. 


I know the whos_online which also uses the sesskey value needs to be treated similarly to the sessions table. But whos_online can get empty values, whereas the sessions table normally shouldn't store empty records. So at the application level there is some syncing to manage.

But you're reporting a schema issue, before the application layer.
I'm surprised that the testing of these changes didn't flag up this issue. Maybe MariaDB is more forgiving?

**Comment by torvista** [comment]
Still an issue.
I tried selecting the installer to use utf8 instead of default mb4, but it still would not create the sessions table.
xampp windows 10, 10.1.29-MariaDB, php 7.1.2.

**Comment by torvista** [comment]
tried again with xampp 10.1.32-MariaDB, php 7.1.17. Still failed to create the sessions table.

**Comment by drbyte** [comment]
Fixed by https://github.com/zencart/zencart/commit/a4beff5d9a2add48470224c8812639d0440039ef
