### ISSUE TITLE
Search Sidebox: A non well formed numeric value encountered

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1691]
```
PHP Notice:  A non well formed numeric value encountered in C:\xampp\htdocs\zc156\includes\templates\template_default\sideboxes\tpl_search.php on line 18
```
It's complaining about the use of `$column_width` which reflects the value present in **Configuration->Layout Settings->Column Width - Right/Left Boxes**; the default value is `150px`, which is not a valid numeric value.

**Comment by drbyte** [comment]
Resolved by https://github.com/drbyte/zencart/commit/48cafc403b5338cc88dcd5908a3cf8a471376bb3
