### ISSUE TITLE
zc156: create_account/jscript_form_check.php check_state error

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#1696]
in
includes/modules/pages/create_account/jscript_form_check.php
there is 
```
  check_state(<?php echo (int)ENTRY_STATE_MIN_LENGTH . ', "' . ENTRY_STATE_ERROR . '", "' . ENTRY_STATE_ERROR_SELECT; ?>");
```
I think the closing php tag and quotation marks are wrong:
```
  check_state(<?php echo (int)ENTRY_STATE_MIN_LENGTH . ', "' . ENTRY_STATE_ERROR . '", "' . ENTRY_STATE_ERROR_SELECT . '"'; ?>);
```

**Comment by drbyte** [comment]
I agree.
Other `jscript_form_check.php` files appear to be wrong too.

It's been like that since v1.3.9 !

**Comment by torvista** [comment]
Triple word score for me then!

**Comment by dakanji** [comment]
Same in the jscript_main.php files too. Will push the fix.
