### ISSUE TITLE
PHP Warning thrown during admin currency_cron processing

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1697]
I'm seeing the following logged each time the /admin/currency_cron.php script runs:
```
PHP Warning:  include(/site_root/admin/includes/languages/english): failed to open stream: No such file or directory in /site_root/admin/includes/init_includes/init_languages.php on line 38
```
That comes from the following code-block
```php
// include the language translations
  require(DIR_WS_LANGUAGES . $_SESSION['language'] . '.php');
  $current_page = basename($PHP_SELF);
  if (file_exists(DIR_WS_LANGUAGES . $_SESSION['language'] . '/' . $current_page)) {
    include(DIR_WS_LANGUAGES . $_SESSION['language'] . '/' . $current_page);
  }
```
... where line 38 is that last `include`.  The issue's root-cause is the fact that `$current_page` isn't defined during that cron processing, so the `file_exists` function's return is based on the existence of the language **directory**, not a **file**.

The issue can be corrected by using `is_file` instead of `file_exists`.

**Comment by drbyte** [comment]
I suspect setting `$PHP_SELF` in `currency_cron.php` may also resolve it:

```php
$PHP_SELF = __FILE__;
```

Granted, perhaps `is_file` may be a more universal fix.

**Comment by lat9** [comment]
Which one do you prefer?  I'm staging a PR to use `is_file` right now.
