### ISSUE TITLE
suggestion:  my account, newsletter preferences, update stays on same page

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#1704]
At the moment, updating the subscription preference takes the user back to the My Account page with a messagestack confirmation. It seems more intuitive to me, for the update page to be shown again with the new status, thereby confirming it. 
Personally I have a second tick box for another consent (for an email mod asking their opinion 3 weeks after the sale), so that reinforces for me that that page should show the status after the update.

**Comment by drbyte** [comment]
A PR is welcome

**Comment by drbyte** [comment]
Closed by PR #1772
