### ISSUE TITLE
Handling of jQuery inclusion in responsive_classic

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1713]
The newer responsive_classic pulls in jQuery using basically the same technique as template_default: try to pull from the CDN, and if that doesn't work, pull it from the local jscript directory.

However, the code in responsive classic produces: 

`<script type="text/javascript">window.jQuery \|\| document.write(unescape('%3Cscript type="text/javascript" src="includes/templates/responsive_classic/jscript/jquery.min.js"%3E%3C/script%3E'));</script>`
 
which would fail by default, since this file does not exist.  Should we: 

a) Simply change this code to pull the file from template_default, where it *does* exist.
b) Keep this logic in case someone wants to locally update responsive_classic, but add an inclusion from template_default if this fails. 

I'd be happy to do a PR for either once a decision is made.

**Comment by drbyte** [comment]
I think just ensuring that the `includes/templates/responsive_classic/jscript/jquery.min.js` file exists is sufficient.

**Comment by scottcwilson** [comment]
PR submitted. ( #1714 )  oops got the number wrong.

**Comment by scottcwilson** [comment]
Oh I also didn't see your i.e. statement - I just check and move on to template default.  I don't think we want to be maintaining this file in multiple places.
