### ISSUE TITLE
Is the final_price selection still needed in ./index_filters/default_filter.php ?

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1719]
It seems like this could be removed with no ill effect and reduce the number of joins (since TABLE_SPECIALS would no longer be needed).

**Comment by drbyte** [comment]
I'm all for optimizing, but I'm not understanding the context of your question. Can you share how you arrived at this question?

Also, if `final_price` is removed, then it would seem `specials_new_products_price` would need removal too else the join would still have to happen.

**Comment by scottcwilson** [comment]
I was looking at doing a pricing mod, and I found this query.

**Comment by drbyte** [comment]
Were `final_price` and `specials_new_products_price` unused in the query results you were parsing?

**Comment by scottcwilson** [comment]
It would need more thorough testing, and there's a template dependency of course, but in my testing it seemed not to cause harm to remove these fields.

**Comment by proseLA** [comment]
i have removed the TABLE_SPECIALS from said script on a heavily modified test site with no ill effect.  i have tested price sorting on a search sub-set of products that included special prices and the sorting worked fine.  again, my site is heavily modified, so i can not speak for all sites, but on first look, i think this is a good catch by scott, and we could safely remove the join.

if we are looking at filters for searching and joins to reduce overhead, i'm curious if future development allows a user to create additional fields for a particular chosen product type and then allows for searching/filtering on those specified fields, as well as removing existing fields for searching/filtering?  this is an area where i have to do extensive customization in the past.

**Comment by drbyte** [comment]
Feel free to submit a PR for this change.

**Comment by scottcwilson** [comment]
The advantage of removing this is offset by the disadvantage of breaking templates which permit sorting by price, so we should probably leave it  be.  Closing as a suggestion only applicable to some shops.
