### ISSUE TITLE
1.6 installer: Fatal error: Unable to parse TEXT_ERROR_ADMIN_CONFIGURE in systemChecks.yml

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#1721]
Windows, xampp, php 7.2.6
On first entry into the installer it chokes.
I'm leaving the debug as is, since I think the relevant bit is stack trace 3: it shows the require path has double slashes for some reason and so I assume not loading application_top

`[06-Jul-2018 09:22:20 Europe/Madrid] PHP Warning:  Use of undefined constant TEXT_ERROR_ADMIN_CONFIGURE - assumed 'TEXT_ERROR_ADMIN_CONFIGURE' (this will throw an Error in a future version of PHP) in D:\Documents\Dropbox\Dev\public_html\zencart-develop\zc_install\includes\systemChecks.yml on line 12
[06-Jul-2018 09:22:20 Europe/Madrid] PHP Fatal error:  Uncaught InvalidArgumentException: Unable to parse file "D:\Documents\Dropbox\Dev\public_html\zencart-develop\zc_install\includes/systemChecks.yml": Unable to parse line 14 (TEXT_ERROR_ADMIN_CONFIGURE). in D:\Documents\Dropbox\Dev\public_html\zencart-develop\zc_install\includes\vendors\yaml\lib\class.sfYaml.php:101
Stack trace:
#0 D:\Documents\Dropbox\Dev\public_html\zencart-develop\zc_install\includes\classes\class.systemChecker.php(20): sfYaml::load('#\r\n# @package I...')
#1 D:\Documents\Dropbox\Dev\public_html\zencart-develop\zc_install\includes\modules\pages\index\header_php.php(23): systemChecker->__construct('admin')
#2 D:\Documents\Dropbox\Dev\public_html\zencart-develop\zc_install\index.php(34): require('D:\\Documents\\Dr...')
#3 {main}
  thrown in D:\Documents\Dropbox\Dev\public_html\zencart-develop\zc_install\includes\vendors\yaml\lib\class.sfYaml.php on line 101`

**Comment by drbyte** [comment]
Yes, since the admin config file is no longer needed or provided, the installer shouldn't be testing for it, and also there's no longer any associated error message for it.
