### ISSUE TITLE
156 installer: no message when database credentials are incorrect

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#1722]
Windows, xampp, php 7.2.6
In the installer, enter database credentials.
If any of the username, password or db name are wrong/the db does not exist, there is no error message (there is a debug).
Pressing "Continue" just seems (to the user) to not work at all.

**Comment by scottcwilson** [comment]
Try merging my PR and see  if it fixes it; I noticed the code was just looking at one specific error type so I made it more general.

**Comment by scottcwilson** [comment]
When I say "my PR" I mean this: https://github.com/zencart/zencart/pull/1739

**Comment by drbyte** [comment]
Closed by fix in #1739

**Comment by torvista** [comment]
Window 10, xampp php 7.3.4

156b installer
with incorrect db password: no GUI error message, only a debug.

**Comment by drbyte** [comment]
I get this:
<img width="1049" alt="Screen Shot 2019-05-27 at 2 09 00 PM" src="https://user-images.githubusercontent.com/404472/58434313-0a1c1c00-8089-11e9-876a-6f11cb8b15ca.png">

**Comment by torvista** [comment]
I've tried xampp phps back to 5.6, Chrome, FF, Edge.
All the same: no console errors, no popups blocked, nothing not found on the F12 network tab.

This is accessed using a virtual host at:
https://www.dev.test/zencart-156b/zc_install/index.php
the certificate is self-signed and triggers a warning on the first access, but once accepted, no more errors.

On the network tab, ajaxTestDBConnection.php runs and the exact response is this, including the leading br.

`<br />
<b>Warning</b>:  mysqli_connect(): (HY000/1045): Access denied for user 'baduser'@'localhost' (using password: YES) in <b>D:\Documents\Dropbox\Dev\public_html\zencart-156b\includes\classes\db\mysql\query_factory.php</b> on line <b>102</b><br />
{"error":true,"errorList":{"runLevel":"database","errorLevel":"FAIL","mainErrorText":"Problems with Database Connection","methods":{"checkNewDBConnection":null},"extraErrors":["1045:Access denied for user 'baduser'@'localhost' (using password: YES)"]}}`

I've no doubt it is my local environment, but still, I'd like to know why. Dropbox and antivirus are switched off for this test.

**Comment by torvista** [comment]
anything else I can do to debug this?

**Comment by zcwilt** [comment]
So I guess the main thing that stands out is that ajaxTestDBConnection.php is returning mixed content.
i.e. html & json, when it should only be retuning json. The fact that it is returning html will cause the popup to fail.

Have you set your environment or altered code to display warnings etc.

**Comment by torvista** [comment]
You mean all this stuff should not be coming back;
`<br /> <b>Warning</b>: mysqli_connect(): (HY000/1045): Access denied for user 'baduser'@'localhost' (using password: YES) in <b>D:\Documents\Dropbox\Dev\public_html\zencart-156b\includes\classes\db\mysql\query_factory.php</b> on line <b>102</b><br /> `

**Comment by zcwilt** [comment]
No it shouldn't.
While the application_top for the installer does set 

    error_reporting(E_ALL);

By default it also sets 

    @ini_set('display_errors', 0);

So not sure why you would be getting the errors being displayed/returned by the ajax call.

**Comment by torvista** [comment]
I found that in my virtual hosts configuration was this:
php_admin_flag display_errors on

This would not allow any local script to override it, so setting display_errors to false never worked.
This was the setting that caused the html to be returned with the json.

**Comment by zcwilt** [comment]
Thanks for the update.
