### ISSUE TITLE
Zencart with Docker

### ISSUE THREAD

**Issue by lunf** [zencart/zencart#1732]
Hi all,

I am looking for official Zen Cart docker image and I could not find one. I am hoping that you are going to support Docker in the recent future.

Thank you,

**Comment by drbyte** [comment]
Hi,
There is not currently an official Zen Cart docker image.
However, the requirements are simple, so combining necessary images is relatively straightforward.
See 
http://www.zen-cart.com/content.php?48-what-are-the-server-requirements-to-run-zen-cart

**Comment by zcwilt** [comment]
Just a note here. I've recently started using docker over my previous vagrant set up for development.
I'm working up some documentation for this.

**Comment by barco57** [comment]
I wait with bated breath for documentation to see how you setup docker.

**Comment by zcwilt** [comment]
Zen Cart and Docker
===================

While there is no official Docker image to use with Zen Cart, we can leverage other projects to achieve this.

Personally I use laradock and while this was built to run Laravel code it can also be used for Zen Cart.

First you need to install docker & docker-compose 

see

https://docs.docker.com/install/
https://docs.docker.com/compose/install/

Then follow the instructions for installing laradock (basically a matter of cloning their repository and creating an initial .env file)

See http://laradock.io/

Edit the .env file
------------------

set the `APP_CODE_PATH_HOST`

I usually have a common directory where I store my apps/sites

e.g. `/home/USERNAME/development`

and under this may have 

`/home/USERNAME/development/v156`

`/home/USERNAME/development/mysite`

`/home/USERNAME/development/laravelapp`

etc.

So in this case I would set 

`APP_CODE_PATH_HOST=/home/USERNAME/development`

For now you can leave all the other .env settings as is.

Create an nginx .conf file
--------------------------

Before starting docker, we need to create a `.conf` file for nginx.

Within the directory that you cloned the laradock code, there will be an nginx/sites directory.

In that directory we will create an nginx conf file. This should be named for the site you are creating 
i.e. If your site is called zcv156, create a file called `zcv156.conf`

The .conf file should look like 

    server {
    
        listen 80;
    
        # For https
         listen 443 ssl;
         ssl_certificate /etc/nginx/ssl/default.crt;
         ssl_certificate_key /etc/nginx/ssl/default.key;
    
        server_name zcv156.test;
        root /var/www/zcv156;
        index index.php index.html index.htm;
    
        location / {
             try_files $uri $uri/ /index.php?$query_string;
        }
    
        location ~ \.php$ {
            try_files $uri /index.php =404;
            fastcgi_pass php-upstream;
            fastcgi_index index.php;
            fastcgi_buffers 16 16k;
            fastcgi_buffer_size 32k;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            #fixes timeouts
            fastcgi_read_timeout 600;
            include fastcgi_params;
        }
    
        location ~ /\.ht {
            deny all;
        }
    
        location /.well-known/acme-challenge/ {
            root /var/www/letsencrypt/;
            log_not_found off;
        }
    
        error_log /var/log/nginx/zcv156_error.log;
        access_log /var/log/nginx/zcv156_access.log;
    }

remeber to cusomize 

 - server_name
 - root note the root should be `/var/www/YOUR_SITE`, where `YOUR_SITE` is the same name as the directory in `APP_CODE_PATH_HOST` e.g `/var/www/zcv156`
 - error_log
 - access_log

based on your server

At this point you will also need to edit your `/etc/hosts` file 

You will need to add an entry that looks like

`127.0.0.1 zcv156.test`

You now have to decide which services you want docker to start, to serve your Zen Cart app.

For simplicity, we are going to use nginx as the http server and mariadb for the database.

There are some problems using apache2 as the http server and mysql as the database server that I haven't figured out yet, but will update when I do.

You can now use docker-compose to start your container

e.g. 

`docker-compose up -d nginx mariadb adminer`

Running this command can take some time initially as the containers are built, but will be much faster subsequently.

Adminer
-------

The docker-compose command above starts up a container running `Adminer`

`Adminer` is a light weight replacement for `phpmyadin` and can be accessed through the browser using `localhost:8080`
 

Zen Cart Database Settings
--------------------------

Unlike normal installs of Zen Cart the DB_SERVER is not set to 'localhost' or '127.0.0.1' 

Instead it is set to the name of the docker container name for the db server.

Given we are using mariadb the DB_SERVER should be 

`define('DB_SERVER', 'mariadb');`

and the credentails should be 

`define('DB_SERVER_USERNAME', 'root');`

`define('DB_SERVER_PASSWORD', 'root');`

@todo
-----

 - Server logs 

 - How to run multiple php versions

 - How to run multiple docker installs
 
 - better ssl configuration

**Comment by zcwilt** [comment]
Another option is http://devilbox.org which I've been playing around with.
Advantages over `laradock` are 

 - Simpler setup for Zen Cart
 - Integrate front page giving access to lots of tools
 - Uses `Mailhog` which allows for capture/inspection of emails sent from Zen Cart
 - Better integration of phpMyAdmin
 - Can still support other frameworks like Laravel etc.
  
Will write up some docs for this as well.
