### ISSUE TITLE
v156 New product not added to correct category

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#1736]
@Zen4All,
 
With the new edited categories/products code somewhere before or near the commit: https://github.com/zencart/zencart/commit/2e7ddadcb9fe4e67d4130906f6aac6772d357e2b
it appears that if have navigated to a category then selected to add a product, the product ends up being added to the root of the store rather than the current category.  It must then be moved to the desired category to place it where desired.

Historically, once a user has navigated to a category and then selects to add a product, the category at that point becomes the master category for the product.  That does not appear to be happening now.

**Comment by Zen4All** [comment]
I'll take a look at it this week

**Comment by Zen4All** [comment]
@mc12345678 
Found the culprit. The category is passed to the new product collectinfo page, but is not put in to the correct variable. Thus losing the value.
In trying to correct this issue I found some more inconsistencies, having to do with $_POST and $_GET values. This means the solution will take a bit more time.

**Comment by drbyte** [comment]
Closed via #1737
