### ISSUE TITLE
v156: Include base AJAX processing in the admin?

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1738]
Is it time to update the admin to use the base AJAX processing that's included in the storefront?  

I'm thinking that an `/admin/ajax.php` would `require` the version in the storefront root, the admin header would require the storefront `/includes/template_default/jscript/jscript_framework.php` and the admin's `classes` directory would now include an `ajax` sub-directory ... mimicking the storefront behavior.

**Comment by drbyte** [comment]
How about a counter-proposal of consolidating all the admin-side classes/functions into the catalog-side? 
(ie: isn't your reason for wanting the admin accessible by ajax really a desire to gain access to those classes/functions anyway?)

**Comment by lat9** [comment]
My main reason for suggesting the AJAX inclusion on the admin is to update some of the admin-level handling with processing similar to that on the storefront.  I appreciate the security that's built into that storefront processing and wanted to have a "good" baseline for plugin and/or core changes in the admin going forward.

**Comment by drbyte** [comment]
Can you give some examples of things you're thinking of updating?

**Comment by lat9** [comment]
I'm working on a plugin (don't yet know whether it's going to be free or commercial) that enables Wordpress-like tags for products.  I've got AJAX processing on the admin's categories/products edit pages where those tags are added and/or removed from the database via AJAX calls when a button or link is clicked.

About the only thing I needed to change on the /admin/ajax.php was the base directory (DIR_FS_ADMIN vs. DIR_FS_CATALOG) through which the ajax-handler classes are located.

**Comment by drbyte** [comment]
Is it possible to keep all these files on the catalog-side, and not in the "admin" folder structure?

I'd prefer to avoid duplicate code that needs separate maintenance.

I guess the main problem might be that if your ajax script relies on cookies being included, then at least the admin folder needs an ajax handler file; but everything else could be left in the catalog classes/functions structure.

**Comment by drbyte** [comment]
(Speaking of product tags, whatcha think of #954 ? :) )

**Comment by lat9** [comment]
So, like many of the "shared" admin/storefront scripts, would the admin version do a `require` of the storefront version?  Would the potentially admin-only AJAX handlers live in `includes/classes/ajax` or `YOUR_ADMIN/includes/classes/ajax`?

The change that I've made for this handling also modifies the admin's `init_admin_auth.php` to return an AJAX `logged_out` error if the page-load was requested via AJAX but an admin's not currently logged in.

**Comment by drbyte** [comment]
I envision all the code living in catalog `/includes/` structure. The point of this is so that eventually all code can be in just `/includes/`, and the "admin" directory would only be for UI stuff as much as possible. Like with the v2/160/develop code where we moved (almost) all admin functions/classes to catalog-side, this begins to make a proper api-harness possible. 

In looking at the code, I concede that one may need to copy `/ajax.php` to `/admin/ajax.php`, but after that there shouldn't need to be much admin-side code added.

**Comment by lat9** [comment]
I'll also note that the `ajax.php` modules filename is not defined in (er) `/includes/filenames.php`.

**Comment by drbyte** [comment]
> I'll also note that the ajax.php modules filename is not defined in (er) /includes/filenames.php.

Is that something that really needs defining? ie: likely to be altered application-wide?

Or is your point inspired more from "breaking pattern", esp for zen_href_link() calls etc?

**Comment by lat9** [comment]
Right on the use for the zen_href_link calls.

Can the assumption be made that the admin directory is always a first-level subdirectory of the store's file-system?  Since the `ajax.php` processing is a pseudo- `index.php`, it's pulling in the application_top processing, so that `DIR_FS_CATALOG` is unknown on initial entry.

I'm thinking that the /admin/ajax.php should simply `require '../ajax.php`, but don't know what (if anything) that will break.

**Comment by drbyte** [comment]
> Can the assumption be made that the admin directory is always a first-level subdirectory of the store's file-system?

Yes, that's reasonable.

**Comment by lat9** [comment]
Questions, questions ... should the zc156 admin's `includes/javascript_loader.php` pull in the `jscript_framework.php`?  If so, should that module always be pulled from the storefront's `includes/templates/template_default/jscript` directory?

**Comment by drbyte** [comment]
I hadn't thought about pulling it from `javascript_loader`, but it seems sensible.

Yes. I think it's safer to pull it specifically from `template_default` (and not some other template) since it's pretty reasonable to expect it to be the "most current" (as provided for/by ZC anyway).

**Comment by lat9** [comment]
I should have a PR ready later today.

**Comment by lat9** [comment]
Arggh, compatibility with the admin logout processing, I received
```
{"error":"logged_out","redirect":"http:\/\/localhost\/zc156\/pincH-ael-prEss\/login.php"}
```
on the screen on an admin session timeout.

**Comment by drbyte** [comment]
Closed by PR #1795

**Comment by Zen4All** [comment]
I Just used admin Ajax on an addon I am making for 1.5.6 and it works like a dream 🎉 🤗

**Comment by Zen4All** [comment]
Just for my information, and may others, but this also means yo need to use front end functions and classes in the ajax class file, right?

**Comment by lat9** [comment]
Not if the AJAX file is intended strictly for the admin environment!  The admin version of the `config.core.php`, which is run as part of the AJAX initialization, brings in (er) the base admin files.

**Comment by lat9** [comment]
Note that this issue should be reopened.  @Zen4All's comment (which I had "ignored") was spot-on.  Any AJAX invoked on the admin side is now bringing in the _**storefront**_ application_top.php, which is not desired behavior.
