### ISSUE TITLE
Use of includes/local/configure.php fails on initial db create in 1.5.6 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1744]
In 1.5.5 and below, I could create the file includes/local/configure.php as follows: 

```
<?php
define('ADMIN_BLOCK_WARNING_OVERRIDE', '1');
```

It seems like this doesn't work anymore.  When the database issue described in #1740 is fixed, I'll try again and gather more details if I can't fix it at that time.

**Comment by scottcwilson** [comment]
OK.  Let me look around to see if any documentation needs to be updated because I could swear that I learned this from reading documentation.

**Comment by drbyte** [comment]
#1740 resolved.

**Comment by scottcwilson** [comment]
> the dev- prefix is already .gitignored

This was true in 160 but not 156. Just added a PR.

**Comment by drbyte** [comment]
merged

**Comment by scottcwilson** [comment]
For those who may be looking at this in the future: the file I created was: 
includes/extra_configures/dev-override_admin_rename_dialog.php

with the contents: 
```
<?php
define('ADMIN_BLOCK_WARNING_OVERRIDE', '1');
```
