### ISSUE TITLE
v156 When adding a non-basic product can not preview info.

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#1747]
@Zen4All 
 Changes made to support #1736 did not fully resolve the ability to add product to the starting category for product that are not the default general product.  

Now, after filling in information about the product and attempting to select the preview button, the form attempts to load the product type admin file for the chosen product type which has been removed from the overall fileset.

In each product type's `collect_info.php` file, recommend changing `$type_handler` to `FILENAME_PRODUCT` in the new_product zen_draw_form located at or around line 168.

**Comment by Zen4All** [comment]
I'll take a look at it

**Comment by drbyte** [comment]
Is this resolved now that the PR is merged?
