### ISSUE TITLE
Products All and New Products issues on max display per page

### ISSUE THREAD

**Issue by ajeh** [zencart/zencart#175]
Products All products_all no longer uses MAX_DISPLAY_PRODUCTS_ALL to set the number of Products per page.

New Products products_new no longer uses MAX_DISPLAY_PRODUCTS_NEW to set the number of Products per page.

Products listing, New Products, Specials, Featured and All Products each have a separate setting for how many to display per page.

**Comment by drbyte** [comment]
@ajeh Is this still an issue? Or was it resolved with the ListingBox code changes?

**Comment by ajeh** [comment]
And silly things like the Product Description length and such :)

**Comment by ajeh** [comment]
I am going to really have to go through this one more time as I am pretty sure a couple are out of place. It is a little dizzying matching up the counts.

**Comment by drbyte** [comment]
Is it really necessary to have separate counts?  It's just as dizzying for the end-user having to set everything separately when I can't see any universally-relevant need to have so many unused options.

IMO for the 0.05% chance that someone needs separate granular control, they can change it in PHP.

**Comment by ajeh** [comment]
MAX_DISPLAY_SPECIAL_PRODUCTS_INDEX - Specials Page
MAX_DISPLAY_SPECIAL_PRODUCTS - Specials Listing box 
MAX_RANDOM_SELECT_SPECIALS - Specials Sidebox

MAX_DISPLAY_PRODUCTS_NEW - New Products Page
MAX_DISPLAY_NEW_PRODUCTS - New Listing box
MAX_RANDOM_SELECT_NEW - New Sidebox

MAX_DISPLAY_PRODUCTS_FEATURED_PRODUCTS - Featured Page
MAX_DISPLAY_SEARCH_RESULTS_FEATURED - Featured Listing Box
MAX_RANDOM_SELECT_FEATURED_PRODUCTS - Featured Sidebox

MAX_DISPLAY_PRODUCTS_ALL - All Products Page

MAX_DISPLAY_UPCOMING_PRODUCTS - Upcoming Listing Box

MAX_DISPLAY_NEW_REVIEWS - Reviews Pages
MAX_RANDOM_SELECT_REVIEWS - Reviews Sidebox


PRODUCT_LISTING_DEFAULT_SORT_ORDER - Product Listing Sort Order
PRODUCT_LIST_DESCRIPTION - Product Listing Product Description length

PRODUCT_NEW_LIST_SORT_DEFAULT - New Product Listing Sort Order
PRODUCT_NEW_LIST_DESCRIPTION - New Listing Product Description length

PRODUCT_FEATURED_LIST_SORT_DEFAULT - Featured Listing Sort Order
PRODUCT_FEATURED_LIST_DESCRIPTION - Featured Listing Product Description length

PRODUCT_ALL_LIST_SORT_DEFAULT - All Products Listing Sort Order
PRODUCT_ALL_LIST_DESCRIPTION - All Products Listing Product Description length


Specials Page needs to use MAX_DISPLAY_SPECIAL_PRODUCTS
Product Listing Sort Order not used and need new define like Featured - PRODUCT_LISTING_DEFAULT_SORT_ORDER
Specials Sort Order not defined using - PRODUCT_SPECIALS_LIST_SORT_DEFAULT

New Page, Featured Page and All Page not using Product Description lengths

I think this covers it all.

**Comment by scottcwilson** [comment]
Guys, what's the decision on this?  Chris, were you leaning towards one set of constants?  If so I'd be happy to do this if you will write up the requirements.

**Comment by drbyte** [comment]
Initially we need to just link up all the new listingBox things to each of the respective constants' values.

@zcwilt is going to look into that.

**Comment by scottcwilson** [comment]
This looks as though it might be complete -  the 'pagination' settings I see in various definitions match the constants shown above.
