### ISSUE TITLE
Search: should it use OR? or AND?

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#1770]
i was looking at searching after #1583 got closed and the discussion there.

in playing with the search function, it seems that we are constructing default searches with an `or` as opposed to an `and`.  and i think that is wrong.

for example, if one searched for `pan red`; we would return all pans as well as all red socks, red kittens, red shoes, etc.  

i think we should only return those items where both search terms exist in the fields that we are searching.  i think using `or` in this situation is wrong.  but that is just my opinion, so i am curious what other people think.

a.) multiple search terms in a search should return only those items where all search terms exist;

versus

b.) multiple search terms should return any items where at least one search term exists.

currently, v160 is doing b.) and i think we should be doing a.)

thoughts?

**Comment by proseLA** [comment]
@drbyte do you not know this section of the code well?  this is rather silly to me....  and frankly i burned a bunch of time figuring this out....  as i suppose i am not that familiar with the code....

ADVANCED_SEARCH_DEFAULT_OPERATOR

determines the default.  no idea that constant exists; and i suppose that is why no one really commented on this issue.  feel free to close this unless you feel some other discussion is needed on it.

**Comment by drbyte** [comment]
You said "i am curious what other people think". In my experience if I'm the first to chime in then others hold back. So I chose to wait and let others speak.

But if you've determined that no discussion is needed because the app already provides the ability to self-determine how it is implemented, then I agree it makes sense to close it.

`Admin->Configuration->My Store->Default Search Operator` (defaults to 'and')

**Comment by proseLA** [comment]
indeed it does....

`INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) VALUES ('Default Search Operator', 'ADVANCED_SEARCH_DEFAULT_OPERATOR', 'and', 'Default search operators', '1', '17', 'zen_cfg_select_option(array(\'and\', \'or\'), ', now());`

philosophically, i'm not sure i agree with a var that is only used in 1 function; and that can be overridden based on input.  ie, it is set to `and`  but searching for `red or kitten` would override it to `or`.  but i digress, and i will now cease on this issue.
