### ISSUE TITLE
New install css is broken

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#1776]
When doing a new  install I do not include the docs folder.
This breaks the new layout for the install pages, as it refers to the css files in the docs folder.

**Comment by drbyte** [comment]
I've found occasionally in some environments that I need to use `/zc_install/` with the trailing `/` instead of just `/zc_install` else the CSS doesn't load.

But using the CSS from the docs folder is news to me. Will investigate.

**Comment by Zen4All** [comment]
Did some investigating myself, and found it is the  tpl_zc_install_suggested_default.php that is referring to 
"./docs/zen.css"

**Comment by drbyte** [comment]
Ah, okay. 
That's probably an unexpected side-effect of the PR'd changes to the docs files.
A fix is welcome, else I'll look into it maybe next week.

**Comment by drbyte** [comment]
Closed by #1777
