### ISSUE TITLE
Discussion: Stop making configure.php read-only?

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#184]
In modern-day hosting configurations, is it really beneficial to set configure.php to read-only anymore?

Isn't it more of a nuisance, rather than actually providing any meaningful security anymore? 

It was originally implemented to protect (somewhat) against world-writable folder problems on servers built using last decade's defaults.

Is it really needed anymore? 

(Since ZC v1.3.0 any click catalog-side has automatically attempted to set configure.php to read-only if it was found to be writable (based on whatever the SAPI was configured for)).

I'm proposing this is no longer necessary, and I think removing it would make the end-user more pleasant.

Are there any known common hosting configurations where this is highly likely to be problematic? If so, please explain, along with references if possible.

**Comment by scottcwilson** [comment]
I agree with @lhungil 's first point - prevents accidental override of my local configuration vs live site configuration.

**Comment by drbyte** [comment]
Lots of good suggestions here. Some ought to be posted as separate `issues`
