### ISSUE TITLE
Latest release and PHP 5 end of service

### ISSUE THREAD

**Issue by jeyca** [zencart/zencart#1841]
The lateste release 1.5.5f is is only compatible with PHP5.6

> NOTE: v1.5.5f is NOT compatible with PHP 7.2 ... it will trigger dozens of "warnings about undefined constants"

but PHP 5 support will end on december 31st, so is ZenCart v2 released before end of the year? Or does latest version of ZenCart work mostly with PHP5.6 and will just throw warnings?

**Comment by Zen4All** [comment]
Zen Cart 1.5.5f is compatible with php versions up to 7.1

**Comment by jeyca** [comment]
ah ok, just for 7.2 its not, ok

**Comment by Zen4All** [comment]
no, but keep a close eye on zen cart 1.5.6, as that will work with php 7.2
