### ISSUE TITLE
Possible change to admin/orders.php notifications?

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1858]
After pushing that header-notification update for #1853, it occurred to me that the current interfaces used for the `NOTIFY_ADMIN_ORDERS_LIST_EXTRA_COLUMN_HEADING` and `NOTIFY_ADMIN_ORDERS_LIST_EXTRA_COLUMN_DATA` notifications make them very version-dependent.

I was looking to incorporate, for instance, back into zc155f, but that version of `orders.php` is a table-based rendering while the zc156 (and presumably follow-on versions) use a div-based display.

Would you accept a PR to make those notifications more future-proofed?

**Comment by drbyte** [comment]
By future-proofing, do you mean rearranging where they're situated?

**Comment by lat9** [comment]
I mean that instead of a "blast" notification, where the observer echoes out content, to expect an array back so that the (presumed) tabular data is styled (i.e. table vs. div) in the manner that's currently being used by the _Customers->Orders_ page's listing display.

**Comment by drbyte** [comment]
That's a much bigger overhaul, but I agree it's more efficient and makes more sense.

**Comment by lat9** [comment]
I'll get a PR staged later today.

**Comment by lat9** [comment]
There you go!
