### ISSUE TITLE
Specials date validation fails to work

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1970]
Javascript errors occur when entering invalid dates by typing into a date field. 

<img width="1333" alt="screen shot 2018-12-23 at 2 46 29 pm" src="https://user-images.githubusercontent.com/4391638/50387041-ab114000-06c1-11e9-9cd9-977f39374490.png">

**Comment by drbyte** [comment]
Is this new to v1.5.6?

**Comment by scottcwilson** [comment]
Yes.  Fine in 1.5.5.

**Comment by scottcwilson** [comment]
Argh, I'm sorry that's not true.  It *was* a bug in 1.5.5 as well - I just didn't notice it.

**Comment by scottcwilson** [comment]
The date validation seems not to work at all.  If you type 13/25/2018 in one of the dates and press update, it gives you a log and a white page.  I have submitted a fix for this.

**Comment by scottcwilson** [comment]
Fixed by #1978 except for Products Price Manager.  New issue #1982 opened for that work. 
Please close this ticket.
