### ISSUE TITLE
v156 Categories do not indicate status of included product

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#1979]
Perhaps this is an operator error issue that I haven't identified yet, but noticed today while navigating the new ZC 1.5.6 catalog->categories/products menus that there does not appear to be any indication of the number of product that are contained within a category and/or the status of them being active.

In ZC 1.5.5 and below, there was an indicator something like x of y product active. I haven't yet searched for an admin operator to turn it on/off or if the code even supports that, but didn't recall seeing anything new in the install/upgrade script to account for that and currently don't see that data (viewed originally on a desktop).

**Comment by scottcwilson** [comment]
Seems ok to me: 

<img width="1745" alt="cat_counts" src="https://user-images.githubusercontent.com/4391638/50388640-9eeda880-06ea-11e9-85ed-3ead2a28952c.png">

**Comment by mc12345678** [comment]
Based on that feedback, I went back to look at the source code. Even though this time it was from my mobile, I could see that the information is there, but css had hidden it.  

I'll have to go back to my desktop to see if the screen has been zoomed in or what the resolution is.  

Unfortunately, I don't find that hiding such already minimal information an improvement in the usefulness of the administration. There is an improvement that one doesn't have to "scroll" left and right within the "frame" that is created, but as has been done in so many of the "mobile/tablet" implementations there is no way to back out and get a more desktop view.

As to the presence of the Quantity header, that too was hidden, showing a mobile view of just the Category's id, Categories/Products, Status button, and the buttons that follow to address the category.

**Comment by mc12345678** [comment]
Well, like said in the onset, basically operator error.  Had Microsoft Edge zoomed in to 120% (not on purpose, just one of those things that happened at some point while using the keyboard and mouse).  

When I backed it off to at most 110% (didn't try to determine the exact percentage break), the remaining text was restored to the screen.  Ahh well...  

May have to go find the boundaries for all that occurring and make my own changes.

**Comment by scottcwilson** [comment]
Did you want to close this issue then?

**Comment by proseLA** [comment]
scott, please close this issue.  operator errors (which we all do) should not, in my mind, necessitate the opening of an issue.

**Comment by scottcwilson** [comment]
I don't have close authority.  @mc12345678  please close.

**Comment by drbyte** [comment]
It might be prudent to make those display at the 1024 breakpoint so that people on smaller devices could at least flip to landscape mode in order to see those extra columns, even if only for reference.

But the more I think about it the more I think it needs a broader re-analysis before making such changes.
