### ISSUE TITLE
v156 problem with zen_draw_form functiom

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#1988]
ok, i am looking to test v156 code.  first off, i am seeing a lot of admin functions/classes that are including the same from the customer facing side.  THANK YOU!

admin/includes/functions/html_output.php

is not one of them.  in looking at the code, for zen_draw_form, this makes little sense to me:

```////
// Output a form
  function zen_draw_form($name, $action, $parameters = '', $method = 'post', $params = '', $usessl = 'false') {
    $form = '<form name="' . zen_output_string($name) . '" action="';
    if (zen_not_null($parameters)) {
      if ($usessl) {
        $form .= zen_href_link($action, $parameters, 'NONSSL');
      } else {
        $form .= zen_href_link($action, $parameters, 'NONSSL');
      }
    } else {
      if ($usessl) {
        $form .= zen_href_link($action, '', 'NONSSL');
      } else {
        $form .= zen_href_link($action, '', 'NONSSL');
      }
    }
```
it seems the $usessl is not doing anything.  it looks to be fixed in the develop branch, although it still accepts the $usessl variable as an input and proceeds to do nothing with it.  probably to prevent plugins from breaking.   

not sure if you want to do anything to address it for a 'lettered' fix for v156 or not; if so, i can do a PR.

best.

**Comment by drbyte** [comment]
We can't remove it as a parameter passed to the function.
But a PR which removes the unnecessary `if ($usessl)` conditions is fine.
