### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by keneso9** [zencart/zencart#1994]
Hi
Not an issue, rather a feature that needs (imho) to be added to the cart, as there are lots of European users, and I'd guess some extra European who do business in Europe as well.
I think this should be part of the cart without the need of plugin.
Apologies if this is not the place for such suggestions, in case please disregard, and discard.
Thank you

**Comment by wiztechinc** [comment]
Even though it's now just Europe, this kind of thing is probably in the future for the US as well. Let's get ahead of the game and stay ahead on privacy issues please.

**Comment by jsteggy** [comment]
@wiztechnic California passed its own version of data protection in 2018 going to effect in 2020. [https://searx.me/?q=california%20data%20protection%20law&categories=general](https://searx.me/?q=california%20data%20protection%20law&categories=general) Seems likely that more states will pass some kind of data protection law, which only complicates meeting requirements.

**Comment by lat9** [comment]
I'll toss my two-cents in here.  If we only bake things that are used _everywhere_, why is there `Configuration->Regulations`?  Why do we have downloadable products, since not every store uses that feature?

EU stores, I believe, reflect a large portion of the Zen Cart base and, as @wiztechnic and @jsteggy indicated, the future for the US is looming.

**Comment by wiztechinc** [comment]
The freebie mod developed by our friends in England actually doesn't make intense changes. I do not see why this can't be added in with appropriate toggles. I do think an explanation is also required and I'll be glad to write up such. I can't do much with coding at this point but writing is something I can do easily.  As far as meeting requirements, I think this is taken care of - it's doubtful that other countries will go past the European rules and there's is only one thing lacking in the free mod that should be there (and is in their paid version) that requires more coding. The other issue is about deleting a person's data. This is probably always going to be problematic and don't suggest going there with anything in zen cart. I really don't see this as much of an add really.

**Comment by keneso9** [comment]
> there's is only one thing lacking in the free mod that should be there (and is in their paid version) that requires more coding.

I am using the attached js, with language  extra_defines, although I believe with the fine coders here it can be made in better way.
[jscript_fz-gdpr.zip](https://github.com/zencart/zencart/files/2721150/jscript_fz-gdpr.zip)

**Comment by wiztechinc** [comment]
@keneso9 That's a clean solution but only for cookies I gather? https://www.zen-cart.com/showthread.php?222981-General-Data-Protection-Rules

**Comment by keneso9** [comment]
@wiztechinc Yes, it has settings for 3 types: statistics, marketing, preferences, with the latter being the default, and the other two optional.
Optimally the choice should be registered for future reference, and actually disabling the third party cookies for marketing, and statistics.
OT (kinda)
I've seen many - even big - sites that have implemented it in a very loose way, and instead of using the explicit opt-in, they use the opt-out, which basically nobody does, as we just click ok, and some make the banner disappear as soon as you navigate the page/site, which in my understanding should not be possible before explicit opt-in.

**Comment by torvista** [comment]
As part of my implementation of GDPR/deleting customer details on request, I have modified delete customer to obfuscate customer personal details ("deleted by request") rather than delete the records completely, thereby maintaining the audit trail with their orders and not leave undocumented "holes" in the database.
Would this be accepted as a PR?

**Comment by drbyte** [comment]
> As part of my implementation of GDPR/deleting customer details on request, I have modified delete customer to obfuscate customer personal details ("deleted by request") rather than delete the records completely, thereby maintaining the audit trail with their orders and not leave undocumented "holes" in the database.
> Would this be accepted as a PR?

While it's only *one* part of GDPR, it would be good to implement. 
I'd entertain a PR for review.

**Comment by torvista** [comment]
Regarding order details:
As far as I believe, order data including personal details should be retained for a specific period for accounting purposes dependent on local laws, for example 7 years.
So, as far as GDPR goes, if someone wants all their records deleted, you'd need to delete their customer data immediately, and their order details 7 years later! Implying that a date_deleted field should be added into the customers_info table to facilitate that!

For this PR I'm just going to deal with the personal data as a first step: the above needs much more clarification.

**Comment by drbyte** [comment]
Implemented in v158:
<img width="392" alt="Forget Customer" src="https://user-images.githubusercontent.com/404472/100905151-b9fbf200-3495-11eb-88bc-0c540d954d27.png">

Thanks to torvista for some of the code.

**Comment by scottcwilson** [comment]
GDPR experts: Is the change mentioned above by @drbyte sufficient?  Not sure what more would need to be done.

**Comment by torvista** [comment]
As far as obfuscating/deleting customer data, yes I think so. As far as ZC meeting GDPR. no not at all.
I think somewhere there needs to be available a collaborative specification/workflow defined regarding all aspects of handling customer data, that people can review/flesh out with what they have already implemented/learn from other's solutions, to arrive at a consensus of what is needed first. Something that does not develop into a serial post discussion as per this thread with no end or collating of ideas. Such a spec. probably already exists elsewhere for other platforms..?

**Comment by scottcwilson** [comment]
This work is going to have to be done as a plugin.  We just don't have the capacity to do this.
