### ISSUE TITLE
v2 EZ Pages Admin needs to look in new table for pages_title 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1999]
Order by clauses use pages_title which is no longer in ezpages table.   Currently using this page (Admin->Tools->EZ-Pages) gives a white screen. 

[01-Jan-2019 13:32:21 America/New_York] PHP Fatal error:  1054:Unknown column 'pages_title' in 'order clause' :: select * from ezpages order by toc_chapter, toc_sort_order, pages_title limit 0, 20 ==> (as called by) /Users/scott/Sites/demo_160/admin/ezpages.php on line 520 <== in /Users/scott/Sites/demo_160/includes/classes/db/mysql/query_factory.php on line 171

**Comment by scottcwilson** [comment]
You should merge pull request 2000 before attempting to fix this.

**Comment by drbyte** [comment]
Reminder: "No Longer Works" is basically NEVER descriptive of the real problem. Please remember to use meaningful titles in Issues and in PRs.

Also, while I'm at it, PR titles are used for preparing changelog documents, so "Fixes #123456" in a PR title is useless, and makes documenting things harder.

**Comment by drbyte** [comment]
To clarify: 
The "Fixes #123456" text for a PR should go in the body message, not the title/subject. If you're relying on commit messages to build PR content, then the first line of the commit message becomes the PR title, and the 2nd line starts the PR body text. Put your "Fixes" comment on line 2 so it's part of the body.

**Comment by scottcwilson** [comment]
We should assign to v2 and fix this issue.
