### ISSUE TITLE
Suggest: English language string "GIFT" should not be hardcoded

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2079]
A better approach would be to use a single function which checks a model number string, so not only could people use their own language for "GIFT" but multiple strings could be used if required. 

Suggested as a v2 enhancement.

**Comment by drbyte** [comment]
Agreed.
I think the scope of this affects:
- /includes/classes/shopping_cart.php - calculate()
- /admin/specials.php
- /admin/products_price_manager.php
- /includes/functions/functions_prices.php - zen_get_products_special_price()

**Comment by scottcwilson** [comment]
Also: 

- includes/modules/order_total/ot_gv.php
- includes/classes/shipping.php
- admin/specials.php

**Comment by drbyte** [comment]
Eeks -- github-search-fail! :D

**Comment by scottcwilson** [comment]
LOL it's tough because there are defines which also use the GIFT string.  It will be a trickier change than someone might intuitively think.

**Comment by scottcwilson** [comment]
Should we move this back to the 1.5.x stream?

**Comment by scottcwilson** [comment]
Closing due to lack of interest.
