### ISSUE TITLE
Should stock-related processing be consolidated?

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2090]
If we provided access to products.products_quantity either through a function (or perhaps moved it to a separate table) we could more easily facilitate multiple warehouse support.  

@lat9 Any thoughts on this?

**Comment by lat9** [comment]
Providing access to the value via a function (with included notifier to allow override) would certainly lay the foundation to allow multiple-warehouse support.

Moving that value to a separate table will break many existing add-ons and site-specific customizations.

**Comment by zcwilt** [comment]
@lat9 At this point I think v2 is going to break all current plug-ins. Given that, at least for core code I don't see any benefit for moving the products_quantity to a new table.

One thing we played around with quite a while ago was to move code for things like ``Tax Calculation`` and ``Stock Management`` into ``Strategy`` Classes. Now while the inbuilt classes would just mimic current code, notifiers and class interfaces/composition would allow plug-ins to override the base methods. This would also allow, if needed, stock operations to access other tables. e.g. for multi-location. This would also allow for ``lifo`` and ``fifo`` operations, given someone wanted to write a plug-in to do that.

**Comment by lankeeyankee** [comment]
I think this would be a great feature and allow larger enterprises with multiple locations to make use of ZC.

I personally don't think breaking all existing modules will make v2 dead in the water(I am aware it's "backburnered" with no new timeline but I really hope it's not abandoned!). There will obviously be a very slow period at first as people wrote new modules, but if it's a true plug and play architecture where the user can just click a couple buttons to install, upgrade or delete a module, then it is 100% worthwhile to draw a line in the sand and say this is the way it is moving forward. I truly hope v2 can get kickstarted again.

**Comment by drbyte** [comment]
Yes, it's only "backburnered".

**Comment by drbyte** [comment]
I think stock-processing could be centralized and controlled by adding some strategic Notifier hooks that would allow the processing to be handled according to various strategies depending on store needs. This would allow enterprise-scale things to be implemented with relative ease.

**Comment by drbyte** [comment]
PRs welcome for moving the existing processing into an observer class which responds to notifier hooks.

**Comment by drbyte** [comment]
Stock-Related Processing for `products.products_quantity`
- Catalog-side 
  - is "written" only by the `order` class, and that's wrapped inside a Notifier conditional.
  - is "read" by a couple shared functions, product-listings via index_filter, and SNAF pages
- Admin-side
  - is "written" by product-edit pages, and when deleting an order
  - is "read" in various listing pages

**Comment by scottcwilson** [comment]
Here's the list of files I have from the catalog side:

includes/filenames.php
includes/classes/shopping_cart.php
includes/classes/order.php
includes/index_filters/default_filter.php
includes/index_filters/music_genre_filter.php
includes/index_filters/record_company_filter.php
includes/functions/functions_prices.php
includes/functions/functions_lookups.php
includes/functions/functions_general.php
includes/templates/responsive_classic/templates/tpl_modules_products_new_listing.php
includes/templates/responsive_classic/templates/tpl_document_product_info_display.php
includes/templates/responsive_classic/templates/tpl_product_reviews_info_default.php
includes/templates/responsive_classic/templates/tpl_document_general_info_display.php
includes/templates/responsive_classic/templates/tpl_product_reviews_default.php
includes/templates/responsive_classic/templates/tpl_product_info_display.php
includes/templates/responsive_classic/templates/tpl_modules_products_all_listing.php
includes/templates/responsive_classic/templates/tpl_product_music_info_display.php
includes/templates/responsive_classic/templates/tpl_modules_products_featured_listing.php
includes/templates/responsive_classic/templates/tpl_product_free_shipping_info_display.php
includes/templates/template_default/templates/tpl_modules_products_new_listing.php
includes/templates/template_default/templates/tpl_document_product_info_display.php
includes/templates/template_default/templates/tpl_product_reviews_info_default.php
includes/templates/template_default/templates/tpl_document_general_info_display.php
includes/templates/template_default/templates/tpl_product_reviews_default.php
includes/templates/template_default/templates/tpl_product_info_display.php
includes/templates/template_default/templates/tpl_modules_products_all_listing.php
includes/templates/template_default/templates/tpl_product_music_info_display.php
includes/templates/template_default/templates/tpl_modules_products_featured_listing.php
includes/templates/template_default/templates/tpl_product_free_shipping_info_display.php
includes/modules/products_quantity_discounts.php
includes/modules/responsive_classic/product_listing.php
includes/modules/product_listing.php
includes/modules/pages/products_all/header_php.php
includes/modules/pages/product_free_shipping_info/main_template_vars.php
includes/modules/pages/document_general_info/main_template_vars.php
includes/modules/pages/featured_products/header_php.php
includes/modules/pages/document_product_info/main_template_vars.php
includes/modules/pages/product_music_info/main_template_vars.php
includes/modules/pages/advanced_search_result/header_php.php
includes/modules/pages/index/main_template_vars.php
includes/modules/pages/product_info/main_template_vars.php
includes/modules/pages/shopping_cart/header_php.php
includes/modules/pages/products_new/header_php.php

**Comment by scottcwilson** [comment]
Not going to pursue in the short term; too little demand.
