### ISSUE TITLE
v156a Template selection cleared on restoration of session after timeout and choice of template

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#2118]
Perhaps obscure, but seems like it could be a problem.

Here's the setup:
Goto `Tools`->`Template Selection`
Select the `edit` button.
Change or leave the template the same but be sure to select the save button.
the URI will look something like: `admin/template_select.php?page=1&tID=1&action=save`
Allow the session to timeout.
Refresh the page either by F5, selecting the reload on the browser, clicking on the link in the browser and pressing enter, etc...
This will result in the need to login again to the admin panel with the following on the uri:
`admin/login.php?camefrom=template_select.php&page=1&tID=1&action=save`

Once the credentials are entered, the file processes the absent data as if to save the template selection and all options become wiped out.  This could be observed by using the above uri (modifying `admin` to the appropriate `admin` folder) without all of the previous steps.

I believe some similar occurrences happen on other such "save" type entries where the URI still contains action to affect the database.

Considered solutions (specifically for `template_select.php` but possibly for other admin windows) include (but are not limited to): 
- Redirecting after a save to remove the save action from the URI. (Seems "easiest" to correct)
- Aborting a save action if there is no data provided. (Would need to be sure that such a save operation couldn't possibly have an empty data set potentially providing unnecessary corrections; however, by not implementing this level of review, the problem could still occur if the URI were collected off of the web page and applied at any time whether logged in or not)
- Both of the above options would be a good idea.  Removing it from the URI would prevent restoration from a timeout to cause the observed problem and preventing saving of blank information when accessing the action uri of a saving page without posting the applicable information would prevent the possibility of blanking out the associated save data.

Other ideas of consideration and discussion welcome.

I have been through the `catalog` menu from `product types` to `manufacturers` and have not found a similar issue. I have been through a portion of the Categories/Products screen(s), but not specifically for this topic and at all views so not claiming that as complete.  I have also (so far) been through the `tools` menu for Layout Boxes Controller and Banner Manager (Template Selection was where this was observed).

**Comment by drbyte** [comment]
Closed by #2119
