### ISSUE TITLE
problem with get and post in v156 in admin/includes/modules/product

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#2122]
when one is collecting info on a new product, the product type is a hidden field.  see:

https://github.com/zencart/zencart/blob/95fbf3081f06f4027046dfa1fd191776f1b59cd5/admin/includes/modules/product/collect_info.php#L170

when one now looks at the preview, we have moved the product type to a GET as part of the form.  see:

https://github.com/zencart/zencart/blob/95fbf3081f06f4027046dfa1fd191776f1b59cd5/admin/includes/modules/product/preview_info.php#L48

i believe the correct code should be a _POST on the product type.  as in:

`      echo zen_draw_form($form_action, FILENAME_PRODUCT, 'cPath=' . $cPath . (isset($_POST['product_type']) ? '&product_type=' . $_POST['product_type'] : '') . (isset($_GET['pID']) ? '&pID=' . $_GET['pID'] : '') . '&action=' . $form_action . (isset($_GET['page']) ? '&page=' . $_GET['page'] : ''), 'post', 'enctype="multipart/form-data"');`

**Comment by drbyte** [comment]
@Zen4All - thoughts?
While the GET currently works due to the POST: GET: 1 check in the product.php file (link below), if there's no need for it as a GET param (and therefore cluttering the URL), it may be good to remove the redundancy.
As long as all the product-types process the POST, of course.

https://github.com/zencart/zencart/blob/95fbf3081f06f4027046dfa1fd191776f1b59cd5/admin/product.php#L14

**Comment by Zen4All** [comment]
@drbyte - I'll take a look at this today

**Comment by drbyte** [comment]
@Zen4All is this already done?

**Comment by Zen4All** [comment]
Looking at the v1.5.7 code, I can only find $_POST references. So yes this looks like it is fixed

**Comment by drbyte** [comment]
Thanks!

**Comment by proseLA** [comment]
i looked at the v157 branch, and it looks exactly the same as my initial post on 1/26.

am i missing something?

**Comment by Zen4All** [comment]
@proseLA  I now see where you are seeing the problem. I'll get right on it

**Comment by Zen4All** [comment]
The particular line of code,  can be removed. I'll make a PR
