### ISSUE TITLE
V2 and the future of legacy plug-ins

### ISSUE THREAD

**Issue by zcwilt** [zencart/zencart#2133]
This post was prompted by a discussion in #2090 
Firstly, apologies to @lat9  as I may have over simplified the position regarding legacy plug-ins.

It's always been the idea with v2 to provide core infrastructure and internal api such that we move away from the problems of upgrading between versions (especially where a store has plug-ins that override core code)

By the very nature of enforcing plug-ins to this new infrastructure, we are saying that legacy plug-ins will no longer work.

However we also realise that releasing a product that breaks all plug-ins completely would be detrimental. There are a couple of ways this will be mitigated. Firstly by incorporating some ``popular`` plug-ins into core. An example here is `Guest Checkout`. Secondly by providing a deprecation schedule for some core changes that would break legacy plug-ins.

We have introduced new object oriented ways for writing core code, especially in admin side code, including new controllers, language handling, Laravel type models and eloquent ORM query builders. These additions will make it much easier for plug-in authors to write code that never touches core,

It is the case even now though  that all the legacy code that plug-in authors use is still available.
They can still write admin pages in the old procedural style, they can still use the legacy ZC query builder, and can still use defines for language translation.

So there is going to be a transition period, but at some point we will need to start enforcing(deprecating legacy code) the use of the new infrastructure.

Another example here is php 5.6 support. Despite the fact that 5.6 is end of life, we have decided not to use a lot of the new syntactic sugar that 7+ provides, at least for some period to allow for hosts to upgrade.

Even given this, it's still likely that some legacy plug-ins will break, that's inevitable given the huge changes to code both admin and catalog side. However I don't see that to be any different to say the introduction of the ``AdminSanitizer`` code which itself broke a number of plug-ins.

**Comment by torvista** [comment]
In my opinion...
the past-to-current incremental, non-breaking, tinkering of legacy code has been a huge waste of development time. To say the big bang jump to a modern, future-proof codebase is long overdue is putting it very mildly indeed and so active progress on that path is greatly appreciated.

But what is underneath is academic to most businesses. To convince current users to move to what is effectively a new program, will need to include not just the most popular plugins, but more functionality to compete with the leading ecommerce solutions, or why would any business bother to do all that work to develop a new program to match the level of the old one+mods?
It doesn't matter if it breaks everything when 90% of the currently-listed plugins are out-of-date hacks anyway. The other 10% should be core. 

The other project I work on (Dolibarr), includes a module-builder in the core code.
This is a built-in function that will auto-create all the files/structure necessary for an external module (plugin) that adds/overrides/extends the core functionality. So no looking through a wiki to copy and paste example code.
I think this is a must, to spoon-feed people like me to re-do whatever hacklets they have done in the past, to the new structures and to ensure rigid adherence to best practices for the future. You need to make it easy for those of us who have day and night jobs apart from Zen Cart.

**Comment by dakanji** [comment]
On the other hand, there is very good reason not to throw out battle tested code, [however ugly that code may appear](https://www.joelonsoftware.com/2000/04/06/things-you-should-never-do-part-i/). I have seen one project go under after the chucking out of the old stuff and the introduction of "eloquent ORM query builders" and the like.

I suppose the core devs are perfectly happy with things but from where I sit, v200 is looking extremely complex and opaque. I hope it doesn't turn out to be too complex.

Probably a good idea to keep v15x going as a a backstop.
