### ISSUE TITLE
Store Pickup anomaly

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#2151]
As far back as zc151, the `storepickup.php` shipping module's configuration for the tax-basis shows

![image](https://user-images.githubusercontent.com/2685585/52071942-056baf00-2552-11e9-98eb-6aea1f297487.png)

... where the **Tax Basis** description indicates that there should be a setting for _Store_, but the only options available are _Shipping_ and _Billing_.

Was this an oversight, or was there a reason to drop that setting (if it was ever there!)?

**Comment by lat9** [comment]
Agreed on both counts, but the shipping tax calculations are "driven" by the currently-selected shipping method and actually made in `includes/modules/order_total/ot_shipping.php`.  

Any change to the processing will require an update to both modules, with `ot_shipping.php` updated to add a clause to its tax-basis determination for the `Store` value.

**Comment by lat9** [comment]
Actually, for a _**Store Pickup**_ shipping method, shouldn't the tax_basis just be set to `Store`?

**Comment by drbyte** [comment]
> Actually, for a _**Store Pickup**_ shipping method, shouldn't the tax_basis just be set to `Store`?

Yes, that's what I wrote in my bullet points above. Of course it also assumes that "store pickup" always only ever offers pickup at the same address location that the store's "default address" is set to in Admin->Configuration->My Store.

**Comment by drbyte** [comment]
> Yes ... but, there is _currently_ no accurate way to glean the zone associated with a configured pickup location, since the _**Pickup Locations**_ setting is fairly free-format and unvalidated.

Fully agreed.

**Comment by lat9** [comment]
This is also complicated by the fact that while there's a store-defined country and zone (**_Configuration->My Store->Country_** and **_->Zone_**, respectively), the shipping setting includes only _**Configuration->Shipping/Packaging->Country of Origin**_ with no associated zone).

**Comment by drbyte** [comment]
Would a variant of `mzmt` be useful as a Store Pickup replacement?
Or maybe just some of its features might be useful as idea inspiration to improve it.

Instead of creating `N` number of zones, perhaps storing anything that's only used "by the module itself" as `json` in a single define might be less clutter to manage. Perhaps the complexity comes not so much in storage but in the UI that's geared around constants.

Finding a way to associate zone details with selectable options would certainly help in terms of billing-related tax controls when using this module.

**Comment by lat9** [comment]
... and what is `mzmt`?

**Comment by drbyte** [comment]
Multi-Zone-Multi-Table
https://www.zen-cart.com/downloads.php?do=file&id=2138

**Comment by scottcwilson** [comment]
I misread this as "nzt" - the drug from the movie Limitless. :) 

http://www.theclearpill.com/about.html

**Comment by scottcwilson** [comment]
I'd like to propose the following resolution for this issue: 
- Add Store as a value to the config MODULE_SHIPPING_STOREPICKUP_TAX_BASIS.
- Provide a notifier in includes/modules/order_total/ot_shipping.php below line 104 (final else branch) to allow the setting of $shipping_tax and $shipping_tax_description.

Most stores running Zen Cart will not have locations in multiple states; we don't need to build this edge case into the core.

**Comment by scottcwilson** [comment]
The Store comment has been removed from the configuration_description for MODULE_SHIPPING_STOREPICKUP_TAX_BASIS.  Closing.
