### ISSUE TITLE
orders.shipping_method handling in 1.5.6

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2171]
Some shipping methods have names that use HTML Entities in this field.  This causes problems for programs that export this data, particularly into XML. 

USPS (First-Class&trade; Package Service)

Would it make sense to remove strings like &trade; and &reg; before saving the shipping method? And/or perhaps stripping HTML tags? 

I'd be happy to make the PR, just wanted to get some input first.

**Comment by lat9** [comment]
Scott, are you sure?  It looks to me like the size of that field was _increased_ from varchar(128) to varchar(255) at zc155.

**Comment by scottcwilson** [comment]
You're right - updated reasoning.

**Comment by lat9** [comment]
Could you give an example where the 255-characters would be exceeded?

**Comment by scottcwilson** [comment]
Forget the 255.  I updated the text to remove this.  I just want to get rid of the HTML entities.

**Comment by lat9** [comment]
Could you give an example of a program that converts this information to XML?  Just trying to understand the scope and verification method for any associated change.

**Comment by scottcwilson** [comment]
I can't point to  a specific example that's publicly available but I'm sure you know that doing an XML order export is not an uncommon thing.

**Comment by lat9** [comment]
All I'm saying is that it's _difficult_ to verify that any associated change has corrected unwanted behavior without having some means of reproducing the issue.

**Comment by scottcwilson** [comment]
To repro the issue is trivial.  Install USPS, add First Class Shipping.  This comes out as "United States Postal Service (First-Class&trade; Package Service)".  Build a small exporter that exports orders in the following format: 

<?xml version="1.0" encoding="UTF-8"?>
<Order>
<OrderNumber>114164</OrderNumber>
<Shipping>United States Postal Service (First-Class&trade; Package Service)</Shipping>
</Order>

After the change is made, verify the &trade is gone.

**Comment by lat9** [comment]
Apologies, Scott, but isn't this something that the XML exporter should take care of, e.g. using `html_entity_decode`?  I don't see this as a base Zen Cart issue.

**Comment by drbyte** [comment]
USPS always uses and expects the symbols. Altering what's stored could break plugins that try to re-query USPS or some passthru shipping service that needs to read the exact name.
Example: edit-orders might need to read it and grab an updated quote based on the chosen method.
Or passing it to ShipStation might encounter a case where ShipStation is wanting exactly the name of the service as USPS calls it.

I don't think ZC should be changing this.
