### ISSUE TITLE
Simplify template-specific inclusion of `jscript_framework.php`

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#2211]
The "core" version of a template's auto-loaded `jscript/jscript_framework.php` is currently distributed for **both** the `template_default` and the `responsive_classic` templates.  There are a couple of problems with this:

1. Since the file is not included in the `classic` template's directory structure, that processing is not loaded for that template (or clones thereof).
2. An identical file is distributed for both the `template_default` and `responsive_classic` templates, leading to the possibility of "forgetting" to change the file in both directories.
3. Template authors who follow the pattern set by `responsive_classic` can mistakenly distribute a down-level version of that file.

I suggest a two-fold approach, considering the `template_default` version of the file to be **core**:

1. Modify the `responsive_classic/jscript/jscript_framework.php` to simply `require` the template_default version.
2. Include a copy of the above file in the `classic` template's `jscript` sub-directory.

**Comment by drbyte** [comment]
Closed by #2213
