### ISSUE TITLE
Customer Interface Features needed in core

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2217]
- Ask A Product Question should be part of the Zen Cart core.
- Contact Us and Ask A Question should include a phone number in addition to a name and email address. 

These are pretty basic features and Zen Cart users shouldn't have to do work to add them.

**Comment by torvista** [comment]
Agreed. Long since implemented in my shop.

**Comment by scottcwilson** [comment]
This is (mostly) done.  Closing.
