### ISSUE TITLE
Double click prevention on checkout confirmation

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2219]
Right now in includes/modules/pages/checkout_confirmation/jscript_main.php the `button_timeout` function does 

`
  button.style.cursor="pointer";^M
  button.disabled = true;^M
`
why do either of these? It's possible the payment method hasn't completed, and the button should still be locked, and once the page gets refreshed to checkout success, the cursor resets anyhow.

**Comment by drbyte** [comment]
> Right now in includes/modules/pages/checkout_confirmation/jscript_main.php the `button_timeout` function does
> 
> `button.style.cursor="pointer";^M button.disabled = true;^M`
> why do either of these? It's possible the payment method hasn't completed, and the button should still be locked, and once the page gets refreshed to checkout success, the cursor resets anyhow.

I'm confused. You said it's using pointer/true, but the code uses either wait/true or pointer/false:
https://github.com/zencart/zencart/blob/dabf6584cb5c84a91f59dd41a4f0d28394b221df/includes/modules/pages/checkout_confirmation/jscript_main.php#L28-L40

I think some context is missing here ... ?

**Comment by scottcwilson** [comment]
The timeout function resets the values to pointer/false.  I'm saying don't do this .  Keep them at wait/true.
