### ISSUE TITLE
v156: Multiple definitions of osh_updated_by function

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#2224]
As reported in [this ](https://www.zen-cart.com/showthread.php?225244-Multiple-definition-of-function-osh_updated_by)Zen Cart posting, I blew it for the changes associated with #1342.

Pre-existing installations using `zen_update_orders_history` have that function defined in an `/includes/functions/extra_function`-based file.  The extra functions are included by the `init_general_functions.php` processing which is, unfortunately, _prior to_ the now in-core load of the `functions_osh_update.php`.

**Comment by lat9** [comment]
That PR just pushed swaps the load of the `functions_osh_update.php` with `init_general_functions.php`, to allow that in-core version of the function to be defined _prior to_ the load of the `extra_functions` files.

Any pre-existing definition of that function will no longer load, based on that now-previous definition.

**Comment by drbyte** [comment]
Closed by #2225
