### ISSUE TITLE
ZC156 version error

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2226]
Hi,
in a new install (xampp 7.3.3) of today's zip of 1.56 from Github, I see the version check is confused...is this as expected?
![Clipboard02](https://user-images.githubusercontent.com/4391026/54916075-ea397200-4ef8-11e9-90e0-feaf97d146ce.gif)

**Comment by drbyte** [comment]
When it's showing `v{.{ :: {` it's because your server isn't communicating with the version-server.

For me this morning it's giving correct results:
<img width="393" alt="Screen Shot 2019-03-25 at 9 28 02 AM" src="https://user-images.githubusercontent.com/404472/54923285-522f8e80-4ee0-11e9-9e9d-7c194c014aeb.png">

**Comment by torvista** [comment]
Firewall and Antivirus off.

This is the same release ZC156a fileset using the same (imported) database on different Xampps.

php 7.3.0

![Clipboard01 ok](https://user-images.githubusercontent.com/4391026/54934711-43b49780-4f1f-11e9-9862-e8c294ad541d.gif)

php 7.3.3

![Clipboard01 nok](https://user-images.githubusercontent.com/4391026/54934734-4b743c00-4f1f-11e9-87b4-d789f310a1a4.gif)

**Comment by drbyte** [comment]
It seems your CURL setup in your PHP 7.3.3 is unable to make a satisfiable connection on https.

While we can (and will) tweak the version-lookup code to simply ignore this situation, you won't know about the problem when we do that.

**Comment by torvista** [comment]
Well, yes and no...it transpires that the Xampp 7.3.3 distribution is missing the certificate used for curl, as ably demonstrated by the curltester. Once copied from a previous installation, all is good.

> Connecting to Zen Cart Version Server (http) ...
GOOD: CURL Connection successful.

>Connecting to Zen Cart Version Server (https) ...
Error 77: error setting certificate verify locations: CAfile: C:\xampp.7.3.3\apache\bin\curl-ca-bundle.crt CApath: none

>Connecting to Zen Cart Support Server (https) ...
Error 77: error setting certificate verify locations: CAfile: C:\xampp.7.3.3\apache\bin\curl-ca-bundle.crt CApath: none

>Connecting to USPS (port 80)...
GOOD: CURL Connection successful.
