### ISSUE TITLE
ZC156a: Various language related issues

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2231]
\admin\includes\languages\english.php
define('HEADER_LOGO_WIDTH', '200px');
define('HEADER_LOGO_HEIGHT', '70px');

should not have px
-------------
\admin\includes\languages\english\coupon_restrict.php
define('MAX_DISPLAY_RESTRICT_ENTRIES', 20);

not a language constant
-------------
\admin\includes\languages\english\index.php
Three dots for an ellipsis
define('HEADING_TITLE', 'Choose an action...');
-------------
\admin\includes\languages\english\layout_controller.php
duplicated constant
define('TABLE_HEADING_ACTION', 'Action');
-------------
\admin\includes\languages\spanish\whos_online.php
define('WHOIS_TIMER_REMOVE', 1200); // seconds when removed from whos_online table - 1200 default = 20 minutes
define('WHOIS_TIMER_INACTIVE', 180); // seconds when considered inactive - 180 default = 3 minutes
define('WHOIS_TIMER_DEAD', 540); // seconds when considered dead - 540 default = 9 minutes
define('WHOIS_SHOW_HOST', '1'); // show Last Clicked time and host name - 1 default
define('WHOIS_REPEAT_LEGEND_BOTTOM', '12'); // show legend on bottom when more than how many entries - 12 default

not language constants
-------------
\admin\includes\languages\english\sqlpatch.php
  define('SQLPATCH_HELP_TEXT','The SQLPATCH tool lets you install system patches by pasting SQL code directly into the textarea '.
                              'field here, or by uploading a supplied script (.SQL) file.<br />' .
                              'When preparing scripts to be used by this tool, DO NOT include a table prefix, as this tool will ' .
                              'automatically insert the required prefix for the active database, based on settings in the store\'s ' .
                              'admin/includes/configure.php file (DB_PREFIX definition).<br /><br />' .
                              'The commands entered or uploaded may only begin with the following statements, and MUST be in UPPERCASE:'.
                              '<br /><ul><li>DROP TABLE IF EXISTS</li><li>CREATE TABLE</li><li>INSERT INTO</li><li>INSERT IGNORE INTO</li><li>ALTER TABLE</li>' .
                              '<li>UPDATE (just a single table)</li><li>UPDATE IGNORE (just a single table)</li><li>DELETE FROM</li><li>DROP INDEX</li><li>CREATE INDEX</li>' .
                              '<br /><li>SELECT </li></ul>' 

br between last two li not allowed
-------------
\includes\languages\english.php
  define('CART_SHIPPING_METHOD_ZIP_REQUIRED','true');

not language constant
-------------
\includes\languages\english\modules\order_total\ot_coupon.php
  define('MODULE_ORDER_TOTAL_COUPON_HEADER', TEXT_GV_NAMES . '/Discount Coupon');
  define('MODULE_ORDER_TOTAL_COUPON_DESCRIPTION', 'Discount Coupon');
  define('MODULE_ORDER_TOTAL_COUPON_TEXT_ENTER_CODE', TEXT_GV_REDEEM);
  define('MODULE_ORDER_TOTAL_COUPON_HEADER', TEXT_GV_NAMES . '/Discount Coupon');

repeated constant and should this not be "Discount Coupons", plural
-------------
\includes\languages\english\meta_tags.php
// Define which pages to tell robots/spiders not to index
// This is generally used for account-management pages or typical SSL pages, and usually doesn't need to be touched.
  define('ROBOTS_PAGES_TO_SKIP','login,logoff,create_account,account,account_edit,account_history,account_history_info,account_newsletters,account_notifications,account_password,address_book,advanced_search,advanced_search_result,checkout_success,checkout_process,checkout_shipping,checkout_payment,checkout_confirmation,cookie_usage,create_account_success,contact_us,download,download_timeout,customers_authorization,down_for_maintenance,password_forgotten,time_out,unsubscribe,info_shopping_cart,gv_faq,gv_redeem,gv_send,popup_image,popup_image_additional,product_reviews_write,ssl_check,shopping_cart,no_account,order_status');

are these really language-dependent?
-------------
\admin\option_name.php
  <button type="submit" class="btn btn-primary">Update Sort Order</button>
  
hardcoded text

**Comment by barco57** [comment]
```
\admin\includes\languages\english.php
define('HEADER_LOGO_WIDTH', '200px');
define('HEADER_LOGO_HEIGHT', '70px');

should not have px
```
While WIDTH and HEIGHT attributes do not need/require px declared because of the browser always dealing with WIDTH and HEIGHT attributes as being in pixels, actually having px on there doesn't cause any issues as it is basically ignored unlike changing it to % which under HTML5 would throw an error. 
I personally think the larger problem is that it is set to 200 x 70 when the actual image dimensions are 192 x 68 which means it is being scaled up for display, with the aspect ration being slightly off, which is causing the logo to be a little bit blurry.

**Comment by torvista** [comment]
> having px on there doesn't cause any issues
True. But, but in html5 it should be an integer:
https://www.w3.org/TR/2012/WD-html-markup-20120329/img.html

And yes those values are incorrect for the actual logo size so it does gives a bad impression.

**Comment by mc12345678** [comment]
> \admin\includes\languages\english.php
define('HEADER_LOGO_WIDTH', '200px');
define('HEADER_LOGO_HEIGHT', '70px');
>
> should not have px

I have seen html validators indicate that px should not be there.  Problem? Well, certainly it will still process, but can bring about one more "note" about the layout/design.

For some of the others where a constant was defined within the language area, what is the recommendation for relocation? What issue(s) are being created with them where they are?

**Comment by torvista** [comment]
Duplicate constant = bug.
In my opinion constants that are not language/locale-related should be elsewhere.
While they are not a bug and don't cause an issue, it's all part of code improvement and separation.
Similarly there are still occurrences of font tags in language files.
