### ISSUE TITLE
Possible issue in hideStateField() in includes/modules/pages/login/jscript_addr_pulldowns.php

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2235]
The other files that contain the same function  

includes/modules/pages/checkout_payment_address/jscript_addr_pulldowns.php
includes/modules/pages/create_account/jscript_addr_pulldowns.php
includes/modules/pages/checkout_shipping_address/jscript_addr_pulldowns.php
includes/modules/pages/address_book_process/jscript_addr_pulldowns.php

all check that `stText` is defined using 

`if (document.getElementById("stText")) {`

but this file does not.  Shouldn't it? 

(Also - it would be better to consolidate all this duplicated code if possible.)

**Comment by torvista** [comment]
If stText does not exist in the current fileset, I don't think it should not be checked-for anymore/should be removed.
It went in 1.55, that's long ago enough.

**Comment by scottcwilson** [comment]
I guess the challenge is that it might be in an old template?  Not sure.

**Comment by torvista** [comment]
Yes, sure it will be in a OLD template from 1.54. Not a concern now.

**Comment by drbyte** [comment]
Yes, all the JS that handles the in-page validation and the myriad config options for address/country/zone handling should be cleaned up and consolidated.
`stText` is just one of many.

**Comment by scottcwilson** [comment]
> Yes, sure it will be in a OLD template from 1.54. That's a concern for someone else.

The thing to remember is that most free templates are rarely, if ever, updated.  It would just be a bit harsh to completely break them.

**Comment by lankeeyankee** [comment]
This comes back to the line in the sand question. At what point do you say, for the greater good moving forward we have to do x which could potentially break a, b, c which are all older and unmaintained contributions? And a lot of the free templates should be marked as "for reference purposes" since they are very old designs and do a huge disservice to people building a new site.

**Comment by torvista** [comment]
> At what point do you say, for the greater good moving forward we have to do x which could potentially break a, b, c which are all older and unmaintained contributions?

On any version change i.e 156x->157.
Put a warning in the changelog. Done. Omelette, breaking eggs etc...
People cannot expect to upgrade without any work, we are a loooong way from that and getting rid of messy stuff like this is part of the climb.

**Comment by lat9** [comment]
I'm fairly certain that these discrepancies are addressed in PR#4754.

**Comment by lat9** [comment]
@scottcwilson, can this now be closed?
