### ISSUE TITLE
ZC156, admin\includes\ckeditor.php, DIR_WS_EDITORS missing closing semicolon

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2245]
`<script type="text/javascript" src="../<?php echo DIR_WS_EDITORS ?>ckeditor/ckeditor.js"></script>`

**Comment by drbyte** [comment]
While it's definitely more specific to include the semicolon, it's not syntactically wrong. I just tested it in PHP 4.4 thru to 7.2.

We can tidy it up, but I'm curious: Is it triggering an error for you?

**Comment by torvista** [comment]
no, I think the IDE flagged it. I thought it was obligatory.

**Comment by drbyte** [comment]
Resolved.
