### ISSUE TITLE
156, admin: console error due to missing bootstrap.min.css.map

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2247]
Since bootstrap.min.css contains /*# sourceMappingURL=bootstrap.min.css.map */
console in Firefox points out it is missing.
In the interest of having a nice, error-free console, is there any reason NOT to include it?

**Comment by Zen4All** [comment]
That is a comment in the css as far as I know, So it should not give an error, and bootstrap.min.css.map is not needed

**Comment by zcwilt** [comment]
sourcemaps can be useful for developers as an as to debugging, although they have little benefit for minified files. While we could just remove the line from the file, the problem would return if we decided to use the cdn version.

If it really bothers you, you have 2 options.~
Disable sourcemaps in chrome dev tool settings.
Create an empty bootstrap.min.css.map in the same directory as the css file.
Note also. only seems to be Chrome dev tools that gives the error. Don't see it with Firefox.

**Comment by Zen4All** [comment]
> Note also. only seems to be Chrome dev tools that gives the error. Don't see it with Firefox.

For me it was the other way around. So it is probably a setting somewhere in Chrome and FF.

**Comment by torvista** [comment]
I just want an empty console...so I don't have to think..."is that something I have caused or was it already there?"
I have not changed any settings from the browser install. I only get it on Firefox (Windows).
I know most of what I report are not problems as such, but I believe that before I start hacking away, vanilla code
- should not cause any php errors/warnings in strict mode
- should validate in the Developer tools and W3c Online
- should pass the IDE inspections
as all of these are used to fix errors introduced by modifications/revise modifications carried over during an upgrade.
The baseline should be a clean sheet as much as possible, nitpicking as it is.
