### ISSUE TITLE
156:  \includes\languages\english\popup_coupon_help.php unbalanced p tag

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2254]
`define('TEXT_NO_CAT_TOP_ONLY_DENY', '<p>This coupon has specific Product Restrictions.');`

**Comment by zcwilt** [comment]
Given the output is part of an unordered list, probably don't need the <p> tag

**Comment by torvista** [comment]
Thought as much, I wasn't sure, I could not get it to display (easily) to check.
