### ISSUE TITLE
val_function - is it and the supporting code, ready?

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#2263]
The other day a user of new ZC 1.5.6a ran into a problem with setting the email address of one of the configuration email settings where an email address like this `name <email@domain>` turned into `name &lt;email@domain&gt;`. So I began looking into what it might take to clean up the response to be acceptable.

Thing is, because of the admin sanitizer, the data that is fed to the configuration value check is already strictly sanitized.

So question is, is that really the desired and expected condition? Before I take the already cleaned up content to make it usable for final result, I'd like to be sure that there isn't some other quick flip expected. Especially since I was looking at offering it as a class for the base code.

**Comment by drbyte** [comment]
It could be that the sanitizer is the problem here. Unfortunately it's quite complicated to apply different sanitizer rules to individual configuration settings. It could be that val_function is actually an (unintended but convenient) solution to that complexity.
