### ISSUE TITLE
156: incorrect default_template images

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2266]
includes/templates/template_default/images/always-free-shipping.png 
is actually a .gif and referenced in TEXT_PRODUCT_FREE_SHIPPING_ICON
There is also an existing always-free-shipping.gif.

includes/templates/template_default/images/call_for_prices.png 
is actually a .jpg and referenced in OTHER_IMAGE_CALL_FOR_PRICE
There is also an existing call_for_prices.jpg.

includes/templates/template_default/images/free.png 
is actually a .gif and referenced in OTHER_IMAGE_PRICE_IS_FREE
There is also an existing free.gif.

**Comment by drbyte** [comment]
Closed by b0d6c9c72
