### ISSUE TITLE
includes/languages/english/create_account.php missing </li> tags

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2269]
`define('EMAIL_TEXT', 'You are now registered with our store and have account privileges:  With your account, you can now take part in the <strong>various services</strong> we have to offer you. Some of these many services include:' . "\n\n<ul>" . '<li><strong>Order History</strong> - View the details of orders you have completed with us.' . "\n\n" . '<li><strong>Permanent Cart</strong> - Any products added to your online cart remain there until you remove them, or check them out.' . "\n\n" . '<li><strong>Address Book</strong> - We can deliver your products to an address other than yours! This is perfect to send birthday gifts direct to the birthday-person themselves.' . "\n\n" . '<li><strong>Products Reviews</strong> - Share your opinions on our products with other customers.' . "\n\n</ul>");`

Suggest it also be toned down a bit:
`define('EMAIL_TEXT', 'You now have an account with '. STORE_NAME . ' providing:' . "\n\n<ul>" . '<li><strong>Order History</strong> - View order details.</li>' . "\n\n" . '<li><strong>Permanent Cart</strong> - Products you add to your cart will remain there until removed or purchased.</li>' . "\n\n" . '<li><strong>Address Book</strong> - Define additional addresses (for example to send a gift).</li>' . "\n\n" . '<li><strong>Products Reviews</strong> - Share your opinion on products you have purchased.</li>' . "\n\n</ul>");`

**Comment by mc12345678** [comment]
- In the *Permanent Cart* section converting "check them out" to "purchased" implies that all items come at a financial cost to the customer, though maintaining a free item in ones cart would also be saved.  
- Writing a review doesn't require that the product to have been purchased.  First interpretation of the statement was that a review would only be possible to write if the author of the review had purchased the item from the store.  When that was disproved, then consideration was if the author had purchased the product from any source, but even then it is possible that the item was given as a gift either from the store or from an alternate source that provides the same product.

**Comment by scottcwilson** [comment]
Agree with second bullet from @mc12345678, but not the first one.  Purchased is a reasonable word to use here.   Free items are an edge case.
