### ISSUE TITLE
STRICT_ERROR_REPORTING is ignored by admin/application_top.php

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2284]
....because the admin configure.php that may have this constant defined is loaded **after** the check for STRICT_ERROR_REPORTING.
Catalog is ok.

**Comment by torvista** [comment]
...I'm surprised this has not been dealt with...easy change/it's a bug and seems pretty crucial for development....

**Comment by scottcwilson** [comment]
After #2445 is done I can merge this change in too.
