### ISSUE TITLE
order_total collect_posts redirects before allowing validation of other errors

### ISSUE THREAD

**Issue by robryanx** [zencart/zencart#229]
I am wondering about the invalid coupon checking code under `collect_posts` in `ot_coupon`.
The redirect code prevents further `collect_posts` functions from being ran.

The example I have in this case is that we run coupon codes, rewards points and gift vouchers. Ideally you would have each run and determine whether there are any errors and then redirect back.

This is already somewhat covered in `checkout_confirmation` by this code:

``` php
if ($messageStack->size('checkout_payment') > 0) {
  zen_redirect(zen_href_link(FILENAME_CHECKOUT_PAYMENT, '', 'SSL'));
}
```

**Comment by scottcwilson** [comment]
Please assign to me.

**Comment by scottcwilson** [comment]
Please close as discussed.

**Comment by drbyte** [comment]
You said:

> What @robryanx is asking for is really more of an architectural improvement (gather all error messages at once, rather than one by one) than a true defect.

I agree: an architectural improvement could be beneficial. Not sure why you think this should be closed.

**Comment by scottcwilson** [comment]
Oh! I thought that we agreed I should abandon the PR and we should close the issue.  Can we at least take it out of 160 so it's not blocking the release?
