### ISSUE TITLE
FYI - 1.5.6b cutoff planned for April 30

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#2296]
If all the stars align properly, I hope to begin release-prep for v1.5.6b on May 1, with a goal of releasing within a week, time-permitting.

So, this is just a little advance notice that if you have something that "needs" to be in "b", now is the time to get the PR submitted.

I know there are some open Issues without resolution yet. I probably can't get to those before May 1 either, so if you think it's important for "b", then let's get some more discussion happening on them, or even a PR.

**Comment by scottcwilson** [comment]
Please be skeptical of any medium or low priority fixes which could jeopardize this release date.  It's more important to release and get a PHP 7.2+ compatible version out than it is to include one more fix at this point.

**Comment by torvista** [comment]
> Please be skeptical of any medium or low priority fixes which could jeopardize this release date. 
What does this mean? Don't submit anything until ...?
I submit things as I find them, someone else can choose to ignore them, no?

**Comment by Zen4All** [comment]
I don't think @scottcwilson meant not to submit anymore, but for the ream to be cautious on what to accept for the next release,

**Comment by torvista** [comment]
Normally I check if a fault in current/156 is fixed in develop.
If the same problem exists, should I PR against 156 or develop? Either way someone has to choose to port to the other or not, but what is preferred?

**Comment by scottcwilson** [comment]
@Zen4All Correct - I'm just saying "let's not jeopardize the long awaited release of 1.5.6b just to pull in one more fix which is not critical."  The closer to a release you are, the higher the priority a fix should be for it to be added in - otherwise you're risking breaking the build (or necessitating quick re-release) for a very low benefit.

**Comment by Zen4All** [comment]
That's exactly why i like the tight release regime software like Ubuntu is using.
Set fixed dates for releases, new features, non critical fixes, and critical fixes.

Not saying Zen Cart should adopt a strict policy like that, but it would be nice (IMHO) to have some sort of guide, like releasing a version once a year. Like it happend the past couple of years, each in december, which was probably a coincidence. Bug fix releases can be done more often of-course.

**Comment by scottcwilson** [comment]
Can we get an update on where things are?  It's been a week since the cutoff; how close are we to release and what are the outstanding issues?
