### ISSUE TITLE
Monthly Sales Chart shown $1 when sales went over $1,000

### ISSUE THREAD

**Issue by Pan2020** [zencart/zencart#2304]
A bug or display problem?
https://i.imgur.com/XyVy26S.png

When a single day's sale went over $1,000... it shown as $1 for today's value.

**Comment by Pan2020** [comment]
Is it due to the string processing that can lead to the comma (,) delimited off the rest of numbers?!
For example: $1,216.45 -> delimited at "," -> $1

**Comment by drbyte** [comment]
Turns out it's just a display problem (bug). In the language file there's a `%d` placeholder which converts to decimal/digit format, but can't handle commas. Changing it to `%s` makes it display correctly.

`/admin/includes/languages/english/index.php`

```diff
-define('TEXT_SALES_TODAY', 'Sales <strong>Today</strong> (%s) &nbsp;<strong>$%d</strong>');
+define('TEXT_SALES_TODAY', 'Sales <strong>Today</strong> (%s) &nbsp;<strong>$%s</strong>');
-define('TEXT_SALES_YESTERDAY', '<strong>Yesterday</strong> (%s) &nbsp;<strong>$%d</strong>');
+define('TEXT_SALES_YESTERDAY', '<strong>Yesterday</strong> (%s) &nbsp;<strong>$%s</strong>');
```

**Comment by Pan2020** [comment]
This issue is now resolved!
https://i.imgur.com/7zXlmre.png

Thank you @drbyte !
