### ISSUE TITLE
156 installer final screen improvement

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2308]
Currently the installer completes, states that
- installation is complete, i.e nothing else to do (incorrect)
- You can now access your shop and admin...(oh no you can't)
- and offers two links to click on, one of which cannot work...
followed by the instruction that the admin is disabled until the installer directory is removed.
It should be the other way round, the instruction should be before the links, or it just invites to click on the link first and get the alert.
![Clipboard05](https://user-images.githubusercontent.com/4391026/56848575-06ab3e80-68eb-11e9-9d11-2129023da8db.gif)
Remove the text "Installation completed"
And the links message should state "Subsequently you may access .... below".

In my opinion,

**Comment by Zen4All** [comment]
An other option would be to ad something to auto delete the install dir after installation. This is also done in numerous other software packages, and will improve user experience, nit having to use ftp

**Comment by torvista** [comment]
Ooo no, personally I totally disagree with ANY self-deleting/automatic thing. It's very confusing (local install to test, things self-delete, stuff works, upload files to production, stuff doesn't work, what did **I** do wrong etc.)
Zen Cart/open-source is a DIY thing, making grown-ups read, think and do stuff does them no harm. There's too much dumbing-down in the world already.
FTP and delete is well within everyone's limits, and if it isn't, they are in the wrong place!

**Comment by Zen4All** [comment]
That is where I disagree. IMHO If we want Zen Cart to survive, and thrive, we need to be less DIY.
But that discussion should be done i a separate issue.

**Comment by torvista** [comment]
Ha, ha, we should discuss this spanish style (where I live)...two spaniards, three opinions.
