### ISSUE TITLE
Need help with who's online session destruction.

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#2309]
Using the software as of https://github.com/zencart/zencart/commit/0fc00f8305a348e48733bed13d90045ae1bf8241 for ZC 1.5.6 to run a test to try to "help" a zenner that reported an issue with items listed in the shopping cart while trying to view who's online: https://www.zen-cart.com/showthread.php?225355

So, here's my situation: Currently using/testing PHP 7.1.22.  If I goto the store side of the shop and add an item to the cart, then in the admin try to go to who's online with the setting to not hide admin ip addresses, there is nothing shown on the right side of the screen regarding a cart.  There is html in the source code identifying the location of where there should be something, but no data provided.

I then created a series of data dumps to see what was going on, with the following code in admin/whos_online.php
````php
        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3 configurationColumnRight">
          <?php
          $heading = [];
          $contents = [];
          echo print_r($info, true);
          if (!empty($info)) {
            $heading[] = ['text' => '<h4>' . TABLE_HEADING_SHOPPING_CART . '</h4>'];
            $tag = 0;
            $session_data = '';
            $result = $db->Execute("SELECT value
                                    FROM " . TABLE_SESSIONS . "
                                    WHERE sesskey = '" . $info . "'");
            $session_data = trim($result->fields['value']);
          echo "\n" . print_r($session_data, true);

            $hardenedStatus = FALSE;
            $suhosinExtension = extension_loaded('suhosin');
            $suhosinSetting = strtoupper(@ini_get('suhosin.session.encrypt'));

//    if (!$suhosinExtension) {
            if (strpos($session_data, 'cart|O') == 0) {
              $session_data = base64_decode($session_data);
            }
            if (strpos($session_data, 'cart|O') == 0) {
              $session_data = '';
            }
//    }
echo "\n" . print_r($session_data, true);
            // uncomment the following line if you have suhosin enabled and see errors on the cart-contents sidebar
            //$hardenedStatus = ($suhosinExtension == TRUE || $suhosinSetting == 'On' || $suhosinSetting == 1) ? TRUE : FALSE;
            if ($session_data != '' && $hardenedStatus == TRUE) {
              $session_data = '';
            }

echo "\n" . "session_data_start: " . print_r($_SESSION, true);
            if ($length = strlen($session_data)) {

              $start_field = [];
              $session_data_field = [];

              $session_fields = [
                                  'id' => 'customer_id|s',
                                  'currency' => 'currency|s',
                                  'country' => 'customer_country_id|s',
                                  'zone' => 'customer_zone_id|s',
                                  'cart' => 'cart|O',
                                ];

              foreach ($session_fields as $key => $value) {
                $start_field[$key] = strpos($session_data, $value);
echo "\n" . "start_field: " . print_r($start_field[$key], true);
echo "\n" . "key: " . print_r($key, true);

                // If the session type is not found then don't try to initiate it.
                if (false === $start_field[$key]) {
echo "\n" . "start_fieldfalse: " . print_r($start_field[$key], true);
echo "\n" . "valuefalse: " . print_r($value, true);
                  continue;
                }

                $session_data_field[$key] = substr($session_data, $start_field[$key], (strpos($session_data, ';', $start_field[$key]) - $start_field[$key] + 1));

                if ('cart' === $key) {
echo "\ncart_data: " . print_r($key, true);
                  $end_cart = (int)strpos($session_data, '|', $start_field[$key] + strlen($value));
                  $end_cart = (int)strrpos(substr($session_data, 0, $end_cart), ';}');
                  $session_data_field[$key] = substr($session_data, $start_field[$key], ($end_cart - $start_field[$key] + 2));
echo "\n" . "sessiondatafieldkey: " . print_r($session_data_field[$key], true);
                }
                echo "<br/>";
echo "sessiondecode: " . print_r($session_data_field[$key], true);
                session_decode($session_data_field[$key]);
              }
/*
              $start_id = (int)strpos($session_data, 'customer_id|s');
              $start_currency = (int)strpos($session_data, 'currency|s');
              $start_country = (int)strpos($session_data, 'customer_country_id|s');
              $start_zone = (int)strpos($session_data, 'customer_zone_id|s');
              $start_cart = (int)strpos($session_data, 'cart|O');
              $end_cart = (int)strpos($session_data, '|', $start_cart + 6);
              $end_cart = (int)strrpos(substr($session_data, 0, $end_cart), ';}');

              $session_data_id = substr($session_data, $start_id, (strpos($session_data, ';', $start_id) - $start_id + 1));
              $session_data_cart = substr($session_data, $start_cart, ($end_cart - $start_cart + 2));
              $session_data_currency = substr($session_data, $start_currency, (strpos($session_data, ';', $start_currency) - $start_currency + 1));
              $session_data_country = substr($session_data, $start_country, (strpos($session_data, ';', $start_country) - $start_country + 1));
              $session_data_zone = substr($session_data, $start_zone, (strpos($session_data, ';', $start_zone) - $start_zone + 1));

              session_decode($session_data_id);
              session_decode($session_data_currency);
              session_decode($session_data_country);
              session_decode($session_data_zone);
              session_decode($session_data_cart);
*/
echo "\n" . "session_data: " . print_r($_SESSION, true);
              if (isset($_SESSION['cart']) && is_object($_SESSION['cart'])) {
echo "\n" . "incart-session: " . print_r($_SESSION['cart'], true);
                $contents[] = ['text' => $full_name . ' - ' . $ip_address . '<br />' . $info];
                $products = $_SESSION['cart']->get_products();
                for ($i = 0, $n = sizeof($products); $i < $n; $i++) {
                  $contents[] = ['text' => $products[$i]['quantity'] . ' x ' . '<a href="' . zen_href_link(FILENAME_PRODUCT, 'cPath=' . zen_get_product_path($products[$i]['id']) . '&pID=' . $products[$i]['id']) . '">' . $products[$i]['name'] . '</a>'];
                }
````
it seems that attempting to decode the session information clears out the existing admin session as the display of session_data provides an empty array and the incart-session output is never provided. This does not matter whether logged in or not. On the same server ZC 1.5.5f works fine, user tracking in both ZC 1.5.6a+ works without issue, but who's online destroys the session.

Here is server information:

Server OS: Linux 4.14.67-grsec-grsec+
Server Date: 04/28/2019 01:11:15  
Server Up Time: 01:11:15 up 198 days, 23:23, 0 users, load average: 2.58, 3.11, 2.92
HTTP Server: Apache
PHP Version: 7.1.22 (Zend: 3.1.0)
PHP File Uploads: On
Upload Max Size: 64M
PHP Memory Limit: 90M
POST Max Size: 65M
Database Engine: MySQL 5.6.34-log
Database Date: 04/28/2019 01:11:15
Database Data Size: 6,057 kB
Database Index Size: 1,638 kB
MySQL Slow Query Log Status: On
MySQL Mode: NO_ENGINE_SUBSTITUTION

Here is session settings in admin/configuration:

Cookie Domain | True |  
Force Cookie Use | False |  
Check SSL Session ID | False |  
Check User Agent | False |  
Check IP Address | False |  
Prevent Spider Sessions | True |  
Recreate Session | True |  
IP to Host Conversion Status | true |  
Use root path for cookie path | False |  
Add period prefix to cookie domain | True

What else might help someone looking to resolve this issue? I've tried replacing the 1.5.6 admin/whos_online.php with the ZC 1.5.5 version of it did not correct the loss of the session.  I don't see (may not be looking in nor for the right information) that suhosin is in use, so not expecting that portion of code to be of importance.

**Comment by Zen4All** [comment]
It is something that has been happening since as long as I can remember. Even in Zen Cart 1.3.8 this problem existed. On the same server you sometimes has thee problem, and then it can disappear all of the sudden.

**Comment by barco57** [comment]
This symptom has always been fixed with suhosin.session.encrypt = off in a php.ini but there is no suhosin for PHP7

**Comment by Zen4All** [comment]
Suhosin is dead, and not maintained since 2016.

**Comment by drbyte** [comment]
@mc12345678 wrote: 

> it seems that attempting to decode the session information clears out the existing admin session 

I encountered this on a couple sites recently - any hit at the whos-online page forces an admin logout (er, well, session destruction). Haven't been able to devote the time to finding out "why".

> I've tried replacing the 1.5.6 admin/whos_online.php with the ZC 1.5.5 version of it did not correct the loss of the session.

That's helpful to know. That would have been one of my first diagnostics too. Perhaps maybe it's something that changed in init_sessions or functions/sessions.php?

**Comment by drbyte** [comment]
Interestingly, I discovered the same issue on a 1.5.5e cart.

**Comment by drbyte** [comment]
Credit to @scottcwilson, this seems to fix it:

```diff
                if ('cart' === $key) {
-                  $end_cart = (int)strpos($session_data, '|', $start_field[$key] + strlen($value));
-                  $end_cart = (int)strrpos(substr($session_data, 0, $end_cart), ';}');
-                  $session_data_field[$key] = substr($session_data, $start_field[$key], ($end_cart - $start_field[$key] + 2));
+                  $end_cart = (int)strpos($session_data, 'check_valid|s');
+                  $session_data_field[$key] = substr($session_data, $start_field[$key], ($end_cart - $start_field[$key]));
                }
```

**Comment by drbyte** [comment]
I'm changing the file's line-endings from CRLF to LF for consistency. This makes it a huge uncomparable diff, hence posting the fix above.
I'm tidying some other things in the file's code while I'm at it. Just adding some line breaks for readability and changing some ternary true:false to a straight return.

**Comment by scottcwilson** [comment]
Code hygiene matters! :)
