### ISSUE TITLE
Strict MySQL errors thrown for paypalwpp processing.

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#2310]
As reported in [this ](https://www.zen-cart.com/showthread.php?225365-Problem-of-checking-out-the-cart-PHP-error-1264-Out-of-range-value-for-column)Zen Cart thread, there are some database errors that can be throw for more strict versions of MySQL.

Still waiting to see the length to which the `paypal::payment_type` should be expanded, but the **Out of range value for column 'exchange_rate'** issue can be corrected by casting that field's value to a float, on/around line 536 of `includes/modules/payment/paypalwpp.php`:

```php
                          'mc_currency' => $this->responsedata['PAYMENTINFO_0_CURRENCYCODE'],
                          'settle_amount' => (float)urldecode($this->responsedata['PAYMENTINFO_0_SETTLEAMT']),
                          'settle_currency' => $this->responsedata['PAYMENTINFO_0_CURRENCYCODE'],
                          'exchange_rate' => (urldecode($this->responsedata['PAYMENTINFO_0_EXCHANGERATE']) > 0 ? (float)urldecode($this->responsedata['PAYMENTINFO_0_EXCHANGERATE']) : 1.0),
```

**Comment by drbyte** [comment]
Closed in fad7aa434
