### ISSUE TITLE
admin/includes/modules/product/preview_info.php: Back button is old-style image

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2327]
The Back button is old image style, the Update/Insert and Cancel buttons are text-style.

![Clipboard01](https://user-images.githubusercontent.com/4391026/57167931-e3f3bb00-6dff-11e9-9590-22931df96494.gif)

Suggest change:

```
echo ( (isset($_GET['search']) && !empty($_GET['search'])) ? zen_draw_hidden_field('search', $_GET['search']) : '') . ( (isset($_POST['search']) && !empty($_POST['search']) && empty($_GET['search'])) ? zen_draw_hidden_field('search', $_POST['search']) : '');

        echo zen_image_submit('button_back.gif', IMAGE_BACK, 'name="edit"') . '&nbsp;&nbsp;';
       
 if (isset($_GET['pID'])) { 
```

to

```
echo ( (isset($_GET['search']) && !empty($_GET['search'])) ? zen_draw_hidden_field('search', $_GET['search']) : '') . ( (isset($_POST['search']) && !empty($_POST['search']) && empty($_GET['search'])) ? zen_draw_hidden_field('search', $_POST['search']) : '');

        <button type="submit" class="btn btn-default" name="edit" title="<?php echo IMAGE_BACK; ?>"><?php echo IMAGE_BACK; ?></button>

        <?php if (isset($_GET['pID'])) {
```

**Comment by Zen4All** [comment]
I tried that when I revamped the pages, but it did not work. That's why it is still in it's old style. But if you say it does work, I will try this change to see if I was wrong.

**Comment by Zen4All** [comment]
Just tested again, and this solution stil does not work. When clicking you are forwarded to the listing page.

I think we actually need something like zen_back_link

**Comment by torvista** [comment]
> When clicking you are forwarded to the listing page
Doh, I didn't even register that!
I guess this is also relevant for the Back button not working on the metatags preview page:
https://github.com/zencart/zencart/issues/2307#issuecomment-487272070

**Comment by Pan2020** [comment]
I had made this issue before, see #2275 !!
I had made suspect on the fact that buttons are more than just the "button" since there is more stuffs involved.
Also, due to the back button here is `<input>` and not `<button>` like some other converted "Back" button. Therefore, it is surely have to do more than just swap `<input>` into HTML5 with CSS.
