### ISSUE TITLE
checkout payment: if T&C enabled, make required

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2344]
includes/templates/template_default/templates/tpl_checkout_payment_default.php
change
`<?php echo  zen_draw_checkbox_field('conditions', '1', false, 'id="conditions"');?>`
to
`<?php echo zen_draw_checkbox_field('conditions', '1', false, 'id="conditions" required');?>`

and so avoid any more javascript shenanigans,
https://github.com/zencart/zencart/issues/535

**Comment by torvista** [comment]
..this would be ok normally, but as the code currently stands, adding a coupon will also require this to be ticked so the page can be reloaded...so bear that in mind if you use coupons.
This has a bearing on this too:
https://github.com/zencart/zencart/issues/2342

**Comment by torvista** [comment]
To recap, adding or removing a coupon requires a page reload.
If T&C is required and made 'required', coupon add/remove will also require this to be ticked each time. Irritating for the user.

What is the suggested solution for this?

T&C checkbox could be made sticky, that's half the irritation removed.

Make the coupon and page submit separate forms....not sure about that.

**Comment by scottcwilson** [comment]
@torvista You did some work on this - are you willing to close this issue?

**Comment by torvista** [comment]
Currently if T&C is true but unticked, the Continue button is shown but disabled: clicking on it generates no message/feedback to the user.
If the T&C checkbox was set to "required", at least there would be a browser message/no need for any JS on the button.
While my posts above indicate there is more to consider to make this ideal, I think it should be at least "required" for now.

**Comment by scottcwilson** [comment]
If you submit a PR I'll merge it. Thanks.

**Comment by torvista** [comment]
By making the checkbox required, it seems that this becomes redundant.
https://github.com/zencart/zencart/blob/37992f227ecfecc5e233aa562726ea85f7b91f5f/includes/modules/pages/checkout_payment/jscript_main.php#L25-L42
In fact having the Continue disabled it prevents the browser popup notice on the checkbox.

**Comment by brittainmark** [comment]
Has this been fixed by : Disable continue if T&C not present #4833

**Comment by torvista** [comment]
I think my last two posts are stil valid: the current situation is not ideal.

**Comment by brittainmark** [comment]
Yes Agreed. Not sure if making required. Solved the issue. I was trying to stop reentry of cc details being required. Another option may be to spoof disable with JavaScript and present a pop-up with information.

**Comment by torvista** [comment]
With required, the browser disables the submit and puts a popup on the required checkbox. That seems the most  user-friendly solution for T&C.

**Comment by brittainmark** [comment]
I think if I change line 199 in 
from
`<?php echo  zen_draw_checkbox_field('conditions', '1', false, 'id="conditions"');?>`
to
`<?php echo  zen_draw_checkbox_field('conditions', '1', (isset ($_POST['conditions']) && ($_POST['conditions'] == '1')), 'id="conditions"  required');?>`
This populates the checked field if it is set and makes it required.
I need to get gift vouchers working to test it out. 
Obviously, if you are using gift vouchers and a cc to pay, you would need to enter the gift voucher info first, or you would lose the cc details you have entered.
When I have gv working, I'll see how it looks.
NOTE: I am not looking at one-page checkout!

**Comment by brittainmark** [comment]
OK done some more testing. I need to set $_SESSION['conditions'] to keep the tick box ticked when processing gift vouchers.
A question.
If someone leaves the checkout process, should the $_SESSION['conditions'] be remembered or should it be reset when you enter the checkout process?
