### ISSUE TITLE
checkout_process - no cartID check

### ISSUE THREAD

**Issue by robryanx** [zencart/zencart#2349]
I notice on 1.56 there is a cartID check on checkout_payment and checkout_confirmation but not checkout_process, meaning that someone can navigate to the confirmation page, add products in another tab, then submit a changed order.

Am I overlooking something? Maybe it wasn't an issue in normal flows? Paypal in context I believe would just charge the new amount? Noticed it in the context of payment methods like Afterpay and Zippay which work similar to incontext and generate a token from an overlay on the payment page, but authorise for the exact amount only.

Could also be an issue in terms of shipping calculation.

**Comment by zcwilt** [comment]
Hmm.
I've checked code, going all the way back to our original beta release and can't find a time where we ever checked the cartID in checkout process. However I do note that the check does exist in the original `osc` code.

Will try and do some more digging as to why we never included this code, if possible.

**Comment by robryanx** [comment]
A much bigger related change is that there isn't any payment lifecycle method to clear an active payment, for token based payment methods like Paypal where a customer is directed back with a token to continue the checkout. Basically the order_totals `clear_posts` but for payments.

I ended up with something like this:
```php
if (isset($_SESSION['cart']->cartID) && $_SESSION['cartID']) {
  if ($_SESSION['cart']->cartID != $_SESSION['cartID']) {
    $payment_modules->clear_payment();
    $order_total_modules->clear_posts();
    unset($_SESSION['payment']);
    unset($_SESSION['shipping']);

    $messageStack->add_session('checkout_shipping', ERROR_CART_ALTERED, 'error');
    zen_redirect(zen_href_link(FILENAME_CHECKOUT_SHIPPING, '', 'SSL'));
  }
}
```

And for example for Paypal you would end up with something like this:

```
public function clear_payment()
{
    unset($_SESSION['paypal_ec_temp']);
    unset($_SESSION['paypal_ec_token']);
    unset($_SESSION['paypal_ec_payer_id']);
    unset($_SESSION['paypal_ec_payer_info']);
    unset($_SESSION['paypal_ec_markflow']);
    unset($_SESSION['paypal_ec_incontext']);
}
```
