### ISSUE TITLE
Shipping tax still displays for coupon that includes free shipping

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#2353]
If a coupon with some form of _Free Shipping_ is applied to an order with a **taxed** shipping cost, the order's shipping tax _is_ removed from the order's total, but the associated `tax_class` is not reduced by the shipping cost's tax.  For instance (on a store that displays prices with tax), if the original order shows:
```
Sub-Total:                   $38.50
Per Item (Best Way):          $5.50
FL TAX 10%:                   $4.00
Total:                       $44.00
```

... and a coupon that offers a 100% discount with free shipping is applied, the order then shows:
```
Sub-Total:                   $38.50
Per Item (Best Way):          $5.50
Discount Coupon: ALLFREE :  -$44.00
FL TAX 10%:                   $0.50  <-- Shouldn't be there
Total:                        $0.00
```

PR forthcoming, once I validate the various paths.

**Comment by drbyte** [comment]
Fixed in #2354
