### ISSUE TITLE
Back button is now saving instead of going back

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#2357]
https://github.com/zencart/zencart/blob/53e277eb10894031d09424202d68c460847a6855/admin/includes/modules/product/preview_info.php#L162
I am not sure who tested this,but this updated back button is wrong. If the fix was this easy I would have changed it to this ages ago.
Now if you make edits to a product, go to preview and then press back. The product is saved and you are returned to the product listing.
You can have only submit button in a form. Multiple submit buttons will all do the same thing.
Until a working solution is found, the old style button should be used in the code

**Comment by drbyte** [comment]
> Now if you make edits to a product, go to preview and then press back. The product is saved and you are returned to the product listing.

Um, no, only if you didn't update both affected files.

**Comment by drbyte** [comment]
![Screen Recording 2019-05-26 at 04 35 PM](https://user-images.githubusercontent.com/404472/58386902-6709ca80-7fd4-11e9-88a9-9959d64a3150.gif)

**Comment by Zen4All** [comment]
You're right, it works. 👍 . Not sure what happened yesterday, as I did update all files.maybe something got cached. Tested again this morning, and all is working as it should
