### ISSUE TITLE
admin, customers.php: form anchor/name "setstatus" already defined

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2368]
![Clipboard02](https://user-images.githubusercontent.com/4391026/58476541-4dda5880-8151-11e9-87fd-db6a60e2ed45.gif)

**Comment by torvista** [comment]
There are other validation errors raised due to the inputs and a-links on each line being descendants of the tr which has a role="button".
But, nothing else flagged for this file.

**Comment by scottcwilson** [comment]
Fix submitted. #2377
