### ISSUE TITLE
156b: catalog, edit account, DOB error checking

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2370]
If I enter 1970-21-05 it accepts it, but stores 1970-01-01.
related:
https://www.zen-cart.com/showthread.php?221024-Changing-the-Date-Format-to-UK

Time for a rethink?
What I mean is that I am finding it confusing from a user point of view with respect to there are now two formats for entering dates (with their associated empty-field example formats) and how they may be displayed subsequently/differently, based on likely modifications to the language files.
catalog-account edit and admin account-edit.
From a short time testing with vanilla 156b and my 155 production (UK-modified) shop and in-progress (UK-modified)  upgrade I see inconsistencies that look like a rabbit-hole I don't want to go down.

**Comment by mc12345678** [comment]
Have you tried on your ZC 1.5.5 version to attempt editing the date of birth field while using the responsive_classic template in mobile mode? (index.php?main_page=account_edit&layoutType=mobile)

It won't accept a date-of-birth entry without at least the modification that was incorporated into 1.5.6b. Yes that incorporation did not perform an additional validation of an invalid manually entered date such as performed above. The additional commits referencing this issue perform that check, notifying the customer of the expected format and display of the entered value.

As to forcing one method of entry only, before embracing jQuery into the front end, that's the way it was. Just that the sequence of entry could be modified to suit,
