### ISSUE TITLE
ZC156b: admin, functions_general.php has hard-coded text warnings

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2373]
I guess the fact this is in a function means the error needs be passed back to the calling page and dealt with there?
Still,l I don't find any other direct reference to this issue.

```
      $messageStack->add_session('<b>WARNING: Cannot copy from Product ID #' . $products_id_from . ' to Product ID # ' . $products_id_to . ' ... No copy was made' . '</b>', 'caution');
    } else {
      if (!zen_has_product_attributes($products_id_from, 'false')) {
        // no attributes found to copy
        $messageStack->add_session('<b>WARNING: No Attributes to copy from Product ID #' . $products_id_from . ' for: ' . zen_get_products_name($products_id_from) . ' ... No copy was made' . '</b>', 'caution');
      } else {
        // invalid products_id
        $messageStack->add_session('<b>WARNING: There is no Product ID #' . $products_id_to . ' ... No copy was made' . '</b>', 'caution');
```

**Comment by lat9** [comment]
For the function's use, the messages could be defined in an `admin/includes/languages/english/extra_definitions/` file.  That way, they're available for each page-load.

**Comment by torvista** [comment]
I'm working on a PR for product copy: to include copy also metatags and linked categories from work I did eons ago. It had the same hard-coded message stack stuff, 
Maybe I will include a change to "fix" this too.

**Comment by torvista** [comment]
I included it in this PR
https://github.com/zencart/zencart/pull/2383
