### ISSUE TITLE
ZenCart v157 branch 

### ISSUE THREAD

**Issue by mesnitu** [zencart/zencart#2374]
Hi
Just to check if v1.5.7 is to receive fixes from 1.5.6b and will be the last 1.5 version or a lot of stuff is going to change in 157

**Comment by torvista** [comment]
I was going to ask sort of the same thing...should PRs be based on 156b or 157?

**Comment by drbyte** [comment]
PRs for serious bugs can go against v156.

All others, including improvements or "bugs-me-fixes" or new features, will go against v157.

**Comment by zcwilt** [comment]
Actually just  to be absolutely clear here.
All new pull requests must be against the v157 branch. 
PR authors can state if they think the PR should be backported to `v156` in the issue/pull request, but the dev team will `triage` and if warranted will add a `backport` tag to the PR

For any PR's that have already been done against `v156`, please do not amend or add another PR for `v157`, we can change the base branch ourselves.
