### ISSUE TITLE
admin: products to categories changes

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2384]
Hi,
long ago Conor did a mod for me 
https://www.zen-cart.com/downloads.php?do=file&id=1228
to add functionality to this, and make an ordered list of the categories as shown in the screenshots.

Current/157, no selection:
![p2c_old](https://user-images.githubusercontent.com/4391026/58727303-349d0a80-83e4-11e9-946a-89b6262832d4.gif)

My version adds this:
![p2c_new](https://user-images.githubusercontent.com/4391026/58727351-5a2a1400-83e4-11e9-9e67-55c39a14ac60.gif)

Current listing:
![p2c_old_list](https://user-images.githubusercontent.com/4391026/58727373-6910c680-83e4-11e9-925f-746774bae65c.gif)

My version:
![p2c_new_list](https://user-images.githubusercontent.com/4391026/58727390-74fc8880-83e4-11e9-9a00-831fa2258039.gif)

Would a PR be accepted to include this?

**Comment by drbyte** [comment]
Sure.

**Comment by torvista** [comment]
Next time you mess with the install and upgrade sql, can you register this page as a link from 
Admin->Catalog.

**Comment by scottcwilson** [comment]
Sure - submit your PR, then create a new issue and tag me and I'll take care of it.

**Comment by torvista** [comment]
ok. The leap from the last PR to adding Conors mods is a big one. While it all works of course, it doesn't look like core code so I was going to update the plugin and invite input while it's standalone.
I'll PR the install sql soon though for the Admin link.

**Comment by torvista** [comment]
I'm closing this for now until it is ready for primetime.

**Comment by torvista** [comment]
The first working draft of this is now up for testing. Awesome code from Conor RIP, but a merge from hell with the jump from 155 to 157.
I have not cleaned up the code at all yet (comments, merge comments, debugs etc. to help me refer back to previous versions), just interested in functionality testing.
The code uses Ceon custom functions which may have use generally for displaying sorted full category paths for the category copy/delete infoboxes....or could be used as a basis to enhance the current categories functions...
 https://github.com/torvista/zencart/tree/products_to_categories

Further work is to look at sorting options for the product display.

**Comment by torvista** [comment]
inexplicably merged...
https://github.com/zencart/zencart/pull/3066
