### ISSUE TITLE
products_id validation on first load init_sanitize?

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#2428]
At one point a Zen Cart poster was asking about how to address URI information such as an invalid `products_id` and/or `cPath` value.  When I went looking at the page load process, I found that `includes/init_includes/init_sanitize.php` has a "sanitization" of the products_id; however, it only triggers once a session has begun and basically this set of code has been executed once before for the session. Ok, so carry on with the page load and it seems that the applicable product type has its own "check" of if at least the `products_id` exists, though it is with a different query (meaning DB does get asked for the same "answer" but with two different questions).

Anyways, what is the reason that `init_sanitize.php` has:
````php
/**
 * validate products_id for search engines and bookmarks, etc.
 */
  if (isset($_GET['products_id']) && isset($_SESSION['check_valid']) &&  $_SESSION['check_valid'] != 'false') {
    $check_valid = zen_products_id_valid($_GET['products_id']);
    if (!$check_valid) {
      $_GET['main_page'] = zen_get_info_page($_GET['products_id']);
      /**
       * do not recheck redirect
       */
      $_SESSION['check_valid'] = 'false';
      zen_redirect(zen_href_link($_GET['main_page'], 'products_id=' . $_GET['products_id']));
    }
  } else {
    $_SESSION['check_valid'] = 'true';
  }
````
instead of (Note the changes in the initial `if` statement and the absence of the `else`):
````php
/**
 * validate products_id for search engines and bookmarks, etc. on first and all following visits.
 */
  if (isset($_GET['products_id']) && (!isset($_SESSION['check_valid']) || $_SESSION['check_valid'] != 'false')) {
    $check_valid = zen_products_id_valid($_GET['products_id']);
    if (!$check_valid) {
      $_GET['main_page'] = zen_get_info_page($_GET['products_id']);
      /**
       * do not recheck redirect
       */
      $_SESSION['check_valid'] = 'false';
      zen_redirect(zen_href_link($_GET['main_page'], 'products_id=' . $_GET['products_id']));
    }
  }
 
  $_SESSION['check_valid'] = 'true';
````

Expectation of the revised code is that on the first page load the sanitization will execute, if the page gets redirected because the `products_id` was invalid then the inner check will be omitted, if the page never redirects because of an invalid `products_id` then `$_SESSION['check_valid']` will be `'true'`.  Not entirely sure what effect this change has on downstream processes, but it seems like it offers an earlier detection. Part of the question is if it was intentionally designed to have a delayed operation and to just let the associated `product_type` somewhat deal with it?

**Comment by drbyte** [comment]
Appears to have been fixed in #2510
