### ISSUE TITLE
Admin, infobox, classes/table_block.php - params incorrect

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2429]
Regarding the array passed to 
`function tableBlock($contents) {`

From the calling code (eg modules/copy_product.php), two array components can be included in the class:
['align']: this text gets inserted as-is in the class. So it should be a css selector.
['params']: this is a single word that ALSO gets inserted as-is in the class.
This doesn't seem right...I would have assumed that params would be a complete string
eg: id="whatever" 
to be added **after** the class.
So I think this param is currently redundant but should be fixed to allow correct insertion of a parameter.

> $tableBox_string .= '<div class="row';
>             if (zen_not_null($this->table_row_parameters)) {
>               $tableBox_string .= ' ' . $this->table_row_parameters;
>             }
>             if (isset($contents[$i][$x]['align']) && zen_not_null($contents[$i][$x]['align'])) {
>               $tableBox_string .= ' ' . $contents[$i][$x]['align'];
>             }
>             if (isset($contents[$i][$x]['params']) && zen_not_null($contents[$i][$x]['params'])) {
>               $tableBox_string .= ' ' . $contents[$i][$x]['params'];
>             } elseif (zen_not_null($this->table_data_parameters)) {
>               $tableBox_string .= ' ' . $this->table_data_parameters;
>             }
>             $tableBox_string .= '"';
>             $tableBox_string .= '>';

There are two instances of this code, I see in Develop that it is modified but still has the problem.

**Comment by scottcwilson** [comment]
Are you sure admin/includes/modules/copy_product.php is actually using `tableBlock`? I thought the only use was in messageStack.

**Comment by torvista** [comment]
ADMIN only
to summarise, both the align and params are added to the class

div class="row HERE".....

so they are really both class styles, not alignments nor parameters (unlike the catalog-side version).
The only use of params is by the admin messagestack.
The example useage in boxes.php is wrong

> Example usage:
  $heading = array();
  $heading[] = array('params' => 'class="menuBoxHeading"',

So to make this all "logical", the array instances of align and params should be renamed class and the section in table_block should add a full parameter after the class.
So, there is no bug, this is legacy code that is confusing.
