### ISSUE TITLE
admin reviews Edit button broken/redundant / bug in admin/product.php

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2430]
On the admin review listing, there are three buttons in the infobox.
![Clipboard01](https://user-images.githubusercontent.com/4391026/59163874-9527f800-8b06-11e9-8c54-9445900e9c50.gif)
The third "Details" links to 
ADMIN/product.php?cPath=2117&pID=2855
which is nothing at all: header and footer with no body content...since there is no action set and product.php has no fallback for no action.

I'm working on a PR for the reviews page and will fix the button to point to edit product, 
but also product..php currently has
`$action = (isset($_GET['action']) ? $_GET['action'] : '')`
maybe it should be
`$action = (isset($_GET['action']) ? $_GET['action'] : 'new_product')`

**Comment by drbyte** [comment]
@Zen4All are you interested in tackling the `product.php` button?

**Comment by Zen4All** [comment]
:+1:

**Comment by Zen4All** [comment]
@torvista Can you please tell me on which page this is happening, as I seem to be unable to find it.

**Comment by torvista** [comment]
I think you have fixed it already no?

**Comment by Zen4All** [comment]
Could be 😃. Could you please check? So we can solve or close?

**Comment by torvista** [comment]
fixed.
