### ISSUE TITLE
admin, constant TEXT_GV_REDEEM repeated

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2432]
declared in english.php and again in gv_name.php

**Comment by torvista** [comment]
related
https://github.com/zencart/zencart/pull/2444#issue-288640922

**Comment by scottcwilson** [comment]
Yep, basically the same problem.

**Comment by torvista** [comment]
define('TEXT_GV_REDEEM','Redemption Code');
is now defined in english.php...for global use.

But, if embedded/used in another constant definition in admin gv_mail.php,
that gives a php error as english.php has not loaded prior to this language file.

Similarly for admin gv_sent where it is used for a table heading (and is missing/causes an error).

In the current constant-loading method, it does not look like one constant will do.
It seems to me that this constant needs to be defined in the language file for on each admin page that uses it, then if !defined put around the global definition in english.
