### ISSUE TITLE
admin, category_product_listing, $order_by not defined, php error

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2433]
Shown up by Report All Errors.
There is no default, so $order_by may not be defined.
            

> switch ($_SESSION['categories_products_sort_order']) {
>                 case (0):
>                   $order_by = " ORDER BY c.sort_order, cd.categories_name";
>                   break;
>                 case (1):
>                   $order_by = " ORDER BY cd.categories_name";
>                 case (2);
>                 case (3);
>                 case (4);
>                 case (5);
>                 case (6);
>               }

Similarly for products,

**Comment by scottcwilson** [comment]
This variable is set in admin according by a defined set of possible values (0-6) - it must have a value and can't be outside this range.  So this really isn't a flaw (you could add anti-bugging and make 0 the default I guess, but not sure it's worth it).

**Comment by torvista** [comment]
Ok, but still, an error gets triggered.
To trigger this, install Report All Errors and enable it for the admin.
Go into a category with products and change the sort order to Products Model

> PHP Notice:  Undefined variable: order_by in .....\category_product_listing.php on line 623

Which is the last line of the sql:
```
               $categories = $db->Execute("SELECT c.categories_id, cd.categories_name, cd.categories_description, c.categories_image,
                                                   c.parent_id, c.sort_order, c.date_added, c.last_modified, c.categories_status
                                            FROM " . TABLE_CATEGORIES . " c, " . TABLE_CATEGORIES_DESCRIPTION . " cd
                                            WHERE c.parent_id = " . (int)$current_category_id . "
                                            AND c.categories_id = cd.categories_id
                                            AND cd.language_id = " . (int)$_SESSION['languages_id'] .
                                            $order_by);
```

But this is a **category** query, so, there is something else amiss here.

**Comment by mc12345678** [comment]
For the provided code, the below change of the affected code section would eliminate the error and maintain operation as it was previously provided.

````php
case (1):
$order_by = " ORDER BY cd.categories_name";
break;
case (2);
case (3);
case (4);
case (5);
case (6);
$order_by = '';
````

The difference being to add a break after the assignment for case 1 and to assign an empty string for all subsequent values.

**Comment by scottcwilson** [comment]
I think @torvista  is already working on this in his PR: #2443

**Comment by torvista** [comment]
No, that commit is for products-to-categories.

**Comment by scottcwilson** [comment]
Ah, right you are.  Fixed.
