### ISSUE TITLE
unnecessary log files from hackers....

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#2434]
try:

yoursite.com/type.php?template=tag_()%7%2011%20B%7D;@unlink(FILE);eval($_POST%5Bqazw%5D);print(md5(999));%7B//../rss

something i see frequently (or similar attempts).  this generates unnecessary log files:

PHP Fatal error:  Uncaught Error: Call to a member function get_template_dir() on null

i have found that modified the code here:

https://github.com/zencart/zencart/blob/d139166b2f210ae416fea2337d5b9f32b9c3a51e/includes/languages/english/credit_cards.php#L49

and adding above:
```php
if (is_null($template)) {
    zen_redirect(FILENAME_DEFAULT);
}
```

resolves this issue.

**Comment by drbyte** [comment]
Your code suggestion is fine as a patch for older versions.

I've chosen to fix it differently in v157: https://github.com/zencart/zencart/commit/fc8c53d7b14854d2aeaf783ea43273a9ac061c01
