### ISSUE TITLE
product_to_categories: action edit_update not used

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2439]
I believe this clause is not required...the only place action edit_update occurs is in products price manager.
```
<?php
        if ($action != 'edit_update') {
          require(DIR_WS_MODULES . FILENAME_PREV_NEXT_DISPLAY);
          ?>
```

**Comment by drbyte** [comment]
@Zen4All - Thoughts?

**Comment by Zen4All** [comment]
I'll check it tomorrow

**Comment by Zen4All** [comment]
@torvista 
I can not find the mentioned code in 'admin/products_to_categories.php'

**Comment by torvista** [comment]
>I can not find the mentioned code in 'admin/products_to_categories.php'

...not anymore! I didn't include it in the PR I made....which has now been committed.
It is in the previous version:
https://github.com/zencart/zencart/blob/16cebdf36013bd1949623629bbfab705a5f2d81d/admin/products_to_categories.php

**Comment by Zen4All** [comment]
So this is solved and can be closed?

**Comment by torvista** [comment]
I guess so!
