### ISSUE TITLE
admin, mail.php: php notice undefined index message_html

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2455]
Admin-> Email Options->Enable HTML emails.
Enter Send email

> PHP Notice:  Undefined index: message_html in ...\zencart-157\admin1\mail.php on line 297

Which is in 
```
                <?php
                if (EMAIL_USE_HTML == 'true') {
                  echo zen_draw_textarea_field('message_html', 'soft', '100%', '25', htmlspecialchars(stripslashes($_POST['message_html']), ENT_COMPAT, CHARSET, TRUE), 'id="message_html" class="editorHook form-control"');
                } else {
                  echo TEXT_WARNING_HTML_DISABLED;
                }
                ?>
```
I would have thought the reference to  $_POST['message_html'] would have been substituted for a cleaned/set variable at the top of the script....

**Comment by scottcwilson** [comment]
I don't get this in PHP 7.2.13. What is your configuration?

**Comment by torvista** [comment]
7.3.4 using Report All Errors

**Comment by scottcwilson** [comment]
Thanks that was my issue - needed higher PHP.
