### ISSUE TITLE
fn: zen_remove. $zen_remove_error may not be set and missing constant

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2456]
```
  function zen_remove($source) {
    global $messageStack, $zen_remove_error;

    if (isset($zen_remove_error)) $zen_remove_error = false;
```
Why is this not just:

`$zen_remove_error = false;`
otherwise it is never set if there are no errors,

and constant
ERROR_DIRECTORY_NOT_REMOVEABLE is not defined.

**Comment by scottcwilson** [comment]
I don't think the code suggestion is correct; it is set outside the function or inside it.
Fixed the define.

**Comment by torvista** [comment]
If it already set outisde the function, it is overwritten to false.
Then if there is an error it is changed to true.

If it is NOT set outside the function and there is NO error, it stays undefined.

So anything that uses the function has to check if it's set before evaluating it. One would assume the function will return a value true/false, not true or unset/or maybe false.

**Comment by drbyte** [comment]
As far back as v1.3.7 this section of code remains unchanged, and in that same timeframe nowhere else in core code has ever used that variable in global scope.
The function is only called from within itself, recursively, and in more recent versions also from the log-cleaner in Store Manager, and neither cares about that variable's value.

I think I'd do as @torvista suggests: remove the `isset` and just set it to false.
I'd also remove it from the `globals` list inside the function, and I'd `return` the variable's value at the end of the function in case the calling code wants to know the status.

**Comment by torvista** [comment]
> I'd also remove it from the globals list inside the function, and I'd return the variable's value at the end of the function in case the calling code wants to know the status.
Does that mean you are going to do that?

I found this issue in the first place as BackupMysql (both Plugins and my version) references it, so I don't want it to be forgotten and re-discovered again subsequently, now this is closed.

**Comment by drbyte** [comment]
> > I'd also remove it from the globals list inside the function, and I'd return the variable's value at the end of the function in case the calling code wants to know the status.
> 
> Does that mean you are going to do that?

I might. Time permitting. A PR is welcome. 
Issue re-opened so we don't lose track of it until it's done.

> I found this issue in the first place as BackupMysql (both Plugins and my version) references it.

It would be good to provide this sort of context in the future when posting an issue. I did wonder "why" you'd bothered to post about something like this that probably wouldn't be flagged by code analysis tools. But I tire of asking people "why?" all the time. Maybe I'll have to go back to that.
