### ISSUE TITLE
"classic" folder should be deprecated

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2480]
The "classic" folder exists to indicate to the user which folders can be overridden by template files. 

We could allow "responsive_classic" to serve this same purpose, and remove the existing "classic" folders.  

**Remove**: 
./includes/languages/classic
./includes/languages/english/classic
./includes/languages/english/extra_definitions/classic
./includes/languages/english/html_includes/classic
./includes/languages/english/modules/order_total/classic
./includes/languages/english/modules/payment/classic
./includes/languages/english/modules/shipping/classic
./includes/modules/classic
./includes/modules/sideboxes/classic
./includes/templates/classic
./includes/index_filters/classic  (assuming #2629 is merged)

**Create**: 
./includes/languages/responsive_classic
./includes/languages/english/modules/order_total/responsive_classic
./includes/languages/english/modules/payment/responsive_classic
./includes/languages/english/modules/shipping/responsive_classic
./includes/modules/sideboxes/responsive_classic
./includes/index_filters/responsive_classic

**Already Present**: 
./includes/languages/english/extra_definitions/responsive_classic
./includes/languages/english/html_includes/responsive_classic
./includes/languages/english/responsive_classic
./includes/modules/responsive_classic
./includes/templates/responsive_classic

**Comment by torvista** [comment]
My view is that the example template folders should never be touched....they should be copied.
So how about naming them appropriately, like "example_responsive1", "example_classic".
Maybe retire classic once and for all...what purpose does it serve that responsive does not?

**Comment by lat9** [comment]
Just remember, too, that there's _guidance_ sprinkled in various wikis and readme.txt files that identify that template-override locations are identified by the inclusion of `/classic` sub-directories in various spots.

**Comment by wiztechinc** [comment]
No! Not everyone wants to use that dang responsive code. Most existing templates out there don't. I don't and having a default normal template base to use to prove problems or lack of problems is definitely muddied by the complicated responsive.  Just keep it.

**Comment by dbltoe** [comment]
IMHO, that's what I used to call "clinging tenaciously to the trailing edge of technology."  With SE ranking being affected by a lack of responsive sites, I would prefer that the respsonsive_classic become just classic.  Maybe use the ZCA or Color change the responsive_classic.
Keep template_default as is and, if wanted, add the ZCA Bootstrap.
We will provide a far better out-of-the-box product.

**Comment by scottcwilson** [comment]
@wiztechinc No one is forcing you to use anything.  Furthermore, the classic folder is not actually used; what's used is template_default in the event of a fallback.  Classic is for documentation only. 

@lat9 Yes, we will want to update the documentation if this change is approved by the core team.

**Comment by mc12345678** [comment]
> Furthermore, the **classic folder is not actually used; what's used is template_default in the event of a fallback. Classic is for documentation only**.

This is incorrect. If that were truly so, then why for example are there differences between:
includes/templates/classic/css/stylesheet.css and
includes/templates/template_default/css/stylesheet.css?
or the use of includes/languages/english/classic/header.php and why it is different than the default version and not overridden in the responsive_classic version?

Further having an empty template folder makes it far easier to develop and code than to try to muddle through other code to figure out if the problem is the base code or something added.

What is being done to engage other template developers to engage in the community part of development? Seems the last one that did this a lot has not been nearly as supportive any time recently. Yes yet another template type is described above which nearly gives reason for something like classic to still exist so that there is a blank surface readily available for development.

I guess I just don't see the need to get rid of it or what it is hurting and what problem it causes. What does this accomplish other than just changing something to say that it has changed?

**Comment by scottcwilson** [comment]
I see your point.  Let me reframe my complaint. 

We curently have TWO ugly non-reponsive templates.  Let's skinny this down to just ONE ugly non-responsive template. 

> What is being done to engage other template developers to engage in the community part of development? 
This is a great question.   If each of us (@mc12345678, @lat9, @scottcwilson) were to add or update a template, there would be three more decent up to date templates.  I think other template developers want to see activity and growth in Zen Cart before they commit resources. We can help this happen, but of course it's not guaranteed.

**Comment by wiztechinc** [comment]
Let's see - engaging other template developers. Well, it seems like everything suggestion I've had or anything I've objected to in the past 5 years has been ignored. There is not one way to do things and working cooperatively to develop an open source project should allow for more criticism. Calling anything obnoxious does not further conversation. How about just listening? Don't want to stir up more controversy but ..... stop shooting people down!

**Comment by drbyte** [comment]
@wiztechinc wrote:
> Considering the fact that a responsive template that passes google inspection only requires a bit of php code and some CSS changes, as I have always said, bootstrap templates are bloated and unnecessary. Oh, not to mention hard to alter. Back to my usual complaint

Delia, yes, you've been objecting to all approaches taken towards responsive features. Your comments have been noted, but I can't find where you've explained exactly the steps that should be taken to get full responsive support "without the bloat" as you call it. An objection is fine, but in the absence of working suggestions, other approaches have been taken. That doesn't mean they've been "the best" or the "easiest", nor does it mean they've been "wrong" or "incorrect". They "work", but clearly you think they could "work better". So this is an invitation to show a better way.
Would you be willing to contribute a template that provides full responsive capability "without the bloat"?

**Comment by lankeeyankee** [comment]
I also vote for getting rid of classic. And if sticking with the responsive template, maybe have someone update it for 2019. It's pretty dated.

**Comment by barco57** [comment]
Not opposed to removing the classic folders, but not bothered if they were left there either.

**Comment by torvista** [comment]
To repost, I think I would still bin classic and maybe rename responsive_classic to "example1" to prevent people touching it/encourage them to clone it, it is still a valid starting point.

**Comment by torvista** [comment]
Once this

https://github.com/chadlly2003/zencart_responsive_classic_redesign

is ready, since template_default is supposedly the reference, I think it should be updated to html5 and formatted etc. so all future templates can be easily compared/only **real** differences show up in comparison software.

And bin classic.
