### ISSUE TITLE
Managing language defines shared between admin and storefront

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2518]
I'd like to consolidate defines which are commonly updated and exist both on the catalog and admin side.  As an example, in includes/languages/english/email_extras.php (and admin/includes/languages/english/email_extras.php), we have defines for EMAIL_FOOTER_COPYRIGHT.  If we put this in one place, users would only have to update it once and get it automatically in admin->tools->send email.  

Possibilities include: 
- creating a <filename>_shared.php file at the same level as the current file.
- creating a separate "shared" hierarchy that mirrors the current hierarchy, e.g. includes/languages_shared/english/email_extras.php
- doing a require of the catalog side on the admin side, but checking if !defined for common variables on admin.
- having a single file that contains all the shared defines.
- others?

**Comment by drbyte** [comment]
Does your meaning of the word "shared" here differ from the meaning of "shared" regarding catalog-side template-overrides?

**Comment by scottcwilson** [comment]
Sorry should have been more clear: "shared" between admin and catalog side.  One define used two places.  (Not two defines used one place each.)

**Comment by scottcwilson** [comment]
The shared stuff you are thinking of was in 2.0 wasn't it?

**Comment by drbyte** [comment]
Preference is to avoid adding more subdirectory infrastructure.

Doing catalog-side-includes from the Admin, where the files are identical, makes sense as a consolidation step. 
The challenge with that is your goal isn't to reduce duplicated files, but rather you're wanting to provide template-specific support from the admin side, when it could be any one of various templates that's actually the important one, particularly in multi-language environments.

**Comment by drbyte** [comment]
Closing in favor of @zcwilt pending plugin updates which augments language loading slightly. De-duplication can be re-addressed later.
