### ISSUE TITLE
Flashing tab title in admin

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2570]
I truly hate this.  

Are there enough people that want it that it should be made switchable or can we just get rid of it?  Several customers have asked me to remove it already.

**Comment by mc12345678** [comment]
What flashing is this? I mean, when I login via mobile I may initially get the full menu bar and have to wait for css or related process to revise it to the hamburger menu option which then also moves content on the screen.

**Comment by drbyte** [comment]
Ya, I have no idea what this is referring to either.

**Comment by scottcwilson** [comment]
Login to admin, then let your session time out.  The title on the tab flashes.

**Comment by scottcwilson** [comment]
(at least in Chrome)

**Comment by drbyte** [comment]
1. Please make the title descriptive of the actual problem. "Flashing admin" doesn't mean anything without context. It certainly doesn't reflect that it has anything to do with the "title on the browser tab", nor session timeouts.

2. The flashing is done by the keepalive feature. Sounds like you're not using the feature, in which case you can delete the `/admin/includes/keepalive_module.php` file.

**Comment by drbyte** [comment]
Looks like you can also just add `'flashTitle': false,` to the jTimeout call if you want it to never flash

**Comment by scottcwilson** [comment]
>Looks like you can also just add 'flashTitle': false, to the jTimeout call if you want it to never flash

Yes, that was what I was proposing.   PR ok?

**Comment by drbyte** [comment]
Looks like a newer jTimeout version is available which can be told to stop the tab flashing after session timeout. Submitting a PR with those updates now. Test it and see if it does what you're after.

**Comment by scottcwilson** [comment]
Thank you!

**Comment by scottcwilson** [comment]
Fixed by #2574.
