### ISSUE TITLE
Upgrading from zc154, MODULE_PAYMENT_PAYPALWPP_CHECKOUTSTYLE

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#2575]
The subject setting (for the paypalwpp.php payment method) was not defined in zc154.  After upgrading to zc156b, I'm seeing an undefined constant warning for that setting during the payment method's construction.

Perhaps this section
```php
    if (MODULE_PAYMENT_PAYPALWPP_CHECKOUTSTYLE != 'InContext') {
      $this->use_incontext_checkout = false;
    }
```

should be changed to
```php
    if  (!defined('MODULE_PAYMENT_PAYPALWPP_CHECKOUTSTYLE') || MODULE_PAYMENT_PAYPALWPP_CHECKOUTSTYLE != 'InContext') {
      $this->use_incontext_checkout = false;
    }
```

**Comment by drbyte** [comment]
I assume this is without re-installing the module, right? 

Have you visited the admin payment modules screen at all before this happened? If not, does the problem go away after you do?

We've tried to prevent the need to remove-and-reinstall "core" payment modules by auto-installing missing settings just by visiting the admin payment modules screen, but maybe this setting got past that. If so, it'd be good to make the module install the setting automatically.

**Comment by lat9** [comment]
You're correct @drbyte; I'd not yet navigated to the admin's payment modules screen.

However, since that check is in the class constructor, that code fragment tosses that "Use of undefined constant" PHP Notice on entry to that screen in the admin.

**Comment by lat9** [comment]
Noting that subsequent entries to the admin/payment modules screen no longer tosses that notice as the configuration setting is added on that first entry.

**Comment by lat9** [comment]
Similar issue with authorizenet_aim.php, since MODULE_PAYMENT_AUTHORIZENET_AIM_CURRENCY wasn't previously defined.

At the bottom of the constructor, I suggest changing

```php
    // set the currency for the gateway (others will be converted to this one before submission)
    $this->gateway_currency = MODULE_PAYMENT_AUTHORIZENET_AIM_CURRENCY;
```
to
```php
    // set the currency for the gateway (others will be converted to this one before submission)
    $this->gateway_currency = defined('MODULE_PAYMENT_AUTHORIZENET_AIM_CURRENCY') ? MODULE_PAYMENT_AUTHORIZENET_AIM_CURRENCY : 'USD';
```

**Comment by scottcwilson** [comment]
This seems like a solid suggestion to me.  Cindy, are you going to create the PR?

**Comment by lat9** [comment]
Sure, I'll get one going.

**Comment by lat9** [comment]
Noting that similar issues (i.e. requirement of that one-time after-upgrade navigation to Modules->Payment) exist in the updated versions of authorizenet.php and paypaldp.php.

The a.net change could be handled as above (simply adding the if not defined, use default logic), but the changes to paypaldp.php include a fair amount of database re-organization so it's not as simple.  

Perhaps the `zc_install` instructions (at the end) could be updated to "remind" the person performing the update that they'll need to log into the admin and, at a minimum, navigate to **_Modules->Payment_** to make sure that all the updates are performed.

**Comment by scottcwilson** [comment]
Love the idea, but I'm worried that zc_install is already so noisy that they'd miss it.  What if we just had a flag (set to 0 by each upgrade script) indicating that various release-specific actions needed to be taken, and messaged the admin if the flag was not set to 1 (you must do X action - click here).

**Comment by lat9** [comment]
Like a hidden (i.e. Modules) configuration setting?  

That makes sense to me, since the zc_install process places the site into maintenance-mode, so an admin login is necessary to restore the storefront access anyway.

**Comment by scottcwilson** [comment]
Yes, exactly.

**Comment by drbyte** [comment]
Let's not add extra flags.

I think we can probably trigger the (installed) modules to do their inspect-and-refresh from within zc_install, by pulling (as little as possible of) the code from admin/modules.php which does that.

**Comment by drbyte** [comment]
> we can probably trigger the (installed) modules to do their inspect-and-refresh from within zc_install, by pulling (as little as possible of) the code from admin/modules.php which does that.

Someone wanna test this code by firing it somewhere in zc_install?

```php
<?php
/**
 * zc_install functions
 *
 * @package functions
 * @copyright Copyright 2003-2019 Zen Cart Development Team
 * @license http://www.zen-cart.com/license/2_0.txt GNU Public License V2.0
 * @version $Id: zc_install/includes/functions/installer_funcs.php $
 */

/**
 * Instantiate each shipping/payment/ot module, which in turn causes them to upgrade themselves if coded to do so.
 */
function triggerModuleUpdates()
{
    global $db;
    foreach (['shipping', 'payment', 'order_total'] as $module_type) {
        $module_directory = DIR_FS_CATALOG_MODULES . $module_type . '/';
        $module_key = 'MODULE_' . strtoupper($module_type) . '_INSTALLED';
        $directory_array = [];
        if ($dir = @dir($module_directory)) {
            while ($file = $dir->read()) {
                if (!is_dir($module_directory . $file)) {
                    if (preg_match('~^[^\._].*\.php$~i', $file) > 0) {
                        $directory_array[] = $file;
                    }
                }
            }
            sort($directory_array);
            $dir->close();
        }

        $installed_modules = [];
        foreach ($directory_array as $file) {
            if (file_exists(DIR_FS_CATALOG_LANGUAGES . $_SESSION['language'] . '/modules/' . $module_type . '/' . $file)) {
                @include(DIR_FS_CATALOG_LANGUAGES . $_SESSION['language'] . '/modules/' . $module_type . '/' . $file);
                @include($module_directory . $file);

                $class = substr($file, 0, strrpos($file, '.'));
                if (class_exists($class)) {
                    $module = new $class;
                    if (@$module->check() > 0) {
                        $installed_modules[] = $file;
                    }
                }
            }
        }

        $db->Execute("UPDATE " . TABLE_CONFIGURATION . "
                      SET configuration_value = '" . $db->prepareInput(implode(';', $installed_modules)) . "',
                          last_modified = now()
                      WHERE configuration_key = '" . $db->prepareInput($module_key) . "'");


    }
}
```

**Comment by scottcwilson** [comment]
This is on my list.  Hope to report back soon.

**Comment by scottcwilson** [comment]
Should this ticket be closed? MODULE_PAYMENT_PAYPALWPP_CHECKOUTSTYLE is now auto installed and it seems like using keys() to check for needed configuration updates solves a lot of problems.

**Comment by scottcwilson** [comment]
Please create a PR with this change integrated.

**Comment by drbyte** [comment]
Turns out trying to call this from zc_install is near impossible due to all the dependencies on languages, functions and config settings.

Need to document that an Admin should visit the Admin->Modules pages after upgrading ZC.

**Comment by scottcwilson** [comment]
That was what I thought.  

The good news is that upgrade instructions already include this step. 

Should we close this ticket?
