### ISSUE TITLE
admin, zen_draw_input_field: parameter required not implemented

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2578]
> function zen_draw_input_field($name, $value = '~*~*#', $parameters = '', $required = false, $type = 'text', $reinsert_value = true) {

The "required" parameter does not get used/added.

I did this
`      $field .= ($required ? ' required' : '') . ' />';`

**Comment by scottcwilson** [comment]
Looks like this got broken in 1.3.9.  In 1.3.8, it was used.

**Comment by drbyte** [comment]
Is there any forum discussion about "why" that was changed(removed)?

**Comment by scottcwilson** [comment]
I suspect this is lost in the mists of time.

**Comment by scottcwilson** [comment]
Changed in 1.3.9a:
 * @version $Id: html_output.php 14139 2009-08-10 13:46:02Z wilt $
@zcwilt you don't by chance remember a ten year old change, do you? :)

**Comment by scottcwilson** [comment]
LOL it gets worse. The `required` parameter *is* used in `zen_draw_pull_down_menu`, but if your template sets it to true, in PHP 7.3 you get a notice about the undefined string TEXT_FIELD_REQUIRED.

**Comment by drbyte** [comment]
> LOL it gets worse. The `required` parameter _is_ used in `zen_draw_pull_down_menu`, but if your template sets it to true, in PHP 7.3 you get a notice about the undefined string TEXT_FIELD_REQUIRED.
> 
> (In admin, this define is set to `'&nbsp;<span class="fieldRequired">* Required</span>'`)

I can't find it right now, but I think this has been discussed before.

**Comment by scottcwilson** [comment]
Yikes.  Mucho hacking required to get this to work.  Admin fields were too wide to show asterisk for required fields.  Submitting two PRs - one for catalog side and one for admin side.

**Comment by torvista** [comment]
My "fix" looks pretty puny after all that!!

**Comment by scottcwilson** [comment]
All fixes matter, Steve. :)

**Comment by scottcwilson** [comment]
Please close; this has been resolved.

**Comment by drbyte** [comment]
Merged #2589 and #2590
