### ISSUE TITLE
Get rid of old PHP_VERSION checks for 5.5 and below

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2586]
Candidates for cleanup
./admin/includes/functions/general.php
./admin/includes/header.php
./admin/sqlpatch.php
./includes/application_top.php
./includes/classes/class.zcPassword.php
./includes/extra_configures/enable_error_logging.php
./includes/functions/password_funcs.php
./includes/modules/payment/square.php
./ipn_main_handler.php

Instead we can do this in application_top for catalog and admin: 
    if (version_compare($phpVersion, '5.6.0', '<')) die();

**Comment by drbyte** [comment]
How about the scenario where someone is upgrading from an older ZC version, which requires an older PHP version, and staging it on the same server? If you force a die() (or remove critical functionality that keeps it secure like password hashing support for older versions), then "staging" becomes very complicated.

**Comment by scottcwilson** [comment]
They use php.ini to set the PHP version for the updated directory.

**Comment by drbyte** [comment]
Do you envision just changing the code, or are you planning to also do thorough testing that nothing is broken by the removal of logic that is nested around/amongst the version-checking code?

**Comment by scottcwilson** [comment]
I really try to test changes, Chris.  It's a best practice, after all.

**Comment by drbyte** [comment]
Sorry, that came out wrong. I was in the middle of another conversation while typing. I forgot to write the important part: there are some complex things in there, inside some complex parts of the code, and some of them are difficult to test (and I don't have time to do that kind of testing right now), particularly if it involves payment modules. (Although I don't think the Square stuff is relevant.)

It's a good idea. Just gotta handle-with-care.

Would also need to make sure zc_install is very aggressive about making it clear that nothing (in catalog/admin) will run if the PHP version is too old.

**Comment by scottcwilson** [comment]
I could do the easiest and most obvious ones first so people could carefully check them in bite sized pieces.  It's true that some of them are "controversial."  :)

**Comment by scottcwilson** [comment]
Files that need attention: under includes: 
includes/functions/password_funcs.php
includes/extra_configures/enable_error_logging.php
.includes/classes/class.zcPassword.php
includes/modules/payment/square.php
includes/application_top.php
includes/extra_configures/enable_error_logging.php

under admin:
admin/sqlpatch.php
admin/includes/header.php
admin/includes/functions/general.php

**Comment by drbyte** [comment]
Is this completed?

**Comment by scottcwilson** [comment]
No there are a few more I believe.  I will check.
