### ISSUE TITLE
php warnings constants already defined SHIPPING_NOT_INCLUDED, TAX_NOT_INCLUDED

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2594]
156c and 157
present in ot_coupon and ot_gv. I moved them to english.

**Comment by scottcwilson** [comment]
These look to be obsolete.  I have an issue open about this -see Issue #2583.

**Comment by scottcwilson** [comment]
This once can be knocked out quickly so I submitted a PR.  Many others exist in the ticket referenced above.
