### ISSUE TITLE
missing constant ERROR_DEFINE_PRODUCTS_FILTER from product_to_categories

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2595]
My bad it seems.
admin english.php needs two additions....this should have shown up when someone (else) tested the PR....

from:
`define('ERROR_DEFINE_PRODUCTS_MASTER_CATEGORIES_ID', 'Warning: No Master Categories ID has been set for this Product');`
to 
```
  define('ERROR_DEFINE_PRODUCTS_MASTER_CATEGORIES_ID', 'Warning: No Master Categories ID has been set for this Product');
  define('ERROR_DEFINE_PRODUCTS_FILTER', 'Warning: No product has been selected');
  define('WARNING_DUPLICATE_PRODUCTS_TO_CATEGORY_LINKED', 'Warning: Cannot link products to the same category');
```

**Comment by scottcwilson** [comment]
the last 2 seem to be unused though.

**Comment by scottcwilson** [comment]
... in newer versions of Zen Cart.  These are old old defines.

**Comment by torvista** [comment]
It's too time consuming/confusing to explain what's what so I'll leave it for now.
