### ISSUE TITLE
Undefined variable: aInfo in admin1\record_artists.php when no artists

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2596]
>  PHP Notice:  Undefined variable: aInfo in ....zencart-157\admin1\record_artists.php on line 292
> PHP Notice:  Trying to get property 'artists_id' of non-object in ....\zencart-157\admin1\record_artists.php on line 292

Install with no demo data/delete Artists and browse to Admin->Extras->Record Artists

**Comment by scottcwilson** [comment]
@zcwilt How 'bout we get rid of the music stuff in 1.5.7?

**Comment by zcwilt** [comment]
Have no problem with removing, as per v2.
