### ISSUE TITLE
Login page, split mode: create account form javascript loaded unnecessarily

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2604]
On the Login page:
all the form-checking javascript is loaded whether the login is split (on the create_account page) or vertical (inline, on the login page).
The js should check for the mode in use.
Also the on_load_main loads this and causes a console error in split mode.
update_zone(document.create_account);

I put all the <script> in a clause:
`if (USE_SPLIT_LOGIN_MODE == 'false') {//false=vertical mode in use`

**Comment by drbyte** [comment]
Fixing errors is important of course.
But keep in mind that the .js files get cached by the browser, so loading them on additional pages is moot.

**Comment by torvista** [comment]
The error was (as usual mine).
Still, having update_zone run onload generates a lot of unnecessary form stuff in the head for the form drop-down.
Also, as this javascript is *.php in /pages/login it is included in the head. I assume that means it is not cached, as it would be if they were discrete *.js files?

So for a returning (not-new) customer who is just logging in, that is all in the head for nothing.
I also have a great deal more javascript form checking than vanilla (second email field, taxid format-per-country, postcode check-per-country) with inline-error-messaging, so it is more of a saving.

**Comment by scottcwilson** [comment]
Can this be closed?

**Comment by drbyte** [comment]
I thought somewhere we'd done some consolidation of a bunch of the JS stuff, probably to remove it from templates and stick it into centralized jQuery, so we could attach events and keep all actions in fewer files. Maybe it was in v2.

Doing that (whether with jQuery or not) would resolve this issue.

**Comment by scottcwilson** [comment]
Team: please update this issue to note if you're planning to do this investigation so we don't duplicate effort.

**Comment by drbyte** [comment]
Feel free to investigate.

**Comment by scottcwilson** [comment]
No JS skillz, sadly. :(

**Comment by torvista** [comment]
> some consolidation of a bunch of the JS stuff, probably to remove it from templates and stick it into centralized jQuery
Is that still the preferred option? Not that I am going to do it, just to leave something resolved in this issue.
