### ISSUE TITLE
DB Version wrong.

### ISSUE THREAD

**Issue by ccooksey** [zencart/zencart#2617]
zc_install/sql/updates/mysql_upgrade_zencart_156.sql might be wrong. I think
project_version_minor='5.6b' should be
project_version_minor='5.6c'
and project_version_comment='Version Update 1.5.5->1.5.6b' should be
project_version_comment='Version Update 1.5.5->1.5.6c'
It works even if you don't do that, but it would be nice if it kept up. The upgrade instructions might want to point out that these commands could / should be run for completeness.

**Comment by drbyte** [comment]
Huh?
It does:
https://github.com/zencart/zencart/blob/10d454d9243ada82bae87e875dbc483c6953283d/zc_install/sql/updates/mysql_upgrade_zencart_156.sql#L257-L258

**Comment by drbyte** [comment]
Edit: 
Oh ... you mean that the 156c stamping hasn't been applied to v157.  
Ya, will merge that forward.

**Comment by drbyte** [comment]
> The upgrade instructions might want to point out that these commands could / should be run for completeness.

No, I specifically have never told people to do that. I want it to persist and recognize exactly what step was actually performed. Leaving it set to the original that was actually applied when the upgrade was done is valuable for troubleshooting. 
And, given that it's extremely rare to do any database changes between lettered versions, there's no point telling people to manually run any SQL commands just for this.

If one really wants to run the commands, of course they can. Those who don't think of it don't need it.

**Comment by ccooksey** [comment]
I suppose so. The sql linked directly from the upgrade instructions at https://www.zen-cart.com/showthread.php?224704-Zen-Cart-v1-5-6-released#post1359669 took me to a version of mysql_upgrade_zencart_156.sql that had the 'b' in it. I followed the link "run these half dozen statements (etc)"

**Comment by drbyte** [comment]
Ah! Thanks for the broader context. Link updated. 

Thanks!

**Comment by ccooksey** [comment]
Yea, sorry about that. It never occurred to me to was a link issue. Thanks for the speedy response.
