### ISSUE TITLE
157: admin/template_select.php: undefined index on template language association

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2620]
1) install an additional language.
2) Click on Create a new association: debug error

> Undefined index: lang in ....public_html\zencart-157\admin1\template_select.php on line 180

as the $_POST['lang'] is not set.

**Comment by scottcwilson** [comment]
I don't get this error. Using PHP 7.3.

**Comment by scottcwilson** [comment]
Can you write up more precise steps to replicate?

**Comment by torvista** [comment]
Using php 7.3.7, 
install Report All Errors and enable for Admin.

**Comment by scottcwilson** [comment]
Yep, got it now.  Thanks.
