### ISSUE TITLE
undefined index: classes/shipping.php

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2624]
Debug when the constants are empty:
'PHP Notice:  Undefined offset: 1 in ...\tienda-156\includes\classes\shipping.php on line 100
 PHP Notice:  Undefined offset: 1 in ...\tienda-156\includes\classes\shipping.php on line 104

  $za_tare_array = preg_split("/[:,]/" , str_replace(' ', '', SHIPPING_BOX_WEIGHT));
      $zc_tare_percent= (float)$za_tare_array[0];
100      $zc_tare_weight= (float)$za_tare_array[1];
      
$za_large_array = preg_split("/[:,]/" , str_replace(' ', '', SHIPPING_BOX_PADDING));
      $zc_large_percent= (float)$za_large_array[0];
104      $zc_large_weight= (float)$za_large_array[1];`

(PHP 7.3.7, Report All Errors installed, NoDups enabled for Catalog.)

This does not appear to occur in 1.57 but the file is the same.  Is there another fix elsewhere?

**Comment by scottcwilson** [comment]
These 2 constants have been in the DB as long as I can remember.  
Add them if you need them: 
`INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) VALUES ('Package Tare Small to Medium - added percentage:weight', 'SHIPPING_BOX_WEIGHT', '0:3', 'What is the weight of typical packaging of small to medium packages?<br />Example: 10% + 1lb 10:1<br />10% + 0lbs 10:0<br />0% + 5lbs 0:5<br />0% + 0lbs 0:0', '7', '4', now());
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) VALUES ('Larger packages - added packaging percentage:weight', 'SHIPPING_BOX_PADDING', '10:0', 'What is the weight of typical packaging for Large packages?<br />Example: 10% + 1lb 10:1<br />10% + 0lbs 10:0<br />0% + 5lbs 0:5<br />0% + 0lbs 0:0', '7', '5', now());
`

**Comment by torvista** [comment]
The constants are not missing, they are empty (in my case as I handle this with Advanced Shipper).
The errors refer to the assumed existence of the second array element, not the undefined constants.

**Comment by scottcwilson** [comment]
oops I read that too fast - thought it said "Undefined constant." 
Should you just set these values to 0:0 instead of empty?

**Comment by torvista** [comment]
After actually reading the admin text properly for probably the first time, I would agree with you. The problem is actually between the screen and the chair.
