### ISSUE TITLE
Sortable Orders' Status

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#2631]
Any interest in incorporating [Sortable Orders Status](https://github.com/lat9/sortable_orders_status_v2/) into zc157?  If so, I'll get a PR going.

**Comment by drbyte** [comment]
Sure.

Request: I see in the install SQL you're `'0'` quoting the default `0` value. Let's not do that in the PR.

**Comment by lat9** [comment]
Will do; I'll get that updated in the plugin as well.

**Comment by lat9** [comment]
While I'm in there, should I 'unquote' the defaults for `orders_status::orders_status_id` and `orders_status::language_id`?

If **Yes**, should I also update the zc157 db-update script to change those defaults?

**Comment by drbyte** [comment]
Yes and yes

**Comment by lat9** [comment]
Given that this adds a field to the `orders_status` table, is there anything (other than the zc_install updates) that should be done to initialize that field for zc157 early testers?

**Comment by drbyte** [comment]
> Given that this adds a field to the `orders_status` table, is there anything (other than the zc_install updates) that should be done to initialize that field for zc157 early testers?

Testers should just manually run any SQL updates added since they last ran (either manually or via zc_install) the 157 upgrade sql.
