### ISSUE TITLE
New MINMAX defines missing from language files 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2632]
Recent PRs have added filter_var checks for some of the integer fields in admin.  However, the error messages use defined text strings which are still missing.  For example: `TEXT_MIN_ADMIN_EMAIL_ADDRESS_LENGTH`, `TEXT_MAX_ADMIN_ADDRESS_BOOK_ENTRIES_LENGTH`, etc.

Note that `TEXT_EMAIL_ADDRESS_VALIDATE` *is* present.

**Comment by scottcwilson** [comment]
@mc12345678 are you working on this issue?

**Comment by mc12345678** [comment]
To an extent.

I thought that recently a default generic error definition had been incorporated which would allow a response of the system to still handle the verification even if a specific error was not encoded in the language files. With that in place (need to verify that such a generic define is present which I don't recall seeing being added yet) there isn't quite the need for the extra defines to support operation. The extra defines would be needed for clarity.

So, today (before the previous message) I was thinking on what generic message for the specific MIN/MAX defines might be like. I still think that given consistent naming, that there is a way to provide a generic message for each of those types. The other side though is how to support overrides/developer incorporation of messages. I think a part of that is to review the "plan" on plugins as I have not read all of the references in wilt's post.

As to @DrByte's discussion (elsewhere in the issues/pulls) of specific messages for specific defines, well, open for discussion on which may need specific handling.

So yes, still considering how to address and haven't walked away from this issue.

**Comment by scottcwilson** [comment]
Follow on work was done for this issue in #3183.
