### ISSUE TITLE
Plugin System

### ISSUE THREAD

**Issue by zcwilt** [zencart/zencart#2641]
v157 Plugin Infrastructure
====================

We had originally started writing a plugin infrastructure for v2, however this had some problems and pushbacks from plugin authors and the wider community.

The main push back was the fact that legacy plugins would no longer work with v2.

We have spent some time re architecting code from v2 for v157 and present more details here.

First of all we just want to explain why we need a new plugin architecture.

The simple reason is ease of installation and upgrading. The new plugin system provides an 
admin interface that lists all available plugins and whether they are installed or not, much like the interfaces for payments/shipping etc. Plugins can be upgraded to a new version and also downgraded, if the user finds the latest version is broken.

There is some documentation for the [new plugin system](https://zc-dev-docs.readthedocs.io/en/latest/devdocs/plugins/pluginsystem.html)

Note: The `readthedocs` site is being used to update the current docs.zen-cart.com site and we will shortly update DNS to reflect this.

Developers will ask two questions (well probably they will ask loads of questions, but maybe these are the two most important)

Q1. Will current plugins continue to work.

The answer here is `maybe`. In general if the plugin would have worked with v1.5.6 then chances are it will continue to work.
However, if the plugin overwrites core code then the chances are it will need some modification.
The reason for this, is that we intend to introduce new notifiers/code into places such as admin orders/customers etc to allow for changing 
the columns displayed and change row actions etc. 

Q2. Will I have to completely re-write my plugin to work with the new system.

Again the answer is maybe. For plugins that don't overwrite core files changing to use the new plugin system is just a matter of reorganizing your current plugin files into the new directory structure. 

Roadmap
------------

It's our intention to include the new plugin system into v157, however there will also need to be some work done in providing new notifiers/code to completely mitigate the need to overwrite core code. We have some upcoming PR's to address this, but also hope that contributors here 
will also help with that effort.

**Comment by lat9** [comment]
Looking at the [directory structure](https://zc-dev-docs.readthedocs.io/en/latest/devdocs/plugins/directorystructure.html), it appears that the design requires that a plugin's _entire_ `manifest` be stored for each version.  I'm just noting that this could cause storage issues for some sites, given that some plugins have a slew of files and might just be updating one or two files for a given release.

**Comment by zcwilt** [comment]
@lat9 Really good point.
So the idea of the versioned directories was to allow for `downgrading`.

I guess we could add an option to reclaim space used by older versions.

This would still mean that at some point there would need to be at least two versioned directories.

**Comment by lat9** [comment]
Understood, @zcwilt.  Is there going to be an option via which a site admin can simply `disable` an installed plugin?

I'm envisioning the case where I install a plugin and determine that it's not doing what I expected.  I _might_ want to keep it around a bit (but inactive) as I investigate the issue.  Ultimately, I might choose to remove the plugin entirely.

**Comment by scottcwilson** [comment]
Downgrading is often so problematic that I wonder if it's worth supporting.   Let's not make this harder than it needs to be to support edge cases.

**Comment by lat9** [comment]
I can see the utility of not so much downgrading as back-testing, with a new version of a plugin installed.

**Comment by zcwilt** [comment]
Just a quick update.

Some PR's have been done to start to flesh out the plugin system, although at the moment these are pretty much admin only. Catalog side will come shortly as in the main it will reuse admin side components for loading resources.

I do have a basic implementation of an admin page to manage plugins. 
e.g. List/Install/Uninstall etc though this still needs a bit of work.

The plugin system was mentioned in issue #2678 and just want to clear up some possible misconceptions. 

 - The new plugin system **will not break** current plugins. There maybe other things that break some plugins in 156/7 but not the new system.

 - The new plugin system is not a panacea for the `hacked core files` problem. It may in some cases help to alleviate the problem, but if a legacy plugin does hack core files then it won't be usable in the new plugin system, unless and until core code is modified to allow easier override, probably using notifiers.

**Comment by zcwilt** [comment]
Just an update here. Work on the `Plugin System` has been on a bit of a hiatus. This is mainly due to some work I've been doing on using array files for language defines. 
The use of array files have huge benefits for the plugin architecture especially if they are a required feature. I'll be starting an issue shortly to discuss this in more depth.

Just to head off some comments though. The use of both array language files and their use in plugins will not affect legacy plugins, which should continue to work as is.

**Comment by scottcwilson** [comment]
It seems like this item is complete - are there more things to do or should this be closed?
