### ISSUE TITLE
html_output: css_buttons, mouse_out, mouse_over

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2648]
Prior to a minor PR, a question.
Consider these constructions of classes to apply to the mouse actions.
```
$mouse_out_class  = 'cssButton ' . (($type == 'submit') ? 'submit_button button ' : 'normal_button button ') . $sec_class;
    $mouse_over_class = 'cssButtonHover ' . (($type == 'button') ? 'normal_button button ' : '') . $sec_class . $sec_class . 'Hover';
```
There are only two button types in use: 'submit' or 'button'.
In the case of a 'submit' button, should not the mouse_over also have the class 'submit_button button', same as mouse_out?
It seems these tests are not covering both states for both types: there should be a mouse_out and mouse_over made for each type, at least to make this easier to understand.

**Comment by drbyte** [comment]
I was wondering the other day if we can just drop all that code and use basic CSS rules to take care of it automatically, without requiring all this extra markup?

**Comment by torvista** [comment]
It certainly seems overkill/dizzyingly complex.

**Comment by drbyte** [comment]
I'd welcome the removal of those old mouse_out/mouse_over things.

And very simple CSS rules for CSS buttons.

**Comment by wiztechinc** [comment]
methinks this is up my alley.

**Comment by wiztechinc** [comment]
Since the classic template is not being removed at this time, I think I should remove the button images too.  But then there's an admin setting for switching between the two and appropriate code for the switch that should be removed as well. I don't think we should encourage folks to use images.  I'm thinking very few carts still use the actual images now. Anyone else have different experience than I?

**Comment by lat9** [comment]
There are still a lot of sites out there 'waiting' for an upgrade with templates that use image-based buttons.  Removing that support will make those upgrades even more difficult.

**Comment by wiztechinc** [comment]
That's why I was asking. I have seen only one with image buttons in the past 3 years or longer myself.

**Comment by wiztechinc** [comment]
Removing the mouse_out and mouse_over was simple and there's no use for either in the Classic or present Responsive Classic. 

There is other code in that section of the html_output that appears outdated (along with other mentions of tooltip etc further down)
` if (defined('CSS_BUTTON_POPUPS_IS_ARRAY') && CSS_BUTTON_POPUPS_IS_ARRAY == 'true') {
      $popuptext = (!empty($css_button_text[$button_name])) ? $css_button_text[$button_name] : ($button_name . CSSBUTTONS_CATALOG_POPUPS_SHOW_BUTTON_NAMES_TEXT);
      $tooltip = ' title="' . $popuptext . '"';
    } else {
      $tooltip = '';
    }`  
Can someone confirm that is no longer used? I don't see anything anywhere else that uses it.

There's little reason for a button to have several css classes when only one is specific. For example, with the css buttons, the product info add to cart button has these: cssButton submit_button button  button_in_cart. 

Changed the code to drop out the button class as I see no reason for that, leaving cssButton as the main class.  But others may disagree. The button in cart isn't necessary unless someone wants to style that one differently from the rest so I can live with that. 

I've fixed the css and removed the extra classes which simplified both templates. The Responsive CSS could be simplied further but I think that would mean totally rewriting it and I'm not sure the effort is worth it. (and I'm not itching to open that can of worms unless requested)

I will start the PR if no one objects or prefers that to be done now

**Comment by drbyte** [comment]
> There is other code in that section of the html_output that appears outdated (along with other mentions of tooltip etc further down)
> ` if (defined('CSS_BUTTON_POPUPS_IS_ARRAY') && CSS_BUTTON_POPUPS_IS_ARRAY == 'true') { $popuptext = (!empty($css_button_text[$button_name])) ? $css_button_text[$button_name] : ($button_name . CSSBUTTONS_CATALOG_POPUPS_SHOW_BUTTON_NAMES_TEXT); $tooltip = ' title="' . $popuptext . '"'; } else { $tooltip = ''; }`
> Can someone confirm that is no longer used? I don't see anything anywhere else that uses it.

I'm pretty sure that's no longer needed.

> I've fixed the css and removed the extra classes which simplified both templates. The Responsive CSS could be simplied further but I think that would mean totally rewriting it and I'm not sure the effort is worth it. (and I'm not itching to open that can of worms unless requested)

Best to not touch any template files if at all possible.

**Comment by wiztechinc** [comment]
The only changes I made were to the css files, nothing else in the template.

**Comment by wiztechinc** [comment]
my apologies as I should do more with github so that I don't end up here again.  back to how to do a PR.  My fork is of course way behind since I haven't touched anything in while. Did find instructions to reverse the compare and sync my fork so created a PR to do that but see no way to go further. Better to delete the fork and start again?

**Comment by wiztechinc** [comment]
ha pr 3292  - proud, so proud!
