### ISSUE TITLE
Ask a Question: Add product_type_layout setting?

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#2667]
Now that **_Ask-a-Question_** has been included in the core, shouldn't there be a way for a store-owner to _easily_ indicate that they don't want it included in their product-details pages?

Looking back to when **_Tell-a-Friend_** was part of the core, there was a product-type-layout setting that allowed the easy enabling of that section for each of the core product types.

**Comment by scottcwilson** [comment]
Seems like a reasonable request.  Will you submit a PR?

**Comment by lat9** [comment]
Sure.
