### ISSUE TITLE
Undefined index: login_attempt - includes\modules\pages\password_forgotten\header_php.php

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2670]
ZC157, Report all Errors, for catalog.
Use password forgotten page, generates debug:

> PHP Notice:  Undefined index: login_attempt in ,....\public_html\zencart-157\includes\modules\pages\password_forgotten\header_php.php on line 23

Which is
`if ($_SESSION['login_attempt'] > 9)`

**Comment by drbyte** [comment]
Closed in #2751
