### ISSUE TITLE
problem with zc_install checks

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#2673]
i have spun up a clean/new debian machine running debian 10 (buster).

i can **without question** confirm .htaccess is enabled, and that the TEXT_ERROR_HTACCESS_SUPPORT is getting displayed.

unfortunately i can not provide a fix as .yml files are currently not in my wheelhouse.

**Comment by scottcwilson** [comment]
Something unexpected is happening in checkHtaccessSupport() in  zc_install/./includes/classes/class.systemChecker.php.  Can you pull out this function and run it stand alone to see where it's getting into trouble?

**Comment by drbyte** [comment]
The .htaccess check specifically attempts to access a file that should *not* be accessible if .htaccess files are in place and enabled in Apache. The file request should be denied. Of course, this requires that you're actually using Apache. If you're using a different webserver software that doesn't support .htaccess then the check will fail.

**Comment by proseLA** [comment]
**Apache/2.4.38 (Debian) Server at v156.com Port 80**

putting incorrect code in the .htaccess file causes an internal server error.  not sure what more to say with regards to what webserver software i am using.  other than i'm building a vagrant box from scratch running debian, and i only installed apache.

scott, thanks for pointing out the function.  herein lies the/my problem, your test relies on data outside of the zc_install directory.  and specifically:

STORE_ROOT/includes/.htaccess

if that file is not there, the response code comes back as 200.

for someone like myself, that uses the zc_install directory to update the database, and i just plug that directory into a working ZC install, i'm not sure it is a good assumption to rely on files that exist outside of that directory.  i would think that as we are inside of the zc_install directory, tests should only rely on files from within that directory.

problem isolated.

**Comment by drbyte** [comment]
> if that file is not there, the response code comes back as 200.

... which exactly proves the point: you have no .htaccess protection in the store which is being tested.

> i would think that as we are inside of the zc_install directory, tests should only rely on files from within that directory.

That's not a realistic test, since there's no point testing a directory that's going to be deleted.

**Comment by proseLA** [comment]
i would change the error message:

> Support for ".htaccess" files is not enabled.

it is misleading at best....

**Comment by drbyte** [comment]
> misleading

I suppose. But only if you're doing something completely outside of what it was designed for in the first place.

**Comment by drbyte** [comment]
Edit: I was checking a configuration where the URL was getting redirected (which we follow), but the redirect was to a non-existing error page, which caused a 404-not-found response instead of the expected 403-forbidden.
So, while it's a false-positive for .htaccess problems, it's indirectly pointing out a different problem :|

**Comment by dbltoe** [comment]
Sorry to comment on closed but saw no referral to a new topic.
Still getting this with the test install suggested by Scott.  Get the 403 every way BUT with the zc_install.
Asking for two reasons, general compatibility and the doc I'm writing for cPanel install. 
Do I need to address the false positive and how to detect correct operation?

**Comment by scottcwilson** [comment]
John, this might be a useful post for the forum in case some other user has a similar issue.

**Comment by dbltoe** [comment]
https://www.zen-cart.com/showthread.php?225304https://www.zen-cart.com/showthread.php?225304
