### ISSUE TITLE
Undefined index: search_orders_products \admin\orders.php

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2675]
ZC156/7
Admin->Customers->Orders
Search in first field.

> PHP Notice:  Undefined index: search_orders_products in ...\zencart-157\admin1\orders.php on line 362

due to no check on the second/product search field $_GET['search_orders_products']

>$placeholder = zen_output_string_protected(isset($_GET['search']) && $_GET['search_orders_products'] != '' ? $_GET['search'] : HEADING_TITLE_SEARCH_ALL);
>

**Comment by scottcwilson** [comment]
Can not reproduce in current 1.5.7.

**Comment by torvista** [comment]
I have today's zencart Github: PHP 7.3.5, with Report All Errors enabled for admin

**Comment by scottcwilson** [comment]
Ah Report All Errors was what I was missing.  Thanks.

**Comment by torvista** [comment]
I don't understand why don't you ALL have it on ALL the time, then these many minor things don't even get out of the gate/get picked up immediately....same as always working in strict mode and doing html validation....

**Comment by scottcwilson** [comment]
Because I am importing new databases and/or recreating databases from scratch ALL the time.

**Comment by torvista** [comment]
Understood.
It's a pain but every time I reinstall ZC157, in goes Report All Errors and Superglobals. I don't leave home without them.
