### ISSUE TITLE
attributes, quotation marks shown as html on order confirmation

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2677]
ZC157
Create an attribute value that has quotation marks, ie. "Lite"
Add to a product.
Add to Cart.
Product attribute is displayed ok:
![01 cart](https://user-images.githubusercontent.com/4391026/62122996-3e010100-b2c7-11e9-8e77-770ef0a70b6c.gif)

Go through checkout.
On Order Confirmation, quotes are shown as html entities:
![2 confirmation](https://user-images.githubusercontent.com/4391026/62123013-45c0a580-b2c7-11e9-95b4-caf671927305.gif)

**Comment by torvista** [comment]
this is the offending line in \templates\tpl_checkout_confirmation_default.php
`      <li><?php echo $order->products[$i]['attributes'][$j]['option'] . ': ' . nl2br(zen_output_string_protected($order->products[$i]['attributes'][$j]['value'])); ?></li>`

I can't determine if this really needs zen_output_string_protected wrapped around it or the function neeeds a parameter to stop the quoting.

**Comment by drbyte** [comment]
I "think" it might be a case of double-encoding, where it's done first in the cart class, which is fine for display on the cart page, but then when data is moved to the order it gets kept as already-encoded and then is re-encoded for display.
(The intention behind encoding it is to prevent malicious attribute values entered in text fields from being displayed in harmful ways.)
But there may be a chicken/egg situation where in the case of one type of data we're bringing already-encoded content forward, but in the other case it's raw.

https://github.com/zencart/zencart/blob/cf80573f891163eb5e76c03334efcbd085c76c0e/includes/modules/pages/shopping_cart/header_php.php#L98-L104
https://github.com/zencart/zencart/blob/cf80573f891163eb5e76c03334efcbd085c76c0e/includes/templates/template_default/templates/tpl_shopping_cart_default.php#L102
https://github.com/zencart/zencart/blob/5092080f9a0bac4751bcf126a337b89e9f404cdb/includes/classes/order.php#L541-L545
https://github.com/zencart/zencart/blob/5092080f9a0bac4751bcf126a337b89e9f404cdb/includes/templates/template_default/templates/tpl_checkout_confirmation_default.php#L134

**Comment by torvista** [comment]
I knew there was more to it, but I don't have the theory clear enough about how data is passed about between objects/pages to offer any progress on this...over to the pros.

**Comment by scottcwilson** [comment]
Can not repro on clean install. 

<img width="883" alt="Screen Shot 2020-04-20 at 1 08 54 AM" src="https://user-images.githubusercontent.com/4391638/79716079-8e7c1c80-82a3-11ea-82c2-03488197293b.png">

**Comment by scottcwilson** [comment]
Product was newly created from scratch, then the Line 1 attribute (from Demo data) was added. 
Line 1 is Option Type Text. 
Nothing special or unusual.

**Comment by scottcwilson** [comment]
Modifying quantity in cart didn't help.  Completely unable to repro.  Anyone else?

**Comment by barco57** [comment]
Confirmed, able to reproduce. Clean install, new product created, NEW attribute name/value created and attached to the product. Does it in the order comments also
![quotes_in_attributes_and_comments](https://user-images.githubusercontent.com/1237035/79718766-72c44680-82a2-11ea-8744-d6e0eef08cda.png)

**Comment by scottcwilson** [comment]
Specifics of attribute "test attribute" ?

**Comment by scottcwilson** [comment]
Order comments DID repro - thanks for noticing that.

**Comment by barco57** [comment]
I did not use the demo data attributes. I created a new option name and option value from scratch.

products_options_values_name field has `&quot;pink&quot;` in it

**Comment by barco57** [comment]
I suppose I should also specify that I entered "pink" with the quotes when creating the option value

**Comment by scottcwilson** [comment]
oh sorry I was using a TEXT option in my testing and entering "foo".  
Do you want to open another defect for the order comments?

**Comment by lat9** [comment]
Noting that the _Options Name Manager_ has saved the **"pink"** value's name as **&quot;pink&quot;** in the database.  The `shopping_cart` page's rendering doesn't run that name through `zen_output_string_protected`, so the issue's not seen there.

Both the `checkout_confirmation` and `account_history_info` pages' output do use that function for the attributes' output.

Looks like the source of the issue is the `order` class' conversion of the cart to an order.  Using `htmlspecialchars_decode` to "put Humpty Dumpty back together again" for the non-text (i.e. customer-entered) attributes corrects the issue.
