### ISSUE TITLE
[Feature] Add shopping cart define_page

### ISSUE THREAD

**Issue by wiztechinc** [zencart/zencart#2679]
I'm truly curious as to why the shopping cart text has never been put into core as a define page. I did a mod years ago but it's a pain to remember it when upgrading. Cart owners find this very handy. Easy to do so I have to think someone thought this was not something that should be done.

**Comment by drbyte** [comment]
How often do they change the text on that section of that page?
If they set it once and rarely touch it, then upgrading is no different than editing the language file.

**Comment by scottcwilson** [comment]
Possibly useful - upsell prompts, etc. could be put in there.

**Comment by wiztechinc** [comment]
I have some that need it often. And I also believe in making my clients self-sufficient so when they need to change it, they don't have to get someone to do it for them. Sure changing the language file is a no brainer for me but for 98% of my clients, it's nigh to impossible.  Since it isn't easily editable, folks are missing appropriate message placement. They usually come to me asking me to put the message into checkout - like checkout_shipping when the actual shopping cart page is perfect. Here's an example:
We use FedEx which has restrictions. Please read our Fedex Shipping Options (click on Shipping tab above) prior to ordering for more information. We do not refund shipping.
We ship Monday through Friday (excluding holidays) from Santee (San Diego) California. Orders received by 1:00 PM Pacific Time will typically ship the same day the order is received. Click here to see FedEx shipping options

**Comment by wiztechinc** [comment]
> Possibly useful - upsell prompts, etc. could be put in there.

Well, you would know!  Thank you.

**Comment by scottcwilson** [comment]
Shipping text is powerful.  Could even use it as a nudge to close.  "Complete your purchase in the next 10 minutes to ship today!"

**Comment by wiztechinc** [comment]
One rule of thumb I adhere to - folks are rushing through to buy - and it's more trouble to read a shipping policy or delivery information if you have to go find the links and read a separate page. Streamline, reduce clicks, format appropriately to catch one's attention.  It's even more critical on mobile devices.

**Comment by dbltoe** [comment]
Last date to Order for Christmas, Valentine's etc.  --  Maunfacturing will be on vacation the second week of September.  Would use it a lot on most sites.

**Comment by drbyte** [comment]
Good reasons.
PR welcome.

**Comment by wiztechinc** [comment]
eek. So have to remember how to do this.......

**Comment by drbyte** [comment]
PR welcome

**Comment by wiztechinc** [comment]
done long time ago. I don't recall the # but it's in there.....

**Comment by scottcwilson** [comment]
https://github.com/zencart/zencart/commit/70d2141099df4e32db9e72f6cd988f4c50e6f1c1

**Comment by scottcwilson** [comment]
Works.  Please close.
