### ISSUE TITLE
Admin, Configuration, Logging: Log Destination path missing slashes

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2686]
ZC157 fresh install. Xampp, windows, php 7.3.5
I notice most of the path slashes are missing:
![Clipboard01](https://user-images.githubusercontent.com/4391026/62233636-3f1a5700-b3c9-11e9-98ef-361ab5b3a3db.gif)

This will have been populated by the installer.
I suppose its a windows thing...
Needless to say enabling the logging generates a debug on every page load.

**Comment by drbyte** [comment]
A PR is welcome, as long as it doesn't require adding a ton of extra code just to support Windows. If the extra code is highly specific, it'll probably be rejected.

**Comment by torvista** [comment]
I have no idea why the slashes are missing....I assume I am not the only one to see this?

**Comment by drbyte** [comment]
I'm guessing it's a nearly-never-used feature.

**Comment by lankeeyankee** [comment]
If that happened during a default install it is something introduced since 1.5.5f. Because I have a local xampp copy of 1.5.5f and it only has /page_parse_time.log in that field.

**Comment by torvista** [comment]
Since I have no time to check this, and it is of a very low priority, and I have more important things to do, I checked it.

In class.zcDatabaseInstaller.php

>     $sql = "update ". $this->dbPrefix ."configuration set configuration_value='".  DIR_FS_ROOT . "logs/page_parse_time.log' where configuration_key = 'STORE_PAGE_PARSE_TIME_LOG'";

mysql simply ignores the backslashes in the DIR_FS_ROOT so they have to be escaped.
I did this and it worked: path was inserted into db correctly and the log is written-to as expected with catalog navigation.

>     $sql = "update ". $this->dbPrefix ."configuration set configuration_value='".  $this->db->prepare_input(DIR_FS_ROOT) . "logs/page_parse_time.log' where configuration_key = 'STORE_PAGE_PARSE_TIME_LOG'";

**Comment by torvista** [comment]
Subsequently I discovered in my shop that I had long ago changed the logging command to use a custom define and not this one.
Why, because it is installation-location specific, meaning a remote db restored to a local installation will have an incorrect path location, and so not be 100% portable.

Further to what I have mentioned, I think this constant STORE_PAGE_PARSE_TIME_LOG should be removed from the admin options/not be auto-generated and either it be assigned in code

`define('STORE_PAGE_PARSE_TIME_LOG', DIR_FS_LOGS.'/page_parse_time_catalog.log');`

or removed completely and references to it should be substituted for the /logs directory.

**Comment by drbyte** [comment]
Or maybe the whole thing should be extracted to an optional plugin, since it's seldom used.

**Comment by scottcwilson** [comment]
Should this be closed?
