### ISSUE TITLE
Order construction, shipping_module_code set to array?

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#2690]
In [this](https://github.com/zencart/zencart/commit/4bb9ea8d142fdc13c8b83376bf89ee4d7840b138#diff-0c591cf6bf5e115dc78721e77d60d9ea) commit, going back to August 2018, the initial value for the order's `info['shipping_module_code']` is now set to an _array_.  What's the reasoning there?  A shipping-module-code is a string, normally including an `_` and the array value is causing `explode` to throw a hissy-fit on one of my plugins.

**Comment by scottcwilson** [comment]
Interesting ... I too have had troubles with that.  Is there some kind of error condition that causes it to reach that branch?

**Comment by lat9** [comment]
Initial entry to `checkout_shipping` for an order.  There's a chicken/egg situation between the `order` (initiated first) and the `shipping`, which actually sets the cheapest shipping-module's code into the session.

**Comment by scottcwilson** [comment]
I sure don't like those double ternary statements.  Could we set this above the array building with some if statements?

**Comment by lat9** [comment]
Sure; I'll submit a PR for zc157, but it's kind of water-under-the-bridge for zc156 as the `array()` setting has been present since zc156-vanilla.

**Comment by lat9** [comment]
@scottcwilson, can you (or anyone else) think of a case where `$_SESSION['shipping']` _is_ set, but the associated `$_SESSION['shipping']['id']` isn't?

**Comment by scottcwilson** [comment]
I will look more carefully next time it happens.

**Comment by lat9** [comment]
I _believe_, but don't _know_, that the issue will also surface coming in from a PPEC button's processing and/or if a customer &mdash; after entering checkout initially &mdash; modifies their cart, making the currently-selected shipping no longer valid.
