### ISSUE TITLE
[Idea] Consolidate two Document product types

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2693]
Do we really need two?  Can't we squeeze this down to one?  Looking at  #2566 shows how confusing and buggy the current situation of having two is.

**Comment by lat9** [comment]
Just like [product_music](#2691), having the two types, one a simple document (that can't be added to the cart) and the other a document-product (that can), gives store-owners _options_.

**Comment by scottcwilson** [comment]
IT'S A STORE.  There shouldn't BE any products which can't be added to the cart.  What in blazes is the reasoning behind creating these _hors commerce_ items?

**Comment by lat9** [comment]
It's _flexibility_, and not willy-nilly removing functionality that is currently in-use.  I suggest, as with `product_music` that you poll on the Zen Cart forums to see what the removal/combination affect will be.

**Comment by drbyte** [comment]
> There shouldn't BE any products which can't be added to the cart. What in blazes is the reasoning behind creating these

The "document" products are used on some sites to offer things like manuals, and they use the document_categories sidebox to show only those (document_general) items in a separate navigation.

The document_general is for not-for-purchase docs, and document_product is for-sale docs.

**Comment by wiztechinc** [comment]
In all my time with zen cart I have had only 2 or 3 customers that deviated from the normal product to either document type. But I've seen a lot of carts with the products general being used instead because folks don't know they can do it differently.  I like having the options no matter how little use these get. It comes down to educating the developing and cart owners. We all think products to buy first, not documents to buy or just a document category

**Comment by lankeeyankee** [comment]
We are using documents for info and I would hate to see it removed.

**Comment by barco57** [comment]
yeah, combining these would be a bad idea. I know one developer who works on ZC sites and uses ZC more as a CMS and uses the Document - General for there portfolio category.

**Comment by mc12345678** [comment]
A non-profit with which I volunteer uses the Document-General product type to identify events at which they will be. For those which they coordinate/run, then an alternate/appropriate product type is used for the occasion.  This is in parallel with using the Zen Cart software and a developed product type to support collecting donations at the same place that they are providing specific information (some calculated from entered data).
