### ISSUE TITLE
PHP notice. undefined variable logger: admin...application_bottom.php

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2701]
ZC157, Report All Errors->enable ignoreDups for admin.
Admin-->Logging->Log Page Parse Time set to true.
Creates a debug log on every **admin** page load.

> PHP Notice:  Undefined variable: logger in ....\zencart-157\admin1\includes\application_bottom.php on line 16

**Comment by scottcwilson** [comment]
Should this be closed?
