### ISSUE TITLE
SEARCH_DEFAULT_TEXT missing...

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#2704]
if we look at the instances of this field in the repo, it does not look like it is defined in the right place.

the language file where this constant is defined is not loaded for the search box....  unless i am missing something...

https://is.gd/PP6GdO

it seems it is needed here:

includes/languages/english/extra_definitions/search.php  

to address the error here:

```PHP Warning: Use of undefined constant SEARCH_DEFAULT_TEXT - assumed 'SEARCH_DEFAULT_TEXT' (this will throw an Error in a future version of PHP) in /var/www/zc156/includes/templates/template_default/sideboxes/tpl_search.php on line 18.```

**Comment by scottcwilson** [comment]
No issue found in 1.5.7 in both responsive classic and default template.   Can you repro on a clean new install?

**Comment by proseLA** [comment]
i can try...  quick question:  on your test server, in:

admin -> tools -> layout boxes controller

is sideboxes/search turned ON?

problem will only manifest itself if that sidebox is ON.

**Comment by scottcwilson** [comment]
Classic: 
![image](https://user-images.githubusercontent.com/4391638/62564087-48d10e00-b852-11e9-92d9-00f9cf110632.png)

Responsive:
![image](https://user-images.githubusercontent.com/4391638/62564213-71f19e80-b852-11e9-87db-76178ee62c17.png)

**Comment by proseLA** [comment]
awesome.  thanks.  i'll see if i can get a fresh install spun up.

**Comment by scottcwilson** [comment]
Can this be closed?

**Comment by proseLA** [comment]
yes
