### ISSUE TITLE
javascript let or const instead of var

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2706]
PHPStorm is always complaining about this, and from what I read, in general yes the vars should be replaced.
What is the panels view on this?.

**Comment by scottcwilson** [comment]
LOL maybe we should get rid of the PHP4 "var" keywords too. 
ES6 is universal, so yes, we should migrate to let as files are changed.

**Comment by torvista** [comment]
So phpstorm should be set to do inspections based on EICMAscript6 then?
