### ISSUE TITLE
Advanced search: Give an option to "not" search in meta_tags

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#2708]
The processing in the `advanced_search_results` includes matches in the `meta_tags_products_description` table.  Some stores might want to include meta-tag information but **not** want it to affect the products that turn up in the search.

**Comment by drbyte** [comment]
Clarification:

Are you suggesting another Admin configuration switch?

Or suggesting offering an option to the customer to do the exclusion (which I think would only confuse the customer).

**Comment by lat9** [comment]
I'm suggesting _yet another_ Admin configuration switch.

**Comment by drbyte** [comment]
If we do it, I guess it makes sense to put it next to the search-related `and/or` config switch.

**Comment by drbyte** [comment]
But I'm wondering the use-case.

Is the real reason that they actually need an "exclude phrases from search" option, instead of "skip the metadata"?

**Comment by lat9** [comment]
I'll need to check with my client to determine the base reasoning, but there appear to be keywords in a product's meta-data that aren't necessarily present in the product's name/description so there can be somewhat extraneous products that show up in the search.

**Comment by scottcwilson** [comment]
Hang on - what about just a checkbox on the advanced search page?  Wouldn't that get you what you want?

**Comment by drbyte** [comment]
That's what I asked earlier.

In this case it appears that the desire is for the storeowner to disable the extra search by default.

**Comment by lat9** [comment]
Some additional feedback from that client ...

The site uses the products' meta-tags _primarily_ to give guidance to search engines.  Meta-tag descriptions might include cross-sell information and/or additional product-type features that would result, in the current search, in "uninteresting" products being displayed ... and those uninteresting products might (depending on a product's sort-order) be displayed _before_ the products that are "interesting".
