### ISSUE TITLE
constants for email debugging and options; unable to define prior to loading defaults

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2714]
In functions_email are

>   //if (!defined('EMAIL_SYSTEM_DEBUG')) define('EMAIL_SYSTEM_DEBUG', 0);//steve disabled to allow preview_email to use it.
>   if (!defined('EMAIL_ATTACHMENTS_ENABLED')) define('EMAIL_ATTACHMENTS_ENABLED', true);
> ....
>   if (!defined('EMAIL_ATTACH_EMBEDDED_IMAGES')) define('EMAIL_ATTACH_EMBEDDED_IMAGES', 'Yes');
> ......
>   if (!defined('SMTPAUTH_EMAIL_PROTOCOL')) define('SMTPAUTH_EMAIL_PROTOCOL', 'none');

These are not in a function, so are loaded on pageload.
I found I could not find a place in a separate file, where I could define one of them "prior" to this: they always load these values/as !defined. 
Should not these constants be INSIDE the function, so can be defined outside as required?

**Comment by drbyte** [comment]
You can put them in your local/configure.php or into a file in your extra_configures directory.

**Comment by torvista** [comment]
To explain, I want to use EMAIL_SYSTEM_DEBUG to show the html on screen, but as part of a mod (from SWGuy) I am updating/expanding to preview the various email templates html in the Admin.
So I want to be able to use different definitions (0/preview)of the constant on demand/in the code, i.e. not have a fixed value elsewhere, such as you suggest, and don't find a way to do it without commenting out the original test. 
Since this constant (and 2 of the other 3) are not used outside of the function, could/should they not be defined inside it?
