### ISSUE TITLE
EMAIL_GREET_NONE missing comma after name

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2715]
```
define('EMAIL_GREET_MR', 'Dear Mr. %s,' . "\n\n");
define('EMAIL_GREET_MS', 'Dear Ms. %s,' . "\n\n");
define('EMAIL_GREET_NONE', 'Dear %s' . "\n\n");
```

**Comment by scottcwilson** [comment]
If it was up to me we would get rid of all the gender stuff.

**Comment by torvista** [comment]
Yes, only two genders is so old-fashioned.

**Comment by scottcwilson** [comment]
Not so much that it's old fashioned - but it's yet another question (like birthday) that's NONE OF YOUR BUSINESS!  So don't ask!

**Comment by torvista** [comment]
I was joking...but really, who has this this question enabled?

**Comment by drbyte** [comment]
This was already fixed: it got lost in the midst of mixing multiple things into one PR in #2750 called "minor edits"
