### ISSUE TITLE
Need to move UPLOAD_FILENAME_EXTENSIONS out of configuration group 2

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2717]
This is not an integer value.  See forum thread
https://www.zen-cart.com/showthread.php?225774-1-5-6c-bug-for-file-upload-attributes&p=1360580#post1360580

Probably a good location would be group 13 (attributes).

**Comment by lat9** [comment]
I'll agree that a home in the Attributes group would be more logical.  If that move occurs, I'll suggest also moving the associated **Maximum File Upload Size** setting (although it _is_ a number) just to keep the settings together.

**Comment by scottcwilson** [comment]
That's fair ... but if we do that, we have separated out an integer value from group 3.  Maybe instead of looking at configuration_group_id (2 or 3)  in includes/init_includes/init_db_config_read.php we should look for configuration names starting with MAX_ or MIN_ and cast *those* to integer.

**Comment by lat9** [comment]
Isn't that what the val_function is to be used for?  Why not move the upload-size and add a validation for an integer value?

**Comment by scottcwilson** [comment]
This is to guard against bad guys modifying integer values *outside* of the context of Zen Admin.  You can read about it here: https://www.thatsoftwareguy.com/blog/2019/06/24/payment-page-credential-stealing-in-zen-cart/

**Comment by lat9** [comment]
I'm just wont to have all that `magic` embedded (and relatively undocumented) processing; it makes it "very difficult" to debug when something goes awry.

**Comment by mc12345678** [comment]
How "crazy" are the two of you going to go?  Personally I've always been confused about why those two upload bits are together in the Maximum area, and think that would have the same confusion about them in the attributes area.  In my view, they are not so forcefully tied together to require them to be together as compared to: 

Downloads Controller Order Status Value >= lower value | 2  
-- | -- 
Downloads Controller Order Status Value <= upper value | 4 

Found in Attribute Settings

If these were separated between minimum and maximum values (even though they too are integers, no?), then these would truly be confusing.   

Understand that there is this dual approach to controlling the purity of the data being considered. The files when retrieving the data from the database and then there is this data in the database to help identify how to treat new data being *added* through the normal process. Unfortunately, this database modification process that has resulted in the need for validating integer values seems (no proof identified) like it could be used to modify the val_function information. The val_function process basically allows those entering information to receive a sort of first response to entering the information although perhaps not quite as quick as some sort of JavaScript keyboard filtering or something. Where in the process the evaluation/problem solving is occurring makes a difference in where to look. Loading the information, the `includes/init_includes/init_db_config_read.php` file.  Storing something, more likely the configuration path and `val_function`.

**Comment by scottcwilson** [comment]
> How "crazy" are the two of you going to go? 
Assuming a top end is a serious mistake. :)

**Comment by drbyte** [comment]
In looking at this further I think merely changing the configuration_group_id number is a bad idea.

A better solution is to move the accepted filetypes to a PHP file, perhaps even (catalog-side, since that's the only place this setting is used) configure.php. 
This setting changes so seldom for majority of stores that it's not needed as an admin setting, and limits risk of unauthorized changes by not making it editable without authorized access to the server filesystem.

(Aside: Zen Cart already prevents downloads and executions of uploaded files when Apache .htaccess is in place.)
