### ISSUE TITLE
Product Audit

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2721]
Every once in a while I see anomalies in databases: 
- product master category set to 0.
- {product master category, product id} pair not in products to categories
- products and categories at the same level

The root cause is generally that the databases were populated by unorthodox methods (buggy versions of ez populate,etc.)

Is there any interest in an audit tool to detect these issues?  Or should this just be a contrib?

**Comment by lankeeyankee** [comment]
I think an audit tool would be great addition, anyone that sells products should be interested in data integrity on their ecommerce site

**Comment by drbyte** [comment]
Probably worth putting it into Store Manager.

I wonder if this code we put into the v156 upgrade SQL might be worth including, or used as inspiration for identifying the need for cleanup:
https://github.com/zencart/zencart/blob/ddf8a7693850836142030d6ac6fdb11bfa712a35/zc_install/sql/updates/mysql_upgrade_zencart_156.sql#L115-L162

**Comment by scottcwilson** [comment]
Let me put the audit tool out as a contrib first and see what the feedback is.  Maybe there will be cases I have never seen that I can check for as well.  A first run on the troubled database with just one check found six items, so winning?

**Comment by torvista** [comment]
I have had this in my admin header for a very long time, to check for valid master category ids, on the dashboard page only.

> //steve master category check, on the index page
if ($current_page == 'index.php') {
    $products_master_category_check_sql = "SELECT p.products_id, master_categories_id, products_model, products_name FROM " . TABLE_PRODUCTS . " p, " . TABLE_PRODUCTS_DESCRIPTION . " pd WHERE master_categories_id NOT IN (SELECT categories_id FROM " . TABLE_PRODUCTS_TO_CATEGORIES . " ptc WHERE ptc.products_id = p.products_id) AND pd.products_id = p.products_id AND pd.language_id = '" . (int)$_SESSION['languages_id'] . "'";
    $products_master_category_check = $db->Execute($products_master_category_check_sql);
    if ($products_master_category_check->count() > 0) {
        foreach ($products_master_category_check as $product_row) {
            $linked_categories_sql = "SELECT categories_id FROM " . TABLE_PRODUCTS_TO_CATEGORIES . " WHERE products_id = " . $product_row['products_id'];
            $linked_categories = $db->Execute($linked_categories_sql);
            $category_urls = '';
            foreach ($linked_categories as $category_row) {
                $category_linked_name = zen_output_generated_category_path($category_row['categories_id']);
                $category_linked_path = implode("_",array_reverse(explode("_", zen_get_generated_category_path_ids($category_row['categories_id']))));
                $category_urls .= '<br />' . $category_row['categories_id'] . ': <a href="categories.php?cPath=' . $category_linked_path . '" target="_blank" title="open category in a new window">' . $category_linked_name . '</a>';
            }
            $master_category_invalid = '<b>' . $product_row['products_id'] . ' ' . $product_row['products_model'] . ' ' . $product_row['products_name'] . '</b>' . $category_urls;
            $messageStack->add('invalid master_categories_id=' . $products_master_category_check->fields['master_categories_id'] . ': ' . $master_category_invalid, 'error');
        }
    }
}
//eof steve

**Comment by scottcwilson** [comment]
Decent amount of progress on some basic issues that I see from time to time.  Should be able to release the contrib this month.

**Comment by scottcwilson** [comment]
Audit has been released.   https://www.zen-cart.com/downloads.php?do=file&id=2261

**Comment by scottcwilson** [comment]
Closing this for now - we can revisit in the future.
