### ISSUE TITLE
Click table-row to jump into edit-mode for product details

### ISSUE THREAD

**Issue by judygunderson** [zencart/zencart#2724]
I noticed in 1.5.6c that you can no longer just click on the product name int the admin to open it to edit it.  You have to go to the right side and click the edit icon.

After all these years of being able to just click the product name... this is mildly irritating, so thought I would bring it up just in case anyone else is mildly irritated by it. :)

I only tested this in Mozilla Firefox... so maybe it is a browser issue????

**Comment by wiztechinc** [comment]
nope, using chrome 1.5.6a so it was changed. Definitely want it back.

**Comment by Zen4All** [comment]
The problem was that it was driven by a JavaScript that gave problems in some browsers. So the choice was made to remove the functionality.
If there is enough interest, I am willing to look into a good solution to get it back.

**Comment by mc12345678** [comment]
Seeing as it seems to work when drilling down categories, it seems like it should be able to be reincorporated in kind for products. That is if the browsers/systems that were having trouble editing product are not still having the same problem at the category level.

**Comment by Zen4All** [comment]
The problem with the products was, if I remember correctly, was that the same click space, contained multiple overlapping click functions with JavaScript., thus sometimes resulting in a non functioning site.
For the categories the code is simpler.

I'll take a look in an update later today.

**Comment by Zen4All** [comment]
I added a simple link to the product name.
