### ISSUE TITLE
Coupons: Removing shipping tax when shipping isn't included

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#2735]
zc156c, responsive-classic template, shipping to Florida.

Modified:
- Shipping: Item, now uses Taxable Goods as its tax-class
- Taxable Goods: Modified Florida tax-rate to be 10%

On entry to `checkout_payment`, all calculations are correct:
![image](https://user-images.githubusercontent.com/2685585/63050956-456d0080-beaa-11e9-9909-2acdb622a619.png)

Add a 5%-off coupon (not free shipping):
![image](https://user-images.githubusercontent.com/2685585/63051075-751c0880-beaa-11e9-9924-ce9f4639df52.png)

Tax value (and total) is now incorrect as 5% has been deducted from the shipping-tax amount.  Tax should be $3.35 ($2.85 + $0.50); total should be $36.84.

**Comment by scottcwilson** [comment]
I'll take it if no one else wants it.

**Comment by drbyte** [comment]
Shouldn't you just change the sort-order of the ot_shipping and ot_coupon modules, such that the coupon applies before shipping?

**Comment by lat9** [comment]
> 
> 
> Shouldn't you just change the sort-order of the ot_shipping and ot_coupon modules, such that the coupon applies before shipping?

Unfortunately, the store that found this issue provides coupons _with_ free shipping and those without, so the coupon needs to be after shipping for the former, but _could_ be before the shipping for the latter.

**Comment by mc12345678** [comment]
> Shouldn't you just change the sort-order of the ot_shipping and ot_coupon modules, such that the coupon applies before shipping?

Wouldn't this change in sort order need to be done on the fly then? E.g. one coupon may be intended to affect the product only, while another may be to affect the shipping? 

Also, why does the returned coupon discount not reflect the change in the shipping cost? It seems based on the displayed discount reduction that the intention is that it shouldn't touch the shipping rate and therefore the tax amount is incorrectly determined; however, it also seems like it should/could still offer a discount on the shipping because there does not appear to be anything that prevents touching the shipping fee, just that it is not causing it to be free.

**Comment by lat9** [comment]
This root cause of this issue, IMO, is that an order's tax-calculations are _so_ distributed that there's very little accountability as to where a tax-amount was added.

For this case, `ot_coupon` doesn't have all the information it needs to do its task.  While current versions of Zen Cart capture the shipping-cost and shipping-tax for the order, the shipping-tax-class (and/or tax-group) isn't.  That's needed to determine the tax-group to which the shipping-tax has been added, so that the shipping-tax can be handled correctly for the case identified by this issue.

**Comment by drbyte** [comment]
Fair points. 
I know I was originally thinking in terms of taxes, not discounts, when I saw and began replying to this. Sounds like there's more going on than just the sort.
Thanks for continuing to investigate. 👍

**Comment by lat9** [comment]
Over the weekend, I'll put together a set of "talking points" that identify my view (given the "challenges" that EO has in order-reconstruction) of what's needed to pull Zen Cart's tax-handling into some modicum of control.  Note that many of the elements that EO needs will also provide store owners some element of track-ability as well.

**Comment by lat9** [comment]
Here's another one, this time with the coupon's sort-order greater than that of shipping.  Using zc156c, demo products.  Modified Item shipping to be taxed, Florida tax changed to 10%, off10 coupon is for 10% off (no restrictions, no shipping).

![image](https://user-images.githubusercontent.com/2685585/63429828-2eb63480-c3e9-11e9-86b9-9077b3165b15.png)

Noting that the tax calculation is incorrect; it _should be_ $4.50.

**Comment by lat9** [comment]
Let's go back to basics.  I think that part of the issue lies in the `ot_coupon` configuration, but its configuration settings' descriptions are _pretty vague_:

![image](https://user-images.githubusercontent.com/2685585/63437287-40530880-c3f8-11e9-969d-6d67aa9dc12a.png)

If I try to set Include Tax to false, I receive a message that Re-calculate Tax? must be set to None, which is confusing the heck out of me.  Could someone provide a description of what these settings mean and how they _should_ be used.

- **Include Shipping**.
- **Include Tax**
- **Re-calculate Tax**
- **Tax Class**

**Comment by lat9** [comment]
I'm seeing part of (if not the source of) the issue.  `ot_shipping` performs its calculations and updates to the order's total and tax on `__construct` instead of during the `process` method!  That says that the order's shipping cost is added to the order _first_ and without regard to its associated sort-order.

**Comment by lat9** [comment]
While that ot_shipping change has corrected those two cases of tax miscalculations for the coupon, I'd like to keep this issue open until there's a response to my request for a definition of what those `ot_coupon` settings are _intended_ to do.

**Comment by drbyte** [comment]
Was this fixed in #3482 as part of #3462?

**Comment by scottcwilson** [comment]
Looks mighty familiar.
