### ISSUE TITLE
Admin Tax Rounding not the same as Catalog

### ISSUE THREAD

**Issue by zcwilt** [zencart/zencart#276]
Scenario
Tax is set at 20%. 
Product price including tax is 6.99 which when entered into Products Price (Gross) on the product entry page is calculated as 5.825 in the Products Price (Net) entry field. 
Preview page changes this to 2 decimal places making it 5.83. 
Tax added to 5.83 is 7.00.
Tax added to 5.825 is 6.99

The product list in admin shows the product as 7.00 as do any order pages and invoices. 
Store side shows the correct value of 6.99

**Comment by scottcwilson** [comment]
Wilt, if you want, you can assign this to me.

**Comment by zcwilt** [comment]
HI @scottcwilson 

When I first looked at this, I was purely testing on 1.5.x code (where the bug was posted against)
However when testing against 1.6.0 code, we get different results, and in fact catalog appears to have a rounding issue when using the test scenario above. 

The problem is that the current code (both 1.5 and 1.6) has some very brittle code, such that fixing rounding issues for 1 set of tests, will then break rounding in another set of tests. 

So still debating how to address this.

**Comment by drbyte** [comment]
The consolidation of many functions and the order class may have resolved these issues.

Ref #1030 #967

**Comment by scottcwilson** [comment]
Retested following original instructions in 1.5.5; replicated; upgraded database to 1.6.0; problem still exists.  Will investigate further.

**Comment by scottcwilson** [comment]
I have what I believe is a potential fix that I will submit as a PR after a bit more testing.  All unit tests pass.

**Comment by scottcwilson** [comment]
Please assign to me.

**Comment by ricksuff** [comment]
Are you sure this is resolved? Following complaints from a client, we set up a vanilla 1.5.6c fileset with the clients database.

Tax is set at 20%

Front end shows product priced at £266.00 on product page, and in shopping cart.

Admin category_product_listing page shows product price as £265.99

Product edit page shows Net price as 221.6640, and Gross price as 265.9968

Admin orders page for with this product shows 
Price (excl) as £221.66 
Price (incl) as £265.99 
Total (excl) as £221.66 
Total (incl) as £265.99 
Sub-total as £266.00, 
Total (inc VAT) as £266.00, 
VAT included (20%) as £44.33

**Comment by lat9** [comment]
I don't think so; I've noted that a change to `/admin/includes/functions/general.php`'s `zen_add_tax` needs to be aligned with the storefront (no rounding) before Edit Orders can be used ... for exactly the reason posted above:
![image](https://user-images.githubusercontent.com/2685585/73261653-83c95400-419a-11ea-99ab-230e381b563d.png)

**Comment by ricksuff** [comment]
@lat9 - following your suggestion, whilst it does display the correct price on the category_product_listing page, and it corrects the Price (incl) and Total (incl) values, it still leads to a discrepancy where adding the displayed VAT (20%) value to the Total (excl) value is £0.01 off. (See attached screenshot)
<img width="1507" alt="Screenshot 2020-01-28 at 23 18 38" src="https://user-images.githubusercontent.com/60371457/73311278-f7607500-421d-11ea-8a59-e5372f1fccda.png">
