### ISSUE TITLE
redundant template: functions_email

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2764]
>   $emodules_array[] = array('id' => 'low_stock', 'text' => 'Low Stock Notices');
>   $emodules_array[] = array('id' => 'cc_middle_digs', 'text' => 'CC - Middle-Digits');
>   $emodules_array[] = array('id' => 'purchase_order', 'text' => 'Purchase Order');

I assume cc_middle_digs is redundant.

**Comment by drbyte** [comment]
Redundant in what context?

One could argue that that whole section of code is redundant.

What are you really asking?

**Comment by torvista** [comment]
While working on a mod for previewing emails, I thought to re-use this already existing array and saw the credit card reference and assumed it is not used anymore. Whether the whole array is in use I didn't think about.

**Comment by drbyte** [comment]
Fair.

**Comment by torvista** [comment]
So is this array likely to disappear completely...I should not use it with a mod?

**Comment by drbyte** [comment]
While the array is not officially maintained, it is used by the admin email-archive-viewer plugin.

**Comment by torvista** [comment]
ok, thanks
