### ISSUE TITLE
Admin Sanitizer: Stripping backslashes

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#2767]
Running a Windows XAMPP installation of zc157; the sanitizer is apparently stripping backslashes:

![image](https://user-images.githubusercontent.com/2685585/63654399-bb455780-c747-11e9-8c8b-7fd0457000cb.png)

**Comment by torvista** [comment]
maybe not
https://github.com/zencart/zencart/issues/2686

**Comment by lat9** [comment]
Thanks for the link, @torvista.  I'll close this issue as a duplicate.
