### ISSUE TITLE
email contact _us always sent as text

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2771]
There is an email template for contact us, and there is processing in header_php.php for the html section, so one would assume the choice is there.
But there is no provision for this module in zen_mail, so it defaults to being sent as text as $customers_email_format never gets set.

Personally I think it should be text-only (bin the template) with a return name/address of the sender so it can be easily replied to, and no need for the anti spam stuff in the footer. It should be bare bones in my opinion.

**Comment by drbyte** [comment]
Yes, it is intentionally always sent as text.

**Comment by torvista** [comment]
Unfortunately this is not pointed out in the documentation (that it is always text, despite a template existing). In fact it would seem strange to detail this odd-one-out and still keep the template in place.

While irritating and unnecessary, perhaps the last step to allow html emails should be completed in zen_mail, based on ADMIN_EXTRA_EMAIL_FORMAT, just so everything is as expected/as is documented.

**Comment by drbyte** [comment]
> Unfortunately this is not pointed out in the documentation (that it is always text, despite a template existing). In fact it would seem strange to detail this odd-one-out and still keep the template in place.

Fine. Submit a PR to delete the file.

> While irritating and unnecessary, perhaps the last step to allow html emails should be completed in zen_mail, based on ADMIN_EXTRA_EMAIL_FORMAT, just so everything is as expected/as is documented.

I don't understand this comment/request/suggestion.  If the unused template file is deleted, what else is needed?

**Comment by torvista** [comment]
> If the unused template file is deleted, what else is needed?
Update of the documentation.

Actually making it work would leave the documentation as is, the template as is and be consistent in having formatting available for all emails. Maybe there are people using it so removal should have some justification/someone may ask for it to be put back!
