### ISSUE TITLE
Admin change customers authorization status not working

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2774]
New install of ZC157, php 7.3.7, Report All Errors on

Clicking on the green square icon appears to do nothing apart from create a few php errors.

**Comment by scottcwilson** [comment]
You're right but I'm unsure of the desired action.  When you press green should it go to 4 (banned)?

**Comment by torvista** [comment]
I would have expected that (...with a corresponding email to that effect?), otherwise what is the point of it being clickable?

**Comment by scottcwilson** [comment]
I think that's only appropriate for CUSTOMERS_APPROVAL_AUTHORIZATION 0.  If you use 1 or 2, I think it should reset to the value you are using (from 0).
