### ISSUE TITLE
admin: zen_draw_separator: dealing with empty size parameters

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2779]
I came across this creating an html error when the height parameter was empty.
Current code:
```
// Output a separator either through whitespace, or with an image
  function zen_draw_separator($image = 'pixel_black.gif', $width = '100%', $height = '1') {
    if (substr(rtrim($width), -1) != "%") $width = $width . 'px';
    return zen_image(DIR_WS_IMAGES . $image, '', '', $height, 'style="width:' . $width . ';"');
  }
```

If the size parameters are omitted, the defaults are used. OK.
If the size parameters are empty (empty constants), then it uses '' as the value. Not OK.

For HTML5 the width/height tags can only be in pixels (no units). But in many cases a % is passed to this.
So, I ended up with this.

```
// Output a separator either through whitespace, or with an image
function zen_draw_separator($image = 'pixel_black.gif', $width = '100%', $height = '1')
{
    if ($width === '') {
        $width = '100%';
    } elseif (ctype_digit($width)) {
        $width .= 'px';
    }
    if ($height === '') {
        $height = '1px';
    } elseif (ctype_digit($height)) {
        $height .= 'px';
    }
    $style = 'style="width:' . $width . ';' . 'height:' . $height . ';"';
    return zen_image(DIR_WS_IMAGES . $image, '', '', '', $style);
}
```

But really both these (catalog/admin) and subsequent passing though to zen_image may need a rethink regarding size parameters....

**Comment by wiztechinc** [comment]
I really think there might be a better way than this.  What about an hr? yes it's full width but it is css formatable. I've never understand why this was done this way. If someone can explain how this is necessary, I would like to hear it.

**Comment by dbltoe** [comment]
IMHO images should no longer have hard-coded sizing unless absolutely necessary.  Handle the majority with css and make those hard-coded changeable through admin menu changes saved in the database.  It was part of the problem for the logo when we went responsive.

**Comment by dbltoe** [comment]
Yes, hr is much better and it can still be styled in html5 for width by:
<hr style="width:50%">

**Comment by dbltoe** [comment]
I'm for removing most of the height and width hard-coding and relying on css.  More flexibility is my goal.  Take as an example, includes/modules/category_row.php. Came across this in doing a recent project.
Lines 39 & 40 establish the layout for the categories page.  Leaving the `, SUBCATEGORY_IMAGE_WIDTH, SUBCATEGORY_IMAGE_HEIGHT` out of the statement allows ease of manipulation in both mobile and desk with a simple width call.
Of, course consistency in the size of images in a specific area (category, product, additional)would be best.  However, that's seldom the case.

**Comment by torvista** [comment]
So, how about a wholesale cull of the use of zen_draw_separator for drawing a line, to hr in a single PR?

**Comment by wiztechinc** [comment]
please - replacing it with an hr maybe?

**Comment by torvista** [comment]
There are about 100 instances of this function drawing a black line of varying thickness, but the little fly is that the default hr is white and so would need its own style/class. So not as neat as one would like, unless by overriding the less in the admin css.
Shown here for comparison:
![Clipboard02](https://user-images.githubusercontent.com/4391026/76329838-5e794b00-62ed-11ea-8478-0788894a7c92.gif)

Opinions?

**Comment by wiztechinc** [comment]
It's not white - it just doesn't show up as well against a grey but I prefer it over a heavy black line myself.. Maybe a personal preference? My UI brain's not worrying this morning but the real test is what it looks like on the whole page, not just the little bit from the site shown larger than normal. I suggest trying just an hr and then posting a screenshot of more of the page.

**Comment by wiztechinc** [comment]
Here's an example against white and it shows up very nicely.
![image](https://user-images.githubusercontent.com/5367263/76683406-34b87080-65da-11ea-8cf0-09a409cde015.png)

**Comment by drbyte** [comment]
> I've never understand why this was done this way. If someone can explain how this is necessary, I would like to hear it.

It was used for exactly the purpose stated: "Output a separator either through whitespace, or with an image". When table-based layouts were required in order for browsers to display properly, the only way to incorporate the necessary padding and dividers was through various hacks such as this.

I agree it's no longer the best approach. It works fine, and is harmless in the places where it sits inside a table-based element being displayed. But when those pages are refactored then these dividers can just be pretty much removed. Not even a need to "replace" it really: just remove it where it serves no purpose after other work is done. Then eventually the function can be removed after being deprecated.
