### ISSUE TITLE
Store customer and order language in database

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2784]
I see that storing the order language has gone on the back burner:
https://github.com/zencart/zencart/issues/832
Essential for order_status updates.

For bulk emailings (gift certificates for example), the language aspect is also necessary.
In the case of such lists (abandoned carts /  customers who registered or never bought / back in stock notifications) I think there there is also a need to store customer signup language.
While implementing the code to support all this is way off, adding the database fields could be done now. I would prefer the fields are more logically named like, order_language_code and customer_language_code (instead of just language_code).

Then those of us with our custom code in place can work on making it fit for PRs.

**Comment by scottcwilson** [comment]
> While implementing the code to support all this is way off, adding the database fields could be done now. 

I think this feature has mostly died from lack of love.  Why not build a PR which does the whole thing rather than trying to piecemeal it?

**Comment by Zen4All** [comment]
It had nothing to do with lack of love, but time management. At the time the code bas of the 1.6.0 branch was changing a lot, and I decided to wait until there was a good good base to work with.

I'll see what can be ported over to the 1.5.7 branch, and create a new PR.

This already happened  with ez-pages, and I am preparing a pul for multi lingual country names.

**Comment by scottcwilson** [comment]
I'm not a multi-language guy (heck, I'm still struggling with English!) but I think this will be a big win for stores that serve multilingual communities.  Thanks for your help.

**Comment by torvista** [comment]
@Zen4All, did I ever send you the code for order status update to send in the relevant language?
Maybe we should conspire on these issues as I get the impression there are very few who use multiple languages.

**Comment by Zen4All** [comment]
@torvista Not that I remember, but isn't that already covered by Zen Cart?

**Comment by torvista** [comment]
Not that I am aware of, the Order Status email is sent in the admin language in use at the time, not the order language.
I send the email in the order language, irrespective of the admin language:
https://github.com/zencart/zencart/issues/832

**Comment by Zen4All** [comment]
I understand. Will look at that code this later this week

**Comment by torvista** [comment]
While we still update the orders one by one, the obvious (leaving aside the need for an api for a ERP to do this) next step is to multiple-select the shipped orders in a group and update them in one step.
I vaguely remember Super Orders had this, but I never got round to looking at it.
Edit Orders may also have relevant code.
So while I don't use both (and so don't know what I am talking about!),..maybe there is a need for a review and integration of these overlapping mods, taking into account language needs such as this thread, rather than piecemeal changes.

**Comment by Zen4All** [comment]
@torvista Super Orders does

**Comment by torvista** [comment]
Can I do a PR to add to table orders:
order_language_id

**Comment by drbyte** [comment]
> Can I do a PR to add to table orders:
> order_language_id

PR is fine. But we should store the string, not the id. ie: `en` or `es`
`language_code varchar(10) default ''`
I suggest approx 10 chars in case people really want to store locale instead, and write bespoke code to adjust for it (ie: `en_US` vs `en_GB`, etc)

**Comment by torvista** [comment]
I note that is a break from the current languages table of 2 chars for the code.
Should there not be a default? If there is a default the code would not need to account for an empty field. It could use english on a new install and the store default language on an upgrade. Easy to change if required.

**Comment by drbyte** [comment]
Forcing a default is pointless. Accommodating "no match" is still the same as accounting for "blank", since both cases would need to do a fallback. Probably to the store's default.

As for matching the default of 2, sure we can do that, since we don't allow for locales anyway.
Next week when someone wants it longer, we can deal with that PR then.

**Comment by torvista** [comment]
add language_code to orders table
https://github.com/zencart/zencart/pull/3105
