### ISSUE TITLE
unnecessary code?

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#2788]
https://github.com/zencart/zencart/blob/2d33e22ffc3311e4f6c5b6ed5da717827c8bfa51/includes/classes/order.php#L98-L113

if my eyes and my IDE do not deceive me, i believe this code is not used anywhere else in this function, and is therefore unnecessary.

or am i missing something?

**Comment by scottcwilson** [comment]
Lines 98-120 (in 1.5.7) appear to not  be required anymore.  Do you want to create a PR?

**Comment by drbyte** [comment]
Closed in #2790

**Comment by scottcwilson** [comment]
@drbyte Did you mean to close this issue?  The problem has indeed been resolved.
