### ISSUE TITLE
admin declarations of TEXT_GV_REDEEM

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2791]
define('TEXT_GV_REDEEM','Redemption Code');
is now defined in english.php...for global use.

But, if embedded/used in another constant definition in admin gv_mail.php,
that gives a php error as english.php has not loaded prior to this language file.

Similarly for admin gv_sent where it is used for a table heading (and is missing/causes an error).

In the current constant-loading method, it does not look like one constant will do.
It seems to me that this constant needs to be defined in the language file for on each admin page that uses it, 
or put into gv_name.php
then if !defined put around the global definition in english.

_Originally posted by @torvista in https://github.com/zencart/zencart/issues/2432#issuecomment-527505446_

**Comment by scottcwilson** [comment]
It looks like 
TEXT_GV_REDEEM
should also be migrated to includes/languages/english/gv_name.php
