### ISSUE TITLE
Oversanitization of configuration entries

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2794]
If you go to admin-configuration-layout settings, and set Bread Crumbs Navigation Separator to >> it converts these symbols to &gt;&gt;.  This actually works the first time, but if you try to edit it again, it converts the & to &amp; and everything falls apart.  Verified bad in 1.5.6c.

**Comment by mc12345678** [comment]
Recommend the filter: FILTER_SANITIZE_FULL_SPECIAL_CHARS.  The php manual at https://www.php.net/manual/en/filter.filters.sanitize.php says that it works similar to `htmlspecialchars`; however, it does not indicate that  it did not indicate that the default `double_encode = true` is either true or false.  Initial testing shows that it is actually false such that `>>` will first be converted to `&gt;&gt;` and when refreshed will remain `&gt;&gt;`.  No specific filter had been applied to the Bread Crumbs Navigation Separator nor many of the other configuration options.

**Comment by scottcwilson** [comment]
Sounds like a plan - you going to do it? 
@lat9 You had raised this issue elsewhere - just letting you know it is being tracked.

**Comment by mc12345678** [comment]
Well, problem is that depending on the configuration_key being addressed, that filter will not allow html to come through as expected/desired. I comment on this because of one of the threads to which this issue was referenced: https://www.zen-cart.com/showthread.php?225862-HTML-tags-in-configuration-fields

Either a separate filter may be necessary or an additional filter added to the class that was developed to support email addresses that may use/reference the existing sanitization class.

**Comment by scottcwilson** [comment]
Crazy question: should admin panel entered data even be subject to sanitization?  It's coming from inside the house.

**Comment by lat9** [comment]
FWIW, I've corrected (right, wrong or indifferent) the site that I'm currently upgrading to zc156c by adding an `/admin/includes/extra_datafiles` module containing

```
$cncsp_sanitizer->addSimpleSanitization('PRODUCT_DESC_REGEX', array('configuration_value'));
```

**Comment by scottcwilson** [comment]
What are we doing with this one?

**Comment by Zen4All** [comment]
I do not care much what we do, or how we do it, as long as it stops (over) sanitizing configuration values.
It is driving me and my customers crazy. :weary:

**Comment by scottcwilson** [comment]
@Zen4All can you be specific about which values are the most problematic so we can be sure those cases are solved?

**Comment by Zen4All** [comment]
Every field that contains html characters like &"<>

**Comment by scottcwilson** [comment]
Does this list look complete? 

 BREAD_CRUMBS_SEPARATOR           
 BEST_SELLERS_FILLER              
 CATEGORIES_SEPARATOR             
 CATEGORIES_SEPARATOR_SUBS        
 CATEGORIES_COUNT_PREFIX          
 CATEGORIES_SUBCATEGORIES_INDENT  
 EZPAGES_SEPARATOR_HEADER         
 EZPAGES_SEPARATOR_FOOTER         
 CURRENCIES_TRANSLATIONS          
 STORE_OWNER_EMAIL_ADDRESS                   
 EMAIL_FROM                                  
 SEND_EXTRA_ORDER_EMAILS_TO                  
 SEND_EXTRA_CREATE_ACCOUNT_EMAILS_TO_STATUS  
 SEND_EXTRA_CREATE_ACCOUNT_EMAILS_TO         
 SEND_EXTRA_GV_CUSTOMER_EMAILS_TO            
 SEND_EXTRA_REVIEW_NOTIFICATION_EMAILS_TO    
 CONTACT_US_LIST                             
 SEND_EXTRA_LOW_STOCK_EMAILS_TO

**Comment by lat9** [comment]
I'll add to the list:

STOCK_MARK_PRODUCT_OUT_OF_STOCK
EMAIL_SMTPAUTH_PASSWORD
CATEGORIES_COUNT_SUFFIX

**Comment by Zen4All** [comment]
and STORE_NAME_ADDRESS

**Comment by scottcwilson** [comment]
PR for your consideration.

**Comment by Zen4All** [comment]
@scottcwilson Tested on a 1.5.6 test store, and your PR seems to do the trick

**Comment by scottcwilson** [comment]
PR #3198 will resolve this in 1.5.6.  Still working on a 1.5.7 change.

**Comment by mc12345678** [comment]
Struggling to understand....  The solution to oversanitization is no sanitization?

**Comment by drbyte** [comment]
That's why the PR was closed: it's not ideal.

**Comment by scottcwilson** [comment]
@mc12345678 if you have time it would be great to have a solid, code-only fix for this in 1.5.6.  The trouble is, using the val functions is not practical.  This PR, as a 1.5.6 fix is not as risky as you might think, since the validations are only skipped on the admin side (where hopefully all inputs are good in the first place).  

The 1.5.7 fix for the emails uses the val_functions as noted previously.  @drbyte is leaning towards doing the same thing for the other fields which might contain meta characters.   Stay tuned.

**Comment by scottcwilson** [comment]
Looks like the fix for non-email fields will *not* use val_functions - @drbyte and I are working out the details in #3236 - stay tuned.

**Comment by dennisns7d** [comment]
It appears to me that SEND_EXTRA_CREATE_ACCOUNT_EMAILS_TO_STATUS does not belong on the list. As currently configured in 1.5.7, I am unable to change this setting. It trips the TEXT_EMAIL_ADDRESS_VALIDATE error regardless of whether I select 0 or 1.

I removed the val_functions for this item and this item now works like the other SEND_EXTRA_*_EMAILS_TO_STATUS items.

**Comment by scottcwilson** [comment]
The list above is no longer accurate - the associated 1.5.7 fix did not include the email items. See #3236 to see how the final change was done.
