### ISSUE TITLE
admin: Undefined index: parent_id in admin function zen_get_path from category_product_listing

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2795]
php 7.3.8, Report All Errors for Admin

Admin->Catalog->Catalog/Products
at TOP:
page parameter is ?cmd=category_product_listing

Click on Hardware: 
page parameter is ?cmd=category_product_listing&cPath=1

go Back:
page parameter is ?cmd=category_product_listing

Click on Hardware: 
page parameter is ?cmd=category_product_listing&cPath=1

Use Drop Down to go to TOP:
page parameter is ?cmd=category_product_listing&cPath=0

Debug generated
PHP Notice:  Undefined index: parent_id in ....\zencart-157\admin1\includes\functions\general.php on line 69

it's due to the GET having 0 in it and so $cPath_array is being created incorrectly.

**Comment by torvista** [comment]
In admin1/includes/init_includes/init_category_path.php 
I changed 

```
// calculate category path
  if (isset($_POST['cPath'])) {
    $cPath = $_POST['cPath'];
  } elseif (isset($_GET['cPath'])) {
    $cPath = $_GET['cPath'];
  } else {
    $cPath = '';
  }
```

to

```
// calculate category path
  if (isset($_POST['cPath'])) {
    $cPath = $_POST['cPath'];
  } elseif (isset($_GET['cPath']) && $_GET['cPath'] != '0') {
    $cPath = $_GET['cPath'];
  } else {
    $cPath = '';
  }
```

**Comment by mc12345678** [comment]
If this is to be the path of resolution, suggest:
````php
} elseif (!empty($_GET['cPath'])) {
````
Probably would want to do the same for $_POST.

**Comment by torvista** [comment]
...why is the third result empty instead of 0?

**Comment by drbyte** [comment]
Probably because of strict checking:
```diff
  function zen_get_path($current_category_id = '') {
    global $cPath_array, $db;
// set to 0 if Top Level
-    if ($current_category_id == '') {
+    if ($current_category_id === '') {
      if (empty($cPath_array)) {
        $cPath_new= '';
      } else {
        $cPath_new = implode('_', $cPath_array);
      }
    } else {
```

In v2 the plan was to set a constant for TOP_LEVEL_CATEGORY, since the true "parent" might not always be "0". Unfortunately this code in v1 still assumes 0=topmost category, which sometimes makes parsing a little confusing.

**Comment by Zen4All** [comment]
Can we do a port back??

**Comment by mc12345678** [comment]
> Probably because of strict checking:
> 
> ````diff
>   function zen_get_path($current_category_id = '') {
>     global $cPath_array, $db;
> // set to 0 if Top Level
> -    if ($current_category_id == '') {
> +    if ($current_category_id === '') {
>       if (empty($cPath_array)) {
>         $cPath_new= '';
>       } else {
>         $cPath_new = implode('_', $cPath_array);
>       }
>     } else {
>  ````
> 
> In v2 the plan was to set a constant for TOP_LEVEL_CATEGORY, since the true "parent" might not always be "0". Unfortunately this code in v1 still assumes 0=topmost category, which sometimes makes parsing a little confusing.

There is also the "issue" of admin/includes/init_includes/init_category_path.php where `zen_not_null($cPath)` is falsey then $cPath_array is set to an empty array instead of an array that contains a single element.  These two together (`$cPath` as an empty array and `$current_category_id`  set to a falsey value) cause `$cPath_new` to be an empty string.

**Comment by torvista** [comment]
not seen this issue anymore.
