### ISSUE TITLE
post install alert-page not working

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#2799]
(@zcwilt ?)
When doing a clean install of Zen Cart 1.5.7, and continuing directly to the admin, without deleting the install folder.  Normally the alert page pops up. Now with the new cmd= structure in place the alert page results in an error page.

**Comment by zcwilt** [comment]
Agreed. Definitely caused by my recent PR #2753 
Will do a PR today. 
Thanks

**Comment by scottcwilson** [comment]
I have always wanted this page to have another link, similar to the down for maintenance page, where it just "re-checks" the status, so you don't have to type in the Admin URL again in the address bar.  Possible?
