### ISSUE TITLE
admin   function zen_catalog_href_link: encoding ampersands

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2806]
Hi,
should not this function have similar jiggery-pokery as function zen_href_link, for cleaning up the link with regard to ampersands, multiples etc.,  and also a final substitution for &amp ;?
eg
`
$link = preg_replace('/(&{2,}|(&amp;)+)/', '&', $link);

    // Convert any remaining '&' into '&amp;' (valid URL for href)
    $link = str_replace('&', '&amp;', $link);`

Also that trigger error looks likes it need to be retired! 

(Html validator in Chrome  complains about the unencoded ampersands, but not in Firefox.)

**Comment by torvista** [comment]
> Html validator in Chrome complains about the unencoded ampersands, but not in Firefox.
The HTML Validator plugin developer tells me Chrome is correct, Firefox is lacking in some of the apis required.

**Comment by drbyte** [comment]
Closed in #2815
