### ISSUE TITLE
Add to Cart no longer works

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2820]
Latest build, after an add to cart, it goes to the shopping cart page and says the cart is empty.

**Comment by scottcwilson** [comment]
When you go back to 426ac1692e2407343b6fabe3adac32941810092f it works.  (This is the merge from Aug 12.

**Comment by scottcwilson** [comment]
Also works on 6c60744a21b30cde7fcc0de6da1100818c157e46 but stops working on next commit which is c39dc2ede72dd8afb63f6945b823173c98f4deb4.  So this PR seems to have broken it: 

https://github.com/zencart/zencart/pull/2813

**Comment by scottcwilson** [comment]
@zcwilt is investigating.

**Comment by zcwilt** [comment]
Yeps.

Found the (stupid) mistake. pr shortly.
