### ISSUE TITLE
admin whos_online not loading language constants

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2824]
Open Whos Online from the Admin menu: ok

Click on  Exclude Admin IP Addresses:No,  and the language constants are not loaded thereafter.
I note the url: /whos_online.php?na=0

![Clipboard01](https://user-images.githubusercontent.com/4391026/65032429-6f9b5d80-d943-11e9-850e-40fe45e4642f.gif)

**Comment by Zen4All** [comment]
confirmed

**Comment by scottcwilson** [comment]
New in 1.5.7, @zcwilt perhaps this is an interaction with the plugin manager?  seems to be confused that $_GET['cmd'] = 'whos_online' is not set, so it doesn't load the language file.

**Comment by scottcwilson** [comment]
This is definitely the plugin stuff; if you go back to the commit before #2813, whos_online works.
