### ISSUE TITLE
admin's header.php, strpos can return (bool)false

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#2829]
The line referenced below can, I believe, throw PHP notices since a URL that doesn't include a '?' will result in a `(bool)false` return.  I'd submit a PR, but I can't wrap my head around the greater-than condition ... what's the '5' counting past?

https://github.com/zencart/zencart/blob/d7a819dce97c895208c85e508977b2c6f455db07/admin/includes/header.php#L135

**Comment by drbyte** [comment]
I think the 5 chars thing is anticipating SEFU with `index` being the shortest possible string to bother with checking for a `?` symbol in the URL.

But, I'm not getting any errors/notices running this in http://sandbox.onlinephpfunctions.com:
```php
error_reporting(E_ALL);
$url = 'foo';
echo var_dump(strpos($url, '?')); // false
echo var_dump(strpos($url, '?') > 5); // false
```

**Comment by lat9** [comment]
OK, I'll bite ... what the heck is SEFU?

**Comment by drbyte** [comment]
lol -- old acronym for "search engine friendly urls"

**Comment by lat9** [comment]
Got it; I knew I'd seen that somewhere.  If there's no issue (as you noted above), I'll go ahead and close this ... it just looked funny to me.

**Comment by lat9** [comment]
This is bugging me.  If the _intent_ is to add either `&amp;vcheck=yes` or `?vcheck=yes` depending on whether or not there's a pre-existing '?' in the url, why all the complexity?  Shouldn't that line simply read:
```
 $url .= (strpos($url, '?') === false ? '&amp;' : '?') . 'vcheck=yes'; 
```

**Comment by drbyte** [comment]
> why all the complexity?

So you're suggesting change `> 5` to `=== false` ?
I guess, while it's 3x more characters, `=== false` is more intuitive than `> 5`.

(Actually I think it would need to be `!== false`)

**Comment by lat9** [comment]
Of course, you're correct on the `!== false`.
