### ISSUE TITLE
refactor to initialize order->products->attributes array

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#2838]
in php 7.x, the php errors associated with countable can be addressed better if we properly initialize our arrays.  for example, i have found this problem frequently associated with the attributes array in the order class.  

in this code snippet:

https://github.com/zencart/zencart/blob/71d448ff583ebee10a832f3337ff69068ec9e78e/includes/templates/template_default/templates/tpl_account_history_info_default.php#L44-L46

we would not need the isset if in the following snippet:

https://github.com/zencart/zencart/blob/71d448ff583ebee10a832f3337ff69068ec9e78e/includes/classes/order.php#L240-L241

if we were to add:
`$this->products[$index]['attributes'] = array();`

between the 2 lines. 

it would not require so many changes for other scripts in custom templates to be making the same isset or is_array statement whenever looking at the attributes associated with our products.  which many templates seem to do.

**Comment by mc12345678** [comment]
This would undoubtedly also assign the existence of the key `['attributes']` to `$this->products[$index]` which is a test in many places where the test is `if (isset($this->contents[$products_id]['attributes'])) {` which would be better modified to a test of not being `empty`. The same `!empty()` type test would be able to replace the above check of `isset() && count() > 0` combination.

While not seen in core code, if for some reason the `['attributes']` key were unset in some other code, then it would need to again be reset to be an `array()`.

**Comment by scottcwilson** [comment]
Should this issue be closed?  We have fixed many of the cases where the countable notice is issued.

**Comment by proseLA** [comment]
i do not deal a lot with attributes.  so i have no problem with you doing whatever you or numbers want to do.

in speaking with a trusted coder friend of mine, it is a noble pursuit to properly initialize all arrays as well as adhere to mysql strict_mode (not relevant to this specific issue, but its late and i thought i would throw it in).  and something that one should do when designing from scratch.  

however, those goals become a lot harder to attain when dealing with legacy code.  of which i would put ZC.  so i have no problem with closing it or whatever.  if v157 is only designed to run with php7.0 and greater, i would suggest the movement towards `is_countable` as opposed to `isset`.  i think...

**Comment by scottcwilson** [comment]
Can this issue be closed?

**Comment by proseLA** [comment]
fine with me.

**Comment by scottcwilson** [comment]
You have to close it because you're the opener.

**Comment by drbyte** [comment]
We should probably do this. At least in the context of the specific case mentioned.
We're already initializing lots of arrays, and correctly. But the specific example has a domino effect ... which I agree needs addressing.
