### ISSUE TITLE
Delete of category with no linked product displays linked product text

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#2839]
Found today when testing the deletion of a category that had no linked product that there is a warning presented regarding linked product and ensuring that the link(s) are properly modified; however, this doesn't make sense to display if the category doesn't have linked product.

Good to know the process, but this seems like the wrong point at which to discuss it.  Why?
- Always showing this text regardless the status of the contained product will reduce the importance of what the message is conveying.
- Displaying this message when there are no linked product would cause the concerned store owner to break away from the current action of deleting the category to go check if there is in fact a linked product and send them down some unnecessary path using time that could be better spent managing the store.
- Displaying this text for all conditions may also drive the concerned individual to seek out if there is a problem with the code/database when it is simply useful information provided for the wrong condition.

This was initially a part of: https://github.com/zencart/zencart/blame/f89a3b8269c7b513693ab5a0dce4469fd403cff9/admin/category_product_listing.php#L1041 in: https://github.com/zencart/zencart/pull/1604/files which became:  https://github.com/zencart/zencart/blame/v157/admin/category_product_listing.php#L1045

Perhaps a new function should be added to check if a category has linked product? There is already `zen_get_product_is_linked($products_id)` which either could be used within the function or it could have its own code to determine if the category has linked product.  Seems that if this concept is to be included that it not just be some stand alone code but something that could be otherwise used.

**Comment by torvista** [comment]
Since I have an update for this file pending, I'll have a look at this shortly...

**Comment by torvista** [comment]
While preparing a PR to improve this, a question...

A product is in it's master category and is linked to other categories.
In the p2c table, there are entries for the master category and the additional links.
When that master category is deleted, in the p2c table the product id-master category entry is deleted but the links are not.
This means the product becomes an orphan thing. It is not findeable in the category listing, but it exists in the products table.
This seems incorrect.

Thinking about this from a failsafe point of view (avoiding accidental deletion), I propose that
a) If a product is in it's master category, and is NOT linked elsewhere: that category cannot be deleted without first manually moving or deleting those master products.
I've put links in the Infobox to make that easier.

b) If a product is in it's master category, and IS linked elsewhere: the category can be deleted, but those master category ids are automatically reset to the next linked category, effectively moving the products automatically. So the product does not get orphaned/lost.

Thoughts?

**Comment by mc12345678** [comment]
> a) If a product is in it's master category, and is NOT linked elsewhere: that category cannot be deleted without first manually moving or deleting those master products.
I've put links in the Infobox to make that easier.

This seems reasonable, provided the product exists, there are categories off of the root, the product is identified in the p2c table, and the product doesn't have a master_categories_id (is equal to 0).
> b) If a product is in it's master category, and IS linked elsewhere: the category can be deleted, but those master category ids are automatically reset to the next linked category, effectively moving the products automatically. So the product does not get orphaned/lost.

Concern here (and really for any of this) is that by auto-assigning a category, it could be equivalent to automatically placing the product on sale. While removing a product from its master category may remove a sale and increase the cost to the customer, it doesn't idirectly mpact the profit other than a possible reduction in moving large quantities of the product at a lower price. If something like this auto-move is to be done, the store owner should be given the chance to know more about the category to which it is being moved and/or a "say" in that happening. In issue #2807, @lat9 and I have been discussing concerns about product that have quantity discounts and application of a sale. Specifically understanding the impact on product when a sale is applied. Movement (by deletion or otherwise) of a product into such a sale category would fall under that same umbrella.

Some other possible situations that may be of some worth considering is if the product doesn't exist but is referenced in the p2c table or if the category(ies) identified to the product no longer exist in the categories table... Effectively addressing those two conditions helps maintain referential integrity and a reason why all categories associated with a product get deleted when reassigning the product to categories. (This is something I was trying to write about in #2841, but apparently have to rewrite that because it has been lost from my browser. I'll try to go flush out an answer to questions posed there).

**Comment by torvista** [comment]
> This seems reasonable, provided the product exists, there are categories off of the root, the product is identified in the p2c table, and the product doesn't have a master_categories_id (is equal to 0).

A product with no master category id (=0) is an error, it should never happen/be allowed to happen. That's one of my points: that code should prevent that/not allow it.

> auto-assigning a category, it could be equivalent to automatically placing the product on sale. 
True. Better to force manual intervention. 

So scenarios:
1) products linked into category: links get deleted with category (as per current code).
2) master products in category: do not allow category deletion (have to manually move or delete master products first).

**Comment by torvista** [comment]
Well, see what you make of this, as an initial effort for delete_category:
https://github.com/torvista/zencart/tree/admin-category_listing

**Comment by scottcwilson** [comment]
I thought this was fixed by @torvista changes but I just checked and it isn't.

**Comment by torvista** [comment]
Don't know what happened there.

So to recap what the outcome should be.

Delete Category.
If there are no products therein: no messages, allow deletion.

If the products therein are ALL linked: show warning message about linked products, allow deletion.

If one of the products therein is a master: show warning message about linked products, show warning message about master products, and do not allow deletion.

If all products therein are master (none linked): show warning about master products and do not allow deletion.

**Comment by scottcwilson** [comment]
Not positive about 3rd and 4th point.  I would rewrite the second point as:
If ANY of the products are linked, show linked products warning, otherwise do not.

**Comment by torvista** [comment]
Ok, I've done this (no PR yet).
Warnings are there, no prevention of deletion.
This is a category with subs:
![Clipboard01](https://user-images.githubusercontent.com/4391026/81511769-e1357b00-931b-11ea-8c67-9d66edef1e39.gif)

Bottom category:
![Clipboard02](https://user-images.githubusercontent.com/4391026/81511811-33769c00-931c-11ea-80ad-e0d99d9297a5.gif)

Empty category:

![Clipboard03](https://user-images.githubusercontent.com/4391026/81511843-67ea5800-931c-11ea-938a-91d12a2493d6.gif)

**Comment by torvista** [comment]
I've pushed this part to a branch admin-delete-category, but will have to shelve it for now:
I am unclear on several things in category_product_listing.php: 
case 'delete_category_confirm,
that handles this form, and am not sure if I am seeing the big picture or it really needs a review.
But, I will not have time for the moment.
