### ISSUE TITLE
IMAGE_ICON_LINKED_CATEGORY is missing

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#2847]
After one of the last commits I am getting this warning `PHP Warning: Use of undefined constant IMAGE_ICON_LINKED_CATEGORY - assumed 'IMAGE_ICON_LINKED_CATEGORY'` when viewing the category listing page in the admin (@torvista ?? as you were working on this I think)

**Comment by torvista** [comment]
yes, it's pending in here
https://github.com/zencart/zencart/pull/2823

**Comment by Zen4All** [comment]
ok thanks
