### ISSUE TITLE
Currency-cron fails if additional admin-sanitizers are present

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#2849]
Starting with the introduction of the admin's 'adminSanitizer' in zc155, any store that has the `/admin/currency_cron.php` set up as a cron job **will fail** if additional sanitizers (those present in the `/admin/extra_datafiles` sub-directory), since the `AdminRequestSanitizer` class is not loaded when the `$loaderPrefix` is set to `currency_cron`.

Errors similar to 

> PHP Fatal error:  Class 'AdminRequestSanitizer' not found

are found in the site's `/logs` directory.

Noting that the most expedient solution to the problem is to clone `/admin/includes/auto_loaders/config.adminSanitize.php` into `/admin/includes/auto_loaders/currency_cron.adminSanitize.php`.

**Comment by drbyte** [comment]
Resolved by #2873 #2872
