### ISSUE TITLE
Admin: bootstrap 4?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2858]
Any reason why this is not used instead of 3, in the admin?

Just before submitting this, I did 5 seconds research, and I guess one answer is that the pages which have had a facelift/removed the tables have the BS3 style column classes and would need revamping again.
Still, the BS3 import could be removed from the main stylesheet and put into each file to import BS3/4 as applicable, until all is changed to BS4?

**Comment by Zen4All** [comment]
At the time I started to update to bs3, bs4 was still in beta.

**Comment by torvista** [comment]
So, no concrete reason not to change to BS4, apart from the work involved on existing files.

**Comment by Zen4All** [comment]
yes, I had a quick try converting to BS4, but it found it was not worth the effort at this moment in time.

**Comment by drbyte** [comment]
Save for actual markup changes in many files, what other incompatibilities are introduced by the change? 
I imagine the datepicker would require changing.

**Comment by Zen4All** [comment]
At the moment I can not think of anything that would break.
I do suggest to update the page structure to something like was proposed in ZC1.6, where the ```<head>``` was moved from the admin pages to its own file, making maintenance and changes easier.
