### ISSUE TITLE
Should initial quantity account for both min and units?

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#2876]
Have been in a discussion in the forum: https://www.zen-cart.com/showthread.php?225986-min-max-display-function

And somewhat finally had enough of a condition I've noticed over the years:
If the minimum quantity assigned to a product is more than the units, Zen Cart does not adjust the initial quantity display on the product page to the next unit value.  Sure, the store owner should consider matching the two or setting the minimum to a value less than the units (for which Zen Cart does "adjust").

So question is, what problem(s) can be seen if 
````php
  function zen_get_buy_now_qty($product_id) {
    $check_min = zen_get_products_quantity_order_min($product_id);
    $check_units = zen_get_products_quantity_order_units($product_id);
    $buy_now_qty=1;
// works on Mixed ON
    switch (true) {
      case ($_SESSION['cart']->in_cart_mixed($product_id) == 0 ):
        if ($check_min >= $check_units) {
          $buy_now_qty = $check_min;
        } else {
          $buy_now_qty = $check_units;
        }
        break;
      case ($_SESSION['cart']->in_cart_mixed($product_id) < $check_min):
        $buy_now_qty = $check_min - $_SESSION['cart']->in_cart_mixed($product_id);
        break;
      case ($_SESSION['cart']->in_cart_mixed($product_id) > $check_min):
      // set to units or difference in units to balance cart
        $new_units = $check_units - fmod_round($_SESSION['cart']->in_cart_mixed($product_id), $check_units);
//echo 'Cart: ' . $_SESSION['cart']->in_cart_mixed($product_id) . ' Min: ' . $check_min . ' Units: ' . $check_units . ' fmod: ' . fmod($_SESSION['cart']->in_cart_mixed($product_id), $check_units) . '<br />';
        $buy_now_qty = ($new_units > 0 ? $new_units : $check_units);
        break;
      default:
        $buy_now_qty = $check_units;
        break;
    }
    if ($buy_now_qty <= 0) {
      $buy_now_qty = 1;
    }
    return $buy_now_qty;
  }
````
were changed in the first case statement to:
````diff
  function zen_get_buy_now_qty($product_id) {
    $check_min = zen_get_products_quantity_order_min($product_id);
    $check_units = zen_get_products_quantity_order_units($product_id);
    $buy_now_qty=1;
// works on Mixed ON
    switch (true) {
      case ($_SESSION['cart']->in_cart_mixed($product_id) == 0 ):
        if ($check_min >= $check_units) {
-          $buy_now_qty = $check_min;
+          $buy_now_qty = $check_units * ceil($check_min/$check_units);
        } else {
          $buy_now_qty = $check_units;
        }
        break;
      case ($_SESSION['cart']->in_cart_mixed($product_id) < $check_min):
        $buy_now_qty = $check_min - $_SESSION['cart']->in_cart_mixed($product_id);
        break;
      case ($_SESSION['cart']->in_cart_mixed($product_id) > $check_min):
      // set to units or difference in units to balance cart
        $new_units = $check_units - fmod_round($_SESSION['cart']->in_cart_mixed($product_id), $check_units);
//echo 'Cart: ' . $_SESSION['cart']->in_cart_mixed($product_id) . ' Min: ' . $check_min . ' Units: ' . $check_units . ' fmod: ' . fmod($_SESSION['cart']->in_cart_mixed($product_id), $check_units) . '<br />';
        $buy_now_qty = ($new_units > 0 ? $new_units : $check_units);
        break;
      default:
        $buy_now_qty = $check_units;
        break;
    }
    if ($buy_now_qty <= 0) {
      $buy_now_qty = 1;
    }
    return $buy_now_qty;
  }
````

What this does (or seems to do) is to select the lowest multiple of units that exceeds the minimum when the product is not yet in the cart.  All associated quantities are assumed to be positive (if this is an incorrect assumption in usage please identify).  This seems to be a place where it could reasonably be incorporated as there are not yet any other items of that product in the cart so do not have to worry about mixes/matches on first addition.  Further, this suggested change does not appear to affect other areas of the cart, though if it does, please point out my mistake.

Again, the specific change is from:
````php
          $buy_now_qty = $check_min;
````
to:
````php
          $buy_now_qty = $check_units * ceil($check_min/$check_units);
````

**Comment by lat9** [comment]
Rather than providing a fix-up, wouldn't it be better for the product's definition to message back to the admin that the values aren't correct?

**Comment by mc12345678** [comment]
> Rather than providing a fix-up, wouldn't it be better for the product's definition to message back to the admin that the values aren't correct?

That is what I would consider the follow on action to arrange for in admin initial assignment/revision to accommodate; however, for existing stores more could/should be done.  Thing is that if this code change is considered problematic then a similar admin change would not make sense so wanted to start with verifying that the result is not problematic.

Further, unless an upgrade SQL is incorporated to ensure this condition, then initial population of a product's quantity and/or the use of a buy now button where units is less than the minimum quantity will display the initial quantity selection of product without being auto-adjusted to the appropriate combination of quantity unless the minimum quantity is itself a factor of units.  (e.g. Units of 2, minimum of 4 would not require a modification, but with units of 2 and minimum of 5 would expect 6 to be entered for the first entry.) At which point additional work would be necessary to bring those items in line.

I began to think that perhaps such a "high" number shouldn't be the first to populate the product; however, in the case where the units exceed the minimum, the displayed quantity is adjusted to provide the unit value which is also a "high" number... Also in the situation of using the "Buy Now" button, manual adjustment of quantities slows down the process.  Therefore, it seemed that in the reverse condition (minimum more than units) a similar determination/display would be appropriate with the follow on adjustment of ensuring good data be entered. I wonder if it should be required or just notified about similar to the identification of free shipping and others on the preview page.
