### ISSUE TITLE
php notices for payment using paypal express paypalwpp.php

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2889]
ZC156 codebase, php7.3.10, Report All Errors:Catalog Nodups

Using ZC156 version of paypalwpp.php
Debugging on.

On a transaction I got three debug logs (all for multiple undefined indexes).
Line numbers are correct for ZC156c vanilla file.

1) 

> PHP Notice: Undefined index: token in .../tienda-156/includes/modules/payment/paypalwpp.php on line 775
> PHP Notice: Undefined index: token in .../tienda-156/includes/modules/payment/paypalwpp.php on line 775
> PHP Notice: Undefined index: token in .../tienda-156/includes/modules/payment/paypalwpp.php on line 775
> PHP Notice: Undefined index: PAYMENTACTION in .../tienda-156/includes/modules/payment/paypalwpp.php on line 1606
> PHP Notice: Undefined index: token in .../tienda-156/includes/modules/payment/paypalwpp.php on line 775
> PHP Notice: Undefined index: token in .../tienda-156/includes/modules/payment/paypalwpp.php on line 775
> PHP Notice: Undefined index: token in .../tienda-156/includes/modules/payment/paypalwpp.php on line 775
> PHP Notice: Undefined index: token in .../tienda-156/includes/modules/payment/paypalwpp.php on line 775
> PHP Notice: Undefined index: entry_telephone in .../tienda-156/includes/modules/payment/paypalwpp.php on line 1660
> PHP Notice: Undefined index: token in .../tienda-156/includes/modules/payment/paypalwpp.php on line 775
> PHP Notice: Undefined index: token in .../tienda-156/includes/modules/payment/paypalwpp.php on line 775
> PHP Notice: Undefined index: L_ERRORCODE0 in .../tienda-156/includes/modules/payment/paypalwpp.php on line 1701
> PHP Notice: Undefined index: L_ERRORCODE0 in .../tienda-156/includes/modules/payment/paypalwpp.php on line 1726
> PHP Notice: Undefined index: RESULT in .../tienda-156/includes/modules/payment/paypalwpp.php on line 2873

2)

> PHP Notice: Undefined index: RESULT in .../tienda-156/includes/modules/payment/paypalwpp.php on line 2873
> PHP Notice: Undefined index: BUSINESS in .../tienda-156/includes/modules/payment/paypalwpp.php on line 1840
> PHP Notice: Undefined index: PAYMENTREQUEST_0_COUNTRYCODE in .../tienda-156/includes/modules/payment/paypalwpp.php on line 1842
> PHP Notice: Undefined index: PAYMENTREQUEST_0_SHIPTOPHONENUM in .../tienda-156/includes/modules/payment/paypalwpp.php on line 1844
> PHP Notice: Undefined index: PAYMENTREQUEST_0_SHIPTOSTREET1 in .../tienda-156/includes/modules/payment/paypalwpp.php on line 1852
> PHP Notice: Undefined index: countries_id in .../tienda-156/includes/modules/payment/paypalwpp.php on line 2018

3)

> PHP Notice: Undefined index: PAYMENTACTION in .../tienda-156/includes/modules/payment/paypalwpp.php on line 327
> PHP Notice: Undefined index: RESULT in .../tienda-156/includes/modules/payment/paypalwpp.php on line 2873
> PHP Notice: Undefined index: PAYMENTSTATUS in .../tienda-156/includes/modules/payment/paypalwpp.php on line 2878
> PHP Notice: Undefined index: PNREF in .../tienda-156/includes/modules/payment/paypalwpp.php on line 440
> PHP Notice: Undefined property: paypalwpp::$response in .../tienda-156/includes/modules/payment/paypalwpp.php on line 466
> PHP Notice: Undefined index: PPREF in .../tienda-156/includes/modules/payment/paypalwpp.php on line 513
> PHP Notice: Undefined index: ship_country in .../tienda-156/includes/modules/payment/paypalwpp.php on line 522
> PHP Notice: Undefined index: PAYMENTINFO_0_SETTLEAMT in .../tienda-156/includes/modules/payment/paypalwpp.php on line 537

On comparison with the ZC157 paypalwpp.php, most of the notices coincide with differences/obvious fixes, so I used this file in the ZC156 site.

The logs are reduced but still require attention.

1)
9 repeated warnings:
> PHP Notice: Undefined index: token in .../tienda-156/includes/modules/payment/paypalwpp.php on line 777

2) 

> PHP Notice: Undefined index: PAYMENTREQUEST_0_PAYMENTACTION in .../tienda-156/includes/modules/payment/paypalwpp.php on line 327

3)

> PHP Notice: Undefined index: BUSINESS in .../tienda-156/includes/modules/payment/paypalwpp.php on line 1846
> PHP Notice: Undefined index: PAYMENTREQUEST_0_COUNTRYCODE in .../tienda-156/includes/modules/payment/paypalwpp.php on line 1848
> PHP Notice: Undefined index: PAYMENTREQUEST_0_SHIPTOPHONENUM in .../tienda-156/includes/modules/payment/paypalwpp.php on line 1850
> PHP Notice: Undefined index: PAYMENTREQUEST_0_SHIPTOSTREET1 in .../tienda-156/includes/modules/payment/paypalwpp.php on line 1858
> PHP Notice: Undefined index: countries_id in .../tienda-156/includes/modules/payment/paypalwpp.php on line 2024

I have the debugging logs available on request.

**Comment by lat9** [comment]
FWIW, I'm gathering the corrections for those slew of PHP notices for paypalwpp.php, paypaldp.php and the paypalwpp_admin_notifications.php.

Once I feel that I've captured them all, I'll submit a PR with those changes.

**Comment by torvista** [comment]
Great!

**Comment by lat9** [comment]
There are the PR's for both zc157 and zc156.

**Comment by torvista** [comment]
156: A pile of notices are generated when entering the admin Paypal IPN page (paypal.php)...

**Comment by lat9** [comment]
Yes, I only focused on `paypalwpp.php` and `paypaldp.php` in those PRs, since I don't have any sites that are using the `paypal`(unsuffixed) version.

**Comment by torvista** [comment]
I use Paypal Express paypalwpp, but I am referring to the Admin->Customers->Paypal IPN screen, which generates the notices, just on opening it:

> PHP Notice: Undefined index: paypal_ipn_sort_order in ADMIN/paypal.php on line 105.
PHP Notice: Undefined variable: reset_paypal_ipn_sort_order in ADMIN/paypal.php on line 108.
PHP Notice: Undefined index: payment_status in ADMIN/paypal.php on line 108.
PHP Notice: Undefined index: payment_status_name in ADMIN/paypal.php on line 157.

and more repeats of the last one.

**Comment by lat9** [comment]
Ah, those PRs covered only the `/includes/modules/payment/*.php` files associated with those PayPal modules' processing.

**Comment by torvista** [comment]
Just had a payment and got these two debugs

> Request URI: /ipn_main_handler.php?type=ec&token=EC-XXXXXXXXXXX&PayerID=XXXXXXXXXX, IP address: 142.183.252.187
#1 paypalwpp->findMatchingAddressBookEntry() called at [/includes/modules/payment/paypalwpp.php:2278]
#2 paypalwpp->ec_step2_finish() called at [/includes/modules/payment/paypalwpp.php:2123]
#3 paypalwpp->ec_step2() called at [//ipn_main_handler.php:81]
--> PHP Notice: Undefined index: zone_id in //includes/modules/payment/paypalwpp.php on line 2691.

which in my file is
$this->zcLog('findMatchingAddressBookEntry - 1-stats', 'lookups:' . "\n" . print_r(array_merge($country->fields, array('zone_country_id' => $country_zone_check->fields['zone_id']), $logMsg), true) . "\n" . 'check_zone: ' . $check_zone . "\n" . 'zone:' . $zone_id . "\nSubmittedAddress:".print_r($address_question_arr, TRUE));

and 
>Request URI: /tienda/ipn_main_handler.php, IP address: 173.0.81.1
--> PHP Notice: Undefined index: ppdebug in /ipn_main_handler.php on line 120.
Request URI: /tienda/ipn_main_handler.php, IP address: 173.0.81.1
--> PHP Notice: Undefined index: exchange_rate in /ipn_main_handler.php on line 155.
Request URI: /tienda/ipn_main_handler.php, IP address: 173.0.81.1
--> PHP Notice: Undefined index: settle_amount in /ipn_main_handler.php on line 157.
Request URI: /tienda/ipn_main_handler.php, IP address: 173.0.81.1
--> PHP Notice: Undefined index: parent_txn_id in /ipn_main_handler.php on line 182.
Request URI: /tienda/ipn_main_handler.php, IP address: 173.0.81.1
--> PHP Notice: Undefined index: auth_status in /ipn_main_handler.php on line 185.

**Comment by torvista** [comment]
Is anyone reviewing debug errors associated with these payments?
I am getting 3-4 per payment, despite the fixes. 
Happy to share logs privately.
