### ISSUE TITLE
invalid cPath yields mixed results

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2903]
example:
a valid category by navigation is
Home ::  Hardware ::  Graphics Cards 
..../zencart-157/index.php?main_page=index&cPath=**1_4**

but manually entering the cpath (or a spider) can use
..../zencart-157/index.php?main_page=index&cPath=**2_4**
which should not be valid, but it yields the same products and the breadcrumb of
Home ::  Software ::  Graphics Cards 

I am seeing such url mixtures on my live site. The result may be a list of products or "There are no products to list in this category."

This seems incorrect (I noticed this due to errors triggered by the code for structured data, so that is one knock-on effect: incorrect structured data being generated),
and would suggest an invalid cPath should redirect to the correct path structure for the last cPath element (in this case using 4).

**Comment by lankeeyankee** [comment]
Yes, I think it would be best to redirect to last cPath element, too.

**Comment by mc12345678** [comment]
So to which "correct path" should that be mapped, why and why not? Resolutions I've considered for this are to automatically map to the master category path as reached from the root, a linked path (if it exists), just the final category without any additional breadcrumbs, completely drop the cPath. There may be others.

**Comment by torvista** [comment]
1) Product exists only in it's master category: redirect to that complete-correct cPath category, as the initial example does not.

2) Product exists in multiple categories.
Final cPath element is valid: redirect to the correct complete-correct cPath category.
If the final element is not valid, you could go further up to check each cPath element to find if the product exists in another branch and redirect it there.

It's really ensuring that that there is no "hole" for a "page not found" nor a possibility of creating a mutant page such as the initial example. They all effect page results and eventually sales.

**Comment by lankeeyankee** [comment]
I think taking it to the master category would be best

**Comment by drbyte** [comment]
The logic for this is in `init_category_path.php`. It starts by using a cPath if supplied, and then does lookups for matches in other cases such as if not supplied etc. It does use master category if no cPath is supplied in the URL.
