### ISSUE TITLE
admin/categories.php->edit_category_metatags: php notices

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2904]
ZC157, php 7.3.10, Report All Errors
Admin->Catalog->Categories/Products->Click on the metags icon:

> [Request URI: /zencart-157/admin1/index.php?cmd=categories&cPath=&cID=1&action=edit_category_meta_tags, IP address: 127.0.0.1
#1  require(..\zencart-157\admin1\categories.php) called at [..\zencart-157\admin1\index.php:11]
--> PHP Notice: Undefined offset: 1 in ..\zencart-157\admin1\categories.php on line 490.
[Request URI: /zencart-157/admin1/index.php?cmd=categories&cPath=&cID=1&action=edit_category_meta_tags, IP address: 127.0.0.1
#1  require(..\zencart-157\admin1\categories.php) called at [..\zencart-157\admin1\index.php:11]
--> PHP Notice: Undefined index: metatags_title in ..\zencart-157\admin1\categories.php on line 497.
[Request URI: /zencart-157/admin1/index.php?cmd=categories&cPath=&cID=1&action=edit_category_meta_tags, IP address: 127.0.0.1
#1  require(..\zencart-157\admin1\categories.php) called at [..\zencart-157\admin1\index.php:11]
--> PHP Notice: Undefined offset: 1 in ..\zencart-157\admin1\categories.php on line 509.
[Request URI: /zencart-157/admin1/index.php?cmd=categories&cPath=&cID=1&action=edit_category_meta_tags, IP address: 127.0.0.1
#1  require(..\zencart-157\admin1\categories.php) called at [..\zencart-157\admin1\index.php:11]
--> PHP Notice: Undefined index: metatags_keywords in ..\zencart-157\admin1\categories.php on line 516.
[Request URI: /zencart-157/admin1/index.php?cmd=categories&cPath=&cID=1&action=edit_category_meta_tags, IP address: 127.0.0.1
#1  require(..\zencart-157\admin1\categories.php) called at [..\zencart-157\admin1\index.php:11]
--> PHP Notice: Undefined offset: 1 in ..\zencart-157\admin1\categories.php on line 528.

**Comment by torvista** [comment]
490
`            <?php echo zen_draw_label(TEXT_EDIT_CATEGORIES_META_TAGS_TITLE, 'metatags_title[' . $languages[$i]['id'] . ']', 'class="col-sm-3 control-label"'); ?>`

$languages has not been created.
On first look, this is missing code in 
```
    case 'edit_category_meta_tags':
      // handled by another switch/case later
      break;
```
that IS in  case 'update_category_meta_tags':

but I see there is more to this regarding actions, maybe further rationalisation is required...so over to someone else.

to create

**Comment by Zen4All** [comment]
> 490
> ` <?php echo zen_draw_label(TEXT_EDIT_CATEGORIES_META_TAGS_TITLE, 'metatags_title[' . $languages[$i]['id'] . ']', 'class="col-sm-3 control-label"'); ?>`
> 
> $languages has not been created.
> On first look, this is missing code in
> 
> ```
>     case 'edit_category_meta_tags':
>       // handled by another switch/case later
>       break;
> ```
> 
> that IS in case 'update_category_meta_tags':
> 
> but I see there is more to this regarding actions, maybe further rationalisation is required...so over to someone else.
> 
> to create

In my virgin version, $laguages is set on line 10
https://github.com/zencart/zencart/blob/dce11b3435ce6f55b579578f20f40894f2c38f37/admin/categories.php#L10
So I suspect you may have something missing in your version of the file?

**Comment by torvista** [comment]
As usual I decided to not do it....then did it anyway.
https://github.com/zencart/zencart/pull/2946
