### ISSUE TITLE
use of $html=0 in zen_address_label

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#2918]
https://github.com/zencart/zencart/blob/2456d36af123ed0c774c8e857cadb80b60db66ee/includes/classes/order.php#L1090
Above is just 1 example, but I am seeing a use of 0 in multiple place where I think actually false is meant.
In my understanding 0 is not the same as false, but I could be wrong.

(@lat9 this may concern you to, as you use the function in your OPC module)

**Comment by drbyte** [comment]
> In my understanding 0 is not the same as false, but I could be wrong.

It all depends on how the value is used.  If "strict comparison" (type comparison) is used, then it would be troublesome.

Currently that variable is used without strict typing, so it isn't causing a problem:
https://github.com/zencart/zencart/blob/272ca5de662d199ce3872ee5a0581c28f9a10e76/includes/functions/functions_customers.php#L35-L36

**Comment by Zen4All** [comment]
okay, thank you

**Comment by drbyte** [comment]
That said, while it's not urgent, consistency is gool.  So I'd welcome a PR that converts all those `zen_address_label` `$html` `0` values to `false`.

**Comment by Zen4All** [comment]
Will do shortly

**Comment by lat9** [comment]
Thanks for the heads-up, @Zen4All.  I'll get those changes staged for _OPC_ as well.
