### ISSUE TITLE
Admin: Options Name Manager

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2924]
I'm working on this file and see for the Deletion of an Option Name, exists this (as Yoda would say):
```
            if ($products->RecordCount() > 0) {
              ?>

              <?php
// extra cancel
              if ($products->RecordCount() > 10) {
                `?>
````
This seems only to be used to display the Cancel button at the **top** of the list when the list is >10, in addition to the default Cancel button at the end of the list.
I think it should ONLY be at the top of the list as the subsequent list is only informative, and in any case you can only cancel, or ....cancel.
I'll change as thus.

**Comment by torvista** [comment]
There is an option on this page and the Values Manager to Show/hide the tools for making global changes.
Why?
The show/hide option is at the **top** of the page so really the tools should be hidden by default and appear at the **top** of the page.
They are actually at the bottom, so they are not using up screen space unnecessarily...if anything, I think they are easily overlooked, which is unfortunate, powerful as they are.

I would actually get rid of the show/hide and just put a jump link there, to draw attention to their existence and to jump down to them.
Opinions?

**Comment by Zen4All** [comment]
I never really understood this option 😕, and have never changed it

**Comment by torvista** [comment]
I suppose it is to put another bit of security in place to make site self-destruction a bit more difficult..?
But I don't agree with it. A big red warning should be enough. Anyone with Admin access should be grown-up enough to read and think for themselves, and either act, back off or ask for advice.

A long standing thing for me is the lack of a built-in mysql backup in ZC.
A one-click-link-to-create-a-backup right next to the warning telling you to make a backup is the bit that is missing from a joined-up interface.
In my opinion.

**Comment by torvista** [comment]
Insert a New Option Name
This has only three fields available: Name, Type and Sort Order.
The processing in 
case 'add_product_options':
expects three more POST variables which are not in the form for a NEW Name (so, debug logs for those).

Now either these three should be removed from the POST processing and also from the SQL execute (as they will be set to the default values by the DB table definition),
or,
all the fields should be available as per the EDIT Option Name function.

**Comment by torvista** [comment]
Insertion of a New Option Name
On initial page load of this admin page, by default there is a form to insert a new option name.
As part of this form, there is a hidden field which specifies the id of the new option name (i.e. on each page load the last id is retrieved+1) and this is passed as a POST and used for the insertion.
This seems wrong to me.
I don't see why it should be specified in the form (multiple users etc.)...it should be determined just prior to the sql for the insertion, no?

**Comment by Zen4All** [comment]
I have a PR ready, that fixes this, including many other changes. Will post the pr later today

**Comment by torvista** [comment]
Doh...I have done loads of changes to this file too!
https://github.com/torvista/zencart/tree/option_name_manager

**Comment by Zen4All** [comment]
> Doh...I have done loads of changes to this file too!
> https://github.com/torvista/zencart/tree/option_name_manager

:grin:  I'll do a comparison. Probably we have a lot of things the same.

**Comment by Zen4All** [comment]
@torvista 
Steve, I just did a compare, and you have a lot of changes did not do.
I did the following: I mad a PR with option_name_manager.php to the 1.5.7 branch. Once thy get approved or disapproved, you do your PR.

**Comment by torvista** [comment]
ok.

**Comment by torvista** [comment]
at some point...
