### ISSUE TITLE
Comments on admin order page

### ISSUE THREAD

**Issue by jwlambcap** [zencart/zencart#2925]
This has been happening since 1.5.1 (at least for me). When upgrading with a clean install, the code is missing to show customer comments on the admin page. The yellow circle appears indicating that the comments exist, but the comments do not post under the "Comments" section on the right.  To fix, the code for adjusting orders.php adding the last line.  I just upgraded to clean install of 1.5.6.c and it still does not include this fix.

        // indicate if comments exist
        $orders_history_query = $db->Execute("select orders_status_id, date_added, customer_notified, comments from " . TABLE_ORDERS_STATUS_HISTORY . " where orders_id = '" . $oInfo->orders_id . "' and comments !='" . "'" );

	if ($orders_history_query->RecordCount() > 0) {
            $contents[] = array('align' => 'left', 'text' => '<br />' . TABLE_HEADING_COMMENTS . ":");
            $contents[] = array('align' => 'left', 'text' => $orders_history_query->fields['comments']);
        }
![missing comments](https://user-images.githubusercontent.com/57806323/68997831-14fd7f80-0868-11ea-89c0-4197fd3ea5c2.png)

**Comment by lankeeyankee** [comment]
Nice catch, and definitely should be in a pull request. Just need to edit your code to remove ` after the closing bracket

**Comment by jwlambcap** [comment]
That ' was from github when I clicked on the <> insert code brackets. Edited to reflect it correctly. Thank you.
