### ISSUE TITLE
Admin: attribute_controller, missing filename warning

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2927]
after adding an attribute to a test product, this warning appears stuck in the middle.
![Clipboard01](https://user-images.githubusercontent.com/4391026/68995018-71bd6200-0889-11ea-82c0-67aa9a919070.gif)
Seems to be using the empty field for the filename when adding the attribute.
I have no experience with this, but I would have thought this field should not even appear if the product is not virtual?

**Comment by Zen4All** [comment]
I found the bug, the if statement was giving the opposite result.

I will make a PR for it

**Comment by Zen4All** [comment]
If you look in the downloads manager page, which color has the attribute there?

**Comment by torvista** [comment]
Sorry, I never saw this reply. Just tried it, error does not occur.

**Comment by torvista** [comment]
Good grief....blind/senile, take your pick....it's still there.
Just pick a product, add a color:
![Clipboard01](https://user-images.githubusercontent.com/4391026/74591424-25182d00-5018-11ea-96a8-ac686614e0d7.gif)

**Comment by torvista** [comment]
Issue is still present.

**Comment by scottcwilson** [comment]
Yep.  Reproduced.

**Comment by scottcwilson** [comment]
The fix I submitted fixes *future* additions of attributes. You will have to clean up past additions yourself or just regenerate your test database.  This is a 1.5.7 bug only.
