### ISSUE TITLE
Rare: whos online table crashes when network drops

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#2935]
It's been reported that if the admin whos-online page is open and auto-refreshing at the same time that the server's network/internet connection fails/drops/disconnects then the whos-online db table may become corrupted, requiring a manual table-repair.

Somewhat challenging to recreate the situation, particularly since where this was reported there were several zc stores affected on the same server. (MariaDB/cPanel/PHP7.2)

**Comment by wiztechinc** [comment]
I've certainly never heard of that but I can definitely say (which I suspect is not unknown amongst us here) that this is the table that is most likely to crash.

**Comment by scottcwilson** [comment]
Data point: Using the MAMP environment, killing mysqld while viewing who's online will *not* repro this issue.

**Comment by drbyte** [comment]
Closing due to lack of ability to recreate. Willing to reopen it when steps to reproduce are available.
