### ISSUE TITLE
Should Downloads Manager page also display values for Product is Virtual/Always Free Shipping?

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2936]
When set incorrectly (e.g. Product is Virtual = Yes or Always Free Shipping = Yes), shipping calculations will be wrong for a mixed cart of downloadable and physical products.  If the Downloads Manager page showed this, it would be easier to track down this misconfiguration.

**Comment by ajeh** [comment]
If you have a solution for this go ahead and post it

**Comment by scottcwilson** [comment]
I haven't written any code, I just thought this would be one way to solve the problem.  Of course another would be to prevent it from arising in the first place by adding checking to the product update process.

**Comment by drbyte** [comment]
Agreed: if there's a bug in catalog-side display/calc then let's fix that.

**Comment by scottcwilson** [comment]
You can assign to me if you want, I'm happy to do it in 1.5.8.
