### ISSUE TITLE
admin zen_href_link encoding ampersands in the url

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2940]
I believe this is incorrect, there was mention of something related a couple of weeks ago but I don't find it.

eg: Option Name Manager
Change the Option Name sort order and you seen the url as such:

> https://www.dev.test/zencart-157/admin1/index.php?cmd=options_name_manager&amp;page=1&option_order_by=products_options_name

this is coming from this
`location = '<?php echo zen_href_link(FILENAME_OPTIONS_NAME_MANAGER, 'page=' . (!empty($_GET['page']) ? $_GET['page'] : 1)); ?>&option_order_by=' + $('#sortOrder').val();`

If I stick another parameter in  there, it encodes that too:
eg:
`location = '<?php echo zen_href_link(FILENAME_OPTIONS_NAME_MANAGER, 'page=' . (!empty($_GET['page']) ? $_GET['page'] : 1) . '&products_order_by=' . $products_order_by); ?>&option_order_by=' + $('#sortOrder').val();`

> https://www.dev.test/zencart-157/admin1/index.php?cmd=options_name_manager&amp;page=1&amp;products_order_by=name&option_order_by=products_options_name

Is this ok or not?

**Comment by Zen4All** [comment]
You have an error in your code, You are closing the php tag. It should look like this
```
location = <?php echo zen_href_link(FILENAME_OPTIONS_NAME_MANAGER, 'page=' . (!empty($_GET['page']) ? $_GET['page'] : 1) . '&products_order_by=' . $products_order_by . '&option_order_by=' + $('#sortOrder').val()); ?>
```

**Comment by torvista** [comment]
I don't find anything to suggest that...if this IS a "problem"/incorrect, I think it is in the zen function.

**Comment by mc12345678** [comment]
> there was mention of something related a couple of weeks ago but I don't find it.

Possibly referencing this PR? (https://github.com/zencart/zencart/pull/2912)

**Comment by torvista** [comment]
Yes that was it.
