### ISSUE TITLE
Wrong coupon calculation for case 'P' (percentage)

### ISSUE THREAD

**Issue by webchills** [zencart/zencart#2941]
1.5.6 and 1.5.7

Create a coupon with percentage 10
Do not set any product or category restrictions.
Depending on the setting for Coupon Minimum calculated from "Allowed Products" or "All Products" you get different results for the coupon value during the checkout of the same product.

includes/modules/order_total/ot_coupon.php around line 531 is:

```php
case 'P': // percentage
//              $od_amount['total'] = zen_round($orderTotalDetails['orderTotal']*($coupon->fields['coupon_amount']/100), $currencyDecimalPlaces);
              $od_amount['total'] = zen_round($coupon_total*($coupon->fields['coupon_amount']/100), $currencyDecimalPlaces);
```
should be:

```php
case 'P': // percentage
              $od_amount['total'] = zen_round($orderTotalDetails['orderTotal']*($coupon->fields['coupon_amount']/100), $currencyDecimalPlaces);
//              $od_amount['total'] = zen_round($coupon_total*($coupon->fields['coupon_amount']/100), $currencyDecimalPlaces);
```

**Comment by lat9** [comment]
FWIW, I'm not seeing this with the current zc158 alpha.

**Comment by scottcwilson** [comment]
Closing.  Anyone who has current repro steps is welcome to reopen.
