### ISSUE TITLE
Use zen_update_orders_history when updating an order's status

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#2943]
With the incorporation of the `zen_update_orders_history` function for zc156, I'm seeing that its use wasn't trickled down to

1. /ipn_main_handler.php
2. ~~/includes/classes/order.php~~
3. /includes/modules/payment/*.php
4. /includes/modules/payment/paypal/paypal_functions.php

One of the main 'drivers' for this common function is to consolidate an order's status-update to enable watching observer(s) to take action on an order's status _change_.

I'll be happy to submit a PR for both the zc157 and zc156 branches.

**Comment by drbyte** [comment]
Do you envision just adding some notifier hooks?
Or are separate functions needed in each of the payment modules?
Or should the notifier hook be in the payment.php class which brokers many of the calls to the methods in the payment modules?

**Comment by lat9** [comment]
Nope, I'm looking to convert the various status-history updates to use `zen_update_orders_history`.  That function's got the (common) notifier hook.

**Comment by drbyte** [comment]
Okay, makes sense.

**Comment by lat9** [comment]
I'll get that PR going over the weekend.

**Comment by lat9** [comment]
Noting that no update is _desired_ within `/includes/classes/order.php`, since that's recording the initial order, so there's no change in status!
