### ISSUE TITLE
International Name Formats (reference)

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#2949]
NAMES AROUND THE WORLD

Overview of the many different ways people are named around the world:
http://www.w3.org/International/questions/qa-personal-names

Article has guidelines for how to deal with the wide spectrum of international names in Web forms including suggestion of using a single field for "Full Name" and let people type family name first or last, as appropriate for their culture.

The article also recommends supplementing the full-name field with a field for "what should we call you?" If you do this, also show examples of how this info will be used. It's hard to decide how you'll like to be referred to without knowing the context.

See also:

International Sites: Minimum Requirements
http://www.useit.com/alertbox/20050808.html

International Usability: Big Stuff the Same, Details Differ
http://www.useit.com/alertbox/international-sites.html

**Comment by torvista** [comment]
I don't see any need in my site for a two-field name...one field would be cleaner as everyone in spain has two surnames and maybe a double forename.
And me with one name and one surname always causes doubt when entered into a spanish form expecting two surnames. So, I'd go for one field. That's a big PR!

**Comment by drbyte** [comment]
Ya, it'd be a major change. Not suitable for a minor version release.
