### ISSUE TITLE
options values manager have a "go to" or search feature

### ISSUE THREAD

**Issue by lankeeyankee** [zencart/zencart#2950]
When you get to over 100 pages of options values, it can be quite tedious to locate the one you want to edit or just to see what is there for a certain option name. Being able to search by option name to return just those results would be amazing. Or a go-to dropdown list of all option names would work, too, giving another way to see all option names from the values page. 

Using attributes for filters and comparisons on many thousands of products means a huge amount of options values. It's gotten unwieldy and we waste a lot of time guessing which page number to click to get to where we need to be.

**Comment by wiztechinc** [comment]
Agree this needs to be looked at. Major issue when trying to edit any of it. Not as bad when setting things up at first.

**Comment by lankeeyankee** [comment]
A bonus would be to add a "display per page" dropdown to change how many results are displayed per page including a "display all" option. I know this is in the config>maximum values, but to have the flexibility to change it on the fly would be a real time saver. Leaving it at the default 10 is best when you are adding since the add section is at the bottom of the display and you don't have to scroll too much. If you are searching for an option name and there are 30 results, it is usually desirable to be able to see all 30 at once, to help when changing sort orders or editing the values.

**Comment by Zen4All** [comment]
Funny how brilliant minds have the same idea at the same time.
I am almost ready to make a PR for this page. Also containing a drop-down to filter to one option.
I have no time to do it this weekend, but will push the PR on Monday

**Comment by Zen4All** [comment]
> A bonus would be to add a "display per page" dropdown to change how many results are displayed per page including a "display all" option. I know this is in the config>maximum values, but to have the flexibility to change it on the fly would be a real time saver. Leaving it at the default 10 is best when you are adding since the add section is at the bottom of the display and you don't have to scroll too much. If you are searching for an option name and there are 30 results, it is usually desirable to be able to see all 30 at once, to help when changing sort orders or editing the values.

I like this suggestion. I'll see if I can incorporate it in the upcoming PR

**Comment by torvista** [comment]
> Being able to search by option name to return just those results would be amazing.
I'm finishing off an overhaul for option_name_manager (I have a branch open). I've got the global tools showing only matching products/categories, maybe filter code could be adapted for this purpose.

**Comment by Zen4All** [comment]
a screen shot of what i have coded
![Screenshot from 2019-12-07 00-49-37](https://user-images.githubusercontent.com/2766593/70364394-b175d900-188c-11ea-801c-a20d0311f873.png)
 so far

**Comment by lankeeyankee** [comment]
> 
> 
> a screen shot of what i have coded so far
> for the code see https://github.com/Zen4All/zencart/blob/options_values_manager/admin/options_values_manager.php
> ![Screenshot from 2019-12-07 00-49-37](https://user-images.githubusercontent.com/2766593/70364394-b175d900-188c-11ea-801c-a20d0311f873.png)

That looks awesome!!

**Comment by mc12345678** [comment]
On the addition of items concept, it would be great if after adding an option value to an option name if the previous option name would remain "active" so it need not be selected again.

**Comment by Zen4All** [comment]
@mc12345678  Yes, already working on that. Adding the parameters to the redirects etc.

**Comment by mc12345678** [comment]
> Yes, already working on that. Adding the parameters to the redirects etc.

If I understand correctly (and really should wait to see the results): Other than perhaps coming to option values manager from option names manager where having the options_id in the url may be of benefit, posted data from within the option values manager could be used here (from the options name manager as well). Otherwise, from within option values manager, the posted data would have to become get data when submitting the new option value along with everything else that was being updated/changed.

**Comment by scottcwilson** [comment]
Has this been fixed by @torvista changes in this area? Can this be closed?

**Comment by torvista** [comment]
Not guilty, didn't touch options values

**Comment by scottcwilson** [comment]
Geez who did this change.  Was it @Zen4All ?   Anyhow you can see there's filtering which makes things easier to find.  Not sure if this is satisfactory. 

<img width="1075" alt="Admin_Options_Values_Manager" src="https://user-images.githubusercontent.com/4391638/80865408-4bcd2380-8c57-11ea-824d-b0f7eff062c4.png">

**Comment by Zen4All** [comment]
It was me. Have not made the fix yet I think. Have to check.
Will give answer tomorrow

**Comment by dbltoe** [comment]
While you're at it, the buttons for each value should match the buttons for the names in the options names manager.
Names has Edit > Delete
Values has Update > Delete

**Comment by scottcwilson** [comment]
Might be better to make a separate ticket, or even do the PR yourself @dbltoe.  We don't want to hijack @lankeeyankee 's ticket.

**Comment by dbltoe** [comment]
With the advent of all these changes, I have been totally unable to discover where the button is generated in the code.
Plus, I now have a witness (haredo) that PRs just do not work well for me.
I spent the first four hours today just trying to figure out where the button is defined.  No luck as the best choice's define was "Update the Sort Order" when inspecting clearly says Update {-(

**Comment by torvista** [comment]
> Names has Edit > Delete
> Values has Update > Delete

My view is that
Update is to submit new values/changes that have been made.
Edit is to proceed to make changes to the values currently shown.

>PRs just do not work well for me

I feel your pain!

option values manager looks like weeks of pain if I look at it, I'm not going there (again).
Button is here

> `                        <a href="<?php echo zen_href_link(FILENAME_OPTIONS_VALUES_MANAGER, 'action=update_option_value&value_id=' . $values_value['products_options_values_id'] . '&' . ($currentPage !== 0 ? 'page=' . $currentPage . '&' : '') . ($filter !== 0 ? 'set_filter=' . $filter . '&' : '') . ($max_search_results != 0 ? 'max_search_results=' . $max_search_results : '')); ?>" class="btn btn-primary" role="button"><?php echo IMAGE_UPDATE; ?></a>`

**Comment by Zen4All** [comment]
Ok, I lost track. Can somebody please tell me, what I was supposed to check/fix?

**Comment by scottcwilson** [comment]
I was wondering if the changes so far were sufficient to satisfy this ticket.  @lankeeyankee can you weight in?

**Comment by lankeeyankee** [comment]
There was an issue I discovered and mentioned in the pull request @Zen4All https://github.com/zencart/zencart/pull/2955 I think this might still be an open issue

**Comment by scottcwilson** [comment]
I'm going to close.  Please open a new feature request if there are additional needs.
