### ISSUE TITLE
option_name_manager: allows a duplicate option name

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2952]
1) In option_name_manager, it is allowed to add a duplicate name. Why?
2) There is a check for a duplicate AFTER it has been inserted to show a message.
This is broken:
```
$check = $db->Execute("SELECT COUNT(products_options_name) AS count
                                 FROM " . TABLE_PRODUCTS_OPTIONS . "
                                 WHERE language_id = " . (int)$languages[$i]['id'] . "
                                 AND products_options_name = '" . zen_db_input($option_name) . "'");
          if ($check->RecordCount() > 1) {
            $duplicate_option .= ' <strong>' . strtoupper(zen_get_language_name($languages[$i]['id'])) . '</strong> : ' . $option_name;
          }
```

The message clause is never entered as the sql returns the count (one result), not the multiple values, so is never > 1.

So, in light of this, why is a duplicate allowed in the first place?

**Comment by Zen4All** [comment]
There is no problem with duplicate names. I sometimes use them deliberately. For example one as a drop-down, and one as a read-only.

**Comment by torvista** [comment]
ok.
Then just this test needs to be fixed...I see there is a similar test later in the code that is correct so I'll copy that.
