### ISSUE TITLE
ipv6 v ipv4 in error logging

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#2959]
https://github.com/zencart/zencart/blob/31130d1df3befce2888f162ac65f1f97be90ed25/admin/orders.php#L580-L580

my sites now get ipv6 addresses.  i frequently see ipv6 addresses in the orders table.  so hard coding an ip address type here makes little sense to me.

in addition, in my zen-cart error logs, i have never seen any ipv6 addresses.

digging a little into the code brings up the function `zen_get_ip_address()` which is defined on the admin side as well as the store side.  it would be nice to have it defined in 1 place.

i can not tell if that is what is being used for the enable error logging.

can we say with confidence that the ip address in the ZC error logging is the same as being used for the function?  (sorry i have not dug further...)  and has anyone seen ipv6 addresses in their zc logging?  my sites run apache and the raw apache logs definitely have ipv6 addresses in them.

**Comment by lat9** [comment]
The error logging is (currently) using the as-supplied version of  `$_SERVER['REMOTE_ADDR']`.  I suppose that `enable_error_logging.php` could be modified to use `zen_get_ip_address` if the function exists (as errors could occur prior to the function loading).

**Comment by drbyte** [comment]
The choice to use dnsstuff for lookups came from the fact that domaintools .com reduced their lookup limits awhile back. 

That said, both services lookup accepts both ipv4 and ipv6 interchangeably: even the dnsstuff response to a type=ipv4 request with an ipv6 IP passed to it will still do a useful lookup.

**Comment by drbyte** [comment]
> it would be nice to have it defined in 1 place.

Of course. There are plans to consolidate by de-duplicating. But keep in mind that hundreds of addons distribute altered copies of the same files involved by such changes. So there will be pain when upgrading.

**Comment by proseLA** [comment]
>  So there will be pain when upgrading.

unfortunately upgrading is always a pain...  no worries on that.... 

a link that got generated was this:

http://www.dnsstuff.com/tools#whois|type=ipv4&&value=2604:2000:12c2:9a6:9dda:2f85:c13e:dc00

which returns some of their blog posts, but little else of value.  looks unadulterated from ZC base code.  perhaps i have done too many lookups??  (which frankly i do not think i have done...)

but more importantly, for me, is the consistent use of an IP address.  i am trying to figure out if a malicious actor is the same person.  ideally, the apache log, the ZC error log, and the IP address in the orders table should all be consistent.  if they are, great!  and i will shut up...  but i'm not convinced that they are at this moment

**Comment by drbyte** [comment]
> but more importantly, for me, is the consistent use of an IP address. i am trying to figure out if a malicious actor is the same person. ideally, the apache log, the ZC error log, and the IP address in the orders table should all be consistent. if they are, great! and i will shut up... but i'm not convinced that they are at this moment

Zen Cart can only report on the data it receives. If someone is spoofing, Zen Cart can only do so much to uncover that fact. Zen Cart reads proxy details as passed through to PHP from Apache(or whatever http server), which reads its data from whatever other filters (ie: firewall systems) the server/hosting-company might have in place to identify the authenticity of a visitor's fingerprint.

So: if Zen Cart receives an ipv6 address, that's what it will record. Same if it receives an ipv4 address: that's what it will record.

> ... both services lookup accepts both ipv4 and ipv6 interchangeably: even the dnsstuff response to a type=ipv4 request with an ipv6 IP passed to it will still do a useful lookup.

> a (ipv6) link ... (for dnsstuff)  returns some of their blog posts, but little else of value.

The tests I did used a shorter ipv6 address. Evidently the longer address doesn't work even when specifying ipv6 as the type. You can use whois.domaintools .com as an alternate.
