### ISSUE TITLE
html_output, zen_draw_hidden_field: value only auto-populated with type string

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2960]
`} elseif (isset($GLOBALS[$name]) && is_string($GLOBALS[$name])) {`

Why only strings? Why not other types?

And is this related to the practice of not casting (integer) variables to integers at the start of a script, but only when they are used in a query?

**Comment by drbyte** [comment]
Can you elaborate on how this came up as a problem for you?
Apparently you wanted it to do something that it didn’t. 
What and why?

**Comment by torvista** [comment]
Working on Multiple Product Copy mod.
The first page is a form of search criteria.
On submit it reloads the page (with that POST data) to show some results.
To try again/modify those results/go back to the previous form, there are a load of hidden fields to re-POST the search criteria back/make the form fields sticky
eg:
echo zen_draw_hidden_field('copy_as');
These hidden fields are populated as per this thread title, but not for those globals that I have sanitized to integers: 
$copy_as = (int)$_POST['copy_as']
at the start of the script start, so to use $var in the script instead of using them as (int)$_POST[''var] all the time. Seemed cleaner, but threw up this issue.

So, the real question is how best to re-POST those variables back, apart from manually loading them.
echo zen_draw_hidden_field('copy_as', $_POST['copy_as'])

**Comment by Zen4All** [comment]
Take a look at product_preview.php. I belies there is a function there that reposts all post values to hidden fields.

**Comment by drbyte** [comment]
> Why only strings? Why not other types?

As to "other" types, I think the only "other" type I'd consider "safe" for passing through with that function would be (int) ... which would handle your use-case. I'm not opposed to a PR with that change.

**Comment by torvista** [comment]
That  Re-POST chunk crops up in several places so I think I'll use that.

However, the IDE complains about this, and it does seems wrong to me....should not the !array test be on $value instead of $key

foreach($_POST as $key => $value) {
            if (!is_array($_POST[**$key**])) {

**Comment by Zen4All** [comment]
I think your ide is a bit to strict. Just ignore it.

**Comment by torvista** [comment]
... I'll blame it on the hangover.

**Comment by torvista** [comment]
I've had a long stare at this and want a second opinion.
Does this make sense to anyone:
![Clipboard01](https://user-images.githubusercontent.com/4391026/70866480-6d5c9580-1f6a-11ea-9dd9-5ac41f5cbd07.gif)

or do you reckon its a bug similar to this:
https://github.com/kalessil/phpinspectionsea/issues/968

**Comment by drbyte** [comment]
Array keys are normally integers or strings, but POST keys "could" also be arrays, such as when you're parsing multi-language fields in one form where the field name is the same but for the language key. 

It could be that the EA parser is ignoring that $_POST is involved, or it could be pointing out that your code is indeed using POST arrays and thus this code block won't treat those correctly. 

All depends on your context.

**Comment by torvista** [comment]
FYI it's a PHPstorm "problem":
https://github.com/kalessil/phpinspectionsea/issues/1468
