### ISSUE TITLE
PHP Notice: Undefined index: page in specials and featured

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2969]
Just finishing some minor fixes for specials.php
https://github.com/torvista/zencart/tree/specials
only this error is left.

```
// reset page when page is unknown
                    if ((empty($_GET['page']) || $_GET['page'] == '1') && !empty($_GET['fID'])) {
                      $old_page = $_GET['page'];
```
caused by adding a new special price.
GET(page) is not set so error is triggered by $old_page = $_GET['page'];

But I see variations on this code scattered through admin, so not sure if this is a mistake /what is the correct solution.

**Comment by scottcwilson** [comment]
Was this fixed in #3062 ?  When I retested specials after this merge, I didn't see any issues.

**Comment by torvista** [comment]
It looks the same, but I didn't get any errors either....

**Comment by torvista** [comment]
This is still an item. The same code exists in both specials and featured:
```
// reset page when page is unknown
                    if ((empty($_GET['page']) || $_GET['page'] == '1') && !empty($_GET['fID'])) {
                      $old_page = $_GET['page'];
```
The first addition (of a special/featured), causes the "PHP Notice: Undefined index: page" referring to the line:  $old_page = $_GET['page'];
Similar code is in category_product_listing ($old_page = $_GET['page'];), but that code I think needs review too as it should have brackets around the clauses.

Not sure of the correct approach for this....
