### ISSUE TITLE
Adding cost, markup and margin to the product editing screen

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2975]
Any objections to or thoughts on this?  Many businesses like to price on a margin or markup basis, and we could make this model available to Zen Cart users without too much work.

**Comment by torvista** [comment]
This implies a cost field...linking to the big picture of Dual Pricing which I am all in favour of.
https://github.com/zencart/zencart/issues/2678

**Comment by Zen4All** [comment]
[Products Profit/Margin Calculator + Report](https://www.zen-cart.com/downloads.php?do=file&id=175) is a good base for cost price

**Comment by lankeeyankee** [comment]
It would be best if it could be configurable on/off somewhere, there will be users that do not want this since they use accounting or erp software which controls these aspects. It would add unnecessary clutter to the collect info page for these users.

**Comment by Zen4All** [comment]
> It would be best if it could be configurable on/off somewhere, there will be users that do not want this since they use accounting or erp software which controls these aspects. It would add unnecessary clutter to the collect info page for these users.

That is easy to code

**Comment by scottcwilson** [comment]
Targeted for 1.5.8 or a future release.

**Comment by scottcwilson** [comment]
Closing for now.
