### ISSUE TITLE
Admin page registration GUI feedback, instantiate messagestack earlier, return values

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2979]
While fiddling with auto-adding a new menu page, I see that zen_register_admin_page adds an entry to the admin log, but there is no on-screen indication of anything having happened.
messageStack is instantiated after the admin_access functions so is not available.
a) Could this be moved earlier to provide this?
b) On a successful registration, zen_register_admin_page could return the values it was called with, to provide variables for use in the user confirmation message.

**Comment by mc12345678** [comment]
Perhaps some sort of intermediate handler would be necessary.

This is what I see with trying to move the as provided `message_stack` class to an earlier load point:
The `message_stack` class (loaded at load point 100) depends on session data being available.
Session data is made available at load point 60 which also is well after the load point for the associated function.  
Further, the message_stack class does not provide a method to possibly move the session data to the `$this->errors` array at a later point and if the `__construct` method were again called where that session data is moved, then any data previously stored in `$this->errors` is removed by the first line of code in the method.

Perhaps a global variable could be set that is then "converted" or referenced at least after the session has been started to incorporate/produce the message that is to be shown.

I think that something like this was previously discussed back in Zen Cart 1.5.3 or earlier where the request was to modify or remove the `$this->errors = array();` statement from the `__construct()` method, though I'm thinking that actually perhaps a better solution is to move the code:
````php
      if (isset($_SESSION['messageToStack']) && is_array($_SESSION['messageToStack'])) {
        for ($i = 0, $n = sizeof($_SESSION['messageToStack']); $i < $n; $i++) {
          $this->add($_SESSION['messageToStack'][$i]['text'], $_SESSION['messageToStack'][$i]['type']);
        }
        $_SESSION['messageToStack'] = '';
      }
````
to a separate method within the class may be better and to have that method called from the `__construct`.  This way, if the class is instantiated prior to the session, at least the `add` method could be used and a later trigger point could be incorporated to transition `$_SESSION['messageToStack']` into `$this->errors` and therefore as applicable that method could be executed.



(Some time later)
And after all of that above, I created a PR to support making the above "possible". See https://github.com/zencart/zencart/pull/2984

**Comment by torvista** [comment]
...had/have no time to look at this yet, thanks for the effort.

**Comment by mc12345678** [comment]
Haven't had a chance to functionally test it myself. I do apologize that while the comments say "fixes" this, it really is only to offer the opportunity for implementation of what you described above. So... don't be surprised if this thread "temporarily" closes if/when the above is accepted.
