### ISSUE TITLE
Multiple Product Copy Delete - mod peer review

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2985]
I would be grateful for some feedback on this, 
https://www.zen-cart.com/showthread.php?180447-Multiple-Products-(Copy-Move-Delete)
with a view to a future PR.
https://github.com/torvista/Zen-Cart_Multiple-Products-Copy-Move-Delete
thanks

**Comment by torvista** [comment]
I don't envision further changes on my part....so do I prepare a PR for this yet?

**Comment by torvista** [comment]
I have had no feedback on this whatsoever, so
a) it's perfect 🤣 
b) it's not as essential as I consider it to be, and should stay a plugin, which would be a shame after all the work I put into it.
c) I should just PR it anyway and damn the torpedoes.
 
Answers on a postcard please (for older viewers who remember such things)....

**Comment by drbyte** [comment]
It's written as an additional admin page. Do you envision it being kept separate? or to replace another page?

**Comment by torvista** [comment]
Kept separate, in the list next to product to categories, as they are complementary.

**Comment by lankeeyankee** [comment]
I have installed and briefly tested. I like it and haven't found any issues with my limited testing. One feature request would be to allow multiple product selections by holding the ctrl to select individually or shift to select a range. That way you can change the master category ID and/or multi-link multiple items at once which would definitely be a big time saver. That might require some JS to work, I am thinking of this functionality from the advanced shipper module and how much time it saves me by allowing multiple selections.

**Comment by torvista** [comment]
>  I am thinking of this functionality from the advanced shipper module
I'm not sure, which aspect of AS you are referring to...?

**Comment by lankeeyankee** [comment]
Sorry, the popup where you select items/categories/manufacturers to add to a method. You can multi-select in those lists.

**Comment by torvista** [comment]
Yes I see. I don't think I'll be up to doing that soon....see what the verdict is on the current functionality...but be my guest!

**Comment by lankeeyankee** [comment]
If I was capable, I'd certainly do it. Alas, my coding skillz are less than wafer-thin. Just thought I'd throw it out there in case it was an easy add for you. Otherwise, it's looking good and is definitely a handy function to have, thanks so much for extending it and sharing.

**Comment by torvista** [comment]
> less than wafer-thin

Unfortunately most days my brain feels like Mr. Creosote.

**Comment by torvista** [comment]
Given the end is nigh,
https://github.com/zencart/zencart/issues/2973#issuecomment-612686832
PR today or not?

**Comment by scottcwilson** [comment]
This is a lot of code.  Save for 1.5.8?

**Comment by torvista** [comment]
It's been under my virtual feet around for months, I'd like to get it out of the way really.

**Comment by lankeeyankee** [comment]
I have not found any issues with it using for a couple weeks.

**Comment by torvista** [comment]
Have you used all the options?

**Comment by torvista** [comment]
>This is a lot of code. Save for 1.5.8
If I submit it, is it not easier for people to try out?
I can always cancel the PR.

**Comment by lankeeyankee** [comment]
> 
> 
> Have you used all the options?

Yes, and have not had any issues to report

**Comment by scottcwilson** [comment]
Should this issue be closed since there's a PR waiting for 1.5.8?

**Comment by drbyte** [comment]
> Should this issue be closed since there's a PR waiting for 1.5.8?

No. We don't need to close every issue.

I've linked this issue to the PR so it will close when the PR is merged.

**Comment by drbyte** [comment]
> If I submit it, is it not easier for people to try out?

Yes, in many cases having an PR makes evaluating the changes much easier.
