### ISSUE TITLE
What lightbox tool is most mobile+desktop friendly these days?

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#299]
For the new template in v1.6.0 I'd like to incorporate a lightbox for product images (main image, plus additional images), and maybe even feature/specials images (although that's maybe more of a carousel thing) but I want something that's very mobile-friendly ... such as just start swiping left/right on product images to see more ... maybe without even needing to click the image to "start" the swipe capability. 

Without implementing jQuery-Mobile, what do you suggest? 

(Keep in mind the current implementation is based on jQuery 1.11, and is geared around Zurb Foundation as the css/js framework, so suggestions should ideally be based on tools that would work with that combination with minimal extra configuration required. The simpler the better for storeowners and template designers to be able to customize, of course.)

**Comment by wiztechinc** [comment]
I would prefer to see something specially coded for this. Too many of the
existing lightboxes are just more complicated than necessary - leading
towards heavier files loads.

I use the basic fancybox - 48kb. I think it needs to be simpler and lighter
weight than that. - and would be nice, I guess, if it was expandable by
adding js files to it. Think basic functionality - for example
http://deliatest.com/1_5_3/index.php?main_page=product_info&cPath=1_9&products_id=26

Delia Wilson Lunsford
WizTech, Inc., (formerly Delia Wilson Design, LLC.)
434-202-4307
Terms and Conditions for working with WizTech, Inc.
(http://www.teamwiztech.com/terms-conditions.php)

**Comment by DivaVocals** [comment]
Zen Colorbox.. It works and is responsive..

**Comment by Zen4All** [comment]
Zen Colorbox was my first choice to, but have to admit I'm not a real expert

**Comment by wiztechinc** [comment]
As an example of how little jquery it can take to do big things. I paid
someone to do the jquery for both of these. And the jquery is all in the
source

Additional images hover
http://zencartdelia.com/testing/index.php?main_page=product_info&cPath=23&products_id=180
attributes images hover
http://zencartdelia.com/testing/index.php?main_page=product_info&cPath=23&products_id=84


Delia Wilson Lunsford
WizTech, Inc., (formerly Delia Wilson Design, LLC.)
434-202-4307
Terms and Conditions for working with WizTech, Inc.
(http://www.teamwiztech.com/terms-conditions.php)

**Comment by IronLady** [comment]
Regarding the lightbox choices. 

1. Colorbox for its lightweight.
2. Swipebox for its ability to swipe next/prev image inside the lightbox
3. Magnific Popup for its flexible API. Example of magnific popup in ZC is <a href="http://demo.pepperthemes.com/morphling/demo/index.php?main_page=product_info&products_id=1" target="_blank>here</a>

**Comment by DivaVocals** [comment]
https://github.com/AndrewBerezin posted a solution to adding swipe support to Colorbox:
https://github.com/jackmoore/colorbox/issues/395#issuecomment-44210822

**Comment by drbyte** [comment]
All of this feedback is greatly appreciated.

We'll take a look at these. 

If additional suggestions come up, please post them here too!

**Comment by Spike00** [comment]
Hello Chris, is there somewhere a discussion about the new template and the mobile stuff?
I think that the first decision is between an all in one solution going with a responsive template, vs a solution which provides a mobile version different from the desktop version. I know Google push towards  the responsive solution, but for an e-commerce, where there may be a lot of stuff not needed / useful in the mobile version, I believe it's much better not to simply hide it, but not to create it at all, of course due to performance reasons. I'd like to discuss this topic, of course if it has not already been discussed and closed :)

**Comment by DivaVocals** [comment]
@Spike00 wouldn't it be better to create a NEW issue for a template discussion versus hijacking this one (which is regarding lightbox solutions??) It's pretty easy to search the existing issues to see if there is an existing conversion going with regards to templates..

**Comment by Spike00** [comment]
@DivaVocals of course, if I wrote here, I thought it was appropriate, both because the topic could have bene discussed in many places, so my first question was about the existence of the discussion somewhere, and then, the topic could change the answer to the question about a lightbox being at the same time mobile and desktop friendly. In other words: before discussing of a responsive solution, I asked if it has already been discussed if going responsive or not.

**Comment by IronLady** [comment]
@Spike00 https://github.com/zencart/zc-v1-series/issues/304

**Comment by DivaVocals** [comment]
@Spike00 Understood, but I think it's clear, that this particular thread is simply regarding lightbox solutions, not a full on template discussion..

**Comment by scottcwilson** [comment]
Thank you @Spike00  and @IronLady.  I think this topic is critical.

**Comment by zcadditions** [comment]
Not a function every site owner will need or want.

There are hundreds  of image light-boxes and all have different features and options, IMO I would focus on simplifying the core image structure to better handle adding light-boxes, carousels, swap effects, ect. as an "optional" plugin.

**Comment by mc12345678** [comment]
However, much of the comment by outside organizations/reviewers are based on what ecommerce applications come with out-of-the-box... If capability is limited to the ability to add on other options then little further progress will be seen by those that are trying to find their first/next ecommerce solution. Not to say that perhaps image the structure couldn't be improved, but in a way many of the changes being made are to improve on the out-of-box experience and then to the "I want something different" perspective.  ZC already offers ways of incorporating new/different other methods to support "optional" plugins.  The other discussion above offers an improved out-of-the-box experience.

**Comment by zcadditions** [comment]
yea, completely understandable. As it's being bloated with foundation as its framework, why implement a 3rd party light-box, why not just continue to build of the foundation framework for the "New" template keeping the core of the template consistent which would create a improved consistent out-of-box experience.

**Comment by drbyte** [comment]
What about http://photoswipe.com ?

**Comment by wiztechinc** [comment]
promising. I would have to use it to see if I have problems with it. I don't like some of what it says but don't know how actual images would be affected. 

I do think anything should be expandable - in that basic use would only incorporate a small bit of js - expanding to add other functions then could be accomplished by having an auto switch to a larger js. No one has come back to me and asked for anymore than the basic. They seem to be quite satisfied - just thinking about the customers who may want it fancied up.

**Comment by Zen4All** [comment]
@drbyte This is looking good. Right now I am viewing the tool on my tablet and I am pleasantly surprised with it's functions.

**Comment by IronLady** [comment]
Photoswipe is good, I used it too. You can see it in action [here](http://demo.pixelgue.com/valyria/index.php?main_page=product_info&cPath=3&products_id=24&zenid=411b7cdc5704fa1333ff89ac735a75a9) by clicking on any product image

**Comment by drbyte** [comment]
I'm discovering that a lot of formerly-very-popular js-driven lightbox tools are no longer actively maintained.

Is this just because there's a large shift away from jQuery-based things? 
Or is it because there are better tools that we should be considering instead?

**Comment by wiztechinc** [comment]
The ones that have been popular were too much (too fancy, too heavy, too complicated) as far as I was concerned and I have one better integrated and smaller in size than any others.

**Comment by drbyte** [comment]
I'm all for lighter weight!  usually easier to maintain that way too, and less clashes with other JS-driven tools. 

Mind sharing which one that is? Link?  I'd love to check it out.

**Comment by drbyte** [comment]
Or do you mean the custom one you talked about a few posts back?

**Comment by wiztechinc** [comment]
fancybox - all I did was dump the js file into the product info folder, add smidge of css and attached a class to the product image, the attributes images and the additional images - so it is the one I was talking about before.  The js is 48kb. It is a project that has been maintained over the years but what I said before is that it can be done better for this purpose. My experience has always been to let a friend of mine look at my request and how zen cart works and he always comes up with small ways of doing things. That's what zen cart needs - not a project that has to be kept up with and have us dependent on them. I'm really quite sure this can be done for little money - my friend does not work for free but he is cheap.  And yeah, I know, we need volunteers but I don't know a good js programmer who will work for free - and most of the rest of us just aren't that knowledgeable - thus the use of varying existing projects. But the lightbox is not passing fad any longer. I consider it a must and one of the things that usually comes with a packaged template - free or paid. Not having it makes zen cart just look really old fashioned and clunky.
