### ISSUE TITLE
admin: zen_get_countries includes disabled countries

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#2991]
The storefront version of the function properly returns a country-list including _only_ (under function parameter control) the countries currently enabled for a store.  The same cannot be said for the admin version of that function (present in `/admin/includes/functions/general.php`).

**Update:** Noting that the function is used by the admin's `customers.php`, `geo_zones.php`, `index_setup_wizard.php1 and `zones.php` (as well as a couple of plugins).

**Comment by drbyte** [comment]
What was the use-case that exposed this to be a problem? ie: were you just editing a customer record? 
Or working with a plugin that edits orders and allowed you to access countries that it shouldn't?
etc?

**Comment by lat9** [comment]
It's our `friend`, **_Edit Orders_**, which is currently using that built-in processing.

**Comment by lat9** [comment]
I can see, now, that having *all* the countries available via those admin functions _is_ needed, allowing an admin to view all customers' addresses.

How about the admin version of `zen_get_countries` at least contain some indication (like `(*)`) to identify that a country is disabled?
