### ISSUE TITLE
layout settings, box widths reduced to integers: width has no units

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2993]
eg:
Admin->Configuration->Layout Settings->Column width - Left Boxes
default is 150px and text states px may be used.
In fact this is stripped by this:
`$column_width = (int)BOX_WIDTH_LEFT;`
leading to this:
`<div class="leftBoxContainer" id="<?php echo str_replace('_', '-', $box_id ); ?>" style="width: <?php echo $column_width; ?>">`
resulting in this:
`<div class="leftBoxContainer" id="documentcategories" style="width: 150">`
and this warning

> CSS: “width”: only “0” can be a “unit”. You must put a unit after your number.

So, while this can be easily fixed to be consistent and remove the error for px, does it not need to be re-thought to handle any units?

**Comment by drbyte** [comment]
Units have been forced to `px` directly within the template via https://github.com/zencart/zencart/pull/3442
