### ISSUE TITLE
many cookies, cross-site resource, SameSite warnings

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2995]
I notice while navigating around categories the creation of many cookies:
![cookies](https://user-images.githubusercontent.com/4391026/72330198-59fe3080-36b6-11ea-87d0-8ed32f7cb8c4.gif)
These generally are created on the first entry into a category (not subsequent entries) and disappear when entering into another category.
Since each one triggers a warning about the SameSite attribute requiring to be set in the near future (Chrome 80), I was wondering what is the explanation for all these creations/deletions?

**Comment by Zen4All** [comment]
Those are mostly cookies for the zen cart site, how is it possible they appear on your own site?

**Comment by torvista** [comment]
I've since restarted the pc and looked again...now all is expected with only the zenid. Possibly at the time I had a zillion other tabs open and Developer Tools was showing them too..?!
