### ISSUE TITLE
spiffycal - not localised

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3014]
Just noticed this only offers EN month names.
Looking at the code it is very old (2001) and the IDE lights up like a xmas tree with all the things it doesn't like...is there a plan for an update/replacement?

**Comment by Zen4All** [comment]
Spiffy is planned to be phased out. I have made a start at the product pages (collect_info.php).
This page uses datepicker. You can use that code as a guide

**Comment by torvista** [comment]
Great. Done that for Specials..

**Comment by torvista** [comment]
Just for cross-reference:
https://github.com/zencart/zencart/issues/3020
