### ISSUE TITLE
Admin login updates

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#3015]
I  know that the admin login page has been revamped not so long ago, but there are stile some problems with it.
- it is not resizing correctly on small screens
- the alt-stylesheet is for 90% a copy of the bootstrap css

I have made an updated login page, as well as the password forgotten page, which can be seen [here](https://zc157.zen4all-dev.nl/sOund-fIO-matCh)
- These page now make use of bootstrap.
- I also added a view password button as an extra, but this can be left out.

**Comment by drbyte** [comment]
I'd be open to a PR.

Let's skip the "view password" part. I don't see it serving a beneficial purpose.

You might want to fix the line-breaks in the generated HTML:
<img width="3190" alt="Screen Shot 2020-01-20 at 10 09 49 PM" src="https://user-images.githubusercontent.com/404472/72772455-ea1a0980-3bd1-11ea-99fa-28bdb34bdbea.png">

**Comment by drbyte** [comment]
Closed by #3019
