### ISSUE TITLE
query_factory.php queryFactoryResult class calls non-existent method

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#3016]
For the life of me, I am not entirely sure how I was able to cause the error triggered at: 
https://github.com/zencart/zencart/blob/2d38f4758d3777595a38e616e419eb133c204255/includes/classes/db/mysql/query_factory.php#L684-L708

but in the last logic statement: `$this->set_error` is called; however, this class does not contain the `set_error` method, nor does the class inherit the `queryFactory` class where the function/method is defined.  

This was caused by my narrow resolution of https://github.com/zencart/zencart/issues/1745.

It appears that the issue could be resolved by extending the `queryFactory` class followed by implementing the interfaces that are currently referenced or the code associated with the `set_error` method could be duplicated in this class (I don't consider duplication to be as good of a solution).

**Comment by drbyte** [comment]
I'm guessing to trigger it would have required making a direct call to `Move()` and passing a row that doesn't exist.

Without exploring it yet, I think the best solution is to remove the line calling set_error, as it's not really necessary ... ie: triggering EOF is probably enough.

**Comment by drbyte** [comment]
Pinging @zcwilt

**Comment by mc12345678** [comment]
Well, I tried extending the `queryFactory` class and was presented myDebug files for loading both the catalog and admin that prevented page load. In essence mysqli_ was identified as not available when processing early load files. Can provide content of those in a separate post.

Reason I say not sure how I created the associated myDebug leading to this discovery is that I thought the associated code made appropriate checks to prevent a problem going to `Move(0)`, which I remember was the out-of-bounds call that caused the myDebug file to be generated. 

Perhaps a `trigger_error` instead of a call to `set_error` to maintain the notification capability of the class?

**Comment by drbyte** [comment]
> I thought the associated code made appropriate checks to prevent a problem going to `Move(0)`, which I remember was the out-of-bounds call that caused the myDebug file to be generated.

I would have expected that condition to trigger for any invalid row specified, not specifically 0.

> Perhaps a `trigger_error` instead of a call to `set_error` to maintain the notification capability of the class?

Well given that call to `set_error` has been doing nothing for years, I'm certain nothing is directly depending on it. And I don't see the value of cluttering logs. If we had a full exception-handling subsystem then I'd consider throwing an exception that's already caught, just so advanced debugging could be available. But clearly nobody's been relying on this else it would have been reported years ago. So I'm reluctant to keep it. 
That said I know @zcwilt was involved with the refactor of QueryFactoryResult, so should get his input too.

**Comment by drbyte** [comment]
Having chatted with @zcwilt about it, pretty sure we'll just delete the call to set_error.

**Comment by mc12345678** [comment]
FYI, this does also apply to Zen Cart 1.5.6 and I found the myDebug log that was initiated identifying this issue, though was a little surprised that it came about on a shopping cart update (with a plugin that evaluates the shopping cart) and specifically triggered when calling the `Rewind` method.  Still trying to dig into the unusual series of events that led to the attempt to notify about the out-of-bounds condition. 

Wanted to report.

Thank you for identifying the planned path forwards.

**Comment by mc12345678** [comment]
To possibly round out this item and how it was initially identified:

Plugin attempted to store the results of an `Execute` query into a variable that was sustained in the session.  I decided to not try to keep the data and instead query again as applicable because I could not easily/quickly find a way to retain the full result of the query.  Part of the issue is that `$obj->resource` was not being retained and therefore when attempting to `Rewind` there was no data available and although the counter had a value of 2 indicating more than one record was returned, `RecordCount()` reported 0 and `Move(0)` reported that it basically was out-of-bounds. 

The idea was to nearly have a sort of cache of data locally stored so that a query did not need to be run again for a product, although the "memory" of that cache was to survive the session not just through a page load.  Further although the likelihood of the underlying data to change on any one session was considered low, having the current data on each page load makes more sense than trying to retain it from page to page for a session.

So on reconsideration of the previous usage, it seems that the data should have been collected for each usage rather than retained on a session basis and therefore the "new" direction is fine.  Doesn't mean that there isn't still something fishy going on or that something doesn't need correction (if even just for me to understand better), but I don't appear to have a continued use case needing resolution for retaining the query results within a session. (Even if I am still puzzled. :) )

**Comment by drbyte** [comment]
I suppose the call to mysql-seek could be preceded with a more rubust check to ensure that the same resource's known num_rows contains enough records.

However, I'm more inclined to use a session-cached array variable than a db-resource if I need to persist some data between sessions. Assuming it's not an insanely large dataset, of course.
