### ISSUE TITLE
messageStack->add_session not working

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3017]
The messages are going into SESSION but not being displayed.
In config_core.php, the breakpoint needs to be >60 to work.
```
  $autoLoadConfig[61][] = array('autoType'=>'classInstantiate',
                                 'className'=>'messageStack',
                                 'objectName'=>'messageStack');
```

**Comment by drbyte** [comment]
Have you updated since the messageStack update was merged?
https://github.com/zencart/zencart/pull/2984/files

**Comment by torvista** [comment]
Yes, I'm up to the minute. As soon as I change that to 60 it stops working.

**Comment by drbyte** [comment]
We're talking about the Admin, right?

The most up-to-date does the session stuff at 100.

**Comment by torvista** [comment]
The class instantiates at 32, the new method add_**from**_session runs at 100.
It's the 32 I have to change to 61 for ->add_session to work.
I guess from your questions you can't replicate the problem?

**Comment by drbyte** [comment]
32 is instantiating the class, and fires `__construct`

the `add_from_session`, called at 100, is what actually puts things into the session.

While the `__construct` also fires `add_from_session` at 32, when it fires at 100 it should work fine.

Perhaps it simply needs removing the `add_from_session` call from the `__construct` ?

**Comment by torvista** [comment]
with load at 32 and and_from_session removed from class, it still doesn't work.

**Comment by drbyte** [comment]
@torvista Normally calling `messageStack->addSession` happens before a `zen_redirect()` and then it's from that redirected state that the session content is displayed.

Are you calling zen_redirect?

**Comment by torvista** [comment]
Yes. I understand the difference between add and add_session.
Hence I found that all the error messages were correctly going into the session variable, building up that array, until I found what made it work. Then they all got displayed on the redirect.

Try adding a special via product id, with an empty field. Message goes to session, but not displayed.

**Comment by torvista** [comment]
Can anyone confirm they can replicate this issue...or it's just me?

**Comment by lat9** [comment]
Confirming.  The messageStack's class is now being instantiated _prior to_ the session's start and its constructor is pulling those messages from the (not-yet-established) session ... that's the issue.

I'll suggest that the messageStack's instantiation be moved to load-point 61, just after the session is established for proper operation.

**Comment by lat9** [comment]
My bad; I'm seeing (now) that there's an additional call to the `add_to_session` occurring at load-point 100.

**Comment by drbyte** [comment]
Init System bug fixed in https://github.com/zencart/zencart/commit/2ebd1a1a35940cd483d68daa5a4c775187f006b9
And messageStack updated to remove duplication.

**Comment by torvista** [comment]
Woohoo a _real_ bug!

**Comment by torvista** [comment]
This is not working again (odd phrase)...try MOVE or COPY product to its current category.
