### ISSUE TITLE
[Suggestion] Error logging: Include maximum error level in debug-filename

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#3022]
Giving credit where credit is due, one of my customers suggested that it would be a great help if the debug-log's file name identified the maximum error level, e.g.

```
myDEBUG-yyyymmdd-hhiiss-xxxxx.log (notices only)
myDEBUG-deprecation-yyyymmdd-hhiiss-xxxxx.log (contains at least one deprecation)
myDEBUG-warning-yyyymmdd-hhiiss-xxxxx.log (contains at least one warning)
myDEBUG-error-yyyymmdd-hhiiss-xxxxx.log (contains at least one error)
myDEBUG-fatal-yyyymmdd-hhiiss-xxxx.log (contains a fatal error)
```

Admin-level logs would use a `myDEBUG-adm` prefix.  It would be possible to have up to five separate logs generated for a single page-load, assuming that a notice, then a deprecation, then a warning, then an error and finally a fatal-error occurring on that load.

Essentially, the log-file's name would start presuming notices and be modified each time a 'higher' level of error was detected.

Any interest?  Note that I'll be updating "Report All Errors" to contain this functionality.

**Comment by wiztechinc** [comment]
That could help - but really the biggest issue I have is logs not writing to the log folder on a specific hosting but instead they write to the site logs and you have to access cpanel and wade through way worse than the log folder. I do believe Chris is aware of this issue (and I think it has to do with a specific php vehicle?) but if there was anyway to get that tended to in addition I sure would be extremely grateful. 

Most sites that I access either have no error logs or so many that it's best to dump the folder and start over so what you are suggesting is nice but not as helpful as one might think.

**Comment by lat9** [comment]
Understood, do you or @drbyte have any 'footprint' that's common to the 'no logs generated' condition?

If that was determined, at least an admin-level notification (via the messageStack) could be issued to let someone know that the code knows that there's going to be an issue?

**Comment by drbyte** [comment]
The footprint might be able to be determined by the phpinfo output (Admin->Tools->Server Info) ... and looking for where it says the error log is put (assuming ZC was unable to override it)

**Comment by drbyte** [comment]
Probably fastest to copy/paste that page into a text file ... from both a "working" and "non-working" site, and compare the text files.  ... rather than trying to paste the whole thing here.

**Comment by wiztechinc** [comment]
definitely the problem reads: 
/home/xxxxx/logs/xxxxx_com.php.error.log for both local and master 

and the one that still writes to the log folder is 
/home/xxxxxx/public_html/logs/myDEBUG-adm-1579640510-588221.log for local and master says error_log
--

**Comment by wiztechinc** [comment]
uh, have no idea why the bold and larger font. 

Still can grab both full php info output but there is a site somewhere on the same hosting with an older server. I just have to figure out which site ... That info above is from two different hosting companies.

**Comment by drbyte** [comment]
I suppose after setting the error log file destination we could read it back to see if it got set properly.

But I'm not sure about setting a messageStack alert, since if it's not something ZC can control, then it's quite likely that the hosting company isn't going to "fix it" either, and then it's just an annoying alert, which eventually people become blind to, but then they're also blind to "real" alerts that show up in a true problem situation, so that's not ideal.

**Comment by drbyte** [comment]
> it would be a great help if the debug-log's file name identified the maximum error level

Can you describe "great help" in more detail? 

If the "real" desire behind the suggestion is to just ignore lower-level messaging while in production, then just set the reporting level accordingly.

If the intention is to just delete the lower-priority stuff, ignoring it, then why chew up server space at all in the first place? Just tell the logging to ignore it.


> ```
> myDEBUG-yyyymmdd-hhiiss-xxxxx.log (notices only)
> myDEBUG-deprecation-yyyymmdd-hhiiss-xxxxx.log (contains at least one deprecation)
> myDEBUG-warning-yyyymmdd-hhiiss-xxxxx.log (contains at least one warning)
> myDEBUG-error-yyyymmdd-hhiiss-xxxxx.log (contains at least one error)
> myDEBUG-fatal-yyyymmdd-hhiiss-xxxx.log (contains a fatal error)
> ```
> 

Somehow that feels like a non-trivial change to make. Maybe not.  If it's a one-liner then okay. But if it adds several dozen if/else things or a bunch more complexity then I worry we're solving the wrong problem.

**Comment by drbyte** [comment]
> uh, have no idea why the bold and larger font.

It's a Markdown syntax thing: You followed on the next line with a `--` which tells it to treat the line above as a heading. ;)

**Comment by lat9** [comment]
Doesn't `zc_install` now check to see that the `/logs` directory is writeable?

**Comment by torvista** [comment]
regarding logs not being written where expected, I'm not sure if this is still an issue:
https://github.com/zencart/zencart/issues/2686

**Comment by wiztechinc** [comment]
> Doesn't `zc_install` now check to see that the `/logs` directory is writeable?

Yup - this is not the same thing. These servers refuse to put the logs in the log folder. I have no idea why and no one has spent much time trying to figure it out. Bad enough to have to use cpanel to see the logs but when that one log folder is mgs large, well, you might think it was unwieldy. 

Thanks Chris, I use all sorts of punctuation to express ideas and will be more traditionally boring from here out.

**Comment by wiztechinc** [comment]
> regarding logs not being written where expected, I'm not sure if this is still an issue:
> #2686

Definitely not the same thing. This happens when you move sites from one server to another. My server had no issues but the new servers at my favorite zen cart hosting company react this way with no changes. We are not talking new installs, folks. 

And this has been identified for some time now. And I just moved all my sites to the other company from my own server. So it's a bigger issue for me now than a year ago.

**Comment by drbyte** [comment]
> These servers refuse to put the logs in the log folder. I have no idea why and no one has spent much time trying to figure it out. Bad enough to have to use cpanel to see the logs but when that one log folder is mgs large, well, you might think it was unwieldy.

I'm not sure it's an issue Zen Cart can solve.

At least you do have cPanel to access it!

**Comment by wiztechinc** [comment]
uh, so I really don't like that response. I know it's server related and I think Q may even know why. It just makes my life so much harder. There must be a solution to this considering how many zen cart websites we are talking about. Not a small issue

**Comment by lat9** [comment]
> 
> 
> definitely the problem reads:
> /home/xxxxx/logs/xxxxx_com.php.error.log for both local and master
> and the one that still writes to the log folder is
> /home/xxxxxx/public_html/logs/myDEBUG-adm-1579640510-588221.log for local and master says error_log

I'll note, based on that debug-logname format, that you're apparently running a version of Zen Cart _prior to_ 1.5.6.  The updates to the logging interface at that time converted the format (and now overrides the PHP base logging via the `error_log` function).  The new format is similar, but sortable:

`myDEBUG-[adm-]-yyyymmdd-hhssii-mmmm.log`.

**Comment by mc12345678** [comment]
Would whatever naming convention still provide a sequence order of the logs such that the first "issue" appears before the "last"? 

Often a final higher order issue is caused by the various lower level issues and wouldn't want the issue caused by the lower level problems to be necessarily the most recent log to then have to weed through the other lesser issues in some haphazard sequence.  

Certainly notices and deprecations either individually or combined would provide development assistance as they might allow continued current operation but lead to future higher order issues.

**Comment by lat9** [comment]
Good point, @mc12345678; I'll keep that in mind.

**Comment by lat9** [comment]
Yep, using the following naming convention will enable those logs to be shown at least in a time group:

```
myDEBUG-yyyymmdd-hhiiss-xxxxx.log (notices only)
myDEBUG-yyyymmdd-hhiiss-xxxxx-deprecation.log (contains at least one deprecation)
myDEBUG-yyyymmdd-hhiiss-xxxxx-warning.log (contains at least one warning)
myDEBUG-yyyymmdd-hhiiss-xxxxx-error.log (contains at least one error)
myDEBUG-yyyymmdd-hhiiss-xxxxx-fatal.log (contains a fatal error)
```

**Comment by wiztechinc** [comment]
> I'll note, based on that debug-logname format, that you're apparently running a version of Zen Cart _prior to_ 1.5.6**a**. The updates to the logging interface at that time converted the format (and now overrides the PHP base logging via the `error_log` function). The new format is similar, but sortable:
> 
> `myDEBUG-[adm-]-yyyymmdd-hhssii-xxxxx.log`.
> 
> **Updated:** That change was introduced in zc156**a**, with the trailing `xxxxx` being the milliseconds, addressing `php-fpm` installations.

Whoa, thank you for figuring that one out. Just installed a 1.56 site - error log reading correctly now in phpinfo. Will see if an update can fix this issue on older sites. Thanks!!!!!

**Comment by lat9** [comment]
Yep, I've got a client with 'Q' and I couldn't deal with the php-fpm/no logs syndrome.

**Comment by barco57** [comment]
Guys, it is a cPanel PHP-fpm thing, not really something we have yet to figure out.

**Comment by wiztechinc** [comment]
> Guys, it is a cPanel PHP-fpm thing, not a thing that we have found a resolution for, and digging around on cPanel forums and the wider internet not produced a resolution.

I would love a fix that doesn't require upgrading. How about a patch if we've identified the source of the issue?  Can anyone direct me to some code at least where this changes for 1.5.6?

**Comment by drbyte** [comment]
> I would love a fix that doesn't require upgrading. How about a patch if we've identified the source of the issue? Can anyone direct me to some code at least where this changes for 1.5.6?

It's all driven by:
/includes/extra_configures/enable_error_logging.php
(and the admin equivalent file has its own changes, which now simply point to the non-admin file)

**Comment by wiztechinc** [comment]
Just in that one file? Do see multiple changes between 1.5.5 and 1.5.6. Does it all come down to this?
 If so, can just replacing the file work? : $log_prefix = (IS_ADMIN_FLAG) ? '/myDEBUG-adm-' : '/myDEBUG-';
$log_date = new DateTime();
$debug_logfile_path = DIR_FS_LOGS . $log_prefix . $log_date->format('Ymd-His-u') . '.log';
unset($log_prefix, $log_date);

**Comment by wiztechinc** [comment]
oh, yuck. So in an addon domain with 1.5.5f running on 7.1 does put the error logs in the folder. One on 5.6 does not. Could the php version be the root of the issue?

**Comment by drbyte** [comment]
> oh, yuck. So in an addon domain with 1.5.5f running on 7.1 does put the error logs in the folder. One on 5.6 does not. Could the php version be the root of the issue?

Each PHP version's settings are compiled separately, so yes conceptually it "could" be the PHP version ... but not because of the version so much as the configs chosen when compiling it.

**Comment by wiztechinc** [comment]
both sites are on the same server

**Comment by lat9** [comment]
@wiztechinc, for Zen Cart versions prior to 1.5.7, you can use the [plugin](https://www.zen-cart.com/downloads.php?do=file&id=1792) from which the functionality was derived.
