### ISSUE TITLE
zc_install: No database collation choice on initial installation

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#3034]
On an initial install, as the subject indicates, there's no choice offered for the database collation.  The install completes, using `utf8mb4_general_ci` collation.

I'm seeing the following in the test site's /logs directory:
```
[24-Jan-2020 13:04:40 Europe/Berlin] PHP Notice:  Undefined index: db_charset in C:\xampp\htdocs\test_utf8\zc_install\ajaxLoadMainSql.php on line 22
[24-Jan-2020 13:04:46 Europe/Berlin] PHP Notice:  Undefined index: db_charset in C:\xampp\htdocs\test_utf8\zc_install\ajaxLoadMainSql.php on line 38
```

**Comment by lat9** [comment]
Removed via [this](https://github.com/zencart/zencart/commit/eda04664982206c40089f0591fc6ecd18d708ed4#diff-1e16f22e8f523b2389ad8724c452e44c) commit back in September cryptically titled "Update database default".

**Comment by ScotteSolutionsLtd** [comment]
Hi all, what would be the ideal situation here? In regards to the database installation step and dealing with charsets:
- allow the user to choose from a static list
- use the default reported by the server once successful connection has been made (which is basically what happens now and should be sufficient?)
- add a button/ajax that can grab a list of charsets from the server (after db creds are entered and prior to form submission). This would also serve to test the database connection prior to submitting the form in the database step. Submitting the form could then include an alternate charset.

**Comment by torvista** [comment]
Well Shirley leaving it up to the default db collation is not a good thing (latin/swedish)...especially at this point when most if not all users of the installer have absolutely no clue of the significance of these things and the pita that it can be to fix later on.

**Comment by drbyte** [comment]
If you don't use `utf8mb4` (which we support) or some other long-multibyte-friendly format, then if customers enter emojis in order comments you'll get PHP Fatal Errors because the database rejects the insert.

Thus I'm inclined to leave it at only a single choice.
