### ISSUE TITLE
admin: sorting tables, recommended method?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3038]
There are several pages where users would want to change the displayed sort order (pPID, model, name, price, date etc.), ideally by clicking on icons next to the column title.
Is there a recommended method to implement this, either already existing in core or in some well-written plugin, that we could standardise on?

**Comment by Zen4All** [comment]
Like this ??
![Screenshot from 2020-01-26 12-02-31](https://user-images.githubusercontent.com/2766593/73134226-5febfe00-4034-11ea-85cd-dfc122662356.png)

**Comment by torvista** [comment]
Yes, looks good.

**Comment by proseLA** [comment]
hopefully, this would address the problem that i see here:

https://github.com/zencart/zencart/blob/c80db1cb9b46d08de18c03606713c3050a06d165/admin/category_product_listing.php#L431-L450

if there is not a ```$current_category_id```, then the sorting choices are for category as opposed to product.  if one does a search when on this page, and products show up, one can not sort the products at all.  and changing the ```$zc_skip_products``` to false and then attempting to sort, one loses the search criteria previously entered and reflected in the ```$_GET['search']```.

**Comment by lankeeyankee** [comment]
> Like this ??
> ![Screenshot from 2020-01-26 12-02-31](https://user-images.githubusercontent.com/2766593/73134226-5febfe00-4034-11ea-85cd-dfc122662356.png)

That would be really nice to have implemented, including all of the column sorting.

**Comment by torvista** [comment]
While the front end can look the same whatever method is chosen, I was interested in developers choices for their plugins and any conclusions they have come to as to the "best" method to use.
I imagine the easiest to implement method is a jquery thing...but which and why, or why not and what instead,

**Comment by torvista** [comment]
@Zen4All, where do you have that implemented?

**Comment by Zen4All** [comment]
I have it implemented in a custom mode. I'll post a link as soon as I am home later tonight

**Comment by Zen4All** [comment]
@torvista see my [CITTINS](https://github.com/Zen4All-nl/Collect-Info-Through-Tabs-In-New-Style-for-Zen-Cart) module, and the [zen4all_category-products_listing.php](https://github.com/Zen4All-nl/Collect-Info-Through-Tabs-In-New-Style-for-Zen-Cart/blob/master/Installation_files/YOUR_ADMIN/zen4all_categories_product_listing.php) file

**Comment by torvista** [comment]
Why don't you PR these improvements?

**Comment by Zen4All** [comment]
Because it is not ready, the sorting is, but the rest is not.

**Comment by torvista** [comment]
There seems a lot of code in there for each column. Would it not be much cleaner  and easier to maintain with a jquery plugin?

**Comment by Zen4All** [comment]
@torvista  it is very possible that the code can be reduced. I am a wannabe coder, and my primary goal is almost always to get something working first, and after that I try to reduce/streamline the process

**Comment by torvista** [comment]
There are so many jQuery plugins for this, can someone make a suggestion based on experience?

**Comment by torvista** [comment]
I've used this for years. I've just had another look and see no reason to change, it's still active:
jQuery: https://github.com/Mottie/tablesorter

If anyone has a stronger preference, fine, I would just like something to be available to use in the admin globally.

**Comment by scottcwilson** [comment]
If required, please open a new thread in Discussions to cover this topic.  This is not an issue as such.

**Comment by torvista** [comment]
DIscussion: https://github.com/zencart/zencart/discussions/5781
