### ISSUE TITLE
Admin: include Backupmysql in core

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3050]
Is there a reason why this is not included in the core/ a PR would be considered?

**Comment by barco57** [comment]
I think one of the problems with it in the core is that in certain server environments the backupmysql module doesn't work. Where exec() is turned off, which the module relies on, it throws an error
`ERROR: Your server's "exec()" command has been disabled. This script cannot run. Ask your host if they are willing to re-enable PHP exec(). `
I would think that before inclusion in the core a method to do a database backup that doesn't require exec() would need to be implemented so as to not include code that may or may not work depending on the server environment. 

I do note that on a server where the ZC backupmysql module doesn't work a Wordpress install with the UpdraftPlus plugin does create DB backups with no issues. So there is a way to do it without exec()

**Comment by drbyte** [comment]
There are of course 3rd party db-dump tools written in PHP and other languages, as barco57 mentioned.

The desire by the ZC core team is to not have to maintain specialized code for manually dumping (or restoring) db contents using PHP logic.
The plugin uses the mysqldump binary ... which leaves all the complexity of MySQL database exporting in the hands of MySQL's own supplied code. Not only is the mysqldump process WAY MORE speedy than a PHP-backup script, it's also certain to be maintained by the MySQL authors.

Having the db-backup script usable as a plugin allows people to use it if their server can handle the basic requirements of calling the mysqldump binary on the server, using PHP's `exec()` command. It's a fairly simple requirement -- granted, some PCI purists deny the use of that function, so its availability is questionable on various shared-hosting providers; although it's usually freely accessible on a VPS; that said, most managed-VPS providers provide a backup-scheduler service that trumps the need for the plugin altogether making it moot. And, those same PCI-conscious providers that deny the `exec()` function often also provide a backup feature as well (whether it can be scheduled, or self-managed is another issue).

**Comment by torvista** [comment]
Interesting comments.
I find it an essential developer tool rather than an admin utility, for 
a) rapidly getting a snapshot of the production database for import into a development environment, without leaving either Admin.
b) easily repeatedly restoring / resetting a development db to a known baseline when testing things that manipulate the database,

One might say that that is a minority use case, or could argue that a tool to facilitate/encourage users to always develop/test/add mods well away from their production site is a good thing.

So, back to my original question, (based on an ongoing attempt to stuff into core the essential mods I have to merge every time on an update)...plugin or PR?

**Comment by drbyte** [comment]
I don't think it's core material for now.

You can submit updates to the plugin if you wish. Granted, there are a couple plugins out there for it now. Doesn't one of them do PHP-based scripting if the server binary can't be called?  I feel like the plugin is an adequate tradeoff for requirements.

**Comment by torvista** [comment]
>You can submit updates to the plugin if you wish.

Done.
https://github.com/torvista/Zen_Cart-Backup_MYSQL_Plugin
