### ISSUE TITLE
catalog functions_prices: zen_get_products_display_price uses classes instead of id

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3054]
There are a great deal of spans being created/inserted like
`$show_normal_price = '<span class="normalprice">' . $currencies->display_price($display_normal_price, zen_get_tax_rate($product_check->fields['products_tax_class_id'])) . ' </span>';`

They appear to be all unique, and my feeling is these should all be id, not class....especially if they may be required to be manipulated by other mod's javascript.
Opinions?

**Comment by zcadditions** [comment]
id's will throw errors on listing pages

**Comment by torvista** [comment]
Aha! I am browser-based, I can only think of one page at a time.
