### ISSUE TITLE
Layout Boxes Controller

### ISSUE THREAD

**Issue by judygunderson** [zencart/zencart#3059]
I think it would be easier for Admins if most all of the boxes were turned OFF under Left/Right and single column.  In all these years of building sites, I have very seldom seen people use most all the boxes as they are presented now and it would be a time saver to not have to go line by line and turn off boxes.  It would be less time consuming to turn them ON. if you want them

I would say keeping the categories box, search box, search box header, shopping cart, information and ez pages should be plenty of boxes (which in my experience are most used) to display at the outset.

Thoughts??

**Comment by wiztechinc** [comment]
My sql turns off most of those boxes when i install a new template cause. So I get what you are saying but then deciding which ones is truly more site specific than general. I actually don't use the information box - perferring ez pages links in other places.  So the list of necessary ones may vary widely among us. There's definitely some I think are not useful and would never turn on such as the whos online one. I also never use the shopping sidebox as I use cart in the header mod.  So in reality I'm comfortable with turning them all off and starting over using a script or a template change.

**Comment by judygunderson** [comment]
I like how the bootstrap template does it – everything off and set to zero, which is what made me think of this. 

Judy Gunderson

**Comment by drbyte** [comment]
> I like how the bootstrap template does it – everything off and set to zero, which is what made me think of this.

That's how every template does it by default: everything off and set to zero.

To get the template_default opinionated settings enabled for easy demo on new installs for new users, you need to click the "reset" button, which then copies over those defaults.

**Comment by wiztechinc** [comment]
The text says it resets the sort order. Not that it can restore the boxes from the previous template after changing the template. I did think that you could keep them but I thought it was more automatic at some point. Like it simply kept the boxes when changing the template. Been wondering if my memory was faulty. Any deviance from just the resetting sort order then requires text changes there. Correct?

**Comment by drbyte** [comment]
The text could be clearer. It resets to the defaults set in the db (for which there is no admin control, which which you could update with phpMyAdmin or an sql script).
There are 3rd party mods that do things like clone settings from a different template, etc. 
Some template authors have completely ripped the page apart to do things which ultimately make compatibility with other templates impossible.

**Comment by torvista** [comment]
How about two buttons to switch them all off or on?

**Comment by wiztechinc** [comment]
I can certainly fix the text. I said years ago to rely on me for instructions (also noticed outdated tutorials today). Writer first, artist second, developer (money generator) third. So it literally just restores the last active template boxes? The idea of a button would be appealing to some but I can see disaster looming as a newbie/site owner screws it up. So instructions would be VERY important.

**Comment by wiztechinc** [comment]
one other bit that irritates - an number of the boxes have single turned on as a default when there's no single. Since it doesn't affect anything, it's not a big deal but I don't see any reason why the single box is checked as default.

**Comment by wiztechinc** [comment]
Ah just yuk. Now I'm confused. and may confusing everyone else as well. 1.5.7 does not turn off the boxes if you change the template and does just reset the box sort order. So maybe ignore my comments on that part. Default singles still a thing.
