### ISSUE TITLE
Using declare(strict_types)

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3060]
When revising a file for a PR, I assume that it is now preferable to add/use the strict types declaration:
declare(strict_types=1);

**Comment by drbyte** [comment]
No.

Zen Cart still supports some PHP versions lower than 7.0 where `strict_types` was added (since it relates to scalars which were added then).
Adding an unsupported declaration will trigger warnings that cannot be suppressed, and flood the error-logging system.

**Comment by torvista** [comment]
So, it affects more than just that one file where is it declared?
