### ISSUE TITLE
Bug/php notice: messagestack undefined index

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3061]
ZC157 as of today php 7.3.14 (local)
On every admin pageload:

> 
> [12-Feb-2020 11:22:04 Europe/Madrid] Request URI: /zencart-157/admin1/, IP address: 127.0.0.1
> #1  require(..blah..\public_html\zencart-157\includes\autoload_func.php) called at [..blah..\public_html\zencart-157\admin1\includes\application_top.php:36]
> #2  require(..blah..\public_html\zencart-157\admin1\includes\application_top.php) called at [..blah..\public_html\zencart-157\admin1\home.php:10]
> #3  require(..blah..\public_html\zencart-157\admin1\home.php) called at [..blah..\public_html\zencart-157\admin1\index.php:11]
> --> PHP Notice: Undefined index: messageStack in ..blah..\public_html\zencart-157\includes\autoload_func.php on line 47.
> 
> [12-Feb-2020 11:22:04 Europe/Madrid] Request URI: /zencart-157/admin1/, IP address: 127.0.0.1
> #1  require(..blah..\public_html\zencart-157\includes\autoload_func.php) called at [..blah..\public_html\zencart-157\admin1\includes\application_top.php:36]
> #2  require(..blah..\public_html\zencart-157\admin1\includes\application_top.php) called at [..blah..\public_html\zencart-157\admin1\home.php:10]
> #3  require(..blah..\public_html\zencart-157\admin1\home.php) called at [..blah..\public_html\zencart-157\admin1\index.php:11]
> --> PHP Notice: Undefined index: messageStack in ..blah..\public_html\zencart-157\includes\autoload_func.php on line 50.

**Comment by lat9** [comment]
Carrying over from the issue posted above, apparently `$current_page` is no longer being set, either:
```
[12-Feb-2020 10:21:12 Europe/Madrid] Request URI: /zencart-157/admin1/index.php?cmd=specials, IP address: 127.0.0.1
#1 require(...\zencart-157\admin1\includes\init_includes\init_display_logs.php) called at [...\zencart-157\includes\autoload_func.php:27]
#2 require(...\zencart-157\includes\autoload_func.php) called at [...\zencart-157\admin1\includes\application_top.php:36]
#3 require(...\zencart-157\admin1\includes\application_top.php) called at [...\zencart-157\admin1\specials.php:9]
#4 require(...\zencart-157\admin1\specials.php) called at [...\zencart-157\admin1\index.php:11]
--> PHP Notice: Undefined variable: current_page in ...\zencart-157\admin1\includes\init_includes\init_display_logs.php on line 59.
```

**Comment by scottcwilson** [comment]
Just fixed last night.  See #3072

**Comment by scottcwilson** [comment]
Issue reported by @lat9 - I fixed a bunch of issues with specials in #3071 - I think this issue might be fixed as well.  Will be easy to retest once these two PRs are merged in.

**Comment by lat9** [comment]
FWIW, I just picked up the most recent zc157 file-set and have found that `$current_page` is no longer set _anywhere_ within the admin!  Noting that for prior versions of Zen Cart, that variable is set within the admin's `init_languages.php` processing.

**Comment by scottcwilson** [comment]
Cindy this file: `admin1\includes\init_includes\init_display_logs.php ` doesn't exist in an up to date unchanged copy of 1.5.7.

**Comment by lat9** [comment]
Right, it's part of the [Display Logs](https://vinosdefrutastropicales.com/index.php?main_page=product_info&cPath=2_3&products_id=21) plugin, which has worked successfully on Zen Cart versions since v1.5.0.

Many of my plugins check to see which 'page' it's on via `$current_page` and the lack of that variable in zc157 will cause those to break.

**Comment by scottcwilson** [comment]
OK but can you please open a separate issue for that, since it's not related to the messageStack issue?
