### ISSUE TITLE
zc157 admin: Missing $current_page variable

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#3073]
Splitting from #3061:

Apparently the `$current_page` is no longer being set:
```
[12-Feb-2020 10:21:12 Europe/Madrid] Request URI: /zencart-157/admin1/index.php?cmd=specials, IP address: 127.0.0.1
#1 require(...\zencart-157\admin1\includes\init_includes\init_display_logs.php) called at [...\zencart-157\includes\autoload_func.php:27]
#2 require(...\zencart-157\includes\autoload_func.php) called at [...\zencart-157\admin1\includes\application_top.php:36]
#3 require(...\zencart-157\admin1\includes\application_top.php) called at [...\zencart-157\admin1\specials.php:9]
#4 require(...\zencart-157\admin1\specials.php) called at [...\zencart-157\admin1\index.php:11]
--> PHP Notice: Undefined variable: current_page in ...\zencart-157\admin1\includes\init_includes\init_display_logs.php on line 59.
```

FWIW, I just picked up the most recent zc157 file-set and have found that `$current_page` is no longer set _anywhere_ within the admin!  Noting that for prior versions of Zen Cart, that variable is set within the admin's `init_languages.php` processing.

Noting that the file referenced in that log is part of the [Display Logs](https://vinosdefrutastropicales.com/index.php?main_page=product_info&cPath=2_3&products_id=21) plugin, which has worked successfully on Zen Cart versions since v1.5.0.

Many of my plugins check to see which 'page' is active via `$current_page` and the lack of that variable in zc157 will cause those to break.

**Comment by scottcwilson** [comment]
Looks like it was removed in this commit:

commit ed185a59fa81d18da3fe414c4a7eee62cb69666e
Author: zcwilt <ian@zen-cart.com>
Date:   Fri Aug 23 13:19:54 2019 +0100

@zcwilt Can you comment?

**Comment by zcwilt** [comment]
Hmm. not sure why I removed it. will fix
