### ISSUE TITLE
ZC156 PHP Notice: Undefined index: paypal_ec_token  in /includes/modules/payment/paypal/paypal_curl.php on line 664.

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3074]
Caused as part of a paypal express payment.
Without going into the world of debugging Paypal Express, this is the code:
```
    if ($token == '') $token = $_SESSION['paypal_ec_token'];
    if ($token == '') $token = time();
```
I infer that it is possible/not an error if $_SESSION['paypal_ec_token'] is empty/not set, since it is checked on the next line. So I assume a suitable change would be:
```
$token = !empty($_SESSION['paypal_ec_token']) ? $_SESSION['paypal_ec_token'] : time();
```

**Comment by drbyte** [comment]
Yes that change would be fine in terms of PHP logic.

But, as you mention, there's uncertainty about whether the token should be empty in the first place. 

You didn't say what part/stage of Express Checkout was happening when this Notice occurred. Was it SetExpressCheckout, GetExpressCheckout, or DoExpressCheckout?
Or was it not actually for an Express transaction, but rather for a DirectPayment with credit card?

**Comment by torvista** [comment]
The full log, just realised it was a refund.

[17-Feb-2020 11:19:05 Europe/Madrid] Request URI: /ADMIN/orders.php?status=2&page=1&oID=20200142&action=doRefund, IP address: 185.202.162.225
#1  paypal_curl->log() called at [/CATALOG/includes/modules/payment/paypal/paypal_curl.php:609]
#2  paypal_curl->_logTransaction() called at [/CATALOG/includes/modules/payment/paypal/paypal_curl.php:473]
#3  paypal_curl->_request() called at [/CATALOG/includes/modules/payment/paypal/paypal_curl.php:268]
#4  paypal_curl->RefundTransaction() called at [/CATALOG/includes/modules/payment/paypalwpp.php:1081]
#5  paypalwpp->_doRefund() called at [/../ADMIN/orders.php:279]
--> PHP Notice: Undefined index: paypal_ec_token in /CATALOG/includes/modules/payment/paypal/paypal_curl.php on line 664.

[17-Feb-2020 11:19:05 Europe/Madrid] Request URI: /ADMIN/orders.php?status=2&page=1&oID=20200142&action=doRefund, IP address: 185.202.162.225
#1  paypal_curl->log() called at [/CATALOG/includes/modules/payment/paypal/paypal_curl.php:614]
#2  paypal_curl->_logTransaction() called at [/CATALOG/includes/modules/payment/paypal/paypal_curl.php:473]
#3  paypal_curl->_request() called at [/CATALOG/includes/modules/payment/paypal/paypal_curl.php:268]
#4  paypal_curl->RefundTransaction() called at [/CATALOG/includes/modules/payment/paypalwpp.php:1081]
#5  paypalwpp->_doRefund() called at [/.../ADMIN/orders.php:279]
--> PHP Notice: Undefined index: paypal_ec_token in /CATALOG/includes/modules/payment/paypal/paypal_curl.php on line 664.

**Comment by torvista** [comment]
PR as suggested?
