### ISSUE TITLE
ZC156 Paypal debug log, PHP Notice: Undefined index: zone_id in /includes/modules/payment/paypalwpp.php

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3076]
Code line 2466 on ZC157 file
`$this->zcLog('findMatchingAddressBookEntry - 1-stats', 'lookups:' . "\n" . print_r(array_merge($country->fields, array('zone_country_id' => $country_zone_check->fields['zone_id']), $logMsg), true) . "\n" . 'check_zone: ' . $check_zone . "\n" . 'zone:' . $zone_id . "\nSubmittedAddress:".print_r($address_question_arr, TRUE));`

I think an isset is enough as that field may not have a result:

` $this->zcLog('findMatchingAddressBookEntry - 1-stats', 'lookups:' . "\n" . print_r(array_merge($country->fields, array('zone_country_id' => isset($country_zone_check->fields['zone_id']) ? $country_zone_check->fields['zone_id'] : ''), $logMsg), true) . "\n" . 'check_zone: ' . $check_zone . "\n" . 'zone:' . $zone_id . "\nSubmittedAddress:".print_r($address_question_arr, TRUE));`

**Comment by mc12345678** [comment]
Shouldn't the `zone_country_id` be given more of a numeric value or null or something when there isn't an associated value to assign?
