### ISSUE TITLE
variable $rows mishandled in admin reports

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3078]
If you look at the stats_*.php files in admin, the $rows variable gets set and reset with no references in between.  See: stats_customers.php line 53 and 71, stats_products_lowstock.php lines 61 and 62, stats_products_viewed.php line 61 and 62, 

Low priority code cleanup feature that would be good for a beginner.

**Comment by ScotteSolutionsLtd** [comment]
Thanks - I added a pull request...the checks are still running but I hope it helps.
https://github.com/zencart/zencart/pull/3080
