### ISSUE TITLE
Admin language selection dropdown

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3081]
Any reason why this can't be displayed on all admin pages?
Or, why is it disabled on some pages?

**Comment by Zen4All** [comment]
By my knowledge, the drop down disappears when you are doing an action (like editing contents) on a page.

**Comment by torvista** [comment]
I have had it enabled by default for so long I don't remember why I did it.
As far as I have just seen, it **does** seem to only be hidden on updating a field, so I'll go back to vanilla and see what problem I had originally.

**Comment by torvista** [comment]
As I was saying, to expand on that, 
currently the language selector is hidden when there is an action, and if there is an action, that parameter is not included with the language link.

While I've had to change both those aspects to allow a language change on the order Edit page for our specific reason...is there some situation where this is a problem/could the language selector not be shown on all pages irrespection of an action?

(Also BISN, to send notifications in both languages requires the admin to manually change the language to perform the email sends for each language).)
