### ISSUE TITLE
preview_info bug : closing parenthesis

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#3096]
https://github.com/zencart/zencart/blob/50020d417efe52eb756046ee4843e9f18de36caf/admin/includes/modules/product/preview_info.php#L83
This line contains an extra closing bracket. This should be removed, or there should be an extra opening bracket.
@mc12345678, I believe this is your code, can you provide the solution? and also check tho other preview files?

**Comment by torvista** [comment]
This is done in a pending PR that I'll complete shortly.
https://github.com/zencart/zencart/pull/3064#issuecomment-594195480

**Comment by mc12345678** [comment]
And that is why I hadn't modified it following torvista's identification of the issue. Thank you both for identifying that issue and apologies for the bug.

**Comment by Zen4All** [comment]
Thanks guys.
 I'll close this issue when the pr is done

**Comment by torvista** [comment]
this can be closed now.
