### ISSUE TITLE
Unable to Use "Delete Matching Attribute from ALL Products"

### ISSUE THREAD

**Issue by Pan2020** [zencart/zencart#3097]
I tried to delete certain option value from ALL products.

Zen Cart does have the option in "Option Value Manager" with the box called "Delete Matching Attribute from ALL Products where Option Name and Value ..."
**However, when I tried to use it... it did NOT do anything!**

I recorded video to show the bug in-action.
https://youtu.be/DHbOsSP2v1M

**Comment by drbyte** [comment]
@torvista @scottcwilson Have you replicated this?

**Comment by scottcwilson** [comment]
Admin > Catalog > Option Name Manager 
Went to Delete all Option Values from ALL products using this Option Name
Select Memory, Delete
Verify attribute is not on product 2

Looks ok to me in 1.5.7.

**Comment by scottcwilson** [comment]
<img width="1418" alt="Screen Shot 2020-05-19 at 2 21 26 PM" src="https://user-images.githubusercontent.com/4391638/82363651-1efd6800-99dc-11ea-8386-0ed5adefdaba.png">

**Comment by scottcwilson** [comment]
Suggest closing.
