### ISSUE TITLE
Help tips for admin

### ISSUE THREAD

**Issue by wiztechinc** [zencart/zencart#3098]
Bear with me here as I am a writer and can get wordy.

As many applications and software have help tips, the Zen Cart admin would benefit from such a system. I already have a fair amount of the text necessary for these tips. Such as this one below - which actually highlights what appears to be the different terminology on the clients facing pages versus the text in admin. 

The Expected Sort Field under Configuration in My Store: The website shows upcoming products - with, yes, the expected date to the side in smaller type. The average person looking at admin only sees the expected date text without any mention of upcoming products. The help text then would refer to this - and I was short and sweet here - "as expected = upcoming". Simply hints to further educate the user. 

I don't know if any of you have ever counted how many admin settings there are or if you've ever seen/heard the reaction of a newbie in admin. One, right now on my website (which means this is not accurate as it hasn't been updated since I did this in 2012) I have 539 settings. 

Two, newbies in admin are completely overwhelmed by the array of choices because there is just so much. Anything to assist someone to learn about zen cart should be front and center. It is a free program that anyone can install from most cpanels. That doesn't take any knowledge of anything in reality except how to login to an admin interface and start playing. That's really how I personally ended in Zen Cart .

Tool tips can be just little hover overs that pop up when you hit the ? mark. The text could pulled from a text / html file. I'm absolutely not the expert on how this can be integrated into the present admin but have created this inside another little CMS years ago.  (And this is truly old)
![image](https://user-images.githubusercontent.com/5367263/75908183-a5f86680-5e17-11ea-90d5-53cf409181f6.png)

**Comment by torvista** [comment]
If there are options that are not self-explanatory or not explained clearly, those should be fixed for the reasons you have detailed, so let's fix them.

I am currently working on improving half a dozen admin names and descriptions. This needs to be done both in the install and upgrade sql, and is not a trivial thing, in fact it is a real pain.

To spare you that pain and help you get all that useful info from your site/head into the code, I would suggest you make a spreadsheet with the constant name, old text, new text and optional tool tip for all the improvements you wish, and let someone else build the sql from it later.

To helpfully see the name of the constant in each infobox, this needs to be set
ADMIN_CONFIGURATION_KEY_ON  to 1
but I don't know how to get at it apart from opening a configuration page then substituting the page config number to 6:
gID=6

then you'll see the option in the list.

**Comment by scottcwilson** [comment]
Delia, this is on my someday maybe list.  See 
https://www.zen-cart.com/showthread.php?226020-Operator-s-Manual-in-Admin

**Comment by wiztechinc** [comment]
Torvista - it's all in a database now so that's a easy one. Be glad to help you in your process as much as I can. I was just starting to update everything I have based on the more recent versions which means I have a lot of work in front of me to do only that.

Scott - yes but admin notes? I tried those once and really didn't like it but that was long ago.  I really wasn't thinking that complicated.  I'll look at the mod again.

**Comment by torvista** [comment]
I note that in the Developers toolkit, you can list all the configuration constants in a table. This could be cut and pasted into a spreadsheet as a base adding modifications.

**Comment by wiztechinc** [comment]
Thanks for that tip. It might save me time in updating what I have now. Too bad there's not an export on that but you are right, copying and pasting works to some degree. File needs too much clean up to use but becomes a good guide. Unless you've got a better idea? The problem is that breaks in the description create a new row - sometimes then creating 4 rows where there should be one. That same query though would be ideal. What I exported is close to usable - needing to do a find and replace to put the names of the sections in versus the numbers.

**Comment by torvista** [comment]
you could export direct from phpmyadmin...

**Comment by wiztechinc** [comment]
That's what I did immediately. Thus the find and replace to create names instead of numbers.

**Comment by drbyte** [comment]
So there's lots of talk here of extracting current "configuration settings descriptions". I guess that's a separate phase from "help tips"?

**Comment by wiztechinc** [comment]
That is only for getting a list of the configurations setting in order to attach the correct text to each one. My present list in my database is out of date.

**Comment by torvista** [comment]
How about
a) A review over the option titles to see if any are really unintuitive/require modification.
b) Expanding the option description as much as necessary/incorporating the info from Delias site.
c) Make this description the tool tip.

**Comment by wiztechinc** [comment]
my tool tips do go further than that. I'll have to look to see exactly what I got where. For example: configuration >My Store >Switch to Default Language Currency, the extra text is "This would only pertain to a multi-language cart if you are showing a language change sidebox. Since languages are not tied to a specific currency most of the time, it would be rare to change this setting." (Since I haven't checked this out in years, I may well be wrong on some of it so don't hit me!)

**Comment by wiztechinc** [comment]
> How about
> a) A review over the option titles to see if any are really unintuitive/require modification.
> b) Expanding the option description as much as necessary/incorporating the info from Delias site.
> c) Make this description the tool tip.

After ignoring your suggestion and struggling with it all for a few days, I admit this is the best way forward.  This is complicated!  Back to the spreadsheet issue though.  I got 3 and was hoping to merge bits and pieces but the differences between the default database output via phpmyadmin, the cut and paste from the developer's tool and my database output, the differences are too stark. Best to get a query that outputs something similar to the developer's tool. I opened the file and just didn't feel like fighting through it. Can anyone tell me where that query is or nudge me to writing the query? If I have time I'll give it a go.

**Comment by torvista** [comment]
> and my database output
what exactly do you mean by this? A modified ZC admin?

**Comment by wiztechinc** [comment]
> > and my database output
> > what exactly do you mean by this? A modified ZC admin?

The database of listings from allthingszencart.com. Every configuration/entry in zencart is there now but it's outdated. So it has nearly all the info as well as the extra text. I am just trying to update the list first to get all present configuration settings. I'm probably going to have to start over with my database but getting it all into any semblance of a usable spreadsheet is messy. Of course it's all there in the developer's tool but it does not copy well into a spreadsheet. So I need an alternative to your suggestion about using that. I'm spinning my wheels at this point trying to get something I can work with.

**Comment by torvista** [comment]
try that, got to rush
https://www.dropbox.com/s/apb160ysefbxq65/admin%20constants%20SQL.ods?dl=1

**Comment by wiztechinc** [comment]
my humble and sincere thanks!

**Comment by torvista** [comment]
this may be of use in other circumstances
https://github.com/torvista/zen-cart_list-configuration-constants

**Comment by wiztechinc** [comment]
ah tools!  Thanks again. Got a ways to go before I'm truly helpful here.

**Comment by torvista** [comment]
If your data has the constant names along with the text data/explanation, it won't be too difficult to merge/reference with vlookup in a spreadsheet.

**Comment by wiztechinc** [comment]
got it going now. So now I have questions. Not appropriate to delve into these details in this type of thread but now seeing I made some assumptions years ago and now realize they may not be correct or not fully understand new settings. First one I looked up was a DrByte explanation from 2008. Maybe still valid but I have no way to know for sure. So this really isn't something I can fully do by myself without someone else's detailed knowledge. I guess I can just leave a question mark where appropriate for later? Would prefer to be sure on each entry as I work. That's just my OCD interfering. I now have an excel spreadsheet with the extra text dumped in (not then fully correct for each line since I was missing settings). I can send to anyone who wants to take a peek.

**Comment by torvista** [comment]
just add a comments column for doubts/questions and make it shareable somewhere for others to read and edit.

**Comment by wiztechinc** [comment]
okay, I will do that once I get far enough along. I don't want to have to work it while online.

**Comment by scottcwilson** [comment]
The list of current configuration description strings is here: 
https://docs.zen-cart.com/user/admin_pages/configuration/all/

**Comment by wiztechinc** [comment]
nice!  So we could possibly use this as a way to insert help tips in admin? I'll compare to what I have.

**Comment by drbyte** [comment]
> So we could possibly use this as a way to insert help tips in admin?

Well, at the very least you could PR sub-text to those descriptions to add additional explanation, so that end-users using that site as a documentation resource would see those additional explanations, whether or not any popover-help-tips are ever implemented.

**Comment by scottcwilson** [comment]
> nice! So we could possibly use this as a way to insert help tips in admin? 

Not sure exactly how to answer this.  It's a report that pulls data out of the configuration fields.  So it wouldn't help you insert.  And it creates a set of markdown files, so it's not something you'd want to add to your admin.

**Comment by wiztechinc** [comment]
> Not sure exactly how to answer this. It's a report that pulls data out of the configuration fields. So it wouldn't help you insert. And it creates a set of markdown files, so it's not something you'd want to add to your admin.

Report? So you do the report to create these files? But then they are online and can be referenced? I'm all about not duplicating efforts and combining data. I frequently will generate some sort of report and edit it to make it more usable. Since those are editable files, I would assume it's possible to add info there. But then I don't know how you do that. Just generate a one time report? Keep a connection between a database and the new files so that when data changes, it automatically changes what you have online? I actually don't know what markdown files are obviously. I'm quite impressed with the new docs - so much better than the wiki and I had no clue they existed.

**Comment by drbyte** [comment]
Implemented in 1.5.7
