### ISSUE TITLE
configuration table datetime fields default

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3099]
> CREATE TABLE configuration (
>   configuration_id int(11) NOT NULL auto_increment,
>   configuration_title text NOT NULL,
>   configuration_key varchar(180) NOT NULL default '',
>   configuration_value text NOT NULL,
>   configuration_description text NOT NULL,
>   configuration_group_id int(11) NOT NULL default '0',
>   sort_order int(5) default NULL,
>   last_modified datetime default NULL,
>   date_added datetime NOT NULL default '0001-01-01 00:00:00',

If last_modified and date_added were default as current timestamp, there would be no need to include them in a query. Any reason for not doing so?

**Comment by scottcwilson** [comment]
These tables were designed before that was an option.

**Comment by ScotteSolutionsLtd** [comment]
For mysql >= 5.6.5 this type of usage is allowed:
```
  last_modified datetime default ON UPDATE CURRENT_TIMESTAMP,
  date_added datetime NOT NULL default CURRENT_TIMESTAMP,
```

**Comment by scottcwilson** [comment]
@ScotteSolutionsLtd - true, but like I said, these tables were designed many moons ago, before MySQL5.6 was even a twinkle in someone's eye. :)

**Comment by drbyte** [comment]
At some point when we force MySQL 5.6 as the minimum we could make the change. But there's no pressing need for that.
