### ISSUE TITLE
Suggestion: Page-specific templates should use code similar to code the sideboxes use to auto-generate the CSS IDs and classes

### ISSUE THREAD

**Issue by DivaVocals** [zencart/zencart#310]
Starting over from #304 which is now WAY off-topic and long in the tooth..

Typically when I build a Zen Cart template there's a LOT of overrides I find that I need to include with my template to "fix" (address) what are either missing IDs and classes within the default template or to add a level of consistency to classes and IDs that IMHO is missing in the current default template. Perhaps now is the time to start to examine the entire default template.

One one of my "pet peeves" as it were with the current default template.. :smile:  If you look at looking at the actual template PHP files you will see that there is an inconsistency and vagueness with regards to the classes and IDs. Compare thsi to the  If you look at looking at the actual template and sidebox PHP files, and you will see that this is managed very differently.  I would like to see the template page classes and IDs named with a LOT more consistency. The method used for naming sideboxes classes and IDs should be applied to the page specific classes and IDs as well.

The way this is managed with sideboxes is BRILLIANT and unambiguous.The generic class names are clear and unambiguous (rightBoxContainer, rightBoxHeading, sideboxContent) and as long as I know the sidebox name, I KNOW what the IDs for headings, container, and content are going to be.. Would like to see the page templates managed the same way..

Quotes from @drbyte  from the original issue #304
>I agree with @DivaVocals that standardizing of the naming of IDs and classes is necessary. The consistency that's currently present is not dynamically generated, thus leading to the perception of inconsistency.

>As to the repeated comment about HTML5, as @bislewl pointed out, @zcwilt already noted that HTML5 and mobile-friendly are some of the primary features in the upcoming release.

>I believe @DivaVocals was wanting the page-specific templates to use something like the following code which the sideboxes use to auto-generate the IDs applied to sideboxes

	
	<div class="leftBoxContainer" id="<?php echo str_replace('_', '-', $box_id ); ?>" style="width: <?php echo $column_width; ?>">
	<h3 class="leftBoxHeading" id="<?php echo str_replace('_', '-', $box_id) . 'Heading'; ?>"><?php echo $title; ?></h3>
	<?php echo $content; ?>
	</div>
	

>and also currently used on the <body> tag in all pages:

	<?php  $body_id = ($this_is_home_page) ? 'indexHome' : str_replace('_', '', $_GET['main_page']);?>
	<body id="<?php echo $body_id . 'Body'; ?>">

>While PHP code suggestions are welcome, I think this discussion is still at a stage that's too early to turn into code yet. The code snippet I posted was simply to set context and explain what @DivaVocals was referring to, since everybody else was missing the point.

Last point: 
I'd also like to suggest that some of the old generic classes used in the default template files be renamed so that they tell you exactly what they do.. The old "back" and "forward" class names are terribly vague.. and while many of us are "used to" them now, that doesn't mean that they should not be modified to be a lot clearer.. I know that there was a valid reason for "back" and "forward", but it's ambiguous, and whatever meaning those names used to have that reasoning is certainly passe now. Why not replace "back" and "forward" with "floatRight" and "floatLeft" and eliminate the ambiguity with these generic classes. Why use the very generic "content" class when (based on how this class is pretty consistently used) "centerColumnContent" is a lot more descriptive.

**Comment by wiztechinc** [comment]
I want to reaffirm what Crystal is saying. No matter the template, we need
to be using ids and classes that designate what item actually is and using
descriptive classes in addition. I always use the old defaults and it's not
an issue but after all these years I still have to pause and think if
forward is left or right. The more obvious the better.
ᐧ

Delia Wilson Lunsford
WizTech, Inc., (formerly Delia Wilson Design, LLC.)
434-202-4307
Terms and Conditions for working with WizTech, Inc.
(http://www.teamwiztech.com/terms-conditions.php)

**Comment by IronLady** [comment]
Since we will use Foundation as the framework. 
Maybe it'll look like this

Zen Cart | Foundation
------------ | -------------
.back | .left
.forward | .right
.clearBoth | .clearfix
.centeredContent | .text-center

**Comment by DivaVocals** [comment]
I don't think that ANY decision regarding the use of Foundation or Bootstrap has been definitively established.. Since WordPress was brought up as an example in the #304 issue, WordPress' core and **default themes** do not include Bootstrap or Foundation. It would appear that the WordPress devs left the decision of using Bootstrap or Foundation in the hands of siteowners to be implemented via plugins or themes.. I would HOPE that the Zen Cart dev follow this same convention.. The decision to use Bootstrap or Foundation should not be taken out of the hands of site owners..

**Comment by DivaVocals** [comment]
Also while another separate issue was created to discuss classes and IDs #312, I do think that that issue is totally on point with this discussion..

**Comment by IronLady** [comment]
> I don't think that ANY decision regarding the use of Foundation or Bootstrap as a framework for catalog templates has been definitively established.

I am sure that I read it here somewhere that catalog side will use foundation. This need a clarification. 

I am completely agree with you. We shouldn't use any css framework on default theme. But, it's okay if we use it on new classic theme :)

**Comment by DivaVocals** [comment]
I will have to disagree here.. I don't think that the default template or the bundled Classic template should adopt any framework.. The Classic template should be a starting point, which is why I am advocating replacing it's current incarnation with Barebones..

**Comment by DivaVocals** [comment]
Had some caffine, some calories, and then re-read some of my earlier missives.. I was thinking as I was eating of the template I am currently building on where I am using Bootstrap and Awesome Fonts. In this template, I have Bootstrap and Awesome Fonts configured as admin configurable items that I can turn on or off.

@IronLady was thinking that the inclusion of Bootstrap or Foundation could indeed be a part of the default template if managed in a similar manner.. 

WHAT IF it's done in a way that's similar to the way jQuery is now part of core code. (a CDN with a fallback to a physical file if present) If it can be done in a manner that gives shopowners/site developers a CHOICE about whether or not to include a framework, and gives themm a CHOICE as to which framework they want to use, AND prevents someone from doing something silly like including BOTH frameworks, I think this might be doable.. 

Thoughts??

**Comment by barco57** [comment]
Well, here goes, my first comment on github, let's see if I can figure out Markdown

@DivaVocals 
>I don't think that ANY decision regarding the use of Foundation or Bootstrap as a framework for catalog-side templates has been definitively established. Except for the use of Foundation as the framework for the new v1.6 admin templates, I have not yet seen any indication that this definitely will be carried over to the catalog-side templates...

issue #299 starts with
>For the new template in v1.6.0 I'd like to incorporate a lightbox for product images (main image, plus additional images), and maybe even feature/specials images (although that's maybe more of a carousel thing) but I want something that's very mobile-friendly ... such as just start swiping left/right on product images to see more ... maybe without even needing to click the image to "start" the swipe capability.
...
>(Keep in mind the current implementation is based on jQuery 1.11, and is geared around Zurb Foundation as the css/js framework, so suggestions should ideally be based on tools that would work with that combination with minimal extra configuration required. The simpler the better for storeowners and template designers to be able to customize, of course.)

I think that clearly shows that a new template is in the works that uses Zurb Foundation to be implemented on the catalog-side. What hasn't been spoken yet, I believe, is whether or not the new RWD template is going to be included in addition too the classic template or a replacement for the classic template. I suspect they are waiting for the conversation about the template to mature further....

**Comment by DivaVocals** [comment]
@barco57  Thanks for the reference.. but my position on standardizing on one CSS framework is the same.. I think that not giving shopowners and template designers a choice is a mistake.. Why Foundation and not Bootstrap.. WHY make folks choose.. I am of the opinion that the default template for Zen Cart should be framework agnostic.. Again since WordPress was used as an example, the default WordPress themes are framework agnostic.. On the other hand there is quite a buzz in the Joomla forums over the Joomla devs decision to bundle in Bootstrap with the Joomla core.. 

> **Since Joomla doesn’t force Bootstrap (and they shouldn’t)**, then the potential for these issues arising increases. But would forcing Bootstrap help at all? A CMS needs to be flexible, and users should be able to choose from the many frameworks available to find one that works for them; taking away that choice limits Joomla and its users. 

The issue for Joomla users is that apparently there aren't any checks when it comes to third-party extension developers.. This is not dis-similar to what happened with Zen Cart modules and jQuery..

>First of all, third-party extension developers don’t often check whether Bootstrap is already loaded, which that there code will load the library from the JUI too, resulting in Bootstrap being loaded twice which creates a huge amount of CSS conflicts. 

My point here is that framework choices should be left to site owners/site developers.. There has to be a way to modernize the template by offering BOTH of the populare CSS frameworks and give folks a choice in the direction they choose.

**Comment by zcwilt** [comment]
>
My point here is that framework choices should be left to site owners/site developers and there needs to be safeguards so that siteowners and module/template developers can't do silly things.. There has to be a way to modernize the template by offering BOTH of the popular CSS frameworks and give folks a choice in the direction they choose.

I should first say that when it comes to html/css, I'm a noob and while I have been doing a lot of work (especially in admin) regarding foundation, I try and get others to help me with the more complex stuff.

Given that, one thing that springs to mind in terns of how we allow for different frameworks is the opinions those frameworks make.

So foundation and bootstrap both have heavy opinions in terms of the grid they use, it's therefore difficult to write a common template that satisfies both frameworks.

So, we don;t want to write Zen Cart in a way that makes it too opinionated, we want to allow for people to use a foundation/bootstrap/etc themes. I'm struggling to understand how best we do that;

One suggestion, and this is something we have toyed with in the past, is to allow for a more complex parent/child relationship for themes. 

thoughts ?

**Comment by DivaVocals** [comment]
Well there's a couple of theoretical approaches that come to mind..

1. Follow a model similar to how WordPress themes work.. In WordPress a default WordPress installation includes more than one default template and one would then create a child theme based on the parent template they select. In fact for the most part, ANY WordPress theme can become a parent theme. The recommended path is for siteowners to create child themes based on these themes (similar to the the current Zen Cart default template and overrride structure).

This provides sitebuilders with the flexibility to determine how they want to structure their theme.. Add Foundation, Bootstrap, something proprietary, etc..

2. The other option is similar to what I have been doing with recent site builds.. I created a down and dirty plugin which allows me to turn on/off from the admin, Awesome Fonts, Foundation Fonts, Bootstrap, and Foundation. I have it configured so that for each option I turn on, I can choose only ONE font library, and only ONE CSS Framework. The links to the CDNs are added to the html_header.php where they load ahead of the stylesheets and javascript... It's down and dirty, but I think you get the point..

**Comment by drbyte** [comment]
> Follow a model similar to how WordPress themes work.. In WordPress a default WordPress installation includes more than one default template and one would then create a child theme based on the parent template they select. In fact for the most part, ANY WordPress theme can become a parent theme. The recommended path is for siteowners to create child themes based on these themes (similar to the the current Zen Cart default template and overrride structure).

NOTE: A middle-step "shared" template folder has been added in #350 and updated with #377 and #380

**Comment by DivaVocals** [comment]
Right I looked at this and it seems to just add a level between your_template and default_template. I assume the allows two templates to "share" the same modifications saving me the trouble of reapplying common mofifications when changing templates? While this seems similar to my reference to WordPress, this is in fact a little different. In WordPress, any theme I install can be selected as the default theme. You can create a child theme from any installed theme. Each child theme is specific to one parent theme.. the shared folder operates a little differently, but does add some interesting options..
