### ISSUE TITLE
Document General Catalog : various php notices on info page

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3102]
(php 7.3.14, Report All Errors on)

> PHP Notice: Undefined variable: flag_show_product_info_in_cart_qty in ...
\public_html\zencart-157\includes\templates\template_default\templates\tpl_document_general_info_display.php on line 94.

and another four more notices.
I won't be dealing with this.

**Comment by scottcwilson** [comment]
I'd like to consolidate or eliminate the extra product types.  This is extra software to maintain.
