### ISSUE TITLE
admin categories products not showing up...

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#3103]
according to my admin, i am using v1.5.7-alpha.  this is definitely on the v157 branch. 

i am not sure if this is a data issue with my dataset, or something else.  from my admin menu, i would select catalog => categories/products.  this menu selection brings up:

admin/index.php?cmd=categories

and no categories show up.  if i go directly to:

admin/category_product_listing.php

my categories do appear.  

is my menu option incorrect?  and is an action needed for that menu?  or is there a problem with the code (which i can not seem to find)?

**Comment by scottcwilson** [comment]
If you go to admin->Catalog->Categories/Products, the URL you should see is 
/admin/index.php?cmd=category_product_listing

If you are not seeing that you should probably delete and recreate your database.

**Comment by proseLA** [comment]
thanks.
