### ISSUE TITLE
Development Environment - Windows

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3106]
After being encouraged to prise myself off Xampp, I started to investigate...the virtual machine world.
Not much in the current docs:
https://docs.zen-cart.com/dev/

There was Vagrant and Habitat
https://github.com/zencart/habitat
http://zencart.github.io/habitat/technical.html

but maybe now is Docker...devilbox.
https://github.com/zencart/zencart/issues/1732
https://zc-dev-docs.readthedocs.io/en/latest/dockerdev/dockerdev.html
https://readthedocs.org/projects/zc-dev-docs/downloads/pdf/latest/

Finding this stuff scattered about is bewildering for me who only really works with Zen Cart and does not have the time to investigate nor want to learn more than really necessary.
I started documenting the Virtualbox, Vagrant route to encourage others, but I think that was a waste of time after finding these links.

So, is this really the best way forward in 2021?
https://readthedocs.org/projects/zc-dev-docs/downloads/pdf/latest/

(and can out-of-date info/links be retired/have indications that they out-of-fashion or redirected to a single source?)

If the pdf needs some updates on this aspect, just mention them here for the time being, I am still disposed to make a less-formal but more detailed explanation for other non-pro developers like me.

**Comment by Zen4All** [comment]
IMHO the easiest way is to use xammp, or something equal. Very easy to setup,and use.

**Comment by wiztechinc** [comment]
I know you are probably going to think I'm crazy but I do all my work online. You can actually have a gitbhub site in cpanel. But I never use xxamp anymore at all. I do have some really good hosting and plenty of domains to toss things around in.

**Comment by scottcwilson** [comment]
Steve, it would be great to see a writeup on https://docs.zen-cart.com/dev/.  
Instructions on contributing: https://github.com/zencart/documentation

**Comment by torvista** [comment]
I'm looking for some consensus of "we use this and this with this because of this and it's better than that because of this".
Or a discussion with some conclusion. I don't have the time to try various solutions and find out the disadvantages the hard way.

For me the big picture here is to:

a) educate users to develop and manage their site in the most efficient and safe way (virtual machine and git?). They should be using the most efficent tools as much as the professional developer, if not more as their livelihood may depend on it, but it is up the advanced users to facilitate that education/shortcut the learning curve and spoon-feed the setup of the best environment./recommend working practices.

b) facilite the progression of the user to a user/developer. able to communicate and comfortable with contributing.
There are many ZC users, but very few contributors. That has to change and it will not without leveraging the user base.

First a solution, then a writeup.

Hence my question, is the process described in the pdf still considered optimum (not just valid, as all solutions are valid) or not?
https://readthedocs.org/projects/zc-dev-docs/downloads/pdf/latest/

**Comment by scottcwilson** [comment]
I use a Mac.  You Windows people are crazy.  :)

**Comment by torvista** [comment]
Yes, both of us....just don't go there.

**Comment by lat9** [comment]
FWIW, I've got my version of XAMPP set up to use multiple PHP versions and, thanks to @torvista's Zen Cart postings, support Ceon URI Mappings.  I'm not sure what the perceived downside(s) of XAMPP are, but I'm perfectly happy with _my_ setup.

**Comment by torvista** [comment]
Last time I looked (not very well, evidently), multiple php with a single Xampp was not feasible. Evidently not..is your setup based on this?
https://themanish.com/run-multiple-version-of-php-in-xampp-windows-without-installing-multiple-xampp/

The downside for me is the disruption to keep it updated/install a new one for the latest php/mysql. almost every month. In the past my hosting would be months behind these minor updates but now it is almost immediate/it is impossible to be ahead locally.

**Comment by drbyte** [comment]
None of the ZC core team do dev testing on local windows environments. So how you choose to set up your local dev environment is up to you. 

The key components are:
- a code editor that doesn't mangle PHP files (Nowadays PhpStorm or VS Code are good options.)
- a place to "run" the code: an environment that supports PHP+Apache/Nginx+MySQL ... whether that be an external webserver designed for running websites, or Xampp or one of its equivalents, or a virtualized machine/container service like Vagrant/Docker.
- ideally some knowledge of version-control-services like git

The old Habitat virtual machine for Vagrant is no longer maintained by the ZC dev team because we no longer use it, and the Laravel Homestead project on which it was based is equally suitable, so duplication of efforts was pointless.

**Comment by lat9** [comment]
I've got my multi-PHP XAMPP environment set up based on [this](https://stackoverflow.com/questions/45790160/is-there-way-to-use-two-php-versions-in-xampp) stackoverflow posting.

**Comment by torvista** [comment]
ok, thanks for the input.
