### ISSUE TITLE
additions to catalog error_logging format

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3107]
I did some changes to the format that I find helpful:
changing this:

> [08-Mar-2020 13:11:52 Europe/Madrid] Request URI: /tienda/index.php?main_page=checkout_shipping
> IP address: 127.0.0.1
> #1  require(D:\blah_blah\blah_blah\blah_blah\blah_blah\blah_blah\public_html\tienda\includes\modules\pages\checkout_shipping\header_php.php) called at [D:\blah_blah\blah_blah\blah_blah\blah_blah\blah_blah\public_html\tienda\index.php:36]
> --> PHP Notice: Undefined index: id in D:\blah_blah\blah_blah\blah_blah\blah_blah\blah_blah\public_html\tienda\includes\modules\pages\checkout_shipping\header_php.php on line 198.

to this

> [08-Mar-2020 13:36:29 Europe/Madrid]
> Customer: 5857 - Jose Bloggs
> Navigation: [0][checkout_shipping] [1][not set] [2][not set]
> Request URI: /tienda/index.php?main_page=checkout_shipping
> IP address: 127.0.0.1
> #1  require(CATALOG/includes/modules/pages/checkout_shipping/header_php.php) called at [CATALOG/index.php:36]
> --> PHP Notice: Undefined index: id in 
> #1  require(CATALOG/includes/modules/pages/checkout_shipping/header_php.php) called at [CATALOG/index.php:36] on line 198.

This has helped me determine the bizarre steps which steps a customer has taken to trigger a log, and is much easier on the eye.
Also this can be copied and pasted into a bug report without needing to strip out the path.

```
if (!empty($backtrace)) {
        $backtrace = PHP_EOL . rtrim($backtrace);
    }
    //steve removed absolute paths from $backtrace
    $backtrace = str_replace('\\', '/', $backtrace);
    $backtrace = str_replace(DIR_FS_CATALOG, 'CATALOG/', $backtrace);
    $errfile = str_replace('\\', '/', $errfile);
    $errfile = str_replace(DIR_FS_CATALOG, 'CATALOG/', $errfile);
    //steve customer info and navigation
    $extra_info = PHP_EOL;
    if (zen_is_logged_in()){
        $extra_info .= 'Customer: ' . $_SESSION['customer_id'] . ' - ' . $_SESSION['customer_first_name'] . ' ' . $_SESSION['customer_last_name'] . PHP_EOL;
    } else {
        $extra_info .= 'Guest' . PHP_EOL;
    }
    $extra_info .= 'Navigation: ' .
    '[0][' . (!empty($_SESSION['navigation']->path[0]) ? $_SESSION['navigation']->path[0]['page'] : 'not set') . '] ' .
    '[1][' . (!empty($_SESSION['navigation']->path[1]) ? $_SESSION['navigation']->path[1]['page'] : 'not set') . '] ' .
    '[2][' . (!empty($_SESSION['navigation']->path[2]) ? $_SESSION['navigation']->path[2]['page'] : 'not set') . ']' . PHP_EOL;
    //$message = date('[d-M-Y H:i:s e]') . ' Request URI: ' . $_SERVER['REQUEST_URI'] . ', IP address: ' . (isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : 'not set')  . $backtrace;
    $message = date('[d-M-Y H:i:s e]') . $extra_info . "Request URI: " . $_SERVER['REQUEST_URI'] . "\nIP address: " . (isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : 'not set')  . $backtrace;
```

But this is not finished...since the admin side uses this same code, some more work is required to deal with that/substitute /ADMIN in the path etc. and that seems more complicated than warranted...perhaps someone else is interested in pursuing this?

**Comment by scottcwilson** [comment]
My vote would be to skip the refinement of modifying the path in both cases.  Just leave it - it's a good reminder in case there are multiple carts on the same server, and it's an extra processing step you could just eliminate to reduce the chances of error.

**Comment by torvista** [comment]
I settled on this:
//bof steve extra debug info
    //remove absolute paths from $backtrace for readability
    $backtrace = str_replace(['\\', DIR_FS_CATALOG], ['/', 'CATALOG/'], $backtrace);
    $extra_info = PHP_EOL;
    if (IS_ADMIN_FLAG) {
        $extra_info .= 'Admin' . PHP_EOL;
    } else {
        $extra_info .= (zen_is_logged_in() ? 'Customer: ' . $_SESSION['customer_id'] . ' - ' . $_SESSION['customer_first_name'] . ' ' . $_SESSION['customer_last_name'] : 'Guest') . PHP_EOL;
        $extra_info .= 'Navigation: ' .
            '[0][' . (!empty($_SESSION['navigation']->path[0]) ? $_SESSION['navigation']->path[0]['page'] : 'not set') . '] ' .
            '[1][' . (!empty($_SESSION['navigation']->path[1]) ? $_SESSION['navigation']->path[1]['page'] : 'not set') . '] ' .
            '[2][' . (!empty($_SESSION['navigation']->path[2]) ? $_SESSION['navigation']->path[2]['page'] : 'not set') . ']' . PHP_EOL;
    }
  //$message = date('[d-M-Y H:i:s e]') . ' Request URI: ' . $_SERVER['REQUEST_URI'] . ', IP address: ' . (isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : 'not set')  . $backtrace;
    $message = date('[d-M-Y H:i:s e]') . $extra_info . 'Request URI: ' . $_SERVER['REQUEST_URI'] . "\nIP address: " . ($_SERVER['REMOTE_ADDR'] ?? 'not set')  . $backtrace;
//eof
