### ISSUE TITLE
Remove Newsletter feature

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3112]
We have discussed this before - the practice of sending volume email from your hosting account is harmful and not something we should be encouraging.  Is it time to remove this feature?

**Comment by barco57** [comment]
yes, and replaced it with the Email Address Exporter Admin Tool and some helpful text about third-party services that provide email marketing services.

**Comment by scottcwilson** [comment]
Would you be willing to author this text?

**Comment by wiztechinc** [comment]
Ditto. Maybe because Michael's company has brainwashed me but most hosts don't allow much emailing at all anymore. No question best practice for best results would be third party. 

When you say author, do you mean code or write or both? Michael, we can work on this together. But I don't see any reason why we wouldn't have the email exporter in the cart as default due to this issue.  I just installed/used it recently and I think it has improved but may need some tweaking in reality (being able to chose what info is being exported)

Though the mailchimp module was nicely done, Scott, I've taken it further into zen cart integration by the way.  I think it's important to give alternatives.

**Comment by scottcwilson** [comment]
I meant write documentation for this change with recommendations.  As @barco57  said, "some helpful text about third-party services that provide email marketing services."

**Comment by wiztechinc** [comment]
mailchimp, constant contact and who else?

**Comment by scottcwilson** [comment]
That's a fine start.

**Comment by wiztechinc** [comment]
yes, I can't think of any others.  Surely there must be? I'll think on this after a nap!

**Comment by scottcwilson** [comment]
This document will be stored in git and will be updatable at any time.  Please just do a first draft.

**Comment by wiztechinc** [comment]
got it

**Comment by judygunderson** [comment]
I agree wholeheartedly!!!

Judy Gunderson
406-880-4330

Follow Us!
Get Zenned Blog
FaceBook

Visit our online retail stores
TJ's Attic - Collectibles
Learn About Feng Shui


From: Scott C Wilson 
Sent: Tuesday, March 10, 2020 5:52 AM
To: zencart/zencart 
Cc: Subscribed 
Subject: [zencart/zencart] Remove Newsletter feature (#3112)

We have discussed this before - the practice of sending volume email from your hosting account is harmful and not something we should be encouraging. Is it time to remove this feature?

**Comment by lat9** [comment]
Might I suggest posting on the Zen Cart forums that this removal is under consideration.  You'll get a wider audience and possibly some push-back.

**Comment by drbyte** [comment]
Maybe what we need to do in core is not just replace with export option, but also offer a simple interface for sending newsletter-like messages through a specific SMTP account, different from the main store SMTP?
That way it could be overridden to send stuff through PhpList/SendGrid/Mailgun/Smtp2go, etc?
Or export.
Whatever direction, I agree/prefer that ZC should just be a broker to feed something else, not "be" the newsletter "mailer", as "newsletters" is not ZC's core expertise.

**Comment by wiztechinc** [comment]
The issue is that many web hosts don't allow, throttle or don't deliver these types of emails anymore. Sure can be sent from a specific SMTP account but the risks of it not working are getting higher. So a substitute by Zen Cart does not fix the issue. I just personally believe folks needs to know that to get a true ability to send mass emails should be offered other ways.

**Comment by drbyte** [comment]
Apologies: I didn't explain a contextual point: Sendgrid/Mailgun are specifically geared to DO that kind of mass delivery. That's their core business. (So is individual transactional email, but that's besides the point.) 

Nevertheless, I agree: I don't think ZC should offer robust "design, send, monitor" capability for newsletter messaging. Just feed the data for it.

**Comment by scottcwilson** [comment]
To add some color to Chris' explanation: what makes this different is that the  SMTP Email Mail Host you will specify will *not* be your server.  It will be a different server.  Right now if you are using SMTP email you generally just specify a server controlled by your hoster in that field.

**Comment by wiztechinc** [comment]
I see. Really not what I was thinking. I would guess that needs to be part of my research here. I swear I'll get to this  - as soon I get a little more accustomed to being completely homebound!

**Comment by scottcwilson** [comment]
From a documentation perspective, just start small with Mailchimp.

**Comment by wiztechinc** [comment]
okay, that I can do. Especially that's the only real integration. Did you see my note that I've taken that further?

**Comment by wiztechinc** [comment]
uh, I do have config settings for it instead of altering the files.

**Comment by scottcwilson** [comment]
Delia, please put your article in the doc repo:
https://github.com/zencart/documentation
in content/user/email/newsletters.md 
it's all set and waiting for you! :)

**Comment by dbltoe** [comment]
A little late to the party but, most of our customers use the newsletter and might be effected by its removal.  I agree with lat9 about a poll on the forum.

**Comment by wiztechinc** [comment]
shortly - recovering from one of my customers using the newsletter function generating many many failed messages and guess who is copied on all of those emails? I must return to a less critical stance.....

**Comment by wiztechinc** [comment]
Edits done in the file. but forgot to remove the **Content from Delia here** line.  Uh, don't know if I did this right or not or what needs to happen next.

**Comment by wiztechinc** [comment]
Also had written up a bit about the why: s many hosting companies have restricted the ability of users to send large numbers of emails, this function has been removed from this version. Though your present version allows it and it may look like it still works, if you attempt to send large numbers (this could be as little as a couple of hundred), you may find that 1) your emails are not sent, generating multiple emails to you per each email sent which then clogs your inbox, 2) your webhost may penalize you or throttle you, shutting down or slowing down your website or 3) it works, you send thousands of emails and get your server designated as a spammer, restricting your (and every other website on the server) ability to send and receive emails.

**Comment by drbyte** [comment]
> Also had written up a bit about the why: s many hosting companies have restricted the ability of users to send large numbers of emails, this function has been removed from this version. Though your present version allows it and it may look like it still works, if you attempt to send large numbers (this could be as little as a couple of hundred), you may find that 1) your emails are not sent, generating multiple emails to you per each email sent which then clogs your inbox, 2) your webhost may penalize you or throttle you, shutting down or slowing down your website or 3) it works, you send thousands of emails and get your server designated as a spammer, restricting your (and every other website on the server) ability to send and receive emails.

That sounds quite alarmist. I'd rather avoid that.

**Comment by wiztechinc** [comment]
Uh, no, it's true but like I said I also had that but I did not put it into the file. This is the text:
There are several alternatives to an built-in newsletter service provider; the 
best known free one is Mailchimp.com. Mailchimp is a professional newsletter 
interface that allows emails to be sent free. As of this writing, you can have 
2000 contacts, reports, automation and more. They offer a few pre-built templates
and is sufficient for most small sites. Email lists can be exported from your
Zen Cart version, using a simple free mod and then imported into your account. 
An integrated mailchimp mod is available in the plugin section: 
https://www.zen-cart.com/downloads.php?do=file&id=425 
They also have paid features and now position themselves as a full marketing platform.

Other providers exist as well but have very limited free features or can be 
expensive. Constant Contact is the best known paid provider but cannot be fully 
integrated into Zen Cart and can't be edited or changed to fit your situation or wants. 
If you are interested in another service, just google "newsletter provider service" to get 
a view of the possibilities

**Comment by scottcwilson** [comment]
I don't see a PR.  What file did you put that into?

**Comment by wiztechinc** [comment]
Put it directly into the file you created.  Didn't do the pr since I forgot to remove the extra line and don't see how to edit it again.

**Comment by scottcwilson** [comment]
OK I will take care of it.

**Comment by drbyte** [comment]
When talking about specific providers I prefer we refrain from too many specifics about their current offerings, because those can change every day.

Please don't take offense if I update your text to be much more generic.

**Comment by scottcwilson** [comment]
Thanks Chris.  Also on my list is to mention SMTP providers but that may wait for a mod to make better use of such services.

**Comment by scottcwilson** [comment]
https://docs.zen-cart.com/user/email/newsletters/

**Comment by scottcwilson** [comment]
Since removing has become controversial, we might want to defer this, but I'll let @drbyte close the ticket if he agrees.

**Comment by drbyte** [comment]
> Also on my list is to mention SMTP providers but that may wait for a mod to make better use of such services.

Rewriting the newsletter or mass-email features to allow directing outbound messages to an alternate SMTP provider could be a possible interim step, and could set the stage for alternate integrations to be done more easily.
