### ISSUE TITLE
The “type” attribute is unnecessary for JavaScript resources.

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3119]
Would a PR removing all these references on html5 pages be accepted through gritted teeth or scathingly ignored?

**Comment by proseLA** [comment]
moving away from legacy stuff is so difficult.

personally i think time is better spent working towards a templating system for the admin side.  we have so much repetitive code for all of the html.  it would just be nicer to change it in 1 place.

**Comment by torvista** [comment]
Yes. Agreed.
But in the short term this is low-hanging fruit and another step to a "clean sheet":
https://github.com/zencart/zencart/pull/3116#issuecomment-598351632
and within the reach of those of us with little time.

**Comment by drbyte** [comment]
Please don't.

It's entirely harmless, and only creates more work for upgraders. When the javascript code is overhauled it will make very good sense at that time.
