### ISSUE TITLE
WARN_DATABASE_VERSION_PROBLEM is not a language constant

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3126]
..in my opinion.

**Comment by drbyte** [comment]
I suppose it could be deleted and you can update all the docs to just tell people to define it in their configure.php or extra_configures files if they want to override it.

**Comment by scottcwilson** [comment]
Suggested close - this complaint is true but harmless.   Same could be said of `CART_SHIPPING_METHOD_ZIP_REQUIRED` and `CART_OT_SHOW` - also not worth changing.

**Comment by torvista** [comment]
wasn't a complaint, just pointing out it's in the wrong place as is a switch, not a language string for translation. I struggled to find it documented anywhere.

**Comment by scottcwilson** [comment]
Someday maybe it would be a good idea to create a new file for settings which are very infrequently (maybe never) updated and put things like this in there (vs creating new DB entries for things that almost never change).  Such a file could also house the various magic numbers that are used in Zen Cart.  (Example: includes/modules/pages/account/header_php.php pulls the last "3" orders.  We could make this a defined constant.)

**Comment by scottcwilson** [comment]
Nope.

**Comment by torvista** [comment]
Another
'MAX_DISPLAY_RESTRICT_ENTRIES' => 20,

**Comment by torvista** [comment]
WARN_DATABASE_VERSION_PROBLEM
Why not remove this?
It indicates a problem to be resolved, it's an admin-only message, why should hiding it be an option?
