### ISSUE TITLE
zen_db_perform/zen_db_perform_language: Incorrect each->foreach conversion?

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#3133]
In `zen_db_perform`:
https://github.com/zencart/zencart/blob/16492dac60df3f032e2b7bdf0a092a94bf959ef4/includes/functions/database.php#L10

and `zen_db_perform_language`:
https://github.com/zencart/zencart/blob/16492dac60df3f032e2b7bdf0a092a94bf959ef4/includes/functions/database.php#L89

In both cases, `$data` is an _associative_ array with the column-name as the key and the column-value as the (er) value.

Shouldn't each of those lines be changed to read?
```php
    foreach($data as $key => $value) { 
```

Noting that the code reads the same for zc156c (albeit in the /admin/includes/functions sub-directory).

**Comment by drbyte** [comment]
In PHP if there's no need to make use of the array-index "key", then it doesn't need to be identified.

In the scenarios you quoted the `foreach` only uses the values. 
In contrast, the next `foreach` below it does need the index while it loops through the data, so we identify it so it can be used, in this case with a variable name `$columns` which gives a bit of meaning/context as well (although admittedly `$column` might have been slightly more accurate):
https://github.com/zencart/zencart/blob/16492dac60df3f032e2b7bdf0a092a94bf959ef4/includes/functions/database.php#L104-L107

**Comment by lat9** [comment]
Thanks for the PHP lesson!  Verified via separate test script; closing.
