### ISSUE TITLE
Multiple Categories Link Manager button gives blank screen

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3134]
Using the demo data, if you go to Admin->Catalog->Categories/Products-> drill down to the product level, then press "C" for copy, at the bottom of the sidebox on the right, there's a button at the bottom labelled "Multiple Categories Link Manager."  Clicking the button gives a blank screen.

**Comment by torvista** [comment]
I can't reproduce this...this happens on all products?
What's the log say?

**Comment by scottcwilson** [comment]
[23-Mar-2020 02:09:58 America/New_York] PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in /Users/scott/Sites/gh_demo_157/admin/products_to_categories.php on line 28
[23-Mar-2020 02:09:58 America/New_York] PHP Stack trace:
[23-Mar-2020 02:09:58 America/New_York] PHP   1. {main}() /Users/scott/Sites/gh_demo_157/admin/index.php:0

NOTE: This only happens in PHP 5.6; in PHP 7.1, it is fine.

**Comment by drbyte** [comment]
`function zen_validate_categories(int $ref_category_id, int $target_category_id = 0, $reset_master_category = false)
`

Ya, those `int` typehints are scalar typehints, which are only available since PHP 7.

**Comment by scottcwilson** [comment]
OK - we just have to remember to say that Zen Cart 1.5.7 is for PHP 7.1 and higher only. 
https://docs.zen-cart.com/user/first_steps/server_requirements/

**Comment by drbyte** [comment]
> OK - we just have to remember to say that Zen Cart 1.5.7 is for PHP 7.1 and higher only.
> https://docs.zen-cart.com/user/first_steps/server_requirements/

No.

While it'd be wonderful to have everyone jump to a modern PHP version, or at least have upgraders use a truly separate staging environment for doing and testing their upgrades where they also only use a modern PHP version, the reality is that most people will upgrade directly on the same server, using an old PHP version. Thus we're maintaining backward compatibility by avoiding use of features not supported back that far.

**Comment by scottcwilson** [comment]
OK - but doesn't that mean that this issue should be fixed then?

**Comment by drbyte** [comment]
I did: https://github.com/zencart/zencart/commit/658bf48d06c0c7e4393cd09961a195465e7f4ea3

**Comment by scottcwilson** [comment]
oops - just saw the close, not the related fix.  Thanks for confirmin.

**Comment by dbltoe** [comment]
Is it too convoluted to suggest to the upgrader to use a subdomain and take advantage of most hosts' multi-php manager at upgrade?

**Comment by drbyte** [comment]
> Is it too convoluted to suggest to the upgrader to use a subdomain and take advantage of most hosts' multi-php manager at upgrade?

It's a good suggestion. Hard to document though, especially if their host doesn't offer a multi-php manager.

**Comment by dbltoe** [comment]
We use it and mod list on every upgrade.  Just check the old database collation.
Perhaps an addition of "If your host provides multi-php manager..." to your excellent "How do I rebuild..."
Scotts mod list gives us a quick look at what might be hanging around from earlier versions.
Just another vote for it's inclusion in 1.5.7 (with the minor sort addition)

**Comment by scottcwilson** [comment]
Aside: if you like Mod List, you'll *love* View Schema. :). Coming next month! 
https://www.thatsoftwareguy.com/zencart_view_schema.html

**Comment by drbyte** [comment]
Is there a way for mod-list and view-schema to sit "outside zencart" instead of adding dozens of files into a site ... which then also have to be maintained?

**Comment by scottcwilson** [comment]
Interesting concept.  Maybe the extras menu could peek into a "tools" folder which could contain utilities like this (also EZPopulate, MySQL Backup, etc.).  But would it be worth extra effort?  Not sure.  I will noodle on it.

**Comment by wiztechinc** [comment]
> Is it too convoluted to suggest to the upgrader to use a subdomain and take advantage of most hosts' multi-php manager at upgrade?

Most of the carts I'm upgrading are really old - because their hosting companies is turning off/upgrading their server where they have running ancient versions (really really ancient) so in many cases they are being moved to another server or another hosting company. Then usually they also don't have multi-php manager either.

**Comment by scottcwilson** [comment]
I have also hit what Delia is seeing.  If they have PHP 5.4, they just *don't have* PHP7 on that server.

**Comment by dbltoe** [comment]
Perhaps another reason to steer the folks in the right direction.
DirectAdmin, Plesk, Froxlor, Virtualmin, and Ajenti all provide multi-php.
With cpanel and PHP-FPM, our servers can provide 5.4 through 7.3.
I'm sure Mike has similar capabilities.
CloudLinux provides hardened/secured from 4.4 up.

**Comment by lat9** [comment]
> 
> 
> > Is it too convoluted to suggest to the upgrader to use a subdomain and take advantage of most hosts' multi-php manager at upgrade?
> 
> It's a good suggestion. Hard to document though, especially if their host doesn't offer a multi-php manager.

Noting, too, that many store's SSL certificates don't cover subdomains ... so that's an extra expense.  I normally use a sub-directory for any upgrade handling so that the upgrade 'inherits' the live site's SSL certificate.

**Comment by drbyte** [comment]
> Noting, too, that many store's SSL certificates don't cover subdomains

Good point. Although one doesn't need SSL for testing staging stuff as long as they stay away from payment processing and don't mind the browser giving warnings about not-secure forms during that temporary period.

**Comment by wiztechinc** [comment]
So yes steer clients to better hosting - that has cpanel certs at no extra cost first. But remember the better the hosting the less likely they will have lower php versions installed since they present security risks. You really don't want client using 5.4 across all their websites ...... Many hosts no longer allow anything below 7.0.

**Comment by dbltoe** [comment]
At the risk of tooting our horn, it automagically happens on our servers.  Tell the installer to go with https:// and you get it.
I know we are getting far off target here, and I apologize if I am the dragger.  Just reiterating that our hosting is here to support Zen Cart and the Zen Cart family.  It galls me how many items that are free to the host are passed on as an expense for the user.

**Comment by wiztechinc** [comment]
As it does on another major zen cart hosting company.

**Comment by dbltoe** [comment]
As mentioned above, I'm sure Mike can provide the same.  Not sure of the others.
Just want folks to know the options are there and we provide what we can to keep Zenners in business.
