### ISSUE TITLE
fix responsive classic totals....

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#3139]
this is what i get from the base v156c release for the responsive classic template on a desktop display:
![Screenshot from 2020-03-25 08-48-12](https://user-images.githubusercontent.com/1095136/77556570-f0e52700-6e75-11ea-9ecc-366b70dce976.png)
i have seen user complaints about this very issue on the forum.
if one were to look at this line here:
https://github.com/zencart/zencart/blob/22424cedd39d8b4b8496438507f8a897881e0644/includes/templates/template_default/templates/tpl_checkout_payment_default.php#L38
and remove the class element of `forward`; this problem would get resolved.  the text for the billing address would need to get changed as that text is no longer to the left of the address.  However, IMO, we should not indicate where anything is in a responsive design.  Other than the words `shown` or `displayed`, things like to the left make numerous assumptions about users viewports and the like.
i see this code in v157 as well.  i am **NOT** the css guru.  i have no problem doing a PR for these changes but would like input prior to doing them.
i did look at the change as well on a mobile device; and it looks fine there.  in addition, that text is not to the left there either.  so i think the text needs to be changed to accomodate mobile.

**Comment by scottcwilson** [comment]
This issue is fixed in 1.5.7.

**Comment by lat9** [comment]
> 
> 
> This issue is fixed in 1.5.7.

Could you provide a link to the PR that made this correction?

**Comment by scottcwilson** [comment]
https://github.com/zencart/zencart/pull/2856

**Comment by proseLA** [comment]
confirmed.  thanks!
