### ISSUE TITLE
admin categories description clean <p /> tag

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3150]
While clearing a bug (unrelated) , I find this;
```
 // clean $categories_description when blank or just <p /> left behind
        $sql_data_array = [
          'categories_name' => zen_db_prepare_input($categories_name_array[$language_id]),
          'categories_description' => ($categories_description_array[$language_id] === '<p />' ? '' : zen_db_prepare_input($categories_description_array[$language_id]))
        ];
```
This seems too deliberate to be a mistake, anyone care to explain the 

` <p />`  tag instead of `</p>`?

**Comment by drbyte** [comment]
It was added in 1.2.0 to catch cases where javascript-driven rich-text editors would leave behind empty html blocks, usually empty paragraphs.

I think one of the editors at the time was leaving a self-closing paragraph tag, hence the `<p />`.

But a better way would be to just test if `empty(trim(strip_tags($foo)))`
