### ISSUE TITLE
Admin, auto-strip http/s from product_url when entering/editing products

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3157]
Since day 1 I have stripped this from user-inputted urls since they are always (in my case at least) copied and pasted from a browser.
For example I use this on the preview 
function mv_remove_http($url = '')
{
	return(str_replace(array('http://','https://'), '', $url));
}

I would like to submit a suitable function for this, any preference for other methods?
https://stackoverflow.com/questions/4357668/how-do-i-remove-http-https-and-slash-from-user-input-in-php

**Comment by drbyte** [comment]
I'm assuming you were trying to solve some business problem by doing so. 
What was that problem?

I see it creating another problem: namely, if you insert/paste something like this:
`Read more at <a href="http://example.com/readmore">our website</a>` 
and strip out just the `http://` or `https://` ...
... then you're going to end up with:
`Read more at <a href="example.com/readmore">our website</a>` 
... which is a `relative` URL, so when someone clicks that link they're going to be taken to:
`https://your_store.com/example.com/readme` which is completely wrong.

**Comment by scottcwilson** [comment]
The intention here is to get rid of the requirement to remove "http://" isn't it?  So you can just copy and paste from the browser's address bar?   (If this already works perfectly then maybe we can remove the (without http://) message.)

**Comment by drbyte** [comment]
Gimme an example of the workflow where this is needed. I see one person talking about "copy and paste from a browser" and another saying "copy... from the browser's address bar", and the context of the proposal is in a "preview" screen. Too much vagueness. Let's get specific.

**Comment by torvista** [comment]
I am on about copying an address from a browser address bar, to the URL field(s) in admin product collect info. Just the url, not a <a link.
These would be the link to the manufacturers webpage for that specific product.
All my products use a specific link.

**Comment by scottcwilson** [comment]
We may be making this more complicated than need be.  My only desire on this is to get rid of the text that says "without http://" (and obviously the need for the text in the first place).  

What has to be done to get there?  Steve, would you be satisfied with this as an outcome?

**Comment by torvista** [comment]
This works for me in preview_info:
$products_url = $_POST['products_url'];
  foreach ($products_url as &$url){ // remove protocol
      $url = str_replace(array('http://', 'https://'), '', $url);
  }

**Comment by drbyte** [comment]
Thanks for clarifying what this is really about.

**Comment by drbyte** [comment]
I gather the simple change would be:
```diff
  foreach($product as $prod) {
    $products_name[$prod['language_id']] = $prod['products_name'];
    $products_description[$prod['language_id']] = $prod['products_description'];
-    $products_url[$prod['language_id']] = $prod['products_url'];
+    $products_url[$prod['language_id']] = str_replace(array('http://', 'https://'), '', $prod['products_url']);
  }

**Comment by torvista** [comment]
From what I can see, that bit is only dealing with the Select from the db, which should be ok already...
It does not clean the http from the POST from the previous page which is used in the preview, and so the link would be broken in the preview text. 
It does not clean the link used in the hidden field in the form either.

**Comment by drbyte** [comment]
You're right. Sorry, I think someone gave me decaf coffee today instead of regular!

Your code snippet from earlier is fine:

> This works for me in preview_info:
> $products_url = $_POST['products_url'];
> foreach ($products_url as &$url) {
>     $url = str_replace(array('http://', 'https://'), '', $url);
> }
> unset($url);
