### ISSUE TITLE
PHP Notice admin: /local and normal configure.php are both loaded by application_bootstrap

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3159]
I know I already reported this, but do not find it.
When I have a /local/configure defined, I get all the php notices in the browser, for all the repeated cosntants, eg.:

> Notice: Constant HTTP_SERVER already defined in......0\Dev\public_html\zencart-157\admin\includes\configure.php on line 17 

I just put a clause around the second load and have had no problems, prepare a PR?

**Comment by drbyte** [comment]
Thanks, but no thanks.

While you're welcome to make such changes in your own configure.php file, I prefer NOT to merge a PR that hides such issues, since in production it's expected that those values are only declared in the configure.php file, and it would be wise to have such notices show up if the particular shop's logging is set to catch them.

Further, in production, it is best to set the server to never display ANY errors to the browser, for security reasons. You are of course free to alter that for yourself especially in development.

**Comment by torvista** [comment]
I had to read that a few times but still think we are at cross purposes.
Just so I am clear, 
as far as I was aware, the /local/configure is intended to provide local credentials for a development site and so is never copied to a production site.  So it has all the same constants as the production configure, maybe more for debugging, but since it is never uploaded to the production site (or it would break the site with different credentials) that would not matter
At the moment both are loaded, giving the corresponding error. The fact it is shown in the ebrowser is incidental/not the problem, it only highlights the double loading.

The suggested PR is not meant to hide anything, just load only one of the configures.

**Comment by lat9** [comment]
The issue, I believe, is in the ordering of application_bootstrap's load.  Previous versions of Zen Cart have the 'strict-error-reporting' detection _prior to_ the load of the /local (if exists) and /includes versions of the configure.php files, while  `application_bootstrap.php` includes that detection **after** those configure.php files load.  I'll suggest restoring the original ordering.

Currently:
```php
/**
 * Set the local configuration parameters - mainly for developers
 */
if (file_exists('includes/local/configure.php')) {
    /**
     * load any local(user created) configure file.
     */
    include('includes/local/configure.php');
}
/**
 * check for and load application configuration parameters
 */
if (file_exists('includes/configure.php')) {
    /**
     * load the main configure file.
     */
    include('includes/configure.php');
}
/**
 * set the level of error reporting
 *
 * Note STRICT_ERROR_REPORTING should never be set to true on a production site. <br />
 * It is mainly there to show php warnings during testing/bug fixing phases.<br />
 * note for strict error reporting we also turn on show_errors as this may be disabled<br />
 * in php.ini. Otherwise we respect the php.ini setting
 *
 */
if (defined('STRICT_ERROR_REPORTING') && STRICT_ERROR_REPORTING == true) {
    @ini_set('display_errors', TRUE);
    error_reporting(E_ALL);
} else {
    error_reporting(0);
}
```

Suggested change:
```php
/**
 * set the level of error reporting
 *
 * Note STRICT_ERROR_REPORTING should never be set to true on a production site. <br />
 * It is mainly there to show php warnings during testing/bug fixing phases.<br />
 * note for strict error reporting we also turn on show_errors as this may be disabled<br />
 * in php.ini. Otherwise we respect the php.ini setting
 *
 */
if (defined('STRICT_ERROR_REPORTING') && STRICT_ERROR_REPORTING == true) {
    @ini_set('display_errors', TRUE);
    error_reporting(E_ALL);
} else {
    error_reporting(0);
}
/**
 * Set the local configuration parameters - mainly for developers
 */
if (file_exists('includes/local/configure.php')) {
    /**
     * load any local(user created) configure file.
     */
    include('includes/local/configure.php');
}
/**
 * check for and load application configuration parameters
 */
if (file_exists('includes/configure.php')) {
    /**
     * load the main configure file.
     */
    include('includes/configure.php');
}
```

**Comment by torvista** [comment]
Are we discussing two things here?
1) The fact that a second configure is loaded with the duplicated constants, which is wrong.
2) Why or why not an error is triggered/reported.

I was pointing out the first one. The second one is, er, secondary.

But the post from lat9 indicates (I think) why this does not raise an error on the catalog. So something also to be rationalised at the same time.
 
But in the suggested solution, where does one put one's define for strict error reporting:
https://www.zen-cart.com/content.php?315-what-is-strict_error_reporting
Chicken, egg no?

**Comment by lat9** [comment]
My suggestion was to _restore_ the sequence to that present in previous Zen Cart's **admin** start-up.  I'll grant (and I'd though of, too) that moving that `STRICT_ERROR_REPORTING` clause _after_ the load of the /includes/local/configure.php would enable said file to include that constant without making modifications to Zen Cart core files.

**Comment by drbyte** [comment]
Having `local/configure.php` load before `configure.php` AND still loading both, allows one to stick a single define in the `local` file (the point is, a less-than-complete-copy-of-configure.php, because not everything is needed in the local file) and still let all the other normal `configure.php` defines be processed.

The proposed either/or for local/configure vs configure would break that, which I'm not agreeable to.

**Comment by lat9** [comment]
Right, but the current application_bootstrap.php processing is **different** from previous Zen Cart versions' load.  That section regarding `STRICT_ERROR_REPORTING` needs to be either before the /local load or, preferably, after the potential /local load and before the main admin configure.php file is loaded.

Otherwise, various admin AJAX processors will fail in a local-test environment due to that message output prior to the HTTP header's send.

**Comment by torvista** [comment]
Well, I have always thought the local configure.php was a copy of / a replacement for, the real configure.php, since it had the same name but was for local/development use: hence "local".
I have always installed a site, then copied the generated configure to /local making a very easy comparison between the two when necessary.
I never thought it would only have the **differences** in it, especially since almost all the constants are in fact different for local use.
Having other constants in it for development use (show errors, trap emails) seems to me to be a logical but optional extension (while those additional constants are in the main code as
if (!defined....).
I would propose this file is used as such (as a complete copy) and documented as such.

**Comment by drbyte** [comment]
Planning to delete the admin configure.php in 1.5.8

**Comment by drbyte** [comment]
> My suggestion was to _restore_ the sequence to that present in previous Zen Cart's **admin** start-up. I'll grant (and I'd though of, too) that moving that `STRICT_ERROR_REPORTING` clause _after_ the load of the /includes/local/configure.php would enable said file to include that constant without making modifications to Zen Cart core files.

The re-ordering was requested by @torvista back in https://github.com/zencart/zencart/issues/2284 and implemented in https://github.com/zencart/zencart/pull/2474/files

**Comment by lat9** [comment]
@torvista, can this issue be closed?  It looks like there's been significant 'traction' over the past 2+ years.

**Comment by torvista** [comment]
With vanilla ZC158 and configure.php files duplicated in
admin/include/configure.php
admin/include/local/configure.php

admin breaks with 

> Warning: Constant HTTP_SERVER already defined in...etc.

Shopfront is not giving an error, probably due to as discussed above.
