### ISSUE TITLE
Admin: Product Data input - reorder entry fields by drag and drop

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3162]
I found the vanilla order less than intuitive for my needs, so changed it last century.
While that is still the case, probably this is the one form that most people would like to reorder to taste/it would be impossible to agree a changed format.
So, how about making it a drag and drop field form, whose order is saved on preview?
I investigated for 5 minutes, seems not too difficult.
Anyone done it and have a method they can recommend?

**Comment by lankeeyankee** [comment]
This would be amazing, along with ability to hide fields that always stay constant which for me is things like product is call for price, qty min, qty max, qty min/max mixed and several others that I have never used once. I currently modify the collect info file to hide these fields to unclutter the page. Although not sure how you'd enable the hidden fields, would probably need to be a switch for that.

**Comment by torvista** [comment]
Ditto. Lots of stuff I never use either, but essential for others, hence the idea.

**Comment by wiztechinc** [comment]
> > labels that truly make no sense
> 
> That's a red rag to a bull...you need to grab it by the horns and submit those pesky labels to your plain-english-speaking will, so they DO make sense. Now is the time....

Except the problems isn’t just the labels since some settings require a fair amount of explanation. Thus my drive for more explanations/help. I am presently building a workshop in my basement rather than on the computer for my sanity. Haven’t forgotten, just the world is upside down right now.

**Comment by Zen4All** [comment]
I have been waiting working on this in my citrine module.
It gives you the ability to add, remove, reorder any field for the collect info page, for each product type. Changes are saved in the database.
It is for for 80% ready. I can post a link if you are interested.

**Comment by torvista** [comment]
...why don't you go for 100%...although I still haven't got round to looking it, from the snippets you have posted it seems a no-brainer to submit it.

**Comment by Zen4All** [comment]
I want to go for the 100% believe me, but a day only has 24 hours. But maybe I should move this mod up the priority list

**Comment by torvista** [comment]
at the risk of repeating myself, is it on Github to be contributed to?

**Comment by lankeeyankee** [comment]
@Zen4All could it be used as the basis for creating a drag and drop admin homepage? That would be a good step towards developing new widgets for the homepage such as visual reports and/or graphs for various metrics, etc. This would help modernize the interface and give the user useful information at a glance.

**Comment by Zen4All** [comment]
@lankeeyankee 
Yes it could. The drag&drop is a standard jQuery snippet, that can be found at jQuery.com

**Comment by lankeeyankee** [comment]
These are the types of changes that would encourage the average user to upgrade, things that directly improve their experience and help give them deeper insights to make better business decisions. Alas, my skills are eroded to about 0 so I can only be useful in testing.

**Comment by Zen4All** [comment]
IMHO One of the biggest pro is it eliminates the need for all the extra "admin/includes/modules/product_type/" files.

**Comment by wiztechinc** [comment]
> IMHO One of the biggest pro is it eliminates the need for all the extra "admin/includes/modules/product_type/" files.

so literally the different product types are mostlyabout just what is presented as you create and edit products? Making mods so much easier in general? I'm in. I'm not super great with jquery but have someone who is that I work with in case I run into problems. 

@Zen4All  - github? or something I can play with? not sure how helpful I can be because my php skills have also eroded but this sounds like it might be worth the effort.

**Comment by Zen4All** [comment]
@wiztechinc see [Collect Info Through Tabs In New Style for Zen Cart](https://github.com/Zen4All-nl/Collect-Info-Through-Tabs-In-New-Style-for-Zen-Cart). Be aware it is a work in progress, so do not use on a live shop. Not all functionality is ready, but it will give you a good indication of what is the end goal

**Comment by wiztechinc** [comment]
Thanks, I'll check it out.

**Comment by wiztechinc** [comment]
I like it. It's actually the product tabs used in admin and though I actually can't see it at work right now I'm convinced this is a great way to go. It can used to streamline so much of the admin. The biggest issue is finding all the disparate things that go along with the product. If there was a simpler way to work with one product without have to search and go to full new screens etc, then this is definitely a possibility. As I said many times, learning the cart features is daunting. I vividly remember trying to learn it all on my own thinking it just didn't feel organized. Organizational schemes are hopefully the most efficient way of looking at something and from a owner point of view, I do not believe the present organization is that most efficient method. And no, I've never come up with higher thoughts than that to offer suggestions.

**Comment by torvista** [comment]
closing this as it is not an issues, but on a wishlist.
