### ISSUE TITLE
Featured: php notices, general review

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3173]
I'm working on this...
I find this parameter 'manual'
`<?php echo ((int)$_GET['manual'] == 0`
The only mention of 'manual' in the admin that I find, is in init_sanitze to allow this parameter, but I don't find anywhere that sets it.
Anyone can cast a light on this...otherwise it can be removed I think.

**Comment by scottcwilson** [comment]
You mean for `admin/featured.php` right?  It looks unused.

**Comment by torvista** [comment]
yes
