### ISSUE TITLE
Saving to new user profile only saves to super_user

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#3179]
@torvista , @drbyte 
https://github.com/zencart/zencart/blob/34fd4324ac76dbfec1cfa9196a846ec8545880c8/admin/users.php#L183

since the above line was added all users are saved as super_users when trying to set another user profile to a user

**Comment by torvista** [comment]
ok....

**Comment by torvista** [comment]
https://github.com/zencart/zencart/pull/3180

**Comment by drbyte** [comment]
> #3180

@torvista TIP: when you do a PR to resolve an Issue, if put a comment in the PR comments saying "Closes #0000" or "Fixes #0000" it will auto-link them together and when the PR is merged it'll auto-close the Issue.  Plus it'll show notes about the linkages automatically on both sides.
