### ISSUE TITLE
Options Name Manager discuss

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3201]
Hi,
Zen4All pre-empted a big PR I had almost finished earlier this year. I'm getting around to re-merging it.

The Global Tools On/Off **selection** right in prime GUI space seems pointless to me and I would get rid of it altogether.
Any reason to keep it?

**Comment by lankeeyankee** [comment]
Not in my mind, I think it's just fine at the bottom of the page. Would be nice to include the same type of select-able "display number on page" dropdown that he added to the options values page, that is quite handy and is something I think could be useful on many admin pages.

**Comment by torvista** [comment]
I meant remove the **selection** of whether to display those tools, not remove the tools, ie always display the tools at the bottom. I don't see the point of hiding them, unless it is to prevent their queries when not used.

**Comment by lankeeyankee** [comment]
ah, yes, I agree, that should be removed entirely

**Comment by mc12345678** [comment]
As it was described to me many years ago was that there are those people that like and know how to use those features and there are those that do not.  To support leaving the store "that way", there is the option setting in the configuration menu to "default" with those options off or default with them on... 

My question is why change the presence of the ability to show/hide the additional capability? What issue is it causing?

**Comment by torvista** [comment]
Visual clutter that adds no value.
Old
![old](https://user-images.githubusercontent.com/4391026/79189268-95c5a500-7e21-11ea-915e-3a10367d0582.gif)

New
![new](https://user-images.githubusercontent.com/4391026/79189273-98c09580-7e21-11ea-8174-94ef054d842f.gif)

I would also get rid of the admin switch, I forgot it was there.

**Comment by torvista** [comment]
While reviewing existing code, I don't follow this use of $copy_from_values->MoveNext(); in the middle of the clause. I have only ever seen MoveNext at the end of a clause, where logically it moves to the next element in the object. The code works for copying values between names but I don't see how!

```
if ($copy_from_values->RecordCount() > 0) {
          // successful copy
          $next_id = ($start_id->fields['products_options_values_id'] + 1);
          while (!$copy_from_values->EOF) {
            $current_id = $copy_from_values->fields['products_options_values_id'];
            $sql = "INSERT INTO " . TABLE_PRODUCTS_OPTIONS_VALUES . " (products_options_values_id, language_id, products_options_values_name, products_options_values_sort_order)
                    VALUES (" . (int)$next_id . ", " . (int)$copy_from_values->fields['language_id'] . ", '" . $copy_from_values->fields['products_options_values_name'] . "', " . (int)$copy_from_values->fields['products_options_values_sort_order'] . ")";
            $db->Execute($sql);
            $copy_from_values->MoveNext();
            if ($copy_from_values->fields['products_options_values_id'] != $current_id || $copy_from_values->EOF) {
              $sql = "INSERT INTO " . TABLE_PRODUCTS_OPTIONS_VALUES_TO_PRODUCTS_OPTIONS . " (products_options_id, products_options_values_id)
                      VALUES (" . (int)$options_id_to . ", " . (int)$next_id . ")";
              $db->Execute($sql);
              $next_id++;
            }
          }
          $messageStack->add(SUCCESS_OPTION_VALUES_COPIED . ' from: ' . zen_options_name($options_id_from) . ' to: ' . zen_options_name($options_id_to), 'success');
        } else {
          // warning nothing to copy
          $messageStack->add(ERROR_OPTION_VALUES_NONE . ' from: ' . zen_options_name($options_id_from) . ' to: ' . zen_options_name($options_id_to), 'warning');
        }
```

**Comment by drbyte** [comment]
It's an interesting approach. It's advancing to the next record before looping from the start. I guess the intention is to compare against subsequent values?

**Comment by scottcwilson** [comment]
Clever code is often brittle and leads to hard to debug problems.  Suggest simplification.

**Comment by torvista** [comment]
I usually replace movenexts with foreach. I didn't want to fix something that wasn't broken but I guess now is the time.

**Comment by torvista** [comment]
Well, since I never modified this, I assumed it was ok. It's not... work in progress.

**Comment by torvista** [comment]
>I guess the intention is to compare against subsequent values?

I can't see the point of this logic/the

>if ($copy_from_values->fields[....

clause.
As far as I can see a single foreach is adequate:
copy a new value into the products_options_values table
write a value-option pair into the products_options_values_to_products_options table

Maybe I am missing something but this check;
>if ($copy_from_values->fields['products_options_values_id'] != $current_id 
|| $copy_from_values->EOF) {

The first part is always true until the last iteration due to the preceeding movenext, so yes it checks  subsequent values are different. On the last iteration , this fails....but the $copy_from_values->EOF is true so the last value is copied.
What's the point? Checking for duplicate values (not working)?

I don't like to replace it because I don't understand, it's rare to come across code that has no purpose.

**Comment by mc12345678** [comment]
What I see that section doing is ensuring that only the first instance of a `products_options_values_id` is incorporated into the destination option name such that if there is a table problem that has caused the `products_options_values` table to have two or more instances of the same `products_options_values_id` or for the `products_options_values_to_products_options` table to have two or more records with the same `products_options_id`. In either of those conditions, only the first instance of the `products_options_values_id` would be duplicated regardless of the quantity of the remaining.  Ultimately, if the result did not look as desired (not all attributes copied), then copying of the "missing" attributes could be performed and the desired result obtained through a subsequent copy.

Such a problem could occur if aspects of the tables had been modified/disturbed and then possibly under any of the following circumstances/situations:
- products_options_values does not have a requirement to have unique products_options_values_id except when combined with languages_id, so in a multiple language environment every products_options_values_id exists for the number of times that there are language records.
- if the primary key were removed from the table `products_options_values`, then it would be possible to assign the same `products_options_values_id` to any number of items, not just those in another language.
- The table `products_options_values_to_products_options` is a join table that has a primary key based on the record that is generated by a value pair of `products_options_values_id` and `products_options_id`.  There is nothing strictly in the database table that ensures that there is no duplication of either id or combination of ids in the table.  Therefore, if improperly managed through other code, then there is the possibility that there are two records that contain the exact same information but at a different `products_options_values_to_products_options_id` and cause a duplicate `productts_options_values_id` to exist in the resulting query.

Basically it appears that the code is intended to ensure that the destination location receives what appears to be the expected results or at least in such a way that if the destination doesn't have/receive all of the data, then it would/should raise a flag to the individual making the copy (e.g. I had X items on this list and only got Y items, how come?)

However, there is one thing about this process... It depends on the `products_options_values_id` being sequential when looking at storage... Wasn't this sequence broken in either this or a recent update based on not seeing a need for items to be copied/created in such sequence? The fact that this test and query: 
````php
            if ($copy_from_values->fields['products_options_values_id'] != $current_id || $copy_from_values->EOF) {
              $sql = "INSERT INTO " . TABLE_PRODUCTS_OPTIONS_VALUES_TO_PRODUCTS_OPTIONS . " (products_options_id, products_options_values_id)
                      VALUES (" . (int)$options_id_to . ", " . (int)$next_id . ")";
              $db->Execute($sql);
              $next_id++;
            }
````
*blindly* assigns `(int)$next_id` to `products_options_values_id` and then increments it by one indicates that there was some previously thought out process to ensure that the "next" `products_options_values_id` would in fact have the next number in sequence not just some other random number that may need to be looked up...

**Comment by torvista** [comment]
Well, what an answer, thanks for taking the time.
The insert of new values is sequential in that the next_id is taken from the max value of the column. But from deletions, there will be gaps in the overall sequence/column.
I think a better approach would be to do a check on the db on entering this page and values manager, so things can be corrected immediately?

**Comment by torvista** [comment]
While looking at coding a check that there are no duplicates in the products_options_values table, I find I cannot edit the table to manually create a duplicate id-language pair:

![Clipboard01](https://user-images.githubusercontent.com/4391026/79700801-caf64b00-8298-11ea-99d8-18297534fec2.gif)

I assume this means it is impossible to create a duplicate by any means so there is no point in checking for a duplicate?

**Comment by drbyte** [comment]
Yes, if primary keys and unique indexes are in place there shouldn't be any duplicates.

If we're missing a necessary unique index then that's worth a detailed discussion.

**Comment by torvista** [comment]
ok so I conclude
1) table products_options_values
The only check one can do (apart from TEXT at 0), is that 
repeat ids = the number of languages , no more no less.

2) table products_options_values_to_products_options
products_options_values_to_products_options_id: cannot be duplicated (mysql prevents it)
products_options_id  & products_options_values_id CAN be duplicated, so that can/should be checked.

**Comment by drbyte** [comment]
I haven't studied those attribute relationships in a long time, so I can't confirm. 
mc12345678 probably deals with it more often :)
