### ISSUE TITLE
Admin: admin_account.php: notice by redeclaration of HEADING_TITLE

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3204]
This includes its own language file and users.php, so there is a notice due to the duplicated HEADING_TITLE.
For the minimal overhead, for now, why not put (repeat) the necessary constants in admin_account and stop including the users language file?
Related:
https://github.com/zencart/zencart/pull/1074

**Comment by scottcwilson** [comment]
We can just check to see if HEADING_TITLE is defined before defining it.

**Comment by scottcwilson** [comment]
This ticket can be closed now that #3224 has been merged, right?

**Comment by torvista** [comment]
yep

**Comment by scottcwilson** [comment]
Steve, would you please take a look through the open issues you created and see what other ones can be closed?

**Comment by torvista** [comment]
Yes, I try to do that regularly....
