### ISSUE TITLE
Admin: users.php - Edit of existing user, no profile selected reports as Updated

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3225]
Not a bug,.
If the profile if changed from the current valid one, to Choose Profile instead of a valid profile, the messagestack reports that the details were updated correctly (not true) and the current profile is maintained.
So, not a problem but not quite correct, function zen_update_user does not seem to deal with $profile = 0.
If the Select option was '' instead of 0 it could be set to required.

**Comment by torvista** [comment]
Additional point to note:
1) add admin password as per wiki
https://www.zen-cart.com/content.php?44-how-do-i-change-or-reset-my-admin-password-(i-lost-it)
2) While in admin, there is a messagestack reminder to delete it.
3) delete the user...messagestack reminder is still shown after the delete.
4) refresh the page (resubmitting the deleteconfirm). Reminder is cleared but a notice is generated
--> PHP Notice: Undefined index: admin_name in....\zencart-157\admin\includes\functions\admin_access.php on line 275.

**Comment by drbyte** [comment]
@torvista Did you close this because it's resolved?

**Comment by torvista** [comment]
No.
Seemed such a rare case/non-issue that unless I "fixed" it, it would languish here until Scott complained. And I **really** need to do some work: next week the great unwashed are back on the streets here and we will be very busy.
