### ISSUE TITLE
localization not respected for date_available field 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3243]
Continuing @torvista 's issue from #3020.  

Two issues need fixing:
- Hardcoded text string YYYY-MM-DD below Date Available.
- Localization support for this field, which should be available by modifying the define DATE_FORMAT_DATE_PICKER.  

These issues are both fixed in #3242.  Opening this ticket for tracking.

**Comment by scottcwilson** [comment]
Fixed by #3242.

**Comment by torvista** [comment]
related?
https://www.zen-cart.com/showthread.php?225221-Admin-date-text-boxes-return-dates-in-different-date-format&p=1374445
