### ISSUE TITLE
installer and local configure confusion

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3244]
For a re-install on an existing db, locally.
There is a 
/includes/configure.php with the remote hosting config
/includes/local/configure.php with the local dev config

1) Run installer as Clean Install
It detects and mentions the existence of the /local file and states it will be used.
2) On the Database Setup page this popup is shown
![Clipboard01](https://user-images.githubusercontent.com/4391026/79139458-a260e380-7db6-11ea-9ee5-63f70dfaa369.gif)
in conjunction with these error messages, and you cannot proceed any further.

> [13-Apr-2020 18:44:26 Europe/Madrid] PHP Notice:  Undefined index: db_charset in D:\....\Dev\public_html\zencart-157\zc_install\ajaxTestDBConnection.php on line 25
> [13-Apr-2020 18:44:26 Europe/Madrid] PHP Warning:  file_exists() expects parameter 1 to be a valid path, array given in D:\....\public_html\zencart-157\zc_install\includes\classes\class.systemChecker.php on line 283
> [13-Apr-2020 18:44:26 Europe/Madrid] PHP Warning:  file_exists() expects parameter 1 to be a valid path, array given in D:\....\public_html\zencart-157\zc_install\includes\classes\class.systemChecker.php on line 283
> [13-Apr-2020 18:44:26 Europe/Madrid] PHP Notice:  Trying to access array offset on value of type null in D:\....\public_html\zencart-157\zc_install\includes\classes\class.systemChecker.php on line 48
> [13-Apr-2020 18:44:26 Europe/Madrid] PHP Notice:  Trying to access array offset on value of type null in D:\....\public_html\zencart-157\zc_install\includes\classes\class.systemChecker.php on line 658

---------------

> 
> Apr 13 2020 18:44 -- checkFileExists
> FAILED
> (
>     [fileDir] => D:\...\...\..\zencart-157/includes/local/configure.php
> )
> 
> ---------------
> Apr 13 2020 18:44 -- checkFileExists
> FAILED
> (
>     [fileDir] => includes/local/configure.php
> )
> ---------------
> Apr 13 2020 18:44 -- checkNewDBConnection
> PASSED
> 

Note the change in orientation of the slashes of  [fileDir]

**Comment by drbyte** [comment]
As far as I recall this part of the code hasn't been touched in a long time. 
I'm surprised that you're newly getting a `FAILED` response.

Yes, you've pointed out that some array indexes are being checked that "don't exist", so we'll work on that. But I'm curious whether this `FAILED` response is actually new, or has always been happening?

**Comment by drbyte** [comment]
One fix, which might also have undesired side effects, is to change `class.systemChecker.php` on line 281-3:

```diff
-  public function checkFileExists($filepath)
+  public function checkFileExists($parameters)
  {
-    return file_exists($filepath);
+    return file_exists($parameters['fileDir']);
  }
```

**Comment by torvista** [comment]
Same result, slightly different debugs

> [13-Apr-2020 19:30:16 Europe/Madrid] PHP Notice:  Undefined index: db_charset in D:\....\public_html\zencart-157\zc_install\ajaxTestDBConnection.php on line 25
[13-Apr-2020 19:30:16 Europe/Madrid] PHP Notice:  Trying to access array offset on value of type null in D:\....\public_html\zencart-157\zc_install\includes\classes\class.systemChecker.php on line 48
[13-Apr-2020 19:30:16 Europe/Madrid] PHP Notice:  Trying to access array offset on value of type null in D:\....\public_html\zencart-157\zc_install\includes\classes\class.systemChecker.php on line 660

> ---------------
Apr 13 2020 19:30 -- checkFileExists
PASSED
(
    [fileDir] => D:\...\public_html\zencart-157/includes/local/configure.php
)


---------------
Apr 13 2020 19:30 -- checkFileExists
FAILED
(
    [fileDir] => includes/local/configure.php
)


---------------
Apr 13 2020 19:30 -- checkNewDBConnection
PASSED

**Comment by torvista** [comment]
I always suspect Windows and slashes....

**Comment by lat9** [comment]
Why is `local` capitalized in that message?  Could that be the underlying issue?

**Comment by drbyte** [comment]
> Apr 13 2020 19:30 -- checkFileExists
PASSED
(
[fileDir] => D:...\public_html\zencart-157/includes/local/configure.php
)

> Apr 13 2020 19:30 -- checkFileExists
FAILED
(
[fileDir] => includes/local/configure.php
)

Okay, good. So it's passing properly.

The "fail" is for another check of "relative path".  Haven't checked "why" it's even doing that. 
Is the install still failing to read/use the "local" file?

Again, I don't understand why this is "new"

**Comment by drbyte** [comment]
> Why is `local` capitalized in that message? Could that be the underlying issue?

No, I thought the same. It's a hardcoded language string, intended just to make it obvious that it's using the local file. It's not a case mismatch.

**Comment by drbyte** [comment]
Does the proposed fix above resolve the issue? If not, please provide more details of what was expected vs what's actually happening in the end.

**Comment by torvista** [comment]
I tried the fix you provided, then posted the changed logs.
The result in the browser was the same: popup message then unable to proceed further as the popup comes up each time. Message text is confusing as it says problem but file will be used.
Then you commented.
Not sure what else I can provide.

**Comment by drbyte** [comment]
When did this "break"?

**Comment by torvista** [comment]
Now and again I run the installer to reset the demo products, but probably did not have a local in place until very recently as I had put no copy on a remote hosting until a week or so ago to test paypal.
So this may have been an issue for some time....but if few people have this setup, it would not come to light.
I appreciate the efforts to investigate this on a minority setup, but I maintain that a local dev server on Windows is a first step to encourage users to manage their live sites better and hopefully become modders and contributors, so I believe it is important.

I assume you cannot replicate this.

**Comment by torvista** [comment]
I tried this on remote hosting, same result with modified file. Logs were the same too.
Note that this is with two /local and two normal configure.php in place.

**Comment by scottcwilson** [comment]
This is an experts-only feature.  Are you sure you want to make changes for it now?

**Comment by drbyte** [comment]
I was able to replicate it.

Removing the code that flags the information message is harmless.

**Comment by torvista** [comment]
confirmed working :thumbsup:
