### ISSUE TITLE
SQL style, quotation marks

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3250]
What is the preferred style on the the string: single or double quotation marks?

> $db->Execute("DELETE FROM " . TABLE_PRODUCTS_OPTIONS . " WHERE products_options_id = " . (int)$option_id);

or

> $db->Execute('DELETE FROM ' . TABLE_PRODUCTS_OPTIONS . ' WHERE products_options_id = ' . (int)$option_id);

**Comment by Zen4All** [comment]
Double

**Comment by torvista** [comment]
Should be in the Developer docs, coding style.

**Comment by scottcwilson** [comment]
Single is really better - double quoted strings are checked for interpreted variables.   But this is an ultra-minor point.

**Comment by torvista** [comment]
That's what I thought (single better), IDE suggests single, by default.

**Comment by scottcwilson** [comment]
> Should be in the Developer docs, coding style.

Noted.  I'm going to get an update to that doc this month.  You can close this issue.

**Comment by scottcwilson** [comment]
Probably needs clarifications:
- for strings in general, use single quotes (at least on the outside). 
- in MySQL statements, use double quotes for consistency because sometimes variable interpolation will be used.

**Comment by drbyte** [comment]
> * in MySQL statements, use double quotes for consistency because sometimes variable interpolation will be used.

- for consistency: yes
- for variable interpolation: prefer no

I prefer to never use variable interpolation, because it obscures what's going on. It's always more clear to concatenate the strings and variables inline. That's the way you'll see the code everywhere in ZC.

**Comment by scottcwilson** [comment]
Agreed - in fact, was not a good explanation in the first place.

- in MySQL statements, use double quotes for consistency and because character values will be single quoted.
