### ISSUE TITLE
DB Create/Update Process should create Report All Errors configuration. 

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#3252]
[This](https://github.com/zencart/zencart/pull/2493) PR captured the associated code, but not the 3 configuration settings (present in **_Configuration->Logging_**).

**Comment by scottcwilson** [comment]
The three settings are in Configuration > Logging now, though, right?

**Comment by lat9** [comment]
I was looking through the code, expecting those settings to be set during zc_install and didn't see them.  They're still applied via an admin `init_include`; shouldn't they be pulled into the `zc_install` process?

**Comment by scottcwilson** [comment]
Oh ok.  Suggested retitle: DB Create/Update Process should create Report All Errors configuration.  They're not really missing.
