### ISSUE TITLE
installer: SSL all site?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3269]
I note that while the installer is run from https: and "Enable SSL for storefront" is marked by default, it defaults to the storefront as http, which is what is used in HTTP_CATALOG_SERVER
![Clipboard01](https://user-images.githubusercontent.com/4391026/79324843-807b7400-7f10-11ea-97e3-0e61521f407e.gif)
Is that still a valid default for 2020 when all sites should be https now?
I am aware of the use of HTTP_CATALOG_SERVER/HTTPS_CATALOG_SERVER and how the subsequent discussions of the settings required for SSL are confusing to users, due to legacy code.
But maybe its better to set it all https in the installer.

**Comment by drbyte** [comment]
> I note that while the installer is run from https: and "Enable SSL for storefront" is marked by default

Clarification:
- the installer DETECTS whether it https works, and will redirect TO https if it's available
- then if https is detected, the checkbox will be automatically "checked"

It is not "marked by default".

**Comment by torvista** [comment]
Ok, then if SSL is detected, are not those marked fields now redundant in respect to needing to be shown to the user?
I understand they represent two constants, but also that for sitewide SLL, they should be both set to https in configure. This would be very confusing for users at this point so another reason not to show them.
Or, unhide them if the Default is unticked?

The "issue" is that by accepting all defaults and with SSL in place, the configure ends up with http for the store instead of https.

**Comment by drbyte** [comment]
I suppose we could change all those http to https if SSL is enabled. And we could hide/show things dynamically.

But that's all a bandage, and is masking things that they'll suddenly "see" again in the configure.php file if they go to edit it. At least here they can click to see a description.

But ... maybe there's an even better option: remove these fields from display.
ie: who EVER edits these fields? (I never do nowadays.)  Is server technology finally at the place where we can completely SKIP all these domain/url input fields? (ie: just auto-detect and save them to configure.php)
Are you (generic "y'all")  prepared to answer forum questions for users that "would have" had these fields available but now don't, if we remove them?

**Comment by scottcwilson** [comment]
I'd say keep them, but make them show https as a reassurance to the storeowner of what the URLs will look like.  I think my change did that if you want to re-open it.
