### ISSUE TITLE
Remove PHP7+ syntax?

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3275]
We are saying 1.5.7 can be used under PHP 5.6, but there are a couple of PHP7+ syntax statements.

admin/includes/functions/general.php line 2964 (zen_get_master_categories_pulldown declaration uses int hint).
admin/categories.php line 395 uses [] list unpacking.

**Comment by mc12345678** [comment]
I was just about to start an issue about the use of parameter type hinting such as in `zen_get_master_categories_pulldown` and if parameter type hinting was going to make it into this version or not...

**Comment by scottcwilson** [comment]
I don't think so - if you see the conversation in #3134 @drbyte is keen to to ensure the software continues to work in PHP5.6 to make life easier for upgraders.

**Comment by torvista** [comment]
I've removed that int:
https://github.com/zencart/zencart/pull/3283

**Comment by scottcwilson** [comment]
Looks like we still need to fix 
admin/categories.php line 395 uses [] list unpacking.
@torvista will you do?
