### ISSUE TITLE
Unreachable code in admin side zen_get_all_get_params() 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3276]
admin/includes/functions/general.php line 93 is below a continue. 

This has been there since at least 1.5.4 so it's not urgent but should be cleaned up at some point.

**Comment by torvista** [comment]
`} else {
            continue; // legacy code doesn't support passing arrays by GET, so skipping any arrays
            foreach(array_filter($value) as $arr){
              $get_url .= zen_output_string_protected($key) . '[]=' . rawurlencode(stripslashes($arr)) . '&';
            }`

I take this to mean that the continue would be removed at some point allowing the next clause to be used.
