### ISSUE TITLE
installer php notices  Trying to access array offset on value of type bool in class.systemChecker.php

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3277]
Initial page load. Using file from PR today.

> PHP Notice:  Trying to access array offset on value of type bool in D:\....\zencart-157\zc_install\includes\classes\class.systemChecker.php on line 669
> PHP Notice:  Trying to access array offset on value of type bool in D:\....\zencart-157\zc_install\includes\classes\class.systemChecker.php on line 669
> PHP Notice:  Trying to access array offset on value of type bool in D:\....\zencart-157\zc_install\includes\classes\class.systemChecker.php on line 674

**Comment by drbyte** [comment]
Those are while trying to check for latest version.
Why is it getting no response? Are you offline when that happens? Is version-checking working in the Admin?

**Comment by torvista** [comment]
Its the usual Xampp. Version check works in the admin.
I took the @ off the file request and this is what appears in the debug:

> [15-Apr-2020 19:51:57 Europe/Madrid] PHP Warning:  file(http://ping.zen-cart.com/version_id.txt?v=1.5.7-alpha&amp;p=7.4.4&amp;a=Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.4.4&amp;r=www.dev.test&amp;m=zc_install): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
