### ISSUE TITLE
control of ADMIN_CONFIGURATION_KEY_ON

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3293]
This switch is in group 6, hidden. When set to 1 it causes the configuration_key name to be displayed:
![Clipboard03](https://user-images.githubusercontent.com/4391026/79507794-a00dbc00-8038-11ea-9405-942e953092a5.gif)
I think it is very useful and I think undocumented.
Could the switch for this not be put in the Developers Tool Kit?

**Comment by scottcwilson** [comment]
Note that the keys are also documented in the docs:
https://docs.zen-cart.com/user/admin_pages/configuration/all/

**Comment by torvista** [comment]
If I wanted to know a constant name I'd search in the db for the strings, if I didn't know about ADMIN_CONFIGURATION_KEY_ON, 
which is infinitely faster if you want to build some queries quickly, as I was yesterday.

I understand that list is for building the help on, but has to be maintained.

**Comment by scottcwilson** [comment]
I'm open to this idea - just wanted to clarify on one point:

> I understand that list is for building the help on, but has to be maintained.
The help is automatically generated by a script.  It doesn't need manual maintenance.

**Comment by scottcwilson** [comment]
Also thinking about config page 6 got me inspired to improve that page, so thanks for that.

**Comment by wiztechinc** [comment]
ah, I couldn't find the other discussion about the help where you had asked me a question. The docs appear to have a way to edit them, supposedly expanding the info which is definitely needed. I like this approach using it in admin now but is this temporary for the help buttons?

**Comment by scottcwilson** [comment]
> The docs appear to have a way to edit them, supposedly expanding the info which is definitely needed.

Not sure why you're saying this so tentatively.  If you want to change the documentation, you submit a PR.  

>  I like this approach using it in admin now but is this temporary for the help buttons?

I don't understand what you're asking here.   If you're unhappy about the buttons, please submit a PR.   If you're asking a different question, please rephrase it.

**Comment by wiztechinc** [comment]
You keep saying doc info is generated automatically by a script. Will the script need to be run  again if changes occur? Does the script create the pages? If we edit the docs.zencart, does that make a permanent change that will not be overwritten by running the script again? I can definitely get started adding info into the docs. I just need clarity here. I never saw any discussion about creating this new set of docs so I'm just trying to figure out what's going on.

**Comment by scottcwilson** [comment]
Please read the CONTRIBUTING and README files in the documentation repo. 

If you have more questions, open a separate issue.

**Comment by wiztechinc** [comment]
not helpful at all. I give up.

**Comment by drbyte** [comment]
> not helpful at all. I give up.

Fair point.

Granted, this discussion is completely off-topic for the Issue in which it was started.



> You keep saying doc info is generated automatically by a script. Will the script need to be run again if changes occur? 

Yes.

> Does the script create the pages? 

Yes

> If we edit the docs.zencart, does that make a permanent change that will not be overwritten by running the script again? 

No. 
Manual intervention would be required before merging what the script generates, to make sure the new generated content doesn't overwrite added extra content has been contributed.

**Comment by drbyte** [comment]
I've moved the "generated content" discussion to a new issue: 
https://github.com/zencart/documentation/issues/191

**Comment by wiztechinc** [comment]
thank you

**Comment by scottcwilson** [comment]
The use of the ADMIN_CONFIGURATION_KEY_ON flag is now documented on https://docs.zen-cart.com/dev/developer_environment/
