### ISSUE TITLE
Bug admin, orders. Click on order listing does not update infobox

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3304]
as per subject.

**Comment by scottcwilson** [comment]
Consequence of PR #3247.

**Comment by scottcwilson** [comment]
One possible solution would be to put the bubble over at the right, and make that clickable, but then have the rest of the row, from there over to the order id on the  left, be clickable to select the order.

**Comment by scottcwilson** [comment]
@drbyte @Zen4All This should really be fixed before 1.5.7 is released.

**Comment by drbyte** [comment]
Is this "click on the row" important only because of historical muscle-memory? 
Or other reasons?

**Comment by scottcwilson** [comment]
How else do you select a particular order to see the summary in the sidebox?

**Comment by drbyte** [comment]
> How else do you select a particular order to see the summary in the sidebox?

Button Bar:
<img width="82" alt="Screen Shot 2020-04-29 at 2 47 39 PM" src="https://user-images.githubusercontent.com/404472/80634397-6ff6ed80-8a28-11ea-9881-af20f2b78da0.png">

**Comment by scottcwilson** [comment]
From an accessibility perspective, don't you think it's better to be able to click the whole row?  Also, this is not backwards compatible.

**Comment by drbyte** [comment]
This is the same change that was made to the Categories/Products admin pages in 1.5.6

**Comment by scottcwilson** [comment]
a) I didn't like this either
b) The product name is a much larger target than the (e) icon.

**Comment by drbyte** [comment]
> a) I didn't like this either

Me too.

I'd rather the row was clickable.

But I totally hate the injected JS for "onclick", mostly because it's ugly HTML.

But, we use it all over the place.

@Zen4All did you ever find a way to make the row clickable when we add other clickable elements onto the row as well? (ie: button bar, popover, etc)

**Comment by Zen4All** [comment]
> @Zen4All did you ever find a way to make the row clickable when we add other clickable elements onto the row as well? (ie: button bar, popover, etc)
Other then putting a link in every cell of the row no. :disappointed: , but I can do some searching again.

**Comment by torvista** [comment]
> This is the same change that was made to the Categories/Products admin pages in 1.5.6

But the category/product listing is a listing with no infobox.

For orders we update status and send emails from the infobox and never enter into the order details.
If this does not get fixed/reverted in vanilla code, I'll certainly be reverting it personally.

**Comment by scottcwilson** [comment]
BTW others complained about the categories/products change - see #2724. 

Possibly crazy idea but just hear me out: make the order id a button so it's bigger and easier to click.  Then make that the link.   Thoughts?

**Comment by scottcwilson** [comment]
Possible implementation provided.

**Comment by lat9** [comment]
Here's an approach similar to that that I've used for a custom report.

Start by adding an `id=` tag to the orders' _listing_ table so that it's specifically identifiable:

```php
        <div class="row"><?php echo TEXT_LEGEND . ' ' . zen_image(DIR_WS_IMAGES . 'icon_status_red.gif', TEXT_BILLING_SHIPPING_MISMATCH, 10, 10) . ' ' . TEXT_BILLING_SHIPPING_MISMATCH . $extra_legends; ?></div>
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9 configurationColumnLeft">
            <table id="order-table" class="table table-hover">
              <thead>
                <tr class="dataTableHeadingRow">
                    <?php
```

Then, use a `data-*` type attribute on each listing row to identify the current order's ID:

```php

                    if (isset($oInfo) && is_object($oInfo) && ($orders->fields['orders_id'] == $oInfo->orders_id)) {
                      echo '<tr id="defaultSelected" class="dataTableRowSelected" data-oid="' . $orders->fields['orders_id'] . '">' . "\n";
                    } else {
                      echo '<tr class="dataTableRow data-oid="' . $orders->fields['orders_id'] . '">' . "\n";
                    }
```

Finally, add some jQuery at the bottom of the page to handle the redirect.  Note that the last column of each row (the 'Action' column) is excluded from the redirect-handling:

```
// -----
// Script to process clicks to reduce generated HTML.
//
?>
<script defer>
<?php
$edit_link = zen_href_link(FILENAME_ORDERS, zen_get_all_get_params(array('oID', 'action')) . "oID=[*]&action=edit");
?>
$("#order-table .dataTableRow > td").not(':last-child').on('click', (function() {
    var link = '<?php echo $edit_link; ?>';
    window.location.href = link.replace('[*]', $(this).parent().attr('data-oid'));
}));
</script>
```

**Comment by scottcwilson** [comment]
Second possible implementation provided.

**Comment by scottcwilson** [comment]
Whatever we decide, I'd like it to be used on the Categories/Products page too.  I find it maddening to click a row and not have anything happen.

**Comment by scottcwilson** [comment]
I encourage anyone who is skeptical about this bug report to try navigating the orders screen on a phone.  Amazingly painful!  My vote would either be to restore the old code or use Cindy's solution. 

Once this is fixed we should take a hard look at the orders list and see what columns could reasonably be hidden on a phone (a la #3393) to make this screen easier to use.
