### ISSUE TITLE
admin page structure bootstrap

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3310]
Can someone confirm what it should be?
I assume it is the first example, I've seen both.

```
body tag
require header
  <div class="container-fluid">
    content
  </div>
require footer
body tag close
```

or

```
body tag
 <div class="container-fluid">
require header
    content
  </div>
require footer
body tag close
```

**Comment by Zen4All** [comment]
It is #1 for me. That is how I structured all the pages.
putting the header (dropdown menu) in side the container complicates the resizing

**Comment by drbyte** [comment]
Both examples above leave out the location of html_head

```
head
require admin_html_head
any page-specific extras
/head
body tag
require header
  <div class="container-fluid">
    content
  </div>
require footer
body tag close
```

**Comment by drbyte** [comment]
The `fluid` part of `container-fluid` may not be required on all pages. Depends how wide the content is and what the intention is on mobile sized viewports.

**Comment by drbyte** [comment]
If a page needs the header to be wrapped inside a resizable container div, then probably the footer should be inside that same div.

So, question: are there legitimate cases for occasionally pushing the header/footer inside the body container div?

**Comment by torvista** [comment]
apparently not.
