### ISSUE TITLE
PRE-RELEASE refresh install and upgrade guides in docs

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3316]
Per #3311 for the following files: 
docs/readme_installation.html
docs/readme_how_to_upgrade.html
docs/important_site_security_recommendations.html

do the following in mid May before release: 
- refresh the content on these pages from docs site 
- add a link at the top of these pages pointing to latest content on docs.zen-cart.com

**Comment by torvista** [comment]
What is the intended release date or thereabouts?

**Comment by scottcwilson** [comment]
Target date is 5/17.

**Comment by scottcwilson** [comment]
Closing this issue - PR can be tweaked or merged at will.
