### ISSUE TITLE
Replace Language Icons with letters instead of Country Flags

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3335]
> I've put out a request for copyright approval for us to distribute an updated icon, but haven't heard back. Maybe I'll have to find another source. Maybe country flags are the wrong indicator. Maybe font-awesome instead.

What about these
https://flagicons.lipis.dev/

Can't we put all the en-related icons in the distribution to keep everyone happy?

**Comment by scottcwilson** [comment]
Restore the UK image from 1.5.5 as icon.gif and add individual images for Canada, USA and NZ.  People who really want their own flag to show can then modify the associated image for their language in Admin > Localization > Languages.

**Comment by wiztechinc** [comment]
Just another headache Scott. no icons are preferrable to multiple for one language.

**Comment by Zen4All** [comment]
I prefer the icons, above text, but it is easier/quicker to see IMHO

yesterday I cam across this interesting github repo, which makes use of css flags instead of images:
https://github.com/lipis/flag-icon-css

**Comment by scottcwilson** [comment]
> Just another headache Scott. no icons are preferrable to multiple for one language.

No action is required if you are happy with the UK flag.

**Comment by wiztechinc** [comment]
It then sometimes triggers the US client who thinks it's unpatriotric. That just irritates me. I would prefer to avoid having to manually make the change or have the same dang conversation of - no one besides you sees the stupid icon.

**Comment by torvista** [comment]
This is the answer:
>People who really want their own flag to show can then modify the associated image for their language in Admin > Localization > Languages.

And as for the default icon...I have no idea (but would like to know) the geographic distribution of ZC users.

**Comment by scottcwilson** [comment]
Can we ship the other flags to make this an easy change?  Perhaps from the link you posted?  Then I'll just post a FAQ on how to do this.

**Comment by wiztechinc** [comment]
actually I don't like that. It's been better for me to tell my clients to deal with it. Now you can be adding in another idiot task for me to do when it's so highly unimportant and I say again - using flags to designate language was never a good idea to begin with. The icons are highly distracting and not useful- especially in a one language cart. In all the years I've worked in zencart I have only worked with 2 multi language carts. Most of my clients are US or Canadian based but have worked with brits and aussies in the past. I have no idea what the distribution of use is worldwide but really there's could easily be more US because of the higher population of the country.  

So prefer no icon if it's a one language cart - that will solve all my problems.

**Comment by scottcwilson** [comment]
A complete set of flags would also let us display shipping destination flag on the orders page which would be quite convenient for stores that do a lot of cross border trade.

**Comment by drbyte** [comment]
The `lipis` images that @torvista and @Zen4All mentioned work very well, save for the fact that they're all (appropriately) identified by country and not by any associated language code, so using them for language purposes would require some architectural changes. 

But if they're to be included in Zen Cart then there's an added wrinkle in that the assets would need to be available in both catalog and admin, and that can get ugly when it comes to asset files like this.
Is there a CDN-hosted set of flags that could be used instead? That would simplify this sharing between admin/catalog.

**Comment by scottcwilson** [comment]
Why don't we mark this a 1.5.8 feature and table it for now since more thought is required.  I think it could be powerful, it's just more complicated than it initially appears.

**Comment by drbyte** [comment]
Meh. Maybe not.

**Comment by torvista** [comment]
I think this issue has taken on a life of it's own in the sense that it's a solution looking for a problem to solve. None of this is on any users wishlist. 
My opinion is that the current image be replaced with a single one. That is fixing an actual problem/mistake.

I think the icon/language indicator should be hidden for single-language shops. But in a single PR long in the future if agreed. Keep it on show for now to be consistent.

**Comment by scottcwilson** [comment]
> None of this is on any users wishlist.
Agreed.  Closing.

**Comment by proseLA** [comment]
> I think the icon/language indicator should be hidden for single-language shops. 

this is an idea that i like...

**Comment by g2ktcf** [comment]
> I think the icon/language indicator should be hidden for single-language shops.

I agree that this is a good thing.  However, this can be done via the template right?
