### ISSUE TITLE
Installer new version links

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3336]
This message is two concatenated links.
The first redirects to Sourceforge, the second to Zen Cart, which then goes to Sourceforge. Doesn't look right to me...
![Clipboard05](https://user-images.githubusercontent.com/4391026/80110543-15b8e100-857f-11ea-903c-42fa90c94e58.gif)

**Comment by scottcwilson** [comment]
There's the `getit` link and the `latest` link - it would be good if we could standardize on one of these.
