### ISSUE TITLE
boolean v string in configuration

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#3337]
after burning a bunch of time, i realized all config values in the configuration table are strings.  has there ever been any though of converting them when reading them and making them available for use?  something like:
```php
function convert_to_boolean($value)
{
    if (in_array($value, array('True', 'TRUE', 'true'))) {
        $value = true;
    }
    if (in_array($value, array('False', 'FALSE', 'false'))) {
        $value = false;
    }
    return $value;
}
```
i think string comparisons to true or false get to be confusing.  and frankly i think:

```php
if (DISPLAY_CART)
```
is much cleaner than:
```php
if (DISPLAY_CART == 'true')
```
thoughts?  (other than the obvious PAIN it will inflict for converting all of the existing code and plugins.)

**Comment by scottcwilson** [comment]
Remember that the schema is online for easy access.  If you're in doubt about a field, you can just look it up. 

https://docs.zen-cart.com/dev/schema/schema_156/

**Comment by proseLA** [comment]
the schema has little to do with the issue i am bringing up.  in fact, if you look at the code, the schema would be wrong for configuration groups 2 or 3, as `is_int` would be false on the key read directly from the table, but true on the constants provided by the core which is based on the same table.  see:
https://github.com/zencart/zencart/blob/b710725c5352cfdb4cc9114d3926739a2d3333e1/includes/init_includes/init_db_config_read.php#L24-L28

i would further state that the constant `UPLOAD_FILENAME_EXTENSIONS` looks to be part of config group 3, so that looks to be a bug to me.  as casting it to an integer gives a value of `0`.   so i'm not really sure how that would work.  unless the sample data is wrong for v156c.

**Comment by scottcwilson** [comment]
I only mentioned the schema because you said it took you a bunch of time to figure out that the config values were strings. Looking at the schema quickly shows you that they are strings.

The schema is never "wrong" - not sure what you mean by that.  The logic you are excerpting there forces the values 2 and 3 to ints because bad guys were attacking one of these values and putting in JS code.  Yes it falls over for the filename extensions.  That's why if you look at 1.5.7, this stuff was replaced using the PHP filter_var validation.

**Comment by drbyte** [comment]
> has there ever been any thought of converting them when reading them and making them available for use?

Yes, there have been such thoughts ... if only for the value of consistency and semantic meaning. 
But never implemented.

> (other than the obvious PAIN it will inflict for converting all of the existing code and plugins.)

Yes such a migration is a massive pain. 
And some would say it makes it nightmarish for people upgrading.

And doing such an overhaul might be better handled via a rewritten approach to configuration settings.

**Comment by proseLA** [comment]
> ***Later: OK, I think I see what you mean - you're saying looking at the schema and concluding that all config values were strings would be an error because the MIN/MAX values are forced to int. That's true as of 1.5.6c only - in 1.5.6b, all values were still strings.
> 
> But your recommended change - to cast these boolean type strings to boolean in the same way - is unlikely to be adopted, given that it would break all existing code, templates and mods.

- glad that you are understanding what i am saying.
- i really only look at the latest released code, and the future version.  i rarely go back to prior versions except when looking at when a specific line or code block was changed. (or helping someone with an older version...)
- a massive pain...  i get it... 

>And doing such an overhaul might be better handled via a rewritten approach to configuration settings.
- yes.  storing functions in the database always seemed a little unusual to me...
