### ISSUE TITLE
Port things from V2/Develop?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3344]
Are there aspects of this that could be listed, in the sense of "this has been started/already done etc." with a view to either guiding someone wishing to implement the same or avoiding reinventing the wheel, and/or as suggestions for back porting to the current branch?

**Comment by scottcwilson** [comment]
Things DONE:
Default Attribute 
https://github.com/zencart/zencart/pull/1087

Things I'd like to do in the future:
System inspection
https://github.com/zencart/zencart/pull/1100

Find Dup Models
https://github.com/zencart/zencart/pull/1069

**Comment by scottcwilson** [comment]
Also @drbyte is considering backporting the merge of admin/includes/functions and includes/functions which was done in 2.0.

**Comment by scottcwilson** [comment]
Also some items from the \ZenCart namespace, such as how admin URLs are built now (`/admin/index.php?cmd=customers` vs the old `/admin/customers.php`)

**Comment by drbyte** [comment]
> Are there aspects of this that could be listed, in the sense of "this has been started/already done etc." with a view to either guiding someone wishing to implement the same or avoiding reinventing the wheel, and/or as suggestions for back porting to the current branch?

Do you mean "What are all the features of v2, that would make people want to migrate?"
And then "how can we bring all those back into v1.5x"?

**Comment by scottcwilson** [comment]
Some documentation was captured here: 
https://github.com/zencart/zencart/blob/develop/docs/whatsnew_2.0.md

**Comment by torvista** [comment]
> Do you mean "What are all the features of v2, that would make people want to migrate?"
No, I was meaning "if you are thinking of fixing/changing xxx, this was done/started in v2 so use that as a basis."

Unfortunately, I feel the "what will make people migrate" discussion gets repeated but never gets followed through, to define concrete conclusions/goals on a public roadmap. So the input from us on the outside of the core team will continue to be ad-hoc, instead of making a contribution to real forward progress, whatever that is!

**Comment by scottcwilson** [comment]
Also backported from 2.0 was the ability to process query results using `foreach`.  Much more intuitive for developers.

**Comment by zcwilt** [comment]
> Unfortunately, I feel the "what will make people migrate" discussion gets repeated but never gets followed through, to define concrete conclusions/goals on a public roadmap. So the input from us on the outside of the core team will continue to be ad-hoc, instead of making a contribution to real forward progress, whatever that is!

I'm disappointed that you feel that way. In v157 most of the `progress` is based on contributions from people outside the core team, and in general we probably accept at least 95% of those PR's.

 I would agree that we don't have a good public roadmap. Is there a better way of doing this. 

The roadmap needs to be community driven, although of course eventually decided by core team, but there tends to be only a few voices here, and those voices can be very opinionated and very diverse.

It's obvious now that the v2/develop experiment failed, and we don't want to go down that route again. The hours of developer time could have been better spent. (note this is not blaming others, it was our choice to do that) 

Any ideas you or others have will be listened to.

**Comment by scottcwilson** [comment]
Suggested path forward:
- After 1.5.7 is delivered, open a new thread on the forum asking "What would you like in 1.5.8."
- Timebox the thread: "This thread will only be open for 30 days" (or whatever).
- Once the timebox is up, close the thread, get the decision makers together, hash out a position and publish it.  I would timebox this phase to (say) 3 days.

**Comment by torvista** [comment]
No, no, no, not again. It will die a death. Again.
I’ve been mulling this over, for years. And overnight. Now with my advanced age (55) I’m allowed the attendant lack of patience and grumpiness. So here we go.

It all boils down to where to you want the project to be.
Until that is clear, all these bun fights of “what do people want” are just pointless.
I thought, Prestashop or Magento killer?

So I found and read this, all four parts of it
https://build.prestashop.com/news/prestashop-in-2019-and-beyond-part-1-current-architecture/
Time well spent, made me realise I know nothing about current software development/platforms.
I also read these
https://www.joelonsoftware.com/2000/04/06/things-you-should-never-do-part-i/
https://www.joelonsoftware.com/2000/08/09/the-joel-test-12-steps-to-better-code/

So, I’ll reiterate, if you have no defined end-point, how can you get there?

How can you measure progress?
How can you hit milestones and plan releases?
And how can you get those willing to invest their time in contributing, to do so in a constructive manner and not (like me) come up with a huge code change that takes ages to review, for something that wasn’t broken in the first place?
Or wasting time tinkering with something that is going to be refactored completely?
How can you assign people/allow people to take ownership of a change and avoid people working on the same thing at the same time?
All these things are unmanaged because there is no public plan.

I’ve said before that the concept must be “get new users keep current ones”: if you want people to use ZC instead of something else, you have to look at the competition and make a plan based on that.

The project desperately needs to up the number of contributors.
In the last year only seven people have made more than 10 commits. How does that compare to the user base?

There is a flurry of activity here, but on the forum where most people are, who would know?
From 2007 when I joined the forum, to date, the communication on the plan has improved from zero to very poor. Any discussion such as this would be roundly ignored and so gave a high-handed impression (whether true or not) of “we know better, so we don’t waste time on answering”.

While support was/is always exceptional, the encouragement/interchange of ideas/suggestions with the user base has been dismal. As a result (I opine) it’s no wonder there are so few contributors.

I think you realised at some point you could not progress without accepting help from outside and finally opened up on Github, grudgingly, to allow the great unwashed to taint the pristine code ideals with their grubby, amateur efforts. It took me a very long time to get enough confidence in what I was doing or rather to stop caring so much, to offer anything. I now figure something is always better than nothing, that’s what peer review is for.

I think you need to suggest (i.e. be clear it is something that can evolve with user input), a plan based mainly on the functionality of the competition. The platform the underlying code is based on /how to migrate gradually, is out of the user remit/a core team decision.

There must be no-end of collaborative tools out there to allow you to subsequently invite current users to add their concerns, collating, evaluating and dismissing/incorporating into the plan.
But with communication: an ignored wishlist on the forum serves only to reinforce the impression of disconnection with the users.
These threads are no good/not appropriate, they just peter out with nothing to show for the hours wasted in replies. These threads should be for "issues", not strategic discussions.

I think if a current ZC user needs something so bad, they should pay for it/be able to get other users to jointly pay/ to get it made.
If they want a plugin in the core, make it clear they can/no-one is stopping them from adding it.
There is too much of users thinking everything is always for free.

Users need to be converted into contributors.
Unfortunately this requires a real effort in expanding the explanation of setting up a dev environment and Github process for newbies down to real Noddy-level step-by-step (I hate that, but it IS needed, to save time for non-developers/business-people) tutorial, but with the real-world details from real developer experience showing why THIS is the best way (because of a, b, c...). Make it stupid easy and the accepted norm that users must contribute.
Recently there was a detailed post of how a dev uses Github that I am still trying to find time to understand..no doubt there is a damned good reason why that process works, and that should be documented. I just found out about DEVELOPER_MODE by accident. After 13 years!!

You have to remove all the obstacles and get the idea into users heads that ZC is not just about community **support** (from the same 7 people), but community **development**.
All users have invested a great deal of time in their shop.
They want it to get better.
They do not want to move to another solution unless they feel forced/ZC is so far behind the curve they must move on.
If they are encouraged to get involved and they can see that their comments and input is taken into account, whether acted upon or not, why on earth would they move?

Communication is everything…but NOT just on GIthub.

**Comment by scottcwilson** [comment]
I actually agree with you that a holistic, end-state focused plan would be best.  I just think it's not practical.  The project is thinly resourced and people are busy with making a living and other commitments.  

However, short term planning and execution is something that contributors *could* manage.   That's why I am suggesting it as a way forward.

**Comment by torvista** [comment]
Even if not practical, it's existence would maybe incentivise more people to invest their time in it as a project with a future?

**Comment by scottcwilson** [comment]
Can this issue be closed?
