### ISSUE TITLE
Order List button should always be available when scrolling through orders

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3353]
In Admin when you have more than a couple of orders, press Details on the first one.  You'll see the pagination widget that looks like this, including the Order List button

<img width="497" alt="order_list_1" src="https://user-images.githubusercontent.com/4391638/80321153-e60d1180-87e8-11ea-9ed2-a4a14916ace9.png">

But if you go back an order, you'll see the next and previous order buttons, but no Order List.

<img width="540" alt="order_list_2" src="https://user-images.githubusercontent.com/4391638/80321179-10f76580-87e9-11ea-8938-c86cef0cf2d1.png">

Shouldn't Order List be there all the time?

**Comment by lankeeyankee** [comment]
You would think so

**Comment by drbyte** [comment]
I believe the original implementation was following what Super Orders had done.
