### ISSUE TITLE
157 admin squeezed and smaller in mobile

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3366]
See 2 screenshots - 1.5.6 and 1.5.7.   Both are iPhone 6/7/8 in Chrome simulator. 

1.5.6 admin on iPhone 
<img width="416" alt="admin_iphone_156" src="https://user-images.githubusercontent.com/4391638/80602487-31980900-89fd-11ea-9638-ce7556c9c147.png">

1.5.7 admin on iPhone
<img width="431" alt="admin_iphone_157" src="https://user-images.githubusercontent.com/4391638/80602493-33fa6300-89fd-11ea-8ff6-774638cc578f.png">

**Comment by Zen4All** [comment]
I think the order line table is wrapping less for some reason.

**Comment by scottcwilson** [comment]
But even the Orders button at the top is smaller.  It's like everything is shrunk down.

**Comment by Zen4All** [comment]
Yes, that something I think bootstrap does. I first renders the menu/page in the correct width, then discovers there is a table that is wider than the screen. Next Bootstrap shrinks (zoom out) the whole layout.
One solution would be to wrap the table in a div with the class "table-responsive"

**Comment by scottcwilson** [comment]
Well, this issue seems to have gone away, probably because of #3340.  But it may still be a problem for tax included stores.   Closing for now.

**Comment by scottcwilson** [comment]
Related: #3393

**Comment by scottcwilson** [comment]
I think this is related to using the simulator in Chome.  If you get a squeezed screen after switching device to a phone, go to the hamburger menu and reselect the screen from the menu; it looks ok after that.
