### ISSUE TITLE
CKEditor - does not appear in text editor dropdown list 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3371]
Specifically, lists in Admin > Configuration > My Store > HTML Editor and Admin > Catalog > Categories/Products. 

Related - #3289

**Comment by drbyte** [comment]
Fresh install just now. Works for me.

<img width="494" alt="Screen Shot 2020-04-29 at 2 10 54 PM" src="https://user-images.githubusercontent.com/404472/80631178-599a6300-8a23-11ea-9a92-fd19e5eeed93.png">
<img width="1027" alt="Screen Shot 2020-04-29 at 2 11 12 PM" src="https://user-images.githubusercontent.com/404472/80631187-5dc68080-8a23-11ea-8c07-ca639c1f3b44.png">

**Comment by scottcwilson** [comment]
Ugh.  I swear this wasn't working, and now it is. :( 

Closing.
