### ISSUE TITLE
Send order status emails in order language

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3375]
I did my own work to implement this ages ago and was revisiting it today to use the new field in the ZC157 database, with the idea of presenting it asap, since things seem to be hotting up.
However, I don't consider my old workaround adequate for core code.

I note that work was done on 1.6/develop to enable this and was intending to look over that to port it over to my site/ZC157. Possibly too late now but since Zen4all did it, perhaps he can orientate me if it's feasible now or requires 1.6 structure/too different to be easily done?

**Comment by scottcwilson** [comment]
I believe this is the relevant PR.  #1058

**Comment by torvista** [comment]
Yes that was it.

**Comment by scottcwilson** [comment]
This should be a 1.5.8 change, so there's no rush.

**Comment by torvista** [comment]
added by 
https://github.com/zencart/zencart/pull/3399
