### ISSUE TITLE
github "develop" branch: fix/report fatal bugs?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3380]
While perusing zencart-develop code for inspiration, I've come across a fatal error, easily fixed.
Should this codeset be considered as-is/not to be bothered with at all, or we should still push PRs for breaking/fatal errors in the interests of keeping this working for future reference?

**Comment by drbyte** [comment]
What is it?

**Comment by torvista** [comment]
Lots of Call to undefined function zen_black_line() in admin\options_name_manager.php:587

**Comment by drbyte** [comment]
And is your fix to add the function? or remove the calls? Or something else?

The branch is effectively frozen, and not production-ready at all, so we'd rather not start a ton of PRs to it.  

That said, if there's just a single tiny fix to be done, zcwilt might allow it. Hence the questions to understand what you're after.

**Comment by torvista** [comment]
The error is in three files only, I'd replace with all with hr.

I was investigating how the process works to send order status emails in the order language, since I am updating my site to use the new field in ZC157 and thought I would look at incorporating this "approved" process and subsequently PR it to 158.
I have a language pack for develop which I did two years ago and have updated today for this testing (equalised constants, not translated).

I note now that there is another more relevant error (to me) in that with the addition of the langauge pack, the duplicated product/category fields do not get auto-populated.

Otherwise navigating through the admin there are a dozen or so warnings about constants. Easily fixed I imagine.
Catalog complains on all pages about undefined constant DIR_FS_ADMIN, and there are a few other notices, but not much really.
Note this is on php 7.4.5 (I upped the systemCheck max).

**Comment by drbyte** [comment]
> Otherwise navigating through the admin there are a dozen or so warnings about constants. Easily fixed I imagine.
> Catalog complains on all pages about undefined constant DIR_FS_ADMIN, and there are a few other notices, but not much really.

Ignore those in the `develop` branch.

**Comment by drbyte** [comment]
> The error is in three files only, I'd replace with all with hr.

@zcwilt Do you want a PR for this? Or just leave as-is for now?

**Comment by zcwilt** [comment]
It's my opinion that the `develop` branch should be orphaned. 

All of the feedback we got, was that having a branch that diverged so much from current code was too much, and I do understand that position.

Some ideas from `develop` are being incorporated into main line code. e.g. controller files in admin
and I expect us to do more of this as smaller encapsulated changes going forward in v158 etc. 

If there is a particular change in `develop` you want to see going forward, then please open an issue or pr.

**Comment by zcwilt** [comment]
I'm also mindful that it would help to have a better roadmap and we can hopefully address that soon.

**Comment by scottcwilson** [comment]
Can this ticket be closed?
