### ISSUE TITLE
default for ezpages creation - open new window

### ISSUE THREAD

**Issue by wiztechinc** [zencart/zencart#3389]
I don't know why this was changed to open a new window as default but two carts in two days has proven to me that this is just not the way I want it to happen. I rarely ever put exterior pages into ezpages but use the header and footer links to existing zen cart pages which in general never should be a separate window. As this is a tiny change (though I recognize that someone wanted it this way and may argue with me), is it possible to get this taken care of now or am I gonna have to alter the dang code myself so that I don't go crazy for the next year or more?

**Comment by drbyte** [comment]
To make the change on your sites, here's where the code is:
https://github.com/zencart/zencart/blob/22424cedd39d8b4b8496438507f8a897881e0644/admin/ezpages.php#L266-L285

**Comment by wiztechinc** [comment]
Thank you. This really needs changing if there was no discussion before that did this. Later.....

**Comment by scottcwilson** [comment]
Here's the commit.  

https://github.com/zencart/zencart/commit/59e9db98baa784083c4aff3c64b3d2033c5d4f3b#diff-5d1c97c1eadd6b2f2c01b278f6aaa642

I think I'm neutral on this but I would like the visibility default to be 1.

**Comment by scottcwilson** [comment]
Possible resolution: add configuration values to Admin > Configuration > EZ-Pages Settings and allow people to set their own defaults for new page, visible, etc.

**Comment by wiztechinc** [comment]
That certainly works for me

**Comment by scottcwilson** [comment]
Configuration haters be hatin'.

**Comment by wiztechinc** [comment]
> Configuration haters be hatin'.

That's coming...
