### ISSUE TITLE
font-awesome control not in admin/includes/stylesheet.css

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#3398]
In moving most of the info from the stylesheet to the new admin_html_head.php, we lost the settings from line 633 to 688 that control the colors for the admin.
Biggest offender is not having line 669 which results in all the overlays to be the same color as the base.

**Comment by Zen4All** [comment]
Are you sure you are using the correct/clean version of the admin/includes/css/stylesheet.css, because the lines you mention make no sense.

I suspect you mean the overlay in the product listing? I jus t looked, and see the colors just fine.

**Comment by dbltoe** [comment]
yes, the lines are from the 1.5.6c version of stylesheet.css that were stripped when admin_html_head.php was implemented.

**Comment by Zen4All** [comment]
Sorry, but I have no clue what you are trying to explain me.
no lines were stripped from the file
There are some layout changes between ZC1.5.6 and ZC1.5.7.
Can you tell me which page you are seeing this, and maybe make a screenshot (would be very helpful)?

**Comment by dbltoe** [comment]
When the 1.5.6c version of admin/includes/stylesheet.css was sanitized to move much of the styling into 1.5.7's new admin_html_head.php, the calls for font-awesome icons (lines 633-688 of the 1.5.6c stylesheet) were not incorporated in the new admin_html_head.php nor left in the stylesheet.css for 1.5.7.
Without those, the standard ZC color scheme for admin font-awesome icons is not set.
The result is such that the icons are the wrong color (they default to the current a font color) and overlays are often the same color as the circle underneath.
It's like trying to see the rhinoceros in the image on Facebook.

**Comment by barco57** [comment]
John, what you saying doesn't nake a lot of sense.
In 1.5.6c the code that includes the overlay on the move is as follows
`<div class="fa-stack fa-lg move">
                          <i class="fa fa-circle fa-stack-2x base"></i>
                          <i class="fa fa-stack-1x overlay" aria-hidden="true"><strong>M</strong></i>
                        </div>`
in 1.5.7 the code for move is now
`<a href="URL_HERE" class="btn btn-sm btn-default btn-move" role="button" title="Move"><strong>M</strong></a>`
As you can see the overlay has been completely removed so there is no longer any need for the css for the overlays.

**Comment by barco57** [comment]
> and overlays are often the same color as the **circle** underneath.

That tells me a lot

1.5.6 category product listing
![category_product_listing_php156](https://user-images.githubusercontent.com/1237035/80896410-34bc1f00-8cb3-11ea-93ee-d08055f21255.png)
1.5.7 category product listing
![category_product_listing157](https://user-images.githubusercontent.com/1237035/80896419-443b6800-8cb3-11ea-8c63-f53bbaf78238.png)

**Comment by dbltoe** [comment]
![butons](https://user-images.githubusercontent.com/5122886/80896449-c9268180-8cb3-11ea-81f3-534e1f38da7e.png)

**Comment by dbltoe** [comment]
and... 156
![156c](https://user-images.githubusercontent.com/5122886/80896487-52d64f00-8cb4-11ea-9813-b9746f2623dd.png)

**Comment by barco57** [comment]
ok, one of the two of us has something wrong... And I synced my 157 to the github before testing

1.5.7
![orders157](https://user-images.githubusercontent.com/1237035/80896531-e9a30b80-8cb4-11ea-9f3b-d5254a11659a.png)

and 1.5.6
![orders156](https://user-images.githubusercontent.com/1237035/80896538-f6bffa80-8cb4-11ea-9de9-20f469aa7566.png)


So what is that wrench Icon for?

**Comment by barco57** [comment]
Oh, edit orders... so your testing edit orders in 1.5.7 already? what?

**Comment by barco57** [comment]
So what your really saying is that the overlay css lines should, for the time being, added back in to support legacy add-ons that have not yet been updated to support the new way of doing buttons on those pages in the admin.

**Comment by dbltoe** [comment]
Edit Orders   But other mods use fontawesome as well.  Hate to have more css added somewhere else when the code can slide in to an existing sheet.  669 is what makes the wrench visible and other lines are what keep the circle from matching the a href color.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
What I was writing while you posted.
I test it all because I've found several instances where a move or sanitation has affected more than just one item on one page.
Just like the responsive_classic template, it appears we're starting to go one step beyond what really needed to be done to make it work.  And, for what gain.

**Comment by wiztechinc** [comment]
I’m thinking that the whole admin needs to be reevaluated. CSS needs to be consistent and controlled centrally.  I’m not happy with what I’m hearing. A major discussion for 1.5.8?

**Comment by barco57** [comment]
well, let me channel Scott for a minute...
do we need to carry code to support something that is no longer in the core, the overlay code for the stacked fa icons? or should the addons themselves add the code to their addons for their icon display? 
end channeling

consider that if the CSS is added back in it better be wrapped in a comment stating that it is there for legacy addons because there will be other PRs that want to remove it because it does nothing in core and we all know stuff that does nothing in the core will end up on Scott's chopping block.
Consider that lat9 borrowed from the only page in the admin that used the overlay FA icons, the category product listing, to add the edit orders icon to the orders page, where the orders page just uses image links. Help me here, what other addons also use the overlay method, I know image handler does...

yes, Delia, it needs to be sorted out. The question being as the core moves forward do you need to test a bunch of mods to see what methods they use to add buttons, icons and leave legacy code behind to cater to them or do the addon authors adjust their methods for injecting buttons , icons to match the core method? and if we do leave legacy code available for them to use, how do we encourage them to change to the newer method so that at a later date legacy stuff can be removed without rehashing this same conversation over and over again.

**Comment by wiztechinc** [comment]
Now is when planning is essential. A peek under the hood was not a happy experience for me but definitely I’m no expert in what is being used right now. I don’t mind a challenge but I also don’t tolerate frustration very well anymore if you haven’t noticed.  I’m thinking I will dig into this. Perhaps I can be more helpful in this area, but not at the moment. It will take time to figure what’s going on and I actually hate working in others’ css.

**Comment by barco57** [comment]
yes, I am aware you don't like frustration, I talk to you on the phone... and you also don't like Bootsrap, so be prepared for frustration. I suspect that as more pages in the admin are reworked they will be moving to the btn method instead of the image links further orphaning the stack FA icon method.

**Comment by wiztechinc** [comment]
Lol, gee,  thanks michael! Yes, I do know what we are talking about here. That’s why I haven’t dove into this before.

**Comment by scottcwilson** [comment]
> do we need to carry code to support something that is no longer in the core ... 

No.  Modders will need to mod.

**Comment by Zen4All** [comment]
So this is not really a bug, but more a use of css code in a place it was never intended to be used.
I made the css styling to be used on the product listing page.

**Comment by lat9** [comment]
> 
> So this is not really a bug, but more a use of css code in a place it was never intended to be used.
> I made the css styling to be used on the product listing page.
I don't understand this statement.  What 'place' was CSS not intended to be used?

**Comment by Zen4All** [comment]
Other places then the product listing page.

**Comment by lat9** [comment]
... and it was working in zc156 because?

**Comment by dbltoe** [comment]
The point that many (IMHO) are missing is that something was working with the font-awesome icons ACROSS THE BOARD.  A decision made in one area made it more difficult for those that follow to use the standard settings that were available in the css.  Why decide that no one else can use it if you're not going to?
In lurking through other comments on other subjects, I've noted several times when a constant or observer is taken out then returned when it was noted that the removed item could be helpful or used in another way.
We're talking about 14 lines of un-minified css sized out at 2K like I was wanting flash and iframes added to the core.
That's what **_I_** don't get.

**Comment by drbyte** [comment]
1. Is there a convenient way to re-include the removed markup, without muddling things in core?

2. What are the downsides to keeping it in core? (not that I want to keep unused stuff in core, only to have people ask "what's this for?" later)

3. How many 3rd party plugins were using that markup? How hard is it for them to convert their buttons to the new when upgrading other things?

**Comment by lankeeyankee** [comment]
This is a great "line in the sand" discussion. At what point do you say we are not supporting this old way of doing things? I am not a module author, maintainer, or modifier apart from some hacks needed for my own purposes, so I understand the weight of my opinions are quite limited. But I don't think it's unreasonable to say these are the changes needed to your modules to keep them compatible with the current version.

I think this should be enforced so both admin and frontend remain consistent, it's weird and unprofessional looking to have things like different button styles and zen cart really needs to step up its game to appeal to new users in 2020 and beyond, it's still pretty 2010-ish.

**Comment by torvista** [comment]
>both admin and frontend remain consistent
Disagree completely and impossible...templates!
Admin is about providing fast. concise information to professional/admin users who can tie their own shoelaces. Nice to be consistent between pages (buttons etc), but far too much screen space wasted with Bootstrap. Admins are not going to do their admin elsewhere if the page is not responsive!

Front end is a different thing for the teeming hordes with millisecond attention spans.

**Comment by wiztechinc** [comment]
No new template on the catalog side? No, so let's not worry about it all "matching" yet. I prefer this to be reality but we not there.

**Comment by lankeeyankee** [comment]
I was referring to the default responsive template, the out-of-the-box setup that a new user will first see and start to explore.

**Comment by wiztechinc** [comment]
> I was referring to the default responsive template, the out-of-the-box setup that a new user will first see and start to explore.

I am aware and that's what I was referring to as the default template.

**Comment by lat9** [comment]
Noting that the addition of that stylesheet doesn't help in the EO situation, since there's no notification within the `admin_html_head.php` through which additional stylesheets can be inserted.  The EO change affects the `orders.php` file and there's no non-core-file-overwrite method through which to use that stylesheet.

**Comment by drbyte** [comment]
> The EO change affects the `orders.php` file and there's no non-core-file-overwrite method through which to use that stylesheet.

You have two options:
- update `orders.php` to actually use `admin_html_head.php` (it does not yet before v1.5.7a)
- as you say, edit the core file to include the added stylesheet

> there's no notification within the `admin_html_head.php` through which additional stylesheets can be inserted. 

Yes and no.
Yes: there's no Notifier hook. (although, for zc_plugin plugins there is a naming convention)
No: actually there is a way to add additional stylesheets: Just add a file in `pagename_XXXXX.css` format.

eg: if `admin_html_head.php` is called, one can add a file like `/admin/includes/css/orders_edit_plugin.css`
```css
@import url("v156_compatibility.css");
```

**Comment by lat9** [comment]
Thanks for the advice, @drbyte, but none of those methods 'work' for me.  I've already got a pre-zc156 check (since the styling changed then, too) and now to add an iszc157 vs iszc157OrLater is just further complication.  So much for making a drop-in plugin.

I'm not ready to port EO to a zc_plugin since (a) it's got some storefront files, too, and the current plugin management doesn't support dual-mode plugins and (b) that would make the changes zc157+ only.
