### ISSUE TITLE
Opinions? Remove extra <br> tags from infoBox content?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3402]
Since each array element is now in it's own div, there is no need for these line breaks, in fact it wastes space.
e.g. in orders:
![Clipboard01](https://user-images.githubusercontent.com/4391026/80921708-3ef42100-8d78-11ea-8a03-c208058df32c.gif)
but this is in _**lots**_ of places.

Could be done with a big global find and replace....

**Comment by Zen4All** [comment]
I would not go and replace them automatically. It is better do it in a page by page review, as there are cases where the extra vertical space is wanted for a clearer view.
I already have removed a lot of the breaks, but as you have noticed there are still a lot of places that need to be reviewed.

**Comment by dbltoe** [comment]
Agreed.  And it needs to be so that any tap areas are not overlapping for mobile.  I'm sure some of them were added for that reason.  Don't see many overlaps reported for 1.5.7 but dropping breaks could quickly change that.

**Comment by scottcwilson** [comment]
@torvista Is it worth doing a PR changing this in a couple of places so people can play with it?

**Comment by torvista** [comment]
I did this last night
https://github.com/zencart/zencart/pull/3417

No time to do more for a few hours....have to work sometimes!

**Comment by drbyte** [comment]
Before we go and make a bunch of code changes, what's the result of inspecting the impact on usability when making the change?

**Comment by torvista** [comment]
I was planning to do a PR per file, so checks can be made.

**Comment by scottcwilson** [comment]
Would it be better to hold things like this until we get past the release?  This is not critical to 1.5.7.

**Comment by torvista** [comment]
If I see stuff, I can report it or fix it myself while I am still in the mood.
It can all be put on hold, that's someone else's decision, I'm not stressing if this does not get in 157.
If it's a problem, then I'll stop of course....
