### ISSUE TITLE
Admin Profiles: Limit Home Page Access

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#3408]
In some cases, a limited-account admin has no business viewing the store's monetary information that's posted on the admin home-page.

Would it be possible to add a setting to the Admin Profiles to limit this access, especially in the case where an admin has access to a single page?

**Comment by scottcwilson** [comment]
what if we added a checkbox called "display dashboard widgets"?

**Comment by scottcwilson** [comment]
v2 had this concept that individual widgets would have permission settings.  Maybe we'll do that too.  

Probably the fastest short term fix for you would be to modify admin/index_dashboard.php and check for `zen_is_superuser()`.  I have done this for a few clients.

**Comment by wiztechinc** [comment]
> v2 had this concept that individual widgets would have permission settings. Maybe we'll do that too.
>
Thank heavens, I thought I remembered that. I’m not crazy! I liked the concept

**Comment by drbyte** [comment]
Basic restrictions have been set in the respective modules. They're easily refined as needed.
