### ISSUE TITLE
bug ckeditor: broken link to config.js when in subdirectory

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3409]
![Clipboard01](https://user-images.githubusercontent.com/4391026/80959402-0baca300-8e07-11ea-8c52-ccf4bc24c323.gif)

This should be https://www.dev.test/zencart-157/editors/ckeditor/config.js

relevant code:

`customConfig: '/<?php echo DIR_WS_EDITORS . 'ckeditor/config.js'; ?>',`

Looks easy...but I can't get it to work: once the leading / is removed, it uses the cdn url.

**Comment by torvista** [comment]
and while you are at it, this also needs correcting:

> <php
> // Other options:

**Comment by drbyte** [comment]
> Looks easy...but I can't get it to work: once the leading / is removed, it uses the cdn url.

Argh. I hate subdirectories!

**Comment by drbyte** [comment]
@torvista I think #3413 fixes this.

**Comment by torvista** [comment]
Good grief, no apologies for not fixing that!
