### ISSUE TITLE
layout settings Categories Subcategories Indent sanitation

### ISSUE THREAD

**Issue by wiztechinc** [zencart/zencart#3412]
Since I always run sql and don't change this setting (I don't know if there are others that do this), I found in 1.5.6 and my 1.5.7 installation (close to current) that editing the field simply by saving the default &nbsp;&nbsp; changes to &amp;nbsp;&amp;nbsp; 

If this has been tended to recently, let me know. This seems to be the case in all settings such as layout and ezpages when using the &.

**Comment by drbyte** [comment]
Yes, this is fixed in 1.5.7

**Comment by wiztechinc** [comment]
How long ago?  I'm not far behind.  Using git on cpanel which isn't completely satisfactory but i pulled in the full files not long ago.

**Comment by drbyte** [comment]
3 weeks ago
https://github.com/zencart/zencart/pull/3236

**Comment by wiztechinc** [comment]
thank you- obviously time to totally redo everything!
