### ISSUE TITLE
main_page is removed when using zen_get_all_get_params

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#3421]
Where to start...

I was reviewing a potential alternate solution for what I posted on the forum here: https://www.zen-cart.com/showthread.php?226678-this_is_home_page-fails-with-custom-parameters&p=1368455#post1368455

Where the completeness of the URI was not accurately being generated.  It may actually be because of this issue, but allow me to continue.

So, I found a solution which I liked, but I wanted to see how my demo site responded... So my fix was to modify includes/init_includes/init_sanitize.php like so:
````diff
-     $check_valid = zen_products_id_valid($_GET['products_id']);
+     $check_valid = zen_products_id_valid($_GET['products_id']) && isset($_GET['main_page']) && zen_not_null($_GET['main_page']);
````
I then went to a product page which is also where I had an ajax script to perform screen updates based on actions taken on the page.  For some reason, the page kept reloading.  I tried a different browser and the same thing was happening; however, I was able to at least get more "console" information.  I found some anomolies that I didn't like and had difficult finding in the store's code, but was finally able to determine that there was something with the ajax code that was causing the reload.

What I came to find out was that when the link is/was generated to access the ajax code, there had been a desire to pass to ZC the information necessary to provide information to the page so that an indexing system reviewing the page code would be able to reach a real product and not attempt to index the ajax software. So the thought in programming was to use the Zen Cart function `zen_get_all_get_parameters`. After all, everything to define the product is in the URL correct? Well, not so.  Apparently way back when in the following commit: https://github.com/zencart/zencart/commit/34da99ad2db99e6fe37ac5e1419b3c1c43b6f9f6
added some exclusion parameters that can not be excluded from being excluded. One of those is `main_page`.

Well, because the parameter `main_page` wasn't on the uri when the ajax operation was executed, ZC then went through its processes based on the above path that didn't have `main_page` but did have `products_id` and caused the page to reload.  Once I added the `main_page` parameter to the URI with the additional sanitization as previously described, the page loaded properly and did not cycle back around.

So, wondering:
Why is `main_page` specifically excluded from the returned parameters that are supposedly on the uri? 
Is there a reason that something couldn't be added to permit it (other than manually including it in putting the uri together)?
Should there be some other function added to return the `main_page` parameter or just to do the:
`(!empty($_GET['main_page']) && zen_not_null($_GET['main_page']) ? 'main_page=' . zen_output_string_protected($_GET['main_page']) . '&' : '')`
type code wherever such is possible/desired?

How many places might the code need to be changed to account for `main_page` on the catalog side to account for similar issues that might be seen if the uri is sanitized further as described above?

**Comment by drbyte** [comment]
> Apparently way back when in the following commit: [34da99a](https://github.com/zencart/zencart/commit/34da99ad2db99e6fe37ac5e1419b3c1c43b6f9f6)
> added some exclusion parameters that can not be excluded from being excluded. One of those is `main_page`.

Actually, that commit didn't add any exclusions. It merely relocated them as part of refactoring to deal with another matter. 
The `main_page` exclusion has been present since at least v1.1.4 in 2004.

Core code uses of `zen_get_all_get_params()` are normally as the 2nd parameter to `zen_href_link()` which generates `main_page` via its first parameter.

**Comment by mc12345678** [comment]
I admit that I had not dug deep enough and long enough to find proper cause for the code to be present as it is.  I apologize that you did so much, finding the initial information to be back in 2004 in at least version 1.1.4 possibly some earlier version.

> Core code uses of `zen_get_all_get_params()` are normally as the 2nd parameter to `zen_href_link()` which generates `main_page` via its first parameter.

So, yes, did somewhat get to the root of the issue I am considering/discussing: `zen_href_link()` in its "normal" use will seek code to be processed via `index.php`, but can be overridden to use whatever base page is provided in the first parameter and then add on the additional existing parameters from the second function parameter (therefore requiring `main_page` be added if so needed/desired).

So here's the use issue... making an ajax call that includes the parameter `products_id` and application of #3453 without passing `main_page` as a parameter causes the page to recursively reload... Ie. `zen_href_link('ajax', 'products_id=1&act=n&method=p')` causes `index.php?main_page=ajax&products_id=1&act=n&method=p` but `zen_href_link('ajax', 'products_id=1&act=n&method=p', $request_type, true, true, true)` will give: `ajax.php?products_id=1&act=n&method=p` which is calling a different base file and not including the `main_page` parameter.

Of course in trying to use "reusable" code, I wanted to fully use the Zen Cart function `zen_get_all_get_params` as it seemed like a method to collect all of the parameters on `$_GET`, but the code and the result(s) reflect that `main_page` is not retained as a factor and is specifically omitted.

For my purposes I could leave it alone because I have a solution for my issue, but... I also have proposed a "fix" at #3453 that could cause others grief if a similar solution is not wrapped more into the code...

I had a couple of approaches in mind: the `zen_get_all_get_params` function adding a parameter to allow keeping parameters instead of just an array of parameters to omit (that extends to omitting a parameter that may be desired), changing all of the uses of `zen_get_all_get_params` to include the call to omit the `main_page` parameter and stop omitting the `main_page` parameter in the result, the third option I was considering would be some additional function that would give everything that is in the existing function and the main_page parameter....

To me if there are no other considerations, the first option seems the best as the existing code could be used and only those that need to keep the `main_page` or whatever other parameter that is removed by adding a call parameter.  The third option seems the most wasteful, to basically add duplicate code to stop filtering on a single parameter every once in a while.  The second option would take a lot of time, is prone to mistakes, and would also affect plugins where the use would either need to specifically omit the `main_page` parameter or would probably want to stop adding it to the results of the `zen_get_all_get_params` function.

The other thought was/would be if there was a way to call the ajax function as a `main_page` and therefore the `products_id` parameter could/would be on the uri and a `main_page` parameter would also and there would not be the cyclic load that I experienced after applying #3453 when the ajax address didn't specifically have a `main_page` parameter but did have `products_id`.

**Comment by drbyte** [comment]
Even after following the links to the forum thread (but not so far as investigating the plugin code that initiated the discussion), I'm still not clear why the ajax call is depending on any of this. 

Assuming the ajax handler is listening for passed parameters, why not just pass the necessary parameters to the ajax call so it can understand what's intended. That could include passing main_page as something else like `origin_page` and whenever the ajax handler's primary logic is done it can redirect to main_page or do whatever it was wanting done with it.

What am I missing?

**Comment by mc12345678** [comment]
Maybe things have devolved from where they were before and what seemed necessary...

The discussion at that thread is different than where I ended up with this thread. I mean, yes I could (sort of) reproduce the problem on demand, but what/where I see the issue I don't consider it so much against the SEO as the processing problem I'm trying to resolve.

So, perhaps the plugin code needs to be modified though the following were the key factors of consideration:
- ajax code needs to receive information about the action being performed.
- any whois type tracking needs to not necessarily record/return the ajax specific action/operation but instead at least show information specific about the product or at least not show the ajax action request as being the "last" action.

The genesis was: add two parameters necessary to use the ajax.php file.
Add information to the URI to help identify the current site page along with the next item.
Ensure that the page history (whois tracking) provides understandable information to identify where the customer is at (which product).
Expand the above to support URI rewriter operation (introduction of zen_href_link function use).
Maintain information on the page so that search engines do not automatically index these ajax links which are unreachable by the search engine.

So the current setup/call for ajax use looks something like this:

In here theURL could be set to the file's name or the full path to and including the file's name as seen from the internet.
````php
    var option = {
      url: theURL + "?cPath=54_56&products_id=156&main_page=product_info&act=DPU_Ajax&method=dpu_update",
      data: combinedData.JSON,
      timeout : 30000
    };
````
The previous one (which causes a problem with #3453) was like this:
````php
    var option = {
      url: theURL + "?cPath=54_56&products_id=156&act=DPU_Ajax&method=dpu_update",
      data: combinedData.JSON,
      timeout : 30000
    };
````
Originally it was basically just:
````php
    var option = {
      url: theURL + "?act=DPU_Ajax&method=dpu_update",
      data: combinedData.JSON,
      timeout : 30000
    };
````

But this didn't give enough information when looking at whois while using the on product page manipulators at least not until the internal code called also adjusts the navigation history when the code is called... Not the proudest "moment" but seems like it accomplishes the needed task. So basically, if the URI were again generated like it was, the needed information is passed in the combinedData, the called code corrects the navigation history so that the "page load" doesn't get registered and there is no "need" for concern of specific `zen_href_link` output.... Maybe...

Anyways, the result is still the same regarding the absence of handling/collecting the `main_page` parameter if it is not manually added. But, perhaps I have found the way forwards with my code, even if there remains a sort of alternate issue available, but not a problem for me at the moment.

**Comment by drbyte** [comment]
Okay, I think I get the gist of what you're saying.

Questions:
- if you chose to pass the product Id as `pid` or `product_id`, instead of the `products_id` (which is associated with fallback lookups which were designed before ajax), does this whole issue go away?
(I'm not asking this in order to "make this go away". I'm asking in order to isolate scope to be sure we're identifying exactly the right thing to fix.)

- when you say "whois tracking", do you mean "navigation_history"? or "whos_online"? I'm confused because "whois" is usually associated with "who owns a website domain or IP", not with Zen Cart internals

Aside: there's probably a need to intercept the default flow so that ajax calls are ignored by the navigation_history process, much like login skips "itself" when redirected to login during checkout.

**Comment by drbyte** [comment]
This may be worth investigating: in your dpu ajax class, does removing the current visit from navigation history help mitigate issues?

```php
$_SESSION['navigation']->remove_current_page();
```

There's a call to `add_current_page()` as part of the init system, so subsequently removing it as part of your plugin logic may solve some of your issues.

**Comment by mc12345678** [comment]
> Questions:
>
> - if you chose to pass the product Id as `pid` or `product_id`, instead of the `products_id` (which is associated with fallback lookups which were designed before ajax), does this whole issue go away?
(I'm not asking this in order to "make this go away". I'm asking in order to isolate scope to be sure we're identifying exactly the right thing to fix.)

Sorry for the delay in responding.  There are a few things upon which I've been contemplating as well as trying to look over and try.  So... I did post a suggested correction to address the products_id on the URL issue without a main_page associated.  Anyways, let me try to stay on track here.  If I were to use pretty much any other parameter, then the page refresh issue that is seen to occur would go away. That alternate parameter would still need to be captured (for use), though would also be subject to whatever other "management" is done to such web addresses.  It would not necessarily make the *whole* issue go away but would actually move it to something/somewhere else. Also if there was anything to be captured from the URI specifically then it would not be available.  For example, it seems that right now the products_id is posted; however, that is through the existing data in the add-to-cart section where there is not the current categories_id nor its current main_page. Yes both can be added, but because of the absence of that data to "know" it requires recreation rather than taking directly from the current information.  For example if wanted to know if product was being viewed on one of the linked pages, it basically wouldn't be possible without that additional information.

Now as far as what is/was being attempted.... There actually were a few things, which means more than likely at least one too many. :) Wanted to be able to use standard parameters that define/identify a product, so that meant at least products_id to be associated (Now statement is `products_id` and some sort of `main_page=`) and should have meant the `main_page` parameter as well, but there seemed to be a bit of play available. I also wanted to be able to allow detection/review of the selection(s) being made so that they could be potentially be logged (if someone was wanting to capture that information) or to ensure that it wasn't logged (minimize data capture/tracking of on page changes). Then there was the desire that if there was URL information "available" on the page (as a result of using ajax), wanted to be able to leave behind a full URL as generated by `zen_href_link`... So, like said, probably too much for consideration, but each thing was added one at a time once the issue with logging of the history was initially identified.

>
> - when you say "whois tracking", do you mean "navigation_history"? or "whos_online"? I'm confused because "whois" is usually associated with "who owns a website domain or IP", not with Zen Cart internals
>
> Aside: there's probably a need to intercept the default flow so that ajax calls are ignored by the navigation_history process, much like login skips "itself" when redirected to login during checkout.

Oye, call that some sort of late night rambling.  Who's online was the idea in mind as discussed in the associated forum.  Basically having the opportunity to see what user(s) are online and where they are at in the shopping process... When no action is taken to address the ajax feed, then the who's online reflects the call to the ajax '`act`ion' and associated `method`.

Looking a little more at the existing code, it appears that the operation is actually more of a logging thing than a skip thing at the moment.  Thinking back on it a little, the thought was to add some code that works and could be disabled rather than leaving it out and having to add it in for some reason. So yes, I apologize for the terminology used, I had an idea/concept in mind and incorrectly spoke.

**Comment by drbyte** [comment]
Thanks for the updated thoughts. I appreciate the deeper explanation.

> having the opportunity to see what user(s) are online and where they are at in the shopping process... When no action is taken to address the ajax feed, then the who's online reflects the call to the ajax '`act`ion' and associated method.

Just to clarify: are you saying that your preference is that the whos-online still shows the actual page the shopper is "on", and does *not* show the last AJAX URL they recently called?

(Note to self: The whos-online URL is recorded via `zen_update_whos_online()` called in `init_special_funcs.php`, which is separate from navigation-history workflow.)

**Comment by mc12345678** [comment]
> Just to clarify: are you saying that your preference is that the whos-online still shows the actual page the shopper is "on", and does not show the last AJAX URL they recently called?
>
> (Note to self: The whos-online URL is recorded via `zen_update_whos_online()` called in `init_special_funcs.php, which is separate from navigation-history workflow.)

So there are two plugins that I've touched that each use this similar method of passing information to the `ajax.php` processor.  I believe each has their need.  DPU seems more appropriate (if desired/wanted) to track the selections made/identifying the current page at least at the point of submitting the final result if not during the selection process (note that if only the ajax parameters are identified in the whos-online aspect, then a storeowner reviewing shopper's actions would primarily only see the ajax url for each customer looking at a product page and not know at which product the customer is viewing <- **problem**). The other plugin in mind is attribute image swap, well, there may be a desire to track the selection/change; however, I would think that it would be less of an indicator of product selection/review though could be for some.  These two modules currently have a single AJAX URL associated with them, though combined there are then two and I would think it would be "wasteful" for both of them to react with the same/similar response (other than for debugging purposes) and add *data* to anything downstream.  Both of these directly affect product selection/review.  

I could also see that other ajax related options may not offer much valuable information that couldn't be captured in some other way if needed/wanted.  For example adding a product to the cart. I would expect at least two ways to capture that information if done via `ajax`. One would be through monitoring the ajax operation, the other the operations of the cart itself. I assume either provides some sort of information that ***may*** be valuable. One being the origination point (most likely the `ajax` request), the other the product being added (either operation).

Not having seen a great number of plugins yet using `zcAjax`, it is hard for me to provide an assessment of needing to know the AJAX URL in an always situation (information during development can always be helpful). Makes me wonder if adding an additional parameter would be of benefit, but then wonder about the entire "integration" of that seeing the discussion of the initiation of the load process and any negative use of such a parameter. Or perhaps if the solution would be something controlled by the associated ajax implementation where some trigger might be available to do one or the other (output or remove the associated AJAX URL identifier).  

Right now have been trying to address/correct what the store owner sees as part of the customer process.  Unfortunately for those that have a tool such as user tracking, logging/identification of ones selections (through the whos-online process) adds a number of records to that dataset (so almost a desire to be able at some point to exclude that information from one side but have it presented on the other... :/ As in the possibility of instantaneous observation, but no long-term logging.)

**Comment by drbyte** [comment]
Is a quick magic fix to update `zen_update_whos_online` to skip `main_page=ajax`?

ie: the same way `navigation_history` does:

```php
      // check whether there are pages which should be blacklisted against entering navigation history
    if (preg_match('|ajax\.php$|', $_SERVER['SCRIPT_NAME']) && $_GET['act'] != '') return;
```
