### ISSUE TITLE
Notice: shipping estimator: Trying to access array offset on value of type bool: $selected_shipping

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3433]
Report All Errors on of course, php 7.4.5, mysql strict developer mode.

This is an upgraded real database, using Advanced Shipper, which may be relevant.

Admin: SHOW_SHIPPING_ESTIMATOR_BUTTON = 2
add product to cart, login, go to checkout, get warning:
--> PHP Notice: Trying to access array offset on value of type bool in zencart-157\includes\templates\template_default\templates\tpl_modules_shipping_estimator.php on line 14.
 which is
<?php echo zen_draw_hidden_field('scid', $selected_shipping['id']); ?>

Superglobals says it's a boolean
![Clipboard01](https://user-images.githubusercontent.com/4391026/81329804-5b0d0080-909f-11ea-96f4-2c838bcee6e9.gif)

this variable comes from includes\modules\shipping_estimator.php
which on first viewing is out of my pay grade, so I'll pass on this one. Thanks.

**Comment by scottcwilson** [comment]
If `selected_shipping` is false, it hasn't selected a shipping module.  So you could just wrap this in `is_array($selected_shipping)`.

**Comment by torvista** [comment]
Yes, it occurs when there are no shipping modules enabled as well. So, I'd go with your suggestion.
