### ISSUE TITLE
Proposal: remove ALL image-button support (use CSS only)

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#3434]
How many storeowners intentionally WANT to use image-buttons on their site?

While it'd be a big overhaul, is it safe to remove all our "button gif" image files, and change the function to not support the images at all?

**Comment by barco57** [comment]
I have built a new site in a long time that used image buttons and on most upgrades bringing their old  image buttons forward tend to clash with a redesign and there are new buttons that there weren't images for and we tend to scrap them and switch to css buttons.

**Comment by wiztechinc** [comment]
I rarely ever see sites with image buttons and if I do they are really old sites that need upgrading and therefore need a new template that uses css buttons.

**Comment by drbyte** [comment]
Good. I was hoping for that feedback.

Still, dropping it is a big decision with significant consequences to old templates. :(
I'd love to hear more feedback about how aggressive we need to be about backward compatibility for supporting image buttons ...

**Comment by scottcwilson** [comment]
One way to test this would be set make the 1.5.7 data conversion set `IMAGE_USE_CSS_BUTTONS` to `true`.  Anyone who found this objectionable could always flip it back to `false`.

**Comment by scottcwilson** [comment]
My vote on the proposal would also be yes.  The buttons are a relic from another age.

**Comment by wiztechinc** [comment]
> One way to test this would be set make the 1.5.7 data conversion set `IMAGE_USE_CSS_BUTTONS` to `true`. Anyone who found this objectionable could always flip it back to `false`.

that's start. I'm for removing them entirely now.

**Comment by DocBenc** [comment]
I wrote class and function to handle CSS buttons with fa font and similars years ago. In 2020 i dont think many stores are using image buttons.

**Comment by drbyte** [comment]
> One way to test this would be set make the 1.5.7 data conversion set `IMAGE_USE_CSS_BUTTONS` to `true`. Anyone who found this objectionable could always flip it back to `false`.

Fortunately it does already use that as a default.

**Comment by scottcwilson** [comment]
It is the default for new installations but not upgrades.  I'm suggesting doing it in the upgrade script.   New installations are unlikely to want to use those hoary old images.

**Comment by proseLA** [comment]
i'm all in for the new and out with the old.  losing image buttons is a big win as far as i'm concerned.

**Comment by torvista** [comment]
>make the 1.5.7 data conversion set IMAGE_USE_CSS_BUTTONS to true.
The first people who find weird/new (css) buttons on their upgrade site may post about it...you wont get to hear from the rest who read the thread. So I don't think it would be an accurate marker.

Would it not be more appropriate to leverage that old forum thingy (where the actual users live), and mention that you're thinking of dropping support and who uses image buttons?

**Comment by scottcwilson** [comment]
Maybe.  But more often than not, the opinion of any one user is an expression of their own particular parochial concerns.  It's anecdotal and certainly not a basis for deciding whats best for the future of the product.  It also excludes the opinions of potential new users who might be attracted to a product with less baggage from 2005.

**Comment by drbyte** [comment]
> Would it not be more appropriate to leverage that old forum thingy (where the actual users live), and mention that you're thinking of dropping support and who uses image buttons?

You are right. A forum post will be seen by more end-users, not developers.

Do you promise to help keep the forum discussion on-topic, so that it doesn't devolve into all kinds of things unrelated to image-buttons?

**Comment by lankeeyankee** [comment]
I vote 100 times for removal. And put a note with the old templates they are there for archival purposes in case anyone wants to upgrade it to work with modern zen cart version. Because backward compatibility should only go back a couple versions, not a decade. I would not be surprised if any of the old templates that use images also don't work for other reasons.

**Comment by scottcwilson** [comment]
Poll is here: 
https://www.zen-cart.com/showthread.php?226701-Should-we-delete-image-buttons-in-the-next-version

**Comment by lat9** [comment]
Just please, _please_, keep the functions for downward compatibility ... perhaps adding a notification to enable site-specific customizations to provide an override if needed.

**Comment by dakanji** [comment]
Tried to visit forum to vote but logged out and it seems there is no "Password Forgotten" function anywhere I can see.

**Comment by barco57** [comment]
https://www.zen-cart.com/login.php?do=lostpw

**Comment by dakanji** [comment]
Cheers. Any idea where the actual usual link of button to this is?
Couldn't locate one on the login form.

**Comment by barco57** [comment]
I had to force the issue by purposely failing the login and then it gave me https://www.zen-cart.com/login.php?do=login where there is an inline link in the text to that lost password page.

**Comment by dakanji** [comment]
i see ... Thanks. 
Not the most user friendly set up
