### ISSUE TITLE
installer does not insert new field, invalid datetime default 0001-01-01 00:00:00

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3438]
following on from this
https://github.com/zencart/zencart/issues/2397

I find that on upgrading my production db, the query
```
# Add customer secret
ALTER TABLE customers ADD customers_secret varchar(64) NOT NULL default '';
```
is not executed, and there is no record of it failing (unlike as I mentioned in the other thread).
It fails due to the invalid default on customer_dob of 0001-01-01 00:00:00: if I change it to 1000-01-01 00:00:00 before running the upgrade, it executes.

I note that the default is still set to 0001-01-01 00:00:00 in the install sql for many fields!

**Comment by scottcwilson** [comment]
Please double check the DOB field in your customers table - it should be called "customers_dob" (not "customer_dob") - can you confirm this?

**Comment by scottcwilson** [comment]
Also what are you upgrading from?

**Comment by scottcwilson** [comment]
... and can you run, stand alone, the file zc_install/sql/install/zero_dates_cleanup.sql to see if it completes without error?  (This file should be run by the installer but maybe it's failing in your setup.)

**Comment by scottcwilson** [comment]
This default *should* work - the old default was 0000-00-00 00:00:00 which does not work anymore.  What is your MySQL version?

**Comment by scottcwilson** [comment]
We are investigating.  Although @lat9 carefully documented this issue, I very cleverly forgot to do anything about it. :(

**Comment by scottcwilson** [comment]
Also are you in strict mode?

**Comment by torvista** [comment]
10.4.11-MariaDB
I have php strict mode set in the main fileset but that should not affect the installer.

In localConfig I had the DB_MYSQL_MODE in STRICT....mode, since this is development stuff.....
I've just tried it in traditional, and the insert executed.

So, is this not exactly the reason to use strict mode: to get an early heads up on these things?

**Comment by drbyte** [comment]
> So, is this not exactly the reason to use strict mode: to get an early heads up on these things?

Yes.

But even MySQL is evidently totally conflicted on the best solution: In their documentation they've said the NO_ZERO_DATES setting is deprecated and if you set it you'll get errors, but it's also the default, and they can't decide how/when to add a new setting to do whatever they're thinking of doing next with it.

**Comment by drbyte** [comment]
So, apart from the dates issue, which we can continue discussing back in the other open issue, is there another problem with install?

**Comment by torvista** [comment]
I have not checked that all the upgrade settings are applied, but there is an example here now:
https://github.com/zencart/zencart/issues/3445

But as for this issue, when using the default traditional setting, it seems ok.
