### ISSUE TITLE
Add Display Logs to core?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3441]
Since Report All Errors is in, the omission of it's sibling is even more evident, for me.
This is a companion to RAE and something I have kept in the ZC157 fileset for so long I forgot that it wasn't core already.

**Comment by lankeeyankee** [comment]
Yes please, I agree this should be in the core

**Comment by scottcwilson** [comment]
Direct link to Display Logs: 
https://www.zen-cart.com/downloads.php?do=file&id=1583

@lat9 What say you?

**Comment by lat9** [comment]
[Display Logs](https://github.com/lat9/display_logs) has been a stable, drop-in plugin since January of this year, aligning with the error-severity indication now used in zc157 and the most recent version of RAE.  

The only 'issue' remaining is the conversion to use HTML-5 for the display, but I wouldn't want the Bootstrap-bloat to affect the information display, just prettify those ugly image-buttons.

**Comment by wiztechinc** [comment]
I like it! For a store owner to have that kind of knowledge and control, it’s fantastic but it also can save a developer time.

**Comment by dbltoe** [comment]
I still think it's nice to sort the display in the order of the admin menu pages.  https://www.zen-cart.com/showthread.php?218710-Mod-List-Support-Thread&p=1333420#post1333420

**Comment by dbltoe** [comment]
The only wish for display logs is an option for it to text/e-mail the owner.

**Comment by drbyte** [comment]
> The only wish for display logs is an option for it to text/e-mail the owner.

Do you mean "choose a log file manually and forward a copy of it by email"?

Or do you mean "every time an error happens in real time send me an email about it, even hundreds of times per second"?

**Comment by torvista** [comment]
>The only wish for display logs is an option for it to text/e-mail the owner.

Well, the beauty of open source is you can add that torture instrument as you wish!

To be honest the idea of having a note in the admin saying there is a log, but no way of seeing it without ftp, seems to be only half the job. Hence the suggestion to include it.

**Comment by scottcwilson** [comment]
To me, the note in admin is sufficient because it lets me know I need to open an FTP session both to pull the logs and to fix the issue that caused the logs.

**Comment by wiztechinc** [comment]
> To me, the note in admin is sufficient because it lets me know I need to open an FTP session both to pull the logs and to fix the issue that caused the logs.

Yes no emails because of the panic that can create. I don’t want my clients screaming emergency. Most of the logs are not the site going down or even a page going down. Many times nowadays it’s more about warnings due to Php version  changes. No need to give folks heart attacks but more info like the mod would be gratefully accepted.

**Comment by lat9** [comment]
> 
> 
> To me, the note in admin is sufficient because it lets me know I need to open an FTP session both to pull the logs and to fix the issue that caused the logs.

... or you could just view that log using **_Display Logs_**, without the need for FTP.

**Comment by torvista** [comment]
> I need to open an FTP session.

Precisely.
If I have a notice of an error in the admin, I want to see that error from the admin, not open another program.

**Comment by drbyte** [comment]
> If I have a notice of an error in the admin, I want to see that error from the admin, not open another program.

I would agree that if there were notices but not way to view the details then it would be half-baked. But there aren't any.

**Comment by drbyte** [comment]
Two phases I'd like to see:

1. If we put this into core then I'd prefer to use the new plugin architecture for it. That way it's self-contained in one directory.

2. I'd much rather get rid of debug log files altogether and go a more modern route of using an external log aggregator that handles alerting, merging, alarms, and even other things like uptime monitoring, etc.  Two great candidates for this, that even the average shopowner could use, are Sentry and Honeybadger. Just need to write a plugin for it. Developers and Support Staff will appreciate the ability to notice problems in real time. And duplicates are automatically combined, which makes finding trends much easier and reduces the "noise" to sort through when looking for a specific thing.

**Comment by scottcwilson** [comment]
Logging options: feature for 1.5.8?  Very powerful.

**Comment by torvista** [comment]
While I proposed it, I don't see I'll be able to get it ready, business is snapping at my heels now the teeming hordes are on the loose again.

**Comment by drbyte** [comment]
> business is snapping at my heels now the teeming hordes are on the loose again.

That's a good problem to have! Hope it goes smoothly and profitably for you!

**Comment by torvista** [comment]
Thanks, I'll try to clear loose ends before going dark!

**Comment by proseLA** [comment]
> 1. If we put this into core then I'd prefer to use the new plugin architecture for it. That way it's self-contained in one directory.

excuse me, but i am a little ignorant on the new plugin architecture; is this new architecture documented somewhere?

**Comment by zcwilt** [comment]
@proseLA 
Documentation for the new plugin system is here
https://zc-dev-docs.readthedocs.io/en/latest/devdocs/plugins/pluginsystem.html
This is in the process of being converted to put on `docs.zen-cart.com`
It is also a little out of date, though most stuff will still be the same.

**Comment by zcwilt** [comment]
I've a branch

**Comment by zcwilt** [comment]
I have a branch 
https://github.com/zencart/zencart/compare/v157...zcwilt:v157-new-plugin-infrastructure?expand=1

This includes a conversion of the display logs contribution to the new plugin architecture.

Note code and conversion aren't 100% complete yet, but it does work as is.
