### ISSUE TITLE
comparison of new and upgraded database: minor differences in fields and defaults

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3445]
While examining if the upgrade had proceeded completely, I find a significant number of differences between the schema of my db and vanilla ZC157.
My db was originally 1.38 so has received all the subsequent upgrades, supposedly.

I did an export from BC and have noted my mods, but here you can see the differences.
They seem to be mainly text/mediumtext and defaults. There is the occasional field too!
Just wondering why and if these should be restored?
[schema comparision.pdf](https://github.com/zencart/zencart/files/4603018/schema.comparision.pdf)

**Comment by scottcwilson** [comment]
This would be a valuable report, but you have to turn off strict mode so the upgrades actually work.  Right now you're missing customers_secrets from the customers table, which only happened because you have data in the data fields which is not compatible with strict mode.

Would you please use 
  define('DB_MYSQL_MODE', 'NO_ENGINE_SUBSTITUTION');
in your configure files and rerun?

**Comment by torvista** [comment]
This **was** run in traditional mode, and customers_secret **is** there:
![Clipboard01](https://user-images.githubusercontent.com/4391026/81485126-20e06200-924b-11ea-924e-dd3445f13b1c.gif)

The issue is not the upgrades for now, but the differences between my upgraded legacy schema and the latest install,  and hence possible omissions in previous upgrade scripts.

**Comment by scottcwilson** [comment]
A lot of this seems to be local customization.  `entry_telephone` is not in the address_book table in either new or upgraded databases.  `entry_postcode` is supposed to be 10, not 34, etc. 

I didn't fix all the changes to text fields but I fixed everything else; if you create a new 1.3.8 database and run through the latest upgrades, it should be basically the same as a new 1.5.7 database (with the exception of text fields).  

But you have other differences that make me think your MODE is wrong - the customers_basket table should not contain final price; the drop is there in the 157 update and it's not there in the new install.  So why is it there in yours?  Are there logs?

**Comment by torvista** [comment]
The left column is a vanilla install.
The right column is a legacy upgrade.
The **far** right column on the right indicates all the fields I have modified: "mod", almost all the ones you have mentioned, so they should be ignored.

You mentioned final_price from customers_basket. I assumed that that was something from Recover Cart (which I now do not use) since it is not in the vanilla install. But no, it is legacy and should have been dropped on the upgrade to 156 (not 157)...so I need to check on last years upgrade.

> if you create a new 1.3.8 database and run through the latest upgrades, it should be basically the same as a new 1.5.7 database (with the exception of text fields).

I would have assumed it should be identical...why differences in text fields? It's only size?

**Comment by scottcwilson** [comment]
> why differences in text fields?

I think I stopped there on the last round of fixes, which were just merged in.  
You're welcome to improve it further if you have time.  Testing and retesting these changes is super time consuming.   I think things are identical back to 1.5.1 if you upgrade vs new 1.5.7.

**Comment by torvista** [comment]
Ok, thanks for the explanation that changes to text fields were not implemented in the upgrade scripts.

> Testing and retesting these changes is super time consuming

Yep.

That leaves me me six anomalies to investigate, one day when I have spare time...or possibly I could set someone else on it....
I assume that over the years multiple masochists have created documentation/spreadsheets etc. that detail each sql addition/modification back to the ark.
In the interests of not re-inventing a wheel in that parallel universe of spare time, having access to those documents for collation (!), rectification, updating..publication etc. would be encouraging....

As a side note, this free tool does database compares and also generates scripts for any differences you wish to implement:
http://www.nobhillsoft.com/NHDBCompare.aspx

**Comment by scottcwilson** [comment]
Would you please note the 6 differences so they're easily accessible?

**Comment by torvista** [comment]
Differences:

customers_basket
	final_price
	
orders
	downloaded

products_options
	products_options_comments (field size)

square_payments
	transaction_id
	tender_id

admin_activity_log
key idx_severity_zen
	
ezpages_content
key idx_ezpages content
key ez_pages

**Comment by scottcwilson** [comment]
orders.downloaded is a local change you made. 
square_payments is not part of the default install 
admin_activity_log.idx_severity_zen is not part of the default install
ezpages_content.idx_ezpages_content is named ezpages_content.idx_ezpages_content in upgrade  but it's the same index.

customers_basket.final_price was dropped in 1.5.6 (operation failed) and in 1.5.7. 
products_options.products_options_comment was changed in length in 1.5.6

Starting with the 1.3.9 demo database, in mode NO_ENGINE_SUBSTITUTION, these two fields are properly upgraded.

Same operation, mode STRICT, these two fields are properly upgraded.  

Can't repro.

**Comment by scottcwilson** [comment]
Suggest closing.

**Comment by torvista** [comment]
>orders.downloaded is a local change you made.

Not that I was aware of. Never used downloads.

>square_payments is not part of the default install

No, but it is a payment method included in the fileset, and those fields (transaction_id
tender_id) are not part of it.
I note that once enabled/installated in the admin and the table is created, a Clean Install does not remove it. Possibly I enabled it and it became debris in subsequent re-installs. But still does not explain the two extra fields.

>admin_activity_log.idx_severity_zen is not part of the default install

Don't know where that may come from...what mods would touch this table?
