### ISSUE TITLE
Plugin authors question: are you using split_page_results_new.php ?

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#3457]
The `admin/includes/classes/split_page_results_new.php` was put in core in v1.5.1 but has never been integrated into core code.

Are your plugins using it? 

I'd like to remove it since it's unmaintained.

**Comment by scottcwilson** [comment]
I see zero references in my archive of contributions.

**Comment by lat9** [comment]
Ditto; I'd always wondered why there were two.

**Comment by drbyte** [comment]
The catalog-side split-page-results is more efficient, and the admin "new" one initially attempted to offer those improvements admin-side, but was never implemented.

That said, I might take a stab at converting all the admin pages to use the new after syncing some updates from catalog-side.

@scottcwilson does the plugin archive have any alterations to the non "new" admin file? Any catalog-side alterations either?

**Comment by scottcwilson** [comment]
No hits on admin.  Catalog are as follows but most of these are older. 

Dynamic_Attribute - includes/classes/split_page_results.php
ZCA-Responsive-Classic - includes/classes/split_page_results.php
ZCA_BOOTSTRAP_TEMPLATE - includes/classes/split_page_results.php
dover_fine - includes/classes/split_page_results.php
dynamic_filter - includes/classes/split_page_results.php
mobizencart - includes/classes/split_page_results.php
product_pagination - includes/classes/split_page_results.php
responsive_sheffield - includes/classes/split_page_results.php
tableau2 - includes/classes/split_page_results.php
westminster - includes/classes/split_page_results.php
westminster_new - includes/classes/split_page_results.php
winchester_black - includes/classes/split_page_results.php
winchester_responsive - includes/classes/split_page_results.php
