### ISSUE TITLE
Sort order changes for Specials and Featured Products

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#346]
The way Wilt set up the dashboard widgets so you can drag them around is really nice.  Could we do that for the sort order stuff for specials and featured?  I know I'm asking just in the nick of too late but it just occurred to me. :(

**Comment by zcwilt** [comment]
Interesting idea, :) 
While we do have some workboard stuff e.g. https://github.com/zencart/zc-v1-series/issues/63
that change the way some admin pages are built, and use ajax etc to make the admin experience better, I hadn't considered adding drag/drop to other pages. 

Will keep it in mind as I look to roll out LEAD stuff for various admin pages.

**Comment by scottcwilson** [comment]
Someone asked me just the other day if sort order on products could be implemented using drag and drop.  Possible with the new LEAD stuff?

**Comment by drbyte** [comment]
This drag-and-drop idea is a nice-to-have, but requires numerous changes on the Admin side. Some of those are in-progress but still quite a way off. This can be re-addressed later once the infrastructure is more amenable to this sort of thing.
