### ISSUE TITLE
SQL syntax error in admin zen_get_configuration_key_value_layout()

### ISSUE THREAD

**Issue by dennisns7d** [zencart/zencart#3461]
I've been fiddling around trying to get Stock by Attributes Combined working with ZC 1.5.7. This exposed an error:
`[14-May-2020 20:12:25 America/Los_Angeles] Request URI: /zencart157b/zcadmin/index.php?cmd=products_with_attributes_stock, IP address: 127.0.0.1
#1 trigger_error() called at [C:\xampp\htdocs\zencart157b\includes\classes\db\mysql\query_factory.php:171]
#2 queryFactory->show_error() called at [C:\xampp\htdocs\zencart157b\includes\classes\db\mysql\query_factory.php:143]
#3 queryFactory->set_error() called at [C:\xampp\htdocs\zencart157b\includes\classes\db\mysql\query_factory.php:270]
#4 queryFactory->Execute() called at [C:\xampp\htdocs\zencart157b\zcadmin\includes\functions\general.php:2799]
#5 zen_get_configuration_key_value_layout() called at [C:\xampp\htdocs\zencart157b\zcadmin\products_with_attributes_stock.php:1127]
#6 require(C:\xampp\htdocs\zencart157b\zcadmin\products_with_attributes_stock.php) called at [C:\xampp\htdocs\zencart157b\zcadmin\index.php:11]
--> PHP Fatal error: 1064:You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''0' at line 1 :: select configuration_value from product_type_layout where configuration_key='PRODUCT_INFO_PREVIOUS_NEXT_SORT' and product_type_id='0 ==> (as called by) C:\xampp\htdocs\zencart157b\zcadmin\includes\functions\general.php on line 2799 <== in C:\xampp\htdocs\zencart157b\includes\classes\db\mysql\query_factory.php on line 171.`

Note that the value that product_type_id is being compared to has a leading single quote, but no closing quote. Line 2799 of admin/includes/functions/general.php within the zen_get_configuration_key_value_layout function is:
`    $configuration_query= $db->Execute("select configuration_value from " . TABLE_PRODUCT_TYPE_LAYOUT . " where configuration_key='" . zen_db_input($lookup) . "' and product_type_id='". (int)$type);`
Removing the single quote just before (int)$type avoids triggering the error.

The same function on the catalog side in includes/functions/functions_lookups.php places single quotes on both sides of (int)$type.

With the database using int(11) for the product_type_id field, it seems to me that neither the admin nor the catalog versions of this function should be placing quotes around (int)$type.

**Comment by scottcwilson** [comment]
Fixed in #3463.  Thank you for reporting this issue.
