### ISSUE TITLE
PHP notice in gv_faq.php - comparison should be assignment

### ISSUE THREAD

**Issue by dennisns7d** [zencart/zencart#3465]
When I navigated to Gift Certificate FAQ, I encountered the following in a log file:
`[15-May-2020 09:17:27 America/Los_Angeles] Request URI: /zencart157b/index.php?main_page=gv_faq, IP address: 127.0.0.1
#1 require_once(C:\xampp\htdocs\zencart157b\includes\languages\english\gv_faq.php) called at [C:\xampp\htdocs\zencart157b\includes\modules\require_languages.php:23]
#2 require(C:\xampp\htdocs\zencart157b\includes\modules\require_languages.php) called at [C:\xampp\htdocs\zencart157b\includes\modules\pages\gv_faq\header_php.php:15]
#3 require(C:\xampp\htdocs\zencart157b\includes\modules\pages\gv_faq\header_php.php) called at [C:\xampp\htdocs\zencart157b\index.php:36]
--> PHP Notice: Undefined index: faq_item in C:\xampp\htdocs\zencart157b\includes\languages\english\gv_faq.php on line 21.

[15-May-2020 09:17:27 America/Los_Angeles] Request URI: /zencart157b/index.php?main_page=gv_faq, IP address: 127.0.0.1
#1 require_once(C:\xampp\htdocs\zencart157b\includes\languages\english\gv_faq.php) called at [C:\xampp\htdocs\zencart157b\includes\modules\require_languages.php:23]
#2 require(C:\xampp\htdocs\zencart157b\includes\modules\require_languages.php) called at [C:\xampp\htdocs\zencart157b\includes\modules\pages\gv_faq\header_php.php:15]
#3 require(C:\xampp\htdocs\zencart157b\includes\modules\pages\gv_faq\header_php.php) called at [C:\xampp\htdocs\zencart157b\index.php:36]
--> PHP Notice: Undefined index: faq_item in C:\xampp\htdocs\zencart157b\includes\languages\english\gv_faq.php on line 23.`

On line 21, the comparison (==) should be an assignment (=).

**Comment by drbyte** [comment]
Thanks. Looks like it was an error introduced in #2920
