### ISSUE TITLE
Should target="_blank" include rel="noopener" or rel="_noreferrer"?

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#3466]
Lighthouse is a Chrome developer's tool (aka Google Lighthouse for Firefox).

It reports that instances of links going off-site and using target="_blank" could have a safety problem.

https://web.dev/cross-origin-resource-sharing/

Current version has 84 files with links that contain target="_blank".  Not all are cross-origin (bring in data from off-site to a new page).

Our additions of links to the new docs.zen-cart.com (admin/includes/languages/english.php and admin/includes/languages/english/modules.php are examples) have added to the number of files with this condition. Eight (8) files in all with the added target="_blank" going off-site to docs.

Most others are in footers for the site and emails.

It appears that the recommended correction is for links to Zen Cart of any type should be rel="noopener" and those to other than Zen Cart as rel="noreferrer".

The noopener ensures new window operation while noreferrer prevents load of the Referer header.

Submitted for discussion.

I can do the PRs but, would like to know if this is considered a priority at this point.

**Comment by drbyte** [comment]
Continuing the discussion:
Generally speaking, from an overall tech perspective, `noopener` is good to use everywhere that `_blank` is used. It is essential to use it where there's risk of the destination site attempting a hijacking. When used between internal or trusted resources this risk is much lower.

For `noreferrer` it's beneficial when you don't want to disclose where you came from, or want the visit to show up in analytics as a direct visit (not referred). This is usually wanted when linking to external services, such as goo gle maps or IP-address lookups, etc.

Here's what I'm thinking so far:
- for offsite links such as to product URLs linked from product pages or from banner ads, add `rel="noreferrer noopener"`.
- for ZC documentation/forum links, `noopener` is fine. 
- email: probably remove the `target="_blank"` altogether.
- do not add `nofollow`: let the storeowner decide if they want that, and they can do that manually
- ezpages and sitemap already have `rel="noreferrer noopener"`

Undecided about priority...
