### ISSUE TITLE
admin: keepalive_module add styles in the body

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3472]
This commit
https://github.com/zencart/zencart/commit/f80805fc50856dd27fd5fca5427abdf854f41bdf
adds css styles into the body instead of the head.
```
<style>
.jAlert {font-size: 1.5rem;}
.ja_btn {font-size: 1.5rem; padding: 15px !important;}
</style
```

**Comment by drbyte** [comment]
Only on pages that are not yet using the new `admin_html_head`

So the validator will be happier over time as refactors take place in next version.
