### ISSUE TITLE
admin testing of a hidden / development template

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3474]
as referenced by this merge
https://github.com/zencart/zencart/pull/2992

As far I as I can see, the only way this can work is if 
a) you define a template for **every** installed language: which is the active/current/working template.
b) Set the default template to be your hidden / development template: "new_template"
c) add your admin ip to website maintenance.
d) Then you may use 
&t=new_template
to see the default (now hidden) template

Correct?

I am revising the admin template_select page to clarify this, as I found the process very un-inituitive.

**Comment by scottcwilson** [comment]
Once you figure it out, if you could add a new entry to https://docs.zen-cart.com/user/template/ that would be great.

**Comment by torvista** [comment]
Hmmm, that wasn't quite the answer I was looking for!

Nonetheless I have already revised the page to include this information.

I was pondering if there should also be a &t=off, for example, to switch off the override?

**Comment by torvista** [comment]
ok, try this out: 
https://github.com/zencart/zencart/pull/3484

**Comment by drbyte** [comment]
Closed by #3484
