### ISSUE TITLE
PHP notice in Ask A Question

### ISSUE THREAD

**Issue by dennisns7d** [zencart/zencart#3478]
In the catalog, navigate to a product and click "Ask a Question". This results in the following PHP notice:
`[17-May-2020  10:13:55 America/Los_Angeles] Request URI:  /zencart157/index.php?main_page=ask_a_question&products_id=26, IP  address: 127.0.0.1 #1   require(C:\xampp\htdocs\zencart157\includes\templates\template_default\templates\tpl_ask_a_question_default.php)  called at  [C:\xampp\htdocs\zencart157\includes\templates\responsive_classic\common\tpl_main_page.php:178] #2   require(C:\xampp\htdocs\zencart157\includes\templates\responsive_classic\common\tpl_main_page.php)  called at [C:\xampp\htdocs\zencart157\index.php:97] --> PHP Notice: Undefined variable: telephone in  C:\xampp\htdocs\zencart157\includes\templates\template_default\templates\tpl_ask_a_question_default.php  on line 69.`

**Comment by drbyte** [comment]
Thanks
