### ISSUE TITLE
WhosOnline Destroying Session

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#3491]
After the first access of a populated Who's On Line from the admin, every attempt to enter or exit results in

 PHP Warning: session_decode(): Failed to decode session object. Session has been destroyed in /home/dibble/public_html/fribble/includes/classes/WhosOnline.php on line 350.

This only happens when there IS someone online and showing in the listing.  When no one is online and both the excludes are set to yes, there are no failures.

**Comment by drbyte** [comment]
I can't replicate this. I wonder if it's server-specific in terms of PHP session configuration settings and/or PHP addons that attempt to encrypt/"harden" session data?

**Comment by dbltoe** [comment]
![sepialiterature info](https://user-images.githubusercontent.com/5122886/82353328-e43c0580-99c4-11ea-9b32-2daa19f918db.png)
Can provide more info if needed.

**Comment by dbltoe** [comment]
I had not tested it when WhosOnline was first merged and would not have found it were it not for the log.

**Comment by scottcwilson** [comment]
I have seen this before but can't recall the specifics.

**Comment by dbltoe** [comment]
With spider enabled and no other onlines, all works as advertised.

**Comment by drbyte** [comment]
Yes, me too.

This time it seems it's happening only when the admin whos-online viewer tries to read the cart of a not-logged-in user. In that case it breaks the current admin session and throws the error.
