### ISSUE TITLE
Bring default country-address-format assignments up to date

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#35]
Many built-in country records have a default address-format assignment of '1' which is not always correct. 

We welcome input for updates, but with your update recommendation, please provide a URL to a website which offers official confirmation of the correct format you're proposing. 

We'll happily incorporate updates which can be officially confirmed. 

Thanks!

**Comment by jtwebsitedesign** [comment]
If we're good with this list, I can start updating the records in ZenCart?
http://bitboost.com/ref/international-address-formats.html#Formats

**Comment by drbyte** [comment]
Sure. 
If your findings suggest the need to create "new" formats, double-check other references to be certain one of the existing formats can't be used.

**Comment by jtwebsitedesign** [comment]
Ok, will do.

**Comment by jtwebsitedesign** [comment]
Since some countries were missing from the other link, I'm using this reference instead:
https://www.informatica.com/products/data-quality/data-as-a-service/address-verification/address-formats.html

A few questions as I'm running through this list:

1) Is this accurate formatting for ID 1-5 in v1.6?
https://www.zen-cart.com/wiki/index.php/Table_address_format#address_format_id

2) I see an ID 6 (UK) and ID 7 (Australia) in v1.6, but not sure of the actual address format for these ID's. Can you confirm?

3) I assume ID 3 is meant to have the country on the next line, as follows. Is that correct?
$firstname $lastname
$streets
$city
$postcode - $state
$country

4) Do the parenthesis in ID 4 indicate that the postcode will be hidden if not present? For example, Angola has a Locality but no Postcode. Not sure if we need a new format, or if ID 4 will suffice.

5) What to do for countries with "no standard address format" (for example, Afghanistan)?

**Comment by drbyte** [comment]
> 2) I see an ID 6 (UK) and ID 7 (Australia) in v1.6, but not sure of the actual address format for these ID's. Can you confirm?

Yes.

> 5) What to do for countries with "no standard address format" (for example, Afghanistan)?

I believe it just uses id:1 for that

**Comment by jtwebsitedesign** [comment]
Sorry, maybe my questions weren't clear. I see these formats in the following Wiki. But 6 and 7 are missing. Is this Wiki correct and up-to-date for ZC v1.6? What are the formats for 6 & 7?

https://www.zen-cart.com/wiki/index.php/Table_address_format#address_format_id

Default Entries

address_format_id:	1
address_format:	$firstname $lastname$cr$streets$cr$city, $postcode$cr$statecomma$country
address_summary:	$city / $country

address_format_id:	2
address_format:	$firstname $lastname$cr$streets$cr$city, $state $postcode$cr$country
address_summary:	$city, $state / $country

address_format_id:	3
address_format:	$firstname $lastname$cr$streets$cr$city$cr$postcode - $statecomma$country
address_summary:	$state / $country

address_format_id:	4
address_format:	$firstname $lastname$cr$streets$cr$city ($postcode)$cr$country
address_summary:	$postcode / $country

address_format_id:	5
address_format:	$firstname $lastname$cr$streets$cr$postcode $city$cr$country
address_summary:	$city / $country

**Comment by drbyte** [comment]
>  Is this Wiki correct and up-to-date for ZC v1.6? 

Probably not.

> What are the formats for 6 & 7?

You can see them in the address_formats table in the db, or in the install SQL:
```sql
INSERT INTO address_format VALUES (1, '$firstname $lastname$cr$streets$cr$city, $postcode$cr$statecomma$country','$city / $country');
INSERT INTO address_format VALUES (2, '$firstname $lastname$cr$streets$cr$city, $state    $postcode$cr$country','$city, $state / $country');
INSERT INTO address_format VALUES (3, '$firstname $lastname$cr$streets$cr$city$cr$postcode - $statecomma$country','$state / $country');
INSERT INTO address_format VALUES (4, '$firstname $lastname$cr$streets$cr$city ($postcode)$cr$country', '$postcode / $country');
INSERT INTO address_format VALUES (5, '$firstname $lastname$cr$streets$cr$postcode $city$cr$country','$city / $country');
INSERT INTO address_format VALUES (6, '$firstname $lastname$cr$streets$cr$city$cr$state$cr$postcode$cr$country','$postcode / $country');
INSERT INTO address_format VALUES (7, '$firstname $lastname$cr$streets$cr$city $state $postcode$cr$country','$city $state / $country');
```

**Comment by jtwebsitedesign** [comment]
Ah, perfect thanks!

I see the word "comma" after $state in 1 and 3, are those meant to be $cr line breaks?

**Comment by drbyte** [comment]
> I see the word "comma" after $state in 1 and 3, are those meant to be $cr line breaks?

In the function that applies these formats you'll see the `$statecomma` gets translated to the value of `state` followed by a `,` comma ;)

**Comment by jtwebsitedesign** [comment]
Thanks for confirming. So far, I've not found any countries that have the "State, Country" on one line. So it appears that ID 1 & 3 are not applicable as currently written.

**Comment by drbyte** [comment]
> @jtwebsitedesign wrote:
> 4. Do the parenthesis in ID 4 indicate that the postcode will be hidden if not present? For example, Angola has a Locality but no Postcode. Not sure if we need a new format, or if ID 4 will suffice.

No, from what I'm seeing, the parentheses will be output as-is. Not hidden. So, if there was no postcode between the parentheses they would just show up as `()`.

**Comment by drbyte** [comment]
@jtwebsitedesign Did you ever finish the compare?

**Comment by jtwebsitedesign** [comment]
Unfortunately no, I never quite found the time.

**Comment by drbyte** [comment]
Yes, it'd be great to look into this; thanks!

Responding to your questions:

1. I guess leave it as-is. Perhaps gather a list of notes about such exceptions for community review.
2. New is fine, as long as it's necessary. I'm hoping it doesn't result in creating dozens more.
3. Standard practice is two parts: generate upgrade syntax for the upgrade sql, and also to directly update the original install sql which gets used on new installs.
4. Nothing stands out at this moment.

**Comment by brittainmark** [comment]
I have been through all the countries and tried to fit them as best as possible to the existing definitions.
Below is my analysis and proposed settings. I have added the different address format codes after the groups. All of the countries except Spain were in address format 1 that needed changing. 

**Countries not defined :** All currently set to 1: `$firstname $lastname$cr$streets$cr$city, $postcode$cr$statecomma$country`
Afghanistan; Antarctica; Bouvet Island; British Indian Ocean Territory; Cape Verde; Costa Rica; Cuba; Iraq; Korea; Democratic People's Republic of; Mongolia; Nicaragua; Saint Vincent and the Grenadines; Seychelles; St. Pierre and Miquelon; Timor-Leste; Virgin Islands (British)

**Countries defined as 1:** `$firstname $lastname$cr$streets$cr$city, $postcode$cr$statecomma$country`
Myanmar; Somalia  : Has no state
Nigeria	: Has country on a new line :` $firstname $lastname$cr$streets$cr$city, $postcode$cr$state$cr$country`

**Countries defined as 2:**` $firstname $lastname$cr$streets$cr$city, $state    $postcode$cr$country`
American Samoa; Bermuda; Canada; Cayman Islands; China; Colombia; Guam; Indonesia; Japan; Jordan; Korea, Republic of; Latvia; Lebanon; Lesotho; Marshall Islands; Micronesia, Federated States of; Northern Mariana Islands; Palau; Puerto Rico; United States; United States Minor Outlying Islands; Virgin Islands (U.S.)

**Countries defined as 3:** `$firstname $lastname$cr$streets$cr$city$cr$postcode - $statecomma$country`
El Salvador; India
Guatemala : Has country on a new line :` $firstname $lastname$cr$streets$cr$city$cr$postcode - $state$cr$country`

**Countries defined as 4:** Brackets should be removed from this format: `$firstname $lastname$cr$streets$cr$city ($postcode)$cr$country`
Singapore; Taiwan

**Countries defined as 5:** `$firstname $lastname$cr$streets$cr$postcode $city$cr$country`
Åland Islands; Albania; Algeria; Andorra; Argentina; Armenia; Austria; Azerbaijan; Belarus; Belgium; Bosnia and Herzegowina; Bulgaria; Chile; Croatia; Cyprus; Equatorial Guinea; Estonia; Ethiopia; Faroe Islands; Finland; France; French Guiana; French Polynesia; French Southern Territories; Germany; Greece; Greenland; Guadeloupe; Guinea; Guinea-bissau; Haiti; Heard and Mc Donald Islands; Honduras; Iceland; Iran (Islamic Republic of); Israel; Italy; Kuwait; Lao People's Democratic Republic; Liberia; Liechtenstein; Luxembourg; Macedonia, The Former Yugoslav Republic of; Madagascar; Martinique; Mayotte; Moldova; Monaco; Montenegro; Morocco; Mozambique; Netherlands; New Caledonia; New Zealand; Norway; Paraguay; Philippines; Poland; Portugal; Réunion; Romania; San Marino; Saudi Arabia; Senegal; Slovenia; Sri Lanka; Sudan; Svalbard and Jan Mayen Islands; Sweden; Switzerland; Syrian Arab Republic; Tajikistan; Tokelau; Tunisia; Turkmenistan; Uruguay; Wallis and Futuna Islands; Zambia

**Countries defined as 5:** Has a sorting code after city I think these can be left as 5
Czech Republic; Denmark; Slovakia (Slovak Republic)

**Countries defined as 5:** Has postcode on a separate line :$firstname `$lastname$cr$streets$cr$postcode$cr$city$cr$country `
Ecuador; Georgia

**Countries defined as 5:** Has state on a new line : `$firstname $lastname$cr$streets$cr$postcode $city$cr$state$cr$country`
Tanzania, United Republic of; Malaysia; Mexico; Panama

**Countries defined as 5:** Other
Spain	: Province (state) in brackets () : `$firstname $lastname$cr$streets$cr$postcode $city ($state)$cr$country`
Serbia	: Has a [PAK] number after city. I don't know what this, it is does not seem to be required when I check against Royal Mail Addressing standards

**Countries defined as 6:** `$firstname $lastname$cr$streets$cr$city$cr$state$cr$postcode$cr$country`
Anguilla; Brazil; Dominican Republic; Egypt; Falkland Islands (Malvinas); Guernsey; Hungary; Ireland; Isle of Man; Jersey; Kazakhstan; Kenya; Malta; Nauru; Pitcairn; Russian Federation; South Africa; South Georgia and the South Sandwich Islands; St. Helena; Swaziland; Thailand; Turks and Caicos Islands; Ukraine; United Kingdom; Uzbekistan

**Countries defined as 6:** Has no postcode  
Angola; Antigua and Barbuda; Aruba; Bahamas; Barbados; Belize; Benin; Bolivia; Bonaire, Sint Eustatius and Saba; Botswana; Burkina Faso; Burundi; Cameroon; Central African Republic; Chad; Comoros; Congo; Cook Islands; Côte d'Ivoire; Curaçao; Djibouti; Dominica; Eritrea; Fiji; Gabon; Gambia; Ghana; Gibraltar; Grenada; Guyana; Hong Kong; Jamaica; Kiribati; Libya; Macao; Malawi; Mali; Mauritania; Mauritius; Montserrat; Namibia; Niger; Niue; Palestine, State of; Peru; Qatar; Rwanda; Saint Lucia; Samoa; Sao Tome and Principe; Sierra Leone; Sint Maarten (Dutch part); Solomon Islands; South Sudan; Suriname; Togo; Tonga; Trinidad and Tobago; Tuvalu; Uganda; Vanuatu; Western Sahara; Yemen; Zimbabwe

**Countries defined as 7:**` $firstname $lastname$cr$streets$cr$city $state $postcode$cr$country`
Australia; Bahrain; Bangladesh; Bhutan; Christmas Island; Cocos (Keeling) Islands; Norfolk Island; Pakistan

**Countries defined as 7:** With state on new line with postcode : `$firstname $lastname$cr$streets$cr$city$cr$state $postcode$cr$country`
Brunei Darussalam; Cambodia; Lithuania; Nepal; Papua New Guinea

**Countries defined as 7:** Hasno postcode
Saint Kitts and Nevis

**Countries with unique codes:**
Kyrgyzstan: `$country$cr$postcode $city$cr$state$cr$streets$cr$firtsname $lastname`
Maldives: `$firtsname $lastname$cr$streets$cr$state $city $postcode$cr$country `
Oman: `$firtsname $lastname$cr$streets$cr$postcode$cr$city$cr$state$cr$country`
Turkey: `$firtsname $lastname$cr$streets$cr$postcode/$city/$state$cr$country `
United Arab Emirates: `$firtsname $lastname$cr$streets$cr$state,$country`
Venezuela: `$firtsname $lastname$cr$streets$cr$city $postcode,$state$cr$country`
Viet Nam: `$firtsname $lastname$cr$streets$cr$city-$postcode$cr$country `

Before I commit to coding these I thought I would put them out there for people to see. 
If a field is missing like postcode does it get ignored and therefore could stay in the group? see Countries defined as 6: but no postcode above for example.

Not sure If I have missed something. What is the last element '$city / $country' address_summary used for?
INSERT INTO address_format VALUES (1, '$firstname $lastname$cr$streets$cr$city, $postcode$cr$statecomma$country','$city / $country');

Is it just a description of the address type?

If/when I code the changes do you want the value to be changed only if it was set to its original value? In nearly all cases 1. This will avoid changing values that someone has changed on their database?

It might also be useful for someone to pick a few random countries and see if they agree with my choices.

Get back to me when you can and let me know how you would like me to proceed.

**Comment by torvista** [comment]
Well, that's a lot of work you have contributed.

I would disagree with Spain, I've never seen a province in brackets, and the example from the reference page doesn't either.
Madrid in this example is the province and the city!
![Clipboard01](https://user-images.githubusercontent.com/4391026/118715097-82a2b700-b823-11eb-9695-67b7b94887ff.gif)

I have always used format 3, that's good enough.

**Comment by brittainmark** [comment]
Fine by me is the province never entered? I assumed that Madrid was the city "locality".
Did you look at any others?

**Comment by torvista** [comment]
That is a poor example as the capital Madrid is the same as the province the "Comunidad de Madrid" so one would not put both.
I would have thought the most common format to suit all but the weirdest, would just be the address fields in order
Street
Town (address line 2)
Province
Postcode
Country
since postal services will process from the bottom up as the item gets closer to the destination.

**Comment by brittainmark** [comment]
That is address format 6 that we use in the uk
For info Royal mail provide the following example for spain.
Sra Ana Jimenez
Mimbreras 4
03201 ELCHE (Alicante)
SPAIN
