### ISSUE TITLE
Attribute Images upload problem

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#3511]
1.5.7 load with demo and nothing else.

Demo Product ID 2  Attribute ID 6  Attribute Images Enabled

Attributes Controller allows selection of an image and reports that the image has been added to the attribute.

No yellow dot next to the attribute after update and no file is registered in the database.  The file DOES get uploaded to the images/attributes folder.

There is no option to type in a file name although the docs say it is an option.

**Comment by dbltoe** [comment]
It's also interesting that, apparently, the Configuration > Attributes Settings > Enable Attribute Images was defaulted to false even though line 2705 of the mysql_zencart.sql says it should have been set to true.

I thought this could have been from using other than the latest (yesterday) merge. But I checked and I had used the latest merge.  Yet when the images first did not work, I had to go to Attribute Settings to turn them on.  !?!

**Comment by scottcwilson** [comment]
> It's also interesting that, apparently, the Configuration > Attributes Settings > Enable Attribute Images was defaulted to false even though line 2705 of the mysql_zencart.sql says it should have been set to true.

Mine is set to *true*, from a database created 2 minutes ago.

**Comment by Zen4All** [comment]
> There is no option to type in a file name although the docs say it is an option.

Noticed this too, but there never was in any version. Would be a good feature to add.

**Comment by scottcwilson** [comment]
> There is no option to type in a file name although the docs say it is an option.

Would you please point me to the file that needs fixing?

**Comment by dbltoe** [comment]
> > It's also interesting that, apparently, the Configuration > Attributes Settings > Enable Attribute Images was defaulted to false even though line 2705 of the mysql_zencart.sql says it should have been set to true.
> 
> Mine is set to _true_, from a database created 2 minutes ago.

Can ALMOST swear I never touched it BUT, not the real problem.

**Comment by dbltoe** [comment]
> There is no option to type in a file name although the docs say it is an option.

Let's just completely remove this line of additional/supplemental information and focus on the rest of the issue (the real problem).  Sometimes, my adding all the steps taken in discovering/recreating a problem seems to muddy the waters and detract from the main premise.

**Adding an image to an attribute in the latest merge does not work.**

**Comment by scottcwilson** [comment]
> Adding an image to an attribute in the latest merge does not work.

Reproduced.

**Comment by scottcwilson** [comment]
Root cause: $_POST['attributes_image'] is not set, but the required data *is* in $_FILES. 
Change admin/attributes_controller.php around line 424 to look for data in $_FILES? 
@torvista Would you please check?  Recent changes to this file were by you.

**Comment by torvista** [comment]
ok

**Comment by torvista** [comment]
It's actually working but the default "delete image" is always set to true.

**Comment by scottcwilson** [comment]
Verified.  Thanks guys.
