### ISSUE TITLE
Added Information on Accessibility

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#3525]
This would be an added item under https://docs.zen-cart.com/user/template/
I would recommend placement as item 1 or 2 considering its impact on SEO and customer satisfaction.
Not sure all formatting is correct.  Still trying to get my head around that. Couldn't find info on weight.
[accessibility.txt](https://github.com/zencart/zencart/files/4671433/accessibility.txt)

**Comment by scottcwilson** [comment]
Fantastic, thank you!   Only two small markdown issues: 
- weight should be 10 for alphabetic sorting (see https://github.com/zencart/documentation/blob/master/CONTRIBUTING.md)
- Put a space after the # signs for headers.
It's a pain working with Markdown at first - takes a while to get used to it.

You can see your good work at 
https://docs.zen-cart.com/user/template/accessibility/

**Comment by scottcwilson** [comment]
@drbyte Please close. 
@dbltoe You can open issues in the doc repo if you like - it's a bit faster. 
https://github.com/zencart/documentation
