### ISSUE TITLE
input type = number doubts

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#3527]
https://github.com/zencart/zencart/blob/ad51bfdefa16b5b8f82eff76caa4251ad83bf8e0/admin/includes/functions/html_output.php#L256
Has this been tested properly? As far as I know type 'number' can only be used if the decimal is a dot. There are a lot Zen Cart of setups where the local usage is a comma for the decimal separator in valuta.
Not sure if this is a problem in the admin, but made me wonder.

**Comment by drbyte** [comment]
Passing `price` isn't (yet) implemented anywhere in core code, but I've been using it in production for some english-speaking sites and it has stopped a lot of accidental data-entry errors (eg. entering product prices).

I'm also aware that some stores store prices to 4 decimal places, so using `price` wouldn't work for them the way this is implemented, but adding `price4` or something as another `$type` could be an option.

**Comment by Zen4All** [comment]
Thanks for checking 👍
