### ISSUE TITLE
Help with input labels on all, new, and featured

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#3528]
My original "test" site was all priced by so I missed some labels.  Trying to work up a PR but brain dead on code.

For all, new, and featured all listings.   Where productID = 117, the goal is:

Add: `<label for="products_id[117]">products_id[117]</label><input type="text" name="products_id[117]" value="0" size="4">`

Proposed below is not correct.  Looking for assistance and correction of line 91 of includes/templates/responsive_classic/templates/tpl_modules_products_all_listing.php.
 
```php
 $link = TEXT_PRODUCT_ALL_LISTING_MULTIPLE_ADD_TO_CART . 
"<label for=" . $products_all->fields['products_id'] . "> . $products_all->fields['products_id'] . "</label>
<input type=\"text\" name=\"products_id[" . $products_all->fields['products_id'] . "]\" value=\"0\" size=\"4\" />";
```

**Comment by scottcwilson** [comment]
Maybe something like 
<span class="sr-only"><?php echo TEXT_PRODUCT_ALL_LISTING_MULTIPLE_ADD_TO_CART . 'products_id[' . $products_all->fields['products_id'] . ']'; ?></span>

**Comment by dbltoe** [comment]
have to have the <label> to meet requirement.
Just trying to get code propagated by variable.

**Comment by drbyte** [comment]
"meeting the requirement" is one thing (ie: add a `<label>` containing random text)

Making the label semantically relevant is another. It should visually add something useful, not distract from usefulness, not clutter the display, and generally make sense.
Even when the same kind of element is repeated many times on the page.

In that regard, what are you envisioning this `<label>` should actually contain? And how to prevent the new element from making the page a visual mess?

**Comment by drbyte** [comment]
Update: I do realize you're essentially wanting the changes that were done for regular product-listing to be reflected in these other listing views.

In that regard, the same code changes would apply, eg:

```diff
-$link = TEXT_PRODUCT_ALL_LISTING_MULTIPLE_ADD_TO_CART . "<input type=\"text\" name=\"products_id[" . $products_all->fields['products_id'] . "]\" value=\"0\" size=\"4\" />";
+$link = TEXT_PRODUCT_ALL_LISTING_MULTIPLE_ADD_TO_CART . "<input type=\"text\" name=\"products_id[" . $products_all->fields['products_id'] . "]\" value=\"0\" size=\"4\" aria-label=\"' . ARIA_QTY_ADD_TO_CART . '\">";
```

I still worry that the semantic meaning is somewhat lost, even though the field has a label. Hopefully other nearby context lets them know "what" they're adding to cart.

**Comment by dbltoe** [comment]
Yeah, agree.  Kind of a "Do me right or do me wrong but, just do me."  Should have caught them earlier.  Just want to stop the accessibility "bleeding" on those three pages.

Family today.  PR later.

**Comment by drbyte** [comment]
@dbltoe 
Which is better for the label?
- `ARIA_QTY_ADD_TO_CART`
  **which reads as:** `aria-label="Enter quantity to add to cart"`

- `TEXT_PRODUCT_ALL_LISTING_MULTIPLE_ADD_TO_CART . "products_id['" . (int)$products_all->fields['products_id'] . "]'`
  **which reads as:** `aria-label="Add: products_id[345]"`

**Comment by dbltoe** [comment]
If  this is what you are saying for 138 in includes/modules/responsive_classic/product_listing.php the checker doesn't like it. 
I may have munged up when adding your code as well.
`$lc_button = '<div class="list-input"><span class="list-addtext">' . TEXT_PRODUCT_LISTING_MULTIPLE_ADD_TO_CART . "products_id{'" . (int) $products_all->fields['products_id'] ."]' </span><input type="text" name="products_id[' . $listing->fields['products_id'] . ']" value="0" size="4" aria-label="' . ARIA_QTY_ADD_TO_CART . '"></div>';`
