### ISSUE TITLE
Asset caching optimization

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#353]
TODO: Test and verify that the http headers being sent for images, css, js all have proper future-dated expiry, etc

What improvements, if any, are needed for the .htaccess asset optimization rules provided in the /images/ and /includes/templates/ folders? And why, specifically

**Comment by barco57** [comment]
Avoid expecting the server to be setup with Etags turned on in Apache, particularly where cPanel recommends Etags=off for PCI compliance.
