### ISSUE TITLE
Search function in attributes controller seems to be useless

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#3530]
While working on some last minute UI updates, I was testing the search box.
No matter what i type in, the search always returns empty.
Furthermore, the file name in the form goes to category_product_listing, instead of attributes_controller.
Working on a PR to solve this.

**Comment by Zen4All** [comment]
Looking through the code, there seems to be nothing to do a search.

**Comment by scottcwilson** [comment]
Might have been accidentally deleted when it was restructured - @torvista any thoughts?

**Comment by Zen4All** [comment]
going to take a look at older ZC versions

**Comment by Zen4All** [comment]
Looking at ZC 1.5.5, and ZC 1.5.6, The code for this is almost the same, and there is no code to do a search.

Apparently nobody uses the search box on the attributes page, as I can not recall any complaints.

Any objectives to just remove the search box?

I suspect the search box is an old remnant for OsC, where the attributes page was loaded as part of an other page, that did contain the search code.

**Comment by scottcwilson** [comment]
Seems to work in 1.5.4.  Try searching for "memory" on the test data set.

**Comment by scottcwilson** [comment]
Root cause: zen_draw_form() clobbers the $_GET['cmd'] variable when called with method = 'get'. 
It's a small fix, done in a minute.

**Comment by torvista** [comment]
I don't see the point of the search form, it returns a product/category listing from another page. 
What's that got to do with attributes?

I would remove it.

**Comment by scottcwilson** [comment]
Here's a possible use case: 
- I want to edit the attributes on some product.  
- I have a deep category hierarchy and can't remember which category the product is in.
- I search for the product, get the listing, and then press the "A" icon to restart the attributes controller. 

Bear in mind that this worked in 1.5.6 and prior.

**Comment by Zen4All** [comment]
> Here's a possible use case:
> 
> * I want to edit the attributes on some product.
> * I have a deep category hierarchy and can't remember which category the product is in.
> * I search for the product, get the listing, and then press the "A" icon to restart the attributes controller.
> 
> Bear in mind that this worked in 1.5.6 and prior.

Ok, not how I would do it, but that's just my opinion, and I am only one of many users. All with their own workflows.

If the search indeed goes to the category listing, the reset button, and search word result, code can also be eliminated
