### ISSUE TITLE
Possible problem: duplicate admin_profile names

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#3540]
There's no "unique" index on the `admin_profiles` table.
This means someone can insert multiple entries of the same name, but have different controls associated with them.

Adding a unique index to the table solves the problem of potential ambiguity.

PROBLEM: existing data 
If there are already duplicates in the table then adding the unique index will fail.

Question: How many storeowners are likely to have created multiple same-named-profiles?

**Comment by drbyte** [comment]
Side-problem: we made the field varchar(255) instead of varchar(191) and thus setting an index requires either changing the field length to be shorter "first", or setting an index of a specified length(not desirable).

So, to add the index I envision an upgrade statement being 2 parts, like this:

```sql
ALTER TABLE admin_profiles MODIFY profile_name varchar(191) NOT NULL default '';
ALTER TABLE admin_profiles ADD UNIQUE idx_profile_name_zen (profile_name);
```

**Comment by wiztechinc** [comment]
The email address is frequently duplicated - more than the same user name. If there is guards against this now, great but I see this often after upgrades and them having issues. In fact I don't recall ever seeing the user name duplicated.

**Comment by barco57** [comment]
"The email address is frequently duplicated" - I also see this all the time, then they wonder why they have problems resetting the admin password

**Comment by drbyte** [comment]
Can either/both of you contribute to a new issue related to the Admin Email Address?
This discussion should be taken there, as it's completely unrelated to the "admin profile name" (like "Superuser" or "Order Processing") that this issue is referring to.

Note that the Admin email address was intentionally allowed to be non-unique. But if there are problems with that, let's discuss and fix. (I can see where pwd resets could be troublesome, but what else?) Again, let's discuss in an issue dedicated to that subject.
