### ISSUE TITLE
Can't add/update product with new product.php

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#3543]
Was having problems with alpha and thought it might be the DB.  Meanwhile, beta arrives.
Load beta and demo with nothing else.
Go to Categories/Products
Click on hardware, then CDROM Drives.
Click New Product.
When info is added click Preview
Blank form and error.
![adminProduct](https://user-images.githubusercontent.com/5122886/83234906-aa05fd00-a156-11ea-89d4-cc0dc2abd425.png)

**Comment by dbltoe** [comment]
Something in #3514 is not playing well with others.

**Comment by zcwilt** [comment]
See comments on #3514

**Comment by scottcwilson** [comment]
Thanks for taking the time to narrow this down.  (And for catching this in the first place!)
