### ISSUE TITLE
Duplicate email addresses for admin users makes forgot password fail

### ISSUE THREAD

**Issue by wiztechinc** [zencart/zencart#3546]
If more than one admin user has the same email address, the cart does not send out a forgot password email, leading the cart owner to think the cart is broken.

**Comment by drbyte** [comment]
Currently it sends a reset token to the FIRST admin user in the db that has that email address (according to whatever sort-order the db decides, which is usually creation order).

**Comment by drbyte** [comment]
Question: WHY are people forgetting their password? Is it because they're rarely using it?

**Comment by wiztechinc** [comment]
Like I said before, I know this happened in past versions but have no clue if it works now.

**Comment by wiztechinc** [comment]
> Question: WHY are people forgetting their password? Is it because they're rarely using it?

I wish I could tell you that folks have their act together but they frequently don't. I gather lots of folks just ship based on the order email. So they don’t log in often and sometimes the owners use employees to manage things and rarely log in. You cannot imagine how flustered some folks get when presented with the change your password scenario.

**Comment by drbyte** [comment]
> You cannot imagine how flustered some folks get when presented with the change your password scenario.

Oh, I can. They sure do.

What I'm seeking to understand here is the root causes so we can find a solution that is both user-friendly to those who have limited understanding, but still actually continues to keep their account secure.

**Comment by drbyte** [comment]
Options: 
- Could send a new token to ALL admin accounts having that email address. So that would send multiple emails to the same address, but without the Admin Username. So they'd probably be equally confused.
- Could also include the Admin Username, but then the email contains COMPLETE ACCESS to the Admin for anyone who's hacked the email account. Or, if it's a generic email address (ie: sales@example.com) then ALL staff suddenly get all the credentials.
- Stop allowing repeated email addresses. But that makes things more complicated.
- Leave as-is.

**Comment by wiztechinc** [comment]
As long as an email does go out, I really don’t think much more is necessary. It would be nice if they were  alerted  to the fact there’s more than one admin with the same email address. But the problems only arose when no emails went out. When did this get fixed?

**Comment by lat9** [comment]
> 
> 
> Options:
> 
>     * Stop allowing repeated email addresses. But that makes things more complicated.

Although it makes the change "more complicated" (like what do you do when there are multiple email addresses), I believe that this is the best forward-going option.

**Comment by barco57** [comment]
if it is sending to the first of the duplicate email addresses it finds but they really want to reset the password for an admin username of one of the other duplicates they can't figure out why it doesn't work. Why they have duplicates, I have no idea, can't fix stupid. why are they forgetting their password...see previous sentence.

**Comment by wiztechinc** [comment]
> > Options:
> > ```
> > * Stop allowing repeated email addresses. But that makes things more complicated.
> > ```
> 
> Although it makes the change "more complicated" (like what do you do when there are multiple email addresses), I believe that this is the best forward-going option.

Yes, but....most of my clients are upgrading,  not establishing new stores.

**Comment by dbltoe** [comment]
In the interest of the "who screwed it up" inquiry, I'd think any admin would appreciate the ability to say they were not the one with that e-mail/username.
I say unique.

**Comment by lankeeyankee** [comment]
I am surprised to learn you can have multiple admins with a single email. It never occurred to me to even try. It seems very odd to me that this is allowed behavior. Is it that much hardship to have people change it for those that are using this method? My vote would be unique.

**Comment by lat9** [comment]
> 
> 
> > > Options:
> > > ```
> > > * Stop allowing repeated email addresses. But that makes things more complicated.
> > > ```
> > 
> > 
> > Although it makes the change "more complicated" (like what do you do when there are multiple email addresses), I believe that this is the best forward-going option.
> 
> Yes, but....most of my clients are upgrading, not establishing new stores.

... and that's one of the _complications_.  What I was thinking was to alert/nag on `superuser` login (_once per session_) via messageStack and email to the store-email of the condition.
