### ISSUE TITLE
zc157-beta: Display Logs missing from admin menus

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#3552]
I just did a fresh install of the zc157-beta and don't see "Display Logs" in the Tools dropdown.  Did I miss something?  There are logs (that I've copied) in the /logs directory.

**Comment by lat9** [comment]
Oh, I see (now) that it has to be installed first.  What's with that?

**Comment by Zen4All** [comment]
I think the idea is that it can be used as a demo for other mod developers

**Comment by wiztechinc** [comment]
holy crap, is the plugin manager as simple as it appears? Display logs looks good by the way. Can't  wait to see it in major action when things gets really bad.....

**Comment by drbyte** [comment]
> holy crap, is the plugin manager as simple as it appears?

Yes, but it only works so far for admin-only plugins (nothing for catalog-side).

**Comment by wiztechinc** [comment]
yep, can see that but most of the mods I use are only admin side. I'm now salivating for more - a template install system........ one can dream about the future! And this can give me something to do - converting some mods.

**Comment by zcwilt** [comment]
There are some real challenges in getting the plugin system working for catalog side code (although not insurmountable). I'm hoping to post something soon regarding the catalog side.

**Comment by scottcwilson** [comment]
Should this be closed?
