### ISSUE TITLE
zen_update_orders_history error

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#3558]
This morning, I'm getting

> [03-Jun-2020 11:42:21 UTC] PHP Fatal error: Uncaught Error: Call to undefined function zen_update_orders_history() in /includes/modules/payment/paypal/paypal_functions.php:648
Stack trace:
#0 /ipn_main_handler.php(470): ipn_update_orders_status_and_history('5291', '1', 'parent')
#1 {main}
thrown in /includes/modules/payment/paypal/paypal_functions.php on line 648

>[03-Jun-2020 11:42:21 UTC] Request URI: /ipn_main_handler.php, IP address: 173.0.81.1
--> PHP Fatal error: Uncaught Error: Call to undefined function zen_update_orders_history() in /includes/modules/payment/paypal/paypal_functions.php:648
Stack trace:
#0 /ipn_main_handler.php(470): ipn_update_orders_status_and_history('5291', '1', 'parent')
#1 {main}
thrown in /includes/modules/payment/paypal/paypal_functions.php on line 648.

Order 5921 is posted and completed as normal.  It was posted on 5/27/2020 and appears to have been triggered by a customer checking order history/status.

**Comment by scottcwilson** [comment]
Check your copy of `includes/functions/functions_osh_update.php`.  That's where `zen_update_orders_history` is defined.

**Comment by dbltoe** [comment]
File is there and matches latest beta.
Line 38 is there.
Wondering if EMP holdover could be part of the problem as I get WHOOPS when trying to place an order as a customer.  I know EMP was there before 1.5.7

**Comment by scottcwilson** [comment]
Is this happening on a 1.5.7 test store?

**Comment by dbltoe** [comment]
yep

**Comment by dbltoe** [comment]
Not finding any of the old EMP files on the site.

**Comment by scottcwilson** [comment]
The smallest possible fix would be to modify 
includes/modules/payment/paypal/paypal_functions.php
to define zen_update_orders_history
as is done in includes/modules/payment/square.php 
lines 1283-1296.  

But I kinda hate the fact that this little function is defined in two places already. 
It would be nice to consolidate this repetition, put the function alone by itself in a file, and include that file. 

@drbyte what say you?

**Comment by zcwilt** [comment]
Catalog side `functions_osh_update.php` is loaded in `config.core.php` at breakpoint 60
However it is not loaded in `paypal_ipn.core.php`

It may not be as simple as just loading `functions_osh_update.php` in `paypal_ipn.core.php` as we would have to look at the function dependencies, especially the globals definitions (and other function calls) to ensure they are set in a manner that is expected.

**Comment by scottcwilson** [comment]
In this code path, application_top.php is not included.

**Comment by zcwilt** [comment]
Still loads application_top.php line 113

**Comment by lat9** [comment]
> 
> 
> Catalog side `functions_osh_update.php` is loaded in `config.core.php` at breakpoint 60
> However it is not loaded in `paypal_ipn.core.php`
> 
> It may not be as simple as just loading `functions_osh_update.php` in `paypal_ipn.core.php` as we would have to look at the function dependencies, especially the globals definitions (and other function calls) to ensure they are set in a manner that is expected.

I believe that it's safe to load (as in the `config.core.php`) the `functions_osh_update.php` in the `paypal_ipn.core.php` file prior to the `functions_general.php`.

**Comment by drbyte** [comment]
I've updated the `paypal_ipn.core.php`. As lat9 said I believe it should be safe to load there.

**Comment by scottcwilson** [comment]
> Still loads application_top.php line 113

Sure enough!  I didn't look down that far.  It would be nice to refactor out these two separate lines into one, at the top of the file as is the general practice.
