### ISSUE TITLE
Plugin manager unique_key is to short

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#3564]
In the database there are several unique_key fields in the new plugin tables. The length of these fields is set to varchar(20), which in my opinion is to short. My proposal would be to increase the size to at least varchar(32).

**Comment by zcwilt** [comment]
Hi. 
Working on an update to the plugin control schema now to support a contribution id (for update checking)
Will incorporate this change with that.

**Comment by Zen4All** [comment]
thx
