### ISSUE TITLE
Option: Allow customer "upload" from cloud storage services like dropbox chooser or filepicker.com

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#357]
Consider implementing support to allow customers to submit images using online services such as:
https://www.filepicker.com
https://www.dropbox.com/developers/chooser
(ie: instead of uploading attachments)

**Comment by jtwebsitedesign** [comment]
Yes! This would be a BIG feature for a lot of stores. Especially those that specialize in arts/media and need uploads in excess of 100mb (I've had this request a few times!). I'm a big fan of Dropbox, good API documentation too.
