### ISSUE TITLE
Plugin Manager displaying 'Countries' instead of 'Plugins'

### ISSUE THREAD

**Issue by dennisns7d** [zencart/zencart#3570]
The Plugin Manager is displaying "Displaying **1** to **10** (of **12** Countries)" at the bottom of the page. I think that it should display the appropriate units (Plugins).

The TEXT_DISPLAY_NUMBER_OF_COUNTRIES constant is used in admin/includes/templates/table_view.php instead of something appropriate for the current page.

**Comment by drbyte** [comment]
Thanks @dennisns7d
