### ISSUE TITLE
zc157: DEBUG_AUTOLOAD no longer works

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#3574]
Noting that the code that _used to_ provide that output has been removed from the zc157 version of `/includes/autoload_func.php`.

**Comment by lat9** [comment]
Noting, too, that the `init_script` and `classInstantiate` 'autoType's  are no longer processed by that module.  Where did that processing go?

**Comment by zcwilt** [comment]
I'll add back some debug stuff. it's possible to get some debug output already. 
In application_top.php just after 

`$initSystem = new InitSystem('catalog', $loaderPrefix, FileSystem::getInstance(), $pluginManager, $installedPlugins);`

and before 

`$loaderList = $initSystem->loadAutoLoaders();`

add `$initsystem->setDebug(true);`

Note also processing for `init_script` and `classInstantiate` are handled in the InitSystem class.

**Comment by lat9** [comment]
That's part of the issue, @zcwilt.  The other issue is that the `class` auto-loader type now _presumes_ (incorrectly in some cases) that the class-instantiation's name is based on the file name.  Not true in the issue I referenced above and for other of my plugins.

**Comment by lat9** [comment]
Here's the auto-loader for the `product_pagination` plugin:
```php
<?php
// -----
// Part of the "Products Pagination" plugin by lat9 (lat9@vinosdefrutastropicales.com)
//
if (!defined('IS_ADMIN_FLAG')) {
    die('Illegal Access');
}

// -----
// There's a bit of trickiness going on here.  The base split_page_results class has been modified so that
// it won't load if the database configuration hasn't been read, so need to load the class again
// after the database reads have been done and the session is established so that the class is defined.
//
// Since that class uses a common function provided by the pagination observer, the split_page_results
// class needs to be loaded after that.
//
$autoLoadConfig[117][] = array (
    'autoType' => 'class',
    'loadFile' => 'split_page_results.php'
);

$autoLoadConfig[116][] = array (
    'autoType' => 'class',
    'loadFile' => 'observers/class.products_pagination_observer.php'
);

$autoLoadConfig[116][] = array (
    'autoType'   => 'classInstantiate',
    'className'  => 'products_pagination_observer',
    'objectName' => 'ppObserver'
);
```

That plugin makes modification to the `split_page_results` class but doesn't 'know' it needs to override until the database is loaded.  The updated class looks for the instance of `$ppObserver` to determine whether/not to reload the class-definition.  Apparently, that `classInstantiate` is either not being run or it's creating an object of a different name.

**Comment by lat9** [comment]
Noting also that `version.php` is no longer guaranteed to load first:
```
  0 => 
  array (
    'type' => 'include',
    'filePath' => 'C:/xampp/htdocs/zc157a/includes/classes/OnePageCheckout.php',
  ),
  1 => 
  array (
    'type' => 'include',
    'filePath' => 'includes/version.php',
  ),
```

**Comment by lat9** [comment]
The `product_pagination` issue is caused by the introduction of `include_once` and `require_once` in zc157's `autoload_function.php`:
```php
    switch ($entry['type']) {
        case 'include':
            //echo 'case "include": ' . $entry['filePath'] . "<br>\n";
            include_once $entry['filePath'];
            break;
        case 'require':
            //echo 'case "require": ' . $entry['filePath'] . "<br>\n";
            require_once $entry['filePath'];
            break;
```
That plugin needs to be able to load that class-file twice.

**Comment by drbyte** [comment]
> That plugin needs to be able to load that class-file twice.

Reloading the same class file twice may "work", but is kinda an antipattern. Is there another way for that plugin to extend the pagination so its features can be used as overrides?  

IIRC its changes are in the generated HTML output, for which we could extract a template or something that would suit for allowing markup to be varied for various reasons. (Apologies if I'm mixing up plugins in my recollection)

**Comment by zcwilt** [comment]
As @drbyte said, double loading a class is an anti-pattern with possible side-effects.
However for now I've added the ability to force load a class only.
In a class config in the autoloader you can do 

```
$autoLoadConfig[117][] = array (
    'autoType' => 'class',
    'loadFile' => 'split_page_results.php',
    'forceLoad' => true
);
```

I would however like to deprecate this during v158 and better understand how we can provide hooks/notifiers to support your plugin.

**Comment by zcwilt** [comment]
> That's part of the issue, @zcwilt. The other issue is that the class auto-loader type now presumes (incorrectly in some cases) that the class-instantiation's name is based on the file name. Not true in the issue I referenced above and for other of my plugins.

I don't see any evidence for this.
As before the `objects` instantiation name is taken from the `objectName` field

**Comment by lat9** [comment]
> 
> 
> As @drbyte said, double loading a class is an anti-pattern with possible side-effects.
> However for now I've added the ability to force load a class only.
> In a class config in the autoloader you can do
> 
> ```
> $autoLoadConfig[117][] = array (
>     'autoType' => 'class',
>     'loadFile' => 'split_page_results.php',
>     'forceLoad' => true
> );
> ```
> 
> I would however like to deprecate this during v158 and better understand how we can provide hooks/notifiers to support your plugin.

Shouldn't the same approach be taken with the `init_include`'s migration to a `require_once` instead of the `require` that was used previously, i.e. give a plugin the opportunity to force an additional load of an init_include during the page startup?

**Comment by lat9** [comment]
> 
> 
> > That's part of the issue, @zcwilt. The other issue is that the class auto-loader type now presumes (incorrectly in some cases) that the class-instantiation's name is based on the file name. Not true in the issue I referenced above and for other of my plugins.
> 
> I don't see any evidence for this.
> As before the `objects` instantiation name is taken from the `objectName` field

Agreed, I was just having hissy-fits when I saw that the processing had changed and was assuming the worst.
