### ISSUE TITLE
Using Plugin Manager, reports sorts wrong

### ISSUE THREAD

**Issue by wiztechinc** [zencart/zencart#3584]
Converted a report to be installed with the plugin manager with a sort order of 20. Installed originally at 2 instead of 20 and does not move in the reports list when changing the sort order directly in the database.

**Comment by drbyte** [comment]
Yes, the Reports and Tools menu sort alphabetically by default, unless you override it:

https://github.com/zencart/zencart/blob/a64a899631a4c1db42b6743650d4e505c7336f6f/admin/includes/languages/english.php#L696-L697

**Comment by wiztechinc** [comment]
How many other surprises? Yikes, thanks for the quick answer.

**Comment by drbyte** [comment]
> How many other surprises? 

I'm sure you weren't expecting a playful response, but ... I promise it's not intended to be an easter-egg hunt! :)

**Comment by wiztechinc** [comment]
I am aware. Just wondering how long it’s gonna take to figure out all the changes that could prove to drive me crazy.  This is a major change not obvious at all with the sort field still in the database. I’m now wondering how to highlight the changes in detail in one place.

**Comment by scottcwilson** [comment]
Great news - every release has release notes.  And this very feature is one of the line items!

**Comment by wiztechinc** [comment]
Well, of course but those line items frequently come with few details. "Admin - Alphabetical sorting of Reports and Tools menus." Does not tell me that the sort can be overwritten, that the sort field still exists etc. This is the kind of thing when I hit on it after the release, I turn to the forum for answers which have been much harder to get in recent years. Thanks to all who have answered questions recently!

**Comment by barco57** [comment]
> Yes, the Reports and Tools menu sort alphabetically by default, unless you override it:
> 
> https://github.com/zencart/zencart/blob/a64a899631a4c1db42b6743650d4e505c7336f6f/admin/includes/languages/english.php#L696-L697

aha! I have mentioned a couple of times in different places about the tools menu sorting alphabetically but nobody ever pointed that out

**Comment by scottcwilson** [comment]
These are the two menus that modders are most likely to add to, so they can become hard to navigate - alpha sort as an option makes it a bit easier.

**Comment by wiztechinc** [comment]
I'm certainly okay with the change. No complaints there.
