### ISSUE TITLE
admin_id selection error in includes/functions/functions_customers

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#3587]
I've found the Whoops error after finding an error with OPC set to Guest Checkout true.

As lat9 correctly stated earlier, OPC has nothing to really do with the Whoops error.

Recreation of the error:

1. Logged in admin decides he does NOT want a Single Admin ID to place customer orders.
2. admin goes to admin > Configuration > My Store and Customer Place Order: Single Admin ID
3. Instructions state the default is 1 BUT, to disable the feature, set the value to 0 (this is the EMP_LOGIN_ADMIN_ID)
4. admin then goes to Customers, selects a customer (beta is Bill Smith) and clicks on the Place Order Button.
5. admin gets the coveted Whoops notification.

Probable reason is in includes/functions/functions_customers.php

Starting on line 294, the admin system checks to see if the ID of the person logged is on the list of allowed admins.

As soon as the code below is given a '0' for (int)EMP_LOGIN_ADMIN_ID, it's all over but the shouting.

```
    $check = $db->Execute(
        "SELECT admin_id, admin_pass 
           FROM " . TABLE_ADMIN . " 
          WHERE admin_id = " . (int)EMP_LOGIN_ADMIN_ID . "
          LIMIT 1"
    );
```

Is it also a concern that non-super users would need this set to 1 if they have access to Customers.

Anyone with access to My Store could affect their actual ability to work with the customers.

This is not in the docs when clicking on the ? in My Store.  When it's sorted, I will add instructions in the docs.  That I think I can do.

**Comment by drbyte** [comment]
> As soon as the code below is given a '0' for (int)EMP_LOGIN_ADMIN_ID, it's all over

That's interesting, given that casting the value to `(int)` would force a blank to be `0`.
Thus it begs the question: what's your `EMP_LOGIN_ADMIN_ID` set to? And does that equate to any `admin_id` value in your db?

**Comment by dbltoe** [comment]
The five steps above set the EMP_LOGIN_ADMIN_ID from one to zero.
Doing so is the only way you can recreate the Whoops.
I may have selected the wrong spot for the fix for the problem.
Would we ever have an admin_id of zero?

**Comment by drbyte** [comment]
> Would we ever have an admin_id of zero?

No.

**Comment by drbyte** [comment]
Does making this fix solve it?
https://github.com/zencart/zencart/commit/e5e1f56056367607660ea4b069f8197946217e37

**Comment by drbyte** [comment]
Does it make any difference which Admin user is logged in? 
Or are you only doing this with the default Admin User # 1?

**Comment by dbltoe** [comment]
I'll create an additional and see.

**Comment by dbltoe** [comment]
No difference.
I know I'm a code dummy but, how can `WHERE admin_id = " . (int)EMP_LOGIN_ADMIN_ID . "`find an admin when it is zero?

**Comment by drbyte** [comment]
It can't.

**Comment by dbltoe** [comment]
Not getting my hackles up.  Just tried to get as close as I could before reporting.
Maybe with more study, I'll one day be able to submit the fix as well.

**Comment by drbyte** [comment]
How about this: https://github.com/zencart/zencart/commit/b3c96528c0875d3038235dd669d0f0eef18a19e2

**Comment by dbltoe** [comment]
💯

**Comment by drbyte** [comment]
I wonder if the original EMP code has the same issue?

**Comment by drbyte** [comment]
Now that that's fixed, I've pushed some additional updates to that section of the code and changed the EMP defaults to off.

**Comment by dbltoe** [comment]
It does not give the Whoops.  Just propagates the e-mail and invites you to log in.

**Comment by dbltoe** [comment]
All our customers like the feature.  Not sure they use it but they like it so, maybe a reconsideration on the OFF?  Just sayin'

**Comment by drbyte** [comment]
Shouldn't they give some intentional thought to "who" should be allowed to use the feature?

**Comment by dbltoe** [comment]
Ya but that would be in the profiles setup.  As it is now, the super can limit access to my store so the other profiles can't muck it up.

**Comment by drbyte** [comment]
Hmmm

**Comment by dbltoe** [comment]
I think I can 'splain it in the docs

**Comment by dbltoe** [comment]
Off Topic  Is it my dying SSD or is there a prob with the forum?

**Comment by drbyte** [comment]
I'm sorting out a vhost problem that a DNS change exposed

**Comment by scottcwilson** [comment]
There was a problem with the forum yesterday; it has been partially fixed but the search (which powers the "Newest Forum Posts" link) still doesn't work.
