### ISSUE TITLE
Missing FILENAME_PRODUCTS define

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#3588]
`[14-Jun-2020 21:19:19 UTC] Request URI: /jetmar/, IP address: 108.71.219.74
#1 include(/jetmar/includes/modules/dashboard_widgets/BaseStatisticsDashboardWidget.php) called at [/jetmar/index_dashboard.php:63]
#2 require(/jetmar/index_dashboard.php) called at [/jetmar/home.php:25]
#3 require(/jetmar/home.php) called at [/jetmar/index.php:11]
--> PHP Warning: Use of undefined constant FILENAME_PRODUCTS - assumed 'FILENAME_PRODUCTS' (this will throw an Error in a future version of PHP) in /jetmar/includes/modules/dashboard_widgets/BaseStatisticsDashboardWidget.php on line 58.`
The widget does want to check the page for the superuser.
There are many FILENAME_PRODUCTS_***** but, no simply FILENAME_PRODUCTS define.

**Comment by drbyte** [comment]
Thanks
