### ISSUE TITLE
Admin: Clicking product preview icon on listing opens product edit

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#3589]
On the category_product_listing page when clicking on the product preview icon, which is in front of the product name, opens a new tab for the shop showing the product as expected. But it also opens the edit product page.
This caused by the javascript which enables one to click anywhere on the product line to open the edit screen. This new script in effect adds back the bug which was removed by removing the click script that was there in older Zen Cart versions.
Maybe people should just learn to accept they need to click the product name, or the edit icon at the end of the line.

**Comment by scottcwilson** [comment]
Or, we could get rid of the preview icon and create a new icon to the right of product meta tags for preview.  I have never used the current preview icon, although I certainly do need product edit all the time.

**Comment by torvista** [comment]
Just to muddy the waters....
I often have links to other products embedded in product descriptions.
Those links I use in native format, not rewritten.
The Preview link uses the rewritten form.
I use the id column as links to the storefront using the native url, and copy those into product descriptions.
So, I do use **a** preview, but not **the** Preview.
And I always view a product after even the simplest editing.
