### ISSUE TITLE
v158 branch is now the default

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#3607]
Developers:

Now that v1.5.7 is released, if you are submitting a PR for a showstopper bugfix that requires an "a/b/c/d/" release then it should probably be PR'd against `v157`

Otherwise, **all new PRs should go to `v158`**.

To use `v158`, you should checkout the `v158` branch into your local cloned repository.

Updating "Working Branches"
Once you've cloned `v158` locally, if you have any "working branches" for other features you've been staging, to PR them you'll need to first `merge` the `v158` branch into your "working branch". You may want to rebase your changes onto the branch. 
If this all sounds confusing, another way is to make a backup copy of the directory you've been working in and create a new branch from the v158 branch and manually copy all your code changes onto the new branch. You've done this a hundred times in the past by making copies of directories and using Beyond Compare/etc to copy code changes over, starting on a different set of files.

**Comment by proseLA** [comment]
might something like this also be useful:

```git remote set-head origin v158```

on one's local copy?
