### ISSUE TITLE
OT coupon code tax error of excluded products

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#3612]
in `includes/modules/order_total/ot_coupon.php` the tax amount of an excluded product is removed twice from the total price resulting in unexpected amount showing as part of the order total.

approx line 620:

```php
        if ($this->include_tax == 'true') {
         $orderTotal -= $productsTaxAmount;
        }
        if (DISPLAY_PRICE_WITH_TAX == 'true')
        {
          $orderTotal -= $productsTaxAmount;
        }
```
resolution appears to be changing `if` to include `or` or simply removing second `if` statement

Ref: https://www.zen-cart.com/showthread.php?226857-OT-coupon-code-tax-error-of-excluded-products

**Comment by scottcwilson** [comment]
1.5.8 line number is 646.  Would you please PR?
