### ISSUE TITLE
admin, categories, adding an image filename manually

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3628]
If the file is not found, there is an error message and the category listing page is displayed. 

I think it would be better to 
a) include the incorrect filename in the error message and 
b) reload the category edit page to easily correct it.

And, that's assuming there is not a leap forward to check for a valid filename on the fly after entering a filename manually...and so not leave the category edit page at all.

**Comment by scottcwilson** [comment]
Note: ./admin/categories.php line 176 references non-existent constant MESSAGE_IMAGE_ADDED_MANUAL.

**Comment by torvista** [comment]
https://github.com/zencart/zencart/pull/3627

**Comment by scottcwilson** [comment]
This hasn't yet been fixed in 1.5.8.

**Comment by scottcwilson** [comment]
I can add it to my PR #3815 if you wish - I just didn't want to conflict with what you might be doing.

**Comment by torvista** [comment]
I've no time for anything ZC these days, unless something comes up I had a hand in, so go ahead.

**Comment by scottcwilson** [comment]
OK done.

**Comment by scottcwilson** [comment]
@torvista can this be closed?

**Comment by torvista** [comment]
Closed means it's been done or will not be done, so I guess it's still pending. I'll look at it again.

**Comment by scottcwilson** [comment]
Please PR or close.
