### ISSUE TITLE
Do we need noindex and nofollow in setup wizard

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#3634]
I am preparing a PR with converting all admin files to use admin_html_head.php. My question is do we really need noindex and nofollow here? As it is already after admin login, and can never be reached by a search engine.
https://github.com/zencart/zencart/blob/b75923a06280b2bc4ca41d8ae7cb443568aa26f2/admin/index_setup_wizard.php#L83

**Comment by drbyte** [comment]
For that page I guess not.
