### ISSUE TITLE
Named shopping baskets, named wishlists

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#364]
Features frequently requested:
- [ ] Ability to save my shopping basket contents ... and name that basket and ability to retrieve that basket later, independently of making other purchases.
  - [ ] Ability to share a URL link for that basket to my friends so they can look at the things I'm considering buying, ostensibly to give me feedback
- [ ] Similarly, named wishlists and the ability to pull items into wishlist from named baskets.
- [ ] And ability to have wishlists be made publicly accessible to other than the customer ... such as enabling "wedding gift registry" or similar registries. 
  - [ ] And ability to mark an item in the wishlist as being "purchased already by XYZ person" (or anonymously).

**Comment by wiztechinc** [comment]
yes!!

Delia Wilson Lunsford
WizTech, Inc., (formerly Delia Wilson Design, LLC.)
434-202-4307
Terms and Conditions for working with WizTech, Inc.
(http://www.teamwiztech.com/terms-conditions.php)

**Comment by barco57** [comment]
:+1:

**Comment by scottcwilson** [comment]
You could use my Save for Later mod as a base for this work.

**Comment by DivaVocals** [comment]
:+1:

**Comment by barco57** [comment]
needs an admin page where the store admin can see the wishlists, or an aggregate of products placed in wishlists. I know of one client with the current wishlists mod that goes through wishlists to get ideas for products that might sell well on special.

**Comment by ajeh** [comment]
@scottcwilson can you add multiple save for later rather than just one?

**Comment by scottcwilson** [comment]
At the moment, no.

**Comment by drbyte** [comment]
@scottcwilson Would you consider doing a PR to bring Save For Later into core code?

**Comment by scottcwilson** [comment]
I could but it doesn't offer named baskets.

**Comment by drbyte** [comment]
Fair; at least it's a starting point from which one can iterate.
