### ISSUE TITLE
Add Selected To Cart Fails For New, Featured, and All

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#3640]
Open either New Products, Featured Products, or All Products

Change any product's quantity to 1 and click on the Add Selected to Cart.

Nothing but screen refresh.  No error logged.

**Comment by zcwilt** [comment]
Think it's this commit.
https://github.com/zencart/zencart/commit/d9e5be1462326e5450f0306cb6f8378494214b17

**Comment by scottcwilson** [comment]
Yep, looks like a bug in 1.5.7.  Thanks for reporting.

**Comment by scottcwilson** [comment]
LOL you beat me to it!
