### ISSUE TITLE
1.5.7 and 1.5.8 Less than all Observers executed on notify.

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#3656]
Code that had been installed to a system which has recently been "progressively" upgraded began providing notifications of variables not set in an observer class; however, the update action code was present (verified to be spelt correctly, verified to be `attached`, verified to be camel-cased correctly) to perform the assignment.  When I added a `trigger_error` event to the observer, it did not fire.  When I found that another observer was listening for the same event, I disabled the other observer and suddenly the observer having the "problem" was fully functional.

Tracked down that it appears that in recently updated observer code, if the observer is found and executed once, then the code stops trying to determine if there are other observers for that notifier...

Proposed fix for ZC 1.5.7: #3654 
Proposed fix for ZC 1.5.8: #3655

**Comment by drbyte** [comment]
Closed by #3654

**Comment by scottcwilson** [comment]
nice catch!

**Comment by lat9** [comment]
Yes, that would have caused a lot of hair-pulling!
