### ISSUE TITLE
v157 Strict php with not logged in customer causes order_history sidebox notice on each page load

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#3657]
When the order_history sidebox module code is executed:
`includes/modules/order_history.php`
strict php execution is enabled, 
and customer is not in the "checkout process" (not logged in and not in guest checkout), then notices are thrown
`--> PHP Notice: Undefined index: customer_id in includes/modules/sideboxes/order_history.php on line 18.`
on each page load.

This is a result of the following ZC 1.5.7 code not executing:
https://github.com/zencart/zencart/blob/f6fe46046a3a465ea13b728beecd6d8bc045a4ae/includes/modules/sideboxes/order_history.php#L11-L13
and ZC 1.5.8 code:
https://github.com/zencart/zencart/blob/557ab5d5542ac29f3dd368994a6edb686c740a75/includes/modules/sideboxes/order_history.php#L11-L13

to bypass the code that determines the history of the customer.

At that time, the user is not logged in (so satisfies the first portion of the `if`, but also is not in guest checkout which causes the second part to fail and code after this early escape to be executed.  The intent appears to be to escape this code if there is no order history expected for the person visiting the site, which ultimately would be true if the person is identified as not being logged in, regardless of their guest checkout status as supposedly an individual in guest checkout is not logged in...

Any other observer code would need to recognize this "issue" and not attempt to identify the person as logged in unless the resulting condition could be handled.

Suggestion is to modify the above logic to simply return if `!zen_is_logged_in()` and not be concerned with the condition of guest checkout... 

````php
if (!zen_is_logged_in()) {
    return;
}
````

**Comment by dennisns7d** [comment]
This file was changed June 19, 2020..

There are a number of places where similar quick returns are used. The code is:
`if (!zen_is_logged_in() || zen_in_guest_checkout()) {
    return;
}`

To restore the execution of this file prior to June 19, I would change the && currently there to ||.

**Comment by lat9** [comment]
> 
> 
> This file was changed June 19, 2020..
> 
> There are a number of places where similar quick returns are used. The code is:
> `if (!zen_is_logged_in() || zen_in_guest_checkout()) { return; }`
> 
> To restore the execution of this file prior to June 19, I would change the && currently there to ||.

Nope, you don't want to make that change.  That code line currently indicates that if a customers is not logged in or if a customer is in guest-checkout, don't do this.

**Comment by lat9** [comment]
> Suggestion is to modify the above logic to simply return if `!zen_is_logged_in()` and not be concerned with the condition of guest checkout...
> 
> ```
> if (!zen_is_logged_in()) {
>     return;
> }
> ```

I'll suggest using the code fragment suggested by @dennisns7d 
```
if (!zen_is_logged_in() || zen_in_guest_checkout()) {
```

**Comment by mc12345678** [comment]
> > This file was changed June 19, 2020..
> >
> >There are a number of places where similar quick returns are used. The code is:
> > ````
> > if (!zen_is_logged_in() || zen_in_guest_checkout()) { return; }
> > ````
> >
> > To restore the execution of this file prior to June 19, I would change the && currently there to ||.
>
> Nope, you don't want to make that change. That code line currently indicates that if a customers is not logged in or if a customer is in guest-checkout, don't do this.


> > Suggestion is to modify the above logic to simply return if !zen_is_logged_in() and not be concerned with the condition of guest checkout...
> >
> > ````
> > if (!zen_is_logged_in()) {
> >     return;
> > }
> > ````
> I'll suggest using the code fragment suggested by @dennisns7d
> 
> ````
> if (!zen_is_logged_in() || zen_in_guest_checkout()) {
> ````

Perhaps just didn't get back to revise the previous post, but the above response(s) are about the same topic and yet slightly conflicting.

That said, I still don't see the need to have these two separate functions to do this, but might as well keep with what ever has been created...

So, this going to be made a "first timers only" type correction?

**Comment by dennisns7d** [comment]
It appears that my observations muddied the waters instead of clarifying things, so I'll try again.

Prior to June 19, the bulk of the code in order_history.php was contained in the following statement:
`if (zen_is_logged_in() && !zen_in_guest_checkout()) {`

The change of June 19 attempted to invert this logic to use quick return, but was done incorrectly:
`if (!zen_is_logged_in() && zen_in_guest_checkout()) {`
The && should have been changed to || here.

This would align this code with other quick returns scattered elsewhere.
`if (!zen_is_logged_in() || zen_in_guest_checkout()) {`
