### ISSUE TITLE
The future of Mod List 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3659]
@dbltoe has indicated he thinks mod list should be built into the core.  I'm open to this idea but I want to see if there are any objections before moving forward.  Of course I would use @zcwilt's new plugin logic to do this. 

For those who are unfamiliar with Mod List, it can be seen here: 
https://www.zen-cart.com/downloads.php?do=file&id=2039 

When this was done in 1.6.0, it was called "System Information."  (We can't just backport the PRs that did it because they used the 1.6 infrastructure.)

**Comment by dbltoe** [comment]
Yes, and include the sort so it aligns itself with the menu alignment.  Line 66 of mod_list.php`$pages_query_raw = " SELECT * FROM " . TABLE_ADMIN_PAGES . " ORDER BY menu_key ASC ";`

**Comment by drbyte** [comment]
Questions, in no particular order, regardless of prior implementation in 1.6.0:
- what's the purpose of having it in core?
- how exactly are people expected to make use of it? Should they view it as an upgrade tool? When else will they know they're supposed to use it?
- what problem is it solving for them? 
- what problem does it create for them once they start using it? (ie: now what do I do with this info? how do I fix something that I think is broken? how do you prevent them from "fixing" things that aren't actually broken/bad?
- what's the better title for it? "Mod List" is meaningless to the new storeowner. Nothing is called "mod" in Zen Cart.

**Comment by scottcwilson** [comment]
I'd like @dbltoe to answer the first 4 questions from the user perspective.
Question 5: We could stick with System Information, as in 1.6.0.
Question 6: It doesn't interact with changed files at all.  Changed files is just `ls -lt` on your catalog folder.

**Comment by dbltoe** [comment]
With the magnitude of mods most folks throw at ZC, I find it an invaluable tool for the "know enough to be dangerous" crowd.
First, it lets me know what is, not, and partially there.
If a define was left out or a configuration key, the user will immediately see an all caps listing in the Page Name column.
It's nice to know what database changes were made by a mod for troubleshooting purposes.
Missing Admin Configuration Pages is a better help during upgrade than installation but, I've found it useful in both.
It helps let you know if you left out or missed that one file/setting in mod removal.
I don't see anymore problem with this than adding Display Logs.  True, the Mod List is not as definitive an aid as the Display Logs but, it's there even if the log file is not.
I've only run across one item that appeared to need fixing and actually didn't.  That was discussed earlier (additional Category page in the catalog Menu Key that is set to Display N). Might want to add a Display = Y to the sort 
I like the Mod List as nothing (other than the one Category item) gets there without the store owner installing or turning on a mod.
It's been one of my top ten loads for some time and was very helpful in the Whoops! testing.

**Comment by scottcwilson** [comment]
LOL I just realized that when I fixed the bug that @proseLA pointed out I forgot to update it for the new tables in Zen Cart 1.5.7.  Better do that soon. 

Anyhow, @drbyte take it as a suggestion - I'm ok either way, but it was championed by @dbltoe and I wanted to bring it up.

**Comment by proseLA** [comment]
just to be clear; i pointed out a bug in the ZC core.  i then pointed out the non-standard way that mod_list names its page_key when adding a record into the admin_pages table that obfuscates that core ZC bug.

**Comment by scottcwilson** [comment]
Mod List has been updated to use the Plugin Manager.

**Comment by scottcwilson** [comment]
Closing.  Those who want to use Mod List can get it from the Plugins Library.
