### ISSUE TITLE
Reduced create account requirement

### ISSUE THREAD

**Issue by barco57** [zencart/zencart#366]
The act of creating an account should only require the collection of an email address and password. All other information (address, phone, etc..) can be gathered when that information becomes useful, such as at purchase time. This would also remove the current create account process from being a barrier to those who might only want to begin to create a wishlist ( issue #364 )

**Comment by DivaVocals** [comment]
That's a direction I want to move in with COWOA as well.. In fact I am looking to make the actual creation of an account during checkout to be moved to AFTER the purchase is complete, and prompt the user to create an account at that time with the information already collected during the checkout..

**Comment by barco57** [comment]
Both methods should be implemented

**Comment by zcwilt** [comment]
We are working on this as part of Guest Checkout in v1.6.0 
Once it is finished, you can review and comment
