### ISSUE TITLE
Where/how to capture/pass item of concern

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#3664]
Back in ZC 1.5.6, changes were made to the way upgrades were done through ZC 1.5.3, and through 1.5.5. Specifically, the upgrade script for Zen Cart 1.5.3 adds the country 'South Sudan' whether that country is in the database or not. In the ZC 1.5.5 upgrade the countries 'Curaçao' and 'Sint Maarten (Dutch part)' are added the same way. What this means (and this primarily only affects those in this condition/situation) is that if a store that appears to have a database version less than 1.5.3 and already had added any of those three countries to the store (including using the original default country numbers of 246, 247, and 248, respectively) then as they go through an upgrade to 1.5.6 or above, then the country/countries will be added again.

Now, to also recognize another perspective, whether a number was assigned or not, the upgrade process never ensured that a new country would not be duplicated. Certainly by having an "assigned" number it becomes easier to troubleshoot and determine that there is/has been a difference and offers one the idea to investigate how/why there is/was a difference.  Further, there are those that do/will manually take control of the countries they wish to have listed which may incorrectly include deleting the country.

I was looking for a possible place in the docs files, but then was wondering about the docs site, then perhaps a forum thread, etc... So, in a way looking for a suggestion of where the above may be captured to maybe help those that later find that they have the same country listed twice and/or have problems with zone type configurations that include/associate those three countries (however rare one or more people think it may be).

**Comment by drbyte** [comment]
Is someone actually running into a chaos situation where the numbers assigned for these countries is messing things up? 
Since it created the country's associated zones in tandem with the country, any given store will have its own data in sync with itself. 
Sure, the id numbers may not match the id numbers in other stores, but that's another issue. Canonically the store is still in sync with itself. 
I haven't run into cases where these specific factors you're mentioning (specific countries and their zones) have posed a functional problem.

Have you example cases?

**Comment by drbyte** [comment]
The real root cause is really a design flaw inherited from OsC that we haven't fixed: all country references should have been on ISO-3 code, not on an autoincrementing id. 
Changing that is a big overhaul. But off-topic for the issue at hand.

**Comment by torvista** [comment]
> all country references should have been on ISO-3 code, not on an autoincrementing id.

Exactly.

**Comment by lat9** [comment]
> 
> 
> Is someone actually running into a chaos situation where the numbers assigned for these countries is messing things up?
> Since it created the country's associated zones in tandem with the country, any given store will have its own data in sync with itself.
> Sure, the id numbers may not match the id numbers in other stores, but that's another issue. Canonically the store is still in sync with itself.
> I haven't run into cases where these specific factors you're mentioning (specific countries and their zones) have posed a functional problem.
> 
> Have you example cases?

Unfortunately, yes.  I've got a client who's got additional countries defined, essentially expanding on the UK so that there are separate countries for England vs. Scotland vs. Wales.  Those countries' IDs are in the 241-251 countries_id range.

**Comment by scottcwilson** [comment]
This would work for future country creation SQL statements: 

INSERT INTO countries (countries_name, countries_iso_code_2, countries_iso_code_3, address_format_id) SELECT 'South Sudan','SS','SSD','1' FROM DUAL WHERE NOT EXISTS (SELECT * FROM countries WHERE countries_iso_code_3 = 'SSD' LIMIT 1);

A new row is only created where needed.

**Comment by Zen4All** [comment]
After a quick look at the code, I think updating the code is not that complex. The biggest issue is writing a foolproof updater for the database to update all involved tables to use ISO codes instead of id where applicable. Not all tables and code needs updating.

**Comment by drbyte** [comment]
> > Is someone actually running into a chaos situation where the numbers assigned for these countries is messing things up?
> > Since it created the country's associated zones in tandem with the country, any given store will have its own data in sync with itself.
> > Sure, the id numbers may not match the id numbers in other stores, but that's another issue. Canonically the store is still in sync with itself.
> > I haven't run into cases where these specific factors you're mentioning (specific countries and their zones) have posed a functional problem.
> > Have you example cases?
> 
> Unfortunately, yes. I've got a client who's got additional countries defined, essentially expanding on the UK so that there are separate countries for England vs. Scotland vs. Wales. Those countries' IDs are in the 241-251 countries_id range.

To clarify, their country/zone ids are all in sync with each other, correct?
Your point is just that when those ids were added it means they no longer correspond with what a "fresh install" would do, thus any SQL scripts or code that relies on ids instead of ISO codes would need special care. And that's my point too.

**Comment by scottcwilson** [comment]
Can this ticket be closed?
