### ISSUE TITLE
Plugin Installer sql file handling 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3667]
Updating Mod List to use the Plugin Manager.  I have a .sql file to be run. 

It looks like the installer wants to run 
zc_plugins/ModList/1.4.0/Installer/install.sql

but the documentation 
https://docs.zen-cart.com/dev/plugins/encapsulated_plugins/sql_installation/

Suggests the file should be in 
zc_plugins/ModList/1.4.0/Installer/sqlInstall/install.sql

Which is correct? 
Also we should probably indicate that the filename is hardcoded as "install.sql".

**Comment by lat9** [comment]
Are SQL changes provided by a plugin **_required_** to use an installation SQL rather than doing `$db`-based updates?

**Comment by zcwilt** [comment]
No. If no install.sql exists the installer will look for a file called ScriptedInstaller.php 
and you can use that to do your sql changes using $db

**Comment by zcwilt** [comment]
@scottcwilson  will update docs soon. Correct location is just in the `Installer` directory

**Comment by scottcwilson** [comment]
I can take care of it - I am working in that area anyhow.  Will update shortly.

**Comment by scottcwilson** [comment]
Updated.  https://github.com/zencart/documentation/pull/279
