### ISSUE TITLE
zc157: Plugin installer, message-only on error

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#3677]
I carried over a zc156c-era database that has `Display Logs` already installed (without the associated file-set).  When I attempt to install the zc157-included version of the plugin, I'm met with the following message, no log, no additional information:

![image](https://user-images.githubusercontent.com/2685585/86777765-8ec8c000-c027-11ea-91a3-74a09d088f17.png)

Shouldn't the installer either log a warning identifying the underlying issue or include the error-information in that message?

**Comment by lat9** [comment]
FWIW, this issue _was_ due to a preexisting version of Display Logs being present.  Corrected via edit of `zc_plugins/DisplayLogs/3.0.0/Installer/ScriptedInstaller.php` line 13 from:

```php
            "INSERT INTO " . TABLE_CONFIGURATION . " 
```
to
```php
            "INSERT IGNORE INTO " . TABLE_CONFIGURATION . " 
```
Within the plugin-architecture, I'm unclear as to how to correct this for future use.  Does this warrant a 3.0.1 version or does the change get applied to 3.0.0?

**Comment by zcwilt** [comment]
So two questions here.

**What to do with errors**

The plugin architecture does `log` internally the sql errors that occur, and you can see them if you change the code in
`includes/classes/PluginSupport/ScriptedInstaller.php`

and change this line 

            $this->errorContainer->addError(0, $this->dbConn->error_text, false, PLUGIN_INSTALL_SQL_FAILURE);
to 

            $this->errorContainer->addError(0, $this->dbConn->error_text, true, PLUGIN_INSTALL_SQL_FAILURE);

There currently no `file` logging of errors, although provision has been made for this.

The Plugin Manager will be further updated during v158 and this should be addressed.

**Do we release a v3.0.1**

I don't think this is necessary. The change from `INSERT` to `INSERT IGNORE` should definitlely be backported to v157.

**Comment by dbltoe** [comment]
We had the issue of a beta test site having the original 2.0.0 and being updated to 1.5.7 release.  Deleting and reinstalling failed.

The addition of ignore corrected the problem immediately.

**Comment by lat9** [comment]
Without those issues logged, it makes it _very difficult_ for plugin authors to diagnose any issues that might arise when a plugin's installation failed.

**Comment by drbyte** [comment]
I believe #3679 fixes this.

**Comment by scottcwilson** [comment]
I added a note to the plugin documentation encouraging people to use INSERT IGNORE, IF NOT EXISTs, etc. 
I got bit by this too! 

https://docs.zen-cart.com/dev/plugins/encapsulated_plugins/sql_installation/

**Comment by scottcwilson** [comment]
Can this issue be closed?
