### ISSUE TITLE
page_key categories in user profile

### ISSUE THREAD

**Issue by simon1066** [zencart/zencart#3678]
ZC157: Similar to the way that the page_key categories appears in the Mod List mod, identified in this thread
 
https://www.zen-cart.com/showthread.php?225892-Admin_Pages-gt-page_key-categories-in-1-5-6c

this redundant(?) page_key also crops up when setting the options for a User Profile (catalog section).

**Comment by drbyte** [comment]
> this redundant(?) page_key also crops up when setting the options for a User Profile (catalog section).

It's not redundant.
If you don't tick the box for it then the associated users won't be able to add/edit categories.

**Comment by simon1066** [comment]
Yes I see now, thanks for confirming what that does - I hadn't fully explored the functions of all of the user profile Catalog options.
