### ISSUE TITLE
Paypal Express - Duplicate Orders with new Order number with stricter MySQL

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#3693]
Discovered this issue on a ZC 1.5.6 site that is using MySQL 5.7 (php 5.6 currently), and see that the same code exists in ZC 1.5.7.

When a purchase is being processed for immediate claim, the data generated includes the price of the item and the currency.  To store the data, the `settle_amount` is expected to be captured.  The `settle_amount` field is of the data type `decimal(15,4)`... If the text is not "removed", then MySQL throws a fatal error from this assignment: 
ZC 1.5.6:
https://github.com/zencart/zencart/blob/e60c81b6dbac7b1a61fb891397fe20de7b02c623/includes/modules/payment/paypalwpp.php#L544

ZC 1.5.7:
https://github.com/zencart/zencart/blob/07ec9d08de4937aa162edb9f5d767729afd295a0/includes/modules/payment/paypalwpp.php#L536

The result of the fatal error appears to be that an order number is generated which contains all of the paypal information; however, the customer doesn't necessarily seem to be able to fully checkout. After the button times out, the customer can click again, a new order number is generated but the same payment information is captured/collected and it seems this cycle continues...

See #3692 for proposed solution.

Also, I have a feeling that because of another issue in that line `$this->urldecode()` instead of `urldecode()` that information from authorizations is not properly captured back into the database as a result of the code "stopping" at that point... I believe I saw someone posting an issue with authorizations somewhere in the forum and not being able to see the associated data in the ZC admin orders screen... These two issues may be why... I do not (yet) know how the data looks that is returned from: `$this->responsedata['PAYMENTINFO_0_SETTLEAMT']`

**Comment by mc12345678** [comment]
Additional "related" issue #3696 affecting the same line of code.

**Comment by drbyte** [comment]
Closed by #3692 and #3696
