### ISSUE TITLE
Put Find Duplicate Product Models in the core or in zc_plugins?

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3717]
Another 1.6 integration for consideration.

Find Duplicate Models is a script that reports non-unique model numbers in the products table.   This is an important check for many external systems, such as Quickbooks, which require unique model numbers. 

Find Duplicate Models was built in to Zen Cart 2.0/1.6.  Any interest in adding it to 1.5.8, and if so, where.

**Comment by wiztechinc** [comment]
No question of the value for some customers but I may have had one only that needed it. Extra for me not core

**Comment by torvista** [comment]
+1
Essential for me.

**Comment by barco57** [comment]
+1 for Core

**Comment by Zen4All** [comment]
Undecided

**Comment by proseLA** [comment]
plugin.

**Comment by lankeeyankee** [comment]
core for sure, needed safety check

**Comment by scottcwilson** [comment]
Awaiting input from @drbyte or @zcwilt before proceeding.

**Comment by torvista** [comment]
My general opinion is that if someone is willing to spend their time adding anything to the project it should be welcomed unless there is a very solid reason **not** to.
There is already plenty of functionality in ZC that some shops never have touched, but that others find essential, that's par for the course.
This may be one of those, but so what, if someone is happy to add it?

If this was a commercial project, developer time would be allocated to a strictly defined roadmap for the most efficient progress.
But it isn't, so people will contribute what they feel like, whether "essential" or not.

If this is low-hanging fruit from 1.6, why not? And similarly for anything else that was done in that branch....
