### ISSUE TITLE
zc157/zc158: Missing directories for Developers' Tool Kit

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#3718]
Searching for all files catalog/admin on zc157/zc158 finds no references for files present in the `/zc_plugins` sub-directory.  For zc158, this extends to the newly-added `/app` sub-directory as well.

**Comment by scottcwilson** [comment]
Agreed on `zc_plugins`. 

For 1.5.8 should searching `/app` be optional?  Worried about false positive matches.

**Comment by lat9** [comment]
How about that `/app` sub-directory, too?  I'd much prefer false positives (which I can weed out mentally) that false negatives (which cause me to look elsewhere).

**Comment by lat9** [comment]
... that could help with issues like that reported in #3778, for instance.

**Comment by drbyte** [comment]
The problem with searching the `app` directory is that it also includes a massive `vendor` directory, which contains nothing of core code -- it's all ancillary code used to support the framework.
That should be excluded.

That reminds me, the `/includes/classes/vendors` dir should also be excluded, even in older versions.

**Comment by lat9** [comment]
Couldn't the `app/vendor` simply be excluded?  There have been a couple of `app`-based issues that have arisen; there's nothing worse when trying to debug than a false negative.

**Comment by scottcwilson** [comment]
I will create a new issue out of 

> That reminds me, the /includes/classes/vendors dir should also be excluded, even in older versions.

so these two things can be disposed of separately.

**Comment by scottcwilson** [comment]
Should this be closed?  Or should I create a new ticket to add `app` - `app/vendor`?  Or some mysterious third option?

**Comment by drbyte** [comment]
There's very little in the laravel directories that warrants a full search at this time.
