### ISSUE TITLE
WYSIWYG Editor as default/core admin feature

### ISSUE THREAD

**Issue by IronLady** [zencart/zencart#372]
Would it be better if WYSIWYG Editor (TinyMCE, CKEditor, etc.) included in default installation?
Some user may need table, unordered list, heading tag and other tags for the product description, this will help them who don't have HTML basic understanding. 
I think it's really important.

Thoughts?

**Comment by barco57** [comment]
It used to be and was removed in favor of the WYSIWYG Editor being an addon. I myself like to use CKeditor and add particular plugins too it based on the clients needs, as the CKeditor for 1.5.4 is a stripped down version

**Comment by DivaVocals** [comment]
Mixed feelings about including a WYsiwyg editor.. I am more in favor of a stripped down editor with FEW options other than BASIC options (bold, italics). I find that too many store owners do UGLY things if there are too many editing options, and most of them they don't (read: shouldn't) need to do..

**Comment by IronLady** [comment]
> this will help them who don't have HTML basic understanding
Basic HTML I was referring too are bold, italic, underline, strikethrough, text-align, ul, ol, h1-h6 and other basic text format. No need to include all options. It's better than plain text I think.

**Comment by Zen4All** [comment]
I agree with Iron Lady. It also will decrease the (large) number of installation errors, seen on the forum, when people do install an editor.

**Comment by barco57** [comment]
I would like to know how the editor impacts PCI Compliance as it relates to getting Zen Cart certified. The editor may have been removed so it was not in scope for testing during certification.

**Comment by Zen4All** [comment]
@barco57 Good point

**Comment by drbyte** [comment]
> @barco57 wrote:
> the CKeditor for 1.5.4 is a stripped down version

It's no longer stripped down code-wise; it's only the config file that's abbreviated the button bar to more reasonable basics instead of unnecessary clutter.

**Comment by wiztechinc** [comment]
That's definitely more appropriate use and having dealt with an editor before, I can add in more if necessary but I firmly believe that only bold and italic with headings and lists are the only formatting a customer should do.  One of the biggest problem with any editor is that the more you format and reformat, the more cluttered the code can get. Sometimes one has to dig into the source code in order to remove code that the editor leaves in and then creates problems.

**Comment by DivaVocals** [comment]
Perhaps the editor code should be examined to clean up some of the garbage it adds in. The nesting of inline font color, sizes, font faces that these editors do is aggravatingly awful..

**Comment by drbyte** [comment]
Perhaps, but keep in mind that the end user must find it usable, not crippled. Restricting it to satisfy the HTML purists may break usability for the average shopowners. 

As with everything, finding the right balance is key.

**Comment by DivaVocals** [comment]
I agree.. but geez.. it doesn't even clean up after itself.. If a shop owner is "trying out" fonts, colors, font sizes, the daggone thing just keeps nesting it's darn inline code.. YUCK!!!

**Comment by drbyte** [comment]
Will be improving editor hooks, and will consider optimizing the plugin package. 
Doesn't feel like a good fit for being auto-built-in at this time. 

I completely agree that it's valuable for those who use it. ;)
