### ISSUE TITLE
setting samesite cookie attribute

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#3721]
https://github.com/zencart/zencart/blob/e60c81b6dbac7b1a61fb891397fe20de7b02c623/includes/init_includes/init_sessions.php#L44

we do not seem to be setting the samesite cookie attribute.  perhaps we should?  not sure if we need a new config value (:confounded:) or not....

in addition, we would have to account for the php version, as 7.3 allows for an associative array for use:

```
    $samesite = CONFIG_SAMESITE;  // Lax or Strict or None

    if(PHP_VERSION_ID < 70300) {
        session_set_cookie_params(0, $path .'; samesite='.$samesite, (zen_not_null($cookieDomain) ? $domainPrefix . $cookieDomain : ''), $secureFlag, TRUE);
    } else {
        session_set_cookie_params([
            'lifetime' => 0,
            'path' => $path,
            'domain' => (zen_not_null($cookieDomain) ? $domainPrefix . $cookieDomain : ''),
            'secure' => $secureFlag,
            'httponly' => TRUE,
            'samesite' => $samesite
        ]);
    }
```

or something like this.

**Comment by drbyte** [comment]
Feel free to make a PR to 1.5.8 for this.

I suggest assuming `lax` by default, unless one has added a define for `COOKIE_SAMESITE` as either `strict` or `none` via an `extra_configures` file.
Same in both catalog/admin

**Comment by proseLA** [comment]
looks like i'm off the hook in this one! 

thanks.
