### ISSUE TITLE
Files in ./admin/includes/extra_configures/ under PluginManager

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3724]
It appears that PluginManager does not load these files.  Is this a bug or should they be moved?  I'm hoping it's the former so plugin authors will not need to change their work.

**Comment by zcwilt** [comment]
It's not possible for plugins to use the extra_configures directory at least at the time it is loaded in application_top.php

**Comment by zcwilt** [comment]
more info.

To know what plugins are available we need to have started a db connection and be able to query the database. This isn't possible at the point that extra_configures is loaded.

The very first `override` directory that is available to plugins is the `extra_datafiles` directory.

**Comment by zcwilt** [comment]
Do you have a use case to use `extra_configures` ??

**Comment by scottcwilson** [comment]
I was using it on an old plugin. I can move it easily but this is just a new rule I wasn't aware of.  I'll need to document it too on https://docs.zen-cart.com/dev/plugins/encapsulated_plugins/converting/

**Comment by scottcwilson** [comment]
Hmm.... not sure moving is the way to go.  Can you just make extra_configures load when extra_datafiles is loading (in plugin context)?   The trouble is I have a bunch of plugins that use extra_configures, which was needed when they were created, and lots of other people do too.

**Comment by zcwilt** [comment]
as longs as the contents of extra_configures isn't expected to have any effect on code that happens between when 
extra_configures is normally loaded and the point where plugin system loads the extra_definitions, it shouldn't be a problem.

Currently working on some updates to PluginManager at the moment, will roll that change into the PR.

**Comment by scottcwilson** [comment]
> Currently working on some updates to PluginManager at the moment, will roll that change into the PR.

If it's possible, it would be great to separate out that change, since we're going to have to tell 1.5.7 users to patch it (and possibly backport it to 1.5.7a).

**Comment by zcwilt** [comment]
will backport later. have to go out.

**Comment by scottcwilson** [comment]
Note that current solution does not work in 1.5.8 or 1.5.7 - see comments in your PR.
