### ISSUE TITLE
Dual Mode (encapsulated/pre-encapsulated) plugins

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3725]
People are starting to submit plugins in the new form for 1.5.7 (great!) but in their enthusiasm, sometimes they're just replicating folders (not great!).

I'd like to provide guidance on how to do this moving forward, and I'd like to see what the community thinks before adding it to the docs site.  Here's what I'm proposing: 

- to be added to https://docs.zen-cart.com/dev/plugins/encapsulated_plugins/converting/

### 5. Remove old files and update documentation 

Please *do not* preserve top level folders like `admin` and `includes` with the same files you have created in `zc_plugins/YOURPLUGIN/VERSION/`.  Instead, update the README file for your plugin with guidance like: 

If you are running a  Zen Cart installation older than 1.5.7, do not copy in the `zc_plugins` folder.  Instead, 
go to the `zc_plugins/YOURPLUGIN/VERSION/` folder and copy the `admin` and `includes` folders to your shopping cart (after renaming the `admin` folder.)

**Comment by drbyte** [comment]
I'm having trouble understanding what that new section means.

> "do not preserve top level folders like admin and includes ... in zc_plugins/yourplugin/version"

Huh? We DO want admin and include folders there!

> do not copy in the zc_plugins folder

I would suggest that plugins built for `zc_plugins` DO distribute the `zc_plugins` dir as the parent for ONLY the code that belongs in that directory structure.
Stuff for older plugin editions can be left out of the zip altogether or put in the old dirs and tell them to ignore one set or the other.
I don't like the idea of telling people to "dig way down 3 levels below zc_plugins, find those files and copy them to the root of your store" for older ZC versions.

**Comment by scottcwilson** [comment]
Here's what I'm trying to avoid: 

LICENSE.txt 
README.txt
admin
includes
zc_plugins

(admin and includes are duplicates of what's under zc_plugins).

How to explain this?

**Comment by scottcwilson** [comment]
Bear in mind: if files are duplicated, then bugs will be missed in one place or another.  I really want people to have one set of files.

**Comment by scottcwilson** [comment]
OK I have added some notes to `dev/plugins/encapsulated_plugins/converting.md`
I have also tried to address this issue: https://github.com/zencart/zencart/pull/3726 

Please see this PR: https://github.com/zencart/documentation/pull/293
