### ISSUE TITLE
Plugin upgrade warning should be more descriptive 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3727]
<img width="368" alt="warning" src="https://user-images.githubusercontent.com/4391638/87336125-63564180-c50f-11ea-8e14-28d33a39462b.png">

LOL

admin/includes/languages/english/lang.plugin_manager.php needs a bit of improvement.

**Comment by drbyte** [comment]
Haha!

er, I mean, "blah blah"! 

🤣

**Comment by scottcwilson** [comment]
I kind of prefer "blah blah" to "lorem ipsum." :)

**Comment by barco57** [comment]
lol
