### ISSUE TITLE
Multi lingual country names

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#374]
This may be a to large of a change for ZC 1.6, but I would love to see the country names to be multi lingual in a future release of Zen Cart..
A lot of my customers have shops in multiple languages, and ften ask how and where they can change the county names. Not every one knows the English names for the worlds countries.

**Comment by Zen4All** [comment]
Since I brought the suggestion, I thought to start work on this. It turns out it's not that hard, to accomplish, although a lot of core files need to be changed, and an additional table in the database is needed.

**Comment by zcwilt** [comment]
Good for you for doing the work. I just wish I was ready to commit stuff for https://github.com/zencart/zc-v1-series/issues/63

Changing the admin page for Language management would then just have been a matter of updating a couple of arrays, with probably minimal code to write

**Comment by Zen4All** [comment]
No worries.
This afternoon I finished the work, and have it working on a 1.5.4 installation.
I am also thinking of releasing this as a module on the forum, but then I will have some more work on a readme and a proper fool prove installation script
I'll keep an eye open on #63, because my admin code is indeed largely a copy of orders_status.php, and

**Comment by scottcwilson** [comment]
@Zen4All #63 is done.

**Comment by Zen4All** [comment]
:thumb: I'll start work on a new branch

**Comment by Zen4All** [comment]
These new LEAD pages rock!! :tada:  It makes it really simple to add stuff. After a quick study of the other lead pages, it only took a few minutes to add my own tables and fields

**Comment by scottcwilson** [comment]
What's the best LEAD page template to look at to learn the new system?

**Comment by zcwilt** [comment]
You could take a look at https://github.com/zencart/zc-v1-series/pull/587
As it shows how to add new lead pages.

**Comment by zcwilt** [comment]
I've also opened a boilerplate for Admin LEAD docs at http://docs.zen-cart.com/Developer_Documentation/1.6/code_docs/admin_lead_pages/introduction
Will hopefully have that updated this week, and you can follow updates at 
https://github.com/zencart/documentation

**Comment by Zen4All** [comment]
Because I needed something with multiple tables, I primarily used
* includes\library\zencart\listingBox\src\boxes\AllProductsPage.php
* includes\library\zencart\listingBox\src\boxes\LeadOrdersStatus.php
* includes\library\zencart\listingBox\src\boxes\LeadRecordArtists.php

This gave me enough info to deduce the new code for the multilingual country names.

**Comment by zcwilt** [comment]
@Zen4All Glad you like the new stuff. Don't forget, if you are having any problems, open a new issue and tag @zcwilt and I'll be pleased to help.

**Comment by Zen4All** [comment]
:thumbsup:

**Comment by Zen4All** [comment]
this has been stale for a while, but I am almost finished now. For one small problem. When I try to edit add a zone, the country names show for each language.
![multi_language_countrie_names](https://cloud.githubusercontent.com/assets/2766593/14059254/6be36be2-f33c-11e5-8ca3-520851fe2551.jpg)
I tried a lot of things, but I am unable to find where to put the code to filter on language id.
Some help is appriciated
The code is in this [branch](https://github.com/Zen4All/zc-v1-series/tree/v160-Multilingual-Country-Names)

**Comment by zcwilt** [comment]
in your branch you don't have any sql install for the countries_name db table, so I am getting sql errors

**Comment by Zen4All** [comment]
Your right, will add the Sql later this evening.

**Comment by Zen4All** [comment]
`CREATE TABLE IF NOT EXISTS countries_name (
  id int(11) NOT NULL AUTO_INCREMENT,
  countries_id int(11) NOT NULL,
  language_id int(11) NOT NULL DEFAULT '1',
  countries_name varchar(64) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE countries (countries_id, language_id, countries_name),
  KEY idx_countries_name_zen (countries_name)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;`

**Comment by zcwilt** [comment]
Hi. 
Looks like your problem with zones and multiple entries is a weakness in the current Select2  code.

I note that you have had a stab at doing the geoZones page by adding 

`                        'extraWhere' => 'language_id',
                        'extraWhereVal' => $_SESSION ['languages_id']
`

to the data definition. However  the current code only supports 'extraWhere' where the value is a related GET parameter, and not a fixed value. 
e.g. 

       if ($this->request->has('extraWhere') && isset($this->outputLayout ['fields'] [$this->request->readGet('extraWhere')])) {

            $sql .= ' AND :extraWhereField: = :extraWhereValue:';
            $sql = $this->dbConn->bindVars($sql, ':extraWhereField:', $this->request->readGet('extraWhere'), 'noquotestring');

            $bindVarsType = $this->outputLayout ['fields'] [$this->request->readGet('extraWhere')] ['bindVarsType'];

            $sql = $this->dbConn->bindVars($sql, ':extraWhereValue:', $this->request->readGet('extraWhereVal'), $bindVarsType);
        }


I'll do a PR to core that allows for a more flexible extra where clause on the Select2 sql builder.

**Comment by Zen4All** [comment]
Thanks :+1:

**Comment by zcwilt** [comment]
So I have done a PR https://github.com/zencart/zc-v1-series/pull/885
to better manage language stuff for Select2 drop downs.
Rather than mess with extra where clauses, I've made the language stuff more automated. 

Once the PR has been merged I'll post how to update your code to use it.

**Comment by Zen4All** [comment]
Great

**Comment by zcwilt** [comment]
We've merged PR https://github.com/zencart/zc-v1-series/pull/885
if you update your branch with this, you should find that the Zones just work.
For GeoZonesDetails  you will need to remove the 

                            'extraWhere' => 'language_id',
                        'extraWhereVal' => $_SESSION ['languages_id']

from the autoeComplete definiotion for countries_name

**Comment by Zen4All** [comment]
:+1:  I did the pr and can confirm that it works fine so far :confetti_ball: , will do some more testing.

**Comment by zcwilt** [comment]
Cool.

I did notice one bugette in your code 

In the file includes/library/zencart/Services/src/LeadLanguagesRoutes.php
and the function postProcessInsert, the definition for the countries_name table is 

            array(
                'table' => TABLE_COUNTRIES_NAME,
                'languageKeyField' => 'languages_id',
                'orderBy' => 'countries_id',
                'fields' => array(
                    'countries_id' => 'integer',
                    'countries_name' => 'string',
                )

shouldn't the languageKeyField be language_id

**Comment by Zen4All** [comment]
This one is close to be finished. I only have one small problem. On the country page when I want to input a new country, or edit an existing country, I only get one input box. I have no clue how to change this to two (one for each language).
**current page**
![edit coutry org](https://cloud.githubusercontent.com/assets/2766593/15804411/52caef2e-2b07-11e6-99c0-748630327b54.jpg)
**the result i want**
![edit coutry new](https://cloud.githubusercontent.com/assets/2766593/15804413/58ff7aea-2b07-11e6-9dff-d28de2d27f76.jpg)

I searched in the existing code, but can not find a hint on how to do this.

**Comment by scottcwilson** [comment]
Can you not use the technique shown in admin/includes/modules/product/collect_info.php line 302 (from 1.6.0) - get languages and loop over them?

**Comment by zcwilt** [comment]
For the field you want to be editable for multi-language have you set the language attribute in the field definition

e.g. 

                'record_company_url' => array(
                    'bindVarsType' => 'string',
                    'language' => true,
                    'layout' => array(


There are some layout bugs in current v160 sue to a partial boostrap implementation, that means the language editable fields don't display correctly. I am working on fixes. However temporarily you can remove the 'row collapse' classes from tplLanguageText.php

**Comment by Zen4All** [comment]
@scottcwilson that is the old way of showing the fields, which is not going to work in the new lead pages.

@zcwilt Changing the `row collapse` worked. I now have 2 fields. They need some formatting with css, but I will wait until a final solution is found.

**Comment by Zen4All** [comment]
This is now working perfect in my test enviroment. Now I need to do some checks to see if anything has change with the consolidation of functions from admin to catalog #967, which is a good thing btw

**Comment by Spike00** [comment]
So, for each language supported by the site, we should type in the translations, right? 
What does it happen if there aren't translations for a language? Does it default to english or what?

**Comment by Zen4All** [comment]
@Spike00 on installation of a new language, the values for the country names get copied from the default language, the same as is happening now with for example product names.
When upgrading a Zen Cart store from a previous version to Zen Cart 1.6, the new table gets created, and will be populated with the existing countries

**Comment by drbyte** [comment]
@Zen4All ...

1. Note that I added the missing semicolons in the upgrade .SQL file: https://github.com/zencart/zencart/commit/26ddd0d1c86e7369d9d43d17ad9396d02486b636

2. @ajeh has pointed out that there's still another component that's missing: if someone's already got more than 1 language (english) installed and they run the upgrade SQL they're still missing the country-names for those other languages. 
Do you mind opening a PR with the updated upgrade.SQL to handle that?

**Comment by Zen4All** [comment]
👍  Will do

**Comment by Zen4All** [comment]
I did some searching, and looping through the available languages for setting the language_id for each language name, is not that simple using only sql.
I posted a question on stackoverflow to see is anyone can/will help.

**Comment by Zen4All** [comment]
see #980 for the solution
