### ISSUE TITLE
Logging Anomalies

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#3747]
This is a follow on to #3720 and #3711.  I did a fresh install of today's `zc158` repository, adding a teeny file to `/includes/functions/extra_functions` containing
```php
<?php
$uhoh = nonexistent_function();
```
The Zen Cart installation, on storefront access, displays
![image](https://user-images.githubusercontent.com/2685585/87803577-aae71100-c820-11ea-83c2-26655f93b543.png)

... but there's no associated log in the site's `/logs` sub-directory.

Noting that I did find the following in `/app/storage/logs/laravel.log`
```
[2020-07-17 15:24:07] local.ERROR: Call to undefined function nonexistent_function() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined function nonexistent_function() at C:\\xampp\\htdocs\\zc158\\includes\\functions\\extra_functions\\make_an_error.php:2)
[stacktrace]
#0 C:\\xampp\\htdocs\\zc158\\includes\\modules\\extra_functions.php(43): include()
#1 C:\\xampp\\htdocs\\zc158\\includes\\init_includes\\init_general_funcs.php(53): include('C:\\\\xampp\\\\htdocs...')
#2 C:\\xampp\\htdocs\\zc158\\includes\\autoload_func.php(37): require_once('C:\\\\xampp\\\\htdocs...')
#3 C:\\xampp\\htdocs\\zc158\\includes\\application_top.php(220): require('C:\\\\xampp\\\\htdocs...')
#4 C:\\xampp\\htdocs\\zc158\\index.php(25): require('C:\\\\xampp\\\\htdocs...')
#5 {main}
"} 
```
That log is, of course, missing some of the significant elements (page being accessed, IP address) and looks like it's just going to build up over time (the name isn't suffixed by anything).

**Comment by scottcwilson** [comment]
Thanks for creating an issue; I reported this to @zcwilt this morning.

**Comment by scottcwilson** [comment]
I actually got this with no need to add a non existent function. :(  See my PR #3748

**Comment by zcwilt** [comment]
So finally found what the problem(s) are :-

First Laravel also set's an exception handler (set_exception_handler) which needs to be removed. This is fairly easy.

The second and more difficult problem is the Laravel sets a register_shutdown_function(), and as these are chainable,
they cannot simply be removed. 

There will be a way to override this somehow, but still looking for the point that the handler class is bound to the container(the Laravel store of registered classes)

Still, hope to have a fix soon.

**Comment by lat9** [comment]
FWIW, the changes that @zcwilt has supplied have corrected the issue reported above.

**Comment by scottcwilson** [comment]
Can we close this ticket then?
