### ISSUE TITLE
Laravel

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#3752]
i have played around with it ever so briefly.  i am aware of artisan.

i'm curious about the genesis of the idea of the integration.  as well as how people see this framework being used as part of the ZC ecosphere going forward.

thanks in advance.

**Comment by lankeeyankee** [comment]
Curious about this choice, too. Was this part of 2.0/1.6 and it being ported into 1.5? Or is this an entirely new decision? Was there a discussion about implementing this somewhere or was it a unilateral core-ownership decision? What is the long-term plan for zen cart now you are bolting on a different framework? Is it just for the plugin system or...?

**Comment by drbyte** [comment]
In terms of v1.5.8 the primary purpose is to leverage its capabilities to assist with features being built into the plugin system.
