### ISSUE TITLE
Email creation

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3757]
Is there any interest in adopting an Email HTML to Text converter so we can just create the outbound email using the templates and then automatically convert to text (vs doing it in code the way we do now)? 

Here's one:
https://github.com/soundasleep/html2text

Here's another: 
http://www.chuggnutt.com/html2text

**Comment by drbyte** [comment]
It would help to understand first the specific problems that the current way is causing.
And secondarily what new problems would this idea create?

**Comment by scottcwilson** [comment]
The issue with the current method is that any customizations need to be done twice; one for plain text and one for HTML. 
This would solve that.  Doesn't it seem crazy to build an email up line by line in code?  It's really storeowner unfriendly.

**Comment by scottcwilson** [comment]
This would also be intended to resolve #2742.

**Comment by lat9** [comment]
Doesn't PHPMailer already have such functionality?

**Comment by scottcwilson** [comment]
I am unaware of PHPMailer having this capability.  If you look at  includes/classes/order.php send_order_email() you'll see how the email body is built up twice. 

The .txt format file is certainly one way to go - it's just a bit of a pain because there's still double maintenance when you make changes.

**Comment by lat9** [comment]
In `/includes/classes/vendors/PHPMailer/src/PHPMailer.php`, starting at line 3818 for zc156c:
```php
    /**
     * Create a message body from an HTML string.
     * Automatically inlines images and creates a plain-text version by converting the HTML,
     * overwriting any existing values in Body and AltBody.
     * Do not source $message content from user input!
     * $basedir is prepended when handling relative URLs, e.g. <img src="/images/a.png"> and must not be empty
     * will look for an image file in $basedir/images/a.png and convert it to inline.
     * If you don't provide a $basedir, relative paths will be left untouched (and thus probably break in email)
     * Converts data-uri images into embedded attachments.
     * If you don't want to apply these transformations to your HTML, just set Body and AltBody directly.
     *
     * @param string        $message  HTML message string
     * @param string        $basedir  Absolute path to a base directory to prepend to relative paths to images
     * @param bool|callable $advanced Whether to use the internal HTML to text converter
     *                                or your own custom converter @see PHPMailer::html2text()
     *
     * @return string $message The transformed message Body
     */
    public function msgHTML($message, $basedir = '', $advanced = false)
    {
```

**Comment by scottcwilson** [comment]
Interesting.  We might still need some .txt templates (hopefully fewer than the .html templates we have now) but this could be the ticket.

**Comment by scottcwilson** [comment]
The reason I'm keen on maximum automation of this process is that I think it's long past time to make HTML send the standard, and text the fallback (and to keep the email filters happy).

**Comment by lat9** [comment]
FWIW, although it would be _complicating_, my preference would be to auto-convert the generated HTML if there was **_not_** a like-named .txt file, allowing additional control over those text-format emails.

**Comment by drbyte** [comment]
> I think it's long past time to make HTML send the standard, and text the fallback (and to keep the email filters happy).

Email filters much prefer text-only. Passing HTML is the first step to rejected emails. The second step is neglecting at text-only portion.
