### ISSUE TITLE
Considering: symfony/polyfill for backwards PHP compatibility

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#3759]
https://github.com/symfony/polyfill

This may let us support older and newer PHP versions more seamlessly.

**Comment by lat9** [comment]
... _more seamlessly_, please elaborate.

**Comment by proseLA** [comment]
from their readme:

It is strongly recommended to upgrade your PHP version and/or install the missing extensions whenever possible. This polyfill should be used only when there is no better choice or when portability is a requirement.

so is the plan to support php 5.3 for ZC 1.5.8?

on first glance, i'm not a fan...  perhaps seeing it in action may change my mind.

**Comment by drbyte** [comment]
Primary goal: support newer PHP versions and the improved features they offer. Might make future PHP version compatibility possible before those versions are even released.
Instead of hacking in a bunch of "if-not-function-exists-then-define-it" code the polyfill does that for us. 

Secondary goal: possible backward compatible support for functions that didn't exist in older versions. Same if-not-function-exists-then... benefit.

Third: a possible side-benefit would be mbstring support auto-detection. Would require a massive search-replace of all function use with new function names. 

Support PHP 5.3? I have zero interest in "officially" supporting something that ancient (because there's no way I can test it, without doing dev-environment fanagling that I refuse to do unless I'm being paid a very large custom consulting fee to do it).
But if the side-effect is that something that old magically "works", then great.

Impossible: features that older PHP versions can't offer, such as modern syntax use.

**Comment by mc12345678** [comment]
I personally could see the following functions being of use to support code intentionally written for 7.x/8.x where these functions may not yet be available in the selected 7.x /8.x php version:
- `mbstring` and related,
- `is_iterable`,
- `is_countable`,
- `array_key_first`,
- `array_key_last`,
- `JsonException`,
- `str_contains`,
- `str_starts_with`,
- `str_ends_with`,
- `FILTER_VALIDATE_BOOL`

There may be limited use of/for some of these, but supporting the ability to program forward within the operation of the most recent versions while supporting the acceptable/intentionally planned version(s) seems reasonable to me and helpful.

**Comment by drbyte** [comment]
Included by virtue of the Laravel integration.

**Comment by drbyte** [comment]
Edit: added to v158 in https://github.com/zencart/zencart/commit/15f621951da656d08382af03c51a1b0f116e9ea1
and backported to v157c
