### ISSUE TITLE
zc157: payment.php class, some methods aren't receiving their inputs

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#3770]
... as reported in [this](https://www.zen-cart.com/showthread.php?226988-parameter-zf_order_id-is-not-being-transferred-into-the-after_order_create-method) Zen Cart forum post.

Notably: `after_order_create` and `admin_notification`.

**Comment by scottcwilson** [comment]
Should this ticket be closed?

**Comment by lat9** [comment]
Shouldn't it have auto-closed on the merge?  This issue was mentioned as 'fixed' in the PR.

**Comment by scottcwilson** [comment]
The "Fixes" comment has to be in the first entry.
