### ISSUE TITLE
Per Page Extra Language Files - suggested approach

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3780]
I'd like to add to 1.5.8 the ability to load files that match the patterns 

admin/includes/languages/english/per_page/$current_page_base/*.php 

This way we could de-clutter extra_definitions and make it so plugin authors don't have to say things like "Edit admin/includes/languages/english/order.php (or lang.orders.php) and add these lines ..."   They could take advantage of auto loading instead. 

I would likely backport this as a plugin so people could use this technique in 1.5.7 and below.

**Comment by wiztechinc** [comment]
great idea. Anything that streamlines things is welcome!

**Comment by lat9** [comment]
Is there such a value as `$current_page_base` in the admin?  I thought that the closest you could get was `$current_page` (which includes the `.php` suffix).

**Comment by scottcwilson** [comment]
Sorry, this was intended to be pseudocode - yes, I believe you are right but I'd have to work in this area to be sure.

**Comment by scottcwilson** [comment]
Looking for approval of the concept and the name "per_page".  Will move forward once that's done.

**Comment by drbyte** [comment]
With the zc_plugins system is this really needed now?

**Comment by scottcwilson** [comment]
Yes.  Because an arbitrary language file can't be loaded by a plugin; it relies on the autoloader.

**Comment by drbyte** [comment]
I'm not sure I follow.

In the zc_plugins directory structure you could have:
`zc_plugins/NAME/VER/admin/includes/languages/english/lang.order.php` 

or worst case with maybe the legacy filename:
`zc_plugins/NAME/VER/admin/includes/languages/english/order.php`

And that file could contain all the language stuff needed for that page beyond what's already in the core language def's.

Why would another two subdirectory levels be needed?

**Comment by drbyte** [comment]
To be clear: I do like the idea of uncluttering (and using way less of) the `extra_definitions` dir, and avoiding all edits to the core language files.

**Comment by scottcwilson** [comment]
This is an issue for me because I'm building a little tool to allow people to easily add a dashboard widget to show orders in a specific status.  I don't want to tell them to edit admin/includes/languages/english/order.php and I was hoping not to put it in extra_definitions. 

Not all plugins will use the plugin manager.  But if you don't like this naming convention, what about 
admin/includes/languages/english/PLUGIN-NAME.order.php ?

**Comment by scottcwilson** [comment]
Also: I'm trying to build for 1.5.6 and 1.5.7.

**Comment by scottcwilson** [comment]
Look at all these language files that have to be *merged by hand* in COWOA v2.4, for example: 

./includes/languages/english/westminster_new/checkout_shipping.php
./includes/languages/english/westminster_new/login.php
./includes/languages/english/westminster_new/checkout_payment.php
./includes/languages/english/westminster_new/logoff.php
./includes/languages/english/westminster_new/no_account.php
./includes/languages/english/westminster_new/checkout_process.php
./includes/languages/english/westminster_new/checkout_confirmation.php
./includes/languages/english/westminster_new/order_status.php
./includes/languages/english/westminster_new/time_out.php
./includes/languages/english/westminster_new/gv_redeem.php
./includes/languages/westminster_new/english.php

with the naming convention I suggested: 
./includes/languages/english/westminster_new/cowoa.checkout_shipping.php
./includes/languages/english/westminster_new/cowoa.login.php
./includes/languages/english/westminster_new/cowoa.checkout_payment.php
./includes/languages/english/westminster_new/cowoa.logoff.php
./includes/languages/english/westminster_new/cowoa.no_account.php
./includes/languages/english/westminster_new/cowoa.checkout_process.php
./includes/languages/english/westminster_new/cowoa.checkout_confirmation.php
./includes/languages/english/westminster_new/cowoa.order_status.php
./includes/languages/english/westminster_new/cowoa.time_out.php
./includes/languages/english/westminster_new/cowoa.gv_redeem.php
./includes/languages/westminster_new/cowoa.english.php

They could just contain the new defines required and drop right in.

**Comment by syntaxerror** [comment]
I like the idea, but maybe it's better to separate those extra files from the core structure?

T.ex. instead of:
> admin/includes/languages/english/PLUGIN-NAME.order.php ?

Rather use something like:
> admin/includes/languages/plugins/english/PLUGIN-NAME.order.php ?

And then in the same go even add support for overrides per define/string:
> admin/includes/languages/overrides/english/order.php ?

**Comment by drbyte** [comment]
> Look at all these language files that have to be _merged by hand_ in COWOA v2.4, for example:
> 
> ./includes/languages/english/westminster_new/checkout_shipping.php
> ./includes/languages/english/westminster_new/login.php
> ./includes/languages/english/westminster_new/checkout_payment.php
> ./includes/languages/english/westminster_new/logoff.php
> ./includes/languages/english/westminster_new/no_account.php
> ./includes/languages/english/westminster_new/checkout_process.php
> ./includes/languages/english/westminster_new/checkout_confirmation.php
> ./includes/languages/english/westminster_new/order_status.php
> ./includes/languages/english/westminster_new/time_out.php
> ./includes/languages/english/westminster_new/gv_redeem.php
> ./includes/languages/westminster_new/english.php

With a plugin that touches a dozen files like that, it makes sense to use a single `extra_datafiles/plugin_name.php` file to contain all the additions it makes, instead of touching numerous files.

**Comment by syntaxerror** [comment]
> With a plugin that touches a dozen files like that, it makes sense to use a single `extra_datafiles/plugin_name.php` file to contain all the additions it makes, instead of touching numerous files.

Sorry if it's obvious, but how does that work for a multilingual setup, how should it be used for such?

**Comment by scottcwilson** [comment]
@syntaxerror Sorry I missed this comment.  If you have a suggestion for improving the documentation page you linked, please post it in the doc repo (https://github.com/zencart/documentation) or create a PR.

**Comment by syntaxerror** [comment]
Can't fix the docs if I'm not sure how it works, as stated. :)

**Comment by torvista** [comment]
>  includes/languages/english/extra_definitions/ even if I'm not sure how those works

Everything defined in the files in this directory is available on all pages....so while it may be a bit "wasteful" in the sense that these constants are not needed on most pages, its a lot cleaner from a maintenance/upgrade point of view than making minor additions to multiple core files.

**Comment by scottcwilson** [comment]
I'm going to beef up the explanations further - check again in 10 minutes.

**Comment by scottcwilson** [comment]
Closing for now, let's get the conversion to the new language file format done before adding anything more to it.
