### ISSUE TITLE
Maybe: use Intervention image package

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#3782]
https://github.com/Intervention/image
https://github.com/Intervention/imagecache

Perhaps these proven and well-supported packages might make a good basis for replacing Image Handler's painful image caching system.

Maybe even https://github.com/thephpleague/glide

**Comment by wiztechinc** [comment]
And including it in zen cart core? Please! Whatever works but I install image handler on every site. I consider the caching functions to be required. Since I really can’t look at code only, a thorough discussion of this and all issues would be greatly appreciated.

**Comment by dbltoe** [comment]
I would just request an on/off switch.  We have an enterprise license with a commercial product that we install on all our customers' sites.  It far exceeds simple caching.

**Comment by scottcwilson** [comment]
Clearly this ticket should be retitled: Intervention: Call me maybe.
