### ISSUE TITLE
Exclude vendor folder from developer's toolkit search 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3783]
From the discussion surrounding #3718 

> That reminds me, the /includes/classes/vendors dir should also be excluded, even in older versions.

Target 1.5.8 but possibly suitable for backport.

**Comment by lat9** [comment]
How about a developer constant through which additional directories can be 'easily' added to the DTK's sub-directory list(s)?

**Comment by drbyte** [comment]
Closed by f6f3268

**Comment by drbyte** [comment]
> How about a developer constant through which additional directories can be 'easily' added to the DTK's sub-directory list(s)?

"easily" is "relative". Probably better to have some sort of registration requirement for plugins.
But I'm not a fan of having every plugin declare even more global-scope constants that just take up RAM in exchange for the 1% of time they might rarely ever be used, and never relevant catalog-side.
But this shouldn't be hijacking the current thread.
