### ISSUE TITLE
Language Files - move to new array structure?

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#3785]
@zcwilt wrote:
>While code exists to use arrays catalog side, we haven't yet converted any language files to the new array structure.
Question: do we go ahead and do this for v158?

Benefits:
- No more "already defined" issues when duplicates are encountered when loading up the language strings (because it'll update the array instead, before then setting all the defines in place)
- matches zc_plugins approach to languages
- already in zc_install
- backward-compatible insomuch as other files that define language constants will still be able to do that, since core code still uses constants for rendering all language output

Cons:
- touches a lot of files

**Comment by scottcwilson** [comment]
We could also significantly consolidate (and reduce) definitions this way, making it much easier to create a new language pack.

**Comment by lat9** [comment]
Just noting that upgrading sites to v158 that have customized admin language text is already going to be a major PITA due to the language files' renaming.  If you're going to go down this array-structure path eventually, I'll suggest doing it now to decrease the pain in post-v158 upgrades.

**Comment by scottcwilson** [comment]
Yep.  I really want to bite the bullet NOW and get this done with.  See also #3739.

**Comment by vandijkstef** [comment]
Any reason not to go into getText ( _()/_e() ) and move into .po/.mo land?

Major upside of the defines is that autocomplete loves them

**Comment by drbyte** [comment]
> Any reason not to go into getText ( _()/_e() ) and move into .po/.mo land?

While I like the idea of using an `_()` or `e()` helper for outputting strings, I'm not convinced that `.po` or `.mo` is necessary.

Agreed: IDEs are very friendly to the defines. Moving away from the defines does lose that major convenience.

**Comment by torvista** [comment]
ZC158: What is the recommended location for 
- additional language strings
- overrides

I have extra texts used in category_product_listing page.
I have just placed an additional array in a file in /extra_defines....which did not get picked up,
and then put same data in the main array in /lang_english.php, and they did not get used either,
neither when in lang_category_product_listing.php.

I have old format files and new mixed in the language directory (for comparison). Does that make a difference?
I removed the english and category_product_listing, no change.

So, what am I doing wrong?

**Comment by proseLA** [comment]
personally, i am not a fan of how IDEs work dictating coding structure.  

i'm having a few problems with this new langauge loader for v158.  i am not sure where to post about it...  here seems as good as any; let me know if i'm adrift.

on a v158 system, i enabled the COD payment module.  a couple of PHP notices, but more importantly Fatal Error on admin when looking at the order due to a file not found error.

`PHP Fatal error:  require(): Failed opening required '/var/www/zcdev/includes/languages/english/modules/payment/cod.php`

**Comment by scottcwilson** [comment]
Looks like cod was the only language file to get converted on the storefront side - @zcwilt was this a test that got checked in accidentally?

**Comment by brittainmark** [comment]
A question. Is this likely to happen?
As I have been playing with PHP8 and have found and modified the files generating the warnings for already defined constants. If not and you would like the modified files(or if they would be usefull anyway) I am happy to branch and create a pull request with the changes. All I have done is put a if (!defined([constant])) in front of each of the constants I have found being redefined.
The following is a list of the files I have found needing changes.
/includes/languages/english/account_edit.php
/includes/languages/english/account_history_info.php
/includes/languages/english/account_history.php
/includes/languages/english/account_password.php
/includes/languages/english/account_newsletters.php
/includes/languages/english/account_notifications.php
/includes/languages/english/account_password.php
/includes/languages/english/address_book_process.php
/includes/languages/english/advaced_search.php 
/includes/languages/english/advaced_search_results.php 
/includes/languages/english/checkout_payment.php
/includes/languages/english/checkout_process.php
/includes/languages/english/checkout_shipping_address.php
/includes/languages/english/discount_coupon.php 
/includes/languages/english/index.php 
/includes/languages/english/login.php 
/includes/languages/english/popup_search_help.php
/includes/languages/english/responsive_classic/index.php

**Comment by drbyte** [comment]
@brittainmark you can see that in v158 we've begun this conversion. Here's a link to the admin files:
https://github.com/zencart/zencart/tree/v158/admin/includes/languages

**Comment by torvista** [comment]
Is there no code snippet lurking in someone's archive to do the conversion en bloc of existing language pack files? Even if not 100% ready...

**Comment by drbyte** [comment]
> Is there no code snippet lurking in someone's archive to do the conversion en bloc of existing language pack files? Even if not 100% ready...

Most recent, but not re-implemented yet was: https://github.com/zencart/zencart/tree/3f2fa132d1867287ebfcd58b25fc96fd99c20eae/laravel/app/Console
A former rendition of it was: https://github.com/zcwilt/zcgo
It will probably not be distributed "in" Zen Cart, but as a separate utility to be used entirely independently.

**Comment by torvista** [comment]
Thanks, I found and tried that some time ago, but got nowhere. I did post about it, but can't find it.

The old docs/instructions are missing the bit that explains to someone who works with Zen Cart and little else, what they need to do with that /laravel folder and their (local) server installation, to be able to run that command/Laravel.
Not a step-by-step, just big picture stuff....

**Comment by drbyte** [comment]
> The old docs/instructions are missing the bit that explains to someone who works with Zen Cart and little else, what they need to do with that /laravel folder ...

Since, as I said, the language convert tool will likely be a standalone entirely independent utility, it no longer has anything to do with the /laravel directory. That's completely intentional.

I'll queue up a delete of those docs to avoid the confusion.

You asked for code snippets. That's the only reason I mentioned the above. 
Re-implementing it for anyone to use is very low on current priorities list.

**Comment by scottcwilson** [comment]
> on a v158 system, i enabled the COD payment module. a couple of PHP notices, but more importantly Fatal Error on admin when looking at the order due to a file not found error.
> 
> `PHP Fatal error: require(): Failed opening required '/var/www/zcdev/includes/languages/english/modules/payment/cod.php`

For now just copy the old file in from 157.  This is a work in progress.

**Comment by torvista** [comment]
FWIW, I made a script to 99% convert language files to lang. files if anyone else is an early adopter.

And, in the interests of leaving the core lang. files intact/untouched, where would one put constant definitions to
- allow the override of core constant definitions?
- add new definitions?

**Comment by scottcwilson** [comment]
@torvista Would you please run your script and set up the 1.5.8 storefront side lang files in the new format?  And check your script in to extras for translators to use?

**Comment by torvista** [comment]
Is this not going to break things as per the COD module as mentioned above?
i.e. that issue should be resolved first?

**Comment by scottcwilson** [comment]
it's a chicken and egg problem I think - can you do both?  
a) Pull in english/lang.whatever or its override
b) If not found, Pull in engish/whatever or its override

**Comment by scottcwilson** [comment]
@proseLA I decided it was more productive to fix the cod module (which is the first storefront side language file in the new style) rather than remove `./includes/languages/english/modules/payment/lang.cod.php` and restore `includes/languages/english/modules/payment/cod.php` from an older version.  But if we can't get the storefront side language files converted quickly enough, that might be the fallback.

**Comment by torvista** [comment]
I should do it this week.

**Comment by scottcwilson** [comment]
Thanks - this will be helpful to other translators.  Heck, even to me if I do the english translations!

**Comment by scottcwilson** [comment]
I'll get the storefront switched over to the new language defs style as soon as @torvista's conversion utility is available.

**Comment by scottcwilson** [comment]
Changes in #4532 will allow storefront side language files to use the new format.  We'll also build some conversion tools to help people get updated.

**Comment by torvista** [comment]
I've spent far too long on this, that I can't justify at all, but it's here

https://github.com/torvista/Zen_Cart-Language_File_Converter

I don't consider it good enough to be included in ZC, it was not meant for public review/meant to be a simple/quick thing to code....as if.

**Comment by scottcwilson** [comment]
Thanks for your work.  Will submit PRs if I can spot any improvements but just having the basics will save us all a lot of time.

**Comment by scottcwilson** [comment]
@torvista please approve #4532 so we can move forward.

**Comment by scottcwilson** [comment]
Your tool gave me a huge head start.  The whole process of doing the storefront language files took just a couple of hours.

**Comment by torvista** [comment]
Glad to hear it. Rather you than me.

**Comment by scottcwilson** [comment]
First pass submitted: #4540 - will need deduping and refinement.

**Comment by scottcwilson** [comment]
Notes on conversion: https://docs.zen-cart.com/dev/languages/158_language_files/

**Comment by torvista** [comment]
After more fettling with the converter (works properly now), I can easily alphasort all the language files as per the main language file.
It makes comparison even easier
Shall I go ahead and alphasort all language files?

**Comment by scottcwilson** [comment]
Not sure - why would this make comparison easier, since they're in a different order than 1.5.7?

**Comment by torvista** [comment]
If the originals are alphasorted and the created files also alphasorted, they line up in comparison software easily.

![Clipboard01](https://user-images.githubusercontent.com/4391026/152573872-ca4895ee-3324-4a4b-ba6a-66017c20985b.gif)

**Comment by torvista** [comment]
>but the originals are not alphasorted by default.

I'm suggesting that I do that.

**Comment by scottcwilson** [comment]
I misunderstood - I was thinking you were meaning files below the 'english/' folder.   Your PR was merged.

**Comment by scottcwilson** [comment]
This work is complete.
