### ISSUE TITLE
hide product

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3788]
Suggested/recommended method?
Based on IP or an extra url parameter?

**Comment by lat9** [comment]
IP's more difficult to circumvent; a `$_GET` parameter, once discovered, can be used by whomever.

**Comment by drbyte** [comment]
Also depends on why you're hiding it.
Is it just hiding from search engines?
Is it for "logged-in users only"?  of a certain customer group?
Is it only for people who visit the page via a link you send in a newsletter mailing?
Is it pre-release, where you don't want it visible until a certain date, except for a few certain people? 
 ... and then again, how do you define those people?

IPs can be a moving target if peoples' IPs are changing regularly, even within a certain provider. Requires maintenance of the list.
GET allows you (and those who know it) to share a link/param to those whom you want to disclose, but doesn't give you final control.

**Comment by torvista** [comment]
MY reason is purely to work on product descriptions (which may be text images, graphs, links between other offline products etc.) at leisure, on the production site.
No big deal if someone wants to use a GET parameter, but probably easy to use same code as whatever Down for Maintenance with admin IP uses. Not even looked yet.
But I appreciate there are multiple reasons and use-cases as outlined above....

**Comment by scottcwilson** [comment]
If this is your use case then you can set the product to disabled so it won't appear to most people in the storefront, then make two small tweaks: 

	includes/index_filters/default_filter.php
	includes/modules/pages/product_info/main_template_vars.php

These files check products_status = 1.  You can add a condition like "or the logged in customer is Steve".

**Comment by scottcwilson** [comment]
You could also use the new PRODUCT_THROWS_200_WHEN_DISABLED define (conditionally set if the logged in user is Steve) if you use my fix.

**Comment by torvista** [comment]
I think basing the condition on a specific-logged in user is the most useful method in this and other use-cases.
Thanks.

**Comment by torvista** [comment]
includes/index_filters/default_filter.php
includes/index_filters/header_php.php
includes/modules/pages/product_info/main_template_vars.php

**Comment by scottcwilson** [comment]
includes/modules/pages/product_info/header_php.php
only required for 1.5.6 - not 1.5.7.

**Comment by scottcwilson** [comment]
Glad you were successful - perhaps you could write up instructions in a forum post for others who might wish to also do this?

**Comment by torvista** [comment]
Well I did this

extra_datafiles/zz_my_file.php
define('CUSTOMERS_SHOW_DISABLED_PRODUCTS', array(1, 10039, 10630));

extra_functions/zz_my_functions.php

function mv_show_disabled_products()
{
    return zen_is_logged_in() && in_array((int)$_SESSION['customer_id'], CUSTOMERS_SHOW_DISABLED_PRODUCTS, true) ? ' OR p.products_status = 0' : '';
}

And modified the four queries to
WHERE (p.products_status = 1" . mv_show_disabled_products() . ")  

since I wanted to minimise the modification of the query.
