### ISSUE TITLE
move to function or class?

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#3795]
https://github.com/zencart/zencart/blob/d738150a6ac29ae31d52dc673af24ce0a36099db/admin/orders.php#L524-L577

any thoughts on moving this section of code to a zen function or the order class for re-use by a plugin?

it only requires 3 vars, ```$oID``` which is passed to the method, and ```$db``` and ```$zc_notifier```.

it would make the edit orders plugin much cleaner.

**Comment by drbyte** [comment]
The problem with putting all of that into a function is that it's really template code: it's almost all HTML.
And putting rendered HTML into a function makes it very hard to maintain.

So the bigger question to explore is: what exactly does "Edit Orders" as a plugin need to "change" in this area of the code? Is it just cosmetic? Or is there actual real logic that is critical to alter?

**Comment by proseLA** [comment]
no, edit orders does not need to change anything here.  i think that this is the point...

i'm just looking for opportunities to reduce code duplication as i "try" and help out with various things.

i have always hated that plugin.  it's confusing; the totals don't add up; i think the design is inherently flawed... MO.  (that said, on cursory look, the current maintainer is doing a much better job.)

for whatever reason, i have decided to move my clients to the latest version of it.  i am "attempting" to help out with the modernization of that plugin, for now, from a purely cosmetic standpoint; ie getting rid of gifs and using bootstrap buttons. and using the admin_head_html script.

it would be nice to not have to duplicate code; which the edit orders plugin does, in this place.

it would be great if the admin had a real templating system that plugin authors could leverage against.  as it does not, it seems that this was some low hanging fruit.

**Comment by drbyte** [comment]
In fact if memory serves me correctly that particularly prev/next navigation was inspired BY the Edit Orders plugin, with the aim of making that part of the EO plugin NOT require any customization or alteration of original code.

**Comment by proseLA** [comment]
not sure how that it is relevant here.

if my memory serves me correctly, i remember when stock ZC had a pull down menu for all of the orders in this part of the code/navigation; i remember having to pull that code out, as it was creating big performance issues. 

while there is no alteration necessary, each time that code gets updated in ZC, it will need to be updated in the edit orders plugin.  

let me try a different approach: let's assume edit orders is part of the base ZC code.  how would we change the structure of this part of the code?  or would we not?  and we would have duplicate code in both scripts?

**Comment by scottcwilson** [comment]
> In fact if memory serves me correctly that particularly prev/next navigation was inspired BY the Edit Orders plugin, with the aim of making that part of the EO plugin NOT require any customization or alteration of original code.

Are you sure that wasn't **Super** Orders?

**Comment by proseLA** [comment]
> 
> Are you sure that wasn't **Super** Orders?

you may be correct. memory is definitely not my strong suit. 

best.

**Comment by mc12345678** [comment]
I too recall it being Super Orders that added the order "navigation".

So, there has been a file added for the header navigation which is "html" related, would there not be a similar file/template to support the order navigation? Of course it would seem that it may be best suited to remain within `admin/orders.php`, but it could also be placed as a template file, a modules file, or in the includes folder to be drawn in by the associated code...

**Comment by drbyte** [comment]
I don't disagree that lots of "shared" output logic makes sense to extract out. But why are we doing that for 1 plugin?

Anyway, my bigger point is: 
That's begging for a full-on templating system.

I'd prefer to reserve that for a specific ZC release that does ONLY that.

One of the reasons I'm working on extracting all queries and business-logic "out" of the admin pages and into functions (and ideally classes) is (apart from allowing "logic" to be centrally contained to an "api" of sorts, eventually providing an endpoint to actually use it as such) so that converting the entire admin to using a proper template structure will be less prone to breaking, and relatively painless to do.

**Comment by proseLA** [comment]
> I don't disagree that lots of "shared" output logic makes sense to extract out. But why are we doing that for 1 plugin?

it's a popular plugin?  some would argue that the functionality of editing an order should be inherent in the base code of ZC. 

> 
> Anyway, my bigger point is:
> That's begging for a full-on templating system.
> 

yes please.

> I'd prefer to reserve that for a specific ZC release that does ONLY that.
> 
> One of the reasons I'm working on extracting all queries and business-logic "out" of the admin pages and into functions (and ideally classes) is (apart from allowing "logic" to be centrally contained to an "api" of sorts, eventually providing an endpoint to actually use it as such) so that converting the entire admin to using a proper template structure will be less prone to breaking, and relatively painless to do.

ideally classes....  yes, that would be ideal...

**this is not such a big deal.**  i'm just not sure at times what the focus is.  we add the admin_head_html; but not to all pages.  it somehow made it to the admin page registration (a page threatened to be removed); but not to admin users, profiles, etc.

i also understand it is far easier to sit on this side, critique and ask; then it is to sit on your side, decide and do.

i'll leave this open for another day or 2 in case someone else wants to chime in, and close soon thereafter.

best.
