### ISSUE TITLE
ZC forum access issues

### ISSUE THREAD

**Issue by simon1066** [zencart/zencart#3797]
Excuse my posting here - am unable to use the forum.

Not sure if you are aware of any underlying problems but as of yesterday when logging in to the forum (@simon1066) I get

You have been banned for the following reason:
No reason was specified.
Date the ban will be lifted: Never

Tried from different IP addresses in case there was a block of some sort - no joy. Given the apparent generic nature of the message and that I'm still 'Totally Zenned' I assume this is a mistake. 

Additional possibly related issues: 
- A couple of attempts at creating new accounts @simon1066_1 / @simon1066_2 (so I could post support requests) were partially unsuccessful in that I did not receive any activation emails (tried with two different email addresses and checked spam folder). 
- Used the forum sendmessage.php form  - no reply (but it could be that I haven't waited long enough).
- Password reset request sent but no email received.

**Comment by scottcwilson** [comment]
Simon, thanks for your message.  There's a lot of cleanup going on and you must have been caught up in it.  I'll ask the folks doing this to look at your account.

**Comment by scottcwilson** [comment]
You should be good to go.

**Comment by scottcwilson** [comment]
Please close this issue.

**Comment by drbyte** [comment]
Yahoo has started rejecting all our forum emails, which in turn marks the forum account as "bounced email" which suspends normal use of the account until it can be reviewed to ensure it wasn't tampered with (or created) by bots.

All the deliverability-checking tools say there should be nothing wrong, but Yahoo's AI has their own opinion.
We've attempted escalation, but thus far no response from them. Continuing to investigate options.
