### ISSUE TITLE
function zen_get_generated_category_path_ids: preg_replace

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3801]
I get debugs with this:
`$calculated_category_path_string = preg_replace('/<br ?/?>$/', '', $calculated_category_path_string);`

> --> PHP Warning: preg_replace(): Unknown modifier '?' in .....\includes\functions\functions_categories.php on line 1007.

This is my mongrel shop, so the line numbers do not match core code.
Anyway I believe the / should be escaped:
`$calculated_category_path_string = preg_replace('/<br ?\/?>$/', '', $calculated_category_path_string);`

**Comment by drbyte** [comment]
Yes, either escaped or a different delimiter used.
