### ISSUE TITLE
new plugin installer....

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#3807]
i'm a little confused.

zc157 has packaged 1 admin plugin.  i installed that plugin (Display Logs) and that plugin does not show up on any of the admin menus, but instead provides something in the message stack.

i am trying to package my plugin, it seems to work, but the plugin is now on the extras menu and it is there twice.

if i disable my new plugin, both entries get removed.

i am not sure if i am doing something wrong; if there is a bug in the plugin installer or how the display logs does not come up on a menu.  

would appreciate any guidance on the subject.

**Comment by zcwilt** [comment]
The DisplayLogs plugin should appear in the tools menu.

For your plugin,what method are you using to add the plugin to the menu

For the DisplayLogs plugin it uses an Installer/ScriptedInstaller.php file.
Are you using the same method for your plugin.

**Comment by proseLA** [comment]
i have nothing in the installer class....

when i looked here:

https://docs.zen-cart.com/dev/plugins/encapsulated_plugins/directory_structure/

i saw nothing on the installer class....  i suppose if i would have looked a few entries down on the side bar, it would have provided some help.

i'll look a bit at the installer class and play around.  i'll let you know what i come up with...

thanks for the input!

**Comment by scottcwilson** [comment]
> ... i saw nothing on the installer class ...

Yep, what's there is correct but confusing.  The Installer folder is optional and this example happened not to included it.  I will add it for clarity.

**Comment by proseLA** [comment]
> The DisplayLogs plugin should appear in the tools menu.
> 
> For your plugin,what method are you using to add the plugin to the menu
> 
> For the DisplayLogs plugin it uses an Installer/ScriptedInstaller.php file.
> Are you using the same method for your plugin.

some answers, more questions.  i had previously added some entries into using the admin page registration tool to demonstrate a point in a since merged PR.  so there were 2 separate rows in the `admin_pages` table.  that is why i was seeing double.  i forget some of the things i do.  now, when the plugin manager disabled my plugin, the behavior was as expected, however the rows in the `admin_pages` table were unaffected.  so the field `display_on_menu` was set to `Y`, but no entries were displayed on the menu.  as someone who likes to look at data, i find it a bit confusing.  it seemed to affect those rows without displaying them.  i'm guessing it's building some sort of new array?

my next question concerns file paths.  let's say i am building a new plugin, whose class loads other classes from various vendors.  outside of this installer, i might do something like this within my plugin:

```require DIR_FS_ADMIN . 'includes/classes/prose/vendor/autoload.php';```

will that code now work with the new encapsulated plugins?  or should i reference that in a new way so that those vendor classes get properly loaded?

thanks in advance.

**Comment by drbyte** [comment]
> when the plugin manager disabled my plugin, the behavior was as expected, however the rows in the `admin_pages` table were unaffected. so the field `display_on_menu` was set to `Y`, but no entries were displayed on the menu.  as someone who likes to look at data, i find it a bit confusing. it seemed to affect those rows without displaying them. i'm guessing it's building some sort of new array?

No, this is not new behavior. If the language-defines for the menu entries don't exist then the menu entry is skipped (cuz there's nothing to display). That's why both entries disappeared as soon as you disabled the plugin (causing its defines to not load).

**Comment by proseLA** [comment]
thanks.
