### ISSUE TITLE
Is it time for Responsive_Classic to be the Template_Default?

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#3818]
With today's proliferation of mobile devices, isn't the use of template_default outdated?  Just like having a non-SSL site, today's non-responsive site is a kiss of death in the SEO race.

I understand the use of template_default to have a fall-back area for files not changed but, with responsive templates, there's no fall-back to a responsive file.  https://www.zen-cart.com/showthread.php?219735-Responsive-Classic-(built-in-to-Zen-Cart-v1-5-5)-Support-Thread&p=1371472#post1371472

I've been looking at the two files in the docs on custom templates and they are incorrect when it comes to adding responsive_classic files to a custom template.  The docs can be changed, of course, but can become a convoluted mess in doing so.

If responsive_classic were to become the new template_default, we would be moving Zen Cart totally into the modern era template wise.

We brought responsive_classic almost totally compliant with accessibility for 1.5.7 and I have been working on revising it even more than the color change mod haredo and I came up with.  When really played with and broken down, I have the template down to four background colors, four font colors, and two border colors.  Even those could easily be doubled to show the store owner the locations of the colors but, this way, the cart is ready to go from the start.

This breakdown has also unearthed many layout problems (e.g. on the product listing if it is sold out, free, has a discount available, or any other non-standard item in the cartBox.  I believe I've gotten pretty much all of that gone.  I still have to finalize the shopping cart and checkout pages for it to be complete.  (is OPC going to core)  You can see the work at sepialiteratureDOTinfo  The radius settings are at the behest of the client.  The only current problems with accessibility is a couple of forms that were missed in 1.5.7 when they were named.

Summarizing:
Proposed Steps:

1. Classic should go
2. template_default be infiltrated by responsive_classic.

Result:

1. Either one template ready to sell or
2. One template needing a few color changes - then sell

The pros should be obvious.  The cons are more with an upgrade than anything else I can see.

**Comment by wiztechinc** [comment]
I'm sure this will come as no surprise but no, I do not agree. If the responsive was attractive and followed good graphic rules, I might be okay with this. But it's only an example of responsive, not an example of good practices from a visual / graphic view.

**Comment by dbltoe** [comment]
No, I'm not.  Nor was I touting it as whiz bang, graphic phenom.  I think you would at least agree that Classic holds no use.

Template_default's only claim to fame is as a repository for files that aren't normally edited.  It certainly can't be used by any store.  In 1.5.7, it's not even available as a selection for testing.  Responsive_classic is the default in 1.5.7

And, if a storeowner does as in the above thread, the fall back is not to responsive_classic but to template_default which will cause the template to fail in many cases.  Mods are often confusing as to whether or not the new template file goes in template_default or YOURTEMPLATE.

Give me sales over visual/graphic any day.  I've yet to find an SE that can see it anyway.

**Comment by wiztechinc** [comment]
I believe the fall back is more about alerting the store owner that he/she screwed up. Sales - well, I want to tell you in no certain terms that black as the predominating color generally hurts sales. That's what I mean by graphic rules.

**Comment by dbltoe** [comment]
Black Sales Matter 😀 

Seriously, we're talking concept and you're a no for color?  The beauty will be that, finally, it can be easily changed to pink in minutes.

**Comment by wiztechinc** [comment]
Prospective zen cart owners look at ..... color. Not concept.

**Comment by scottcwilson** [comment]
@dbltoe Would you be willing to take charge of removing the black from the responsive classic template so we could move forward?  Maybe provide three palettes that meet accessibility level A (for more flexibility), then we could provide three screenshots and instructions for switching? 

I would think that changing stylesheet_colors line 29 and 30 would do the trick, then line 37 to match.

**Comment by scottcwilson** [comment]
@drbyte has argued against this.  Suggest closing this ticket.

**Comment by lat9** [comment]
FWIW, I'd much prefer for the base template to be a standards-based one (e.g. Bootstrap-4).  The use of that MobileDetect script by responsive_classic can be a right PITA.
