### ISSUE TITLE
Removal / change category-tabs menu

### ISSUE THREAD

**Issue by wiztechinc** [zencart/zencart#3822]
Aside from color, the full display of the categories-tab in the default zen cart on the desktop can be extremely distracting when there are multiple categories because it takes up tons of real estate on the desktop.  The added padding for the responsive has made this issue much worse while it meets standards and is more fully realized. 

In all my years of working on Zen Cart, I have never had one client who wanted it and I have only suggested it once where it was appropriate while there were only a few categories. On the mobile version, this menu is hidden or only displayed in the menu (I have not delved into how this works on the responsive template but find it hard to believe it's the same cat menu?). 
Though many are using mobile devices, I find that most of my clients are still using desktop computers in their businesses. This becomes more important when looking at the age of the client themselves which then sometimes drives the age of their customers. Both of my most recent clients are in their 70s and 80s and frequently these older clients come with an already established website of many years in existence.

So, I'm suggesting one of three options:
1) Turn off the default. Do not display this at first. 
2) Re style / recode the tabs into something that can be worked with (for other templates besides the zen cart responsive). I like the option of a new menu as part of default zen cart akin to the ones in existence but is way better than the old standards with hard coded links for some things.
3) Alter it so that it only displays a certain number/length of category names and then has an additional "more" link.

 3 - Alteration of the actual code seems to me to be a time waster in reality as my experience says few folks ever use the cat-tabs at all.

2 - I've worked at getting css to improve the display of these links but find it extremely hard to work with when there are a number of categories. The responsive solution is actually a pretty good fix in this case except for real estate issues.  Mods can fix this if someone is determined to have that top menu but I have developed all sorts of other ways to get around using anything such as ezpages links that highlight certain categories. Or I totally rework the old mods to add more functionality into the top menu links.  I'm not fully satisfied with any of it as it stands right now but would be open to working on an alternative for default zen cart.

1 - my choice! Again I'm thinking not about the working site after installation but the example site that folks see when zen cart is first installed as a tool to sell clients on Zen Cart.

Please respond with your experiences and thoughts as I'm really curious as to how many folks actually leave this turned on.

**Comment by scottcwilson** [comment]
I have several clients who like this.

**Comment by barco57** [comment]
I also have not had a client in a very long time use the cat tabs

**Comment by wiztechinc** [comment]
So would you be agreeable to having it turned off from the start in the default? I wasn't suggesting getting rid of it.

> I have several clients who like this.

**Comment by drbyte** [comment]
I'm intentionally not voicing an opinion at this early stage of discussion.

I do have a question: for storeowners who "want to show all their categories across the top" (let's say they have maybe 5) and find it cumbersome to have to use EZ-Pages Links to create a horizontal nav containing them (and rename them by hand if they rename a category later), what sort of thing/setting/whatever would they be asking for in order to "find out" that Zen Cart has a feature already available to dynamically show all their categories automatically, including changed category names, etc?  
(I agree that "category tabs" isn't an intuitive setting name for them to search for ... er, well, unless they find that term listed on the forum in response to asking there for how to do this very thing. What would that intuitive setting/term/name be?)
How would they know the feature exists in order to turn it on, if it weren't "on by default" and can be "turned off in 3 clicks" if they don't want it?

Okay, I guess that's two questions:
- intuitive name for the feature so it's easily found for enabling
- how to make sure they know the feature exists if it's not enabled by default

(And, yes, I agree that the demo products have too many categories for it to make good sense to display by default. Perhaps some default styling that makes that appear better is in order. Or limiting it as you suggested. But seeing some examples of working alternatives would be helpful.)

Anyway, I posed 2 questions which I think would help the discussion (at least, they would help me anyway)

**Comment by wiztechinc** [comment]
> I'm intentionally not voicing an opinion at this early stage of discussion.
> 
> I do have a question: for storeowners who "want to show all their categories across the top" (let's say they have maybe 5) and find it cumbersome to have to use EZ-Pages Links to create a horizontal nav containing them (and rename them by hand if they rename a category later), what sort of thing/setting/whatever would they be asking for in order to "find out" that Zen Cart has a feature already available to dynamically show all their categories automatically, including changed category names, etc?
> (I agree that "category tabs" isn't an intuitive setting name for them to search for ... er, well, unless they find that term listed on the forum in response to asking there for how to do this very thing. What would that intuitive setting/term/name be?)
> How would they know the feature exists in order to turn it on, if it weren't "on by default" and can be "turned off in 3 clicks" if they don't want it?
> 
> Okay, I guess that's two questions:
> 
> * intuitive name for the feature so it's easily found for enabling
> * how to make sure they know the feature exists if it's not enabled by default
> 
> (And, yes, I agree that the demo products have too many categories for it to make good sense to display by default. Perhaps some default styling that makes that appear better is in order. Or limiting it as you suggested. But seeing some examples of working alternatives would be helpful.)
> 
> Anyway, I posed 2 questions which I think would help the discussion (at least, they would help me anyway)

Right to the most important point! I would call it category header menu myself but I absolutely do not know how new owners can be informed about the feature. I was hoping this conversation might help generate some ideas.

**Comment by wiztechinc** [comment]
Here's the screenshot from my large monitor (27"?) with a probably different resolution than most folks use.
![image](https://user-images.githubusercontent.com/5367263/89227396-99855f00-d5ab-11ea-99a5-c3098dbf3ab7.png)

pulling in the browser to a narrower width does this:
![image](https://user-images.githubusercontent.com/5367263/89227507-cdf91b00-d5ab-11ea-89ee-91b3f5482fb1.png)
with no menu button and a reduced/changed header. I hadn't actively realized that til now.

**Comment by dbltoe** [comment]
Your second shot has gone into tablet screen size.  Thus the dropping of some items.  Not quite correct in 1.5.7 and one of the things I've been working on.
Accessibility rears its head more here than anywhere else as clickable areas need to be large enough to prevent two or three items from being selected at once with big fingers.
We normally turn it off but, I would turn it on and turn off categories in a low-category-count environment.
Perhaps leave it with an option to display or not when creating a category.  Could get the customer to featured categories in a hurry.

**Comment by wiztechinc** [comment]
Oh, thanks for the explanation. I like your suggestion as a possible mod!

**Comment by scottcwilson** [comment]
One potential resolution to this problem could be adding another screen to the install process with checkboxes corresponding to desired sideboxes (or even other desired configuration settings).

**Comment by wiztechinc** [comment]
> One potential resolution to this problem could be adding another screen to the install process with checkboxes corresponding to desired sideboxes (or even other desired configuration settings).

Though this is a good idea, I'm not sure how helpful it might be for a first time website owner who knows very little. I run a sql query to fix multiple sideboxes so avoid any issues usually. I personally would be curious to have someone's reactions to this scenario. Hard to test out without a fair amount of work I guess. 

Making things more user friendly is something that I really want in admin with all those settings, but I can see how this could be handy if combined with a pic of each sidebox. Switching back an forth between browser windows is unwieldy and then they have to hunt thru it all to see if they turned off the wrong one. Personally I've found it extremely easy to select the wrong sidebox - selecting the next one down - so I have to check each time!

**Comment by scottcwilson** [comment]
> I can see how this could be handy if combined with a pic of each sidebox.

Delia, if this is something you'd like to add to the documentation, a PR would be welcome.

**Comment by dbltoe** [comment]
Not a fan of this idea as most who load Zen Cart have little concept of all the things it can do nor which way they will go once the store is up.
I can see a store owner knowing if items will be virtual or not.  I can see them knowing whether just anyone can see the prices, will it be dual-priced, or the customer will be required to log in to shop.
Most of our customers have not formulated a category layout prior to cart installation.  Nor, do they have any idea what they might do with sideboxes.  We generally recommend the scrolling sideboxes for product emphasis but there's nothing for category emphasis.
It's more of a location versus categorical solution.  Not unlike the grocery store where the milk, bread, and egos are NEVER together and the candy is ALWAYS at checkout; most store owners feel limited by having several popular items "hidden" from view by the category structure.
Converting the menu to an emphasis menu (categories, products, or both) seems to be a winner.  Adding a bunch of operational choices to the installation may just scare folks away.

**Comment by drbyte** [comment]
As I re-read through this, and related "customization" and "admin settings" discussions, it seems to me that what would be most helpful for the storeowner is a few documentation pages that discuss the various configuration (eg: store layout) features that are (and are not) enabled by default, so they can decide for themselves if/when they wish to make those adjustments, along with how/where to do it.
That way, the many features that are currently enabled-by-default in order to show that the feature exists, can remain.

I'm thinking here of (don't celebrate too loudly here) replacing the book ad in the default template with a link to https://docs.zen-cart.com/user/. And maybe on that page pull the "New User Topics" section up to just below the "First Steps" topic, before the rest of the alphabetical list.

**Comment by dbltoe** [comment]
💯

**Comment by drbyte** [comment]
Okay, I've updated the link. This way people are drawn to the docs site as their primary reference. And each page there talks about how to use the Forum to get more interactive help if needed.

**Comment by barco57** [comment]
> (don't celebrate too loudly here)

Yahoo! This is your celebration
Yahoo! This is your celebration
Celebrate good times, come on (Let's celebrate)
Celebrate good times, come on (Let's celebrate)
There's a party goin' on right here
A celebration to last throughout the years
So bring your good times and your laughter too
We gonna celebrate your party with you
Come on now
Celebration
Let's all celebrate and have a good time
Celebration
We gonna celebrate and have a good time
It's time to come together
It's up to you, what's your pleasure?
Everyone around the world, come on
Yahoo!
It's a celebration
Yahoo!
Celebrate good times, come on
It's a celebration
Celebrate good times, come on
Let's celebrate
There's a party goin' on right here
A dedication to last throughout the years
So bring your good times…

**Comment by wiztechinc** [comment]
> > I can see how this could be handy if combined with a pic of each sidebox.
> 
> Delia, if this is something you'd like to add to the documentation, a PR would be welcome.

What? Actually work and shut up? I can do that! Good ideas, Guys!

**Comment by scottcwilson** [comment]
If you look at 
https://docs.zen-cart.com/user/template/sideboxes/

you can see how I took a couple of screenshots and displayed them. 

You could put your new content here:
https://docs.zen-cart.com/user/sideboxes/sidebox_list/

**Comment by scottcwilson** [comment]
> I'm thinking here of (don't celebrate too loudly here) replacing the book ad in the default template ...

What I'd really like is to get the book back in print.  I find it completely baffling that Goh has walked away after all that work.

**Comment by wiztechinc** [comment]
> If you look at
> https://docs.zen-cart.com/user/template/sideboxes/
> 
> you can see how I took a couple of screenshots and displayed them.
> 
> You could put your new content here:
> https://docs.zen-cart.com/user/sideboxes/sidebox_list/

I notice that the images are pngs - is that because of coding that reduces the size of the images for responsive? I don't normally use pngs due to the larger size and reduce using css sometimes or just don't make the images large enough to need reducing.

Since I haven't done anything with docs, I got some learning time here with prs. I see where it is on github but right off-hand, don't see editing content. Haven't done much looking yet - any advice or directions?

**Comment by wiztechinc** [comment]
> What I'd really like is to get the book back in print. I find it completely baffling that Goh has walked away after all that work.

If there are no copyright issues concerned with it (Goh is listed as the copyright holder), and we can get some working files, this is right up my alley for work. I also have an indexing program (not auto but helps) and have published books before. Don't even need a publisher for this if you have the right tools.   But the lack of index was a major minus on that book.  No index means you might as well not publish.

**Comment by barco57** [comment]
> But the lack of index was a major minus on that book.

There are 8 pages of index at the back of the book...
Was the index great, no.... but it would let you get close to something you were looking for most of the time.

**Comment by wiztechinc** [comment]
> If you look at
> https://docs.zen-cart.com/user/template/sideboxes/
> 
> you can see how I took a couple of screenshots and displayed them.
> 
> You could put your new content here:
> https://docs.zen-cart.com/user/sideboxes/sidebox_list/

I'm getting there. So I do have a question, off-topic(ish). I've never understood how the sideboxes sort after left/right/sort order. Is there some sort of sorting scheme I've just never realized? I want to do these in the best order, either as the non activated  or alphabetically.

**Comment by scottcwilson** [comment]
> I've never understood how the sideboxes sort after left/right/sort order. 

Would you please open a forum thread about this question?  This post is already getting pretty long.

**Comment by mc12345678** [comment]
Ummm.. What about something somewhere (would suspect online, but may be in print with number/letter references) that shows a default view of the catalog with clickable "areas" to pull up documents associated with the clicked/referenced item?
Sideboxes, this Category Tabs feature, the Congratulations! text, etc... ?

**Comment by scottcwilson** [comment]
I welcome documentation PRs.  You can see 

https://docs.zen-cart.com/user/template/page_format/ 

as what's there now.   The header help in particular needs, well, help. :)

**Comment by scottcwilson** [comment]
@wiztechinc is working hard on getting the sideboxes list page in shape - I'll post a link when it's complete.

**Comment by scottcwilson** [comment]
https://docs.zen-cart.com/user/sideboxes/sidebox_list/
