### ISSUE TITLE
zc158: Laravel error handling

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#3823]
Some of the Laravel-detected issues get reported in a log in the `/logs` directory, but some get reported in `/app/storage/logs/laravel.log`.  This is going to be an issue going forward since (1) the logs aren't consolidated and (2) there's no time delineation on the naming of that Laravel log-file.

Sooner or later a zc158 site's going to run out of storage due to accumulated Laravel logs that can't be 'timed out' like the [Log Manager](https://vinosdefrutastropicales.com/index.php?main_page=product_info&cPath=2_3&products_id=73) does for the logs recorded in the `/logs` directory.

Is there a way that (preferably) those logs can be 'promoted' to be visible in the `/logs` directory or at least get the log-file's name to include the date/time that they're issued so that they can be programmatically managed?

**Comment by drbyte** [comment]
Laravel's error logging can be changed from `single` to `daily` in the `app/config/logging.php` file.
This makes its log filename be date-specific, which is consistent with typical server log-rotation strategies.  One could then use some sort of zip-archiving like log-rotations often do, or delete files by date, etc. 

I'll commit this change.

**Comment by zcwilt** [comment]
Just a note. While working on code to upgrade from Laravel 5.8 to Laravel 7, have come up with a better way to completely 
disable laravel logging. While I prefer having the 500 error pages and the laravel woops pages while developing, this is something that can be added back later using developer flags

**Comment by drbyte** [comment]
Closed by #3831 ... at least for now.
