### ISSUE TITLE
EMAIL_ATTACHMENTS_ENABLED - fix or kill?

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3827]
According to the comments in `admin/mail.php`, this setting only works in certain conditions (I have not verified this).  It's also undocumented.   

Should we fix it or remove it?

**Comment by lat9** [comment]
Fix or remove from `admin/mail.php` or in general?  FWIW, I use that functionality in `zen_mail` to attach PDF invoices to after-order emails for a couple of sites.

**Comment by scottcwilson** [comment]
Sorry, I meant fix or kill the attachment functionality.  Dr. Byte has removed the comments so maybe it works?  It does need documenting for sure.

**Comment by scottcwilson** [comment]
Say .... @lat9 would you document this? :)

**Comment by lat9** [comment]
@scottcwilson, if you'll open a document issue that identifies where you'd like the content documented, I'll be happy to.

**Comment by scottcwilson** [comment]
Issue created in documentation repo.

**Comment by drbyte** [comment]
> It does need documenting for sure.

Don't document it (which draws attention to it creates support expectations) unless you intend to fully implement the functionality so that it works for everyone on all servers and never introduces security problems by uploading attachments for temporary use in emails.
