### ISSUE TITLE
Display Logs: Update to include `app/storage/logs/*.log` files, too

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#3830]
Since those Laravel logs are also significant, they should be displayed as well.

I'm unclear how to handle the first (?) plugin update.  When I create v3.1.0 of the plugin, do I include **_all_** the plugin's files in the `/zc_plugins/DisplayLogs/v3.1.0` sub-directory or only the files that have changed?

**Comment by lat9** [comment]
Possibly not needed, due to [this](https://github.com/zencart/zencart/pull/3831) PR.

**Comment by zcwilt** [comment]
To answer your other question.

A plugin version should contain all the files required

Don't forget, in normal circumstances, some one may download version 3.1.0 without ever downloading v3.0.0

**Comment by lat9** [comment]
Thanks, @zcwilt, for the information and the update via that PR.
