### ISSUE TITLE
Question: v158, what are the files generated in /app/storage/framework/views?

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#3832]
There are a bunch of apparently runtime-generated .php files in the subject sub-directory.  What are they used for and 'who' generates them?

**Comment by drbyte** [comment]
Laravel's "output" templating system uses `/resources/views/*.php` (and subdirs) to arrange templates used for generating page output. It's called the "view layer" of the application.

Laravel has a templating engine, called Blade. This allows for both bespoke PHP code and also replaceable parameters and other logic such as looping through resultsets etc. All this gets "compiled" at runtime, and "cached" into the `/storage/framework/views` directory.

Essentially that `/storage/framework` subdir in Laravel is all cache-related stuff of some sort or another.

Laravel generally manages the caching well in terms of regular cleanup, but you can manually force a clearing of the "view" cache with a command-line command:  `php artisan view:clear` run from within the Laravel directory.

**Comment by lat9** [comment]
Thanks for the detailed explanation (I just like knowing what I'm dealing with)!
