### ISSUE TITLE
The url for this store self will be treated as spam

### ISSUE THREAD

**Issue by rubnet** [zencart/zencart#3835]
from v157 
If some customer input the url for this store self  , [this regex](https://github.com/zencart/zencart/blob/v157/includes/classes/observers/auto.non_captcha_observer.php#L73) will treat it as spam

**Comment by drbyte** [comment]
Hi,
Thanks for your note.

Can you provide an example? Why would the customer put the store URL into the firstname or telephone field?

**Comment by rubnet** [comment]
If the customer put the store URL into the enquiry field in contact_us page , then the system will treat it as spam
eg. The url is start with  [HTTPS_SERVER](https://github.com/zencart/zencart/blob/v157/includes/dist-configure.php#L22)  .

Thanks for your help.

**Comment by drbyte** [comment]
Does this change resolve it correctly?
https://github.com/zencart/zencart/pull/3837/files

**Comment by rubnet** [comment]
Yes, wonderful ! Thanks for your quick patch.
