### ISSUE TITLE
Feature? Add confirm email address to account-creation page

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3845]
This refers to the "Confirm Email Address" mod 
https://www.zen-cart.com/downloads.php?do=file&id=107

which requires the email address to be re-entered in a second field, and checks that the two fields match. 

![image](https://user-images.githubusercontent.com/4391638/89626212-0bd59800-d867-11ea-9eca-723d7ee2d9f2.png)

This is a small change which gives you a big boost in data quality and saves busy storeowners from having to deal with complaints. 

(This is not a recommendation that we send registrants a verify link for them to click and verify their email.)

**Comment by drbyte** [comment]
Is this different from https://github.com/zencart/zencart/issues/3803 ?

**Comment by scottcwilson** [comment]
Clarification added.

**Comment by lankeeyankee** [comment]
yes, should defo be part of core!

**Comment by vandijkstef** [comment]
Unsure if this should be part of the core. If it does, we probably want to hook it up to an option. Please consider [this article on the UX of email in forms](https://uxmovement.com/forms/why-the-email-confirmation-field-must-die/) before moving on. It will likely NOT save busy storeowners any time, and it will likely frustrate users.

**Comment by drbyte** [comment]
For those who 'want' this feature, when are people mistyping their own email address?
Are they primarily on mobile devices? (small keyboards?)
Are they unsophisticated users who have no knowledge of password-manager and identity-manager features of their devices which can handle auto-fill without typos?

I think a better user-experience would be an ajax widget that at least looks for common typos (as suggested above) as a basic enhancement. 
(An enhanced regex for the email field, which blocks common misspellings could be an option too)
Even better, could use a 3rd-party service to do instant verification of the email. Busy stores could justify the monthly fee for the 3rd-party service.
