### ISSUE TITLE
duplicate notifiers present potential problem

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#3865]
https://github.com/zencart/zencart/blob/5f9f6abf03b8867d48ec38caca64a34731480fe9/admin/includes/modules/copy_product_confirm.php#L115

https://github.com/zencart/zencart/blob/5f9f6abf03b8867d48ec38caca64a34731480fe9/admin/includes/modules/copy_product_confirm.php#L188

unless i am missing something, i do not know why there are 2 notifiers with the same name.  i have confirmed that the notifier will get called twice.  i think that is a bug and the notifier should only get called once.

**Comment by drbyte** [comment]
My first question is: how/who/when did it get put there in the first place?
To figure that out, look through commit history of the file (github has a History button in top right of the file, and also has a Blame button that lets you look through history of line-numbers).

I see that the duplication, introduced in 1.5.7, came from @lat9 in #3186, which was in response to a concern posted by @scottcwilson in #3185, which refers to code that came in a PR from @scottcwilson in #3161

**Comment by proseLA** [comment]
i am aware of the blame button.  i do use it frequently.  thanks for reminding me of it.  i did not look at it prior to submitting this issue, as the duplication makes little sense to me.  it just seems like a bug.  i could be wrong.

it looks to me that the duplication was introduced prior to that, as i see it cleaned up in #3053.  i see it in the use compact commit in that big pr.  so it predates the other prs referenced here.

it looks like the duplicate one was added here #2981 by @lat9.  so perhaps she can shed light on it.

finally, in working with this observer, i like what @scottcwilson did in #3161.
