### ISSUE TITLE
v156 and earlier, Intentional language loading style/sequence?

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#3868]
Just spent a great deal of time trying to chase down where to change content in a language file...

Here's the issue that I seem to see. I'm working in a multi language site. It is/was being upgraded. Old language files were carried over, existing files were updated to contain the defines expected of the version being installed. Problem is/was that on the main page for example, some characters in the foreign language appeared as if mixed content or incorrectly encoded content. So off to file and content searching I went.

In the search for something that was "unique" in the text displayed, I found content that matched and it matched more than one file.. But it seemed that when I changed a file that was "expected" that the changes were not carried over to the main site, but it also now seems like it opens several operations/capabilities. 

language files in question/problematic:
includes/languages/FOREIGN_LANGUAGE/YOUR_TEMPLATE/index.php
includes/languages/FOREIGN_LANGUAGE/YOUR_TEMPLATE/index-10-01-2012.php

Seems that the code in the template_func class: 
````php
  function get_template_part($page_directory, $template_part, $file_extension = '.php') {
    $directory_array = array();
    if ($dir = @dir($page_directory)) {
      while ($file = $dir->read()) {
        if (!is_dir($page_directory . $file)) {
          if (substr($file, strrpos($file, '.')) == $file_extension && preg_match($template_part, $file)) {
            $directory_array[] = $file;
          }
        }
      }

      sort($directory_array);
      $dir->close();
    }
    return $directory_array;
  }
````
is indiscriminate of the "length" of the filename and simply loads anything that has a `.php` extension and begins with the referenced file's name (e.g. indexXXXXXXX.php where XXXXXXX could be anything that is permitted in a filename.

On this site what was further interesting was that 
includes/languages/FOREIGN_LANGUAGE/YOUR_TEMPLATE/index-10-01-2012.php
loaded before:
includes/languages/FOREIGN_LANGUAGE/YOUR_TEMPLATE/index.php

even though these are alphabetically reversed... 

Something of a bit of further concern is if these files had loaded in the "proper" sequence, then issues may not have been so readily identified; however, it does somewhat call to question how languages will load in newer versions where it may be even easier to overwrite a defined language variable (I don't really want to use the term constant as the plan is to use an array)... I mean as a result I've figured out how to resolve this site, but I guess may be trying to learn another aspect of ZC and/or see if there is something that should be modified or if it is to some extent intentional...

**Comment by torvista** [comment]
I remember falling foul of this long ago, subsequently I have always put the comment in the extension, and have never had a problem since.

I have piles of files next to one another that I use for easy comparison/reference where I have made core modifications:
whatever.php
whatever.155 php
whatever.156 php
whatever.157 MV customdatecomment php

**Comment by drbyte** [comment]
Catalog-side, yes, it did a fuzzy-matching of filename for language-define loading.

This allowed things like the "account" page to load related defines from the other "account" sub-pages, for example.

**Comment by mc12345678** [comment]
Torvista, yeah if I were the first one to be touching the language files, I too would do something to modify either the extension or the prefix of the filename or both as those two characteristics can be found in one way or another throughout the default load sequences.  In my case, carry over of someone else's work to an extent when trying to carry over the foreign language to the new location. Surprisingly something was done in just the right sequence as identified elsewhere in the issues to allow the files on the original site to load in the "alphabetical" sequence where on the copy it loaded in this case reverse alphabetical (really hard to say what the determining factor was in a grouping of only 2 files) but was one of those "No, that file can't be the one that has the content" moments until I pulled up a `preg_match` tool and tried several filenames. Then I began eliminating the extra override files to get back to what was really expected/needed.

Ok, so somewhat a momentary "lapse" or perhaps a learning moment. Will have to see if/how this can be further applied to other coding operations to try to offer simplified expansion of definitions.

Still not sure why the load sequence responded the way it did, though I have the current desired result and see that there is/was a purpose for the load "method". Thank you for the input, if I forget to close this within a few days, please do.
