### ISSUE TITLE
v157 PHP notice in freeshipper.php

### ISSUE THREAD

**Issue by dennisns7d** [zencart/zencart#3874]
PHP 7.1.29 (XAMPP)

I've got freeshipper configured with Shipping Zone set to a zone (not --none--). Navigating to admin->Modules->Shipping trips the following PHP notice:

`[11-Aug-2020 19:48:02 America/Los_Angeles] Request URI: /zencart157sww/zcadmin/index.php?cmd=modules&set=shipping, IP address: 127.0.0.1
#1  freeshipper->__construct() called at [C:\xampp\htdocs\zencart157sww\zcadmin\modules.php:204]
#2  require(C:\xampp\htdocs\zencart157sww\zcadmin\modules.php) called at [C:\xampp\htdocs\zencart157sww\zcadmin\index.php:11]
--> PHP Notice: Trying to get property of non-object in C:\xampp\htdocs\zencart157sww\includes\modules\shipping\freeshipper.php on line 34.

`
The PHP notice is not tripped if Shipping Zone is set to --none--.

**Comment by dennisns7d** [comment]
Similar PHP notices can be tripped in other shipping modules: flat, freeoptions, item, perweightunit, and table.

I suspect that these notices are tripped because the $order object doesn't exist when accessing the modules in this manner.

**Comment by scottcwilson** [comment]
@dennisns7d would you like to PR this?

**Comment by dennisns7d** [comment]
I'll work on it this afternoon.
