### ISSUE TITLE
returning empty array in InitSystem?

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#3884]
https://github.com/zencart/zencart/blob/34742ca0005cb3f2a22f751b7a880539ae2b99fc/includes/classes/InitSystem.php#L215-L222

so, i have not dug in, but i'm guessing that this is part of the new plugin process?  (of which i am a fan!)

in v157, i received the notice `PHP Notice:  Undefined variable: autoLoadConfig in ...:220`; and now when i look at v158, that has been corrected by initializing that var to an empty array.  but we are not putting anything into the array.  so i'm confused as to what is the point of the var, and the return of an empty array?

**Comment by proseLA** [comment]
sorry, i got it...

**Comment by proseLA** [comment]
one last thing, i think this is worthy of inclusion here:

https://www.zen-cart.com/showthread.php?226872-Known-bugs-(and-fixes)-for-v1-5-7-series

**Comment by drbyte** [comment]
Technically it should always get defined, because the files being `require`d will define or add to the array.

**Comment by proseLA** [comment]
in theory, i agree with you.  in practice, i am not sure why i would have seen the PHP notice, i posted above. given that it is not a vanilla install, and that i'm currently too buried to try and track it down/recreate it; i'm not worried about it.  however, ian added the initialization of the array after the release of 1.5.7. i can think of a few reasons why: 

- he ran across the same error i did
- his IDE complained to him
- it is better coding style.

perhaps something else.  it is not important.  sorry to have opened this issue.

**Comment by drbyte** [comment]
No worries. It's good to have captured it. 
I agree it may be worth backporting to 1.5.7.

@zcwilt thoughts?
