### ISSUE TITLE
Coupon Pages still using old styling

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3888]
Most of the admin has been refreshed and looks so much better, but the coupon page is still looking like it did 15 years ago.  @Zen4All help us!  You're our only hope.

**Comment by Zen4All** [comment]
:smile: I'll take look at all admin files. I was standing in my corner waiting for changes to slow down a bit, as the development is going in a fast pace lately. But if people can stay away from the coupon pages for a few days, I will make a PR

**Comment by scottcwilson** [comment]
LOL I know what you mean! Much appreciated.

**Comment by drbyte** [comment]
👍

**Comment by scottcwilson** [comment]
Once complete, I will update screenshots in documentation under #3820

**Comment by drbyte** [comment]
Closed in #3911
