### ISSUE TITLE
Create a brands centerbox 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3907]
Why not build a brands centerbox and then let the brands page use the brands centerbox? 

I see two benefits: 
- people could feature brands on their home page
- the brands page could be a model for people who want to build other centerbox based pages (like turning the Featured Products page into a grid by using the centerbox).

**Comment by drbyte** [comment]
> and then let the brands page use the brands centerbox?

What do you mean by "let the ... page use the ... centerbox"? 
What's the architecture of this look like in your mind?

Am I correct that indirectly you're also proposing a rewrite of the new/all/featured/specials pages as well? I'd like to see a list of pros/cons and the problems this is attempting to solve.

**Comment by scottcwilson** [comment]
Not suggesting changing new/all/featured. 

Just saying that if you built a centerbox then used it on the page as well, you'd let people display this info in two places.

**Comment by drbyte** [comment]
Is there a clearer title for this Issue that captures the intention of this discussion?

**Comment by scottcwilson** [comment]
This could be done as a plugin.
