### ISSUE TITLE
ZC 1.5.8: function zen_date_raw() is no longer found in admin

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#3919]
There may be more uses, but admin/customers.php makes use of the function ```zen_date_raw()```.  This function is no longer found on the admin, and gives a fatal error.
https://github.com/zencart/zencart/blob/b39301512b200db0c519169ac94c4b5e17eeeb02/admin/customers.php#L125

**Comment by Zen4All** [comment]
Also used in:
- banner_manager.php
- featured.php
- products_price_manager.php
- salemaker.php
- specials.php

**Comment by lat9** [comment]
... and various site-specific customizations.

**Comment by drbyte** [comment]
It's in `english.php` because it relates to the locale
