### ISSUE TITLE
Define Pages looking for define_pages_editor.css

### ISSUE THREAD

**Issue by wiztechinc** [zencart/zencart#3921]
Forgive me if this has been noted before. I'm getting an error when trying to edit a define page. 
File does not exist: includes/css/define_pages_editor.css

My installation does not include that file and I don't see it in that location here on github.

**Comment by scottcwilson** [comment]
This is a change you have made.  No reference is made to that file in a default installation.

**Comment by wiztechinc** [comment]
I have made no changes whatsoever. This is cpanel git retrieved version updated today.  Guess I'll pull all files manually again.

**Comment by wiztechinc** [comment]
sigh, okay, all better now. Thanks.

**Comment by scottcwilson** [comment]
Could have bene some old stuff.  If you're working on 1.5.8 you really want to be updating every time you look at the project - it's changing constantly.

**Comment by wiztechinc** [comment]
I do constantly update in cpanel but git just doesn't seem to work that well. Very frustrating for a live site.
