### ISSUE TITLE
AJAX actions potentially not firing during a standard install with internal settings for all https

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#3926]
Something of what might be an unusual condition; however, has the potential to effect ZC users that do not take additional action to prevent.

So I have a (demo) site, where `includes/configure.php` identifies `HTTP_SERVER` and `HTTPS_SERVER` each to begin with https: and `ENABLE_SSL` is defined as `'true'`.  I have *no* root .htaccess file to force redirect to https: and/or www. or non-www., just a plain old install... Now I add some amount of ajax code (perhaps even consider using/accessing whatever is built in) where ajax.php is called from the page's generated `<base href>` tag which in this case (default ZC responsive_classic template file) uses the above HTTP_SERVER/HTTPS_SERVER based on `$request_type`.

Now, using http: one navigates directly to the page that is to load the ajax (which does not perform any type of redirect based on being accessed by http:)... I've tried google chrome, microsoft edge, microsoft internet explorer and the browser on my mobile device and in each of those action expected does not "occur". For example in Microsoft Edge the console identifies this:
````
Access to XMLHttpRequest at 'https://domain/ajax.php?act=ajax_action&method=ajax_class_method' from origin 'http://domain' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```` 

Note the difference between the beginning of each of those addresses.

If instead the page is accessed (directly or by navigation) with https in all of the same above conditions then the expected action(s) take place...

So... What is the best way forwards as ZC begins/continues to incorporate ajax type files/operations into the base code?

I actually came across this by complete accident though was confused about why I wasn't seeing changes occur on pages which seemed to be otherwise ok and I kept getting console errors that didn't seem to make sense.  I mean, it doesn't seem like the built in use of `$request_type` truly helps in that situation because both `XXX_SERVER` defines begin with https:. It's hard to say that the store was "incorrectly" setup considering it is a default store where https happens to be accessible.

Discussion?

**Comment by drbyte** [comment]
Your post is long, and contains lots of data. That's good. But I'm not sure I get your point.
You seem to be suggesting that maybe there's a bug, but then you ask "what's the best way forwards", which seems to imply that you don't think there's a bug but rather it's expected behavior.

Or are suggesting there's a problem when using `$request_type` for building URLs for ajax requests?

You quoted a browser error, but didn't give examples of page URLs generated or the actual JS showing the URL that the ajax call was supposed to go to according to the HTML in the page, so it's unclear whether you're saying that Zen Cart and the generated HTML were correct but the browser just decided to do something different, or whether some html/js was generated wrong.

Factors to keep in mind with browsers:
- HSTS is becoming more and more common, highly encouraged
- Browsers remember (beyond just the "cache") whether you've accessed a domain over https and like to take you back to https, even against your will. Helpful to test in a browser that's never visited that domain before .... ever. Regardless of incognito/private-browsing.

**Comment by mc12345678** [comment]
First, apologies for any confusion inadvertently generated by the OP; however, some of it also is inherent to the issue.

I also think that the title may be a little misleading, but lets discuss further and get the title possibly revised to suit. 

The result of the condition causing the problem is that output of the Ajax call is not presented to the browser for operation. I am not sure where in the process it is "rejected", though understanding of that may lead to a proper solution.  E.g. perhaps it is a jQuery evaluation, perhaps a browser evaluation. The content of the rejection text provided to the console is not generated by ZC software. 

What I see is this:
- The browser has a web address which was initially entered as `http:` and because the content page doesn't "require" `https:` and there is no formulated root `.htaccess` there was no redirect to `https:`. As a result, while on the page, the browser shows `http:`; however, all links generated through ZC are `https:` (primarily because of the use of `zen_href_link`).
- Because both `HTTP_SERVER` and `HTTPS_SERVER` begin with `https:`, it pretty much doesn't matter what `$request_type` returns as any link generated by `zen_href_link` or anything that uses either of those two constants would begin with `https`.
- Although the content associated with the ajax call(s) that I am using doesn't generally require encryption or any other protection offered by `https:`, I can see where other ajax calls may need the "protection" afforded by the use of `https:`.
- The html on the page has all of the indications that the communication will be secure:
````
<base href="https://...
var jsonDataArray = [
                            "key1" => "value1",
                            "key2" => "value2",
                            "key3" => "value3",
                           ];
        var option = { url : "ajax.php?act=action&method=method",
                       data : jsonDataArray,
                       timeout : 300
                     };

        zcJS.ajax(option).done(
            function (response,textStatus,jqXHR) {
                // perform on page action on response data;
            }
        ).fail( function(jqXHR,textStatus,errorThrown) {
            if (window.console) {
              if (typeof(console.log) == 'function') {
                console.log(errorThrown);
              }
            }
        });
````

**Comment by lat9** [comment]
> 
> 
> Something of what might be an unusual condition; however, has the potential to effect ZC users that do not take additional action to prevent.
> 
> So I have a (demo) site, where `includes/configure.php` identifies `HTTP_SERVER` and `HTTPS_SERVER` each to begin with https: and `ENABLE_SSL` is defined as `'true'`. I have _no_ root .htaccess file to force redirect to https: and/or [www](http://www). or non-www., just a plain old install... 

Should this simply be documented as a requirement?  That is, if the site's running https-all-the-time, either a root `.htaccess` file or some /extra_configures or /extra_datafiles element should enforce that 'rule'.

**Comment by drbyte** [comment]
Yes. If the site is going to use https for ANYTHING then nowadays it needs to use https for EVERYTHING.
Browsers are enforcing it more and more.

IMO this is a server-side issue, and not a Zen Cart software issue.

**Comment by lat9** [comment]
... although, the case is certainly worth documenting.

**Comment by scottcwilson** [comment]
I'll take a PR if someone would like to do it.  Running or Troubleshooting section perhaps.

**Comment by mc12345678** [comment]
To the above "list" may include installation and/or Securing website with SSL. Later may just need to indicate the potential issue(s) of not fully forcing https.

**Comment by drbyte** [comment]
The documentation site makes a strong case for SSL already.
