### ISSUE TITLE
adding inactive items to cart....

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#3937]
i do not have a v158 up and running as of yet.  i will get to that soon...

i have tested and confirmed this behavior on v157 relatively thoroughly.  using the test data, set `DISPLAY_CART` to false.  then take a product (i used a mouse, pid = 3), and make it inactive.  now use the following link (as recommended to me by Dr Byte in a post on the board):

https://zc157.com/index.php?main_page=product_info&action=buy_now&products_id=3

the page is not found, but the product is added to the cart, as well as a success message is displayed.

i am not a fan of allowing inactive items to be added to a cart, and then removing them only when you get to the shopping cart page.  it seems wrong.   i am curious about others thoughts on this issue.

screenshot below:

![image](https://user-images.githubusercontent.com/1095136/92294211-e1671100-eede-11ea-81a1-3bd25aff3bb4.png)

**Comment by lankeeyankee** [comment]
that is definitely unwanted behavior!

**Comment by scottcwilson** [comment]
Here be monsters.   You can also add more than the max qty, less than the min, quantities that don't match the specified units, etc.  This stuff is checked on the shopping cart page.  In some cases it's fixed, in some cases checkout is blocked.  I agree it's not ideal but when you start digging in, it's easy to see why they took this short cut.

**Comment by proseLA** [comment]
well, with all of the activity going on in the repo, perhaps it is something that we can look at and address.  if the logic is already embedded in the cart, then perhaps we need this script to access that same logic in an eloquent way.  without code duplication.  perhaps i will look at closer; time willing.

**Comment by proseLA** [comment]
> Here be monsters. You can also add more than the max qty, less than the min, quantities that don't match the specified units, etc. This stuff is checked on the shopping cart page. In some cases it's fixed, in some cases checkout is blocked. I agree it's not ideal but when you start digging in, it's easy to see why they took this short cut.

ok, i do have a v158 machine spun up and the behavior is the same/similar.

@scottcwilson i can not confirm anything that you are saying.  in fact, i can confirm the function does respect the max quantity.  so i'm not real sure about the rest of your statement.  

with respect to my initial comment about this issue, a check on the products status could easily prevent this situation.

```
$check_valid = zen_products_lookup($_GET['products_id'], 'products_status');
```

how we are getting into the `actionBuyNow` function without that, i am not real sure.  in addition, if one looks at the construction of the link; and then at the redirect, there seems to be a new issue, that we are in fact losing the products_id after after adding the inactive or active item to the cart.

**Comment by scottcwilson** [comment]
> @scottcwilson i can not confirm anything that you are saying. in fact, i can confirm the function does respect the max quantity. so i'm not real sure about the rest of your statement.

It lets you add the max and then corrects in the cart.   You know, like I said.

**Comment by proseLA** [comment]
> > how we are getting into the `actionBuyNow` function
> 
> https://github.com/zencart/zencart/blob/e1f7ce08fdd426f3a878ece848678ca54da36ac1/includes/main_cart_actions.php#L45-L50

https://zc157.com/index.php?main_page=product_info&action=buy_now&products_id=3

as stated in the original post.

**Comment by scottcwilson** [comment]
This is *in* the shopping cart class. My preference would be for it to not even reach that point - i.e. be stopped by JavaScript.   Because it gets to the cart there are a bunch of complicated checks that are replicated in multiple places.

**Comment by drbyte** [comment]
This min/max stuff seems to be off-topic from the original issue.

**Comment by drbyte** [comment]
@proseLA my point of posting that code snippet was just to answer your question of "how it gets to the cart's actionBuyNow() in the first place, without checks".

If you feel really strongly that adding your one-line fix is beneficial and has no way of negative side-effects, then submit a PR for it.

**Comment by proseLA** [comment]
no way of negative side effects is always tricky to know....

allow me to back up just a bit.  i have clients that send out emails.  on the email is a link to add the item into the cart, and then bring them to the shopping cart page.  back here, it was suggested to do it this way:

https://www.zen-cart.com/showthread.php?226939-trying-to-understand-SESSION_FORCE_COOKIE_USE&p=1370536#post1370536

if you feel that this is still the proper way to achieve that goal, i will give some thought and do a PR.

based on SEO conversations, i have recently changed clients sites to no longer do 404s on out of stock (and will not be coming back into stock) products.  so the product is now displayed but there is no add to cart button.  but ensuring that you can not add that product to a cart is important, as having messages on 1 page that says the product is added, and then going to the cart and the message says it is now no longer available can be rather confusing to the customer.

**Comment by drbyte** [comment]
> as having messages on 1 page that says the product is added, and then going to the cart and the message says it is now no longer available can be rather confusing to the customer.

Agreed.

**Comment by drbyte** [comment]
>  i have clients that send out emails. on the email is a link to add the item into the cart, and then bring them to the shopping cart page
> ...
> if you feel that this (`action=buy_now`) is still the proper way to achieve that goal

Yes, that's an ideal way to accomplish that outcome

**Comment by proseLA** [comment]
ok.  i'll do a PR.  thanks for the input.
