### ISSUE TITLE
unnecessary field in functions_products

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#3938]
https://github.com/zencart/zencart/blob/ac3be2402476ae89deea7bd4c8a70e96728376ef/includes/functions/functions_products.php#L24

i think `p.products_status` is included in `p.*` and therefore unnecessary in this bit of code.

**Comment by drbyte** [comment]
True. But already done. 
https://github.com/zencart/zencart/blob/v158/includes/functions/functions_products.php

**Comment by proseLA** [comment]
oops! sorry.
