### ISSUE TITLE
EZ-Pages UI fixes

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#3939]
Re: #3929  @Zen4All 

1. Numeric input boxes for sort-order and chapter are extremely wide, which makes their purpose a little confusing (people will think they should put a large value in there).

2. Tiny lang file error re: `TOC:'`

3. For the red/green toggle icons, the image-submits used to give a clue that something would happen with them because hovering over the icon would show the destination URL in the browser (if the browser had it enabled, ie to show in lower left corner), but now does not. This may be unavoidable with the new implementation. Curious whether that was intentional...?

<img width="1440" alt="Screen Shot 2020-09-05 at 8 13 41 PM" src="https://user-images.githubusercontent.com/404472/92315588-ad125400-efb5-11ea-8f9f-5b6e03fc70e8.png">

<img width="1243" alt="Screen Shot 2020-09-05 at 8 22 24 PM" src="https://user-images.githubusercontent.com/404472/92315586-a388ec00-efb5-11ea-8a4d-b1fcf54f8c77.png">

<img width="1440" alt="Screen Shot 2020-09-05 at 8 13 32 PM" src="https://user-images.githubusercontent.com/404472/92315597-ce734000-efb5-11ea-94aa-ecb110dd94aa.png">

**Comment by Zen4All** [comment]
1. Yes after looking at this a bit longer, I probably overdid this one a bit. I'll make them shorter.
2. will fix
3. Not intentional, but caused by moving from a link to a form with a submit button
