### ISSUE TITLE
zen_copy_products_attributes does not consider TABLE_PRODUCTS_ATTRIBUTES_DOWNLOAD

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3952]
This means copying a product with downloads does not work correctly - the downloadable file and its settings are not copied.

Bug in 1.5.7 (probably in 1.5.8 too - can't test because of #3941) 

Suspect bug is *not* new to 1.5.7 but existed in prior releases too.

**Comment by dbltoe** [comment]
Haven't gotten the final handle on it but, copying attributes with images to a product with an existing (diffferent) attribute (e.g. adding color to item already having size) fails as well.  1.5.7.
I'm going to research this more later but wanted to mention similar problem.

**Comment by scottcwilson** [comment]
Thanks - please write this issue up with repro steps at your earliest convenience.
