### ISSUE TITLE
Feature Request: max_execution_time (from the phpinfo core block) should be reported at the top of Server Info

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3957]
Like PHP Memory Limit and Upload Max Size, this is very useful to get at a glance.

**Comment by drbyte** [comment]
Worth noting that the Admin overrides the PHP default:
<img width="1258" alt="Admin Configuration My Store - Max Execution Time" src="https://user-images.githubusercontent.com/404472/93232790-4c6ae000-f748-11ea-9547-b3c462d03d0b.png">

**Comment by qdixon** [comment]
Just remember the user can not override the server limit to be higher, they can only lower the time with this

**Comment by scottcwilson** [comment]
That depends on the host, doesn't it? 
@drbyte Thanks for the reminder - I completely forgot about this!

**Comment by qdixon** [comment]
All PCI setups will have override with php.ini, override server max's disabled. Anyone allowing this is opening up a huge hole in server security. However, this same directive allows for limitation such as lowering max execution time from 60 to 30 lets say if you have a runaway script etc. But going the other way like from 60 to 300 will not work.

**Comment by torvista** [comment]
> But going the other way like from 60 to 300 will not work.
Expanding the switch comment to include this information would helpful, I think.
