### ISSUE TITLE
[158] language file intra-file reference technique required

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3960]
`admin/includes/languages/english/lang.products_to_categories.php` has a define `TEXT_INFO_PRODUCTS_TO_CATEGORIES_LINKER_INTRO`  which references `BUTTON_UPDATE_CATEGORY_LINKS` (also in the same file.  This doesn't work and creates a PHP notice.

**Comment by scottcwilson** [comment]
One obvious (if inelegant) solution would be simply to not do this, and repeat the text.  It's not that egregious because it would only be needed a handful of times.

**Comment by drbyte** [comment]
Agreed: repeating, or rewording in a way that doesn't require naming the button text again, would be ideal.
