### ISSUE TITLE
Page Parse Times plugin needed 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3970]
The page parse time display logic was removed from the core in 1.5.5 as part of the fix to #2686, but no replacement mechanism was created.

**Comment by scottcwilson** [comment]
https://github.com/CeonSupport is this something you would be willing to do?

**Comment by scottcwilson** [comment]
I'd like to get 

https://docs.zen-cart.com/user/performance/speed_up_site/#check-parse-times

update to point to this plugin.

**Comment by drbyte** [comment]
Or just remove that point from the documentation page, since it's currently not relevant.

**Comment by scottcwilson** [comment]
Can you explain why?  Not sure I grok.
