### ISSUE TITLE
jQuery load should be done before the load of javascript files

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#398]
Any jQuery based javascript will depend on jQuery already being there.

**Comment by DivaVocals** [comment]
:+1:

**Comment by jtwebsitedesign** [comment]
Agreed. However, due to jQuery version conflicts (which happen all too often), it's still nice to be flexible and load jQuery and Javascript files in any order necessary. I currently do that by renaming .js files so they auto-load in sequence, but not sure how others do it.

**Comment by bislewl** [comment]
Overall: :+1: 
1. From a CDN or locally?
2. Loading the migrate as well
3. I assume the minified version?

**Comment by drbyte** [comment]
Points well taken. 

site-wide review of javascript is in-progress
