### ISSUE TITLE
CATEGORIES_SPLIT_DISPLAY no longer included anywhere?

### ISSUE THREAD

**Issue by wiztechinc** [zencart/zencart#3985]
Forgive me if this issue has been raised before. 

Documents General are supposed to split out to the document categories box but I'll be danged if I can make the documents categories actually appear in the categories menu with the others.  I know this used to work this way - didn't it? When I did a search for the configuration setting, I got no results for that configuration key in the files. Doing a search back as far as 1.5.4, I can't find it there either. Am I missing something?

**Comment by drbyte** [comment]
I don't know about that constant.

But the categories sidebox excludes `product_type = 3` in
https://github.com/zencart/zencart/blob/563ffd4b06769ee4379c6812a15f957cbf475896/includes/templates/responsive_classic/sideboxes/tpl_categories.php#L31

via:
```php
zen_get_product_types_to_category($box_categories_array[$i]['path']) == 3
```

**Comment by scottcwilson** [comment]
I see no reference to the constant CATEGORIES_SPLIT_DISPLAY in any core file checking back to 1.2.7.

**Comment by wiztechinc** [comment]
Then that config setting is useless? I did find the if statement in the categories box  that I gather simply disallows the docs. Am I correct?

**Comment by wiztechinc** [comment]
I have had clients who also used the css categories box which does not disallow them so I hadn't noticed this before. Since there is a configuration setting, some code that made that work would be great. My first stab at it did not work.

**Comment by drbyte** [comment]
> Then that config setting is useless?

If you're referring to the mystical `CATEGORIES_SPLIT_DISPLAY` that you started with, then it seems yes it's useless in terms of Zen Cart core code. I've no idea where it came from. Probably someone's mod?

**Comment by wiztechinc** [comment]
Well, maybe, but that config key was incorporated into core long ago.  It's in layout settings for split category box.

**Comment by wiztechinc** [comment]
Split Categories Box
Key: CATEGORIES_SPLIT_DISPLAY
Path: Configuration > Layout Settings
Description: Split the categories box display by product type

**Comment by scottcwilson** [comment]
@drbyte Do you want a PR to remove this item from the DB?

**Comment by drbyte** [comment]
> @drbyte Do you want a PR to remove this item from the DB?

> I see no reference to the constant CATEGORIES_SPLIT_DISPLAY in any core file checking back to 1.2.7.

Looks like both of us found incomplete results in our searches.

It was added to the database in v1.2.0.

It was also never used in PHP code.

**Comment by scottcwilson** [comment]
Agreed.  I should have been more explicit in my statement.  It's in the DB but not used in code.

Would you like to proceed with removal?

**Comment by drbyte** [comment]
People always complain when something gets removed.  Suddenly we discover who's actually using something that's never been officially supported. Remember the recent DATE constants?

In what ways are people actually using it? Have people wired it into custom sidebox code? Plugins?

**Comment by scottcwilson** [comment]
> Plugins?

Checked my archive and nada.  No uses.

**Comment by drbyte** [comment]
> Would you like to proceed with removal?

Alright.

Reasons:
- wiring it up to "do something" isn't in any demand
- it probably doesn't suit a true/false switch anyway (it would be better to offer a selection of product-types, or other criteria)
- it's more efficient and specific to just let the individual sideboxes control their own rules for what they want to display, directly in PHP code, and not with brittle config switches.

**Comment by scottcwilson** [comment]
PR #3989 submitted.
