### ISSUE TITLE
Printing orders no longer compact since 1.5.6 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3990]
Switching to Bootstrap causes problems for order printing (which is a way some storeowners handle orders).  
The addresses are stacked, which means much more paper is used. 

Old print output (1.5.5): 
![image](https://user-images.githubusercontent.com/4391638/94750435-09b62400-0354-11eb-81e0-905dbbca7973.png)

New print output (1.5.6-1.5.8): 
![image](https://user-images.githubusercontent.com/4391638/94750517-38cc9580-0354-11eb-9234-14be0c0745e1.png)

I need to fix this for a client running 1.5.7 so for the short term I'm going to use Donnie Ray Jones's fix, documented here: 
https://blog.donnierayjones.com/2014/10/fix-bootstrap3-printing/

Not sure if there is appetite for a PR or perhaps some smart dude like @Zen4All can fix this.

**Comment by scottcwilson** [comment]
I'm going to go ahead and fix the other printing issues unrelated to address stacking in PR #3991.  Then we can decide what to do about the addresses.

**Comment by scottcwilson** [comment]
Platform related ?  I am Chrome/Mac.

**Comment by drbyte** [comment]
That one I screenshotted was Safari/Mac.

With other apps I've found that sometimes the printing "detection" in Bootstrap is based on the "screen window size" at the point of clicking Print, and thus occasionally grabs too-small mode. But I've not seen addresses stacked in Zen Cart before your post.

**Comment by drbyte** [comment]
> I will work on repro steps. I _was_ using a small window because the customer was using a small laptop, so I wanted to get as close to possible. Can you try shrinking your window and see if it happens then?

I did take it down to half-width of screen (from 1400 down to 700px) and it was fine there still.

**Comment by scottcwilson** [comment]
Oh, and I think the use of Chrome is a critical factor in repro as well.

**Comment by drbyte** [comment]
v156 has been in the wild for 12-18 months now. Has anyone else reported this same problem?

**Comment by scottcwilson** [comment]
Most people don't print the order details screen, so not sure how many would report it.

**Comment by scottcwilson** [comment]
Safari looks good, Chrome and Brave have this problem.  I had to fiddle with Firefox to make it preview, but when I did, I got stacking there too.  All on MacOS.

**Comment by scottcwilson** [comment]
This might not be worth fixing in the core - considering closing with a documentation note on how to fix for those who need this.

**Comment by scottcwilson** [comment]
Let's close for now unless there are more complaints, which might be best addressed by documentation and/or a plugin.
