### ISSUE TITLE
Remove unused values from DB if appropriate

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3992]
Follow on to #3989 - investigate use of 

- [x] CC_CVV_MIN_LENGTH
- [x] CUSTOMERS_AUTHORIZATION_PRICES_OFF
- [x] EMAIL_FRIENDLY_ERRORS
- [x] EMAIL_LINEFEED
- [x] MAX_ROW_LISTS_ATTRIBUTES_CONTROLLER

and remove if appropriate.

Please assign to me.

**Comment by drbyte** [comment]
`MAX_ROW_LISTS_ATTRIBUTES_CONTROLLER`
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, val_function, configuration_description, configuration_group_id, sort_order, date_added) VALUES ('Products Attributes - Attributes Controller Display', 'MAX_ROW_LISTS_ATTRIBUTES_CONTROLLER', '30', '{"error":"TEXT_MAX_ADMIN_ROW_LISTS_ATTRIBUTES_CONTROLLER_LENGTH","id":"FILTER_VALIDATE_INT","options":{"options":{"min_range":0}}}', 'Maximum number of attributes to display in the Attributes Controller page', '3', '25', now());

Was it intended to be a paginator control? Are we using a different constant for that instead? Is this one needed? Would it improve things? or is it fine to use whatever other is currently in place?  (I'm inclined to feel that "less is more" when it comes to all these max-per-page control switches. We don't need dozens of them when most pages are fine with one shared value.)

**Comment by drbyte** [comment]
`CUSTOMERS_AUTHORIZATION_PRICES_OFF`
This appears to be a duplication of stuff already implemented as `CUSTOMERS_APPROVAL_AUTHORIZATION`:
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) VALUES ('Customer Approval Status - Authorization Pending', 'CUSTOMERS_APPROVAL_AUTHORIZATION', '0', 'Customer must be Authorized to shop<br />0= Not required<br />1= Must be Authorized to Browse<br />2= May browse but no prices unless Authorized<br />3= Customer May Browse and May see Prices but Must be Authorized to Buy<br /><br />It is recommended that Option 2 or 3 be used for the purposes of Spiders', '5', '65', 'zen_cfg_select_option(array(\'0\', \'1\', \'2\', \'3\'), ', now());

So, yes, I think it's safe to remove this one.

**Comment by scottcwilson** [comment]
No references to CUSTOMERS_AUTHORIZATION_PRICES_OFF in PHP code back to 1.2.7.  Removing.

**Comment by drbyte** [comment]
Does anything in the plugins archive use the remaining ones? In .sql or .php ?

I'm slightly more curious about payment modules that would break.

Also interested in knowing how the other one was used in core, if ever.

**Comment by scottcwilson** [comment]
MAX_ROW_LISTS_ATTRIBUTES_CONTROLLER is used in dual pricing and a Twitch mod.  (They check for it being set and default it otherwise.) It was last used in the core in 1.5.6, removed in 1.57. 

CC_CVV_MIN_LENGTH last used in the core in 1.3.8.  Used in some language packs and old versions of Cybersource and Maxmind. Most recent use looks like 2015, others from 2011.

**Comment by drbyte** [comment]
> MAX_ROW_LISTS_ATTRIBUTES_CONTROLLER is used in dual pricing and a Twitch mod. (They check for it being set and default it otherwise.) It was last used in the core in 1.5.6, removed in 1.57.

v156:
https://github.com/zencart/zencart/blob/e60c81b6dbac7b1a61fb891397fe20de7b02c623/admin/attributes_controller.php#L1101-L1125

Looks like in v157 it was replaced with split_page_results paginator:
https://github.com/zencart/zencart/blob/ace282f116e7d46467f43c97e45f5905e3c94440/admin/attributes_controller.php#L1063-L1071

I'm guessing those other mods are merely touching the same file to add other updates, and not actually using the constant in new code. (And, since as you say they check for its presence and handle its absence, so it's not a big deal. In fact the original ZC code for it does the same.)

**Comment by drbyte** [comment]
> CC_CVV_MIN_LENGTH last used in the core in 1.3.8. Used in some language packs and old versions of Cybersource and Maxmind. Most recent use looks like 2015, others from 2011.

In those mods the constant is only used in relation to the no-longer-used basic cc module. 

It can be removed.
