### ISSUE TITLE
Update icon should not show on shopping cart on items with fixed quantity 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4006]
<img width="207" alt="Screen Shot 2020-10-06 at 3 12 01 PM" src="https://user-images.githubusercontent.com/4391638/95249276-6d25d300-07e6-11eb-92c4-8580f022b94a.png">

If the quantity is not updatable, the update icon shouldn't show on that row.

**Comment by mc12345678** [comment]
Is it to be removed at the bottom of the page with the same consideration? If nothing in the cart is "updatable" that it not be possible to select update which effectively is like a page reload? 

Note that it is possible that the quantity can be increased/modified in the cart through a condition where a product has a minimum quantity, is set to buy now (no quantity box shown) and I think one other factor set, but basically the minimum quantity is not met until the product has been added to the cart from basically the product page that many times... Doesn't really have bearing on the recycle/update button though.

**Comment by scottcwilson** [comment]
> Is it to be removed at the bottom of the page with the same consideration?  

I would say no on that - you might want the screen to be repainted for some reason.

**Comment by drbyte** [comment]
> If the quantity is not updatable, the update icon shouldn't show on that row.

Probably it should still display (for consistency reasons, as well as layout/alignment reasons), but with the `disabled` attribute applied so that it is greyed-out and therefore visually intuitive.

**Comment by scottcwilson** [comment]
disabled="disabled" doesn't work for images.   Had to use opacity.

**Comment by drbyte** [comment]
> disabled="disabled" doesn't work for images. Had to use opacity.

So it's actually still a fully functioning clickable button?

**Comment by scottcwilson** [comment]
I was so focused on the appearance that I didn't think about that - thanks for catching.  Fixed.
