### ISSUE TITLE
PRODUCTS_PRICE_IS_CALL_IMAGE_ON creates duplicate messaging 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4019]
Right now for call for price, we have a text link to the contact us page, and above that the image or text "product is call for price."  Why don't we just use zen_image_button with the call for price image for non CSS button users, and just the text "Call for Price" for CSS buttons users. 

This is how the listing screen currently appears with PRODUCTS_PRICE_IS_CALL_IMAGE_ON set to 0, then 1. 

<img width="297" alt="call_image" src="https://user-images.githubusercontent.com/4391638/95655831-0f400680-0ad8-11eb-81ff-0f35939c1931.png">
<img width="233" alt="call_text" src="https://user-images.githubusercontent.com/4391638/95655833-0fd89d00-0ad8-11eb-9668-6a65a5eed3ff.png">

**Comment by scottcwilson** [comment]
@brittainmark I'm not positive I feel strongly enough about this to make a change.   People who don't like the current layout can tweaks their templates to taste.  Thoughts?

**Comment by drbyte** [comment]
Wasn't there a PR merged that took care of this?

**Comment by scottcwilson** [comment]
No - it was a call for price change but different.  Both listing and product info still have the messaging duplicated.  See product 40.

<img width="477" alt="listing" src="https://github.com/zencart/zencart/assets/4391638/acdccd48-ab73-4e4c-a0cc-4a1f22aaa1be">

<img width="583" alt="product_info" src="https://github.com/zencart/zencart/assets/4391638/72b0b439-eb8b-4af3-8e4b-56de8c531084">

**Comment by scottcwilson** [comment]
Fix could be as simple as changing the link anchor text for call for price but right now this looks confusing.

**Comment by drbyte** [comment]
The call-for-price image is rendered as part of the price:
https://github.com/zencart/zencart/blob/44699b39de92f4c18b3832c3b3800f1cffdf12ff/includes/functions/functions_prices.php#L406-L414

And the call-for-price button (which formerly linked to Contact-Us, but now links to Ask-A-Question) is rendered by `zen_get_buy_now_button()`:
https://github.com/zencart/zencart/blob/44699b39de92f4c18b3832c3b3800f1cffdf12ff/includes/functions/functions_general.php#L204-L206

**Comment by brittainmark** [comment]
As both sets of information are valid. 
I see the options as:
1) if it is call for price do not display the price
2) have a flag to disable call for price as the price
3) have a flag to not display call for price in buy now (this will mean that the link is not present)
4) Change the price to display the call for price link and disable the buy now button.
5) leave it as is and let people change the template themselves

My preference is option 1 followed by option 2.

What do you think?

**Comment by scottcwilson** [comment]
Call for Price is rendered as a CSS button if CSS buttons is on.  (That was the fix @drbyte mentioned.)

In the interest of getting ready for 2.0.0, let's close this item (at least for now) - it's very low priority.  Thanks for looking at it.
