### ISSUE TITLE
includes\modules\order_total\ot_group_pricing.php PHP warnings

### ISSUE THREAD

**Issue by lindasdd** [zencart/zencart#4022]
Per changes made by swguy on my cart, should this file have this for lines 17 and 18 due to PHP 7 error warning's?

$this->title = defined('MODULE_ORDER_TOTAL_GROUP_PRICING_TITLE') ? MODULE_ORDER_TOTAL_GROUP_PRICING_TITLE : null;
    if (null === $this->title) return false;
    $this->description = defined('MODULE_ORDER_TOTAL_GROUP_PRICING_DESCRIPTION') ? MODULE_ORDER_TOTAL_GROUP_PRICING_DESCRIPTION : null;
    if (null === $this->description) return false;

**Comment by scottcwilson** [comment]
Does the default code in the constructor not work for you?   Unchanged 1.5.7 has 

```
    $this->title = MODULE_ORDER_TOTAL_GROUP_PRICING_TITLE;
    $this->description = MODULE_ORDER_TOTAL_GROUP_PRICING_DESCRIPTION;
    $this->sort_order = defined('MODULE_ORDER_TOTAL_GROUP_PRICING_SORT_ORDER') ? MODULE_ORDER_TOTAL_GROUP_PRICING_SORT_ORDER : null;
    if (null === $this->sort_order) return false;
```

**Comment by lindasdd** [comment]
It does not. As you'll see below though, this isn't a clean install. I'm using one of your plugins. I don't think the plugin is the issue though, it is just happens to be the file calling ot_group_pricing.php in this instance.

On my cart I get the following warning log:

[12-Oct-2020 13:42:30 UTC] Request URI: /localhost/index.php?main_page=shopping_cart, IP address: ::1
#1  ot_group_pricing->__construct() called at [C:\Program Files\Ampps\www\localhost\includes\modules\YOUR_TEMPLATE\inc_gp.php:6]
#2  include_once(C:\Program Files\Ampps\www\localhost\includes\modules\YOUR_TEMPLATE\inc_gp.php) called at [C:\Program Files\Ampps\www\localhost\includes\templates\YOUR_TEMPLATE\templates\tpl_shopping_cart_default.php:177]
#3  require(C:\Program Files\Ampps\www\localhost\includes\templates\YOUR_TEMPLATE\templates\tpl_shopping_cart_default.php) called at [C:\Program Files\Ampps\www\localhost\includes\templates\YOUR_TEMPLATE\common\tpl_main_page.php:190]
#4  require(C:\Program Files\Ampps\www\localhost\includes\templates\YOUR_TEMPLATE\common\tpl_main_page.php) called at [C:\Program Files\Ampps\www\localhost\index.php:94]
--> PHP Warning: Use of undefined constant MODULE_ORDER_TOTAL_GROUP_PRICING_TITLE - assumed 'MODULE_ORDER_TOTAL_GROUP_PRICING_TITLE' (this will throw an Error in a future version of PHP) in C:\Program Files\Ampps\www\localhost\includes\modules\order_total\ot_group_pricing.php on line 17.

[12-Oct-2020 13:42:30 UTC] Request URI: /localhost/index.php?main_page=shopping_cart, IP address: ::1
#1  ot_group_pricing->__construct() called at [C:\Program Files\Ampps\www\localhost\includes\modules\YOUR_TEMPLATE\inc_gp.php:6]
#2  include_once(C:\Program Files\Ampps\www\localhost\includes\modules\YOUR_TEMPLATE\inc_gp.php) called at [C:\Program Files\Ampps\www\localhost\includes\templates\YOUR_TEMPLATE\templates\tpl_shopping_cart_default.php:177]
#3  require(C:\Program Files\Ampps\www\localhost\includes\templates\YOUR_TEMPLATE\templates\tpl_shopping_cart_default.php) called at [C:\Program Files\Ampps\www\localhost\includes\templates\YOUR_TEMPLATE\common\tpl_main_page.php:190]
#4  require(C:\Program Files\Ampps\www\localhost\includes\templates\YOUR_TEMPLATE\common\tpl_main_page.php) called at [C:\Program Files\Ampps\www\localhost\index.php:94]
--> PHP Warning: Use of undefined constant MODULE_ORDER_TOTAL_GROUP_PRICING_DESCRIPTION - assumed 'MODULE_ORDER_TOTAL_GROUP_PRICING_DESCRIPTION' (this will throw an Error in a future version of PHP) in C:\Program Files\Ampps\www\localhost\includes\modules\order_total\ot_group_pricing.php on line 18.

**Comment by scottcwilson** [comment]
Oh ok.  You must have an old copy of Discount Preview.  You just need to upgrade.  Get it here: 
https://www.thatsoftwareguy.com/store/index.php?main_page=product_info&cPath=1_4&products_id=1

If you bought within the past 2 years, you get a discount.

**Comment by drbyte** [comment]
> Per changes made by swguy on my cart, should this file have this for lines 17 and 18 due to PHP 7 error warning's?
> ```diff
>- $this->title = MODULE_ORDER_TOTAL_GROUP_PRICING_TITLE;
>+ $this->title = defined('MODULE_ORDER_TOTAL_GROUP_PRICING_TITLE') ? MODULE_ORDER_TOTAL_GROUP_PRICING_TITLE : null;
>+ if (null === $this->title) return false;
>- $this->description = MODULE_ORDER_TOTAL_GROUP_PRICING_DESCRIPTION;
>+ $this->description = defined('MODULE_ORDER_TOTAL_GROUP_PRICING_DESCRIPTION') ? MODULE_ORDER_TOTAL_GROUP_PRICING_DESCRIPTION : null;
>+ if (null === $this->description) return false;
> ```

Given that those constants are already defined in core code, my question is: why aren't they defined in your case?

**Comment by lindasdd** [comment]
In Core they are defined via includes\languages\english\modules\order_total\ot_group_pricing.php 

In this instance I am calling on them via a plugin that is firing on the Shopping Cart page which means the order_total defines haven't been called on yet.

I fixed it by adding the necessary defines to the extra_definitions language file that handles the rest of the needed defines for this plugin and left includes\modules\order_total\ot_group_pricing.php in its original form.

**Comment by drbyte** [comment]
> In Core they are defined via includes\languages\english\modules\order_total\ot_group_pricing.php

Correct. No change required there.

> In this instance I am calling on them via a plugin that is firing on the Shopping Cart page which means the order_total defines haven't been called on yet.

That's a problem with your plugin IMO.

If your plugin is loading the ot modules then it should also be loading the necessary language files. 
An old version of `inc_gp.php` that I have indeed already loads the language files before calling the actual ot modules.

So, as `swguy` already mentioned perhaps there are some plugin upgrades you need to apply both to support the stricter newer PHP version requirements as well as benefit from bugfixes/improvements made to the plugin.

> I fixed it by adding the necessary defines to the extra_definitions language file that handles the rest of the needed defines for this plugin and left includes\modules\order_total\ot_group_pricing.php in its original form.

That feels like the wrong "fix". Duplicating defines creates other problems down the chain.
