### ISSUE TITLE
Product date available should be for stock < 1?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4024]
I don't think it makes sense to show a date for when it's available, if it is already available!

I added a clause here
`  if ($products_date_available > date('Y-m-d H:i:s')) {`

to
`if ($products_date_available > date('Y-m-d H:i:s') && zen_get_products_stock((int)$_GET['products_id']) < 1)`

**Comment by proseLA** [comment]
- in the future, can you please reference a permalink from the code base so that some of us do not have to burn time searching for where you are?
- have we not done enough fiddling around with `products_date_available` to leave it alone for a release or two?
- the idea that because an item has stock available makes it available is not a universal idea for business practices associated with all ZC store owners.
- every time i see this field mentioned, i cringe.  the logic and its use throughout ZC gets confusing and each release causes me grief; despite well intentioned efforts by the community.

**Comment by torvista** [comment]
> in the future, can you please reference a permalink from the code base so that some of us do not have to burn time searching for where you are?

Normally I would, I assumed anyone here has an IDE that would find that instantly, as it is unique to one file.

> have we not done enough fiddling around with products_date_available to leave it alone for a release or two?

No idea about that.

> the idea that because an item has stock available makes it available is not a universal idea for business practices associated with all ZC store owners.

Really? Well, hence the ? in the title. Always open to learn how others work.

**Comment by scottcwilson** [comment]
> > in the future, can you please reference a permalink from the code base so that some of us do not have to burn time searching for where you are?
> 
> Normally I would, I assumed anyone here has an IDE that would find that instantly, as it is unique to one file.

It really is a good practice to explain your context - remember, you have been looking at this issue for a while, but everyone else is starting from scratch.  Also, these issues sometimes come up months or even years later, and it's good to have full details to make them easier to understand.

**Comment by proseLA** [comment]
> > in the future, can you please reference a permalink from the code base so that some of us do not have to burn time searching for where you are?
> 
> Normally I would, I assumed anyone here has an IDE that would find that instantly, as it is unique to one file.

i think you spend far more time configuring your IDE than i do.  i love my IDE, but configuring it to work the way i would like is a full time job.  that said, it is hardly unique to 1 file:

`prose@charmes:~/vBoxes/zcart/base157$ grepp -l \$products_date_available.\>.date 
includes/templates/template_default/templates/tpl_product_free_shipping_info_display.php
includes/templates/template_default/templates/tpl_document_general_info_display.php
includes/templates/template_default/templates/tpl_document_product_info_display.php
includes/templates/template_default/templates/tpl_product_music_info_display.php
includes/templates/template_default/templates/tpl_product_info_display.php
includes/templates/responsive_classic/templates/tpl_product_free_shipping_info_display.php
includes/templates/responsive_classic/templates/tpl_document_general_info_display.php
includes/templates/responsive_classic/templates/tpl_document_product_info_display.php
includes/templates/responsive_classic/templates/tpl_product_music_info_display.php
includes/templates/responsive_classic/templates/tpl_product_info_display.php
`

> 
> > have we not done enough fiddling around with products_date_available to leave it alone for a release or two?
> 
> No idea about that.

i find it advantageous to keep a little bit on top of the comings and goings.  these are all reasonably new.

https://github.com/zencart/zencart/blob/f56ccabab78809bd7bfdb56d2d2a1c6f31dd2b3c/includes/functions/functions_products.php#L103-L128
> 
> > the idea that because an item has stock available makes it available is not a universal idea for business practices associated with all ZC store owners.
> 
> Really? Well, hence the ? in the title. Always open to learn how others work.

i have a customer who sets up items ahead of time.  they are active, with a date available in the future.  in his implementation of ZC, those items will NOT appear and you can hopefully not add them to the cart.  even though the stock is > 0.  he has purchased the items and now is just waiting on delivery.  once they are delivered, he will either remove the date or if the date is in the past, the items are now available to view and purchase.

that's how he operates.

i could potentially make some of these new functions work; but as has been discussed ad nauseum in the past, without a products class, everything (at least to me) gets rather confusing and convoluted.  

furthermore the idea that you are requesting to now apply zc functions to a template, well, i just do not think it is good design.  ideally, templates are for the displaying of data.

these are just my opinions; do with them as you see fit.
