### ISSUE TITLE
[158] EZ-Pages footer configuration not working 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4033]
Look at this screenshot of Admin.  Question: is the Action DVDs link displayed in the Footer? 

<img width="915" alt="config_ezpages" src="https://user-images.githubusercontent.com/4391638/96386020-bcb0bb00-1165-11eb-8a64-e0615a094f9f.png">

In 1.5.8, it is!  ~~Because the sort order is > 0.~~ Because the admin/ezpages.php tool is buggy.   This is *quite confusing*.  Why don't we just use the sort order (zero or non-zero) to configure the display of an EZPage in the header, footer or sidebox?

**Comment by drbyte** [comment]
> Why don't we just use the sort order (zero or non-zero) to configure the display of an EZPage in the header, footer or sidebox?

Back in original design people requested the ability to set the sort order independently of whether its status was on/off.

**Comment by scottcwilson** [comment]
If we want to maintain this, fine - but shouldn't the behavior of the template be to *not* show the EZ-Page in this configuration?

**Comment by drbyte** [comment]
Should there be less confusion?  Probably.

Thanks for pointing it out.

I don't recall whether it (this footer status discrepancy you mention) has always been this way, vs when it "changed", let alone "why".

**Comment by scottcwilson** [comment]
These are 1.5.8 issues only; 1.5.7 works great.

**Comment by scottcwilson** [comment]
Retitling to reflect the root cause of the problem, which is fixed in my PR.
