### ISSUE TITLE
responsive_mobile.css has a lot of duplication

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4040]
Looks like entire blocks are duplicated.  See for example the two blocks starting with the comments "account page" and "bof account pages".

**Comment by dbltoe** [comment]
That's the design.  One is for portrait (bof account pages after 216) and the other (account page after 12) for landscape.
See lines 12 and 216.

**Comment by scottcwilson** [comment]
Sure enough!

**Comment by dbltoe** [comment]
There is an error on line 89.  #download should be #downloads

**Comment by scottcwilson** [comment]
You want to fix that, and then add a comment at the top explaining the duplication?

**Comment by dbltoe** [comment]
Hesitant to stop at line 89 and I think there are several more.
Do you feel the clarification is important enough to not wait?

**Comment by scottcwilson** [comment]
Fix what you have when you have it rather than waiting for perfection, which never comes.
