### ISSUE TITLE
Preparing release of v157a

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#4043]
Target date: Oct 29, 2020

Seeking a list of critical bugs that need to be fixed for inclusion.

**Comment by scottcwilson** [comment]
AFAIK it's ready.

**Comment by mc12345678** [comment]
zen_draw_products_pull_down_categories_attributes is still not properly addressed...

Legacy code that doesn't implement the 5th parameter (not expected to do so) will not execute the "default" code below:
````php
        default: //legacy: show all categories with products with attributes
            $categories = $db->Execute("SELECT DISTINCT c.categories_id, cd.categories_name " .
                " FROM " . TABLE_CATEGORIES . " c, " .
                TABLE_CATEGORIES_DESCRIPTION . " cd, " .
                TABLE_PRODUCTS_TO_CATEGORIES . " ptoc, " .
                TABLE_PRODUCTS_ATTRIBUTES . " pa " . " 
                WHERE pa.products_id= ptoc.products_id 
                AND ptoc.categories_id= c.categories_id 
                AND c.categories_id = cd.categories_id 
                AND cd.language_id = " . (int)$_SESSION['languages_id'] . " 
                ORDER BY categories_name");
            break;
  ````

I thought there had been some progress made on it, but looks like the issue (#3895) has stalled?

**Comment by drbyte** [comment]
> I thought there had been some progress made on it, but looks like the issue (#3895) has stalled?

It does appear to have stalled.

**Comment by drbyte** [comment]
Released. https://github.com/zencart/zencart/releases/tag/v1.5.7a
