### ISSUE TITLE
Setting admin switches/defaults based on user?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4044]
There are admin switches "hidden" in gid= 6.

No default suits everyone, as illustrated here:
https://www.zen-cart.com/showthread.php?227331-Product-Master-Category-Bug&p=1374130#post1374130

Where possible, would it not be good design to set a hidden switch/default based on user choice?
a) to remove existing switches from view/simplify the GUI.
b) avoid people looking for a switch, and if it does not exist, asking how to modify it.

So in the above case, the defaults would change to whatever the user selects.
??

**Comment by drbyte** [comment]
> No default suits everyone, as illustrated here:
> https://www.zen-cart.com/showthread.php?227331-Product-Master-Category-Bug&p=1374130#post1374130

That's not even a switch. Just a hard-coded default.

**Comment by drbyte** [comment]
> Where possible, would it not be good design to set a hidden switch/default based on user choice?
> a) to remove existing switches from view/simplify the GUI.

If the switches are removed so the GUI is simplified ... how does the user "select" or "set" their desired default?

**Comment by drbyte** [comment]
Or are you proposing that each Admin user's "last-used choice" for every radio-button, checkbox, dropdown, on every page, be remembered so that the next time they come to that same screen their last-used choice is re-selected? 

What if they only wanted "that" choice "that one time"?

Interesting discussion. Raises all kinds of questions that would need to be considered before attempting to implement.

What if the storeowner wanted to reset the defaults for everyone? Overriding everyone's previously-used (or even "saved") preferences?

**Comment by torvista** [comment]
> Or are you proposing that each Admin user's "last-used choice" for every radio-button, checkbox, dropdown, on every page, be remembered so that the next time they come to that same screen their last-used choice is re-selected?
Yes: last choice is remembered.

And no not every one, just ones where there is a doubt as to what to use as a default
&&  when someone suggests an admin switch to deal with it
&& you say no.

And not to change things, just an idea to possibly use as people modify/add new code.

**Comment by mc12345678** [comment]
This is something I tried to bring up in one of the other multitude of discussion threads, might such a "feature" include some sort of "save as default button" on the page(s) where implemented? This way the "one off" issue can be addressed perhaps even a restore or reset default? Ie. back to the "core" (super admin controlled and/or just as shipped) defaults that the user from there can diverge and from there return? (popup like menu option upon hover or some such "symbology" with assistive text?)

Think that "last used choice" (session based) might be something for current login with additional "long-term" option (database most likely).

Unfortunately also thinking/considering the need for some sort of "security" control? User able/not able to adjust their default(s) of particular (name object whether screen, page, configuration, etc...)?

**Comment by torvista** [comment]
While a "full" implementation would be all selections stored in each personal profile and a master reset, I really was not thinking that is necessary...who is asking for that?

I was only suggesting that the idea of using hidden, user-changed defaults-based-on-use may be a good idea to improve the GUI/user experience with little overhead when I think the vast majority of shops are single users?

**Comment by scottcwilson** [comment]
Most shops would not need per user defaults.  Also, there is very little demand for a feature like this.
If someone wants needs it, it should be built as a plugin, not added to the core.
