### ISSUE TITLE
[157a] Seeing console logs on login page

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4045]
Just refreshed a local copy with the current 157 branch.  When I click on the "Login" button, I'm seeing the following in the FireFox console log:
![image](https://user-images.githubusercontent.com/2685585/97196018-5ab60e00-1782-11eb-94e8-58514849c4f4.png)

**Comment by drbyte** [comment]
@lat9 That was a server issue. Should be resolved now.

**Comment by lat9** [comment]
All better this morning, thanks.
