### ISSUE TITLE
Should we have zc_install attempt to make writable dirs where needed?

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#405]
The zc_install inspection process currently only "reports" whether necessary folders are writable, and doesn't actually attempt to make the necessary changes.

Granted, it can't make any changes if permissions won't allow, but in cases where the server does allow it, we should make the necessary changes automatically.

**Comment by scottcwilson** [comment]
Agreed!  And put up a super-obvious error if not allowed but permissions not satisfactory.

**Comment by scottcwilson** [comment]
Hmmm... just started getting an redirect loop on admin in 1.6.0 with a fresh install - I wonder if it's caused by an issue like this.

**Comment by drbyte** [comment]
> Agreed! And put up a super-obvious error if not allowed but permissions not satisfactory.

Well, zc_install does flag up relevant errors if the folders aren't writable. 

It just doesn't attempt to change them.
