### ISSUE TITLE
configuration settings update for Report All Errors plugin now in core

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#4053]
https://github.com/zencart/zencart/blob/1b70055491a1d41427d64b79db518917c46912d0/admin/includes/init_includes/init_report_all_errors_admin.php#L12-L17

should the config vars in this script be inserted as part of the sql ZC version upgrade process as opposed to being in the `init_includes` directory?

some of us that have used this plugin since well before its merge into the core could (did) miss out on the `IgnoreDups` selection due to the simplicity of the test here.

**Comment by drbyte** [comment]
Seems sensible. 
I guess that would make the init file you quoted become very similar to the catalog-side file by the same name.

**Comment by proseLA** [comment]
> Seems sensible.
> I guess that would make the init file you quoted become very similar to the catalog-side file by the same name.

yes, that seems correct.

i can do a PR if you are so inclined.

**Comment by drbyte** [comment]
> i can do a PR if you are so inclined.

OK.

I guess the SQL would have to be split up: existing INSERT as INSERT IGNORE, followed (or preceded) by UPDATE WHERE for the description and function fields.

**Comment by proseLA** [comment]
> > i can do a PR if you are so inclined.
> 
> OK.
> 
> I guess the SQL would have to be split up: existing INSERT as INSERT IGNORE, followed (or preceded) by UPDATE WHERE for the description and function fields.

sounds good.  i'll put it on my list.  i think its low priority; but definitely worth doing.
