### ISSUE TITLE
PayPal long suburb issue

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4057]
Saw this in 1.5.6; looks like same issue is present in 1.5.7. 

[26-Oct-2020 18:24:42 UTC] Request URI: /site/ipn_main_handler.php?type=ec&token=EC-0ABCDEFG123456740&PayerID=ABCDEFGHIABCD, IP address: XX.XX.XX.XX
#1  trigger_error() called at [/home/account/public_html/store/includes/classes/db/mysql/query_factory.php:171]
#2  queryFactory->show_error() called at [/home/account/public_html/store/includes/classes/db/mysql/query_factory.php:143]
#3  queryFactory->set_error() called at [/home/account/public_html/store/includes/classes/db/mysql/query_factory.php:270]
#4  queryFactory->Execute() called at [/home/account/public_html/store/includes/classes/db/mysql/query_factory.php:423]
#5  queryFactory->perform() called at [/home/account/public_html/store/includes/modules/payment/paypalwpp.php:2648]
#6  paypalwpp->addAddressBookEntry() called at [/home/account/public_html/store/includes/modules/payment/paypalwpp.php:2055]
#7  paypalwpp->ec_step2_finish() called at [/home/account/public_html/store/includes/modules/payment/paypalwpp.php:1896]
#8  paypalwpp->ec_step2() called at [/home/account/public_html/store/ipn_main_handler.php:81]
--> PHP Fatal error: 1406:Data too long for column 'entry_suburb' at row 1 :: INSERT INTO address_book (entry_firstname, entry_lastname, entry_street_address, entry_postcode, entry_city, entry_country_id, entry_gender, entry_suburb, entry_zone_id, entry_state, customers_id) VALUES ('Michael', 'Jones', '12345 Big Basin Way', '95070', 'Saratoga', 223, '', 'Apartment below Some Random Business Name.', 12, '', 1164) ==> (as called by) /home/account/public_html/store/includes/modules/payment/paypalwpp.php on line 2648 <== in /home/account/public_html/store/includes/classes/db/mysql/query_factory.php on line 171.

**Comment by drbyte** [comment]
`Apartment below Some Random Business Name.` is 42 chars. (And appears to be coming from PayPal)
The `suburb` field is only 32 chars, in v157.

**Comment by scottcwilson** [comment]
Correct.  We have to trim the PayPal data when there's an address change.  (I sure do hate that this can even occur in the first place, but here we are.)

**Comment by drbyte** [comment]
IIRC PayPal accepts up to 100 chars for suburb. Not sure I like that, but from what I can tell they seem to like to allow "extra instructions" there.

**Comment by scottcwilson** [comment]
What I'm going to do here is includes/modules/payment/paypalwpp.php above line 2648

    $maxlen = zen_field_length(TABLE_ADDRESS_BOOK, 'entry_suburb');
    if (strlen($address_question_arr['suburb']) > $maxlen) {
       $address_question_arr['suburb'] = substr($address_question_arr['suburb'], 0, $maxlen); // cap at 100
    }

Happy to put this into a PR if desired.

**Comment by drbyte** [comment]
Trimming it with substr based on the db schema is fine.

I would suggest skipping the temporary variable and the `if` check. Both are redundant. Just inline the substr call.

I've committed this to v158: https://github.com/zencart/zencart/commit/d2c59ba27b8b22eb586869c0a62f782a474069af

**Comment by scottcwilson** [comment]
Great! Thank you.

**Comment by scottcwilson** [comment]
Closing via change noted above.
