### ISSUE TITLE
[157a] JS error in admin/orders.php

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4058]
It looks like we should not have pulled out the `init()` function when converting this file to use admin_html_head.php.  

![Screen Shot 2020-11-02 at 1 56 36 AM](https://user-images.githubusercontent.com/4391638/97838742-cf230c80-1cae-11eb-8e29-7574d97507b1.jpg)

**Comment by drbyte** [comment]
Probably should have removed the onload=init() from the `body` tag.

**Comment by drbyte** [comment]
I'm not seeing any other in-page errors as a result of this. 
So, while mildly unpleasant, it doesn't seem like there are any negative side-effects here.

Is it affecting specific plugins?

**Comment by scottcwilson** [comment]
I agree it's not critical; it's just a bug we should fix.
