### ISSUE TITLE
Deprecated warning in zones shipping module 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4059]
--> PHP Deprecated: strstr(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /store/includes/modules/shipping/zones.php on line 282.

**Comment by drbyte** [comment]
That should already be a string.

What are the steps to trigger this? I tried enabling the Zones module, setting US or 00 as the country for Zone 1, and going to checkout with a US address. No deprecations noted.
Tried checkout with a different country, and even tried changing the zones module country to CA and doing checkout with US address.

How to recreate it?

**Comment by scottcwilson** [comment]
I can't dup it either.  No idea.

**Comment by drbyte** [comment]
I think it would require the delivery address to have been invalid or blank.

I'd expect that a virtual order would skip calling for quotes at all.

**Comment by scottcwilson** [comment]
This is coming from the shipping estimator on the shopping cart page.  No idea on replicating, I am just going off the logs.

**Comment by drbyte** [comment]
I wonder if the supplementary comment "to use chr()" suggests that it was an integer value? 
Still, in base core code I don't understand why it would be a non-string value.

**Comment by drbyte** [comment]
I wonder if some other non-core-code was firing the shipping class's `quotes()` method to gather quotes, but didn't have a valid country set?

Feels like an edge case.
