### ISSUE TITLE
/template_default/templates/tpl_checkout_confirmation_default.php: space between ampersand and array

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4060]
I suspect this is not ok:
`<?php
  $class =& $_SESSION['payment'];
?>`

**Comment by drbyte** [comment]
Should be fine.

Is it causing a specific error?

**Comment by torvista** [comment]
no, just saw it while I was in merging hell and could not find any documentation to assume a space was ok. Previous file version had no space.
