### ISSUE TITLE
zen_draw_products_pull_down: output order and format for Admin

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4066]
Looking at products to categories, the category selection and the product selection...

I note the category selection uses admin\includes\modules\products_previous_next.php but subsequently the products dropdown uses function zen_draw_products_pull_down which is shared with the shopfront.

I was thinking how to modify/choose this on the page (tiny text-link "order by....") to allow choice of ordering and relevant format on the listing, for example.
eg
if sorted by id: "#123 - ProductName - ProductModel"
if sorted by name: "ProductName - ProductModel ( #123)"
if sorted by model: "ProductModel  - ProductName ( #123)"
etc. ad infinitum
I don't want to enter the "I don't use a model" argument now, just mooting the idea.

But, I've concluded that it is too convoluted to try and modify the shared function zen_draw_products_pull_down to serve both shopfront and admin as the users have different needs and so have used a new one for my purposes.

So suggestions to shape this into a PR with a new function, or what?

**Comment by drbyte** [comment]
> uses function zen_draw_products_pull_down which is shared with the shopfront.

Where is it used by the shopfront?

**Comment by torvista** [comment]
I had assumed since it was moved from Admin, it was being shared with shopfront or was planned to be.

**Comment by drbyte** [comment]
It appears as though it's been available in both admin and catalog for many releases.
But I see no use if it catalog-side.
In fact all of the pulldown functions are only used admin-side.

The functions were moved catalog-side so they could be as centralized as possible. The thinking wasn't primarily around "are they used in the admin vs catalog" but rather "these are category-related functions so they'll go into functions_categories.php ... and almost all of these functions files are stored catalog-side".

**Comment by drbyte** [comment]
Also note my proposal in #4083

**Comment by proseLA** [comment]
> It appears as though it's been available in both admin and catalog for many releases.
> But I see no use if it catalog-side.

i see no use on the catalog side as well.

**Comment by torvista** [comment]
Is a choice of format not of interest generally? Or am I the only one whose shop management revolves around SKUs/models?

**Comment by scottcwilson** [comment]
New class `includes/classes/productPulldown.php` should suffice.  If additional notifiers are required, please PR.
