### ISSUE TITLE
lack of consistent load of local/configure.php between zc_install and shop operations...

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#4068]
can we have a consistent application between install and run time?  during runtime, local/configure.php gets loaded first; then configure.php as seen here (operates the same on the catalog side):

https://github.com/zencart/zencart/blob/3d19adc47e8030fc02498a9bef707ea09afd8194/admin/includes/application_bootstrap.php#L45-L59

during a zc_install, we just clobber the configure.php with the local if it exists.  that's seen here:

https://github.com/zencart/zencart/blob/3d19adc47e8030fc02498a9bef707ea09afd8194/zc_install/includes/application_top.php#L58-L60

i think the zc_install should follow the way it is done during shop operations.

**Comment by drbyte** [comment]
There are technical reasons for the difference. 

But, more important...

I gather you were attempting to do  something that failed to produce an outcome you expected. 

Care to provide the actual circumstances that brought you to post this?

**Comment by proseLA** [comment]
> Care to provide the actual circumstances that brought you to post this?

no problem.

i have some defines in my local configure.php; mostly DEBUG defines that are in there.  nothing else.  when i go to update my database, the installer does not find the database, which i know is there and correctly configured.  so now i have to track down why.

perhaps if my memory was stronger, or i was ZC 24/7, and/or i was doing nothing but ZC updates, i would remember this.  but  alas, i am not.  so i have to dig.

in addition, i see people on the board that complain the installer is not giving them the option to update.  is it due to them having a local/configure.php file?  and the installer says nothing about that?

it just seems if you have a properly functioning site, the installer should give you the option to update the database or at least tell you why it can not.

ALERT: minor thread drift; i also discovered i had a field set to MEDIUMTEXT that the installer/updator was looking for as being TEXT.  which meant that the update option was always going back to a v155 to v156 update, despite the v156 updates already having been applied, and the db patch level being reported as v156c.  but alas, i digress...  apologies..

**Comment by torvista** [comment]
some possibly relevant background
https://github.com/zencart/zencart/issues/3159
https://github.com/zencart/zencart/issues/3244

**Comment by proseLA** [comment]
i've looked at the code, as well as reviewed the above mentioned 2 issues.  i have no good answers.  i dislike the idea that these 2 operations (install and running shop) treat these files differently.  i can see how people would use the 2 configure files differently in a running shop; as once out in the wild, people will do what people will do.  but not providing a message as to what is going on when doing an install?  and someone saying that is for "expert" use only?  so let's burn those peoples' time as they can figure it out on their own?  i am not a fan of that sentiment.

if we wanted to use both files (similar to how it is done in a running shop), i can see what a major refactor that is within the context on an install/upgrade.    did we have a message at one time warning about the local configure file?  does it exist now and somehow my browser or i missed it?  perhaps that's the easiest solution, as i'm sure come 158, i will have forgotten this whole discussion.  unfortunately.

**Comment by torvista** [comment]
>did we have a message at one time warning about the local configure file?
Don't know, but I vote for that. One soon gets used to ignoring constant things in the messagestack like " STRICT ERROR REPORTING IS ON" so another one is not a big problem.

As for "experts only"...I could not disagree more. Hammering home the message that "thou shalt not bugger about with your production shop: do it elsewhere/locally" is essential for novices.... and just as essential for experts, in my opinion. So the use of a local configure is something that everyone should be likely to come across.
I ignore it in Beyond Compare so there is never any danger of uploading it.

**Comment by proseLA** [comment]
> > did we have a message at one time warning about the local configure file?
> > Don't know, but I vote for that. One soon gets used to ignoring constant things in the messagestack like " STRICT ERROR REPORTING IS ON" so another one is not a big problem.
> 
> As for "experts only"...I could not disagree more. Hammering home the message that "thou shalt not bugger about with your production shop: do it elsewhere/locally" is essential for novices.... and just as essential for experts, in my opinion. So the use of a local configure is something that everyone should be likely to come across.
> I ignore it in Beyond Compare so there is never any danger of uploading it.

@torvista i really do not follow what you are saying; or its relevance to my post.

my issue is about the consistent loading of configure.php files.  nothing more.  in a running site; both files are loaded.  when running an install/update; the local file version clobbers the other one.  there is no consistency between those two.  because of the clobbering of the one configure.php file, when doing an install/update on a running site, the installer does not give an option to update; nor does it remind you of the local configure.php file which is why it can not do the update.

**Comment by drbyte** [comment]
> did we have a message at one time warning about the local configure file? 

Yes. Removed in https://github.com/zencart/zencart/issues/3244 because @torvista reported it to be confusing as it wasn't used.

**Comment by drbyte** [comment]
> i have some defines in my local configure.php; mostly DEBUG defines that are in there. nothing else. when i go to update my database, the installer does not find the database, which i know is there and correctly configured. so now i have to track down why.

It's important to note that zc_install NEVER actually executes the configure.php file.
It only parses it in order to read the defines that zc_install needs in order to operate.

You are correct that zc_install currently ignores the main configure.php if a local/configure.php is found. So, if your local/configure.php is being used for purposes other than to at least contain the defines normally expected in includes/configure.php then those will not be picked up.

**Comment by proseLA** [comment]
> > did we have a message at one time warning about the local configure file?
> 
> Yes. Removed in #3244 because @torvista reported it to be confusing as it wasn't used.

in re-looking at that issue, i do not think he was complaining about the message; he was complaining about the fact that you could not proceed any further.  

the message is informative; not being able to proceed as indicated by your comment that you could replicate the bug is, to me, a different issue that was resolved somehow by removing that message.

i will adjust my environment accordingly.  as well as pay closer attention to others contributions.

**Comment by drbyte** [comment]
I was looking into how easy it would be to merge the two files during zc_install, by loading and parsing both and picking the right override etc, but it feels like an overhaul I don't particularly want to tackle presently.

I use this `zc_install/includes/localConfig.php` feature instead of the `/includes/local/configure.php`:
https://github.com/zencart/zencart/blob/v157/zc_install/includes/localConfig.php#L17-L45

**Comment by proseLA** [comment]
> I was looking into how easy it would be to merge the two files during zc_install, by loading and parsing both and picking the right override etc, but it feels like an overhaul I don't particularly want to tackle presently.
> 
> I use this `zc_install/includes/localConfig.php` feature instead of the `/includes/local/configure.php`:
> https://github.com/zencart/zencart/blob/v157/zc_install/includes/localConfig.php#L17-L45

i appreciate you taking a look.  frankly, i do not blame you.  i did look as well:

> if we wanted to use both files (similar to how it is done in a running shop), i can see what a major refactor that is within the context on an install/upgrade.

thanks.
