### ISSUE TITLE
[156-158] orders::order_weight neither set on order creation nor included on order query

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4070]
The `orders::order_weight` field was added to the database for zc156 but has never been set during order-creation or gathered on an order query.

**Comment by scottcwilson** [comment]
Seems like this is fixed in 1.5.8 - $order->info['order_weight'] is set.  Is there any remaining work, or should this ticket be closed?

**Comment by lat9** [comment]
> 
> 
> Seems like this is fixed in 1.5.8 - $order->info['order_weight'] is set. Is there any remaining work, or should this ticket be closed?

... and starting with 1.5.7**b**.
