### ISSUE TITLE
[158] $languageLoader object: var_export does not handle circular references 

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4087]
Tracking down issue #4070 on zc158 (using the current version of [Super Globals](https://github.com/lat9/super_globals_plus)), I ran into a a recursion limit upon the output of the `$languageLoader` variable.

I created a teeny script to see what was up, placing it in the root of my local test site:
```php
require 'includes/application_top.php';

$value = var_export($languageLoader, true);

echo $value;

require DIR_WS_INCLUDES . 'application_bottom.php';
```

When that script is run, the following PHP warning is logged:
```
[15-Nov-2020 14:06:33 UTC] Request URI: /zc158/test.php, IP address: ::1
#1  var_export() called at [C:\xampp\htdocs\zc158\test.php:4]
--> PHP Warning: var_export does not handle circular references in C:\xampp\htdocs\zc158\test.php on line 4.

[15-Nov-2020 14:06:33 UTC] Request URI: /zc158/test.php, IP address: ::1
#1  var_export() called at [C:\xampp\htdocs\zc158\test.php:4]
--> PHP Warning: var_export does not handle circular references in C:\xampp\htdocs\zc158\test.php on line 4.
```

What is it with that `$languageLoader` variable that makes it have those circular references?

**Comment by drbyte** [comment]
It's because the `mainLoader` element is an object reference back to the same `Zencart\LanguageLoader\LanguageLoader` object that is `$languageLoader`.

Using `dump()` instead of `var_export()` shows it:
<img width="491" alt="Screen Shot 2021-02-03 at 3 12 12 PM" src="https://user-images.githubusercontent.com/404472/106804784-d3efb780-6633-11eb-9f7c-0e44bbea8698.png">

@zcwilt can the `mainLoader` element be removed from the array?

**Comment by lat9** [comment]
Bumping this.  Do I need to unset the $languageLoader for SuperGlobals to interoperate with zc158?

**Comment by drbyte** [comment]
In its current state, given that the $languageLoader presently generates `defines` (eg: backward compatible with older ZC versions) for each language entry it has detected, you could probably just tell Super Globals to skip it, like it does for several other resources.

**Comment by lat9** [comment]
OK, will do.

**Comment by scottcwilson** [comment]
Can this one be closed @lat9 ?

**Comment by scottcwilson** [comment]
Closing for now; please re-open if you feel this still needs work.
