### ISSUE TITLE
ZC158, class Customer: PHP Notice: A non well formed numeric value encountered, for decimal comma

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4097]
My currency settings are with decimal as comma and separator as decimal point. Don't ask.

So, set the currency as described and make an order.

On the admin customer page, debugs are generated as the text version of the order total extracted from table order_totals text column has a comma in it.

> PHP Notice: A non well formed numeric value encountered in 158\includes\classes\Customer.php on line 310:

https://github.com/zencart/zencart/blob/807ce81b5d96194d701046c823945490e9e5ae9a/includes/classes/Customer.php#L298-L314

and the strings get multiplied with the commas in them.

and also PHP Notice: A non well formed numeric value encountered in 158\includes\classes\currencies.php on line 97.
https://github.com/zencart/zencart/blob/807ce81b5d96194d701046c823945490e9e5ae9a/includes/classes/currencies.php#L95-L98

**Comment by torvista** [comment]
The culprit is the extraction of the text column 
ot.text as order_total
rather than ot.value. 

https://github.com/zencart/zencart/blob/807ce81b5d96194d701046c823945490e9e5ae9a/includes/classes/Customer.php#L488-L501
No doubt there is a good reason for that.

Just to clarify what is available, here you see where I changed the currency parameters before the last order.

![Clipboard01](https://user-images.githubusercontent.com/4391026/99717202-63f87900-2aa9-11eb-8a1f-7de4f709c9a9.gif)

**Comment by drbyte** [comment]
I believe that use of ot_text as order_total came from code merged from  /includes/modules/pages/account_history/header_php.php as found in v157.

How did you handle your comma issues there in v157/older ?

**Comment by torvista** [comment]
> How did you handle your comma issues there in v157/older ?
There are no issues as the text-values are not used in a calculation: they are for "display purposes only".

The calculation for lifetime values in customers.php was previously done using the decimal value from orders.order_total, as I would have expected.

**Comment by scottcwilson** [comment]
Note that in 1.5.7, the display of lifetime value in admin/customers.php is based on orders.order_total (a decimal field).  See admin/customers.php line 1386 for the query. 

In 1.5.8, the customers class uses orders.order_total in getLifetimeValue() (line 293)  but as noted above, uses order_totals.ot_text instead. 

This could be fixed simply by removing 

ot.text as order_total

from line 495 of includes/classes/Customer.php in 1.5.8.  The field orders.order_total is already being pulled by this query - it can just be used as is.  Note that the preg_preplace on line 538 would also not be needed.

**Comment by proseLA** [comment]
alternatively:

ot.value as order_total

but whatever gets decided, lets merge it before a 3rd person points out the same issue!

**Comment by scottcwilson** [comment]
PR Submitted: #4397

**Comment by scottcwilson** [comment]
I wound up doing a bit more than just removing `ot.text as order_total` because the join was no longer required, nor was the `preg_repl`.
