### ISSUE TITLE
ZC158, Admin, Customer Edit Form: additional fields from observer are inside ACCOUNT_COMPANY == 'true' clause

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4100]
The additional fields from the NOTIFY_ADMIN_CUSTOMERS_CUSTOMER_EDIT observer are inside the optional Company section, which may be disabled/hidden.
Is this deliberate?
I would have thought additional fields would have their own group...

**Comment by drbyte** [comment]
Good point. 
That should be outside the ACCOUNT_COMPANY conditional.
