### ISSUE TITLE
Admin, Customer: no notifier for inserting custom fields to customer table

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4103]
ZC158
There are notifiers to display form fields, validate the fields and insert address fields, but there seems to be one missing for the insertion of non-address fields.

https://github.com/zencart/zencart/blob/e3545eb1066e1fc729aac3a2144ee94cec1508c3/admin/customers.php#L157-L177

but I do see this lower down (the second notifier ADMIN_CUSTOMER_UPDATE) but I don't see where it may get used...is it in the wrong place?
https://github.com/zencart/zencart/blob/e3545eb1066e1fc729aac3a2144ee94cec1508c3/admin/customers.php#L213-L224

**Comment by scottcwilson** [comment]
`ADMIN_CUSTOMER_UPDATE` would get used by someone writing a plugin to handle custom fields, wouldn't it? 
I'm not sure what more you are asking for.

**Comment by lat9** [comment]
The 'non-address' fields for the customer can be modified via the `NOTIFY_ADMIN_CUSTOMERS_CUSTOMER_UPDATE` notification. 

I'll note that the `ADMIN_CUSTOMER_UPDATE` notification should be replicated as `NOTIFY_ADMIN_CUSTOMER_UPDATE` to enable auto-loaded or camelCasedFunction type observers to bind to that notification.

**Comment by torvista** [comment]
I've just noticed the "missing" notifier (not) in my original post was added in (by me) in 2021! Not that I noticed.
https://github.com/zencart/zencart/pull/4368

So, can be closed.
