### ISSUE TITLE
V157a PayPal Payments Standard Return To Timeout Page

### ISSUE THREAD

**Issue by sloanxue** [zencart/zencart#4104]
**Describe the bug**
When I using paypal sandbox to test paypal standard payment, the return page is timeout page after payment completed. 
It shows "Whoops! Your session has expired."

**Version**
Zen Cart version: 157a
PHP version: 7.4
MySQL version: 5.7
Plugins that may be related: N?A

**Describe the bug**

I try it both on live hosting and local host, also I just reinstalled a new zencart store by original v1.5.7a.
The problem is still the same.

**Comment by sloanxue** [comment]
Did I miss some thing? such as set configuration of sessions or cache?

**Comment by drbyte** [comment]
Is this the same as this: https://www.zen-cart.com/showthread.php?227429-paypal-sandbox-testing-return-back-to-timeout-page ?

I can't replicate the problem.
I just tested a fresh v157a install and demo data, installed and configured PayPal Standard for sandbox, and went through checkout without problem.

Tested on PHP 7.4 and PHP 8.0RC3, and MySQL 5.7 and 8.0

No customizations made, no plugins installed.

Tested on Chrome, Firefox, Safari.

**Comment by sloanxue** [comment]
Dear Drbyte
Yes, it is the same as zen-cart.com, sorry for duplicate the same problem.
Thank you for making test. 
The problem still happen in my local service and blue host live service. whatever I can sure it is my problem now.
By the way, at beginning I thought the problem is my customizations, so I checked all the files.... then I test fresh v157a...
live host...live host with fresh v157a... and test v139h, the problem does not happen in v139h but in v157a.
So I thought it maybe the bug of v157a.
Your support is greatly appreciated.
