### ISSUE TITLE
Bug: ZC158, shipping estimator, fatal error from missing template file

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4115]
Vanilla install, Admin-Shipping and Packaging->Shipping Estimator Display Settings for Shopping Cart->1 to display as button.

With product in cart, click on button to open Shipping Estimator, creates debug:
```
Request URI: /zencart-158/index.php?main_page=popup_shipping_estimator, IP address: 127.0.0.1
#1  require() called at [...\zencart-158\includes\templates\responsive_classic\common\tpl_main_page.php:178]
#2  require(...\zencart-158\includes\templates\responsive_classic\common\tpl_main_page.php) called at [...\zencart-158\index.php:94]
--> PHP Warning: require(includes/templates/template_default/templates/tpl_popup_shipping_estimator_default.php): failed to open stream: No such file or directory in ...\zencart-158\includes\templates\responsive_classic\common\tpl_main_page.php on line 178.

PHP Fatal error:  require(): Failed opening required 'includes/templates/template_default/templates/tpl_popup_shipping_estimator_default.php' in ...\zencart-158\includes\templates\responsive_classic\common\tpl_main_page.php on line 178
```

**Comment by torvista** [comment]
Possibly related:
https://github.com/mc12345678/zen-cart-sitemap-xml/issues/1

**Comment by drbyte** [comment]
You reported this for v158.
Does it also happen in prior versions?

**Comment by torvista** [comment]
No.

**Comment by torvista** [comment]
Bump. As I have the same issue with an add-on popup (different fileset) and see this issue is still open/unfixed in ZC158.

**Comment by drbyte** [comment]
I've been waiting to investigate this after the Laravel code is removed from the v158 branch (eta: soon), because some of the template override/detect logic was altered when the Laravel code was added and later updated.

**Comment by drbyte** [comment]
@torvista was this fixed with the fix for popup_image yesterday?

**Comment by torvista** [comment]
It's certainly working now.
