### ISSUE TITLE
ZC158 set timezone is overriden

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4116]
I note that that the personalised timezone setting in
 includes\extra_configures\set_time_zone.php has no effect...
or rather it gets changed to UTC subsequently by this
https://github.com/zencart/zencart/blob/e12445b5c1c98e9f3bda0f8afa190b0fdbb697e4/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php#L49

**Comment by drbyte** [comment]
Will be fixed shortly when I finish removing Laravel from the v158 base.
