### ISSUE TITLE
Uncaught TypeError: mysqli_num_rows(): Argument #1 ($result) must be of type mysqli_result, bool given

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#4122]
**Describe the bug**
Today I wanted to test ZC 1.5.8 on php 8.0, but got a fatal error right away.

**Version**
Zen Cart version: 1.5.8
PHP version: 8.0
MySQL version: 8.0.22-0ubuntu0.20.04.3

**Debug/Error Logs**
```
--> PHP Fatal error: Uncaught TypeError: mysqli_num_rows(): Argument #1 ($result) must be of type mysqli_result, bool given in /public_html/includes/classes/db/mysql/query_factory.php:911
Stack trace:
#0 /public_html/includes/classes/db/mysql/query_factory.php(911): mysqli_num_rows()
#1 /public_html/includes/classes/db/mysql/query_factory.php(268): queryFactoryResult->RecordCount()
#2 /public_html/includes/functions/sessions.php(95): queryFactory->Execute()
#3 [internal function]: _sess_gc()
#4 /public_html/includes/functions/sessions.php(117): session_start()
#5 /public_html/includes/init_includes/init_sessions.php(95): zen_session_start()
#6 /public_html/includes/autoload_func.php(36): require_once('...')
#7 /public_html/includes/application_top.php(229): require('...')
#8 /public_html/index.php(25): require('...')
#9 {main}
  thrown in /public_html/includes/classes/db/mysql/query_factory.php on line 911.
```

**Comment by drbyte** [comment]
I encountered this awhile back, both in PHP 8.0-alpha and in PHP 7.4, but then it disappeared.

One thing I tried was the following, which appeared to work but I didn't commit it because I wasn't certain that it's not just a bandage instead of the real fix:

`query_factory.php` line 910:
```diff
-        if (!empty($this->resource)) {
+        if (!empty($this->resource) && $this->resource !== true) {
             return @mysqli_num_rows($this->resource);
         }
```

**Comment by Zen4All** [comment]
👍 that did the trick. FYI I did not encounter this in php7.4

**Comment by scottcwilson** [comment]
MAMP PRO does not have PHP8 yet. :(  They were slow to get PHP7 too if I recall.

**Comment by drbyte** [comment]
This is probably an even better approach:

`        if (!empty($this->resource) && $this->resource instanceof mysqli_result) {`

**Comment by proseLA** [comment]
i tried the 2nd approach and that seems to work.

:+1:
