### ISSUE TITLE
zc_install: zero_dates_cleanup.sql won't work on strict MySQL installations

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4123]
**Describe the bug**
Using the 'model' provided by the subject SQL script to clean up some additional/addon tables, I found that a more strict MySQL installation will deny the update with an "Invalid Data for Column" error.

**Version**
Zen Cart version: 1.5.7b
PHP version: 7.3
MySQL version: MySQL 5.5.5-10.4.10-MariaDB
MySQL Mode: ONLY_FULL_GROUP_BY, NO_AUTO_VALUE_ON_ZERO, STRICT_ALL_TABLES, NO_ZERO_IN_DATE, NO_ZERO_DATE, ERROR_FOR_DIVISION_BY_ZERO, NO_AUTO_CREATE_USER, NO_ENGINE_SUBSTITUTION

**To Reproduce**
Using phpMyAdmin, attempt to run the following query
```
UPDATE tax_class SET date_added = '0001-01-01 00:00:00' WHERE date_added < '0001-01-01' and date_added is not null;
```
on a database where there is one or more `tax_class::date_added` records currently set to '0000-00-00 00:00:00'

**Expected behavior**
The query would work.  I was able to correct the query by using the following 'model':
```
UPDATE tax_class SET date_added = '0001-01-01 00:00:00' WHERE CAST(date_added AS CHAR(20)) = '0000-00-00 00:00:00';
```

**Comment by scottcwilson** [comment]
Or should we add a DB_MYSQL_MODE setting to the dist-configure.php files that permits this update to work, and document this in the upgrade documentation?

**Comment by drbyte** [comment]
Does running this before these updates resolve the issue? 

Turn off all strictness temporarily so that the updates can properly correct the incompatible data:
`SET SESSION sql_mode ='';`

The following could work as well, both because it allows dates outside the normal range, and also doesn't enforce denial of zero-date values:
`SET SESSION sql_mode ='ALLOW_INVALID_DATES';`

If it works as intended, we could add that to the top of the script.

**Comment by scottcwilson** [comment]
Thanks for reporting this, Cindy. This kind of thing is crazy-making during an upgrade. :)

**Comment by lat9** [comment]
No problems!

**Comment by scottcwilson** [comment]
When a final decision is made on the best approach, would the one who makes the PR please also update 

https://docs.zen-cart.com/user/upgrading/date_standardization/

to indicate the required steps for custom date upgrading too?  Thanks.

**Comment by drbyte** [comment]
I don't have a database to test this on right now, but if you can test it, please report back.

https://github.com/zencart/zencart/commit/05dd4bc666eac6fb03d771043492556b002ea0f4

**Comment by lat9** [comment]
Wouldn't it be 'better' in the long run to bite the bullet and change each of those queries to use a form that actually works without that override?  I won't be the first to use the Zen Cart code as a model, to find that it doesn't work.

**Comment by drbyte** [comment]
I'm surprised that you encountered the failure you reported in OP above. I suppose it's possible if there were other fields that needed handling as well.

Anyway, I'm not going to fight it. It's just a utility script aimed to help. A PR is welcome.

**Comment by lat9** [comment]
My OP was not related to a Zen Cart upgrade, it was the fact that I _assumed_ that the date-fixing query provided by the zc_install process would work as a model for similar issues with older addon's database date/datetime fields.

**Comment by drbyte** [comment]
> UPDATE tax_class SET date_added = '0001-01-01 00:00:00' WHERE CAST(date_added AS CHAR(20)) = '0000-00-00 00:00:00';

Curious: Why `CHAR(20)` when `0000-00-00 00:00:00` is 19 characters?
