### ISSUE TITLE
shipping module not getting set, and then used for comparison

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#4124]
https://github.com/zencart/zencart/blob/06937378d8b0a56ac623bd33a5a4dfe46d66ee55/includes/modules/order_total/ot_shipping.php#L65-L81

on line 65, we are setting `$module`; based on the code, it seems possible that it can get set to an empty string.

on line 81, we are now using that potentially empty string as an index within `$GLOBALS`.

we need to check with an `isset` prior to checking the `tax_class` to avoid a PHP notice.

i have seen this behavior out in the wild, with `$module` being set to an empty string.

**Comment by drbyte** [comment]
Argh, I hate $_GLOBALS.

I'd prefer the slightly shorter check for just an empty $module:

```diff
- if ($external_shipping_tax_handler === true || ($module !== 'free' && $GLOBALS[$module]->tax_class > 0)) {
+ if ($external_shipping_tax_handler === true || (!empty($module) && $module !== 'free' && $GLOBALS[$module]->tax_class > 0)) {
```

but of course that assumes that everyone correctly codes their shipping module with a tax_class property, so I guess that means:

```diff
- if ($external_shipping_tax_handler === true || ($module !== 'free' && $GLOBALS[$module]->tax_class > 0)) {
+ if ($external_shipping_tax_handler === true || (!empty($module) && $module !== 'free' && isset($GLOBALS[$module]->tax_class) && $GLOBALS[$module]->tax_class > 0)) {
```

**Comment by proseLA** [comment]
> Argh, I hate $_GLOBALS.
> 
makes 2 of us.

> I'd prefer the slightly shorter check for just an empty $module:
> 
> ```diff
> - if ($external_shipping_tax_handler === true || ($module !== 'free' && $GLOBALS[$module]->tax_class > 0)) {
> + if ($external_shipping_tax_handler === true || (!empty($module) && $module !== 'free' && $GLOBALS[$module]->tax_class > 0)) {
> ```
> 
> but of course that assumes that everyone correctly codes their shipping module with a tax_class property, so I guess that means:
> 
> ```diff
> - if ($external_shipping_tax_handler === true || ($module !== 'free' && $GLOBALS[$module]->tax_class > 0)) {
> + if ($external_shipping_tax_handler === true || (!empty($module) && $module !== 'free' && isset($GLOBALS[$module]->tax_class) && $GLOBALS[$module]->tax_class > 0)) {
> ```

well, we could always define an abstract shipping class with a tax class property, and then have all shipping modules extend the abstract class.  problem solved!  :laughing:

i'll look into doing a PR based on your above code recommendations.

**Comment by proseLA** [comment]
has a determination been made with regards to minimum PHP version for v1.5.8?  some of the coalesce operators available in php 7 can make these checks a little easier to read/code.

**Comment by drbyte** [comment]
> has a determination been made with regards to minimum PHP version for v1.5.8?

Ya, quite awhile ago it was set as 7.3
I don't see any reason why we'd go lower than that. There's an edge chance that 7.4 might be used instead.
