### ISSUE TITLE
Javascript form-checking: contact_us/ask a question

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4125]
Is javascript form-checking now considered unecessary, subsequent to the checks enforced by the browser and php post-submission?

**Comment by drbyte** [comment]
Given that most of its function has been implemented as HTML5 rules already, yes you can probably skip the use of the older form-checking javascript files.

**Comment by torvista** [comment]
Does this imply that the comprehensive form checking for create account etc., should be simplified to make use of equivalent HTML5 rules, when appropriate/due for revision?

**Comment by scottcwilson** [comment]
> Is javascript form-checking now considered unnecessary ... 

No - it saves a form submit to do pre-checking and flag things that won't work.
