### ISSUE TITLE
Admin orders.php:  Why re-format the order_total values?

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4126]
Storefront order totals have already currency-formatted (if needed) the value element of their addition with the output placed in the `orders_total::text` field.  This causes 'issues' for some order_total modules, e.g. reward_points_display.php, that don't supply currency-related `value` elements.

https://github.com/zencart/zencart/blob/05dd4bc666eac6fb03d771043492556b002ea0f4/admin/orders.php#L838

Couldn't the above line be simplified to

```php
<?php echo $order->totals[$i]['text']; ?> 
```

**Comment by drbyte** [comment]
> Couldn't the above line be simplified

Possibly.

Is there a chance that the `'text'` index might be absent but the `value` would be present and thus the `text` could be built from it?

**Comment by lat9** [comment]
Hmm, I've never seen an order-total that only provides the 'value' element, but you've seen a lot more than I have!

**Comment by scottcwilson** [comment]
Closing issue due to lack of interest and activity.
