### ISSUE TITLE
ZC158: SQL Patch tools fatal error

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4130]
~~Mod is not installed so there is no result to be found.~~

OK
SELECT @DPUgID := configuration_group_id FROM configuration_group where configuration_group_title = 'Dynamic Price Updater';

Expanding title up to and including 'Dynamic Price Updater Confi' is ok.

Not OK
SELECT @DPUgID := configuration_group_id FROM configuration_group where configuration_group_title = 'Dynamic Price Updater Config';

> [13-Dec-2020 13:18:07 UTC] PHP Fatal error:  Uncaught Error: Object of class queryFactoryResult could not be converted to string in ...\zencart-158\admin\sqlpatch.php:756
> Stack trace:
> #0 ...\zencart-158\admin\index.php(11): require()
> #1 {main}
>   thrown in ...\zencart-158\admin\sqlpatch.php on line 756
> [13-Dec-2020 13:18:07 UTC] Request URI: /zencart-158/admin/index.php?cmd=sqlpatch&action=execute, IP address: 127.0.0.1
> --> PHP Fatal error: Uncaught Error: Object of class queryFactoryResult could not be converted to string in ...\zencart-158\admin\sqlpatch.php:756
> Stack trace:
> #0 ...\zencart-158\admin\index.php(11): require()
> #1 {main}
>   thrown in ...\zencart-158\admin\sqlpatch.php on line 756.
>

**Comment by torvista** [comment]
Same thing happens with this:

ok
> SELECT @DPUgID := configuration_group_id FROM configuration where configuration_key = 'DPU_VERSIO';

not ok
> SELECT @DPUgID := configuration_group_id FROM configuration where configuration_key = 'DPU_VERSION';

**Comment by drbyte** [comment]
I just tried running both of those queries in v1.5.8 and v1.5.7. No errors on-screen, nor in debug logs.

**Comment by torvista** [comment]
I have strict reporting on.

However, after putting a few echoes in there, I find the reason.

The use of this $value is the error, as $value is indeed an object.
https://github.com/zencart/zencart/blob/e3bf04992876076c46c1c5665437db32b8967d9b/admin/sqlpatch.php#L754-L759

$query_results['output'] is set with the object from a $db-Execute:
https://github.com/zencart/zencart/blob/e3bf04992876076c46c1c5665437db32b8967d9b/admin/sqlpatch.php#L290-L293

But the contents of that object result differ between the queries and so the first one fails the null test (no constant found/no message/no error), but the second does not: I was mistaken in my first post, **this is the result when this constant DOES exist.**

1) query with DPU_VERSIO

![Clipboard01](https://user-images.githubusercontent.com/4391026/102019946-76976280-3d76-11eb-9a47-83974cbfbab0.gif)

2) query with DPU_VERSION


![Clipboard02](https://user-images.githubusercontent.com/4391026/102020057-2ec50b00-3d77-11eb-9185-4d3664a143f0.gif)

So the message IS trying to convert the $value object to a string.

**Comment by drbyte** [comment]
I'm pretty sure that whatever functionality was intended by that `output` index is moot.

So, probably safe to just exclude the loop:
```diff
-        if (zen_not_null($query_results['output'])) {
-          foreach ($query_results['output'] as $value) {
-            if (zen_not_null($value)) {
-              $messageStack->add('INFO: ' . $value, 'caution');
-            }
-          }
-        }
```
