### ISSUE TITLE
Bug ZC158: collect_info - product url is required

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4132]
>           <?php echo zen_draw_input_field('products_url[' . $languages[$i]['id'] . ']', htmlspecialchars(isset($products_url[$languages[$i]['id']]) ? $products_url[$languages[$i]['id']] : zen_get_products_url($pInfo->products_id, $languages[$i]['id']), ENT_COMPAT, CHARSET, TRUE), zen_set_field_length(TABLE_PRODUCTS_DESCRIPTION, 'products_url') . ' class="form-control"', 'url'); ?>

is more easily readable as

```
          <?php echo zen_draw_input_field(
              'products_url[' . $languages[$i]['id'] . ']',
              htmlspecialchars(isset($products_url[$languages[$i]['id']]) ? $products_url[$languages[$i]['id']] : zen_get_products_url($pInfo->products_id, $languages[$i]['id']), ENT_COMPAT, CHARSET, TRUE),
              zen_set_field_length(TABLE_PRODUCTS_DESCRIPTION, 'products_url') . ' class="form-control"',
              'url')
          ; ?>
```
So the 4th parameter 'url' at the end sets the field as required.
I assume this should be an id after the class?

**Comment by Zen4All** [comment]
```'url'``` should be the fifth parameter, to se the field type.
```php
<?php echo zen_draw_input_field('products_url[' . $languages[$i]['id'] . ']', htmlspecialchars(isset($products_url[$languages[$i]['id']]) ? $products_url[$languages[$i]['id']] : zen_get_products_url($pInfo->products_id, $languages[$i]['id']), ENT_COMPAT, CHARSET, TRUE), zen_set_field_length(TABLE_PRODUCTS_DESCRIPTION, 'products_url') . ' class="form-control"', '', 'url'); ?>
```
The problem is that on the admin side the field type is set by the 5th parameter, but on the shop side by the 4th. So someone mistakenly used the wrong function.

I really do not like the way you like the way you rewrote the function over multiple lines. In my view this makes code look messy, and less readable, but that my be my personal taste 😄

**Comment by torvista** [comment]
> I really do not like the way you like the way you rewrote the function over multiple lines
I didn't rewrite anything, I just separated the function parameters onto separate lines in my post so it was easy to see the fourth parameter that was causing the problem.
