### ISSUE TITLE
$db->Execute($sql, 1);  second parameter is an integer, but class hints as string

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4135]
ZC158. 
There are 21 instances of exactly this 
$db->Execute($sql, 1);
I suppose there are many more using the limit, but I was defeated by phpstorm regex find....
https://github.com/zencart/zencart/blob/77d9b255ecccde7fba0b2ab0001e630979e192f4/includes/classes/db/mysql/query_factory.php#L191

**Comment by drbyte** [comment]
This is exactly why strict-typing is entirely annoying.

Most of the time $limit can be, and is, an integer.  Sometimes, although rarely, it is a pair of integers separated by a comma.

To accommodate that we must forfeit strict-typing.

**Comment by torvista** [comment]
Is it not part of the "big picture" for php that existing things get more tightly defined/restricted/controlled, and so the strict typing aspect is something that eventually will be unavoidable/compulsory? So all this is just future-proofing when convenient in development, instead of being forced by a php change?

I also have seen comments about adding function type hinting but not casting/checking the input variables may lead to new unexpected results. As I mentioned elsewhere, using hinting but not reviewing the variables passed seems to be only half the code change required.

Personally I also find it a great help in the IDE to use strict to highlight potential errors/overlooked anomalies caused by mixing types. And I need all the help I can get.
