### ISSUE TITLE
Admin EZ-Pages, Yes/No radio buttons visual issues

### ISSUE THREAD

**Issue by marco-pm** [zencart/zencart#4137]
The Header, Sidebox, Footer, TOC Yes/No radio buttons are not vertically aligned with the labels, and overlap the bottom text input on mobile and large screen.

![Screenshot 2020-12-16 194713](https://user-images.githubusercontent.com/53403229/102393253-6383cd00-3fd8-11eb-9375-c78dc05b6687.jpg)

![Screenshot 2020-12-16 194736](https://user-images.githubusercontent.com/53403229/102393256-641c6380-3fd8-11eb-9354-4ef1ff4219a5.jpg)

Zen Cart version: 1.5.7b

**Comment by drbyte** [comment]
What browsers are you using in these screenshots?

![Admin Ezpages 2020-12-16 at 2 22 35 PM](https://user-images.githubusercontent.com/404472/102396424-6f589a80-3faa-11eb-98f5-43976dca3c60.jpg)

<img width="423" alt="Screen Shot 2020-12-16 at 2 24 08 PM" src="https://user-images.githubusercontent.com/404472/102396437-7384b800-3faa-11eb-9932-49c06c1aa196.png">

**Comment by marco-pm** [comment]
> What browsers are you using in these screenshots?

You're right, forgot to write it.
Chrome 87 and Edge Chromium 87

**Comment by scottcwilson** [comment]
@marco I have checked on phone, tablet and desktop using current Chrome (96) and it looks ok to me.  Are you still seeing it?

**Comment by marco-pm** [comment]
Just checked and it has been fixed on v158 with #3929 👍
We can close this.
