### ISSUE TITLE
Missing space in attributes_controller.php

### ISSUE THREAD

**Issue by simon1066** [zencart/zencart#4143]
ZC v1.5.8 
admin/attributes_controller.php 
line#1549
`<i class="fa fa-square fa-stack-2xrequired-attr-txt" aria-hidden="true"></i>`
should be 
`<i class="fa fa-square fa-stack-2x required-attr-txt" aria-hidden="true"></i>`

The lack of space after 2x causes the attributes_controller legend to look like this:

![Untitled](https://user-images.githubusercontent.com/13421449/103003704-2c0da700-4529-11eb-9e1c-e55a66a652c4.png)

Also present in ZC v1.5.7b line#1619 - in case there's going to be a v1.5.7c release.

**Comment by drbyte** [comment]
Thanks!
