### ISSUE TITLE
shopping cart class and cart_errors design

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#4155]
i am curious if this is good design.

we have a `$_SESSION['cart_errors']` that only gets initialized on the shopping cart page.  and yet the only time it gets added to is within the shopping cart class.  and mostly within the `get_products` function.

does it not make sense to at least check at the beginning of that function, or more likely initiate the var in the `_construct` function as opposed to initiating the var on a page that there is no guarantee it will get hit?

i am unfamiliar with OPC, as i currently have my clients on FEC.  i have noticed a few times getting a PHP notice on an undefined index for this session var.  and while i acknowledge the shortcomings of FEC, it seems to be the design is flawed as there is no guarantee that the var will get initialized from this or some other checkout plugin.

am i wrong?  any thoughts?

**Comment by drbyte** [comment]
Given that the class can be called from anywhere, and that can result in attempts to append to the variable, you're right that it ought to be initialized from inside the class so that it manages its own dependency.

Probably good to put it inside the `reset()` method.

Wanna test this out?
```diff
    public function reset($reset_database = false)
    {
        global $db;
        $this->notify('NOTIFIER_CART_RESET_START', null, $reset_database);
...
        unset($this->cartID);
        $_SESSION['cartID'] = '';
+        $_SESSION['cart_errors'] = '';
        $this->notify('NOTIFIER_CART_RESET_END');
    }
```

**Comment by drbyte** [comment]
Probably good to also add `valid_to_checkout` as well:
```diff
    public function reset($reset_database = false)
    {
        global $db;
        $this->notify('NOTIFIER_CART_RESET_START', null, $reset_database);
...
        unset($this->cartID);
        $_SESSION['cartID'] = '';
+        $_SESSION['cart_errors'] = '';
+        $_SESSION['valid_to_checkout'] = true;
        $this->notify('NOTIFIER_CART_RESET_END');
    }
```

**Comment by proseLA** [comment]
ok, i will test it out.  but i'm letting you know now, this is my last idea for the year.  that's it....  i'm done for the year... nothing more until next year! :smile:

**Comment by proseLA** [comment]
after implementing this on a couple of live sites, i am not seeing any ill affect.

i think this is a worth wild change...  positive upside; no negative downside (that i see...)
