### ISSUE TITLE
refactor has switch wrong for zen_count_products_in_category

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#4163]
https://github.com/zencart/zencart/blob/d6b0ffdd136d32df05cfeee27397ce5211f69381/includes/functions/functions_categories.php#L67-L69

pretty sure this should be `(!$include_inactive)`.

**Comment by proseLA** [comment]
https://github.com/zencart/zencart/blob/d6b0ffdd136d32df05cfeee27397ce5211f69381/includes/functions/functions_categories.php#L1345-L1347

https://github.com/zencart/zencart/blob/d6b0ffdd136d32df05cfeee27397ce5211f69381/includes/functions/functions_categories.php#L632

also looks wrong.

**Comment by drbyte** [comment]
You are correct. 
Interestingly, the last one you mentioned existed before the refactor.

**Comment by drbyte** [comment]
`zen_get_categories_products_list` is used in catalog by new/specials/featured/upcoming modules.
Those probably need updating to match the logic correction.
