### ISSUE TITLE
action=remove_product uses $_GET['product_id']

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4164]
Not so much of a bug report, but an observation.  

While all the other product-related actions use `$_GET['products_id']` (with the **s**), the remove_product action uses an **s**-_less_ version of that $_GET variable.  The `$parameters` passed to the cart's `actionRemoveProduct` method never identify that variable for removal, so the post-action redirect will include that unwanted variable.

**Comment by drbyte** [comment]
> uses an **s**-_less_ version of that $_GET variable

I've always hated those "s" suffixes.

**Comment by drbyte** [comment]
>  The $parameters passed to the cart's actionRemoveProduct method never identify that variable for removal, so the post-action redirect will include that unwanted variable.

Given that all templates, both core and contributed, have the $_GET param as is currently implemented, changing it at the template layer isn't likely ideal. 
Instead, this is probably the most straightforward fix:
```diff
    public function actionRemoveProduct($goto, $parameters)
    {
        if (!empty($_GET['product_id'])) $this->remove($_GET['product_id']);
+        $parameters[] = 'product_id';
        zen_redirect(zen_href_link($goto, zen_get_all_get_params($parameters)));
    }
```
