### ISSUE TITLE
157+: Developers' Took Kit not finding /zc_plugins information

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4165]
**Describe the bug**
As kind of reported in [this](https://www.zen-cart.com/showthread.php?227622-Invoice-Payment-Method-V-23Dec2018-Installation-issue&p=1376471#post1376471) Zen Cart posting, the Developers' Tool Kit isn't finding keywords present in files present in the `/zc_plugins` sub-directory.

**Version**
Zen Cart version:  zc157b

**To Reproduce**
1. Navigate to the admin's Tools :: Developer's Tool Kit.
2. Enter `DISPLAY_LOGS_INCLUDED_FILES` in the last search box, as below, and then press Enter
![image](https://user-images.githubusercontent.com/2685585/104045892-39739400-51ad-11eb-9795-bd83488a59fb.png)

**Expected behavior**
A match should be found on `/zc_plugins/DisplayLogs/v3.0.0/admin/display_logs.php`, but the tool reports that the phrase cannot be located.

**Comment by drbyte** [comment]
Hmmm. 
#3776 added a selection for specifically looking in `zc_plugins`.

**Comment by lat9** [comment]
Yes, a necessary but incomplete change.  That added a "Lookup in the zc_plugins" selection, but didn't add the /zc_plugins sub-directory to any of the other "Find all ..." selections.
