### ISSUE TITLE
Recent Customers list on Admin Dashboard is a slow query

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4171]
Symptom: Admin login is slow, admin home page display is slow. 

Turn on slow query logging and you'll get a report on this query.    In newer versions, this is in admin/includes/modules/dashboard_widgets/RecentCustomersDashboardWidget.php.  In older versions, it's in admin/index_dashboard.php but the query is the same. 

 Time: 2021-01-12T13:25:09.943194Z
 User@Host: dba[dba] @ localhost []  Id:  6616
 Query_time: 1.132665  Lock_time: 0.000265 Rows_sent: 15  Rows_examined: 349083
SET timestamp=1610457909;
SELECT c.customers_id as customers_id, c.customers_firstname as customers_firstname,
                                          c.customers_lastname as customers_lastname, c.customers_email_address as customers_email_address,
                                          a.customers_info_date_account_created as customers_info_date_account_created, a.customers_info_id
                                   FROM customers c
                                   LEFT JOIN customers_info a ON c.customers_id = a.customers_info_id
                                   ORDER BY a.customers_info_date_account_created DESC LIMIT 15;

**Version**
Zen Cart version: 156a (but also in newer versions) 
PHP version: 7.2 
MySQL version: MySQL 5.7.26

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
You need a large database to reproduce this, and a low slow query threshold.  
Turn on slow query logging 
Login to admin as a superuser.

**Expected behavior**
Query should not be slow. 

An EXPLAIN on the query shows the ORDER BY causes the use of temporary tables. 

If we add an index to  customers_info.customers_info_date_account_created  and augment the query to use another WHERE, this issue would be resolved.   This can be verified using EXPLAIN.    You'll see the rows field for table a drop from the entire count for the table down to 15.  See attached image.

a) Add WHERE c.customers_id = a.customers_info_id  to the query

b) In the db upgrade script, do 

ALTER TABLE customers_info ADD INDEX idx_date_account_created (customers_info_date_account_created, customers_info_id);

c) In the db creation script, create the index as well. 

![query](https://user-images.githubusercontent.com/4391638/104323680-7513a400-54b4-11eb-9f2e-24f690da0a71.jpg)

**Comment by drbyte** [comment]
Thanks for reporting this.

For consistency of naming convention (in Zen Cart we've typically added a `_zen` suffix to our intentionally-created indexes, to distinguish them from those auto-generated by phpMyAdmin etc, and also attempt to "mention" multiple fields' names as clues even if heavily abbreviated), I'd suggest:

```sql
ALTER TABLE customers_info ADD INDEX idx_date_created_cust_id_zen (customers_info_date_account_created, customers_info_id);
```

In my testing I found that merely adding the WHERE clause helps a little immediately, depending on the size of the tables. 
Adding the index helps even more by bringing the results down to the LIMIT value. 
Adding the index alone without the WHERE makes no difference.

Feel free to submit a PR to v158.

**Comment by scottcwilson** [comment]
Yep, those were my findings too. It's kind of hilarious how *awful* your intuition is as a guide to optimization, right? :) 

OK will shoot to do a PR this week or next.

**Comment by drbyte** [comment]
> It's kind of hilarious how _awful_ your intuition is as a guide to optimization, right? :)

Too true! The things I expected to "work" ... didn't work as anticipated.

That said, I do wonder if some of the EXPLAIN results (and query performance results) vary based on null vs zero-date entries, and also on whether actual matching customers_info table records exist for all customers-table rows. (There are lots of times I see missing ci records.)
