### ISSUE TITLE
Undefined index: manufacturers_name in modules\product_listing.php

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4175]
ZC158 current (with recent product listing changes)
strict reporting
classic template (as it uses default file).
Browse to a category listing like Graphics cards and get a notice

> [15-Jan-2021 15:53:23 UTC] Request URI: /zencart-158/index.php?main_page=index&cPath=1_4, IP address: 127.0.0.1
#1  include(...\zencart-158\includes\modules\product_listing.php) called at [...\zencart-158\includes\templates\template_default\templates\tpl_modules_product_listing.php:11]
#2  require(...\zencart-158\includes\templates\template_default\templates\tpl_modules_product_listing.php) called at [...\zencart-158\includes\templates\template_default\templates\tpl_index_product_list.php:93]
#3  require(...\zencart-158\includes\templates\template_default\templates\tpl_index_product_list.php) called at [...\zencart-158\includes\modules\pages\index\main_template_vars.php:232]
#4  require(...\zencart-158\includes\modules\pages\index\main_template_vars.php) called at [...\zencart-158\includes\templates\template_default\common\tpl_main_page.php:141]
#5  require(...\zencart-158\includes\templates\template_default\common\tpl_main_page.php) called at [...\zencart-158\index.php:94]
--> PHP Notice: Undefined index: manufacturers_name in ...\zencart-158\includes\modules\product_listing.php on line 362.

which is 
`                    'manufacturers_name' => $record['manufacturers_name'],`

**Comment by drbyte** [comment]
Forgot to push those fixes up
