### ISSUE TITLE
Array to string conversion in tpl_tabular_display.php

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4176]
ZC158
classic template to use default file (problem exists on responsive classic too)
browse to category product listing.

> [15-Jan-2021 17:07:59 UTC] Request URI: /zencart-158/index.php?main_page=index&cPath=1_4, IP address: 127.0.0.1
> #1  require(...\zencart-158\includes\templates\template_default\common\tpl_tabular_display.php) called at [...\zencart-158\includes\templates\template_default\templates\tpl_modules_product_listing.php:40]
> #2  require(...\zencart-158\includes\templates\template_default\templates\tpl_modules_product_listing.php) called at [...\zencart-158\includes\templates\template_default\templates\tpl_index_product_list.php:93]
> #3  require(...\zencart-158\includes\templates\template_default\templates\tpl_index_product_list.php) called at [...\zencart-158\includes\modules\pages\index\main_template_vars.php:232]
> #4  require(...\zencart-158\includes\modules\pages\index\main_template_vars.php) called at [...\zencart-158\includes\templates\template_default\common\tpl_main_page.php:141]
> #5  require(...\zencart-158\includes\templates\template_default\common\tpl_main_page.php) called at [...\zencart-158\index.php:94]
> --> PHP Notice: Array to string conversion in ...\zencart-158\includes\templates\template_default\common\tpl_tabular_display.php on line 35.

repeats several times.

Which is
`      if ($cell_type=='th') $c_params .= ' scope="' . $cell_scope . '" id="' . $cell_title . 'Cell' . $row . '-' . $col.'"';`

Not so simple, so I stuck some echos and gettypes just before this line:

![conversion error Classic](https://user-images.githubusercontent.com/4391026/104757323-35231a00-575d-11eb-8806-e737a2522aaf.gif)

What seems also odd is there are 12 parses (four th, four td, four td) but only three columns on the listing.

**Comment by drbyte** [comment]
Oops, forgot to push those fixes
