### ISSUE TITLE
TEXT_INFORMATION redundant for shopping_cart

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4177]
I believe this is redundant/replaced by a html_define:
https://github.com/zencart/zencart/blob/e11afe2b0c8790f7d24246ad9fd9d036f9563e3b/includes/languages/english/shopping_cart.php#L9

**Comment by scottcwilson** [comment]
It's not bad to have both.   The HTML could change seasonally with the define remaining static, for example.

**Comment by torvista** [comment]
I don't see where this define is currently used in shopping_cart.

By the same reasoning there seems to be multiple defines of TEXT_INFORMATION that are not used:
![Clipboard01](https://user-images.githubusercontent.com/4391026/104812786-f5177200-5804-11eb-845e-83f627c92047.gif)

**Comment by scottcwilson** [comment]
> I don't see where this define is currently used in shopping_cart.

It was present for a long time, which means older templates will still have it.  
Removing it would break older templates for no good reason.
