### ISSUE TITLE
Upgrade option doesn't work with MySql 8.0.17 or greater

### ISSUE THREAD

**Issue by nikhilchaudhary70** [zencart/zencart#4178]
ZenCart upgrade option doesn't come with MySql 8.0.22 version because in MySql 8.0.17 Display width specification for integer data types was deprecated.

Ref: https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-19.html
![Screenshot from 2021-01-16 01-50-53](https://user-images.githubusercontent.com/19204768/104774814-54419c00-579d-11eb-9cc4-ebd5fbde8ba7.png)

**Version**
Zen Cart version:  1.5.7
PHP version: 7.4
MySQL version: 8.0.22

**Comment by drbyte** [comment]
Fixed in upcoming v157c via: https://github.com/zencart/zencart/commit/6ee98c181812ef5bf7f907d150f3acfc7d73aadc
