### ISSUE TITLE
problems in shopping_cart class with mixed

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#4180]
https://github.com/zencart/zencart/blob/e11afe2b0c8790f7d24246ad9fd9d036f9563e3b/includes/classes/shopping_cart.php#L2643-L2649

in this changed array, there is a boolean, 3 arrays, and 2 elements of an array.

i do not deal with attributes much, so this code is a bit foreign to me.  however using the test data, it is very easy to generate a notice here.  add the russ tippins band (pid: 166) to your cart; go to your cart, and change the quantity.  going up results in a php warning on the line 2647.  going down results in a warning on 1789.

**Comment by mc12345678** [comment]
Does a notice occur if no change is made and the page is refreshed by clicking on the update button? My assumption is that it does on both lines 2646 and 2647 in that situation although I haven't had such get logged in Zen Cart 1.5.7 (haven't tried/applied Zen Cart 1.5.8 with strict php/logging of notices).

I do have a proposed solution though based on the above reported situations.

**Comment by proseLA** [comment]
> Does a notice occur if no change is made and the page is refreshed by clicking on the update button? My assumption is that it does on both lines 2646 and 2647 in that situation although I haven't had such get logged in Zen Cart 1.5.7 (haven't tried/applied Zen Cart 1.5.8 with strict php/logging of notices).
> 
> I do have a proposed solution though based on the above reported situations.

yes, it does.
