### ISSUE TITLE
Is invalid attribute className needed on state fields in create account?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4185]
https://github.com/zencart/zencart/blob/d61dc2b7c7bc0f3fb98c45ec74536deb90d8e13c/includes/modules/pages/login/jscript_addr_pulldowns.php#L38-L59

For example

This sets the item class to value "hiddenField":
`theForm.state.className = 'hiddenField'; `
That's clear enough.

This adds another attribute called "className" with value "hiddenField":
`   theForm.state.setAttribute('className', 'hiddenField'); `
This I don't understand.

Previously discussed but not, I think, resolved:
https://www.zen-cart.com/showthread.php?220483-removal-of-id-stText-in-ZC155-causes-various-javascript-failures&p=1359877#post1359877

**Comment by drbyte** [comment]
It was added years ago to support browsers that couldn't support modern javascript.

While it needs cleaning up, merely deleting a few lines is a weak bandage instead of a proper overhaul.

**Comment by lat9** [comment]
@torvista, is this issue now redundant, with the consolidation provided in #4754?
