### ISSUE TITLE
validation: cannot use autocomplete username with input type email

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4187]
For example on a combined login page
![Clipboard01](https://user-images.githubusercontent.com/4391026/105577895-b80b2c80-5d7c-11eb-9d37-c8084204d73a.gif)

After reviewing input as type email
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email
and autocomplete
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

I conclude that type email restricts the allowed characters to email addresses, but username is a string, so there is a conflict.
Changing the autocomplete to "email" removes the error.

There are three instances of this that I could find, if you want a pr.

**Comment by drbyte** [comment]
The use of `autocomplete="username"` is intentional.

Semantically it **is** the user's `username`.
And it **is** a string.

Setting `autocomplete="email"` presumes that it should be the user's primary email address, which leads to many problems with password managers.

**Comment by torvista** [comment]
I understand your point, but
> autocomplete lets web developers specify what if any permission the user agent has to provide automated assistance in filling out form field values, as well as guidance to the browser as to the type of information expected in the field.

so if the input is "email", that means a narrowly-restricted group of characters, whereas "username" (as string) permits a much wider range of characters, is that not the reason for the reported error/conflict?

**Comment by drbyte** [comment]
You are correct that type="email" applies a degree of restriction on allowed characters.
But it does a lot more than that:
- it sets the correct keyboard for the user's device
- it validates the input data to ensure it matches a prescribed pattern
- via that validation it prevents form submission if the provided data doesn't match the pattern, and displays messaging

The addition of `autocomplete="username"` has nothing to do with enforcing the type of characters supplied by the user. No validation is applied. It is used to hint to the browser and password-managers how they might provide suggested content if the user is in the pattern of allowing such automation. It also works in tandem with some mobile-device browsers to give additional hints to appropriate keyboards to offer.

**Comment by torvista** [comment]
It's a bug in the spec..and validator.
https://github.com/validator/validator/issues/983
I should have researched a bit more....

**Comment by drbyte** [comment]
Thanks for pinging them about their bug.

Validators have their place. They can be useful, but I don't always trust their feedback.
