### ISSUE TITLE
[158] Creating account 'insists' on using state dropdowns

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4191]
**Describe the bug**
Running zc158 (current as of this writing).  Demo products loaded, using all default settings -- specifically **_Configuration :: Customer Info :: State - always display as dropdown?_** is set to _false_.

On the storefront, click the Login button and fill out the create-account form.  The "State/Province" defaults (correctly) to an empty text field.  Supply an address, enter FL for the state (the country has defaulted to the 'United States').  For my case, the state was 'auto-filled' (I'm not sure if that has bearing).

**_Update_**: The 'auto-fill' has no bearing.

![image](https://user-images.githubusercontent.com/2685585/105611504-d163a700-5d83-11eb-85b8-921275e86da8.png)

After filling in all the required fields, click the "Submit" button to be met with the following error:
![image](https://user-images.githubusercontent.com/2685585/105611552-0a038080-5d84-11eb-9180-976002474fba.png)

**Version**
Zen Cart version: zc158-dev
PHP version: PHP 8.0.1
MySQL version:  MySQL 5.5.5-10.4.10-MariaDB

**To Reproduce**
See above.

**Expected behavior**
That an account would have been successfully created.

**Comment by torvista** [comment]
I still think country dropdown should be the first thing is the list..apart from getting the province selection in place prior to submit, it could alter how core and custom fields are treated subsequently, with country-specific notes/validation of fields.:
https://github.com/zencart/zencart/issues/1665

**Comment by lat9** [comment]
@torvista, are you referring to the State/Province entry?  Note in the screenshot above that the country dropdown has already been moved to the top of the address-related entries.

**Comment by torvista** [comment]
I was meaning that the state dropdown should update with the country select, avoiding that form submit error:  if I get an error message, it should be from an actual error/mistake on my part, not as a result of not doing something I couldn't do in the first place.

**Comment by torvista** [comment]
While reviewing this and account edit address, I don't see the logic behind an admin switch for displaying the drop down or not, when zones are already defined for that country.

If it is set to false as in this case, a text field for zone is used...but even putting a value in that, that matches a defined zone in the not-shown-dropdown, does not get allowed.
If there are defined zones for a country (and assuming store owner has defined a complete list for that country), I don't see why you would not always show a dropdown....and so improve the user experience by having that dropdown always update on a change of country to prevent the inevitable-but-avoidable submission+refusal that happens currently.

**Comment by scottcwilson** [comment]
> I don't see the logic behind an admin switch for displaying the drop down or not, when zones are already defined for that country.

I would agree with you if we were starting today.  Unfortunately this is a legacy configuration we have to maintain.

**Comment by piloujp** [comment]
Browsing through old issues I realize this issue is identical to issue #5707 and was fixed by PR #5711.
It could be closed without any problem.
