### ISSUE TITLE
edit account header: dob not set when ACCOUNT_DOB is false

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4192]
This line does not set the dob variable if the admin switch is false and the pageload was from the form submission:
https://github.com/zencart/zencart/blob/066e78cc714f5afaaf4eb9665538e25b16040474/includes/modules/pages/account_edit/header_php.php#L24

This will create an error 
PHP Notice: Undefined variable: dob in 
zencart-158\includes\modules\pages\account_edit\header_php.php 
on line 189:
$dob = ($dob == '0001-01-01 00:00:00') ? '' : $dob;

when a field is incorrect, it fails php validation and so the form is redisplayed/page is not redirected to account. 

At the moment, this cannot happen as the fields are checked by the browser and javascript, so all errors get trapped before submission and so the php error checking will not catch any errors and never cause the form to be redisplayed/not redirected.

(I got it as an extra field was not being checked by js due to another bug, so the form was redisplayed.)

So why bother?
Well I think the originally mentioned line was intentioned to set dob, so needs correcting.

And something else I think I suggested elsewhere (or I imagined it) was to not have the redirect at all: after editing a field and submitting the form, I think it is better if the details/form is redisplayed with the success message, so the customer can see the change has been correctly stored. I've done that for my store.

So in this case, the dob notice will occur.

**Comment by mc12345678** [comment]
Though doesn't completely address the above, perhaps line 179 (and associated note) could be changed as:
````diff
- if (!(isset($_POST['action']) && ($_POST['action'] == 'process'))) {
-   // Posted page content is not requested to be processed, populate dob with customer's database entry.
+ if (!(isset($_POST['action']) && ($_POST['action'] == 'process')) || empty($dob)) {
+   // Posted page content is not requested to be processed or is not provided, populate dob with customer's database entry.
````
This should at least remove the undefined variable notice if nothing is done at line 24. Not yet sure of impact on remainder of page load though...
