### ISSUE TITLE
When CSS Buttons are on, ICON_IMAGE_UPDATE should be replaced by a text button that says UPDATE

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4198]
It seems to me that this was just an image that was missed when CSS buttons were introduced.  

Places to change would be

includes/modules/pages/shopping_cart/header_php.php
includes/templates/responsive_classic/templates/tpl_shopping_cart_default.php
includes/templates/template_default/templates/tpl_shopping_cart_default.php

**Comment by drbyte** [comment]
Are you referring to this?

<img width="52" alt="Screen Shot 2021-02-25 at 2 13 07 PM" src="https://user-images.githubusercontent.com/404472/109204680-a51cbb00-7773-11eb-8b26-c756b986e77d.png">

**Comment by scottcwilson** [comment]
Correct.

**Comment by scottcwilson** [comment]
Meh.  This isn't worth the headache.

**Comment by scottcwilson** [comment]
Anyone who really wants it to work this way can just update the main language file and set `ICON_UPDATE_ALT` to "Update".
