### ISSUE TITLE
adding additional notifier?

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#4199]
https://github.com/zencart/zencart/blob/7d2e28dff69ff65bf2daa7384b061b095798aa70/admin/includes/modules/copy_product.php#L49

in looking at this script, i only see 1 notifier.  i am not sure the reasoning for only including the notifier if the product has attributes.  nor am i sure what might be the best way to address my specific issue, which is the need for a notifier outside of the attributes conditional.  or do i continue with maintaining duplicate code for my product type (which, to me, is not ideal).

appreciate any guidance.

**Comment by drbyte** [comment]
I have no objection to it being relocated outside the conditional.

Ref https://github.com/zencart/zencart/pull/1683 
// cc @mc12345678

**Comment by mc12345678** [comment]
The reason for the requested notifier at that point was to provide the ability to add action if the product in question met the requirements to display the option to copy the attributes. As such, the notifier was to be added within the area where such was determined and preferably at the end of that list. I can add a "negative" test at the beginning of my code to not take the action and likely will update how it is used/where it is to be placed throughout the code to match the new location.

Thanks for the heads up.

Btw, there are ways to pull in some code when that action is to be taken without having the notifier in the base code.
