### ISSUE TITLE
[157] jQuery error updating banner that's scheduled

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4204]
**Describe the bug**
zc157b, demo products installed.  Go to the admin's Banner Manager, edit the next-to-last entry (in Sidebox-Banners) adding a _Scheduled At_ and _Expires On_ date and save.

Once the dates have been entered, re-edit the banner, changing the text of the title and press Update.  You're met with 
![image](https://user-images.githubusercontent.com/2685585/107393153-768eb700-6ac8-11eb-8eea-db89b7224a27.png)

and no way to save the update.  Noting that the issue isn't present in the current zc158 file-set, but the spiffyCal elements are no longer being used.

**Version**
Zen Cart version: zc157b
PHP version: 7.3
MySQL version: n/a
What older/newer versions were also tested? zc158

**To Reproduce**
See above.

**Expected behavior**
I'd expect that the updated banner would be correctly saved.

**Debug/Error Logs**
No error logs or console errors were found.

**Comment by drbyte** [comment]
A few things seem to be contributing to the problem:
- when a trailing-space is present and edits are done via keyboard, the "error" state gets set, hence the red outline and blocked submit
- keyboard editing of the numbers may result in the date-format getting swapped between mm/dd and dd/mm

Using mouse-only navigation to edit the date doesn't appear to trigger either of these problems

**Comment by lat9** [comment]
I didn't touch the start/end dates, just changed the banner's title to receive that unwanted error.

**Comment by drbyte** [comment]
Fixed by removing extra space on line 286: https://github.com/zencart/zencart/commit/7ae05632fe371150e5a6b05f90933208aaa1d4b3

**Comment by lat9** [comment]
Nice one, as always, @drbyte.  I'd looked at that code 3-ways-from-Sunday and didn't see that extra space!
