### ISSUE TITLE
Report showing customers with no orders 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4206]
**Is your feature request related to a problem? Please describe.**
Spam accounts can be hard to spot, but they're guaranteed to have no orders.  This would allow easy review of suspected spam accounts. 

**Describe the solution you'd like**
New report under Admin > Reports showing accounts with no orders in reverse chronological order.  

Showing the new customers.registration_ip field in this report will also help identify sources of spam accounts. 

I'll be happy to do the work if approved.

**Comment by lindasdd** [comment]
To provide a little different perspective, my first thought on accounts with no orders is that those are abandoned checkout accounts (and some spam). So while a report on them would be helpful, I wouldn't want to run such a report with immediate deletion in mind.

**Comment by scottcwilson** [comment]
You don't have to delete anything - it's just a report.  You could email them or do whatever you want.

**Comment by scottcwilson** [comment]
This might be better as a plugin.  Closing.
