### ISSUE TITLE
Edit Account: fields are empty

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4210]
ZC158, PHP 8
Customers data does not pre-populate the form fields.
If ZC157 version of header is used, fields are populated.

**Comment by scottcwilson** [comment]
Confirmed.  Seems like the issue is 
includes/modules/pages/account_edit/header_php.php  line 21. 

```
$gender = $firstname = $lastname = $nick = $dob = $email_address = $telephone = $fax = $email_format = $customers_referral = '';
```

**Comment by drbyte** [comment]
> Seems like the issue is
> includes/modules/pages/account_edit/header_php.php line 21.
> 
> ```
> $gender = $firstname = $lastname = $nick = $dob = $email_address = $telephone = $fax = $email_format = $customers_referral = '';
> ```

That was added in https://github.com/zencart/zencart/commit/0ac7ebf3239e82a25ea2d138d26eda2787c2e1b9 to correct the issue reported by @torvista in https://github.com/zencart/zencart/issues/4192

**Comment by scottcwilson** [comment]
Should this just be 

```
$dob = ''; 
```
?

**Comment by drbyte** [comment]
I'm not sure I follow why that would be necessary.

The whole purpose of adding the long list of vars was so that *all* of them are initialized to blank, since 80% of the last year's code updates has been related to uninitialized vars.

Tell me: how is line 21 wiping out vars that are set to values on subsequent lines?

**Comment by scottcwilson** [comment]
html_output.php line 499.  The global value is used rather than the passed parameter in zen_draw_input_field().

**Comment by scottcwilson** [comment]
Haven't tested but could work: reset those variables around includes/modules/pages/account_edit/header_php.php line 178 after the $account query.

**Comment by drbyte** [comment]
I'll revert the prior fix, and fall back to only fixing $dob.
