### ISSUE TITLE
placeholder on select: tpl_modules_address_book_details.php

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4215]
ZC158
placeholder on a select is flagged as invalid html, is there a reason for placeholder here on the country dropdown?
https://github.com/zencart/zencart/blob/c51e8bc594e49f4da5c904f86d9aa8fb8c5ed593/includes/templates/template_default/templates/tpl_modules_address_book_details.php#L100-L102

**Comment by proseLA** [comment]
NO!  there is no good reason.

good catch.  i would pull it out.  `placeholder` only valid for `input` and `textarea`.  Not sure how a suggestion could pop up on a pulldown.

**Comment by drbyte** [comment]
Closed in #4225
