### ISSUE TITLE
Left over debug code ??

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#4226]
@torvista 
https://github.com/zencart/zencart/blob/d87bc5b3ace80d80d6365a95d975683bddcd83f1/includes/templates/template_default/templates/tpl_modules_address_book_details.php#L2

**Comment by torvista** [comment]
Yes, my mistake, but I did remove it when it was pointed out....a bit of push-pull confusion on my part I expect.

**Comment by drbyte** [comment]
Closed in #4227
