### ISSUE TITLE
[157] PHP parse error on PHP 5.6

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4228]
**Describe the bug**
The zc157 family is supposed to run on PHP 5.6, but when accessing the admin I'm receiving (after setting STRICT_ERROR_REPORTING to true) the following:
```
 Parse error: syntax error, unexpected ':', expecting '{' in C:\xampp\htdocs\zc157a_bs4\includes\functions\php_polyfills.php on line 14 
```

**Version**
Zen Cart version: zc157c (current fileset)
PHP version: 5.6

**To Reproduce**
Steps to reproduce/demonstrate the behavior:

With PHP 5.6 in use, attempt to access the site's admin.

**Expected behavior**
The admin screen would be displayed

**Debug/Error Logs**
See above.

**Additional context**
The error arises due to the `bool` return hint on the `array_is_list` function declaration.  (update) removing the `: bool` from the function declaration corrects the issue.
```php
if (!function_exists('array_is_list')) {
    function array_is_list(array $array): bool
    {
        if ([] === $array) {
            return true;
        }

        $nextKey = -1;

        foreach ($array as $k => $v) {
            if ($k !== ++$nextKey) {
                return false;
            }
        }

        return true;
    }
}
```

**Comment by drbyte** [comment]
You are right. Fixed in https://github.com/zencart/zencart/commit/cc97e971f07fc18371e0e85af9fd0965dc30f6c4
