### ISSUE TITLE
Some password managers break Place Order in 1.5.7+

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4229]
**Describe the bug**
When you use a password manager, it sometimes replaces the customer's email in the email address box with a stored email, thus breaking place order.

**Version**
Zen Cart version:  157
PHP version: 7.3

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Admin >Customers > Customers > select customer
2. Press Place Order
3. Observe that the customer's email is not filled in; rather, your own cart email is in the email address field.

We could fix this by using a different name and ID on the login page when Place Order is being performed.

**Comment by drbyte** [comment]
To clarify: 
- ZC is filling in the email field correctly, meaning the browser does NOT have a blank email address field
- and then the browser (or password manager) is aggressively replacing the email with a remembered one without the user invoking the password manager?

**Comment by drbyte** [comment]
> We could fix this by using a different name and ID on the login page when Place Order is being performed.

Perhaps, but that's actually extremely complex, requiring architectural changes I don't want us to do.

**Comment by scottcwilson** [comment]
> To clarify:
> 
> * ZC is filling in the email field correctly, meaning the browser does NOT have a blank email address field
> * and then the browser (or password manager) is aggressively replacing the email with a remembered one without the user invoking the password manager?

Correct.

**Comment by drbyte** [comment]
Which password managers are doing this?

**Comment by drbyte** [comment]
I think it's on the password manager to behave properly.

No plans to address this.
