### ISSUE TITLE
repeated use of NOTIFY_HEADER_START_POPUP_IMAGES_ADDITIONAL

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4232]
At the start of these two files I note these notifiers are named the same...is that correct?
The closing notifiers at the end of the files are named differently.

https://github.com/zencart/zencart/blob/fadade0e55e79f00bab24826c546123327345d07/includes/modules/pages/popup_image/header_php.php#L16

https://github.com/zencart/zencart/blob/fadade0e55e79f00bab24826c546123327345d07/includes/modules/pages/popup_image_additional/header_php.php#L11

**Comment by mc12345678** [comment]
To save anyone else from having to do the initial research. As far as on github, that (those?) notifiers were part of the initial load of Zen Cart to github.  I have not researched further back to see why/when they were each/both added to have the same notifier name.

**Comment by drbyte** [comment]
Inconsistency is noted. Changing it may do more harm than good.

What business problem is this situation causing?

**Comment by torvista** [comment]
It's not causing me any problem, it just seemed incorrect.

**Comment by drbyte** [comment]
> Changing it may do more harm than good.

Given it's been like this "forever"-ish, as mc12345678 pointed out, I wonder if multiple plugins have built dependency upon the present naming; thus changing it would break those?

I'd entertain a change if someone were to audit image-related plugins to check for the use of this notifier to see whether altering it would be problematic.

**Comment by lat9** [comment]
> 
> 
> > Changing it may do more harm than good.
> 
> Given it's been like this "forever"-ish, as mc12345678 pointed out, I wonder if multiple plugins have built dependency upon the present naming; thus changing it would break those?
> 
> I'd entertain a change if someone were to audit image-related plugins to check for the use of this notifier to see whether altering it would be problematic.

Just checked Image Handler; it's not used there.
