### ISSUE TITLE
[Feature] Reduce likelihood of Password Forgotten being marked as spam

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4244]
The documentation https://docs.zen-cart.com/user/email/advanced_email_troubleshooting/#encoding-and-character-sets states: 

> It is inevitable and unfortunate that certain short emails, such as ‘password forgotten’, especially when sent as HTML emails, appear to mail-server Spam filters as just an image (the logo) and a small amount of text, which they regard as a flag for potential Spam mail.

What if we force password forgotten to be sent as plain text?  Or, what if we increase the amount of content in password forgotten - perhaps with information on new products, perhaps with just plain text.

**Comment by barco57** [comment]
doesn't sending "information on new products" with a password reset email blur the line between transactional and marketing email?
I have found stripping all of the disclaimers from the transactional emails improves the deliverability of those emails.

**Comment by drbyte** [comment]
> I have found stripping all of the disclaimers from the transactional emails improves the deliverability of those emails.

Ditto. That's why we stripped those out of Zen Cart.

**Comment by drbyte** [comment]
> Or, what if we increase the amount of content in password forgotten

Maybe.

> perhaps with information on new products, perhaps with just plain text.

No.

> What if we force password forgotten to be sent as plain text? 

That could be explored.
Simple test:
`/includes/modules/pages/password_forgotten/header_php.php` contains a call to `zen_mail()` and passes `$html_msg` as a parameter. Replace `$html_msg` with `'none'`: that should tell it to use text-only mode.

Then see whether spam rates change.

**Comment by scottcwilson** [comment]
Clarification: I think this only works in Zen Cart 1.5.7, right?  In 1.5.6 we don't check

```
if (is_array($block)) {
```
before setting parts of the array.

**Comment by drbyte** [comment]
Ya, wrapping in that check would certainly prevent warnings like `Illegal string offset` (although it will still work with those warnings, but generate logs).

**Comment by scottcwilson** [comment]
Do you want to invite people on the forum who are having forgotten password deliverability issues to try this?
Do you want me to?

**Comment by drbyte** [comment]
> Do you want to invite people on the forum who are having forgotten password deliverability issues to try this?

I haven't seen any such posts recently.

**Comment by scottcwilson** [comment]
I was thinking more that we could create a new post and announce this as an experiment that people might want to join.

**Comment by scottcwilson** [comment]
See #4705

**Comment by scottcwilson** [comment]
I think what has been done so far in the two PRs referenced above is sufficient for now.
