### ISSUE TITLE
V1.5.7 Options Values Manager Quirk(s)

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#4256]
So, today is the first time that I've actually looked at the results of the changes made to the Options Values Manager. First, it drove me to investigate my database because when using the default Zen Cart demo data, I was basically presented with information indicating that the site had absolutely no option values associated with any option names... 😲 

Then, upon further investigation I see that ***ONLY*** the option values associated with the selected option name is presented. Ok, sort of get it, but there is no "show all" option. 
So then I go through the various option names to see what changes on the screen...
When I go to say the second option name of "Color", I see that at the bottom the selector is set for "Color" (auto-changed from the previous option name of "Amount")
Step through this for each and the selector at the bottom increments to match the selected option name until...
I get to "Line 1". At this point, the selector at the bottom reverts back to "Amount" and this is the first option name that is present that doesn't have any option values on it...
So open the dropdown, but... "Line 1" is not in the list.. Neither is "Line 2", "Line 3", "Line 4", "Logo Back", nor "Logo Front"... 

While I'm not a real fan of the new view and if I was looking for an option value by its name that I have to cycle through each option name (including whatever associated page(s)) instead of simply paging through a large list, this lack of consistency and/or missing message that it is "not possible" to add an option value or to not even show the option name in the first dropdown to begin with is confusing.

This appears to originate from the difference in these two code sections:
https://github.com/zencart/zencart/blob/ac93cffc22aee90a8872596e41335233d0afd13f/admin/options_values_manager.php#L641-L644
https://github.com/zencart/zencart/blob/ac93cffc22aee90a8872596e41335233d0afd13f/admin/options_values_manager.php#L828-L833

Shouldn't the items to be selected be determined one time and used/reused for the other selection list? Possibly to have either a list of items that don't support option values and therefore are not selectable or populate the first list with that information, or..or..or..

Then I notice that in options names manager, to add an option name, one now has to click a button to indicate the desire to insert an option name, populate the desired information and then select the button to submit. Then, after submitting, if another option name is desired to be entered that same "process" has to be followed again.. But in option values manager the ability to add an option value remains to simply start typing in the option value information to be associated with the selected option name and press insert... Process doesn't include an extra "I want to add an item selection" before actually typing information.

Then further comparing the two, the option names manager has removed the ability to hide/show the global tools. Now, if one desires to quickly access the insert option (which includes the above described Press "insert" button first step), it is not possible to simply press the end key on the keyboard, but instead scroll to some point possibly with the keyboard, possibly with a mouse, to bring this button into view, which when selected expands information down below the button (likely/possibly) requiring further scrolling to add data... Gripe? Yeah go ahead call it that. In the world of fast, easily accessible, simple, would think that there might have been some more push back on some of these changes or further ways to incorporated to back implement rather than to "create" work for those that are able to program. Really apologize for the frustration as some of this was also discussed in: https://github.com/zencart/zencart/issues/3201 to some extent and ignored and also not further duplicated. Maybe 1.5.8 is more consistent, will see..

Now also, in trying to ensure that in the above text I used the correct "names" for the two tools, I see other obvious/immediate differences. The button locations are on opposite sides of the screen. Intentional? Maybe, considering that both appear so similar, annoying? Definitely. Did I miss the "early boat" on being able to make comment? Yup, definitely. That's what happens while working on other things.

**Comment by torvista** [comment]
I'm guilty of the major changes to name manager, and I think Zen4All for values manager, so no coordination there.
Inevitably each will code as they feel appropriate, so the community input is essential to point out out these details.
I assume others check the useabilty before they are merged...but if everyone assumes that, then almost no-one checks them!!

> Maybe 1.5.8 is more consistent

Don't think so.
