### ISSUE TITLE
157c Breadcrumb link contains extra trailing slash for Home link 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4266]
Introduced in 1.5.7c, applies to stores in subfolders.  
Breadcrumb link on product info page for Home is `http://localhost:8888/my_store//` but should be `http://localhost:8888/my_store/`

Worked correctly in 1.5.7b.

**Comment by simon1066** [comment]
I found it also applies to a store not in subfolder. Not sure if you've seen it but was raised, and solved, here:

[https://www.zen-cart.com/showthread.php?227863-Double-slash-in-breadcrumb-home-link-v1-5-7c](url)

**Comment by scottcwilson** [comment]
Closed via https://github.com/zencart/zencart/commit/b2887b442fcf9639eeb2ad808055eaf277c13117
