### ISSUE TITLE
Products viewed report: date lost when navigating pagination links

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#4268]
When selecting a specific date range, page 1 shows things fine.
But navigating to page 2 the date range switches back to defaults. So does clicking back to page 1.

Reported in: https://www.zen-cart.com/showthread.php?227899-Products-viewed-report-date-lost-when-navigating-pagination-links

Cause: it seems we are losing the post vars when we hit the paginator, as it is doing a GET request. 
Additional factor: the split page results is coming up with a different result set than the raw SQL. 

**Version**
Zen Cart version: v1.5.7

**To Reproduce**
For example, today is 3/31/2021. When I open "products viewed' section, it will show start date of 03/01/2021 and end date of 3/31/2021. The data displayed below seems correct. But if I change the start date to a different number, like 03/15/2021, I notice the data in page 1 will be changed, which is correct. If I go to page 2, the data will be changed back to 03/01/2021 to 3/31/2021. The start date showing on the top will be changed back 03/01/2021 as well. If I go to page 1 then, the data will be changed back to the default date range (03/01/2021 to 3/31/2021).

**Comment by scottcwilson** [comment]
This has been fixed in 1.5.8.
