### ISSUE TITLE
Plugin Manager: Fatal error:  Uncaught TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback,

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4270]
ZC158, php8.03
Admin->Plugin Manager, creates debug

Error shown as image to highlight double slash in filepath, if relevant.

![Clipboard02](https://user-images.githubusercontent.com/4391026/113394466-98097200-9398-11eb-8750-e313668ccab5.gif)

**Comment by drbyte** [comment]
@zcwilt this is because no `$viewFactoryResolver` is set, which requires an instance of `\Illuminate\Contracts\View\Factory`, and we're not using `illuminate/view`.

**Comment by torvista** [comment]
I would like to be porting things to this plugin architecture, is this bug very complicated to resolve?

**Comment by zcwilt** [comment]
The problem is related to displaying pagination links via Laravel (as we are using that to get the result set) 
Working on a fix at the moment
