### ISSUE TITLE
Should we add a config for SESSION_TIMEOUT_CATALOG

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4273]
We have one for admin, of course - wonder if we ought to have one for storefront?  This variable, if set, is referenced in `includes/functions/sessions.php`.

**Comment by drbyte** [comment]
Why?
What's the business case for doing this?
What percentage of users would need this?

**Comment by scottcwilson** [comment]
This provides a lightweight way of doing "keep cart" type functionality without needing to change code.

**Comment by lat9** [comment]
Perhaps this could be a 'soft' configuration setting, i.e. via an extra_datafiles `define` to provide the override instead of yet-another real configuration setting?

**Comment by scottcwilson** [comment]
That's what people do now, but this means it's out of reach for storeowners that don't have the skills to do this.

**Comment by lat9** [comment]
The session-related stuff is confusing enough to "storeowners that don't have the skills", IMO.

**Comment by scottcwilson** [comment]
I quite agree for the others, but this one is trival.  I would even put it in Configuration > My Store to make it more visible.

**Comment by drbyte** [comment]
The default PHP configuration for session length, which is rarely touched, is 24 minutes.
Thus an idle browser will clear itself after 24 min of non-use.
Abandoned PCs in public environments will be safe after 24 min of non-use.
Abandoned back-office PCs will be safe after 24 min of non-use. (But let's not sidetrack about Admin, cuz it has legitimate security matters, and is already handled separately).

What new session length are you contemplating recommending to storeowners who want a fake "keep cart" feature by extending the session length? 2 hours? 24 hours? 4 weeks? 365 days?

**Comment by scottcwilson** [comment]
I'd let them decide.  But I'm kinda partial to "until the end of time."

**Comment by drbyte** [comment]
I don't think the session cookie should be the determiner. That's a weak bandage.

What's the real problem we're trying to solve here?
If it's the convenience of a not-logged-in shopper dropping in and out of the store without ever purchasing, then a basket-contents cookie specific to their browser should be used instead.

Or is it something else we're trying to solve?

**Comment by scottcwilson** [comment]
Correct - just make it convenient for people to shop slowly.
