### ISSUE TITLE
contact_us: name and email_address not sticky

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4279]
ZC158
They are set to empty on all page loads...
https://github.com/zencart/zencart/blob/35dc5cbc67b99851217a12e580c6130f7b67fd63/includes/modules/pages/contact_us/header_php.php#L118-L119

is there any reason they cannot be sticky as per telephone and enquiry?

It's annoying on failure of error checks such as a failed reCaptcha, which is not caught by the browser validation.

**Comment by mc12345678** [comment]
Sorry... 

If ZC 1.5.8 is PHP 7.x+ only, then may recommend

````php
$email_address = $email_address ?? '';
$name = $name ?? '';
````
Otherwise:
````php
$email_address = isset($email_address) ? $email_address : '';
$name = isset($name) ? $name : '';
````
The set to empty was to eliminate notices upon first accessing the page and did not get "updated" to reflect load/reload of the page where the "problem" was something other than those fields being empty upon submission.
