### ISSUE TITLE
ZC158 Admin: Handling of missing/undefined images

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4282]
Bit of a rabbit hole....

Admin, edit a product with no category image and you get a note where the image would be: "IMAGE FILE IS MISSING".
Being in uppercase, this shouts "error" at me and so I take it to mean the "the file that should be here is missing/is not found": it's not missing, it is just not defined.

So, looking at this and function zen_info_image that creates this, encourages me to modify it to produce two messages: one for "not defined"/ok and another for "missing"/NOT ok. 

But then, function zen_info_image uses the **admin** version of function zen_image which has no error-checking/is very basic, whereas the **shopfront** function zen_image **does** have some stuff for error checking.

Also function zen_info_image also has a note to be deprecated which I don't understand
https://github.com/zencart/zencart/blob/35dc5cbc67b99851217a12e580c6130f7b67fd63/admin/includes/functions/general.php#L11

So the question is, prior to making any changes to this, 

is there a plan for function zen_info_image to be dropped / admin zen_image to be dropped / shopfront zen_image to be used?

**Comment by drbyte** [comment]
> Also function zen_info_image also has a note to be deprecated which I don't understand

The comment is in relation to the function having been used in the past to generate a 3px border or HR in various places, usually in old table-based layouts. The comment reflects the intention to stop allowing that.

**Comment by scottcwilson** [comment]
@torvista Please close.

**Comment by torvista** [comment]
When no image is defined, this function still returns a misleading "Image Missing" message instead of "Image Undefined".

**Comment by scottcwilson** [comment]
The current message is fine.  We really don't need changes in this area.
