### ISSUE TITLE
ZC158: PHP Notices: Undefined offset: 1 in paypal_curl.php and paypalwpp due to timeout?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4294]
Just including them all as I suspect they can be cured by one fix?
Transaction log is below.
> 
> #1  paypal_curl->_parseNameValueList() called at [CATALOG/includes/modules/payment/paypal/paypal_curl.php:592]
> #2  paypal_curl->_logTransaction() called at [CATALOG/includes/modules/payment/paypal/paypal_curl.php:472]
> #3  paypal_curl->_request() called at [CATALOG/includes/modules/payment/paypal/paypal_curl.php:198]
> #4  paypal_curl->DoExpressCheckoutPayment() called at [CATALOG/includes/modules/payment/paypalwpp.php:560]
> #5  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #6  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #7  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #8  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined offset: 1 in /.../includes/modules/payment/paypal/paypal_curl.php on line 576.
> 
> #1  paypal_curl->_logTransaction() called at [CATALOG/includes/modules/payment/paypal/paypal_curl.php:472]
> #2  paypal_curl->_request() called at [CATALOG/includes/modules/payment/paypal/paypal_curl.php:198]
> #3  paypal_curl->DoExpressCheckoutPayment() called at [CATALOG/includes/modules/payment/paypalwpp.php:560]
> #4  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #5  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #6  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #7  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined index: ACK in /.../includes/modules/payment/paypal/paypal_curl.php on line 618.
> 
> #1  paypal_curl->_parseNameValueList() called at [CATALOG/includes/modules/payment/paypal/paypal_curl.php:475]
> #2  paypal_curl->_request() called at [CATALOG/includes/modules/payment/paypal/paypal_curl.php:198]
> #3  paypal_curl->DoExpressCheckoutPayment() called at [CATALOG/includes/modules/payment/paypalwpp.php:560]
> #4  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #5  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #6  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #7  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined offset: 1 in /.../includes/modules/payment/paypal/paypal_curl.php on line 576.
> 
> #1  paypalwpp->_errorHandler() called at [CATALOG/includes/modules/payment/paypalwpp.php:567]
> #2  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #3  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #4  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #5  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined index: L_ERRORCODE0 in /.../includes/modules/payment/paypalwpp.php on line 3186.
> 
> #1  paypalwpp->_errorHandler() called at [CATALOG/includes/modules/payment/paypalwpp.php:567]
> #2  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #3  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #4  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #5  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined index: L_ERRORCODE0 in /.../includes/modules/payment/paypalwpp.php on line 3186.
> 
> #1  paypalwpp->_errorHandler() called at [CATALOG/includes/modules/payment/paypalwpp.php:567]
> #2  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #3  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #4  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #5  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined index: L_ERRORCODE0 in /.../includes/modules/payment/paypalwpp.php on line 3194.
> 
> #1  paypalwpp->_errorHandler() called at [CATALOG/includes/modules/payment/paypalwpp.php:567]
> #2  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #3  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #4  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #5  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined index: RESULT in /.../includes/modules/payment/paypalwpp.php on line 3194.
> 
> #1  paypalwpp->_errorHandler() called at [CATALOG/includes/modules/payment/paypalwpp.php:567]
> #2  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #3  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #4  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #5  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined index: L_ERRORCODE0 in /.../includes/modules/payment/paypalwpp.php on line 3195.
> 
> #1  paypalwpp->_errorHandler() called at [CATALOG/includes/modules/payment/paypalwpp.php:567]
> #2  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #3  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #4  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #5  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined index: L_ERRORCODE0 in /.../includes/modules/payment/paypalwpp.php on line 3196.
> 
> #1  paypalwpp->_errorHandler() called at [CATALOG/includes/modules/payment/paypalwpp.php:567]
> #2  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #3  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #4  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #5  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined index: L_ERRORCODE0 in /.../includes/modules/payment/paypalwpp.php on line 3197.
> 
> #1  paypalwpp->_errorHandler() called at [CATALOG/includes/modules/payment/paypalwpp.php:567]
> #2  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #3  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #4  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #5  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined index: L_SHORTMESSAGE0 in /.../includes/modules/payment/paypalwpp.php on line 3199.
> 
> #1  paypalwpp->_errorHandler() called at [CATALOG/includes/modules/payment/paypalwpp.php:567]
> #2  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #3  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #4  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #5  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined index: L_LONGMESSAGE0 in /.../includes/modules/payment/paypalwpp.php on line 3199.
> 
> #1  paypalwpp->_errorHandler() called at [CATALOG/includes/modules/payment/paypalwpp.php:567]
> #2  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #3  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #4  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #5  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined index: RESULT in /.../includes/modules/payment/paypalwpp.php on line 3199.
> 
> #1  paypalwpp->_errorHandler() called at [CATALOG/includes/modules/payment/paypalwpp.php:567]
> #2  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #3  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #4  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #5  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined index: L_ERRORCODE0 in /.../includes/modules/payment/paypalwpp.php on line 3200.
> 
> #1  paypalwpp->_errorHandler() called at [CATALOG/includes/modules/payment/paypalwpp.php:567]
> #2  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #3  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #4  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #5  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined index: L_SHORTMESSAGE0 in /.../includes/modules/payment/paypalwpp.php on line 3200.
> 
> #1  paypalwpp->_errorHandler() called at [CATALOG/includes/modules/payment/paypalwpp.php:567]
> #2  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #3  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #4  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #5  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined index: L_LONGMESSAGE0 in /.../includes/modules/payment/paypalwpp.php on line 3200.
> 
> #1  paypalwpp->_errorHandler() called at [CATALOG/includes/modules/payment/paypalwpp.php:567]
> #2  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #3  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #4  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #5  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined index: L_ERRORCODE1 in /.../includes/modules/payment/paypalwpp.php on line 3200.
> 
> #1  paypalwpp->_errorHandler() called at [CATALOG/includes/modules/payment/paypalwpp.php:567]
> #2  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #3  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #4  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #5  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined index: L_SHORTMESSAGE1 in /.../includes/modules/payment/paypalwpp.php on line 3200.
> 
> #1  paypalwpp->_errorHandler() called at [CATALOG/includes/modules/payment/paypalwpp.php:567]
> #2  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #3  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #4  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #5  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined index: L_LONGMESSAGE1 in /.../includes/modules/payment/paypalwpp.php on line 3200.
> 
> #1  paypalwpp->_errorHandler() called at [CATALOG/includes/modules/payment/paypalwpp.php:567]
> #2  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #3  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #4  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #5  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined index: L_ERRORCODE2 in /.../includes/modules/payment/paypalwpp.php on line 3200.
> 
> #1  paypalwpp->_errorHandler() called at [CATALOG/includes/modules/payment/paypalwpp.php:567]
> #2  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #3  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #4  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #5  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined index: L_SHORTMESSAGE2 in /.../includes/modules/payment/paypalwpp.php on line 3200.
> 
> #1  paypalwpp->_errorHandler() called at [CATALOG/includes/modules/payment/paypalwpp.php:567]
> #2  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #3  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #4  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #5  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined index: L_LONGMESSAGE2 in /.../includes/modules/payment/paypalwpp.php on line 3200.
> 
> #1  paypalwpp->terminateEC() called at [CATALOG/includes/modules/payment/paypalwpp.php:3203]
> #2  paypalwpp->_errorHandler() called at [CATALOG/includes/modules/payment/paypalwpp.php:567]
> #3  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #4  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #5  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #6  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined index: paypal_ec_token in /.../includes/modules/payment/paypalwpp.php on line 3026.
> 
> #1  paypalwpp->terminateEC() called at [CATALOG/includes/modules/payment/paypalwpp.php:3203]
> #2  paypalwpp->_errorHandler() called at [CATALOG/includes/modules/payment/paypalwpp.php:567]
> #3  paypalwpp->before_process() called at [CATALOG/includes/classes/payment.php:252]
> #4  payment->before_process() called at [CATALOG/includes/modules/checkout_process.php:91]
> #5  require(CATALOG/includes/modules/checkout_process.php) called at [CATALOG/includes/modules/pages/checkout_process/header_php.php:14]
> #6  require(CATALOG/includes/modules/pages/checkout_process/header_php.php) called at [CATALOG/index.php:35]
> --> PHP Notice: Undefined index: paypal_ec_markflow in /.../includes/modules/payment/paypalwpp.php on line 3038.
> 

> 2021-04-15 09:42:12
> -------------------
> (live transaction) --> https://api-3t.paypal.com/nvp
> Request Headers: 
> Array
> (
>     [0] => Content-Type: text/namevalue
>     [1] => X-VPS-Timeout: 90
>     [2] => X-VPS-VIT-Client-Type: PHP/cURL
>     [3] => X-VPS-VIT-Integration-Product: PHP::Zen Cart(R) - PayPal/NVP
>     [4] => X-VPS-VIT-Integration-Version: 1.5.8
> )
> 
> 
> Request Parameters: {DoExpressCheckoutPayment} 
> Array
> (
>     [PAYMENTREQUEST_0_AMT] => 31.11
>     [PAYMENTREQUEST_0_ITEMAMT] => 26.11
>     [PAYMENTREQUEST_0_SHIPPINGAMT] => 5
>     [L_PAYMENTREQUEST_0_NAME0] => Todos los artículos en el carro (ver los detalles en la tienda y en el comprobante de la tienda).
>     [L_PAYMENTREQUEST_0_AMT0] => 26.11
>     [PAYMENTREQUEST_0_PAYMENTACTION] => Sale
>     [ALLOWEDPAYMENTMETHOD] => InstantPaymentOnly
>     [PAYMENTREQUEST_0_SHIPTONAME] => *CUSTOMER NAME*
>     [PAYMENTREQUEST_0_SHIPTOSTREET] => Roibeira
>     [PAYMENTREQUEST_0_SHIPTOSTREET2] => Betanzos
>     [PAYMENTREQUEST_0_SHIPTOCITY] => Betanzos
>     [PAYMENTREQUEST_0_SHIPTOSTATE] => A Coruña
>     [PAYMENTREQUEST_0_SHIPTOZIP] => 15300
>     [PAYMENTREQUEST_0_SHIPTOCOUNTRYCODE] => ES
>     [BUTTONSOURCE] => ZenCart-EC_us
>     [RETURNFMFDETAILS] => 0
>     [PAYMENTREQUEST_0_CUSTOM] => EC-10173-123456789
>     [PAYMENTREQUEST_0_INVNUM] => 10173-123456789-[STORE NAME]
>     [PAYMENTREQUEST_0_CURRENCYCODE] => EUR
>     [TOKEN] => EC-987654321
>     [PAYERID] => ABCDEFGH
>     [NOTIFYURL] => https://STORENAME/ipn_main_handler.php
>     [METHOD] => DoExpressCheckoutPayment
>     [USER] => PAYPAL API USERNAME
>     [PWD] => ****************
>     [VERSION] => 124.0
>     [SIGNATURE] => ****************************************************St6K
> )
> 
> 
> Response: 
> Array
> (
>     [] => 
>     [CURL_ERRORS] => (28) Connection timed out after 10000 milliseconds
> )
> 
> (28) Connection timed out after 10000 milliseconds
> Array
> (
>     [url] => https://api-3t.paypal.com/nvp
>     [content_type] => 
>     [http_code] => 0
>     [header_size] => 0
>     [request_size] => 0
>     [filetime] => -1
>     [ssl_verify_result] => 0
>     [redirect_count] => 0
>     [total_time] => 10.000442
>     [namelookup_time] => 0.000768
>     [connect_time] => 0
>     [pretransfer_time] => 0
>     [size_upload] => 0
>     [size_download] => 0
>     [speed_download] => 0
>     [speed_upload] => 0
>     [download_content_length] => -1
>     [upload_content_length] => -1
>     [starttransfer_time] => 0
>     [redirect_time] => 0
>     [redirect_url] => 
>     [primary_ip] => 
>     [certinfo] => Array
>         (
>         )
> 
>     [primary_port] => 0
>     [local_ip] => 
>     [local_port] => 0
>     [http_version] => 0
>     [protocol] => 0
>     [ssl_verifyresult] => 0
>     [scheme] => 
>     [appconnect_time_us] => 0
>     [connect_time_us] => 0
>     [namelookup_time_us] => 768
>     [pretransfer_time_us] => 0
>     [redirect_time_us] => 0
>     [starttransfer_time_us] => 0
>     [total_time_us] => 10000442
> )
> 
> 
> DoExpressCheckoutPayment, Elapsed: 10001ms -- Failed
> (28) Connection timed out after 10000 milliseconds
> Array
> (
>     [url] => https://api-3t.paypal.com/nvp
>     [content_type] => 
>     [http_code] => 0
>     [header_size] => 0
>     [request_size] => 0
>     [filetime] => -1
>     [ssl_verify_result] => 0
>     [redirect_count] => 0
>     [total_time] => 10.000442
>     [namelookup_time] => 0.000768
>     [connect_time] => 0
>     [pretransfer_time] => 0
>     [size_upload] => 0
>     [size_download] => 0
>     [speed_download] => 0
>     [speed_upload] => 0
>     [download_content_length] => -1
>     [upload_content_length] => -1
>     [starttransfer_time] => 0
>     [redirect_time] => 0
>     [redirect_url] => 
>     [primary_ip] => 
>     [certinfo] => Array
>         (
>         )
> 
>     [primary_port] => 0
>     [local_ip] => 
>     [local_port] => 0
>     [http_version] => 0
>     [protocol] => 0
>     [ssl_verifyresult] => 0
>     [scheme] => 
>     [appconnect_time_us] => 0
>     [connect_time_us] => 0
>     [namelookup_time_us] => 768
>     [pretransfer_time_us] => 0
>     [redirect_time_us] => 0
>     [starttransfer_time_us] => 0
>     [total_time_us] => 10000442
> )
>

**Comment by scottcwilson** [comment]
These logs reference
includes/modules/payment/paypalwpp.php on line 3186.
includes/modules/payment/paypalwpp.php on line 3194.

those lines don't exist in 1.5.7 or 1.5.8.

What code version are you running here?

**Comment by scottcwilson** [comment]
Fixing this:
--> PHP Notice: Undefined index: ACK in /.../includes/modules/payment/paypal/paypal_curl.php on line 618.

is just a matter of checking if it's set before referencing it.

**Comment by torvista** [comment]
>those lines don't exist in 1.5.7 or 1.5.8.

Sorry, I forgot I had Ceon Surcharges stuff in there. Using 158 as base.

3186
> if ($response['L_ERRORCODE0'] == 10422 || $response['L_ERRORCODE0'] == 10486) {

3194
> $errorNum = urldecode($response['L_ERRORCODE0'] . $response['RESULT']);

**Comment by scottcwilson** [comment]
1.5.8 has not been released, and you shouldn't be using it on a live store.
The 'L_ERRORCODE0' references are bugs in Ceon's code; you can fix them just by checking if this array entry is set.

**Comment by torvista** [comment]
>The 'L_ERRORCODE0' references are bugs in Ceon's code

I don't see why. I think all of this is a communication issue and so there is no response array...implying there should be a check to deal with it and prevent all the "errors" at the same time.

>and you shouldn't be using it on a live store.

Yes of course, I know that but I've been following it long enough to take the informed risk.
I got fed up with comparing 156-157-158 and having to double investigate if an issue I had was already fixed, before doing a bug report/PR against 158. I just don't have the time and my frankenstore was getting too complicated with mods and future fixes. Now it's much easier for me and I don't push anything to my shop before it's thoroughly checked.

**Comment by scottcwilson** [comment]
When I say "bugs in Ceon's code," I mean that 

if ($response['L_ERRORCODE0'] == 10422 || $response['L_ERRORCODE0'] == 10486) {

should be 

if (!empty($response['L_ERRORCODE0']) && ($response['L_ERRORCODE0'] == 10422 || $response['L_ERRORCODE0'] == 10486)) {

**Comment by torvista** [comment]
Why is this to do with CEON code?
https://github.com/zencart/zencart/blob/35dc5cbc67b99851217a12e580c6130f7b67fd63/includes/modules/payment/paypalwpp.php#L2992

**Comment by lat9** [comment]
Might I suggest that rather than adding various `!empty($response['L_ERRORCODE0')` to that and various other checks that, prior to the switch
https://github.com/zencart/zencart/blob/35dc5cbc67b99851217a12e580c6130f7b67fd63/includes/modules/payment/paypalwpp.php#L2941
... a clause similar to be added
```php
if (empty($response['L_ERRORCODE0'])) {
    $response['L_ERRORCODE0'] = '';
}
```
