### ISSUE TITLE
ZC158:shopfront, php notices on not found product id

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4295]
ZC158, php8, with demo products.

eg:
.for 
....zencart-158/index.php?main_page=redirect&products_id=1575

The product is (correctly) not found, but with these debugs:

> [20-Apr-2021 14:01:40 UTC] Request URI: /zencart-158/index.php?main_page=product_info&products_id=1575, IP address: 127.0.0.1
> #1  zen_get_products_base_price() called at [...\zencart-158\includes\modules\products_quantity_discounts.php:62]
> #2  require(...\zencart-158\includes\modules\products_quantity_discounts.php) called at [...\zencart-158\includes\modules\pages\product_info\main_template_vars.php:148]
> #3  require(...\zencart-158\includes\modules\pages\product_info\main_template_vars.php) called at [...\zencart-158\includes\templates\responsive_classic\common\tpl_main_page.php:178]
> #4  require(...\zencart-158\includes\templates\responsive_classic\common\tpl_main_page.php) called at [...\zencart-158\index.php:94]
> --> PHP Notice: Undefined index: products_price in ...\zencart-158\includes\functions\functions_prices.php on line 421.
> 
> [20-Apr-2021 14:01:40 UTC] Request URI: /zencart-158/index.php?main_page=product_info&products_id=1575, IP address: 127.0.0.1
> #1  zen_get_products_base_price() called at [...\zencart-158\includes\modules\products_quantity_discounts.php:62]
> #2  require(...\zencart-158\includes\modules\products_quantity_discounts.php) called at [...\zencart-158\includes\modules\pages\product_info\main_template_vars.php:148]
> #3  require(...\zencart-158\includes\modules\pages\product_info\main_template_vars.php) called at [...\zencart-158\includes\templates\responsive_classic\common\tpl_main_page.php:178]
> #4  require(...\zencart-158\includes\templates\responsive_classic\common\tpl_main_page.php) called at [...\zencart-158\index.php:94]
> --> PHP Notice: Undefined index: products_priced_by_attribute in ...\zencart-158\includes\functions\functions_prices.php on line 423.

**Comment by scottcwilson** [comment]
seems like this has been fixed - can this ticket be closed?

**Comment by torvista** [comment]
yes
