### ISSUE TITLE
Place Order with COWOA

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4297]
Is there any appetite for a PR that integrates COWOA created accounts with the Place Order button?

**Comment by drbyte** [comment]
Since COWOA isn't as well supported anymore vs OPC, I'm not sure I see the appeal for this, as far as core code anyway.

What would the PR involve?

**Comment by scottcwilson** [comment]
I think it's probably a small change.  I might just write it up on the forum for those who are interested when I get to doing it.

**Comment by scottcwilson** [comment]
Hopefully one day we'll have one COWOA to rule them all. :)
