### ISSUE TITLE
zc158: Base class no longer provides getStaticObserver method

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4305]
The subject method, used by my [Watching Observers](https://github.com/lat9/watching_observers) plugin, has gone missing in zc158.  As such, that plugin no longer functions on that Zen Cart version.

Simply install that drop-in plugin on a zc158 installation and see the white-screen that results.

**Comment by scottcwilson** [comment]
@zcwilt Looks like this was done in 95345e02d3b99ec186c1f64ed91ffff2035df84a.
