### ISSUE TITLE
function zen_create_coupon_code, parameter length hinted as int, but SECURITY_CODE_LENGTH is string

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4317]
ZC158
https://github.com/zencart/zencart/blob/85873df88db6fcafbf70386f41ebef10da79847e/includes/functions/functions_gvcoupons.php#L77-L81

if casting SECURITY_CODE_LENGTH to int, maybe
 $length = (int)$length;
is redundant?

**Comment by drbyte** [comment]
Is PHP reporting a problem?
Or is it just your IDE that's making a suggestion?

**Comment by torvista** [comment]
I didn't get a problem with it, just an IDE red marker.

**Comment by scottcwilson** [comment]
Does casting fix this?

**Comment by proseLA** [comment]
@scottcwilson

IMO, i am not a fan of correcting code because someone's IDE reports a problem.  however, i see a couple of issues.  for testing:  

- i have tested under php 7.4, and 8.0
- create a file in the store root called test.php.  within that file, add the following code:
```
<?php
//    declare(strict_types=1);
    require('includes/application_top.php');

    echo __FILE__ . ':' . __LINE__ . '<br>';
    $test = zen_create_coupon_code();

    echo "-------->" . $test  . "<---------<br>";
    die(__FILE__ . ':' . __LINE__);
```
- now go that url, ie something line https://zcdev.com/test.php
- everything looks fine to me.
- now un-comment out the 1st line with the strict types.  you will now generate an error.
-  this line of code that steve has pointed out will always present a problem in its construction:
https://github.com/zencart/zencart/blob/85873df88db6fcafbf70386f41ebef10da79847e/includes/functions/functions_gvcoupons.php#L77
- if you type hint any method parmater as anything but a string, and use a default any ZC constant, that's a problem.  all zc configuration constants are strings, despite their values potentially looking like integers or boolean.
- how to approach solving this problem is a different story.  one could refactor all of the base ZC calls to cast to int on the call to the function.  i think that's ugly as we now have to refactor all calls to the function.  and i think it defeats the whole purpose of the default value.
- one could remove the type hints.
- an alternative solution could get more to some inherent ways ZC loads the config values.  which seems the most elegant solution for moving forward.  php could soon require all functions to have type hints.  removing them to solve this issue seems kicking the ball down the path.

**Comment by scottcwilson** [comment]
> IMO, i am not a fan of correcting code because someone's IDE reports a problem.  
As a rule I agree.  I want us to be spending time fixing actual bugs.  

> all zc configuration constants are strings, despite their values potentially looking like integers or boolean.
I don't think this is true anymore.  Look at `laravel/app/Models/Configuration.php` line 25 and how it handles group 2 and 3 items as integers.  Could we expand this to select values in other groups, such as SECURITY_CODE_LENGTH?

**Comment by proseLA** [comment]
interesting.  learn something new everyday......

i think these sort of problems will continue.  i have never been a fan of the config values always returning a string.  apparently 3 years ago, groups 2 and 3 went to integer.

as PHP evolves, i think more strict typing will become the rule.  i am not sure how best to handle it.  perhaps a new field in the configuration table to indicate type?  i'm just not sure how much refactoring you want to do.  for now, we could also keep an array of values that need to be cast to integer.  but i'm certainly open to other ideas...

it would be great (but painful) to move all of those boolean string values to return an actual boolean.  yet another massive refactor.

**Comment by scottcwilson** [comment]
> perhaps a new field in the configuration table to indicate type? 
someday maybe.  I think for now handling these oddballs on an ad hoc basis could be a good short term solution.

**Comment by torvista** [comment]
1) casting it to int solves this issue. Yes just a sticking plaster. But that's where the project is at currently.
2) I assume that what php introduces as optional now will become obligatory one day so the use of hints and strictness should be a criteria if a Development Roadmap is ever done.
3) Meanwhile, while the current flurry of belated housekeeping is most welcome/encouraging, there is no development: it is all just tinkering and maintenance. 
Until there is a plan, there can be no hope to progress/increase Zen Cart use/encourage more users to progress to contributing. Here we have been too few for far too long already and I have never seen anything being done to redress that decline.

In my opinion.

**Comment by proseLA** [comment]
> 1) casting it to int solves this issue. Yes just a sticking plaster. But that's where the project is at currently.
> 

without addressing the other issues you bring up at this time, casting what to int when?  could you be more specific with regards how you would propose solving this issue? ie some code where?

i'm sure the other stuff will get addressed in due time.

**Comment by torvista** [comment]
In the parameter list
`int $length = (int)SECURITY_CODE_LENGTH`

**Comment by torvista** [comment]
I think just removing the type hint is best, there are bigger fish to fry!

**Comment by proseLA** [comment]
> My bad, casting does not work in the parameter list. This is ok for php8, but not for php 7.4 `int|string $length = SECURITY_CODE_LENGTH`

in my testing, casting in the manner suggested fails as well in php 8.0.  from the php doc (https://tinyurl.com/yynbr4s8):

The default value must be a constant expression, not (for example) a variable, a class member or a function call.

**Comment by torvista** [comment]
> i am not a fan of correcting code because someone's IDE reports a problem

Not blindly no, but these are tools that go a long way to allow preventative code improvement instead of curing randomly-detected problems. Since most problems now are php-upgrade-related, pre-fixing detected potential issues when reviewing a file for some other issue seems prudent: fixing things before they are reported as broken.

Returning to the title of this issue, removing the type hint is enough to postpone the problem.
Otherwise this function, file and anything that uses it is marked as a serious error, hiding other potential errors too.

Disabling the inspection is not a solution. Removing the hint or fixing the underlying issue are the options.

**Comment by scottcwilson** [comment]
We could create a list of db values like this which are actually integer values, then have `laravel/app/Models/Configuration.php` handle them the same way it handles group 2 and 3 (i.e. make them integer).

**Comment by torvista** [comment]
I can't comment on that.

**Comment by proseLA** [comment]
> We could create a list of db values like this which are actually integer values, then have `laravel/app/Models/Configuration.php` handle them the same way it handles group 2 and 3 (i.e. make them integer).

not a fan.  if we want to create a list like this, we should modify the configuration table to add a field `configuration_type`.

data should be stored in the database, not in the code.

**Comment by scottcwilson** [comment]
That's a big change for a small number of affected items.  We can't change 'True' to true because it would break all the templates out there, so we'd only do the integer ones.  

I'm seeing the following variables that need conversion to Integer: 

```
SECURITY_CODE_LENGTH
SMALL_IMAGE_WIDTH, 
HEADING_IMAGE_WIDTH
SUBCATEGORY_IMAGE_WIDTH
IMAGE_SHOPPING_CART_WIDTH
CATEGORY_ICON_IMAGE_WIDTH
SUBCATEGORY_IMAGE_TOP_WIDTH
MEDIUM_IMAGE_WIDTH
IMAGE_PRODUCT_LISTING_WIDTH
IMAGE_PRODUCT_NEW_LISTING_WIDTH
IMAGE_PRODUCT_NEW_WIDTH
IMAGE_FEATURED_PRODUCTS_LISTING_WIDTH
IMAGE_PRODUCT_ALL_LISTING_WIDTH
PRODUCTS_LIST_PRICE_WIDTH
PREVIOUS_NEXT_IMAGE_WIDTH
SMALL_IMAGE_HEIGHT
HEADING_IMAGE_HEIGHT
SUBCATEGORY_IMAGE_HEIGHT
IMAGE_SHOPPING_CART_HEIGHT
CATEGORY_ICON_IMAGE_HEIGHT
SUBCATEGORY_IMAGE_TOP_HEIGHT
MEDIUM_IMAGE_HEIGHT
IMAGE_PRODUCT_LISTING_HEIGHT
IMAGE_PRODUCT_NEW_LISTING_HEIGHT
IMAGE_PRODUCT_NEW_HEIGHT
IMAGE_FEATURED_PRODUCTS_LISTING_HEIGHT
IMAGE_PRODUCT_ALL_LISTING_HEIGHT
PREVIOUS_NEXT_IMAGE_HEIGHT
```

**Comment by scottcwilson** [comment]
We've spent way too much time talking about something that doesn't affect any actual stores.  Steve, I will merge a PR that removes the type hint if you put it in, but please let's move on to real issues that need our attention.

**Comment by proseLA** [comment]
this has always been a problem.  laravel does it so much cleaner.  i hate all of the casting one needs to do because we have nver fixed the base legacy code.  look at the following code:

```
$configQuery = $db->Execute("select * from " . TABLE_CONFIGURATION);

     echo "-------->" . $configQuery->count() . "<---------<br>";

     $intCount = 0;
     foreach ($configQuery as $config) {
         if (is_numeric($config['configuration_value'])) {
             $intCount++;
         }
     }
    echo "-------->" . $intCount . "<---------<br>";
    die(__FILE__ . ':' . __LINE__);
```
results are:

707 total
373 numeric
