### ISSUE TITLE
problem in message stack

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#4318]
https://github.com/zencart/zencart/blob/89ffaf447f4bf05361983f367da31c1c5bf7f8ad/includes/classes/message_stack.php#L14-L17

zen_image is not loaded at this time.

**Comment by proseLA** [comment]
[06-May-2021 21:17:27 America/Los_Angeles] PHP Fatal error:  Uncaught Error: Call to undefined function zen_image() in /var/www/zcdev/includes/classes/message_stack.php:14
Stack trace:
#0 /var/www/zcdev/includes/autoload_func.php(27): include_once()
#1 /var/www/zcdev/includes/application_top.php(248): require('/var/www/zcdev/...')
#2 /var/www/zcdev/index.php(25): require('/var/www/zcdev/...')
#3 {main}
  thrown in /var/www/zcdev/includes/classes/message_stack.php on line 14

[06-May-2021 21:17:27 America/Los_Angeles] Request URI: /index.php, IP address: 192.168.14.74
--> PHP Fatal error: Uncaught Error: Call to undefined function zen_image() in /var/www/zcdev/includes/classes/message_stack.php:14
Stack trace:
#0 /var/www/zcdev/includes/autoload_func.php(27): include_once()
#1 /var/www/zcdev/includes/application_top.php(248): require('/var/www/zcdev/...')
#2 /var/www/zcdev/index.php(25): require('/var/www/zcdev/...')
#3 {main}
  thrown in /var/www/zcdev/includes/classes/message_stack.php on line 14.

**Comment by drbyte** [comment]
Serves me right for making late-night commits. 🤭

**Comment by drbyte** [comment]
Fixed via https://github.com/zencart/zencart/commit/8bf4f7711e8e34085dab351113909e73fe451f94
