### ISSUE TITLE
Aliasing of notifiers to transition to new observer class methods

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#4326]
Now that Zen Cart 1.5.7+ uses an observer method name style of `notify_lower_case_notifier_name` or `notifier_lower_case_notifier_name`, I've realized that I have notifiers in plugins that *do not* start with either the word `NOTIFY` or `NOTIFIER`. Without the notifier beginning with either of these two words, the new lower case notifier name method will not fire.  I would like to in some sensical way move towards redefining the notifiers with minimal discouragement to users that currently observe those notifiers.

1. I have considered simply changing the notifiers on the next update and indicating what the changes are. That's easiest for me.
2. (original plan) I have seen that in the observer process that there is a method: `eventIdHasAlias` that is used during execution to check for possible aliases; however, such an alias is identified by private variable array `observerAliases` (`array('OLD NOTIFIER' => 'NEW NOTIFIER MAPPING')`. This means that without modifying the associated class, it is not possible to override that value. The above method also is private, so unless an entire replacement class is incorporated in the plugin to override the observer process, the file itself would need to be modified. The file I see as applicable (for ZC 1.5.7) is `includes/classes/class.base.php`, but in Zen Cart 1.5.8 it appears to be `includes/classes/traits/NotifierManager.php`.
3. I have considered also placing both notifiers side-by-side (vertically really) which would execute one then the other, adding a note that the older notifier would be deprecated on the next revision for example. Easy for me, but potentially involves support interaction that could otherwise be addressed.
4. I have considered doing the replace and leaving a note to indicate what the older notifier was so that at least it would be searchable for those attempting to integrate their "older" code with the new notifier naming. Similar to easy for me in the first above, but also involves support to likely repetitively identify that the notifier was replaced.
5. I've considered doing nothing about the notifier naming and just using/dealing with the other two available options for method use in the observer class (`updateCamelCasedNotifierName`/`update`). Also relatively easy, but offers the perception that the code is "old" or not up to making changes that take advantage of the latest, blah blah blah...

Complication I primarily foresee with expanding the capability of an "outside" product providing its own alias type array includes random firing of events because of the renaming, "abuse" of holding over an alias that no longer applies to that plugin especially where two different plugins use the same naming for a given notifier.

Is/was there a plan to support this type of aliasing operation beyond the core code? Suggestions going forwards for making the either the changes to the notifiers within the plugin code or in some way through an access tool to the private variable?

**Comment by mc12345678** [comment]
For those reviewing this "issue", still welcome suggestion/input on what might be considered a good way forwards with addressing the rename of notifiers then. Agree that userland aliasing support *would/is* complicated. 

I don't really like the "leave it alone/do nothing" option and I know for certain that existing notifiers are being used.

Thanks for the feedback!

**Comment by lat9** [comment]
As an early-adopter of the Zen Cart notify/observe infrastructure, I'll note that going through my plugins to change notifier names to be now suitable will have a downward-cascading effect on other customizations that use those notifications.

**Comment by drbyte** [comment]
> As an early-adopter of the Zen Cart notify/observe infrastructure, I'll note that going through my plugins to change notifier names to be now suitable will have a downward-cascading effect on other customizations that use those notifications.

Since your observers almost all use only the original `update()` function combined with switch/case statements, they're largely unaffected by the new naming option added in v1.5.7. 
Granted, the reason the new naming was added was because you and others disliked losing the ability to use search to find the uses of the notifier, and the new naming allows for that when the naming convention is used.

**Comment by drbyte** [comment]
> The change was made with the intention of it becoming the primary way for plugins to operate, with the expectation that the old would be retired. The old has been retained solely for backward compatibility.

I should clarify. My statement was too strong. 
We have no intentions of deprecating or retiring the original `update()` or `updateCamelCasedName()` syntaxes anytime soon.
I more intended to convey: for new development where you use notifier/observer features, we recommend using the new syntax wherever possible.

**Comment by mc12345678** [comment]
> > The change was made with the intention of it becoming the primary way for plugins to operate, with the expectation that the old would be retired. The old has been retained solely for backward compatibility.
> >
> I should clarify. My statement was too strong.
> We have no intentions of deprecating or retiring the original `update()` or `updateCamelCasedName()` syntaxes anytime soon.
> I more intended to convey: for new development where you use notifier/observer features, we recommend using the new syntax wherever possible.

I wouldn't say that should beat yourself up about the original statement. 

As to use of the newer method, I would say I had two concepts in writing this "issue", to see where things stood about integrating what appeared to be a plan to broaden the ability to "transition" (although current use was to correct a spelling mistake) and to seek some assistance from those that review this area of development on ways considered appropriate/best for making that transition without necessarily going all out about it... Documentation in instructions, documentation in the forum, documentation in the code, step-by-step incorporation over versions that may take a long time to further incorporate and identification of deprecation, etc... while also not just ripping the band aide off. :)

**Comment by drbyte** [comment]
I recommend always using event-specific update() calls. And, since searchability is possible when using the `notify_` prefix I recommend using that approach.
All the approaches are [documented](https://docs.zen-cart.com/dev/code/notifiers/#event-specific-update-methods).

For plugins that must support older Zen Cart versions you can use the older syntax.
For new development, use the new syntax.

**Comment by mc12345678** [comment]
> I recommend always using event-specific update() calls. And, since searchability is possible when using the `notify_` prefix I recommend using that approach.
> All the approaches are [documented](https://docs.zen-cart.com/dev/code/notifiers/#event-specific-update-methods).
> 
> For plugins that must support older Zen Cart versions you can use the older syntax.
> For new development, use the new syntax.

Somewhat.  The use of the prefix `NOTIFY_` or `NOTIFIER_` wasn't previously, well, a standard... `EVENT_NAME` basically had been all that was considered necessary, so in development of other plugins and use of the `notify` method, an `EVENT_NAME` may have been chosen to be unique for the plugin, but without either prefix. 

I know for me that I have a number of reasons to use the more targeted event-specific update calls, but for the purpose of this thread the issue/desire is to make it most possible with minimal impact on all to change from the current `EVENT_NAME` that doesn't begin with either prefix to one that does and not significantly impact the work(s) of others. New development, sure, will use notifiers that begin with one of the two prefixes just have to clean up other code along the way.

**Comment by drbyte** [comment]
> The use of the prefix NOTIFY_ or NOTIFIER_ wasn't previously, well, a standard... EVENT_NAME basically had been all that was considered necessary, so in development of other plugins and use of the notify method, an EVENT_NAME may have been chosen to be unique for the plugin, but without either prefix.

Correct. The "notify_" prefix wasn't a requirement previously. But then y'all didn't like the implemented standard, so we added one. And you don't like that one either.

We were hesitant to just let "any" function name be allowed, but I suppose we could just skip the naming convention of starting with "notify_" or "notifier_", and lookup whether a public function exists for whatever the event name is and call that, before falling back to older syntaxes. Then the onus is entirely on you the plugin developer to ensure you don't use conflicting names or names that clash with PHP reserved words.

**Comment by scottcwilson** [comment]
Can this ticket be closed?  We have an aliasing mechanism for notifier renames: 
https://docs.zen-cart.com/dev/code/notifiers/#event-aliasing
