### ISSUE TITLE
Expansion of Language overrides for 8 files?

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#4327]
Was in the process of updating a site and had reviewed the code process for language overrides... Fortunately for pages (`main_page=`) there is a "convenient" process where first the templated language file is loaded if present and then the default version of the language file. Thus, if a template has modified a specific definition it is seen "first" and becomes the definition to be used, but if the template override file doesn't include a define that is in the default template, well it gets loaded "just-in-case" or to allow the template's files to be "smaller"...

From a generic perspective this was being followed and used so that the "new" template override file had just the changes from the original code. But then the `button_names.php` file in the template was modified, the page reloaded and woops, only the stated defines (different from or extra to the original) were presented.  A little more digging identified that at the end of the `includes/languages/english.php` file there are 8 files that are loaded in this case to ***only*** load the template override version if it exists otherwise the default version...

As a result, the templated version has to contain **ALL** of the defines and not just the overridden ones. While I suspect that this is some sort of osC carryover, what is the identified reason not to override the same way as is done for `require_languages.php` or what is the problem of doing something like that?

**Comment by drbyte** [comment]
Seems not to be an issue for v1.5.8
https://github.com/zencart/zencart/blob/b4462b7c40fa804c599051be6f73d3566606fea1/includes/languages/english.php#L597

**Comment by mc12345678** [comment]
Correct upon further inspection in ZC 1.5.8, the existing concept was moved into the ResourceLoaders area:
https://github.com/zencart/zencart/blob/b4462b7c40fa804c599051be6f73d3566606fea1/includes/classes/ResourceLoaders/CatalogFilesLanguageLoader.php#L53-L62

Which then loads:
https://github.com/zencart/zencart/blob/b4462b7c40fa804c599051be6f73d3566606fea1/includes/classes/ResourceLoaders/FilesLanguageLoader.php#L15-L22

Note that in the first code "snippet" the template overrides are loaded first and then the core files, at the end of that "grouping" is where the 8 files are loaded to which I was referring. Even if it isn't changed, I think that it would be good to have some reasoning behind why they are loaded the way they are.  Of course I was initially thinking of something like expediency or resources because those files are loaded on each and every page load not just when a specific page is loaded, but that's true with the main language file as well...

Main language loader:
https://github.com/zencart/zencart/blob/b4462b7c40fa804c599051be6f73d3566606fea1/includes/classes/ResourceLoaders/CatalogFilesLanguageLoader.php#L53-L62

**Comment by drbyte** [comment]
How big of an issue is this? 

I mean ... how often have people complained about this in the last 15 years?

**Comment by scottcwilson** [comment]
Also might not be an issue in the future depending on the direction taken for language file definitions.  Suggest we close this ticket.

**Comment by mc12345678** [comment]
> Also might not be an issue in the future depending on the direction taken for language file definitions. Suggest we close this ticket.

So a reason I brought this up was to encourage either identification as to why it is not different (doesn't respect the override modifies the core information perspective) or to encourage a change for these files.  Based on the response/evaluation thus far there does not appear to be a plan to modify the loading of these 8 files to where core items "missed" in the override are filled in by the core.

Now, on the other side, there may or likely is a reason to have/identify specific files to load regardless the core code. This code "snippet" does that and for a developer could be modified or used to support that operation. More than likely, if these 8 files were transitioned to the loading process of other template overrides, then this `loadExtraLanguageFiles` method would be posed for removal and that facility would be "lost" or need to be otherwise implemented where/when needed.

As to complaint specific about this area of code? At this time I can not specifically state that it has uniquely been identified as an area of issue, but I can see how it can contribute to the "problem" with upgrading for general users.  Those are individuals that may not know or realize that these files may cause problems. I can see though in myDebug logs that if a constant (or information being otherwise requested) is not present that in future PHP versions that an error will be thrown. At that point, while current systems place some "random" text on the screen, future versions may stop displaying any information.

Following that "train of thought", I have a program, upgrade, or otherwise that I'm testing that is not working, I'll just go get something else that works "out-of-the-box" with whatever "nicety" I was trying to test... Blah, blah, blah other reasons that other software is sought...

I'm fine with it being closed, but I am under no delusion that the process will change other than in the potential reduction from 8 files to 7 with a ***yes*** to issue #3434, which appears to be the case. Meaning, it appears that this list is expected to be trimmed down by the removal of `FILENAME_BUTTON_NAMES` unless that file remains with just "less content" (image file names removed but image "name" or text maintained).
