### ISSUE TITLE
After 1.5.4 upgrade to 1.5.7c shipstation can no longer import orders.

### ISSUE THREAD

**Issue by spyder0069** [zencart/zencart#4328]
Tonight I updated from 1.5.4 which was running on php 5.6.40 to zencart 1.5.7c (changed site to php 7.3.27).  ZC_install  upgraded the database and I was able to configure everything.  The store is taking orders properly.  I am receiving payment.  Emails are working.

Shipstation is installed and was working before the upgrade.  After the upgrade shipstation is able to connect to the store but does not import any new "processing" orders.  I contacted shipstation support and they did not see any errors come through on their end but were unable to see the new orders.

Has any of the table structure changed that would cause their plugin to no longer work.  Anyone else running shipstation on 1.5.7?

I am dreading the thought of entering the shipping info manually tomorrow for every order.  :^)

**Comment by spyder0069** [comment]
After a little more searching I found the answer.  [https://www.zen-cart.com/showthread.php?227224-shipstation-no-longer-importing-orders-after-upgrade&p=1373225#post1373225](url)

One user explains "the constants DATE_TIME_FORMAT and DATE_FORMAT_SHORT, which used to be present in the main language file (e.g. /includes/languages/english.php) have magically disappeared in zc157."

**Comment by drbyte** [comment]
Note: shipstation plugin has been updated for compatibility. See https://www.zen-cart.com/downloads.php?do=file&id=1324
