### ISSUE TITLE
search, modify order by, notifier

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4332]
If this is to override the order by clause:

https://github.com/zencart/zencart/blob/b4462b7c40fa804c599051be6f73d3566606fea1/includes/modules/pages/search_result/header_php.php#L446-L448

would it not be cleaner to pass $order_str to the notifier and concatenate the query parts after the notifier?

**Comment by torvista** [comment]
Continuing my musings, I find that prior to line 446, $listing_sql **already** exists due to default_filter.
So adding a few echos, and searching for dvd, gives this info with file and line numbers.

> default filter 65: $listing_sql=SELECT p.products_id, p.products_type, p.master_categories_id, p.manufacturers_id, p.products_price, p.products_tax_class_id, pd.products_description, IF(s.status = 1, s.specials_new_products_price, NULL) AS specials_new_products_price, IF(s.status = 1, s.specials_new_products_price, p.products_price) AS final_price, p.products_sort_order, p.product_is_call, p.product_is_always_free_shipping, p.products_qty_box_status FROM products p LEFT JOIN specials s ON s.products_id = p.products_id LEFT JOIN products_description pd ON pd.products_id = p.products_id AND pd.language_id = 1 LEFT JOIN products_to_categories p2c ON p2c.products_id = p.products_id LEFT JOIN manufacturers m ON m.manufacturers_id = p.manufacturers_id WHERE p.products_status = 1 AND p2c.categories_id = 0
> 
> header 445: $listing_sql=SELECT p.products_id, p.products_type, p.master_categories_id, p.manufacturers_id, p.products_price, p.products_tax_class_id, pd.products_description, IF(s.status = 1, s.specials_new_products_price, NULL) AS specials_new_products_price, IF(s.status = 1, s.specials_new_products_price, p.products_price) AS final_price, p.products_sort_order, p.product_is_call, p.product_is_always_free_shipping, p.products_qty_box_status FROM products p LEFT JOIN specials s ON s.products_id = p.products_id LEFT JOIN products_description pd ON pd.products_id = p.products_id AND pd.language_id = 1 LEFT JOIN products_to_categories p2c ON p2c.products_id = p.products_id LEFT JOIN manufacturers m ON m.manufacturers_id = p.manufacturers_id WHERE p.products_status = 1 AND p2c.categories_id = 0
> 
> header 449: $listing_sql=SELECT DISTINCT p.products_image, p.products_quantity , p.products_sort_order, m.manufacturers_id, p.products_id, pd.products_name, p.products_price, p.products_tax_class_id, p.products_price_sorter, p.products_qty_box_status, p.master_categories_id, p.product_is_call FROM (products p LEFT JOIN manufacturers m USING(manufacturers_id), products_description pd, categories c, products_to_categories p2c ) LEFT JOIN meta_tags_products_description mtpd ON (mtpd.products_id= p2c.products_id AND mtpd.language_id = 1) WHERE (p.products_status = 1 AND p.products_id = pd.products_id AND pd.language_id = 1 AND p.products_id = p2c.products_id AND p2c.categories_id = c.categories_id AND ( ( pd.products_name LIKE '%dvd%' OR p.products_model LIKE '%dvd%' OR m.manufacturers_name LIKE '%dvd%' OR mtpd.metatags_keywords LIKE '%dvd%' OR mtpd.metatags_description LIKE '%dvd%' OR pd.products_description LIKE '%dvd%') )) order by p.products_sort_order, pd.products_name

So, as things are at the moment, the query cannot be modified via the notifier as param1 is read-only.
Either the $listing_sql needs to be repeated to p2 as the least breaking change, or the $order_by clause could be overwritten...some guidance is required.

**Comment by proseLA** [comment]
https://github.com/zencart/zencart/blob/b4462b7c40fa804c599051be6f73d3566606fea1/includes/modules/pages/search_result/header_php.php#L386

at this notifier point, one could easily modify the `$_GET` array to accomplish needed sort.

**Comment by torvista** [comment]
...indeed.....thanks.
