### ISSUE TITLE
Admin side zen_image_submit should respect IMAGE_USE_CSS_BUTTONS config setting  

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4333]
If you call `zen_image_submit` in an admin function, it still uses the old images even if you have CSS Buttons turned on.  This seems like a bug to me.  Thoughts?

**Comment by proseLA** [comment]
the ZC team has worked hard at merging the admin and storefront functions to have a single definition (which i applaud).  

rather than putting work into correcting a duplicate admin function, i would suggest work at merging the html output functions.

those are my thoughts.

**Comment by drbyte** [comment]
Scott, is your query admin-specific? eg, unrelated to storefront?

**Comment by scottcwilson** [comment]
Yes - clarifying title to reflect that.

**Comment by drbyte** [comment]
Ref #3368

**Comment by scottcwilson** [comment]
This function was deprecated in 1.5.8 with the comment "Use <button> markup instead." 

As an example, in 1.5.7, coupon_admin.php did this: 
```
<?php echo zen_image_submit('button_preview.gif',COUPON_BUTTON_PREVIEW); ?>
```
This has been changed in 1.5.8 to: 

```
<button type="submit" class="btn btn-primary"><?php echo IMAGE_PREVIEW; ?></button>
```

Closing.
