### ISSUE TITLE
v158: image for products in category_product_listing page w/Image Handler

### ISSUE THREAD

**Issue by simon1066** [zencart/zencart#4335]
In normal use the images for products displayed in the category_product_listing page are Zen Cart's small images, resized according to the values of IMAGE_SHOPPING_CART_WIDTH, IMAGE_SHOPPING_CART_HEIGHT. 

With Image Handler installed a large 'base' image can be uploaded with the subsequent small, medium and large images being generated on-the-fly. In that case the images for products displayed in category_product_listing page are actually these large base images, resized as above. This can negatively impact the load times of the category_product_listing pages.

I suggest an admin switch be added to allow the user to choose whether or not to display the images. (Perhaps in lieu of the Image Handler plugin being modified to allow for smaller images to be displayed).

**Comment by scottcwilson** [comment]
You don't have to display the images; go to Admin > Configuration > Product Listing and set Display Product Image to 0.
