### ISSUE TITLE
Reconcile handling of actions in admin search results 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4337]
Relevant file: admin/category_product_listing.php  around l. 912, where the action buttons are being built for edit, delete, move and copy.

Further to @drbyte question in #4288 it seems as though all these actions should be handled in the same way.  Right now, delete and edit are different from move and copy. 

Not sure what to do, just entering this ticket so the issue doesn't get lost.

**Comment by scottcwilson** [comment]
@proseLA You might have a fresher perspective.

**Comment by proseLA** [comment]
i see 3 instances of:

```
(isset($_GET['search']) ? '&search=' . $_GET['search'] : '')
```
in this script.  i see no reason why all 3 instances could not use:
```
$search_parameter
```

best.

**Comment by scottcwilson** [comment]
I believe you are correct - thanks for confirming.
