### ISSUE TITLE
language file getting loaded twice...

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#4342]
pretty sure this line should be commented out:

https://github.com/zencart/zencart/blob/bf85f1ea4a2ab56701203ca8669736b8d42482a4/admin/modules.php#L347

as the language file now seems to be part of the part of the move to artisan from this commit:

https://github.com/zencart/zencart/commit/65eec8d06ebf33a487f8c4f4c46b3a57c3ddeacc

one example of where language file now gets loaded:

https://github.com/zencart/zencart/blob/bf85f1ea4a2ab56701203ca8669736b8d42482a4/includes/classes/payment.php#L65

**Comment by scottcwilson** [comment]
Fixed by #4532
