### ISSUE TITLE
ZC158, admin, orders: sanitation of oID

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4352]
I think these need to be rationalised as trim is only for strings, and it is already set as an integer (gives error with strict types).

https://github.com/zencart/zencart/blob/eb2d13f582c67027702617d026fd969dadb5757e/admin/orders.php#L22-L23

https://github.com/zencart/zencart/blob/eb2d13f582c67027702617d026fd969dadb5757e/admin/orders.php#L49-L51

There is also differing santitation for POST oID and oID is also cast to integer multiple times....

**Comment by drbyte** [comment]
IIRC the reason `trim()` was added was because mods (maybe Edit Orders?) were submitting strings with preceding/trailing spaces.
