### ISSUE TITLE
Group Pricing / Wholesale

### ISSUE THREAD

**Issue by bislewl** [zencart/zencart#436]
Perhaps the ability to offer wholesale pricing on a product/category level, would be much preferred for group pricing. Also the ability to offer certain customers additional products would be nice.

**Comment by wiztechinc** [comment]
I almost never find a cart using the group pricing and frequently install the dual wholesale mod. Folks usually prefer a different price per each product and not a percent off all products.

**Comment by DivaVocals** [comment]
Playing devils advocate.. why does it have to be ONE or the OTHER.. can't BOTH options be offered?? Don't use the one that does not suit your situation..

**Comment by jtwebsitedesign** [comment]
I agree, both options should be offered. However, bislewl has a point about slightly improving the core group pricing feature. If pricing by category were implemented, that would greatly reduce the number of Dual Pricing installations that would otherwise be overkill on many sites.

**Comment by drbyte** [comment]
Is this a request for:

- [ ] Link a Salemaker Sale to a certain customer_group_pricing record?  (ie: apply category-specific discount percentages based on group membership)

- [ ] Assign multiple prices per product, which then must be tied to certain groups and authorizations?

**Comment by jtwebsitedesign** [comment]
I think the first option would be perfect. The second option is much more complicated, and something the Dual Pricing module handles really well.

I assume the Salemaker feature could be built right into the Group Pricing page like this?

![image](https://cloud.githubusercontent.com/assets/1544893/16430219/634db2c0-3d2f-11e6-8eb8-fc176729dfef.png)

**Comment by drbyte** [comment]
> I assume the Salemaker feature could be built right into the Group Pricing page like this?

Interesting approach worth considering.

**Comment by torvista** [comment]
We deal with many workshops and more and more they expect to able to order online. Indeed we would encourage it to reduce our time on the phone.
Currently Group Pricing is not finished/is not realistically useable for wholesale. It has to be applicable per manufacturer, and/or per category. Per product is not something we personally would need but no doubt someone does.
We get different discounts from different manufacturers and consequently our discounts to wholesale customers are set per supplier-manufacturer.

**Comment by scottcwilson** [comment]
Closing due to lack of interest.
