### ISSUE TITLE
Whoops! Session timed out (Authorize.net SIM)

### ISSUE THREAD

**Issue by webspacecreations** [zencart/zencart#4362]
**Describe the bug**
Attempting to checkout via Authorize.net SIM (on-site w/ SSL) results in a Whoops! Session timed out page in 1.5.7c. Checkout completed in well under 5 minutes (default PHP session length of 24 minutes) as well as after increasing session length to 2 hrs on server. Attempt to login again fails (already logged in), which indicates there is something specific about the Authorize.net SIM payment module causing problems and that the session is still active. This is on a new install of 1.5.7c with only the UPS add-on module (UPS ground selected as shipping method) installed.

Note: checkout with PayPal completes just fine. This is a SERIOUS problem as the card is actually charged (if card is valid), but ZenCart & customer think the transaction failed. This was a problem in v1.5.6c as well (the primary reason for the upgrade) and the most obvious culprit (since customer is actually remaining logged in) is something to do with the security measures (which may not be as relevant today as they once were). Attempts to fix this in v1.5.6c failed and unless there are any developments, I'll take a stab at it again in 1.5.7c.

**Version**
Zen Cart version: v1.5.7c
PHP version: 8.0
MySQL version: 5.7
Plugins that may be related: 
What older/newer versions were also tested? 1.5.6c

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Go to website
2. Add product to cart
3. Begin checkout
4. Select Credit card (Authorize.net SIM on-site) as payment option
5. Enter CC details
6. Submit payment

**Expected behavior**
Upon valid CC information and a successful charge, the success page should be shown.

**Debug/Error Logs**
PROBABLY IRRELEVANT:
[06-Jun-2021 05:18:24 UTC] Request URI: /, IP address: xxx.xxx.xx.xx
#1  products_viewed_counter->should_be_excluded() called at [/home/account/public_html/includes/classes/observers/class.products_viewed_counter.php:17]
#2  products_viewed_counter->__construct() called at [/home/account/public_html/includes/autoload_func.php:44]
#3  require(/home/account/public_html/includes/autoload_func.php) called at [/home/account/public_html/includes/application_top.php:222]
#4  require(/home/account/public_html/includes/application_top.php) called at [/home/account/public_html/index.php:25]
--> PHP Warning: Undefined array key "spider_flag" in /home/account/public_html/includes/classes/observers/class.products_viewed_counter.php on line 37.
 
**Devices (please complete the following information):**
Linux
Chrome

**Additional context**
https://github.com/zencart/zencart/issues/3565

**Comment by drbyte** [comment]
This should take care of the issue since SIM takes the customer offsite and back again, and Chrome requires that a samesite cookie override be set: https://docs.zen-cart.com/user/payment/payment_whoops_timeouts/

**Comment by webspacecreations** [comment]
That helps to explain why the issue seems to have sprung up only recently. That didn't fix it for me, but if PHP8 is caching the cart, it may take time to refresh the cache. It also gives me a place to start investigating... would Authorize.net's Accept.js method avoid the browser issue?

It would help a lot if itemized products were sent to Authorize.net so that merchant has a record of the actual purchase. Is there any interest in such a contribution?

**Comment by drbyte** [comment]
If your site isn't running over https then the samesite stuff won't take effect at all.

In your `/includes/configure.php`:
```
define('HTTP_SERVER', 'https://www.YOURSITE.com');
define('HTTPS_SERVER', 'https://www.YOURSITE.com');
```

**Comment by drbyte** [comment]
The PHP header can't control what happens when "returning from Authorize.net", which is where the issue arises.

The accept.js method might help, but that requires almost a complete rewrite of the module.

Item details are sent with payment requests, so should show up in the authorize.net details.

**Comment by webspacecreations** [comment]
Please let's not be so quick to close this ticket or make assumptions. Site is definitely running over https and specified as both for http and https in configure.php. ENABLE_SSL is true. I've also confirmed that the extra_configures contains the additional file you linked to. This is absolutely NOT working in Chrome. I should note this server is running LiteSpeed (the most current in the 5.4 branch).

I have restored the .htaccess directive that forces https URLs and attempted to add .htaccess directives to address the cookie issue for LiteSpeed (https://blog.litespeedtech.com/2020/11/02/header-edit-set-cookie-alternative/) and Apache (https://community.shopify.com/c/Shopify-APIs-SDKs/SameSite-Cookie-via-htaccess-file/td-p/644341/page/2), but still getting that Whoops! error. The most comprehensive PHP-specific documentation I've found is at https://github.com/GoogleChromeLabs/samesite-examples/blob/master/php.md

Chrome is stalling out with the Whoops! error with the authorize.net transact.dll in the URL bar, so I gather ZenCart is looking for the session cookie, not finding it, and giving the Whoops! page (even though user is logged in if the URL is changed back to merchant site). This problem exists for both on-site and off-site checkout with Authorize.net.

In theory, sessions shouldn't need to be in place when the transact.dll page loads the ZenCart page... just grab the authentication token Authorize.net provides, verify it's a valid signature (transaction isn't forged), and close out transaction in database. So, why isn't that happening? If you point me in the direction where security measures / session enforcement is likely killing this process I can more efficiently identify how to securely resolve this for Authorize.net SIM and make a contribution back to the codebase.

I'm not sure what you consider itemized details (Level 2 data), but those are definitely not being passed with the Authorize.net SIM method.

**Comment by drbyte** [comment]
The "whoops, session timed out" message is a result of the browser not being able to connect back to the session cookie that was used during the customer's shopping session. The samesite setting enforced by (some) browsers now in 2021 prevents browsers from reconnecting to former sessions (via their cookie) when redirects occur. This is (in some part) why Authorize.net has deprecated the SIM method.

Using AIM completely avoids these cookie issues. AIM also transmits purchased-item details as part of the transaction "description" (not as Level 2 data). AIM also offers more useful logging/debugging if something goes wrong because the module stays in charge of the transaction instead of handing the browser off to other sites.

**Comment by webspacecreations** [comment]
And it puts a major PCI / security headache right back in the merchant's arena. Not acceptable IMO for many of the small-time merchants using ZenCart. The obvious solution is to pass session ID and securityToken along to Authorize.net as passthru values, then use them to identify the appropriate transaction on the ZenCart side and complete the transaction... except being logged in and having an active session is a substantial dependency that really isn't simple to unravel (after spending a few hours in the code). It's now clear to me why the cookie workaround attempt is being made. Although it might have worked in the past (and may continue to work for the next few months for some), it's the wrong approach and really fragile to future browser developments related to third party cookies. I think I'm very close to possibly making it work if there's some way to make ZenCart think user is logged in from the passthru session ID.

Another solution would be to show a temporary page that redirects back to the cart and passes the POSTed values from Authorize.net. Maybe PayPal does something like that, I'm not sure.

At this point, it looks like an Accept.js payment module is a better approach for the way ZenCart is designed unless there's a simple way to recreate the session from the passthru value from Authorize.net. I'm ready to do the legwork and not looking to fault anyone... it'd be awesome to move the tone in a more productive direction.

**Comment by webspacecreations** [comment]
For anyone encountering this problem with Authorize.net (SIM), there's a "simple" workaround:

1. Open includes/modules/payment/authorizenet.php
2. On/around line 331, change the x_relay_URL parameter line to:
      `'x_relay_URL' => zen_href_link(FILENAME_CHECKOUT_PROCESS, 'action=confirm&zenid=' . session_id() , 'SSL', true, false),`
3. Save
4. Go to Admin -> Sessions and be sure "Force Cookie Use" is set to False (passing the session ID in the URL bypasses the cookie problem)

Tested on ZenCart 1.5.7c, but probably works on many other versions of the cart. Tested with SIM set to Onsite, but Offsite should work too.

Note: the only code change needed is appending the zenid (used to recreate session) to the relay URL. This should be a "future-proof" workaround for browsers shutting down 3rd party cookie support.

**Comment by drbyte** [comment]
> puts a major PCI / security headache right back in the merchant's arena

> Tested with SIM set to Onsite, but Offsite should work too.

SIM in "Onsite" mode doesn't solve the PCI issues you mention.

**Comment by webspacecreations** [comment]
Is SIM onsite not tokenized, i.e. is CC info collected by merchant?
