### ISSUE TITLE
Spiffycal direct date entry issues

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4363]
**Describe the bug**
Go to Admin > Reports > Products Viewed.
In the Start Date, type "3/5/2021".  Hit tab.  Observe that the date is changed to 05/03/2021. 

**Version**
Zen Cart version: 1.5.7
PHP version: 7.3

Same issue observed in older uses of Spiffycal, such as 1.5.6 Admin > Catalog > Specials.

**Comment by proseLA** [comment]
**get rid of spiffyCAL!**

we use datePicker is any number of other places.  of which i am a fan.

https://jqueryui.com/datepicker/

ps, i am able to reproduce the bug as well.

**Comment by scottcwilson** [comment]
It would be great if we could get rid of Spiffycal in Zen Cart 1.5.8 (and replace it with jQuery Datepicker). However, we still have to support 1.5.7 for a while more, so I'd like to get this bug fixed.

**Comment by scottcwilson** [comment]
Closing issue due to lack of interest and activity.
