### ISSUE TITLE
Improve zen_get_show_product_switch

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4370]
This function is called 14 times in includes/modules/pages/product_info/main_template_vars.php, and each call has 3 or 4 database queries.  We could check the database once and bring back all relevant SHOW_ values for the product, and store them in memory, and then build the relevant variables from the contents of memory (rather than repeatedly querying).  

Would you accept a PR to do this?

**Comment by drbyte** [comment]
Okay. Eventually my goal is a product class that owns all of this; however, it's too early for that yet, so a micro refactoring could be an acceptable bandage.

In looking at it, it's possible we've already got the data in memory, so I wonder if the simplest refactor might be:

- the queries being run against `configuration` and `product_type_layout` tables in `zen_get_show_product_switch()` may be redundant, as the values are already in-memory as constants. So, testing them with `defined('foo')` and returning `constant('foo')` might suffice.
- the queries in `zen_get_show_product_switch_name()` can probably be avoided where already retrieved by adding something like this to the top of the function, leaving the rest of the function's logic as fallback:
```php
    global $product_info;
    if (!empty($product_info) && !$product_info->EOF && (int)$product_info->fields['products_id'] === (int)$lookup) {
        return strtoupper($prefix . $product_info->fields['type_handler'] . $suffix . $field_prefix . $field . $field_suffix);
    }
```
