### ISSUE TITLE
ZC158, shopfront listings prices appear to be links, but are not links.

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4382]
The css makes the cursor as pointer over the whole item listing, implying it is all a link to the product. But only the image and name are links, not the prices, so clicking on them does nothing.

Confusing in my opinion.

![Clipboard01](https://user-images.githubusercontent.com/4391026/122051719-35474480-cde5-11eb-9018-3df1598df233.gif)

**Comment by scottcwilson** [comment]
Please create a PR.

**Comment by torvista** [comment]
whole item is a link, or text name is link (preferred)?

**Comment by scottcwilson** [comment]
Lowest code solution would be the whole div is a link, but use your best judgement.

**Comment by torvista** [comment]
I think the whole block should be the link, where the linked area matches the colour change area on hover.
At the moment each element is linked/not linked and then sorted for display.
A PR would remove all those individual links and put one on the whole block.
I can't see a problem with that...but I often don't...

**Comment by scottcwilson** [comment]
Go for it.

**Comment by torvista** [comment]
Another rabbit hole.
Currently for example with new products listing:
![Clipboard01](https://user-images.githubusercontent.com/4391026/156143254-d99921b7-f23e-4311-b02c-eaa841426d0d.gif)

Lots of white space between the image, name, price due to hard-coded **br** and margins on the **a href** tag for the image and the name.

https://github.com/zencart/zencart/blob/2859c4d095f22b84a78bafa73003a14edc757c90/includes/modules/new_products.php#L73-L74

I would get rid of the repeated a href and put one around all three items. Without any further changes, that compresses all:
![Clipboard01](https://user-images.githubusercontent.com/4391026/156144158-fb5a615d-8b06-46ba-a77a-49bad33d830e.gif)

So requiring css changes and possibly better done with divs around each item...to maintain things as they are.

Others more experienced in template development are better-placed than me to make decisions/correct this issue.

**Comment by scottcwilson** [comment]
This is a template issue, and opinions will differ about the right way to do it. I want minimal effort to be going into tweaking the responsive classic template, and am for that reason closing this issue.

**Comment by dbltoe** [comment]
Sorry,

Never saw this or was asked to contribute an opinion.

I have been working on bootstrap mainly as people seem to be shying away from responsive_classic.

I had gotten RC into contrast compliance but was not yet working on link compliance.

There are four pages at least that are customized in bootstrap but still use the same method to show the item(s) and this is a type A accessibility problem.

Only the portion that does not have "discernible text" (like the first anchor in line 71 of featured_products.php) needs to have a title tag for accessibility.  The image below shows only the image between the > and the </a

I can probably PR all of them tomorrow if wanted.

![Screenshot 2022-12-10 150149](https://user-images.githubusercontent.com/5122886/206875139-96e1c027-153a-4290-ba85-2d117ae72fb7.png)

**Comment by scottcwilson** [comment]
> I have been working on bootstrap mainly as people seem to be shying away from responsive_classic.

This is absolutely the right choice.
