### ISSUE TITLE
Rename Configuration > Index Listing to Configuration > Centerboxes 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4387]
I find the name of this menu entry quite confusing.  To me, "Index Listing" is another name for the product listing page. 

Thoughts?

**Comment by torvista** [comment]
I agree that it is not intuitive as the names for the other listings. But as it contains options pertaining to those other listings, I would use Main Listing or Default Listing. Centerboxes means nothing to me.
Single Column has gone from ZC158.

**Comment by scottcwilson** [comment]
It's not related to whether or not there's a single column. 

Centerboxes is the term of art that Zen Cart uses for the pieces of content that reside in the center. 
https://docs.zen-cart.com/user/template/centerboxes/

https://docs.zen-cart.com/user/first_steps/glossary/

**Comment by scottcwilson** [comment]
Closing - now that this is documented, it's less worthwhile to change it.
