### ISSUE TITLE
ZC158: PHP Fatal error:  Uncaught TypeError: nl2br() operating on NULL,  due to db default being NULL

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4388]
If the order comment is NULL (database default), a fatal error is triggered on the second nl2br:
https://github.com/zencart/zencart/blob/72c02e3df5437883729f068be67d1aa89d70b311/admin/orders.php#L952-L957

It would be null if the comment field is not set on the insert of the record. I haven't checked if that is the case in any core code, but my autoemailer script does not bother setting it, so I do have NULL in this field.
I note the use of zen_output_string_protected on the first nlbr prevents the error.
So, more than one way to approach this...

**Comment by proseLA** [comment]
not seeing it.  tested with:
```
    $test = null;

    echo nl2br(zen_output_string_protected($test));
    echo nl2br($test);
```
no errors.

what am i missing?

**Comment by torvista** [comment]
Good question, I forgot I have
declare(strict_types=1);
at the start of the file...still, it serves its purpose in squeezing these out!
