### ISSUE TITLE
Listing boxes sort order issue

### ISSUE THREAD

**Issue by ajeh** [zencart/zencart#439]
Listing boxes no longer display in the order set in Index Listing.
SHOW_PRODUCT_INFO_MAIN_NEW_PRODUCTS
SHOW_PRODUCT_INFO_MAIN_FEATURED_PRODUCTS
SHOW_PRODUCT_INFO_MAIN_SPECIALS_PRODUCTS
 SHOW_PRODUCT_INFO_MAIN_UPCOMING

There are other sets included in Stock settings.

**Comment by zcwilt** [comment]
Just a note on this one. 
Because listingboxes are now more flexible, the old defines are no longer used.
What's needed is a way to do CRUD stuff on the listingbox_* database tables.
Will do something for this, once I've finished up some other PR's I'm working on.
