### ISSUE TITLE
Configuration page names are hard coded in english

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4391]
https://github.com/zencart/zencart/blob/190bda0360fe1b3ad64c00fbcbd2da9404012884/zc_install/sql/install/mysql_zencart.sql#L3064-L3089

I believe these are the only things left to complete localisation?

**Comment by mc12345678** [comment]
So, while this seems like an issue, it appears that these can still be overridden...

in: https://github.com/zencart/zencart/blob/e54348a0a2f4a59c769e628d84344184969e218d/admin/configuration.php#L185-L190

If (for title of My Store for example) 'CFGTITLE_My Store' is defined, then the associated language override will be handled. The same is true of 'CFGDESC_My Store'.

**Comment by torvista** [comment]
No. That code is for changing constant titles and descriptions.
The page name is used directly:
https://github.com/zencart/zencart/blob/e54348a0a2f4a59c769e628d84344184969e218d/admin/configuration.php#L53-L55
https://github.com/zencart/zencart/blob/e54348a0a2f4a59c769e628d84344184969e218d/admin/configuration.php#L93
