### ISSUE TITLE
remove commas prior to calculation in customer class

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#4394]
https://github.com/zencart/zencart/blob/190bda0360fe1b3ad64c00fbcbd2da9404012884/includes/classes/Customer.php#L314

in a situation where the order  is over 1,000.00, the comma needs so be removed.  leaving the comma as part of the calculation results in a:

PHP Notice: A non well formed numeric value encountered in /var/www/zcdev/includes/classes/Customer.php on line 314.

i am sure there is a reason why we are using the text from the orders_total table and then stripping out the currency indicators, as opposed to using the value from said table, but the reason escapes me at this moment.

https://github.com/zencart/zencart/blob/190bda0360fe1b3ad64c00fbcbd2da9404012884/includes/classes/Customer.php#L495

https://github.com/zencart/zencart/blob/190bda0360fe1b3ad64c00fbcbd2da9404012884/includes/classes/Customer.php#L538

**Comment by torvista** [comment]
Related
https://github.com/zencart/zencart/issues/4097

**Comment by scottcwilson** [comment]
Hopefully fixed by #4397
