### ISSUE TITLE
STOREFRONT: Promote strings defined more than once to includes/languages/english.php 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4395]
Whether or not the new language file structure is adopted in the storefront (see #3785), the same kind of duplicate reduction for the admin suggested in #3739 should also be done on the storefront. 

Below is a list of candidate definitions.  These could be moved out of page specific files into includes/languages/english.php.

ATTRIBUTES_PRICE_DELIMITER_PREFIX
ATTRIBUTES_PRICE_DELIMITER_SUFFIX
ATTRIBUTES_WEIGHT_DELIMITER_PREFIX
ATTRIBUTES_WEIGHT_DELIMITER_SUFFIX
ENTRY_CATEGORIES
ENTRY_DATE_FROM
ENTRY_DATE_TO
ENTRY_EMAIL
ENTRY_EMAIL_CONTENT_CHECK_ERROR
ENTRY_EMAIL_NAME_CHECK_ERROR
ENTRY_ENQUIRY
ENTRY_INCLUDE_SUBCATEGORIES
ENTRY_MANUFACTURERS
ENTRY_NAME
ENTRY_PRICE_FROM
ENTRY_PRICE_TO
ENTRY_TELEPHONE
ERROR_AT_LEAST_ONE_INPUT
ERROR_INVALID_FROM_DATE
ERROR_INVALID_KEYWORDS
ERROR_INVALID_TO_DATE
ERROR_PRICE_FROM_MUST_BE_NUM
ERROR_PRICE_TO_LESS_THAN_PRICE_FROM
ERROR_PRICE_TO_MUST_BE_NUM
ERROR_TO_DATE_LESS_THAN_FROM_DATE
FREE_SHIPPING_DESCRIPTION
FREE_SHIPPING_TITLE
HEADER_ALT_TEXT
HEADER_LOGO_HEIGHT
HEADER_LOGO_IMAGE
HEADER_LOGO_WIDTH
HEADER_SEARCH_BUTTON
HEADER_SEARCH_DEFAULT_TEXT
HEADER_TITLE_CART_CONTENTS
HEADER_TITLE_CATALOG
HEADER_TITLE_CHECKOUT
HEADER_TITLE_LOGIN
HEADER_TITLE_LOGOFF
HEADER_TITLE_MY_ACCOUNT
HEADING_ADDRESS_INFORMATION
HEADING_BILLING_ADDRESS
HEADING_DELIVERY_ADDRESS
HEADING_ORDER_DATE
HEADING_ORDER_HISTORY
HEADING_ORDER_NUMBER
HEADING_PAYMENT_METHOD
HEADING_PRODUCTS
HEADING_QUANTITY
HEADING_RETURNING_CUSTOMER
HEADING_SEARCH_CRITERIA
HEADING_SEARCH_HELP
HEADING_SHIPPING_METHOD
HEADING_TAX
HEADING_TITLE_NESTED
HEADING_TITLE_PRODUCTS
HEADING_TOTAL
ICON_ERROR_ALT
ICON_IMAGE_ERROR
ICON_IMAGE_SUCCESS
ICON_IMAGE_TINYCART
ICON_IMAGE_TRASH
ICON_IMAGE_UPDATE
ICON_IMAGE_WARNING
ICON_SUCCESS_ALT
ICON_TINYCART_ALT
ICON_TRASH_ALT
ICON_UPDATE_ALT
ICON_WARNING_ALT
NOT_LOGGED_IN_TEXT
ORDER_HEADING_DIVIDER
OTHER_BOX_NOTIFY_REMOVE_ALT
OTHER_BOX_NOTIFY_YES_ALT
OTHER_BOX_WRITE_REVIEW_ALT
OTHER_DOWN_FOR_MAINTENANCE_ALT
OTHER_IMAGE_BLACK_SEPARATOR
OTHER_IMAGE_BOX_NOTIFY_REMOVE
OTHER_IMAGE_BOX_NOTIFY_YES
OTHER_IMAGE_BOX_WRITE_REVIEW
OTHER_IMAGE_CALL_FOR_PRICE
OTHER_IMAGE_CUSTOMERS_AUTHORIZATION
OTHER_IMAGE_CUSTOMERS_AUTHORIZATION_ALT
OTHER_IMAGE_DOWN_FOR_MAINTENANCE
OTHER_IMAGE_PRICE_IS_FREE
OTHER_IMAGE_REVIEWS_RATING_STARS_FIVE
OTHER_IMAGE_REVIEWS_RATING_STARS_FOUR
OTHER_IMAGE_REVIEWS_RATING_STARS_ONE
OTHER_IMAGE_REVIEWS_RATING_STARS_THREE
OTHER_IMAGE_REVIEWS_RATING_STARS_TWO
OTHER_REVIEWS_RATING_STARS_FIVE_ALT
OTHER_REVIEWS_RATING_STARS_FOUR_ALT
OTHER_REVIEWS_RATING_STARS_ONE_ALT
OTHER_REVIEWS_RATING_STARS_THREE_ALT
OTHER_REVIEWS_RATING_STARS_TWO_ALT
PAGE_ACCOUNT
PAGE_ACCOUNT_EDIT
PAGE_ACCOUNT_HISTORY
PAGE_ACCOUNT_NOTIFICATIONS
PAGE_ADDRESS_BOOK
PAGE_ADVANCED_SEARCH
PAGE_CHECKOUT_SHIPPING
PAGE_PRODUCTS_NEW
PAGE_REVIEWS
PAGE_SHOPPING_CART
PAGE_SPECIALS
PREV_NEXT_PRODUCT
PRIMARY_ADDRESS_TITLE
SEARCH_DEFAULT_TEXT
SEND_TO_TEXT
SET_AS_PRIMARY
TABLE_HEADING_BUY_NOW
TABLE_HEADING_COMMENTS
TABLE_HEADING_IMAGE
TABLE_HEADING_MANUFACTURER
TABLE_HEADING_PRICE
TABLE_HEADING_PRIVACY_CONDITIONS
TABLE_HEADING_PRODUCTS
TABLE_HEADING_SHIPPING_ADDRESS
TABLE_HEADING_STATUS_COMMENTS
TABLE_HEADING_STATUS_DATE
TABLE_HEADING_STATUS_ORDER_STATUS
TABLE_HEADING_WEIGHT
TEXT_ALL_CATEGORIES
TEXT_ALL_MANUFACTURERS
TEXT_ALSO_PURCHASED_PRODUCTS
TEXT_ATTRIBUTES_PRICE_WAS
TEXT_ATTRIBUTES_QTY_PRICE_HELP_LINK
TEXT_ATTRIBUTE_IS_FREE
TEXT_AVAILABLE_BALANCE
TEXT_BUY
TEXT_CLOSE_WINDOW
TEXT_COUPON_GV_RESTRICTION
TEXT_COUPON_GV_RESTRICTION_ZONES
TEXT_COUPON_HELP_CATEGORIES
TEXT_COUPON_HELP_DATE
TEXT_COUPON_HELP_DESC
TEXT_COUPON_HELP_FIXED
TEXT_COUPON_HELP_FREESHIP
TEXT_COUPON_HELP_HEADER
TEXT_COUPON_HELP_MINORDER
TEXT_COUPON_HELP_NAME
TEXT_COUPON_HELP_PRODUCTS
TEXT_COUPON_HELP_RESTRICT
TEXT_CURRENT_REVIEWS
TEXT_DATE_ADDED
TEXT_DATE_AVAILABLE
TEXT_GREETING_GUEST
TEXT_GREETING_GUEST_SHOWCASE
TEXT_GREETING_PERSONAL
TEXT_MANUFACTURER
TEXT_MORE_INFORMATION
TEXT_NOW
TEXT_NO_CAT_RESTRICTIONS
TEXT_NO_CAT_TOP_ONLY_DENY
TEXT_NO_PRODUCTS
TEXT_NO_PRODUCTS2
TEXT_NO_PROD_RESTRICTIONS
TEXT_NO_PROD_SALES
TEXT_NO_PURCHASES
TEXT_NUMBER_OF_PRODUCTS
TEXT_OF_5_STARS
TEXT_ONETIME_CHARGE_DESCRIPTION
TEXT_ONETIME_CHARGE_SYMBOL
TEXT_OUT_OF_STOCK
TEXT_PASSWORD_FORGOTTEN
TEXT_PRICE
TEXT_PRIVACY_CONDITIONS_CONFIRM
TEXT_PRODUCTS_QUANTITY
TEXT_PRODUCTS_WEIGHT
TEXT_PRODUCT_MANUFACTURER
TEXT_PRODUCT_NOT_FOUND
TEXT_PRODUCT_OPTIONS
TEXT_PRODUCT_QUANTITY
TEXT_PRODUCT_WEIGHT
TEXT_SEARCH_HELP
TEXT_SEARCH_HELP_LINK
TEXT_SEARCH_IN_DESCRIPTION
TEXT_SHOW
TEXT_SUCCESS
TEXT_TOTAL_AMOUNT
TEXT_TOTAL_ITEMS
TEXT_TOTAL_WEIGHT
TEXT_VISITORS_CART
TITLE_CONTINUE_CHECKOUT_PROCEDURE
TITLE_PLEASE_SELECT
TITLE_SHIPPING_ADDRESS
WARNING_PRIMARY_ADDRESS_DELETION

**Comment by mc12345678** [comment]
Isn't it doubly prudent to not only identify the existence of duplicate defines but the values to which are assigned? E.g. in some cases a long version in others short? (or in other words reproducing the effort applied to the other issue)

**Comment by scottcwilson** [comment]
"candidate definitions" -> things that should be checked for appropriateness for consolidation.
