### ISSUE TITLE
ZC158: malformed url creates debug

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4399]
using this url
https://DOMAIN/index.php?main_page=product_info

is handled ok on the shopfront "product not found", but creates a debug.
I know it is malformed but these spiders are sloppy.

> [27-Jun-2021 16:28:55 Europe/Madrid] Request URI: /zencart-158/index.php?main_page=product_info, IP address: 127.0.0.1
> #1  zen_get_products_base_price() called at [...\zencart-158\includes\modules\products_quantity_discounts.php:62]
> #2  require(...\zencart-158\includes\modules\products_quantity_discounts.php) called at [...\zencart-158\includes\modules\pages\product_info\main_template_vars.php:148]
> #3  require(...\zencart-158\includes\modules\pages\product_info\main_template_vars.php) called at [...\zencart-158\includes\templates\responsive_classic\common\tpl_main_page.php:178]
> #4  require(...\zencart-158\includes\templates\responsive_classic\common\tpl_main_page.php) called at [...\zencart-158\index.php:94]
> --> PHP Warning: Undefined array key "products_price" in ...\zencart-158\includes\functions\functions_prices.php on line 421.
> 
> [27-Jun-2021 16:28:55 Europe/Madrid] Request URI: /zencart-158/index.php?main_page=product_info, IP address: 127.0.0.1
> #1  zen_get_products_base_price() called at [...\zencart-158\includes\modules\products_quantity_discounts.php:62]
> #2  require(...\zencart-158\includes\modules\products_quantity_discounts.php) called at [...\zencart-158\includes\modules\pages\product_info\main_template_vars.php:148]
> #3  require(...\zencart-158\includes\modules\pages\product_info\main_template_vars.php) called at [...\zencart-158\includes\templates\responsive_classic\common\tpl_main_page.php:178]
> #4  require(...\zencart-158\includes\templates\responsive_classic\common\tpl_main_page.php) called at [...\zencart-158\index.php:94]
> --> PHP Warning: Undefined array key "products_priced_by_attribute" in ...\zencart-158\includes\functions\functions_prices.php on line 423.
> 
> [27-Jun-2021 16:28:55 Europe/Madrid] Request URI: /zencart-158/index.php?main_page=product_info, IP address: 127.0.0.1
> #1  zen_get_products_base_price() called at [...\zencart-158\includes\modules\products_quantity_discounts.php:86]
> #2  require(...\zencart-158\includes\modules\products_quantity_discounts.php) called at [...\zencart-158\includes\modules\pages\product_info\main_template_vars.php:148]
> #3  require(...\zencart-158\includes\modules\pages\product_info\main_template_vars.php) called at [...\zencart-158\includes\templates\responsive_classic\common\tpl_main_page.php:178]
> #4  require(...\zencart-158\includes\templates\responsive_classic\common\tpl_main_page.php) called at [...\zencart-158\index.php:94]
> --> PHP Warning: Undefined array key "products_price" in ...\zencart-158\includes\functions\functions_prices.php on line 421.
> 
> [27-Jun-2021 16:28:55 Europe/Madrid] Request URI: /zencart-158/index.php?main_page=product_info, IP address: 127.0.0.1
> #1  zen_get_products_base_price() called at [...\zencart-158\includes\modules\products_quantity_discounts.php:86]
> #2  require(...\zencart-158\includes\modules\products_quantity_discounts.php) called at [...\zencart-158\includes\modules\pages\product_info\main_template_vars.php:148]
> #3  require(...\zencart-158\includes\modules\pages\product_info\main_template_vars.php) called at [...\zencart-158\includes\templates\responsive_classic\common\tpl_main_page.php:178]
> #4  require(...\zencart-158\includes\templates\responsive_classic\common\tpl_main_page.php) called at [...\zencart-158\index.php:94]
> --> PHP Warning: Undefined array key "products_priced_by_attribute" in ...\zencart-158\includes\functions\functions_prices.php on line 423.
> 
>

**Comment by proseLA** [comment]
why not on line 50, add:
```
if (zen_products_id_valid($products_id_current)) {
``` 
and then close the `if` statement at the end of the file?

**Comment by torvista** [comment]
I assumed you meant 50 in functions prices...but that is in a function.
I would have thought this anomaly should be handled/trapped in the header/as early as possible.
At the moment the lack of a $_GET['products_id'] just sets a products_id of 0 which gets passed to the normal processing, instead of aborting normal processing. Seems pointless and wasteful and leads to the reported debug.

**Comment by proseLA** [comment]
> I assumed you meant 50 in functions prices...but that is in a function.
> I would have thought this anomaly should be handled/trapped in the header/as early as possible.
> At the moment the lack of a $_GET['products_id'] just sets a products_id of 0 which gets passed to the normal processing, instead of aborting normal processing. Seems pointless and wasteful and leads to the reported debug.

what makes you think it is getting trapped earlier in v157?  (fwiw, it is not....)

the function `zen_products_id_valid` gets called 3 times for a valid product on a page load.  seems pointless and wasteful as well...  but does not report a debug.

while i definitely agree with you, legacy code gets updated as we go...  it seems that this problem is related to a change in `zen_get_products_base_price`; but i no longer have the energy to dig deeper as to why it now happens.

i do agree we can catch it earlier though.  i'm thinking that this section of code:

https://github.com/zencart/zencart/blob/88cb37d8991ed4c2c6b1e70d83ba4a1e0ca32329/includes/modules/pages/product_info/main_template_vars.php#L133-L148

should all get moved to after line 93 and before the closing brace on line 94.

**Comment by torvista** [comment]
I would agree with that.

I would point out that just previous to that  block, is a method to add some custom processing to this file.
https://github.com/zencart/zencart/blob/88cb37d8991ed4c2c6b1e70d83ba4a1e0ca32329/includes/modules/pages/product_info/main_template_vars.php#L127-L131
So anything in that file that also expects a product_id should clause that out based on $product_not_found being true.

**Comment by drbyte** [comment]
Maybe just the closing `}` on line 94 needs to be moved down to line 152?

**Comment by proseLA** [comment]
> Maybe just the closing `}` on line 94 needs to be moved down to line 152?

that works as well....

**Comment by scottcwilson** [comment]
Closing as fixed by #4408
