### ISSUE TITLE
Change template default to use newer icons

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4401]
We have more up to date icons in responsive_classic.  But people who build their own template don't benefit from them unless they copy these files over.  We could make them the default with these steps: 

- copy the icons from ./includes/templates/responsive_classic/images/icons/ into ./includes/templates/template_default/images/icons/
- change includes/languages/english/icon_names.php to refer to the .png files.

we would retain the old .gif icons for older templates but the newer ones would be the default moving forward. 

Happy to do this, just want it approved first.

**Comment by dennisns7d** [comment]
Some tweeking may be in order to the zenCssButton function in includes/functions/html_output.php. It appears that it assumes the $image is a GIF when extracting the basename.

**Comment by drbyte** [comment]
> Some tweeking may be in order to the zenCssButton function in includes/functions/html_output.php. It appears that it assumes the $image is a GIF when extracting the basename.

Done in 5e092b3d152ff9780b0914ae2d9c46051ee25e0a
