### ISSUE TITLE
Pass also the current product information to the observers for NOTIFY_ADMIN_PROD_LISTING_DATA

### ISSUE THREAD

**Issue by marco-pm** [zencart/zencart#4403]
Right now only the `$extra_data` parameter is passed to the observers for the `NOTIFY_ADMIN_PROD_LISTING_DATA_B4_QTY` and `NOTIFY_ADMIN_PROD_LISTING_DATA_AFTER_QTY` notifiers.
This is not very useful since this way the observer doesn't know the current product id, therefore it cannot extract specific data from the database to be shown in the admin product listing for each product.
The product id should then be passed as parameter. Even better, you could pass it the entire `$product` array, which would also include additional data already extracted thanks to the `NOTIFY_ADMIN_PROD_LISTING_PRODUCTS_QUERY` notifier.

**Comment by drbyte** [comment]
Agreed.
In the v158 branch it does:
```php
              $zco_notifier->notify('NOTIFY_ADMIN_PROD_LISTING_DATA_B4_QTY', $product, $extra_data);
```
```php
              $zco_notifier->notify('NOTIFY_ADMIN_PROD_LISTING_DATA_AFTER_QTY', $product, $extra_data);
```

**Comment by marco-pm** [comment]
You're right, it was already done in #4239 ! I forgot to check the v158 branch 😓
Thanks!

**Comment by mc12345678** [comment]
Note though that even without it being sent in the notifier, `$product` is also accessible as a global variable (coding style dependent) that could be used/accessed. This assumes that somehow `category_product_listing.php` isn't being accessed from within a function or other object that takes the file out of global scope or prevents access to that variable.
