### ISSUE TITLE
Admin: expand options for Disable Category

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4406]
Prompted by the need to examine this to resolve a current bug,
https://github.com/zencart/zencart/issues/4405

how about expanding the associated options too?

For example, for a category with no subcategories:
1 – disable this category.  Leave all product’s status unchanged.
2 – disable this category and included master products.
3 - disable this category, included master products and linked products.

For example, for a category with subcategories:
1 – disable this category only.
2 - disable this category and subcategories. Leave all product’s status unchanged.
3 - disable this category, subcategories and included master products.
4 - disable this category, subcategories, master products and linked products.

And anything else to add to someone's workload?

**Comment by scottcwilson** [comment]
To be clear, the semantics of (1) would be just that the category doesn't show up in the sitemap or the categories sidebox?  Individual products in that category would still be accessible by direct reference or through search? 

It might help sell this idea if you were to flesh out the different use cases.
