### ISSUE TITLE
v158 Undefined method outputMessageList

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#4416]
https://github.com/zencart/zencart/blob/1b73700e1be6648d8de614d3829eb4ba72120667/includes/classes/ViewBuilders/PluginManagerController.php#L123

The method called above, does not appear to exist anywhere. Plans/thoughts? Should it be localized to includes/classes/ViewBuilders/PluginManagerController.php or is it going to be somewhere in the "stack up" of other accessed resources?

Discovered while I was trying to add install issue "messages" as to why the installation was not successful using plugins installer related code and came across the following fatal error (fyi, mydebug file name doesn't identify it as anything "special": myDEBUG-adm-YYYYMMDD-HHMMSS-RANDOM.log):
````
[Date Time TimeZone] PHP Fatal error:  Uncaught Error: Call to undefined method Zencart\ViewBuilders\PluginManagerController::outputMessageList() in /rootPath/includes/classes/ViewBuilders/PluginManagerController.php:123
Stack trace:
#0 /rootPath/includes/classes/ViewBuilders/BaseController.php(37): Zencart\ViewBuilders\PluginManagerController->processActionDoInstall()
#1 /rootPath/admin/plugin_manager.php(89): Zencart\ViewBuilders\BaseController->processRequest()
#2 /rootPath/admin/index.php(11): require('/rootPat...')
#3 {main}
  thrown in /rootPath/includes/classes/ViewBuilders/PluginManagerController.php on line 123
````
While doesn't really matter in a "code doesn't exist" situation: PHP 8.0 and haven't (yet) enabled strict mode.

**Comment by brittainmark** [comment]
@carlwhat fix [here](https://www.zen-cart.com/showthread.php?228868-zc_plugin-zen-cart-1-5-8-missing-method-PluginManagerController-outputMessageList()&p=1388924#post1388924) works.

modify includes/classes/ViewBuilders/BaseController.php

add 
```
public function outputMessageList($errorList, $errorType)
    {
        if (!count($errorList)) {
            return;
        }
        foreach ($errorList as $error) {
            $this->messageStack->add_session($error, $errorType);
        }
    }  
```

**Comment by proseLA** [comment]
based on the v157 implementation, it seems that the carlwhat (aka me) fix referenced above puts it in the right place. 

i think this is a method that was simply missed as part of a conversion.
