### ISSUE TITLE
Fatal error: Uncaught TypeError: mysqli_num_rows(): Argument #1 ($result) must be of type mysqli_result, bool given 

### ISSUE THREAD

**Issue by arman77262** [zencart/zencart#4417]
Please Help Me to Solve It
![code](https://user-images.githubusercontent.com/28687897/126132187-2a596127-84b9-474f-9b99-cc0be362c3d2.png)
![error](https://user-images.githubusercontent.com/28687897/126132206-b0c5117f-15cd-45dc-89a4-c60e3cf19da2.png)

Fatal error: Uncaught TypeError: mysqli_num_rows(): Argument #1 ($result) must be of type mysqli_result, bool given in E:\xampp\htdocs\pweb\classes\ChangePassword.php:37 Stack trace: #0 E:\xampp\htdocs\pweb\classes\ChangePassword.php(37): mysqli_num_rows(false) #1 E:\xampp\htdocs\pweb\admin\password-change.php(9): ChangePassword->PasswordChange(Array) #2 {main} thrown in E:\xampp\htdocs\pweb\classes\ChangePassword.php on line 37

-----------------Code------------------

<?php 

    include_once '../lib/Database.php';
    include_once '../helpers/Format.php';

    class ChangePassword{

        private $db;
        private $fr;

        public function __construct()
        {
            $this->db = new Database();
            $this->fr = new Format();
        }

        public function PasswordChange($data){

            

            $email = $this->fr->validation($data['email']);
            $newpassword = $this->fr->validation(md5($data['password']));
            $c_password = $this->fr->validation(md5($data['c_password']));
            $v_token = $this->fr->validation(md5($data['v_token']));

            if (empty($v_token)) {
               $error = "Token Is Not Avliable";
                return $error;
            }else{
                if (empty($email) || empty($newpassword) || empty($c_password)) {
                    $error = "Filds Are Must Not Be empty";
                    return $error;
                }else{
                    $token_query = "SELECT v_token FROM tbl_user WHERE v_token='$v_token'";
                    $token_result = $this->db->select($token_query);

                    if (mysqli_num_rows($token_result) > 0) {
                        echo $token_result;
                    }else{
                        $error = "Invalid Token";
                        return $error;
                    }
                }
            }

        }

    }

?>

**Comment by scottcwilson** [comment]
This is not Zen Cart.

**Comment by drbyte** [comment]
Looks like your query is failing, thus you're getting a boolean (probably `false`, due to the failure) and thus there is nothing to parse.

And yes, as was mentioned, your code isn't related to Zen Cart, so you appear to be posting in the wrong github project.
