### ISSUE TITLE
zen_field_length cannot handle DateTime fields

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4419]
Running `$db->MetaColumns(TABLE_CUSTOMERS);` returns, for the field `customers_dob` the values 

```
[CUSTOMERS_DOB] => queryFactoryMeta Object ( [type] => datetime [max_length] => )
``` 

So calculations done on `max_length` such as the one in `zen_field_length` fail and generate a PHP warning. 

This is an issue because files like `includes/templates/template_default/templates/tpl_modules_create_account.php` do 

```
<?php echo zen_draw_input_field('dob','', zen_set_field_length(TABLE_CUSTOMERS, 'customers_dob', '20') . ' id="dob"
...
```

**Comment by drbyte** [comment]
Already resolved.

https://github.com/zencart/zencart/commit/3e0eceacccf1faf75d84d9fea8d1dde5fdf7aa2d
https://github.com/zencart/zencart/commit/fadade0e55e79f00bab24826c546123327345d07
