### ISSUE TITLE
When IS_ADMIN_FLAG === true but catalog side files should naturally be loaded?

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#4434]
Trying to possibly address an issue; however, one way of correcting it is to detect if `IS_ADMIN_FLAG` is true from a file that is stored in the catalog. The file is always accessed when using either the admin or catalog. Part of the intent of the catalog file is to then reach out to other files based on being accessed by the admin "fileset" or the catalog "fileset". 

So, the question is, when might `IS_ADMIN_FLAG` be "officially" set to true (by overall design/need), a catalog side file be accessed, and as a result that strictly only catalog files be loaded? E.g. does one of the plugins that support the admin being the customer cause this condition? Otherwise, should something session related be evaluated?

This potentially relates to issue #4432.

**Comment by scottcwilson** [comment]
When you go to Admin > Modules > Payment | Shipping | Order Total, catalog side files for the associated module type are loaded.  Does this answer your question?  Otherwise I am not sure what you are asking.
