### ISSUE TITLE
order confirmation email html, onetime charge table layout

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4446]
ZC158, with value for onetime charge
`<tr>`
`<td class="product-details" align="right" valign="top" width="30">1&nbsp;x</td>`
`<td class="product-details" valign="top">FS365 5L [out of stock temporarily] (SO-SO-0045) </td>`
`<td class="product-details-num" valign="top" align="right">37,49&euro;</td></tr>`
`<tr><td class="product-details">   	*onetime charges = </td>`
`<td>148,83&euro;</td></tr>`

Note the product details are three columns, but the onetime line is two columns.
I assume the first onetime column should have colspan=2.

**Comment by scottcwilson** [comment]
Please PR

**Comment by dbltoe** [comment]
It might also need a slightly different class so CSS can handle formatting without adjusting the others.
Something like .product-details-2col maybe?

**Comment by scottcwilson** [comment]
@neekfenwick please note in #5499

**Comment by neekfenwick** [comment]
> @neekfenwick please note in #5499

No problem, thanks.

**Comment by scottcwilson** [comment]
@torvista Please PR or close.
