### ISSUE TITLE
[To Do] PHP 8.1 compatibility

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#4449]
The following will need to be addressed for PHP 8.1 compatibility.

**Deprecated in PHP 8.1:**
- [x] `strftime()`. Ref: https://wiki.php.net/rfc/deprecations_php_8_1#strftime_and_gmstrftime
  _**Impact**: Used extensively. Alternatives could be messy._
  Probably best to retire-and-replace `ADMIN_NAV_DATE_TIME_FORMAT`, `DATE_FORMAT_LONG`, `DATE_FORMAT_SHORT` constants with new names since format syntax will likely be different.
  Also, affects all (including non-core) credit card payment modules which display a dropdown of month/year selections.
 
- [x] `FILTER_SANITIZE_STRING`. Ref: https://wiki.php.net/rfc/deprecations_php_8_1#filter_sanitize_string
  _**Impact**: 2 use-cases, which can probably be easily rewritten._

**Changed in 8.1:**
- [x] `htmlspecialchars(), htmlentities(), htmlspecialchars_decode(), html_entitity_decode() and get_html_translation_table()` now use `ENT_QUOTES | ENT_SUBSTITUTE` rather than `ENT_COMPAT` by default. This means that `'` is escaped to `&#039;` while previously it was left alone. Additionally, malformed UTF-8 will be replaced by a Unicode substitution character instead of resulting in an empty string. Ref https://news-web.php.net/php.internals/112782
  _**Impact**: There are only a half-dozen places where no default is specified. Adding specificity is probably straightforward._

- [x] Changed default `mysqli` Error Mode from `silent` to `exception`. Ref: https://wiki.php.net/rfc/mysqli_default_errmode
  _**Impact**: investigation required. Simply overriding the default in `query_factory` may be enough._

**Unrelated to official core code (but may affect some plugins, like image-handler):**
- [x] `file_info` resources converted to objects (started in 8.0, more in 8.1). Ref https://github.com/php/php-src/commit/b85f0d1cd0cc49ad339b8129c3d45181b56eff24

**Comment by drbyte** [comment]
strftime() | date_format()
---- | ----
`%B` | `F`
`%T %x` | `H:i:s` followed by locale-formatted date, like 02/05/09
`%H %x` | `H` followed by locale-formatted date eg: 02/05/09
`%H` | `H`
`%x` | (no matching pattern for locale-formatted date)
`%b %y` | `M y`
`%b` | `M`
`%a %d` | `D d`
`%Y-%m-%d %H:%M:%S` | `Y-m-d H:i:s`
`%A %d %B, %Y` | `l d F, Y`
`%B - (%m)` | `F - (m)`
`%y` | `y`
`%Y` | `Y`
`%B, %Y` | `F, Y`
`%m` | `m`

**Comment by proseLA** [comment]
any thought to moving towards storing all date time stamps as a unix timestamp `int(11)` in the database?  

big refactor, but is that not the direction that php seems to be going considering they are deprecating `strftime`.

**Comment by drbyte** [comment]
> any thought to moving towards storing all date time stamps as a unix timestamp `int(11)` in the database?
> 
> big refactor, but is that not the direction that php seems to be going considering they are deprecating `strftime`.

Hm, that is definitely a huge refactoring. I'm not sure it's needed. 
If it were impossible to convert from MySQL datetime/time formats then it'd be more critical, but that's not changing.

**Comment by scottcwilson** [comment]
Can we just use `date('F')` instead to build a list of dates?

**Comment by proseLA** [comment]
> For the `strftime` deprecation, perhaps it's time to migrate the language definitions for months' names into the (er) `languages` table. We could then build on that, providing a `zen_get_monthname` function.

i have no idea why this is needed.  php has so many options for dates including internationalization.  as to whether we want to provide a code in the languages table for international date formatting, that approach seems reasonable.

> Can we just use `date('F')` instead to build a list of months?

i am a fan of doing this idea.  one can see the recent commit i made to my payment module:

https://github.com/proseLA/authorizenet_cim/commit/35a0bfaaf6b8eae9f90e32cfac034b2b834043c9

**Comment by scottcwilson** [comment]
I would be happy to reassign this ticket if someone would like to step up and volunteer.

**Comment by proseLA** [comment]
done.  it affects these items here as well:

https://github.com/zencart/zencart/blob/64e09214fd5341622ebf55a2fd22c595b146f7cb/admin/includes/languages/lang.english.php#L17-L21

i would propose changing the name to anything that uses the php `date` to start with `PHP_DATE` as seem in line 21.  which would change line 19 to: `PHP_DATE_FORMAT`.  i think the short is not needed.  short is assumed.  and we can then use `PHP_DATE_FORMAT_LONG`.

**Comment by scottcwilson** [comment]
How about I just add PHP_DATE_FORMAT as another define?  These constants are use by plugins sometimes.
Can you note your language file needs and I'll get them merged in?  I'm still changing this file and I'd like to avoid conflicts.

**Comment by torvista** [comment]
Is it being borne in mind the eternal format issue:
DD/MD/YYY or MM/DD/YYYY
to have some easy way to set that without editing language files as is the case now?

**Comment by proseLA** [comment]
> Is it being borne in mind the eternal format issue: DD/MD/YYY or MM/DD/YYYY to have some easy way to set that without editing language files as is the case now? Or is that considered easy enough?

i hate dates.  but i am willing to take part of this problem on...

editing language files will remain the option and will continue to address the format issue.

the only real (potentially big) issue is the language part of it that i think lat9 brings up.  and whether we want to provide months and days in the chosen language of the store.  which the php date functions seem to provide.  although tracking down all of the international codes may be a little work...

**Comment by lat9** [comment]
> Can we just use `date('F')` instead to build a list of months?

As identified in the above PR, the PHP `date` function does not provide internationalization of the month and day names.

**Comment by proseLA** [comment]
i have looked at this internalization issue.  IMO this type of refactor would be best suited to a class file, similar to the currencies class.

**Comment by scottcwilson** [comment]
In fairness, `admin/includes/languages/lang.english.php` has defines for each month.  Maybe they should be shared.

**Comment by proseLA** [comment]
which should also be retired.  refactoring should hopefully involve less code not more.

those defines are used for `zen_draw_date_selector` which is only used in coupon_admin.  why should the coupon_admin not be refactored to use `datepicker` similar to so many other scripts?  i think that's more fair.

```
charmes: # grepp -l datepicker
admin/banner_manager.php
admin/includes/javascript/jquery-ui-i18n.min.js
admin/includes/javascript_loader.php
admin/includes/auto_loaders/config.core.php
admin/includes/functions/datepicker.php
admin/includes/modules/product_free_shipping/collect_info.php
admin/includes/modules/product_music/update_product.php
admin/includes/modules/product_music/collect_info.php
admin/includes/modules/product/collect_info.php
admin/includes/modules/document_general/collect_info.php
admin/includes/modules/update_product.php
admin/includes/modules/document_product/collect_info.php
admin/specials.php
admin/featured.php
admin/product.php
admin/products_price_manager.php
charmes: # grepp -l zen_draw_date_selector
admin/includes/functions/html_output.php
admin/coupon_admin.php
```

**Comment by scottcwilson** [comment]
> why should the coupon_admin not be refactored to use datepicker similar to so many other scripts?  

I am very open to this if you are willing to do it.  As you said in #4363, it would be nice to converge around datepicker.

**Comment by proseLA** [comment]
despite #4553 being closed, i have not given up on this problem.  as i stated above, i believe a class file is the way to handle it.  the class file could be something such as:
```
<?php

    class zcDate
    {
        var $language_code;

        function __construct()
        {
            $this->language_code = setlocale(LC_TIME, 0);
        }

        function output(string $string = 'MMMM/dd/yyyy', int $timestamp = 0)
        {
            if ($timestamp === 0) {
                $timestamp= time();
            }
            $this->dateObject = datefmt_create(
                $this->language_code,
                IntlDateFormatter::FULL,
                IntlDateFormatter::FULL,
                date_default_timezone_get(),
                IntlDateFormatter::GREGORIAN,
                $string
            );
            return $this->dateObject->format($timestamp);
        }
    }
```
within `application_top` or somewhere of your choosing, we could create a var for use such as `$zcDate = new zcDate();` so that it is globally available.  we could then replace all `strftime` calls with `$zcDate->output(FORMAT, TIMESTAMP);`.  we could also eliminate the 12 months in all language files.

what would need to be decided is how to set the language_code in the `_construct` above.  and whether that should be a new constant or how that gets set. 

thoughts?

**Comment by lat9** [comment]
Where's the function `datefmt_create` defined?  Additionally, I'd be concerned that the definition of the `LC_TIME`` constant is

> LC_TIME for date and time formatting with [strftime()](https://www.php.net/manual/en/function.strftime.php)

What happens when strftime is fully removed?  Will that constant be removed as well?

**Comment by proseLA** [comment]
> Where's the function `datefmt_create` defined? Additionally, I'd be concerned that the definition of the `LC_TIME` constant is
> 
> > LC_TIME for date and time formatting with [strftime()](https://www.php.net/manual/en/function.strftime.php)
> 
> What happens when strftime is fully removed? Will that constant be removed as well?

i'm not really sure i understand the question.  the `datefmt_create` function is part of the `IntlDateFormatter` (https://www.php.net/manual/en/intldateformatter.create.php) which requires PECL intl >= 1.0.0.  as such this page: 

https://docs.zen-cart.com/user/first_steps/server_requirements/#php-extensionsmodules-used-by-zen-cart 

needs to be updated to reflect the `intl` extension is now required.  either that or the class would need to be updated to test for that function and be updated accordingly.

> what would need to be decided is how to set the language_code in the `_construct` above. and whether that should be a new constant or how that gets set.

with regards to the `LC_TIME` constant, that needs to be set per process with `strftime`.  as i stated above, this could get set in the `_construct` function, and the question remains whether we establish a new ZC constant (probably best) or some other route.  ie, contruct method gets changed to something like:

```
function __construct(string $lc = '')
        {
            if (empty($lc)) {
                $lc = NEW_ZC_LANGUAGE_CODE_CONSTANT;
            }
            $this->languageCode = $lc;
        }
```
using the above, we could then override the constant as needed.  code:
```
    $zcDate = new zcDate();
    echo "----777---->" . $zcDate->output('MMMM dd, yyyy') . "<---------<br>";
    echo "----month-1---->" . $zcDate->output('MMMM', 1609488000) . "<---------<br>";

    $zcDate = new zcDate('ca_ES');
    echo "----888---->" . $zcDate->output('MMMM dd, yyyy') . "<---------<br>";
    echo "----month-1---->" . $zcDate->output('MMMM', 1609488000) . "<---------<br>";
```
output:
```
----777---->February 04, 2022<---------
----month-1---->January<---------
----888---->de febrer 04, 2022<---------
----month-1---->de gener<---------
```
does that help answer your question?

**Comment by proseLA** [comment]
in looking at this further, i am convinced this is the proper way to go.  less functions and more classes.

unfortunately, the intl date formatter and `date` method use different format strings.  and if we wanted to account for both types, it represents a bit more work.

**Comment by scottcwilson** [comment]
@lat9 Do you feel this has been addressed adequately or is there more work yet to be done?

**Comment by lat9** [comment]
Not quite; FILTER_SANITIZE_STRING is still used within zc_install/ajaxValidateAdminCredentials.php and I'm still checking the `htmlspecialchars` et al changes.
