### ISSUE TITLE
ZC158 Admin, category_product_listing: disable category icon does not disable category

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4455]
Irrespective of the options chosen in the subsequent infobox, category remains enabled.

**Comment by torvista** [comment]
The parameters in this new function are opposite to that used in the function call:
https://github.com/zencart/zencart/blob/602e7dd9b828af36642e49d0cf0acd81c5a869d7/includes/functions/functions_categories.php#L1139

**Comment by mc12345678** [comment]
Ehh?
1.5.7:
https://github.com/zencart/zencart/blob/2aae461926f1082dc33cd6411229d17484ebe1cb/admin/category_product_listing.php#L56-L79
1.5.8:
https://github.com/zencart/zencart/blob/35b347e7b04903ed50b4c1272f957bec3a53307f/admin/category_product_listing.php#L60-L77
with function:
https://github.com/zencart/zencart/blob/35b347e7b04903ed50b4c1272f957bec3a53307f/includes/functions/functions_categories.php#L1139-L1146

To me, those look programmatically the same...

I didn't get a chance to test/review this on a test site yet, but considering I've seen that you are using/testing with PHP 8.0, I was wondering if there is/was something in the logic tests in the above lines 73 and 75 or perhaps in some sort of sanitization upstream that is causing a change to the data for comparison to affect this section of code... I don't see that categories_status is in some way sanitized to possibly change its data type that might cause an unusual conversion, but seems either something new about PHP 8.0 or there is some other code change that is causing this (repeatable) issue.

**Comment by lat9** [comment]
Why not just change the usage of the current `zen_set_category_status` to supply the arguments in the order expected by that function?

**Comment by mc12345678** [comment]
> Why not just change the usage of the current `zen_set_category_status` to supply the arguments in the order expected by that function?

So, was trying to think from different perspectives about the "solution", fortunate thing is that 1.5.8 is not yet considered production ready. 

On the one hand, if either of the two involved files were used/addressed/modified in a plugin, the one more likely modified would be `category_product_listing.php` where modifying it "en mass" may affect multiple sites or plugins (again not yet really applicable though in 1.5.8 as a non-production product). The function's parameters, well again may affect plugins if they used the parameters as expected by the function compared to how they were placed in the admin file's code. 

It is for these two reasons I then suggested a third option which was a second function that accomplishes the same task but with a different name (perhaps it could just be an alias function for the original where the parameters are swapped in calling the original function). 

Whatever, I originally misunderstood the statement (and hard work) of the second post in this thread. It wasn't until I forced the posted code and reread it that I realized what was being said/suggested and actually happening. I have no existing nor foreseen code that would be affected in by any of these three solutions or any that I can think of.

**Comment by torvista** [comment]
> Why not just change the usage of the current `zen_set_category_status` to supply the arguments in the order expected by that function?

Possibly because someone may prefer the id as the first parameter, being the "most important" one.
Since this is not used in production, no problem to swap the parameters in the calling file, I would say.

**Comment by lat9** [comment]
> 
> 
> > Why not just change the usage of the current `zen_set_category_status` to supply the arguments in the order expected by that function?
> 
> Possibly because someone may prefer the id as the first parameter, being the "most important" one.
> Since this is not used in production, no problem to swap the parameters in the calling file, I would say.

You misunderstood my (poorly written) comment.  What I said is, I think, what you said.  Keep the function intact and `correct` the calling usage.

**Comment by proseLA** [comment]
> > > Why not just change the usage of the current `zen_set_category_status` to supply the arguments in the order expected by that function?
> > 
> > 
> > Possibly because someone may prefer the id as the first parameter, being the "most important" one.
> > Since this is not used in production, no problem to swap the parameters in the calling file, I would say.
> 
> You misunderstood my (poorly written) comment. What I said is, I think, what you said. Keep the function intact and `correct` the calling usage.

i agree.  category first, then status.
