### ISSUE TITLE
zc157: Delete-product pre-selects master-category-delete checkbox

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4465]
If an admin chooses to delete a linked product, a confirmation screen is displayed.  That screen includes checkboxes for the product's master category and each of its linked ones.  When deleting a linked product, IMO, only the linked category should be pre-selected, but the master-category choice is also selected:
![image](https://user-images.githubusercontent.com/2685585/133891475-bda9bfa9-1f46-4940-992b-b60c430536ce.png)

**Version**
Zen Cart version: 157c

Interestingly enough `/admin/includes/modules/delete_product.php` already has the notion of not also removing the product from its master category, but the logic is the reverse of what I'd expected:

```php
<?php

/**
 * @copyright Copyright 2003-2020 Zen Cart Development Team
 * @copyright Portions Copyright 2003 osCommerce
 * @license http://www.zen-cart.com/license/2_0.txt GNU Public License V2.0
 * @version $Id: Steve 2020 Apr 20 Modified in v1.5.7 $
 */
if (!defined('IS_ADMIN_FLAG')) {
    die('Illegal Access');
}

$product_categories_string = '';
$product_categories = zen_generate_category_path($pInfo->products_id, 'product');
if (!isset($category_path)) {
    $category_path = '';
}
$preselect_master_category = true; // set to false to prevent accidental deletion
for ($i = 0, $n = count($product_categories); $i < $n; $i++) {
    $category_path = '';
    for ($j = 0, $k = count($product_categories[$i]); $j < $k; $j++) {
        $category_path .= $product_categories[$i][$j]['text'];
        if ($j + 1 < $k) {
            $category_path .= '&nbsp;&gt;&nbsp;';
        }
    }
    if (count($product_categories) >= 1 && (int)zen_get_parent_category_id($pInfo->products_id) === (int)$product_categories[$i][count($product_categories[$i]) - 1]['id']) {
        $product_categories_string .= '<div class="checkbox text-danger"><label><strong>' . zen_draw_checkbox_field('product_categories[]', $product_categories[$i][count($product_categories[$i]) - 1]['id'], $preselect_master_category) . $category_path . '</strong></label></div>';
        $product_master_category_string = $category_path;
    } else {
        $product_categories_string .= '<div class="checkbox"><label>' . zen_draw_checkbox_field('product_categories[]', $product_categories[$i][count($product_categories[$i]) - 1]['id'], true) . $category_path . '</label></div>';
    }
}
```

**Comment by torvista** [comment]
Related
https://github.com/zencart/zencart/pull/2831

followed by
https://github.com/zencart/zencart/issues/3160

**Comment by lat9** [comment]
OK, but why the reversion to enabling the master-category to be removed too?

**Comment by torvista** [comment]
So, what is the consensus on a product delete?

My opinion:  
If a product is **unlinked** (only exists in one category/master category): that category is preselected for deletion / Delete is final.  Infobox text should indicate this.

If a product **is linked** (exists in multiple categories + master category): only the linked categories are preselected / Delete will remove the links unless the master category is manually selected. 
The display should have the master category first in the list, shown highlighted and unselected.  Infobox text should clarify this.

**Comment by scottcwilson** [comment]
I agree with Cindy. 
The help text agrees with her too.  ("The Master category is de-selected ...")

PR coming.
