### ISSUE TITLE
ZC158, currencies: PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string * string classes/currencies.php

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4475]
There is a calculation: https://github.com/zencart/zencart/blob/35b347e7b04903ed50b4c1272f957bec3a53307f/includes/classes/currencies.php#L96-L97

but $rate ($this->currencies[$currency_type]['value']) is a string:
https://github.com/zencart/zencart/blob/35b347e7b04903ed50b4c1272f957bec3a53307f/includes/classes/currencies.php#L32-L40
I assume value should be just cast to float.

**Comment by torvista** [comment]
1) Casted "value" to float.
2) Where "value" is used in a calculation, I casted the other parameter in the method parameter definition and the few calls to that function.
I assume restricting what is passed to functions is something that should be implemented for new code and when refactoring. 

There is a mass of changes that would cascade out just from casting this class's methods parameters, but it has to happen sometime.

For review:
https://github.com/torvista/zencart/tree/currencies_float

**Comment by lat9** [comment]
Perhaps, rather than casting to a float (which has all kinds of penny-off rounding implications), we should have a `zen_convert_currency_value` function that simply 'sanitizes' a supposed currency (string)input based on the currently active currency?

**Comment by torvista** [comment]
I couldn't say. There are so many instances of rounding errors reported over the years.
Perhaps there needs to be test routines using documented scenarios where the current default code produces errors....ask the forum.

**Comment by lat9** [comment]
Was this, by chance, related to the change made for #4870 and #4871?

**Comment by torvista** [comment]
I see that of these changes in the PR,  in my site I only have the first float implemented in currencies. I'll remove that/revert to original code and see what occurs in light of the recent changes.
