### ISSUE TITLE
Zone restricted shipping modules won't show up in estimator unless state dropdown is used

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4476]
**Describe the bug**
Prior to login, the shipping estimator on the checkout page must have the state and zip code filled in to get an accurate quote.  

(This assumes Admin > Configuration > Shipping > Shipping Estimator Display Settings for Shopping Cart is set to 2)

This occurs with the Bootstrap template or any template whose tpl_modules_shipping_estimator.php respects the value of ACCOUNT_STATE_DRAW_INITIAL_DROPDOWN when painting the shipping estimator page. 

**Version**
Zen Cart version: 1.5.7c
PHP version: 7.4

**To Reproduce**
Set Admin > Configuration > Customers > State - Always display as pulldown? to FALSE.
Enable the flat rate shipping module, with no Shipping Zone set.
Place an item in the cart, then go to the shopping cart page and enter state as FL and zip as 33773.
Observe that Flat Rate shipping is quoted.

Using the instructions in 
https://docs.zen-cart.com/user/locations/zone_definitions/
create the Zone for the US Continental 48 States & DC.
Set the Shipping Zone in the Flat module to this new zone.

Update the shopping cart page and observe that Flat no longer shows.

Set Admin > Configuration > Customers > State - Always display as pulldown? to TRUE.
Refresh the shopping cart, and set the state dropdown to FL, zip as 33773, then press Update for the shipping estimator.

Observe that Flat now shows.

(Note: once you have done this, you must reset Admin > Configuration > Customers > State - Always display as pulldown? to FALSE, then  login and logout and  to reset the system state, otherwise pulldown = false will appear to work because SESSION data has been set.) 

**Expected behavior**
Flat should show in both cases.

Possible solution: Update the template file tpl_modules_shipping_estimator.php and

**Comment by piloujp** [comment]
This issue is identical to issue #5672 which was fixed by PR #5712 (fixing this old issue too).

**Comment by scottcwilson** [comment]
Thanks!
