### ISSUE TITLE
'storepickup' not identified as cheapest, even if it's the only method available

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4478]
As identified in [this](https://www.zen-cart.com/showthread.php?220781-One-Page-Checkout-Support-Thread&p=1384427#post1384427) Zen Cart posting, the `storepickup` method is never identified as the cheapest method ... even if it's the only method available.

`/includes/classes/shipping.php` is enforcing this restriction, which results in no shipping-method being selected for an order and wrecks havoc with 'One Page Checkout' (and possibly other plugins).

The issue is present in the zc157 series (and possibly earlier) as well as the current zc158 file-set.

Suggest changing (and backporting to zc157) `/includes/classes/shipping.php`'s cheapest method to enable storepickup to be quoted as the cheapest if it's the only shipping module available.

**Comment by scottcwilson** [comment]
I would merge a 1.5.8 PR that makes this change.
