### ISSUE TITLE
admin, product, preview_info should have notifiers for extra product fields

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4490]
While extra fields can be added to the product admin page, there are no notifiers in the preview_info page.

This prevents those new fields 
a) being displayed on the preview page
b) being retained for auto-filling those fields on the product admin page when the Back button is used (for a new product with no id yet).

**Comment by scottcwilson** [comment]
@torvista would you be willing to build a PR?

**Comment by torvista** [comment]
ok
