### ISSUE TITLE
improve performance in admin -> orders

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#4500]
https://github.com/zencart/zencart/blob/35b347e7b04903ed50b4c1272f957bec3a53307f/admin/orders.php#L904-L908

the above query will be returned based on the primary index.  which is the `orders_status_history_id` field.

the primary index and the `date_added` field should mimic their sort and therefore the sort is not required.

i would be interested in examples where those 2 fields do not sort the same; as to whether we should account for those edge cases is a different story.

**Comment by scottcwilson** [comment]
Tested on a large (80K orders) table and didn't see a noticeable difference.

**Comment by proseLA** [comment]
> Tested on a large (80K orders) table and didn't see a noticeable difference.

if i may be so bold, what was your methodology for said test?  and resulting measurements?

i ran the following 3 queries 3 times on a table with 187,953 rows.  the results are below each query.

```
select * from orders_status_history;
```
0.183 sec
0.161
0.161
```
select * from orders_status_history order by date_added;
```
0.260 sec
0.224
0.227
```
select * from orders_status_history order by orders_status_history_id;
```
0.156 sec
0.146
0.162

**Comment by scottcwilson** [comment]
I just loaded the admin > orders page.  The numbers you are posting about would not be noticeable to the human eye.  They're fine improvements, they just don't buy you a faster orders page load.

**Comment by proseLA** [comment]
that's because i am testing on an isolated server speced out reasonably well.  on a shared hosting platform, a 40% reduction in this one query might be helpful.  might not.

i think it is something that people should be aware of as speed, with numerous queries on a single page, is always a concern.  and finding incremental improvements that do NOT affect the operation is, IMO, always worth wild.

i am a bigger fan of changes like this than i am of changing to UPPERCASE in mysql statements to conform to some standard, that while admirable, we never seem to accomodate.  but again, this is merely a personal preference.

**Comment by torvista** [comment]
Everything adds up.
My test showed .0058 to .011 improvement on 35k records.
Seems a no-brainer to implement every performance-related PR/no discussion really necessary if proven.

**Comment by torvista** [comment]
Additionally, should not 
zen_db_input($oID)
be quoted or cast to integer?

**Comment by proseLA** [comment]
> Additionally, should not zen_db_input($oID) be quoted or cast to integer?

i do not think so.

the refactoring of this script, and specifically of `$oID` is an interesting idea.  looking at this section of code:
https://github.com/zencart/zencart/blob/35b347e7b04903ed50b4c1272f957bec3a53307f/admin/orders.php#L46-L61
makes my head spin.

all of the code could be simplified, and it is already cast to an integer.  why we are continuously casting to an integer later and putting it back through other `zen_db_` functions, you got me.

**Comment by lat9** [comment]
FWIW, I've started doing some additional sanitization for should-be-int $_GET variables.  Essentially, if the variable `isset` then it should also be of `ctype_digit`, otherwise, I `unset` the associated variable and pretend that it wasn't specified.

**Comment by torvista** [comment]
I wasn't looking at $oID, I was looking at zen_db_input which returns a string so should be quoted.
But if $oID is already an integer, it doesn't need to be passed through that function at all/does not need to be quoted.

**Comment by mc12345678** [comment]
In all this "optimization" discussion, how much of it is server and server configuration independent? In earlier versions of Zen Cart, there was some attempts to use what would appear to be "internal" pointers and "rules" to provide data in a sequence without specifically calling the sequence and when loading followed by reloading the page two different result sets were provided (i.e. initially in sequence, but on second page load (refresh), the order was otherwise). 

What about adding date_added as an index? Besides can not count on the creation date being in sequence with a previous/subsequent sequence id as one may code to change both the value stored and the date instead of "overriding" it by placement of a new/next value as in, oops made a mistake. It seems that the data to be retrieved is intended to be shown/reflect the time stamp sequence not some automatically inserted numerical value which suggests that perhaps an index on the date/time is appropriate here.

**Comment by scottcwilson** [comment]
@proseLA do you want to just extract out the change suggested in the first post and submit as a PR?

**Comment by scottcwilson** [comment]
Thanks @lat9 for the extra sanitization checks.   Looking forward to that PR.
Thanks @proseLA for driving this issue to closure. 
Additional unresolved issues, please open a new ticket and/or PR.
