### ISSUE TITLE
stray strong tag needs removal in admin orders

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#4506]
https://github.com/zencart/zencart/blob/35b347e7b04903ed50b4c1272f957bec3a53307f/admin/orders.php#L893

there is no closing tag for the `strong` element.  the `th` element is already styled.  and i suppose there is potential to add a class as well (if one is very tricky!) with the `align` element.

**Comment by scottcwilson** [comment]
Thanks for this fix.
