### ISSUE TITLE
no need for important in admin stylesheet.css

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#4517]
in a vanilla install, these are the absolute last items in the css chain.  i see no need for the addition of the `!important` inclusion in these elements.  MO, they should be removed; as MO we should attempt to minimize if not eliminate the use of `!important`.

https://github.com/zencart/zencart/blob/da27b8abd1ed623e94a65ed1262fa3d22a5facaa/admin/includes/css/stylesheet.css#L872-L884

**Comment by scottcwilson** [comment]
Have you tested without?  In my experience this is sometimes required when modifying settings from Bootstrap.

**Comment by proseLA** [comment]
> Have you tested without? In my experience this is sometimes required when modifying settings from Bootstrap.

i have now looked at **ALL** of them.  the only one that needs modification is `align-bottom`.  removing the important from there changes the alignment in `admin/options_name_manager.php`.  that rule could be changed to:
```
tbody>tr>td.align-bottom {
  vertical-align: bottom;
}
```
we do not use `align-top` except in a script that, while part of the repo, is an old remnant that could be removed. 

i am of the opinion that `!important` is a crutch that should be avoided.

some info on where these are used.

```
charmes: # grepp -l align-top
admin/includes/css/bootstrap.min.css
admin/includes/css/stylesheet.css
admin/categories.php

charmes: # grepp -l align-middle
admin/banner_manager.php
admin/includes/css/stylesheet.css
admin/specials.php
admin/coupon_admin.php
admin/reviews.php
admin/featured.php
admin/customers.php
admin/option_name.php
admin/ezpages.php
admin/countries.php
admin/downloads_manager.php
admin/manufacturers.php

charmes: # grepp -l align-bottom
admin/includes/css/bootstrap.min.css
admin/includes/css/stylesheet.css
admin/options_name_manager.php

charmes: # grepp -l font-weight-bold
admin/sqlpatch.php
admin/includes/css/stylesheet.css
admin/layout_controller.php
admin/specials.php
admin/featured.php
admin/coupon_restrict.php
admin/orders.php


```

**Comment by scottcwilson** [comment]
Thanks for double checking.  PR as time allows.

**Comment by scottcwilson** [comment]
I could have *sworn* I saw cases where it was required.  I will keep an eye out.

**Comment by dbltoe** [comment]
Have I used it? yes.  Mostly when the existing CSS was too "murky" and a quick addition to something like stylesheet_zcustom.css made sure it was seen.
Is it more of a crutch than tool? Probably
Should it be avoided? Yes  Often it is an excuse to not bother touching existing code.
Interesting article today,  https://www.stefanjudis.com/today-i-learned/the-surprising-behavior-of-important-css-custom-properties/

**Comment by proseLA** [comment]
>  Interesting article today, https://www.stefanjudis.com/today-i-learned/the-surprising-behavior-of-important-css-custom-properties/

apparently the author agrees with me (or I with him):

"I stand by it: it's best to avoid !important and if you really have to use it, consider it very carefully. And honestly, I wouldn't mix !important into custom property values because this surprising "quirk" is very hard to spot!"
