### ISSUE TITLE
157c Undefined index and undefined variable notices in paypalwpp.php 

### ISSUE THREAD

**Issue by daphilli224** [zencart/zencart#4528]
1. Undefined index PHP notice for PAYMENTREQUEST_0_ADDRESSSTATUS in paypalwpp.php on line 1847.
2. Undefined variable notice for country_code3 in paypalwpp.php on lines 1983, 1997, and 2010.
3. Undefined index notice for countries_id in paypalwpp.php on line 2022 (2X).
4. Undefined variable notice for address_book_id in paypalwpp on line 2075.
PayPal Express Checkout Debug Mode set to Log file
Errors appear for virtual products where shipping is not required.

Possible fixes:
1. insert the following prior to setting $step2_payerinfo: if (empty($response['PAYMENTREQUEST_0_ADDRESSSTATUS'])) $response['PAYMENTREQUEST_0_ADDRESSSTATUS'] = '';
2. Initialize $country_code3 along with other default American country-related data after setting $country_code = 223 as follows: $country_code3 = 'USA';
3. test $country1->fields['countries_id'] and $country2->fields['countries_id']) and either bypass the debug output or modify the data output if empty or not set at line 2022. 
4. similarly, test $address_book_id and either bypass the debug output or modify the data output if empty or not set at line 2075.

**Version**
Zen Cart version: 1.5.7c
PHP version: 7.3.27
MySQL version: 8.0.26
Plugins that may be related: None
What older/newer versions were also tested? 1.5.5f

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Set Report all Errors to IgnoreDups and PayPal Express Checkout payment module Debug Mode to Log File
2. Log in to storefront
3. Add virtual product to cart and checkout, selecting PayPal Express
4. Complete payment using PayPal and log out of storefront
5. Check for myDEBUG files in the log directory

**Expected behavior**
No myDEBUG files are expected and desirable

**Screenshots**
If applicable, add screenshots to help explain.

**Debug/Error Logs**
See below.
 
**Devices (please complete the following information):**
 - Operating System: Mac OS 10.15.7
 - Browser: Firefox 95.0.2

**Additional context**

[myDEBUG-20220103-133417-550669.log](https://github.com/zencart/zencart/files/7826517/myDEBUG-20220103-133417-550669.log)

**Comment by daphilli224** [comment]
Additional information is posted in the forum in PayPal Express Checkout Support. Checkout is through the normal route, not through the PayPal Express button. I have not tested with the button.

**Comment by mc12345678** [comment]
Forum link is: https://www.zen-cart.com/showthread.php?228574-Undefined-index-and-undefined-variable-errors-in-paypalwpp

**Comment by scottcwilson** [comment]
@daphilli224 Thanks for this detailed writeup.

**Comment by scottcwilson** [comment]
Any volunteers for this ticket?

**Comment by lat9** [comment]
@daphilli224, I know it's been a while, but do you still have the paypalwpp debugs associated with the issues.

Note also, that it helps to enable **_Configuration :: Logging :: Backtrace on Notice Errors_**, since that give additional 'breadcrumbs' to understand the calling sequence prior to the logged notice.

**Comment by daphilli224** [comment]
Logs are attached. I've also set backtrace on notice errors to yes. Thank you for checking into this issue.
[ipn_1641234883_ELvd9.log](https://github.com/zencart/zencart/files/8647290/ipn_1641234883_ELvd9.log)
[Paypal_CURL_EC-07H75804EC224424U_CYCk1.log](https://github.com/zencart/zencart/files/8647291/Paypal_CURL_EC-07H75804EC224424U_CYCk1.log)
[Paypal_CURL_EC-07H75804EC224424U_sXmV3.log](https://github.com/zencart/zencart/files/8647292/Paypal_CURL_EC-07H75804EC224424U_sXmV3.log)
[Paypal_CURL_EC-07H75804EC224424U_zCbT8.log](https://github.com/zencart/zencart/files/8647293/Paypal_CURL_EC-07H75804EC224424U_zCbT8.log)
[paypalwpp_Paypal_Action_01-03-2022-13-34_a9gT.log](https://github.com/zencart/zencart/files/8647294/paypalwpp_Paypal_Action_01-03-2022-13-34_a9gT.log)
[paypalwpp_Paypal_Action_EC-07H75804EC224424U_AAZK1.log](https://github.com/zencart/zencart/files/8647295/paypalwpp_Paypal_Action_EC-07H75804EC224424U_AAZK1.log)
[paypalwpp_Paypal_Action_EC-07H75804EC224424U_RRCt6.log](https://github.com/zencart/zencart/files/8647296/paypalwpp_Paypal_Action_EC-07H75804EC224424U_RRCt6.log)
