### ISSUE TITLE
#4502 introduces new php notice....

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#4531]
in both of the following examples, the first conditional could be true if `empty($_GET['page']`.  the very following line we are now using that same empty var to assign it to a new var.  that generates a `PHP Notice: Undefined index: page`.

https://github.com/zencart/zencart/blob/7f3d0e06da91bd943af42cbb0fc2eccb6bf7c094/admin/specials.php#L459-L460

https://github.com/zencart/zencart/blob/7f3d0e06da91bd943af42cbb0fc2eccb6bf7c094/admin/featured.php#L371-L372

**Comment by scottcwilson** [comment]
@mc12345678 I think the intention here was `if (!(empty($_GET['page']) ...` wasn't it?

**Comment by mc12345678** [comment]
> @mc12345678 I think the intention here was `if (!(empty($_GET['page']) ...` wasn't it?

No, the intention was to in fact to keep/use `empty()` in the first test. That there were differences between occurrences of the code group (some invoking the notice described above) is/was a direction to address. That additional code adds an interim tracking variable to allow identifying or restoring the original value for some currently unused future situation. I wasn't sure of anyone's use of that variable among the implementations so didn't want to remove without further discussion.

The additional value could be assigned something "appropriate" in these (and perhaps other) uses or it could be removed. While I'm for code simplification I am also for helping the "neighbor" for which this code section that modifies the `$_GET` value(s) may want to evaluate them along the way... Either of these two actions would address the notice that is possibly generated.

By the way, @proseLA what was the use case that generated the notice?

**Comment by proseLA** [comment]
i think i was just clicking around on the pages.  i am away from my development box; once i am back in front of it i can give exact steps to reproduce.  

would not doing
```
$old_page = $_GET['page'] ?? 1;
```
address the issue?

**Comment by mc12345678** [comment]
> would not doing
> 
> ```
> $old_page = $_GET['page'] ?? 1;
> ```
> 
> address the issue?

Unfortunately, no that wouldn't exactly correct the "issue". It wouldn't consistently carry the old/expected value.  further make the need for `$old_page` to not exist because it wouldn't reflect the original value of the page parameter. E.g. a more appropriate tool to capture the old value would be found by:
````php
$old_page = $_GET['page'] ?? null;
````
Again, though that would be if `$old_page` was to be used/kept otherwise that line is not necessary.

**Comment by proseLA** [comment]
@mc12345678

- 23 days ago, you had a PR merged correcting page numbers.
- that PR introduced this new PHP notice/bug.
- i reported this bug.
- you then asked me for a use case that generated this notice.
- this error is so obvious and easy to reproduce.  why would you want a use case scenario for a bug that was introduced by your PR and is so easy to reproduce on one's own?
- in looking at this code, why would we care about this var `$old_page`?  it is not being used anywhere else on this script.  it makes no sense to me.

i am not looking for any answers to my rhetorical questions.  

i find it extremely hard to imagine that you would be unable to reproduce it on your own; or that you would need any extra input from me to resolve said code.

i am a fan of getting rid of code that makes no sense.  this old_page var is never used.  i would drop it.  but its not my section of code.

and considering my stated preference for NOT assigning anything to any `$_GET` var, i really have no desire to look at this code or comment on it any more than i have already done.

**Comment by scottcwilson** [comment]
Using PHP 7.4, when I go to Admin > Catalog > Specials, then page around, I can't repro this issue. 
Likewise featured page.  @proseLA Would you please try to build repro instructions?

**Comment by proseLA** [comment]
```
charmes: # gss
On branch v158
Your branch is up to date with 'origin/v158'.
```

![image](https://user-images.githubusercontent.com/1095136/150368586-7256ca5e-2d8f-46ca-935a-534efa524064.png)

![image](https://user-images.githubusercontent.com/1095136/150368692-e7199842-21db-4c5e-b391-64547e1c3e9f.png)

https://zcdev.com/admin/index.php?cmd=specials
https://zcdev.com/admin/index.php?cmd=specials&sID=27

on the 2nd click the error is reproduced.

i have NO IDEA why we have this var: `$old_page` on any page.  it does not do anything:
```
charmes: # grepp old_page
admin/specials.php:465:                    $old_page = $_GET['page'];
admin/featured.php:378:                    $old_page = $_GET['page'];
admin/category_product_listing.php:783:              $old_page = $_GET['page'];
admin/category_product_listing.php:795:                if ($old_page != $_GET['page']) {
```
referencing a comment from 11 days ago (1/8/2022):
> Again, though that would be if $old_page was to be used/kept otherwise that line is not necessary.

**Comment by scottcwilson** [comment]
Reproduced.  @mc12345678 go to Admin > Catalog > Specials, then click on the product name for one of the specials.

**Comment by scottcwilson** [comment]
@mc12345678 Would you please fix this issue?

**Comment by lat9** [comment]
Noting that a 'simple' replacement in the zc157 branch of /admin/specials.php of
![image](https://user-images.githubusercontent.com/2685585/171050809-e3755b6c-7536-4904-bdc4-c6f44259258f.png)
to
![image](https://user-images.githubusercontent.com/2685585/171050892-3ac7409c-e505-4d9d-bc7a-1e9c8f0a3684.png)

seems to have corrected the issue for that page.  I'm wondering, since the issue affects a couple of pages, whether yet-another admin function would be merited, e.g.

```php
function zen_admin_current_listing_page($sql_query_raw, $getvar_name, $dbfield_name, $listing_max) {
    if (!isset($_GET[$getvar_name])) {
        return 1;
    }
    $page = 1;
    $check_page = $db->Execute($sql_query_raw);
    if ($check_page->RecordCount() > $listing_max) {
        $check_count = 0;
        foreach ($check_page as $item) {
            if ((int)$item[$dbfield_name] === (int)$_GET[$getvar_name]) {
                break;
            }
            $check_count++;
        }
        $page = round((($check_count / $listing_max) + (fmod_round($check_count, $listing_max) !== 0 ? .5 : 0)));
    }
    return $page;
}
```

**Comment by mc12345678** [comment]
1) What about non numeric pages? 
2) Why does this new function return a page value of 1 if `$_GET[$getvar_name]` is not defined on the page load, instead of just leaving the page designation alone (returning the current page) or instead returning a value that identifies that the function didn't have information available to determine an appropriate alternate page designation (e.g. `null`) ? Curious why the returned page would be 1 if a particular selection within all of the available options that might be on any page is not provided. Wouldn't a flag be a better choice to return such as `null` or `false`? 
3) I suspect the current incorporation would keep this function within the existing test equivalent to: 
````php
if ((empty($_GET[$page_identifier]) || $_GET[$page_identifier] == '1') && !empty($_GET[$getvar_name])) {
  /* do action */
}
````

4) What therefore would be the action to be performed? Perhaps something akin to: 
````php
if ((empty($_GET[$page_identifier]) || $_GET[$page_identifier] == '1') && !empty($_GET[$getvar_name])) {
  /* do action */
  $returned_page = zen_admin_current_listing_page($page_query_raw, $getvar_name, $dbfield_name, $listing_max);
  if (!is_null($returned_page)) {
    $_GET[$page_identifier] = $returned_page;
  }
}
````

**Comment by lat9** [comment]
> 1. What about non numeric pages?
> 
>     2. Why does this new function return a page value of 1 if `$_GET[$getvar_name]` is not defined on the page load, instead of just leaving the page designation alone (returning the current page) or instead returning a value that identifies that the function didn't have information available to determine an appropriate alternate page designation (e.g. `null`) ? Curious why the returned page would be 1 if a particular selection within all of the available options that might be on any page is not provided. Wouldn't a flag be a better choice to return such as `null` or `false`?
> 
>     3. I suspect the current incorporation would keep this function within the existing test equivalent to:
> 
> 
> ```
> if ((empty($_GET[$page_identifier]) || $_GET[$page_identifier] == '1') && !empty($_GET[$getvar_name])) {
>   /* do action */
> }
> ```
> 
>     4. What therefore would be the action to be performed? Perhaps something akin to:
> 
> 
> ```
> if ((empty($_GET[$page_identifier]) || $_GET[$page_identifier] == '1') && !empty($_GET[$getvar_name])) {
>   /* do action */
>   $returned_page = zen_admin_current_listing_page($page_query_raw, $getvar_name, $dbfield_name, $listing_max);
>   if (!is_null($returned_page)) {
>     $_GET[$page_identifier] = $returned_page;
>   }
> }
> ```

1. Non-numeric pages?  Please elaborate.
2. If `$_GET[$getvar_name]` isn't set, that (to me, anyway) implies (like with the orders' listing) this is a request for the first page of the listing ... and the main module's processing will determine what to associate with the first list item and, thus, the first page of the listing.
3. I'm presuming that you're referring to the clause in your current PR which introduces additional issues.  For that reason, I've not included it.  I've tested the kinda-sorta-not-exactly pseudo-code in my previous post and it (to my eyes) performs the function intended.  Have you found a condition where that multi-use function doesn't fulfill the requirements?
4. My intent was to provide a full-function (er) function to be used without additional checks for the various listing pages, so I'm (again) not understanding your comment.

**Comment by mc12345678** [comment]
`$_GET[$getvar_name]` doesn't represent the page designation as coded above. 

So consider this. Your on page 5 of umpteen. You select a record to delete and select delete. You confirm delete. Now using the provided new function all by itself on what page 1) will you be redirected and 2) should you be redirected?
