### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [zencart/zencart#4533]
Dear @zencart team,

In first, I wish you a Happy New Year.

It will be nice to remove old parts like:
- https://sourceforge.net/p/zencart/mailman/
- https://sourceforge.net/p/zencart/code/

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example.
- https://sourceforge.net/p/zencart/

To disable/delete tabs, go here: https://sourceforge.net/projects/zencart/
To add a new tab, go here: https://sourceforge.net/projects/zencart/
To change informations, go here: https://sourceforge.net/p/zencart/admin/overview
To export, go here: https://sourceforge.net/p/zencart/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/zencart/admin/overview
- "Preferred Support Page (for users of your project)", here: https://sourceforge.net/p/zencart/admin/overview
- A new tab, go here: https://sourceforge.net/projects/zencart/

Thanks in advance.

**Comment by zcwilt** [comment]
Hi

Thanks. Working on migrating stuff
Will be updating this over the next couple of weeks.
