### ISSUE TITLE
Demo images not present  - ZipArchive not found on install of 1.5.8 zen cart

### ISSUE THREAD

**Issue by brittainmark** [zencart/zencart#4535]
Missing class ZipArchive on install
causing error and demo images not installing when loading demo data on install.

**Version**
Zen Cart version:  1.5.8
PHP version: 8.0.14
MySQL version: 	mysqlnd 8.0.14 
Plugins that may be related:  none vanilla install
What older/newer versions were also tested? no

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Perform vanilla installation with demo data

**Expected behavior**
complete install without error

**Debug/Error Logs**
Include debug logs containing PHP and/or MySQL error details. These are often found in your /logs/ directory as myDebug-xxxxx.log files.
[10-Jan-2022 11:06:12 UTC] PHP Fatal error:  Uncaught Error: Class "ZipArchive" not found in /home/lotus/public_html/innerlightcrystals/Test158/zc_install/ajaxLoadMainSql.php:58
Stack trace:
#0 {main}
  thrown in /home/lotus/public_html/innerlightcrystals/Test158/zc_install/ajaxLoadMainSql.php on line 58 

**Devices (please complete the following information):**
 - Operating System: Ubuntu 20.04.3 LTS 64 bit
 - Browser Firefox 95.01
**Additional context**
Trying to test new address format installation. All tables have been successfully created with expected data.

**Comment by brittainmark** [comment]
Solved by adding php-zip to server. Do we need to add check?

**Comment by scottcwilson** [comment]
I wouldn't want to block the install for this.  Thanks for reporting though - will see what can be done.

**Comment by brittainmark** [comment]
Agreed could be a warning like pdo-sqlite

**Comment by brittainmark** [comment]
I'll have a look.

**Comment by brittainmark** [comment]
PR #4536 submitted
