### ISSUE TITLE
Installation not all check performed if pdo_sqlite missing

### ISSUE THREAD

**Issue by brittainmark** [zencart/zencart#4537]
**Describe the bug**
If PHP extension pdo_sqlite is missing from the server, then the checking process stops and no other checks are performed. This means that the installation can attempt to continue even if there are other configuration issues that must be fixed before installation can continue.

**Version**
Zen Cart version: 1.5.8
PHP version: 8.0.14
MySQL version: mysqlnd 8.0.14 
Plugins that may be related: 
What older/newer versions were also tested?

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. disable mod pdo_sqlite
2. Perform vanilla installation

**Expected behavior**
Not sure if 
1) installation should complete all other installation checks then stop
or
2) Not display clean install button.

**Screenshots**
without sqlite

![cleanInstallon](https://user-images.githubusercontent.com/63110817/148786925-9dfe3ed1-574f-4702-a52f-52e3b2e08332.JPG)

with sqlite enabled

![sqliteEnabled](https://user-images.githubusercontent.com/63110817/148787038-8577bdf4-23f8-4642-9001-5cade81196ce.JPG)
![sqliteEnabled2](https://user-images.githubusercontent.com/63110817/148787058-dcaaca77-27e0-457b-bf8d-b647b745c185.JPG)

**Debug/Error Logs**
no logs produced 

**Devices (please complete the following information):**
 - Operating System: Ubuntu 20.04.3 LTS 64 bit
 - Browser: Firefox 95.01

**Comment by brittainmark** [comment]
two  solutions.

1.  If pdo_sqlite is **not** an essential mod for PHP change remove line **criticalError: true** from the systemCheck.yml file
2. If pdo_sqlite is an essential mod for PHP change, **errorLevel: WARN to errorLevel: FAIL**


pdosqliteExt:  
 &nbsp; &nbsp; &nbsp; runLevel: always  
 &nbsp; &nbsp; &nbsp;  **errorLevel: WARN**  
 &nbsp; &nbsp; &nbsp; **criticalError: true**
 &nbsp; &nbsp; &nbsp; mainErrorText: <?php echo TEXT_ERROR_PDOSQLITE_SUPPORT .PHP_EOL; ?>  
 &nbsp; &nbsp; &nbsp; methods:  
   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;     checkExtension:  
   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;     parameters:  
   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;       extension: pdo_sqlite

From my limited experiments, it appears that pdo_sqlite is not essential. I would therefore suggest option1
I can submit PR for either.

**Comment by brittainmark** [comment]
I have done some more digging and the only use of SQLite appears to be in the laravel directory
laravel/vendor/illuminate/database/Connectors/ConnectionFactory.php has
```
 public function createConnector(array $config)
    {
        if (! isset($config['driver'])) {
            throw new InvalidArgumentException('A driver must be specified.');
        }

        if ($this->container->bound($key = "db.connector.{$config['driver']}")) {
            return $this->container->make($key);
        }

        switch ($config['driver']) {
            case 'mysql':
                return new MySqlConnector;
            case 'pgsql':
                return new PostgresConnector;
            case 'sqlite':
                return new SQLiteConnector;
            case 'sqlsrv':
                return new SqlServerConnector;
        }

        throw new InvalidArgumentException("Unsupported driver [{$config['driver']}].");
    }

    /**
     * Create a new connection instance.
     *
     * @param  string  $driver
     * @param  \PDO|\Closure  $connection
     * @param  string  $database
     * @param  string  $prefix
     * @param  array  $config
     * @return \Illuminate\Database\Connection
     *
     * @throws \InvalidArgumentException
     */
    protected function createConnection($driver, $connection, $database, $prefix = '', array $config = [])
    {
        if ($resolver = Connection::getResolver($driver)) {
            return $resolver($connection, $database, $prefix, $config);
        }

        switch ($driver) {
            case 'mysql':
                return new MySqlConnection($connection, $database, $prefix, $config);
            case 'pgsql':
                return new PostgresConnection($connection, $database, $prefix, $config);
            case 'sqlite':
                return new SQLiteConnection($connection, $database, $prefix, $config);
            case 'sqlsrv':
                return new SqlServerConnection($connection, $database, $prefix, $config);
        }

        throw new InvalidArgumentException("Unsupported driver [{$driver}].");
    }
```

**I therefore suggest that the check be removed from SystemCheck.yml**

**Comment by scottcwilson** [comment]
Sending to Ian for decision.  Thanks for digging in to this!

**Comment by brittainmark** [comment]
Think this should be addressed as part of 1.5.8 as it can lead to incorrect instalations.

**Comment by zcwilt** [comment]
Hmmm.

Would have to dig back through git blame/history 

At a guess, going to assume this was done as part of test framework stuff, but might be mistaken.

I agree that for an install, we don't need sqllite so I would go with the option of removing from  systemCheck.yml 

The Laravel stuff is a re herring.

**Comment by zcwilt** [comment]
@brittainmark if you want to remove from systemCheck.yml I would be happy with that.

Our phpunit.xml does rely on sqlite for local testing, however that should not enforce sqlite on install.
