### ISSUE TITLE
New fatal error in options name manager

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4543]
[11-Jan-2022 11:19:25 America/New_York] Request URI: /gh_demo_158/admin/index.php?cmd=options_name_manager, IP address: ::1
#1  trigger_error() called at [/Users/scott/Sites/gh_demo_158/includes/classes/db/mysql/query_factory.php:665]
#2  queryFactory->show_error() called at [/Users/scott/Sites/gh_demo_158/includes/classes/db/mysql/query_factory.php:632]
#3  queryFactory->set_error() called at [/Users/scott/Sites/gh_demo_158/includes/classes/db/mysql/query_factory.php:273]
#4  queryFactory->Execute() called at [/Users/scott/Sites/gh_demo_158/includes/classes/pulldown.php:88]
#5  pulldown->runSQL() called at [/Users/scott/Sites/gh_demo_158/includes/classes/productPulldown.php:95]
#6  productPulldown->processSQL() called at [/Users/scott/Sites/gh_demo_158/includes/classes/pulldown.php:93]
#7  pulldown->generatePullDownHtml() called at [/Users/scott/Sites/gh_demo_158/includes/functions/functions_categories.php:356]
#8  zen_draw_pulldown_products() called at [/Users/scott/Sites/gh_demo_158/includes/functions/functions_categories.php:378]
#9  zen_draw_pulldown_products_having_attributes() called at [/Users/scott/Sites/gh_demo_158/admin/options_name_manager.php:750]
#10 require(/Users/scott/Sites/gh_demo_158/admin/options_name_manager.php) called at [/Users/scott/Sites/gh_demo_158/admin/index.php:11]
--> PHP Fatal error: 1054:Unknown column 'p.products_name' in 'order clause' :: SELECT DISTINCT pd.products_id, p.products_sort_order, p.products_price, p.products_model
                FROM products p
                INNER JOIN products_description pd ON (p.products_id = pd.products_id) 
				
				WHERE pd.language_id = 1  ORDER BY p.products_name ==> (as called by) /Users/scott/Sites/gh_demo_158/includes/classes/pulldown.php on line 88 <== in /Users/scott/Sites/gh_demo_158/includes/classes/db/mysql/query_factory.php on line 665.

**Comment by proseLA** [comment]
i'll take a look when i'm in front of my computer.

**Comment by scottcwilson** [comment]
Doesn't look bad - you just have to join on description if you're using product name to sort.

**Comment by proseLA** [comment]
> Doesn't look bad - you just have to join on description if you're using product name to sort.

nah.... it's a sillier error than that.  PR soon.

**Comment by scottcwilson** [comment]
>  also, i take it you are seeing this error as well, or is it just me?

This warning is fixed in #4544
