### ISSUE TITLE
MySQL error on Options Name Manager page 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4546]
--> PHP Fatal error: 3065:Expression #1 of ORDER BY clause is not in SELECT list, references column 'gh_demo_158.pd.products_name' which is not in SELECT list; this is incompatible with DISTINCT :: SELECT DISTINCT pd.products_id, p.products_sort_order, p.products_price, p.products_model
                FROM products p
                INNER JOIN products_description pd ON (p.products_id = pd.products_id)

            WHERE pd.language_id = 1  ORDER BY pd.products_name ==> (as called by) /Users/scott/Sites/gh_demo_158/includes/classes/pulldown.php on line 88 <== in /Users/scott/Sites/gh_demo_158/includes/classes/db/mysql/query_factory.php on line 665.

This can be suppressed by using sql_mode = 'NO_ENGINE_SUBSTITUTION'; but the goal is to have the core code run error/warning free in STRICT mode.

**Comment by proseLA** [comment]
@scottcwilson 
please provide full error log, mysql mode, as well as steps to reproduce the error.  i am not able to reproduce it.

![image](https://user-images.githubusercontent.com/1095136/149161584-1b149c25-a194-45ba-baf6-b0c684153118.png)

**Comment by proseLA** [comment]
what does `SELECT @@sql_mode;` show?

**Comment by scottcwilson** [comment]
In Admin > Version, I see 

MySQL Mode: ONLY_FULL_GROUP_BY, STRICT_TRANS_TABLES, NO_ZERO_IN_DATE, NO_ZERO_DATE, ERROR_FOR_DIVISION_BY_ZERO, NO_AUTO_CREATE_USER, NO_ENGINE_SUBSTITUTION

**Comment by scottcwilson** [comment]
You just have to add pd.products_name to the columns in the SELECT.

**Comment by proseLA** [comment]
> This can be suppressed by using sql_mode = 'NO_ENGINE_SUBSTITUTION'; but the goal is to have the core code run error/warning free in STRICT mode.

>In Admin > Version, I see
>
>MySQL Mode: ONLY_FULL_GROUP_BY, STRICT_TRANS_TABLES, NO_ZERO_IN_DATE, NO_ZERO_DATE, ERROR_FOR_DIVISION_BY_ZERO, NO_AUTO_CREATE_USER, NO_ENGINE_SUBSTITUTION

> You just have to add pd.products_name to the columns in the SELECT.

i'm getting a lot of conflicting information here.  and i do not like correcting my code without being first able to reproduce the error.

your mysql mode does not cause me to reproduce this error.  in addition, your first comment about NO_ENGINE_SUBSTITUTION seems to be incorrect, as that is already part of your sql mode.

the error is related to ONLY_FULL_GROUP_BY;  if you were to remove that from your mode, i'm guessing it would work. 

but again, i am not able to reproduce on my dev box using the test data.  and i am also in agreement that all of these queries should be able to run warning free in STRICT mode.

last try, what is your database engine (from your server info page)?  mine is:

Database Engine: MySQL 5.5.5-10.3.31-MariaDB-0+deb10u1-log

i'll add that field, but now i'm very curious as to why i can not reproduce the error.

**Comment by scottcwilson** [comment]
That's why - I have Database Engine: MySQL 5.7.34.
Once you make the fix I will verify that it's resolved; you're not changing things blind.

**Comment by scottcwilson** [comment]
Works like a charm.  Thanks.

**Comment by scottcwilson** [comment]
Note that for a fully log-free experience, you still require #4544 but that will come soon.

**Comment by scottcwilson** [comment]
Fastest gun in the West. :)  Just merged.
