### ISSUE TITLE
admin splitPageResults returns inaccurate query row total

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#4558]
we can not count on this calculation for all queries:
https://github.com/zencart/zencart/blob/2ebaeeb1495c26df624de2624297e139237b5419/admin/includes/classes/split_page_results.php#L114-L119

in my limited testing, any query that already involves a `sum` in the query (or potentially a `count`) will return inaccurate results.  for example, using the test data from a link similar to this: https://zcdev.com/admin/index.php?cmd=stats_products_viewed; prior to calling the `new splitPageResults`, my query is:
```
SELECT p.products_id, pd.products_name, sum(v.views) as total_views, l.name as language, p.products_type, pt.type_handler, pt.allow_add_to_cart FROM products p 
LEFT JOIN products_description pd ON p.products_id = pd.products_id LEFT JOIN languages l ON l.languages_id = pd.language_id 
INNER JOIN count_product_views v ON p.products_id = v.product_id AND v.language_id = l.languages_id LEFT JOIN product_types pt ON p.products_type = pt.type_id 
WHERE date_viewed BETWEEN CAST('2015-12-19' AS DATE) AND CAST('2022-01-18' AS DATE) GROUP BY p.products_id, pd.products_name, language, p.products_type, pt.type_handler, pt.allow_add_to_cart ORDER BY total_views DESC
```
executing this sql statement directly on my test data returns 19 rows.  the `splitPageResults` returns 46.  the cascade effects on the pager as now we have 3 pages with a max result set of 20; when in fact there is only 1 page of results.

**Comment by scottcwilson** [comment]
Would you be willing to take this ticket?

**Comment by proseLA** [comment]
> Would you be willing to take this ticket?

noting that there are 46 instances in 41 different scripts in the admin of `new splitPageResulst` and my limited time will not allow for testing everything, sure, i'll take this ticket.

**Comment by torvista** [comment]
> my limited time will not allow for testing everything

Of course.

If you put up a list of the pages you've not tested, others can take chunks on, hopefully.

**Comment by proseLA** [comment]
@torvista 
i looked at the orders page and products category.  below is a list of pages that use this function.  but in fact, i'm pretty confident my change works.  in fact, i think it's simpler and cleaner.  unfortunately i do not have any benchmarking as to whether it is more or less efficient.

```
admin/music_genre.php
admin/orders_status.php
admin/gv_queue.php
admin/record_artists.php
admin/banner_manager.php
admin/salemaker.php
admin/stats_products_viewed.php
admin/specials.php
admin/attributes_controller.php
admin/tax_rates.php
admin/options_name_manager.php
admin/coupon_admin.php
admin/reviews.php
admin/media_types.php
admin/group_pricing.php
admin/tax_classes.php
admin/stats_products_purchased.php
admin/products_expected.php
admin/geo_zones.php
admin/stats_customers.php
admin/featured.php
admin/options_values_manager.php
admin/customers.php
admin/gv_sent.php
admin/stats_products_lowstock.php
admin/customer_groups.php
admin/coupon_restrict.php
admin/paypal.php
admin/product_types.php
admin/newsletters.php
admin/category_product_listing.php
admin/template_select.php
admin/currencies.php
admin/ezpages.php
admin/countries.php
admin/languages.php
admin/media_manager.php
admin/record_company.php
admin/orders.php
admin/downloads_manager.php
admin/zones.php
admin/manufacturers.php
```

**Comment by torvista** [comment]
Started at the end to be contrary.
Compared local results with PR class to production results with 158 class.

admin/languages.php: no error, but only two languages

admin/media_manager.php: no error, but no results/no entries

admin/record_company.php: no error, but no results/no entries

admin/orders.php: no change in totals

admin/downloads_manager.php: 
bad sql, fatal error
1060 Duplicate column name 'products_attributes_id'
in:
[WITH countresults AS (SELECT pad.*, pa.*, pd.*, p.* FROM products_attributes_download pad LEFT JOIN products_attributes pa ON pad.products_attributes_id = pa.products_attributes_id LEFT JOIN products_description pd ON pa.products_id = pd.products_id AND pd.language_id = 1 LEFT JOIN products p ON p.products_id = pd.products_id WHERE pa.products_attributes_id = pad.products_attributes_id ORDER BY pd.products_name ) SELECT count(*) as total FROM countresults]

admin/zones.php: using the the country filter at the bottom of the page always gives 0 to 0 of 296 zones irrespective of results.

admin/manufacturers.php: no error/no change

**Comment by proseLA** [comment]
@torvista you are great.  thank you.

with regards to the download manager; best practices:

https://bigdata-madesimple.com/top-10-best-practices-in-mysql/#:~:text=7.%20Use%20SELECT%20*%20only%20if%20needed

no good deed goes unpunished.

**Comment by proseLA** [comment]
@torvista 
just so i understand, the only page where there was a problem was `admin/downloads_manager.php`?  everything else was fine with the exception of the `zones.php` which gave the same 0 of 0 as the current pager?

**Comment by proseLA** [comment]
as i stated in my PR #4561 

> i pulled out code that was not needed; and left in code that was used for $this->paginateByLetter which is only used in countries and seems to work fine.

i missed the fact that the `zones.php` also makes use of this section of code.  which is why those numbers are off.  that section of code is not all affected.

**Comment by torvista** [comment]
I only did the ones I listed before I keeled over for the night. Correct, no apparent problems.
Others should have a go at the rest today, we have multiple business issues today so no chance for me to do more.

**Comment by proseLA** [comment]
all issues are addressed until someone reports something new.  

i think results are much better, although the problem identified by @torvista with the `downloads_manager` runs the potential of causing problems for plugin authors who use the `select p.*, pd.*` in their select statements and then use the `splitPage` object.  (caveat emptor, i may be guilty myself!)

**Comment by torvista** [comment]
I've been through the list and only these pages have a similar problem:
gv_sent
paypal
ezpages

**Comment by proseLA** [comment]
@torvista thank you!

what do you think about the changes for country and zones?  the pager function (in the most literal sense) was never going to work with countries and zones.  now at least the information presented seems accurate.  see:

`admin/index.php?cmd=zones&page=ITALY`

**Comment by torvista** [comment]
Seems fine to me.
Although, on the zone page I would have put the country selector under the main title, not at the bottom of the page.

**Comment by proseLA** [comment]
> Seems fine to me. Although, on the zone page I would have put the country selector under the main title, not at the bottom of the page.

thanks for checking.

with regards to country placement; that would be a new and separate issue.

**Comment by robryanx** [comment]
Just to note with CTE I think it is mysql 8 only.
I think though a subquery would work in the same way:
```php
$countSQL = 'SELECT count(*) as total FROM (' . $sql . ') countresults';
```
I actually come across this a few times in the past and ended up writing a separate count query rather than a sub query which seems better, assuming it works for everything.

**Comment by proseLA** [comment]
> Just to note with CTE I think it is mysql 8 only. I think though a subquery would work in the same way:
> 
> ```
> $countSQL = 'SELECT count(*) as total FROM (' . $sql . ') countresults';
> ```
> 
> I actually come across this a few times in the past and ended up writing a separate count query rather than a sub query which seems better, assuming it works for everything.

interesting.  thanks for the info.  will play around a bit.  much appreciated.

**Comment by scottcwilson** [comment]
Please LMK when this is ready for merge.

**Comment by proseLA** [comment]
hopefully later this week. i'm working on installing an older version of mysql/maria-db on my development box for additional testing.

**Comment by proseLA** [comment]
@robryanx i hate doing code that needs to work with unsupported libraries.  i'm not sure whether to thank you or curse you. i'll go with the former. :+1: 

@scottcwilson ready for merge...
