### ISSUE TITLE
ZC158: Update icon on classic missing

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4579]
![update](https://user-images.githubusercontent.com/4391026/151570740-2c4f5715-4ce9-4725-bc35-d988c6bfb8d9.gif)

This  definition is in lang.english and so global.
https://github.com/zencart/zencart/blob/580028276f6885dcb97d6c662f615d6e0b1803ff/includes/languages/lang.english.php#L231

I would have thought this image to be a template item, not a language item.

**Comment by torvista** [comment]
and also I note that even when corrected, the alt text is above 30 chars
https://github.com/zencart/zencart/blob/580028276f6885dcb97d6c662f615d6e0b1803ff/includes/languages/lang.english.php#L236
which means the css button will never be used/it will always be an icon.
https://github.com/zencart/zencart/blob/580028276f6885dcb97d6c662f615d6e0b1803ff/includes/functions/html_output.php#L283

**Comment by scottcwilson** [comment]
it looks for the image in the template folder. 
Please shorten the alt text in your submission to fix.

**Comment by torvista** [comment]
What is happening is the alt text is too long: that is from the core language file.
Consequently it uses the filename in the language file (which is .png), which does not exist in the default template (it is .gif), so it displays the alt text.
So, there are various aspects to this.

**Comment by scottcwilson** [comment]
Let's just add the icon.  PR #4584

**Comment by torvista** [comment]
Why is there a second icon? Seems out of place. Also on responsive classic
![Clipboard01](https://user-images.githubusercontent.com/4391026/151771875-daef7b10-0514-4e30-bb8d-d15fcc9a0e66.gif)
.

**Comment by scottcwilson** [comment]
The second icon is so that you can update multiple quantities at once.

**Comment by torvista** [comment]
Any inline icon updates all of the quantities. I think it is redundant.

**Comment by scottcwilson** [comment]
> Any inline icon updates all of the quantities.
Right but not everyone knows this. 

This is a low priority nit that's unrelated to the actual issue (missing image).  I really don't want changes to either RC or classic.  If you want to submit a PR to make this change in Bootstrap, feel free.
