### ISSUE TITLE
Uncaught pblm

### ISSUE THREAD

**Issue by skbormon** [zencart/zencart#4585]
Fatal error: Uncaught TypeError: mysqli_num_rows(): Argument #1 ($result) must be of type mysqli_result, bool given in C:\xampp\htdocs\projects\thapa\registration\regi.php:18 Stack trace: #0 C:\xampp\htdocs\projects\thapa\registration\regi.php(18): mysqli_num_rows(false) #1 {main} thrown in C:\xampp\htdocs\projects\thapa\registration\regi.php on line 18
![problem no 18](https://user-images.githubusercontent.com/89042568/151674903-9f51fa86-9f68-44b6-a0db-84e2a4019c0e.png)

( why says problem in line no 18 )

**Comment by scottcwilson** [comment]
This is a plugin or some other project - it's not Zen Cart.
