### ISSUE TITLE
ZC158: language override fallback anomaly

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4608]
Sorry this is a head-spinner regarding how language overrides and fall-backs work in a multi-language store.

Conside a two language store (my spanish language pack is up to date for this) and, for example lang.index.php which in the vanilla install has a core version and a responsive_classic override.
Looking at 'HEADING_TITLE' => 'Congratulations! You have successfully installed your Zen Cart® E-Commerce Solution.'

Uniquely Identify the texts in each of the four files for testing e.g.
'HEADING_TITLE' => 'Congratulations! You have successfully installed your Zen Cart® E-Commerce Solution. EN CORE'
'HEADING_TITLE' => 'Congratulations! You have successfully installed your Zen Cart® E-Commerce Solution. EN RC'

'HEADING_TITLE' => '¡Enhorabuena! Ha instalado su tienda Zen Cart&reg; con éxito. ES CORE',
'HEADING_TITLE' => '¡Enhorabuena! Ha instalado su tienda Zen Cart&reg; con éxito. ES RC',

When all four are enabled, all works as expected: each language shows the RC version.
However when disabling the same line in the files, things get unexpected.

Scenarios
1) EN RC: comment out the single line in the override file.
Shop displays the EN CORE version as expected.

2) ES RC: comment out the single line in the override file.
Shop displays the EN RC version, NOT the ES CORE version as would be expected:
![Clipboard01](https://user-images.githubusercontent.com/4391026/153058817-638e4162-f6d3-4f90-852c-5203b40a90bb.gif)

Following on
EN RC: now additionally comment out the single line in the override file.
Shop now displays the ES CORE version.

Following on
ES CORE: now additionally comment out the single line in the core file.
Shop displays the EN CORE version as would be expected.

Following on
EN CORE: now additionally comment out the single line in the core file.
Shop displays HEADING_TITLE as would be expected.

So, the problem is the fallback from the override to the core non-english file, falls back to the english override instead of the non-english core.

**Comment by scottcwilson** [comment]
Please put a zip of the updated Spanish files somewhere so I can pull down and test locally.

**Comment by torvista** [comment]
https://github.com/torvista/Zen_Cart-Spanish_Language_Pack/tree/v158

**Comment by scottcwilson** [comment]
can't repro - when I update all 4 files, then comment out includes/languages/spanish/responsive_classic/lang.index.php define for HEADING_TITLE it shows ES CORE define.

**Comment by torvista** [comment]
I still get the same, commenting the single line in ES RC

![Clipboard01](https://user-images.githubusercontent.com/4391026/153501823-eef7adc5-58de-42c4-bd11-77c1ebc912a5.gif)

gives me the EN RC version instead of ES CORE.

![Clipboard01](https://user-images.githubusercontent.com/4391026/153501968-e5d225fc-8a54-4a7f-9b01-aecb5b6a9b0a.gif)

I'll have a cursory look....

**Comment by torvista** [comment]
It may seem a minor issue, but it impacts on how to recommend users that overrides are implemented.

**Comment by scottcwilson** [comment]
![Screen Shot 2022-02-10 at 5 01 15 PM](https://user-images.githubusercontent.com/4391638/153503953-b2e9d497-fdf1-4b1f-af2e-dc9bf5626293.jpg)

**Comment by scottcwilson** [comment]
You have removed all the old style language files, right?

**Comment by scottcwilson** [comment]
Please go here:
https://github.com/scottcwilson/zencart/tree/v158
Download a zip, replace the storefront include file with yours, load the language pack, do the 4 changes and try running it, and see if it works there.

**Comment by scottcwilson** [comment]
Only happens if template is set to RC.  When template is set to classic, the correct /includes/languages/spanish/lang.index.php is read.

**Comment by scottcwilson** [comment]
FINALLY it's happening on my side too.  OK give me a bit and I'll see what's happening.

**Comment by scottcwilson** [comment]
Fixed includes/classes/ResourceLoaders/ArraysLanguageLoader.php on your test site.  Please keep testing and let me know if that did it - seems right to me.

**Comment by torvista** [comment]
That works for me!

**Comment by scottcwilson** [comment]
Grab includes/classes/ResourceLoaders/CatalogArraysLanguageLoader.php from my PR and retest.

**Comment by torvista** [comment]
Good stuff, that works.

**Comment by scottcwilson** [comment]
Please keep hitting this hard.  You are the only multi-lingual person in the frequent contributors group, AFAIK.

**Comment by torvista** [comment]
I've got overrides in multiple places and have done orders in both languages with no further anomalies found. I think you can merge for now.

My override method is duplicate the original, comment out everything, enable only the constant for changing.
So an override could have only one thing in it.
