### ISSUE TITLE
shopfront account_edit, CSS buttons formatting is different

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4609]
One for the template experts, of which I am not.
Any reason why these are different (1.3em/1.2em)?
![Clipboard01](https://user-images.githubusercontent.com/4391026/153462804-e66f118d-40be-46e2-b616-0d5039ad244a.gif)

They are the same 157/158.

**Comment by scottcwilson** [comment]
It's just a setting in stylesheet_css_buttons.css 
`font-size: 1.2em`

includes/templates/responsive_classic/css/stylesheet_css_buttons.css (lines 3-5) 

No idea why it was done this way; it has been this way since the template was created.

**Comment by barco57** [comment]
cause QA on Responsive Classic was missing...

**Comment by torvista** [comment]
That spreadsheet is indeed horrific. Hence I backed out of the world of pain that is removing all those classes but it sorely needs it (maybe a rcv2 template is required?).
Meanwhile I've done a sticking plaster for this issue.

**Comment by scottcwilson** [comment]
Please don't spend time on fixes for RC.  People should be using Bootstrap and leaving the old templates behind.

**Comment by lat9** [comment]
Noting, however, that there are a bunch of sites using a 'clone' of the `responsive_classic`.

**Comment by torvista** [comment]
I have not ventured into template-land for aeons but I'm surprised visual stuff like this has not been spotted and corrected long ago.

**Comment by scottcwilson** [comment]
> Noting, however, that there are a bunch of sites using a 'clone' of the `responsive_classic`.

Agreed, but they have tweaked their CSS to taste long ago.

**Comment by torvista** [comment]
fixed in https://github.com/zencart/zencart/pull/4610
