### ISSUE TITLE
Coupon input field on payment page should not be displayed if there are no valid coupons in use.

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4612]

**Comment by marco-pm** [comment]
Do you mean "don't show the coupon input field if there aren't coupons that the customer can redeem"? If that's the case, I disagree.

**Comment by torvista** [comment]
There are various scenarios here.
1) Coupons are not enabled at all.
2) Coupons are enabled but there are none valid at all.
2) Coupons are enabled but there are none valid for this order.
3) Coupons are enabled and one has been redeemed.
In this case the text shown should be changed and I think the removal process should be a link, not the same text box.
![image](https://user-images.githubusercontent.com/4391026/154860763-7dc0e31b-4ee8-44d5-9067-2967f416147a.png)

> Do you mean "don't show the coupon input field if there aren't coupons that the customer can redeem"? If that's the case, I disagree.

Why?

**Comment by marco-pm** [comment]
> There are various scenarios here.
> 
> 1. Coupons are not enabled at all.
> 2. Coupons are enabled but there are none valid at all.
> 3. Coupons are enabled but there are none valid for this order.
> 4. Coupons are enabled and one has been redeemed.
>    In this case the text shown should be changed and I think the removal process should be a link, not the same text box.
>    ![image](https://user-images.githubusercontent.com/4391026/154860763-7dc0e31b-4ee8-44d5-9067-2967f416147a.png)
> 

ok, now it's clear 😊 (the issue's title is misleading)
I agree on the change for point 4.

**Comment by proseLA** [comment]
> 
> ok, now it's clear blush (the issue's title is misleading) I agree on the change for point 4.

that is one that i disagree.  how could one remove said coupon if the input field is not there?

i am now of the opinion that this should be left as is.  

personally, i hate seeing a coupon field if none are available.  that said, if one were to remove it when none are available and only display it when there are available coupons, one risks alienating the repeat customer who is not privy to said coupon.  said customer might notice when the field is there and when it is not there, and then demand coupon use when he sees the field from store owner.

it's easier to have plausible deniability if the field is always there.

**Comment by marco-pm** [comment]
> that is one that i disagree. how could one remove said coupon if the input field is not there?

with a button next to "your current redemption code: CODE"

> if one were to remove it when none are available and only display it when there are available coupons, one risks alienating the repeat customer who is not privy to said coupon. said customer might notice when the field is there and when it is not there, and then demand coupon use when he sees the field from store owner.

That's exactly the reason why I prefer to always show the input field, even on cases 2. and 3. For consistency.
Or maybe add an option in the admin, let the store owner decide.

**Comment by torvista** [comment]
I think 1 is clear.
2  and 3 Probably needs the scenarios fleshing out to avoid the customer annoyance you mention. Or leave it as it is for now, if it's a rabbit hole.

4
> how could one remove said coupon if the input field is not there?

Click on a "Remove Coupon" link? instead of typing anything. More mobile-friendly and **language independent.**
And change the text completely. At the moment the first paragraph should not even be there.

**Comment by scottcwilson** [comment]
Note that you can always turn off coupons, then the prompt never shows up at all.

I was just looking at WooCommerce and found that they also prompt even if there are no coupons available.

**Comment by scottcwilson** [comment]
Changing this will cause confusion.  Consider customers trying to add a coupon and not realizing restrictions prohibit this coupon - they'll complain to the store owner.
Let's leave as is.
