### ISSUE TITLE
constant 'EMP_SHOPPING_FOR_MESSAGE_SEVERITY' is not a language constant

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4631]
https://github.com/zencart/zencart/blob/bec4004f42605e7072a820d06db2939af4f0171c/includes/languages/lang.english.php#L93

And I think should be caution, not success.

I can do a PR to move it to the Twilight Zone (gID=6).

**Comment by scottcwilson** [comment]
Please remove this constant and hardcode 'caution' where it is used.

**Comment by scottcwilson** [comment]
Fixed by #4632
