### ISSUE TITLE
javascript resizing obsolete?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4636]
there are various uses of functions resize scattered about

e.g.
https://github.com/zencart/zencart/blob/bec4004f42605e7072a820d06db2939af4f0171c/includes/modules/pages/popup_image/jscript_main.php#L12-L26

Looks pretty obsolete. 

Places the image in the centre, but it is cut-off/incomplete so the calculations are off.

![Clipboard01](https://user-images.githubusercontent.com/4391026/154753483-2278aa69-8360-4a17-8513-acfb5dc95073.gif)

**Comment by scottcwilson** [comment]
Probably so. IE 6?  Ugh.

**Comment by torvista** [comment]
I don't use this, so touching core image lack-of-management is something I won't be doing.
I don't think it is fit for purpose and probably the section that most needs replacement a long time ago.
Just stick in IH and move on is my opinion.

**Comment by lat9** [comment]
Although this issue preceded #6004, I believe that it's the same (and there's currently a PR linked to the latter).
