### ISSUE TITLE
admin, css: h1 etc. used as classes not used

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4647]
`.pageHeading, h1, .h1, h2, .h2, h3, .h3, h4, .h4, h5, .h5, h6, .h6 {`

I don't find any use of h1 etc. as classes, so these .h1 etc references can be removed?

**Comment by scottcwilson** [comment]
Looks like @Zen4All put these in, and I'd rather not remove them.

**Comment by proseLA** [comment]
@torvista removing unused classes from css files is not a good idea.

other store owners may use them in their customizations and template files.

**Comment by Zen4All** [comment]
I can not remember if I put them in 😄 , but like proseLA said, some people may use them.
I think they were added because of overrides that may be needed for bootstrap
