### ISSUE TITLE
language constant CART_SHIPPING_METHOD_ZIP_REQUIRED is not language-related

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4649]
This language constant determines if the shipping estimator demands a postcode to be entered.
https://github.com/zencart/zencart/blob/4cd96422e50deb62d0303d232548e25d4c583be7/includes/templates/template_default/templates/tpl_modules_shipping_estimator.php#L65-L71
Long ago I modified this based on the selected country, but it certainly is not something that one would vary per language....it should be set per country or maybe based on the address format already defined for a country.

Thoughts?

**Comment by lat9** [comment]
Hmm, perhaps via lookup in `address_format::address_format` for the selected country, looking for the presence of the `$postcode` element?

Noting also that the constant is used only by the `shipping_estimator`.
