### ISSUE TITLE
lang.audience $define not defined?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4654]
based on an IDE complaint, but should the "return $define" be inside the if, otherwise it is returning an undeclared variable?
https://github.com/zencart/zencart/blob/4cd96422e50deb62d0303d232548e25d4c583be7/includes/languages/english/lang.audience.php#L1-L6

**Comment by scottcwilson** [comment]
Yep that's a bug.  Please PR.

**Comment by proseLA** [comment]
> Yep that's a bug. Please PR.

this is NOT a bug.  it is a violation of PSR-2; which is a coding style to which i think we are supposed to adhere.  see:

https://www.php-fig.org/psr/psr-2/#:~:text=5.1.%20if%2C%20elseif%2C%20else

plenty of examples of this style in ZC.  see:

https://github.com/zencart/zencart/blob/dee55fbd0b13e3c4a35a89d39c6e20ab9e145daf/admin/includes/defined_paths.php#L42-L47

considering the aforementioned file is a new file, i would say fix it.  i would not touch the defined_paths.

IMC.

**Comment by scottcwilson** [comment]
We shouldn't be creating logs.  $define needs to be defined.

**Comment by proseLA** [comment]
> We shouldn't be creating logs. $define needs to be defined.

u r right.  i missed what he was saying.  sorry.
