### ISSUE TITLE
PHP warnings on login when customers basket contains unavailable products

### ISSUE THREAD

**Issue by daphilli224** [zencart/zencart#4670]
**Describe the bug**
PHP warnings issued in shopping_cart.php: Undefined array key, and Trying to access array offset on value of type null

**Version**
Zen Cart version: 157c
PHP version: 7.3 (production)
MySQL version: 8.0 (production)
Plugins that may be related: probably none, possibly stock_by_attributes
What older/newer versions were also tested? 157c also tested with PHP 8.0.8 mysql 5.7.34 (development)

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Login and get a product in the shopping cart
2. Logout without checking out - the product is saved in the customers basket
3. Deactivate the product in the admin 
4. Login to the store side and see two warnings - (1) Please update your order, The item: blah blah, We are sorry but this product has been removed from our inventory at this time., This item has been removed from your shopping cart.  (2) Notice: For your convenience, your current shopping cart has been combined with your shopping cart from your last visit. Please review your shopping cart before checking out. 
5. Check the log file and notice four PHP warnings

**Expected behavior**
I expect no PHP warnings, notices or errors

**Screenshots**
If applicable, add screenshots to help explain.

**Debug/Error Logs**
[02-Mar-2022 08:34:57 America/New_York] Request URI: /index.php?main_page=shopping_cart, IP address: ::1
#1  shoppingCart->get_products() called at [/path to my domain/includes/modules/pages/shopping_cart/header_php.php:22]
#2  require(/path to my domain/includes/modules/pages/shopping_cart/header_php.php) called at [/path to my domain/index.php:35]
--> PHP Warning: Undefined array key 696 in /path to my domain/includes/classes/shopping_cart.php on line 1316.

[02-Mar-2022 08:34:57 America/New_York] Request URI: /index.php?main_page=shopping_cart, IP address: ::1
#1  shoppingCart->get_products() called at [/path to my domain/includes/modules/pages/shopping_cart/header_php.php:22]
#2  require(/path to my domain/includes/modules/pages/shopping_cart/header_php.php) called at [/path to my domain/index.php:35]
--> PHP Warning: Trying to access array offset on value of type null in /path to my domain/includes/classes/shopping_cart.php on line 1316.

[02-Mar-2022 08:34:57 America/New_York] Request URI: /index.php?main_page=shopping_cart, IP address: ::1
#1  shoppingCart->attributes_price() called at [/path to my domain/includes/classes/shopping_cart.php:1333]
#2  shoppingCart->get_products() called at [/path to my domain/includes/modules/pages/shopping_cart/header_php.php:22]
#3  require(/path to my domain/includes/modules/pages/shopping_cart/header_php.php) called at [/path to my domain/index.php:35]
--> PHP Warning: Undefined array key 696 in /path to my domain/includes/classes/shopping_cart.php on line 933.

[02-Mar-2022 08:34:57 America/New_York] Request URI: /index.php?main_page=shopping_cart, IP address: ::1
#1  shoppingCart->attributes_price() called at [/path to my domain/includes/classes/shopping_cart.php:1333]
#2  shoppingCart->get_products() called at [/path to my domain/includes/modules/pages/shopping_cart/header_php.php:22]
#3  require(/path to my domain/includes/modules/pages/shopping_cart/header_php.php) called at [/path to my domain/index.php:35]
--> PHP Warning: Trying to access array offset on value of type null in /path to my domain/includes/classes/shopping_cart.php on line 933.

 
**Devices (please complete the following information):**
 - Operating System: [e.g. Windows, Mac, Android, iOS] Mac OS 10.15.7
 - Browser [e.g. chrome, firefox] and version number] Firefox 97.0.1

**Additional context**
Add any other context about the problem here. Error logs are from development system.

**Comment by proseLA** [comment]
#4487 #4523

this problem was addressed in v158.  the fix did not make it into v157d.

it can be addressed by adding `continue;` after this line here:

https://github.com/zencart/zencart/blob/742b837868a2b128df96b6635c413c8187972679/includes/classes/shopping_cart.php#L1232

**Comment by scottcwilson** [comment]
Closing as complete in 1.5.8.
