### ISSUE TITLE
Cannot re-initialize "Send Copy" fields in Configuration > Email Settings 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4671]
All of the configs on the page Admin > Configuration > Email settings that begin with "Send Copy of ..." and contain an email address have a quirk: 

If you have a single email address in them and want to remove the address, you cannot. 
If you do so, you get the error message 
The text entered does not resolve to an acceptable email address.

**Comment by proseLA** [comment]
the problem starts with a val_function of `sanitizeEmail`

adding the following conditional would address said issue:
```
static public function sanitizeEmail(&$val) {
		if (empty($val)) {
			return true;
		}
```
but what about config values that require an email?

it seems a new function might be required, ie:
```
static public function sanitizeEmailNullOk(&$val) {
		if (empty($val)) {
			return true;
		}
               return sanitizeEmail($val);
}
```

**Comment by scottcwilson** [comment]
Some fields can be blank and others not. The "Send Copy" fields can all be blank.

**Comment by proseLA** [comment]
> Some fields can be blank and others not. The "Send Copy" fields can all be blank.


> 
> it seems a new function might be required, ie:
> 
> ```
> static public function sanitizeEmailNullOk(&$val) {
> 		if (empty($val)) {
> 			return true;
> 		}
>                return sanitizeEmail($val);
> }
> ```
as i stated above, i believe the new function below would work for the send copy.  so the value for `val_function` would need to change for those values to the above function., ie, 

```
UPDATE `configuration` SET
    `val_function` = '{\"error\":\"TEXT_EMAIL_ADDRESS_VALIDATE\",\"id\":\"FILTER_CALLBACK\",\"options\":{\"options\":[\"configurationValidation\",\"sanitizeEmailNullOK\"]}}'
WHERE `configuration_key` = 'SEND_EXTRA_ORDER_EMAILS_TO';
```

**Comment by lat9** [comment]
Those conditional email settings are
- SEND_EXTRA_LOW_STOCK_EMAILS_TO
- SEND_EXTRA_CREATE_ACCOUNT_EMAILS_TO
- SEND_EXTRA_DISCOUNT_COUPON_ADMIN_EMAILS_TO
- SEND_EXTRA_GV_ADMIN_EMAILS_TO
- SEND_EXTRA_GV_CUSTOMER_EMAILS_TO
- SEND_EXTRA_ORDERS_STATUS_ADMIN_EMAILS_TO
- SEND_EXTRA_ORDER_EMAILS_TO
- SEND_EXTRA_REVIEW_NOTIFICATION_EMAILS_TO

... and the associated settings ending with _SEND would then be removed.

**Comment by lat9** [comment]
Modules affected by removal of the _SEND settings:
![image](https://user-images.githubusercontent.com/2685585/157507002-65d25f66-d37c-4979-a614-ea9055a203a5.png)
![image](https://user-images.githubusercontent.com/2685585/157507067-bf7d0dbd-7c49-47c4-9828-2ee80cee7e59.png)
![image](https://user-images.githubusercontent.com/2685585/157507238-09a7b4e4-dfa3-4c83-84bc-0afe72c46b47.png)

**Comment by scottcwilson** [comment]
> ... and the associated settings ending with _SEND would then be removed.
I would not be wild about this.
Sometimes people want to turn off and on this behavior but leave the email addresses in place.

**Comment by lat9** [comment]
> > Some fields can be blank and others not. The "Send Copy" fields can all be blank.
> 
> > it seems a new function might be required, ie:
> > ```
> > static public function sanitizeEmailNullOk(&$val) {
> > 		if (empty($val)) {
> > 			return true;
> > 		}
> >                return sanitizeEmail($val);
> > }
> > ```
> 
> as i stated above, i believe the new function below would work for the send copy. so the value for `val_function` would need to change for those values to the above function., ie,
> 
> ```
> UPDATE `configuration` SET
>     `val_function` = '{\"error\":\"TEXT_EMAIL_ADDRESS_VALIDATE\",\"id\":\"FILTER_CALLBACK\",\"options\":{\"options\":[\"configurationValidation\",\"sanitizeEmailNullOK\"]}}'
> WHERE `configuration_key` = 'SEND_EXTRA_ORDER_EMAILS_TO';
> ```

How about a slight name change: `sanitizeEmailOptional(&$val)`?

Additionally, since `empty` would be satisfied by '0' as well as '', I'd prefer a strict test for `=== ''`?

**Comment by mc12345678** [comment]
Where in the configuration options is an email required? 
If there was such a requirement, why is it not part of the installation? 

The only required email in installation is the admin user email address, even though email operations are not even setup in the install to help that admin user recover login.

Btw, this issue already had/has a solution in PR #4407.
