### ISSUE TITLE
ZC158 Admin, specials: PHP Warning: Undefined array key "page" when adding special

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4686]
php 8.16, strict reporting
select a product by the dropdown, add a price. Debug generated on Save.

> --> PHP Warning: Undefined array key "page" in ...\admin\specials.php on line 464.

**Comment by proseLA** [comment]
not a new issue, see #4531

**Comment by scottcwilson** [comment]
If I could revert PR #4502 I would but changes have been made on top of it. @mc12345678 would you please fix your stuff?

**Comment by torvista** [comment]
Actually these debugs are also generated when clicking on the specials in the list.

**Comment by lat9** [comment]
I'm not seeing this on the current v158 branch.  I
- Clicked on "Specials"
- Clicked on the "Add Special by Selection" button.
- Chose a product
- Added a price (no dates)
- Pressed "Save"

No log was generated.

**Comment by proseLA** [comment]
#4986 addressed this issue.

**Comment by scottcwilson** [comment]
Can this be closed @torvista ?
