### ISSUE TITLE
PayPal Pro not working in Zencart v1.5.7d with PHP 8.0.16

### ISSUE THREAD

**Issue by nntestinfo11** [zencart/zencart#4691]
**Describe the bug**
PayPal express checkout is working fine on checkout page. But when using PayPal pro (Credit Card) the continue button is not working. You can check here.

**Version**
Zen Cart version: **1.5.7d**
PHP version: **8.0.16 (Zend: 4.0.16)**
MySQL version: **5.7.23-23**
Plugins that may be related:  **NO PLUGIN INSTALLED. ITS FRESH COPY OF ZENCART.**
What older/newer versions were also tested? **ITS FRESH ZENCART 1.5.7d**

Template : **Responsive Classic Template**

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
On checkout page, PayPal Express is working fine, But when put credit card details in PayPal Pro(Card Area), And click on Continue Button its not working. Its not moving forward.

**Debug/Error Logs**
[11-Mar-2022 04:17:58 UTC] Request URI: /ajax.php?act=ajaxPayment&method=prepareConfirmation, IP address: 117.228.34.21
#1 zcAjaxPayment->prepareConfirmation() called at [/home2/dev1nlinksolutio/public_html/ajax.php:85]
--> PHP Warning: Undefined array key "cc_id" in /home2/dev1nlinksolutio/public_html/includes/classes/ajax/zcAjaxPayment.php on line 130.

[11-Mar-2022 04:17:58 UTC] Request URI: /ajax.php?act=ajaxPayment&method=prepareConfirmation, IP address: 117.228.34.21
#1 zcAjaxPayment->prepareConfirmation() called at [/home2/dev1nlinksolutio/public_html/ajax.php:85]
--> PHP Warning: Undefined variable $paypaldp in /home2/dev1nlinksolutio/public_html/includes/classes/ajax/zcAjaxPayment.php on line 167.

[11-Mar-2022 04:17:58 UTC] PHP Fatal error: Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in /home2/dev1nlinksolutio/public_html/includes/classes/ajax/zcAjaxPayment.php:167
Stack trace:
#0 /home2//public_html/includes/classes/ajax/zcAjaxPayment.php(167): method_exists(NULL, 'alterShippingEd...')
#1 /home2//public_html/ajax.php(85): zcAjaxPayment->prepareConfirmation()
#2 {main}
thrown in /home2//public_html/includes/classes/ajax/zcAjaxPayment.php on line 167

[11-Mar-2022 04:17:58 UTC] Request URI: /ajax.php?act=ajaxPayment&method=prepareConfirmation, IP address: 117.228.34.21
--> PHP Fatal error: Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in /home2//public_html/includes/classes/ajax/zcAjaxPayment.php:167
Stack trace:
#0 /home2//public_html/includes/classes/ajax/zcAjaxPayment.php(167): method_exists(NULL, 'alterShippingEd...')
#1 /home2//public_html/ajax.php(85): zcAjaxPayment->prepareConfirmation()
#2 {main}
thrown in /home2//public_html/includes/classes/ajax/zcAjaxPayment.php on line 167.

**Comment by scottcwilson** [comment]
Would you please check again?  This may have been fixed.
