### ISSUE TITLE
delivery address change for store pickup?

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#4698]
https://github.com/zencart/zencart/blob/7e383aa8a48375cde4afdecec7ef7c859540f1ad/includes/classes/order.php#L149-L152

i do not like this section of code.  we are populating the delivery address of the order with the customer address; but if it is store pickup, we are saying there is no address.  which does not reflect what is in the database.

would a better solution not be to populate the delivery address withe the store address?  and then remove this section of code?

i find myself jumping through hoops with observers to address this information.  we have 3 different addresses in the orders table.  can we not populate the delivery address with the correct one?

**Comment by proseLA** [comment]
https://github.com/lat9/edit_orders/blob/37ec6ab8fb11c84d03228a24ddaae8eac7ad5e2a/YOUR_ADMIN/includes/classes/observers/EditOrdersAdminObserver.php#L147-L171

seems others need to do the same thing.

**Comment by scottcwilson** [comment]
I would be open to a PR.

**Comment by proseLA** [comment]
i'll take a look.

**Comment by proseLA** [comment]
ok, after taking a look, i'm punting on this.

the potential for conflict is too great for me.  the only address i see is stored in a config value, `STORE_NAME_ADDRESS`.

i'm not so interested in parsing this data and then presenting it (hopefully) to the admin in a proper manner.

it seems the proper way to handle this would be to have config values for the actual address in the shipping module.  and then the question i have is what happens when there are 2 stores from where a customer could pick up their order.

it also seems counter intuitive to store a delivery address of the customer's address in the database when clearly they have selected store pickup; and only change it on the query.

just seems like there are too many issues for me to want to effect a change.

perhaps someone else.

**Comment by scottcwilson** [comment]
Closing for now then.
