### ISSUE TITLE
PHP Fatal error: Uncaught Error: Undefined constant "TEXT_DATE_TIME" in tpl_down_for_maintenance_default.php

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4701]
Enable down for maintenance.
View Down for Maintenance shopfront page
Disable down for maintenance.
Refresh Down for Maintenance shopfront page: creates debug.

Constant exists only when down for maintenance is true:
https://github.com/zencart/zencart/blob/dc22072b1a1ea66b3e4fce9efe781ca43557f5e2/includes/modules/pages/down_for_maintenance/header_php.php#L19-L25

Suggested fix?

**Comment by scottcwilson** [comment]
When I test this, when I go to the down for maintenance page it goes to the home page instead right away with no log.

**Comment by torvista** [comment]
True.
After investigating further I find you also need to have your ip in the whitelist to trigger the debug.
Then it fails the redirect clause:
https://github.com/zencart/zencart/blob/dc22072b1a1ea66b3e4fce9efe781ca43557f5e2/includes/init_includes/init_customer_auth.php#L30-L32

**Comment by scottcwilson** [comment]
Still can't repro but looking at the code, I guess I would remove the if statement on 
includes/modules/pages/down_for_maintenance/header_php.php line 19.

**Comment by torvista** [comment]
php8.0.17 and strict reporting
I'm using locally and just put 127.0.0.1 in the whitelist.
Enable DFM, refresh to get DFM screen, disable, refresh: error.
The storefront footer is missing, but the rest of the page displays, so it's not so obvious it's broken.

Removing the If clause as suggested seems correct since normally it would not get here at all, only the admin IP.
