### ISSUE TITLE
bug in reset tokens in square

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#4702]
https://github.com/zencart/zencart/blob/dc22072b1a1ea66b3e4fce9efe781ca43557f5e2/includes/modules/payment/square.php#L601-L609

lines 605 and 607 need to end `')");` no `'");`

apparently no one is resetting their tokens.

**Comment by proseLA** [comment]
https://github.com/zencart/zencart/blob/dc22072b1a1ea66b3e4fce9efe781ca43557f5e2/includes/modules/payment/square.php#L685-L690
apparently no one is losing their refresh tokens, else the `resetTokensAndDisconnectFromSquare` method would have gotten called, and a fatal error resulting from the missing end parenthesis.

**Comment by scottcwilson** [comment]
Should we close now that the old Square module is deprecated?

**Comment by proseLA** [comment]
> Should we close now that the old Square module is deprecated?

i see a plan to deprecate the old module, but the code is still in the repo.

**Comment by scottcwilson** [comment]
Right, but it won't work in a couple of weeks, so people won't be running it anymore - right?

**Comment by scottcwilson** [comment]
@proseLA If you have time please fix since we're not getting rid of the old Square after all.
