### ISSUE TITLE
differences in address in order class based on method.

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#4709]
does anyone else get screwed up with the differences in the country based on the function called in the order class?  for example:

https://github.com/zencart/zencart/blob/bcb5e974ba036487bce144e53003e2ea702aa7af/includes/classes/order.php#L145

that section is in the query method.  country is a string.  now in the cart method, we have this:

https://github.com/zencart/zencart/blob/bcb5e974ba036487bce144e53003e2ea702aa7af/includes/classes/order.php#L474

country is now an array.

this inconsistency gets to be problematic when dealing with payment methods.  payment methods are inherently tied to an address.  and in my experience, plenty of store owners want to be able to accept additional payments AFTER the order comes in.  this can be for whatever reason.  and over the years i have found myself jumping through hoops to ensure that i get the right country field into the payment method. 

i think we should convert all of the address fields from the query back into an array.  could mean a bunch more code changes, but it  makes much more sense to me.

thoughts?

**Comment by scottcwilson** [comment]
> does anyone else get screwed up with the differences in the country based on the function called in the order class?
Yes sir.

**Comment by proseLA** [comment]
i'm going to change this as soon as i have time.  i thought it might be a problem on the admin side; but it seems that `zen_address_format` takes care of any potential difference in the structure:

https://github.com/zencart/zencart/blob/ee3ee1581705d1f11c38afe34c3a7ba13746fda4/includes/functions/functions_addresses.php#L293-L305
