### ISSUE TITLE
1.5.7d IgnoreDups not stopping all duplicates being ignored.

### ISSUE THREAD

**Issue by brittainmark** [zencart/zencart#4712]
**Describe the bug**
The Ignore Duplicates configuration flag is not loaded early enough to prevent some duplicate configuration keys being reported.
I use zen_Image-Handler and the key zen_Image-HandlerIH_DEBUG_ADMIN is reporting as a duplicate for every page.
**Version**
Zen Cart version: 1.5.7d
PHP version: 8.0
MySQL version: 8.0.17 
Plugins that may be related: Image Handler
What older/newer versions were also tested? none

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Load any store or admin page.

**Expected behavior**
Duplicate not be reported

**Screenshots**
none

**Debug/Error Logs**
```
[03-Apr-2022 08:44:01 Europe/London] Request URI: /test/, IP address: 127.0.0.1
#1  define() called at [/home/lotus/public_html/innerlightcrystals/test/includes/init_includes/init_db_config_read.php:26]
#2  require_once(/home/lotus/public_html/innerlightcrystals/test/includes/init_includes/init_db_config_read.php) called at [/home/lotus/public_html/innerlightcrystals/test/includes/autoload_func.php:37]
#3  require(/home/lotus/public_html/innerlightcrystals/test/includes/autoload_func.php) called at [/home/lotus/public_html/innerlightcrystals/test/includes/application_top.php:222]
#4  require(/home/lotus/public_html/innerlightcrystals/test/includes/application_top.php) called at [/home/lotus/public_html/innerlightcrystals/test/index.php:25]
--> PHP Warning: Constant IH_DEBUG_ADMIN already defined in /home/lotus/public_html/innerlightcrystals/test/includes/init_includes/init_db_config_read.php on line 26.
```

 
**Devices (please complete the following information):**
 - Operating System: windows10
 - Browser [e.g. chrome, firefox] and version number firefox 98.0 64bit

**Additional context**
two possible fixes:
1)  mod includes/extra_configures/enable_error_logging.php lines 28-33 from
 ```
$ignore_dups = false;
    if (IS_ADMIN_FLAG === true) {
        $ignore_dups = (defined('REPORT_ALL_ERRORS_ADMIN') && REPORT_ALL_ERRORS_ADMIN == 'IgnoreDups');
    } else {
        $ignore_dups = (defined('REPORT_ALL_ERRORS_STORE') && REPORT_ALL_ERRORS_STORE == 'IgnoreDups');
    }
```
to  
```
if (IS_ADMIN_FLAG === true) {
        if (!defined('REPORT_ALL_ERRORS_ADMIN')) {
            $use_cache = (isset($_GET['nocache']) ? false : true ) ;
            $configuration = $db->Execute('SELECT configuration_key AS cfgkey, configuration_value AS cfgvalue, configuration_group_id
                                 FROM ' . TABLE_CONFIGURATION . ' WHERE configuration_key = "REPORT_ALL_ERRORS_ADMIN"', '', $use_cache, 150);
            if ($configuration->RecordCount() > 0) define(strtoupper($configuration->fields['cfgkey']), $configuration->fields['cfgvalue']);
        } 
        $ignore_dups = (defined('REPORT_ALL_ERRORS_ADMIN') && REPORT_ALL_ERRORS_ADMIN == 'IgnoreDups');
    } else {
        if (!defined('REPORT_ALL_ERRORS_STORE')) {
            $use_cache = (isset($_GET['nocache']) ? false : true ) ;
            $configuration = $db->Execute('SELECT configuration_key AS cfgkey, configuration_value AS cfgvalue, configuration_group_id
                                 FROM ' . TABLE_CONFIGURATION . ' WHERE configuration_key = "REPORT_ALL_ERRORS_ADMIN"', '', $use_cache, 150);
            if ($configuration->RecordCount() > 0) define(strtoupper($configuration->fields['cfgkey']), $configuration->fields['cfgvalue']);
        } 
        $ignore_dups = (defined('REPORT_ALL_ERRORS_STORE') && REPORT_ALL_ERRORS_STORE == 'IgnoreDups');
    }
```
You would also need a global $db statement, which could be added at the top or in the if statements.  
OR     

2. mod select in includes/init_includes/init_db_config_read.php line 17 and admin/includes/Init_includes/init_db_config_read.php line 30
to
```
'SELECT configuration_key AS cfgKey, configuration_value AS cfgValue FROM  ' . TABLE_CONFIGURATION . ' WHERE configuration_key IN ("REPORT_ALL_ERRORS_ADMIN","REPORT_ALL_ERRORS_STORE")
UNION
SELECT configuration_key AS cfgKey, configuration_value AS cfgValue FROM  ' . TABLE_CONFIGURATION 
```
This will cause the report errors to be processed first.

Also noticed a difference in the processing of the define statements. I assume that admin does not use configuration groups  2 or 3 or it does not matter if they are not processed as integers.

**Comment by lat9** [comment]
I'm not seeing this running zc157d running with IH 5.2.0.  Note that in the base IH distribution, the setting `IH_DEBUG_ADMIN` is a pseudo-configuration setting, set by (whichever gets there first):
- /includes/extra_datafiles/image_handler_logging.php
- /includes/classes/bmz_image_handler_class.php
- /admin/includes/classes/observers/ImageHandlerAdmin.php

In each of those modules, the constant is defined only if it's not already defined.

**Comment by brittainmark** [comment]
This happens on my installation. I raised it not specifically because of image handler. This could occur with anything that sets a config variable that is held in the database before init_db_config that is selected before REPORT_ALL_ERRORS_++++

I found that I had IH_ADMIN_DBUG in my configuration table. I assume it should not be there. I raised the bug against the zen_cart code not the Image_handeler code,

**Comment by lat9** [comment]
A lot of sites use that method to override configuration settings.  I'm not sure that I see the utility of overcomplicating the base Zen Cart logging to deal with the side effect.  You're not running with 'IgnoreDups' on a live site, are you?

**Comment by brittainmark** [comment]
Not at the moment. Quite happy for it to be shelved. Just thought I would raise it in case anyone else had found that IgnoreDups did not stop all the warning messages.
