### ISSUE TITLE
Also Purchased Products query causes unwanted SQL server reboots

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4718]
**Describe the bug**
A site I manage has an `orders` table approaching 100,000 records with an `orders_products` that's closing in on 2,000,000 records.

Since the upgrade to zc157d, I've noticed frequent error logs indicating that the SQL server has restarted.  When I requested information from the site's webhost, support pointed to the SQL_ALSO_PURCHASED query as the culprit.  The site uses a count value of 6 for the display.

When I plug that query into the site's phpMyAdmin (with a specific product 'filled in'), the query runs upwards of 14 seconds to produce a result.
```
DEFINE('SQL_ALSO_PURCHASED', "SELECT p.products_id, p.products_image, max(o.date_purchased) as date_purchased
                     FROM " . TABLE_ORDERS_PRODUCTS . " opa, " . TABLE_ORDERS_PRODUCTS . " opb, "
                            . TABLE_ORDERS . " o, " . TABLE_PRODUCTS . " p
                     WHERE opa.products_id = %u
                     AND opa.orders_id = opb.orders_id
                     AND opb.products_id != %u
                     AND opb.products_id = p.products_id
                     AND opb.orders_id = o.orders_id
                     AND p.products_status = 1
                     GROUP BY p.products_id, p.products_image
                     ORDER BY date_purchased desc, p.products_id");
```

I've also tried the updated version of the query for zc158:
```
DEFINE('SQL_ALSO_PURCHASED', "SELECT p.products_id, p.products_image, max(o.date_purchased) as date_purchased
                     FROM " . TABLE_ORDERS_PRODUCTS . " opa
                     INNER JOIN " . TABLE_ORDERS_PRODUCTS . " opb ON (opa.orders_id = opb.orders_id)
                     INNER JOIN " . TABLE_ORDERS . " o ON (opb.orders_id = o.orders_id)
                     INNER JOIN " . TABLE_PRODUCTS . " p ON (opb.products_id = p.products_id)
                     WHERE opa.products_id = %u
                     AND opb.products_id != %u
                     AND p.products_status = 1
                     GROUP BY p.products_id, p.products_image
                     ORDER BY date_purchased desc, p.products_id");
```
... with no major difference in the time-to-result.

**Version**
Zen Cart version:  zc157d
PHP version: N/A
MySQL version: 5.7, but the results also occur on my localhosted MySQL 5.5.5-10.4.10-MariaDB
Plugins that may be related: None
What older/newer versions were also tested?  See above.

**Expected behavior**
The query shouldn't be bringing the SQL server to its knees.

**Additional context**
MySQL is not my one of my 'native' languages, but I believe that the source of the issue is the sheer volume of records that are required by the query.

I've tried a couple of modifications, which brought the time-to-response down to 4-ish seconds, with the best one being:
```
define('SQL_ALSO_PURCHASED',
   "SELECT DISTINCT p.products_id, p.products_image
      FROM " . TABLE_ORDERS_PRODUCTS . " opb
            INNER JOIN " . TABLE_PRODUCTS . " p ON p.products_id = opb.products_id
     WHERE opb.products_id != %u
       AND p.products_status = 1
       AND opb.orders_id IN (
              SELECT orders_id FROM " . TABLE_ORDERS_PRODUCTS . " WHERE products_id = %u
           )
     ORDER BY opb.orders_id DESC, p.products_id ASC"
);
```
That removes the reliance on (a) the `orders` table (b) the MAX() function and (c) the GROUP BY.

I'm 'fixing to' deploy this for my client, but would appreciate a couple of MySQL-speaking eyes to see if I'm heading in the right direction.

**Comment by scottcwilson** [comment]
If it was me I'd constrain the orders_products query with a date (so orders_id > X where X an order placed 3 years ago, for example).

**Comment by lat9** [comment]
Agreed, but that's going to bring in that massive `orders` table to the query as well.  Additionally, should the query be returning sold-out products?

**Comment by scottcwilson** [comment]
You are checking status=1 so I think that's sufficient. 
If you wanted to avoid that query, you could just create a constant (say ORDERS_PER_MONTH) and then just subtract that value * 36 from the last order number. 
You're going to have to test all this to make sure it works but short of that I would just disable also sold products for a store like this - it's not worth waiting even 4 seconds for a page load.

**Comment by proseLA** [comment]
i am a big fan of CTE.  they make queries much easier to read.

i do not believe mysql 5.7 supports them.  you could try under that maria db version, as it looks like it supports them.

i am NO db expert, but as your result set is from the product table, i think that should be your primary table.

i am not sure if this improves performance as i do not have that big a dataset to play with, but perhaps try:

```
with
  orderNumbers as (
    select distinct orders_id from orders_products where products_id = 8687
  ),
  productNumbers as (
    select distinct products_id as pid from orders_products where orders_id in (
     select * from orderNumbers
    )
  )

select products_id, products_image from products
inner join productNumbers on pid = products_id
where products_id != 8687 and products_status = 1
```

(you can replace table names and product ids as necessary.)

hope that helps.

**Comment by brittainmark** [comment]
Long shot. Rarely is it faster to use a sub-select rather than a join but as you are joining a very large table to itself you could try  
```
define('SQL_ALSO_PURCHASED',"SELECT p.products_id, p.products_image, max(o.date_purchased) as date_purchased
                     FROM  " . TABLE_PRODUCTS . " p
                     INNER JOIN  " . TABLE_ORDERS . " o ON (op.orders_id = o.orders_id)
                     INNER JOIN  " . TABLE_ORDERS_PRODUCTS . " op ON (op.products_id = p.products_id)
                     WHERE o.orders_id in (SELECT sop.orders_id FROM  " . TABLE_ORDERS_PRODUCTS . " sop WHERE sop.products_id = %u)
                     AND p.products_id != %u
                     AND p.products_status = 1
                     GROUP BY p.products_id, p.products_image
                     ORDER BY date_purchased desc, p.products_id");
```
This is definitely slower on small tables.
You could also limit the orders in the sub-select.

**Comment by lat9** [comment]
Thanks, @brittainmark, I'd tried that too.  In posting this issue, I was attempting to find a general solution (for all large orders/orders_products tables sites), but I'll most likely do a core-file edit (which I hate to do) for the referenced site.

**Comment by lat9** [comment]
Oh my!  Somehow (I'm guessing in the update of the database to utf8mb4), one of the important keys for the orders_products table got wiped.

Re-adding that key
```
ALTER TABLE orders_products ADD INDEX `idx_orders_id_prod_id_zen` (`orders_id`,`products_id`);
```
resulted in a reduction from 1.6764271259308 seconds to 0.16917109489441 seconds ... a fair improvement.  I'm guessing that the "wipe" occurred when the utf8mb4-conversion.php script timed out on that humongous `orders_products` table.
