### ISSUE TITLE
ZC158: paypalwpp.php: Undefined array key "L_PAYMENTREQUEST_0_NAME0", L_PAYMENTREQUEST_0_AMT0, L_PAYMENTREQUEST_0_QTY0

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4722]
php 8.0.17 same error on production and local server.
I have a modified module file, but these line numbers reflect the vanilla file.

> Request URI: /ipn_main_handler.php?type=ec&markflow=1&clearSess=1&stage=final
> IP address: 127.0.0.1
> #1  paypalwpp->getLineItemDetails() called at [CATALOG/includes/modules/payment/paypalwpp.php:1744]
> #2  paypalwpp->ec_step1() called at [CATALOG/ipn_main_handler.php:75]
> --> PHP Warning: Undefined array key "L_PAYMENTREQUEST_0_NAME0" in ...\includes\modules\payment\paypalwpp.php on line 1371.
> 
> Request URI: /ipn_main_handler.php?type=ec&markflow=1&clearSess=1&stage=final
> IP address: 127.0.0.1
> #1  paypalwpp->getLineItemDetails() called at [CATALOG/includes/modules/payment/paypalwpp.php:1744]
> #2  paypalwpp->ec_step1() called at [CATALOG/ipn_main_handler.php:75]
> --> PHP Warning: Undefined array key "L_PAYMENTREQUEST_0_AMT0" in ...includes\modules\payment\paypalwpp.php on line 1374.
> 
> Request URI: /ipn_main_handler.php?type=ec&markflow=1&clearSess=1&stage=final
> IP address: 127.0.0.1
> #1  paypalwpp->getLineItemDetails() called at [CATALOG/includes/modules/payment/paypalwpp.php:1744]
> #2  paypalwpp->ec_step1() called at [CATALOG/ipn_main_handler.php:75]
> --> PHP Warning: Undefined array key "L_PAYMENTREQUEST_0_QTY0" in ...\includes\modules\payment\paypalwpp.php on line 1393.
> 

I believe this is caused by the products having price of zero/Price is Free.
Shipping is 7 euros,
Cart has only the one product.
I didn't feel like setting up a vanilla cart with paypal to demonstrate as it seems pretty clear.
Here is the start of the loop that parses the cart contents. When this is zero cost, it jumps out of the loop:
https://github.com/zencart/zencart/blob/8b59c2160c9e61bda9a78e44d9e35b7fad8fd566/includes/modules/payment/paypalwpp.php#L1294-L1301

But inside the loop are set the array elements referenced in the error log.

After the loop these lines cause the errors as the array elements have not been set.
```
$optionsLI["L_PAYMENTREQUEST_0_NAME$k"] = str_replace(array('&','=','%'), '*', $optionsLI["L_PAYMENTREQUEST_0_NAME$k"]);
$optionsLI["L_PAYMENTREQUEST_0_AMT$k"] = round($optionsLI["L_PAYMENTREQUEST_0_AMT$k"], 2);
$itemQTY = $optionsLI["L_PAYMENTREQUEST_0_QTY$j"];
```

Maybe Paypal experts can suggest the best way to set these or just check for empty on the offending lines, given the comment
// PayPal is inconsistent in how it handles zero-value line-items, so skip this entry if price is zero

**Comment by torvista** [comment]
I decided to check for empty, since there could be any number of elements.

**Comment by lat9** [comment]
My current thought on this is that line 1297 should be modified to read
```
        if ($n !== 1 && $order->products[$i]['final_price'] == 0) {
```

That will ensure that there's at least one `PAYMENT_REQUEST_0_` element of each 'type' created by that upper loop, making the follow-on code "happy".
