### ISSUE TITLE
Remove old version of Square from 1.5.8 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4725]
The existing Square implementation is being sunsetted and should be removed from the build.

**Comment by dbltoe** [comment]
Unfortunately, we've yet to get a decision on which of the old files MUST stay.

i.e., deleting the includes/modules/payment/square_support folder results in a partial blank page when trying to view the details of any order that used the Square Payment method.

I do believe ProseLA is working on this but am not in the loop.

Personally, that removal is the only problem experienced by any of our customers.  So far, in the instances where we removed all but that folder, we have seen an occasional error for line 234 of squareWebPay_handler.php but, I cannot say with any certainty what is causing the problem.

**Comment by scottcwilson** [comment]
> Unfortunately, we've yet to get a decision on which of the old files MUST stay.

That's part of the work for this PR.

**Comment by scottcwilson** [comment]
I deleted `includes/modules/payment/square_support` and don't see any logs.  Please post your logs so I can check.

**Comment by dbltoe** [comment]
You will not see a log BUT, click on a new order from the home page.
On the Orders page, find an order using Square.
click on that order then click on Details.
You will get a partial blank screen ending after the Date Purchased.

**Comment by scottcwilson** [comment]
Can not reproduce.  Works fine on mine.

**Comment by scottcwilson** [comment]
To be clear: this is in 1.5.8 with an imported and upgraded 1.5.7 database that has Square orders.
I would not recommend removing these files from a 1.5.7 installation until you do the upgrade.

**Comment by lat9** [comment]
@proseLA, will stores that upgrade to use `square_webPay` be able to manage pre-existing orders that were placed via `square`?

**Comment by scottcwilson** [comment]
I am assuming these will be old enough so it's not relevant.  People can still install the old plugin if they need it.   We removed linkpoint, for example.

**Comment by proseLA** [comment]
> @proseLA, will stores that upgrade to use `square_webPay` be able to manage pre-existing orders that were placed via `square`?

i am not real sure what you mean by 'manage'?  if you mean, give refunds and the like on the order, i would guess no, not without changing the orders table.  if you mean, add order comments, change order statuses, etc without generating error logs, my guess would be yes.

note that prior to doing this module, i had ZERO experience with square, and i have zero clients who use square.

on my v158 dev site, i frequently have my module there, and then the files are deleted.  on v158, looking at order processed with square with those files removed, i see this on the orders page:

![image](https://user-images.githubusercontent.com/1095136/177208140-eb5c977f-5420-4622-9ade-dec856f3b6c0.png)

ZC generates no error logs in this situation (that i see) while running either php 7.4, 8.0, or 8.1.

hope that helps!

**Comment by dbltoe** [comment]
> will stores that upgrade to use square_webPay be able to manage pre-existing orders that were placed via square?

What I did for our customers was changed the orders - payment_module_code from square to square_webPay.

No glitches so far BUT, we are keeping the one folder includes/modules/payment/square_support.  We do get errors without that.

**Comment by scottcwilson** [comment]
Decided to abandon this PR; too many other more important things to worry about.
