### ISSUE TITLE
PayPal Log Errors on PayPal Here Transactions

### ISSUE THREAD

**Issue by daphilli224** [zencart/zencart#4745]
**Describe the bug**
Fatal error on undefined constant MODULE_PAYMENT_PAYPAL_CURRENCY in paypal_functions.php, and undefined array keys "payment" and "shipping" in ipn_main_handler.php when a PayPal Here transaction occurs.

**Version**
Zen Cart version: 1.5.7c
PHP version: 8.0.2
MySQL version: 8.0.8
Plugins that may be related: no related plugins
What older/newer versions were also tested? none

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Turn on PayPal debug mode (log file) if not already on
2. Execute PayPal Here transaction where the PayPal account is also used in a zen-cart store
3. See IPN logs including one or more IPN warning logs
4. See errors in warning log

**Expected behavior**
Zen cart should not process any IPN messages with txn_type = 'paypal_here' since PayPal Here is not integrated into Zen Cart to my knowledge.

**Screenshots**
If applicable, add screenshots to help explain.

**Debug/Error Logs**
The following is edited copy of typical IPN warning log associated with a PayPal Here transaction:
[24-Apr-2022 17:02:55 America/New_York] Request URI: /ipn_main_handler.php, IP address: XXX.X.XX.XX
--> PHP Warning: Undefined array key "payment" in /[path to zen-cart]/ipn_main_handler.php on line 295.

[24-Apr-2022 17:02:55 America/New_York] Request URI: /ipn_main_handler.php, IP address: XXX.X.XX.XX
--> PHP Warning: Undefined array key "shipping" in /[path to zen-cart]/ipn_main_handler.php on line 296.

[24-Apr-2022 17:02:55 America/New_York] PHP Fatal error:  Uncaught Error: Undefined constant "MODULE_PAYMENT_PAYPAL_CURRENCY" in /[path to zen-cart]/includes/modules/payment/paypal/paypal_functions.php:182
Stack trace:
#0 /[path to zen-cart]/includes/modules/payment/paypal/paypal_functions.php(196): select_pp_currency()
#1 /[path to zen-cart]/ipn_main_handler.php(311): valid_payment(0, 'USD')
#2 {main}
  thrown in /[path to zen-cart]/includes/modules/payment/paypal/paypal_functions.php on line 182

[24-Apr-2022 17:02:55 America/New_York] Request URI: /ipn_main_handler.php, IP address: XXX.X.XX.XX
--> PHP Fatal error: Uncaught Error: Undefined constant "MODULE_PAYMENT_PAYPAL_CURRENCY" in /[path to zen-cart]/includes/modules/payment/paypal/paypal_functions.php:182
Stack trace:
#0 /[path to zen-cart]/includes/modules/payment/paypal/paypal_functions.php(196): select_pp_currency()
#1 /[path to zen-cart]/ipn_main_handler.php(311): valid_payment(0, 'USD')
#2 {main}
  thrown in /[path to zen-cart]/includes/modules/payment/paypal/paypal_functions.php on line 182.

 
**Devices (please complete the following information):**
 - Operating System: Mac OS 11.6.5
 - Browser: Firefox 99.0.1
 - Also occurs on Windows 10 machine with Firefox

**Additional context**
Our organization occasionally operates our store in person in addition to our online presence. When operating in person, payment is made with cash, or with a credit card using the PayPal Here card reader. We have done this for years without any problems or noticing any error messages, but sometime after transitioning from zen cart 155f to 157c and to php 8, IPN warning logs began appearing. No changes were made to the PayPal settings in zen cart. An IPN log and an IPN warning log appeared for each PayPal Here transaction; sometimes more than one log occurred when the credit card was inserted incorrectly in the card reader, or the card rejected for some reason. Examining the logs revealed all were associated with PayPal Here transactions and had a transaction type of 'paypal_here'.

One possible fix that I implemented and that appears to work correctly is to die in ipn_main_handler.php when the $_POST['txn_type'] of an incoming IPN message equals 'paypal_here'. I inserted the following at line 105 of ipn_main_handler.php:
if (isset($_POST['txn_type']) && $_POST['txn_type'] == 'paypal_here') die(); // do not process IPN messages from PayPal Here transactions

I suppose another solution might be to turn off PayPal debug mode, but we prefer to keep the logs for any potential questions or problems that may occur with an online transaction. We save the logs online for a month, then save offline for three years and then delete them.

**Comment by lat9** [comment]
@daphilli224, do you still have a copy of the paypal debug logs?  That would help to identify the processing path that's causing the issues.

**Comment by daphilli224** [comment]
Logs attached from the transaction reported in the issue. I edited the business email, purchaser email, and path to zencart. I do not have http request and response logs if there were any. Hope the logs help.

Dave

**Comment by lat9** [comment]
Dave, I'm not seeing that attachment.
