### ISSUE TITLE
admin: init_gzip defines need a review?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4750]
These hard-coded defines seem out of place:
https://github.com/zencart/zencart/blob/fef8d4d40d0bbd3179116b7a2536653d78fa0947/admin/includes/init_includes/init_gzip.php#L12-L16

I only find them used in the BackupMySQL mod, so it appears they should not be here in vanilla code?

**Comment by scottcwilson** [comment]
If we remove these it will break everyone who has an old copy of backup manager.   People don't necessarily update all their plugins on an upgrade.

**Comment by torvista** [comment]
Apart from them not being used by Zen Cart, there's no provision for other (local) environments, so even more reason they should in the plugin, and not here.
