### ISSUE TITLE
Addressing `strftime` deprecation in PHP 8.1 and additional date-formatting options

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4756]
Breaking this issue out as (initially) a discussion regarding the ultimate solution to the issue.  Much discussion is present in #4449 with possibilities presented by @proseLA.

**Comment by lat9** [comment]
Starting by copying this pertinent post from the 'parent' issue:

despite #4553 being closed, i have not given up on this problem.  as i stated above, i believe a class file is the way to handle it.  the class file could be something such as:
```
<?php

    class zcDate
    {
        var $language_code;

        function __construct()
        {
            $this->language_code = setlocale(LC_TIME, 0);
        }

        function output(string $string = 'MMMM/dd/yyyy', int $timestamp = 0)
        {
            if ($timestamp === 0) {
                $timestamp= time();
            }
            $this->dateObject = datefmt_create(
                $this->language_code,
                IntlDateFormatter::FULL,
                IntlDateFormatter::FULL,
                date_default_timezone_get(),
                IntlDateFormatter::GREGORIAN,
                $string
            );
            return $this->dateObject->format($timestamp);
        }
    }
```
within `application_top` or somewhere of your choosing, we could create a var for use such as `$zcDate = new zcDate();` so that it is globally available.  we could then replace all `strftime` calls with `$zcDate->output(FORMAT, TIMESTAMP);`.  we could also eliminate the 12 months in all language files.

what would need to be decided is how to set the language_code in the `_construct` above.  and whether that should be a new constant or how that gets set. 

thoughts?

_Originally posted by @proseLA in https://github.com/zencart/zencart/issues/4449#issuecomment-1029566848_

**Comment by proseLA** [comment]
some thoughts:

- new configuration value, despite how much i abhore adding another one.
- perhaps start minimizing the potential choices store owners have for date fields to 2 or 3.  is this even possible?

back when i had more time and was more motivated, i worked extensively on this problem.  the core of my work is the new class as seen here:

https://github.com/proseLA/zencart/blob/zcDate/includes/classes/zcDate.php

that branch has only 1 commit, which is seem here:

https://github.com/proseLA/zencart/commit/3cf8ccaa903959a931e5a48bbf34cd5937c50a53

i attempted to get at every instance of `strftime` and convert it using the php international date format.  one must have the php international date formatter installed and be running php 8.1 to use said format.

in theory, the output should remain the same.

the class has a `debug` method for comparing formats to see if they work.

as documented in the previous thread, one could copy the above class file, create a `test.php` script in the root directory of their test store and play accordingly.  here would be a sample starting point:

```
<?php
    declare(strict_types=1);
    require('includes/application_top.php');

    include_once DIR_FS_CATALOG . DIR_WS_CLASSES . 'zcDate.php';


    $zcDate = new zcDate();
    echo "----888---->" . $zcDate->output() . "<---------<br>";
    echo "----month-1---->" . $zcDate->output('MMMM', 1609488000) . "<---------<br>";

    $zcDate = new zcDate('ca_ES');
    echo "----888---->" . $zcDate->output() . "<---------<br>";
    echo "----month-1---->" . $zcDate->output('MMMM', 1609488000) . "<---------<br>";


    die('<br>' . __FILE__ . ':' . __LINE__);
```

**Comment by lat9** [comment]
Also found [this](https://github.com/alphp/strftime/blob/master/src/php-8.1-strftime.php) potential update strictly for the strftime deprecation.

**Comment by proseLA** [comment]
> Also found [this](https://github.com/alphp/strftime/blob/master/src/php-8.1-strftime.php) potential update strictly for the strftime deprecation.

i think this is interesting.  but if you look at [this issue (and read all the comments), ](https://github.com/alphp/strftime/issues/8) you can see the potential problems that exist.

i am not sure i am a fan of this approach.  they are trying to do a 1 to 1 replacement for `strftime`.  so, assuming we go that route, developers and store owners would have to preserve and keep on with the `strftime` formats.  as opposed to using the actual date format that php plans to support going forward.

while this approach may seem like an easier approach, i'm not sure, in the long run, it will be productive.

i think it could be a stopgap measure to install for potential plugins that still use it; albeit i would suggest creating a log for all instances that use it.

i kept a bunch of conversion formats in the class for those installs that are not running php 8.1 and/or do not have the international date installed.  you can see that here:

https://github.com/proseLA/zencart/blob/3cf8ccaa903959a931e5a48bbf34cd5937c50a53/includes/classes/zcDate.php#L77-L82

i do NOT support the idea of keep `strftime` in zc core code because we found a replacement function that potentially could work.  i do support potentially using this replacement function so that store owners can know which plugins still make use of a deprecated function.

i'm still a fan of creating a new date class and using that as we see fit.  and using the new date formats that will be supported going forward.

i'm also a fan of minimizing the number of constants we use for date formats.

just MO.

**Comment by lat9** [comment]
I wasn't proposing keeping the strftime, per se, but trying to mitigate the issues for various uses of strftime for both core and plugin usage.  For example, using your class as a replacement for strftime, I'm receiving
```
[01-May-2022 13:41:00 UTC] Request URI: /zc158/, IP address: 127.0.0.1
#1  zcDate->output() called at [C:\xampp\htdocs\zc158\includes\counter.php:55]
#2  require(C:\xampp\htdocs\zc158\includes\counter.php) called at [C:\xampp\htdocs\zc158\includes\application_top.php:253]
#3  require(C:\xampp\htdocs\zc158\includes\application_top.php) called at [C:\xampp\htdocs\zc158\index.php:25]
--> PHP Warning: Undefined array key "%A %d %B, %Y" in C:\xampp\htdocs\zc158\includes\classes\zcDate.php on line 100.
```

FWIW, I'm having a devil of a time figuring out how to 'manage' those different date formats.  @drbyte had a start, comparing the strftime vs. date formats in #4449, but it would help to have a fully-fleshed-out table to include the IntlDateFormatter's formats, too.

**Comment by proseLA** [comment]
its been a bit since i looked at this code.  unfortunately i do not document things so well...  and it was intended as a work in progress.  in addition, i'm not tying to your line numbers; however this is what i have found:

- with debug off, you should pass an international date format string.
- with debug on, you should pass a strftime format string.

so in includes/counter.php assuming debug is off, if i were to pass: `echo $zcDate->output('EEEE dd MMMM, yyyy');` the results are `Sunday 01 May, 2022`.

now if i turn debug on, i would need to pass `echo $zcDate->output('%A %d %B, %Y');` and the results are `Sunday 01 May, 2022` (ie they are the same).

i do get an undefined array key.  and that is because this line is commented out:

https://github.com/proseLA/zencart/blob/3cf8ccaa903959a931e5a48bbf34cd5937c50a53/includes/classes/zcDate.php#L20

and there needs to be a define for that constant:
```
define('PHP_DATE_FORMAT_LONG', 'l d F, Y');
```

and when all of that is in place, the debug log gives me:
```
[01-May-2022 08:43:41 America/Los_Angeles] strftime format string: %A %d %B, %Y Result: {"intlDate":"Sunday 01 May, 2022","phpDate function":"Sunday 01 May, 2022","strftime":"Sunday 01 May, 2022"}
```
there are times when the intlDate format are not needed, ie the date is in just numbers.  in addition, i can see the possibility of some installs running php 8.1 and NOT having the international date format installed.  so i wanted to account for all of those possibilities.

i used the debug part of my class to take a strftime format, and then work with it to create the other 2 formats.  and the tables for the conversions are part of the 2 arrays seen here:

https://github.com/proseLA/zencart/blob/3cf8ccaa903959a931e5a48bbf34cd5937c50a53/includes/classes/zcDate.php#L11-L62

i created those arrays based on all of the date formats that i found in the base ZC code.

hope that helps.

**Comment by lat9** [comment]
I've had a chance to 'percolate' the changes required; following is my current proposal/pseudo-design-document.  As we work through the design, I'll be updating this section so that there's documentation of the to-be-developed interface.

Comments and corrections appreciated.

# Proposal for `strftime` Replacement

For the replacement of the to-be-deprecated in PHP 8.1+  `strftime`  function, I propose that we make use of a `zcDate` class as proposed by @prosela.  That class' intended use will be to support the *locale-specific* day-of-week and month names, using a _subset_ of the available formats supported by `strftime`.

The `zcDate` class will process the formatting request, based on the PHP version and the availability of the `IntlDateFormatter` class

1. If the PHP version is less than 8.1, use the `strftime` function.
2. Otherwise
   1. If the `IntlDateFormatter` class is available, as detected by the presence of the `datefmt_create` function, use the `datefmt_create` function.
   2. Otherwise, use the `date` function (which will display the day-of-week and month names in English only).  For this case,
      1. The `%X` format (preferred date format based on locale) will use a language-specific formatting constant `DATE_FORMAT_SHORT`.
      2. The `%x` format (preferred time format based on locale) will use the `%H:%M:%S` format.

  See the **_`strftime` Format Conversion_** section below for the conversions required for the supported date-formatting possibilities.

Core files currently using `strftime` (see the ***In-Core Use*** section, below) will be modified to either

1. Convert the request to use the PHP `date` function if no locale-specific formatting is required.
2. Convert the request to use `zcDate` otherwise.

The `zcDate` class will be loaded by both the `core` and `paypal_ipn` auto-loaders at load-point 0 and instantiated at load-point 115 in both auto-loaders, since the locale is set by the currently-active language file (loaded during load-point 110 processing).

## Analysis

The format strings used by `IntlDateFormatter` are documented [here](https://unicode-org.github.io/icu/userguide/format_parse/datetime/#date-field-symbol-table).

### In-Core Use

The following Zen Cart "core" modules are currently making use of `strftime`:

| Module Name                                                  | Formats Used                                           |
| ------------------------------------------------------------ | ------------------------------------------------------ |
| /admin/banner_statistics.php                                 | %B                                                     |
| /admin/includes/classes/stats_sales_report_graph.php         | `%T %x`, %H, %x, `%b %y`                               |
| /admin/includes/functions/functions_banner_graphs.php        | %b                                                     |
| /admin/includes/header.php                                   | ADMIN_NAV_DATE_TIME_FORMAT (`%A %d %b %Y %X`)          |
| /admin/includes\modules\dashboard_widgets\BaseStatisticsDashboardWidget.php | DATE_FORMAT_SHORT (`%m/%d/%Y`)                         |
| /admin/includes\modules\dashboard_widgets\TrafficDashboardWidget.php | DATE_FORMAT_SHORT (`%m/%d/%Y`), `%a %d`                |
| /includes/classes/order.php                                  | DATE_FORMAT_LONG (`%A %d %B, %Y`)                      |
| /includes/classes/traits/NotifierManager.php                 | `%Y-%m-%d %H:%M:%S`                                    |
| /includes/counter.php                                        | DATE_FORMAT_LONG (`%A %d %B, %Y`)                      |
| /includes/functions/functions_dates.php                      | DATE_FORMAT_LONG (`%A %d %B, %Y`), `%m/%d/%Y %H:%M:%S` |
| /includes/functions/functions_files.php                      | `%m/%d/%Y %H:%M:%S`                                    |
| /includes/modules/new_products.php                           | %B                                                     |
| /includes/modules/payment/authorizenet.php                   | `%B - (%m)`, %y, %m, %Y                                |
| /includes/modules/payment/authorizenet_aim.php               | `%B - (%m)`, %y, %m, %Y                                |
| /includes/modules/payment/paypaldp.php                       | `%B - (%m)`, %y, %m, %Y                                |
| /includes/modules/specials_index.php                         | %B                                                     |
| /laravel/vendor/illuminate/database/Query/Grammars/SQLiteGrammar.php | ???                                                    |
| /laravel/vendor/nesbot/carbon/src/Carbon/Traits/Date.php     | ???                                                    |

### `strftime` Format Conversion

| `strftime` | `datefmt_create` |   `date`   | Description                                                  |
| :--------: | :--------------: | :--------: | ------------------------------------------------------------ |
|    `%a`    |       `E`        |    `D`     | Abbreviated day name, based on locale, e.g. Sun through Sat  |
|    `%A`    |      `EEEE`      |    `l`     | Full day name based on locale, e.g. Sunday through Saturday  |
|    `%b`    |      `MMM`       |    `M`     | Abbreviated month name based on locale, e.g. Jan through Dec |
|    `%B`    |      `MMMM`      |    `F`     | Full month name, based on locale e.g. January through December |
|    `%d`    |       `dd`       |    `d`     | Two-digit day of the month (with leading zeros), 01 through 31 |
|    `%H`    |       `HH`       |    `H`     | Two digit representation of the hour in 24-hour format, 00 through 23 |
|    `%m`    |       `MM`       |    `m`     | Two digit representation of the month, `01` (for January) through `12` (for December) |
|    `%M`    |       `mm`       |    `i`     | Two digit representation of the minute, 00 through 59        |
|    `%S`    |       `ss`       |    `s`     | Two digit representation of the second, 00 through 59        |
|    `%T`    |    `HH:mm:ss`    |  `H:i:s`   | Same as "%H:%M:%S"                                           |
|    `%x`    |       TBD        | **Note 1** | Preferred date representation based on locale, without the time |
|    `%X`    |       TBD        |  `H:i:s`   | Preferred time representation based on locale, without the date |
|    `%y`    |       `YY`       |    `y`     | Two-digit representation of the year                         |
|    `%Y`    |      `YYYY`      |    `Y`     | Four-digit representation of the year                        |

**Notes**:

1. When the `%x` format is requested and the formatting will be performed via the `date` function, `zcDate` uses a language-specific `DATE_FORMAT_SHORT` formatting string.
2. For the `datefmt_create` conversions' `TBD` elements, need to review the usage of the `IntlDateFormatter` class date- and time-format options.

**Comment by proseLA** [comment]
i suppose the question is which format do we want to supply to the new class when calling from another script?  personally, i think we should be always supplying the `datefmt_create` format to this class.  and if that function is not available, we should be converting to one of the other formats depending on what is installed.  (this corresponds to `debug = false` in my work in progress).

most excellent write-up that i think covers most of the bases!

**Comment by lat9** [comment]
> i suppose the question is which format do we want to supply to the new class when calling from another script? personally, i think we should be always supplying the `datefmt_create` format to this class. and if that function is not available, we should be converting to one of the other formats depending on what is installed. (this corresponds to `debug = false` in my work in progress).
> 
> most excellent write-up that i think covers most of the bases!

The idea is that the `zcDate` class accepts `strftime`-format (er) formatting strings, since they're the easiest to do a find-and-replace action on.  Using the format-conversion tables identified in the write-up, the class will determine which path (`strftime` vs. `date` vs. `datefmt_create`) is to be used and each format-string simply undergoes a `str_replace` action to convert the `%`-preceded format types with their `date` or `datefmt_create` version.

**Comment by lat9** [comment]
OK, I've come to the opinion that, as in @proseLA's baseline, we're going to need an additional language-specific constant to identify the base `locale` to use for the default date formatting of the `%x` and `%X` formats.

The default language file(s) current use `setlocale` to set their default locale, but there doesn't appear a way to retrieve the 'full' locale, which is important given that a language-specific date in `en_US` is different from one formatted for `en_GB`.  In either of those cases, the return value from `setlocale(LC_TIME, 0);` is `en` ... no `_US` or `_GB` suffix.

**Comment by lat9** [comment]
Noting, too, that the `DATE_FORMAT_SHORT` storefront definition was removed (_sigh_) in zc1.5.7a (https://github.com/zencart/zencart/commit/bcd724e495cdf37bbdd145ca4412991235c27266).

**Comment by lat9** [comment]
> OK, I've come to the opinion that, as in @proseLA's baseline, we're going to need an additional language-specific constant to identify the base `locale` to use for the default date formatting of the `%x` and `%X` formats.
> 
> The default language file(s) current use `setlocale` to set their default locale, but there doesn't appear a way to retrieve the 'full' locale, which is important given that a language-specific date in `en_US` is different from one formatted for `en_GB`. In either of those cases, the return value from `setlocale(LC_TIME, 0);` is `en` ... no `_US` or `_GB` suffix.

Never mind on this too (I really didn't want yet-another language-specific constant).  The `locale_get_default()` function (available when the `datefmt_create` function is also present) returns the fully-formed current localet.

**Comment by proseLA** [comment]
> > i suppose the question is which format do we want to supply to the new class when calling from another script? personally, i think we should be always supplying the `datefmt_create` format to this class. and if that function is not available, we should be converting to one of the other formats depending on what is installed. (this corresponds to `debug = false` in my work in progress).
> > most excellent write-up that i think covers most of the bases!
> 
> The idea is that the `zcDate` class accepts `strftime`-format (er) formatting strings, since they're the easiest to do a find-and-replace action on. Using the format-conversion tables identified in the write-up, the class will determine which path (`strftime` vs. `date` vs. `datefmt_create`) is to be used and each format-string simply undergoes a `str_replace` action to convert the `%`-preceded format types with their `date` or `datefmt_create` version.

as `strftime` is the deprecated method, my opinion is that `zcDate` should accept `datefmt_create` formats.

i'm not of the opinion that because one path is the easiest, that is the way to go.  i think the more challenging path can be the more rewarding.  

looking at some point further down the road from now, our class will be accepting formatting strings that are applicable to a long since deprecated method.

in addition, as you can see the amount of work (and how easily confusing all of this is), i'm not convinced that using `strftime` formats is the easiest; one still needs to figure out the conversion and put in into place.

in my class, i used that `debug` method to help with converting from one format to another.

again, just MO.

**Comment by lat9** [comment]
> > > i suppose the question is which format do we want to supply to the new class when calling from another script? personally, i think we should be always supplying the `datefmt_create` format to this class. and if that function is not available, we should be converting to one of the other formats depending on what is installed. (this corresponds to `debug = false` in my work in progress).
> > > most excellent write-up that i think covers most of the bases!
> > 
> > 
> > The idea is that the `zcDate` class accepts `strftime`-format (er) formatting strings, since they're the easiest to do a find-and-replace action on. Using the format-conversion tables identified in the write-up, the class will determine which path (`strftime` vs. `date` vs. `datefmt_create`) is to be used and each format-string simply undergoes a `str_replace` action to convert the `%`-preceded format types with their `date` or `datefmt_create` version.
> 
> as `strftime` is the deprecated method, my opinion is that `zcDate` should accept `datefmt_create` formats.
> 
> i'm not of the opinion that because one path is the easiest, that is the way to go. i think the more challenging path can be the more rewarding.
> 
> looking at some point further down the road from now, our class will be accepting formatting strings that are applicable to a long since deprecated method.
> 
> in addition, as you can see the amount of work (and how easily confusing all of this is), i'm not convinced that using `strftime` formats is the easiest; one still needs to figure out the conversion and put in into place.
> 
> in my class, i used that `debug` method to help with converting from one format to another.
> 
> again, just MO.

Remember that the date-/time-formatting strings don't need to include only the format identifiers, they can also include "words" which might contain the characters associated with the `datefmt_create` formatting strings, e.g. 'The ladder was delivered on %d/%m/%Y'.  I stand by the use of the `strftime` format strings as being used in the `output` method's format input.

I'll point out that the _goal_ here, is to provide a means for the base and plugin modules can request locale-specific date and time formatted strings for zc158, **not** as a full-function date formatter.

**Comment by lat9** [comment]
> 
> Remember that the date-/time-formatting strings don't need to include only the format identifiers, they can also include "words" which might contain the characters associated with the `datefmt_create` formatting strings, e.g. 'The ladder was delivered on %d/%m/%Y'. I stand by the use of the `strftime` format strings as being used in the `output` method's format input.
> 
> I'll point out that the _goal_ here, is to provide a means for the base and plugin modules can request locale-specific date and time formatted strings for zc158, **not** as a full-function date formatter.

I'll recant the first assertion, regarding the inclusion of "words" in the formatting string, since that causes the date-format output to 'choke'.

I still stand by the use of the `strftime` formats being required by the `zcDate` class to make the change relatively transparent to the Zen Cart base and associated plugins, i.e. the method used to return the formatted date **_will change_**, but the associated formatting strings **_don't_**.

**Comment by proseLA** [comment]
i suppose where you are now going is that you plan on adding a `strftime` function in the base that returns a `zcDate` output.  hence why you like the use of `strftime` formats for the `zcDate` class.  am i on the right track here?

and the reasoning is so that all of those old plugins will not need updating and will still work under 8.1?

i am reminded of an old thread from many moons ago, that i believe chris started, with regards to a revamp of the whole structure of ZC.  the general consensus at that time was to preserve the functionality of all the existing plugins.  and that revamp into more of an object oriented structure was tabled.  i may have even been on that side of the argument.  and of which, my thinking has now changed.  but i see both sides of it.

if my memory on said thread is wrong, i do apologize.  but it is something i think about over the years, and wonder where ZC would be now, had the consensus gone the other direction.

**Comment by lat9** [comment]
Not planning on adding the function, but modifying each in-core use of strftime to use $zcDate->output, trying (key-word) to make the change minimally intrusive.

The strftime format-strings are, IMO, more descriptive/definitive than the ones provided by datefmt_create.

**Comment by lat9** [comment]
... as I continue my stream-of-thought 'moments' ... the class will adjust its `IntlDateFormatter` output if it detects that the `locale` has changed since instantiation; no additional `locale` changes required.
