### ISSUE TITLE
`brands` page's header processing makes it "difficult" to use with non-base templates

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4757]
The `brands` page's `header_php.php` processing injects in-core-specific HTML classes for the active template's use.  I _thought_ that the header processing was supposed to create template-independent structures that could further be formatted by the currently-active template.

That header processing also assumes that there's a maximum of 6 brands-per-output-line for the rendering.

Should the header/template combination be updated so that the template is "in charge of" the formatting of the standardized data returned by the header's processing?

**Comment by scottcwilson** [comment]
This is the time to make that kind of change, since Brands is completely new.
