### ISSUE TITLE
Paypal Express Checkout Forced Guest to Join Up (Create Account & Continue)

### ISSUE THREAD

**Issue by njcyx6649250** [zencart/zencart#4776]
**Describe the bug**
It may not be the bug on Zen cart side. But I still want to report this issue here and see how other developers think. Maybe there is a way to improve. I believe there are still many zen cart websites using PayPal express checkout modules. If the customer has to sign up an account to checkout (no matter website account or paypal account), it will be inconvenience to the customers and it will significantly affect the website sale.

So in your shopping cart, if you click the PayPal Express Checkout button, the paypal landing page will still show the "checkout with debit/credit card" section below the PayPal login section. Click on that link, you can still fill your card & address info, but the "Continue" button below is changed to "Create Account & Continue". So you have to sign up a PayPal account then.

Discussion link:
https://www.zen-cart.com/showthread.php?228806-Paypal-Customer-Forced-to-Join-Up

**Version**
Zen Cart version:  1.57d
PHP version:  7.4
MySQL version: 5.7
Plugins that may be related: paypalwpp.php
What older/newer versions were also tested? n.a.

**To Reproduce**
Please see description above. 

**Expected behavior**
Under "checkout with debit/credit card" page, there should be "Continue as Guest" option or "Continue" option so I can complete the checkout without creating a PayPal account. 

**Debug/Error Logs**
Troubleshooting steps:
1. Disable InContext Checkout in admin->Modules->Payment->PayPal Express. No help.
2. Comment out the following text in paypalwpp.php. No help

if ($this->use_incontext_checkout && $options['SOLUTIONTYPE'] == 'Sole') $options['SOLUTIONTYPE'] = 'Mark';
 
**Devices (please complete the following information):**
Computer #1. Windows 10. Firefox, Chrome, Edge. Incognito mode or not. No change
Computer #2. Windows 10. Firefox, this issue was resolved. Chrome, issue remains.

**Comment by scottcwilson** [comment]
We may or may not be able to fix this.  PayPal just forces people to use PayPal sometimes; I have never seen rhyme or reason to it.   At one point the theory was that you could only use your credit card a certain number of times before they'd force you to use your PayPal account.

**Comment by njcyx6649250** [comment]
Update. I found a walk around solution: I installed one-page checkout plug-in. Now the customer can checkout by his credit card, without creating a zen cart/paypal account. It uses PayPal payments pro plug-in, not PayPal express checkout plug-in then.

**Comment by dbltoe** [comment]
Please see my answer at https://www.zen-cart.com/showthread.php?228806-Paypal-Customer-Forced-to-Join-Up&p=1389010#post1389010

**Comment by scottcwilson** [comment]
Thanks John.
