### ISSUE TITLE
ZC158 extra_definition language files process in system-dependent/random order

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4785]
As processed here:
https://github.com/zencart/zencart/blob/d66fa7265a227a1fbd274c1b308f677005d0a6b4/includes/classes/FileSystem.php#L31-L39

On windows $fileList is in alphasorted order ascending, on *nix, it is not/seems pretty random.
This is not unexpected with the use of dir command, as noted in the php site:
> The order in which directory entries are returned by the read method is system-dependent.

 I rely on my site-specific language files being loaded as expected/in alphasort order, as some defines re-use other defines that are already included.
While I of course am not demanding my personal requirements are met, I think it is important that behaviour should be consistent.
This caused me some consternation when a simple update killed my site after the usual local testing.
I know local testing should be done using the same environment as production.

I just put sort in there
```
        }
        sort($fileList);
        $dir->close();
```

There are other uses of dir which perhaps should also be rationalised.

**Comment by torvista** [comment]
Aside of this, while tracking down the issue it appears that
\includes\modules\extra_definitions.php
is not in use? I had a die in there that had no effect.

**Comment by lat9** [comment]
Perhaps the use of `glob` instead of `dir` would help as that function always returns the files in alphanumeric sort order.

**Comment by lat9** [comment]
> Aside of this, while tracking down the issue it appears that \includes\modules\extra_definitions.php is not in use? I had a die in there that had no effect.

Hmm, in zc157 (and, presumed, earlier), that file was loaded during the init_templates.php processing.  For zc158, it's commented out:
![image](https://user-images.githubusercontent.com/2685585/167614041-9d365f54-593c-4371-afee-5cfa28b60124.png)

**Comment by lat9** [comment]
Changed via [this](https://github.com/zencart/zencart/commit/65eec8d06ebf33a487f8c4f4c46b3a57c3ddeacc) commit.  @zcwilt, what was the 'motivation' for the change?

**Comment by torvista** [comment]
PR as suggested or glob?

**Comment by scottcwilson** [comment]
Steve, please open a new issue on the \includes\modules\extra_definitions.php
 issue so we can track that separately. 

My preference would be to close this issue.  Windows hosting is not recommended and we don't have tons of additional developers to do all the tweaks required to make it work well.

**Comment by lat9** [comment]
This is a downward incompatibility that needs to be addressed or at least fully investigated.

**Comment by lat9** [comment]
The issue, IMO, is that previous versions of Zen Cart made use of /modules/extra_definitions.php (which can be overridden) while the current zc158 implementation removes that.

**Comment by torvista** [comment]
I understand that windows production servers should not be supported.
However there is a bigger picture.
In an ideal world all ZC store owners test modifications on a duplicate shop in an environment that mirrors their production environment. Convincing them to do that and educating them how to do that is a valuable investment in the path to making them contributors.

Meanwhile in the real world, users will continue modifying a live shop until it dies, then grudgingly look for the easiest way to set up a duplicate. In many cases that will be a Xampp-like package on Windows which for 99.9% of the time, works fine, and so they will look no further. That goes for me and I think lat9 at least. Yes we should know better.

I think now I have had only two occasions since ZC1.3.8 where my site death has been caused by an environment difference such as highlighted in this thread, so have still not set up a Docker-like environment. My bad.

Consequently, while not supporting Windows servers is correct, attention should be paid to any issues that arise and if a fix does not involve Windows-specific code and breaks nothing else, why not include it?

Otherwise it should be noted in the “Reasons to set up a duplicate environment” section of the Documentation. All with the intention of avoiding the scenario of shop-owner panic when facing a white screen of death with no debugs when they think they have been good in trying things out locally. Been there, done that.

As for my shenanigans with circular defines, yes I’ve simplified it all already thanks. Since I work in a vacuum I expect disagreement, but while it is constructive who can complain.

**Comment by lat9** [comment]
With the overall use of the `FileSystem` class to load files in zc158, we've lost the compatibility for the alphabetical loading of files from specific directories which has been present in *all* prior versions of Zen Cart:

- `/includes/extra_datafiles`
- `/includes/functions/extra_functions`
- `/includes/languages`
  - All language files were previously loaded via the `template_func::get_template_part` method, which performed a `sort` of the returned directory files.  A specific page could have additional language constants loaded, e.g. `login_guest.php` and `login_guest2.php` for the `login` page.  For previous versions of Zen Cart, those two files would **always** be loaded in that order, with zc158 that is no longer guaranteed.
  - The `extra_definitions` sub-directory files' load could be overridden on a template basis via `/includes/modules/extra_definitions.php` which is now not used.

The `FileSystem` class uses the PHP `dir` class for its gathering of a list of matching files to be loaded.  That `dir` class returns the file-list in a "system-dependent" order.  For `*nix`systems, that translates into "unpredictable".
