### ISSUE TITLE
admin/stats_sales_report_graph, PHP 8.1 issues

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#4786]
running php 8.1, and the current v158 code base, we missed some strftime functions as seen here:

https://github.com/zencart/zencart/blob/d66fa7265a227a1fbd274c1b308f677005d0a6b4/admin/includes/classes/stats_sales_report_graph.php#L263-L283

i we were to change the `strftime` call to `$zcDate->output` we get the following error:
```
[08-May-2022 20:45:59 America/Los_Angeles] PHP Fatal error:  Uncaught Error: Call to a member function output() on null in /var/www/zcdev/admin/includes/classes/stats_sales_report_graph.php:277
```
looking at `$this` prior to line 277, we can see that `$this->startDates` and `$this->endDates` are not set:

![image](https://user-images.githubusercontent.com/1095136/167337595-95f578ce-40b4-4deb-972d-e22803d5dc83.png)

and that is as far as i took it...

**Comment by proseLA** [comment]
it also seems that `$zcDate` is not instantiated at that point. (albeit that is a minor point and easily corrected...) but i am not sure from which link the startDate and endDate should be coming from.

**Comment by lat9** [comment]
Thanks for that @proseLA, I'd thought that all usage was in the comments.  `$zcDate` is instantiated as CP 5 (way early) so that anyone that wants to override its use (either storefront or admin) has plenty of 'runway'.

Since the use will be in a class, the class needs to declare that `$zcDate` is `global`.

**Comment by lat9** [comment]
Sigh, that report has additional issues:
![image](https://user-images.githubusercontent.com/2685585/167398035-730343d1-b892-4f4e-8764-3671d17bfea5.png)

I'm going to start with a refactor so that I've got a better view of what the heck is going on.

**Comment by proseLA** [comment]
i decided to take another look and stab at fixing this issue.  apparently one of my tools does not output protected values.  so the problems seemed far less than i thought.

**Comment by lat9** [comment]
> i decided to take another look and stab at fixing this issue. apparently one of my tools does not output protected values. so the problems seemed far less than i thought.

Please don't, I've got the class refactored so that it's more readable and I'll be tackling those deprecations next.
