### ISSUE TITLE
Github Error: fatal: bad object refs/tags/v1.5.5

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4801]
As far as I can ascertain, this error I'm getting (Gitkraken and in terminal) is related to **this** repository.
I can push/pull to my origin, but cannot fetch from zencart.
Hence I do not see any new commits from a couple of days ago.
If no-one else has anything odd going on I'll close this.

**Comment by proseLA** [comment]
i am having no problems pulling from the remote upstream.
