### ISSUE TITLE
ZC158, php 8.1.6: PHP Deprecated: ctype_digit()int to string conversion ... admin\includes\classes\stats_sales_report_graph.php

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4802]
new install, main admin page

[16-May-2022 16:00:06 UTC] Request URI: /zencart/admin/, IP address: 127.0.0.1
#0 [internal function]: zen_debug_error_handler()
#1 \zencart\admin\includes\classes\stats_sales_report_graph.php(67): ctype_digit()
#2 \zencart\admin\includes\modules\dashboard_widgets\SalesReportDashboardWidget.php(21): statsSalesReportGraph->__construct()
#3 \zencart\admin\index_dashboard.php(75): include('\zenca...')
#4 \zencart\admin\home.php(25): require('\zenca...')
#5 \zencart\admin\index.php(11): require('\zenca...')
--> PHP Deprecated: ctype_digit(): Argument of type int will be interpreted as string in the future in \zencart\admin\includes\classes\stats_sales_report_graph.php on line 67.

[16-May-2022 16:00:06 UTC] Request URI: /zencart/admin/, IP address: 127.0.0.1
#0 [internal function]: zen_debug_error_handler()
#1 \zencart\admin\includes\classes\stats_sales_report_graph.php(67): ctype_digit()
#2 \zencart\admin\includes\modules\dashboard_widgets\SalesReportDashboardWidget.php(21): statsSalesReportGraph->__construct()
#3 \zencart\admin\index_dashboard.php(75): include('\zenca...')
#4 \zencart\admin\home.php(25): require('\zenca...')
#5 \zencart\admin\index.php(11): require('\zenca...')
--> PHP Deprecated: ctype_digit(): Argument of type int will be interpreted as string in the future in \zencart\admin\includes\classes\stats_sales_report_graph.php on line 67.

**Comment by lat9** [comment]
Wonderful, I'm currently running 8.1.5 with no errors.  Let me get that PHP version updated and I'll get this PR'd.
