### ISSUE TITLE
Notify (via email?) someone when "The email server could not deliver mail ..."

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4803]
More and more, I'm seeing logs of the ilk
```
[16-May-2022 12:18:41 America/Chicago] Request URI: /create-account, IP address: ---
#1 trigger_error() called at [/home/mysite/public_html/includes/functions/functions_email.php:377]
#2 zen_mail() called at [/home/mysite/public_html/includes/modules/create_account.php:440]
#3 include(/home/mysite/public_html/includes/modules/create_account.php) called at [/home/mysite/public_html/includes/modules/pages/create_account/header_php.php:17]
#4 require(/home/mysite/public_html/includes/modules/pages/create_account/header_php.php) called at [/home/mysite/public_html/index.php:36]
--> PHP Notice: Email Error: SMTP Error: The following recipients failed: joe@example.com: The mail server could not deliver mail to joe@example.com. The
account or domain may not exist, they may be blacklisted, or missing the
proper dns entries.
<br /> in /home/mysite/public_html/includes/functions/functions_email.php on line 377.
```
when a site's configured to use SMTP email and running on a 'smart' email server.  Being lowly PHP notices, they're only logged when full logging is enabled and the site's admin(s) need to scroll through all the logs to identify the issue, i.e. the customer's not going to receive the emails that they think they will, whether create-account or order-confirmations or for any plugins (think BISN) that also send out emails.

As much as I hate to add more configuration settings, I'm considering an new `Configuration :: E-mail Options` setting.  The proposed setting would be set to either an empty string or a collection of email addresses to which the notifications would be sent.

Any other suggestions?

**Comment by dbltoe** [comment]
More and more, the fault of undelivered mail (where the email is a valid address) is a failure of the hosts' DKIM, DMARC, and/or SPF settings.
If those settings are not correct, even sending to several addresses might not be successful.
Perhaps add a link to test the store's email settings.  Like https://mxtoolbox.com/SuperTool.aspx?action=mx%3YOUR_SITEdotCOM&run=toolpage.

**Comment by lat9** [comment]
Great idea, @dbltoe.  Still ruminating here as to the best way to notify/indicate the issue.

Another possibility that came to mind is to add a field to the customer's record to indicate that the account's email address is valid.  If any records are found when navigating to the home page, to indicate via message to check the `Customers :: Customers` page and to add an "Invalid Email" filter to that page.

**Comment by scottcwilson** [comment]
Sometimes this is an issue of data entry at account creation time.  I see a lot of @gmail.con addresses that yield a similar log.

**Comment by lat9** [comment]
Agreed, but most of the ones I've been seeing are site-specific, non-gmail.

**Comment by dbltoe** [comment]
I went into the Showcase on the forum and grabbed a site from Books.  yard-sale.com

https://mxtoolbox.com/SuperTool.aspx?action=mx%3ayard-sale.ca&run=toolpage is the report AND, if you click on the spf lookup under the DNS Record Published row, you'll find that their SPF is set to websitewelcome.com

With a missing DMARC  AND a bad SPF, they're going to have most of their emails denied.  Many will be thrown in the bit bucket without notification to the sender or receiver.

**Comment by barco57** [comment]
I find misspelled domains on emails all the time when I check and clean email queues. Double entry of email addresses on the registration page would catch a lot of these.

**Comment by scottcwilson** [comment]
I see a decent number of these too, but I'm not sure I want to get email just because of this - I'm going to see the issue when I check logs (or if I get a specific client complaint, which is driven by a customer complaint.)

**Comment by dbltoe** [comment]
ditto on the no email.

**Comment by lat9** [comment]
A specifically-named log, gathered on a per-month basis?  I.e. /logs/bounced_emails_yyyy_mm.log?

**Comment by scottcwilson** [comment]
That's a very powerful idea.

**Comment by torvista** [comment]
`Being lowly PHP notices, they're only logged when full logging is enabled and the site's admin(s) need to scroll through all the logs to identify the issue,`

In an ideal world there are no logs. But php is creating more all the time for minor stuff, so something serious like this is easily  overlooked. I would certainly want a notification if emails were failing.

**Comment by proseLA** [comment]
> A specifically-named log, gathered on a per-month basis? I.e. /logs/bounced_emails_yyyy_mm.log?

i am NOT a fan of adding `_yyyy_mm` to any log files.  log files should have time stamps as part of their messages, and a properly configured/maintained server, a sysadmin would go though logs and/or have log rotate properly configured.  adding those elements further complicates sysadmin maintenance.  


> `Being lowly PHP notices, they're only logged when full logging is enabled and the site's admin(s) need to scroll through all the logs to identify the issue,`
> 
> In an ideal world there are no logs. But php is creating more all the time for minor stuff, so something serious like this is easily overlooked. I would certainly want a notification if emails were failing.

could not disagree more.  in an ideal server, there are no errors in the logs.  logs serve a very important function, especially when doing forensic investigations.

**Comment by scottcwilson** [comment]
I think you may have misread what Steve wrote - he meant '... there are no logs *being created*', not that logging is something that doesn't exist.

**Comment by lat9** [comment]
> > A specifically-named log, gathered on a per-month basis? I.e. /logs/bounced_emails_yyyy_mm.log?
> 
> i am NOT a fan of adding `_yyyy_mm` to any log files. log files should have time stamps as part of their messages, and a properly configured/maintained server, a sysadmin would go though logs and/or have log rotate properly configured. adding those elements further complicates sysadmin maintenance.
> 
> > `Being lowly PHP notices, they're only logged when full logging is enabled and the site's admin(s) need to scroll through all the logs to identify the issue,`
> > In an ideal world there are no logs. But php is creating more all the time for minor stuff, so something serious like this is easily overlooked. I would certainly want a notification if emails were failing.
> 
> could not disagree more. in an ideal server, there are no errors in the logs. logs serve a very important function, especially when doing forensic investigations.

I have no preference either way.  Let's do a consensus vote via up- or down-thumbs on this comment; I'll go with the majority over the weekend.

**Comment by scottcwilson** [comment]
Just add the date like the logs do.  It's a convenience and it gives unique filenames.

**Comment by torvista** [comment]
> could not disagree more. 
That seems to be our default setting these days!

Yes as Scott said, I meant the ideal is for sites to be error-free/not generate logs. Of course the logs are critically important and are a fundamental admin tool/must be acted on.

**Comment by torvista** [comment]
> I'm not seeing that original logged message within the PHPMailer language files,

I do find a fragment/the source string in PHPmailer
` 'recipients_failed' => 'SMTP Error: The following recipients failed: ',`

**Comment by lat9** [comment]
> > I'm not seeing that original logged message within the PHPMailer language files,
> 
> I do find a fragment/the source string in PHPmailer ` 'recipients_failed' => 'SMTP Error: The following recipients failed: ',`

Ah, thanks for that!  That gives me 'hope' that my update will be multi-language supporting!
