### ISSUE TITLE
Add function for adding to TABLE_CONFIGURATION

### ISSUE THREAD

**Issue by bislewl** [zencart/zencart#483]
Almost every single module I write, I have to make some entries to the TABLE_CONFIGURATION, It would be really nice if there was a function that allowed this to happen with out having to type out SQL queries all the time.

Agree? Disagree?

function add_config_value(){
if(!defined()){
$db->Execute("INSERT INTO ". TABLE_CONFIGURATION....
}

}

**Comment by drbyte** [comment]
Hmmm ... I'd written some code for that a long time ago, and clearly it never got included. Right now I've no idea where I left it.

Probably also useful to have some helpers for configuration-groups too, as well as removing config values.

For the purpose of similar naming of functions, I might suggest they start with `zen_config_`, like `zen_config_add_value()`, `zen_config_add_group()`, etc

For the modules you're thinking of, are you speaking in terms of a payment/shipping module where one typically uses the class's `install()` method to put these values in? Or are you referring to other things?

**Comment by bislewl** [comment]
Yes, that's the direction I was thinking. I'm referring to things like Ajax Back In Stock, Zen Light Box, Zencart Product Badges, Etc. Things that only fall into the Configuration Menu.  I guess this is more useful for auto-installers (which there could be a whole discussion on those pros/cons). When creating installers using this: https://www.zen-cart.com/downloads.php?do=file&id=1971 the files each need to go through making inserts into the DB for each value versus if it used a function or a class it would make it quicker. To make a function for a single module to do this is usually more time consuming than just coding it. But if we had a common function it might make the life of some of us dev's a little nicer. If I get time maybe I'll throw it together and do a pull request.

**Comment by scottcwilson** [comment]
This issue is over 5 years old.  If someone wants to put in a PR it will be accepted, but I don't think the issue needs to be kept open.
