### ISSUE TITLE
PHP deprecated errors with php 8.1.6 and Square payment module

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4836]
ZC158. PHP 8.1.6.
Enter admin->payment modules.

> [29-May-2022 15:27:47 UTC] Request URI: /zencart/admin/index.php?cmd=modules&set=payment, IP address: 127.0.0.1
> #0 D:\GitHub\zencart\includes\classes\vendors\square\connect\lib\Model\CreatePaymentRequest.php(20): zen_debug_error_handler()
> #1 D:\GitHub\zencart\includes\classes\vendors\square\connect\autoload.php(39): require('D:\\GitHub\\zenca...')
> #2 D:\GitHub\zencart\includes\modules\payment\square_support\ZenCartConnectCreatePaymentRequest.php(22): square->{closure}()
> #3 D:\GitHub\zencart\includes\modules\payment\square.php(81): require_once('D:\\GitHub\\zenca...')
> #4 D:\GitHub\zencart\admin\modules.php(187): square->__construct()
> #5 D:\GitHub\zencart\admin\index.php(11): require('D:\\GitHub\\zenca...')
> --> PHP Deprecated: Return type of SquareConnect\Model\CreatePaymentRequest::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in D:\GitHub\zencart\includes\classes\vendors\square\connect\lib\Model\CreatePaymentRequest.php on line 659.
> 
> [29-May-2022 15:27:47 UTC] Request URI: /zencart/admin/index.php?cmd=modules&set=payment, IP address: 127.0.0.1
> #0 D:\GitHub\zencart\includes\classes\vendors\square\connect\lib\Model\CreatePaymentRequest.php(20): zen_debug_error_handler()
> #1 D:\GitHub\zencart\includes\classes\vendors\square\connect\autoload.php(39): require('D:\\GitHub\\zenca...')
> #2 D:\GitHub\zencart\includes\modules\payment\square_support\ZenCartConnectCreatePaymentRequest.php(22): square->{closure}()
> #3 D:\GitHub\zencart\includes\modules\payment\square.php(81): require_once('D:\\GitHub\\zenca...')
> #4 D:\GitHub\zencart\admin\modules.php(187): square->__construct()
> #5 D:\GitHub\zencart\admin\index.php(11): require('D:\\GitHub\\zenca...')
> --> PHP Deprecated: Return type of SquareConnect\Model\CreatePaymentRequest::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in D:\GitHub\zencart\includes\classes\vendors\square\connect\lib\Model\CreatePaymentRequest.php on line 669.
> 
> [29-May-2022 15:27:47 UTC] Request URI: /zencart/admin/index.php?cmd=modules&set=payment, IP address: 127.0.0.1
> #0 D:\GitHub\zencart\includes\classes\vendors\square\connect\lib\Model\CreatePaymentRequest.php(20): zen_debug_error_handler()
> #1 D:\GitHub\zencart\includes\classes\vendors\square\connect\autoload.php(39): require('D:\\GitHub\\zenca...')
> #2 D:\GitHub\zencart\includes\modules\payment\square_support\ZenCartConnectCreatePaymentRequest.php(22): square->{closure}()
> #3 D:\GitHub\zencart\includes\modules\payment\square.php(81): require_once('D:\\GitHub\\zenca...')
> #4 D:\GitHub\zencart\admin\modules.php(187): square->__construct()
> #5 D:\GitHub\zencart\admin\index.php(11): require('D:\\GitHub\\zenca...')
> --> PHP Deprecated: Return type of SquareConnect\Model\CreatePaymentRequest::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in D:\GitHub\zencart\includes\classes\vendors\square\connect\lib\Model\CreatePaymentRequest.php on line 680.
> 
> [29-May-2022 15:27:47 UTC] Request URI: /zencart/admin/index.php?cmd=modules&set=payment, IP address: 127.0.0.1
> #0 D:\GitHub\zencart\includes\classes\vendors\square\connect\lib\Model\CreatePaymentRequest.php(20): zen_debug_error_handler()
> #1 D:\GitHub\zencart\includes\classes\vendors\square\connect\autoload.php(39): require('D:\\GitHub\\zenca...')
> #2 D:\GitHub\zencart\includes\modules\payment\square_support\ZenCartConnectCreatePaymentRequest.php(22): square->{closure}()
> #3 D:\GitHub\zencart\includes\modules\payment\square.php(81): require_once('D:\\GitHub\\zenca...')
> #4 D:\GitHub\zencart\admin\modules.php(187): square->__construct()
> #5 D:\GitHub\zencart\admin\index.php(11): require('D:\\GitHub\\zenca...')
> --> PHP Deprecated: Return type of SquareConnect\Model\CreatePaymentRequest::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in D:\GitHub\zencart\includes\classes\vendors\square\connect\lib\Model\CreatePaymentRequest.php on line 690.

**Comment by scottcwilson** [comment]
Is this the new or the old Square? The old Square won't be part of 1.5.8.   See #4818.

**Comment by torvista** [comment]
Ah, old Square.
