### ISSUE TITLE
v157 customer_ip address empty.

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#4841]
i have been trying to track down a problem with the whos_online script.  there are times when the cart has no index for the customer_ip address on this line:

https://github.com/zencart/zencart/blob/742b837868a2b128df96b6635c413c8187972679/admin/whos_online.php#L331

i am curious if anyone else has experienced this problem?  or if we feel this is somehow corrected in v158.

here is an example of the log file with a capture of the `$cart` object where one can see no `customer_ip` in the array.

```
4 --> PHP Notice: bad cart IP ADDRESS--->{"products":[],"total":"$0.00","cartObject":{"contents":
[],"total":0,"weight":0,"cartID":null,"content_type":false,"free_shipping_item":0,"free_shipping_weight":0,
"free_shipping_price":0,"download_count":0,"total_before_discounts":0,"display_debug_messages":false,
"flag_duplicate_msgs_set":false,"flag_duplicate_quantity_msgs_set":[]},"currency_code":"USD","cartID":"",
"language_name":"english","language_id":1,"language_code":"en",
"customer_hostname":"ec2-3-227-42-0.compute-1.amazonaws.com","cart_errors":""} 
in /var/www/myhosting/ADMIN/whos_online.php on line 293.
5
6 [01-Jun-2022 08:36:56 America/Los_Angeles] Request URI: /ADMIN/index.php?cmd=whos_online, IP address: 2603:8001:d300:1b81:608b:4704:bc55:753b
7 #1  require(/var/www/myhosting/ADMIN/whos_online.php) called at [/var/www/myhosting/ADMIN/index.php:11]
8 --> PHP Notice: Undefined index: customer_ip in /var/www/myhosting/ADMIN/whos_online.php on line 295.
```
my line numbers are slightly different due to incorporation of the common html header in the admin as well as the line for the capture of the `$cart` object.

i have not been able to reproduce the issue, but i have been getting logs on a live site.

**Comment by scottcwilson** [comment]
I'd be happy to take a PR that guards against this.
