### ISSUE TITLE
Different Square Associate Links

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#4842]
In the Credit Card Processing Banner, the banner URL is listed as https://www.zen-cart.com/partners/square_promo which redirects to https://squareup.com/signup?country_code=us&signup_token=6BB5B2E676

Under Requirements in the Docs for Square Web Pay Payments API, the link to create a Square account is https://squareup.com/t/f_partnerships/d_partnerpage/p_zencart/c_general/o_free_processing/u_signup/l_us?route=signup%3Fsignup_token%3D6BB5B2E676.

If we assume the latter is correct, should the redirect for the ezPage be redone?

**Comment by scottcwilson** [comment]
I think these will both work.  @Ian ?

**Comment by scottcwilson** [comment]
The signup token is the same for both and that's what matters.  It's fine as is.
