### ISSUE TITLE
Packingslip has lost Notifiers

### ISSUE THREAD

**Issue by brittainmark** [zencart/zencart#4846]
**Describe the bug**
The Notifiers: 
NOTIFY_ADMIN_PACKINGSLIP_HEADING
NOTIFY_ADMIN_PACKINGSLIP_SORT_DISPLAY
NOTIFY_ADMIN_PACKINGSLIP_DATA
are missing from the admin>packingslip.php
**Version**
Zen Cart version: 1.5.8
 I will recreate and send PR.

**Additionally,** while I am there I noticed that if $attr_img_width was added to the  site_specific_overrides for invoice.php and Packingslip.php then the listeners  NOTIFY_ADMIN_PACKINGSLIP_DEFAULTS and NOTIFY_ADMIN_INVOICE_DEFAULTS could be removed. 
If you want to keep it consistent, you could change the name $attr_img_width to $show_attr_img_width, but that does not sound correct, 
Would prefer to change the documentation to say that this value can be overridden.

**Comment by proseLA** [comment]
i do not see how this is a bug.  the first 3 mentioned notifiers were never part of the repo.

additionally, NOTIFY_ADMIN_PACKINGSLIP_DEFAULTS also looks to never be part of the repo.

**Comment by scottcwilson** [comment]
Lost compared to what?  I'm also not seeing them anywhere.

**Comment by brittainmark** [comment]
When I originally submitted the changed to invoice and packing slip they both had the notifiers to add new columns #4447 this was replaced by #4518. I obviously got it wrong and did not resubmit the correct version of the packing slip.  

@proseLA - There was not a category for "Whoops, I made a mistake!" So I thought Bug was the nearest thing to a correct category.

The second part is still relevant.  I do not think  NOTIFY_ADMIN_PACKINGSLIP_DEFAULTS and NOTIFY_ADMIN_INVOICE_DEFAULTS are needed if I change 

`$attr_img_width = '25'`

to

`if (!isset($show_product_images)) $attr_img_width = '25'`

It could then be dealt with in the same was as the show attributes. This could be a way forward for all hard coded values if you do not want to create constants.

**Comment by scottcwilson** [comment]
Ah ok.  Please submit a corrected version of the file and I'll get it merged in.  Thanks for your eagle-eyed checking!

**Comment by brittainmark** [comment]
Shall I remove  these notifiers? NOTIFY_ADMIN_PACKINGSLIP_DEFAULTS and NOTIFY_ADMIN_INVOICE_DEFAULTS 
and replace as suggested?

**Comment by scottcwilson** [comment]
I only see the second one.  I don't see NOTIFY_ADMIN_PACKINGSLIP_DEFAULTS.
You have spent way more time in this area than I have. 
Use your best judgement and proceed.

**Comment by brittainmark** [comment]
Fixed by #4850

**Comment by proseLA** [comment]
> @proseLA - There was not a category for "Whoops, I made a mistake!" So I thought Bug was the nearest thing to a correct category.
> 

IMO, now you are only compounding your mistake.  bug implies problem with the code.  i spent time researching if those notifiers were ever in the repo going back a number of versions.

more accurately describing the issue prevents other contributors from squandering time looking for things in an attempt to further research the issue and help with the situation.

**Comment by brittainmark** [comment]
Accepted! I will try to put in more detail next time I make a mistake. Sorry for wasting people's time.
