### ISSUE TITLE
Additional variables needed in `/admin/includes/extra_datafiles/dist-site_specific_admin_overrides.php

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4852]
Starting a list for now, simply to record the additional variables needed and, in some cases, that a change is needed to an admin module as well.

1. From RecentOrdersDashboardWidget.php, `$includeAttributesInPopoverRows`; the module also requires update.
2. From orders.php, `$quick_view_popover_enabled`, `$includeAttributesInProductDetailRows`, `$show_product_tax` and `$show_zone_info`.

**Comment by scottcwilson** [comment]
From customers.php, once #4857 merged, $show_registration_ip_in_listing

**Comment by scottcwilson** [comment]
@brittainmark Will you take this?

**Comment by brittainmark** [comment]
Yes will look at it.

**Comment by brittainmark** [comment]
Do you want all in one PR or 1 PR per change?

**Comment by scottcwilson** [comment]
One is fine TY.

**Comment by brittainmark** [comment]
fix #5506
