### ISSUE TITLE
Use of ACCOUNT_STATE_DRAW_INITIAL_DROPDOWN

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4858]
Recently I updated the text for admin switch ACCOUNT_STATE_DRAW_INITIAL_DROPDOWN regarding the display of the state as a dropdown or as a text field. 
This has proved to be incorrect as the display or not of the dropdown is not consistent between the shipping estimator and the other three uses.

**shipping_estimator**
setflag
$flag_show_pulldown_states = (ACCOUNT_STATE_DRAW_INITIAL_DROPDOWN === 'true');

HTML
dropdown: label "zonelabel", dropdown "stateZone" is rendered if $flag_show_pulldown_states is true
input: label "stateLabel", input field "state" is always rendered.

Javascript
If the dropdown has options, it is shown and input field is hidden. Vice-versa if no options.
If country is changed, js handles the update of the dropdown and the subsequent show/hide of the dropdown/input field. 

The other three uses
**address_book_process, create_account, checkout_new_address** 
are identical between them...suggesting they should be using the same template module anyway.

Setflag
$flag_show_pulldown_states = (
(($process == true || $entry_state_has_zones == true) && $zone_name == '')
|| ACCOUNT_STATE_DRAW_INITIAL_DROPDOWN == 'true' 
|| $error_state_input) 
? true : false;

$process is set for a submission of a new/update address.
$entry_state_has_zones is set if the country has zones defined
$zone_name set for a submission of a new/update address, from a check of the state input field against a zone with a matching name for the country.
$error_state_input is set to false if $zone_name check was false/not found.

HTML
"stBreak" is rendered if $flag_show_pulldown_states is true
dropdown: label "zonelabel", dropdown "stateZone" is rendered if $flag_show_pulldown_states is true
input field: label "stateLabel", input field "state" is always rendered.

Javascript:
"stBreak" is always hidden
Otherwise show/hide and update on country change is the same as the shipping estimator.

I don't see the point of ACCOUNT_STATE_DRAW_INITIAL_DROPDOWN...nor of NOT always having the dropdown when there are zones defined.
What is the point of not showing a dropdown, letting the customer manually enter their province, then failing it because it does not exactly match a pre-defined zone?

Why not remove ACCOUNT_STATE_DRAW_INITIAL_DROPDOWN and make the dropdown always display where possible?

As for making the three address forms use the same template, that's another issue to open.

**Comment by scottcwilson** [comment]
> I don't see the point of ACCOUNT_STATE_DRAW_INITIAL_DROPDOWN...nor of NOT always having the dropdown when there are zones defined.

These options exist because some people want it to work that way.  You may not, but some people do; that's why they're there.
