### ISSUE TITLE
PluginManagerController::outputMessageList() referenced but not defined

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4863]
See 

https://www.zen-cart.com/showthread.php?228868-zc_plugin-zen-cart-1-5-8-missing-method-PluginManagerController-outputMessageList()

**Comment by mc12345678** [comment]
Duplicate of: https://github.com/zencart/zencart/issues/4416

**Comment by scottcwilson** [comment]
Right you are!  TY.
