### ISSUE TITLE
Admin, customers, calculation of lifetime value fails due to inconsistent results of float casting/currency symbol location

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4870]
ZC158, php 8.1.6 (don't think it matters)

Make a couple of orders.
Admin->Customers->infobox may not show a lifetime value/cause a warning,

The calculation of this uses a casting to float:
https://github.com/zencart/zencart/blob/ac1bb27387a3a49a6d52c1334ac60c8b65927378/includes/classes/Customer.php#L313

If the currency symbol is on the left, the float renders it zero.
If the currency symbol is on the right, and decimal is a point and thousands are a comma. the float renders it correctly.
If the currency symbol is on the right, and decimal is a comma and thousands are a point. the float drops everything after the  decimal comma.

**Comment by lat9** [comment]
That result is an inconsistency between the `order_total` gathered and subsequently formatted prior to submission to the `getLifetimeValue` method by the `getOrderHistory` method.  PR forthcoming later today.

**Comment by lat9** [comment]
I'll note also (and correct via this issue) that the `getOrderHistory` method, on line 534:

![image](https://user-images.githubusercontent.com/2685585/173917182-79f7b3c2-b50f-4dec-b9c8-1ee3326a551f.png)

is using the current currency-conversion value instead of that which was used for the order itself.

**Comment by lat9** [comment]
... and it just gets worse.  Now that the lifetime value is not zero, the admin's Customers listing throws the following error since the 'order_total' element of the last-order element returned has been previously formatted.
```
[15-Jun-2022 16:10:10 America/New_York] Request URI: /zc158/hoisT-PYL-teAch/index.php?cmd=customers, IP address: 127.0.0.1
--> PHP Fatal error: Uncaught TypeError: Unsupported operand types: string * float in C:\xampp\htdocs\zc158\includes\classes\currencies.php:97
Stack trace:
#0 C:\xampp\htdocs\zc158\includes\classes\currencies.php(64): currencies->rateAdjusted('$63.84', true, 'USD', 1.0)
#1 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\customers.php(1060): currencies->format('$63.84', true, 'USD', 1.0)
#2 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\index.php(11): require('C:\\xampp\\htdocs...')
#3 {main}
  thrown in C:\xampp\htdocs\zc158\includes\classes\currencies.php on line 97.
```
