### ISSUE TITLE
MySQL length attribute elimination in mysql 8.0.17

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4875]
We can no longer rely on the result of `SHOW COLUMNS` to return a length for integer values in recent versions of MySQL.

See https://www.zen-cart.com/showthread.php?228870-Fatal-error-in-admin-includes-functions-general_functions-php for a proposed solution.

**Comment by scottcwilson** [comment]
Documentation:
https://dev.mysql.com/doc/refman/8.0/en/numeric-type-attributes.html

**Comment by scottcwilson** [comment]
Yep, already part of the PR coming-soon!

**Comment by proseLA** [comment]
> FWIW, I find those one-line if statements to be very unreadable and that they could pose issues on any changes. 

in addition, PSR requires curly braces around conditional statements; which is my opinion makes them more readable.

as previously noted, i am a fan of adhering to PSR.

also noting that i prefer the switch case coding, proposed by @lat9 for this situation.

**Comment by scottcwilson** [comment]
I wanted to post the smallest change possible for 1.5.7.  For 1.5.8, my PR has the `case` notation.
