### ISSUE TITLE
PHP 8.0+: Configuration validation warnings and deprecations

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4891]
The majority of the issues previously identified by @mc12345678 in this (https://github.com/zencart/zencart/pull/4407) PR are still valid, even with the changes currently merged for this PR (https://github.com/zencart/zencart/pull/4881) and the corrections provided by this (https://github.com/zencart/zencart/pull/4890) one.

I'm still seeing this PHP Warning:
```
[19-Jun-2022 07:29:03 America/New_York] Request URI: /zc158/hoisT-PYL-teAch/index.php?cmd=configuration&gID=12&cID=293&action=save, IP address: 127.0.0.1
#0 [internal function]: zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\functions\configuration_checks.php(53): filter_var()
#2 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\configuration.php(22): zen_validate_configuration_entry()
#3 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\index.php(11): require('C:\\xampp\\htdocs...')
--> PHP Warning: configurationValidation::sanitizeEmailNullOK(): Argument #1 ($val) must be passed by reference, value given in C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\functions\configuration_checks.php on line 53.
```
and this PHP deprecation:
```
[19-Jun-2022 07:29:03 America/New_York] Request URI: /zc158/hoisT-PYL-teAch/index.php?cmd=configuration&gID=12&cID=293&action=save, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\classes\configurationValidation.php(58): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\classes\configurationValidation.php(24): configurationValidation::sanitizeEmail()
#2 [internal function]: configurationValidation::sanitizeEmailNullOK()
#3 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\functions\configuration_checks.php(53): filter_var()
#4 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\configuration.php(22): zen_validate_configuration_entry()
#5 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\index.php(11): require('C:\\xampp\\htdocs...')
--> PHP Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\classes\configurationValidation.php on line 58.
```

The warning is, I believe, due to the way that the base PHP `filter_var` function deals with the FILTER_CALLBACK handling.  I'll be re-reviewing @mc12345678's changes in the referenced PR as well as the expected behavior in the call-chain from `configuration.php` to `zen_validate_configuration_entry` to see how the behavior can remain the same without passing the values by reference.

**Comment by lat9** [comment]
What is the purpose of this section of `configurationValidation::SanitizeEmail` supposed to provide?

https://github.com/zencart/zencart/blob/538601126506f1c3c80ed1a5b956f659b1043d94/admin/includes/classes/configurationValidation.php#L66-L69

I'm having a hard time 'wrapping my head around it'.

**Comment by lat9** [comment]
OK, that section's going to be removed.  I'll note also that the "Contact Us dropdown" setting is also an optional list; I'll be updating the zc_install to include that as a `sanitizeEmailNullOK` validation.

**Comment by mc12345678** [comment]
> What is the purpose of this section of `configurationValidation::SanitizeEmail` supposed to provide?
> 
> https://github.com/zencart/zencart/blob/538601126506f1c3c80ed1a5b956f659b1043d94/admin/includes/classes/configurationValidation.php#L66-L69
> 
> I'm having a hard time 'wrapping my head around it'.

Why even ask?  See below. 

> OK, that section's going to be removed. I'll note also that the "Contact Us dropdown" setting is also an optional list; I'll be updating the zc_install to include that as a `sanitizeEmailNullOK` validation.

Of course, anything you don't understand, you dispose of. No surprise there. That it took 11 months from when a functional solution was provided, wow.

**Comment by scottcwilson** [comment]
> Of course, anything you don't understand, you dispose of. 

No need to blame Cindy, you can blame me. I explicitly asked all committers not to merge anything from you that was not an obvious bug fix, given how inscrutable your writing (both code and prose) tends to be, and given that you have been unwilling to resolve problems that you yourself introduced. 

You're obviously a clever fellow, and I'd love to have your help, but right now you're being a pain.  Would you behave this way if it was a paid gig?

**Comment by lat9** [comment]
> Why even ask?
> 
Because I thought that someone would quickly step in and identify what that section did.  I've got limited time available currently and, after waiting for 3 hours with no response, I took the plunge.  If _you_ know what that section's purpose was, please enlighten me.
