### ISSUE TITLE
Send Email To: Selection Is Not Really Required on Contact_Us

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#4900]
Somewhat of a two-fold problem that I can separate if needed.

1.  Regardless of any selections being set for the Send Email to:, the focus when landing on the Contact Us page is on the Full Name.  Most of the time, users just enter their name, email, message, and hit send.  At topkayaker.com, they really need a separation between kayak questions, order questions, and website concerns.  They are constantly having to forward emails internally that went to kayak questions instead of order questions.  Swapping their position in the Contact Us form would simply swap who would be forwarding emails.  Since the Send Email To: only shows up when items are entered in the Admin, it will never result in an error for not having something in a required field.  Right now, our workaround is to have the first item set to go to an autoresponder that let's them know they have not selected a valid department and gives a little more information.  If they properly select kayak questions, order questions, or website; the proper email is sent.  Perhaps a method to focus on the Send Email To: if it exists is the first step to making this better.
2. The Send Email To: field in the Contact Us form is set as required.  The problem is that, if used by the store, the field will never be blank and there is no way for the owner to insert a "Please Select" like in the sideboxes.  Therefore, the user can fill in the three other required fields and just hit enter.  The email is sent even if the department they want to reach was not selected.

I combined these as I think the change of focus and actually requiring a Send Email To: option should be combined as a final repair for the problem.

Minor is that the responsive_classic propagates the field without emphasis and with a smaller font than everything else on the page.  This contributes to the overlooking of the selection but is easily fixed with CSS.

In this case, I'm seeing the same response in all browsers. 😃

**Comment by torvista** [comment]
If space is not at a premium, how about changing the dropdown to radio buttons but none selected by default, so they are forced to think?

**Comment by scottcwilson** [comment]
LOVE this solution.  Adds visibility to options when they exist.

**Comment by lat9** [comment]
I'm exploring an alternate solution that would be in effect for _all_ templates.  Essentially, looking at modifying the on-load javascript so that if the 'send_to' dropdown is present, it's given focus and displays all selections.

**Comment by lat9** [comment]
FWIW, changing `/includes/modules/pages/contact_us/on_load_main.js` to the following appears to correct the issue
```
if (document.contact_us) { if (document.getElementById('send-to')) { document.getElementById('send-to').focus(); document.getElementById('send-to').size = document.getElementById('send-to').length; } else if (document.contact_us.contactname) { document.contact_us.contactname.focus() }};
```

If that's acceptable, a PR will be forthcoming later today.

**Comment by dbltoe** [comment]
This really looks great.  Works with tabs and keyboard selection.  And, if it forced them to select off of Please Select, it would be perfect.

**Comment by lat9** [comment]
> This really looks great. Works with tabs and keyboard selection. And, if it forced them to select off of Please Select, it would be perfect.

I'll get that included as well and correct the sizing of the dropdown for `responsive_classic`.

**Comment by scottcwilson** [comment]
Please post a screenshot - could be useful for docs.

**Comment by lat9** [comment]
Screenshot, as requested:
![image](https://user-images.githubusercontent.com/2685585/174681313-074d5673-d6b3-415b-a2ac-c075df9410cb.png)

**Comment by scottcwilson** [comment]
Nice!

**Comment by dbltoe** [comment]
On my 1.5.7 test, Please Select is accepted when Send Email is clicked.
Checking 1.5.8

**Comment by dbltoe** [comment]
Emails are not listing the selection as the subject of the message.  Some folks will have folders that are populated based on the subject of the email.

**Comment by lat9** [comment]
> On my 1.5.7 test, Please Select is accepted when Send Email is clicked. Same response in 1.5.8

What browser?  On FireFox, here's what 1.5.8 shows if "Please select" remains:
![image](https://user-images.githubusercontent.com/2685585/174684111-516122e1-ff15-46ed-be2e-1e9cbafbcec5.png)

**Comment by dbltoe** [comment]
Chrome Again ☹️

**Comment by lat9** [comment]
Bleeping Chrome.  Do you have any Apple devices to test with?  Safari is also on my 'not favorite' list and we don't allow Apple devices in our house.

**Comment by dbltoe** [comment]
☹️ same response for Safari on iPad with latest OS

**Comment by dbltoe** [comment]
Unfortunately, Chrome and Safari currently lead in usage and HTML5 compatibility according to [PC Mag](https://www.pcmag.com/picks/chrome-edge-firefox-opera-or-safari-which-browser-is-best).  Probably because of Android and iOS phones.

**Comment by scottcwilson** [comment]
Radio buttons might be worth another look.

**Comment by lat9** [comment]
I haven't given up ... yet.

**Comment by dbltoe** [comment]
Now, it's a challenge.  🙂

**Comment by lat9** [comment]
OK, I think I've got it, based on [this w3schools](https://www.w3schools.com/tags/att_select_required.asp) example.  The only thing that's going to be somewhat wonky is that the select box can't be expanded on load and the focus needs to be on the "Full Name" so that the send-to isn't selected by that on-load focus
![image](https://user-images.githubusercontent.com/2685585/174689625-514b6235-db15-456f-a352-f7937d8bfab9.png)

**Comment by lat9** [comment]
I suppose, for clarity, the "Send Email To" element could be placed at the end, after the message.  Thoughts?

**Comment by dbltoe** [comment]
I can certainly live with it like this.  IMO, the main thing is to force them to select an option.
👍

**Comment by lat9** [comment]
OK, just pushed an update to the associated PR.  The distinction is that the "Please select ..." option needs to be `readonly` for Chrome to "not consider" that option as a selection to satisfy the `select` tag's `required` attribute.  There's now a teeny bit of jQuery included in the `contact_us` page to force that attribute.

Unfortunately, there's no 'maintainable' way to force HTML attributes on options created via `zen_draw_pull_down_menu`.

**Comment by scottcwilson** [comment]
What about using the 'size='  parameter the way the manufacturers select sidebox does?  This would make the addresses visible.

**Comment by lat9** [comment]
> What about using the 'size=' parameter the way the manufacturers select sidebox does? This would make the addresses visible.

I've gone back &mdash; testing with Chrome, Firefox and Edge &mdash; and found that the combination of
1. Forcing the "Please select ..." option as `disabled` (rather than `readonly`) via the jQuery in `jscript_main.js`.
2. Setting the 'size=' attribute to show all options.
3. Setting the focus to either the '#send-to' dropdown, if present, or the "Full Name".
4. Supplying a default value to `zen_draw_pull_down_menu` that is **not present** in the array, so that none of the selections (including the `''` value for "Please select ...") is set as selected

results in the proper operation on those desktop browsers.

**Comment by lat9** [comment]
PR updated to reflect the above changes.

**Comment by lat9** [comment]
Noting the following part of the HTML 5 specification on required `select` tags (https://html.spec.whatwg.org/multipage/form-elements.html#the-select-element):

![image](https://user-images.githubusercontent.com/2685585/175771913-a6520dbd-1280-4618-9d47-bc8af2b4ef7f.png)
