### ISSUE TITLE
Shopfront edit account: redirect back to form to check details

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4911]
Currently after the customer edits account details, the browser is redirected to the My Account page.

Personally after editing details and submitting, I would prefer to see a confirmation of the changed details. Since there is no display-only view of customer details this means a redirect to the edit form again.

Opinions?

**Comment by scottcwilson** [comment]
I'd rather not see this.  It's easy enough to click View or change my account information, then Back if you really want to confirm your changes.
