### ISSUE TITLE
shipping estimator postcode field named zip_code

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4912]
On all other instances of a postcode field (create account, address book, checkout shipping/payment address) it is name and id of postcode.
On the shipping estimator it is name zip_code with no id.
Any objection to me changing this to match the rest?
While it is no big deal adding this exception in the postcode validation JS I have watching this field everywhere, it seems a good moment to consolidate it.

**Comment by scottcwilson** [comment]
Thank you.  Please proceed.
