### ISSUE TITLE
Fatal Error when Clicking on Product Title or .... more info

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#4915]
Based on code as of 06/24/2022 11:30 and loaded with demo.

This affects only products listed on center pages that have a _...more info_ button instead of an Add: box.

Clicking on any Product Title or the _... more info_ button results in

> WARNING: An Error occurred, please let us know!
and  the following error:
`[25-Jun-2022 16:49:12 UTC] Request URI: /index.php?main_page=product_info&cPath=25&products_id=100, IP address: 2**.***.***.**9
#1 trigger_error() called at [/includes/classes/db/mysql/query_factory.php:665]
#2 queryFactory->show_error() called at [/includes/classes/db/mysql/query_factory.php:632]
#3 queryFactory->set_error() called at [/includes/classes/db/mysql/query_factory.php:273]
#4 queryFactory->Execute() called at [/includes/modules/attributes.php:65]
#5 require(/includes/modules/attributes.php) called at [/includes/modules/pages/product_info/main_template_vars.php:50]
#6 require(/includes/modules/pages/product_info/main_template_vars.php) called at [/includes/templates/responsive_classic/common/tpl_main_page.php:178]
#7 require(/includes/templates/responsive_classic/common/tpl_main_page.php) called at [/index.php:94]
--> PHP Fatal error: 1054:Unknown column 'popt.products_options_comment_position' in 'field list' :: SELECT DISTINCT popt.products_options_id, popt.products_options_name, popt.products_options_sort_order,
popt.products_options_type, popt.products_options_length, popt.products_options_comment, popt.products_options_comment_position,
popt.products_options_size,
popt.products_options_images_per_row,
popt.products_options_images_style,
popt.products_options_rows
FROM products_options popt
LEFT JOIN products_attributes patrib ON (patrib.options_id = popt.products_options_id)
WHERE patrib.products_id= 100
AND popt.language_id = 1 order by LPAD(popt.products_options_sort_order,11,"0"), popt.products_options_name ==> (as called by) /includes/modules/attributes.php on line 65 <== in /includes/classes/db/mysql/query_factory.php on line 665.`

In a fresh install of 1.5.8 with demo click on Test 10% by Attrib from the #navCatTabs.

The first item is Hewlett Packard - by attributes SALE.

Clicking on either the title or the ... more info button will result in a page (URL index.php?main_page=product_info&cPath=25&products_id=36) and the WARNING: .....

FWIW, the link is correct for this product.

**Comment by scottcwilson** [comment]
You have to regen your database.  A change was made to the schema.
