### ISSUE TITLE
Zen Cart banner images refer to http://www.zen-cart.com; should be https://

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4925]
Banners again, looking at the various Zen Cart banner images, when a link is included in the image, that link is to http://www.zen-cart.com instead of https://www.zen-cart.com.
![image](https://user-images.githubusercontent.com/2685585/175810750-9db2949f-4063-4b2a-8b07-c730a550e55a.png)
![image](https://user-images.githubusercontent.com/2685585/175810813-e19d1fc4-bb20-4171-a7a0-159496e22fd2.png)

**Comment by lat9** [comment]
Also the /images/banners/think_anim.gif:
![image](https://user-images.githubusercontent.com/2685585/175811280-ea68e269-4fbf-4550-ad08-e2d424c22e64.png)

**Comment by scottcwilson** [comment]
Good catch.  Sending to Ian.

**Comment by zcwilt** [comment]
hmmm

**Comment by dbltoe** [comment]
All the links are https but the graphic has HTTP

Maybe some new, exciting graphics?

**Comment by zcwilt** [comment]
Can this be closed now.

**Comment by scottcwilson** [comment]
It seems like the trend now is to omit the protocol entirely (and just use www.zen-cart.com or zen-cart.com).  I'd be happy to accept a PR with new graphics.
