### ISSUE TITLE
Storefront sanitization: Review/update handling for various 'standard' variables

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4929]
As reported here:
https://www.zen-cart.com/showthread.php?228293-popup-image-additional-sql-injection-attack&p=1383167

I've had this in place ever since with no recurrence of the logs.
Should this be included?

**Comment by lat9** [comment]
I'll say "Yes".  When I plug that URL into my zc158 test site (running PHP 8.1), I receive the following logs
```
[28-Jun-2022 08:48:13 America/New_York] Request URI: /zc158/index.php?main_page=popup_image_additional&amp;pID=50+%27-6863+union+all+select+CONCAT(0x3a6f79753a,0x4244764877697569706b,0x3a70687a3a)%23&amp;pic=0&amp;products_image_large_additional=bmz_cache/madstad/md-info_01jpg.image.500x500.jpg, IP address: ::1
#0 C:\xampp\htdocs\zc158\includes\modules\pages\popup_image_additional\header_php.php(39): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\index.php(35): require('C:\\xampp\\htdocs...')
--> PHP Warning: Undefined array key "products_image_large_additional" in C:\xampp\htdocs\zc158\includes\modules\pages\popup_image_additional\header_php.php on line 39.

[28-Jun-2022 08:48:13 America/New_York] Request URI: /zc158/index.php?main_page=popup_image_additional&amp;pID=50+%27-6863+union+all+select+CONCAT(0x3a6f79753a,0x4244764877697569706b,0x3a70687a3a)%23&amp;pic=0&amp;products_image_large_additional=bmz_cache/madstad/md-info_01jpg.image.500x500.jpg, IP address: ::1
#0 [internal function]: zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\modules\pages\popup_image_additional\header_php.php(39): stripslashes()
#2 C:\xampp\htdocs\zc158\index.php(35): require('C:\\xampp\\htdocs...')
--> PHP Deprecated: stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in C:\xampp\htdocs\zc158\includes\modules\pages\popup_image_additional\header_php.php on line 39.
```

**Comment by torvista** [comment]
I'm surprised there is not something already in place to filter a dodgy pID?

**Comment by lat9** [comment]
There is, in /includes/init_includes/init_sanitize.php, but it's allowing non-numeric characters.  That (obviously) needs some review.

**Comment by lat9** [comment]
I'm pretty sure that this has been asked before, but given that there are no `$_GET` arrays in a standard ZC install and the $_GET arrays are one of the normal 'script-kiddy' things, is it time to disallow all $_GET arrays during the storefront sanitization?

**Comment by proseLA** [comment]
> I'm pretty sure that this has been asked before, but given that there are no `$_GET` arrays in a standard ZC install and the $_GET arrays are one of the normal 'script-kiddy' things, is it time to disallow all $_GET arrays during the storefront sanitization?

no.

i think we should have an extra script for devs/store owners to do their own sanitizing.  or some sort of auto-loading similar to auto-loading of observers.  

i think it's a valid question, but lets not inflict more pain on those of us maintaining some of these stores.

**Comment by proseLA** [comment]
> there are no `$_GET` arrays in a standard ZC install....

#4934

**Comment by lat9** [comment]
> > there are no `$_GET` arrays in a standard ZC install....
> 
> #4934



> > there are no `$_GET` arrays in a standard ZC install....
> 
> #4934

I don't understand; that's simply changing how an invalid `manufacturers_id` is handled.

**Comment by scottcwilson** [comment]
Possible confusion over wording?  I think was meant was, 
"There are no $_GET variables which are themselves arrays." 
Correct?

**Comment by proseLA** [comment]
scott is correct.

my apologies.

**Comment by torvista** [comment]
In the case of a custom **storefront** GET variable, I assume it needs to be added to one of the $saniGroup arrays manually or an override file created, there's no other method?

**Comment by drbyte** [comment]
> In the case of a custom **storefront** GET variable, I assume it needs to be added to one of the $saniGroup arrays manually or an override file created, there's no other method?

For bespoke code, just sanitize it in your code wherever you use it. 
Even for plugins, since your plugin code is what uses that variable, and your plugin knows what to do with it, just sanitize it where you use it.

**Comment by torvista** [comment]
Ok, I had the idea that the sanitation was based on a whitelist, only allowing what was specifically listed.

**Comment by scottcwilson** [comment]
If some nice person would like to update the documentation, it kind of trails off at the end ... 

https://docs.zen-cart.com/dev/code/admin_sanitization/
