### ISSUE TITLE
zc158: debug for category image = null

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4962]
In the categories table, categories_image default is null.
admin->edit a category that has never had an image:

> PHP Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in admin\categories.php on line 418.

Since the demo has images for all categories, this error does not show after deleting a category image as the field is then set to an empty string, but if you set the field in the db manually to null and refresh the edit category page, the error shows.

Perhaps the easiest solution is to change the db default to an empty string?

**Comment by lat9** [comment]
See my comment for #4963.

**Comment by torvista** [comment]
This is not fixed by https://github.com/zencart/zencart/pull/4994
as the debug is caused by strpos operating on null
https://github.com/zencart/zencart/blob/7a60f75c2358052f9109abb6821e6c0300093502/admin/categories.php#L418
