### ISSUE TITLE
Warning Source map error bootstrap.min.css.map

### ISSUE THREAD

**Issue by brittainmark** [zencart/zencart#4967]
**Describe the bug**
When using Firefox a warning is generated when you are in developer mode. The warning occurs when you enter any page in admin. 
The warning only shows if you have the inspector open.
In Firefox, the warning is:
Source map error: Error: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
`Resource URL: https://innerlightcrystals.co.uk/Test158/YOURADMIN/includes/css/bootstrap.min.css
Source Map URL: bootstrap.min.css.map`

In Edge, the warning is:
`DevTools failed to load source map: Could not parse content for https://innerlightcrystals.co.uk/sales/YOURADMIN/includes/css/bootstrap.min.css.map: Unexpected end of JSON input`

This does not cause any issues with the page loading.

The issue can be solved by removing the last line in bootstrap.min.css namely
`/*# sourceMappingURL=bootstrap.min.css.map */`

If this is removed, bootstrap.min.css.map is no longer required.

**Version**
Zen Cart version: 1.5.8 & 1.5.7d
PHP version: 8.0.21
MySQL version: 
Plugins that may be related: 
What older/newer versions were also tested?

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Log in to admin
2. inspect item on web page
3. view console
**Expected behavior**
no console warnings

**Debug/Error Logs**
none produced
 
**Devices (please complete the following information):**
 - Operating System: Windows 10, Ubuntu 20.04.4
 - Browser :  Firefox: 101.01, Edge: 103.0.1264.44

**Comment by scottcwilson** [comment]
... or we could add the .map to the build.  Not sure which is best.

**Comment by torvista** [comment]
Why not add it, since it is a development tool?

**Comment by brittainmark** [comment]
The .map file does exist, but it is empty, which is the issue. If you know what should go in it then yes, add the details. Sorry, I don't know what is required.

**Comment by torvista** [comment]
It's in the download:
https://getbootstrap.com/docs/3.4/getting-started/#whats-included-precompiled

**Comment by brittainmark** [comment]
Thanks for the link. To quote them.

> This is the most basic form of Bootstrap: precompiled files for quick drop-in usage in nearly any web project. We provide compiled CSS and JS (bootstrap.*), as well as compiled and minified CSS and JS (bootstrap.min.*). CSS [source maps](https://developers.google.com/web/tools/chrome-devtools/javascript/source-maps) (bootstrap.*.map) are available for use with certain browsers' developer tools.

This reads to me that the map files are for development. If this is the case, shouldn't they be excluded from the production environment.

**Comment by torvista** [comment]
If it is not loaded in normal use and gets rid of another semi-confusing error, what's the harm?

**Comment by scottcwilson** [comment]
@brittainmark Would you please try adding it and submit a PR if it gets rid of the error?

**Comment by brittainmark** [comment]
Just to be clear, my solution is to remove the line
`/*# sourceMappingURL=bootstrap.min.css.map */`
from
 bootstrap.min.css 

I'll submit a pr. Feel free to reject if it is not what you wanted.

**Comment by scottcwilson** [comment]
I read your comment too quickly.  I'd rather not delete it - this is manual work that needs to be remembered each time we update the CSS.

**Comment by brittainmark** [comment]
Fine by me, I don't know enough about bootstrap and I could not find the map files.

**Comment by scottcwilson** [comment]
It's all good.  Thank you for reporting this issue - I have seen this before and been annoyed by it.
