### ISSUE TITLE
paypalwpp, getLanguageCode: PHP Deprecated error and more.......

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4985]
ZC158, php 8.1.7
In summary there appear to be multiple things awry in function getLanguageCode.

Anyone interested should look at the whole function while I drag it through the mud.

The starting point was this currently-in-fashion debug:
PHP Deprecated: strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated in \includes\modules\payment\paypalwpp.php on line 1125.
https://github.com/zencart/zencart/blob/f89654027d7e7a2dc9c579364246b6fec15c9bd2/includes/modules/payment/paypalwpp.php#L1123-L1130
the offending check being the third line.
It transpires that the first entry in $user_locale_info is null.

The $user_locale_info array is built just prior to this and has six elements related to language.
https://github.com/zencart/zencart/blob/f89654027d7e7a2dc9c579364246b6fec15c9bd2/includes/modules/payment/paypalwpp.php#L1112-L1121
The first (null) element comes from the use of method 
lng->get_browser_language() 
which actually returns nothing: it creates an array $lng->language

So I believe the first lines should be
```
    $lng->get_browser_language();
    array_unshift($user_locale_info, strtoupper($lng->language['code']));
```

That solves the original null error, which I'll PR for now unless otherwise educated.

But still, the order of the loading of the array is effectively the language priority, so the browser language has priority over the session language....which I would disagree with.

Onwards...
I have an english/spanish store and I was testing with an address in Finland, with the browser in english.
So the $val array was then (EN, EN, FI, FI, FI, ES) as expected...but it is not, as the initialisation of this array is from the $locales array: which is **not being found at this point**.
Consequently the array missing these from my locales.
```
    [0] => en_GB.utf8
    [1] => English_United Kingdom.1252
    [2] => en
```
whereas the vanilla locales are $locales = ['en_US', 'en_US.utf8', 'en', 'English_United States.1252'];

Onwards...
But, the Paypal site was always being shown in spanish (despite the browser language being english) , and the log showed it was indeed always passing   [LOCALECODE] => ES.
So looking at the $to_match array I find:
(
    [0] => US
    [1] => AU
    [2] => DE
    [3] => FR
    [4] => IT
    [5] => GB
    [6] => ES
    [7] => AT
    [8] => BE
    [9] => CA
    [10] => CH
    [11] => CN
    [12] => NL
    [13] => PL
    [14] => PT
    [15] => BR
    [16] => RU
    [17] => DA_DK
    [18] => HE_IL
    [19] => ID_ID
    [20] => JA_JP
    [21] => NO_NO
    [22] => PT_BR
    [23] => RU_RU
    [24] => SV_SE
    [25] => TH_TH
    [26] => TR_TR
    [27] => ZH_CN
    [28] => ZH_HK
    [29] => ZH_TW
)
Which is a mixture of hard-coded country codes and language codes….and indeed without the $locales array (containing "EN") the only match is ES…so that explains that.

But still, even with a hacklet to include those locales for testing, it still does not filter the correct language as there is no match in the $to_match array: there is no "EN".

Additionally this check makes little sense to me.
https://github.com/zencart/zencart/blob/f89654027d7e7a2dc9c579364246b6fec15c9bd2/includes/modules/payment/paypalwpp.php#L1123-L1130

Once EN is added to the array, it works as expected. So this comparison method needs work.

Onwards...
The observant will have noticed the extra array: $additional_language_codes which is added when incontext is in use...except that parameter is never passed to the function/it is never used: only the default mode "ec".

So lots of food for thought there.

**Comment by lat9** [comment]
The 'mention' above will, I believe, correct the following portion.  Since the language files are now loaded via class-based methods, the main language file (and any template-overrides) will need to 'globalize' the `$locales` setting for `paypalwpp` (and anyone else) to gain access to the setting.

> Onwards...
> I have an english/spanish store and I was testing with an address in Finland, with the browser in english.
> So the $val array was then (EN, EN, FI, FI, FI, ES) as expected...but it is not, as the initialisation of this array is from the $locales array: which is not being found at this point.
> Consequently the array missing these from my locales.
> 
>     [0] => en_GB.utf8
>     [1] => English_United Kingdom.1252
>     [2] => en
> 
> whereas the vanilla locales are $locales = ['en_US', 'en_US.utf8', 'en', 'English_United States.1252'];

**Comment by lat9** [comment]
> But still, the order of the loading of the array is effectively the language priority, so the browser language has priority over the session language....which I would disagree with.


While I agree that it appears 'funny' to be viewing a site in Spanish and then being redirected to PayPal in English, English _is_ my first language and the language of my browser and I'd find it a PITA to have to change the PayPal language back to English to complete my purchase on a Spanish-language site.

Other opinions welcomed!

**Comment by lat9** [comment]
> Onwards...
> The observant will have noticed the extra array: $additional_language_codes which is added when incontext is in use...except that parameter is never passed to the function/it is never used: only the default mode "ec".

The _now-observant_ have noticed that the 'incontext' input was apparently once thought necessary, but all calls to `getLanguageCode` appear to be without that argument.
