### ISSUE TITLE
contact_us debugs from direct url &action=send

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4987]
ZC158, php 8.1.7

If you use the url 

> https://SITE/index.php?main_page=contact_us&action=send

you get plenty of debugs. Who would do that? 212.102.33.246 for one, and others over the last few months,

> [06-Jul-2022 15:15:44 UTC] Request URI: /zencart/index.php?main_page=contact_us&action=send, IP address: 127.0.0.1
> #0 [internal function]: zen_debug_error_handler()
> #1 \zencart\includes\modules\pages\contact_us\header_php.php(25): strip_tags()
> #2 \zencart\index.php(35): require('D:\\GitHub\\zenca...')
> --> PHP Deprecated: strip_tags(): Passing null to parameter #1 ($string) of type string is deprecated in \zencart\includes\modules\pages\contact_us\header_php.php on line 25.
> 
> [06-Jul-2022 15:15:44 UTC] Request URI: /zencart/index.php?main_page=contact_us&action=send, IP address: 127.0.0.1
> #0 [internal function]: zen_debug_error_handler()
> #1 \zencart\includes\functions\functions_strings.php(53): preg_replace()
> #2 \zencart\includes\classes\observers\auto.non_captcha_observer.php(42): zen_sanitize_string()
> #3 \zencart\includes\classes\traits\NotifierManager.php(87): zcObserverNonCaptchaObserver->updateNotifyContactUsCaptchaCheck()
> #4 \zencart\includes\modules\pages\contact_us\header_php.php(29): base->notify()
> #5 \zencart\index.php(35): require('D:\\GitHub\\zenca...')
> --> PHP Deprecated: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in \zencart\includes\functions\functions_strings.php on line 53.
> 
> [06-Jul-2022 15:15:44 UTC] Request URI: /zencart/index.php?main_page=contact_us&action=send, IP address: 127.0.0.1
> #0 [internal function]: zen_debug_error_handler()
> #1 \zencart\includes\functions\functions_email.php(720): substr_count()
> #2 \zencart\includes\modules\pages\contact_us\header_php.php(31): zen_validate_email()
> #3 \zencart\index.php(35): require('D:\\GitHub\\zenca...')
> --> PHP Deprecated: substr_count(): Passing null to parameter #1 ($haystack) of type string is deprecated in \zencart\includes\functions\functions_email.php on line 720.

> [06-Jul-2022 15:15:44 UTC] Request URI: /zencart/index.php?main_page=contact_us&action=send, IP address: 127.0.0.1
> #0 \zencart\includes\modules\pages\contact_us\header_php.php(22): zen_debug_error_handler()
> #1 \zencart\index.php(35): require('D:\\GitHub\\zenca...')
> --> PHP Warning: Undefined array key "contactname" in \zencart\includes\modules\pages\contact_us\header_php.php on line 22.
> 
> [06-Jul-2022 15:15:44 UTC] Request URI: /zencart/index.php?main_page=contact_us&action=send, IP address: 127.0.0.1
> #0 \zencart\includes\modules\pages\contact_us\header_php.php(23): zen_debug_error_handler()
> #1 \zencart\index.php(35): require('D:\\GitHub\\zenca...')
> --> PHP Warning: Undefined array key "email" in \zencart\includes\modules\pages\contact_us\header_php.php on line 23.
> 
> [06-Jul-2022 15:15:44 UTC] Request URI: /zencart/index.php?main_page=contact_us&action=send, IP address: 127.0.0.1
> #0 \zencart\includes\modules\pages\contact_us\header_php.php(24): zen_debug_error_handler()
> #1 \zencart\index.php(35): require('D:\\GitHub\\zenca...')
> --> PHP Warning: Undefined array key "telephone" in \zencart\includes\modules\pages\contact_us\header_php.php on line 24.
> 
> [06-Jul-2022 15:15:44 UTC] Request URI: /zencart/index.php?main_page=contact_us&action=send, IP address: 127.0.0.1
> #0 \zencart\includes\modules\pages\contact_us\header_php.php(25): zen_debug_error_handler()
> #1 \zencart\index.php(35): require('D:\\GitHub\\zenca...')
> --> PHP Warning: Undefined array key "enquiry" in \zencart\includes\modules\pages\contact_us\header_php.php on line 25.
> 
> [06-Jul-2022 15:15:44 UTC] Request URI: /zencart/index.php?main_page=contact_us&action=send, IP address: 127.0.0.1
> #0 \zencart\includes\classes\observers\auto.non_captcha_observer.php(42): zen_debug_error_handler()
> #1 \zencart\includes\classes\traits\NotifierManager.php(87): zcObserverNonCaptchaObserver->updateNotifyContactUsCaptchaCheck()
> #2 \zencart\includes\modules\pages\contact_us\header_php.php(29): base->notify()
> #3 \zencart\index.php(35): require('D:\\GitHub\\zenca...')
> --> PHP Warning: Undefined array key "contactname" in \zencart\includes\classes\observers\auto.non_captcha_observer.php on line 42.
>

**Comment by torvista** [comment]
I just added a check for empty of the three compulsory fields with a redirect if so.

**Comment by scottcwilson** [comment]
Move the check for 
```
    $antiSpam = !empty($_POST[$antiSpamFieldName]) ? 'spam' : '';
```
up to the first line of the `if` block and redirect if it's spam. 
See if that fixes it.

**Comment by torvista** [comment]
At the moment the spam field feigns a successful sending of the email, so I think that should stay as it is.
This particular issue is for a compulsory field being empty, which in my logs is always enquiry.
