### ISSUE TITLE
modules/checkout_process surplus parameter

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4988]
ZC158
https://github.com/zencart/zencart/blob/6cec70b0f9621d706a4fa9c1548c7d951ef7c02f/includes/modules/checkout_process.php#L101

is calling
https://github.com/zencart/zencart/blob/6cec70b0f9621d706a4fa9c1548c7d951ef7c02f/includes/classes/order.php#L750

**Comment by scottcwilson** [comment]
I could have sworn I fixed this.  Please PR.

**Comment by torvista** [comment]
I thought I'd seen it too.

**Comment by scottcwilson** [comment]
https://github.com/zencart/zencart/pull/4978
