### ISSUE TITLE
currency update: debug for ecb xml retrieval failure

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5010]
zc158, php 8.1
1) it seems the site is refusing connections: 503, when accessed from the shop.
https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml
When accessed manually, it uses a captcha.

2) The handling of this file/error is not adequate and so continues processing instead of a return false.

https://github.com/zencart/zencart/blob/81782eb678d072952ad919629e0352c77a49aaba/includes/functions/functions_exchange_rates.php#L88-L95

> --> PHP Warning: Undefined array key "GBP" in \includes\functions\functions_exchange_rates.php on line 108.

This seemed an easy fix but not so, the retrieval of the ECB xml is an issue.
Also the use of the static array seems to me overwritten/recreated on every currency check?

**Comment by lat9** [comment]
Looks like ECB has changes to using a REST interface: https://sdw-wsrest.ecb.europa.eu/help/

**Comment by lat9** [comment]
Hmm, I'm not seeing that error.  Running the current alpha zc158 on PHP 8.1.  I've disabled the secondary currency server, now just ecb:
![image](https://user-images.githubusercontent.com/2685585/179018013-39b3b324-b52b-40c7-b345-53fc3b5fced1.png)

**Comment by lat9** [comment]
> zc158, php 8.1
> 
>     1. it seems the site is refusing connections: 503, when accessed from the shop.
>        https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml
>        When accessed manually, it uses a captcha.
> 
>     2. The handling of this file/error is not adequate and so continues processing instead of a return false.
> 
> 
> https://github.com/zencart/zencart/blob/81782eb678d072952ad919629e0352c77a49aaba/includes/functions/functions_exchange_rates.php#L88-L95
> 
> > --> PHP Warning: Undefined array key "GBP" in \includes\functions\functions_exchange_rates.php on line 108.
> 
> ... Also the use of the static array seems to me overwritten/recreated on every currency check?

The `static` property on that array allows the data to be gathered from ECB just once for the page-load and then reused on subsequent calls to the function.

**Comment by torvista** [comment]
The updating is now working ok with no changes to core files, but the problem was not the updating failing, but the handling of a failed retrieval.
