### ISSUE TITLE
suggestion: template_default should be html5

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5011]
Since template_default is intended to be the reference/starting point, should it not be html5?
If classic needs html4, then add it's own overrides or just bin it completely...what is the point of keeping that old template in place when absolutely no-one should use it as an example?

**Comment by torvista** [comment]
different issues, maybe there is a reason, but I doubt it, probably just waiting for someone to do it, like all things.

**Comment by scottcwilson** [comment]
I would be glad to merge a PR if one was created.

**Comment by brittainmark** [comment]
Just done a quick w3c validation, and it complains about valign. This is used throughout zen cart

I was thinking I could hardcode as it currently is, replacing valign with style="{vertical-align:...}"
is that acceptable, and do you want me to change it everywhere?

**This is the list of files containing valign:**
mcs_learn_more.html
vbv_learn_more.html
admin/coupon_admin_export.php
admin/developers_tool_kit.php
admin/includes/attributes_preview.php
admin/includes/javascript/calendarcode.js
admin/includes/javascript/flot/jquery.flot.canvas.min.js
admin/includes/javascript/flot/jquery.flot.js
admin/includes/javascript/flot/jquery.flot.min.js
admin/includes/javascript/spiffyCal/spiffyCal_v2_1.js
admin/includes/modules/document_general/preview_info_meta_tags.php
admin/includes/modules/document_product/preview_info_meta_tags.php
admin/includes/modules/product_free_shipping/preview_info_meta_tags.php
admin/includes/modules/product_music/preview_info_meta_tags.php
admin/includes/modules/product/preview_info_meta_tags.php
admin/invoice.php
admin/media_manager.php
admin/salemaker.php
admin/store_manager.php
admin/whos_online.php
includes/classes/order.php
includes/modules/payment/authorizenet/authorizenet_admin_notification.php
includes/modules/payment/paypal/paypal_admin_notification.php
includes/modules/payment/square_support/square_admin_notification.php
includes/templates/template_default/common/tpl_main_page.php
includes/templates/template_default/templates/tpl_modules_products_all_listing.php
includes/templates/template_default/templates/tpl_modules_products_featured_listing.php
includes/templates/template_default/templates/tpl_modules_products_new_listing.php
not_for_release/zc_plugins/ModList/1.4.0/admin/mod_list.php
not_for_release/zc_plugins/ModList/1.4.1/admin/mod_list.php
zc_plugins/DisplayLogs/v3.0.0/admin/display_logs.php


I probably don't need to do not_for_release.

**Comment by proseLA** [comment]
flot is a library.  we are using 0.8.3.  8 years old.

current release is 4.2.2.  see:

https://github.com/flot/flot/tags

not sure how much pain is going to be involved here.

**Comment by brittainmark** [comment]
Happy to take on a bit of pain. Just wondering about approach and scope.  If a replacement with hardcoded style statements is acceptable as a starting point.  As at some point they will probably want changing. 

Did not mean to include flot or any of the javascript. That's what happens when you use grep to get all the occurrences.

**Comment by brittainmark** [comment]
Agreed @dbltoe .

I have done the low-hanging fruit.
1. admin/denied.php
1. admin/server_info.php
1. ndsbc.html

Does anyone know if admin/popup_image.php is used, I cannot find any calls to it.

If I zc_plugins/DisplayLogs/v3.0.0/admin/display_logs.php should it be a new version? If so, any pointers. I have not done a plugin in this form yet.

**Comment by proseLA** [comment]
> Does anyone know if admin/popup_image.php is used, I cannot find any calls to it.
> 

https://github.com/zencart/zencart/blob/d0318f5d0855a556d98fbac1a504bebe8fbb04db/admin/banner_manager.php#L523

**Comment by brittainmark** [comment]
Thanks, @proseLA . I did not spot the javascript link. I'll have alook at it.

If I zc_plugins/DisplayLogs/v3.0.0/admin/display_logs.php should it be a new version? If so, any pointers. I have not done a plugin in this form yet.

**Comment by scottcwilson** [comment]
Please PR here:
https://github.com/lat9/display_logs
Let Cindy take care of the versioning.

**Comment by scottcwilson** [comment]
Oh yes right- I had forgotten that.  I will update the plugin page. 

Hmmm... I already updated it and very cleverly didn't read the note. :(

**Comment by brittainmark** [comment]
OK some hints on creating v 3.0.1 of display_logs.
I have created a css file and modified display_logs.php will need #5029 fixed (can pr a fix). 
Reading [Upgrading an encapsulated plugin](https://docs.zen-cart.com/dev/plugins/encapsulated_plugins/upgrading/) suggests that I need to copy all the files to v3.0.1

Do I need to modify the scripted installer or leave it out, it appears to just add the necessary configuration keys and register display logs.

Additionally, what should I change in the manifest?

**Or** finally, do you want a separate PR for this, and you will sort it all out?

**Sorry still learning!**

One Observation. If a plugin changes frequently, and you keep all the files each time, then this will quickly become a lot of files that are being added to the download. It could get quite big.

**Comment by lat9** [comment]
@brittainmark, it's probably best to create a separate PR for the "Display Logs".  I agree with your observation, it echoes a concern that I raised back when the zc_plugins handling was introduced.

**Comment by proseLA** [comment]
according to [the docs,](https://docs.zen-cart.com/dev/plugins/encapsulated_plugins/upgrading/) one can just rename the directory.  is that not the case?

the doc page was written by @scottcwilson; so is it not the law? 

when i recently upgraded my [inventory plugin](https://www.zen-cart.com/downloads.php?do=file&id=2279), that is what i did.  no complaints on the forum...

**Comment by scottcwilson** [comment]
As I have written, I have written.  :)

**Comment by scottcwilson** [comment]
Are we there yet?  Can this be closed?

**Comment by scottcwilson** [comment]
OK.

**Comment by scottcwilson** [comment]
Closing.  I really don't want to see a lot of work done on template_default.  The bootstrap template should be used as a reference template for developers wishing to build something.

**Comment by torvista** [comment]
I disagree. That's a plugin.

While I agree cosmetic work should be as limited as possible, the default template is where code fixes and improvements go/it's **THE** reference, and so should be the comparable base for every other template.
Hence it should be formatted html5,   
then responsive_classic should be identical where there is no change - the only differences should be **real** differences,   
and classic should be removed, it serves no purpose anymore.
