### ISSUE TITLE
banner statistics unused code?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5016]
I was going to correct the html for the caption, but how does this code even get used?
https://github.com/zencart/zencart/blob/81782eb678d072952ad919629e0352c77a49aaba/admin/banner_statistics.php#L313-L316

**Comment by drbyte** [comment]
Ya, I removed those captions in https://github.com/zencart/zencart/pull/1572 ... I left that code-block in case someone felt the need to re-implement it. It might require some updating for proper display though.

**Comment by scottcwilson** [comment]
Closing for now.
