### ISSUE TITLE
new Date class provides inaccurate information in debug log.

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#5017]
i am not sure why we do not check if international date is installed on php versions less than 8.1.  it makes no sense to me.

if i turn debug on to play with this class, my debug logs show intl is not installed.  and now i'm on a wild goose chase to try and install it.

if we are less than 8.1 and you want to use sftrtime; fine.  but lets not provide inaccurate data into debug logs.

https://github.com/zencart/zencart/blob/1a6e4803238c742cd799fdff97e14006a3875f38/includes/classes/zcDate.php#L32-L38

**Comment by lat9** [comment]
I don't understand the issue.  For PHP versions < 8.1, `strftime` is available for use.  Otherwise, the code checks to see if the international date is installed.  What debug logs are you receiving?

**Comment by proseLA** [comment]
writing this code in a php 7.4 environment:
```
    $zcDate = new zcDate();
    $zcDate->enableDebug();

    echo $zcDate->output('%x');
    die('<br>' . __FILE__ . ':' . __LINE__);
```
results in the following log:

```
[12-Jul-2022 09:36:20 America/Kentucky/Louisville] Debug enabled: 
zcDate::__set_state(array(
   'intlDateInstalled' => false,
   'useStrftime' => true,
   'locale' => NULL,
   'strftime2date' => NULL,
   'strftime2intl' => NULL,
   'debug' => true,
   'observerAliases' => 
  array (
    'NOTIFIY_ORDER_CART_SUBTOTAL_CALCULATE' => 'NOTIFY_ORDER_CART_SUBTOTAL_CALCULATE',
  ),
))

[12-Jul-2022 09:36:20 America/Kentucky/Louisville] zcDate output for '%x' with timestamp (1657632980), with format converted to '%x': '"07\/12\/22"'
```

even though `intl` is installed.

dates are confusing enough.  if someone wants to use the debug facility for it, we should provide correct information in the log.

the fact that we are using `strftime` is superfluous (and is already there).
