### ISSUE TITLE
zc_plugin for admin not creating correct path to include css files if site in sub directory.

### ISSUE THREAD

**Issue by brittainmark** [zencart/zencart#5029]
**Describe the bug**
When writing an admin plug in if you need to add your own css files for the plugin they should be placed in zc_plugins\YOURPLUGIN\VERSION\admin\include\css. If your site is not top level admin_html_head.php point to the wrong file.

Using display_logs as an example.
I create zc_plugins\display_logs\3.0.0\admin\includes\css\display_logs.css
The admin_html_head.php code creates a relative path of  "/zc_plugins/DisplayLogs/v3.0.0/admin/includes/css/display_logs.css"

This points to "YOURSITE/zc_plugins/DisplayLogs/v3.0.0/admin/includes/css/display_logs.css" which is fine if your site is not a subdirectory.

Options.
1. Change the code to point to "../zc_plugins/DisplayLogs/v3.0.0/admin/includes/css/display_logs.css" This works as you are currenlt in YOURADMIN folder
1. Change the code to include the subdirectory if it exists "/MySiteSubDirectory/zc_plugins/DisplayLogs/v3.0.0/admin/includes/css/display_logs.css"  i.e. DIR_WS_CATALOG minus trailing slash.

**Version**
Zen Cart version: 1.5.8
PHP version: 8.0.20

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Create a zen cart shop in a subdirectory of the main site.
1. add zc_plugins/DisplayLogs/V3.0.0/admin/includes/css/display_logs.css
1. put something in display_logs.css e.g. table {background:red}
1. install display logs if not already done so (admin>modules>plugin manager, select display logs, Install and install)
1. Create a logfile in your logs directory with a name like myDEBUG-adm-20220708-174655-111752.log
1. Return to admin home page
3. click on the link in the display message
4. log will display with no error, but the background will not be red (assuming you made that change)
5. if you enter the browser console you will see that the display_logs.css failed to load as the file could not be found.

**Expected behavior**
The created css file is loaded from the correct location

**Debug/Error Logs**
None created

**Comment by proseLA** [comment]
good catch...

we have gone from here in v157:

https://github.com/zencart/zencart/blob/742b837868a2b128df96b6635c413c8187972679/includes/classes/FileSystem.php#L120-L128

to here in v158:

https://github.com/zencart/zencart/blob/e0298ab2170449b3fc92d527ee73a95a53b4ac08/laravel/app/Models/PluginControl.php#L22-L26

looks like `DIR_WS_HTTPS_CATALOG : DIR_WS_CATALOG`  is missing in v158

**Comment by brittainmark** [comment]
ok so need to update admin_html_head.php to add
($GLOBALS['request_type'] == 'SSL' ? DIR_WS_HTTPS_CATALOG : DIR_WS_CATALOG)
to the paths of the include files. 
shall I pr?

**Comment by proseLA** [comment]
MO.

bugs need fixing.

one should not need to request permission to PR something.   it is a community effort.

if your PR is crap; hopefully the maintainers will say so, and not merge.  else i'll complain about it after it is merged!

:boom: :boom: :boom: :satisfied:

**Comment by brittainmark** [comment]
OK I'll do it. Glad I waited for your first comment, or it would have been crap 💩
pr to follow.

**Comment by proseLA** [comment]
man, can someone tell me the point of this `ltrim`?  makes 0 sense to me:

https://github.com/zencart/zencart/blob/e0298ab2170449b3fc92d527ee73a95a53b4ac08/laravel/app/Models/PluginControl.php#L30-L32

**Comment by proseLA** [comment]
@brittainmark 
try replacing the `PluginControl.php` with the following code, and let me know if it works for you.  i think it will require additional testing.  it is confusing for sure.
```
namespace App\Models;

use Illuminate\Database\Eloquent\Model as Eloquent;

class PluginControl extends Eloquent
{
    protected $table = TABLE_PLUGIN_CONTROL;
    protected $primaryKey = 'unique_key';
    protected $keyType = 'string';
    public $incrementing = false;
    public $timestamps = false;
    protected $guarded = [];
    private $subdirectory;


    public function getRelativePath()
    {
        $this->subdirectory = ($GLOBALS['request_type'] == 'SSL' ? DIR_WS_HTTPS_CATALOG : DIR_WS_CATALOG);
        $relativePath =  $this->subdirectory . 'zc_plugins/' . $this->unique_key . '/' . $this->version . '/';
        return $relativePath;
    }

    public function getAbsolutePath()
    {
        $relativePath = $this->getRelativePath();
        $absolutePath = rtrim(DIR_FS_CATALOG, $this->subdirectory) . '/';
        return $absolutePath;
    }

}
```

**Comment by brittainmark** [comment]
Close, but no 🍌.
The issue is if the subdirectory contains any character that are at the end of the path, they are incorrectly removed by the rtrim.
In my case:
DIR_FS_CATALOG =/home/lotus/public_html/innerlightcrystals/Test158/
$this->subdirectory= /Test158/

so the last "S" is removed from the $absolutePath giving 
$absolutePath  = /home/lotus/public_html/innerlightcrystal/
not
$absolutePath  = /home/lotus/public_html/innerlightcrystals/
as required

my proposed solution
change
`$absolutePath = rtrim(DIR_FS_CATALOG, $this->subdirectory) . '/';`
to
`$absolutePath = substr(DIR_FS_CATALOG, 0, -strlen($this->subdirectory)) . '/';`

Shall I pr or do you want to do any testing before I submit? 
Have closed previous pr.

**Comment by brittainmark** [comment]
The above fixes my issue, but I think there are more issues with admin_html_head.php and javascript_loader.php have more issues.
For example, admin_head.php line 41
`$directory_array = $template->get_template_part($absoluteDir . 'admin/includes/css/', '/^global_stylesheet/', '.css');`
will create a directory path of /home/lotus/public_html/innerlightcrystals/admin/include/css using my example above.
This does not include the subdirectory, and should not ever exist on a live implementation with or without a subdirectory, as the admin folder should be renamed. 
There are similar occurrences in javascript_loader.php 

Additionally, getTemplatePart in PageLoader.php is creating strings like
zc_plugins/DisplayLogs/v3.0.0/catalog//home/lotus/public_html/innerlightcrystals/admin/includes/javascript/
to search for directories.

I am totally confused now. 
Do I need to understand Laravel to understand what is going on? 
Or is this an issue that needs raising separately?
Or am I barking up the wrong tree?

**Comment by brittainmark** [comment]
To make javascript work for admin
 javascript_loader.php need modifying
lines 68-75 from
```
if (file_exists($absoluteDir . 'admin/includes/javascript/' . basename($PHP_SELF, '.php') . '.php')) {
        echo "\n";
        require $absoluteDir . 'admin/includes/javascript/' . basename($PHP_SELF, '.php') . '.php';
    }
    if (file_exists($absoluteDir . 'admin/includes/javascript/' . basename($PHP_SELF, '.php') . '.js')) {
        echo "\n";
?>
        <script src="<?php echo $relativeDir ?>admin/includes/javascript/<?php echo basename($PHP_SELF, '.php') . '.js'; ?>"></script>
```
to

``` 
if (file_exists($absoluteDir . substr($relativeDir, 1) . 'admin/includes/javascript/' . basename($PHP_SELF, '.php') . '.php')) {
        echo "\n";
        require $absoluteDir . $relativeDir . 'admin/includes/javascript/' . basename($PHP_SELF, '.php') . '.php';
    }
    if (file_exists($absoluteDir . substr($relativeDir, 1) . 'admin/includes/javascript/' . basename($PHP_SELF, '.php') . '.js')) {
        echo "\n";
?>
        <script src="<?php echo $relativeDir ?>admin/includes/javascript/<?php echo basename($PHP_SELF, '.php') . '.js'; ?>"></script>
```

**Comment by brittainmark** [comment]
OK I think I have finally got it. The function getAbsolutePath has changed too between 1.5.7 and 1.5.8.
```
class PluginControl extends Eloquent
{
    protected $table = TABLE_PLUGIN_CONTROL;
    protected $primaryKey = 'unique_key';
    protected $keyType = 'string';
    public $incrementing = false;
    public $timestamps = false;
    protected $guarded = [];
    
    public function getRelativePath()
    {
        $relativePath =   ($GLOBALS['request_type'] == 'SSL' ? DIR_WS_HTTPS_CATALOG : DIR_WS_CATALOG) . 'zc_plugins/' . $this->unique_key . '/' . $this->version . '/';
        return $relativePath;
    }
    
    public function getAbsolutePath()
    {
        $absolutePath = DIR_FS_CATALOG . 'zc_plugins/' . $this->unique_key . '/' . $this->version . '/';
        return $absolutePath;
    }
    
}
```

This works great for javascript. Just needs one change to admin_html_head.
line 48 from
``` 
if (file_exists($absoluteDir . substr($relativeDir, 1) . 'admin/includes/css/' . basename($PHP_SELF, '.php') . '.css')) {
```
to
```
if (file_exists($absoluteDir  . 'admin/includes/css/' . basename($PHP_SELF, '.php') . '.css')) {
```
Which makes sense as you are now using the absolute value for the plug in path and adding to it to get what you need.

**Comment by proseLA** [comment]
create a PR. 

i'll look at it later. 

but i've been thinking that a refactor is needed to eliminate duplicate code in the javascript loader and the admin_head. 

less code is preferable.

**Comment by proseLA** [comment]
> OK I think I have finally got it. The function getAbsolutePath has changed too between 1.5.7 and 1.5.8.
> 
> ```
> class PluginControl extends Eloquent
> {
>     protected $table = TABLE_PLUGIN_CONTROL;
>     protected $primaryKey = 'unique_key';
>     protected $keyType = 'string';
>     public $incrementing = false;
>     public $timestamps = false;
>     protected $guarded = [];
>     
>     public function getRelativePath()
>     {
>         $relativePath =   ($GLOBALS['request_type'] == 'SSL' ? DIR_WS_HTTPS_CATALOG : DIR_WS_CATALOG) . 'zc_plugins/' . $this->unique_key . '/' . $this->version . '/';
>         return $relativePath;
>     }
>     
>     public function getAbsolutePath()
>     {
>         $absolutePath = DIR_FS_CATALOG . 'zc_plugins/' . $this->unique_key . '/' . $this->version . '/';
>         return $absolutePath;
>     }
>     
> }
> ```
> 
> This works great for javascript. Just needs one change to admin_html_head. line 48 from
> 
> ```
> if (file_exists($absoluteDir . substr($relativeDir, 1) . 'admin/includes/css/' . basename($PHP_SELF, '.php') . '.css')) {
> ```
> 
> to
> 
> ```
> if (file_exists($absoluteDir  . 'admin/includes/css/' . basename($PHP_SELF, '.php') . '.css')) {
> ```
> 
> Which makes sense as you are now using the absolute value for the plug in path and adding to it to get what you need.

in my testing, this is correct.  i would PR with changes to those 2 files.

**Comment by brittainmark** [comment]
pr created #5035 5035
