### ISSUE TITLE
Making zen cart admin HTML5 standard

### ISSUE THREAD

**Issue by brittainmark** [zencart/zencart#5039]
I have been looking at HTML5 for zen cart since #5011 was opened. I have been looking at the ADMIN side, primarily because it only has to look at one template to consider.
I was thinking of making the changes to html_output.php and would like feed back. You can see the proposed changes [HERE](https://github.com/zencart/zencart/commit/0b292f6d4274e4de209d950825e9ac36920d5f9f) or look at [Brittainmark/zencart branch ](https://github.com/brittainmark/zencart/tree/brittainmark-admin_html_output)

### line 140-146
Remove the width and height parameters and replace with CSS style.
I could also add in a check to see if style is already present in $parameters and if it is, add to or replace as appropriate.

### The rest of the changes*
I have added "id" to all the input elements except **zen_draw_hidden, zen draw_form, zen_draw_separator and zen_draw_label.**
## The reason for the change
In HTML5 the label field's "for" element needs to match with an input element "id" field not the "name" element. Also, width and height are superseded by CSS.
The way I have done this is to use the $name for both the "name" and "id" element.
Replace width and height with style.

The reason I propose doing it this way is that there are  571 calls to zen_draw_[input] that do **not** have an "id" specified, and only 338 with an "id" specified.
This is still a lot of work, but I feel is the lesser task. I would also need to check to see that the "id" matches and if not make changes if necessary.

Additionally, it would mean that all input elements have an "id" to allow CSS  against and labels.
Finally, I think it would make the code tidier, as you would not have to include 'id="some_bloody_id"' in the $parameters field on every call to create an input field.

If I have done this completely wrong. Please feel free to educate me on how I could have shown you the changes and got feed back.
If you have any other ideas that might help get zen cart to html5 standard or other ways I could have achieved this, please comment.
If you are happy with this approach, please also comment, so I can proceed.
Thanks

**Comment by torvista** [comment]
>The way I have done this is to use the $name for both the "name" and "id" element.
> there are 571 calls to zen_draw_[input] that do not have an "id" specified, and only 338 with an "id" specified.

I think that's right.  
To simplify the code, the function should add an id if not defined in the function call.  
And for all those that **do** have an id defined, if they are the same, remove them. If they are not the same, plan to change and remove them too.

**Comment by brittainmark** [comment]
have sublitted #5085
