### ISSUE TITLE
ip address in order...

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#5062]
i have never understood why the IP address is formatted this way:

![image](https://user-images.githubusercontent.com/1095136/181318410-5f2b7e36-93c8-4ef4-928a-8e01d3639bdb.png)

in the code, we establish the `$_SESSION['customers_ip_address']` as the `$_SERVER['REMOTE_ADDR']` and then for the order we put them both in there.

is there a reason for this?

https://github.com/zencart/zencart/blob/3b6d8a8c7fe6bbe62633660bbf8e367759bdb798/includes/application_top.php#L256-L260

https://github.com/zencart/zencart/blob/3b6d8a8c7fe6bbe62633660bbf8e367759bdb798/includes/classes/order.php#L448

https://github.com/zencart/zencart/blob/3b6d8a8c7fe6bbe62633660bbf8e367759bdb798/includes/classes/order.php#L825

**Comment by scottcwilson** [comment]
Many moons ago, when payment was made by PayPal, these two strings were different.  Here's an order from 2010 showing this: 


<img width="232" alt="pp" src="https://user-images.githubusercontent.com/4391638/190904333-92d50add-318b-403f-89d3-8d5272fdc406.png">

**Comment by scottcwilson** [comment]
I'd be happy to accept a PR that didn't show the second IP if they were identical, btw.

**Comment by scottcwilson** [comment]
Please PR or close.  Thanks.
