### ISSUE TITLE
Improve Accessibility for Sideboxes

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#5063]
When the sideboxes for New Products, Specials, and Featured are generated, if an items fits the qualifications, the link and information are presented in <div class="sideboxContentItem" and generate an A link using the image as the text for the link,

The image data for the Bug' Life DVD comes out to be:
`<img src="images/dvd/a_bugs_life.gif" alt="A Bug's Life Linked" title="A Bug's Life Linked" width="100" height="80"><br>"A Bug's Life Linked"</a>`

The system is taking the Product's Title and uses it for the alt tag, the image title, and the displayed link text underneath.

This generates an alert for Redundant Alternativ Text.  This confuses browser readers and might make the SEs lower rank for keyword stuffing.

If the link is changed to the following, all Accessibility standards would be met.

`<img src="images/dvd/a_bugs_life.gif" alt="" role="presentation" title="A Bug's Life Linked" width="100" height="80"><br>"A Bug's Life Linked"</a>`

Most all browsers see the empty alt tag as being presentational.  The newer browsers will accept the role tag.  This will result in about 35 alerts on the main page of the out-of-the-box going away.

I'm assuming the changes would be made in (e.g. Featured) at line 17 of includes/template_default/sideboxes/tpl_featured.php.

Since these are different from the items in the center boxes AND I am not knowledgeable enough to figure the code.  I enter it here.

If someone presents the proper code change, I will do the PR and hopefully not mess it up. 😄 

FYI -- It appears that the center page layout for Featured and others uses the same tpl.

**Comment by lat9** [comment]
Except for those templates (?) that create the HTML `<img>` tags themselves, this change could be consolidated by an update to the `zen_image` function, present in `/includes/functions/html_output.php`.  I'll take care of the code-change, since that function needs a bit of refactoring as well.
