### ISSUE TITLE
shopfront TEXT_DATE_ADDED: multiple places where date substitution is not implemented

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5072]
One example
![Clipboard01](https://user-images.githubusercontent.com/4391026/182041512-32168cd1-1320-4e43-bf7e-cc4fb754b61f.gif)

searching for uses of TEXT_DATE_ADDED shows others.

**Comment by lat9** [comment]
Affected files:
- /includes/templates/responsive_classic/templates/tpl_modules_products_all_listing.php
- /includes/templates/responsive_classic/templates/tpl_modules_products_new_listing.php
- /includes/templates/template_default/templates/tpl_modules_products_all_listing.php
- /includes/templates/template_default/templates/tpl_modules_products_new_listing.php
