### ISSUE TITLE
MobileDetect requires updating

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5075]
ZC version @version 2.8.33
Source  @version 2.8.39

I just got a debug due to this. Latest version has the fix.

**Comment by scottcwilson** [comment]
./includes/classes/Mobile_Detect.php is the file; a PR is welcome.  Please post the debug for documentation.

**Comment by torvista** [comment]
No way this can be automagically included from the source to keep it up to date?

**Comment by proseLA** [comment]
> No way this can be automagically included from the source to keep it up to date?

way.

a little research can go a long way.

download the 2.8.33 zip.  extract.  compare the `Mobile_Detect.php` class file in the root to the one in the ZC file referenced above.  exactly the same.

get the 2.8.39 zip, extract and put the same file in said location, and test.

zips are here:

https://github.com/serbanghita/Mobile-Detect/tags

**Comment by torvista** [comment]
Yes I'm already using the latest version/no problem in retrieving it manually.
That wasn't the question. Just wondered in this modern world of dependencies etc., whether it could be done/flagged when a new release is available?

**Comment by scottcwilson** [comment]
Closed by #5083.

**Comment by torvista** [comment]
Time for another update?
Current version is 3.74.0.

Noting the file and class is now MobileDetect (no hyphen) and will not work until 
`namespace Detection;`
is commented out.

I don't know how to deal with the namespace issue to allow the file to remain native.

**Comment by scottcwilson** [comment]
I will open a new issue.  Thanks for identifying this.
