### ISSUE TITLE
Strip admin name and site full path from error logs to prevent disclosure in error reports

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5102]
I've done that, seems like a good idea.

**Comment by mc12345678** [comment]
A given store can have multiple admin folders (on purpose), how would the logs differentiate issues with the multiple folders under some sort of information elimination? 

What about adding more info instead of removing it?  (Yes, I know that giving guidance doesn't mean it will be heeded.)

**Comment by torvista** [comment]
dunno, have a go with the draft
https://github.com/torvista/zencart/tree/error_logging

**Comment by proseLA** [comment]
i hate this idea.  

if an intruder gets access to your log files, there are bigger problems than the location of the admin directory.

**Comment by torvista** [comment]
> i hate this idea.

Of course, :grin:

I was thinking of less-experienced people accidentally pasting their details into the public domain, and also just cutting out chaff in the text so it is a little clearer/easier to read for the same users.

**Comment by scottcwilson** [comment]
If someone accidentally discloses their secret-admin-name, all they have to do in recent versions of Zen Cart is rename the folder.  No configure.php updates.  So I'm not sure this is worth a lot of effort.

**Comment by mc12345678** [comment]
> If someone accidentally discloses their secret-admin-name, all they have to do in recent versions of Zen Cart is rename the folder. No configure.php updates. So I'm not sure this is worth a lot of effort.

Goes back to both torvista's and ZCwilt's points. Torvista is targeting protection for new users who already are behind the ball a little and may not yet realize the significance of mitigating unapproved access to even the login screen. The other that security is provided by not letting it be known where that login exists. 

While I can appreciate the intent of further obfuscation by not logging the info, I also see added difficulty of not having that info. Of course leads to a suggestion of some sort of flag, setting, configuration option or possibly easily added or removed code (plugin) as a possible solution. 

Further a store that is operated or managed by more than one individual then requires updating of all involved about what the new admin is. People being people are more likely to go the easy route and leave it alone to maybe learn the lesson though possibly after some problem...

**Comment by torvista** [comment]
> If someone accidentally discloses their secret-admin-name, all they have to do in recent versions of Zen Cart is rename the folder.
Prevention is better than cure.

> Further a store that is operated or managed by more than one individual then requires updating of all involved about what the new admin is.
Good point, in practice means everyone's browser favourites need updating and ensures everyone also knows who screwed up.

>I'm not sure this is worth a lot of effort
I think it is pretty much done already.

**Comment by scottcwilson** [comment]
Thanks for the suggestion, but I'd rather not have this.
