### ISSUE TITLE
error log on missing image

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5121]
When a product has an image defined but it is not found, I generate an error log. Otherwise it would never be detected.
Is that PR of interest?

**Comment by zcwilt** [comment]
hmm. thought PRODUCTS_IMAGE_NO_IMAGE might cover this, but think that only works if there is no image defined for a product, and not if an image is defined but then isn't there.

**Comment by torvista** [comment]
One thing is ensuring an image is always shown in the storefront/there is no visible error, that is covered.
Another is flagging the problem for fixing, which is not covered.

**Comment by scottcwilson** [comment]
Please don't - there are plugins that can detect this kind of thing.  I often run test sites with minimal images to verify other things.

**Comment by torvista** [comment]
`I often run test sites with minimal images to verify other things.`
I have an admin switch for it. It's only on when the site is supposedly complete.
