### ISSUE TITLE
responsive_classic/mobile: header icons not showing?

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#5122]
Is it just me or did some change the the CSS in zc157/zc158 result in the non-display of the `responsive_classic`'s mobile header icons?

On my zc156 test site:
![image](https://user-images.githubusercontent.com/2685585/184574529-d7ed5c1e-f83a-4162-a171-693f665b2a20.png)

On my zc157 local host site:

![image](https://user-images.githubusercontent.com/2685585/184574590-afbab800-de7a-4d34-b378-a805463a38b3.png)

On my zc158 local host site:

![image](https://user-images.githubusercontent.com/2685585/184574693-255ed747-44aa-41d0-b2e0-79a52b708580.png)

**Comment by dbltoe** [comment]
I made a change some days ago to the hamburger (white) and I am seeing the changes that were merged.

![image](https://user-images.githubusercontent.com/5122886/184594266-beb86436-76bd-43c4-80c9-9d1e7a640938.png)

**Comment by lat9** [comment]
I'm seeing that white hamburger, and I've done another compare against the current v158 repository.  Using both Firefox's and Chrome's mobile emulators, I see (as above) the hamburger but not the FA icons.

**Comment by lat9** [comment]
... although, I do see those icons when testing via Responsively (arggh).

**Comment by barco57** [comment]
When using the emulators in firefox and chrome it is required to refresh when switching to mobile view to trigger the mobile detect to see the new viewport size.

**Comment by dbltoe** [comment]
I use Mobile simulator - responsive testing tool  version 3.7.3

No refresh required and works fully with inspect.

**Comment by lat9** [comment]
> When using the emulators in firefox and chrome it is required to refresh when switching to mobile view to trigger the mobile detect to see the new viewport size, when using responsive_classic.

Yep, I know.  Didn't make a difference ... for me.
