### ISSUE TITLE
jquery.mmenu.all.css maybe due for updating: /templates/responsive_classic/css/jquery.mmenu.all.css

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5127]
While seeing that this has a minor css error, I see it has not been updated for seven years.
Perhaps a template expert should review it.

I believe it comes from here:
https://github.com/FrDH/mmenu-js

There is a similar file in version 5.74 in /dist/css
Onwards, the package structure changes.

**Comment by barco57** [comment]
Hmmm, version 5.5.3 that we use was MIT licensed and then it changed in 5.6.0 it changed to CC-BY-NC-4.0
Not sure what consequence the license change has on our usage of it, if any.

**Comment by zcwilt** [comment]
hmm. MIT is copy-left compatible
will check for the creative commons license

**Comment by zcwilt** [comment]
This may be a problem
v4.0 CC stuff is compatible with GPL v3, but not GPL2 
note: for various reasons we can't update ZC to be GPL v3

**Comment by zcwilt** [comment]
I guess this is only a problem if we try and pull in a later version. we could just hard fix our code

**Comment by scottcwilson** [comment]
Dependency checking is now part of the build process.  No need for separate issues unless there is a security alert that requires immediate updating.  

https://docs.zen-cart.com/dev/release_process/dependency_checks/
