### ISSUE TITLE
Stray end tag

### ISSUE THREAD

**Issue by brittainmark** [zencart/zencart#5130]
**Describe the bug**
there is an additional </td> tag in orders, causing validation error Stray end tag td.

**Version**
Zen Cart version: 1.5.8
PHP version: 8.0.20

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Go to 'admin>orders'
3. view page source
4. copy page source 
5. paste into https://validator.w3.org/nu/#textarea
6. click validate

**Expected behavior**
there should be no validation errors.

**Comment by brittainmark** [comment]
Thanks, @proseLA. Shall do, I did ask earlier. But you are the first to say stop. So I will for simple fixes.

**Comment by mc12345678** [comment]
> i would just create PRs for simple fixs as opposed to creating an issue... but that's just me...

If that is the way, then the following should be updated: https://github.com/zencart/zencart/blob/v158/CONTRIBUTING.md#guidelines

Specifically the content referenced by the section on [Guidelines for Reporting Bugs](https://docs.zen-cart.com/dev/contributing/issues/).

**Comment by brittainmark** [comment]
Ok Guess I'll keep creating issues. No problem, just trying to do it right.

**Comment by scottcwilson** [comment]
it's all good.  Thanks for helping to improve our code base.
