### ISSUE TITLE
Undefined variable $gInfo in admin\group_pricing.php

### ISSUE THREAD

**Issue by OldNGreyBMR** [zencart/zencart#5144]
**Describe the bug**
Undefined variable $gInfo in admin\group_pricing.php line 227

**Version**
Zen Cart version: 158
PHP version: 8.1

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1 In Admin select Customers | Group Pricing
2 select Customers | Customer Groups [ with no groups]
3 Warning log file created

**Expected behavior**
No error expected

**Debug/Error Logs**
20-Aug-2022 06:50:14 UTC] Request URI: /zc158_ALPHA_Test/Admin/index.php?cmd=group_pricing, IP address: 192.168.1.63
#0 E:\Web\zc158_ALPHA_Test\Admin\group_pricing.php(227): zen_debug_error_handler()
#1 E:\Web\zc158_ALPHA_Test\Admin\index.php(11): require('E:\\Web\\zc158_AL...')
--> PHP Warning: Undefined variable $gInfo in E:\Web\zc158_ALPHA_Test\Admin\group_pricing.php on line 227.

[20-Aug-2022 06:50:15 UTC] Request URI: /zc158_ALPHA_Test/Admin/index.php?cmd=group_pricing, IP address: 192.168.1.63
#0 E:\Web\zc158_ALPHA_Test\Admin\group_pricing.php(227): zen_debug_error_handler()
#1 E:\Web\zc158_ALPHA_Test\Admin\index.php(11): require('E:\\Web\\zc158_AL...')
--> PHP Warning: Attempt to read property "group_id" on null in E:\Web\zc158_ALPHA_Test\Admin\group_pricing.php on line 227.
 
**Devices (please complete the following information):**
 - Operating System: [e.g. Windows, Mac, Android, iOS]
 - Browser [e.g. chrome, firefox] and version number

**Additional context**
existence of $gInfo not checked on line 224 before accessing "$gInfo->group_id"

**Comment by brittainmark** [comment]
The issue is that for insert ($action='new') the group id is not required. will remove gID= from new actions.

**Comment by brittainmark** [comment]
I have added checks instead of removing, so cancel returns you to the group you were editing.
See #5145

**Comment by OldNGreyBMR** [comment]
Fixed by Check $gInfo and gID set on insert #5145

**Comment by OldNGreyBMR** [comment]
I tested OK with
ZC158 PHP 8.1
ZC158 PHP 8.0
ZC158 PHP 7.4
and then closed issue #5144 not realising it would also close #5145.

You may need to reopen #5145
