### ISSUE TITLE
categories.php: Use of TOPMOST_CATEGORY_PARENT_ID

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5162]
https://github.com/zencart/zencart/blob/a61d28e0bdb35bce0593a3d7a6026650afa41a09/admin/categories.php#L114-L130

Re the TODO comment; I'm not sure if TOPMOST_CATEGORY_PARENT_ID is relevant here? I am not clear on the restrictions in place in this section.

**Comment by scottcwilson** [comment]
I think the intention was to change 

```
         if ($parent_cat->fields['parent_id'] != '0') { 
```
to
```
         if ($parent_cat->fields['parent_id'] != TOPMOST_CATEGORY_PARENT_ID) { 
```

**Comment by drbyte** [comment]
When I added that comment, it was because I hadn't dug in fully to see whether the `'0'` actually meant top-level-cat, and if it is, then whether there were ripple-effect consequences of it.

**Comment by drbyte** [comment]
Ref: https://github.com/zencart/zencart/pull/3690

**Comment by scottcwilson** [comment]
@drbyte Would you please resolve this when you have a moment?  Thanks.

**Comment by drbyte** [comment]
> I think the intention was to change
> 
> ```
>          if ($parent_cat->fields['parent_id'] != '0') { 
> ```
> 
> to
> 
> ```
>          if ($parent_cat->fields['parent_id'] != TOPMOST_CATEGORY_PARENT_ID) { 
> ```

Yes. After digging further, I'm pretty sure the original intent of the `'0'` was to denote what we've now assigned as `TOPMOST_CATEGORY_PARENT_ID`.
