### ISSUE TITLE
Question Tax basis in store pickup

### ISSUE THREAD

**Issue by brittainmark** [zencart/zencart#5200]
Should Store be an option in the MODULE_SHIPPING_STOREPICKUP_TAX_BASIS code below
`    $db->Execute("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Tax Basis', 'MODULE_SHIPPING_STOREPICKUP_TAX_BASIS', 'Shipping', 'On what basis is Shipping Tax calculated. Options are<br>Shipping - Based on customers Shipping Address<br>Billing Based on customers Billing address<br>Store - Based on Store address if Billing/Shipping Zone equals Store zone', '6', '0', 'zen_cfg_select_option(array(\'Shipping\', \'Billing\'), ', now())");`
It is in the description but omitted from the options.
either remove 
`<br>Store - Based on Store address if Billing/Shipping Zone equals Store zone`
or change to
`'zen_cfg_select_option(array(\'Shipping\', \'Billing\',\'Store\')`

Please do not change until #5199 is merged.

**Comment by scottcwilson** [comment]
yes same thing here. You can have a fee for store pickup so tax needs to be handled.

**Comment by brittainmark** [comment]
Install need mod for this change too.

**Comment by brittainmark** [comment]
I'll do this as a separate pr. it complicated #5199 unnecessarliy

**Comment by brittainmark** [comment]
This one is not complete. Will submit the required pr #5219
