### ISSUE TITLE
Question should $tax_basis be set in freeshipper

### ISSUE THREAD

**Issue by brittainmark** [zencart/zencart#5201]
All the other shipping modules have $tax_basis set. Should it also be set in freeshipper
i.e, add
`$this->tax_basis = MODULE_SHIPPING_FREESHIPPER_TAX_BASIS;`
after 
`$this->tax_class = MODULE_SHIPPING_FREESHIPPER_TAX_CLASS;`
and 
`$db->Execute("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Tax Basis', 'MODULE_SHIPPING_FREESHIPPER_TAX_BASIS', 'Shipping', 'On what basis is Shipping Tax calculated. Options are<br>Shipping - Based on customers Shipping Address<br>Billing Based on customers Billing address<br>Store - Based on Store address if Billing/Shipping Zone equals Store zone', '6', '0', 'zen_cfg_select_option(array(\'Shipping\', \'Billing\',\'Store\'), ', now())");`
to the install method.

Please do not change until #5199 merged

**Comment by dbltoe** [comment]
I would think not.  Even if the shipping location required a tax on the cost of shipping, what is tax x zero?

**Comment by brittainmark** [comment]
That's fine.  I agree, just checking as it is in the other free method freeoptions. Not sure if it was for consistency.
It is used by the paypal modules and ot_shipping, but both check it exist and default back to STORE_SHIPPING_TAX_BASIS if it is not set.

**Comment by scottcwilson** [comment]
Yes it does need to be set because Freeshipper has a handling fee which can be non zero.

**Comment by brittainmark** [comment]
Are you happy for me to include in #5199 or seperate pr

**Comment by scottcwilson** [comment]
just stick it in with existing PR

**Comment by brittainmark** [comment]
Will changes need to be made to zen cart upgrade?
or does the process say to uninstall and reinstall all shipping modules?

**Comment by scottcwilson** [comment]
Sorry you are asking whether or not to *add* tax basis - I misread this thinking you were removing tax class.  Just leave it like it is, don't add anything new; no one has complained about needing this yet.

**Comment by brittainmark** [comment]
For info. If it does get added you do need to change the zc_install to create the MODULE_SHIPPING_FREESHIPPER_TAX_BASIS
and I would suggest that it is added to the SQL update file as well.

Will leave as is.
