### ISSUE TITLE
Question: Should we remove PayPal  standard from1.5.8.

### ISSUE THREAD

**Issue by brittainmark** [zencart/zencart#5214]
We have posted many warnings saying don't use PayPal standard in the documentation. Why don't we take the opportunity to remove it from 1.5.8.

One less module to be upgraded to PHP 8.2.

**Comment by brittainmark** [comment]
I also see that Authorize is also end of life. Should that also be removed?

**Comment by scottcwilson** [comment]
Leave them for now (too many other things to do) but skip the PHP 8.2 upgrade on these.

**Comment by proseLA** [comment]
> I also see that Authorize is also end of life. Should that also be removed?

authorize has been saying the keyed pair is EOF for many years now.  unless they state a specific date, i would be very hesitant to remove it.

**Comment by brittainmark** [comment]
I'll look at authorize then.
