### ISSUE TITLE
possible error in search query

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5238]
Three times now, someone has tried an sql injection in the search, here's the complete url.

index.php?main_page=search_result&keyword=LP0060BK%27nvOpzp%3b+AND+1%3d1+OR+(%3c%27%22%3eiKO))%2c%26&inc_subcat=0&search_in_description=0&sort=20a&language=en

On ZC158 vanilla it returns no results, no error, as expected.
My site has a notifier manipulating the from and where string, and it dies with an sql error.

While investigating the differences between the queries, I find that the **original** query is unbalanced with the brackets around all the clauses and online SQL checkers report it as invalid.
The SELECT string has one extra bracket  and the WHERE several.
Perhaps someone more sql-experienced could review it.

### $select_str (string):
SELECT DISTINCT p.products_image, m.manufacturers_name, p.products_model, p.products_quantity ,  p.products_sort_order, m.manufacturers_id, p.products_id, pd.products_name,
      p.products_price, p.products_tax_class_id, p.products_price_sorter,
      p.products_qty_box_status, p.master_categories_id, p.product_is_call , p.products_status , IF (pd.products_name LIKE '%lp0060bk\'nvopzp;%' and pd.products_name LIKE '%1=1%' or  ( pd.products_name LIKE '%\'\"iko)),&%', 1, 0) AS in_name 

### $from_str (string):
FROM (products p
             LEFT JOIN manufacturers m
             USING(manufacturers_id), products_description pd, categories c, products_to_categories p2c ) LEFT JOIN meta_tags_products_description mtpd
            ON (mtpd.products_id= p2c.products_id AND mtpd.language_id = 1)

### $where_str (string):
 WHERE (p.products_status = 1
               AND p.products_id = pd.products_id
               AND pd.language_id = 1
               AND p.products_id = p2c.products_id
               AND p2c.categories_id = c.categories_id  AND ( (  pd.products_name LIKE '%lp0060bk\'nvopzp;%' OR  p.products_model LIKE '%lp0060bk\'nvopzp;%' OR  m.manufacturers_name LIKE '%lp0060bk\'nvopzp;%' OR  mtpd.metatags_keywords LIKE '%lp0060bk\'nvopzp;%' OR  mtpd.metatags_description LIKE '%lp0060bk\'nvopzp;%')  AND  (  pd.products_name LIKE '%1=1%' OR  p.products_model LIKE '%1=1%' OR  m.manufacturers_name LIKE '%1=1%' OR  mtpd.metatags_keywords LIKE '%1=1%' OR  mtpd.metatags_description LIKE '%1=1%')  OR  (  pd.products_name LIKE '%\'\"iko)),&%' OR  p.products_model LIKE '%\'\"iko)),&%' OR  m.manufacturers_name LIKE '%\'\"iko)),&%' OR  mtpd.metatags_keywords LIKE '%\'\"iko)),&%' OR  mtpd.metatags_description LIKE '%\'\"iko)),&%')  ))

### $order_str (string):
 order by p.products_sort_order, pd.products_name

### $listing_sql (string):
SELECT DISTINCT p.products_image, m.manufacturers_name, p.products_model, p.products_quantity ,  p.products_sort_order, m.manufacturers_id, p.products_id, pd.products_name,
      p.products_price, p.products_tax_class_id, p.products_price_sorter,
      p.products_qty_box_status, p.master_categories_id, p.product_is_call , p.products_status , IF (pd.products_name LIKE '%lp0060bk\'nvopzp;%' and pd.products_name LIKE '%1=1%' or  ( pd.products_name LIKE '%\'\"iko)),&%', 1, 0) AS in_name FROM (products p
             LEFT JOIN manufacturers m
             USING(manufacturers_id), products_description pd, categories c, products_to_categories p2c ) LEFT JOIN meta_tags_products_description mtpd
            ON (mtpd.products_id= p2c.products_id AND mtpd.language_id = 1) WHERE (p.products_status = 1
               AND p.products_id = pd.products_id
               AND pd.language_id = 1
               AND p.products_id = p2c.products_id
               AND p2c.categories_id = c.categories_id  AND ( (  pd.products_name LIKE '%lp0060bk\'nvopzp;%' OR  p.products_model LIKE '%lp0060bk\'nvopzp;%' OR  m.manufacturers_name LIKE '%lp0060bk\'nvopzp;%' OR  mtpd.metatags_keywords LIKE '%lp0060bk\'nvopzp;%' OR  mtpd.metatags_description LIKE '%lp0060bk\'nvopzp;%')  AND  (  pd.products_name LIKE '%1=1%' OR  p.products_model LIKE '%1=1%' OR  m.manufacturers_name LIKE '%1=1%' OR  mtpd.metatags_keywords LIKE '%1=1%' OR  mtpd.metatags_description LIKE '%1=1%')  OR  (  pd.products_name LIKE '%\'\"iko)),&%' OR  p.products_model LIKE '%\'\"iko)),&%' OR  m.manufacturers_name LIKE '%\'\"iko)),&%' OR  mtpd.metatags_keywords LIKE '%\'\"iko)),&%' OR  mtpd.metatags_description LIKE '%\'\"iko)),&%')  )) order by p.products_sort_order, pd.products_name

and for academic interest, 

## Notifier-manipulated version
$select_str (string):
SELECT DISTINCT p.products_image, m.manufacturers_name, p.products_model, p.products_quantity ,  p.products_sort_order, m.manufacturers_id, p.products_id, pd.products_name,
      p.products_price, p.products_tax_class_id, p.products_price_sorter,
      p.products_qty_box_status, p.master_categories_id, p.product_is_call , p.products_status , IF (pd.products_name LIKE '%lp0060bk\'nvopzp;%' and pd.products_name LIKE '%1=1%' or  ( pd.products_name LIKE '%\'\"iko)),&%', 1, 0) AS in_name 

### $from_str (string):
FROM (products p
             LEFT JOIN manufacturers m
             USING(manufacturers_id), products_description pd, categories c, products_to_categories p2c ) LEFT JOIN meta_tags_products_description mtpd
            ON (mtpd.products_id= p2c.products_id AND mtpd.language_id = 1) LEFT JOIN products_options_stock posm ON posm.products_id = p2c.products_id

### $where_str (string):
 WHERE (p.products_status = 1
               AND p.products_id = pd.products_id
               AND pd.language_id = 1
               AND p.products_id = p2c.products_id
               AND p2c.categories_id = c.categories_id  AND ((posm.pos_model != '' AND ( posm.pos_model LIKE '%lp0060bk\'nvopzp;%'  and  posm.pos_model LIKE '%1=1%'  or  (  posm.pos_model LIKE '%\'\"iko)),&%' )) OR (  pd.products_name LIKE '%lp0060bk\'nvopzp;%' OR  p.products_model LIKE '%lp0060bk\'nvopzp;%' OR  m.manufacturers_name LIKE '%lp0060bk\'nvopzp;%' OR  mtpd.metatags_keywords LIKE '%lp0060bk\'nvopzp;%' OR  mtpd.metatags_description LIKE '%lp0060bk\'nvopzp;%')  AND  (  pd.products_name LIKE '%1=1%' OR  p.products_model LIKE '%1=1%' OR  m.manufacturers_name LIKE '%1=1%' OR  mtpd.metatags_keywords LIKE '%1=1%' OR  mtpd.metatags_description LIKE '%1=1%')  OR  (  pd.products_name LIKE '%\'\"iko)),&%' OR  p.products_model LIKE '%\'\"iko)),&%' OR  m.manufacturers_name LIKE '%\'\"iko)),&%' OR  mtpd.metatags_keywords LIKE '%\'\"iko)),&%' OR  mtpd.metatags_description LIKE '%\'\"iko)),&%')  ))

### $order_str (string):
 order by p.products_sort_order, pd.products_name

### $listing_sql (string):
SELECT DISTINCT p.products_image, m.manufacturers_name, p.products_model, p.products_quantity ,  p.products_sort_order, m.manufacturers_id, p.products_id, pd.products_name,
      p.products_price, p.products_tax_class_id, p.products_price_sorter,
      p.products_qty_box_status, p.master_categories_id, p.product_is_call , p.products_status , IF (pd.products_name LIKE '%lp0060bk\'nvopzp;%' and pd.products_name LIKE '%1=1%' or  ( pd.products_name LIKE '%\'\"iko)),&%', 1, 0) AS in_name FROM (products p
             LEFT JOIN manufacturers m
             USING(manufacturers_id), products_description pd, categories c, products_to_categories p2c ) LEFT JOIN meta_tags_products_description mtpd
            ON (mtpd.products_id= p2c.products_id AND mtpd.language_id = 1) LEFT JOIN products_options_stock posm ON posm.products_id = p2c.products_id WHERE (p.products_status = 1
               AND p.products_id = pd.products_id
               AND pd.language_id = 1
               AND p.products_id = p2c.products_id
               AND p2c.categories_id = c.categories_id  AND ((posm.pos_model != '' AND ( posm.pos_model LIKE '%lp0060bk\'nvopzp;%'  and  posm.pos_model LIKE '%1=1%'  or  (  posm.pos_model LIKE '%\'\"iko)),&%' )) OR (  pd.products_name LIKE '%lp0060bk\'nvopzp;%' OR  p.products_model LIKE '%lp0060bk\'nvopzp;%' OR  m.manufacturers_name LIKE '%lp0060bk\'nvopzp;%' OR  mtpd.metatags_keywords LIKE '%lp0060bk\'nvopzp;%' OR  mtpd.metatags_description LIKE '%lp0060bk\'nvopzp;%')  AND  (  pd.products_name LIKE '%1=1%' OR  p.products_model LIKE '%1=1%' OR  m.manufacturers_name LIKE '%1=1%' OR  mtpd.metatags_keywords LIKE '%1=1%' OR  mtpd.metatags_description LIKE '%1=1%')  OR  (  pd.products_name LIKE '%\'\"iko)),&%' OR  p.products_model LIKE '%\'\"iko)),&%' OR  m.manufacturers_name LIKE '%\'\"iko)),&%' OR  mtpd.metatags_keywords LIKE '%\'\"iko)),&%' OR  mtpd.metatags_description LIKE '%\'\"iko)),&%')  )) order by p.products_sort_order, pd.products_name

**Comment by scottcwilson** [comment]
Which notifier, called from which file and line number?  Is your plugin public?

**Comment by torvista** [comment]
The point I'm making is that the original query looks and validates as incorrect, although it gets parsed.
The additions by notifier is not the issue here, since it is an external plugin, it just seems to have highlighted it.

The notifiers are  'NOTIFY_SEARCH_FROM_STRING',  'NOTIFY_SEARCH_WHERE_STRING' in includes\modules\pages\search_result\header_php.php

and the Products' Options' Stock Manager plugin is not public: https://vinosdefrutastropicales.com/index.php?main_page=product_info&products_id=46

**Comment by zcwilt** [comment]
I'm a bit confused.

Where you show the select_str/from_str/where_str/order_str/listing_sql 
those queries all seem to be based off the hack query as they contain '%lp0060bk'nvopzp;%'
and not a plain vanilla search

**Comment by zcwilt** [comment]
if this is the case then I'm not bothered that it tries to parse an unbalanced query (from a hack attempt) and does not return an error.
In fact that is exactly what we want.

**Comment by zcwilt** [comment]
If you are saying that the original code (and using a simple search) is returning unbalanced SQL, then that is a different matter

**Comment by torvista** [comment]
With a normal text search the queries (both core and notifier-ed) **are** valid/balanced.

So if the query with the hack string gets corrupted with the extra code, does that not mean the string is not being sanitized 100%?

eg.
**Vanilla**

$select_str (string):
SELECT DISTINCT p.products_image, m.manufacturers_name, p.products_model, p.products_quantity ,  p.products_sort_order, m.manufacturers_id, p.products_id, pd.products_name,
      p.products_price, p.products_tax_class_id, p.products_price_sorter,
      p.products_qty_box_status, p.master_categories_id, p.product_is_call , p.products_status , 
IF (pd.products_name LIKE '%lp0060bk%', 1, 0) AS in_name 

**Hackstring**

$select_str (string):
SELECT DISTINCT p.products_image, m.manufacturers_name, p.products_model, p.products_quantity ,  p.products_sort_order, m.manufacturers_id, p.products_id, pd.products_name,
      p.products_price, p.products_tax_class_id, p.products_price_sorter,
      p.products_qty_box_status, p.master_categories_id, p.product_is_call , p.products_status , 
IF (pd.products_name LIKE '%lp0060bk\'nvopzp;%' and pd.products_name LIKE '%1=1%' or  ( pd.products_name LIKE '%\'\"iko)),&%', 1, 0) AS in_name

**Comment by scottcwilson** [comment]
The string is being sanitized, it's just not a well formed search string.   There's nothing to worry about here.

**Comment by torvista** [comment]
While it may not be a security risk, it causes an error when the plugin uses it in the modified where_string.
So, not sure where the problem/solution lies.

**Comment by proseLA** [comment]
> While it may not be a security risk, it causes an error when the plugin uses it in the modified where_string. So, not sure where the problem/solution lies.

uh....  fix the plugin...

i have tested your URL on my dev machine.  no error log created; the page returns:

 There is no product that matches the search criteria.

not sure what you expect from the base zc code.

**Comment by torvista** [comment]
Needs further investigation.

**Comment by torvista** [comment]
After going dizzy reviewing the code, just for no-one's interest here's what I concluded.
The bad search was actually
LP0060BK'nvOpzp; AND 1=1 OR ('"iKO)),&
which is three strings separated by AND and OR.
ZC code parses this and throws away the double quotes and everything after it, and also ignores that opening bracket so the OR clause becomes only (with the single quote escaped).
LIKE '%\'%'

So, all valid. 
Meanwhile the plugin was not ignoring the opening bracket making the query unbalanced/invalid.
