### ISSUE TITLE
admin ezpages edit icon action is different to  zc157

### ISSUE THREAD

**Issue by OldNGreyBMR** [zencart/zencart#5241]
**Describe the bug**
In zc157 admin ezpages click an edit icon not on the currently selected line ie no right arrow for information, and the edit screen is opened for that ezpage id 
In zc158 admin ezpages the same action does not open the edit screen for that ezpage id 

**Version**
Zen Cart version:  158
PHP version:  7.4, 8.0, 8.1, 8.2
MySQL version: 10.4.17-MariaDB
Plugins that may be related: 
What older/newer versions were also tested? zc157d

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. in admin | ezpages
2. Click on the edit icon for any row not the current row
3. EZ-Pages edit page is not displayed

**Expected behavior**
Clicking on the edit icon for any row that is not the selected row should have the same effect as clicking on the blue Edit button in the  right hand column, for the selected row

**Devices **
 - Operating System:  Windows 10 
 - Browser: Chrome 105.0.5195.127; Microsoft Edge 05.0.1343.42

**Comment by scottcwilson** [comment]
Thanks for reporting.
