### ISSUE TITLE
Admin: Copy Categories

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5267]
I've added this next to the Category-Products listing Move Category action.
It copies the category and subcategories structure only (to another parent category or duplicates it in the current one).
It does not copy the contained products.
Can I PR this? Adds one function,

**Comment by scottcwilson** [comment]
I know some guy asked for this on the forum but I'm not convinced that it's generally useful.

**Comment by scottcwilson** [comment]
Can you make this a plugin?

**Comment by torvista** [comment]
It would be more useful if it also copied products at the same time, and I may do that at some point/that's more work I don't have time for now.
I was thinking this is a base start, and it's not as if there is a lack of space on the category action buttons and does not complicate the code more or mess up any gui. It seems a natural expansion of the current actions. There is copy for products, so why not for categories.
It's not a major change and is something to put on the new features list, so as I've said before why not add stuff if there is no real reason **not** to, rather than the reverse. Another repository/plugin...yawn.

**Comment by scottcwilson** [comment]
> why not add stuff if there is no real reason not to ... 

Every change we make is that much more code that has to be maintained and debugged.  We want to keep the core small so that the functions it provides are needed by almost everyone.

https://docs.zen-cart.com/user/plugins/why_plugins/

**Comment by torvista** [comment]
A plugin means adding a notifier for the extra button and making it public-ready, and suddenly I've spent more time getting it ready than it took to code it, all for a couple of dozen lines of code. I don't have the time to code it in the first place so the altruistic stuff gets left behind these days. That's why it's quicker to just stuff it in the core since it's already ready for that.

**Comment by torvista** [comment]
Since implementing this, we've been using and liking it **a lot**.

![2022-10-25 16_25_04-Admin Category Product Listing](https://user-images.githubusercontent.com/4391026/197800506-5be112d6-d589-4ab6-953f-88f7dafa5863.gif)


As we say up North, "what's not to like?"

**Comment by scottcwilson** [comment]
You can put out a plugin that's not "drop in" - like I said, I don't want to add things that are only desirable to a small number of people.

**Comment by torvista** [comment]
https://github.com/torvista/Zen_Cart-Copy_Categories
