### ISSUE TITLE
zc_install - db install errors don't halt installer

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#528]
In `zc_install`, when db errors occur during db setup (while it's executing various SQL scripts), the error message pops quickly and then proceeds to next page suddenly.

**Comment by ebcode** [comment]
I'd like to tackle this one, but I need a little more info.  What should the behavior be instead?  Should we roll back all database changes and display the error with a "please fix this before proceeding" message?

Also, is there a preferred way to reproduce?

**Comment by drbyte** [comment]
To reproduce during a "fresh install", introduce a SQL error in one of the statements in `zc_install/sql/install/mysql_zencart.sql` perhaps like mangling the `CREATE TABLE 'admin'` syntax.

Another case to test would be adding a new `mysql_something.sql` in `zc_install/sql/plugins/`in which you place SQL with a syntax error.  All the added files named `mysql_*.sql` in that folder will be run during a fresh install, after the main SQL files are processed.

You could do similarly with putting a syntax error in the upgrade SQL for 160 (see the upgrades folder).

Rolling back will be very complicated particularly when considering that handling an upgrade site is a very different experience than doing a fresh install. 

Before even toying with the idea of any rollback I'd start by first capturing the error, logging it (which it might already be doing), and halting the install with an error message on-screen telling them to check the `/logs/zcInstall-DEBUG.log` file for actual error details. 

And probably include something in the error message saying that they need to start over.  (For fresh installs starting over is actually generally as simple as just trying again.  But for upgrades it means they need to manually rollback their database... ie: by restoring it from backup or re-importing its contents.)

**Comment by ebcode** [comment]
Ok.  I've got the install scripts dying when there's a SQL error, and displaying a message to the user in the ajax progress window.

I'm not very familiar with making a pull request on github, though, so I'll have to figure that out first.  Do we discuss the changes to the code here in this thread, or would you rather just look at the code itself?

**Comment by drbyte** [comment]
The Pull Request ("PR") looks good. 

Usually any code discussion happens within the PR comments, to keep it in context.

**Comment by ebcode** [comment]
Ok cool.  It's all pretty straight-forward, so I don't have any other comments atm.
