### ISSUE TITLE
use of NOTIFY_ADMIN_PROD_LISTING_DEFAULT_ACTION

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5280]
I'm trying to add copy category code to the category_product_listing page.. I've added a new notifier for the new icon observer, ok.

Now, the new action "copy_category" requires handling, so I need to use a notifier-observer to replace a hard-coded "case copy_category" in the switch.

This is the ending section of the switch-case that handles the actions.
https://github.com/zencart/zencart/blob/c5cc24e860002674d94981c979b63ba4103df30b/admin/category_product_listing.php#L298-L313

I don't see how to use this notifier to handle a new case/break out to let subsequent code handle $action="copy_category" or rather I don't see the point of this notifier if the action is always deleted subsequently.
Am I supposed to set some new global variable in the observer for the additional new code for the info-box to use?

**Comment by torvista** [comment]
And if the $action is not set/used,  by for example using another POST set in the observer, the formatting breaks with the new infobox:
`<div<?php echo (empty($action)) ? '' : ' class="col-xs-12 col-sm-12 col-md-9 col-lg-9 configurationColumnLeft"'; ?>>`
Making a "clean" plugin is more trouble than it's worth.

**Comment by mc12345678** [comment]
Might suggest adding information into the notifier to allow control of clearing the action like below:

````diff
    case 'setflag_categories':
    case 'delete_category':
    case 'move_category':
    case 'delete_product':
    case 'move_product':
    case 'copy_product':
    case 'attribute_features':
    case 'attribute_features_copy_to_product':
    case 'attribute_features_copy_to_category':
      break;
    default:
+      $clearAction = true;
+      $zco_notifier->notify('NOTIFY_ADMIN_PROD_LISTING_DEFAULT_ACTION', null, $clearAction);
+      if ($clearAction == false) {
+        $action = $_GET['action'] = '';
+      }
+      unset($clearAction);
-      $zco_notifier->notify('NOTIFY_ADMIN_PROD_LISTING_DEFAULT_ACTION');
-      $action = $_GET['action'] = '';
      break;
  }
}
````

**Comment by torvista** [comment]
Thanks for commenting, apologies for not replying sooner.
I'll revisit this asap.
