### ISSUE TITLE
ZC158 Bug: Admin, copy product error when more than one page results

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5282]
Maximum Categories Products Display List default is 10.
When the results are more than this limit/there is more than one page of results, Copy Product causes an error.
E.g. Big Linked has 24 products.

![Clipboard02](https://user-images.githubusercontent.com/4391026/194088516-4ef3406e-fa15-4854-83d2-c3d782a92510.gif)

> Request URI: /zencart/admin/index.php?cmd=category_product_listing&cPath=22&product_type=1&pID=34&action=copy_product&page=1,
> --> PHP Warning: Undefined variable $pInfo in D:\GitHub\zencart\admin\includes\modules\copy_product.php on line 22.
> Request URI: /zencart/admin/index.php?cmd=category_product_listing&cPath=22&product_type=1&pID=34&action=copy_product&page=1
> --> PHP Warning: Undefined variable $pID in D:\GitHub\zencart\admin\includes\modules\copy_product.php on line 25.

Increase the results limit to 24/a single page of results and it works.
![Clipboard03](https://user-images.githubusercontent.com/4391026/194089294-14a71c13-0a74-4c0d-a891-2ddf4036517f.gif)

**Comment by scottcwilson** [comment]
Same issue with move.  (Probably other things too.) 
Requires Admin > Configuration > Logging > Report All Errors = true.

My Repro steps:
- In Admin > Configuration > Maximum Values, ensure Maximum Categories Products Display List is 10.
- Go to Admin > Catalog > Categories/Products, click on Big Linked category
- On first item (Bug's Life), click the "C" button to copy. 
- Observe the debug log.

Fix coming shortly.

**Comment by scottcwilson** [comment]
Note this issue is unique to 1.5.8; worked properly in 1.5.7d.
