### ISSUE TITLE
zc158 bug: paypaywpp cannot access protected property shoppingCart::$content_type 

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5287]
Error: Cannot access protected property shoppingCart::$content_type in ...
/includes/modules/payment/paypalwpp.php:1841
https://github.com/zencart/zencart/blob/d1fb975c8e9ab225b76b48cc24d8bebbf4b612ec/includes/modules/payment/paypalwpp.php#L1841

**Comment by brittainmark** [comment]
@torvista change line to 
` if ($_SESSION['cart']->get_content_type('true') > 0 || in_array($_SESSION['cart']->get_content_type(), array('mixed', 'virtual'))) $this->new_acct_notify = 'Yes'; `
i.e.
`$_SESSION['cart']->content_type` to` $_SESSION['cart']->get_content_type()`
do you want me to submit to your #5060 branch?
