### ISSUE TITLE
Potential fatal error: TEXT_TOP in function zen_get_category_name,  only defined in admin

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5304]
As included here:
https://github.com/zencart/zencart/pull/5266

It is not defined in shopfront so may cause a fatal error when called shopfront.
However, while TEXT_TOP (which is "Top") may be a valid return in the admin, it may not be appropriate for a shopfront use of this function.
Checking my shop, I find several instances of plugins using this function, which led to my fatal error.
But in a short review of vanilla code I don't see where it may fail (when category >1). Still, it is a hole.
For the moment I've just left it as an empty string for shopfront, (defined in the function), but needs more thought.

**Comment by scottcwilson** [comment]
Would you please PR? I think the current admin definition is a reasonable default.

**Comment by torvista** [comment]
Additionally, when creating a new category:
![2022-10-10 12_38_16-Admin Categories — Mozilla Firefox](https://user-images.githubusercontent.com/4391026/194854718-6d22bcc6-5333-4099-9741-64327e9eebb2.gif)

Shortly I'll submit a PR with a switch-case for handling this, in case more cases of unknown knowns surface...

**Comment by torvista** [comment]
closed in https://github.com/zencart/zencart/pull/5306
