### ISSUE TITLE
admin, attributes controller, additional actions debugs

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5335]
ZC158
php 8.2RC4
Choose graphics cards for example

Copy Options to Another Product

> --> PHP Warning: Undefined array key "copy_attributes" in D:\GitHub\zencart\admin\attributes_controller.php on line 780.

Copy Options to Whole Category

> --> PHP Warning: Undefined array key "products_update_id" in D:\GitHub\zencart\admin\attributes_controller.php on line 812.
> --> PHP Warning: Undefined array key "copy_attributes" in D:\GitHub\zencart\admin\attributes_controller.php on line 813.

**Comment by scottcwilson** [comment]
Can you PR?

**Comment by scottcwilson** [comment]
Can this be closed now?  Does #5450 suffice?

**Comment by scottcwilson** [comment]
Checking back - can this be closed?
