### ISSUE TITLE
Undefined variable $ezInfo  on entering admin>tools>EZ-pages 

### ISSUE THREAD

**Issue by brittainmark** [zencart/zencart#5352]
**Describe the bug**
Warning log produced on entering admin>tools>EZ-pages 

**Version**
Zen Cart version: 1.5.8
PHP version: 8.1

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Go to Admin>Tools>EZ-pages
2. if no pages set up, a warning log is produced.

**Expected behavior**
no warning log

**Debug/Error Logs**
```
[27-Oct-2022 16:24:10 Europe/London] Request URI: /Test158/ADMIN/index.php?cmd=ezpages, IP address: 127.0.0.1
#1  require(/home/lotus/public_html/innerlightcrystals/Test158/ADMIN/ezpages.php) called at [/home/lotus/public_html/innerlightcrystals/Test158/ADMIN/index.php:11]
--> PHP Warning: Undefined variable $ezInfo in /home/lotus/public_html/innerlightcrystals/Test158/ADMIN/ezpages.php on line 761.
```

**Comment by brittainmark** [comment]
removed mine sorry did not see that one

**Comment by scottcwilson** [comment]
We have a big pile of fixes for little issues like this - should be merged soon.
