### ISSUE TITLE
Admin, Option Values Sorter does not take language into account

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5355]
php:8.2.0RC5 /10.6.5-MariaDB
Multi-language store.

Admin, Catalog, Option Values Sorter: Choose a product to update the sort order.
The sort order is updated only for one language (the last installed), as the sql does not factor in the language.
https://github.com/zencart/zencart/blob/8972fc0fceb0f1d8ffd2828339063e3292bbc1d5/admin/option_values.php#L30-L32
Possibly one may expect this sql to update all instances, but it doesn't, in this environment at least.
I've done a fix to allow update of current language or all languages, to PR presently.

**Comment by scottcwilson** [comment]
I'd rather it do all languages and not have a switch to choose current vs all.

**Comment by torvista** [comment]
I have the option to update all as the default. But no doubt there are cases when someone wants something different, and it's no extra overhead, I've already done it.
