### ISSUE TITLE
admin_html_head.php: Enable plugins to provide /includes/css/something.php files

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#5365]
Many times, a plugin has configuration settings to enable the admin to further customize the plugin's look and feel.  There's currently no way for a plugin to inject its 'configured' CSS when using the now-current `admin_html_head.php` as it only loads `.css` files from the subject admin sub-directory.

**Comment by torvista** [comment]
The javascript of the plugin could inject the css link into the head. That's what I do.

**Comment by lat9** [comment]
Have the 'rules' changed?  I _thought_ that all `<style>` tags needed to be prior to the first `<script>` one.

**Comment by torvista** [comment]
I use this
```
    //adds css in head, below last css link
   $('head link[rel="stylesheet"]').last().after('<link rel="stylesheet" href="includes/whatever.css" media="screen">');
```

**Comment by lat9** [comment]
That adds a 'pure' `.css` file.  I'm talking about `<style>` tags that inject configuration-specific values, so they need to be an `admin/includes/css/something.php` file to do their processing.

**Comment by scottcwilson** [comment]
Love it.  Any newcomers who'd like to PR this?

**Comment by scottcwilson** [comment]
Can we just add a notifier to satisfy this request?  Or is more work required?
