### ISSUE TITLE
1.5.8 init_sanitize treats integer values in $_GET as invalid, breaks Ceon URI Mapping addon

### ISSUE THREAD

**Issue by neekfenwick** [zencart/zencart#5366]
**Describe the bug**
includes/init_includes/init_sanitize.php uses `ctype_digit($_GET[$key])` to check if a GET param is 'valid', and if not it blanks it.  This breaks the current version of Ceon URI Mapping addon, which sets the `$_GET['id']` parameter to an integer value, not a string value.

**Version**
Zen Cart version: 1.5.8
PHP version: 8.1
Plugins that may be related: Ceon URI Mapping 5.1.0

**To Reproduce**
1. Set up vanilla zencart 1.5.8 with an ez page and URI Mapping addon installed with URI mapping for the ez page.
2. Try to visit the ez page's URI

**Expected behavior**
We should get the ez page content.

**Actual behavior**
We get redirected to the home page by the includes/modules/page/header_php.php which finds that $_GET['id'] is not set to a value.

**Unstated major premise**
$_GET parameters are assumed by init_sanitise.php to be string datatypes, and I am not sure if this is a valid hypothesis or not.  I see the line of code coming from @lat9  in https://github.com/zencart/zencart/pull/4954/commits/f7058733872ae6506bef7d9bed9eb3e460775e64 .  A couple of questions that come to mind:
- was this a 'best practise' way of validating $_GET params, or just something that seemed a good idea at the time?
- are there any other addons that modify query parameters by putting integer values into them? (since this code is new for zencart 1.5.8 which is very new this may just be the first time this problem is reported)
- if not simply by `ctype_digit()`, what other way should we validate the data? Is it sensible to gettype($_GET[$key]) and validate according to its type?
- if `ctype_digit()` is correct, should Ceon URI Mapping change instead to only write string values into $_GET?

**Comment by neekfenwick** [comment]
Just to mention, as @mc12345678 pointed out, the products_id used in ZC is generally a mixed datatype as it sometimes has attributes hashed into it, and I see init_sanitize.php does more advanced matching on it using a regex and /\d/, which I find does test positively for an integer PHP datatype as well as a string datatype, which I was a little surprised by.  So, Ceon putting an integer into $_GET['products_id'] passes that test because of the test using preg_match.

The 'id' param failing the test by `ctype_digit` raises the question, must the 'id' param always be a string representation of an integer, or may it be an integer?  Plus the question of the other fields being tested, from looking down the list most of them seem integer values, a few I don't know from sight such as 'disp_order', 'cID', 'categories_id' (is this underscore separated?), 'goto', 'markflow', 'inc_subcat'...

**Comment by torvista** [comment]
related
https://github.com/zencart/zencart/issues/5091

**Comment by mc12345678** [comment]
`$_GET` parameters are modified by multiple plugins, though where in the process they are modified may be different. They may be set to a non-string datatype after the loading of init_sanitize and therefore this issue may not yet be evident. 

That said, the question becomes why do other places in Zen Cart code support type casting `$_GET` or `$_POST` variables to values that are not strings? 
One such `$_GET` example randomly found is at: 
https://github.com/zencart/zencart/blob/8972fc0fceb0f1d8ffd2828339063e3292bbc1d5/includes/modules/pages/search_result/header_php.php#L274
And for `$_POST` the following was found: 
https://github.com/zencart/zencart/blob/8972fc0fceb0f1d8ffd2828339063e3292bbc1d5/includes/modules/shipping_estimator.php#L19

**Comment by lat9** [comment]
There you go; casting those wonky $_GET variables to strings before using (er) string-based comparisons.

**Comment by lat9** [comment]
> `$_GET` parameters are modified by multiple plugins, though where in the process they are modified may be different. They may be set to a non-string datatype after the loading of init_sanitize and therefore this issue may not yet be evident.
> 
> That said, the question becomes why do other places in Zen Cart code support type casting `$_GET` or `$_POST` variables to values that are not strings? One such `$_GET` example randomly found is at:
> 
> https://github.com/zencart/zencart/blob/8972fc0fceb0f1d8ffd2828339063e3292bbc1d5/includes/modules/pages/search_result/header_php.php#L274
> 
> And for `$_POST` the following was found:
> 
> https://github.com/zencart/zencart/blob/8972fc0fceb0f1d8ffd2828339063e3292bbc1d5/includes/modules/shipping_estimator.php#L19

I'm guessing that those modules haven't gone until a close inspection after the 'sanitization' was brought into effect.

**Comment by neekfenwick** [comment]
> That said, the question becomes why do other places in Zen Cart code support type casting `$_GET` or `$_POST` variables to values that are not strings? One such `$_GET` example randomly found is at:

Seeing those lines of code, I'd say it's likely a hangover from:
- when you get a string from somewhere, like a query param, that you know ought to be an int and you want to do lazy sanitation such that malformed data would be chopped off, e.g. mypage.php?id=nasty%20sql%20statement and in the code `$id = (int)$_GET['id']`
- when you get an int from a database result set that always returns strings e.g. `$id = (int)$rs->fields['id'];` or maybe you copy code that did that but now you get the data from `$_POST` but keep the cast.

A regex that pulls up a few other examples across zencart (mostly in admin): \$_(GET|POST)\[['"][\S_]*['"]\]\s+=\s+\(int\)

No other bugs jump out, though. In my mind $_GET, $_POST etc should only ever really hold string values, but this doesn't really warrant further effort, let's focus on actual bugs :)

**Comment by lat9** [comment]
See also [this](https://github.com/zencart/zencart/discussions/4824) GitHub discussion that circles this discussion.

**Comment by lat9** [comment]
> There you go; casting those wonky $_GET variables to strings before using (er) string-based comparisons.

@neekfenwick, does your thumbs-up indicate that the PR I submitted yesterday corrected the integration issue with **_Ceon URI Mapping_**?

**Comment by neekfenwick** [comment]
> > There you go; casting those wonky $_GET variables to strings before using (er) string-based comparisons.
> 
> @neekfenwick, does your thumbs-up indicate that the PR I submitted yesterday corrected the integration issue with **_Ceon URI Mapping_**?

Yes it does fix the issue, I copied the raw init_sanitize.php file from your PR and dropped it into my 1.5.8 store and EZ Pages then worked with Ceon URI Mapping.  I wasn't sure what more to do in terms of feedback, code review etc.

**Comment by scottcwilson** [comment]
@neekfenwick thank you for your thorough documentation of this issue, and welcome to the fun! :)

**Comment by neekfenwick** [comment]
> @neekfenwick thank you for your thorough documentation of this issue, and welcome to the fun! :)

I hope I'm helping :P I've been using zencart since 1.3.x. In upgrading my shop to 1.5.8 I'm running into a few rounding errors causing off-by-a-penny that have plagued us years ago and caused me to modify the zen_add_tax and shopping cart functions relating to rounding attribute pricing, if I can reproduce a sensible case maybe I'll finally file an Issue and see if anyone else agrees :)

**Comment by torvista** [comment]
> rounding attribute pricing

https://github.com/zencart/zencart/issues/4138
