### ISSUE TITLE
Slow Search Results >15s

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5369]
I have Instant Search is use, which is, pretty much, instant.
But using the core search button is way too slow, more than 15s for a result. Product table is 7600 entries.

The bottleneck is not the search, but here:
https://github.com/zencart/zencart/blob/8972fc0fceb0f1d8ffd2828339063e3292bbc1d5/includes/classes/split_page_results.php#L105
I put some execution times in various points to narrow down where the bottleneck was occurring, starting from here
https://github.com/zencart/zencart/blob/8972fc0fceb0f1d8ffd2828339063e3292bbc1d5/includes/modules/pages/search_result/header_php.php#L446
as I was assuming it was a notifier causing the problem.

The times are microtime, seconds *10000 to get some real numbers, the line numbers are off due to debugging code.

Vanilla ZC158 (Product table is 180 entries):
split_page_results 110: pre db execute, execution time: 14.529228210449
split_page_results 116: post db execute, execution time: 29.480457305908

Vanilla ZC158 files with my db (Product table is 7600 entries)
split_page_results 110: pre db execute, execution time: 20.229816436768
split_page_results 116: post db execute, execution time: 11840.398311615

Dev copy of my site (Product table is 7600 entries), plugins that modify the query, switched off.
split_page_results 128: pre db execute, execution time: 25.331974029541
split_page_results 134: post db execute, execution time: 11327.300071716

(Repeating the query does not have the delay, due the caching I assume.)

The query is identical in each case, using a non-existent search term:

> select
>   count(distinct p.products_id) as total
> FROM
>   (
>     products p
>     LEFT JOIN manufacturers m USING(manufacturers_id),
>     products_description pd,
>     categories c,
>     products_to_categories p2c
>   )
>   LEFT JOIN meta_tags_products_description mtpd ON (
>     mtpd.products_id = p2c.products_id
>     AND mtpd.language_id = 1
>   )
> WHERE
>   (
>     p.products_status = 1
>     AND p.products_id = pd.products_id
>     AND pd.language_id = 1
>     AND p.products_id = p2c.products_id
>     AND p2c.categories_id = c.categories_id
>     AND (
>       (
>         pd.products_name LIKE '%jansja%'
>         OR p.products_model LIKE '%jansja%'
>         OR m.manufacturers_name LIKE '%jansja%'
>         OR mtpd.metatags_keywords LIKE '%jansja%'
>         OR mtpd.metatags_description LIKE '%jansja%'
>       )
>     )
>   )
> 
Using EXPLAIN with the query on ZC vanilla
![image](https://user-images.githubusercontent.com/4391026/199309888-d6775b4f-3ba8-46b3-a389-a4d25774c193.png)

ZC vanilla files with imported db/production site
![image](https://user-images.githubusercontent.com/4391026/199310098-d344054a-9979-40f4-b6b2-533e6738c13a.png)

which will mean more to others than me, but I assume should be identical, structurally.

I'd appreciate someone checking a real site for similar problems, as mine is not useable.
Thanks.

**Comment by scottcwilson** [comment]
Have you turned off search in description?

**Comment by torvista** [comment]
Is that an option somewhere?

**Comment by torvista** [comment]
this is about a search from the search header not from the advanced search page

**Comment by scottcwilson** [comment]
> Is that an option somewhere?

Use these instructions: 

https://docs.zen-cart.com/user/search/disable_search_in_description/

**Comment by scottcwilson** [comment]
Also turn off 

Admin > Configuration > My Store > Include meta-tags in product search?

**Comment by torvista** [comment]
The delay is due to the p2c table in the query:
https://github.com/zencart/zencart/blob/8972fc0fceb0f1d8ffd2828339063e3292bbc1d5/includes/modules/pages/search_result/header_php.php#L259-L263

**Comment by lat9** [comment]
Using that suggested search for Google, [this](https://www.sisense.com/blog/use-subqueries-to-count-distinct-50x-faster/) posting looks like it might provide a foundation for a speed-up.

**Comment by scottcwilson** [comment]
I have some large datasets and would be happy to run tests.  Thanks for pushing on this- it could be a real win for big customers.

**Comment by proseLA** [comment]
i think the time is ripe to replace the whole class.  perhaps using a pager library that is well maintained elsewhere in the open source community. ie something like:

https://github.com/laminas/laminas-paginator

**Comment by torvista** [comment]
Refactoring the query will go into the latest volume of my series of TODO books, probably for my reincarnation, meanwhile perhaps some sql guru would like the challenge...

**Comment by scottcwilson** [comment]
LOL "series of TODO books."

**Comment by torvista** [comment]
Thanks, I hope to review this over the weekend..

**Comment by scottcwilson** [comment]
Would anyone be willing to PR this?  Thanks.
