### ISSUE TITLE
paypalwpp: debug for zone_id not set in function addAddressBookEntry

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5372]
For when a matching address is not found, uses function addAddressBookEntry:
if the country code does not return a state from table zones, $check_zone is false here and so zone_id never gets set in this clause:
https://github.com/zencart/zencart/blob/9910e3d1aa80466f9d59afb53ae494849a2bda8c/includes/modules/payment/paypalwpp.php#L2746-L2762

causing a debug when referenced here:https://github.com/zencart/zencart/blob/9910e3d1aa80466f9d59afb53ae494849a2bda8c/includes/modules/payment/paypalwpp.php#L2788

So, zone_id should be set to zero before that initial clause.

**Comment by scottcwilson** [comment]
Please PR
