### ISSUE TITLE
Should we get rid of XHTML artifacts

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#5374]
This forum post: 

https://www.zen-cart.com/showthread.php?229112-Validation-issues-with-Trailing-slash-on-void-elements

made me wonder if it was time to get rid of the trailing slash that we use in various places. 

SO seems to think yes:

https://stackoverflow.com/questions/3558119/are-non-void-self-closing-tags-valid-in-html5

Would you please investigate?

**Comment by dbltoe** [comment]
The short answer, yes.

Info: Trailing slash on void elements [has no effect](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-in-void-element-start-tags-do-not-mark-the-start-tags-as-self-closing) and [interacts badly with unquoted attribute values](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-directly-preceded-by-unquoted-attribute-values).

From line 237, column 3; to line 237, column 249

script>↩  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awes…vl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==" crossorigin="anonymous" />↩

**Comment by scottcwilson** [comment]
Would you like to submit a PR for release in 1.5.8a?

**Comment by dbltoe** [comment]
I'll see what I can get together.  Site problems.

**Comment by dbltoe** [comment]
92 files with one having 1,306 instances may take a while.....

**Comment by dbltoe** [comment]
Someone other than me needs to look at admin/includes/javascript/flot/excanvas.min.jsadmin/includes/javascript/flot/excanvas.min.js (8) and admin/includes/javascript/flot/jquery.flot.image.min.js (1)

I HATE to assume.

**Comment by scottcwilson** [comment]
I was thinking about just doing the one file I mentioned - `includes/functions/html_output.php`.  That should get the lion's share, no?  I definitely don't want you to change every `<br />` to `<br>` - that can be done as part of any fix in the file it's in.

**Comment by scottcwilson** [comment]
Our copy of flot is old; you can ignore that for now.

**Comment by dbltoe** [comment]
jquery.mmenu.min.all.js (18) and jquery.mmenu.oncavas.js (6)  in responsive_classic/jscript?

**Comment by dbltoe** [comment]
foundation.min.js (6) in zc_install/includes/template/foundation?

**Comment by scottcwilson** [comment]
zc_install isn't part of a live  runnning site, so don't worry about it.

**Comment by dbltoe** [comment]
With my system, it's easier just to do them all at once.

They're done.  Just let me know if there are any that need to be undone before the PR.

**Comment by scottcwilson** [comment]
No need to undo anything. I just hadn't intended to burden you with a monster PR.  I just wanted to get the high runners done.

**Comment by dbltoe** [comment]
Takes about twenty minutes to find and two to fix with UlttraFind and UltraEdit.  2,746 <br/>'s to <brr> in less than a minute.

When all else fails, cheat 😃

**Comment by dbltoe** [comment]
The thing I don't know how to do is squash the duplicate changes to a file into one change.  Should be 86 files but became 165

**Comment by dbltoe** [comment]
Did the commit to the web from desktop git but can't find where to do the PR.

**Comment by scottcwilson** [comment]
You added them  on to an existing PR which had other things in it, also had incorrect changes, and changes to images that were not needed.  

Not sure what your workflow is but would you please get your fork in sync with v158 and then just submit ONE pr with 5 or 10 changes so we can do this a bit at a time successfully?  If you submit a PR with 95 changes it's incredibly hard for me to process.

**Comment by scottcwilson** [comment]
This seems mostly done circa 1.5.8a.
