### ISSUE TITLE
inconsistent arrays for new/existing products: notify_admin_product_collect_info_extra_inputs

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5378]
Came across this in the forum by chance, 
https://www.zen-cart.com/showthread.php?229101-Minor-bug-in-notify_admin_product_collect_info_extra_inputs

and it appears to have not been documented yet.

For new products the product type is in $pInfo->product_type (singular)
For editing existing products it's in $pInfo->products_type

**Comment by scottcwilson** [comment]
Can you PR?

**Comment by torvista** [comment]
I don't think so, on initial review this is not trivial.

**Comment by scottcwilson** [comment]
Looks like Cindy is taking it.  Thank you!
