### ISSUE TITLE
Installed ckeditor is not html5 compliant

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#5385]
When one defines the main page, creates a category/product, or simply uses ckeditor to add or edit text in Zen Cart, a line break is saved as `<br/>`.

Even if the Source mode is used, a `<br> `entry is changed to `<br/>` by ckeditor when the item is saved.

https://stackoverflow.com/questions/41496028/how-to-use-br-instead-of-br-in-ckeditor

**Comment by scottcwilson** [comment]
Hopefully the CKEditor team will fix.
