### ISSUE TITLE
default_filter called twice?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5396]
While down the rabbit warren that is the sorting of the products listing, it appears that /includes/index_filters/default_filter.php
is called twice:
https://github.com/zencart/zencart/blob/938f86fe907415930475dd7aa1a8741741bb138e/includes/modules/pages/index/header_php.php#L125-L130
and
https://github.com/zencart/zencart/blob/938f86fe907415930475dd7aa1a8741741bb138e/includes/modules/pages/index/main_template_vars.php#L183-L186
since I get two instances of debugging echos.

I admit I don't understand the program flow here, but it does get parsed twice.

**Comment by scottcwilson** [comment]
It seems odd but it's needed.  I agree this is a wart, but it's how the system works and restructuring it would be a big job with minimal benefit.  Closing.
