### ISSUE TITLE
notifiers that need parameter values...

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#5402]
perhaps someone can enlighten me here.  i have tracked these notifiers down to the initial commit to github 11 years ago.  i am not sure how one could go about utilizing them in their current format.  if one wanted to manipulate any of the string values, please let me know how to do that.

barring an answer to that question, i would propose including the necessary string parameter in the 2nd parameter position.

https://github.com/zencart/zencart/blob/1b2f6eca784fba58946be8dea21545d93c890891/includes/modules/pages/search_result/header_php.php#L211
https://github.com/zencart/zencart/blob/1b2f6eca784fba58946be8dea21545d93c890891/includes/modules/pages/search_result/header_php.php#L225
https://github.com/zencart/zencart/blob/1b2f6eca784fba58946be8dea21545d93c890891/includes/modules/pages/search_result/header_php.php#L257
https://github.com/zencart/zencart/blob/1b2f6eca784fba58946be8dea21545d93c890891/includes/modules/pages/search_result/header_php.php#L386
https://github.com/zencart/zencart/blob/1b2f6eca784fba58946be8dea21545d93c890891/includes/modules/pages/search_result/header_php.php#L448

**Comment by scottcwilson** [comment]
Some of these things were no doubt added as placeholders, "to be expanded" when people started using them.  Please feel free to extend them to make them more useful.   

Not many use these particular notifiers and the examples I found check $_GLOBALS instead of depending on parameters which don't exist.  See https://www.zen-cart.com/downloads.php?do=file&id=2262

**Comment by torvista** [comment]
When I first started using notifiers I came across instances where a parameter seemed to be missing. But I think in all instances I could find it or derive it from something global.
I just thought that was by design, to just pass the essential/local parameters...

I feel breaking changes are part of development. As long as they improve things and are documented, onwards.

**Comment by proseLA** [comment]
> @torvista, here is an example from a previous conversation regarding the "need" to pass parameters in notifiers.
> 
> Of course one of the proposed changes breaks any historical use of the passed notifier value by changing out what is sent.

please provide an example of historical use.

**Comment by proseLA** [comment]
> I'll suggest adding the following on/around line 327:
> 
> ```
> $zco_notifier->notify('NOTIFY_SEARCH_MATCHING_KEYWORD_FIELDS', '', $keyword_search_fields);

i would think that we would be better served adding a notifier in the method `zen_build_keyword_where_clause`, and potentially adding to its signature from where it was called.  i think that would provide much more flexibility for developers that wanted to modify what fields to search.  i'm also a fan of adding type declarations to the method signature.
> ```

**Comment by droidmcse** [comment]
I solved this by making those variables global in the class like so. I am using sphinx to create a more robust search engine for a very large cart. Other things happen around it, but this let me modify the strings.


`  function __construct() {
    $this->attach($this, array('NOTIFY_HEADER_START_ADVANCED_SEARCH_RESULTS', 'NOTIFY_SEARCH_COLUMNLIST_STRING', 'NOTIFY_SEARCH_SELECT_STRING', 'NOTIFY_SEARCH_FROM_STRING', 'NOTIFY_SEARCH_WHERE_STRING', 'NOTIFY_SEARCH_ORDERBY_STRING', 'NOTIFY_HEADER_END_ADVANCED_SEARCH_RESULTS'));
  }

  function update(&$class, $eventID, $paramsArray = array()) {
    **global $currencies, $db, $sphinx_db, $select_column_list, $select_str, $from_str, $where_str, $order_str, $keywords, $listing_sql;**
    if ($eventID == 'NOTIFY_HEADER_START_ADVANCED_SEARCH_RESULTS') {
      
    }
    if ($eventID == 'NOTIFY_SEARCH_COLUMNLIST_STRING') {
      
    }
    if ($eventID == 'NOTIFY_SEARCH_SELECT_STRING') {
      **$select_str .= ", p.products_map, p.products_msrp, p.manufacturers_part_number, product_is_discontinued, product_is_active, product_is_superseded, p.product_is_freight, p.product_is_hazardous, m.manufacturers_image ";**
    }

**Comment by proseLA** [comment]
i'm not a huge fan of using globals everywhere, but i appreciate the the input.
