### ISSUE TITLE
init sanitize getvarname provides value not varname

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#5405]
https://github.com/zencart/zencart/blob/5dd780db8f9dda18911a815b89f34a7aea115f9f/includes/init_includes/init_sanitize.php#L21-L29
this section of code seems to disallow `$_GET` vars to be an array.  

if the value is an array, then it needs to be explicitly allowed via the notifier of `NOTIFY_INIT_SANITIZE_GET_VAR_CHECK`.  that notifier's first argument provides an array.  the key is something called `getvarname` and yet the value for that key is `$getvar` which is the array value and NOT the varname.

now, i suppose one could then retrieve all of the `$_GET` vars in the observer to build an array and find out which varname one is looking for to allow an array as a viable option; but it seems the code is wrong to me.

the first part of this issue is whether anyone is successfully using this notifier, and if so, does what am i saying make sense?

the second part of this issue is that if one were to use an auto loading observer, it looks to me that the auto loading observer is registered AFTER the sanitizing of the `$_GET` vars; which means one would need to manually load that observer prior to the sanitizing of the vars.  which i suppose is not a problem, but it would be nice to see someone confirm that is in fact the case.

**Comment by proseLA** [comment]
it does seem like sanitize is happening before loading of observers:
```
    [152] => Action Point - 96
    [153] => Auto Type Method - processAutoTypeInit_script
    [154] => loading init_script - includes/init_includes/init_sanitize.php
...
    [228] => Action Point - 175
    [229] => Auto Type Method - processAutoTypeInit_script
    [230] => loading init_script - includes/init_includes/init_observers.php
```

**Comment by proseLA** [comment]
finally i would like to state that the 2 notifiers:
```
NOTIFY_INIT_SANITIZE_STARTS
NOTIFY_INIT_SANITIZE_GET_VAR_CHECK
```
are new to v158.

so if someone would like to chime in about changing the method signature of an already existing notifier; show me an approved plugin making use of said notifier.

**Comment by scottcwilson** [comment]
The change I made (lines 24-27) was in PR #4685 - you can read the problem that I fixed.

> Fixes bad URL:
index.php?inc_subcat=0&keyword=1&main_page=advanced_search_result&page=7&search_in_description=1&sort[]=20a

> Reported in
https://www.zen-cart.com/showthread.php?228698-Error-logs-generated-from-Microsoft-IP 

There's no modifying of these parameters, it just reads and checks them for spam.

**Comment by lat9** [comment]
OK, that was my foobar'd comment, where I didn't pay attention to the fact that the `foreach` was doing a simple traversal on an associative array.

Since the OP of the forum report is not likely to have made use of that notification, how about Line 24 be changed to the following
```php
$zco_notifier->notify('NOTIFY_INIT_SANITIZE_GET_VAR_CHECK', ['name' => $getvarname, 'value' => $getvar], $site_array_override); 
```
That way, any current usage of the notification will receive a PHP warning for the now-missing `getvarname` key, so the usage will be made aware of the change.

**Comment by scottcwilson** [comment]
I don't think anyone is using this notifier, since an array is generally not desired in these parameters.  If one is actually intended, you can bypass the redirect.  Not sure the value is required but I guess adding it doesn't hurt - it's mostly for people to say *yes, this parm really should be an array*.

**Comment by scottcwilson** [comment]
@proseLA Do you have a use case for this change?  It was just put in as an anti-spam measure with a bypass option.

**Comment by lat9** [comment]
> I don't think anyone is using this notifier, since an array is generally not desired in these parameters. If one is actually intended, you can bypass the redirect. Not sure the value is required but I guess adding it doesn't hurt - it's mostly for people to say _yes, this parm really should be an array_.

I agree, but some site-specific customizations might need it.

**Comment by lat9** [comment]
So, @proseLA, what 'key' names would you propose?

**Comment by proseLA** [comment]
i was going to use `$varname` and `$varvalue`, removing the `get` part of it.

is that ok?
