### ISSUE TITLE
v158: Admin pagination woes ... again

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#5408]
Using the demo products, choose "Big Linked" (cPath=22).  Navigate to the 3rd page.  Edit "Something about Mary Linked" and then press Cancel.  You're returned to the 2nd page of the products' listing, not the 3rd.

**Comment by scottcwilson** [comment]
@barco57 noted something similar.  I couldn't repro the exact thing he described.

**Comment by lat9** [comment]
I don't know about the 'exact thing', but I was able to reproduce with the demo products' "Big Linked" category (see above).

**Comment by scottcwilson** [comment]
I asked him to re-check and see if it fixes his issue too.  Will get this merged in soon.
