### ISSUE TITLE
Salemaker: dates do not enable

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5415]
1) If past and future dates are set: sale is disabled and cannot be enabled.
2) If a past start date is set and end date is empty: sale cannot be enabled
3) If a past start date is empty, and future end date is set: sale is auto enabled and cannot be disabled
4) If dates are empty: sale can be enabled/disabled ok.

Looks like 1 and 2 are broken.

**Comment by scottcwilson** [comment]
I saw this today and thought I was going crazy!  I wound up just deleting the record and adding it again, and it worked. 

Thanks for confirming and documenting.

**Comment by scottcwilson** [comment]
Repro'ed finding 1 on demo data - this is exactly what I was seeing this morning.  I wonder if `now()` can no longer be used to set `date` type fields?

**Comment by scottcwilson** [comment]
For those who are looking at this, please pull other salemaker fixes in - #5414 and #5421.

**Comment by scottcwilson** [comment]
Note though a behavior of Salemaker that is not well documented: clicking the enable/disable button only works for sales with no start/stop dates; sales with start/stop dates are *automatically* enabled and disabled based on their date settings.

**Comment by scottcwilson** [comment]
Closing; this behavior is not intuitive but documented.
