### ISSUE TITLE
DB Changes needed 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#5417]
These are things that will need to be added to the database create/update scripts for the next numbered  release.
SOME have been added for 1.5.8a but need to be done again for people who installed 1.5.8. 

~~Fix tables for sites using prefixes:~~
~~https://github.com/zencart/zencart/pull/5334~~
People got this from the upgrade if they upgraded post 1.5.8a, or they did it by hand if they upgraded before.
Adding this again will just cause the upgrade to produce errors.

~~Country Turkey rename: https://github.com/zencart/zencart/pull/5416~~

**Comment by lat9** [comment]
Also #5601

**Comment by piloujp** [comment]
Some zones names for Italia, Swiss and Austria have some mistakes or just changed. 
Here is the list:

Austria (14)
Zone id 103, zone name 'Voralberg' should be 'Vorarlberg'

Italy(105)
Zone id 211 'Carbonia-Iglesias' should be deleted as it does not exist anymore.
Zone id 245 'Medio Campidano' should be deleted as it does not exist anymore.
Zone id 253 'Ogliastra' should be deleted as it does not exist anymore.
Zone id 254 'Olbia-Tempio' should be deleted as it does not exist anymore.

A new zone 'Sud Sardegna' with code SU should be added. Some states were grouped into this new one.

Some other have differences in name spelling more or less important. I am not sure all need to be update but I made a list anyway.
Zone id 193, zone name 'Aosta' should be 'Valle D'Aosta' which in SQL query should be 'Valle D\'Aosta'
Zone id 199, zone name 'Barletta Andria Trani' should be 'Barletta-Andria-Trani'
Zone id 226, zone name 'Forlì Cesena' should be 'Forlì-Cesena'
Zone id 233, zone name 'Aquila' should be 'L'Aquila' or 'L\'Aquila'
Zone id 243, zone name 'Massa Carrara' should be 'Massa-Carrara'
Zone id 261, zone name 'Pesaro Urbino' should be 'Pesaro E Urbino'
Zone id 294, zone name 'Verbania' should be 'Verbano-Cusio-Ossola'

Swiss(204)
All 'cantons' (states) names are in German but intenational designation uses English or main local language (German, French or Italian).
Zone id 110, zone name 'Freiburg' should be 'Fribourg'
Zone id 111, zone name 'Genf' should be 'Genève'
Zone id 113, zone name 'Graubnden' with code 'JU' should be 'Graubünden' with code 'GR'
Zone id 116, zone name 'Neuenburg' should be 'Neuchâtel'
Zone id 124, zone name 'Tessin' should be 'Ticino'
Zone id 126, zone name 'Waadt' should be 'Vaud'
Zone id 127, zone name 'Wallis' should be 'Valais'
Well, it should be all.

**Comment by lat9** [comment]
Also #5727

**Comment by scottcwilson** [comment]
I would suggest that the Zone changes suggested in this PR be delivered as plugins for those who need them.  In particular I would not be in favor of having entries in the upgrade scripts which assume a utf8 database.   We want to make it easy for people to upgrade and stay with Zen Cart, even if they're still using an old character set.

**Comment by scottcwilson** [comment]
Accordingly,  I would suggest this issue be closed when #5893 is merged, since at that point, db changes requested in #5727 and #5601 will be part of the 2.0.0 schema.

**Comment by piloujp** [comment]
> I would suggest that the Zone changes suggested in this PR be delivered as plugins for those who need them. In particular I would not be in favor of having entries in the upgrade scripts which assume a utf8 database. We want to make it easy for people to upgrade and stay with Zen Cart, even if they're still using an old character set.

By 'old character set' you mean ISO-8859-1, not old European charset?
I am not sure what is the problem, accentuated letters for European languages are nearly all included in ISO-8859-1. You don't need UTF-8 to write them (you just need to know how to do it). Problems appear when you use local charsets. In database search they are considered as equivalent to the non-accentuated letters, at least with ISO-8859-1, no problem there too.

Some spell mistakes should be corrected, like Graubünden Swiss state that certainly should not be Graubnden, at least Graubunden would be acceptable, or just remove the all thing.

**Comment by scottcwilson** [comment]
> By 'old character set' you mean ISO-8859-1, not old European charset?

Sorry yes.  Old by US standards. :) 
LA Story: "Some of these houses are over TWENTY years old!"

You're probably right on Graubnden.

**Comment by piloujp** [comment]
I did some checking and actually on Swiss post site I could not find any billing depending on state or any zone. Shipping fees only change depending on service, size and / or weight. It makes sense as it is a small country. Swiss zones could be removed without any problem as I don't think anybody will ever use them, at least for shipping fees...
There are still private companies but...
For other countries:
Austria: There is just a missing 'r' that should be corrected.
Italy: They had a big change in 2016 with one new states and four suppressed and incorporated in others. This should be updated. Then why not updating other 'misspelling' at the same time. Data would be more consistent by respecting official naming. There is one accentuated letter but it was already in the database that proves there is no problem with that.

I would add as a shop owner that having the names right is important, it shows a little bit about how you know or care for your customers. It depends on culture but in some countries using wrong names can be offending. Some country like Belgium even has laws that decide which language (Dutch or French) should be used and when or where (cities, streets)...

**Comment by drbyte** [comment]
@piloujp please prepare a PR for the zone/country changes you've mentioned.

Wherever we're doing "updates" to existing data, let's key it on the state/country "code", because we can't depend on the "id" integer because it may have changed if people have deleted and re-added things.

**Comment by piloujp** [comment]
> @piloujp please prepare a PR for the zone/country changes you've mentioned.
> 
> Wherever we're doing "updates" to existing data, let's key it on the state/country "code", because we can't depend on the "id" integer because it may have changed if people have deleted and re-added things.

Ok I am on it. What do I do with Switzerland? Delete or update? If I delete it should the zone_id of following countries (Spain, Australia, Italia) be changed to fill the gap? Probably better not...

**Comment by piloujp** [comment]
Forgot my question about zone_id. After Switzerland they all use autoincrement. In fact for Australia and Italia zone_id is set to NULL, but it can't be null which probably makes use of autoincrement.

**Comment by piloujp** [comment]
PR done.

**Comment by drbyte** [comment]
@piloujp 

> If I delete it should the zone_id of following countries (Spain, Australia, Italia) be changed to fill the gap? Probably better not...

No, for legacy reasons best to leave the numbers intact as they were.

> Forgot my question about zone_id. After Switzerland they all use autoincrement. In fact for Australia and Italia zone_id is set to NULL, but it can't be null which probably makes use of autoincrement.

Correct. When NULL is passed to an autoincrement field, the autoincrement fires and assigns the next number automatically.
