### ISSUE TITLE
PayPal issues in admin viewing orders with latest Github changes to PayPal

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#5418]
#5317 is causing problems in admin - 

```
--> PHP Warning: Undefined array key "currency" in /Users/scott/sites/client/includes/classes/currencies.php on line 108.
--> PHP Warning: Undefined array key "" in /Users/scott/sites/client/includes/classes/currencies.php on line 108.
--> PHP Warning: Trying to access array offset on value of type null in /Users/scott/sites/client/includes/classes/currencies.php on line 108.
[25-Nov-2022 17:25:05 UTC] PHP Fatal error:  Uncaught DivisionByZeroError: Division by zero in /Users/scott/sites/client/includes/classes/currencies.php:108
--> PHP Fatal error: Uncaught DivisionByZeroError: Division by zero in /Users/scott/sites/client/includes/classes/currencies.php:108
```

**Comment by brittainmark** [comment]
Do you have the 
To Reproduce
Steps to reproduce/demonstrate the behavior:
to save me guessing?

**Comment by scottcwilson** [comment]
I think it's just a matter of viewing an order in your admin when PayPal was used for payment - can you not dup it?

**Comment by brittainmark** [comment]
No, I have orders from paypal, but all in USD. Is USD set up as the default currency, or is it using a different default or currency for the order?

**Comment by scottcwilson** [comment]
It uses "Selected Currency."

**Comment by dbltoe** [comment]
https://www.paypal-community.com/t5/Archive/Why-is-my-balance-in-US-Dollars-when-I-m-UK-based/td-p/184874

**Comment by scottcwilson** [comment]
Even setting to USD doesn't fix it.  You're in admin viewing order details, right? ZC 158 + PHP 8.1?

**Comment by brittainmark** [comment]
Using PHP 8.2 and Zen cart 158. Have enabled the currency box and set paypal to selected currency. Created an order in GBP, and Euros still no warnings as above. I did get a warning during the order. But nothing in admin. Have been to look at the invoice. Not sure why this code would be called from admin. As all the changes were to storefront.

My storefront error was 
```
[25-Nov-2022 17:58:32 UTC] Request URI: /Test158/ipn_main_handler.php?type=ec&token=EC-34B27953CN802161E&PayerID=TMC895M53C3GL, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/payment/paypalwpp.php(2203): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/payment/paypalwpp.php(2013): paypalwpp->ec_step2_finish()
#2 /home/lotus/public_html/innerlightcrystals/Test158/ipn_main_handler.php(80): paypalwpp->ec_step2()
--> PHP Warning: Undefined array key "paypal_ec_markflow" in /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/payment/paypalwpp.php on line 2203.
```
I don't think this is related.

I still cannot reproduce. Is it a bad sales record?

**Comment by scottcwilson** [comment]
The order is fine and can be viewed with the old copy of `includes/modules/payment/paypalwpp.php` which doesn't use PR #5317 fix 

stack trace is 
```
#0 /Users/scott/sites/client/includes/classes/currencies.php(108): zen_debug_error_handler()
#1 /Users/scott/sites/client/includes/modules/payment/paypal/paypal_currency_check.php(17): currencies->value()
#2 /Users/scott/sites/client/includes/modules/payment/paypalwpp.php(284): paypalUSDCheck()
#3 /Users/scott/sites/client/includes/modules/payment/paypalwpp.php(215): paypalwpp->update_status()
#4 /Users/scott/sites/client/admin/orders.php(518): paypalwpp->__construct()
#5 /Users/scott/sites/client/admin/index.php(11): require('/Users/scott/si...')
```

**Comment by brittainmark** [comment]
Can you tell me the value of $_SESSION['currency'] when you view the order? If this is not set, it may cause the error you are seeing.

Just eating my tea. will be back in 30 mins.

**Comment by scottcwilson** [comment]
Changing `"includes/modules/payment/paypal/paypal_currency_check.php` line 17  to use `false` as the second parameter fixes it. 

```
        $amount = $currencies->value($amount, false, 'USD');
```
$_SESSION['currency'] is *not* set.

**Comment by scottcwilson** [comment]
Have you changed your cart to call `init_currencies.php` on the admin side?

**Comment by brittainmark** [comment]
No have not changed admin.

Does that mean that your exchange rate is zero for USD or the currency you are using?

Setting to false cause means the exchange rate is not calculated?

**Comment by scottcwilson** [comment]
setting to false means $_SESSION['currency'] is not used.  That's the problem. 
But I think it's probably best to bypass this check entirely, since it's coming from the admin side.  See my PR.

**Comment by brittainmark** [comment]
Neat solution, but if the exchange rate on the file is zero then there will be a failure on the store front.

**Comment by scottcwilson** [comment]
No disregard my first suggestion. I think we should omit this check entirely on the admin side where some of the expected variables aren't set.

**Comment by brittainmark** [comment]
yes agreed, was wondering why your $_SESSION['currency']  is empty?

**Comment by scottcwilson** [comment]
it doesn't appear to be set on the admin side.  Edit `admin/index_dashboard.php` and at the bottom do a `print_r` of `$_SESSION`.  You'll see. 

```
Array ( [securityToken] => 3a731d6e32aef571abac0874f2049e9f [language] => english [languages_id] => 1 [languages_code] => en [selected_box] => configuration [html_editor_preference_status] => NONE [admin_id] => 1 )

```

**Comment by brittainmark** [comment]
Just checked mine and it also is not set. There must be something in my code that is stopping the errors being reported. Just stepped it through the debugger and if I calculate it manually it fails. Now I will have to find what is stopping the error being reported in my code.

Yes, agreed it should not be called in admin. Thanks for finding the issue.

**Comment by scottcwilson** [comment]
Thanks for confirming.

**Comment by brittainmark** [comment]
Finally, managed to reproduce the error. Yes, agree with solution. Thanks again.
