### ISSUE TITLE
ADMIN jquery UI and datepicker requires updating?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5425]
admin is currently 1.10.3 2013

https://github.com/zencart/zencart/blob/053f54f9aa86002a5c913e6a7a12140abff14b6a/admin/includes/javascript/jquery-ui-i18n.min.js#L1-L7

It appears the "latest" min in 1.11.4, which I've been using for a while,
https://www.cdnpkg.com/jqueryui/file/jquery-ui-i18n.min.js/
but I find the UI thing unclear, so could be wrong.

**Comment by proseLA** [comment]
latest min?  not real sure what that means...

latest stable version is 1.13.2.  

they would have a min version of it.  else [you can do it yourself.](https://www.toptal.com/developers/javascript-minifier)

https://jqueryui.com/

and i'm only really a fan of using the min version after it goes into production.  for trouble shooting, minified versions are much harder.  and with browser caching, i think the speed gains in minified versions is not that great.  

i'm sure someone else feels differently.

**Comment by torvista** [comment]
1.13.2 is indeed current, but I was not understanding how the i18n bit works..

1) javascript loader loads
https://code.jquery.com/ui/1.13.2/jquery-ui.min.js
So that seems ok.

2) javascript loader loads
includes/javascript/jquery-ui-i18n.min.js
which is currently titled
jQuery UI - v1.10.3 - 2013-05-03
These are localisation files from here:
https://github.com/jquery/jquery-ui/tree/main/ui/i18n

Almost everything I find online refers to using/including these files as necessary/individually. The few references to using a single file as in ZC lead me to conclude a single-file-minified version is not something that is produced by/available from jquery, but only exists in a couple of cdn, like the one 1.11.4 referenced above, which is probably not up to date at all either. 
It seems to be a DIY file/not easily updated.

So, what to do about it to ease keeping this up to date/using current files?

3) admin_html
Looks for a local file (which does not exist) and then loads https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css
It appears the link should now be pointing to 1.13.2.

**Comment by brittainmark** [comment]
As Zen cart is moving / has moved to HTML 5 should we just move to the HTML form element?
```
 <input type="date" id="birthday" name="birthday">
```
You can see it [here ](https://www.w3schools.com/TAGS/tryit.asp?filename=tryhtml5_input_type_date)
Or have I misunderstood?

**Comment by torvista** [comment]
Interesting observation and certainly relevant to the big picture of date entry.

**Comment by lat9** [comment]
It's certainly a possibility, but the various browsers need to be checked to see the format in which they return those date-type fields.

**Comment by brittainmark** [comment]
The only issue I see is that it will be displayed in the browser display language. I do not know if this is really an issue.
That will eliminate jquery-ui-i18n as I think it only deals with dates.

What other elements of jqueryui are used in Zen cart.

**Comment by brittainmark** [comment]
It appears that tooltip is also used, this could be replaced by adding a title attribute to the required fields.

**Comment by lat9** [comment]
I _believe_ (i.e. I'm not totally sure) that the 'title' displays only on a `hover` event ... which isn't present on touch-type devices, while the tooltip is based on a `click` event which is available on _all_ devices.

**Comment by brittainmark** [comment]
Yes @lat9 you are correct. The tooltip as title will only work on hover.

Have seen the input type date on Firefox, Samsung phone, and edge. Firefox and Samsung phone display on clicking the field. Edge you have to click the calendar icon in the field.  Have also seen Crome on a Samsung phone, there you have to click the down chevron.

**Comment by torvista** [comment]
I note that this local css is missing, maybe by design:
https://github.com/zencart/zencart/blob/9df7dec2ff199a1ab26d30ee40eb585b85181cb7/admin/includes/admin_html_head.php#L26

but all the other css files are locally stored/loaded.

**Comment by scottcwilson** [comment]
Dependency checking is now part of the build process.  No need for separate issues unless there is a security alert that requires immediate updating.  

https://docs.zen-cart.com/dev/release_process/dependency_checks/
