### ISSUE TITLE
Admin, Attributes Controller: copy attributes to another product, Ignore existing attributes: fatal error 

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5446]
eg, choose graphics card
copy to a mouse using Ignore option: blank page.

> --> PHP Fatal error: Uncaught Error: Array callback must have exactly two elements in ...includes\functions\functions_attributes.php:473

(https://github.com/zencart/zencart/blob/dc1a6a64a7970a15380a4e5ef56de531e9a0dbb2/includes/functions/functions_attributes.php#L470-L474)

$copy_from(); is the array of attributes which is being parsed and at this point should skip to the next one.
It looks to me like that totally-out-of-place "$copy_from();" should actually be "continue;".

The saga continues.

**Comment by scottcwilson** [comment]
PHP 8.1, latest 158 in Github.

Attributes Controller - choose graphics card.
Under Additional options - select Copy Options to another Product
Choose Mouse 
Select Ignore existing attributes and add only new attributes

I don't get a blank page, but I do get these two logs:
[13-Dec-2022 11:39:28 UTC] Request URI: /gh_demo_158/admin/index.php?cmd=attributes_controller&products_filter=3&current_category_id=4, IP address: ::1, Language id 1
#0 /Users/scott/sites/gh_demo_158/admin/includes/modules/products_previous_next_display.php(30): zen_debug_error_handler()
#1 /Users/scott/sites/gh_demo_158/admin/attributes_controller.php(864): require('/Users/scott/si...')
#2 /Users/scott/sites/gh_demo_158/admin/index.php(11): require('/Users/scott/si...')
--> PHP Warning: Undefined variable $previous in /Users/scott/sites/gh_demo_158/admin/includes/modules/products_previous_next_display.php on line 30.

[13-Dec-2022 11:39:28 UTC] Request URI: /gh_demo_158/admin/index.php?cmd=attributes_controller&products_filter=3&current_category_id=4, IP address: ::1, Language id 1
#0 /Users/scott/sites/gh_demo_158/admin/includes/modules/products_previous_next_display.php(47): zen_debug_error_handler()
#1 /Users/scott/sites/gh_demo_158/admin/attributes_controller.php(864): require('/Users/scott/si...')
#2 /Users/scott/sites/gh_demo_158/admin/index.php(11): require('/Users/scott/si...')
--> PHP Warning: Undefined variable $next_item in /Users/scott/sites/gh_demo_158/admin/includes/modules/products_previous_next_display.php on line 47.

How do I repro your finding?
Does it make sense to fix these in the same PR or are they different?

**Comment by torvista** [comment]
This bug only occurs with the option 
copy to a mouse using Ignore option: blank page.

The other debugs I've seen but I think are fixed by another pending fix/up my sleeve for incorrect redirects.

**Comment by scottcwilson** [comment]
l'm not sure I understand what "Ignore option: blank page" means. 
Look at how I wrote up the steps in my prior response. 
Please write yours up the same way, step by step.

**Comment by torvista** [comment]
the Ignore option:
![image](https://user-images.githubusercontent.com/4391026/207792390-6f6844e5-38e2-4b6f-97eb-782966307826.png)

which is followed by a blank page. But that may be for php8.2/strict.
