### ISSUE TITLE
Deletion of zen_get_orders_status will cause plugin issues

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#5447]
The function `zen_get_orders_status` was removed in
d79a2cdc4a09184874d77639b0df2b3f0df2b7ca

Plugins like shipworks still use it. 

As reported in 
https://www.zen-cart.com/showthread.php?229181-Quick-question-regarding-third-party-and-zencart-1-5-8

**Comment by scottcwilson** [comment]
I blame overzealous culling in this case @prosela.

**Comment by proseLA** [comment]
ha!  i had nothing to do with it...

although i approved this message.

and who uses shipworks?  i just write my own:

![image](https://user-images.githubusercontent.com/1095136/206045535-d01c769e-831a-419d-b1d3-0f2cfebd7581.png)

**Comment by scottcwilson** [comment]
LOL I didn't mean I was blaming you I meant I was blaming overzealous culling! :)

**Comment by scottcwilson** [comment]
Ugh just another rename I guess. :( ONE DAY I WILL BE VINDICATED!
