### ISSUE TITLE
Coupon percentage off, free shipping and taxes

### ISSUE THREAD

**Issue by ajeh** [zencart/zencart#545]
See:
https://www.zen-cart.com/showthread.php?217875-coupon-percentage-off-free-shipping-and-taxes

Moving the $ratio in case 'E' and 'O' below the $od_amount['total'] should fix the issues on the calculations.

**Comment by zcwilt** [comment]
You just know I love working on Coupons/taxes :)

**Comment by drbyte** [comment]
Was this fixed via: https://github.com/zencart/zencart/commit/935af515a85799234a1524a9ca11d3dc5f50df12 ?

**Comment by drbyte** [comment]
Doesn't look like that was merged into v160 though...

**Comment by drbyte** [comment]
Merged via https://github.com/zencart/zencart/commit/469ae90568ab11a21c9a5037d0c4d7edb8dabf95
