### ISSUE TITLE
Attribute Controller, Copy Attributes to Whole Category: debug Undefined array key "products_update_id

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5450]
php 8.2.0RC7
Select a product with attributes.
Additional Actions->Copy Options to a whole category

--> PHP Warning: Undefined array key "products_update_id" in ...\attributes_controller.php on line 829.

This field is not required for this option.

**Comment by torvista** [comment]
there is another debug for <?php echo zen_draw_hidden_field('copy_attributes', $_GET['copy_attributes']); ?> which should not be there either, same as https://github.com/zencart/zencart/pull/5428.

**Comment by scottcwilson** [comment]
Would you please retest and PR now that a bunch of fixes have been made in this area; not sure what remains.  Thanks.
