### ISSUE TITLE
v158 default for dropdown Attributes not respected

### ISSUE THREAD

**Issue by nickwhaley** [zencart/zencart#5468]
See #3734.

Steps to repo:
1. Create a product
1. Go to Admin > Catalog > Option Value Manager and add an option an option called "Test"
2. Add a new Value called "One"
3. Add a new Value called "Two"
1. Go to Attributes Controller, select the new product. Add "One" as an option, setting sort order = 1, Default Attribute = No, Used for Display Purposes = No.
1. Go to Attributes Controller, select the new product. Add "Two" as an option, setting sort order = 2, Default Attribute = Yes, Used for Display Purposes = No.
1. Go to storefront select the new product.

Expected: the selected attribute is "Two"
Actual: the selected attribute is "One"

Same issue but now in 1.5.8 version. The commit that fixes that issue is not included in v158.

Currently only first attribute option is selected on all dropdown attributes on navigating to the product page. And not the default option.

Applying d65a89e3688f39ed7878d798639183d03e3134cc corrects the problem.

**Comment by nickwhaley** [comment]
I can confirm the store owner has set it up correctly. Applying the same commit from v157 to the v158 completely resolves the issue for the store owner.

**Comment by scottcwilson** [comment]
@nickwhaley Can you briefly describe, in your own words, the issue this is solving?   (Please update the first entry for this issue.). Here's the experience I have, and it seems to work fine: 

- On the demo dataset, look at product 1.  Observe the Memory dropdown doesn't have a default value.
- Go to Admin > Catalog > Option Value Manager, select Memory, Add a new Value called "Please Select"
- Go to Attributes Controller, select this product.  Add "Please Select" as an option, setting sort order = -10, Default Attribute = Yes, Used for Display Purposes = Yes. 
- Go to storefront and refresh product 1.  Observe that Memory dropdown now starts with "Please Select."

**Comment by nickwhaley** [comment]
Added repo steps.

Using Please Select will not be affected by this since when the default value is ignored, the first one is selected anyway.

**Comment by scottcwilson** [comment]
Thanks for writing this up.
