### ISSUE TITLE
V158 can't install with php 8.2

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#5473]
Uploaded to my server the github zip file: zencart-zencart-v1.5.8-161-g7eb7953.zip
Obtained the file by using: https:// github.com/zencart/zencart/zipball/v158/

Unzipped the files. 
Attempted to access the site, was correctly advised that needed to install and or correct any of other possible issues as to why am seeing the screen. 

Accessed zc_install (without using index.php) and was taken to the system check. 

So far so good. To right identifies that am using zen Cart 1.5.8, but then i get or have:
````
Some problems that need fixing before we continue
Incorrect PHP Version.
The PHP version you are using (8.2.0) is not suitable.

This version of Zen Cart® is compatible with PHP versions 7.3 to 8.0, although 7.4.x or higher is recommended.
Check the [www.zen-cart.com](https://www.zen-cart.com/) website for the latest version of Zen Cart®.

For more information about version compatibility and server requirements see [Zen Cart Server Requirements](https://docs.zen-cart.com/user/first_steps/server_requirements/)
````

There is more text below that, but why bother when coming to that first emboldened error message.

Php version enabled on the server was: 8.2 FastCGI, though that shouldn't matter as version was properly picked up and identified. Really any of the other "normal" characteristics for reporting a problem appear non-applicable. Comes down to the fileset, the limits identified for the version and the text that is supposed to be displayed in reference to the installation. 

Initial file inspection identified that the php version for installation is capped at 8.1.19 and that the above text is mostly hard coded but obviously not updated in initial distribution and not yet corrected. 

Note that the online docs to which everything is now directed says that it should be fully functional with php 8.2 and doesn't advise that installation must be with a lower version and certainly not with 7.3.

**Comment by scottcwilson** [comment]
Please PR.  Thanks.

**Comment by scottcwilson** [comment]
... and if it's too much work to get the installer working in 8.2, let me know and we'll update the documentation to say run the installer in 8.1 or lower.

**Comment by mc12345678** [comment]
The changes necessary are minimal, it's more of an issue in the mechanics of it. I only had to change like two things for installation to proceed. Want to try to reduce the hard coded text that needs to be kept current.

The real question becomes what is the real upper limit to be used? Should it be 8.3 or some known sub-version of 8.2? Generally speaking it's easier for a site owner to control the primary and secondary version number, but the tertiary? Not so easy unless have full control.

**Comment by scottcwilson** [comment]
The upper limit is < 8.3, as your PR shows.
