### ISSUE TITLE
v158 installation includes deprecated operation

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#5476]
Installation of ZC 1.5.8 using PHP 8.2 (reproducible on 8.1 as well), ZC Version and software the same as reported in #5473.

Accessing `zc_install` to see the first page results in the following zcInstallDEBUG-XXXXXXX-XXXX.log file issue:
````
PHP Deprecated:  Implicit conversion from float 127813.00000000001 to int loses precision in zc_install/includes/functions/general.php on line 38
````

The code of the line was: https://github.com/zencart/zencart/blob/2e423390aac0cf5ee561eeeea25ce5ec8ce69f23/zc_install/includes/functions/general.php#L38

The function `mt_srand` requires/expects an integer for its input/parameter, `microtime()` defaults to returning a `string` as per the [php manual microtime return values](https://www.php.net/manual/en/function.microtime.php#refsect1-function.microtime-returnvalues). The current operation effectively takes the `msec` portion and then multiplies it by 1,000,000; however, it is possible that the resulting value is not exactly an integer and as of PHP 8.1, the above deprecation notice is thrown. The "safest" resolution I have at this time (concerned about parenthetical relationships going astray is to modify this code to:
````diff
-      mt_srand((double)microtime()*1000000);
+      mt_srand((int)((double)microtime()*1000000));
````

This is also to ensure that the multiplication occurs while the number is still a double (effectively a float) and not after becoming typecast to an integer.

Another possible solution is to increase the number's size by using `microtime(true)` (which will return a number as a `float`) and remove the multiplication, but then may be considered (certainly debatable) to have less of a random seed for the random number generator. 

I don't see the need to change to using the `true` parameter, but the deprecation needs to be addressed.

**Comment by mc12345678** [comment]
Though, based on other review of the software, it appears that it was determined that the `microtime` function should be changed to use the float return value in addition to the multiplication by 1 million. So, I'll follow suit in my proposed correction.

**Comment by mc12345678** [comment]
I will add that as a result of this change, 32-bit systems may be using positive or negative seed values because of the limits of 32 bit integers and the new return value by using `microtime(true)` and then multiplying by a million. Previously the value fit well within a 32 bit integer value. 64 bit systems will not have a problem with this "new" math.

**Comment by scottcwilson** [comment]
Please PR.  Thanks.
