### ISSUE TITLE
zc_install: update Symfony YAML component

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5479]
While the installer is in the spotlight re php compatibility, I just ran an inspection on the folder, finding only this of actual relevance:

https://github.com/zencart/zencart/blob/2e423390aac0cf5ee561eeeea25ce5ec8ce69f23/zc_install/includes/vendors/yaml/lib/class.sfYamlInline.php#L139

**Comment by scottcwilson** [comment]
OK.  Yaml is a vendor library and we must not be using that particular piece of it.  We'll get it updated.

**Comment by scottcwilson** [comment]
Adding this to the Dependency check list.
