### ISSUE TITLE
v158 use of (many) MySQLi_ functions disabled

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#5484]
Unable to use any of the following `mysqli_` related database functions without creating a separate database accessor, modifying core code or restoring the database class to a previous version. 

Appears, like changes to other class member's visibility, that at least one of the `includes/classes/db/mysql/query_factory.php` members became too stringent. The visibility of the member `link` went from `var` (effectively `public`) to `private` in PR #5165. 

As a result of `var link` becoming `private link`, none of the following functions can be used from outside the class as they each require a mysqli reference (`link`) to the database being accessed and there is not a separate handler to get/use that member's value:
````
mysqli_affected_rows
mysqli_autocommit
mysqli_begin_transaction
mysqli_change_user
mysqli_character_set_name
mysqli_close
mysqli_commit
mysqli_dump_debug_info
mysqli_errno
mysqli_error_list
mysqli_error
mysqli_execute_query
mysqli_field_count
mysqli_get_charset
mysqli_get_connection_stats
mysqli_get_host_info
mysqli_get_proto_info
mysqli_get_server_info
mysqli_get_server_version
mysqli_get_warnings
mysqli_info
mysqli_insert_id
mysqli_kill
mysqli_more_results
mysqli_multi_query
mysqli_next_result
mysqli_options
mysqli_ping
mysqli_prepare
mysqli_query
mysqli_real_connect
mysqli_real_escape_string
mysqli_real_query
mysqli_reap_async_query
mysqli_refresh
mysqli_release_savepoint
mysqli_rollback
mysqli_savepoint
mysqli_select_db
mysqli_set_charset
mysqli_sqlstate
mysqli_ssl_set
mysqli_stat
mysqli_stmt_init
mysqli_store_result
mysqli_thread_id
mysqli_use_result
mysqli_warning_count
````
This is known to affect the plugin Easy Populate V4, causing a blank screen, and would affect any code that performed database manipulations using any of the above `mysqli_` functions from outside of the `query_factory` class. This was introduced in Zen Cart 1.5.8 and is independent of php version applicable to that Zen Cart version.

For an example of the error log, an evaluation and the solution to be proposed via PR, see: https://www.zen-cart.com/showthread.php?190417-EasyPopulate-4-0-Support-Thread&p=1391240#post1391240

**Comment by scottcwilson** [comment]
Please go ahead and PR. 
As a reminder, @brittainmark did HUNDREDS of these changes, and while most were fine, a handful needed to be adjusted.
