### ISSUE TITLE
v158 Github PR Request reviews/checks missing a PHP version

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#5488]
After just submitting a PR request and monitoring the Github "checks" of the PR  I noticed a php version check was missing. Keep in mind the lower limit of Zen Cart 1.5.8, It appears that PHP 7.3 is not included in the code review, but is supported by this version of Zen Cart as reported at: https://docs.zen-cart.com/user/first_steps/server_requirements/#php-version 

Just seems like a review/check "opportunity" is being missed.

**Comment by scottcwilson** [comment]
The spirit of including 7.3 was just to allow people on older Zen Cart versions to upgrade and then switch their PHP version.  We don't want people running 1.5.8 on 7.3.
