### ISSUE TITLE
`zen_image`, remove 'role="presentation"' since it's now causing HTML validation errors

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#5494]
![image](https://user-images.githubusercontent.com/2685585/208248386-e54ff1ba-a18e-4ae1-affc-d92144bf0926.png)

**Comment by mc12345678** [comment]
Wouldn't it in part be more appropriate to include the needed `alt` text or only remove the `role` tag when there is no `alt` information?

**Comment by mc12345678** [comment]
And perhaps some may notice the irony in this thread, but the image presented in the original post shows how an html validation review of an image tag has an `alt` parameter that is set to an empty set of quotes that then has a `role` parameter indicating that the role is for `presentation`.

The ironic part is that, if not mistaken, both parameters support screen readers to help those that want or need extra cues about the page content and context.

**Comment by scottcwilson** [comment]
@dbltoe Please confirm ok for accessibility.

**Comment by dbltoe** [comment]
Apparently, the only way to satisfy both HTML and accessibility is to drop the role and propagate the ALT

includes/functions/html_output.php lines 140-146 and 242-248

Apologies to lat9 for pointing things in that direction without checking HTML validation.

**Comment by dbltoe** [comment]
Apologies to lat9 who created this based on my accessibity fix for presentation without my having fully vetting HTML.

In order to satisfy both Accessibility and HTML, the ALT will need to be propagated and the role dropped.

includes/functions/html_output.php lines 140-146 and 242-248

**Comment by mc12345678** [comment]
> Apologies to lat9 who created this based on my accessibity fix for presentation without my having fully vetting HTML.
> 
> In order to satisfy both Accessibility and HTML, the ALT will need to be propagated and the role dropped.
> 
> includes/functions/html_output.php lines 140-146 and 242-248

From the provided image, it appears that the role is acceptable if the alt tag is populated, but not acceptable if the alt tag is missing or add in this case, blank. The above indicates that the role is to plainly be omitted. Did I understand correctly what was provided and does the provided information match the expectation?

**Comment by lat9** [comment]
Noting that the `alt="" role="presentation"` change was introduced in #5063.

**Comment by scottcwilson** [comment]
Another option would be to fabricate an alt tag ("image for product") where one is not available.  Then the validator would be happy.

**Comment by dbltoe** [comment]
Unfortunately, since most of these are nested in an area together, the checkers will see manufacture/duplicate tags.

**Comment by scottcwilson** [comment]
How about "image for <product name>" ?

**Comment by lat9** [comment]
Why not just restore the `alt="{title}"`, repeating whatever was applied to the title and dropping the `role="presentation"`?

**Comment by scottcwilson** [comment]
Seems reasonable.

**Comment by lat9** [comment]
Waiting for @dbltoe's response.

**Comment by dbltoe** [comment]
> How about "image for `product name`" ?

This was what I proposed above.

> In order to satisfy both Accessibility and HTML, the ALT will need to be propagated and the role dropped.

Propagate the ALT with the $product_name and drop the role altogether.

**Comment by lat9** [comment]
`zen_image` displays images for many other things than just products. 

Just so I'm clear, we're essentially reverting the change for #5063 so that the output `<img>` tag replicates the `$alt` function input into both the `alt=` and `title=` HTML attributes and no longer includes `role="presentation"`.

Should an `E_USER_NOTICE` log be issued if the `$alt` parameter evaluates to an empty string to indicate that the associated image will result in an accessibility-validation failure?

**Comment by dbltoe** [comment]
I believe my latest testing showed using just ALT with the $product_name along with dropping the title and role was enough to pass both HTML and accessibility but I won't be able to check for sure till tomorrow. Out of allotted time in the chair this evening. 😞

**Comment by lat9** [comment]
I'll await your assessment tomorrow.

**Comment by dbltoe** [comment]
Couldn't help myself if lines 140 thru 150 of includes/functions/html_output.php go from 
`    // The alt attribute is now provided as an empty string, with the addition of a
    // role="presentation", since most browsers see an empty alt attribute as presentational
    // and now-current browsers also accept the 'role=' attribute.
    $image = '<img src="' . zen_output_string($src) . '" alt=""';
    if (strpos($parameters, 'role="presentation"') === false) {
        $image .= ' role="presentation"';
    }

    if (!empty($title)) {
        $image .= ' title="' . zen_output_string($title) . '"';
    }`

to

`    $image = '<img src="' . zen_output_string($src) . '" alt="ADD SOMETHING LIKE $product_name HERE"';`

then the result will meet both HTML and accessibility

NOTE: the same will need to be done to lines 242 thru 252

You can see it in action (sorta) at myflagpoles.com  I used "this is the first..." or "this is the second..." as alt tags for each of the two code changes.

Hope it makes sense

Axe Dev Tools and Web Aim's Wave will catch the fact that the ALT tags are the same.  ANDI and the Siteimprove Accessibility Checker do not alert on that situation.  HTML is clean.

**Comment by lat9** [comment]
So, where are we on this?

> `zen_image` displays images for many other things than just products.
> 
> Just so I'm clear, we're essentially reverting the change for #5063 so that the output `<img>` tag replicates the `$alt` function input into both the `alt=` and `title=` HTML attributes and no longer includes `role="presentation"`.
> 
> ~~Should an `E_USER_NOTICE` log be issued if the `$alt` parameter evaluates to an empty string to indicate that the associated image will result in an accessibility-validation failure?~~

OK, so for accessibility the `alt=` needs to be different than the `title=`?  I'm prone to keep the `title=` since that's a good hint on desktop viewing.

**Comment by dbltoe** [comment]
IMO, It's perfectly acceptable to keep the title.  I agree that a good hint is always a good idea. 👍

**Comment by lat9** [comment]
One more verification, is it true that `alt=` needs to be different than `title=`?

**Comment by dbltoe** [comment]
You might get an alert if they are the same but it is not a violation of A, AA, or AAA standards to be the same.

**Comment by dbltoe** [comment]
Somewhere in the future we might actually propagate titles with the product title and add an alt tag description input where the image is added to the category/product.

That would eliminate some current alerts and give us two separate inputs to propagate two separate items.
