### ISSUE TITLE
admin side load order

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#5505]
encapsulated plugins get loaded before the autoLoader even starts.  which means that that the `zen_get_zcversion` is not available nor are any of the configuration constants.  

it seems that we are making developers jump through hoops to get an encapsulated plugin to work properly with v157 and v158, despite best intentions.

here is an echo line in an encapsulated plugin function file with `$initSystem->setDebug(true);` to demonstrate (only the first few lines of the autoloader are included):

```
/var/www/zcdev/zc_plugins/ProseMods/1.0.0/admin/includes/functions/extra_functions/test.php:4
function processLoaderList:
Array
(
    [0] => ##################################################################
    [1] => Action Point - 0
    [2] => Auto Type Method - processAutoTypeRequire
    [3] => processing require - /var/www/zcdev/includes/version.php
    [4] => loading require - /var/www/zcdev/includes/version.php - SUCCESS
    [5] => =================================================================
    [6] => Auto Type Method - processAutoTypeClass
```

**Comment by scottcwilson** [comment]
> it seems that we are making developers jump through hoops to get an encapsulated plugin to work properly with v157 and v158, despite best intentions.

Obviously this is not the goal.  If there are shortcomings, let's fix them.

I'm going to leave this for @lat9 since she has more experience in this area.

**Comment by lat9** [comment]
Sorry, the zc_plugins is not an area that I'm familiar with.  That implementation, which I'm still waiting to use, was developed by @zcwilt.

**Comment by scottcwilson** [comment]
I keep thinking you were the one who did DisplayLogs.  My bad. I will dig into this over the next week.

**Comment by scottcwilson** [comment]
Please post the code for `/var/www/zcdev/zc_plugins/ProseMods/1.0.0/admin/includes/functions/extra_functions/test.php:4
` so I can see what you're doing.

**Comment by scottcwilson** [comment]
Specifically, this code would need to be called in the context of a function.  You can't just stick code outside a function in a file in extra_functions, since functions are loaded before other things are completely ready.   You definitely should be able to reference config variables and other things *inside a function* in the extra_functions folder.

**Comment by proseLA** [comment]
> Specifically, this code would need to be called in the context of a function. _You can't just stick code outside a function in a file in extra_functions, since functions are loaded before other things are completely ready._ **You definitely should be able to reference config variables and other things _inside a function_ in the extra_functions folder.**

the section in italics, i have no idea what you are talking about here.  in fact, i just do not think that is correct.  as an example, here is a line of code that exists outside of a function in a file in extra_functions:

https://github.com/zencart/zencart/blob/eacd3f555b3ce7fb07f8c1b79640bebfbf91b486/includes/functions/extra_functions/zca_responsive_functions.php#L44

with regards to the bolded section, the point i am making is with different functions necessary based on zc version information, none of that is available to use in the extra_* directory file structure.  it has to be loaded as part of the script, ie admin/myScript.php.  for example, if i wanted to do this in the extra_functions file in v158, it fails:

```
if (!function_exists('zen_get_orders_status_pulldown_array')) {
    function zen_get_orders_status_pulldown_array()
    {
       ///
    }
}
```
this is because this file gets loaded prior to the system being initialized.  it does not fail here, it fails when zc tried to define a function that has already been defined.

none of the things [mentioned here](https://docs.zen-cart.com/dev/plugins/version/) are available in any of the extra_* directories.

it makes little sense to me to have a _plugin_ loaded prior to the system being initialized.

the encapsulated plugins get loaded here:

https://github.com/zencart/zencart/blob/eacd3f555b3ce7fb07f8c1b79640bebfbf91b486/includes/application_top.php#L207-L219

the system gets initialized further down:

https://github.com/zencart/zencart/blob/eacd3f555b3ce7fb07f8c1b79640bebfbf91b486/includes/application_top.php#L235

so if you wanted to use any config value in any of the extra_* directories, they would not exist at that time.

and i'm not sure there is an elegant solution to this other than defining everything necessary in one's script as opposed to the zc structure.

**Comment by scottcwilson** [comment]
Let's skip to the end

> it makes little sense to me to have a plugin loaded prior to the system being initialized.

It could be that you have found a bug.  It's very early days for encapsulated plugins; there aren't many of them.

**Comment by proseLA** [comment]
> It could be that you have found a bug. It's very early days for encapsulated plugins; there aren't many of them. And things that work when you put a file in the normal cart hierarchy in `extra_functions` (like the example you gave) may not work if you put the file in the encapsulated plugin hierarchy.
> 
> It might make more sense for you not to pursue the path of encapsulated plugins, and just do a regular plugin instead.

once one goes to encapsulated plugins, there is no going back to doing a regular plugin.

please do not take this the wrong way scott, as you do a great service for the ZC community.  but IMO, some of the best improvements since v157 are the `admin_html_head` file and the encapsulated plugins.  and yet, you to choose to ignore both of these advancements in all/most plugins that you release.  i think only you can answer why you choose that path; but i know a lot of work went into making those things happen, and i, for one, choose to embrace those advancements; despite any added work it may entail for me.

**Comment by scottcwilson** [comment]
>  i think only you can answer why you choose that path ...

I haven't had time to do more recent updates and I wanted older versions to be backwards compatible.  It's really not that complicated.

**Comment by scottcwilson** [comment]
It looks like you have one plugin that uses encapsulation (Inventory Manager) and I have one (Mod List).  I'm pretty focused on Zen Cart 1.5.8 - maybe you'd like to take the lead on improving and enhancing encapsulated plugins?

**Comment by proseLA** [comment]
sorry, no can do.  i have already looked at it, and see no easy solutions.

**Comment by scottcwilson** [comment]
Please post the code for /var/www/zcdev/zc_plugins/ProseMods/1.0.0/admin/includes/functions/extra_functions/test.php:4  so I can see what you're doing.

**Comment by mc12345678** [comment]
I'd like to add that if plugins in general didn't load before many of the core system, then observers pretty much would be non-starters.

I don't think it ever got better explained about the code in extra_functions files that is performing an person during the file load. Of course I really thought I was going to find some catchy load sequence issue where a lot of work may have been done to ensure the files loaded in a specific order, but the provided example of calling a function outside of a function definition took things further than what scott was describing. 

The caked function was defined in the few lines just before the call within the same file. In other words the function already existed by the point that it was being used. As far as adding function code that is to be accessible to all operations based on the Zen Cart version? Something about that seems wrong. Why does the rest of Zen Cart need a function that is only being used by the plugin and why wouldn't the file set be specific to Zen Cart version or the needed code be considered elsewhere in the plugin's operation?

Like calling a plugin named function in which that function does a version check to then call/create the necessary Zen Cart versioned function would work unless that was called before the Zen Cart functions were loaded. 

As might recall, the whole idea of adding our allowing loading of the extra_functions folder in plugins was quite a discussion. Not sure if this concept was partially why it originally wasn't incorporated. Although I've not yet made an admin plugin accessible to others as an encapsulated plugin, but have been able to use/load the extra_functions file in a way that it will get loaded by the software if Zen Cart didn't already load it. It's currently based on that code retaining a specific function in it,

**Comment by proseLA** [comment]
@mc12345678 please stay on topic.  the topic is admin side load order.  feel free to raise other issues in separate issues, not on this thread.

@scottcwilson i feel there is enough information already posted here to understand the problem/dilemma.  but if that's what you want...  

take the following code:
```php
echo "-------->" . DIR_FS_CATALOG . "<---------<br>";
echo "-------->" . PROJECT_VERSION_MAJOR . "<---------<br>";
echo "-------->" . STORE_OWNER . "<---------<br>";
die('<br>' . __FILE__ . ':' . __LINE__);
```
and place it at the top of:

admin/includes/functions/extra_functions/add_cookie_path_switch.php

and go to your admin home page.

remove it and then place it here:

zc_plugins/ProseMods/1.0.0/admin/includes/functions/extra_functions/test.php

now look at your admin home page.

if that does not explain the problem to you, i can no longer help.

**Comment by scottcwilson** [comment]
This is exactly what I asked for.  Thanks for responding.

**Comment by zcwilt** [comment]
Just a few notes here while I noodle on the best way to address this.

I'm of the opinion that plugins should never load from an internal extra_functions directory.
It doesn't make sense.

Yet we have it doing that, and would agree with @proseLA  that the point it does that makes no sense either.

As @mc12345678 points out, there is a reason that plugins load some of their code quite early e.g. for some notifications stuff.

However plugins do hook into the autoloader system and therefore allow for loading other code at whatever breakpoint they want, and that includes after version.php has loaded.

I think there is some misunderstanding here as well in terms of converting a legacy plugin to an encapsulated plugin in that you can't just take the structure of a legacy plugin and expect that to work as an encapsulated plugin, including say expecting all extra_* directories to just work.

**Comment by proseLA** [comment]
i have gotten around this problem, by doing my loads at the beginning of my scripts.  for example, if i have a script here:

zc_plugins/ProseMods/1.0.0/admin/proseDoSomethingSpecial.php

at the beginning of the file, i have the following code:

```php
require('includes/application_top.php');
$dir = dirname(__DIR__, 1);
require $dir . '/admin/includes/loaded_after/prose_functions.php';
```
and in that way i keep everything encapsulated.  which to me is ideal.

**Comment by scottcwilson** [comment]
Closing since OP has workaround.
