### ISSUE TITLE
admin, category-product listing, product with no image references directory: 403 erro

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5518]
create a new product with no details apart from name.
it has no image in the listing:

![image](https://user-images.githubusercontent.com/4391026/210885325-64363978-9f26-4f47-be4c-740375eb0106.png)

but the src references the directory instead of a missing image:

![image](https://user-images.githubusercontent.com/4391026/210885430-bab60ce5-00a2-4877-9f8f-d82fd7da7d8e.png)

which is not allowed:

![image](https://user-images.githubusercontent.com/4391026/210885488-7eae2f85-42be-405a-864e-31f8da511d09.png)

**Comment by scottcwilson** [comment]
Thanks for reporting.  I have seen this a few times and always meant to fix it but never got to it.

**Comment by scottcwilson** [comment]
Would you please PR?

**Comment by torvista** [comment]
How the image is handled in preview_info needs a review.
It should be checked at the start of the file, not in the middle, with an error message and replacement if manually-added and not_exists.
I'm out of time at the moment.

**Comment by drbyte** [comment]
> How the image is handled in preview_info needs a review.
> It should be checked at the start of the file, not in the middle, with an error message and replacement if manually-added and not_exists.
> I'm out of time at the moment.

@torvista Can you clarify what you mean here?

From what I see:
Near the top, on line 36 of `/admin/product.php` checks for `GET[action] = 'new_product_preview'` 
which then calls `/admin/includes/modules/new_product_preview.php` which uploads the image, and returns
and then carries on to line 105 of `/admin/product.php` to call the `preview_info.php` module, which merely displays all submitted data, and image.

**Comment by torvista** [comment]
I think I was forgetting preview_info is embedded in another page, so a check IS done earlier.
Noting that when POST is set for a new product with no image, $pInfo->products_image is null but the hidden field to pass the image name to be saved uses $products_image_name.
