### ISSUE TITLE
admin, invoice: html error 

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5520]
![image](https://user-images.githubusercontent.com/4391026/211172287-3e115153-6e7d-47f6-a9ec-06d3649d5e8c.png)

probably could be removed.

**Comment by scottcwilson** [comment]
Root cause: checks in includes/functions/html_output.php line 178 (zen_draw_separator) need to be improved to account for blank width.

**Comment by piloujp** [comment]
I found two ways to fix that :

- First, zen_draw_separator function is called with an empty width parameter only two times in Zen Cart, in invoice.php and packingslip.php. Replacing line 144 in invoice.php 
`      <div><?php echo zen_draw_separator('pixel_trans.gif', '', '10'); ?></div>`
by 
`      <div><?php echo zen_draw_separator('pixel_trans.gif', '1', '10'); ?></div>`
and line 137 in packingslip.php 
`      <div><?php echo zen_draw_separator('pixel_trans.gif', '', '10'); ?></div>`
by 
`      <div><?php echo zen_draw_separator('pixel_trans.gif', '1', '10'); ?></div>`
will do the trick.

- Second way is to modify  html_output.php in admin, rewriting zen_draw_separator function on line 177
```
  function zen_draw_separator($image = 'pixel_black.gif', $width = '100%', $height = '1') {
    if (substr(rtrim($width), -1) != "%") $width = $width . 'px';
    return zen_image(DIR_WS_IMAGES . $image, '', '', $height, 'style="width:' . $width . ';"');
  }
```
to
```
  function zen_draw_separator($image = 'pixel_black.gif', $width = '100%', $height = '1') {
	if (!empty($width)) {
		if (substr(rtrim($width), -1) != "%") $width = $width . 'px';
		$param = 'style="width:' . $width . ';"';
	} else {
		$param = NULL;
	}
    return zen_image(DIR_WS_IMAGES . $image, '', '', $height, $param);
  }
```
`$param = NULL;` could be replaced by `$param = 'style="width:100%;"';` too.

**Comment by scottcwilson** [comment]
@piloujp would you please PR?  Thanks.

**Comment by piloujp** [comment]
Completely forgot about this...
PR is done now.
