### ISSUE TITLE
Using CKEditor on define pages with PHP content breaks the page 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#5526]
- Switch your editor to CKEditor
- Edit a page like define_site_map.php, which contains the code 

```
<a href="<?php echo zen_href_link(FILENAME_CONTACT_US, '', 'SSL'); ?>">Contact Us </a>
```
- Verify you are using CKEditor.  Press Save. 
- Refresh the sitemap page on the storefront and observe that the link is broken.  The link now points to

```
http://localhost:8888/gh_demo_158/%3C?php%20echo%20zen_href_link(FILENAME_CONTACT_US,%20%27%27,%20%27SSL%27);%20?%3E
```

**Comment by scottcwilson** [comment]
This bug was also present in 1.5.7d so it is not new to 1.5.8.

**Comment by scottcwilson** [comment]
Fails in 1.5.6 as well.  Could be that embedding PHP in a define page has simply never worked but it is done in so few places (define_site_map.php is the only built-in page doing it) that no one ever noticed.

**Comment by scottcwilson** [comment]
If no one wants to fix this, then we would simply remove the PHP code from define_site_map.php.

**Comment by lat9** [comment]
I've got many sites that use a PHP-based `define_main_page.php` (and others).  Not sure what (other than marking the files with PHP constructs as `read-only`) a solution might be.

**Comment by scottcwilson** [comment]
If you don't use the HTML Editor, it works fine. I might just remove the PHP (which is really overkill) from this one file so people won't go down this path and get into trouble.

**Comment by piloujp** [comment]
Well in HTML you have to escape < by `&lt;` and > by `&gt;` if not there are interpreted as tag delimiters. With the last v1.58 from Github it is done by default and works fine for me when editing plain text or with CKEditor. But if I replace by < or > (inside href) then sitemap link is broken. Here is the code I have by default:
`<p>If you are having difficulty in locating something on our site, please visit our <a href="&lt;?php echo zen_href_link(FILENAME_CONTACT_US, '', 'SSL'); ?&gt;">Contact Us </a> page and let us know!</p>`

**Comment by scottcwilson** [comment]
Let's just get rid of the PHP in the sample file provided.

**Comment by mc12345678** [comment]
How about adding guidance or direction on the define pages editor page something to the effect that php and or manually entered html should be entered in a text only editor or while the editor supports entry of source or text content? 

Getting rid of the php doesn't really fix anything, using a manually entered internal reference goes against at least some of the docs and is a loss of an easily accessible example of how to implement php code in those type files.

**Comment by scottcwilson** [comment]
Getting rid of the PHP removes a stumbling block that people would hit if they edited this file in HTML mode in the CKEditor.

**Comment by piloujp** [comment]
Why not do both : removing PHP code will avoid troubles when using CKEditor. After all, define pages are designed to a be HTML pages/code.
But In documentation adding an example of PHP code use in text mode like an advanced trick with warning not to use CKEditor at all in this case?

**Comment by scottcwilson** [comment]
Yep.

**Comment by piloujp** [comment]
> As a note, use of ckeditor is not the problem, incorrect use is. Further there are other editors that offer the same feature of generating html for the user and having a source edit view. Exclusion of CKEditor is not a solution.

There is a misunderstanding, I did not suggest removing CKEditor, just PHP code and as you suggested modifying documentation, applying both your suggestion and Scott'one. And I agree CKEditor is not the problem, it does what it should, editing HTML.
