### ISSUE TITLE
admin activity log, output to html/browser: "$current_category_id" is corrupted into html entity

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5532]
Viewing the admin activity log as html; I find this for entries into products_to_categories under the parameters column:

> products_filter=7777¤t_category_id=3683

where the "&curren" of "&current_category_id" has been converted into its entity: "¤"  as it does not need a semicolon!

This particular url is from product->Copy->The P2C button at the bottom of the Copy to Confirm infobox.

I suspect something needs to be done here:
https://github.com/zencart/zencart/blob/bdc110a04c980f02ad1bc398abfae95acf9456c0/admin/admin_activity.php#L199

I tried some variations without success.

**Comment by drbyte** [comment]
How much of a problem does this create if this were never "fixed"? 

Considering: the activity log is for review purposes (not re-enacting by clicking), and probably the unintended abbreviation/substitution may even make it more readable due to the shorter line-length.

**Comment by torvista** [comment]
Well, I was only poking around to ascertain what was being done at a specific time that lead to an error.
As the page and parameters are separated they have to be copy and pastable to re-try the action, so it could be argued it has a need to be correct, apart from the visual aspect.
