### ISSUE TITLE
Admin, comparison of collect_infos: $pInfo->products_id

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5536]
Comparing the five collect_infos, only the product version has this but I suspect all should have it?
https://github.com/zencart/zencart/blob/5fb07cf03e3d0e3d7817a8c3411d0e2345147d5d/admin/includes/modules/product/collect_info.php#L60-L62

**Comment by scottcwilson** [comment]
See #5240

**Comment by scottcwilson** [comment]
Closing as dup of issue noted above.
