### ISSUE TITLE
Developers Toolkit html validation errors

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5540]
![2023-01-16 13_07_09-Admin Developers Tool Kit — Mozilla Firefox](https://user-images.githubusercontent.com/4391026/212676079-9ffb60c4-9e6d-428b-ba24-7ec45a3839fb.gif)

and post search submission:

![image](https://user-images.githubusercontent.com/4391026/212676471-3ede46be-89d9-4685-99cb-8d781b2e61ef.png)
![image](https://user-images.githubusercontent.com/4391026/212676606-8bf28953-fc27-45c9-ae7e-1d846688c05f.png)

**Comment by torvista** [comment]
+ quite a lot of IDE-spotted things.

**Comment by proseLA** [comment]
is html validation on the admin side really a thing?

**Comment by torvista** [comment]
Yes. It got me started on contributing. Maybe these can get others started.
Most "real" issues are too complex to fix for most people.

**Comment by dbltoe** [comment]
One benefit is, if we ever get a full demo site, folks can see that the same emphasis was taken to have the Admin in compliance.
Being the admin, it's more of a "one and done" unless there are areas that would need to be language-oriented.
Simple things like the surrounding of a form with a div the other day can make a customization so much easier.  You won't have to fix it to build it.

**Comment by scottcwilson** [comment]
Consolidated these issues in #5807.
