### ISSUE TITLE
Sold Out button not respecting admin CSS Button setting

### ISSUE THREAD

**Issue by simon1066** [zencart/zencart#5545]
I could be barking up the wrong tree with this as I don't have a vanilla site of ZC v1.5.8 with which to test.

During the process of upgrading from v1.5.7d to v1.5.8 it appeared that the Sold Out button on the product listing and product info pages displays as an image (gif) rather than the CSS button it should be (CSS Button switch in admin is on). 

If it is relevant, the button image has an empty alt tag even though `BUTTON_SOLD_OUT_ALT` is defined.

I'll note that in line 211 of functions_general.php changing the `zen_image` function to the old `zen_image_button` allows the sold out button to be displayed as a CSS button.

Line 211
`$return_button = '<span class="text-center">' . zen_image($template->get_template_dir($image, DIR_WS_TEMPLATE, $current_page_base, 'buttons/' . $_SESSION['language'] . '/') . $image, $alt, '', '', '') . '</span>'; `

Perhaps someone with a ZC v1.5.8 test site could check this.

**Comment by scottcwilson** [comment]
Related issues:
#3368 
#4333

**Comment by lat9** [comment]
> Related issues: #3368 #4333

Those issues are kinda, sorta, not-exactly related, since they're dealing with the admin-side of button-generation; @simon1066 is identifying that the storefront should honor the css-button generation for the "Sold Out" button, which is always rendered as an image.

**Comment by scottcwilson** [comment]
I'm hoping some nice volunteer will scoop up all three.

**Comment by scottcwilson** [comment]
@brittainmark Would you be willing to look at this and perhaps the other two?

**Comment by brittainmark** [comment]
I would argue that we do not change the sold out code as a notifier has been added to allow changes to be made to the button. 
 
1.5.7 code
```
    case ($button_check->fields['products_quantity'] <= 0 and SHOW_PRODUCTS_SOLD_OUT_IMAGE == '1'):
      if ($_GET['main_page'] == zen_get_info_page($product_id)) {
        $return_button = zen_image_button(BUTTON_IMAGE_SOLD_OUT, BUTTON_SOLD_OUT_ALT);
      } else {
        $return_button = zen_image_button(BUTTON_IMAGE_SOLD_OUT_SMALL, BUTTON_SOLD_OUT_SMALL_ALT);
      }
      break;
```
1.5.8 code
```
    case ($button_check->fields['products_quantity'] <= 0 and SHOW_PRODUCTS_SOLD_OUT_IMAGE == '1'):
            global $template;
            $image = BUTTON_IMAGE_SOLD_OUT; 
            $alt = BUTTON_SOLD_OUT_ALT; 
            $return_button = '<span class="text-center">' . zen_image($template->get_template_dir($image, DIR_WS_TEMPLATE, $current_page_base, 'buttons/' . $_SESSION['language'] . '/') . $image, $alt, '', '', '') . '</span>'; 
            $zco_notifier->notify('NOTIFY_ZEN_SOLD_OUT_IMAGE', array_merge($button_check->fields, ['products_id' => (int)$product_id]), $return_button);
            break;
```

**Comment by scottcwilson** [comment]
Right but should have to use a notifier to get what should be the default behavior?

**Comment by brittainmark** [comment]
ok. I see your point. I'll give it some thought.

**Comment by brittainmark** [comment]
Are we happy to keep using zenCssButton?

**Comment by scottcwilson** [comment]
No particular opinion.

**Comment by brittainmark** [comment]
Assuming it's OK to use zen_image_submit then that is the easiest change.
is replace line 211
`$return_button = '<span class="text-center">' . zen_image($template->get_template_dir($image, DIR_WS_TEMPLATE, $current_page_base, 'buttons/' . $_SESSION['language'] . '/') . $image, $alt, '', '', '') . '</span>';`
with 
`$return_button =  zen_image_submit($image, $alt, 'button');`

**Comment by brittainmark** [comment]
Tried zen_submit_image that causes the user to be taken to the cart. zenCssButton leaves you on the same page.
