### ISSUE TITLE
v158 zen_get_configuration_key_value_layout throws warning for non-existent configuration_key

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#5547]
if the function `zen_get_configuration_key_value_layout` is called where `$lookup` is a value that does not exist as a `configuration_key`, then a warning debug log is generated.

Discovered using Zen Cart 1.5.8, PHP 8.2.
Reproducing this requires either removal of a `configuration_key` value from the database that is used in a Zen Cart call or creating code that attempts to use the function with a non-existent value to look up.

**Comment by scottcwilson** [comment]
The creation of a debug log in a case like this seems proper to me.  Your database has been damaged (or your code is bad).

**Comment by lat9** [comment]
> if the function `zen_get_configuration_key_value_layout` is called where `$lookup` is a value that does not exist as a `configuration_key`, then a warning debug log is generated.
> 
> Discovered using Zen Cart 1.5.8, PHP 8.2. Reproducing this requires either removal of a `configuration_key` value from the database that is used in a Zen Cart call or creating code that attempts to use the function with a non-existent value to look up.

@mc12345678, through what path did you _discover_ this issue?  Like @scottcwilson, I'm trying to fathom a real-world case (other than development) where this condition could arise and it shouldn't be reported (via log) as a problem.

**Comment by scottcwilson** [comment]
This behavior is not a bug.
