### ISSUE TITLE
includes/modules/pages/page/header_php.php needs cleanup

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#5552]
- Lots of commented out code 
- variables that aren't set (`$previous_h`,`$next_item_h`)
- variables that may not even be needed anymore (`$next_vssl`, `$previous_vssl`, and same variables for `$h`.)

**Comment by Zen4All** [comment]
Long time absent, but getting back, i am willing to take a look

**Comment by scottcwilson** [comment]
Most appreciated, and welcome back!

**Comment by scottcwilson** [comment]
Fixed by #5556
