### ISSUE TITLE
'TEXT_GREETING_GUEST' missing parameter for sprintf

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5554]
https://github.com/zencart/zencart/blob/0c6e7c422cc7fe4b5252c310d62b90f22f12b206/includes/languages/english/lang.index.php#L3

https://github.com/zencart/zencart/blob/0c6e7c422cc7fe4b5252c310d62b90f22f12b206/includes/functions/functions_customers.php#L17

**Comment by scottcwilson** [comment]
Let's simplify by removing the additional parm from `includes/functions/functions_customers.php`.

**Comment by scottcwilson** [comment]
Would you please PR this @torvista ?
