### ISSUE TITLE
Making admin more senior friendly 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#5565]
What's the interest level in a change like the following. 

I have a client who needs larger icons and buttons on the admin.  So the categories/products listing icons look like this: 

![Screen Shot 2023-01-27 at 11 33 39 AM](https://user-images.githubusercontent.com/4391638/215141920-55463aa0-8513-4dd6-9a39-201371558ba6.jpg)

instead of this: 

![Screen Shot 2023-01-27 at 11 35 11 AM](https://user-images.githubusercontent.com/4391638/215142006-b71379db-3122-402d-9115-df7a7ee118ae.jpg)

**Comment by scottcwilson** [comment]
(Look at the status buttons on the left)

**Comment by torvista** [comment]
Is this not a job for Mr.CSS?

I have long done the opposite, with an override to remove/condense the large amounts of wasted space and infantile-sized texts.

**Comment by scottcwilson** [comment]
It can be done by CSS yes but the CSS required right now is pretty hairy.  Also in some cases (such as the product listing page), the size is specified in code (`fa fa-square fa-lg`).

**Comment by dbltoe** [comment]
adjusting the size is also a good idea to improve proximity on mobile devices.

**Comment by scottcwilson** [comment]
If either of you want to take this, just raise your hand.

**Comment by lat9** [comment]
Can't you (on Windows, I'm sure it's on those Apple devices, too), just press the Ctrl key while sliding your mouse to make the fonts larger?

**Comment by scottcwilson** [comment]
This makes *everything* larger, so it's really not an ideal solution.
