### ISSUE TITLE
/includes/classes/mysql/query_factory.php: `RecordCount` method uses undefined PHP function

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#5567]
The `queryFactory::RecordCount` method could potentially fall into a conditional execution branch that uses the undefined PHP function `mysqli_num_rows`. 

https://github.com/zencart/zencart/blob/70de0c7f26edbb833cf112ab36b1d5d9e718e30e/includes/classes/db/mysql/query_factory.php#L921-L931

**Comment by scottcwilson** [comment]
Why are you saying it's undefined?

https://www.php.net/manual/en/mysqli-result.num-rows.php

**Comment by lat9** [comment]
![image](https://user-images.githubusercontent.com/2685585/215274111-8bdefc05-fb40-4a4e-ae94-6f64a3c05393.png)
