### ISSUE TITLE
Admin: `orders.php` doesn't recognize an order paid via GV/DC

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#5593]
... as described in [this](https://www.zen-cart.com/showthread.php?229288-payment-module-(GV-DC)-no-longer-exists&p=1393039#post1393039) Zen Cart posting.

I just wanted to get it noted here, currently as a _possible_ bug, until I've got time to further explore.

**Comment by lat9** [comment]
Confirmed on zc158, current repository.  Place an order fully paid via Gift Voucher.  When viewing the order's details in the admin, you'll see the message indicated in that Zen Cart posting:
![image](https://user-images.githubusercontent.com/2685585/218117490-74e7cea2-fd2f-4b9e-9ff9-195ba91a3b98.png)

**Comment by proseLA** [comment]
you have an arbitrary hard coding of a payment module that does not exist as a payment method.  that is seen here:

https://github.com/zencart/zencart/blob/9194612d43538401a314fba1b1a1ba6b300b2e7e/includes/classes/order.php#L926

you then have a check for a payment method file which generates the message as seen here:

https://github.com/zencart/zencart/blob/9194612d43538401a314fba1b1a1ba6b300b2e7e/admin/orders.php#L512-L523

one could further refine the check in the admin file.  or go about and create an actual payment method.

**Comment by scottcwilson** [comment]
Suspect this fails for an order "paid" by any discount method.
