### ISSUE TITLE
View in Storefront from admin category/product listing

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#5595]
It would be helpful to have an easy way to open a product or category on the storefront in another window from admin, to double check copy, images, etc. 

<img width="245" alt="view1" src="https://user-images.githubusercontent.com/4391638/218258111-ba3433c4-f59d-49c5-b86d-7bbd8ba093a4.png">

<img width="279" alt="view2" src="https://user-images.githubusercontent.com/4391638/218258116-de7f4bb9-d426-4911-92d9-b57d47c5f9f3.png">

**Comment by scottcwilson** [comment]
You could use `fa-eye` as the icon.  

`<i class="fa fa-eye" aria-hidden="true"></i>`

**Comment by lat9** [comment]
... and what do you envision being displayed if the product is currently disabled?

An additional consideration would be if the site's using some form of analytics, where the page-view would be recorded but, if the product is disabled, would result in either a 301/410/404 HTML response code so that the product's organic search would go to the dustbin.

**Comment by scottcwilson** [comment]
I'd say gray out the eye if it's disabled.

**Comment by torvista** [comment]
> It would be helpful to have an easy way to open a product or category on the storefront in another window from admin, to double check copy, images, etc.

There already is:

![2023-02-11 15_32_13-Admin Category Product Listing — Mozilla Firefox](https://user-images.githubusercontent.com/4391026/218263588-0b83085c-e088-4eac-9cb8-aea20de7852d.gif)

**Comment by torvista** [comment]
The only disadvantage of this is that if using a url-rewriter, it has the friendly-url....so not appropriate if you want to copy the url into another product's description, which we do a lot. For that, I make the ID as a link using the native url.

**Comment by scottcwilson** [comment]
Good grief. In all my years of working with Zen Cart, I have never used that feature.  Thanks for the pointer.
