### ISSUE TITLE
Best-sellers' sidebox: PHP Fatal error based on store's configuration

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#5596]
As identified in [this](https://www.zen-cart.com/showthread.php?223910-ZCA-Bootstrap-4-Template-Support-Thread&p=1393037#post1393037) Zen Cart posting and the following response
![image](https://user-images.githubusercontent.com/2685585/218261893-d1711bba-19eb-4934-82df-4138c487cda0.png) ... the base `/includes/modules/sideboxes/best_sellers.php` invokes the template rendering if the minimum display of the best-sellers is configured as `0` and there are no best-sellers to display ... resulting in a PHP fatal error since the `$best_sellers` array is not initialized for that configuration.

**Comment by dbltoe** [comment]
I believe the 0 is the set default.  Setting the minimum to 1 works fine even when there are no best sellers to report.

**Comment by dbltoe** [comment]
What's strange is that the mysql_zencart.sql line 2459 is supposed to set that to 1 instead of 0
