### ISSUE TITLE
Include Ty Package Tracker Functionality

### ISSUE THREAD

**Issue by damon18** [zencart/zencart#56]
Feature Request for 1.6

Expand and improve the customer orders administration by including the features of the Ty Package Tracker into Zen Cart core.

I had noticed that COWOA is now included so I'm hoping there is a chance for package tracking. These two modules are both tedious to install and complicate upgrades, but the functionality is very desirable to many  sites.

Thanks for considering.

**Comment by drbyte** [comment]
> Is Github even the correct place for feature requests??

Yes, to some extent. Preferably only when working code is supplied with a PR accompanying said request. :)

**Comment by drbyte** [comment]
> shipping tracking as a core feature in Zen Cart might not be a bad idea

Agreed. Open to PRs ;)
