### ISSUE TITLE
Adding the `shipping_tax_rate` to the orders

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#5601]
I can't believe that I didn't submit this before, but there are various elements of processing (e.g. coupons) and plugins (e.g. Edit Orders) that can't properly do their job without knowing what (if any) tax percentage was applied to an order's shipping.

I propose that a `shipping_tax_rate` field `decimal(15,4) DEFAULT NULL be added to the `orders` table.  The `shipping` class would be updated to record the selected shipping method's tax-rate so that a decomposition of the order can be performed without various calculations that result in the penny-off rounding errors.

In the Zen Cart base, the coupon order-total could use that value when it's calculating the deduction for a shipping-included order.

**Comment by lat9** [comment]
It's already there; I'd forgotten to submit the change request so that the value would be in the base.

**Comment by drbyte** [comment]
Closed by #5893

**Comment by lat9** [comment]
Re-opening, since only the database portion has been completed.
