### ISSUE TITLE
admin, modules, product, collect_info_metatags: id is commented out

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5602]
While working on a mod that needed an id on this input field....I find there is already an id defined but commented out:

https://github.com/zencart/zencart/blob/bc7fd44f4d0a46a0204565e42f0024ed72edf57d/admin/includes/modules/product/collect_info_metatags.php#L150

unless someone can come up with a reason for this, I would PR them back in....

**Comment by lat9** [comment]
Interesting; that `id=` attribute has been commented-out going back further than 2018!  Not sure when that started.

**Comment by scottcwilson** [comment]
Please PR.

**Comment by torvista** [comment]
On checking further I see that all four collect_info_metatags.php files have the same three ids commented out:
![2023-06-30 10_52_03-zencart  D__GitHub_zencart  – …_admin_includes_modules_document_general_collect_](https://github.com/zencart/zencart/assets/4391026/dfc3fa0e-e518-45a4-8f29-975cceb7bee8)

There must have been some reason for that...???

**Comment by drbyte** [comment]
It's been commented-out since the metatags features were added in v1.2.5.

Feel free to add them in.
