### ISSUE TITLE
attribute controller: expand product name, remove price

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5615]
Is that lonely price of any use when the price is in the product name?
There is a lot of wasted space and the name has little.
![2023-02-16 18_32_35-Admin Attributes Controller — Mozilla Firefox](https://user-images.githubusercontent.com/4391026/219445165-0fd3318d-b9e1-4a73-9bbf-aa5ceceb23d0.gif)

How about
1) Bin the price
2) expand the name and button to columns 10:2
3) expand the box to a few lines, here it's 5.
4) and, controversially no doubt, make click-on-the-select as a submit/show the Display button only for noscript

![image](https://user-images.githubusercontent.com/4391026/219445109-112f0794-9419-4074-81f1-4e4ee9c29409.png)

**Comment by scottcwilson** [comment]
I'd rather not pursue this.
