### ISSUE TITLE
cart->contents product_id keys may be integer or string: fatal error in zen_get_prid(): for strict types

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5617]
As is my wont, I scatter declare(strict_types=1); about in an attempt to catch my errors and sometimes others.
I find that adding this line to functions_products results in a fatal error in the shopping cart.
It is due to the cart contents product_id used as array key being integer for simple products and string for attribute-products:
eg:

> $this->contents (array):
> Array
> (
>     [24] => Array
>         (
>             [qty] => 1
>         )
> >     [1:edff669e5da95c1d027b04d5412532fa] => Array
>         (
>             [qty] => 1
>             [attributes] => Array
>                 (
>                     [3] => 5
>                     [4] => 1
>                 )
>         )
>     [25] => Array
>         (
>             [qty] => 1
>         )
>     [26:e5bc27b15180c1c193200009aa5ba99c] => Array
>         (
>             [qty] => 3
>             [attributes] => Array
>                 (
>                     [3] => 5
>                     [4] => 1
>                 )
>         )
> )

> $products_id (integer):
> 24
> $products_id (string):
> 1:edff669e5da95c1d027b04d5412532fa
> $products_id (integer):
> 25
> $products_id (string):
> 26:e5bc27b15180c1c193200009aa5ba99c

When the cart checks stock, it fails with

>  PHP Fatal error:  Uncaught TypeError: zen_get_prid(): Argument #1 ($uprid) must be of type string, int given,

due to 
`function zen_get_prid(string $uprid)`

In class shopping->add_cart I see that the product_ids as keys all "go in" as strings but I (eventually) discovered that php with respect to keys, makes numbers that "appear" to be integers as integer keys, so they "come out" mixed.

While removing the type hint on function zen_get_prid will allow this to proceed, I thought it may be something to be documented/considered/dealt with.

**Comment by lat9** [comment]
Unfortunately, the `mixed` type declaration wasn't a PHP 'thing' until 8.0.0 (https://www.php.net/manual/en/language.types.declarations.php)

**Comment by torvista** [comment]
I just thought the fact that array keys may not maintain their type could be a gotcha at some point.
