### ISSUE TITLE
php error in developers toolkit

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#5620]
Newest version of all merges including the new developers_tool_kit.php results in a partial blank page and the following.

```
[22-Feb-2023 14:34:29 UTC] PHP Fatal error: Uncaught Error: Undefined constant "TEXT_ALL_FILES_LOOKUP_CURRENT_LARAVEL" in /frammer1/developers_tool_kit.php:1113
Stack trace:
#0 /frammer1/index.php(11): require()
#1 {main}
thrown in /frammer1/developers_tool_kit.php on line 1113

[22-Feb-2023 14:34:29 UTC] Request URI: /frammer1/index.php?cmd=developers_tool_kit, IP address: 218.645.249.247
--> PHP Fatal error: Uncaught Error: Undefined constant "TEXT_ALL_FILES_LOOKUP_CURRENT_LARAVEL" in /frammer1/developers_tool_kit.php:1113
Stack trace:
#0 /frammer1/index.php(11): require()
#1 {main}
thrown in /frammer1/developers_tool_kit.php on line 1113.
```

**Comment by lat9** [comment]
Are you sure you also grabbed the associated language-file update:
![image](https://user-images.githubusercontent.com/2685585/220660998-eb519440-b3fc-4671-859d-e280b794a0c5.png)

**Comment by dbltoe** [comment]
I don't find that file in 1.5.8 or 1.5.8a distro

**Comment by dbltoe** [comment]
![image](https://user-images.githubusercontent.com/5122886/220670829-3570a36b-275e-4142-8874-c5b50bab3a60.png)
That is the most current file as well

**Comment by scottcwilson** [comment]
Loading the page 
http://localhost:8888/gh_demo_158/admin/index.php?cmd=developers_tool_kit
works correctly for me with no log in PHP 8.1.

**Comment by dbltoe** [comment]
UPDATE
Somehow, my compare lost the two changes to the file in the lines of my trifocals.
Loaded the update mentioned by lat9 and it is now working correctly.
