### ISSUE TITLE
Responsive Classic, Edit shipping & payment address: Continue button and text do not coincide

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5623]
![2023-02-23 11_36_37-Change Shipping Address _ Zen Cart!, The Art of E-commerce — Mozilla Firefox](https://user-images.githubusercontent.com/4391026/220884986-f65d5fa5-dcb6-4278-b97a-5befae3c39a8.gif)

**Comment by scottcwilson** [comment]
Please PR.

**Comment by torvista** [comment]
On the checkout pages, the Continue items are inside the form.
On the edit address pages, there may be two forms, and the Continue items are outside/after the forms.
Not easily done that I can see.
