### ISSUE TITLE
`zc_install`, on initial install, should limit characters used for DB_PREFIX

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#5636]
MySQL table- and field-names _can_ contain a hyphen (and other non-alphanumeric and underscore) characters, but that usage requires the consistent use of backticks (`) around those non-standard names. However, the Zen Cart base (as well as 99.99% of the plugins) don't backtick consistently; that's why a hyphen cannot be used in a database prefix.

From [https://dev.mysql.com/doc/refman/8.0...ntifiers.html:](https://dev.mysql.com/doc/refman/8.0/en/identifiers.html:)

> An identifier may be quoted or unquoted. If an identifier contains special characters or is a reserved word, you must quote it whenever you refer to it. (Exception: A reserved word that follows a period in a qualified name must be an identifier, so it need not be quoted.) Reserved words are listed at [Section 9.3, “Keywords and Reserved Words”](https://dev.mysql.com/doc/refman/8.0/en/keywords.html).
> 
> Internally, identifiers are converted to and are stored as Unicode (UTF-8). The permissible Unicode characters in identifiers are those in the Basic Multilingual Plane (BMP). Supplementary characters are not permitted. Identifiers thus may contain these characters:
> 
> 
> - Permitted characters in unquoted identifiers:
>    - ASCII: [0-9,a-z,A-Z$_] (basic Latin letters, digits 0-9, dollar, underscore)
>    - Extended: U+0080 .. U+FFFF 
> 
> - Permitted characters in quoted identifiers include the full Unicode Basic Multilingual Plane (BMP), except U+0000:
>   - ASCII: U+0001 .. U+007F
>   - Extended: U+0080 .. U+FFFF 
> 
> - ASCII NUL (U+0000) and supplementary characters (U+10000 and higher) are not permitted in quoted or unquoted identifiers.
> - Identifiers may begin with a digit but unless quoted may not consist solely of digits.
> - Database, table, and column names cannot end with space characters.
> - Beginning with MySQL 8.0.32, use of the dollar sign as the first character in the unquoted name of a database, table, view, column, stored program, or alias is deprecated and produces a warning. This includes such names used with qualifiers (see [Section 9.2.2, “Identifier Qualifiers”](https://dev.mysql.com/doc/refman/8.0/en/identifier-qualifiers.html)). The dollar sign can still be used as the leading character of such an identifier when it is quoted according to the rules given later in this section.

Since Zen Cart uses unquoted identifiers, I suggest that `zc_install`, on initial installation, limit the characters used for the `DB_PREFIX` to `[0-9,a-z,A-Z$_]`, with the further limitation that the `$` be disallowed for the first character.

**Comment by scottcwilson** [comment]
Or maybe prefix should not be supported on new installs, since it's an anachronism from a time long long ago.

**Comment by scottcwilson** [comment]
The "Frozen" release of osCommerce removed this feature.   We have to support it for upgrades, but there's no need for new installs.

**Comment by lat9** [comment]
I've seen sites that _do_ use the prefix so as to distinguish between multiple CRMs using the same database, so I'm not a fan of removing it.

**Comment by scottcwilson** [comment]
Those would not be affected by a change targeting initial install time checking.

I would hate to see someone spending time on this when there are so many other issues that actually affect people that need work.

**Comment by drbyte** [comment]
I'm thinking that the easiest "fix" for this would probably just be to apply a regex match against the user-input-db-prefix, stripping out any characters we don't want to support, and storing that "cleaned" string as the DB_PREFIX in the configuration.php file.

**Comment by scottcwilson** [comment]
I REALLY don't want any development resources spent on this.
