### ISSUE TITLE
admin, category-product listing, search with no keyword: debug logs for undefined variable error

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5666]
> [25-Mar-2023 11:42:21 UTC] Request URI: /zencart/admin/index.php?cmd=category_product_listing&search=, IP address: 127.0.0.1, Language id 1
> #0 [internal function]: zen_debug_error_handler()
> #1 D:\GitHub\zencart\includes\functions\functions_search.php(211): substr()
> #2 D:\GitHub\zencart\admin\category_product_listing.php(545): zen_build_keyword_where_clause()
> #3 D:\GitHub\zencart\admin\index.php(11): require('D:\\GitHub\\zenca...')
> --> PHP Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated in D:\GitHub\zencart\includes\functions\functions_search.php on line 211.

> [25-Mar-2023 11:42:21 UTC] Request URI: /zencart/admin/index.php?cmd=category_product_listing&search=, IP address: 127.0.0.1, Language id 1
> #0 D:\GitHub\zencart\includes\functions\functions_search.php(211): zen_debug_error_handler()
> #1 D:\GitHub\zencart\admin\category_product_listing.php(545): zen_build_keyword_where_clause()
> #2 D:\GitHub\zencart\admin\index.php(11): require('D:\\GitHub\\zenca...')
> --> PHP Warning: Undefined variable $where_str in D:\GitHub\zencart\includes\functions\functions_search.php on line 211.

**Comment by torvista** [comment]
This is not fixed by the link referenced.

**Comment by scottcwilson** [comment]
Finger trouble.  Thanks for catching.
