### ISSUE TITLE
`functions_email.php`, refactoring needed

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#5671]
The various functions in the subject file contain a slew of one-line-if statements, e.g.
```php
if (!isset($block['EMAIL_SPAM_DISCLAIMER']) || $block['EMAIL_SPAM_DISCLAIMER'] == '')   $block['EMAIL_SPAM_DISCLAIMER']  = EMAIL_SPAM_DISCLAIMER;
```
... as well as other currently non-standard formatting.  Since that file's been updated for the current release, let's take the opportunity to prettify it!

**Comment by scottcwilson** [comment]
Closed by #5682
