### ISSUE TITLE
Admin, Coupon Restrict: product selection dropdown not filtered, includes products already selected

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5676]
![2023-03-30 11_48_25-Admin Coupon Restrict](https://user-images.githubusercontent.com/4391026/228797884-c2eeed97-692e-496c-a89f-fcb9130f06d2.gif)

**Comment by proseLA** [comment]
close it @torvista !!  u can do it! :wink:

**Comment by torvista** [comment]
fixed in https://github.com/zencart/zencart/pull/5677
