### ISSUE TITLE
observer/notifiers not working...

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#5679]
there are a bunch of notifiers in the shopping cart class that do not work.  i have tested this with latest v158, and the test data.

proof:  create a file on the storefront with the following name and directory structure:

includes/classes/observers/auto.serial_number.php

in that file, add the following content:

```
<?php
    class zcObserverSerialNumber extends base
    {
        public function __construct()
        {
            $this->attach($this, [
                'NOTIFIER_CART_ADD_CART_START',
                'NOTIFIER_CART_INSTANTIATE_START'
            ]);
        }

        public function update(&$class, $eventID, &$p1, &$p2, &$p3, &$p4, &$p5, &$p6, &$p7)
        {
            switch ($eventID) {
                case 'NOTIFIER_CART_ADD_CART_START':
                    die('<br>' . __FILE__ . ':' . __LINE__);
                case 'NOTIFIER_CART_INSTANTIATE_START':
                    die('<br>' . __FILE__ . ':' . __LINE__);
                default:
                    break;
            }
        }
    }
```
now, go to any product page and you should see something like:
`/var/www/zcdev/includes/classes/observers/auto.serial_number.php:18`

now, comment that line 18 out (it is the die statement after the `NOTIFIER_CART_INSTANTIATE_START`).  and go ahead and add anything to your cart.  if you have your debugger installed you will see that you hit line this line:
https://github.com/zencart/zencart/blob/2b09206a713c7241007c16acfb7ea28fe824d053/includes/classes/shopping_cart.php#L274
but, the die statement is not hit in observer.  and it should be.

**Comment by scottcwilson** [comment]
Possibly the issue described in https://docs.zen-cart.com/dev/code/notifiers/#auto-loaded-observers 

Note: This technique will work so long as your class doesn’t have any special requirements on its load point (auto-loaded classes are loaded at point 175, after all other system dependencies are loaded). Most observers won’t need to be loaded “before” all other regular dependencies, so load-point 175 is fine in most cases. If your observer needs to be loaded earlier, then don’t use this special naming convention, but instead manual loading, which is described below. An example of a notifier whose observer should not use auto loading is ZEN_GET_PRODUCTS_STOCK. This fires from the shopping cart class, which has a load point of 80. If you need to observe this notifier, you will want to load earlier than 80.

**Comment by scottcwilson** [comment]
If you look at GA4, it handles this situation by not using an auto loader but rather loading it manually. 

https://www.zen-cart.com/downloads.php?do=file&id=2368

**Comment by proseLA** [comment]
@scottcwilson i will take a look.  while i have manually loaded observers before, i prefer the ease of the auto-loader. 

what makes no sense to me is i have given an example where it fires on 1 notifier on the shopping cart class, but not the other.  so i'm not sure why an earlier load point is needed for 1 notifier but not the other.  they are in the same class.

but i will test and report back when able.

**Comment by lat9** [comment]
When the "Add to Cart" button is clicked on a product information page, that results in a posted redirect with the $_GET variable `action` set to `add_to_cart`.  That `action` is intercepted by `init_cart_handler.php` which loads at **CP 140** and, for that action, will fall through and load `/includes/main_cart_handler.php`.

The `main_cart_handler.php` calls the cart's `actionAddProduct` method which, in turn, calls the cart's `add_cart` method (for a newly added product) which is where that notifier gets fired.

That's a long-winded way of agreeing with @scottcwilson, since autoloaded observers are loaded at **CP 175** which is after the `add_to_cart` action was previously processed and redirected.

**Comment by proseLA** [comment]
earlier than 140 is correct.  139 works.  140 does not.

thanks.

**Comment by lat9** [comment]
> earlier than 140 is correct. 139 works. 140 does not.
> 
> thanks.

Right, that's because any addition at CP 140 will be loaded **_after_** init_cart_handler.php and, thus, won't be listening when the notification fires.
