### ISSUE TITLE
`account_edit`: Desktop DOB formatting incorrect for dd/mm/yyyy

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#5685]
If a site uses the 'alternate' date-formatting (dd/mm/yyyy) and follows the [documented](https://docs.zen-cart.com/user/localization/changing_date_format_157/) instructions:

1. A customer is correctly enabled to enter their DOB on the create-account page using dd/mm/yyyy formatting.
2. The DOB is properly recorded in the database using YYYYMMDD format.
3. The customer's DOB is displayed in dd/mm/yyyy format when an admin views/edits the customer's record.
4. The customer's DOB **is still displayed in mm/dd/yyyy format** when they view their account details in the `account_edit` page:

![image](https://user-images.githubusercontent.com/2685585/229836961-e11c36aa-fb2e-4e9f-b8af-8e5d5a783bb8.png)

The issue was introduced in PR #2337 and I'm not sure what the repercussions of changing the format to reflect the language's format will be.

**Comment by torvista** [comment]
4. appears to be yyyy/mm/dd

**Comment by lat9** [comment]
> 4. appears to be yyyy/mm/dd

... and that's the issue; the date should display as yyyy/dd/mm ... shouldn't it?

**Comment by scottcwilson** [comment]
This is sortable date format, so it should be ok for both UK and US style dates.  I don't think this is a bug.

**Comment by lat9** [comment]
OK, it just looked "off" to me.  Thanks for the clarification.
