### ISSUE TITLE
functions_email: strict error: PHP Fatal error:  str_replace(): Argument #2 ($replace) must be of type array|string, int given

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5689]
Using declare(strict_types=1), php 8.2.3,  strict mode, checkout_confirmation, responsive_classic
PHP Fatal error:  Uncaught TypeError: str_replace(): Argument #2 ($replace) must be of type array|string, int given in ...\includes\functions\functions_email.php:759
https://github.com/zencart/zencart/blob/310f54aba597e2b867dde31585ffee0f5832bba3/includes/functions/functions_email.php#L757-L760

This is when the $value of INTRO_ORDER_NUMBER is parsed, which is an integer from here

https://github.com/zencart/zencart/blob/310f54aba597e2b867dde31585ffee0f5832bba3/includes/classes/order.php#L1316

and created here
https://github.com/zencart/zencart/blob/310f54aba597e2b867dde31585ffee0f5832bba3/includes/classes/order.php#L946

**Comment by torvista** [comment]
I just cast it to string.

**Comment by scottcwilson** [comment]
Please PR.
