### ISSUE TITLE
No insert option in admin when manufacturers list is empty

### ISSUE THREAD

**Issue by simon1066** [zencart/zencart#5699]
**Describe the bug**
In ZC v1.5.8a, if the manufacturers list in admin is empty (as would happen if ZC was installed without demo data) then the `Insert` button is not present. There is therefore no method for subsequently adding a new manufacturer.
Issue raised in this thread, https://www.zen-cart.com/showthread.php?229417-Manufacturers-(v1-5-8a)

**Version**
Zen Cart version: 1.5.8a
PHP version: 8
What older/newer versions were also tested? Issue not present in v1.5.8

**To Reproduce**
1. Install ZC without demo products or delete all existing manufacturers
2. Go to admin > catalog > manufacturers
3. No 'insert' button present

**Expected behavior**
1. Install ZC without demo products or delete all existing manufacturers
2. Go to admin > catalog > manufacturers
3. 'insert' button should be present

Bear with me and I will see if I can resolve this,

**Comment by simon1066** [comment]
Could someone please check if this is an acceptable solution?

Line 329 in `admin\manufacturers.php`, where the insert button is rendered. 

From
```php
      <?php if (empty($action) && !empty($mInfo)) { ?>
        <div class="col-sm-12 text-right">
          <a href="<?php echo zen_href_link(FILENAME_MANUFACTURERS, ($currentPage != 0 ? 'page=' . $currentPage . '&' : '') . 'mID=' . $mInfo->manufacturers_id . '&action=new'); ?>" class="btn btn-primary" role="button"><?php echo IMAGE_INSERT; ?></a>
        </div>
      <?php } ?>
```
To
```php
      <?php
      $mInfo = null;      
      if (empty($action)) { ?>
        <div class="col-sm-12 text-right">
          <a href="<?php echo zen_href_link(FILENAME_MANUFACTURERS, ($currentPage != 0 ? 'page=' . $currentPage . '&' : '') . 'mID=' . $mInfo?->manufacturers_id . '&action=new'); ?>" class="btn btn-primary" role="button"><?php echo IMAGE_INSERT; ?></a>
        </div>
      <?php } ?>
```
Other than the change/addition to the first line also note that  `$mInfo->manufacturers_id` is changed to `$mInfo?->manufacturers_id`

**Comment by lat9** [comment]
Better, I think, to
```php
      <?php
      if (empty($action)) {
        $current_mid = (isset($mInfo)) ? 'mID=' . $mInfo->manufacturers_id : '';
     ?>
        <div class="col-sm-12 text-right">
          <a href="<?php echo zen_href_link(FILENAME_MANUFACTURERS, ($currentPage != 0 ? 'page=' . $currentPage . '&' : '') . $current_mid . '&action=new'); ?>" class="btn btn-primary" role="button"><?php echo IMAGE_INSERT; ?></a>
        </div>
      <?php } ?>
```

Note that the nullsafe operator (`?=`) wasn't introduced until PHP 8.0 and zc158 still supports PHP versions down 7.3.

**Comment by simon1066** [comment]
Thank you. Using that code throws a `Undefined array key "mID"` warning further up the file at my line no. 262
```
$contents[] = ['align' => 'text-center', 'text' => '<button type="submit" class="btn btn-primary">' . IMAGE_SAVE . '</button> <a href="' . zen_href_link(FILENAME_MANUFACTURERS, ($currentPage != 0 ? 'page=' . $currentPage . '&' : '') . 'mID=' . $_GET['mID']) . '" class="btn btn-default" role="button">' . IMAGE_CANCEL . '</a>'];
```
Would it be correct to change the `. 'mID=' . $_GET['mID']) . ` in that line to
`. 'mID=' . (!empty($_GET['mID']))) .` or perhaps `. 'mID=' . ($_GET['mID'] ?? '')) .` ?

**Comment by simon1066** [comment]
Sorry, I haven't quite grasped how that screenshot relates to the `mID` section on line 262. 

I've just been working out what all of the `mID`'s are used for. The `$_GET['mid']` in line 262 is used to add the `mID` of the _selected_ manufacturer to the URL of the Cancel button that shows after clicking Insert. Clicking Cancel then returns to that exact screen.  Without it Cancel would always return you to the manufacturers page with the top most id selected.  So I think there is still a use case for leaving it in.

**Comment by simon1066** [comment]
`<a href="<?php echo zen_href_link(FILENAME_MANUFACTURERS, ($currentPage != 0 ? 'page=' . $currentPage . '&' : '') . $current_mid . '&action=new'); ?>" class="btn btn-primary" role="button"><?php echo IMAGE_INSERT; ?></a>`

It has been noted that I need to move the `&` out of `&action=new`, into `$current_mid`, to prevent double `&&` in some cases and a missing `&` in other cases. I believe I can do that but I would ideally like to understand under what circumstances could I get the extra/deficient `&`, perhaps someone could enlighten me. Thanks.

**Comment by proseLA** [comment]
both problems will happen if `$current_mid` is blank.

**Comment by simon1066** [comment]
I had considered that but couldn't think of any scenario when the `$current_mid` could be blank. If  `$current_mid` is the `manufacturers_id` then that will surely always be present.

```
<?php
      if (empty($action)) {
        $current_mid = (isset($mInfo)) ? 'mID=' . $mInfo->manufacturers_id : '';
     ?>
        <div class="col-sm-12 text-right">
          <a href="<?php echo zen_href_link(FILENAME_MANUFACTURERS, ($currentPage != 0 ? 'page=' . $currentPage . '&' : '') . $current_mid . '&action=new'); ?>" class="btn btn-primary" role="button"><?php echo IMAGE_INSERT; ?></a>
        </div>
      <?php } ?>
```

**Comment by proseLA** [comment]
what does that have to do with anything?  not being able to think of a scenario where that could happen is not reason to code it the way that you are talking.  some bot will find out how to do it.

**Comment by drbyte** [comment]
@proseLA wrote:
> for what is the `$_GET['mid']` even going to be used?

Usually the `page=` and `mid=` (or `cid=`, `pid=`, etc) param are combined to ensure that the displayed list of manufacturers (or whatever list) is rendered not only with the correct results for the current subset of "paginated items" for the specified page, but also so that the cursor/highlighted item is selected within that page.

So yes, while the `mid=` would be moot if there are no other manufacturers, it is indeed relevant when adding a new one when others do exist.
