### ISSUE TITLE
States pull down menu error when creating account

### ISSUE THREAD

**Issue by piloujp** [zencart/zencart#5707]
**Describe the bug**
With a Zen Cart fresh install v1.5.8, v1.5.8a and probably lower, when submitting create account form message  'Please select a state from the States pull down menu.' appear although state field (input text) has been properly filled.

**Version**
Zen Cart version: 1.5.8a
PHP version: 8.2
MySQL version: 8.032
Plugins that may be related: none
What older/newer versions were also tested? 1.5.8

**To Reproduce**
With default install (option Configuration->Customers Details->State field - Display as pulldown when possible? set to false).
1. Go to 'login/Create account' page
2. Fill the form setting country to 'United States', or any country that has zones defined, and submit it.

**Expected behavior**
Create a new account and log in.

**Screenshots**
If applicable, add screenshots to help explain.

**Debug/Error Logs**
 'Please select a state from the States pull down menu.' pop up message.
 
**Additional context**
If admin setting 'Configuration->Customers Details->State field - Display as pulldown when possible?' is set to true or if chosen country has no zone defined, problem disappears, form is accepted normally as a dropdown option has bee chosen. But when country has zones defined but input text is used in form them message popup when submitting and you can't create an account.
Same problem occurs when adding a new address at checkout or in 'My Account->address book', files 'create_account.php' and 'checkout_new_address.php'.

**Fix**
Changing line 201 in 'includes/modules/create_account.php' from:
if ($entry_state_has_zones == true) {
to
if ($entry_state_has_zones == true && ACCOUNT_STATE_DRAW_INITIAL_DROPDOWN === 'true') {

And Changing line 82 in 'includes/modules/checkout_new_address.php' from:
if ($entry_state_has_zones == true) {
to
if ($entry_state_has_zones == true && ACCOUNT_STATE_DRAW_INITIAL_DROPDOWN === 'true') {
will fix the problem.

**Comment by torvista** [comment]
https://github.com/zencart/zencart/issues/1665

https://github.com/zencart/zencart/issues/4858

**Comment by piloujp** [comment]
Is it OK if I PR this?
It is straight forward, just adding a test for State pull down menu setting which was not taken in account.

**Comment by scottcwilson** [comment]
Go for it

**Comment by piloujp** [comment]
Done but unfortunately commit was added first to yesterday' PR #5710. I did a new separate PR and I think was able to delete two files added by error.
Please check.

**Comment by scottcwilson** [comment]
This is a super SUPER easy mistake to make, that I myself have made many times. 

The easiest way to fix it is to close the PR and create a new one.

**Comment by scottcwilson** [comment]
Note: PR is #5711.
