### ISSUE TITLE
spiffyCal "Wonky" Display for 6-week Months

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#5713]
I don't know if it's the current date (2023-04-23, in a month that starts on a Saturday and ends on a Sunday so there should be 6 'rows' of calendar), but viewing the spiffyCal display in the admin's Salemaker tool doesn't display correctly:
![image](https://user-images.githubusercontent.com/2685585/233856410-7c7be688-d238-438b-8181-7a44ddfc8158.png)

To reproduce with the demo products, go to `Catalog :: Salemaker` and click on the down-caret icon to display a date for either the Starting or Ending dates.   Noting that it's going to be date and month-dependent!

**Comment by torvista** [comment]
Time to finally bin this relic?

**Comment by lat9** [comment]
Noting that the datepicker implementation works flawlessly!

**Comment by piloujp** [comment]
I found a bug in spiffyCal_v2_1.js, a " is missing on line 876.
`strOutput += '<td class="cal-HeadCell text-center align-middle>' + msDOW[intLoop] + '<\/td>';`
It should be:
`strOutput += '<td class="cal-HeadCell text-center align-middle**"**>' + msDOW[intLoop] + '<\/td>';`
With this corrected, calendar displays OK.
