### ISSUE TITLE
About products_price_manager.php, the update price is very slow

### ISSUE THREAD

**Issue by Jerry-Freelancer** [zencart/zencart#5714]
**Describe the bug**
I update the price of a product on zen cart's web page, which is very slow and takes about 10 seconds to complete.
I checked products_price_manager.php. At the end, there is the following SQL.

These SQL do not use limit, which leads to the return of hundreds of thousands of data sets. Is this the reason for the slow front-end update?

$productsSpecial = $db->Execute("SELECT p.products_id,
s.specials_id, s.specials_new_products_price, s.expires_date, s.specials_date_available, s.status
FROM " . TABLE_PRODUCTS . " p,
" . TABLE_SPECIALS . " s
WHERE p.products_id = s.products_id
AND s.products_id = " . (int)$_GET['products_filter']);

 $products = $db->Execute("SELECT p.products_id, p.products_model,
                                        p.products_price, p.products_date_available,
                                        p.products_tax_class_id,
                                        p.products_quantity_order_min, products_quantity_order_units, p.products_quantity_order_max,
                                        p.product_is_free, p.product_is_call, p.products_quantity_mixed, p.products_priced_by_attribute, p.products_status,
                                        p.products_discount_type, p.products_discount_type_from, p.products_price_sorter,
                                        pd.products_name,
                                        p.master_categories_id, p.products_mixed_discount_quantity
                                 FROM " . TABLE_PRODUCTS . " p,
                                      " . TABLE_PRODUCTS_DESCRIPTION . " pd
                                 WHERE p.products_id = " . (int)$_GET['products_filter'] . "
                                 AND p.products_id = pd.products_id
                                 AND pd.language_id = " . (int)$_SESSION['languages_id']);

**Version**
Zen Cart version: 1.5.7C
PHP version: 7.4.33
MySQL version: 5.7.42
Plugins that may be related: 
What older/newer versions were also tested?

**Comment by scottcwilson** [comment]
If you have hundreds of thousands of products, you're going to have to get a VPS and fine-tune your hosting.  This is not an issue with core code.

**Comment by Jerry-Freelancer** [comment]
您的邮件，我已接收。
