### ISSUE TITLE
Admin, product-update no longer saves date_available

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#5716]
zc158a, plus current updates, PHP 8.2 with demo products.  Navigate to **_Catalog :: Categories/Products_**, choose and existing product and edit it.

Click on the **Date Available** field, bringing up the datepicker.  Choose today's date, which gets recorded in the input field.  Click **Preview** and then **Update**.

Edit the product again and notice that the **Date Available** field is unchanged.

No debug-logs are generated.

**Comment by lat9** [comment]
My bad; it has to be a date **_later than today_**.

**Comment by torvista** [comment]
Is it not possible to grey out the datepicker up to and including today?

**Comment by drbyte** [comment]
> Is it not possible to grey out the datepicker up to and including today?

https://api.jqueryui.com/datepicker/#option-minDate

https://github.com/zencart/zencart/blob/078b509bb514ab344a034e89508eb02f1e63854c/admin/product.php#L111-L116

https://github.com/zencart/zencart/blob/078b509bb514ab344a034e89508eb02f1e63854c/admin/includes/modules/update_product.php#L18-L27

**Comment by torvista** [comment]
This seems to do the job:
```
<!-- script for datepicker -->
    <script>
      $(function () {
        $('input[name="products_date_available"]').datepicker({
            minDate: 1
        });
      })
    </script>
```
![image](https://user-images.githubusercontent.com/4391026/234776475-568176ec-8e06-4360-b88f-e9f90c997d33.png)
