### ISSUE TITLE
Do not allow ampersand in filename?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5721]
While tracking down a feed generation problem, I discovered some images with an ampersand in the filename, which were causing DomDocument createElement to choke. I never would have thought that ampersands were allowed in filenames, but evidently they are in some environments.

Subsequently I found that file_exists returns false for a filename with an ampersand in it.

So, there seems to be a case for not permitting image filenames at least, to be assigned for products.
I would surmise that this check should be extended to any links to files such as downloads.

**Comment by scottcwilson** [comment]
Not going to pursue.
