### ISSUE TITLE
$db, should it just `die()` when the database connection fails?

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#5722]
Having an issue with one of my sites' servers, where the initial problem is reported as a PHP Warning:
```
[02-May-2023 13:14:55 America/Chicago] Request URI: /search-results?search_in_description=1&keyword=altemp&inc_subcat=0&page=1&sort=2d, IP address: xx.xx.xx.xx
#1  mysqli_connect() called at [/home/mysite/public_html/includes/classes/db/mysql/query_factory.php:64]
#2  queryFactory->connect() called at [/home/mysite/public_html/includes/init_includes/init_database.php:24]
#3  require(/home/mysite/public_html/includes/init_includes/init_database.php) called at [/home/mysite/public_html/includes/autoload_func.php:48]
#4  require(/home/mysite/public_html/includes/autoload_func.php) called at [/home/mysite/public_html/includes/application_top.php:170]
#5  require(/home/mysite/public_html/includes/application_top.php) called at [/home/mysite/public_html/index.php:26]
--> PHP Warning: mysqli_connect(): (HY000/2002): No such file or directory in /home/mysite/public_html/includes/classes/db/mysql/query_factory.php on line 64.
```
This then leads to 9Kb+ log files created on each site access (and it's a busy site) for as long as the database issue's present.

If the `mysqli_connect` isn't successful, shouldn't the page-load just 'die'?

**Comment by drbyte** [comment]
Probably fine. 
There will probably be other ripple-effects from doing so, such as pages that fail to fully draw (eg: missing right-columns, missing footers, etc). And ajax-calls won't return a fail response, which may mean they hang until timeout. Granted, sometimes a db warning of this nature also results in other fatal php errors afterward, which of course has the same side-effects.

**Comment by lat9** [comment]
Maybe a redirect to `nddbc.html` in that case?

**Comment by drbyte** [comment]
There's already `$dieOnErrors`. Perhaps that can be leveraged?

**Comment by scottcwilson** [comment]
> If the mysqli_connect isn't successful, shouldn't the page-load just 'die'?

Dealing with these logs is aggravating and a big waste of time.  Can you try this fix on your busy site and see if it helps?  If so I think this would be the simplest and best way forward.
