### ISSUE TITLE
Fix CSS/styling of Admin for LEAD pages

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#573]
On the pages which use Foundation for grid/css/ajax, fresh styling is needed.

On the pages which have not yet been converted away from nested tables, some compatibility styling needs to be added, as there are display problems with margins and fonts.

**Comment by jtwebsitedesign** [comment]
This sounds like something I could really help with, if you'd like me to give it a shot?

**Comment by drbyte** [comment]
Sure. Initial focus should be:
- [ ] Pages using the new LEAD layout such as everything under "Locations/Taxes" and "Localization" menus. These are all using Foundation as the CSS framework. The look/feel is just the out-of-the-box Foundation styling, which hasn't experienced a Designer's love yet. 
- [ ] Home Page  (has some jQuery UI stuff, uses ajax for the widgets, and Foundation)
- [ ] All the other pages share a pretty common layout (table stuff), and the Foundation/Normalize stuff has interfered with a bit of how they appear. The preference is to keep the Foundation/Normalize stuff, and repair what components it's interfering with by making those interfered-with things cooperate.

**Comment by jtwebsitedesign** [comment]
Ok sounds great. Just give me a little time to review those coding standards and setup, then I'll jump right in!

**Comment by barco57** [comment]
at the bottom of normalize.css is the following:

````
td,
th {
  padding: 0;
}
````

adding to the bottom of stylesheet.css

````
td,
th {
  padding: 2px;
}
````
Seems to solve 99% of the issues I have seen, and doesn't appear to affect the new LEAD pages as far as I can tell.

**Comment by drbyte** [comment]
Yup, that certainly helps with the table stuff. I've initiated pull request #609 with that change.

**Comment by IronLady** [comment]
Add a little touch to the fonts would be nice. Maybe use a google fonts.

```css
@import url(https://fonts.googleapis.com/css?family=Open+Sans:400,700);

body {
    font-family: 'Open Sans', sans-serif;
}
```

**Comment by jtwebsitedesign** [comment]
My apologies for taking so long on this. It took a little time to get setup, and then I got quite busy these past few weeks. Anyhow, I've made some changes and submitted a pull request. A couple notes:

- I mostly focused on the first item on your list: Locations/Taxes and Localization, as well as a few general edits to repair interfering components.

- I normalized the line endings, as described here (without this, my changes were replacing entire files): https://help.github.com/articles/dealing-with-line-endings/

- I touched quite a few files, removing or adding classes and cleaning up little bits of code where necessary. Core functionality was not changed in any case, just the styling of the elements.

- foundation.min.css didn't seem to have a non-minified counterpart, so I just made a few changes right in the file. Unfortunately git shows that the whole file changed :/

- The tables seem to look nicer without the code found in zen-foundation-reset.css. I removed all the code for now, but perhaps you would prefer to remove the file?

- I restyled the admin header/menu to match the LEAD pages. I realize this is outside the scope of this ticket, but it seemed an important factor to make the LEAD pages look really good.

And of course, if you would like me to make separate pull requests or commits, or reverse any other changes, just let me know. I'm here if you have any questions!

**Comment by drbyte** [comment]
Hi Jackie, thanks for this!

A couple changes would make this easier to integrate:

- [ ] can you split the normalizing of line-endings into a separate pull-request? (that means you'd need to create separate branches for the line-endings thing, and another for your admin re-styling work).  This will help us because it's important to ensure that a "formatting-only" change should not change anything else, but since you've got both sets of commits in the same branch it muddies things up :(

- [ ] In fact, if you simply create a new branch and commit your CSS/styling changes to that branch, and do a PR from that branch, that's the first starting point we need. And, to view diffs of those files in github without it showing "the whole file changed", you can open the diff page on github, and add &w=0 to the end of the URL and press Enter, and it'll show the diffs while ignoring the line-endings. 

- [ ] We really don't want to ever change the `foundation.min.css` file (because it's created by someone else, and changing it means upgrades are really hard).  Instead, you could use the zen-foundation-reset.css (and feel free to rename the file to something like maybe `zen-foundation-base.css`?) to insert some overrides that do the same "fixes" that you did in the `foundation.min.css` file.

**Comment by jtwebsitedesign** [comment]
Sounds good. I just submitted a pull request for the line endings. Thanks for explaining the usage of the foundation files. I'm working on moving the edits and will submit a new request for that later. I'll post back here when ready!

**Comment by drbyte** [comment]
Another note of clarification: It may be awhile before we merge your other PR about changing the line-endings. That’s an issue that has a number of knock-on side-effects which we want to review before we embrace it fully. We tried it earlier this year and it created numerous problems so we backed out of it, to revisit it again later. 

That’s all to say that when you do your next PR for the revised CSS/LEAD changes you’re working on, and from another branch (which you should branch from the main v160 branch and not from your line-ending branch), you will probably still see some “whole file diffs”.  Just giving you a heads-up :)

**Comment by jtwebsitedesign** [comment]
Thank you for your patience, I had so much going on over the holidays and finally catching a breath. I've submitted a pull request for your review. Please let me know if you need anything else!

https://github.com/zencart/zc-v1-series/pull/824

**Comment by jtwebsitedesign** [comment]
Anything else you'd like me to complete on this ticket?

**Comment by drbyte** [comment]
@jtwebsitedesign  How invested are you in Foundation, vs Bootstrap?

**Comment by jtwebsitedesign** [comment]
Good question. Since it is more commonly used in the wild, I have more experience with Bootstrap. But I'm open to any framework, so Foundation is fine as well. Are we finding any hurdles using Foundation so far?

**Comment by drbyte** [comment]
@jtwebsitedesign There's some discussion at https://github.com/zencart/zc-v1-series/pull/793#issuecomment-187259075 related to having recently merged a PR for Bootstrap implementation into the v155 Admin vs what problems that could create for future users or plugin authors who style for one framework for v155 and then have to restyle for a different framework when moving to v160.
