### ISSUE TITLE
function zen_get_countries: an invalid country id returns an array with empty values

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5730]
While using and checking the result for this call: zen_get_countries((int)99999, true)
I find the result to be:

> Array
> (
>     [countries_name] => 
>     [countries_iso_code_2] => 
>     [countries_iso_code_3] => 
> )

when I would have expected no array/false, to ease validating the result.

**Comment by piloujp** [comment]
I am  a little late on this but I think this should fix it:
`if (mysql_num_rows($results) == 0) { return false; }`
After the SQL query is done at line 65.

**Comment by piloujp** [comment]
By the way how did you get this error? I can't find, except by rigging the code somewhere...

**Comment by piloujp** [comment]
Forget about my suggested fix above... It is not working. $result which is a QueryFactoryResult object does not seem to have any method to count rows.
Anyway even fixing this issue won' resolve problem. The call to this function that provoked this error should be fixed for sending bad parameter or/and to manage a 'false' response from the function.

**Comment by torvista** [comment]
Two things.
In the country_id function declaration the parameter is hinted as a integer, but uses of this function pass strings...but I could not provoke a debug error trying it. Odd.

My original post is about what happens if an invalid country_id id passed?
The function returns a valid array but with no values.
So to check the results, the calling code will have to check if an element is empty.

When the function is called with a specific country id, it's requesting specific information, it seems more correct to return no array or false, which is easier to check than an empty array element.

Checking that the country_id is valid before calling the function seems like replicating same functionality.

I don't remember what provoked this in the first place....

**Comment by lat9** [comment]
> Two things. In the country_id function declaration the parameter is hinted as a integer, but uses of this function pass strings...but I could not provoke a debug error trying it. Odd.
> 
> My original post is about what happens if an invalid country_id id passed? The function returns a valid array but with no values. So to check the results, the calling code will have to check if an element is empty.
> 
> When the function is called with a specific country id, it's requesting specific information, it seems more correct to return no array or false, which is easier to check than an empty array element.
> 
> Checking that the country_id is valid before calling the function seems like replicating same functionality.
> 
> I don't remember what provoked this in the first place....

To check for "no results returned", the caller should be checking for an empty array (`if ($value === []) {`); no need to call `empty`.

**Comment by piloujp** [comment]
> When the function is called with a specific country id, it's requesting specific information, it seems more correct to return no array or false, which is easier to check than an empty array element.

In theory, yes but it depends on what you want do with the response. If the function output is always an array it can be use as is, but if it can be a boolean too it has to be tested first.
In actual code function zen_get_countries is used everywhere and code is design to use its return array as is, empty or not. Returning a boolean false will break code everywhere.
I was able to test it using this code in functions_addresses.php on line 66:
`if (count($results->fields) == 0) { return false; }`
With this, function returns false when country id is not valid.
Then I changed shipping estimator code (relatively easy code to play with) to get '(int)99999' as  a parameter for the function.
I then got few messages from PHP log each time the function result was used:
'PHP Warning: Trying to access array offset on value of type bool in ...'
As suggested by @lat9 checking for empty array is a lot easier than testing for false in actual code.

Remark  apart from this problem: Empty() is very nice for variables like string or numbers of all sort but it does not work with object and with arrays it depends... When using associative arrays and multidimensional you are going to run into trouble. Still it is advised everywhere on the Net as one method to check for an empty array.

**Comment by piloujp** [comment]
> To check for "no results returned", the caller should be checking for an empty array (`if ($value === []) {`); no need to call `empty`.

I did not know this way! Thanks ! I like how it looks simple. I am generally trying to count number of row in the array...
Do you have some reference for this on the net? I was wondering if you could use it for complex array multidimensional in particular.

**Comment by lat9** [comment]
> > To check for "no results returned", the caller should be checking for an empty array (`if ($value === []) {`); no need to call `empty`.
> 
> I did not know this way! Thanks ! I like how it looks simple. I am generally trying to count number of row in the array... Do you have some reference for this on the net? I was wondering if you could use it for complex array multidimensional in particular.

See this (https://www.php.net/manual/en/language.operators.comparison.php) php.net link.  However, after reviewing how PHP processes an array-to-array comparison, it looks like simply using `count($array) === 0` is more performant than `$array === []`.

**Comment by torvista** [comment]
count($array) = 3 in this case/the array is not empty, just the elements: you need to check one of the contents.

**Comment by scottcwilson** [comment]
Please create a new issue when you find a repro path through normal code operation.
