### ISSUE TITLE
Duplicated lines in reviews header_php.php

### ISSUE THREAD

**Issue by simon1066** [zencart/zencart#5732]
Is there a reason why line 26 is duplicated on line 27?

https://github.com/zencart/zencart/blob/e3d0f86f2e17c2b91cb9cf04a1bf2d883cf9d191/includes/modules/pages/reviews/header_php.php#L25-L29

**Comment by lat9** [comment]
Er, because it's a bug?  Not that it's affecting performance, but for proper coding practices one of those two lines should be removed!

Will you PR?

**Comment by simon1066** [comment]
Of course, will do.

**Comment by scottcwilson** [comment]
I myself always blame jiggery-pokery.
