### ISSUE TITLE
Backslash appears before apostrophe in category meta tags

### ISSUE THREAD

**Issue by simon1066** [zencart/zencart#5735]
**Describe the bug**
An apostrophe added in either of the three meta tag fields for a category, in Admin > Catalog, is escaped (with a backslash). This backslash persists through to the browser. It appears that the escaped character is not recognised and continues escaping every time the meta tag is saved.
As noted in this forum post, https://www.zen-cart.com/showthread.php?229519-Apostrophe-in-meta-description

**Version**
Zen Cart version: 1.5.8a (vanilla)
PHP version: 7.4, 8.1 tested
MySQL version:  10.3.9-MariaDB
Plugins that may be related: none

**To Reproduce**
1. Go to 'Admin > Catalog > Edit a categories meta tag.'
2. Include an apostrophe in either in the three meta tag fields and 'save'
3. View the category page's source code in browser and note the the backslash that escapes the apostrophe persists.
4. Note that this does not occur when editing a product's meta tag.

**Comment by scottcwilson** [comment]
Can you PR?

**Comment by drbyte** [comment]
I'm not seeing the backslashes ...

Admin setup:
<img width="707" alt="Screen Shot 2023-07-28 at 4 14 27 PM" src="https://github.com/zencart/zencart/assets/404472/716b2f30-2968-437c-b5a1-b977f21b0793">

Catalog HTML:
<img width="510" alt="Screen Shot 2023-07-28 at 4 13 51 PM" src="https://github.com/zencart/zencart/assets/404472/bafd741c-aa25-4ed3-8956-37dbc612f134">

**Comment by torvista** [comment]
The backslash issue described is for **Category** metatags.

**Comment by drbyte** [comment]
> The backslash issue described is for **Category** metatags.

Sigh. I did read that. And started testing that, but somehow switched to testing products instead. 🤦‍♂️

**Comment by drbyte** [comment]
@torvista I synced the treatment, so that category metatag quotes/apostrophes are handled the same as with products.
