### ISSUE TITLE
Whos Online status icons inaccurate

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#5740]
**Describe the bug**
Status icon in Tools->Whos Online does not update when a customer goes from an empty cart to a cart with items.  This is described in Zen Cart Forum entry: https://www.zen-cart.com/showthread.php?229530-Who-s-Online-not-showing-active-carts&p=1395104#post1395104

**Version**
Zen Cart version: 1.5.8a
PHP version: 8.2.5
MySQL version: MySQL 8.0.28-0ubuntu0.20.04.3
Plugins that may be related: User Tracking may require a similar change.
What older/newer versions were also tested? 1.5.8

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Go to Admin->Tools->Whos Online.
2. Enable tracking from Admin IP Addresses.
3. Not in the current window navigate to the store.
4. Verify that Whos Online status image reflects the addition of the session indicating that the session is active but no cart.
5. Add a product to the cart.
6. Verify that Whos Online status image reflects the addition of the product to the cart and now that the session is active and with cart.

**Expected behavior**
A visitor with product in a cart should track/appear differently than a visitor that does not have product in the cart. 

**Screenshots**
![f_yz4nifk15C6YJZKNgQmRqSL2OaW0h7X8](https://github.com/zencart/zencart/assets/2072812/13e20d8c-ca2a-4879-8b2c-57be5bc5c10d)

**Debug/Error Logs**
None generated.

**Comment by lat9** [comment]
Thanks for the correction, @mc12345678.  I'll be unavailable (mostly) for the next week, but will review/merge sometime after June 9th.
