### ISSUE TITLE
Drop Table missing in ZC installer mysql_zencart.sql

### ISSUE THREAD

**Issue by piloujp** [zencart/zencart#5745]
In SQL file '../zc_intall/sql/install/mysql_zencart.sql', DROP TABLE IF EXISTS is missing for two tables, 'customer_groups' and 'customers_to_groups' which provokes errors when installing over an existing Zen Cart.

**Version**
Zen Cart version: 1.5.8a
PHP version: 8.19
MySQL version: 8.033
Plugins that may be related: none
What older/newer versions were also tested? none

**To Reproduce**
Run Zencart installer 'clean install' over an already installed Zen Cart.

**Expected behavior**
There are no visible effects, ZC installer manages it well and creates a debug table in database containing SQL error messages "Can't create table....".
In file 'mysql_zencart.sql', around line 673, instruction 'DROP TABLE IF EXISTS customer_groups;' is missing and around line 688, 'DROP TABLE IF EXISTS customers_to_groups;' too.
 
**Devices:**
 - Operating System: Windows 10
 - Browser Brave v1.52.119

**Comment by scottcwilson** [comment]
For consistency this should be fixed.  Please PR.

**Comment by piloujp** [comment]
> For consistency this should be fixed. Please PR.

Done! ;)

**Comment by scottcwilson** [comment]
Thanks guys!
