### ISSUE TITLE
Modify Display Logs zc_plugin to use new list of log prefixes

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#5752]
The file `includes/extra_configures/log_files.php` was introduced in #5751.

The Display Logs utility ~~should~~ might want to use this list rather than having a database configuration variable.

**Comment by lat9** [comment]
Please make sure that the "Display Logs" version is updated if/when this change is incorporated.

**Comment by scottcwilson** [comment]
Agreed, this will require a new version.

**Comment by mc12345678** [comment]
Removing all possibility of having a database accessible setting will inhibit development/debugging. Why not in some way pull from that file and retain the additional database capability of adding/removing monitored prefixes?

**Comment by scottcwilson** [comment]
I'm not convinced that this is worth doing, but Chris felt it was a good idea.

**Comment by lat9** [comment]
The plugin can be updated to use the file contents as the values for the configuration setting's _initialization_ and keep the setting available for additional log-prefixes.

**Comment by proseLA** [comment]
i am not sure why one would not want to be able to see all logs in this directory.  it is a log directory specifically for this individual store.  if there is a log in there, why not display it?  i frequently add other logs into this directory.  i find it cumbersome to have to go through the process of adding something here in order that i can see the logs using this plugin.
