### ISSUE TITLE
Provide admin setting for choosing timezone

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#576]
Considering adding timezone setting to admin and database, and a method to the db queryFactory to set the timezone; then make both initSystems set the timezone (to both PHP and the db connection) after it's been read from the db. Note the chicken/egg situation described there.

This would potentially replace the timezone files currently in the extra_configures files in both admin/catalog.

The problem is figuring out how to avoid bloating core code with a list of all possible timezones, and keeping that list up-to-date .... that's a nightmare. Maybe just a text-only field with a link to the PHP page listing acceptable timezones.

Of course, if the individual webserver isn't up to date and doesn't recognize certain timezones then things will break badly.

**Comment by barco57** [comment]
...or add a question to the install process and either write the timezone to the file where it's currently stored or add it to the database at that time...

**Comment by jtwebsitedesign** [comment]
+1 for adding it into the install process, as well as the admin.

**Comment by scottcwilson** [comment]
Install process? +1
Admin: Meh.  It's only done once.

**Comment by scottcwilson** [comment]
Possible compromise: On Store Manager, display it as a read-only text value, with a note about the file which should be changed if a change is desired.
