### ISSUE TITLE
lang.index.php missing constant TABLE_HEADING_IMAGE?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5766]
https://github.com/zencart/zencart/blob/9df7dec2ff199a1ab26d30ee40eb585b85181cb7/includes/languages/english/lang.index.php#L2-L16

https://github.com/zencart/zencart/blob/9df7dec2ff199a1ab26d30ee40eb585b85181cb7/includes/languages/english/responsive_classic/lang.index.php#L2-L17

**Comment by lat9** [comment]
That constant is defined in `lang.english.php`.  No need for replication in `lang.index.php` unless a template-/site-specific change wants to change the text from the overall default.

**Comment by scottcwilson** [comment]
Tons of consolidation was done in 1.5.8 to ease the burden on translators.
