### ISSUE TITLE
Update MobileDetect

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#5793]
Originally flagged by @torvista in #5075:

> Current version is 3.74.0.

> Noting the file and class is now MobileDetect (no hyphen) and will not work until
`namespace Detection;`
and
as a consequence of that, also
`use BadMethodCallException;`
are commented out.

> I don't know how to deal with the namespace issue to allow the file to remain native.

**Comment by scottcwilson** [comment]
Dependency checking is now part of the build process.  No need for separate issues unless there is a security alert that requires immediate updating.  

https://docs.zen-cart.com/dev/release_process/dependency_checks/

**Comment by torvista** [comment]
But, for this update there are core file changes necessary as the mobile detect class filename and class has changed.

**Comment by torvista** [comment]
As stated above: Mobile_Detect->MobileDetect
