### ISSUE TITLE
1.5.8b? Additional image code no longer reachable

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#5799]
**Describe the bug**
Because of incorporation of PR #5656, unable to display additional images without having a primary image in a default ZC install. This includes that no additional images notifiers are executed as a result of a change to the default template for all recognized product types.

**Version**
Zen Cart version: 1.5.8b? (code modified after the github tag of 1.5.8a)
PHP version: Anything compatible
MySQL version: Anything compatible
Plugins that may be related: 
What older/newer versions were also tested? 1.5.8a and below

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
Install the Zen Cart software that is available on the current v158 branch: https://github.com/zencart/zencart/tree/v158 that incorporates PR #5656.

Install Additional Product Images plugin: https://www.zen-cart.com/downloads.php?do=file&id=1063
As necessary upgrade for any php related issues, though cursory glance doesn't appear to have any obvious specific issues.
Add an additional image using the plugin to a product that has a main image.
Navigate the store to look at the results of that product having both a main image and an additional image.
Remove the primary image from that product.
Attempt to navigate the product again and notice that the additional image(s) are no longer presented.
Return to the admin side and note how additional, additional images can be added to the product that no longer has a main image.

**Expected behavior**
Able to independently address the main image and the additional images on any product page without requiring that a path to a main image file must exist and if it must exist, the a way to bypass the html code that is generated to display the image even though the expectation may be that no image would be displayed for the particular product. This has not been a requirement before, there is no identified level of improvement gained by this being made now part of the core code and is done at the template level rather than either deeper in the code or not at all. 

**Screenshots**
None that seem would add much value.

**Debug/Error Logs**
None generated specifically in relation to this issue.
 
**Devices (please complete the following information):**
 - Operating System: Doesn't matter
 - Browser [e.g. chrome, firefox] and version number: Doesn't matter

**Additional context**
There is another "similar" plugin about which I know exists; however, I do not know how it interfaces with the store.

**Comment by scottcwilson** [comment]
Not having a primary image seems like a defective configuration.  @brittainmark thoughts?

**Comment by brittainmark** [comment]
I tend to agree with @scottcwilson. 
@mc12345678 are you saying this is a feature of a previous version that you are using?

**Comment by scottcwilson** [comment]
Also note that we have utilities like the Missing Images plugin
https://www.zen-cart.com/downloads.php?do=file&id=2268
which will allow you to detect these abnormal conditions.

**Comment by mc12345678** [comment]
> Not having a primary image seems like a defective configuration. @brittainmark thoughts?

Not all product of whatever a store sells must have a primary image. 

> I tend to agree with @scottcwilson. @mc12345678 are you saying this is a feature of a previous version that you are using?

While I don't typically address my own store needs as applicable to all because of I want to do something on my own site, I'll do it, my concern is based on either direct work of others site, software on which I've worked and through the years of discussions in the forum. 

The software to which I referenced has no dependency on the primary image and allows any image to either be or be added to the existing additional images. I've helped others to address at least both of those aspects. 

> Also note that we have utilities like the Missing Images plugins
> 
> https://www.zen-cart.com/downloads.php?do=file&id=2268 https://www.zen-cart.com/downloads.php?do=file&id=1887
> 
> which will allow you to detect various abnormal conditions related to product images.

While I haven't gone back to specifically look at these two plug-ins, I am aware that at least one of them does a search of the fileset to determine if the image path assigned to be the main image is not present or accessible. This is a different condition than described or attempted to be resolved. As modified, a product that has an assigned main image would result in the additional code being accessible, but the main image may not display because the image file is missing. 

The modification that was pushed/accepted was, if there is no main image assigned to a product, then no code associated with additional images is to be accessed (no template file, no module file(s)). The reasoning posed for this was some sort of performance gain. Seems that if the template is too be so modified, then some level of overrides be incorporated so that one could link into perhaps the header files of the page and enable/disable as desired and perhaps looking deeper into the associated module code to enable/disable the follow on html/template file(s).

**Comment by scottcwilson** [comment]
The PR mentioned is all template changes.  You could simply change your own copy of the template to taste.

**Comment by torvista** [comment]
> Not all product of whatever a store sells must have a primary image.

When would a product not have a main image but have additional images?

**Comment by drbyte** [comment]
The additional-images module and corresponding template were designed to be extendible via overrides.
That's why the additional_images module was always called in the template regardless of whether a main image existed.

I do agree that it's not traditional for a "product" to not have a "main image", but Zen Cart is used for a lotta non-traditional "products" too.

The additional-images plugin that mc12345678 mentioned allows the storeowner to upload images for a product, and store their association in the database, without depending on filename-matching like the built-in additional_images module does. I can see where a storeowner may rely strictly on such a strategy, potentially without having a "main" image at all. 

Granted, without having a "main" image, there will be numerous other display issues, such as no thumbnails shown in product listings, specials, sales, featured, etc.

In reviewing the code contained in the core additional_images module, I see that it has very little logic that runs if nothing is found, so I don't see where any CPU processing savings are gained by PR #5656. I'm willing to be proven wrong, but otherwise I would advocate for the reversal of #5656.

**Comment by scottcwilson** [comment]
How would you know what the additional image filename was if you lack a primary image?  I just don't get it.

**Comment by drbyte** [comment]
> How would you know what the additional image filename was if you lack a primary image? I just don't get it.

The referenced plugin: 
> Install Additional Product Images plugin: https://www.zen-cart.com/downloads.php?do=file&id=1063

... it creates a db table to correlate images with products, and provides an uploaded in the Admin for adding them too.

**Comment by brittainmark** [comment]
While I know Drbyte is the expert on zen cart is this not a real issue

> Granted, without having a "main" image, there will be numerous other display issues, such as no thumbnails shown in product listings, specials, sales, featured, etc.

But happy to go with reversal.

**Comment by drbyte** [comment]
It's a fairly minor topic, given that it's quite abnormal to intentionally never have product images.

It can be left for now.

The features of the additional-images plugin might be more interesting to explore, as inspiration for feature-improvement. Granted, it's up for debate whether a cached db query would be faster than a filesystem inspection when looking for any product images, whether main or additional. But I digress.

**Comment by mc12345678** [comment]
The merged "fix" did not correct this issue and only made things worse if used. 

Continue to do as you all see fit. For those interested in the topic, the file changes made so not support the requested feature and until otherwise corrected I suggest not using the new `boolean` value in a `true` state without making other core/template corrections.
