### ISSUE TITLE
Ask A Question email double colons

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5841]
![2023-07-02 20_43_28-ask html](https://github.com/zencart/zencart/assets/4391026/cfa8f0de-717b-4d0f-9a3b-65cf53241171)

Due to a colon after the constant

https://github.com/zencart/zencart/blob/de6597a8674794234b13d9df7f5db0b7978146be/includes/languages/english/lang.ask_a_question.php#L8

 and a colon in the code

https://github.com/zencart/zencart/blob/de6597a8674794234b13d9df7f5db0b7978146be/includes/modules/pages/ask_a_question/header_php.php#L146

**Comment by scottcwilson** [comment]
Yep, it's a bug.  Please PR.

**Comment by torvista** [comment]
I know it's a bug, but didn't want to ask where the colon should go and invite a witty ripost...

**Comment by drbyte** [comment]
> I know it's a bug, but didn't want to ask where the colon should go and invite a witty ripost...

I suggest defining the colon in the `lang.ask_a_question.php` file, and remove it from the `header_php.php` strings.
That would be consistent with how `TEXT_PRODUCTS_NAME` (alternate spelling noted) is used elsewhere.
