### ISSUE TITLE
function filterProductUrlRegex debug for empty parameter

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5849]
While delousing the Flexible Footer, I was getting a debug when updating a page definition,

> --> PHP Warning: Invalid argument supplied for foreach() in ADMIN/includes/classes/AdminRequestSanitizer.php on line 515.

https://github.com/zencart/zencart/blob/e27bdb54a1f92f14a548f5473eb5bab9f3c85d3f/admin/includes/classes/AdminRequestSanitizer.php#L511-L515

the parameter being passed was
`    [page_url] => `

so set, but empty.
Changing the isset on line 511 to !empty fixed it.

**Comment by mc12345678** [comment]
> While delousing the Flexible Footer, I was getting a debug when updating a page definition,
> 
> > --> PHP Warning: Invalid argument supplied for foreach() in ADMIN/includes/classes/AdminRequestSanitizer.php on line 515.
> 
> https://github.com/zencart/zencart/blob/e27bdb54a1f92f14a548f5473eb5bab9f3c85d3f/admin/includes/classes/AdminRequestSanitizer.php#L511-L515
> 
> the parameter being passed was ` [page_url] =>`
> 
> so set, but empty. Changing the isset on line 511 to !empty fixed it.

Able to identify the data type of the unset value? 

Historically, an array seemed to further support an array of items such that having none would basically result in no action. 

If this condition has occurred in this case, it seems like it may happen in many others.

**Comment by torvista** [comment]
This is the entire Sanitize_Debug log:

```
Incoming GET Request Array
(
    [cmd] => flexible_footer_menu
    [page] => 
    [action] => update
)


Incoming POST Request Array
(
    [securityToken] => 1b7d88e24b227c2863ae7822a0493adf
    [page_id] => 3
    [col_header] => Array
        (
            [1] => 
            [2] => 
        )

    [page_title] => Array
        (
            [1] => Specials
            [2] => Specials (translate me)
        )

    [image_delete] => 0
    [page_url] => 
    [col_html_text] => Array
        (
            [1] => Don't miss out on Deal of the Day!
            [2] => Don't miss out on Deal of the Day! (translate me)
        )

    [col_id] => 1
    [col_sort_order] => 13
)


Running Admin Sanitizers

PROCESSING PRODUCT_DESC_REGEX == col_header

PROCESSING PRODUCT_DESC_REGEX == page_title

PROCESSING PRODUCT_DESC_REGEX == col_html_text

PROCESSING PRODUCT_URL_REGEX == page_url

PROCESSING SIMPLE_ALPHANUM_PLUS(GET) == action

PROCESSING SIMPLE_ALPHANUM_PLUS(GET) == page

PROCESSING STRICT_SANITIZE_VALUES == securityToken

PROCESSING STRICT_SANITIZE_VALUES == page_id

PROCESSING STRICT_SANITIZE_VALUES == image_delete

PROCESSING STRICT_SANITIZE_VALUES == page_url

PROCESSING STRICT_SANITIZE_VALUES == col_id

PROCESSING STRICT_SANITIZE_VALUES == col_sort_order

PROCESSING STRICT_SANITIZE_VALUES == cmd

Outgoing GET Request Array
(
    [cmd] => flexible_footer_menu
    [page] => 
    [action] => update
)


Outgoing POST Request Array
(
    [securityToken] => 1b7d88e24b227c2863ae7822a0493adf
    [page_id] => 3
    [col_header] => Array
        (
            [1] => 
            [2] => 
        )

    [page_title] => Array
        (
            [1] => Specials
            [2] => Specials (translate me)
        )

    [image_delete] => 0
    [page_url] => 
    [col_html_text] => Array
        (
            [1] => Don't miss out on Deal of the Day!
            [2] => Don't miss out on Deal of the Day! (translate me)
        )

    [col_id] => 1
    [col_sort_order] => 13
)
```

The debug log occurs in PROCESSING PRODUCT_URL_REGEX for [page_url].

**Comment by lat9** [comment]
> > While delousing the Flexible Footer, I was getting a debug when updating a page definition,
> > > --> PHP Warning: Invalid argument supplied for foreach() in ADMIN/includes/classes/AdminRequestSanitizer.php on line 515.
> > 
> > 
> > https://github.com/zencart/zencart/blob/e27bdb54a1f92f14a548f5473eb5bab9f3c85d3f/admin/includes/classes/AdminRequestSanitizer.php#L511-L515
> > 
> > the parameter being passed was ` [page_url] =>`
> > so set, but empty. Changing the isset on line 511 to !empty fixed it.
> 
> Able to identify the data type of the unset value?
> 
> Historically, an array seemed to further support an array of items such that having none would basically result in no action.
> 
> If this condition has occurred in this case, it seems like it may happen in many others.

IIRC, the `page_url` is a `string` type value.

**Comment by mc12345678** [comment]
> > > While delousing the Flexible Footer, I was getting a debug when updating a page definition,
> > > > --> PHP Warning: Invalid argument supplied for foreach() in ADMIN/includes/classes/AdminRequestSanitizer.php on line 515.
> > > 
> > > 
> > > https://github.com/zencart/zencart/blob/e27bdb54a1f92f14a548f5473eb5bab9f3c85d3f/admin/includes/classes/AdminRequestSanitizer.php#L511-L515
> > > 
> > > the parameter being passed was ` [page_url] =>`
> > > so set, but empty. Changing the isset on line 511 to !empty fixed it.
> > 
> > 
> > Able to identify the data type of the unset value?
> > Historically, an array seemed to further support an array of items such that having none would basically result in no action.
> > If this condition has occurred in this case, it seems like it may happen in many others.
> 
> IIRC, the `page_url` is a `string` type value.

So then the rule should be modified different from the above proposal? E.g. it should account for a non-array based posted value? 

I'm going to look back at the writeup associated with a change I added to see if/what was described in association with modification made in this area. Otherwise I believe that there are instances of similar handling that could be used as a template.

**Comment by torvista** [comment]
There is more to this particular case than I realised as there is some code in extra_configures adding these parameters, that I need to understand further...

**Comment by mc12345678** [comment]
> There is more to this particular case than I realised as there is some code in extra_configures adding these parameters, that I need to understand further...

With concern that a follow on post might be, forget that, the code has no effect,  at some point would you mind identifying the code/file of interest?

**Comment by torvista** [comment]
While this may not be a bug, I'll detail it further for general information.
This mod has custom parameters defined for sanitation:
```
if (class_exists('AdminRequestSanitizer')) {
    $sanitizer = AdminRequestSanitizer::getInstance();
    $group = [
        'col_header' => [
            'sanitizerType' => 'PRODUCT_DESC_REGEX',
            'method' => 'both',
            'pages' => ['flexible_footer_menu'],
            'params' => []
        ],
        'page_title' => [
            'sanitizerType' => 'PRODUCT_DESC_REGEX',
            'method' => 'both',
            'pages' => ['flexible_footer_menu'],
            'params' => []
        ],
        'col_html_text' => [
            'sanitizerType' => 'PRODUCT_DESC_REGEX',
            'method' => 'both',
            'pages' => ['flexible_footer_menu'],
            'params' => []
        ],
        'page_url' => [
            'sanitizerType' => 'PRODUCT_URL_REGEX',
            'method' => 'both',
            'pages' => ['flexible_footer_menu'],
            'params' => []
        ],
    ];
    $sanitizer->addComplexSanitization($group);
}
```
This appears to be the correct structure as per the documentation:
https://docs.zen-cart.com/dev/code/admin_sanitization/

When the offending admin page is submitted that contains the parameter 'page_url',   
if the parameter is empty, the error as initially reported occurs, since it is set, but empty.
if the parameter has a value, there is a different error: 
foreach() argument must be of type array|object, string given in ADMIN/includes/classes/AdminRequestSanitizer.php on line 515.

https://github.com/zencart/zencart/blob/e27bdb54a1f92f14a548f5473eb5bab9f3c85d3f/admin/includes/classes/AdminRequestSanitizer.php#L511-L515

which I can understand as $_POST[$parameterName] is POST['page_url'] which is indeed a string (the url).

So, the foreach is expecting the $_POST[$parameterName] to contain an array.

I don't see why?

**Comment by mc12345678** [comment]
Well, I just finished locally modifying the code for non-array sanitization which would address this issue. 

Working on submitting the PR. Also, in parallel have done some refactoring.

**Comment by mc12345678** [comment]
As to why there is this issue? Well, the sanitizer was built around how it is or would be used in core code. 

Two two fields that use this sanitizer, `products_url` and `manufacturers_url`, are both language dependent and as such are presented as an array. A `page_url` tends to come in one language only... 

Sure, could jump through hoops to support it being multilingual, but I would say not worth it. Instead just add the capability to the sanitizer.

**Comment by torvista** [comment]
Thanks, all clear now.
Note that setCurrentArrayname should be setCurrentArrayName.
