### ISSUE TITLE
Admin, RecentOrdersDashboardWidget br substitution

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5873]
https://github.com/zencart/zencart/blob/8a7ef921623758b2afa10823b6a54bd3aba95322/admin/includes/modules/dashboard_widgets/RecentOrdersDashboardWidget.php#L86

Should this non-substitution
`'<br>' => '<br>'`

be doing something else?

**Comment by torvista** [comment]
I'll note that the Firefox html validator complains about missing closing quotes in attributes

a) from here
https://github.com/zencart/zencart/blob/8a7ef921623758b2afa10823b6a54bd3aba95322/admin/includes/modules/dashboard_widgets/RecentOrdersDashboardWidget.php#L77
until  br / is also removed from the text in title

b) similar complaints until br and br / are removed from the data-content text in the first post.

c)  and also complains about the one order that has more than one hr in it (multiple products).

I expect the existence of < and > is upsetting it....but these are possibly invalid characters.


Not saying it is correct, just commenting.

**Comment by drbyte** [comment]
If the `<br>` tags were substituted with something else that renders a line-break, would the validator be "happy" .... and what would produce such a line-break that would both make it happy and also render meaningfully on-screen?

**Comment by torvista** [comment]
I'm not so much bothered about the validator as querying that substitution doing nothing.

**Comment by drbyte** [comment]
Oh. I gather this is a follow-up to your protest against https://github.com/zencart/zencart/pull/5376
