### ISSUE TITLE
More $db failures to 'squish'

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#5883]
As a follow-on to #5722, which identified the 'database connection failed' as being problematic, I'm also seeing logs of the ilk:
```
--> PHP Warning: mysqli_connect(): (HY000/2002): Connection refused in /home/xxxx/public_html/includes/classes/db/mysql/query_factory.php on line 64.
--> PHP Warning: mysqli_query(): MySQL server has gone away in /home/xxxx/public_html/includes/classes/db/mysql/query_factory.php on line 45.
--> PHP Warning: mysqli_connect(): (08004/1040): Too many connections in /home/xxxx/public_html/includes/classes/db/mysql/query_factory.php on line 64.
```

These SQL server issues also result in a slew of 7-10Kb log files when the SQL server has the identified issues.  Could these also be added to the logs' size-shrink and force a `die()`?

**Comment by drbyte** [comment]
The ones for `mysqli_connect` are relatively safe and easy to add.
The one for `mysqli_query` might be a little more delicate to implement.

One challenge with this is the importance of reporting the problem at least once, so that there's an explanation of what actually IS wrong and causing the site to malfunction.

**Comment by lat9** [comment]
One site that I manage experienced these issues, racking up 30 logs totaling 1.65MB in _one second_.  The largest log (1.05MB) started with connection refused, then MySQL server has gone away and finally a plethora of follow-on logs since the database connection wasn't a mysqli object, e.g.
```
--> PHP Warning: mysqli_query(): Error reading result set's header in /home/xxxx/public_html/includes/classes/db/mysql/query_factory.php on line 45.
--> PHP Warning: mysqli_query() expects parameter 1 to be mysqli, bool given in /home/xxxx/public_html/includes/classes/db/mysql/query_factory.php on line 266.
```

Note that the site's running zc156b (I know, it's on the list to upgrade).

**Comment by drbyte** [comment]
> Note that the site's running zc156b (I know, it's on the list to upgrade).

While I haven't done a direct code analysis to be certain, I'm pretty sure the latest query_factory class can be dropped in. (The harder issue is knowing whether external dependencies were added in latest, but of course dropping it in for a test will expose that pretty quickly. Granted, it's hard to find a time to safely do that if the only way to test is directly in production.)
There were almost no changes between 156-to-157 for that file, but 158 had a bunch of overhaul for refactoring and speed improvements. That said, function-signature-wise I don't recall any noteworthy breaks.

**Comment by drbyte** [comment]
> One site that I manage experienced these issues, racking up 30 logs totaling 1.65MB in _one second_. The largest log (1.05MB) started with connection refused, then MySQL server has gone away and finally a plethora of follow-on logs since the database connection wasn't a mysqli object, e.g.
> 
> ```
> --> PHP Warning: mysqli_query(): Error reading result set's header in /home/xxxx/public_html/includes/classes/db/mysql/query_factory.php on line 45.
> --> PHP Warning: mysqli_query() expects parameter 1 to be mysqli, bool given in /home/xxxx/public_html/includes/classes/db/mysql/query_factory.php on line 266.
> ```

Thanks, that context is helpful.
