### ISSUE TITLE
`role="button"` on `<tr>` tags results in invalid HTML (e.g. admin/customers.php)

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#5905]
What's the motivation for the `role="button"` addition on various `<tr>` tags in `customers.php` (probably repeated elsewhere):
https://github.com/zencart/zencart/blob/9dff1c8397def4e2408fed49a594be622450e14f/admin/customers.php#L1537-L1542

I ask because those result in various HTML validation issues

- The role attribute must not be used on a tr element which has a table ancestor with no role attribute, or with a role attribute whose value is table, grid, or treegrid.
- The element button must not appear as a descendant of an element with the attribute role=button.
- The element a must not appear as a descendant of an element with the attribute role=button.

**Comment by scottcwilson** [comment]
Could be an accessibility requirement?  @dbltoe can you comment?

**Comment by drbyte** [comment]
Does it have to do with making the row clickable?

**Comment by lat9** [comment]
I _believe_ that it's a combination of an accessibility requirement and that the row is clickable to bring up a quick edit of the customer's information.

**Comment by torvista** [comment]
In previous PR's with clickable rows I got rid of the role for the same reason and made the cursor a hand to "compensate".

**Comment by drbyte** [comment]
> In previous PR's with clickable rows I got rid of the role for the same reason and made the cursor a hand to "compensate".

Does removing the role still treat the row as a clickable trigger?

**Comment by lat9** [comment]
> > In previous PR's with clickable rows I got rid of the role for the same reason and made the cursor a hand to "compensate".
> 
> Does removing the role still treat the row as a clickable trigger?

Yes, but the cursor changes to a pointer to @torvista's (er) point instead of a hand.

**Comment by drbyte** [comment]
Aside:
The role=button was added in a large refactoring from table-layouts to divs which also got rid of `onmouseover="rowOverEffect(this)" onmouseout="rowOutEffect(this)"` among other things.
The only remaining pages that still have the old markup are /admin/paypal.php and /admin/media_manager.php
... so those pages might be a handy way to test some ui functionality to be sure old things aren't lost while trying to change this role=button validation matter.

**Comment by brittainmark** [comment]
I had done a load of these corrections in #5085 (closed because it was too big a change).
I changed the `roll="button`" to `roll="option"` and added to `<table>` tag  `role="listbox"` 
Additionally, I added `aria-selected="true" or "false"` to the `<tr>` tag
thus lines 1216 ... 1572-1598
```
<table class="table table-hover">
...
if (isset($cInfo) && is_object($cInfo) && ($customer['customers_id'] === (int)$cInfo->customers_id)) {
?>
                            <tr id="defaultSelected" class="dataTableRowSelected" onclick="document.location.href = '<?php
                                echo zen_href_link(
                                    FILENAME_CUSTOMERS,
                                    zen_get_all_get_params(['cID', 'action']
                                    ) . 'cID=' . $cInfo->customers_id . '&action=edit'
                                ); ?>'" role="button">
<?php
        } else {
?>
                            <tr class="dataTableRow" onclick="document.location.href = '<?php
                                echo zen_href_link(
                                    FILENAME_CUSTOMERS,
                                    zen_get_all_get_params(['cID', 'action']) . 'cID=' . $customer['customers_id']
                                ); ?>'" role="button">
<?php
        }
```
became lines 725 ... 887-893 (I have reformatted below to make it easier to spot the difference)
```
<table class="table table-hover" role="listbox">
...
                  if (isset($cInfo) && is_object($cInfo) && ($customer['customers_id'] == $cInfo->customers_id)) {
                    ?>
                    <tr id="defaultSelected" class="dataTableRowSelected" onclick="document.location.href = '<?php 
                         echo zen_href_link(
                              FILENAME_CUSTOMERS, 
                              zen_get_all_get_params(['cID', 'action']) . 'cID=' . $cInfo->customers_id . '&action=edit
                            '); ?>'" role="option" aria-selected="true">
                    <?php } else { ?>
                    <tr class="dataTableRow" onclick="document.location.href = '<?php
                        echo zen_href_link(
                           FILENAME_CUSTOMERS,
                           zen_get_all_get_params(['cID', 'action']) . 'cID=' . $customer['customers_id'
                         ); ?>'" role=option aria-selected="false">
                      <?php
                    }
```

From my reading at the time, this looked like the way to go. Note, there are a lot of other changes that were made in addition to these to make admin html5 compliant. If this is accepted as a way forward, I can look at this again (I know there are some unnecessary changes in there to make all the id attributes unique and match the name attributes).

**Comment by drbyte** [comment]
That's probably the ideal way to go with it.
