### ISSUE TITLE
'master' is now the official branch to push to

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#5911]
UPDATE: We've switched to using `master` for active development on the "next" release.
Therefore we've renamed `v200` to `master`.
Be sure to update your local git configuration. Github's suggestion via command-line is:
<img width="386" alt="Screen Shot 2023-10-09 at 2 10 35 PM" src="https://github.com/zencart/zencart/assets/404472/82a830b0-c62d-40f3-9409-0c4aaa8721cb">

Original post below:
---
Since v2.0.0 will be the number of the next official Zen Cart release, a new `v200` branch has been created.

All new pull requests should be to this branch.

You can clone that `v200` branch into your own repository, from inside your own Github account.
Once you have cloned it, you can pull that branch down to your local PC to work with it. You can periodically click the button to sync that branch with your own as well.

Here's how to clone the new branch into your own github repo, from inside your own github account page:

![1 Go to Branches page](https://github.com/zencart/zencart/assets/404472/25a5fabb-1312-487f-82af-bc5ba461af5f)

![2  New Branch](https://github.com/zencart/zencart/assets/404472/aaa83d67-aea6-4a9b-bed3-48d7268062f2)

Set the fields as shown, and click the button:
<img width="478" alt="3 Create the branch from upstream" src="https://github.com/zencart/zencart/assets/404472/38517c5e-1dee-46c9-bda5-6d085e53c0a9">

And now make that new branch the "Default" branch for the repo:
![4 switch default branch](https://github.com/zencart/zencart/assets/404472/c9982e02-4e39-41f7-87d7-5df9b3440674)

Now you can sync that `v200` branch from your Github to your Local, and on your local you can branch off of it to submit any pull requests.
First check whether the branch on zencart/zencart has been updated (it will show how many commits it is out of sync). Click the button to Sync your own fork with Zen Cart. 

![5 Sync from origin (out of sync)](https://github.com/zencart/zencart/assets/404472/d01734a7-1561-4f61-8093-a1daba488fdb)

Then pull your v200 branch down to your local.
And if you're working on a Pull Request, branch from this newly updated v200 branch before submitting the PR.

@zencart/contributors

**Comment by drbyte** [comment]
> @drbyte: It is not possible to merge into "main"?

Considering it ...

**Comment by brittainmark** [comment]
@Neustradamus & @drbyte If everything is in main will you still be able to update previous versions of zen cart. Currently, fixes to the latest version are sometimes applied to previous versions. If everything is in main and tagged will that mean that version tagged 1.5.8 will be frozen and updates will not be applied to it?

**Comment by drbyte** [comment]
> @Neustradamus & @drbyte If everything is in main will you still be able to update previous versions of zen cart. Currently, fixes to the latest version are sometimes applied to previous versions. If everything is in main and tagged will that mean that version tagged 1.5.8 will be frozen and updates will not be applied to it?

If we delete old branches then no we won't be able to tag bugfixes onto older versions.

That wouldn't prevent us from doing all "current development for next release" on main/master though.

**Comment by drbyte** [comment]
> Normally all old tagged branches have been merged in main?

Yes, we will merge it back to main. In the past because our development wasn't done directly in main we only merged back to main after a release was tagged. We may revisit that strategy going forward now that we're embracing semver more closely.

**Comment by brittainmark** [comment]
Ok If I understand this correctly what we are saying is that we will only support on version of the code (the latest). 
If there is a bug discovered that applies to multiple versions and the fixed is applied to the latest version, but that module has moved on and is not backward compatible, then it is up to the store owner to manually apply the fix?
Just playing devil's advocate here to make sure this has been completely thought through.

**Comment by drbyte** [comment]
I was answering a hypothetical question.

I'll be clear:  WE ARE **NOT** DELETING ALL HISTORICAL BRANCHES.

This whole topic has gone way off track.

**Comment by drbyte** [comment]
@Neustradamus please introduce yourself. What's your experience with using the Zen Cart application?

**Comment by proseLA** [comment]
if there was an old tagged release and hypothetically we deleted all of the old branches, one could create a new branch from the tag; apply any necessary patches; and then create a new patched release of the old version. 

i'm pretty sure that would work.

**Comment by drbyte** [comment]
> if there was an old tagged release and hypothetically we deleted all of the old branches, one could create a new branch from the tag; apply any necessary patches; and then create a new patched release of the old version.

Yes, I said that too. But, like I also said, there are no plans to delete branches for older versions.

**Comment by drbyte** [comment]
> It is time to start the good future for Zen Cart code!

@Neustradamus you still haven't answered my question ...

**Comment by drbyte** [comment]
Update: `v200` has been renamed to `master`. Be sure to update your local git configuration in order to pull/push against `master` instead of `v200`:

<img width="386" alt="Screen Shot 2023-10-09 at 2 10 35 PM" src="https://github.com/zencart/zencart/assets/404472/2e73bab5-f0fe-4893-992d-8a68fd79e823">

**Comment by drbyte** [comment]
Update: `v200` has been renamed to `master`. Be sure to update your local git configuration in order to pull/push against `master` instead of `v200`:

<img width="386" alt="Screen Shot 2023-10-09 at 2 10 35 PM" src="https://github.com/zencart/zencart/assets/404472/2e73bab5-f0fe-4893-992d-8a68fd79e823">

**Comment by drbyte** [comment]
UPDATE:

Now that 2.0.0 is released, and we're using semantic versioning conventions:

- `master` continues to be the branch where all new features should be PR'd to (and will become 2.1 when it comes time to tag that)
- `2.0` is the branch where all bugfixes for 2.0 should be PR'd to. (And we will re-merge `2.0` over to `master` after merging the PR into 2.0, so that `master` remains consistent)

When 2.1 gets released, then:
- `2.1` is the branch where all bugfixes for 2.1 should be PR'd to.
- `master` will be for future such as 2.2
- `2.0` branch will still be used for bugfixes specific to 2.0.x

etc.
