### ISSUE TITLE
Admin, Extras: all pages missing Insert button

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5923]
php7.4-8.3
ZC2.0.0.

Delete all demo items on any page so there are no records: no Insert button.

**Comment by proseLA** [comment]
#5349

**Comment by scottcwilson** [comment]
Thanks guys. I thought we had fixed this but apparently not.

**Comment by proseLA** [comment]
> Thanks guys. I thought we had fixed this but apparently not.

there are 4 more files that need fixing for this issue that "we" introduced.

**Comment by simon1066** [comment]
As long as there's no rush, I don't mind making the edits to the other files - using @proseLA's media_types.php as an example.

When this issue arose for manufacturers.php #5699, @drbyte made changes that moved the `&` out of `'action=new'` and into `$current_mid` (`$mType_parameter` in this case), #5703

> You'll need to move the `&` out of `'&action=new'`, into `$current_mid`, else you'll have double `&&` in some cases and a missing one in other cases.

Is that something that needs to be done here?

**Comment by torvista** [comment]
Once fixed, perhaps a discussion is warranted (in the forum) who still uses this stuff / splitting this stuff out to a plugin.

**Comment by simon1066** [comment]
Now that the changes are finalised and merged, #5924, I will look at doing the same for the other affected files under 'Extras'
