### ISSUE TITLE
ot_coupon does not need to process if no coupon is entered.

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#5925]
is there a reason why we do not just exit if there is no cc_id?  ie:

```
            if (empty($_SESSION['cc_id'])) {
                return;
            }
```
at the beginning of this method.
 https://github.com/zencart/zencart/blob/7afd3a914c8ba09ecdc1ce46b038eeaf027df1dc/includes/modules/order_total/ot_coupon.php#L133-L138

**Comment by drbyte** [comment]
Based on what subsequent processing happens, at least in core code anyway, I think it's probably safe to do that early-return.

I don't see how any plugins could be hooking into anything that would have negative side-effects with that. 

@zcwilt are we missing anything here?

**Comment by zcwilt** [comment]
probably not

**Comment by drbyte** [comment]
@proseLA I think it's safe to PR it.
