### ISSUE TITLE
paypal time in paypal table...

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#5927]
[as referenced here](https://www.paypal.com/us/cshelp/article/what-format-does-the-api-timestamp-use-ts1085#:~:text=Each%20API%20response%20contains%20a,to%20as%20%22Zulu%20time.%22), paypal always uses ZULU time.

we are then posting that time:

https://github.com/zencart/zencart/blob/4d8945cf2732ec40c1a1a5f009eff4b12fdeb33e/includes/modules/payment/paypal/paypal_functions.php#L285

after converting it here:

https://github.com/zencart/zencart/blob/4d8945cf2732ec40c1a1a5f009eff4b12fdeb33e/includes/modules/payment/paypal/paypal_functions.php#L13-L22

is anyone else bothered by that table storing timestamps from different timezones?  or is it just me?

date_added in the same table makes use of the mysql now function.

https://github.com/zencart/zencart/blob/4d8945cf2732ec40c1a1a5f009eff4b12fdeb33e/includes/modules/payment/paypal/paypal_functions.php#L287

the [now function](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_now), The value is expressed in the session time zone.

**Comment by drbyte** [comment]
> is anyone else bothered by that table storing timestamps from different timezones? 

Interesting. I don't think I'd ever paid much attention to the fact that the timezone value is essentially just stripped off before storing the rest of the date. 

The difference between `payment_date` and `date_added` is that `date_added` is merely when the record is added to the store's database. It could refer to a transaction that happened on a completely different day, since an IPN notification happens out-of-band and can be delayed for various reasons. Or an IPN could be "referring to" something that happened on a different day. My point: we can't fallback to just using `now()`.

**Comment by proseLA** [comment]
> My point: we can't fallback to just using `now()`.

i think you are missing my point. 

i am not suggesting using `now()` for `payment_date`.  i think the method `datetime_to_sql_format` needs to convert the time of the `payment_date` to the timezone of the session.  that way both timestamps are stored in the same timezone.

**Comment by drbyte** [comment]
> timezone of the session

I agree that the improved accuracy would be preferable.

But let's be sure we're using the same definition of "the session". 
It should be converted to the timezone that the server is using to display the store's data.
It is unrelated to a shopper or where their "browser session" exists geographically.

Zen Cart currently assumes that the server's "time" timezone is set to the timezone the store's primary address is domiciled in. In plain language: the storeowner's timezone. That way all dates are presented according to the storeowner's perspective. 

(Yes, I know, ideally the entire application would store all dates/times in Zulu, and every date/time would be converted to the current viewer's timezone for display purposes. But that's not how ZC works right now.)

**Comment by proseLA** [comment]
yes, we are in agreement.  the timezone that the store owner has set which is the timezone in the header bar in the admin, ie, something like:

![image](https://github.com/zencart/zencart/assets/1095136/cea49275-bee2-40c5-8b04-af8de5798c68)

**Comment by drbyte** [comment]
Fortunately, since we can depend on `datetime_to_sql_format()` returning the value as Zulu time (because its input is in Zulu time), we should be able to use PHP date functions to correctly calculate the new datetime value from the store's timezone setting.
