### ISSUE TITLE
dnsstuff link from admin order page no longer works

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#5933]
The order details page in admin shows the IP address of the order, which is used as link anchor text to 

https://tools.dnsstuff.com/#whois|type=ipv4&&value=ORDER_IP_ADDRESS

this link no longer works.  (It advertises a bunch of paid options.)

Not sure what we should replace it with.  When there's agreement on the change to be done, I'll post back to the forum for people who want to update their sites now.

**Comment by scottcwilson** [comment]
Sure enough!  If no objections by end of week, I'll move forward with this.

**Comment by lat9** [comment]
How about https://ipdata.co/order_ip_address?  That would also give the admin some information regarding the thread-level of the ordering IP address.

**Comment by scottcwilson** [comment]
This has very nice output.  It correctly identified the IP I was checking as a likely bad guy. 

I wonder if this should be configurable in case people have subscriptions to premium services that check such things?

**Comment by lat9** [comment]
If they've got an account, there's a login link that could be used.

**Comment by proseLA** [comment]
i vote for ipdata.co.   the data is presented in a much more user friendly way.

in addition, i find the various country and city guides entertaining without being offensive...

**Comment by lat9** [comment]
> Please note, I'm checking with the ipdata.co founder to make sure that this would be OK-fine with him.

... and I just received a response that the link would be appreciated.

**Comment by scottcwilson** [comment]
Absolutely - please ask them what sort of marketing text they would like and I will add it.

**Comment by jonathan-kosgei** [comment]
Thanks @lat9 for the recommendation and thank you all very much for considering us for this and for the positive feedback! We would definitely appreciate the link :wink: 

Some fun tips;
- Use https://ipdata.co/random to see random IPs and get to see different places around the world
- Use https://ipdata.co/me to see the data for your own IP address

**Comment by scottcwilson** [comment]
Thanks for your support of the Zen Cart project, @jonathan-kosgei.

**Comment by scottcwilson** [comment]
@lat9 Will you post to the forum as well?

**Comment by simon1066** [comment]
Should we not also use ipdata.co in `admin/customers.php` and `admin/whos_online.php` instead of the existing `https://whois.domaintools.com/`?

**Comment by scottcwilson** [comment]
Those still work; the one I reported did not.

**Comment by lat9** [comment]
Although, per @simon1066's comment, consistency would be nice.  There are rogue customers and people on-line as well as those who've placed orders.

**Comment by lat9** [comment]
> @lat9 Will you post to the forum as well?

What should I post on the forum?

**Comment by scottcwilson** [comment]
that this is a bug in all versions, your fix is super easy to apply and thanks for the support of our friends at ipdata.co!

**Comment by scottcwilson** [comment]
> Although, per @simon1066's comment, consistency would be nice. There are rogue customers and people on-line as well as those who've placed orders.

I'm open to this change if you want to do it - I was just saying it wasn't required because those links are not currently broken.
