### ISSUE TITLE
Store Pickup & Ship To Address

### ISSUE THREAD

**Issue by bislewl** [zencart/zencart#594]
Something struck me as odd. When Store Pickup is selected. The customer's ship to address is in the order. However some store-owners/employees don't look at the shipping method and just ship regardless.

Shouldn't the TABLE_ORDERS.delivery_\* fields either be left empty or say something like store pickup? Ideally the store they selected (if there is multiple)

**Comment by drbyte** [comment]
Good point. 

Some challenges: 

1. Mustn't store that information until the customer confirms the purchase (else the physical ship-to preference would get lost in case they want to change their mind and ship it). 

2. The `order` class currently uses the customer's selected ship-to address when storing address details into the db. 

3. If the store-pickup address is to be shown on-screen during checkout, there's nothing presently in code to swap the shipping address back-and-forth between store-pickup and the previously-chosen deliver-to address if the customer plays with the shipping method. (nor anything remembering what their previously-chosen deliver-to address was selected as).

4. How do changes to accommodate this impact on other shipping modules?

**Comment by bislewl** [comment]
My thought was for current versions (hackish style none the less) create an observer that after the TABLE_ORDERS.delivery_* fields are saved go back in and wipe those fields it out if the shipping method is store pickup, and add the store selected.

For future versions I have 2 thoughts.
1 Hide the shipping address with JS (when selected)
2 Not save the shipping address when saving the order, sort of like a virtual product that has no shipping, and just store the store selected

The virtual products does have some sort of promise I think even just as a referance point

**Comment by lhungil** [comment]
I think it would be best to place the actual "Ship To" address in the order. So in this case, the actual store's physical address (possibly using an observer).

Short term, probably easiest to have the shipping information be configuration options in the "Store Pickup" shipping module... Which would support multiple different store pickup options without impacting the database or other modules...

**Comment by proseLA** [comment]
i think that it is not as crucial to show the customer the store's address when they select in-store-pickup.  however storing it in the orders table is what i have done in the past by the addition of a function in the orders class.  based on the selection of an in-store pickup shipping method would change the delivery address to the config values for the store.  that way everything is kept in the orders class.

**Comment by scottcwilson** [comment]
Closing issue due to lack of interest and activity.
