### ISSUE TITLE
modules/shipping_estimator: parsing of quotes: "continue"

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5945]
as commented here: https://github.com/zencart/zencart/pull/5942/files#r1298715090
> Should that have been `continue 2;` instead? ie: abort the current foreach (because it's satisfied) and jump to the next iteration of the outer foreach. Perhaps the redundant continue statement was a bug that should have specified the '2' part?

https://github.com/zencart/zencart/blob/bd417ab84933856dcea06cd412373af821cb91bd/includes/modules/shipping_estimator.php#L211

This code is parsed on a change of the selected address.
Although it grabs the correct quote-method, it continues to parse the rest for no reason, so I believe this should be continue 2.

**Comment by drbyte** [comment]
Yes, while it only saves a tiny bit of CPU time, it is more efficient.
