### ISSUE TITLE
Manufactures Sidebox dosn't check for products/active status even when set in admin

### ISSUE THREAD

**Issue by highburyeye** [zencart/zencart#5961]
**Describe the bug**
Manufactures Sidebox dosn't check for products/active status even when set in admin.
Setting ADMIN-->CONFIGURATION-->MAXIUMVALUES-->Manufacturers List - Verify Product Exist to true (1)
should filter the manufactures side box to exlude manufactures with no active products
it dosnt work

**Version**
1.5.8.a
PHP version: 7.4
MySQL version: 8.0.34
Plugins that may be related: none
What older/newer versions were also tested?none

**To Reproduce**
see description

TO FIX EDIT FILE --includes--modules--sideboxes--manufacturers.php
remove quotes around "1" on line 11
if (PRODUCTS_MANUFACTURERS_STATUS === "1") {
change to
if (PRODUCTS_MANUFACTURERS_STATUS === 1) {//BUG FIX TC CHANGED

...
<?php
/**
 * manufacturers sidebox - displays a list of manufacturers so customer can choose to filter on their products only
 *
 * @copyright Copyright 2003-2022 Zen Cart Development Team
 * @copyright Portions Copyright 2003 osCommerce
 * @license http://www.zen-cart.com/license/2_0.txt GNU Public License V2.0
 * @version $Id: lat9 2022 Jul 05 Modified in v1.5.8-alpha $
 */
// only check products if requested - this may slow down the processing of the manufacturers sidebox
if (PRODUCTS_MANUFACTURERS_STATUS === 1) {//BUG FIX TC CHANGED
    $manufacturer_sidebox_query =
        "SELECT DISTINCT m.manufacturers_id, m.manufacturers_name
                    FROM " . TABLE_MANUFACTURERS . " m
                            LEFT JOIN " . TABLE_PRODUCTS . " p ON m.manufacturers_id = p.manufacturers_id
                   WHERE p.products_status = 1
                   ORDER BY manufacturers_name";

**Comment by scottcwilson** [comment]
Please PR.

**Comment by drbyte** [comment]
This is interesting. That setting is stored as a string in the database, and while there's a function to convert some of those settings to integers, that specific key is set to be reserved as a string:

https://github.com/zencart/zencart/blob/207570115910e89cf89a5b3b7c039f7256cd3bbd/laravel/app/Models/Configuration.php#L19C26-L19C26
