### ISSUE TITLE
Developers Tool Kit - Searching

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#5965]
i am not sure why it is on the developers key search that requires an exact search in order to get a hit.  

i further do not know why the description does not mention that one can use `%` for like type searches, ie a search for `ENTRY_POSTCODE_` returns nothing while a search for `ENTRY_POSTCODE_%` returns 1 entry.

does anyone use searches with `%`?

personally i would like to pull it out, so that we can change this section to 1 line:

https://github.com/zencart/zencart/blob/207570115910e89cf89a5b3b7c039f7256cd3bbd/admin/developers_tool_kit.php#L352-L355

the problem would be that a search for `ENTRY_POSTCODE_%` would now fail; although that could be addressed by stripping the `%` prior to the search.  which i suppose would be the easiest way to address this problem.

any one have an issue with simplifying this code?

**Comment by drbyte** [comment]
Exact matching was done so that only config keys could be a direct lookup and not necessarily found in other places, so quick editing of their settings would be an easy next action.
Wildcarding was included for convenience.

What is the problem you're trying to solve?

**Comment by proseLA** [comment]
i think the problem i am trying to solve is accurately described in my OP.

i would like to do wildcard config key searching without the need to enter `%` as part of the search.

i think allowing wildcard searching without providing any clue that it exists on the page nor any direction as to how to do it is a little too, for lack of a better term, heavy handed to me.  

i have never liked not having wildcard searching on the keys, as i really only use this page for searching the keys.  i'm perfectly capable of using `grep` on the command line to search for non db related items.  

and now, after burning a bunch of time, figuring out that the code does in fact do wildcard searches, i do not understand why there is no indication that wildcard config key searches can be done on this page.

i'm sorry, it's not really convenient.  i really do not like it.

**Comment by drbyte** [comment]
> i would like to do wildcard config key searching without the need to enter % as part of the search.

To clarify: you'd like all config key searching to assume wildcard intention all the time. 

ie:  use "WHERE foo LIKE '%bar%'" out of the box

and that when you said 

> change this section to 1 line:

you meant

```diff
 // support configuration_key constants 
- $cfgKeySearch = " OR configuration_key = :zcconfigkey:"; 
- if (strtoupper($search) == $search && preg_match('/^(%?).*(%?)$/', $search)) 
-   $cfgKeySearch = " OR configuration_key like :zcconfigkey: "; 
+ $cfgKeySearch = " OR configuration_key like %:zcconfigkey:% "; 
```

I agree that probably nobody has been manually adding a % in their searches because it was undocumented.
And probably is not even needed if it is done by default.

**Comment by drbyte** [comment]
So assuming I'm understanding you correctly now, then the next logical question is: **what are the potential undesired side-effects?**, other than what you mentioned of no longer needing to include a % manually (and I don't think we need to trim it off, because I'm pretty sure people will be glad to no longer have to add it anyway).

**Comment by proseLA** [comment]
yes, you have it correct.

although i think the diffs should be 
 ```diff
  // support configuration_key constants 
 - $cfgKeySearch = " OR configuration_key = :zcconfigkey:"; 
 - if (strtoupper($search) == $search && preg_match('/^(%?).*(%?)$/', $search)) 
 -   $cfgKeySearch = " OR configuration_key like :zcconfigkey: "; 
 + $cfgKeySearch = " OR configuration_key like '%:zcconfigkey:%' "; 
 ```
and then on line 363:

```diff
-$sql = $db->BindVars($sql, ':zcconfigkey:', str_replace('_', '\_', strtoupper($search)), 'string');
+$sql = $db->BindVars($sql, ':zcconfigkey:', str_replace('_', '\_', strtoupper($search)), 'noquotestring');
```

as far as undesired side effects, the only one i could think was if people were already using `%` in their searches.  other than that, people may see more config values than they intended...  but i'm not really sure it is undesired.

perhaps someone else may come up with something.
