### ISSUE TITLE
paypalwpp: function alterShippingEditButton

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5967]
Is this function obsolete?

https://github.com/zencart/zencart/blob/2e752c08704edfc38623c68dd29ebe22a95872e9/includes/modules/payment/paypalwpp.php#L809-L814

**Comment by lat9** [comment]
Nope, it's used by the `checkout_shipping` and `checkout_confirmation` pages' `header_php.php` files as well as the `zcAjaxPayment.php` class-file.  In the core code, `paypalwpp` is the only payment module that provides that _optional_ method.
