### ISSUE TITLE
ROBOTS_PAGES_TO_SKIP not recognised

### ISSUE THREAD

**Issue by simon1066** [zencart/zencart#5973]
Not sure how I didn't notice this earlier. `<meta name="robots" content="noindex, nofollow">` is not being added to the pages as defined in `robots_pages_to_skip.php`, due to the way in which the file has been formatted. This is since ZC v1.5.8 and was raised in this bug report, https://www.zen-cart.com/showthread.php?229206-Robots_pages_to_skip

Google has been indexing everything at will so I have temporarily re-formatted my defines to a single line entry.

**Comment by scottcwilson** [comment]
Thanks Simon.  Will you PR?

**Comment by scottcwilson** [comment]
Use your best judgement.

**Comment by simon1066** [comment]
okey dokey.
