### ISSUE TITLE
shipping modules: quote array content/error handling

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5979]
Using the incart shipping estimator.
If I pass an invalid postcode to Advanced Shipper, it passes back an error 

![2023-09-02 18_16_12-The Shopping Cart - Motorvista, Motorcycle Accessories Shop (Spain) — Mozilla Fi](https://github.com/zencart/zencart/assets/4391026/37453bff-2454-4be1-9a3a-3d19f1e595b2)

and I'll get a debug from line 210, as the method array is missing the 'id' key
https://github.com/zencart/zencart/blob/b3cd1f31aa5578acc51c3c7c5f29c6c338e311d5/includes/modules/shipping_estimator.php#L202-L216

Here is a normal quote return:
![image](https://github.com/zencart/zencart/assets/4391026/732e795d-de69-4514-9b07-c7833f45a074)

So in the interests of knowing if returning an empty method is ok when the quote is an error, I check the docs:
https://docs.zen-cart.com/dev/code/modules/shipping_modules/

which clear about the required fields for the quote, but not the method.

So, I tried to make an error with a vanilla module and found there was no error handling in the others, only the zone rate.

When testing the zone rate, and for example setting ES as a zone to skip, but choosing ES as the selected country, there is no error shown and in fact the whole quote array is empty:
![2023-09-02 18_21_58-The Shopping Cart - Motorvista, Motorcycle Accessories Shop (Spain) — Mozilla Fi](https://github.com/zencart/zencart/assets/4391026/b0ff4dd5-15f3-4e91-aaec-dab2c35cb774)

The docs state that the module **must** return certain keys in the quote array, but this does not.

That is a side issue but it impinges on whether a quote array should also be checked for a valid method array...or if it should instead be checked earlier for an error message field and then aborted, or should return nothing at all as per zones but not as per the docs....

**Comment by proseLA** [comment]
if advanced shipper is causing an error, i would fix advanced shipper.

i am not a fan of adding additional code to address problems with a plugin.

**Comment by torvista** [comment]
I expected someone to say that.
Hence I tried to explain what might be some inconsistency between core code and docs to get clarification on what should be getting returned in a correct or error case.
