### ISSUE TITLE
Checkout Shipping shows "Continue" to Step 2 Payment, when not available/no shipping allowed

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5988]
Example, 
Disable Shipping Module Store Pickup
Enable Shipping Module freeshipper

Add Free Shipping Product with Weight to cart, this product has Always Free Shipping enabled

**Checkout Shipping:**

![image](https://github.com/zencart/zencart/assets/4391026/db8d63a9-c5ef-4138-b1a4-2f17e316d0ad)

In freeshipping module, set zone restriction to exclude the customer zone:

**1) The cart shows a partial Shipping Estimator, with no information why.**

![image](https://github.com/zencart/zencart/assets/4391026/46b763c3-64c6-4c2c-8348-8ce68e899378)

**2) Checkout Shipping offers to Continue to Payment, (it just redirects back to the shipping page)**

![2023-09-07 15_54_40-Step 1 of 3 - Delivery Information _ Zen Cart!, The Art of E-commerce — Mozilla ](https://github.com/zencart/zencart/assets/4391026/7eb6018f-bb7b-4f32-b5f6-5ed462c314a3)

**Comment by scottcwilson** [comment]
The current behavior is correct IMHO.  Many people won't read the message and will need to press Continue and get bounced back to the Shipping page before they figure out they have to use another address.

**Comment by drbyte** [comment]
I can see how it would be a little more intuitive to disable the "Continue" button if we know there's a problem.

**Comment by torvista** [comment]
>Many people won't read the message and will need to press Continue and get bounced back to the Shipping page before they figure out they have to use another address.

Bad UX in my book. If you can't Continue, don't offer it. A wasted click + a wtf matters these days.
While I'm not keen on being forced to think or read as much as the next millenial, I prefer that than being presented with an option that appears to not work.

**Comment by drbyte** [comment]
Options:

1. "Disable" the button, but leave it on-screen.
2. "Hide" the button, so there's no way to click it. 

Caveats:
- by disabling it but leaving it on-screen, they may still try to click and wonder why it's doing nothing.
- by hiding the button, it leaves them wondering "um, what do I do next? where's the button for the next step?"
(Obviously, we have to all assume that if they're looking for a Continue button, they've not yet noticed the red message that tells them there's a problem to fix, nor have they noticed the one at the top of the screen that tells them their shipping options have changed (if they'd already started checkout earlier and changed their cart contents).)

`tpl_checkout_shipping_default.php`

To do option 1, make the on-screen button "disabled":
```diff
-<div class="buttonRow forward"><?php echo zen_image_submit(BUTTON_IMAGE_CONTINUE_CHECKOUT, BUTTON_CONTINUE_ALT); ?></div>
+<div class="buttonRow forward"><?php echo zen_image_submit(BUTTON_IMAGE_CONTINUE_CHECKOUT, BUTTON_CONTINUE_ALT, (zen_count_shipping_modules() > 0 ? '' : 'disabled="disabled"')); ?></div>
```
Probably will want to enhance the CSS to detect the `disabled` state and show a colour that indicates it's not clickable, maybe make it match the hover state so the hover effect appears to be moot?

To do option 2, wrap one or more of the `buttonRow` divs in a conditional:
```diff
+<?php if (zen_count_shipping_modules() > 0) { ?>
<div class="buttonRow forward"><?php echo zen_image_submit(BUTTON_IMAGE_CONTINUE_CHECKOUT, BUTTON_CONTINUE_ALT); ?></div>
<div class="buttonRow back"><?php echo '<strong>' . TITLE_CONTINUE_CHECKOUT_PROCEDURE . '</strong>' . '<br>' . TEXT_CONTINUE_CHECKOUT_PROCEDURE; ?></div>
+<?php } ?>
```

**Comment by torvista** [comment]
I would hide it...
naturally the eye would goe straight to the bottom of the screen to the disabled Continue without reading.

If it's hidden, it's obvious the process cannot continue and the user is forced to read why.

**Comment by scottcwilson** [comment]
Hiding the button is a terrible idea.  Graying it out or disabling it is reasonable but hiding it is confusing and will lead to customer complaints to shopowners, because customers will be searching high and low trying to find it and not know where it went.  (AGAIN: Many people won't read the message that explains the situation the first time.)

**Comment by drbyte** [comment]
I propose a compromise: Swap the button with "Error". 
<img width="811" alt="Screen Shot 2024-01-11 at 11 20 09 PM" src="https://github.com/zencart/zencart/assets/404472/cafa1ac9-1198-4aaa-907e-30baab631301">

**Comment by torvista** [comment]
>Hiding the button is a terrible idea.

You are welcome to your opinion. A button you can't press, with no linked text explanation is a terrible idea. Maybe the text explanation should be the error button. "Error" implies something internally has broken/is not working/you've done something wrong. All incorrect conclusions for the user.

> Graying it out or disabling it is reasonable but hiding it is confusing and will lead to customer complaints to shopowners, because customers will be searching high and low trying to find it and not know where it went.
Really? Wow, they are stupid.

>(AGAIN: Many people won't read the message that explains the situation the first time.)

Since the page goes nowhere, they've got all the time in the world to read. Sorry, I've no sympathy. There is hardly an excess of text to overload the brain.

But to continue nitpicking for the hard-of-thinking:
 "Not Available **at this Time**": is misleading.
"Sorry, we are not shipping...." is pretty clear, maybe it should be bigger and in blink.
"Please contact us...." **is the call to action** and maybe should be **the** only button to press.

I don't think I've anything further to add, so whatever.
There are some real UX experts lurking here who will have more informed opinions.

**Comment by scottcwilson** [comment]
Final response: We don't have a button you can't press now.  We have a button you can press that yields an error message.  This is accessible and predictable.  It has been like this for 20 years with no complaints or confusion except for one person.  We should not be introducing changes like this, which will cause different behavior in different templates and will cause customer frustration.

**Comment by torvista** [comment]
I've never had a comment from a customer about anything, other than something preventing the purchase.
I certainly don't take that to mean all is perfect and needs no improvement.
Every issue raised on this project comes from "one person", and the more people express their opinion the better.

**Comment by drbyte** [comment]
> But to continue nitpicking for the hard-of-thinking:
"Not Available at this Time": is misleading.
"Sorry, we are not shipping...." is pretty clear, maybe it should be bigger and in blink.

To your point, perhaps the wording can be made clearer. 

Unfortunately, the more words you use, the less people will read it!

Perhaps this:
![Screen Shot 2024-01-12 at 1 45 47 PM](https://github.com/zencart/zencart/assets/404472/ee6c5fd5-7ef5-487b-8afd-50354ea66abd)

**Comment by drbyte** [comment]
> "Please contact us...." is the call to action and maybe should be the only button to press.

You are correct. Under certain circumstances.

But, it's not the "only" CTA. Changing their address or their cart contents may solve the problem.
I imagine that adding yet another block of text that tells them all the possible CTAs they could take is probably counter-productive.

But I suppose if you wanted to change the "Continue" button from being a form-submit to being a link to the Contact Us page, that could work.

**Comment by dbltoe** [comment]
It's always a challenge to be succinct when so much information needs to be displayed to the customer.

The smallest notification I can come up with is

>Unfortunately, we are unable to ship to the address you provided. It appears there may be an issue with the address. Please double-check and ensure it is accurate. If you need further assistance, please feel free to contact our customer support team.

**Comment by drbyte** [comment]
So ... a myriad of opinions have been expressed:
- leave it all alone
- hide the continue button, so the user has to resolve their confusion themselves
- show a disabled error button, so the user has more clarity that they need to resolve something
- do something with "Contact Us" as a call-to-action
- add more error messaging
- clarify what is wrong so the user has more direction about actions they could take

The opinions expressed also appear to be strongly-held. 
And those opinions are based on what individual stores are commonly doing.

Usually such a situation means that adding "yet another" configuration switch may be needed.
But the challenge then is in deciding what options that "switch" offers control over.

**Comment by drbyte** [comment]
Something that's been "lost"/absent from this discussion is that there's no indication given to the customer that if they changed their address to someplace the store ships to (after guessing where that might be), then checkout could proceed.
Similarly, they might be able to shrink the size of their order (probably by weight, cuz that's what affects shipping, more than by price), and then some other shipping options might come available.

That's probably only fixable by having the storeowner add some clarifying text, perhaps in the define-page for this page.

Another option could be to compile some logic that assesses why some "enabled" shipping modules have come back without any available quotes. That could give clues as to potential actions the shopper could take: but it might require asking for additional shipping quotes for simulated modified shipments (ie: fewer packages or lower weights, to test whether the module gives something back for "that"). But that could get really complicated really fast, depending on how much breadth is built to support a wide group of potential shipping modules.

**Comment by torvista** [comment]
>some logic that assesses why some "enabled" shipping modules have come back without any available quotes

I would have thought that this would be the best option in an ideal world, to give precise information/not leave the customer guessing and forcing them to contact the shop or second-guess the reason for the refusal. But, sounds like a lot of work.

I still think no Continue button and a big Contact Us button is the simplest catch-all, to illustrate the only possible course of action even for the most neuronically-challenged.

Others should comment.
