### ISSUE TITLE
admin/category_products_listing: Shouldn't the image-column be optional?

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#5993]
As indicated by a couple of up-votes in [this](https://github.com/zencart/zencart/pull/4222) PR that added the category/product images to the admin's Categories/Products listing, shouldn't the image column have a soft-setting to allow a quick way to disable that information from the view?

Not all sites want that additional 'clutter'.

**Comment by torvista** [comment]
I think an on-page setting is more appropriate.
Generally I use no images for speed, but often I or another admin wants images for identification.
I put it here years ago
![image](https://github.com/zencart/zencart/assets/4391026/6da9c3c6-e320-460f-8c9c-137f5c048f85)
but it would probably be better with the legend.
