### ISSUE TITLE
Modal DIV instead of popup screen. UI/UX suggestion and code.

### ISSUE THREAD

**Issue by MarkoKrsic** [zencart/zencart#6004]
**Is your feature request related to a problem? Please describe.**
A clear problem is user behaviour. Swiping back or closing a tab is a autopilot browsing user's worst progress killer. They will cancel out of the transaction intent on a psychological level.

**Describe the solution you'd like**
Replace JS popup window with Modal DIV.

**Describe alternatives you've considered**
Replaced code inplace for main product image/additional images.

**Additional context**
I have provided the code as file attachments. First review the code then strip off the MODAL_ prefix and rename to `.php` extension to test out for inplace replacement. Tested with 1.58 and 2.0alpha.

Replaces

`/includes/templates/template_default/templates/tpl_modules_main_product_image.php`

and

`/includes/modules/additional_images.php`.

[MODAL_additional_images.txt](https://github.com/zencart/zencart/files/12839360/MODAL_additional_images.txt)
[MODAL_tpl_modules_main_product_image.txt](https://github.com/zencart/zencart/files/12839362/MODAL_tpl_modules_main_product_image.txt)

NOTE:I will put a fork and merge request if warranted, tried doing that first but GitHub is broken right now and trying to fork results in a blank page.

**Comment by lat9** [comment]
Thanks for doing this!  I'm in the middle of something right now, but will check out what you've done real-soon-now!

**Comment by MarkoKrsic** [comment]
I have some more improvements coming, let me know if whats there already is a good start.

In the verison I pusehd last to my fork I have the formatting now working so that image sizes are respected based on the basis of the width setting in the admin menu, before they were hard coded into the CSS. 

I just need to know it's wanted in the project and I will complete it as necessary so that CSS is split out into CSS folder, and the image sources/sizes are respected based on existing admin settings panel for images. 

The issue I am facing is running two modal scripts in the same page, one cancels out the other. If you test it out you will notice the original base image is presented as a  main image but also appears in the listing of additional images. It can be excluded using 

`    for ($i=0, $n=$num_images; $i<$n; $i++) { // Start from 1 to exclude the first image` on line 151but it that prevents the first image from zooming.

Letting you know this if you want to mess around with it otherwise I will get it all done and concise if necessary. I managed to push a merge request finally after posting the above last night so if you like the script as is there is that as well.

**Comment by MarkoKrsic** [comment]
I have completed the work to have the main image show once and open in its own modal with additional images working as expected. Remember to rename to `.php` and strip the` MODAL_` prefix.
[MODAL_tpl_modules_main_product_image.txt](https://github.com/zencart/zencart/files/12845169/MODAL_tpl_modules_main_product_image.txt)
[MODAL_additional_images.txt](https://github.com/zencart/zencart/files/12845170/MODAL_additional_images.txt)

**Comment by scottcwilson** [comment]
@MarkoKrsic Can you update your fork, switch to the master branch and create a PR?

**Comment by scottcwilson** [comment]
PR #6008 has been created - thank you!
