### ISSUE TITLE
Missing insert button when trying to add music genres and recording companies

### ISSUE THREAD

**Issue by techrevolution4evr** [zencart/zencart#6009]
**Describe the bug**
Be sure to explain the business problem that this bug is affecting.

The insert button is missing when I try to add a record company and music genre on the Zen Cart admin console. This also appears for recording artists as well.

**Version**
Zen Cart version: v.1.5.8a 
PHP version: 8,2,1
MySQL version: 8.0
Plugins that may be related: N/A
What older/newer versions were also tested? - Unfortunately not possible. Using this for a college course and our instructor would like us to use the latest version of Zen Cart.

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Go to Your Zen Cart admin login and enter your credentials
2. Click on Extras - Music Genre's/Recording Companies/Record Artists
3. The insert button is not shown on etiher of those pages mentioned.

**Expected behavior**
An insert button is expected on Music Genre's/Recording Companies/Record Artists

**Screenshots**
If applicable, add screenshots to help explain.
![Screenshot from 2023-10-09 14-36-07](https://github.com/zencart/zencart/assets/121281707/c7cfbcb1-f5cc-4cfd-8904-cdde88e7be4f)
![Screenshot from 2023-10-09 14-36-34](https://github.com/zencart/zencart/assets/121281707/0f091811-7138-4029-a3e5-3bce472f6ede)

This is also shown on Record Artists as well.

**Debug/Error Logs**
Include debug logs containing PHP and/or MySQL error details. These are often found in your /logs/ directory as myDebug-xxxxx.log files.

My PHP error log is too long to post. 

MySQL logs: N/A

**Devices (please complete the following information):**
 - Operating System: [e.g. Windows, Mac, Android, iOS]
 - Browser [e.g. chrome, firefox] and version number
  
   Ubuntu Desktop 22.04 with firefox 118.01

**Additional context**
   N/A

**Comment by drbyte** [comment]
I think this is a duplicate of #5923.
Fixes posted in https://github.com/zencart/zencart/pull/5924/files and https://github.com/zencart/zencart/pull/5935/files

**Comment by techrevolution4evr** [comment]
Hello.

When I replace the files using the links you gave me, I am still getting the same issue, only now I can see the Insert button for media manager now.

**Comment by techrevolution4evr** [comment]
My mistake. I did not add all the fixed files before. I did now and all the insert buttons are now showing.

Resolved.
