### ISSUE TITLE
`checkout_new_address` can create invalid address-book records

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#6018]
With the incorporation of [this](https://github.com/zencart/zencart/commit/e3c022f3fd187d39280c373ee8116fbeb0b54fa0) commit (PR #5711 to fix  #5707), if
1. The site's configuration has `ACCOUNT_STATE_DRAW_INITIAL_DROPDOWN` set to 'false' (the installation default)
2. A customer chooses to create a new shipping/billing address during checkout.
3. The new address is associated with a country that has zones (e.g. United States)

The `address_book` table record created by `/includes/modules/checkout_new_address.php` has the `address_book::zone_id` field is set to `0` and no error message is issued if the textual state-field input doesn't match a `zone_code` or `zone_name` associated with that country.

This results in erroneous tax calculations when the site has country/state-specific tax rates and the customer uses that malformed address as their shipping address.

**Comment by piloujp** [comment]
I checked that and found another way fix both original and new bug.
Precedent commit adding ` && ACCOUNT_STATE_DRAW_INITIAL_DROPDOWN === 'true'` should be removed and line (87 for Checkout_new_address.php and 206 for create_account.php) should be changed from
`((trim($state) != '' && $zone_id == 0) ? "(upper(zone_name) like ':zoneState%' OR upper(zone_code) like '%:zoneState%') OR " : "") .`
to
`((trim($state) != '' && $zone_id == false) ? "(upper(zone_name) like ':zoneState%' OR upper(zone_code) like '%:zoneState%') OR " : "") .`
Please have a look at it.

**Comment by lat9** [comment]
Thanks, @piloujp, for your quick reply.
