### ISSUE TITLE
Sort heading anchors should be rel=nofollow for SEO

### ISSUE THREAD

**Issue by neekfenwick** [zencart/zencart#6040]
https://github.com/zencart/zencart/blob/9ae0b145fff3d89bbeafdae83b1f9c00dbdf6788/includes/functions/functions_general.php#L24

My experience with search engines crawling our site is that they will crawl not only each page of results (page 1, 2, 3 etc) but also the sort anchors (sort by product name asc,desc etc). 

e.g. not only
https://www.my-shop.com/index.php?main_page=index&cPath=1_2_3&page=1&sort=2a
https://www.my-shop.com/index.php?main_page=index&cPath=1_2_3&page=2&sort=2a
https://www.my-shop.com/index.php?main_page=index&cPath=1_2_3&page=3&sort=2a

But also a single page sorted in multiple ways:
https://www.my-shop.com/index.php?main_page=index&cPath=1_2_3&page=1&sort=2a
https://www.my-shop.com/index.php?main_page=index&cPath=1_2_3&page=1&sort=2d
https://www.my-shop.com/index.php?main_page=index&cPath=1_2_3&page=1&sort=3a
https://www.my-shop.com/index.php?main_page=index&cPath=1_2_3&page=1&sort=3d

`init_canonical.php` does a good job of creating a `meta name=canonical` tag for search results that does not include the `sort` query parameter, so at least each page of results is treated as canonically the same as an unsorted page, but these sorted pages shouldn't really be crawled at all.

The links to the same page but with different sorting should be `rel=nofollow`.

`        $sort_prefix = '<a href="' . zen_href_link($_GET['main_page'], zen_get_all_get_params(array('page', 'info', 'sort')) . 'page=1&sort=' . $colnum . ($sortby == $colnum . 'a' ? 'd' : 'a')) . '" title="' . zen_output_string(TEXT_SORT_PRODUCTS . ($sortby == $colnum . 'd' || substr($sortby, 0, 1) != $colnum ? TEXT_ASCENDINGLY : TEXT_DESCENDINGLY) . TEXT_BY . $heading) . '" class="productListing-heading" rel="nofollow">';
`

Thoughts?

**Comment by drbyte** [comment]
I agree: links used to control sort-order should be nofollow.

**Comment by neekfenwick** [comment]
I've created PR #6040 but it hasn't auto-linked to this Issue, something wrong with by github-fu.

**Comment by lat9** [comment]
> I've created PR #6040 but it hasn't auto-linked to this Issue, something wrong with by github-fu.

You needed to, like I did in my comment on the commit, add "Fixes #{issue number}" as part of the commit's comments.
