### ISSUE TITLE
Protected variable in BasePluginInstaller causes Exception when ScriptedInstaller generates invalid SQL

### ISSUE THREAD

**Issue by neekfenwick** [zencart/zencart#6041]
**Describe the bug**
PluginInstaller protected field causes a crash in case an SQL error was encountered.

**Version**
Zen Cart version: v158
PHP version: 8.1

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Create a ScriptedInstaller.php that generates invalid SQL.  You can probably just mangle one you have handy.
2. Try to install the plugin via admin/index.php?cmd=plugin_manager

**Expected behavior**
The PluginInstaller sets an `outputMessageList` containing a friendly error message to be seen by the user.

**Screenshots**
![Screenshot from 2023-11-03 15-09-30](https://github.com/zencart/zencart/assets/266415/f529f061-6a2d-4c1b-8522-6149f61f26fd)

**Additional context**
I just started working with the plugin installer today so I'm unsure what the intention is, here.  Should there be a public getter on `BasePluginInstaller` to expose the `errorContainer` object, or is there another way this was intended to work?

I can fix my broken SQL and get on, but this crash in error handling should be addressed 😀 I'd be happy to PR given some guidance.

**Comment by zcwilt** [comment]
Hmm. 
Are you using up to date code. 

My version of that function looks different.

**Comment by zcwilt** [comment]
![image](https://github.com/zencart/zencart/assets/227354/0e1c4f4b-a512-4e11-a0cd-b6b90102ef9a)

**Comment by proseLA** [comment]
similar to [my comment here](https://github.com/zencart/zencart/pull/6036#discussion_r1382043162), it does look like the problem was there in th v1.5.8a-alpha tag and has since been corrected on the master branch.

**Comment by neekfenwick** [comment]
Thanks guys, my mistake, I keep thinking that by being on the `v158` branch I'm going to be using the latest and greatest code.  It does indeed look fixed from a glance at `upstream/master`.
