### ISSUE TITLE
spider hit on popup_image causes debug

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6049]
example bad url from msn bot

> https://SITE/index.php?main_page=popup_image&pid=50

log from local dev/vanilla ZC200 site (as I get different errors on hosting due to custom coding/subsequent processing)

> [10-Nov-2023 19:44:23 UTC] Request URI: /zencart/index.php?main_page=popup_image&pid=50, IP address: 127.0.0.1, Language id 1
> #0 D:\Github\zencart\includes\modules\pages\popup_image\header_php.php(27): zen_debug_error_handler()
> #1 D:\Github\zencart\index.php(35): require('D:\\Github\\zenca...')
> --> PHP Warning: Undefined array key "pID" in D:\Github\zencart\includes\modules\pages\popup_image\header_php.php on line 27.

php8.3.0RC2, strict reporting

**Comment by lat9** [comment]
I'm pretty sure that this is corrected by PR #6044; I'd seen the same in the logs of one of my clients.

**Comment by torvista** [comment]
Yes, it cures this issue. I still get a couple more subsequent debugs that I can't reproduce on a vanilla site. Yet.
