### ISSUE TITLE
Links between admin customer and order page for easier navigation.

### ISSUE THREAD

**Issue by neekfenwick** [zencart/zencart#6054]
The lack of hyperlinks from side panels in Admin give me grief.

**Is your feature request related to a problem? Please describe.**
When viewing an Order, you see the Customer's email address in the side panel but no easy way to navigate to their customer record (for example, to place another order as them).
When viewing a Customer, you see a number of orders, but no easy way to get to those orders.

**Describe the solution you'd like**
- Customer email address viewed next to an order ought to be hyperlinked to the Customers page with that record selected.
- Order details viewed next to a Customer ought to list the last few orders (say, 5), in date order, hyperlinked to the order details page for each order.

I'm going to add these to my local shop just to ease things.

Anyone want to add anything to that?

**Comment by neekfenwick** [comment]
e.g. customer screen:
![Screenshot from 2023-11-16 15-45-41](https://github.com/zencart/zencart/assets/266415/354feeec-934f-4977-a3b4-f673ddc534a9)
e.g. order screen:
![Screenshot from 2023-11-16 15-45-05](https://github.com/zencart/zencart/assets/266415/c1bdc1c9-0b9b-4f1f-91f1-edfc80a67d5a)

**Comment by neekfenwick** [comment]
I just noticed the "Orders" button on the Customers screen that takes you to a pre-filtered Orders screen, so perhaps that idea is redundant, except to say that it would save a click to have the latest order id's listed as a one-click to go to the Details page for that order. I'm pretty sure our staff only ever want to single-click to edit the latest order by a customer.

**Comment by lat9** [comment]
> The lack of hyperlinks from side panels in Admin give me grief.
> 
> **Is your feature request related to a problem? Please describe.** When viewing an Order, you see the Customer's email address in the side panel but no easy way to navigate to their customer record (for example, to place another order as them). When viewing a Customer, you see a number of orders, but no easy way to get to those orders.
> 
> **Describe the solution you'd like**
> 
>     * Customer email address viewed next to an order ought to be hyperlinked to the Customers page with that record selected.
> 
>     * Order details viewed next to a Customer ought to list the last few orders (say, 5), in date order, hyperlinked to the order details page for each order.
> 
> 
> I'm going to add these to my local shop just to ease things.
> 
> Anyone want to add anything to that?

On the orders' listing (**_Customers :: Orders_**), there's a teeny icon next to each customer's name:
![image](https://github.com/zencart/zencart/assets/2685585/2e33bac8-b7db-4bd2-a610-8d1ab4bc7080)
... clicking on that takes you to the **_Customers :: Customers_** listing with that customer's specific record highlighted.

**Comment by neekfenwick** [comment]
> On the orders' listing (**_Customers :: Orders_**), there's a teeny icon next to each customer's name: ![image](https://user-images.githubusercontent.com/2685585/283469093-2e33bac8-b7db-4bd2-a610-8d1ab4bc7080.png) ... clicking on that takes you to the **_Customers :: Customers_** listing with that customer's specific record highlighted.

Wow, I never noticed that :) (or forgot about it) It does exactly what my modification to the email address in the side panel does, no problem removing that if it's redundant.  The pale grey/white icon blends into the background, do you think changing it to a more obvious indicator using a FontAwesome icon might help it stand out?

![Screenshot from 2023-11-17 08-47-20](https://github.com/zencart/zencart/assets/266415/5c971aa7-bcda-41e0-87ef-967464b9d5e6)

On the Customers page with a customer selected, my side panel addition of a list of orders works pretty well, listing the most recent 5, a "..." if there are more than 5, and each has a tooltip showing date, current status.  Is this useful or overkill?

![Screenshot from 2023-11-17 08-54-40](https://github.com/zencart/zencart/assets/266415/dbfb91e4-68e4-47ad-914e-3ef90771d5c3)

I added `Customer::getOrderSummary()` to keep `$db` operations separate from the `customers.php` logic, following the current code style.
