### ISSUE TITLE
category restrictions on coupons only work for master category

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#6057]
in the test data, product `Hewlett Packard LaserJet 1100Xi Linked`, has a master category of `Printers`, but is also in the category of `Big Linked` (at least it is in my test data...).

if one were to set up a coupon that was ONLY valid for `Big Linked` products, this product would not be valid.

is this behavior intended/expected?

it seems wrong to me.

**Comment by lat9** [comment]
It seems wrong to me as well.  I'm envisioning (especially in this season) a "Black Friday" category of products that is some percent-off.

**Comment by lat9** [comment]
Running with the current master repository, I've set that category restriction:
![image](https://github.com/zencart/zencart/assets/2685585/a2ef5003-829f-4d8e-a5b2-25b4f0e63e15)

Placing `Hewlett Packard LaserJet 1100Xi Linked` in the cart, navigating to the `checkout_payment` page and entering the associated coupon-code, I'm seeing that the coupon's deduction **_is_** applied.

What's different in my setup and yours?

**Comment by proseLA** [comment]
i believe your coupon is setup incorrectly.  try adding anything else to your cart.  does the coupon also apply to something else not in that category?

**Comment by proseLA** [comment]
in my experience, the coupon needs to be setup like so to restrict to a category:

![image](https://github.com/zencart/zencart/assets/1095136/91628e47-3d81-48ea-9650-d04935bcf6ea)

**Comment by proseLA** [comment]
wow, that is even listed in [the docs!](https://docs.zen-cart.com/user/order_total/coupons/#:~:text=When%20using%20Coupon,TOP%20DENY)

**Comment by proseLA** [comment]
you can see where it validates the category here:

https://github.com/zencart/zencart/blob/f07e2e6e726a8e2db486066502e3d81a0ed42ea1/includes/functions/functions_gvcoupons.php#L212-L216

the code only checks the categories that come back from the `zen_get_product_path` method.

my solution would be to change that section of code and add the following method:

```
function validate_for_category(int $product_id, int $coupon_id)
{
    global $db;
    $productCatPath = zen_get_product_path($product_id) . getLinkedCategories($product_id);
    $catPathArray = array_unique(array_reverse(explode('_', $productCatPath)));
...
function getLinkedCategories(int $productId): string
{
    global $db;
    $sql = 'SELECT categories_id FROM ' . TABLE_PRODUCTS_TO_CATEGORIES . "
                           WHERE products_id =  $productId";
    $result = $db->Execute($sql);

    $catString = '';
    if ($result->EOF) {
        return $catString;
    }

    foreach ($result as $value) {
        $catString .= '_' . $value['categories_id'];
    }
    return $catString;
}
```

**Comment by lat9** [comment]
> i believe your coupon is setup incorrectly. try adding anything else to your cart. does the coupon also apply to something else not in that category?

With that coupon setup, the coupon only applies to a product in the `Big Linked` category:

![image](https://github.com/zencart/zencart/assets/2685585/2a1affc3-1f6b-4018-a11b-96401ac7c6a8)

Although I _do_ see that adding (per the docs reference) that 'start by excluding all categories' restriction causes the coupon to no longer be applied to the order.

**Comment by proseLA** [comment]
i am having trouble reproducing, but here is a thought.  for the coupon that you have set up, add another valid category.  my theory is that the linked product will now not be valid.  the code looks for only a single restriction and applies the logic differently with 1 restriction as opposed to more than 1 restriction.
