### ISSUE TITLE
zen_field_length(TABLE_PRODUCTS_DESCRIPTION, 'products_name') returns a string

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6063]
Should this function not always return an integer?

**Comment by drbyte** [comment]
Perhaps.
But the value is almost exclusively used (eventually) as a string when output to the browser in the generated HTML for field lengths. 
Sure, it passes through an intermediate function call, but it is ultimately represented as a string.

**Comment by torvista** [comment]
I have certainly used it to limit things in code/not in html and as far as I can see, the code where it is generated produces a string or integers/is inconsistent:

https://github.com/zencart/zencart/blob/1da3aa3efc5fbdce79333c06b10bc738c223e230/includes/classes/db/mysql/query_factory.php#L1006-L1032

It seems logical to return a size/length as an integer.

**Comment by drbyte** [comment]
> the code where it is generated produces a string or integers/is inconsistent:

Yes, the hard-coded `$this->max_length` `case`s are integers when the length isn't found already from the db field, in which case it's a string. Typecasting would be needed. 

> It seems logical to return a size/length as an integer.

In the era of strict types, agreed.
