### ISSUE TITLE
Replace use of bitmap icons in admin with FontAwesome icons

### ISSUE THREAD

**Issue by neekfenwick** [zencart/zencart#6065]
Branch: master

Discussed in #6061 https://github.com/zencart/zencart/pull/6061#issuecomment-1824824164 .. would be nice to replace old fashioned icons used in admin such as `icon_edit.gif` and `icon_info.gif` with FontAwesome icons, to get that modern clean look.  Haven't done a deep dive into what's required but some creating grepping should turn up some good candidates.

I will take a stab at it, we can see what's left over.  I worry that store front may have some difficult to deal with buttons.

**Comment by neekfenwick** [comment]
Question to anyone watching this: Is it worthwhile adding a 'tick' and 'x' icon next to the 'OK' and 'Cancel' buttons on various pages?  Searching for 'IMAGE_CANCEL' in `admin` shows 150+ results like this:

    <a href="<?php echo zen_href_link(FILENAME_ADMIN_ACCOUNT) ?>" class="btn btn-default" role="button"><?php echo IMAGE_CANCEL; ?></a>
https://github.com/zencart/zencart/blob/1da3aa3efc5fbdce79333c06b10bc738c223e230/admin/admin_account.php#L125C28-L125C28

![Screenshot from 2023-11-24 22-07-24](https://github.com/zencart/zencart/assets/266415/68f5f072-6e9c-4600-8efc-f190dec3631e)

Easy to add an icon (and the tick to the other button) but, fairly tedious to do & test:

    <a href="<?php echo zen_href_link(FILENAME_ADMIN_ACCOUNT) ?>" class="btn btn-default" role="button"><i class="fa-solid fa-xmark"></i> <?php echo IMAGE_CANCEL; ?></a>
![Screenshot from 2023-11-24 22-06-43](https://github.com/zencart/zencart/assets/266415/6ca59d75-9c81-41e5-895b-b732c5a18e02)

1/ is this against a style guide (*ahem* you know, the well known ZC style guide)
2/ am I missing a bootstrap helper that would do this automatically?

According to https://icons.getbootstrap.com/icons/check/ there is a bootstrap font, but apparently we're using FontAwesome instead.

**Comment by drbyte** [comment]
>  I worry that store front may have some difficult to deal with buttons

Ya, don't touch storefront in this PR. 
A lot of those icons are already addressed in the Bootstrap Template for storefront.

**Comment by drbyte** [comment]
> there is a bootstrap font, but apparently we're using FontAwesome instead.

True. The FontAwesome icon fonts had more traction than the glyphs Bootstrap provides, so we used those.

I think we even skipped including the Bootstrap glyphs in our distro.

**Comment by drbyte** [comment]
I have no opinion on whether to add the icons into the buttons or not.

Probably the main thing to consider is whether the extra space taken by them might interfere with alignments of other elements in the UI where they appear. Probably a low-risk matter, but worth keeping in mind.

**Comment by neekfenwick** [comment]
Thanks @drbyte, I will avoid the button tick/cross icons for now as it doesn't fit this Issue ("replace bitmap icons") and there so many places it touches on.  For now, replacing bitmaps is a pretty big job but going well.  I am not touching store front at all.

There are many instances of e.g. "fa-solid fa-circle-info" and "fa-solid fa-caret-right" with a few accompanying styles, sometimes a tooltip, sometimes a stack icon, it seems good to wrap them in a helper function.  I have `admin/functions/html_output.php::zen_icon()` similar to how `zen_image()` helps produce `<img>` elements.  A few pages have developed their own way of doing things even when they do use FontAwesome and not a bitmap icon (at least two ways of presenting the 'pencil' edit icon, and category_product_listing does its `btn-edit` etc. buttons differently to everywhere else) so I'm managing some housekeeping and standardisation at the same time.

e.g. before:
![Screenshot from 2023-11-25 15-28-57](https://github.com/zencart/zencart/assets/266415/6c285a0b-4f5c-46c6-a603-389abc0b161c)

after:

![Screenshot from 2023-11-25 15-29-12](https://github.com/zencart/zencart/assets/266415/489f4dc6-d2db-4fef-bd0a-c01b5e81740a)

Work is in progress but going well, nicely therapeutic busywork converting everything cosmetically without having to think about too much business logic :)  50 or 60 admin pages/files affected.  I've used some unwise names inherited from the `.gif` filenames that need fixing up but will push something soon.

**Comment by neekfenwick** [comment]
By the way you mentioned tooltips on the other thread.  There are at least three ways tooltips are done:
1/ `title` on the icon, e.g. `<i class="fa-solid fa-foo" title="Wheee"></i>`
2/ `title` on the parent anchor e.g. `<a href="file.php" title="Wheee"><i class="fa-solid fa-foo" aria-hidden="true"></a>` where the tooltip it on the parent and the icon declares itself invisible to screen readers.
3/ `data-toggle="tooltip"` picked up by Bootstrap to make a fancy tooltip e.g. `<i class="fa-solid fa-foo" data-toggle="tooltip" title="Whee"></i>`

Implementation across `admin` is a little inconsistent.  I'm taking the `aria-hidden` into account, and defaulting all icons created by `zen_icon()` with a tooltip to use `data-toggle` so they use Bootstrap.  This was only done in `coupon_admin.php` with its own little init call to `jQuery('[data-toggle="tooltip"]').tooltip()` which I am moving into `admin_html_head.php`.

**Comment by drbyte** [comment]
Is the "click area" the same for round as it was for square?
I'm thinking usability here. 

Personally I have no preference. It's been square for a long time, but if round looks cleaner but maintains usability, I'm okay with changing it. 

@lat9 may have insights from the Bootstrap template project.

**Comment by lat9** [comment]
> Is the "click area" the same for round as it was for square? I'm thinking usability here.
> 
The area of a circle with a 1-unit diameter is around 0.79 units, so the click-area for a circle is roughly 21% less than that for a square.  The square vs. circle screenshots posted above _appear_ to have
1. Additional white-space between the **Status**-column's icons, which takes away from rows' width real-estate as some sites have quite long category/product names.  Note, too, that there are plugins that insert additional status-icons in that column.
2. Ditto on the **Action**-column's icons.

Since those screenshots aren't exactly the same content (images aren't present in the circle-flavored one), I'm not clear on the exact layout changes.  @neekfenwick, have you viewed the circle-icons' impact on the small-device layouts in both portrait and landscape mode?

> Personally I have no preference. It's been square for a long time, but if round looks cleaner but maintains usability, I'm okay with changing it.
> 

Agreed.
> @lat9 may have insights from the Bootstrap template project.

None come to mind.

**Comment by neekfenwick** [comment]
> The area of a circle with a 1-unit diameter is around 0.79 units, so the click-area for a circle is roughly 21% less than that for a square. The square vs. circle screenshots posted above _appear_ to have
> 
> 1. Additional white-space between the **Status**-column's icons, which takes away from rows' width real-estate as some sites have quite long category/product names.  Note, too, that there are plugins that insert additional status-icons in that column.

I'm fixing this.  On review, I unwisely applied the `fa-fw` "fixed width" style, designed to monospace glyphs so they line up in a column, everywhere.  If they're all the same width anyway, like these square icons, this doesn't really make sense.  What I'm finding is that only the last icon in the columns need to be fixed width: the caret-right or circle-info icons that occupy the last spot and are different widths.  It's back to copacetic now.

> 2. Ditto on the **Action**-column's icons.

If we're talking clickable area vs wasted space (good for buttons especially on mobile) then the square `btn` Bootstrap styles make more sense.  A little foolish of me to run with the round circle icons I found in places like `manufacturers`. 
 I'm changing the action buttons (edit, delete, move etc) back to Bootstrap buttons, and that change needs applying in quite a few places where the 'edit' and 'trash' icons have been used in the round style e.g. manufacturers page.

> Since those screenshots aren't exactly the same content (images aren't present in the circle-flavored one), I'm not clear on the exact layout changes. @neekfenwick, have you viewed the circle-icons' impact on the small-device layouts in both portrait and landscape mode?

Right, the two screenshots came from two separate ZC installations I have, one a `master` development effort, and one happens to be 1.5.8a I have lying around.  I will check mobile when I get to it but they're back to square icons and let's assume Bootstrap is mobile friendly (even the 3.x we seem to be using!)
