### ISSUE TITLE
functions_products: zen_get_prid(): Argument #1 ($uprid) must be of type string, int given

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6082]
add 
declare(strict_types=1);
to the start of functions_products

Add a product to the cart
PHP Fatal error:  Uncaught TypeError: zen_get_prid(): Argument #1 ($uprid) must be of type string, int given, called in includes\functions\functions_products.php on line 550 and defined in \includes\functions\functions_products.php:458

I suggest adding the same (declare(strict_types=1);) to the shopping_cart class at the same time for related useages/as it is debateable exactly where fixes should be applied.

**Comment by drbyte** [comment]
This is a case where coercive typing is intentional, because the incoming value could at any time be a string or an integer.

Fortunately we can change the function signature to accept a hybrid in this case.
