### ISSUE TITLE
admin, manufacturers: 'NOTIFY_ADMIN_MANUFACTURERS_DEFAULT_ACTION' for database update

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6086]
https://github.com/zencart/zencart/blob/b4f4b66fa34675c7653518bf0b57807851b3053b/admin/manufacturers.php#L137-L143

If an observer was wanting to set up a new database field, this would need to be done on initial page load.
This notifier is in a switch that tests for action **existing**, but action is not set on initial page load so this notifier would not execute at this moment.
Should this be **after** the switch?

**Comment by lat9** [comment]
Nope, that's there for an observer (who has added fields to a form on that page via notifications further down) to react to a new 'action' that it's defined.

**Comment by torvista** [comment]
Ah, I misunderstood the preceeding comment.
