### ISSUE TITLE
named arguments not allowed in php 7.x

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#6095]
#6066 added new functions.  a number of calls to the functions make use of named arguments.  named arguments were introduced in php 8.

[the docs need to be updated](https://docs.zen-cart.com/user/first_steps/server_requirements/#:~:text=Zen%20Cart%20v2.0.0,required%20for%20zc_install) or else the named calls need to be refactored.

one such example:
https://github.com/zencart/zencart/blob/a28f1e082c380590a013f50bfcc06dbf26519d7c/admin/orders.php#L1394

i would weigh in on this bug... but i'll just stick with reporting it...

**Comment by drbyte** [comment]
> [the docs need to be updated](https://docs.zen-cart.com/user/first_steps/server_requirements/#:~:text=Zen%20Cart%20v2.0.0,required%20for%20zc_install) or else the named calls need to be refactored.

You are right.

As much as it would be preferred to go with 8.0+ syntax especially since 8.0 will be EOL in a month, we have to decide on whether to make it convenient for upgraders to build their update on the same server/account as an older 7.x site where they might not be able to control/switch PHP versions per-directory, or force them to demand their hosting company to give them more flexibility in order to even attempt an upgrade.

**Comment by proseLA** [comment]
a specious argument in my mind…

for the longest time, there has been this loudly articulated methodology on the board that to do an upgrade, one would create a sub-directory within their web root and do the upgrade there.

and now, you are using that flawed methodology to guide development decisions, because hosting companies may not allow php version selections on a per directory basis.

when doing an upgrade of https://mystore.com; a better solution is to create a new domain, ie https://v158.mystore.com.  this new domain’s document root can (and should) be outside of the old domain’s document root, and, IMO, has numerous advantages over the older flawed methodology.  one of which is that the multiPHP manager used by most hosting companies allows php version selection by domain.

if, as you say, going with the new syntax is preferred, go with that.

> we have to decide...

the proverbial we no doubt....

**Comment by drbyte** [comment]
> one of which is that the multiPHP manager used by most hosting companies allows php version selection by domain.

Correct. Interestingly, the MultiPHP Manager's first iterations started out offering the selection per-directory. It has matured to offer it by domain too.

> when doing an upgrade of https://mystore.com/; a better solution is to create a new domain, ie https://v158.mystore.com/. this new domain’s document root can (and should) be outside of the old domain’s document root

I totally agree.

> for the longest time, there has been this loudly articulated methodology on the board that to do an upgrade, one would create a sub-directory within their web root and do the upgrade there.

Right. "for the longest time" refers to the technical limitations that existed in hosting platforms in those ancient eras.

And those same docs also cater to the still-existing mental picture that the less-tech-savvy storeowner has in their mind of seeing things via a directory-structure ... and have zero concept of what a subdomain is.
But, as you point out, subdomains are a way simpler way of staging any new site within the same hosting account, when one is dependent on their hosting platform as the only way of testing/staging (as opposed to using a local PC).

Nevertheless, docs can be changed. New concepts can be taught.

**Comment by scottcwilson** [comment]
> when doing an upgrade of https://mystore.com; a better solution is to create a new domain, ie https://v158.mystore.com. this new domain’s document root can (and should) be outside of the old domain’s document root, and, IMO, has numerous advantages over the older flawed methodology. one of which is that the multiPHP manager used by most hosting companies allows php version selection by domain.

@proseLA This is an inspired idea.  Would you be willing to write up a page for the documentation describing how to do this so we could show people this approach?

**Comment by dbltoe** [comment]
The reasoning behind my earlier thumbs up is that I have recommended this for years and have had an article on it in our [knowledge base at myZenCartHost.com](https://myzencarthost.com/index.php?rp=/knowledgebase/1/Creating-a-Test-Site-with-cPanel.html).
If you would like me to tailor it to the docs (i.e., a little more generic), I will take a look.

**Comment by scottcwilson** [comment]
Sections D and E look like what I was hoping for.  Maybe I'll get you to add a screenshot or two if you have time.

**Comment by dbltoe** [comment]
I note that D and E don't accurately reflect the steps of the current cPanel Domains section.
I'll fix the article and let you know.

**Comment by scottcwilson** [comment]
TY!

**Comment by dbltoe** [comment]
See what you think.  Note that this is based on version 110.0.17 of cPanel, with version 114 released in August.  Our knowledgebase is, of course, based on our current software versions.  We will probably need a disclaimer that this is using a particular cPanel version, and theirs may look different.
We are currently staying with this version as it allows us to maintain older PHP versions for upgrade help for those still in 5.6 land.

**Comment by scottcwilson** [comment]
OK - https://docs.zen-cart.com/user/upgrading/multiple_php_versions/
