### ISSUE TITLE
attribute radio buttons class names incorrect?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6096]
https://github.com/zencart/zencart/blob/a28f1e082c380590a013f50bfcc06dbf26519d7c/includes/modules/attributes.php#L300-L307

It appears these and the subsequent clauses are missing an underscore/should not have a space, to make the class name reflect the clause:

![2023-12-24 13_02_43-zencart_includes_modules_attributes php at master · zencart_zencart](https://github.com/zencart/zencart/assets/4391026/f6b55e0a-4906-4b6c-a516-c59d531a3a4d)

**Comment by drbyte** [comment]
Interesting discovery.
Digging further, I see that it's been that way since at least v1.5.0.
And there's no CSS rule defined for it in any core CSS files.
<img width="967" alt="Screen Shot 2023-12-24 at 1 01 09 PM" src="https://github.com/zencart/zencart/assets/404472/3f925a48-caf5-4f1c-a2c7-73621fdbb89e">

**Comment by drbyte** [comment]
That said, I'm not sure it needs changing, since one can simply combine the two classes into one selector in a CSS file in order to target the combination. 
ie:
```css
.attribsRadioButton.one {
    font-weight: bold;
}
```

**Comment by lat9** [comment]
> Seems incorrect to have simple classes like "one" etc. that have no obvious relation to anything/no hint of function or use.

**_Seems_**, IMO, is the operative word!  If this was _newly-minted_ code, I would request that the class-name be more descriptive.  Since those classes have been in-core for 12+ years, some site-specific CSS might be using those classes (as @drbyte) described above and I'll suggest keeping them.

**Comment by scottcwilson** [comment]
Closing; no change required.
