### ISSUE TITLE
210804: Update of session variables from editing account/primary address book details

### ISSUE THREAD

**Issue by zcwilt** [zencart/zencart#61]
Original discussion here
http://www.zen-cart.com/showthread.php?210804-Update-of-session-variables-from-editing-account-primary-address-book-details

**Comment by drbyte** [comment]
methinks this would be best resolved via #1021 

... but in the interim some procedural updates could be done to current code, to bring parity to the availability of those vars

**Comment by drbyte** [comment]
Actually, appears to be completed already in v160 core.
