### ISSUE TITLE
currency_cron:  Call to undefined function zen_page_key_exists() in admin/includes/functions/extra_functions/whatever.php

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6102]
Some plugins use a function file in /extra-functions to check their installation...using zen_page_key_exists().
This function is in functions/admin_access...so this must be loaded before anything from /extra_functions.
A normal admin page **does** load as necessary, so no problem.

Since yesterday the files that I use from cron jobs have triggered this error.

currency_cron.core.php does not include admin_access so it's understandable that this error occurs.

What I **don't** understand is why this has started now, there is no php or other environment change that I am aware of.

**Comment by brittainmark** [comment]
Probably not related. I had an issue when running a cron job that `$_SERVER['SCRIPT_NAME']` was not defined, this caused application_top.php to fail. 
This only started happening when I moved to php8.2.
I simply added
```
if (isset($_SERVER['SCRIPT_NAME'])===false) {
    $_SERVER['SCRIPT_NAME'] = basename( __FILE__);
}
```
To the top of the file being called by the cron job.

**Comment by drbyte** [comment]
Like you say, if it's a brand new situation, and nothing in the rest of the code base or server config has been changed, it's kinda hard to code against it.

**Comment by torvista** [comment]
The reason why this has not created an error log previously is of side interest, the point being that at present, the function zen_page_key_exists() in admin_access is not available to currency_cron.

**Comment by drbyte** [comment]
> The reason why this has not created an error log previously is of side interest

I'm not sure I agree with that statement, but whatever. 

We can make it load that function file as well. You'll have to manually fix all your other cron scripts similarly.
