### ISSUE TITLE
Admin: Duplicated CSS

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6118]
https://github.com/zencart/zencart/blob/65ad63eaf2bbb4595cb1a5bc702a965ee90f4bfe/admin/includes/css/menu.css#L54-L63

https://github.com/zencart/zencart/blob/65ad63eaf2bbb4595cb1a5bc702a965ee90f4bfe/admin/includes/css/stylesheet.css#L827-L836

**Comment by drbyte** [comment]
I guess technically the 2 statements belong in separate files.
I suppose we could leave `.navbar` in the `menu.css` file, 
and only leave `.btn-help` in `stylesheet.css`.

But then it's significantly less obvious that the `margin-bottom` is the same in both.
