### ISSUE TITLE
problem with zen_draw_checkbox_field

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#6146]
one is allowed the reuse of the `name` attribute in html.  `id` no.

i have discovered a problem when sending multiple instances of something like this:

```
zen_draw_checkbox_field('myName', '', false, '', 'id="myName[' . $lineItem['orders_products_id'] . ']"')
```
i have tracked it down to this line here, which i am not sure why it is here:

https://github.com/zencart/zencart/blob/70ec8903b49c04ba24d7cb8accead18062d90a17/admin/includes/functions/html_output.php#L432

this problem is easily reproducible by executing the following code:

```
    echo zen_draw_checkbox_field('myName', '', false, '', 'id="myName1"');
    $myName = '';
    echo zen_draw_checkbox_field('myName', '', false, '', 'id="myName2"');
```
the 2nd checkbox is now checked, despite sending false for checked. 

i believe this can be fixed by changing that line to:

```
|| (!empty($value) && !empty($GLOBALS[$name]) && is_string($GLOBALS[$name]) && (stripslashes($GLOBALS[$name]) == $value))
```
note i am using the admin function, but the problem would exist on the storefront as well.  

i am not getting into the difference in the parameter signature in this issue.

**Comment by lat9** [comment]
Unfortunately, the use of the loose comparison (`!empty()`) causes this example to result in the first radio-button not being selected (as it is currently):
```php
$myRadio = '0';
echo zen_draw_radio_field('myRadio', '0');
echo zen_draw_radio_field('myRadio', '1');
echo zen_draw_radio_field('myRadio', '2');
``` 

Before continuing, what is the problem you're trying to solve (i.e. the form's function) wherein there are multiple checkbox elements of the same name in that form?

**Comment by proseLA** [comment]
> Before continuing, what is the problem you're trying to solve (i.e. the form's function) wherein there are multiple checkbox elements of the same name in that form?

is this the direction of the conversation here?  

i have provided an example where a zen function demonstrates non-expected behavior, ie draw a checkbox without the box being checked, and yet it comes back as checked.

if you are comfortable with that behavior and do not feel that is a bug, then feel free to close this issue.

**Comment by lat9** [comment]
I'll note that a slight modification to the supplied code results in the 'expected' behavior:
```php
    echo zen_draw_checkbox_field('myName', 'on', false, '', 'id="myName1"');
    $myName = '';
    echo zen_draw_checkbox_field('myName', 'on', false, '', 'id="myName2"');
```

While the behavior might have been unexpected, I don't consider it a bug.

**Comment by proseLA** [comment]
> While the behavior might have been unexpected, I don't consider it a bug

a discussion of semantics, now?  while not the definitive statement on computer bugs, i would argue that [this wikipedia entry](https://en.wikipedia.org/wiki/Software_bug#:~:text=A%20software%20bug%20is%20an%20error%2C%20flaw%20or%20fault%20in%20the%20design%2C%20development%2C%20or%20operation%20of%20computer%20software%20that%20causes%20it%20to%20produce%20an%20incorrect%20or%20unexpected%20result%2C%20or%20to%20behave%20in%20unintended%20ways.) states that unexpected behavior is a bug.

your solution is what i would call a hack.  and i have no problem using said solution.   so thank you for that.
