### ISSUE TITLE
admin, customers: PHP Warning: Undefined variable $cInfo after search of non-existent email

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6150]
php 8.3

admin, customer, search for an email that does not exist:

[22-Jan-2024 22:38:56 UTC] Request URI: /zencart/admin/index.php?cmd=customers&search=mrblobby@hotmail.com, IP address: 127.0.0.1, Language id 1
#0 D:\GitHub\zencart\admin\customers.php(1918): zen_debug_error_handler()
#1 D:\GitHub\zencart\admin\index.php(11): require('D:\\GitHub\\zenca...')
--> PHP Warning: Undefined variable $cInfo in D:\GitHub\zencart\admin\customers.php on line 1918.

**Comment by drbyte** [comment]
Does this fix it? 
`customers.php`, line 1918:
```diff
-$customer = new Customer($cInfo->customers_id);
+$customer = new Customer($cInfo ? $cInfo->customers_id: null);
```

**Comment by proseLA** [comment]
> Does this fix it? `customers.php`, line 1918:
> 
> ```diff
> -$customer = new Customer($cInfo->customers_id);
> +$customer = new Customer($cInfo ? $cInfo->customers_id: null);
> ```

if my testing, this fix does not work.  

in addition, this error occurs when any search returns an empty set.  

in my testing, moving line 1918 to after the conditional on 1923 resolves the issue.

https://github.com/zencart/zencart/blob/37192e8f3bc1c9093bcdd98969551a5d07624d9a/admin/customers.php#L1918-L1924

**Comment by torvista** [comment]
>in my testing, moving line 1918 to after the conditional on 1923 resolves the issue.  

Seems to be appropriate.

**Comment by drbyte** [comment]
>>Does this fix it? customers.php, line 1918:

>if my testing, this fix does not work.

You're right. 

> in my testing, moving line 1918 to after the conditional on 1923 resolves the issue.

Agreed.
