### ISSUE TITLE
Responsive Classic: misalignment of label for Sort dropdown on larger viewports

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6170]
![image](https://github.com/zencart/zencart/assets/4391026/1152763c-4f8f-4d3b-80bf-dd8b37886ded)

**Comment by torvista** [comment]
Windows 11: it appears to be only in Firefox (Chrome/Edge are as expected).

208px

![208x805](https://github.com/zencart/zencart/assets/4391026/420e179b-9e15-44ca-9b38-e901d7700791)

476px

![476x805](https://github.com/zencart/zencart/assets/4391026/c42ca618-00c4-423f-9a45-cb75aa0661ef)

792px

![792x805](https://github.com/zencart/zencart/assets/4391026/031180d4-bf91-4ecd-b8c9-4def67a4e3a7)

872px

![872x805](https://github.com/zencart/zencart/assets/4391026/22c27cff-e564-4a0f-a856-50c1e4152206)

**Comment by drbyte** [comment]
Interesting that it's only FF on Windows

872px Firefox on MacOS:
<img width="887" alt="Screen Shot 2024-01-29 at 11 43 21 AM" src="https://github.com/zencart/zencart/assets/404472/4f8e2f6e-84f2-480d-a00d-c81588032916">

**Comment by torvista** [comment]
So this should be a bug-report for Firefox.

**Comment by torvista** [comment]
Initial testing was on a laptop
872px on a desktop pc
![image](https://github.com/zencart/zencart/assets/4391026/ead74369-357d-4730-a994-bc780f318292)

872px on another laptop
![2024-01-30 11_38_05-Big Unlinked _ Zen Cart!, The Art of E-commerce — Mozilla Firefox](https://github.com/zencart/zencart/assets/4391026/a4743ccb-e895-4341-a691-f71c5ab7e515)

Bah.

**Comment by torvista** [comment]
I put a site online to allow all pc's at my disposal to check and all were the same/ok.
So, mystery.
