### ISSUE TITLE
label spacing by filters/sorter

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6174]
![2024-01-29 18_03_55-Big Linked _ Zen Cart!, The Art of E-commerce](https://github.com/zencart/zencart/assets/4391026/9e397d63-7b6f-47d2-8f7f-e0e709eada3d)

https://github.com/zencart/zencart/blob/f24e7d5273385ce752be207168fe7b76dc54fe65/includes/languages/english/lang.index.php#L10
https://github.com/zencart/zencart/blob/f24e7d5273385ce752be207168fe7b76dc54fe65/includes/languages/lang.english.php#L430

**Comment by drbyte** [comment]
Right. The trailing space isn't needed. 
Plus it's probably best to avoid adding trailing spaces in language strings. Translators probably will forget to keep them.
