### ISSUE TITLE
Admin order's details | Replace individual product weight with row based total weight

### ISSUE THREAD

**Issue by asiksami** [zencart/zencart#6180]
Could admin order's `product` rows `weight` column be calculated as row based total weight?

When one is processing the order and quickly checks the weight from the row, it might wrongly just use the weight of a one item and not add it with the quantity. This might also be problematic when quantity of a product is lower than 1 (eg. 0.7), and especially on heavy item, weight is too high.

**Comment by scottcwilson** [comment]
Or maybe stack individual weight, line break, total weight?

**Comment by barco57** [comment]
unit/total on line items. Line break in line items is not a good idea.

**Comment by scottcwilson** [comment]
We have line breaks between attributes and the product name already.

**Comment by lat9** [comment]
> unit/total on line items. Line break in line items is not a good idea.

Agreed

> We have line breaks between attributes and the product name already.

All products have weight; not all products have attributes

**Comment by lat9** [comment]
Noting, too, that I'd previously missed any weight(s) that ordered-products' attributes add (sigh).

**Comment by lat9** [comment]
So, here's what the final (to be pushed RSN) display looks like:
![image](https://github.com/zencart/zencart/assets/2685585/92cebe60-4a80-4c46-a980-a5823f06b2d6)

Noting that for non-integer quantities to be 'accepted' in a store, `Configuration :: Stock :: Product Quantity Decimals` must be set to a value other than 0!

**Comment by asiksami** [comment]
Thank you @lat9. I would leave those attribute weights out of display and only on the totals. But this is only my opinion. :)
