### ISSUE TITLE
Missing variable $_GET['gv_no'] causes log

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#6183]
Could be malicious.

[30-Jan-2024 04:34:49 UTC] Request URI: /index.php?main_page=gv_redeem, IP address: .
#0 /home/client/public_html/store/includes/modules/pages/gv_redeem/header_php.php(13): zen_debug_error_handler()
#1 /home/client/public_html/store/index.php(35): require('/home/client/p...')
--> PHP Warning: Undefined array key "gv_no" in /home/client/public_html/store/includes/modules/pages/gv_redeem/header_php.php on line 13.

**Comment by zcwilt** [comment]
While not necessarily malicious (e.g. scanning software might hit this) still think is should be addressed.

I'll take a look.
