### ISSUE TITLE
Admin, orders, order details, 'NOTIFY_ADMIN_ORDERS_ADDRESS_FOOTERS' modification

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6213]
https://github.com/zencart/zencart/blob/f8695674ca2c67f99d9766264ebc77efa2241213/admin/orders.php#L591-L596

Anything added via the notifier is placed in one td:

![image](https://github.com/zencart/zencart/assets/4391026/0cc57e1e-cc3e-45bf-8fa7-e4fcb18c245c)

To add another item such as a tax-id or second telephone etc, you can't add a label neatly as it's all in one table cell.

Could be changed to 
`<tr><?php echo $address_footer_suffix; ?></tr>`
to be more flexible, and also get rid of the extra line above the telephone.

PR?

**Comment by proseLA** [comment]
> To add another item such as a tax-id or second telephone etc, you can't add a label neatly as it's all in one table cell.
> 
> Could be changed to `<tr><?php echo $address_footer_suffix; ?></tr>` to be more flexible, and also get rid of the extra line above the telephone.
> 
i am not really sure how that is more flexible.  are you saying that within the `$address_footer_suffix` var, you will add the `<td>` tags?  and then you can enter your own additional `<tr>` tags?  if that is your idea, i am not a fan.  i like storing data in vars; separate from any html tags.

if you want to add additional rows, i think the `$address_footer_suffix` should be array;  and then one can loop through the array; potentially using the array key for the bold data in column one.

**Comment by torvista** [comment]
> if you want to add additional rows, i think the $address_footer_suffix should be array; and then one can loop through the array; potentially using the array key for the bold data in column one.

Ha. ha...that's exactly what I had done previously, $key/label in column 1 and $value in column 2.

**Comment by torvista** [comment]
https://github.com/zencart/zencart/pull/6329
