### ISSUE TITLE
Configuration :: Images, some settings not used?

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#6223]
Within the new/featured products' images' settings:

![image](https://github.com/zencart/zencart/assets/2685585/2eacfcbf-6325-49f6-9688-c526728e079d)

... I've found a couple of anomalies:
1. The "New Products Listing" width/height is used only in `tpl_modules_products_new_listing.php`, the new listings' centerbox.
2. The "New Products" width/height is used ... **_nowhere_**!
3. The "Featured Products" width/height is used by `/modules/featured_products.php` and `tpl_modules_products_featured_listing.php`, both the sidebox and centerbox.

I guess my question is where are these image heights "supposed" to be used (especially the "New Products" one)?

**Comment by scottcwilson** [comment]
@drbyte In light of the SNAF rework, should these settings be deprecated too? 

```
IMAGE_PRODUCT_NEW_LISTING_WIDTH
IMAGE_PRODUCT_NEW_LISTING_HEIGHT
IMAGE_PRODUCT_NEW_WIDTH
IMAGE_PRODUCT_NEW_HEIGHT
IMAGE_FEATURED_PRODUCTS_LISTING_WIDTH
IMAGE_FEATURED_PRODUCTS_LISTING_HEIGHT
```

**Comment by lat9** [comment]
Those settings (other than the one that's not used) affect the image sizes in sideboxes and centerboxes *only* and have no bearing on the SNAF pages.

**Comment by drbyte** [comment]
IMAGE_FEATURED_PRODUCTS_LISTING_HEIGHT and width were added in v1.2.0
IMAGE_PRODUCT_NEW_LISTING_HEIGHT and width were added in v1.1.1

Their functionality remains the same today as it was back then.

IMAGE_PRODUCT_NEW_HEIGHT and width were added in v1.1.1, and was part of `/modules/new_products.php` in which `IMAGE_PRODUCT_NEW_HEIGHT` appears to have been removed in v1.5.8 via PR #5026 where `SMALL_IMAGE_WIDTH, SMALL_IMAGE_HEIGHT` replaced `IMAGE_PRODUCT_NEW_WIDTH, IMAGE_PRODUCT_NEW_HEIGHT`

**Comment by lat9** [comment]
Thanks for the back-tracking, @drbyte; it appears that I've "done it to myself" again.  I'll get a teeny PR together to correct that image-size usage.

**Comment by torvista** [comment]
Related...https://github.com/zencart/zencart/discussions/5846
