### ISSUE TITLE
Admin, server_info, database variables of value 0 not shown

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6228]
Some variables may have a 0 value, meaning unlimited. These are not shown due to this:
https://github.com/zencart/zencart/blob/78a6e22c75a8e9355e116c14136fba1b8f063bd0/admin/server_info.php#L119

**Comment by torvista** [comment]
Why not show the 0 as that is the actual value?

**Comment by lat9** [comment]
Because, depending on the setting, it's either interpreted as '0' or an empty string.

**Comment by torvista** [comment]
For example in this case, it looks like it's stored as 0, not as nothing.
phpMyadmin
![image](https://github.com/zencart/zencart/assets/4391026/dd4c05e4-93bb-48be-9bb0-0a31d129fa7d)

mariadb
![image](https://github.com/zencart/zencart/assets/4391026/2508b459-26bf-47c2-b6d5-b80abdcad3d7)

**Comment by lat9** [comment]
Yes, but that's one of many.

**Comment by lat9** [comment]
I stand (in the corner) corrected, since that output is using `empty` to determine whether/not to output a variable's value.

**Comment by torvista** [comment]
Why bother checking at all? I took it out and there were no not-set values to cause an error.

**Comment by scottcwilson** [comment]
Repro: go to Admin > Version and click the link "View the database configuration variables".  Zero valued settings will appear blank. 

<img width="400" alt="var" src="https://github.com/zencart/zencart/assets/4391638/0d5eb695-9c19-425b-abea-73b1a9b64347">
