### ISSUE TITLE
proper messaging in upgrade

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#6234]
i was recently testing upgrading a database.  the server was running:

PHP Version: 8.0.25 (Zend: 4.0.25)

unfortunately the code below prevented said upgrade from happening:

https://github.com/zencart/zencart/blob/4e7063f728384bfbe6b3fc8929b35eef2e6be82e/zc_install/index.php#L9-L11

i changed the test to compare to 80000 and the upgrade completed without incident.

whether that will happen in all circumstances, i can not say.  but can we at least properly message what the test is?

**Comment by lat9** [comment]
Right, there was some base issue introduced in PHP 'point' releases for PHP 8/8.1/8.2 that required that minimum version.   Something to do with this PHP issue?

https://github.com/php/php-src/issues/12561#issuecomment-1786428271

Granted, the messaging should be changed.

**Comment by proseLA** [comment]
a php source issue?  that is throwing errors **SINCE** 8.1.25?  i do not think that is the base issue in this case...  i could be wrong.

i think the base issue was potentially introduced here #6095.  but that is for running zc; not per se upgrading the database via the zc_install directory.

whether we want to enforce the php8 or greater for the database upgrade is up to the repo maintainers...  i could see arguments either way; but whatever gets decided, lets have proper messaging that accurately reflects what the conditional is.

**Comment by scottcwilson** [comment]
PHP 8.0.30 (PHP_VERSION_ID 80030 ) was the final version of PHP 8.0.  This change was part of 050e9259b6cc1db17d3468f71d93069753e2356c and it was probably chosen because by the date of commit, 8.0 was already end of life.    We could certainly lower the VERSION_ID specified to support yet older versions of PHP, or we could update the message to say "Use 8.0.30 or more recent."  

It probably shouldn't be 80000 since there were likely bugs in that earliest version - perhaps 80014, which was the first PHP 8.0 release after the first PHP 8.1 release?

**Comment by proseLA** [comment]
i am not a fan of getting caught up in monitoring for EOL or bugs in PHP versions.  in fact, i do think we should get caught up in patch versions of php.  pick a major and a minor version and be done with it.  and provide error messages that accurately state what you are checking.  it is also inaccurate in the admin:

https://github.com/zencart/zencart/blob/4e7063f728384bfbe6b3fc8929b35eef2e6be82e/admin/includes/application_top.php#L9-L11

on the storefront, we send users to the docs page.

https://github.com/zencart/zencart/blob/4e7063f728384bfbe6b3fc8929b35eef2e6be82e/includes/application_top.php#L85-L87

[on the docs page](https://docs.zen-cart.com/user/first_steps/server_requirements/#:~:text=zen%20cart%20v1.5.3%20is%20compatible%20with%20php%205.3.7%20through%20php%205.6), you have to go back to zc v1.5.3 to see a reference to a patch version of php; and that version, 5.3.7, is non-existent.  see the [php version release page.](https://www.php.net/releases/index.php#:~:text=5.4.0%20(tar.gz)-,5.3.29,-Released%3A%2014%20Aug)

**Comment by drbyte** [comment]
`80030` was a typo. That's the actual bug here. It should have been `80003`, to check against PHP 8.0.2 minimum, which exists because the included Laravel integration requires minimum 8.0.2.
