### ISSUE TITLE
Lazy Load Product Listing Images

### ISSUE THREAD

**Issue by simon1066** [zencart/zencart#6246]
`loading="lazy"` is currently (only) used for the listing of category images: 

https://github.com/zencart/zencart/blob/444b7e45ae8acc84bfbbf12cb391b368c601b7b7/includes/modules/category_row.php#L44

I think it would be beneficial to add it to the product listing page in `\includes\modules\product_listing.php`. As that file is overriden in responsive_classic then I presume an edit to `\includes\modules\responsive_classic\product_listing.php` is also needed.

I can submit a PR if need be (probably not until tomorrow).

**Comment by drbyte** [comment]
I've added `loading="lazy"` to PR #6192
