### ISSUE TITLE
Enhancement: Featured Categories

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#6247]
And, looking at the above, I also found something many of my customers could use.  We already have Featured Products, but what about adding [Featured Categories](https://www.semrush.com/blog/seo-ecommerce-category-pages/)?

_Originally posted by @dbltoe in https://github.com/zencart/zencart/discussions/5992#discussioncomment-8180925_

**Comment by scottcwilson** [comment]
Interesting idea.  Centerbox and page for this?

**Comment by lat9** [comment]
Wouldn't this (not small) change go against the guidance just posted on the Zen Cart forums: https://www.zen-cart.com/showthread.php?229962-Feedback-on-2-0-0-beta1

**Comment by drbyte** [comment]
> Wouldn't this (not small) change go against the guidance just posted on the Zen Cart forums: https://www.zen-cart.com/showthread.php?229962-Feedback-on-2-0-0-beta1

If one tried to get it into v2.0.0 release, yes. But there's no version target in this discussion yet.

**Comment by scottcwilson** [comment]
Could be a "next release after 2.0.0" feature.  We need to start building our backlog! :)

**Comment by scottcwilson** [comment]
@drbyte If you are agreeable, please label this 2.1.x.  Thanks!

**Comment by drbyte** [comment]
I'm agreeable to 2.1, but not sure who will code this feature or when that will happen, so untagging it for now.

**Comment by TMCSherpa** [comment]
I have a local copy that 'works' but some idiot nuked the SQL file.
You can add categories, delete them and display them (yay) but the breadcrumbs aren't working properly (parent ID I think) and I know there should be a hook so that deleting categories removes them from featured.
I'll get the SQL file rebuilt so someone can play with it

**Comment by scottcwilson** [comment]
John, you should be able to rebuild the SQL file by looking at your current database schema and comparing it to the default schema.  Thanks for sharing your work.

**Comment by TMCSherpa** [comment]
I made a branch but I don't think it's ready for a pull yet. I need to work on hiding the sidebox for mobile and a couple other things first.
