### ISSUE TITLE
paypaldp.php creates debug logs in PHP8

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#6250]
```
[23-Feb-2024 19:33:36 America/Indiana/Indianapolis] Request URI: /index.php?main_page=checkout_one_confirmation, IP address: 71.14.175.124, Language id 1
#0 /home/client/public_html/includes/modules/payment/paypaldp.php(708): zen_debug_error_handler()
#1 /home/client/public_html/includes/classes/payment.php(279): paypaldp->process_button()
#2 /home/client/public_html/includes/modules/pages/checkout_one_confirmation/header_php.php(407): payment->process_button()
#3 /home/client/public_html/index.php(35): require('/home/client/p...')
--> PHP Warning: Undefined array key "paypalwpp_cc_type" in /home/client/public_html/includes/modules/payment/paypaldp.php on line 708.
```

Plus same for other `cc_` fields.  
These fields are no longer in `$order->info` (see commented out block in `includes/classes/order.php` line 549-553.)
I wonder if they should be uncommented out to prevent this warning.

**Comment by drbyte** [comment]
I don't think it's related to those lines of the order class.

If the $_POST value for those fields is not present in `->process_button()`, then the payment-fields weren't POSTed after being presented to the shopper and their clicking to proceed.

Does the same occur with normal checkout, instead of OPC?

**Comment by scottcwilson** [comment]
That's a good question, but I don't know.  I could ask the client if I could turn off OPC for a few days and monitor.  

I did see other paypaldp.php issues on standard checkout, which I reported here:
https://www.zen-cart.com/showthread.php?229844-paypaldp-and-PHP-8-1

**Comment by scottcwilson** [comment]
OK I have turned off OPC.  They are running 1.5.8a on PHP 8.1.   Let's see if the logs still happen under standard checkout.

**Comment by scottcwilson** [comment]
Of course, no paypaldp.php activity in the last day. :(

**Comment by scottcwilson** [comment]
Confirmed - these logs *do* occur even in standard checkout.
