### ISSUE TITLE
Template Settings helper function is not being loaded 2.0.0-beta1

### ISSUE THREAD

**Issue by kanine** [zencart/zencart#6259]
**Describe the bug**
The helper function tpl() is not available for use within a template.

**Version**
Zen Cart version: 2.0.0-beta1
PHP version: 8.3.3
MySQL version: 10.4.32-MariaDB
Plugins that may be related: None
What older/newer versions were also tested? N/A

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Go to any includes\templates\yourtemplate\template_settings.php
2. Add a new setting
3. Try to use setting in any template eg includes\templates\bootstrap5\common\html_header.php
4. Errors out with tpl() is undefined

**Expected behavior**
The required setting should be accessible from the tpl() helper function

**Additional context**
Looks like the following line needs to be added to includes\init_includes\init_templates.php

`require DIR_FS_CATALOG . DIR_WS_FUNCTIONS . 'functions_templates.php';`

This has been done in the admin area, but not in the main catalog site. Which I think is unintended as the notes in the template_settings.php file indicate this function isn't available in admin.

**Comment by scottcwilson** [comment]
Thanks for testing, @kanine!

**Comment by drbyte** [comment]
You are correct. Thanks for testing the beta1 !

Looking at relocating them to `functions_general_shared.php` for the next build: https://github.com/zencart/zencart/pull/6260

**Comment by kanine** [comment]
All good, I'm reconstructing our entire deployment over the coming weeks so I'll continue to log any bugs I think I've found. I know I'll need to rework some of it again due to the beta but it gives an opportunity to clean my own house in preparation for the 2.0.0 launch.
