### ISSUE TITLE
Path to log file locations defined by DIR_FS_LOGS contained 2  slashes //

### ISSUE THREAD

**Issue by OldNGreyBMR** [zencart/zencart#6277]
**Describe the bug**
When DIR_FS_LOGS is defined in configure.php file the resulting path to error logs contains 2 slashes  eg E:/web/zc158a_vanilla_vanilla/zc158logs//myDEBUG-adm-20240301-221653-549845.log.
Some log files are written to the destination defined by DIR_FS_LOGS, some are not.
The define DIR_FS_LOGS line in the configure.php file requires a forward slash at the end of the path. Some plugins append a slash to the defined path when creating log files (or prepend a slash to the log file name)

**Version**
Zen Cart version: 1.5.8; 1.5.8a 
PHP version:  8.0+
MySQL version: any
Plugins that may be related: 
zca_bootstrap
clone template
edit orders
imagehandler

What older/newer versions were also tested? :1.5.7

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Go to admin/includes/configure.php ensure DIR_FS_LOGS is not set
2.  Open admin and display version
3.  error log setting in core block displays "E:/Web/zc158a_vanilla-vanilla/logs/myDEBUG-adm-20240301-210401-536025.log "
4. Go to admin/includes/configure.php and set DIR_FS_LOGS another folder eg "define('DIR_FS_LOGS','E:/web/zc158a_vanilla_vanilla/zc158logs/');'
5. Open admin and display version
6. error log setting in core block displays "E:/web/zc158a_vanilla_vanilla/zc158logs//myDEBUG-adm-20240301-221653-549845.log "

**Expected behavior**
The log files should be located in the folder defined by DIR_FS_LOGS

**Screenshots**

**Debug/Error Logs**
None
 
**Devices (please complete the following information):**
 - Operating System: Windows, Linux
 - Browser: all

**Additional context**

**Comment by drbyte** [comment]
To clarify: nothing's actually broken here, right? Just a display-anomaly?

Or is Windows doing something new with double-slashes that it's never done before?

**Comment by OldNGreyBMR** [comment]
This is a minor inconvenience that can be addressed going forward. 
I don't think it is just a display problem. Under Admin > Version the text display is the same on Windows and Linux. 

If DIR_FS_LOGS is not defined in configure.php, logs will go to the logs folders in the root of the store.
    [ /includes/defined_paths.php line 29 
    if (!defined('DIR_FS_LOGS')) define('DIR_FS_LOGS', DIR_FS_CATALOG . 'logs'); // trailing slash omitted ]
    
If DIR_FS_LOGS is defined to point somewhere else, when file names and extra paths are concatenated with a slash 
    [/admin/includes/init_includes/init_zca_bootstrap_template_admin.php line124
    $logfile_name = DIR_FS_LOGS . '/zca_bootstrap_' . date('YmdHis') . '.log';  ]
they have two slashes in the path name unless some sanitizer is run on them.

I  tried to move my log files out of the store area because a lot of bots have been searching for variation on log file folders.

**Comment by OldNGreyBMR** [comment]
I'll try leaving the trailing  "/" off the DIR_FS_LOGS definition in configure.php as se if anything breaks.

**Comment by OldNGreyBMR** [comment]
There is a samples entry in the documentation [https://docs.zen-cart.com/user/miscellaneous/configure/](url) that show no trailing space on the DIR_FS_LOGS definitiuon.
