### ISSUE TITLE
Setup Wizard form displays an empty drop down field for store zone

### ISSUE THREAD

**Issue by piloujp** [zencart/zencart#6282]
**Describe the bug**
After ZC install and at first login to admin, setup wizard shows a form with empty drop down field for store zone when selecting a country with no zone.
![FormWemptyField](https://github.com/zencart/zencart/assets/117885587/7fab00df-13d7-441f-afbc-1c7af6dd1d9a)

**Version**
Zen Cart version: Last Github version (2.0.0-beta1) and probably older ones
PHP version: 8.3.3 and probably others
MySQL version: 8.2.0
Plugins that may be related: None

**To Reproduce**
Choose a country with no zone in setup wizard form.

**Expected behavior**
An input text field or no field at all.
This behavior is controlled by JavaScript and I don't think it is possible to replace the dropdown field created with PHP/HTML by a text input field using only JavaScript.
But this field can be hidden when empty using this code on line 103:
```
		  // hide the field and its label if no zone
		  if (theForm.zone_id.options.length == 0)
		      $("#zone_id, label[for=zone_id]").hide();
		  else
                      $("#zone_id, label[for=zone_id]").show();
```
![FormWhiddenField](https://github.com/zencart/zencart/assets/117885587/9ccc6bc1-0841-48d5-aa6e-41d967b0243e)

**Devices (please complete the following information):**
 - Operating System: Windows 11
 - Browser: Firefox 123.0

**Comment by scottcwilson** [comment]
This means Taiwan has no zones in your database.
The default install has no zones for Taiwan: see `zc_install/sql/install/mysql_utf8.sql`.

You could try this plugin but please verify before using:
https://www.zen-cart.com/downloads.php?do=file&id=530

**Comment by piloujp** [comment]
> This means Taiwan has no zones in your database. The default install has no zones for Taiwan: see `zc_install/sql/install/mysql_utf8.sql`.
> 
> You could try this plugin but please verify before using: https://www.zen-cart.com/downloads.php?do=file&id=530

I don't need Taiwan zones... It is just an example. Problem is that displaying this empty dropdown field is weird and could be confusing. One might think it has to be filled to continue the install process...
Or simple logic,: You can't do anything with an empty dropdown field, why displaying it?
