### ISSUE TITLE
Possible v2 SQL upgrade error 

### ISSUE THREAD

**Issue by asiksami** [zencart/zencart#6292]
When running line 108 from `mysql_upgrade_zencart_200.sql` to MariaDB (10.3.39) in PHPMyadmin:

`INSERT INTO zones (zone_country_id, zone_code, zone_name) SELECT (SELECT countries_id FROM countries WHERE countries_iso_code_3 = 'ITA'), 'SU', 'Sud Sardegna' WHERE NOT EXISTS (SELECT * FROM zones WHERE zone_country_id = (SELECT countries_id FROM countries WHERE countries_iso_code_3 = 'ITA') AND zone_code = 'SU');`

Gives you sql error 1064: 
`#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE NOT EXISTS (SELECT * FROM zones WHERE zone_country_id = (SELECT countri...' at line 1`

**Version**
Zen Cart version: v2.0.0-beta1
Web server: Apache/2.4.38 (Raspbian)
PHP version: 8.3.3-1+0\~20240216.17+debian10\~1.gbp87e37b
MySQL version: 10.3.39-MariaDB-0+deb10u2 - Raspbian 10

**Comment by drbyte** [comment]
Hmmm...
It's valid SQL.
I have no problem running that statement on MariaDB 11.2.2.  I don't have a MariaDB 10.3 to test it on.

If you run it via `zc_install` (by upgrading a ZC 1.5.8 or older db) does the same error occur? If not, then perhaps something's going strange with your pasting it into phpMyAdmin.

**Comment by asiksami** [comment]
I tried with the latest v2-beta1 `zc_install` over v.1.5.8 and it gives me the same error. Just to be sure that this error doesn't have anything to do with 3rd party software, I runned this mysql code in console with same results.

Here's the content from `zcInstallLog`. First 5 exceptions are ok, those columns appeared successfully.
```
---------------
Mar 07 2024 12:05 -- systemChecker::findCurrentDbVersion
1.5.8

---------------
Mar 07 2024 12:05 -- upgradeException
ALTER TABLE products MODIFY products_length DECIMAL(8,4) DEFAULT NULL;  1054: Unknown column 'products_length' in 'products'  

---------------
Mar 07 2024 12:05 -- upgradeException
ALTER TABLE products MODIFY products_width DECIMAL(8,4) DEFAULT NULL;  1054: Unknown column 'products_width' in 'products'  

---------------
Mar 07 2024 12:05 -- upgradeException
ALTER TABLE products MODIFY products_height DECIMAL(8,4) DEFAULT NULL;  1054: Unknown column 'products_height' in 'products'  

---------------
Mar 07 2024 12:05 -- upgradeException
ALTER TABLE products CHANGE products_ready_to_ship product_ships_in_own_box TINYINT DEFAULT NULL;  1054: Unknown column 'products_ready_to_ship' in 'products'  

---------------
Mar 07 2024 12:05 -- upgradeException
ALTER TABLE products MODIFY product_ships_in_own_box TINYINT DEFAULT NULL;  1054: Unknown column 'product_ships_in_own_box' in 'products'  

---------------
Mar 07 2024 12:05 -- upgradeException
INSERT INTO zones (zone_country_id, zone_code, zone_name) SELECT (SELECT countries_id FROM countries WHERE countries_iso_code_3 = 'ITA'), 'SU', 'Sud Sardegna' WHERE NOT EXISTS (SELECT * FROM zones WHERE zone_country_id = (SELECT countries_id FROM countries WHERE countries_iso_code_3 = 'ITA') AND zone_code = 'SU');  1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE NOT EXISTS (SELECT * FROM zones WHERE zone_country_id = (SELECT countri...' at line 1  
```
Last one didn't upgrade.

**Comment by drbyte** [comment]
I found a `10.6.16-MariaDB-1:10.6.16+maria~ubu2204` db to test on. 
Statement runs fine without errors.

I wonder if there's something specific to MariaDB 10.3 vs 10.6 regarding this? 
Granted, I'd be surprised that such a significant syntax change would occur between minor point releases.

What language/locales do you have configured on your server? I have only the default character sets and locales for an English-based North American install.

**Comment by asiksami** [comment]
Hmm.. Maybe a hidden bug on 10.3 (?).
Here's `locale -a` result:
```
C
C.UTF-8
en_GB.utf8
fi_FI.utf8
POSIX
```

With MariaDB I go pretty much on defaults. Charset client/connection/database is set to `utf8mb4`. Our store is at Finland, North Europe, and we do have some multibyte characters, but DB is also set for `utf8mb4` charset with `utf8mb4_swedish_ci` collation. I doubt that these affects this (?).

Server though is a 32-bit ARM (Raspbian 10). Could this 32-bit affect this (?)

Hard to tell. 🤔 If no one can replicate this error, I don't mind of updating it by hand on develop server. Production server uses MySQL. It might just be a bug in the version or some setting that fails it.

**Comment by torvista** [comment]
In phpMyadmin I created a new database using utf8mb4_unicode_520ci, imported my production database and tried this query.

MariaDb
10.3.36: fail
10.3.39: fail
10.4.1: pass
10.4.5: pass

**Comment by drbyte** [comment]
Thanks @torvista
That's helpful!

**Comment by drbyte** [comment]
Let's try a modification to the SQL statement...

@asiksami @torvista does this work better?
```diff
INSERT INTO zones ( zone_country_id, zone_code, zone_name ) SELECT
( SELECT countries_id FROM countries WHERE countries_iso_code_3 = 'ITA' ),
'SU',
'Sud Sardegna'
+AS tmp 
WHERE
	NOT EXISTS (
	SELECT
		* 
	FROM
		zones 
	WHERE
		zone_country_id = ( SELECT countries_id FROM countries WHERE countries_iso_code_3 = 'ITA' ) 
		AND zone_code = 'SU' 
	) 
+ LIMIT 1;
```

**Comment by torvista** [comment]
10.3.39
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS tmp
WHERE
    NOT EXISTS (
    SELECT
        *
    FROM
        zones
    WHERE
        zone...' at line 5

**Comment by drbyte** [comment]
Sigh. 
Okay. Here's a bigger variation:

```sql
INSERT INTO zones ( zone_country_id, zone_code, zone_name ) SELECT * FROM
(SELECT countries_id AS zone_country_id, 'SU' AS zone_code, 'Sud Sardegna' AS zone_name FROM countries WHERE countries_iso_code_3 = 'ITA' LIMIT 1) AS tmp 
WHERE NOT EXISTS (SELECT * FROM zones WHERE zone_country_id = ( SELECT countries_id FROM countries WHERE countries_iso_code_3 = 'ITA' ) AND zone_code = 'SU' LIMIT 1) 
LIMIT 1;
```

**Comment by drbyte** [comment]
Edit: slight tweak; apologies that the SQL looks strangely formatted: that's for zc_install's prefix-replacement 
```sql
INSERT INTO zones ( zone_country_id, zone_code, zone_name ) SELECT * FROM
(SELECT countries_id AS zone_country_id, 'SU' AS zone_code, 'Sud Sardegna' AS zone_name
FROM countries WHERE countries_iso_code_3 = 'ITA' LIMIT 1) AS tmp WHERE NOT EXISTS (SELECT *
FROM zones WHERE zone_country_id = (SELECT countries_id
FROM countries WHERE countries_iso_code_3 = 'ITA' LIMIT 1) AND zone_code = 'SU' LIMIT 1)
LIMIT 1;
```

**Comment by torvista** [comment]
both of those passed!

**Comment by drbyte** [comment]
> both of those passed!

Sweet!  Thanks for your help!

**Comment by asiksami** [comment]
Great thanks @drbyte and @torvista. Can also confirm that this latest (merged) change works:

- Manually in `PHPAdmin` with `MariaDB 10.3.39` ✅
- Auto upgrade `v2.0.0-beta1` installer with `MariaDB 10.3.39` ✅

So we can assume that this problem is related only to MariaDB's version 10.3.
