### ISSUE TITLE
Function zen_date_short returning year 2037 instead of 1969

### ISSUE THREAD

**Issue by piloujp** [zencart/zencart#6293]
When a customer creates an account with DOB field set at year 1969 (1969/xx/xx), when editing in my account or in admin/customers AND if DATE_FORMAT constant is set to 'Y/m/d', date displayed is 2037/xx/xx.

**Version**
Zen Cart version: Tested on recent versions, but was there for a while. I remembered having this problem with a customer like 10 years ago...
I tested on fresh install to be sure it is still there.

Steps to reproduce/demonstrate the behavior:
1. Activate DOB field display in Admin/Configurations/Customers details.
2. Set constant DATE_FORMAT in language files (admin. catalogue or both, depending on where you want to edit customer data).
3. Create a customer account with DOB year set to 1969.
4. Edit customer data in My Account or Admin Cutomers.

**Expected behavior**
Displayed date should be 1969 but is 2037

 - Operating System: Windows 11
 - Browser: firefox

Code in 'functions_dates.php' on line 89 that should correct this old PHP date function bug seems to actually be the origin of this bug.
Changing:
```
// error on 1969 only allows for leap year
    if ($year != 1969 && @date('Y', mktime($hour, $minute, $second, $month, $day, $year)) == $year) {
        return date(DATE_FORMAT, mktime($hour, $minute, $second, $month, $day, $year));
    } else {
        return preg_replace('/2037$/', $year, date(DATE_FORMAT, mktime($hour, $minute, $second, $month, $day, 2037)));
    }
```
To:
`        return date(DATE_FORMAT, mktime($hour, $minute, $second, $month, $day, $year));`
fixed the problem.

**Comment by drbyte** [comment]
The problem is that the patch looks for the year to be at the end of the formatted date: the regex `/2037$/` is only replacing `2037` correctly when it's at the end of the string.

**Comment by drbyte** [comment]
I guess since the only 4-digit string would be the year, we could safely remove the `$` from the regex, and even replace the `preg_replace` with `str_replace`.

**Comment by piloujp** [comment]
> The problem is that the patch looks for the year to be at the end of the formatted date: the regex `/2037$/` is only replacing `2037` correctly when it's at the end of the string.
> 
> I guess since the only 4-digit string would be the year, we could safely remove the `$` from the regex, and even replace the `preg_replace` with `str_replace`.

Yes, I figured it out, and the simplest fix is to replace it by $year. But this code is so old and was made to fix a bug in PHP Date function before PHP 5.1 (as far as my search on the Internet could tell me). 
I would say it was written like 10 years ago to keep compatibility with older version of PHP at the time...
In my opinion, we could get rid of it... Except if somebody has heard of this PHP bug still being around more recently.

**Comment by drbyte** [comment]
> In my opinion, we could get rid of it... Except if somebody has heard of this PHP bug still being around more recently

I agree. I have not researched to determine whether that has been correctly fixed.
In PHP 8.3 it seems to still generate a 1969 year when y=1969, m=02, d=29,30,31 (and even days 32,33, etc) so, perhaps it is true that the year segment is indeed stable enough to remove the patch.

**Comment by piloujp** [comment]
The problem was coming from some systems not accepting negative Unix timestamps, Windows and some Linux distributions.
[https://bugs.php.net/bug.php?id=11371](https://bugs.php.net/bug.php?id=11371)
It was in early 2000 years. PHP 5.1 release in 2005 fixed that (in strtotime function). Maybe a bug remained for year 1969. I could not find anything about it, but both PHP and Systems evolved a lot since then (20 years ago) and I am confident we can assume safely the bug is gone for long now.

**Comment by drbyte** [comment]
I agree. 
Feel free to submit a PR.
