### ISSUE TITLE
Copy buttons for address details?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6334]
For those dinosaur businesses like ours that do not yet have end-to-end joined up business software, something we find useful is a complete copy of customer details.
I've added these buttons which copy the name, address, phone, email to the clipboard, without any labels etc. for pasting into other software, spreadsheets etc.
![2024-03-19 13_20_00-Admin Orders](https://github.com/zencart/zencart/assets/4391026/a22cea1d-f43d-4a87-8154-6c218228b288)

**Comment by scottcwilson** [comment]
There's a plugin that does this already. 
https://www.zen-cart.com/downloads.php?do=file&id=2274

**Comment by torvista** [comment]
ok, so that plugin adds a button to the order infobox:
![2024-03-19 15_31_15-Admin Orders — Mozilla Firefox](https://github.com/zencart/zencart/assets/4391026/1a296a8a-e7c8-472b-907e-4c4a56004c8b)

Not quite the same: I added Copy for each address details, since they may be different.

Still, having a copy in the infobox seems useful/would not cause offence, why not add that functionality anyway....

**Comment by drbyte** [comment]
Like you, I'm inclined to prefer the buttons in the main page, not the infobox.

How's your code compare with the plugin's code?

**Comment by torvista** [comment]
Plugin uses observer to create button as expected.
I also used an observer, to insert a script copy to clipboard function after address, that just gets the node.textContent.
So that would need reworking to add to end of orders or a separate jscript file.

**Comment by drbyte** [comment]
> would need reworking to add to end of orders or a separate jscript file

The admin will already auto-load any `includes/javascript/PAGENAME.js` or `PAGENAME.php` file if present. So probably a relatively easy place to put it. And then no observer needed either.
