### ISSUE TITLE
Incorrect date displayed in admin header if `extension=intl` isn't loaded

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#6341]
If running with a PHP base whose `php.ini` doesn't include the `intl` extension, the date in the admin header displays like:

![image](https://github.com/zencart/zencart/assets/2685585/777601e4-787b-41f9-b6d3-ac9158f68b76)

With that PHP extension loaded, the header date's display looks like:

![image](https://github.com/zencart/zencart/assets/2685585/dff7056f-3fcb-4f09-b158-04cb7493307b)

Credit: @proseLA for helping to figure that out!

**Comment by drbyte** [comment]
Aside: I've updated the docs to reflect that `intl` is a required extension:
https://docs.zen-cart.com/user/first_steps/server_requirements/

**Comment by lat9** [comment]
Should there be a zc_install check as well?

**Comment by drbyte** [comment]
> Should there be a zc_install check as well?

Agreed.
