### ISSUE TITLE
Admin, function zen_draw_form: addition of input type="hidden" name="cmd"

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6353]
While debugging an unrelated issue in orders.php, the hidden fields were getting flagged in console errors.

I see this:

![2024-03-23 11_06_52-Admin Orders — Mozilla Firefox](https://github.com/zencart/zencart/assets/4391026/19682fc2-443d-4202-bc69-f2391a0d2839)

This hidden field is added to the form tag in function zen_draw_form when the form is type get:
```
if (strtolower($method) === 'get') {
        $form .= '<input type="hidden" name="cmd" 
```

But this cmd parameter is already added to the form action in function zen_href_link:
```
    else if (!empty($parameters)) {
        $link .= 'index.php?cmd='. $page . '&' . zen_output_string($parameters);
```

So I'm wondering if this hidden field is necessary? Form still works with it removed.

**Comment by drbyte** [comment]
What was the console error message?

**Comment by torvista** [comment]
It's not related, so  for your interest...I've retrieved the min and max order numbers to put those limits on the Order ID search field.
`<input type="number" name="oID" id="oID" class="form-control" placeholder="Order ID:" min="20100001" max="20241234" aria-describedby="helpBlock2">`
I was reviewing this with a mind to PR it.

But when putting an invalid value in there, (apart from the browser popup telling you to put a number in there), the console shows these
![image](https://github.com/zencart/zencart/assets/4391026/e25d7a74-0bcb-4e1b-8869-1f3e33604978)

While I'm not convinced these are real errors, it brought my attention to the cmd hidden field, which appears to be redundant,
