### ISSUE TITLE
PHP error with french language and not with english

### ISSUE THREAD

**Issue by andrela** [zencart/zencart#6362]
**Describe the bug**
I am testing zencart with an updated translation in french with zencart 2.0 rc1 and when in the admin area getting to countries with french language selectioned i have this error below, and the page won't display it's final row with the possibility to view the other countries, i only have Afghanistan to Azerbaijan

When i select english it is fine but i can't find in wich page the error come from so i ask here for hints please

[27-Mar-2024 18:32:58 UTC] PHP Fatal error:  Uncaught ArgumentCountError: 4 arguments are required, 3 given in /var/www/html/zencart/sHarp-E>
Stack trace:
#0 /var/www/html/zencart/sHarp-Emg-sweEt/includes/classes/split_page_results.php(360): sprintf()
#1 /var/www/html/zencart/sHarp-Emg-sweEt/countries.php(262): splitPageResults->display_count()
#2 /var/www/html/zencart/sHarp-Emg-sweEt/index.php(11): require('...')
#3 {main}
  thrown in /var/www/html/zencart/sHarp-Emg-sweEt/includes/classes/split_page_results.php on line 360

[27-Mar-2024 18:32:58 UTC] Request URI: /sHarp-Emg-sweEt/index.php?cmd=countries, IP address: toto
--> PHP Fatal error: Uncaught ArgumentCountError: 4 arguments are required, 3 given in /var/www/html/zencart/sHarp-Emg-sweEt/includes/classe>
Stack trace:
#0 /var/www/html/zencart/sHarp-Emg-sweEt/includes/classes/split_page_results.php(360): sprintf()
#1 /var/www/html/zencart/sHarp-Emg-sweEt/countries.php(262): splitPageResults->display_count()
#2 /var/www/html/zencart/sHarp-Emg-sweEt/index.php(11): require('...')
#3 {main}
  thrown in /var/www/html/zencart/sHarp-Emg-sweEt/includes/classes/split_page_results.php on line 360.

**Version**
Zen Cart version: 2.0.0.rd1
PHP version: 8.2.7 (Zend: 4.2.7)
MySQL version: MySQL 10.11.6-MariaDB-0+deb12u1
Plugins that may be related: no plugins, just the language pack i am working on having done the conversion from 1.5.7 version of philibell
What older/newer versions were also tested?

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
4. See such-and-such

**Expected behavior**

**Screenshots**

**Debug/Error Logs**

 
**Devices (please complete the following information):**
 - Operating System: [e.g. Windows, Mac, Android, iOS]
 - Browser [e.g. chrome, firefox] and version number

**Additional context**

**Comment by drbyte** [comment]
Your language definition for `TEXT_DISPLAY_NUMBER_OF_COUNTRIES` has 3 `%` parameters, instead of only 2. 

English:
```
    'TEXT_DISPLAY_NUMBER_OF_COUNTRIES' => 'Displaying <b>%d</b> of <b>%d</b> Countries',
```
