### ISSUE TITLE
language loader on the admin side...

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#6365]
lets say i wanted to use the this file here:

https://github.com/zencart/zencart/blob/master/admin/includes/languages/english/lang.category_product_listing.php

for some other use.  if the file was on the storefront side, one could load said file using this method:

https://github.com/zencart/zencart/blob/c1b6aba2d61ffea86bc1d28bd964889b03fda415/includes/functions/functions_files.php#L122-L132

there does seem to be a function for loading a new style admin language file that resides in the admin directory tree.  or am i wrong here?  if so, please enlighten me.

in addition, when looking at the above method, could we not make it a bit simpler by removing the `IS_ADMIN_FLAG` conditional?  ie:

```
    global $messageStack, $languageLoader;
    $lang_file = zen_get_file_directory(DIR_FS_CATALOG . DIR_WS_LANGUAGES . $_SESSION['language'] . $folder, $file, 'false');
    if ($languageLoader->hasLanguageFile(DIR_FS_CATALOG . DIR_WS_LANGUAGES,  $_SESSION['language'], $file, $folder)) {
...
```

**Comment by scottcwilson** [comment]
Search for "If you are loading an admin side language file" in this file - it's the last example before back references: 

https://docs.zen-cart.com/dev/code/158_language_files/

**Comment by proseLA** [comment]
so basically:
```php
$languageLoader->loadExtraLanguageFiles(DIR_WS_LANGUAGES, $_SESSION['language'],  'myneededfile.php', '/');
```

thank you.
