### ISSUE TITLE
php 8.0.30: fatal error for ini_set using int values

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6366]
While reviewing a template that does not work php>8.1, I found my shop would not work php<8.1- with no logs.

This was due to two things
1) Fatal errors from all the instances of ini_set using integers instead of strings (including $logging_level)

https://github.com/zencart/zencart/blob/c1b6aba2d61ffea86bc1d28bd964889b03fda415/includes/functions/functions_error_handling.php#L146-L157

2) Duplicated constants due to the main configure loaded after the /local configure. 
Discussed ad nauseam here: https://github.com/zencart/zencart/issues/3159

Neither issue causes a problem 8.1+.

**Comment by lat9** [comment]
Yep, from php.net's description of the ini_set function (https://www.php.net/manual/en/function.ini-set.php):

![image](https://github.com/zencart/zencart/assets/2685585/efc8ed8f-3e77-438d-b048-9cfca8425ce6)

**Comment by lat9** [comment]
OK, I'm not seeing this issue.  Running zc200-rc2 on PHP 8.0.23.  No fatal `ini_set` errors being logged; no whitescreens.

**Comment by drbyte** [comment]
> Fatal errors from all the instances of ini_set using integers instead of strings (including $logging_level)

Were the `fatal` errors caused by `strict_types` mode being enabled?

> most of those @ini_set('value', {integer value}); calls have been there forever. Does that error get reported in zc158[a] running on PHP 7.4, for instance?
>  I'm not seeing this issue. Running zc200-rc2 on PHP 8.0.23. No fatal ini_set errors being logged; no whitescreens.

I suspect that the reason it was not a problem prior to 8.1 is that coercive typing allowed for the differences. PHP has long accepted both strings and integers for ini_set despite having been documented otherwise.

**Comment by torvista** [comment]
`Were the fatal errors caused by strict_types mode being enabled?`

Sorry, yes, I didn't notice that at the time, too deep in a template rabbit-hole. My bad.

**Comment by torvista** [comment]
What a mess!
