### ISSUE TITLE
making product name consistent across the repo....

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#6367]
in looking at the code for v200, it seems that one can successfully override the `zen_get_products_name` function without touching any of the base code.  this is a change that i applaud. (thank you @torvista.  change was done in this commit 759b64d0af.)

the override is done when the `zen_get_products_name` function calls the `zen_get_product_details` function as seen here:

https://github.com/zencart/zencart/blob/c1b6aba2d61ffea86bc1d28bd964889b03fda415/includes/functions/functions_products.php#L32-L34

unfortunately, for the majority of times a customer is displayed a product, the `zen_get_products_name` function is not used.

one such instance is on line 219 here:

https://github.com/zencart/zencart/blob/c1b6aba2d61ffea86bc1d28bd964889b03fda415/includes/modules/product_listing.php#L219-L223

due to the multi-lingual aspect of ZC, one can very easily override the products description, as the method `zen_get_products_description` as seen on line 222 is consistently used whenever calling the products description. 

ideally if one were to want to change the construction of the product name as presented to the customer, one should be able to do it in 1 place; but and most importantly, do it WITHOUT changing any of the base zc code.

i see 2 potential solutions to this problem:

- change all uses of the product name to call the `zen_get_products_name` function.
- change all product listings to only retrieve the `products_id`, and then use the `zen_get_product_details` to retrieve all necessary information about the product.

i think the 2nd option affords more flexibility for more things.  but i'm open on that...  it seems the 1st option might be easier to implement.

does anyone have any thoughts?  and or willingness to accept a PR if one were attempted?

**Comment by drbyte** [comment]
> this change works for all pages that make use of the product listing. but what about the centerboxes? the sideboxes? the shopping cart? some of these places make use of the method zen_get_product_details, ie the shopping cart, and some do not. in addition, some places, the change is available to be made without making a change to the core code... ie, this notifier NOTIFY_MODULES_FEATURED_PRODUCTS_B4_LIST_BOX allows me to change the name there... but why should i have to if it is already changed in the aforementioned function?

Can we assemble a list here of the known affected places? I'm going to look into the bigger picture of this this week, and having a bulleted list would be a little extra help to make sure I'm not missing an edge case.

You mentioned:
- product listing (which now covers the SNAF pages too)
- centerboxes
- sideboxes
- shopping_cart

**Comment by proseLA** [comment]
> Can we assemble a list here of the known affected places? 

i will certainly make an attempt!

**Comment by proseLA** [comment]
this list is by no means exhaustive, but...

### modules that use `NOTIFY_GET_PRODUCT_DETAILS`

- page: shopping cart
- page: checkout confirmation


- centerbox: monthly specials
- centerbox: also purchased


- sidebox: notifications
- sidebox: shopping cart
- sidebox: quick re-order



### modules that do **NOT** use `NOTIFY_GET_PRODUCT_DETAILS`

- centerbox: featured products
- centerbox: upcoming products


- product listing: responsive classic

 
- sidebox: bestsellers
- sidebox: specials
- sidebox: featured products
- sidebox: new products
