### ISSUE TITLE
admin, orders, edit: PHP Warning: Trying to access array offset on false \admin\includes\javascript\orders.php for store_pickup shipping

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6368]
strict reporting,, make an order using store_pickup
Admin, Edit Order:

PHP Warning: Trying to access array offset on false in D:\GitHub\zencart\admin\includes\javascript\orders.php on line 18 etc,

as $order->delivery is not set

So perhaps delivery should be set with the store address?

**Comment by drbyte** [comment]
An additional consideration: Should `zen_address_format()` be getting called, instead of just splitting things all onto separate lines? It already handles a lot of things like missing delivery address, etc.  But its output is "formatted".

**Comment by torvista** [comment]
Well, since this info is for the admin, not the customer, perhaps it should remain a static/constant format.
I found that coping with an empty delivery address requires mods in the orders.php as well as the javascript, hence thinking that the easiest fix is to populate the delivery with the store address as that was the delivery!
