### ISSUE TITLE
Admin > Customers > Customers : Newsletter dropdown shows wrong status

### ISSUE THREAD

**Issue by webchills** [zencart/zencart#6372]
Version:
Zen Cart version:  2.0.0
PHP version:  8.2.16
MySQL version: 10.5.23

Issue:
The dropdown for the newsletter subscription in the admin section (customers > customers) is always showing unsubscribed, no matter if the customers_newsletter field in the customers table is 0 or 1
Changing the value via the dropdown is indeed changing the database value but the status in the dropdown keeps "Unsubscribed" no matter what you are changing to.

Steps to reproduce/demonstrate the behavior:
1. Register a new account and check the newsletter checkbox
2. Verify in the database: customers_newsletter in table customers is 1
3. Admin > customers > customers. Edit the customer. Newsletter dropdown is showing unsubscribed which is wrong

**Comment by scottcwilson** [comment]
Thanks @proseLA and @lat9 for your high speed work!
