### ISSUE TITLE
Update implementation guide

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#6389]
In the docs/ folder in the Zen Cart project.  Both filename and contents refer to 1.5.8.  TY to @barco57 for catching.

**Comment by drbyte** [comment]
https://github.com/zencart/zencart/commit/bc13a5430ca6b09a0b23fe7dbed3564f991e94e6
https://github.com/zencart/zencart/commit/a8baab09b766bb6b3e54439b364862ced138452d
