### ISSUE TITLE
no stamp on file...

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#6390]
is this intentional?

https://github.com/zencart/zencart/blob/a8baab09b766bb6b3e54439b364862ced138452d/includes/init_includes/init_coupons.php#L1-L12

**Comment by scottcwilson** [comment]
No - the files that are missing headers don't get stamped.  We need to build an audit in, perhaps at checkin time.  Thanks for reporting.

**Comment by scottcwilson** [comment]
[admin_noheader.txt](https://github.com/zencart/zencart/files/14933426/admin_noheader.txt)
[storefront_noheader.txt](https://github.com/zencart/zencart/files/14933428/storefront_noheader.txt)

**Comment by zcwilt** [comment]
note: will create a codesniffer action/rule to test for this on PR.

**Comment by drbyte** [comment]
> [admin_noheader.txt](https://github.com/zencart/zencart/files/14933426/admin_noheader.txt) [storefront_noheader.txt](https://github.com/zencart/zencart/files/14933428/storefront_noheader.txt)

Those are helpful; however contain many false-positives: unused files, retired files, 3rd party vendor files, local-dev-only files.
