### ISSUE TITLE
New Products not Displaying

### ISSUE THREAD

**Issue by mprough** [zencart/zencart#6398]
**Describe the bug**
No new products were displaying anywhere, even though the time setting in New Product Listing - Limited to ... is 0

Upon searching I found

Code:
// $display_limit = zen_get_products_new_timelimit();
  $display_limit = zen_get_new_date_range();

**Version**
ZC 2.0
PHP 8.3
Boot 3.6.4

Switching to the commented out code brings all the new products to their parts (sidebox, centerbox, page, etc)

**Comment by scottcwilson** [comment]
Seems like after fixing we should also remove zen_get_products_new_timelimit() and all commented out calls to it.

**Comment by scottcwilson** [comment]
Group 2 and 3 Configuration settings are integers, not strings.  
So this change:
https://github.com/zencart/zencart/commit/5a4aaabe4f15920e0499b0384ad108d950d76766
introduced those two errors.

After my PR is merged I will do a follow on to remove the old unused code; I'll keep this fix small so people can pull it in if they need it.
