### ISSUE TITLE
products_option_values_name gets sanitized

### ISSUE THREAD

**Issue by webchills** [zencart/zencart#6405]
Zen Cart version: 2.0.0
PHP version: 8.2.16
MySQL version: MariaDB 10.5.23
Plugins that may be related: None, Vanilla Installation

If you save an Option Value Name containing a & character it gets sanitized to `&amp;` which should not be the case

Steps to reproduce/demonstrate the behavior:
1. Go to Option Value Manager
2. Add a new option value named Yellow & Green to the color attribute
3. Go to Attributes controller
4. Add the new attribute to any product
5. In the dropdown you see Yellow `&amp;`  Green instead of Yellow & Green
6. Look in the database table products_options_values and you see that the products_options_values_name has been stored indeed as Yellow `&amp;` Green

See attached screens
![option_value_manager_3](https://github.com/zencart/zencart/assets/1009695/704d5906-d18e-4513-8c7e-fbb191c57dc7)
![option_value_manager_1](https://github.com/zencart/zencart/assets/1009695/2b74b9e9-0c7c-43d0-a604-fd9293dcc09b)
![option_value_manager_2](https://github.com/zencart/zencart/assets/1009695/fd40056a-66a2-4663-8abb-d59840c5c901)
![option_value](https://github.com/zencart/zencart/assets/1009695/261f07b9-cdf6-4285-9386-f2d9a7776d4a)

**Comment by lat9** [comment]
I _believe_ that the issue is not so much that the value is stored as `&amp;` but that the Adding New Attributes display in the admin re-running the values' names through `htmlspecialchars`, resulting in an `&amp;amp;` display.  I'm having a devil of a time finding where that multi-select data is generated.

**Comment by webchills** [comment]
The same behaviour is for product_options_name. I don' t think that this is just a minor cosmetic issue in the dropdown.
Why do we replace at all here? 
We do not do this for category names or product names or order status names. In these fields & remain & when saving and for the attribut names and attribute option names it should be the same. Already tried some changes in admin/includes/init_sanitize.php without success so far.

**Comment by lat9** [comment]
It's the embedded function `zen_js_option_values_list` present in the attributes_controller.php which creates a chunk of javascript to display that multi-select list of options.  The value displays properly on the storefront for the options' values and everywhere else that the `&` should be displayed.

**Comment by lat9** [comment]
FWIW, I'm not seeing the same behavior for the options' names.  While the `&` is stored as `&amp;`, the value is properly rendered as a single `&` when displayed both in the admin and on the storefront.

**Comment by webchills** [comment]
I know it's displayed correctly. Instead of struggling with the attributes controller we could just save an & as an & as we do it for other fields as well. Why cluttering the database with all these `&amp;` in these fields? Store a new order_status_name called Testing & Testing and it will be stored as Testing & Testing. What's the benefit/sense of treating attribut names and attribute values names in a different way?

**Comment by lat9** [comment]
> I know it's displayed correctly. Instead of struggling with the attributes controller we could just save an & as an & as we do it for other fields as well. Why cluttering the database with all these `&amp;` in these fields? Store a new order_status_name called Testing & Testing and it will be stored as Testing & Testing. What's the benefit/sense of treating attribut names and attribute values names in a different way?

I agree.  For consistency, the option-names and option-value-names should use the same "rules" for storing character data in the database as all the other admin tools.

**Comment by webchills** [comment]
I suggest the following change in admin/includes/init_includes/init_sanitize.php:

Line 241

from:
`$group = ['categories_name', 'products_name', 'orders_status_name', 'configuration'];`

to:
`$group = ['categories_name', 'products_name', 'orders_status_name', 'option_name', 'value_name', 'configuration'];`

After this change & in option names and option values get correctly stored as & and of course displayed correctly again in the attribute manager dropdown

**Comment by lat9** [comment]
> > I know it's displayed correctly. Instead of struggling with the attributes controller we could just save an & as an & as we do it for other fields as well. Why cluttering the database with all these `&amp;` in these fields? Store a new order_status_name called Testing & Testing and it will be stored as Testing & Testing. What's the benefit/sense of treating attribut names and attribute values names in a different way?
> 
> I agree. For consistency, the option-names and option-value-names should use the same "rules" for storing character data in the database as all the other admin tools.

I'm going to have to take my agreement 'back'.  As far back as 1.5.7 (and most likely earlier), the HTML entities in the options' names and option-values' names have been stored in the database as their encoded value -- e.g. `&` is saved as `&amp;`.  Changing the way that information is saved in the database would pose backwards-compatibility issues on templates and plugins that manipulate/use those fields since, depending on which version of ZC last 'touched' a value, those characters might be encoded ... but they might not.

As such, my counter-proposal is to simply correct the **_display_** of the information, when viewed by the admin's **_Attributes Controller_**.
