### ISSUE TITLE
if ($_SESSION['cart']->in_cart_check not working anymore

### ISSUE THREAD

**Issue by webchills** [zencart/zencart#6408]
Zen Cart version: 2.0.0
PHP version: 8.2
MySQL version: Maria DB 10.5
Plugins that may be related:  None, Vanilla

Many stores are using things like this in their templates/files:

`if ($_SESSION['cart']->in_cart_check('products_id','24') > 0) { //do something`
or
`if ($_SESSION['cart']->in_cart_check('master_categories_id','5') > 0) { //do something`
or
`if ($_SESSION['cart']->in_cart_check('any_field_in_products_table','1') > 0) { //do something`

Often used to disable a shipping module in certain circumstances or to display something in certain circumstances.

Example:

In the shopping cart, a text should be displayed, if a product with products_id 24 is in the cart.
In includes/templates/YOURTEMPLATE/templates/tpl_shopping_cart_default.php the following code is added:
`<?php if ($_SESSION['cart']->in_cart_check('products_id','24') > 0) { ?>`
`<b>TEST</b>`
`<?php } ?>`

In 1.5.8 and any version before this is working as expected and TEST is shown.

Try this in 2.0.0 and nothing is shown

No matter which conditions you are trying to check.

158:
![158](https://github.com/zencart/zencart/assets/1009695/a09a2d74-7f19-478d-8aa1-4ae1f6a59001)
200:
![200](https://github.com/zencart/zencart/assets/1009695/4e937407-de45-4128-9494-22cabc87feb6)

**Comment by scottcwilson** [comment]
Thanks for writing this up.
