### ISSUE TITLE
Multiple taxes calculation error when prices are displayed with tax.

### ISSUE THREAD

**Issue by piloujp** [zencart/zencart#6410]
In last github version of ZC, when multiple taxes apply to a product and option to display prices with tax is set to true, calculated taxes are wrong. When displaying prices without tax, they are OK.

**To Reproduce**
Add a new tax rate with Florida as zone.
Set 'Display prices with Tax' to true.
Set 'Show Split Tax Lines' to true (not necessary, but easier to check).
Log in client side and use an address in Florida.
Add a product to cart and go to last checkout screen.
Check taxes

I have a solution I will PR soon.

**Comment by lat9** [comment]
@piloujp, I realize that this change has been merged but could you be more specific regarding the test case you used for the "new tax rate"?

I know, for instance, that Florida taxes have two components:  a state tax rate and then a municapility tax rate.  Is that what this change is addressing?

**Comment by piloujp** [comment]
> @piloujp, I realize that this change has been merged but could you be more specific regarding the test case you used for the "new tax rate"?
> 
> I know, for instance, that Florida taxes have two components: a state tax rate and then a municapility tax rate. Is that what this change is addressing?

Yes, it is what I did, adding a second tax rate for Florida. I had a first tax at 7% then a second at 10% or whatever.
Problem was that a reverse tax calculation was done on a number always without tax.
