### ISSUE TITLE
admin site-specific css

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#6420]
for those of us that prefer to have our css as separate files as opposed to being in the source of the page, are we receptive to adding something like the following to admin_html.php?

```php
    if (file_exists(DIR_WS_INCLUDES . 'css/site-specific-styles.css')) {
        ?>
        <link rel="stylesheet" href="<?= DIR_WS_INCLUDES .'css/site-specific-styles.css' ?>">
        <?php
    }
```

**Comment by scottcwilson** [comment]
LOL I WAS LITERALLY JUST THINKING THIS!  Please proceed.

**Comment by scottcwilson** [comment]
I have a client who is up in age and needs a larger font, etc.  Had to modify the main admin stylesheet, and thought, "Gee, I wish there was a site-specific file."

**Comment by drbyte** [comment]
Observations:

To Scott's point: We already have `css/site-specific-styles.php`. So your client could use that today.

To Paul's point: "I prefer not bring CSS into the page source", ya you'd have to load a .css file separately.
But you could do that (via an include/require) IN the `css/site-specific-styles.php` file "today".

I'm not opposed to the addition though. However, it should be output *before* the `css/site-specific-styles.php` is processed.

**Comment by scottcwilson** [comment]
I misread this and was thinking we did. not have an admin site specific stylesheet.  But we do!  

It makes no sense to do what @proseLA is suggesting - this actually makes the page load more slowly.

**Comment by proseLA** [comment]
> To Paul's point: "I prefer not bring CSS into the page source", ya you'd have to load a .css file separately. But you could do that (via an include/require) IN the `css/site-specific-styles.php` file "today".
> 
this is a good idea.  i will do that.  thank you.

@scottcwilson in general, css files are cached by the browser.  the hit on performance with regards to the extra conditional is neglible, so i really do not understand about what you are talking.

**Comment by scottcwilson** [comment]
You can watch the network tab in Chrome inspect and see the delay for each file added.
