### ISSUE TITLE
Attempting to select a coupon from page > 1 will occasionally fail 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#6437]
`$cInfo` never gets set on line 1189.

This issue will only be seen on page > 1 if there are > 20 (or > MAX_DISPLAY_SEARCH_RESULTS_DISCOUNT_COUPONS) coupons. 

Will PR after #6436 is merged (and once I figure it out!)

Worked in 1.5.7 and 1.5.8.

**Comment by scottcwilson** [comment]
Working on repro steps.  This is an upgraded db so it may be an issue with the upgrade.

**Comment by scottcwilson** [comment]
It has something to do with the absence of the action parameter.  When run with `action=voucheredit` the same command works fine, but attempting to build the right hand box fails because `$cInfo` is not set.

**Comment by scottcwilson** [comment]
#6381 broke this

**Comment by scottcwilson** [comment]
You have to create `$cInfo` in this case by doing an extra query.

**Comment by drbyte** [comment]
Should we unwrap the `if(isset())` that was added in 6381, too?

**Comment by scottcwilson** [comment]
that's part of the fix - coming soon!
