### ISSUE TITLE
Very minor: customers_info_date_account_created should be date_account_created in Customer.php

### ISSUE THREAD

**Issue by neekfenwick** [zencart/zencart#6444]
Very minor issue, I noticed the field name is wrong in Customer.php.  I'm not sure if this has any actual impact on the system.

https://github.com/zencart/zencart/blob/8eb0b099d98ec053954694cb21cd31d33831790b/includes/classes/Customer.php#L190-L193

While the database field is indeed `customers_info_date_account_created`, the `data` element being referenced here is `date_account_created`.  The result is that the if always tests true, so the `INSERT IGNORE` is always attempted.

Anyone making mods to `Customer.php` might want to include this little fix.

**Comment by scottcwilson** [comment]
thanks, please PR.
