### ISSUE TITLE
Resolve "Alternate page with proper canonical tag" issue in Google Search Console

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#6446]
A lot of sites get this because of the use of cPath in generated URLs (when canonical does *not* have a cPath).  

Would it be better to drop this parameter (at least optionally)?

**Comment by scottcwilson** [comment]
Example: with the test data, responsive classic template and Zen Cart 2.0.0, go to the home page and observe the featured products centerbox.   The link to the mouse is 

index.php?main_page=product_info&cPath=1_9&products_id=26

But if you go to this page and view source, the canonical URL is 

/index.php?main_page=product_info&products_id=26

So the featured centerbox link winds up being unindexable by Google and leads to the page being added to the list of unindexed pages (which wastes your crawl budget). 

<img width="500" alt="non_canonical" src="https://github.com/zencart/zencart/assets/4391638/7675a8e5-8686-4b22-9224-ab0b3832fe76">

**Comment by lat9** [comment]
Wouldn't this also apply to various product listings' product links?

**Comment by drbyte** [comment]
But ... the cPath **is** an alternate path to the canonical URL. So "alternate page with proper canonical tag" is probably an accurate assessment.

A product can be in many categories, so cPath is never used as an authoritative parameter for a product, hence it not being in the canonical URL.

The cPath **is** useful to the human shopper by offering display of additional information/products/data related to the canonical product indicated by the URL. It serves not only as a map to related items, but also a sort of breadcrumb navigation pattern to get "to" the product.

If the cPath is absent, ZC internally guesses it using master-category-id.
But if cPath is provided and points to a linked category other than master, it provides useful navigation data for the shopper.

**Comment by scottcwilson** [comment]
Google used to allow you to ignore specific parameters but no more.  

We could make this optional and people who don't have linked products would benefit.  Otherwise you're wasting your crawl budget.

**Comment by scottcwilson** [comment]
> Wouldn't this also apply to various product listings' product links?

Correct.

**Comment by drbyte** [comment]
Instead of committing such a thing to core directly and then hoping, I recommend implementing it on a dozen sites for several months and collect empirical data for the before and after. And then explore whatever that data indicates as potential coding changes to consider.

**Comment by scottcwilson** [comment]
That's way more work than I can do for free.  This is a big change.  Closing.

**Comment by drbyte** [comment]
Yes, it's a huge change. And I think the coding changes are similarly huge.
