### ISSUE TITLE
Coupon Codes Leaking Via popup_coupon_help

### ISSUE THREAD

**Issue by robryanx** [zencart/zencart#646]
Currently someone can load this page with each sequential coupon id to retrieve all the coupon codes.

I don't think that there is any issue with changing the page to use the coupon code itself for lookup, being a popup I think it is unlikely that it would be commonly bookmarked/ directly accessed.

I might submit a pull request for this if I get time.

**Comment by ajeh** [comment]
I can change the cID to display "information" about the Discount Coupon but where do you see the actual Discount Coupon redemption code?

**Comment by robryanx** [comment]
Sorry, yes you are correct.
Looking again the issue for us is that we just use the coupon code as the coupon name.
I wonder if it would still be best to pass the code so it wouldn't be possible to grab all the coupon data. (minus the actual code as you pointed out).

**Comment by ajeh** [comment]
Many want that title to show.

Any reason not to change your policy of using the Discount Coupon title to something other than the redemption code?

It is something to think about.

**Comment by ajeh** [comment]
This could be helpful as some, may like use the Discount Coupon redemption code as the Title and others might reference the redemption code in the Discount Coupon description.

**Comment by robryanx** [comment]
Nah, no reason not to change it, it is just something I hadn't considered previously and it's interaction with this page.

Not sure how common it is with others but by requiring a name it might lead a lot to simply copy paste the come into the name.

I don't think there would be anything stopping say a coupon site to write a crawler to grab every coupon name and then test to see if it is accepted.
