### ISSUE TITLE
search has some problems...

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#6483]
first off, i think `keywords` needs to be `keyword` here:

https://github.com/zencart/zencart/blob/9abc65e56c48ec709bff86664267e3e93c8e78c2/includes/modules/pages/search_result/header_php.php#L31-L33

one can look at this refactor eda3955a5e and see that the initial code used `keyword`.

because when we roll down to this notifier:
https://github.com/zencart/zencart/blob/9abc65e56c48ec709bff86664267e3e93c8e78c2/includes/modules/pages/search_result/header_php.php#L45

`$keywords` is not even set for the notifier.

curiously enough, the keywords being used for search are now set here:

https://github.com/zencart/zencart/blob/9abc65e56c48ec709bff86664267e3e93c8e78c2/includes/classes/class.search.php#L40

which i suppose is close to the same above (assuming we were to make the change i first talked about), but there is something about that code that smells wrong to me.  i think the `$keywords` in the notifier should be the actual one used in the search.

finally, while i am a fan of having moved all of this to a class file; could we not have broken out the method `buildSearchSQL` into something more manageable than a 300 line method? 

i would think a series of smaller method calls to build the SQL would make the code more readable, as well as provide the ability to extend this class and make specific changes to particular parts.  it just seems that this class/refactor is still a bit unwieldy and not real friendly for developers to extend.

and yes, i'm well aware of the notifiers in there and their use; but it just seems like an opportunity that was missed.

**Comment by drbyte** [comment]
1. Yes, I agree: `$_GET['keywords']` should be `$_GET['keyword']`

2. "i think the $keywords in the notifier should be the actual one used in the search."
Does this work:
```diff
- $zco_notifier->notify('NOTIFY_SEARCH_RESULTS', $listing_sql, $keywords, $result);
+ $zco_notifier->notify('NOTIFY_SEARCH_RESULTS', $listing_sql, $searchOptions->keywords, $result);
```
  (It's a public property on the class, so I'm guessing it might also be updatable by an Observer ... but not sure it matters at this point. Probably one only cares to "read" the var at this stage, not change it.)

3. Yes, we can iterate improvements to the structure of this class.

**Comment by proseLA** [comment]
i think that should work.  i'll take a look over the weekend...

on a related note, is there any thought about 2.1.x having a minimum version of mysql 8.0?

mysql 5.7 has been EOF since 10/2023.  i'm thinking the `split_page_results` could be simplified (hopefully) with common table expressions.  

it seems that one can have a `listing_sql` that executes without problem; but when fed into the `split_page_results` class, it dies.

doing all of this `strpos` sort of stuff for a pager is so fraught with problems:

https://github.com/zencart/zencart/blob/9fdd94c5c045d778784c7dc7fa6da94c0502e76c/includes/classes/split_page_results.php#L85-L100

**Comment by scottcwilson** [comment]
> on a related note, is there any thought about 2.1.x having a minimum version of mysql 8.0?

Too early.  Still tons of clients on 5.7.

**Comment by lat9** [comment]
@proseLA, can this issue be closed, based on that PR back in May?
