### ISSUE TITLE
MFA: no email sent on selection of email as method

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6492]
After enabling MFA, on first login you are redirected to a MFA option.
On selecting the email as method, browser proceeds to next page asking for validation code from email, but no email has been sent.

Additionally, it appears that for a select with a **required** attribute, there needs to be a "Please Select" option in addition to the two options.

![2024-05-26 21_43_05-Admin Mfa — Mozilla Firefox](https://github.com/zencart/zencart/assets/4391026/666b89ab-9b1f-4bb6-addd-c9f4a1ed0c7e)

https://rocketvalidator.com/html-validation/the-first-child-option-element-of-a-select-element-with-a-required-attribute-and-without-a-multiple-attribute-and-without-a-size-attribute-whose-value-is-greater-than-1-must-have-either-an-empty-value-attribute-or-must-have-no-text-content-consider-either-adding-a-placeholder-option-label-or-adding-a-size-attribute-with-a-value-equal-to-the-number-of-option-elements

**Comment by drbyte** [comment]
> After enabling MFA, on first login you are redirected to a MFA option.
On selecting the email as method, browser proceeds to next page asking for validation code from email, but no email has been sent.

I can't replicate the problem. I'm getting the emails.

**Comment by drbyte** [comment]
> Additionally, it appears that for a select with a required attribute, there needs to be a "Please Select" option in addition to the two options.

Trying to understand why it makes sense for such an imposition: Why does the user need to be told to "Please select" something and then have to actually navigate to a new selection, instead of just accepting the first one presented. Less user friendly. Less intuitive.
But this really has nothing to do with email.

**Comment by torvista** [comment]
Maybe being required elevates the importance and all options should have equal weight/there be no default/no pre-selected value?

**Comment by torvista** [comment]
MFA Email:
note that the "missing" email is the first one, due to be sent on **selecting** the OTP/email method.

On subsequent login attempts, the email is sent correctly.

**Comment by torvista** [comment]
Is MFA working 100% for other testers?

**Comment by scottcwilson** [comment]
Testing is on my list, I just haven't gotten to it yet.  Will respond ASAP.

**Comment by drbyte** [comment]
https://github.com/zencart/zencart/commit/5a79768be6011ad7c08347325ac492244fc3ba37 may fix the email-not-sent issue you're mentioning.

**Comment by drbyte** [comment]
While I think it's truly dumb and entirely unintuitive, I suspect the "validator" is imposing the "rule" because of some usability issue.
So, since I think it's important to keep the field marked "required", I've added an empty selection to accommodate the validator.

**Comment by scottcwilson** [comment]
Can this ticket be closed?  The email is working for me too.
