### ISSUE TITLE
Zones shipping module requires cast to double to avoid fatal error php 8.3

### ISSUE THREAD

**Issue by highburyeye** [zencart/zencart#6503]
**Describe the bug**
Fatal php error with php 8.3 in /includes/modules/shipping/zones.php

**Version**
Zen Cart version: 2.0.1
PHP version: 8.3 
MySQL version: 
Plugins that may be related: dont think so
What older/newer versions were also tested?

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
enable zones module, check out, blank page on checkout-shipping page

**Expected behavior**
Shipping page should not be blank

**Screenshots**
n/a
```
[31-May-2024 09:59:34 Pacific/Auckland] Request URI: /index.php?main_page=checkout_shipping, IP address: 101.98.36.94
--> PHP Fatal error: Uncaught TypeError: Unsupported operand types: float + string in /includes/modules/shipping/zones.php:312
Stack trace:
#0 /includes/classes/shipping.php(245): zones->quote('')
#1 /includes/modules/pages/checkout_shipping/header_php.php(185): shipping->quote()
#2 /public_html/index.php(35): require('/var/www/0bedff...')
#3 {main}
  thrown in /includes/modules/shipping/zones.php on line 312.
```
**Devices (please complete the following information):**
Tested on Linux firefox / opera

**Additional context**
to fix modify /includes/modules/shipping/zones.php 
```php
      if ($shipping == -1) {
        $shipping_cost = 0;
        $shipping_method = MODULE_SHIPPING_ZONES_UNDEFINED_RATE;
      } else {
        switch (MODULE_SHIPPING_ZONES_METHOD) {
          case (MODULE_SHIPPING_ZONES_METHOD == 'Weight'):
            // charge per box when done by Weight
            // Handling fee per box or order
            if (constant('MODULE_SHIPPING_ZONES_HANDLING_METHOD_' . $dest_zone) == 'Box') {
              $shipping_cost = (double)($shipping * $shipping_num_boxes) + (double)constant('MODULE_SHIPPING_ZONES_HANDLING_' . $dest_zone) * $shipping_num_boxes;//TC cast to double required for php 8 or fatal error
            } else {
              $shipping_cost = (double)($shipping * $shipping_num_boxes) + (double)constant('MODULE_SHIPPING_ZONES_HANDLING_' . $dest_zone);//TC cast to double required for php 8 or fatal error
            }
            break;
          case (MODULE_SHIPPING_ZONES_METHOD == 'Price'):
            // don't charge per box when done by Price
            $shipping_cost = (double)($shipping) + (double)constant('MODULE_SHIPPING_ZONES_HANDLING_' . $dest_zone);//TC cast to double required for php 8 or fatal error
            break;
          case (MODULE_SHIPPING_ZONES_METHOD == 'Item'):
            // don't charge per box when done by Item
            $shipping_cost = (double)($shipping) + (double)constant('MODULE_SHIPPING_ZONES_HANDLING_' . $dest_zone);//TC cast to double required for php 8 or fatal error
            break;
        }
      }
```

**Comment by drbyte** [comment]
I think you could probably cast only the `constant`, since that's the part that's a string value. 
And I'd probably cast to `float`.

**Comment by highburyeye** [comment]
Yes, that idea seems to work - will continue testing on multiple sites but all good so far. 

So recomended changes are now to the file /includes/modules/shipping/zones.php

if ($shipping == -1) {
        $shipping_cost = 0;
        $shipping_method = MODULE_SHIPPING_ZONES_UNDEFINED_RATE;
      } else {
        switch (MODULE_SHIPPING_ZONES_METHOD) {
          case (MODULE_SHIPPING_ZONES_METHOD == 'Weight'):
            // charge per box when done by Weight
            // Handling fee per box or order
            if (constant('MODULE_SHIPPING_ZONES_HANDLING_METHOD_' . $dest_zone) == 'Box') {
              $shipping_cost = ($shipping * $shipping_num_boxes) + (float)constant('MODULE_SHIPPING_ZONES_HANDLING_' . $dest_zone) * $shipping_num_boxes;//TC cast to float required for php 8 or fatal error
            } else {
              $shipping_cost = ($shipping * $shipping_num_boxes) + (float)constant('MODULE_SHIPPING_ZONES_HANDLING_' . $dest_zone);//TC cast to float required for php 8 or fatal error
            }
            break;
          case (MODULE_SHIPPING_ZONES_METHOD == 'Price'):
            // don't charge per box when done by Price
            $shipping_cost = ($shipping) + (float)constant('MODULE_SHIPPING_ZONES_HANDLING_' . $dest_zone);//TC cast to float required for php 8 or fatal error
            break;
          case (MODULE_SHIPPING_ZONES_METHOD == 'Item'):
            // don't charge per box when done by Item
            $shipping_cost = ($shipping) + (float)constant('MODULE_SHIPPING_ZONES_HANDLING_' . $dest_zone);//TC cast to float required for php 8 or fatal error
            break;
        }
      }
    }
