### ISSUE TITLE
admin, Copy Product: multiple issues/fatal errors

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6504]
master branch, strict reporting, php8.3.8RC1 

There is too much to document, just try it.

**Comment by torvista** [comment]
Broken since the changes introduced from the Product class are not implemented.

**Comment by scottcwilson** [comment]
Duplicated.  Assigning to @drbyte.

**Comment by lat9** [comment]
Likewise, here's a log when I tried to link a product from one category to another:
```
[05-Jun-2024 17:25:40 America/New_York] PHP Fatal error:  Uncaught TypeError: zen_get_admin_module_from_directory(): Argument #1 ($product_type) must be of type int, string given, called in C:\xampp\htdocs\zc200w\admin200\category_product_listing.php on line 229 and defined in C:\xampp\htdocs\zc200w\includes\functions\functions_files.php:205
Stack trace:
#0 C:\xampp\htdocs\zc200w\admin200\category_product_listing.php(229): zen_get_admin_module_from_directory('2', 'copy_product_co...')
#1 C:\xampp\htdocs\zc200w\admin200\index.php(16): require('C:\\xampp\\htdocs...')
#2 {main}
  thrown in C:\xampp\htdocs\zc200w\includes\functions\functions_files.php on line 205

[05-Jun-2024 17:25:40 America/New_York] Request URI: /zc200w/admin200/index.php?cmd=category_product_listing&action=copy_product_confirm&cPath=62&page=1, IP address: 127.0.0.1
--> PHP Fatal error: Uncaught TypeError: zen_get_admin_module_from_directory(): Argument #1 ($product_type) must be of type int, string given, called in C:\xampp\htdocs\zc200w\admin200\category_product_listing.php on line 229 and defined in C:\xampp\htdocs\zc200w\includes\functions\functions_files.php:205
Stack trace:
#0 C:\xampp\htdocs\zc200w\admin200\category_product_listing.php(229): zen_get_admin_module_from_directory('2', 'copy_product_co...')
#1 C:\xampp\htdocs\zc200w\admin200\index.php(16): require('C:\\xampp\\htdocs...')
#2 {main}
  thrown in C:\xampp\htdocs\zc200w\includes\functions\functions_files.php on line 205.

[05-Jun-2024 17:25:40 America/New_York] Request URI: /zc200w/admin200/index.php?cmd=category_product_listing&action=copy_product_confirm&cPath=62&page=1, IP address: 127.0.0.1
--> PHP Fatal error: Uncaught TypeError: zen_get_admin_module_from_directory(): Argument #1 ($product_type) must be of type int, string given, called in C:\xampp\htdocs\zc200w\admin200\category_product_listing.php on line 229 and defined in C:\xampp\htdocs\zc200w\includes\functions\functions_files.php:205
Stack trace:
#0 C:\xampp\htdocs\zc200w\admin200\category_product_listing.php(229): zen_get_admin_module_from_directory('2', 'copy_product_co...')
#1 C:\xampp\htdocs\zc200w\admin200\index.php(16): require('C:\\xampp\\htdocs...')
#2 {main}
  thrown in C:\xampp\htdocs\zc200w\includes\functions\functions_files.php on line 205.
```

**Comment by torvista** [comment]
php 8.3.8, strict reporting

1) On Copy:
PHP Fatal error:  Uncaught TypeError: zen_get_admin_module_from_directory(): Argument #1 ($product_type) must be of type int, string given, called in D:\GitHub\zencart\admin\category_product_listing.php on line 229 and defined in D:\GitHub\zencart\includes\functions\functions_files.php:205
Stack trace:
#0 D:\GitHub\zencart\admin\category_product_listing.php(229): zen_get_admin_module_from_directory('1', 'copy_product_co...')
#1 D:\GitHub\zencart\admin\index.php(16): require('D:\\GitHub\\zenca...')
#2 {main}
  thrown in D:\GitHub\zencart\includes\functions\functions_files.php on line 205

since strict_types has crept into category_product_listing.php 

2) Once 1) is resolved, the copied product is missing multiple fields that should be copied (manufacturer, model, price.....)

**Comment by drbyte** [comment]
@torvista #6520, now merged, should resolve those things

**Comment by torvista** [comment]
Still missing multiple fields from the Copy.
e.g
![2024-06-13 22_10_34-Admin Product](https://github.com/zencart/zencart/assets/4391026/ac94c08a-478e-4b6a-b036-7fd429d3ee9e)

**Comment by torvista** [comment]
Bump.

**Comment by scottcwilson** [comment]
Reproduced in master branch under PHP 8.2.  Reopening.

**Comment by scottcwilson** [comment]
@torvista Please confirm satisfactory at your earliest availability.

**Comment by scottcwilson** [comment]
It looks beautimous to me under PHP 8.2.

**Comment by torvista** [comment]
ok, here, thanks.
