### ISSUE TITLE
Product quantity with 0 as the last digit not being accepted

### ISSUE THREAD

**Issue by vasilt71** [zencart/zencart#6517]
ZC 2.0
PHP 8.3
Store with fractional quantities. 
QUANTITY_DECIMALS constant is set to 2.
Shopping cart quantity field trims all integer values ending in zero(s) to the number without the last zeros, e.g. 10 goes to 1 when updating the field. The issue seems to arise from the preg_replace function on lines 1370 and 2395 in includes/classes/shopping_cart.php.

**Comment by scottcwilson** [comment]
Forum report: https://www.zen-cart.com/showthread.php?230172-Product-quantity-with-0-as-the-last-digit-not-being-accepted

**Comment by scottcwilson** [comment]
Would you like to PR your fix, @vasilt71 ?

**Comment by drbyte** [comment]
The preg_replace has been there for ages.

So I'm wondering if the problem is in some of the outer / wrapping code that was updated in #6011 or #6157

**Comment by piloujp** [comment]
With today's ZC GitHub version (2.1.0-alpha1), I was not able to reproduce this.
Setting QUANTITY_DECIMALS does not seem to have any effect.
I can enter quantity with as much as 4 decimals (more decimals are rounded to 4 dec.) whatever the setting for QUANTITY_DECIMALS.
When last decimal is 0 it is removed but when last non-decimal number is 0, it is not. I can enter quantities of 10, 20 ...

**Comment by piloujp** [comment]
My Bad, I thought it was on admin side.
In cart problem is as described in OP plus All decimal input are rounded to 0 decimal and an error message is displayed.

**Comment by lat9** [comment]
> The preg_replace has been there for ages.
> 
> So I'm wondering if the problem is in some of the outer / wrapping code that was updated in #6011 or #6157

Twas #6157.  PR forthcoming.
