### ISSUE TITLE
Apply a Special/Sale price to a specific attribute 

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6527]
In general, we use Specials to clear stock, in fact the special price gets auto-removed when stock reaches zero.

Unless it is a product with attributes...
since the product IS the attribute, it would be ideal if a special price could be applied to that attribute only/treating the attribute as the discrete product it is, instead of the base product globally, which in some cases encompasses 6 product variants. And of course no-one buys the one you want to sell.
The only way to to currently avoid this is make a separate product for that one variant.

**Comment by drbyte** [comment]
I thought there were some notifier hooks in the pricing functions that could assist with that.

**Comment by torvista** [comment]
Not looked. Maybe it's a grey area / treading in SBA/POSM territory...

**Comment by lat9** [comment]
Noting that the `S` in both `S`BA and PO`S`M refers to those additions' handling of `s`tock, not necessarily pricing.

**Comment by torvista** [comment]
There is an add-on for POSM that does pricing and weight per attribute, which I had not noticed!
