### ISSUE TITLE
fatal error if missing product id on info page

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6529]
Using this url:
SITE/index.php?main_page=product_info

> #0 [internal function]: zen_debug_error_handler()
> #1 includes/functions/html_output.php(27): trigger_error()
> #2 includes/modules/pages/product_info/header_php.php(18): zen_href_link()
> #3 index.php(35): require('.....')
> --> PHP Fatal error: zen_href_link(, , NONSSL), unable to determine the page link. in includes/functions/html_output.php on line 27.

**Comment by scottcwilson** [comment]
Confirmed.

Can this be reproduced any other way than diddling the URL in the browser address bar?

**Comment by torvista** [comment]
Dunno, this has cropped up on my live site, from some spider I imagine.
But as far as I can see, if the header finds no valid $_GET['products_id'], it should redirect immediately?
Instead it assigns 0 (also invalid) and falls into the error.

**Comment by scottcwilson** [comment]
> if the header finds no valid $_GET['products_id'], it should redirect immediately?

Seems reasonable.  Would you please PR?

**Comment by torvista** [comment]
Prefer not to...doesn't this need to send 301 back as well.

**Comment by scottcwilson** [comment]
I would say 404.  See includes/modules/pages/page/header_php.php line 44-46 for an example of how to handle this.

**Comment by torvista** [comment]
I think thought needs to be given to revise the subsequent code where there is another check for the products_id.

**Comment by torvista** [comment]
I consider error logs to indicate errors...something I need to investigate.
"Normal" badly formed urls from spiders or hacks should not cause a log in my opinion. Needless clutter.
