### ISSUE TITLE
problems with multi-lingual websites.

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#6543]
according to [the docs](https://docs.zen-cart.com/user/admin_pages/localization/languages/#:~:text=You%20can%20create%20a%20multi%2Dlanguage%20store%20by%20installing%20language%20packs%20and%20then%20adding%20Languages%20as%20described%20above.), one can create a multi-lingual website.

however, the current implementation of multi-lingual sites will create all kinds of SEO problems, as the implementation of the `hreflang` looks to be wrong.

right now, if one has a multi-lingual site, one can set the language by using a `$_GET` var which in turn sets a `SESSION` var so that from that point on, all pages are now in the chosen language.  for google, that is a problem.  depending on the `SESSION` var, ZC will display the chosen language.  which means the same URL could have different languages, ie mysite.com may be in english, french, italian, etc. depending on the `SESSION`.

in order to properly implement the `hreflang` tag; the tags must be bi-directional, and right now that is not the case.

for example, assuming a default language of `en`; one is at mysite.com; in the header there is an alternate tag for french which is mysite.com/?language=fr.  when one goes to that link, because tags need to be bi-directional, there should be a link back to mysite.com for english.  but of course there is not (there could be mysite.com/?language=en for english; but that does NOT satisfy the bi-directional requirement); when one does go back to mysite.com, it will now be in french, as ZC implements languages based on `SESSION` vars and not `GET` vars.

i believe that unless each language has its own unique url, zc will not be able to conform to successfully implementing the `hreflang` tag.

**Comment by drbyte** [comment]
> there could be mysite.com/?language=en for english; but that does NOT satisfy the bi-directional requirement); when one does go back to mysite.com, it will now be in french, as ZC implements languages based on SESSION vars and not GET vars.

As long as the `GET` parameter is present, the site will render in the specified language, because the session will switch over as long as the GET parameter is part of the URL.

**Comment by proseLA** [comment]
i am not saying the site will not render in the specified language.

what i am saying is that the same URL could be in many different languages, and from an SEO standpoint that is a problem.

there is plenty of good data on the web as to how to successfully implement the `hreflang` tag.  [this site](https://www.weglot.com/guides/hreflang-tag) for example.

the bottom line is that the language must be in the URL, and not in a `SESSION` var.

if we do not want to support the `hreflang` tag, i would totally understand that.  but right now it is in the code, and i still believe it is incorrectly implemented.

**Comment by drbyte** [comment]
Apart from not implementing optional "x-default" tag, if a site has more than one language defined, it automatically generates hreflang links for all defined languages, crosslinking all so no language is missed. I think you called that a backlink. 

While the GET params do trigger session changes, if the user follows that link (on their own or provided by SE results), then they'll get the site in the requested/expected language. 

I read through the entire article you linked, and we "check all the boxes," metaphorically. 

What exactly do you think is missing?

Note that language specific subdomains and subdirectories are not viable options for core code without specialized .htaccess infrastructure which most casual store owners can't implement, and would be specific to Apache , and in this world of alternate web engines (nginx etc) often htaccess isn't even supported anymore.

**Comment by proseLA** [comment]
i can not tell now if you still do not believe there is a problem; or if as you last paragraph states, it is too hard for casual store owners to implement.

with regards to the 2nd point, i refer back to my comment from yesterday:

> if we do not want to support the `hreflang` tag, i would totally understand that. but right now it is in the code, and i still believe it is incorrectly implemented.

i agree that successful implementation would be quite difficult.

with regards to my first point, if you think that from a SEO standpoint, having a URL that changes languages based on a `SESSION` var will not generate problems which can result in pages not getting indexed by search engines, i'm not sure what else i can say on the topic.

i do think that our efforts are better spent elsewhere.
