### ISSUE TITLE
Remove (currently unused and deprecated) `includes/classes/boxes.php`?

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#6544]
While that class file's load is currently forced, its actual class is marked as deprecated and there's no core-code usage.  I'm guessing that it's left-over from the older .dhtml way of adding elements to the admin's menus.

**Comment by scottcwilson** [comment]
I thought it was still used but you're right.  Was it replaced by includes/classes/table_block.php ?

**Comment by drbyte** [comment]
Looks like we deprecated it a long time ago, like 2012.
Probably left it in core just for backward-compatibility of old plugins. 
But it's probably safe to remove now. Anyone who wants it can grab it from prior version zips easily.

**Comment by lat9** [comment]
I'll get that outta there once PR #6541 is merged.
