### ISSUE TITLE
Attributes' +/- pricing display includes product's base price

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#6564]
When a product is priced by attributes, its base price is adjusted by the attribute(s)' pricing when displayed.  In the current Zen Cart repo, the attributes' pricing displayed now includes the product's base price.

To see using the demo products:
1. Create a copy of the "Gift Certificates by attributes" product (id=47), also copying the associated attributes, enable the copied product and set its quantity to some value > 0.
2. Edit the copied product, changing its base price to 5.00.
3. Edit the copied product's attributes, changing the price of the `$5.00` 'Amount' to have a price_prefix of '+' and a price of 0.00.
4. Navigate to the storefront to view the now-active copied product.

The product's attribute selection section's pricing incorrectly includes the $5.00 product base price:
![image](https://github.com/zencart/zencart/assets/2685585/1f93d8fb-b497-4cae-ab2e-c49559cef01f)

**Comment by scottcwilson** [comment]
My interpretation of that has always been that $5 is the lowest price available.  I don't see this as a defect.

**Comment by lat9** [comment]
Look at the pricing.  The `$10.00` amount shows as a +$15.00, not +10.00.  In zc155f, the `$5.00` amount would show without the parenthetical amount since its added price over/above the base price is 0.

**Comment by lat9** [comment]
Noting that this issue also affects the Bootstrap template.

**Comment by scottcwilson** [comment]
OK that I agree is confusing and wrong.
