### ISSUE TITLE
Issue viewing orders not on first page 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#6574]
Same as #6468 but on orders page.  Repro requires a cart with > 20 orders (assuming default settings). 

Repro: go to home page, in the list of new orders on the right hand side, click an order which is more than 20 orders ago.  I will open the page 

admin/index.php?cmd=orders&oID=old-order-number&origin=index

with the right infoBox blank.  Same fix as for customers page required on orders page.

**Comment by lat9** [comment]
Actually, what I'm seeing is (for a site with > 20 orders, with Max Display Orders set to 20), that the issue only appears when clicking on the 21st order in the list.  The orders' page's page-count on the listing still shows page number 1 and the sidebox is empty.

Clicking on order 22+, the page-count shows 2 and the order's sidebox is properly rendered.

**Comment by scottcwilson** [comment]
LOL I was lucky my first test dup'ed it.
