### ISSUE TITLE
Bottom of POSM View All screen is mixed up

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#6580]
Zen Cart logo should be at the very bottom. 

![Screen Shot 2024-07-13 at 2 25 39 PM](https://github.com/user-attachments/assets/ea8cbfea-9504-4d0a-867c-1fbf8ee5b6a1)

**Comment by lat9** [comment]
As a distinction, that's when no products are (a) currently managed or (b) don't have quantities less than the current 're-order level'.

**Comment by scottcwilson** [comment]
I know but the logo should still be at the bottom. This is confusing to look at.
