### ISSUE TITLE
zc install not updating project_version_history

### ISSUE THREAD

**Issue by brittainmark** [zencart/zencart#6593]
zc_install debug error on update  project_version_history.

**Describe the bug**
debug file generated

**Version**
Zen Cart version: 2.0.1
PHP version: MySQL version: 
Plugins that may be related:  n/a
What older/newer versions were also tested?

**To Reproduce**
1. upgrade db from 1.5.8 to 2.0

**Expected behavior**
no debug file and project_version_history updated.

**Debug/Error Logs**
```
[18-Jul-2024 14:51:12 Europe/London] MySQL error 1064 encountered during zc_install:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
INSERT INTO zen_project_version_history (project_version_key, project_version_major, project_version_minor, project_version_patch, project_version_date_applied, project_version_comment)
---------------
```

**Additional context**
the full command is being truncated, so does not include the following select statement.
```
INSERT INTO project_version_history (project_version_key, project_version_major, project_version_minor, project_version_patch, project_version_date_applied, project_version_comment)
SELECT project_version_key, project_version_major, project_version_minor, project_version_patch1 as project_version_patch, project_version_date_applied, project_version_comment
FROM project_version;
```

fix to folllow!

**Comment by scottcwilson** [comment]
i don't believe this is fixed - please retest.

**Comment by brittainmark** [comment]
I tested 1.5.8.a to 2.0.1. and used it on my live site 

![image](https://github.com/user-attachments/assets/ae441d34-4ab6-4b6a-a363-8f6dda6feaa8)

This has not been back ported to 2.0

There are other issues with the db installer class. The #NEXT_X_ROWS_AS_ONE_COMMAND does not work. I believe it is supposed to keep the next n whole commands together, not the next n lines for a single command.

**Comment by brittainmark** [comment]
Just ran against demo. copying zc_install/includes/classes/zcDatabaseInstaller.php from master
![image](https://github.com/user-attachments/assets/846b0f48-3370-49d9-848c-b7fe000242e2)

**Comment by scottcwilson** [comment]
That's not the project_version_history table.  It's the project_version table.  Please check the  project_version_history table.

**Comment by brittainmark** [comment]
Table after initial install
![initialInstall](https://github.com/user-attachments/assets/b69069b9-2098-4968-bedb-6fbfad298b2d)
Table after update
![After201](https://github.com/user-attachments/assets/9c888561-a3a2-438b-94d4-a859b9be8491)
Two additional records have been inserted into the table.
The install copies that last install/update information into the table not the latest version. If that is not correct then the install needs further changing. not sure what more I can do. The change is working as records are now going into the history table. when they wern't before. The screen shots in the previous post show a combination of information from the  history table and the current version table.

**Comment by scottcwilson** [comment]
Sorry, you're right - I was misreading the data.  I wish this data was in a single table so we didn't have to do these operations, but there you are.  Thanks for getting this fixed.

**Comment by brittainmark** [comment]
no problem, i did a double take when i had fixed it.
