### ISSUE TITLE
Plugin Manager: increase default listing limit from 5 entries

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6603]
I must have wasted at least 15 seconds puzzling why a plugin was not showing up in the list, until I noticed there were two pages.
It is hard-coded to 5 entries on the page:

https://github.com/zencart/zencart/blob/3724e7ac313ed5647fc2745af2c155b9b08b1507/admin/plugin_manager.php#L36

which seems unnecessarily low.

It is unlikely that this will ever be a list that needs multiple pages at all, perhaps this should be set very high like 100, when next it is edited.

**Comment by scottcwilson** [comment]
Please PR - 20 seems like a reasonable number and is used elsewhere (max search results, max customers, etc.)
