### ISSUE TITLE
PHP Fatal error: Argument #1 ($country_id) must be of type string|int

### ISSUE THREAD

**Issue by Logandros** [zencart/zencart#6605]
**Describe the bug**
Seeing a new PHP fatal error involving $country_id

**Version**
Zen Cart version: v2.1.0-alpha
PHP version: 8.3.9 (Zend: 4.3.9)
MySQL version: MySQL 8.0.36

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Just found in normal operation via logs, not sure if this occurs when a new customer is choosing a country code.

**Debug/Error Logs**
`[19-Jul-2024 18:40:22 UTC] PHP Fatal error: Uncaught TypeError: zen_prepare_country_zones_pull_down(): Argument #1 ($country_id) must be of type string|int, null given, called in /includes/templates/template_default/templates/tpl_modules_create_account.php on line 93 and defined in /includes/functions/functions_addresses.php:195
Stack trace:
#0 /includes/templates/template_default/templates/tpl_modules_create_account.php(93): zen_prepare_country_zones_pull_down()
#1 /includes/templates/template_default/templates/tpl_login_default.php(90): require('/homepages/46/d...')
#2 /includes/templates/responsive_classic/common/tpl_main_page.php(178): require('/homepages/46/d...')
#3 /index.php(94): require('/homepages/46/d...')
#4 {main}
thrown in /includes/functions/functions_addresses.php on line 195

[19-Jul-2024 18:40:22 UTC] Request URI: /index.php?main_page=login&action=process, IP address: x.x.x.x
--> PHP Fatal error: Uncaught TypeError: zen_prepare_country_zones_pull_down(): Argument #1 ($country_id) must be of type string|int, null given, called in /includes/templates/template_default/templates/tpl_modules_create_account.php on line 93 and defined in /includes/functions/functions_addresses.php:195
Stack trace:
#0 /includes/templates/template_default/templates/tpl_modules_create_account.php(93): zen_prepare_country_zones_pull_down()
#1 /includes/templates/template_default/templates/tpl_login_default.php(90): require('/homepages/46/d...')
#2 /includes/templates/responsive_classic/common/tpl_main_page.php(178): require('/homepages/46/d...')
#3 /index.php(94): require('/homepages/46/d...')
#4 {main}
thrown in /includes/functions/functions_addresses.php on line 195.

[19-Jul-2024 18:40:22 UTC] Request URI: /index.php?main_page=login&action=process, IP address: x.x.x.x
--> PHP Fatal error: Uncaught TypeError: zen_prepare_country_zones_pull_down(): Argument #1 ($country_id) must be of type string|int, null given, called in /includes/templates/template_default/templates/tpl_modules_create_account.php on line 93 and defined in /includes/functions/functions_addresses.php:195
Stack trace:
#0 /includes/templates/template_default/templates/tpl_modules_create_account.php(93): zen_prepare_country_zones_pull_down()
#1 /includes/templates/template_default/templates/tpl_login_default.php(90): require('/homepages/46/d...')
#2 /includes/templates/responsive_classic/common/tpl_main_page.php(178): require('/homepages/46/d...')
#3 /index.php(94): require('/homepages/46/d...')
#4 {main}
thrown in /includes/functions/functions_addresses.php on line 195.`

**Comment by lat9** [comment]
Are there any countries that have been disabled for use via the admin tool?

**Comment by Logandros** [comment]
I just confirmed that they are all enabled. I've also not had the error since I posted this. So maybe just a specific customer messing around?

**Comment by lat9** [comment]
Thanks for the confirmation; I've been trying to recreate without success ... but I'll fuss some more.

**Comment by drbyte** [comment]
I'm guessing this only occurs when the Admin configuration setting for "display create account on login page" is enabled?

It's possible that we're not initializing some of those vars before calling the create_account subtemplate which depends on them.

**Comment by Logandros** [comment]
I tried looking for that setting, I'm not sure if this is what you are referring to otherwise I was unable to find it.
![Admin-Configuration-Customer-Details](https://github.com/user-attachments/assets/e9ad1738-b629-47f5-a1a0-2d07b0fc2be0)

Aside from that I did have the error again as of today in by logs:

I will paste it below even though it looks to be the same issue.

`[23-Jul-2024 10:52:28 UTC] Request URI: /index.php?main_page=login&action=process, IP address: x.x.x.x, Language id 1
#0 /includes/modules/create_account.php(414): zen_debug_error_handler()
#1 /includes/modules/pages/login/header_php.php(25): include('/homepages/46/d...')
#2 /index.php(35): require('/homepages/46/d...')
--> PHP Warning: Undefined variable $country in /includes/modules/create_account.php on line 414.

[23-Jul-2024 10:52:28 UTC] PHP Fatal error: Uncaught TypeError: zen_prepare_country_zones_pull_down(): Argument #1 ($country_id) must be of type string|int, null given, called in /includes/templates/template_default/templates/tpl_modules_create_account.php on line 93 and defined in /includes/functions/functions_addresses.php:195
Stack trace:
#0 /includes/templates/template_default/templates/tpl_modules_create_account.php(93): zen_prepare_country_zones_pull_down()
#1 /includes/templates/template_default/templates/tpl_login_default.php(90): require('/homepages/46/d...')
#2 /includes/templates/responsive_classic/common/tpl_main_page.php(178): require('/homepages/46/d...')
#3 /index.php(94): require('/homepages/46/d...')
#4 {main}
thrown in /includes/functions/functions_addresses.php on line 195

[23-Jul-2024 10:52:28 UTC] Request URI: /index.php?main_page=login&action=process, IP address: x.x.x.x
--> PHP Fatal error: Uncaught TypeError: zen_prepare_country_zones_pull_down(): Argument #1 ($country_id) must be of type string|int, null given, called in /includes/templates/template_default/templates/tpl_modules_create_account.php on line 93 and defined in /includes/functions/functions_addresses.php:195
Stack trace:
#0 /includes/templates/template_default/templates/tpl_modules_create_account.php(93): zen_prepare_country_zones_pull_down()
#1 /includes/templates/template_default/templates/tpl_login_default.php(90): require('/homepages/46/d...')
#2 /includes/templates/responsive_classic/common/tpl_main_page.php(178): require('/homepages/46/d...')
#3 /index.php(94): require('/homepages/46/d...')
#4 {main}
thrown in /includes/functions/functions_addresses.php on line 195.

[23-Jul-2024 10:52:28 UTC] Request URI: /index.php?main_page=login&action=process, IP address: x.x.x.x
--> PHP Fatal error: Uncaught TypeError: zen_prepare_country_zones_pull_down(): Argument #1 ($country_id) must be of type string|int, null given, called in /includes/templates/template_default/templates/tpl_modules_create_account.php on line 93 and defined in /includes/functions/functions_addresses.php:195
Stack trace:
#0 /includes/templates/template_default/templates/tpl_modules_create_account.php(93): zen_prepare_country_zones_pull_down()
#1 /includes/templates/template_default/templates/tpl_login_default.php(90): require('/homepages/46/d...')
#2 /includes/templates/responsive_classic/common/tpl_main_page.php(178): require('/homepages/46/d...')
#3 /index.php(94): require('/homepages/46/d...')
#4 {main}
thrown in /includes/functions/functions_addresses.php on line 195.`

**Comment by drbyte** [comment]
Some ideas to test:
`/includes/modules/create_account.php`, line 414, try:
`$selected_country = !empty($_POST['zone_country_id']) ? (int)$_POST['zone_country_id'] : $country ?? (int)SHOW_CREATE_ACCOUNT_DEFAULT_COUNTRY;`

That should stop the create_account.php error on line 414.

Then, while not ideal, we can permit a null value to the pulldown function, in functions_addresses.php line 195:
```diff
/**
 * Build an array of country zones for pulldown use
 *
- * @param int|string $country_id
+ * @param int|string|null $country_id
 * @return array
 */
-function zen_prepare_country_zones_pull_down(int|string $country_id = 0): array
+function zen_prepare_country_zones_pull_down(int|string|null $country_id = 0): array
{
-    $zones = zen_get_country_zones($country_id);
+    $zones = zen_get_country_zones($country_id ?? 0);
```
