### ISSUE TITLE
Orders page sorting removed but infrastructure remains

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#6619]
The orders page sorting was removed but orders.php lines 1252-1279 still set the unused variable `$disp_order`.  

It might be nice to have a sort dropdown next to the order status filter. Or we could just remove this code.

**Comment by torvista** [comment]
Sort by what?

**Comment by scottcwilson** [comment]
If you look at the code I referenced, you'll see the options.  I'm not sure any of them are terribly useful though.   It looks like it was modeled after the customer page sorting, but even back as far as 1.3.8, it wasn't fully implemented.

**Comment by torvista** [comment]
Yes, I see. Personally I've never missed not having a sort.

**Comment by drbyte** [comment]
> The orders page sorting was removed

When?

**Comment by drbyte** [comment]
> It might be nice to have a sort dropdown next to the order status filter.

Sometimes expanding the filtering options is more advantageous than a "sort". Granted, we do have a search.

**Comment by scottcwilson** [comment]
> > The orders page sorting was removed
> 
> When?

I *thought* it had been but I looked waaaaay back and couldn't find it.  So I guess this code has been there, unused,  forever?   Not strong on this, it's just a bit confusing if you're reading the code.

**Comment by drbyte** [comment]
Agreed: present, but unused, forever. 🤷‍♂️
