### ISSUE TITLE
White screen on php8.0 due to ini_set integer values

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6634]
When testing on php 8.0.30 I got white screen no logs.

I find that this is the problem:
https://github.com/zencart/zencart/blob/cdf79240b5222af70d6540abd9c83cfe8e0bf61d/includes/functions/functions_error_handling.php#L147-L150

From php.net

> 8.1.0 | value now accepts any scalar type (including null). Previously, only string values were accepted.

So the integers need to be strings. $logging_level needs also to be cast to string.

**Comment by drbyte** [comment]
Seems really backwards to convert these integers back to strings. Attempting to support strict-mode is how these got to be integers in the first place, because strict-mode was complaining.

And this is also further complicated by the fact that PHP 8.0 has been EOL since November 2023.

**Comment by torvista** [comment]
Sure, then the docs 
https://docs.zen-cart.com/user/first_steps/server_requirements/
and some installer code needs updating...

**Comment by scottcwilson** [comment]
What release did this happen on? 
Fresh download or modified?

**Comment by torvista** [comment]
aaargh, the original was modified with strict types, so a download should not cause a problem for normal people!

**Comment by scottcwilson** [comment]
thanks for confirming.
