### ISSUE TITLE
New product from duplicate: copy stock?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6636]
Currently the duplication of a product copies the stock to the duplicate.
Since duplication is only a shortcut to a **new/different** product, I suggest the stock should be zero, not the same as the source product.

**Comment by scottcwilson** [comment]
They already have to edit a bunch of things in the new product.  This is not worth doing, please close.

**Comment by torvista** [comment]
Maybe

**Comment by drbyte** [comment]
You could override it to `0` in `copy_products_confirm.php`:
```diff
        // separately_updated_fields - last_modified and products_id are skipped
+        $sql_data_array['products_quantity'] = 0;
        $sql_data_array['products_status'] = 0;
```
Or an observer could add `'products_quantity'` to `$separately_updated_fields` via `NOTIFY_MODULES_COPY_PRODUCT_CONFIRM_DUPLICATE_FIELDS`

**Comment by torvista** [comment]
yes, thanks, I'd used the observer.
