### ISSUE TITLE
Priced attributes look wrong in 2.1.0

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#6646]
View product 1 in ZC 2.0.1.  
The Model dropdown shows 
- Value at no additional cost
- Premium at +$100

Same product in ZC 2.1.0
Value +$299
Premium +$199

Possibly related to #6565 ?

**Comment by lat9** [comment]
Sure enough!  There's something different going on when a priced-by-attribute product has a non-zero vs. zero base price.
