### ISSUE TITLE
System check display in ZC installer when no problem detected

### ISSUE THREAD

**Issue by piloujp** [zencart/zencart#6660]
When installing ZC and no configuration problem has been found, hint about clicking on error message title is displayed although there is no error message. Would a message saying system check did not find any problem not be better?
![Capture2024-08-16_035835](https://github.com/user-attachments/assets/2be6903f-5e6d-42b6-8620-3f65c63346b7)

**Comment by lat9** [comment]
Would you try this with the `zc_install` update (https://github.com/zencart/zencart/pull/6650) provided by @drbyte?

**Comment by piloujp** [comment]
Yes, no problem.
I got this :
![Capture2024-08-18 025941](https://github.com/user-attachments/assets/9edeed7b-e540-4a20-8f98-9046e38d4862)

A message indicating System Check passed successfully would be nice. Actually, you don't know if test was done or not.

**Comment by drbyte** [comment]
It should be showing a green success message, but I think in your case the `configure.php` file is present but blank.
PR will address that, and hide the TIPS message.

**Comment by piloujp** [comment]
I confirm, at this step, configure.php files are blank. They are populated two screens later after the database has been created.
