### ISSUE TITLE
problem with loading of extra data into Customer class....

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#6662]
the use of a Customer class (of which i am a fan) and as seen here:

https://github.com/zencart/zencart/blob/d3306a999b681ebe6e7afca060b0d57c86e72d85/admin/customers.php#L1627-L1631

now prevents the loading of extra data into said object.  loading of extra data would seem to be done here:

https://github.com/zencart/zencart/blob/d3306a999b681ebe6e7afca060b0d57c86e72d85/includes/classes/Customer.php#L344

but `data`  is a protected array which disallows adding of elements from within an observer.

similar to the Product object, i think it is essential to provide for the ability to add extra data or modify data in the Customer object.

currently that ability is not provided, or i can not find it.  

i would guess the former; although i am certainly open to solutions to the ladder.

**Comment by lat9** [comment]
With [this](https://github.com/zencart/zencart/pull/6541) PR, introduced in zc201, the 'base' class is now auto-loaded, enabling you to load your override of the `Customers` class early on in the load process.

**Comment by lat9** [comment]
Crap, if only it was that easy ... it's not.

- Adding this to the psr4AutoLoader
```php
$psr4Autoloader->addPrefix('Zencart\Base', DIR_FS_CATALOG . DIR_WS_CLASSES);
```

- Removing this
```php
$psr4Autoloader->setClassFile('Customer', DIR_FS_CATALOG . DIR_WS_CLASSES . 'Customer.php');
```

- Changing the top bits of the Customer.php class to
```php
namespace Zencart\Base;

use Zencart\Traits\NotifierManager;

class Customer
{
    use NotifierManager;
```

... results in
```
16-Aug-2024 15:17:23 UTC] PHP Fatal error:  Uncaught Error: Class "Customer" not found in C:\xampp\htdocs\zc210\includes\functions\functions_prices.php:20
Stack trace:
#0 C:\xampp\htdocs\zc210\includes\functions\functions_prices.php(1154): zen_get_products_special_price('1', false)
#1 C:\xampp\htdocs\zc210\includes\modules\meta_tags.php(270): zen_get_products_actual_price('1')
#2 C:\xampp\htdocs\zc210\includes\templates\responsive_classic\common\html_header.php(25): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\zc210\index.php(42): require('C:\\xampp\\htdocs...')
#4 {main}
  thrown in C:\xampp\htdocs\zc210\includes\functions\functions_prices.php on line 20
```

**Comment by drbyte** [comment]
@proseLA 

>  `$this->notify('NOTIFY_CUSTOMER_DATA_LOADED', $this->data);` 

I haven't checked the following. Does it mitigate the problem? 

a. Add $this->data as an additional parameter to notify(): 
  `$this->notify('NOTIFY_CUSTOMER_DATA_LOADED', $this->data, $this->data);`
b. In the observer, receive it as `&$data` (or another name). Does it let you modify `$data` and pass it back thru the notifier to the class such that `$this->data` is updated?

**Comment by proseLA** [comment]
yes it does.

that solution would work fine for me.
