### ISSUE TITLE
zc_install: project_version_history record missing

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#6667]
zc157c upgrade; `project_version_history` table missing the version update from 1.5.8->2.0.0, see below.  Note also the missing `project_version_id` of 12.

![image](https://github.com/user-attachments/assets/595c8bba-243e-43cb-b86d-25700c82ad1a)

_Originally posted by @lat9 in https://github.com/zencart/zencart/issues/6650#issuecomment-2294904498_

**Comment by lat9** [comment]
OK, so how did you get that "originally posted" to show up?

**Comment by drbyte** [comment]
(deleted unrelated post)

**Comment by drbyte** [comment]
In trying to reproduce, I'm not able to trigger this situation.

Tried with several 1.3.9 databases, and all the project_version_history records are generated, without skipping ID's, and all steps are listed.

**Comment by drbyte** [comment]
We can re-open if the problem re-appears.

**Comment by scottcwilson** [comment]
Chris, are you sure you're not hitting this bug: https://github.com/zencart/zencart/issues/6593
Fixed by this update: https://github.com/zencart/zencart/pull/6594
