### ISSUE TITLE
Featured Categories needs a centerbox 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#6687]
Featuring a category is not nearly as prominent as featuring a product because there's no centerbox.

Original Featured Categories PR: #6643.

**Comment by scottcwilson** [comment]
OK there is one, it just doesn't work. 

```
--> PHP Fatal error: MySQL error 1051: Unknown table 'c' :: SELECT c.*, pt.product_type_id
                FROM categories
                LEFT JOIN product_types_to_category pt ON (c.categories_id = pt.category_id)
                WHERE categories_id = 34 LIMIT 1 ==> (as called by) /Users/scott/Sites/gh_demo_200/includes/classes/Category.php on line 132 <== in /Users/scott/Sites/gh_demo_200/includes/classes/db/mysql/query_factory.php on line 720.
```

**Comment by scottcwilson** [comment]
Fixed by #6688

**Comment by drbyte** [comment]
Oops. My bad. Thanks for catching that. Wasn't part of the Featured Categories PR: it was an update I made to the Category class which that PR introduced.

**Comment by scottcwilson** [comment]
It was a giant PR.  It's in good shape now - the only remaining issue I have found is in #6692.
