### ISSUE TITLE
Featured Categories addition causing an error (might be install error)

### ISSUE THREAD

**Issue by Logandros** [zencart/zencart#6691]
**Describe the bug**
Seeing an error in logs since testing the latest commits to use the new featured category option. Not sure if I missed some code or an sql update. Not sure if the issue is a bug or something I may have missed. Additionally if I try to set a featured category it breaks the right-hand column of the main page, most likely as a result of the missing sql injection or code error.

**Version**
Zen Cart version: v2.1.0-alpha1
PHP version: 8.3.10
MySQL version: MySQL 8.0.36
Plugins that may be related: n/a
What older/newer versions were also tested? none

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
Install latest commit [935b1e2](https://github.com/zencart/zencart/commit/935b1e203e5e9c0ec167de61734d3dfa7ec2a653)

**Expected behavior**
Should be able to enable a featured category

**Screenshots**

**Debug/Error Logs**
`[25-Aug-2024 22:25:31 UTC] Request URI: /, IP address: x.x.x.x, Language id 1
#0 [internal function]: zen_debug_error_handler()
#1 /includes/classes/db/mysql/query_factory.php(720): trigger_error()
#2 /includes/classes/db/mysql/query_factory.php(665): queryFactory->show_error()
#3 /includes/classes/db/mysql/query_factory.php(265): queryFactory->set_error()
#4 /includes/classes/Category.php(132): queryFactory->Execute()
#5 /includes/classes/Category.php(33): Category->loadCategoryDetails()
#6 /includes/modules/featured_categories.php(45): Category->__construct()
#7 /includes/templates/template_default/templates/tpl_modules_featured_categories.php(12): include('/homepages/46/d...')
#8 /includes/templates/template_default/templates/tpl_index_default.php(78): require('/homepages/46/d...')
#9 /includes/modules/pages/index/main_template_vars.php(232): require('/homepages/46/d...')
#10 /includes/templates/responsive_classic/common/tpl_main_page.php(178): require('/homepages/46/d...')
#11 /index.php(94): require('/homepages/46/d...')
--> PHP Fatal error: MySQL error 1146: Table 'dbs12804405.product_types_to_category' doesn't exist :: SELECT c.*, pt.product_type_id
FROM zencrt_categories c
LEFT JOIN product_types_to_category pt ON (c.categories_id = pt.category_id)
WHERE categories_id = 36 LIMIT 1 ==> (as called by) /includes/classes/Category.php on line 132 <== in /includes/classes/db/mysql/query_factory.php on line 720.`
 
**Devices (please complete the following information):**
 - Windows 11
 - Google Chrome

**Additional context**

**Comment by scottcwilson** [comment]
Please tell me the exact steps to reproduce.  These paths work for me: 

- Go to Admin > Catalog > Featured Categories and click a red status icon to enable a disabled featured category, it works.
- Go to Admin > Catalog > Featured Categories and Add By Selection
- Go to Admin > Catalog > Featured Categories and Add By Category ID.

Please be sure you have updated your fork; I made several changes yesterday.

**Comment by scottcwilson** [comment]
Please also be sure you have recreated your database since the addition of this feature.

**Comment by Logandros** [comment]
To reproduce:
Admin > Catalog > Featured Categories > Add by Category ID

Once I do that, I will start getting the error and it breaks my home page until I delete the featured category. I cannot be sure I did not miss something with regards to the database changes which is why I prefaced this that it may be user error. I double-checked my structure and it looks like the additions are in there but maybe I missed something. Unfortunately that's the best I can do without creating a new DB and then doing a structure compare side by side with WinMerge with my current DB. If it comes to that I will but I was hoping the log might be able to provide where I may have had a misstep.

**Comment by scottcwilson** [comment]
We'll see if anyone else can repro this.

**Comment by drbyte** [comment]
> Table 'dbs12804405.**product_types_to_category**' doesn't exist :: SELECT c.*, pt.product_type_id FROM **zencrt_categories** c LEFT JOIN **product_types_to_category** pt ON (c.categories_id = pt.category_id) WHERE categories_id = 36 LIMIT 1

My bad. PR above fixes it.

**Comment by Logandros** [comment]
Additionally, I'm not sure if where this is pulled from

`PHP Fatal error: MySQL error 1146: Table 'dbs12804405.product_types_to_category' doesn't exist`

Although my DB name is dbs12804405 my SQL structure is actually **zencrt_product_types_to_category** if that helps

![image](https://github.com/user-attachments/assets/1f344800-dc9a-40d7-b4b8-91e7e2ae12cf)

**Comment by scottcwilson** [comment]
> My bad. PR above fixes it.

LOL my eyes passed right over that. Thanks for catching.
