### ISSUE TITLE
issues with refactoring...

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#6701]
@drbyte, it is my understanding a refactor should not change functionality.  

ideally, when we move notifiers, can we try not to flip the meaning of their parameter signatures?

currently:

https://github.com/zencart/zencart/blob/5e10ca745357afc821856c7406505c3024ec7c20/includes/modules/order_total/ot_coupon.php#L1006

previously (v157)

https://github.com/zencart/zencart/blob/742b837868a2b128df96b6635c413c8187972679/includes/modules/order_total/ot_coupon.php#L344

the `$valid` and `$coupon_uses_per_user_exceeded` parms have the opposite meaning, no?

seems it was done in this commit e2408a66

**Comment by drbyte** [comment]
Fair point.

The refactoring included a massive shift in how checks for a lot of different factors was done. Checking for truthy-ness is the pattern used in all the other checks, so it made sense to do similarly in this one.
At least some code notes were left, although I don't recall whether we put anything in any upgrade documentation regarding it.

Apologies for the confusion.

**Comment by scottcwilson** [comment]
Do we want to revert the notifier arguments?  Or update documentation?

**Comment by proseLA** [comment]
for me, there is no need to revert the notifier arguments.  

as far as the documentation goes, the list of notifiers looks to only cover v158 and v200.  and they look correct.  

the change  happened between v157 and v158.

**Comment by scottcwilson** [comment]
Let me put a note in the Release Specific guidance for 1.5.8 then for people who are upgrading from an older version.  Thanks for the details.
