### ISSUE TITLE
ot_coupon question regarding accommodating `attributes_discounted`

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#6710]
i am trying to understand why we we do not allow an observer to overwrite this info:
https://github.com/zencart/zencart/blob/5ce5fe2089cc5401414b2a48dd45450b57be971f/includes/modules/order_total/ot_coupon.php#L620-L624

allow me to provide a simple situation:

- product is $200
- coupon discount is 50%
- selected added attribute cost for product is $100

in the current setup, the calculated discount would be $150.

now, is there a way that the coupon would **NOT** apply to the selected attribute cost?  ie the calculated discount is $100 instead of the $150?

i am not seeing an easy way to do this within this module.

changing this observer seems to be the easiest way to accomplish said task.  but i am curious if there are other solutions prior to making a PR.

**Comment by lat9** [comment]
I _think_ that that was the intent when `$coupon_details` was added to the notifier with [this](https://github.com/zencart/zencart/commit/e2408a66a224e5102862ee115a7632eebeab92a0) commit.

Of course, that variable's quite redundant since the next statement returns `$od_amount`.  How about simply adding `$od_amount` as the 2nd update-able parameter in the notification?

**Comment by proseLA** [comment]
i'm not real sure about that.  i do not want to have to recalculate everything.

it seems that there is something associated with attributes called `attributes_discounted`.  if that is off, a salemaker will not affect it (which is proper); but a coupon ignores that value (which seems improper).

i am not really interested in redoing the coupon class (yet again), so i am just trying to figure out where a new notifier or modifying an existing modifier is appropriate to perhaps make use of `attributes_discounted` in the coupon amount calculation.

**Comment by drbyte** [comment]
Ya, this is actually quite complex.
Currently only the shopping_cart class is aware of `attributes_discounted`, and uses it to calculate the "price" of a product in the cart.

Then `ot_coupon`'s `get_order_total()` looks for "products to which this coupon does NOT apply", and sums their prices, and subtracts those from the cart price to expose the price of the applicable discount. When doing that it uses the previously-calculated product-including-attributes prices (where `attributes_discounted` is incorporated), without any awareness of that flag. (But it's probably in here where that flag would need to be accommodated, but there's no hook for it, and I question whether these calculations should even be done here vs over in the shopping_cart via a publicly-callable method.)

Then the rest of the `calculate_deductions()` method (which fires the mentioned Notifier just before it returns), simply takes that amount-eligible-for-discount and calculates the discount based on "flat amount, vs percentage" (etc) and updates order-totals to reflect the discount.

**Comment by drbyte** [comment]
In the short-term, there's no easy accommodation for that. Like you say, you could use that notifier hook and redo many calculations, which has its maintainability downsides.

In the longer-term, centralizing the affected/related calculations into the shopping-cart, and being able to re-run those from other places with some parameters to determine which data to incorporate, would make it easier to leverage the `attributes_discounted` flag, and perhaps others.
