### ISSUE TITLE
query_factory.php:184 PHP Fatal error:  in_array(): Argument #2 ($haystack) must be of type array, int given

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6737]
(strict mode, seen after restoring a db using **my** BackupMySQL on test hosting)

https://github.com/zencart/zencart/blob/213703ec3b5238503e86c9557bfd32c96a98be94/includes/classes/db/mysql/query_factory.php#L184

Not sure whether the third parameter is necessary.

**Comment by drbyte** [comment]
Argh. My bad. Parameter order backwards.
