### ISSUE TITLE
Sync product-info templates?

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#6740]
### Discussed in https://github.com/zencart/zencart/discussions/6427

<div type='discussions-op-text'>

<sup>Originally posted by **lat9** April 28, 2024</sup>
As this feature is going into Bootstrap v3.7.0 (https://github.com/lat9/ZCA-Bootstrap-Template/pull/364), what's the feeling for combining the `tpl_{product-type-page}_display.php` files in the base Zen Cart?

Other than some base HTML `id` or `class` differences, they're all pretty much the same.  Granted, `product_music_info` is an outlier which is why I've broken out the display of a product's "details" as a separately customizable element as well as having an _optional_ additional information block.</div>

**Comment by TMCSherpa** [comment]
Most of the class and id are shared among the info_display pages so I wouldn't worry about it.

The unique id's are (mostly) not in the stylesheet 
#docGeneralDisplay #pinfo-right{background:none;} is which it shouldn't, it should be in colors wait... yup, it's in colors too. I'll add it to the list of fixes.

**Comment by lat9** [comment]
True on the class/id sharing, but I wanted to preserve the minor differences between the five different product types, just in case there's some site-specific CSS that's "hung its hat" on one of the class/id selectors.
