### ISSUE TITLE
GV Queue vs Guest Checkout

### ISSUE THREAD

**Issue by ajeh** [zencart/zencart#675]
Setting: Upgrade from v155 to v160 with v155 configure.php files
- [x] Guest Settings does not show makes Group 31 in configuration_group but added as Group 26 in configuration
  Tried to change configuration_group to 26 and still does not show
  Guest Checkout using:
  define('BOX_CONFIGURATION_CHECKOUT_SETTINGS', 'Checkout Settings'); //for 1.6.0
  Upgrade sql uses:
  define('BOX_CONFIGURATION_GUEST', 'Guest Checkout');
- [ ] Guest checkout orders a Gift Certificate
- How do they apply it to the order?
- How do they check the GV Balance?
- How do they send it to someone else?
- [x] Terms and Conditions are at Top and Bottom of  step=payment
- [x] My Account shows on Guest Checkout

**Comment by drbyte** [comment]
The first one (group 26) appears to be fixed. `Checkout Settings` appears on the menu, with relevant Guest Checkout options (and more) contained therein)

**Comment by drbyte** [comment]
> T&C at top and bottom of payment

This should now be fixed by commit: https://github.com/zencart/zencart/commit/c643286935b1fdeb2b29933c9afd350e71d6cf15

**Comment by drbyte** [comment]
> My Account shows on Guest Checkout

This appears to be resolved now.

**Comment by drbyte** [comment]
> Guest checkout orders a Gift Certificate

At this particular moment, the GV queue will release it, but no code is issued, and nothing sent. It's orphaned.
Obviously that needs fixing ;)

**Comment by drbyte** [comment]
@DivaVocals @lat9 can you comment on how COWOA chose to handle queuing of GVs purchased by guests without an account?
