### ISSUE TITLE
admin customer edit of address does not work

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#6757]
i am editing a customer address in the admin area.  i am changing a customer address from US to Canada.  both of these countries have state/province pulldowns.  

when clicking update, the country gets moved to afganistan (1st entry) and zc generates no error logs.

**Comment by lat9** [comment]
Related to #6754

**Comment by piloujp** [comment]
If you comment line 270 that reset `$entry_state`, you can then change state. But it has to be done in 2 steps, changing country and saving, then edit again and changing state. This is due to #6754 .
I could not find why `$entry_state` is reset like that...
