### ISSUE TITLE
System Inspection: missing $ in string replacements

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6777]
https://github.com/zencart/zencart/blob/dd38315e34384fbea7711a796975e11d6125f626/zc_plugins/System%20Inspection/1.5.0/admin/includes/languages/english/lang.system_inspection.php#L36-L37

All the examples of simple text replacement 
https://www.php.net/manual/en/function.sprintf.php
seem to use the $, however it does work in this instance.
There are other examples of formatting that do not use the $, and I'll admit to not figuring out the relevance..

**Comment by drbyte** [comment]
You are correct. The `$` should be included. 🤦‍♂️
