### ISSUE TITLE
zc_install database errors

### ISSUE THREAD

**Issue by TMCSherpa** [zencart/zencart#6786]
I haven't done a fresh test install since Aug 7th but sometime between now and then part of the installer stopped using a prefix

 These are from mysql_zencart.sql
Line 2497
[28-Sep-2024 21:48:49 UTC] MySQL error 1146 encountered during zc_install:
Table 'stockzen.configuration' doesn't exist
UPDATE configuration SET configuration_title = 'Customer <em>Place Order</em>: Single Admin ID', configuration_description = 'Identify the ID number of an admin that is permitted to use the <em>Place Order</em> feature on the customers list, regardless of their assigned admin-profile. Set the value to 0 to disable the <em>Single Admin ID</em> feature.' WHERE configuration_key = 'EMP_LOGIN_ADMIN_ID' LIMIT 1;
---------------

Line 2500
[28-Sep-2024 21:48:49 UTC] MySQL error 1146 encountered during zc_install:
Table 'stockzen.configuration' doesn't exist
UPDATE configuration SET configuration_title = 'Customer <em>Place Order</em>: Passwordless Login', configuration_description = 'Login directly to store without entering credentials' WHERE configuration_key = 'EMP_LOGIN_AUTOMATIC' LIMIT 1;
---------------

Line 2503
[28-Sep-2024 21:48:49 UTC] MySQL error 1146 encountered during zc_install:
Table 'stockzen.configuration' doesn't exist
UPDATE configuration SET configuration_title = 'Customer <em>Place Order</em>: Admin Profiles', configuration_description = 'Identify the admin <em>User Profile IDs</em> that are permitted to use the <em>Place Order</em> feature on the customers list &mdash; all admins that are in these profiles are permitted. Enter the value as a comma-separated list (intervening blanks are OK) of Admin Profile IDs, e.g. <b>1, 2, 3</b>. Set the value to 0 to disable the <em>Admin Profiles</em> feature.<br><br><b>Default: 0 </b>' WHERE configuration_key = 'EMP_LOGIN_ADMIN_PROFILE_ID' LIMIT 1;
---------------

Line 2845
[28-Sep-2024 21:48:50 UTC] MySQL error 1146 encountered during zc_install:
Table 'stockzen.configuration' doesn't exist
UPDATE configuration SET configuration_value='true' WHERE configuration_key='DOWNLOAD_ENABLED';
---------------

These are from mysql_demo.sql
Line 429
[28-Sep-2024 21:48:51 UTC] MySQL error 1146 encountered during zc_install:
Table 'stockzen.products' doesn't exist
UPDATE products SET products_date_added = NOW() WHERE products_id = 168 or products_id = 169 or products_id = 170;
---------------

Line 430
[28-Sep-2024 21:48:51 UTC] MySQL error 1146 encountered during zc_install:
Table 'stockzen.products' doesn't exist
UPDATE products SET products_date_added = NOW() - INTERVAL 7 DAY WHERE products_id = 171 or products_id = 172 or products_id = 166 or products_id = 133;
---------------

Line 431
[28-Sep-2024 21:48:51 UTC] MySQL error 1146 encountered during zc_install:
Table 'stockzen.products' doesn't exist
UPDATE products SET products_date_added = NOW() - INTERVAL 20 DAY WHERE products_id = 126 or products_id = 47 or products_id = 34;
---------------

Line 432
[28-Sep-2024 21:48:51 UTC] MySQL error 1146 encountered during zc_install:
Table 'stockzen.products' doesn't exist
UPDATE products SET products_date_added = NOW() - INTERVAL 50 DAY WHERE products_id = 134 or products_id = 131 or products_id = 160;
---------------

Line 433
[28-Sep-2024 21:48:51 UTC] MySQL error 1146 encountered during zc_install:
Table 'stockzen.products' doesn't exist
UPDATE products SET products_date_added = NOW() - INTERVAL 70 DAY WHERE products_id = 57 or products_id = 174;
---------------

Line 434
[28-Sep-2024 21:48:51 UTC] MySQL error 1146 encountered during zc_install:
Table 'stockzen.products' doesn't exist
UPDATE products SET products_date_added = NOW() - INTERVAL 100 DAY WHERE products_id = 6 or products_id = 19;
---------------

Line 437
[28-Sep-2024 21:48:51 UTC] MySQL error 1146 encountered during zc_install:
Table 'stockzen.products' doesn't exist
UPDATE products SET products_date_available = NOW() + INTERVAL 12 DAY WHERE products_id = 16;
---------------

Line 438
[28-Sep-2024 21:48:51 UTC] MySQL error 1146 encountered during zc_install:
Table 'stockzen.products' doesn't exist
UPDATE products SET products_date_available = NOW() + INTERVAL 17 DAY WHERE products_id = 174;
---------------

Line 439
[28-Sep-2024 21:48:51 UTC] MySQL error 1146 encountered during zc_install:
Table 'stockzen.products' doesn't exist
UPDATE products SET products_date_available = NOW() + INTERVAL 27 DAY WHERE products_id = 40;
---------------

Line 440
[28-Sep-2024 21:48:51 UTC] MySQL error 1146 encountered during zc_install:
Table 'stockzen.products' doesn't exist
UPDATE products SET products_date_available = NOW() + INTERVAL 33 DAY WHERE products_id = 34;
---------------

**Comment by TMCSherpa** [comment]
Dunno why it's 18pt bold but it doesn't want to be fixed.

**Comment by drbyte** [comment]
> Dunno why it's 18pt bold but it doesn't want to be fixed.

That's just [Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) converting the `---------------` and treating it as "an underline for a heading".

**Comment by drbyte** [comment]
zc_install reads the `DB_PREFIX` from your `/includes/configure.php` file, and shows it to you in the db setup screen, and allows you to override it by editing it before clicking submit.

**Comment by TMCSherpa** [comment]
I reinstalled the version from Saturday which generated the same errors on install so I tried the version I had from August which also didn't have any install errors.
The latest version from this morning (which only looks like versioning changes) also doesn't generate an error.
I don't know if there was something that changed in the last two days (code base or my laptop) but it appears to be working now and I'm not going to jinks it

**Comment by drbyte** [comment]
You were right. There was a DB_PREFIX bug on UPDATE statements, which prevented a bunch of statements from running properly, resulting in mismatched non-prefixed statements running.
