### ISSUE TITLE
Plugin Manager: extra info

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6798]
Since this page is the admin user's source of all things Plugin-related, perhaps the following information would be useful to include.

1) Link to plugin download page.
1) Link to plugin forum help thread.
1) Include a date with the installed version number (for comparison to the GitHub).
1) Link to GitHub repository including date of last PR (apparently possible).

Since the table creation code is still above my page grade, I'll have to pass on this one.

**Comment by drbyte** [comment]
If a plugin update is available, a link is already provided, and indicates the new version number.

All the other information is accessible from the plugin's download page. So, the PR simply adds a link if the plugin ID is provided and an upgrade is not detectable.
