### ISSUE TITLE
zen_get_categories_products_list(): $categories_id type mismatch

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6814]
https://github.com/zencart/zencart/blob/c6a5c4c5978d19b7a7e6b562c5764c9313d4b40a/includes/functions/functions_categories.php#L505-L525

defined as int but used as strings on last line

**Comment by drbyte** [comment]
Functionally, the code in that function never enforces it to be an integer. Most calls to the function pass a `cPath` string, although when it recursively calls itself it passes a numeric value.

Simplest fix is probably:
```diff
function zen_get_categories_products_list($categories_id, $include_deactivated = false, $include_child = true, $parent_category = TOPMOST_CATEGORY_PARENT_ID, $display_limit = '')
{
    global $db;
    global $categories_products_id_list;
+    $categories_id = (string)$categories_id;
```

**Comment by torvista** [comment]
Many of the primary parameters in the functions in this file are defined in the docblocs as int, when perhaps in fact many may be string or integer.
I assumed the docbloc should be the guide but perhaps each function call and their usage needs individual review to ascertain the most appropriate definition and subsequent "correction" in the usages.

Perhaps natural numbers should always be passed to functions as integers/be expected to be integers?
