### ISSUE TITLE
Table zones' field zone_name too short

### ISSUE THREAD

**Issue by piloujp** [zencart/zencart#6839]
Some countries have zones names too long to fit in actual field `zone_name` (varchar(32)) in table zones.

I had this problem with the French zone "Terres australes et antarctiques françaises". Although the probability this one is used for online shopping is very very low, I can imagine some countries somewhere might have zones names too long to fit.
Even in the States, zone "Federated States Of Micronesia" is close to the limit of 32 characters.

As a new release is coming, I think it would be a good opportunity to increase this field length and being a little bit more future-proof.

**Comment by drbyte** [comment]
Is `varchar(64)` sufficient?

**Comment by lat9** [comment]
Why not go for the gusto and increase to varchar(128)?  There's no additional overhead, right?

Note, too, that any change in the field size here should also be carried over to the orders table's customers_, billing_ and delivery_state fields' definitions.

**Comment by drbyte** [comment]
Changes also affect the UI because it sets field length based on db field size.

**Comment by piloujp** [comment]
Doing a Google search on longest city/places names in the world, I realized that city and street address/suburb fields might need to be in creased too...
[https://en.wikipedia.org/wiki/List_of_long_place_names](https://en.wikipedia.org/wiki/List_of_long_place_names)
[https://worldpopulationreview.com/world-city-rankings/longest-city-names](https://worldpopulationreview.com/world-city-rankings/longest-city-names)

Most of these places will fit in a 64 characters field. Few very long ones in MAUI or Welsh language will need 128 and only Bangkok's ceremonial name (which not use for address anyway) would need more.

Looking at actual order table, most of the address fields are already at 64, only state, city and suburb are 32.
At minimum, I would increase these 3 fields to 64 and if there are no side effects, why not 128.

I tried to increase these fields to 128 on a test cart and could not see any visual change on login page and admin customer edit page. Even when reducing the browser window to its minimum possible width (which did not change with these settings), all fields are always at the same size. What changed was the number of characters you can write in the field. With 128, on a small window, you have to scroll horizontally in the field itself to view everything.

**Comment by drbyte** [comment]
I support the change to 128 for those fields.

**Comment by lat9** [comment]
Field-length extensions will also affect the `address_book` table.

**Comment by piloujp** [comment]
> Field-length extensions will also affect the `address_book` table.

3 tables actually:
`address_book`
`orders`
`zones`

I can make a PR if you want.

**Comment by drbyte** [comment]
> I can make a PR if you want.

Yes please.

**Comment by drbyte** [comment]
> Why not go for the gusto and increase to varchar(128)? There's no additional overhead, right?

I'd forgotten that there is some overhead if the fields are indexed, because indexes are fixed-length even for varchar types.

But, fortunately in this case, none of these affected fields have indexes.
