### ISSUE TITLE
problem with gv_balance

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#6881]
this line here could result in a `$gv_balance` of `null`:
https://github.com/zencart/zencart/blob/8e7560c917f0d6bb2e40a53f514d1fb5ea447b18/includes/modules/pages/checkout_payment/header_php.php#L123

when it is then used here:

https://github.com/zencart/zencart/blob/8e7560c917f0d6bb2e40a53f514d1fb5ea447b18/includes/templates/template_default/templates/tpl_checkout_payment_default.php#L206

you end up with something like:

`onclick="submitFunction(,530.4895)"`

which throws an error on the DevTools Console.

easy fix:

```php
$gv_balance = $customer->getData('gv_balance') ?? 0;
```

**Comment by scottcwilson** [comment]
Documentation: This issue appears to have been present as far back as 2.0.0.
