### ISSUE TITLE
Save order's language in the database

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#832]
@lat9

> For multi-lingual stores, it would "be nice" if the language used during an order's checkout was captured in the database as part of the order processing. This would be an aid in follow-on communications with the customer and in the re-construction of the order information. 

quoted from:
[https://www.zen-cart.com/showthread.php?219536-Save-order-s-language-in-the-database&p=1303961#post1303961](url)

This would be the starting point to discus what is needed to accomplish to set the language, where it is being used, viewed, and/or edited

**Comment by Zen4All** [comment]
I think not only the order language should be set, but also the preferred language a customer wants to use for his/her account.

The language should then probably be set in:

- the orders table for order language
- customers or customers_info table for preferred communications language, and maybe default site language

This could be done at account creation and order creation.

From the back end:
- the administrator should be able to see the preferred language in the customers page, and be able to edit the value.
- orders could/should be displayed in the customers language
- invoice and packing should be displayed in the customers language
- the automatic emails after status updates etc, should be in the customers language.

Some thoughts as a strart

**Comment by drbyte** [comment]
I went thru the same thinking process when considering this for 2.0 ... and it actually gets to be monstrous.

So, as far as code implementation, take it in baby-steps.  Small feature steps will be easier to manage.

**Comment by Zen4All** [comment]
first steps are being taken here: [https://github.com/Zen4All/zc-v1-series/tree/v160-Save-order-language](url)
The language used during checkout is being saved with the order in the orders table

**Comment by torvista** [comment]
My opinion.
The only place this really matters (in vanilla zc) is in the sending of emails from an order update.
Orders page: I show the country of the order in the listing and add a UK flag next to the country name if the order was in english as 99% of our orders are in spanish.

More usefully I use a modified info box to send the emails from the listing page and that has a flashing flag next to the "send Email" box if the admin language is not the same as the order language as a warning. 
![admin_orders_email_flag](https://cloud.githubusercontent.com/assets/4391026/13807654/7b410e0a-eb62-11e5-8d09-f595c83150d6.gif)

Same idea in the order details page.
![admin_orders_email_flag_order](https://cloud.githubusercontent.com/assets/4391026/13807692/bcf36532-eb62-11e5-8bb9-dc75c164d77c.gif)

That has proved sufficient and I think worthy of consideration until the whole issue is fixed.

Other areas where I need to record the browser language is for use with Back in Stock notifications and Abandoned Cart reminders but I had to move the email language defines out of being auto-loaded to ensure the correct ones get used when sending multiple emails at once.

**Comment by Zen4All** [comment]
@torvista If you send me a copy of your code by email. It looks like a workable solution to me, and I am willing to look at it and maybe use it in the new code.

**Comment by torvista** [comment]
ok

**Comment by Zen4All** [comment]
:thumbsup:

**Comment by scottcwilson** [comment]
:thumbsup:  Nice to support multi-lingual stores.

**Comment by Zen4All** [comment]
Update: Order language is captured in orders table, and order update emails are being send to the customer in the language the order was made in.

**Comment by drbyte** [comment]
Yesterday's updates to the order class may affect your work on this. Particularly because the `admin` order class is now gone, and shares with the main `includes/classes/order.php`

**Comment by Zen4All** [comment]
Thanks for the heads up, I'll take a look at it tomorrow.

**Comment by drbyte** [comment]
As for the customer's language preference, I'm inclined to think it's best to store the language 'code' (ie: `en`, `nl`, etc).

In retrospect, perhaps it's best that the order gets the `code` stored too.

Thinking here of idempotency and specificity. What happens if languages get added/deleted multiple times during the lifecycle of the site? There's no need to maintain old language preferences if they're stored as the 2-letter `code`, but if they're just the autoincrementing int value then any time a change is made that value needs to be updated, and if a language gets deleted then the stored "preference" (or order history) is orphaned from any real language values, and can never be auto-reconnected accurately.

**Comment by Zen4All** [comment]
Good point. I will give it a go. I also seem to recall a discussion where you were preferring the 3 letter iso code, over the 2 letter code. Although I can not find that thread at the moment.
