### ISSUE TITLE
Default Case for Switch in customers.php is Never Executed

### ISSUE THREAD

**Issue by jefflew** [zencart/zencart#936]
In `admin/customers.php` if you look at line 22 there is a null condition check on `$action`.  But then within the switch for `$action` there is a `default` case.  This never runs because when the `$action` variable has a value of `''`, it returns false.

It seems that maybe `$cInfo` must be populated somewhere outside of this file which is why the bug was never found?

Removing the null condition seems to correct the issue and then `$cInfo` is set by the default when previewing a customer.

**Comment by drbyte** [comment]
Thanks for reporting this. 

It's possible that this was never found previously because older versions of PHP were less strict about expected properties in an object such as `objectInfo` from which `$cInfo` is derived.

I agree with your fix suggestion. Will need to do some regression testing to check for any undesired side-effects that might also need fixing.

**Comment by jefflew** [comment]
Great, thanks Chris.  Keep up the good work over there!

On Fri, May 20, 2016 at 6:57 PM, Chris Brown <notifications@github.com>
wrote:

> Thanks for reporting this.
>
> It's possible that this was never found previously because older versions
> of PHP were less strict about expected properties in an object such as
> objectInfo from which $cInfo is derived.
>
> I agree with your fix suggestion. Will need to do some regression testing
> to check for any undesired side-effects that might also need fixing.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/zencart/zc-v1-series/issues/936#issuecomment-220752592>
>



-- 

*Jeff Lew*
President

*Phone:* 1-855-686-4649 Ext 700
*Email/Gchat:* jlew@numinix.com
*Skype:* numinix
[image: Numinix] <http://www.numinix.com/>

[image: Facebook] <http://www.facebook.com/numinix> [image: Twitter]
<http://twitter.com/numinix> [image: Google+]
<https://plus.google.com/+Numinix> [image: Instagram]
<http://instagram.com/numinixwebdev> [image: Pinterest]
<http://www.pinterest.com/numinix> [image: Blog]
<http://www.numinix.com/blog/?feed=rss2>

**Comment by jefflew** [comment]
Some more info.  If you get rid of the null check on the action variable, then it will fail to get all of the customer info later on which depends on $cInfo not being set. So if that's intended then just getting rid of the default would reduce confusion.  However, it might be better to just move the second block of code up into the default section. I'm sure you guys can figure out a way to clean up this code. Thanks again.

**Comment by jefflew** [comment]
The reason why this happens is because when the default runs, it sets $cInfo and then another block of code (line 1153 in 1.5.5a) that only runs when $cInfo is not set does not execute leaving out all of the customers_info.

One solution is to add an OR condition that $action is null and then give $action a value so that the code only runs once for the first customer. 

Another is to remove the !isset($cInfo) condition and add in a counter so this block of code only runs on the first loop of the while statement.

**Comment by scottcwilson** [comment]
This premise of this ticket is incorrect.  It is not correct to say that "default" is a synonym for "switch checked variable has no value."  Default simply means the current value does not have a corresponding case.  The default case does indeed run, for example for case 'isconfirm'.

**Comment by drbyte** [comment]
@jefflew Can you explain what the original "problem"/symptoms were that led you to report this issue?

Let's work at tackling the underlying problem ... but to do that means we need to know the original symptoms.

**Comment by jefflew** [comment]
I don't recall the original issue completely.  We were trying to show some new data in the customer preview.
