### ISSUE TITLE
functions_email $moreinfo formatting

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#941]
Code at: https://github.com/zencart/zencart/blob/v160/includes/functions/functions_email.php#L647
```php
    foreach($moreinfo as $key => $val) {
      $extra_info['TEXT'] .= $key . ": \t" . $val . "\n";
      $extra_info['HTML'] .= '<tr><td class="extra-info-bold">' . $key . '</td><td>' . $val . '</td></tr>';
    }
```

1) the colon before the tab in $extra_info['TEXT'] .= $key . ": \t" . $val . "\n"; is superflous if the key is formatted as per the others in this list.
2) if the $key is too brief/an abbreviation, it needs two tabs to line up with the rest of the column in text emails.

Suggest:
```php
foreach($moreinfo as $key => $val) {
      $extra_info['TEXT'] .= $key . (mb_strlen(strip_tags($key))<8 ? "\t\t" : "\t") . $val . "\n";
      $extra_info['HTML'] .= '<tr><td class="extra-info-bold">' . $key . '</td><td>' . $val . '</td></tr>';
    }
```

**Comment by drbyte** [comment]
I'd be willing to entertain a PR for this ... but since `mb_strlen()` isn't compiled into PHP by default, please use `strlen()`.

**Comment by shrz** [comment]
@drbyte I can't find email_collect_extra_info() usage where $moreinfo parameter is set.

**Comment by drbyte** [comment]
The $moreinfo parameter isn't set in original core code. It exists so that plugins can use it.

The default `email_collect_extra_info()` call is at https://github.com/zencart/zencart/blob/v160/includes/classes/order.php#L1270
