### ISSUE TITLE
Create a post-server-move mode for zc_install to detect config file changes

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#947]
@lhungil suggested in #184 ...

>  I would also suggest adding a "post server move" mode to the installer (run on new server after copying database / files, ask for new database details, re-detect physical locations, validate superadmin, write new config file, update settings in DB, handle permissions, etc).
> 
> Changing the installer should help reduce the "pain" encountered when users install, upgrade, or move servers (and hopefully reduce the number of support threads on this topic).

**Comment by drbyte** [comment]
Perhaps a better solution might even be to make it all dynamically-detected so that no -hard-coded paths are needed at all.

**Comment by mc12345678** [comment]
Dynamically from the sense that the software (ZC package) when placed on the server realizes that things are not right and automatically addresses/corrects like the admin directory currently does? or dynamically from the zc_install process to do that?

**Comment by drbyte** [comment]
I suppose maybe this is becoming more and more moot ... considering that the only paths now in configure.php are:

- `DIR_FS_CATALOG` -- which is the only "complete" hard-coded path
- `DIR_WS_CATALOG` -- which only requires edits when the subdirectory name is changed
- `DIR_WS_HTTPS_CATALOG` -- which only requires edits when the subdirectory name is changed for SSL

What's important to consider if we change DIR_FS_CATALOG to be auto-detected is that the Admin also uses this file directly, and since it runs from a subdirectory that means auto-detection here could be more complicated.
