### ISSUE TITLE
backtrace on PHP 5.4 does not exclude E_NOTICE, E_STRICT, E_DEPRECATED 

### ISSUE THREAD

**Issue by khe817** [zencart/zencart#948]
**Issue**: backtrace logs all errors while it shouldn't (Tested with PHP 5.4.41). It works fine for PHP 5.3.29, and 5.6.21 though. Not sure why PHP 5.4 would do that.

**My fix**: in includes/extra_configures/enable_error_logging.php
Add this line:
`if ($errno == E_NOTICE || $errno == E_STRICT || $errno == E_DEPRECATED) return false;`

After:
```
function zen_debug_error_handler ($errno, $errstr, $errfile, $errline) {
  if (!(error_reporting() && $errno)) {
    return;
  }

```

**Comment by drbyte** [comment]
I am not able to replicate this.

**Comment by khe817** [comment]
This happened to one of our clients and only happens with PHP 5.4.41. I have tested with other PHP versions too and could not reproduce the issue. 

I think adding a check there for safeguard does hurt. Or not, since zen cart 1.5.5 says it support PHP 5.5 and above.

**Comment by drbyte** [comment]
Question: Does the proposed fix posted here resolve this issue for you? ->  #1092
