### ISSUE TITLE
Files run through Admin->Tools->Install SQL Patches should ignore additional whitespace

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#951]
Right now, running a file with the statement 

UPDATE products ADD ADD price_w decimal(15,4) NOT NULL default '0.0000';

succeeds, but if you have two spaces after the UPDATE 

UPDATE  products ADD ADD price_w decimal(15,4) NOT NULL default '0.0000';

it fails.

**Comment by drbyte** [comment]
While I understand the point, and agree in part, I'm going to strongly suggest that the SQL in that plugin be fixed, instead.

**Comment by scottcwilson** [comment]
I don't think the SQL is broken though - it just has two spaces instead of one.  PHPMyAdmin wouldn't complain, and you could use it as an argument in $db->Execute().   What's broken is the parser in sqlpatch.  My concern is that this bug in the parser leads to weird superstitious beliefs that "Admin->Tools->Install SQL Patches doesn't always work ..." which I see in mod readme's not infrequently.  

This is a pretty straightforward fix if you'd like me to do it.

**Comment by drbyte** [comment]
Were you envisioning fixing it only for the "update" statements? Because there's like 20 other kinds of SQL statements that would need to be dealt with, with multiple variations of each depending on "ignore" and other factors.
It's actually a humungous re-factoring of the code to accommodate that. 
And then the same in zc_install.

**Comment by drbyte** [comment]
That said, I invite you to look into the code to see what I'm talking about. I'm open to more discussion; just mindful that I think it's a pretty big topic. 
Refactoring to be more efficient is okay, but should be done with unit tests included so future changes can be tested safely and quickly too.

**Comment by scottcwilson** [comment]
I was thinking we could just do a trim on the string after the verb was
parsed out - that might fix it (not sure).

**Comment by scottcwilson** [comment]
My fix is pretty small - I will submit it tomorrow after a bit more testing.

**Comment by scottcwilson** [comment]
Oops I didn't link the fix to this issue.  It's https://github.com/zencart/zencart/pull/969
