### ISSUE TITLE
Add support for "tags" to products, categories, ez-pages

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#954]
Tagging (if the storeowner uses it) allows customers to find "related" products/categories/pages/articles similar to something else they're already viewing.

Implementing this requires numerous components, including (but not limited to):
- [ ] database table of tags, and admin page to manage them
- [ ] database pivot tables to link tags to products, tags to categories, tags to pages
- [ ] admin page changes to allow selecting tags from within product/category/page screens
- [ ] storefront code changes to allow filtering by tags
- [ ] complete rewrite of product-listing pages to allow them to display something "other than products" amongst search results
- [ ] add tag filter to advanced-search criteria page
- [ ] index_filters will be affected

Given that this changes a lot of files that drive other pre-existing functionality, unit tests should be included to help ensure that this feature doesn't break when other components are updated.

**Comment by Zen4All** [comment]
I like this idea/feature, and am willing to dedicate my time to it.

**Comment by AndrewBerezin** [comment]
Products tagging  is a very useful tool! I use it for seo, for Low-frequency queries.

**Comment by Zen4All** [comment]
Maybe using the wordpress table structure as an example is an idea?

**Comment by AndrewBerezin** [comment]
If you're interested, I could offer my own version of the Products tags.

**Comment by Zen4All** [comment]
Off course I am ;)

**Comment by drbyte** [comment]
Thanks @Zen4All  and @AndrewBerezin !

**Comment by drbyte** [comment]
Something to note: A number of Admin pages in v160 are being revamped to use the new LEAD-Pages format ... which basically makes those pages more OOP and makes querying the db a lot simpler.

You can start with building out this feature in a way that uses the old Admin page structure, and later convert it over to the new format. 

I suggest doing the conversion as a second phase. If you're not already familiar with what's being done with the new admin infrastructure, don't let that hold you back from building the feature/components above. (Granted, if you do already grok the new stuff, then it'll be a lot easier to write those pages.)
But, please don't get hung up on that for now.  You're inspired to build the feature, so do that while your creativity is flowing ;)  We can collaboratively refactor it later ;)

**Comment by Zen4All** [comment]
I'll start with the old pages, this way it can also easily be adopted in older versions of Zen Cart as a separate module.

**Comment by drbyte** [comment]
The `select2` javascript used in `LEAD` pages has a nice presentation for tag selection in the UI.

**Comment by drbyte** [comment]
@Zen4All I forgot to mention initially that the index_filters will need enhancements to support this too. (You probably already know this, but I was reminded of it while looking at the checkboxes above)

**Comment by Zen4All** [comment]
Thanks for the heads up. I am using the checkboxes as a guide ;) . I also must admit this feature has been on a low priority lately.

**Comment by lat9** [comment]
I've got an implementation that I'd be willing to "share".  I need to package it up on GitHub; I'll post back when it's available.

Note that there will be some testing required ... it's been developed for 1.5.5f.

**Comment by lat9** [comment]
FWIW, I've just published (https://github.com/lat9/ZenTags/releases/tag/v1.0.0-beta1) my initial beta version.  Please note that the code has been marginally tested &mdash; that's why it's still, in my mind, a beta version.
