### ISSUE TITLE
Add ability to inject promos into category/product listings

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#955]
If tastefully done, cross-promotion of related items or time-sensitive in-store promos can be very beneficial.  (but, oh, please don't use it to force off-site ads onto shoppers!)

Basic criteria:
- [ ] establish criteria for "where" the injected row/cell is to appear (4th row, or 20th product, etc)
- [ ] decide on a system for managing the promo content (ideally a dedicated banner-group would suit best, since this allows leveraging the existing infrastructure instead of writing completely new promo modules)
- [ ] rewrite product-listing to allow injection of the promo cells/rows

Probably more things needed than listed here.

**Comment by scottcwilson** [comment]
Why don't we just add a notifier and let some contributor do this?  Seems like this is feature creep for an initial 1.6.0 release.

**Comment by drbyte** [comment]
Well that's why it's flagged as up-for-grabs, and not part of the v160 milestone tracking.


But there's more to this than adding a notifier. It's a rewrite of how product listings are done.

The up-side to the rewrite of product listings is it could lend itself to displaying more than just products.  For example, the search-results have always used the product-listing infrastructure for displaying results, which means search-results could always only return products, not categories or ez-pages.
Done correctly the reworking to allow promotions could also be adapted to allow for "other-than-product" search results too.
