### ISSUE TITLE
catalog $language_list array pointer not reset so content does not display in languages sidebox

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#971]
In html_header.php:
`while (list($key, $value) = each($language_list)) {
      if ($value['id'] == $_SESSION['languages_id']) continue;
      echo '<link rel="alternate" href="' . ($this_is_home_page ? zen_href_link(FILENAME_DEFAULT, 'language=' . $key, $request_type) : $canonicalLink . '&amp;language=' . $key) . '" hreflang="' . $key . '" />' . "\n";
    }`

This leaves the array pointer at the end so when this array is next used in the languages sidebox, no icons/content is displayed since the while loop is never executed.
tpl_languages.php:

`  while (list($key, $value) = each($language_list)) {
    $content .= '<a href="' . zen_href_link($current_page_base, zen_get_all_get_params(array('language', 'currency')) . 'language=' . $value['code'], $request_type) . '">' . zen_image(DIR_WS_LANGUAGES .  $value['directory'] . '/images/' . $value['image'], $value['name']) . '</a>&nbsp;&nbsp;';
    $lng_cnt ++;
    if ($lng_cnt >= MAX_LANGUAGE_FLAGS_COLUMNS) {
      $lng_cnt = 0;
      $content .= '<br />';
    }
  }`
![clipboard01](https://cloud.githubusercontent.com/assets/4391026/15806590/6116f106-2b46-11e6-979e-f10196bb086f.gif)

Suggest `reset($language_list);` is added to the end of the html_header loop.

**Comment by drbyte** [comment]
Mind testing an idea?

Instead of adding a reset, I think the use of a `foreach` instead of a `while(each)` is better:

```php
  while (list($key, $value) = each($language_list)) {
```
becomes:
```php
  foreach($language_list as $key=>$value) {
```

**Comment by torvista** [comment]
It works when in tpl_languages only. I replaced both anyhow.

**Comment by drbyte** [comment]
Ya, it requires some alternate rewriting in html_header: https://github.com/zencart/zencart/issues/975
