### ISSUE TITLE
LEAD pages not deleting database fields from associated tables

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#974]
On the legacy language page, when deleting a language, all the related language fields in products, and categories etc, were deleted from the database.
Now with the new LEAD page, it seems the language related field are not deleted any more. Was this a deliberate choice? Or has that part of the code not yet been implemented. (asking, because I was looking where to implement my code for deleting country name related fields #374).

**Comment by drbyte** [comment]
I think it was missed, but will have to double-check

**Comment by zcwilt** [comment]
Hmmm. Now I can't remember why I left out the delete. 
However I'm not sure It's relevant to your code.

In general for language bound tables, automated code should take care of deleting.
If that's not the case I will have to do some debugging :)

**Comment by Zen4All** [comment]
@zcwilt  my code is working fine, only when you want to delete a language from the store, the appropriate language related fields in the database are not cleared. So I am going to make a pull request for my part .

**Comment by zcwilt** [comment]
DOH. I'd misunderstood.

**Comment by zcwilt** [comment]
So I'm still deciding on how best to address this.

If you look at https://github.com/zencart/zencart/blob/v160/includes/library/zencart/Services/src/LeadLanguagesRoutes.php

There is a `postProcessInsert` method that builds a table list and updated the language fields for those tables. 

We could re-use that table list for the delete processing. 

The problem then is, how do we support plugins. The traditional method would be to supply a notifier and force the plugin/contribution author to write an observer class to manage the insert/delete of their language bound tables. 

I'm not convinced this is the correct approach.

**Comment by drbyte** [comment]
@Zen4All in the comments to this discussion you mentioned making a pull request. Was that for one you've now done, or is there still one pending as it relates to this issue ticket?

**Comment by Zen4All** [comment]
I do not have the code at hand right now, but I think I was referring to the countries name code. But no fields were cleans from my part. As I was missing the code for all the clean-up

**Comment by drbyte** [comment]
The `record_company` "delete" action isn't deleting related records from `record_company_info` either. I think the same exists with record_artists/info.

**Comment by zcwilt** [comment]
@drbyte The deletion of record artist stuff etc is a seperate prob 
see https://github.com/zencart/zencart/pull/1095
