### ISSUE TITLE
Updated admin - prefer older hover behavior

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#988]
I like the appearance of the new admin, but I miss the older hover behavior. 

I liked that in the older admin the subordinate actions under the top level items (Tools, Reports, etc.) would show without needing to click.

**Comment by zcwilt** [comment]
I agree. However I chose not to implement the hover at the moment as there is a bug in the code used in v155

You can see the bug by clicking on the `header` entry for a menu. e.g. click on the `extras` 
This will display the extras menu. Now hover over any other menu.
The `extras` menu will still be displayed, along with the other hover menu. 

I wanted to fix this (minor) issue before reintroducing the hover

**Comment by zcwilt** [comment]
btw. will leave this issue open, to remind me I do have to fix the behaviour :)

**Comment by scottcwilson** [comment]
Cool thanks for the update.
