### ISSUE TITLE
Mobile users cannot enter anything but numbers in postcode field

### ISSUE THREAD

**Issue by siliconforks** [zencart/zencart#993]
To reproduce:

1. Run Zen Cart 1.5.5 with the new "responsive_classic" template.
2. Using a mobile browser, visit the store login page (i.e., index.php?main_page=login).
3. In the form for creating a new account, in the "Post/Zip Code" field, try to enter a postcode which contains characters other than numbers (letters, spaces, hyphens, etc.).  The input field is actually an `<input type="number">` field which does not allow this.

This is a problem because in most countries, postal codes contain letters and other non-numeric characters.

**Comment by drbyte** [comment]
Ya, the default got released in an Americanized wY. 

You can fix that in /includes/templates/responsive_classic/jscript/jscript_responsive_framework.php

**Comment by drbyte** [comment]
Specifically: comment-out or remove this line:

```js
$('input#postcode').clone().attr('type','number').insertAfter('input#postcode').prev().remove();
```
